### ISSUE TITLE
迁移手册中提到不再提供basePath，为什么官方demo中还在使用呢？

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#1]
1、迁移手册中提到新的图片引用方法，但是demo中还在使用旧的引用方法，表示是可以兼容旧的引用方法么？
2、MHPluginSDK中有哪些特性被遗弃，又有哪些新加的特性呢？

**Comment by laohuang88** [comment]
已经全部清除
