### ISSUE TITLE
iOS 蓝牙模块 BluetoothEvent.bluetoothCharacteristicValueChanged取值问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#100]
#### 环境
- 电脑操作系统: mac
- 手机系统: ios 12
- 相关模块: Bluetooth
- API或者常量: [readFile/isDebug]

#### 现象

在BluetoothEvent.bluetoothCharacteristicValueChanged.addListener打log：console.log("bluetoothCharacteristicValueChanged", character.UUID, value);
打印的结果为：bluetoothCharacteristicValueChanged AA02 00ff00004616000000011701
但是，旧框架取到的value是：AP8AAEYWAAAAARcB，然后通过base64.decode(value)解析。
这是我弄错了还是value的编码变了呢？

**Comment by edwardair** [comment]
说下我的插件情况：旧版本需要base转码，目前新版本，我直接使用原始数据来传，目测不需要转码

**Comment by flingInTheSky** [comment]
懂了

**Comment by JxXiaoXie** [comment]
不转码拿到正常数据了吗？

**Comment by flingInTheSky** [comment]
我现在是这么处理的：拿到的数据是个16进制的数值，把他转化为字节数组，就可以转换为旧版本的数据格式了。固件版本取到的也是个16进制的数值，把它转换为字符串就OK了。不需要base64处理

**Comment by JxXiaoXie** [comment]
嗯， 那你写入蓝牙的数据呢？bt.getService(ServiceUUID).getCharacteristic(RCharacteristicUUID).writeWithoutResponse(data) data的格式。
