### ISSUE TITLE
NumberSpinner在iOS 12.3.2系统显示不出来

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#1000]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: iOS 12.3.2
- SDK分支: 10021
- 相关模块: miot/ui/NumberSpinner

**现象（必填）**
10021分支下，NumberSpinner在iOS 12.3.2系统显示不出来（iOS 12.3.1不会），滑动之后会出现闪退问题，我在demo中验证了也是同样的问题。

**期望（必填）**
期望NumberSpinner在iOS 12.3.2显示正常

**其他的上下文/日志/截图**

![ezgif-5-767d717c8c21](https://user-images.githubusercontent.com/2813239/59497628-68892d00-8ec6-11e9-92a6-7468ec2e7912.gif)

**Comment by santcool** [comment]
请问12.3.2是beta版本吗？

**Comment by fengdexunmi** [comment]
@santcool 不好意思，昨天忘记回复了，系统提示我更新，然后我就升级到12.3.2，不知道是不是beta版本，我就只是跑了com.xiaomi.demo工程的NumberSpinnerDemo，发现这个问题，不设置选中背景色也不行

![IMG_4315CC180D43-1](https://user-images.githubusercontent.com/2813239/59651547-d41c1480-91bc-11e9-9e5e-bed98f1b1921.jpeg)

**Comment by LiuMengzhou** [comment]
首先我们这边都没收到系统更新的通知，所以没办法测试复现。

然后，你再确认一下对照实验是不是用的**同一个DB包**，不管是beta还是线上。
