### ISSUE TITLE
室外温度智能场景联动执行失败

### ISSUE THREAD

**Issue by fishstick77** [MiEcosystem/miot-plugin-sdk#1001]
**是否为新品（必填）**
在售

**关联的产品model**
qmi.powerstrip.v1

**项目ID（必填）**
19689

**企业名称（必填）**
青米（北京）科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:MIUI10.3 Android 8.0.0
- SDK分支: 10011
- 相关模块:

**现象（必填）**
米家中添加智能场景，“温度低于34度时关闭青米智能插排”
场景触发后，智能日志显示"执行失败"，"异常错误"。

**期望（必填）**
智能联动场景执行成功

**其他的上下文/日志/截图**
开发平台上智能场景配置是上线状态
米家app智能日志失败截图如下：
![image](https://user-images.githubusercontent.com/13927045/59502442-557b5a80-8ed0-11e9-9e59-d56d0fc70581.png)

**尝试过的解决办法**
其他智能场景，如日落时关闭，定时关闭等，都可以成功执行。

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
判断温度执行操作，没有相关模块吗？

**Comment by fishstick77** [comment]
> 判断温度执行操作，没有相关模块吗？

这个添加过程，和触发执行的操作都没有插件参与。是通过米家app添加的智能联动，您这边能提供一些建议么？

**Comment by lvjie0519** [comment]
@fishstick77   麻烦提供下相关执行失败的日志或者需要将测试账号给我们，才好方便排查，谢谢。

**Comment by fishstick77** [comment]
> @fishstick77 麻烦提供下相关执行失败的日志或者需要将测试账号给我们，才好方便排查，谢谢。

用户ID：393384955
智能名称：海淀温度低于34℃-青米智能插排2关
执行时间：2019年6月3日19:57

没有日志，这个是指硬件日志么？看起来服务器调用插排开关这个操作看起来是正常的，怀疑有可能是温度订阅推送执行命令的问题？
辛苦了。

**Comment by lvjie0519** [comment]
@fishstick77   麻烦再复现下这个场景错误，如上错误太久，服务端没有保留日志这么久，复现错误了马上知照下，谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，如有问题，在reopen。
