### ISSUE TITLE
获取蓝牙版本，Android和iOS下显示不一致

### ISSUE THREAD

**Issue by codebeautiful** [MiEcosystem/miot-plugin-sdk#1002]
**是否为新品（必填）**
新品 

**关联的产品model**
lcrmcr.safe.ms30b

**企业名称（必填）**
小匠

**环境（必填）**
- 电脑操作系统:[Mac OS/Linux]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master]
- 相关模块:[Device.getBluetoothLE]
Android的米家版本为：5.5.25.3 测试版，5.5.25，5.5.25.1 测试版
iOS的米家版本为：bate 251

**现象（必填）**
在做ble OTA时，获取蓝牙固件版本信息时，分别在iOS，Android上测试，在iOS测试可以拿到正常的版本信息，在Android上测试为乱码
iOS上显示：current version: 2.1.11_0028
Android上显示：current version: c�Q�����3�!F�˝�p��)
调用方法：
```
  if (bt.isConnected) {
      bt.getVersion().then(res => {
        console.log("current version:", res);
        }
}
```

**期望（必填）**
期望在Android和iOS下表现一致

**尝试过的解决办法**
分别在不同的米家App版本下做过测试，上述的版本都存在相同的问题

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@dingshaoran 请你协助查看此问题

**Comment by codebeautiful** [comment]
@dingshaoran @zanetti4 这个问题怎么破，现在就差这一个问题了
