### ISSUE TITLE
Video控件出错{ error: { extra: 0, what: -38 } }

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#1003]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.2]
SDK分支: [master]
相关模块:[Video]
现象（必填）
视频控件正在播放时，切换到桌面，等待10秒，然后回到米家插件，发现视频出现黑屏。过2秒恢复正常，然后使用seek方法设置视频进度，这时出现onError：{ error: { extra: 0, what: -38 } }。

期望（必填）
切换到桌面后回到米家插件后可以正常使用seek方法。

其他的上下文/日志/截图
正常：
![Screenshot_2019-06-17-11-15-43-453_com xiaomi smarthome](https://user-images.githubusercontent.com/14890491/59576967-41b03e00-90f4-11e9-8f60-0148a374467b.png)
出错：
![Screenshot_2019-06-17-11-26-50-117_com xiaomi smarthome](https://user-images.githubusercontent.com/14890491/59576973-48d74c00-90f4-11e9-8f1f-ea797e935bdf.png)

尝试过的解决办法
错误码不清楚，不知道怎么解决。

**Comment by zanetti4** [comment]
经过测试在 ios 12.2并未出现黑屏和使用 seek 方法报错的现象，请参照 [react-native-video](https://www.npmjs.com/package/react-native-video) 文档使用该模块。
另外，我在10021分支上更新了演示文件：com.xiaomi.demo/Main/Host/VideoDemo.js，可以查看。

**Comment by lijian9088** [comment]
不好意思，，写错了，是在android下，ios未出现问题，。小米5s，android7.0版本

**Comment by lijian9088** [comment]
@zanetti4

**Comment by zanetti4** [comment]
我用安卓7测试，没有黑屏现象，但是切回米家插件时，视频会有一瞬间的偏色，马上就恢复正常了。使用 seek 方法可以正常设置进度。你测试这个 VideoDemo.js 也是同样的情况吗？

**Comment by zanetti4** [comment]
那个不是偏色问题，是测试视频本身的颜色……

**Comment by lijian9088** [comment]
谢谢回复，我这边更换视频再测一下，也有可能是视频本身的问题。
