### ISSUE TITLE
米家插件通用UI组件TitleBar可定制性不好

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1005]
**是否为新品（必填）**
新品 
**环境（必填）**
- 电脑操作系统:macOS
- 相关模块:miot-sdk/ui/TitleBar

**现象（必填）**
米家插件通用UI组件TitleBar可定制性不好,例如我想在导航栏右侧添加两个按钮，右第二个不支持自定义图片，只会显示默认图片

**期望（必填）**
导航栏右侧第二个按钮可以自定义图片
还有就是通用UI组件的定制性要高，以满足不同的需求

**Comment by LiuMengzhou** [comment]
用新的吧
https://github.com/MiEcosystem/miot-plugin-sdk/blob/ui_doc/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E6%96%B0%E7%89%88%E5%AF%BC%E8%88%AA%E6%A0%8Fnavigationbar
