### ISSUE TITLE
隐私协议左滑出现黑屏

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#1006]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.ceiling

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
飞慧照明

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]

**现象（必填）**
进入隐私协议时左滑会会出现黑色

**期望（必填）**
正常表现

**其他的上下文/日志/截图**
![7381560753773_ pic](https://user-images.githubusercontent.com/18681867/59583940-50581e80-910f-11e9-9632-4e786c52badf.jpg)

**Comment by zanetti4** [comment]
我先借个 ios 11 手机，测试后会反馈的。刚才测试 ios 12，无论米家 app 的隐私协议还是插件内部的隐私协议，都没有这个问题。

**Comment by zanetti4** [comment]
用 ios 11手机进行测试，也没有发现该问题。如果你那边一直存在此问题，请提供更多的信息。

**Comment by xuanxuandaoren** [comment]
@zanetti4  

## 是FAQ界面 

### 现象 

连接设备，进入插件，点击右上角"..."->点击"使用帮助"，进入FAQ界面，随机点击一个问题进入界面，从左到右滑动退出此界面，会出现黑色线条界面   

### 机型 
iphone XR 
###  iOS版本 
12.3.1

**Comment by santcool** [comment]
已修改，明早到首页下载新的调试包即可。
