### ISSUE TITLE
米家验收部门要求：设置->删除设备 第三方设备需要在重新连接后再次弹出隐私和协议授权提示框

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#1007]
**是否为新品（必填）**
新品

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android /iOS ]
- SDK分支: [master/10021]
- 相关模块:[Host/ui]

**现象（必填）**
Q: 简单明了地描述一下实际的现象。
A: （米家验收部门提的新需求，不实现验收不给过。）

**期望（必填）**
Q:  简单明了地描述一下期望的表现。
A:  米家验收部门给我们提了一个新需求，是在设置页面，点击“删除设备”按钮 删除掉设备后，再次进入插件需要也弹出隐私授权的提示框，跟点击“撤销。。”后的逻辑一致。而且此功能暂时只在第三方设备上需要，而米家系列设备暂不需要。

**其他的上下文/日志/截图**
Q: 提供更多的上下文，有日志或者截图更好。
A：
![Catch(06-12-18-14-24)](https://user-images.githubusercontent.com/8743690/59584225-058ad680-9110-11e9-823b-84b9055f27dd.jpg)

![CatchD883](https://user-images.githubusercontent.com/8743690/59584263-1e938780-9110-11e9-88fb-dd3b4226a22f.jpg)

**尝试过的解决办法**
Q：尝试过哪些操作？
A：看了下当前最新的10021分支的代码，设置->删除设备 当前只有message一个参数，没有回调函数可供实现需求。

**Comment by blockdate** [comment]
Duplicate of #959
