### ISSUE TITLE
Spec 获取属性值报错

### ISSUE THREAD

**Issue by xiaosheng-W** [MiEcosystem/miot-plugin-sdk#1008]
**是否为新品（必填）**
 新品

**企业名称（必填）**
艾欧史密斯（中国）环境电器有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.0
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Spec]

**现象（必填）**
getPropertiesValue 报错code:-704090001
setPropertiesValue 同样报错
**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
{code: -704090001, siid: 2, did: "107157802", piid: 1}

**Comment by zanetti4** [comment]
请把该设备分享给我进行测试，我的米家 id: 894158105

**Comment by xiaosheng-W** [comment]
已经分享

**Comment by santcool** [comment]
请根据https://iot.mi.com/new/guide.html?file=07-%E4%BA%91%E5%AF%B9%E4%BA%91%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E5%BA%94%E7%94%A8%E4%BA%91%E5%AF%B9%E4%BA%91%E6%8E%A5%E5%85%A5/01-%E5%B0%8F%E7%B1%B3IOT%E6%8E%A7%E5%88%B6%E7%AB%AFAPI，最底下的状态码来排查问题。

**Comment by xiaosheng-W** [comment]
请问{code: -704090001, siid: 2, did: "107157802", piid: 1},  http409 , 0客户端错误, 001 Device不存在,是由于什么原因造成的,设备列表设备也是存在的

**Comment by xiaosheng-W** [comment]
APP端切换到preview环境进行开发调试解决001报错

**Comment by betterFuture** [comment]
这个问题解决了吗 我遇到一样的问题

**Comment by xiaosheng-W** [comment]
> 这个问题解决了吗 我遇到一样的问题

解决方式已经回复
