### ISSUE TITLE
希望提供一份 RN 插件内创建 spec 协议的自定义 scene 文档或者 demo，现有的 wiki 文档只提供了定时 scene 创建的字段。

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#1009]
**是否为新品（必填）**
新品

**关联的产品model**
lumi.gateway.mgl03

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:Service.scene

**现象（必填）**
希望提供一份 RN 插件内创建 spec 协议的自定义 scene 文档或者 demo，现有的 wiki 文档只提供了定时 scene 创建的字段。

**Comment by santcool** [comment]
已提供，在此文档的最底下。https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E8%87%AA%E5%8A%A8%E5%8C%96%E9%85%8D%E7%BD%AE
