### ISSUE TITLE
国际化疑问

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#101]
平台：iOS

>      res.registerStrings({
>         zh:{
>             t1:"测试字符串",
>             t2:"数值为{1}",
>             t3:["从{1}到{2}", [0, "非法数据"], [1, "错误数据"], [2, "从 二 到 {2}"], [(v1,v2)=>v1>100, "太多了"]],
>             t4:{
>                 t5:()=>"好的",
>                 t6:["最多{1}"],
>                 t7:(a,b,c)=>`${a}|${b}|${c}`,
>                 t8:"你好"
>             }
>         },
>         en:{
>             t1:"test strigns",
>             t2:"value is {1}",
>             t3:["from {1} to {2}", [0, "invalid data"], [1, "wrong value"], [3, "from three to {2}"], [v1=>v1>100, "too more"]],
>             t4:{
>                 t5:[()=>"good"],
>                 t6:"{1} at most",
>                 t7:(a,b,c)=>`${a}/${b}/${c}`
>             }
>         }
>      });

- 疑问一：console.log(**typeof res.strings.t1**); 输出其实是function，那么在Text控件里，就需要所有国际化文字修改为   res.strings.t1()  函数调用？这样就导致迁移工作量很大，有没有什么一次性解决方案？不然就会有很多警告

- 疑问二：是否支持 pt（葡萄牙）、nl （荷兰）语？
- 疑问三：setLanguage('en') 后，res.strings.t1 为什么还是中文？这两者是否有关联？

**Comment by edwardair** [comment]
问题1，通过预先获取语言，再直接初始化字典解决
问题2，能否增加这两个语言支持

**Comment by laohuang88** [comment]
疑问一，输出的确是一个function，但是他的toString就是原始文本，其实鼓励所有的字符串调用都加上（）来调用。你也可以用miot/ui/LocalizedStrings，它返回的是字符串
疑问二，暂时还没有支持pt和nl， 目前支持的语言参照 https://miecosystem.github.io/miot-plugin-sdk/module-miot_resources-Language.html ， 我们考虑加一下这两种语言
疑问三，如果还是中文则是有问题的，我们测试一下。 不过如果res.strings.t1的结果是缓存过的，则不会改变。
