### ISSUE TITLE
单击和触摸事件不响应

### ISSUE THREAD

**Issue by wxy693172809** [MiEcosystem/miot-plugin-sdk#1010]
**是否为新品（必填）**
新品

**关联的产品model**
“aiqi.remote.xiaomimaze”

**项目ID（必填）**
无项目ID

**企业名称（必填）**
北京爱其科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 7.12
- SDK分支: 10010
- 相关模块:点击触摸

**现象（必填）**
绑定触摸的控件只能在屏幕的上部小部分区域生效，如果控件位于屏幕下半部分布不生效。（开发者模式和苹果手机测试不存在这问题）

**期望（必填）**
点击和触摸事件在全屏生效

**其他的上下文/日志/截图**
![IMG_20190617_192448](https://user-images.githubusercontent.com/11309056/59601451-8f4d9a80-9136-11e9-84f3-60ba702d63c0.jpg)

**尝试过的解决办法**
测试触摸事件绑定的控件占满整个屏幕时，也只有上半部分生效。

 <TouchableHighlight
                  style={styles.button1}
                  onPress={this.btnClick1}
                >
                <Text>上面按钮</Text>
                </TouchableHighlight>
               
                <TouchableHighlight
                  style={styles.button2}
                  onPress={this.btnClick2}
                >
                <Text>下面按钮</Text>
                </TouchableHighlight>

 button1: {
        width: 150,
        height: 40,
        backgroundColor: 'blue',
        justifyContent: 'center',
        alignItems: 'center',
        position:'absolute',left:10,top:50
      },

      button2: {
        width: 150,
        height: 40,
        backgroundColor: 'blue',
        justifyContent: 'center',
        alignItems: 'center',
        position:'absolute',left:10,top:300
      },

**Comment by zanetti4** [comment]
我在10021分支上创建了一个演示文件：com.xiaomi.demo/Main/UIComponent/AbsoluteTouch.js
用安卓7手机测试，无论在开发者模式还是插件中，都能触发下方按钮的点击事件。你可以看一下，如果问题解决了，请关闭此 issue

**Comment by wxy693172809** [comment]
> 我在10021分支上创建了一个演示文件：com.xiaomi.demo/Main/UIComponent/AbsoluteTouch.js
> 用安卓7手机测试，无论在开发者模式还是插件中，都能触发下方按钮的点击事件。你可以看一下，如果问题解决了，请关闭此 issue

之前用米家的是5.5.25版，更新到5.5.29就好使了，之前版本插件模式进去下面会弹一个未连接框，现在版本不弹了也可能是这个原因。
