### ISSUE TITLE
无法监听到上报的属性

### ISSUE THREAD

**Issue by Xiaomi1050708607** [MiEcosystem/miot-plugin-sdk#1011]
**是否为新品（必填）**
新品

**关联的产品model**
xafd.remote.litwidctr

**项目ID（必填）**
66681

**企业名称（必填）**
西安丰盾特种门窗厂

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 9]
- SDK分支: [master/10012]
- 相关模块:[miot/Device]

**现象（必填）**
.addListener((dev,mas,ora)=>{...})，无法监听，{...}大括号里的内容不执行，所以也无法获得监听的数据

**期望（必填）**
监听到上报的属性

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/49677284/59605948-8fec2e00-9142-11e9-94ae-52e7fec51b76.png)
![image](https://user-images.githubusercontent.com/49677284/59606048-c32ebd00-9142-11e9-969e-e42d143abe43.png)

**尝试过的解决办法**
复制api里的Example，依然无法监听

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@Xiaomi1050708607 
1、ios能监听到吗？
2、你这只是监听设备属性，设备的属性又发生对应的改变吗？

**Comment by Xiaomi1050708607** [comment]
感谢@lvjie0519，问题解决了，设备重复上报2种属性后，可以监听到上报的属性。
