### ISSUE TITLE
Wanted:请集成相关的库实现Android和IOS的图片裁剪功能

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1012]
**是否为新品（必填）**
 在售

**关联的产品model**
yeelink.light.bslamp1
yeelink.light.bslamp2
yeelink.light.bslamp3
yeelink.light.color1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
想要一个图片裁剪功能，未在miot-sdk中发现相关的裁剪功能的库

**期望（必填）**
实现Android和IOS的图片裁剪功能，现有的image-picker库不能支持两个平台的裁剪功能

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
@DennisJu007 请查查rn第三方image库看看先，这种需求挺常见的

**Comment by DennisJu007** [comment]
嗯呢推荐使用react-native-image-crop-picker这个库，不知道米家是否能够集成到sdk

**Comment by Woody2016** [comment]
react-native-image-picker这个库满足你们的要求吗？这个是已经集成了的

**Comment by santcool** [comment]
你们这个裁剪，是需要用户自己控制裁剪区域，还是只需要减小图片大小？
