### ISSUE TITLE
安卓平台某些动态大小图片显示模糊

### ISSUE THREAD

**Issue by HunterHeRock** [MiEcosystem/miot-plugin-sdk#1013]
---
**是否为新品（必填）**
在售

**关联的产品model**
roborock.vacuum.tanos
roborock.vacuum.m1s

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
石头科技

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
扫地机器人地图上的机器人图标/充电桩图标是2个伴随地图缩放同时动态缩放的图片，在安卓平台上的显示的图片非常模糊，在IOS 的手机上显示则无明显问题

**期望（必填）**

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46810609/59649119-09703480-91b4-11e9-95cd-26d1f182c625.png)

需要明确的一点是：在调试模式使用远程机器code加载到安卓平台上则这个效果不复现，只有是打包发版之后的使用版本复现。

**尝试过的解决办法**
我们尝试过图片加入resizeMode 修正显示，但是现有的图片并非是部分显示造成的问题，而是已经是可以完全显示了只是效果模糊。

**不要贴大段代码❗️**

**Comment by HunterHeRock** [comment]
补充一个情况：此情况只在引用本地图片资源（使用require）时出现问题，uri链接方式引用外部图片暂未发现问题

**Comment by fishle** [comment]
会不会跟这个问题是一个原因？https://github.com/MiEcosystem/miot-plugin-sdk/issues/1154

**Comment by fishle** [comment]
先根据#1154分析一下，还有问题再打开吧
