### ISSUE TITLE
CommonSetting中法律信息页面iOS与安卓UI差异性

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#1014]
是否为新品（必填）
在售

关联的产品model
yeelink.light.bslamp1
yeelink.light.bslamp2
yeelink.light.bslamp3
yeelink.light.color1

项目ID（必填）
【无项目ID】

企业名称（必填）
Yeelight

环境（必填）

电脑操作系统:[eg.Windows/Mac OS/Linux]
手机系统:[eg.Android 7.1.1iOS 12.3]
SDK分支: [eg.master/10012/...]
相关模块:[eg.Host/Service/Account]
现象（必填）
CommonSetting中法律信息页面iOS与安卓UI差异性如下：
1、iOS有标题，安卓则没有
2、撤销授权按钮名称不同
如下截图

期望（必填）
能修复如上问题

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/9053681/59650189-b26c5e80-91b7-11e9-82bd-b4695c7b9757.png)
![image](https://user-images.githubusercontent.com/9053681/59650194-b5674f00-91b7-11e9-9d58-b76b14515acc.png)

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码❗️

**Comment by zanetti4** [comment]
现在安卓端正在修改，将以 ios 为主。

**Comment by lvjie0519** [comment]
@TheWalkingDead1024   这个模块，Android正在改版，预计25号完成。

**Comment by TheWalkingDead1024** [comment]
> @TheWalkingDead1024 这个模块，Android正在改版，预计25号完成。

收到，感谢

**Comment by DennisJu007** [comment]
@lv @zanetti4 大佬们这个问题改好了么，我下载的最新Android米家测试apk还没有解决呢，米家版本5.5.30.6

**Comment by lvjie0519** [comment]
@TheWalkingDead1024  已修复，使用最新apk进行测试，谢谢。

**Comment by zanetti4** [comment]
@DennisJu007 请使用最新apk进行测试
