### ISSUE TITLE
添加桌面快捷方式

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1015]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulb

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10020]
- 相关模块:[?]

**现象（必填）**
ios添加桌面快捷方式后，点击桌面快捷方式，会先跳转到插件页，再跳到米家设备页，最后回到插件页。
android直接进入插件页。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
能录个小视频并提供一下你使用的代码吗，我这边没法复现。

**Comment by mirse** [comment]
> 能录个小视频并提供一下你使用的代码吗，我这边没法复现。

已发邮件，请排查下，谢谢。

**Comment by santcool** [comment]
这个视频看不出来任何问题。你是说ios不该先进入米家首页？
