### ISSUE TITLE
Device.getDeviceWifi().callMethod在android端会自带sid

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#1016]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
填 新品 or 在售
在售

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
lumi.sensor_ht.v1
lumi.weather.v1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
23954

**企业名称（必填）**
贵司的名称
绿米联创

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS

- 手机系统:[eg.Android 8.1/iOS 11.0]
Android8.1

- SDK分支: [eg.master/10000/...]
10020

- 相关模块:[eg.Host/Service/Account]
Device.getDeviceWifi().callMethod

**现象（必填）**
简单明了地描述一下实际的现象。
在android端请求Device.getDeviceWifi().callMethod
发出去的数据会自带sid

**期望（必填）**
简单明了地描述一下期望的表现。
没有特殊要求，没有自行设置sid，就不要自动附带sid

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![33261F5E-B6AF-4C68-81FF-3D60A95A1A74](https://user-images.githubusercontent.com/10232787/59652164-1cd4cd00-91bf-11e9-9e6d-3270290c8100.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@wanggoingdown    你这打印的是哪里输出的日志？

**Comment by wanggoingdown** [comment]
@lvjie0519 我在开发平台的运营里面看的设备日志

**Comment by lvjie0519** [comment]
@wanggoingdown   调用callmethod方法的时候， 查看下core进程中的log日志

**Comment by wanggoingdown** [comment]
@lvjie0519 我这是个RN插件项目，我看不到日志啊，上面粘贴的是固件的日志

**Comment by lvjie0519** [comment]
@wanggoingdown   
1、Android通过logcat  可以查看日志，没有搭建Android开发环境的，需要安装logcat工具；
2、固件端能否知道是服务端发送过来的rpc请求还是手机发送过来的rpc请求？callmethod有可能走本地也有可能走云端，我这边排查，没发现有带sid。

**Comment by wanggoingdown** [comment]
@lvjie0519 
这是我在logcat上面截取到的log
这个请求是android端发送的，请求成功，code为异常值
但是ios端发送的，请求成功，code为正常值
![A9F8F555-77F4-48B6-B834-C25E7F1996C9](https://user-images.githubusercontent.com/10232787/59813491-453a0400-9344-11e9-9872-7975c4f900b8.png)

**Comment by wanggoingdown** [comment]
@lvjie0519 
这是我在开发者平台上面查看的网关日志，android端发送的请求确实会多加一个sid
![40634F5F-69E6-47C4-84EB-CD08B65548E5](https://user-images.githubusercontent.com/10232787/59813655-e0cb7480-9344-11e9-902c-89c4fa143fc6.png)

**Comment by lvjie0519** [comment]
@wanggoingdown 
1、把设备分享给  894158105账号，同时告知下设备的名称；
2、请把你调用callmethod的代码截图一下，我这边测试，试试。

**Comment by wanggoingdown** [comment]
1.子设备没法分享，米家温湿度传感器
2.以下是调用截图
![19678605-FBCA-435C-A807-0EDD3FE90691](https://user-images.githubusercontent.com/10232787/59817177-766d0100-9351-11e9-8644-0a8bdab041f3.png)

**Comment by wanggoingdown** [comment]
@lvjie0519 已经把该设备的网关分享给你指定的账号了，网关名为：666，子设备名为：米家温湿度传感器

**Comment by wanggoingdown** [comment]
@lvjie0519 有消息了吗

**Comment by lvjie0519** [comment]
@wanggoingdown   咨询了服务端，sid是服务端添加的参数，ios之所以没带，应该是callmethod走的本地，你可以使用ios试试非局域网下会不会出现同样的问题或调用callMethodFromCloud试试，Android下如果要走本地，先调用localping看能否ping通。

**Comment by wanggoingdown** [comment]
@lvjie0519 我按照你的指示进行了以下测试
1.android与ios端都调用了localping，发现都返回false
2.ios端调用callMethodFromCloud，在开发者平台上抓的日志，依然没有携带sid

**Comment by wanggoingdown** [comment]
该问题已经解决，get_device_prop_exp需要向网关请求接口改为Device.parentDevice.getDeviceWifi()
