### ISSUE TITLE
固件升级失败后iOS不能重新升级

### ISSUE THREAD

**Issue by GuZilin** [MiEcosystem/miot-plugin-sdk#1017]
**是否为新品（必填）**
新品

**关联的产品model**
tokit.oven.tk32pro1

**项目ID（必填）**
66516

**企业名称（必填）**
上海纯米电子科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:Android 9/iOS 12.1
- SDK分支: master/10010/
- 相关模块:miot/ui/CommonSetting/CHECK_UPGRADE

**现象（必填）**
固件升级失败后，Android点击“重试”按钮可以继续升级，iOS点击“重试”按钮无反应，无法继续升级。

**期望（必填）**
Android和iOS都能重新升级

**其他的上下文/日志/截图**

Android演示视频：https://v.youku.com/v_show/id_XNDIzMjYzODE0OA==.html?spm=a2h3j.8428770.3416059.1
iOS演示视频： https://v.youku.com/v_show/id_XNDIzMjY0MDAyNA==.html?spm=a2h3j.8428770.3416059.1
视频播放密码：mijia123

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
SDK_10021增加了CommonSetting这个module，修复了这个问题。你可以更新到SDK_10021分支

**Comment by hyunhui2006** [comment]
@GuZilin 确认一个问题：安卓重试多次都是可以成功的吗？iOS重试多次一直都是失败吗？

**Comment by GuZilin** [comment]
> @GuZilin 确认一个问题：安卓重试多次都是可以成功的吗？iOS重试多次一直都是失败吗？

点击重试是有在重新升级，因为过了一会固件是升级成功的，只是iOS点重试界面无任何变化，让用户感觉好像点击无效一样，Android点重试界面会变为正在升级的页面

**Comment by Woody2016** [comment]
为什么第一次点击固件升级会提示失败，这个问题也得查啊。
感觉像是固件端/米家云端返回了错误信息，所以app会提示失败

**Comment by GuZilin** [comment]
> 为什么第一次点击固件升级会提示失败，这个问题也得查啊。
> 感觉像是固件端/米家云端返回了错误信息，所以app会提示失败

这个应该是我们硬件上报的数据有问题（WiFi模组用的不是米家的，上报的数据也都是自己根据米家协议封装的），现在已经修复第一次升级必定失败的bug。但还做不到升级百分之百成功，所以还是会有失败后点击重试的操作。

**Comment by zanetti4** [comment]
这个问题解决了吗？
