### ISSUE TITLE
Android米家正式版App上item无右侧箭头

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#1018]
公司名称（必填）
西安蜂语

是否为新产品（必填）
否

环境（必填）
电脑操作系统:[Windows]
手机系统:[Android]
SDK分支: [10012]

现象（必填）
在米家Android最新测试版App v5.5.25.3上插件是有右侧箭头的，但是在正式版App5.5.25中所有使用ListItem的列表项都没有右侧箭头，通用设置中的列表项也没有，目前使用的开发SDK分支为10012。应该是米家版本导致；

期望（必填）
米家Android正式App什么时候会更新？
![3](https://user-images.githubusercontent.com/15820075/59665026-b5317880-91e4-11e9-8480-3a119cb8022d.jpg)
![4](https://user-images.githubusercontent.com/15820075/59665035-b793d280-91e4-11e9-97b4-a2b8af351f73.jpg)

**Comment by LiuMengzhou** [comment]
#991

**Comment by lvjie0519** [comment]
@ding209   将设备分享到 894158105，同时告知下设备名称，谢谢。

**Comment by ding209** [comment]
@lvjie0519 不好意思，我们产品没有没有不支持共享，产品设置的不支持。

**Comment by lvjie0519** [comment]
@ding209   问题已修复，请使用最新apk，进行测试，谢谢。

**Comment by ding209** [comment]
@lvjie0519 你好，已更新到最新的5.5.30版本，测试后发现这个问题没有彻底解决，我们有两个产品（两个model，小米米家对讲机1S和小米米家对讲机2），如果只添加一种设备，那么一直都是有箭头的。
但是在继续添加另一种设备后，两种设备的就都没有箭头了，很奇怪的现象，并且无论如何也出不来箭头了。
![image](https://user-images.githubusercontent.com/15820075/59816760-eb3f3b80-934f-11e9-9955-ba25fbe685f3.png)
![image](https://user-images.githubusercontent.com/15820075/59816766-eed2c280-934f-11e9-8138-76170f68c9df.png)
![image](https://user-images.githubusercontent.com/15820075/59816770-f2fee000-934f-11e9-84ad-fc88ef381ad1.png)
![image](https://user-images.githubusercontent.com/15820075/59816777-f98d5780-934f-11e9-9fe0-4cc7d2566406.png)

**Comment by ding209** [comment]
包括通用设置界面也没有箭头，用的都是UI框架中的ListItem

**Comment by LiuMengzhou** [comment]
Same as https://github.com/MiEcosystem/miot-plugin-sdk/issues/991#issuecomment-501607289

看来是一个新的问题。。。 @lvjie0519

**Comment by lvjie0519** [comment]
@ding209   已更新到最新的5.5.30版本 是当前线上版本，  线上版本应该有问题，  用如下下载地址下载最新debug版本apk进行测试。
https://fir.im/MiHomeForAndroid

**Comment by ding209** [comment]
@lvjie0519 你好，用这个5.5.25.8 debug版本测试后箭头都是正常的。请问有计划什么时候会更新到正式版本吗？

**Comment by LiuMengzhou** [comment]
> @ding209 已更新到最新的5.5.30版本 是当前线上版本， 线上版本应该有问题， 用如下下载地址下载最新debug版本apk进行测试。
> https://fir.im/MiHomeForAndroid


@lvjie0519  我以为他是用测试版试的，哈哈哈，终于解决了。

**Comment by lvjie0519** [comment]
@ding209   已经开始集测，计划2019/6/25 开始灰度，七天后全量发布。
