### ISSUE TITLE
MessageDialog在Android端复用存在问题

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#1019]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0
- SDK分支: 10021
- 相关模块: miot/ui/MessageDialog

**现象（必填）**
在index.js声明一个MessageDialog，不同的Page都公用这个MessageDialog。
如果我在Page A先对MessageDialog设置了无标题、无取消按钮样式显示正常，然后在Page B对MessageDialog设置了标题和取消按钮，但是在Android端显示的还是无标题和无取消按钮样式，在iOS端是正常的。

**Android端表现**：（**不正常**）

![image](https://user-images.githubusercontent.com/2813239/59668058-6850a080-91ea-11e9-9341-6dfb7af3ac64.png)

![image](https://user-images.githubusercontent.com/2813239/59668202-a4840100-91ea-11e9-9d83-209d09e28691.png)

**iOS端表现**：（**正常**）

![IMG_0019](https://user-images.githubusercontent.com/2813239/59668294-cda49180-91ea-11e9-8608-1fdaadb69e75.PNG)

![IMG_0020](https://user-images.githubusercontent.com/2813239/59668299-d006eb80-91ea-11e9-8fd3-8ed0ea680620.PNG)

**期望（必填）**
期望在Android可以正常复用MessageDialog

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我在10021分支上新建了演示文件：
com.xiaomi.demo/Main/UIComponent/UIDemo.js
com.xiaomi.demo/Main/UIComponent/DialogTest2.js
com.xiaomi.demo/Main/UIComponent/DialogTest3.js
UIDemo 里引入的 MessageDialog，DialogTest2 和 DialogTest3 中进行了复用。在安卓手机可以显示定制的消息对话框，请查看。如果问题得到解决，请关闭此 issue。

**Comment by fengdexunmi** [comment]
@zanetti4 可能我没有说明清楚，我看了DialogTest2.js和DialogTest3.js的代码，这里是两个独立的MessageDialog对象。

![image](https://user-images.githubusercontent.com/2813239/59683058-00aa4d80-920a-11e9-8966-c0500bb2c01c.png)

我这边的实现是放一个隐藏的MessageDialog在所有Page的最上层，需要的时候更改visible来显示，以及更改其他属性（title、message等）

```JavaScript
render() {
      const {
        MessageDialogObject,
      } = this.state;
      return (
        <View>
          <MessageDialog
            title={MessageDialogObject.title || ' '}
            message={MessageDialogObject.message}
            visible={MessageDialogObject.visible}
            confirm={MessageDialogObject.confirm}
            onConfirm={MessageDialogObject.onConfirm}
            cancel={Platform.OS === 'android' ? (MessageDialogObject.cancel || LocalizedStrings.cancel) : MessageDialogObject.cancel}
            onCancel={MessageDialogObject.onCancel}
            cancelable={MessageDialogObject.cancelable || false}
            timeout={MessageDialogObject.timeout}
            onDismiss={() => {
              this.setState({
                MessageDialogObject: Object.assign({}, MessageDialogObject, { visible: false })
              });
            }}
          />
        </View>
      )
    }
```
全局就只有一个MessageDialog，不是每一个Page都有一个MessageDialog对象，传不同的MessageDialogObject控制不同的样式和内容。

**Comment by zanetti4** [comment]
@lvjie0519 这个可能不是 js使用问题，请帮忙查看

**Comment by lvjie0519** [comment]
已修复， 请使用最新apk进行测试，谢谢。
