### ISSUE TITLE
如何使用react-native-canvas插件？

### ISSUE THREAD

**Issue by maker9** [MiEcosystem/miot-plugin-sdk#1020]
**是否为新品（必填）**
新品

**项目ID（必填）**
无项目ID

**企业名称（必填）**
速感科技

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: iOS 11.0

**现象（必填）**
如何正确使用[react-native-canvas](https://www.npmjs.com/package/react-native-canvas)库，
错误提示：Native component for "RNCWKWebView" does not exist

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
![WechatIMG80](https://user-images.githubusercontent.com/32405797/59674667-58d75480-91f6-11e9-96ad-9f11f3354841.jpeg)

**Comment by blockdate** [comment]
这个是需要native端集成才能正常使用。

米家扩展程序目前除了已提供的npm模块之外，只能自行添加纯JS实现的三方库

**Comment by maker9** [comment]
画类似石头扫地机的网格图，有没有SDK, 或者推荐的第三方库？

**Comment by zanetti4** [comment]
石头扫地机的网格图是什么样子？能提供一张图片吗？

**Comment by maker9** [comment]
![1561098264763](https://user-images.githubusercontent.com/32405797/59902255-506a5e00-9430-11e9-83f0-c478d7ca2663.jpg)
![1561098241226](https://user-images.githubusercontent.com/32405797/59902257-5102f480-9430-11e9-8167-4dfe85bd8742.jpg)
![1561098174657](https://user-images.githubusercontent.com/32405797/59902258-5102f480-9430-11e9-8764-b1fbcb2d8a30.jpg)

类似这样的地图

**Comment by zhouliangshun** [comment]
改成svg

**Comment by qfeeltech** [comment]
@zhouliangshun 这是网格图，我们可能需要画1.5万-2万多个小矩形，担心用svg的话，DOM树会太大，影响性能。请问有什么建议吗？谢谢

**Comment by zhouliangshun** [comment]
如果不是动态且刷新要求非常高的话svg应该也能满足，小矩形太多就想办法合并。
