### ISSUE TITLE
新的UI组件需求：带开关列表项是否可以新增右箭头

### ISSUE THREAD

**Issue by LiuMengzhou** [MiEcosystem/miot-plugin-sdk#1023]
有类似的需求就直接在这里盖楼了方便统一管理，看了demo里面没有下面图片中的这种样式，能不能在原基础上支持一下加个带右边箭头的，然后用一个状态来控制右边箭头显示隐藏，具体需求如下：
![image](https://user-images.githubusercontent.com/42829167/59671330-0d21ac80-91f0-11e9-92b6-5a7154104215.png)

_Originally posted by @DennisJu007 in https://github.com/MiEcosystem/miot-plugin-sdk/issues/991#issuecomment-503029878_

**Comment by DennisJu007** [comment]
谢谢大佬支持，我们插件如上图item中的使用方法分两种情况：
1、是有右侧箭头代表这个页面可以点击进入详情页进行具体设置，比如Yeelight灯具设备的“延时关灯”功能，进入详情页可以设置延时时间；
2、是没有右侧的箭头代表不能进入详情页，只能在当前页控制该功能的开关例如：“定时开关”功能

**Comment by DennisJu007** [comment]
大佬有空给排期加个箭头吧哈哈使用场景还是挺多的 @LiuMengzhou
