### ISSUE TITLE
线上正式程序在安卓上报lineNumber错误

### ISSUE THREAD

**Issue by chengshiyuan174** [MiEcosystem/miot-plugin-sdk#1024]
报错：com.facebook.react.bridge.NoSuchKeyException: lineNumber
但全局搜索代码，实际没有一处有用到lineNumber，谷歌了下解决方案说是升级到RN0.59.5自动解决。。但小米实际使用的是0.54，所以能给个解决方案么
![图片](https://user-images.githubusercontent.com/51961974/59694857-d6fa2200-921b-11e9-9bdf-d9dcd801b8f8.png)

**Comment by lvjie0519** [comment]
@chengshiyuan174   请使用最新apk （5.5.25.5版本)， 进行测试，谢谢。

**Comment by chengshiyuan174** [comment]
收集到崩溃信息的APP版本就是62878。。对应的是app好像就是5.5.25版本的线上版本，是否能确认造成这个崩溃率高是最近正式app版本的问题？？

**Comment by lvjie0519** [comment]
@chengshiyuan174    这个是RN库的问题，已经修复了，先使用fir上debug包进行测试，目前正式apk正在集测。
