### ISSUE TITLE
连接路由器的api是什么？文档没有找到

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1025]
看之前的小米插件，在通用设置页面有一个位置管理，位置管理页面有房间管理和连接路由器两个功能，我现在调用位置管理api，进去只有一个房间管理，请问连接路由器的api是什么呢？

**Comment by zanetti4** [comment]
请按照模版填写相应信息

**Comment by LZCaaT** [comment]
> 请按照模版填写相应信息

你好，请问一下，按照模板填写相应信息是什么意思，我现在的设置页面，就是根据com.xiaomi.demo里面的通用设置，调用了host.ui的api，有些api没有找到，比如重置设备和连接路由器，请大佬指点

**Comment by zanetti4** [comment]
提问题时输入框里不是有各项信息么，可以参看其他问题的格式，比如：https://github.com/MiEcosystem/miot-plugin-sdk/issues/1019

**Comment by zanetti4** [comment]
@blockdate 他说的这两个 api，你知道在哪里吗？

**Comment by blockdate** [comment]
1. 以前的位置管理，路由器只是显示，不支持修改。 参考 新API Device.readDeviceNetWorkInfo
2. 打开重置设备的UI，目前没有API支持。

如果有需求，按照issue模板提问，新开一个需求issue，该issue关闭
