### ISSUE TITLE
Wanted：从图片上获取某个像素点的RGB值的API

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1026]
**是否为新品（必填）**
在售

**关联的产品model**
yeelink.light.bslamp1
yeelink.light.bslamp2
yelling.light.bslamp3

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
我们原生实现是从图库或者拍照后获得一张图片，然后在图片上选择一个点，获取到这个像素点的RGB值

**期望（必填）**
提供一个图片上获取某个像素点RGB值的API
类似Android Bitmap.getPixel(x, y)
    /**
     * Returns the {@link Color} at the specified location. Throws an exception
     * if x or y are out of bounds (negative or >= to the width or height
     * respectively). The returned color is a non-premultiplied ARGB value.
     *
     * @param x    The x coordinate (0...width-1) of the pixel to return
     * @param y    The y coordinate (0...height-1) of the pixel to return
     * @return     The argb {@link Color} at the specified coordinate
     * @throws IllegalArgumentException if x, y exceed the bitmap's bounds
     */
    @ColorInt
    public int getPixel(int x, int y) {
        checkRecycled("Can't call getPixel() on a recycled bitmap");
        checkPixelAccess(x, y);
        return nativeGetPixel(mNativePtr, x, y);
    }

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
查看demo里面自带的第三方包

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
@DennisJu007 

你找找看，有没有第三方的图片库能实现这个功能。
