### ISSUE TITLE
spec获取属性值报错 

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#1027]
服务端返回数据
{code: -704090001, siid: 2, did: "107157802", piid: 1}
代码：
Service.spec.getPropertiesValue(specPropsArr)

**Comment by zanetti4** [comment]
请按照模版提供更多信息

**Comment by wanggoingdown** [comment]
@betterFuture 切换成preview环境试试

**Comment by santcool** [comment]
根据[文档](https://iot.mi.com/new/guide.html?file=07-%E4%BA%91%E5%AF%B9%E4%BA%91%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E5%BA%94%E7%94%A8%E4%BA%91%E5%AF%B9%E4%BA%91%E6%8E%A5%E5%85%A5/01-%E5%B0%8F%E7%B1%B3IOT%E6%8E%A7%E5%88%B6%E7%AB%AFAPI) 的 状态码部分的提示，此错误的原因是：did为107157802的设备不存在。
