### ISSUE TITLE
组件使用问题

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1028]
**是否为新品（必填）**
新品

**现象（必填）**
`<Card /> `这个组件，当有几个`<Card />` 按照纵向排列，之间的间距有默认值，请问怎么修改这个值

**期望（必填）**
`<Card /> `纵向排列，它们之间的纵向间距可以修改默认值

**Comment by zanetti4** [comment]
可以给 Card 组件添加 cardStyle 属性:
`<Card
              icon={Images.common.mihome}
              text="默认卡片有icon/文字/阴影/，没有圆角/右上角x"
              visible={this.state.visible1}
              dismiss={_ => this.setState({ visible1: false })}
              cardStyle={{ marginBottom: 50, }}
            />`
如果问题得到解决，请关闭此 issue

**Comment by devYoungyang** [comment]
算是解决了吧，marginBottom为负值才能达到我要的效果，估计还是因为Card纵向默认值的问题

**Comment by LiuMengzhou** [comment]
> 可以给 Card 组件添加 cardStyle 属性:
> 
> ```
> <Card
>   cardStyle={{ marginTop: 0 }}
> />
> ```
> 
> 如果问题得到解决，请关闭此 issue

@devYoungyang
