### ISSUE TITLE
git clone git@github.com:MiEcosystem/miot-plugin-sdk.git提示 Permission denied

### ISSUE THREAD

**Issue by badsdy** [MiEcosystem/miot-plugin-sdk#1029]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- Check 文档了吗？是
- 是否尝试搜索issue？是

---
**是否为新品（必填）**
填 新品

**关联的产品model**
miaomiaoce.sensor_ht.t2

**项目ID（必填）**

**企业名称（必填）**
秒秒测

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Windows
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
git clone git@github.com:MiEcosystem/miot-plugin-sdk.git提示 Permission denied。

 git clone git@github.com:MiEcosystem/miot-plugin-sdk.git
Cloning into 'miot-plugin-sdk'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**期望（必填）**
如何能clone这个项目

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
1.请检查是否正确添加 ssh 公钥到 github
2.当前电脑用户是否有足够的操作权限
