### ISSUE TITLE
缺少获取米家App设置-地区信息的接口

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#103]
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 12.1
- 相关模块:
- API或者常量: 
#### 现象

缺少获取地区信息的接口

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/11364809/49493278-8c741200-f896-11e8-80ed-3cf423c82e4f.png)

#### 尝试过的解决办法

旧的SDK中有接口MHPluginSDK.getCurrentCountryInfoCallback((success, countryInfo) => {})，新版SDK中Host模块有一个类似接口Host.locale.getCurrentCountry().then(country=>{})，但是描述信息太少不清楚是获取当前手机所在地区还是米家选择的地区，另外调用时报错截图如上

**Comment by LiuMengzhou** [comment]
@Handby 感谢你按照模板提出的这个issue
我们马上解决。

**Comment by LiuMengzhou** [comment]
下次记得加上label

**Comment by dingshaoran** [comment]
当前的国家是  中国，可以理解为系统定位返回的 address 信息

**Comment by LiuMengzhou** [comment]
@Handby 
> 旧的SDK中有接口MHPluginSDK.getCurrentCountryInfoCallback((success, countryInfo) => {})

新框架有两个接口获取地区信息:
1. `Service.getServerName` 获取APP当前选择的国家和服务器信息（对应于`MHPluginSDK.getCurrentCountryInfoCallback`）
2. `Host.locale.getLocation` 获取手机当前的定位信息。（国家-省市-区-街道）

以上两个接口的使用可参考 [Main/tutorial/LocalServer.js](https://github.com/MiEcosystem/miot-plugin-sdk/blob/096a9619021dd0179268d369ca8700a90daeab84/projects/com.xiaomi.demo/Main/tutorial/LocaleServer.js)
