### ISSUE TITLE
android提示设备已离线

### ISSUE THREAD

**Issue by huanghaibing** [MiEcosystem/miot-plugin-sdk#1030]
**现象（必填）**
Android手机进入插件时提示 “设备已离线”。但我这边已经连接蓝牙设备了，都可以收发信息。ios下是不会有此提示的。如图：
![image](https://user-images.githubusercontent.com/17466149/59739823-aa382000-9298-11e9-8882-7a33a7b1394d.png)

**期望（必填）**

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@huanghaibing 这米家首页  设备列表页面会显示设备离线吗？

**Comment by huanghaibing** [comment]
没有啊。就是第一次扫描添加设备完成之后，进入到插件页面就弹出这个框。

**Comment by lvjie0519** [comment]
@huanghaibing   
1、你打印下  device信息，看下isOnline的值？
2、回到设备列表首页，看下是否会显示设备离线？

**Comment by huanghaibing** [comment]
打印了isOnline的值为false，但是可以收发到设备上的数据。回到设备列表首页有刚刚添加的一个设备。没有显示设备离线

**Comment by huanghaibing** [comment]
就是第一次添加设备的时候会有设备离线弹出框。退出之后重新进插件就不会有弹框了

**Comment by ding209** [comment]
@lvjie0519 你好，我们的ble产品也遇到和这个一模一样的问题，不另开问题了

**Comment by ding209** [comment]
@lvjie0519 之前也遇到过类似的问题，从Android米家App右上角添加ble设备成功后，此时还未真正进入插件，等到进入插件中时获取到的Device.getBluetoothLE().isConnected以及Device. isOnline都是false，不过点击已添加的设备进入后这些状态都是正常的。这个离线提示弹窗应该也是这个原因引起的吧。
因为米家验收同学说插件提测必须解决这个问题，所以想问下这个问题的排期。

**Comment by lvjie0519** [comment]
@huanghaibing  @ding209    用最新apk测试下试试，我这边用一个蓝牙设备测试没发现问题。

**Comment by ding209** [comment]
@lvjie0519 用最新的米家正式版5.5.30 基本上稳定复现，用最新的米家debug版5.5.30.1 没有复现。

**Comment by ding209** [comment]
@lvjie0519 你好，在最新的正式版App5.5.30 上基本稳定复现，在最新的debug版本5.5.30.1 上也能出现，不过概率比较小，一直循环删除设备再添加设备，试个五六次我这肯定会出现。

**Comment by huanghaibing** [comment]
你好，我这边apk更新到的debug版本5.5.30.1 上还是会出现这个问题

**Comment by huanghaibing** [comment]
@lvjie0519 这个问题怎么解决呢。过几天要开始测试了，请帮忙看一下，谢谢！

**Comment by lvjie0519** [comment]
@huanghaibing  加微信（18750118631）， 详聊下。

**Comment by fishle** [comment]
米家最新版还有问题吗？你的设备pid是多少

**Comment by huanghaibing** [comment]
刚更新了版本，还是会这个问题。pid获取不到。Device信息里面没有这个字段

**Comment by fishle** [comment]
把设备分享到这个账号：894158105

**Comment by huanghaibing** [comment]
已经共享了，看下有没有。

**Comment by fishle** [comment]
收到了，看逻辑这里是根据系统返回的连接状态来判断是否弹框的

**Comment by huanghaibing** [comment]
那这个怎么改呢？

**Comment by fishle** [comment]
用这个安装包复现一下 https://pan.mioffice.cn:443/#/link/A5443A5E0669C235D9B56724F9C17663
然后根据 用OfflineViewDelegate这个tag过滤一下log，发给我

**Comment by fishle** [comment]
长时间未回复，先关单
