### ISSUE TITLE
法律信息中的“撤销授权”按钮Android和ios文案不一致

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1032]
**是否为新品（必填）**
在售

**关联的产品model**
xiaoxun.robot.v1

**企业名称（必填）**
上海小寻科技有限公司

**现象（必填）**
法律信息中的“撤销授权”按钮Android和ios文案不一致，Android端撤销授权按钮名称为“撤销用户协议和隐私政策授权”，ios为“撤销授权”

**期望（必填）**
文案一致

**Comment by zanetti4** [comment]
#1014
这个问题正在修复中……

**Comment by blockdate** [comment]
Duplicate of #1014
