### ISSUE TITLE
高斯模糊怎么使用

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1033]
**是否为新品（必填）**
新品 

**关联的产品model**

**现象（必填）**
看到`miot-sdk`内集成了`gl-react-blur`这个高斯模糊的库可以实现毛玻璃效果，不知道怎么使用

**期望（必填）**
给个使用方法的demo

**Comment by devYoungyang** [comment]
吴磊大佬呢

**Comment by blockdate** [comment]
这个直接参考官方实现就好 https://github.com/gre/gl-react-blur

**Comment by devYoungyang** [comment]
我知道参考官方的，`<Blur factor={0.5} passes={2}>
  http://i.imgur.com/zJIxPEo.jpg
</Blur>`报错

**Comment by blockdate** [comment]
什么错

**Comment by devYoungyang** [comment]
@blockdate `invariant violation:gl.node elements can only be used as children of gl.surface / fl.node and should not be renderd`

**Comment by devYoungyang** [comment]
render里这样写`<Blur factor={0.5} passes={2}> http://i.imgur.com/zJIxPEo.jpg </Blur>` 不行，官方的使用方法介绍太模糊了，
没有https://github.com/react-native-community/react-native-blur这个库清晰明了

**Comment by devYoungyang** [comment]
渲染这样里写<Blur factor={0.5} passes={2}> http://i.imgur.com/zJIxPEo.jpg </Blur>不行，官方的使用方法介绍太模糊了，
没有https://github.com/react-native-community/react-native-blur 这个库清晰明了

**Comment by devYoungyang** [comment]
渲染这样里写 `<Blur factor={0.5} passes={2}> http://i.imgur.com/zJIxPEo.jpg </Blur>` 不行，官方的使用方法介绍太模糊了，
没有https://github.com/react-native-community/react-native-blur 这个库清晰明了

**Comment by blockdate** [comment]
错误信息很明确。

`
<Surface ...set... >
<Blur factor={0.5} passes={2}>
http://i.imgur.com/zJIxPEo.jpg
</Blur>
</Surface>
`

**Comment by blockdate** [comment]
import { Surface } from "gl-react-native"

**Comment by devYoungyang** [comment]
大兄弟，这样写`<Surface width={200} height={200} >
                    <Blur factor={0.5} passes={2}>
                        http://i.imgur.com/zJIxPEo.jpg
                    </Blur>
                </Surface>` 同样的错误，麻烦您亲自试一下

**Comment by devYoungyang** [comment]
@blockdate 搞一下啊，等你呢

**Comment by devYoungyang** [comment]
@blockdate 。。。
