### ISSUE TITLE
调用蓝牙数据加密方法报错

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#1034]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼Q3智能锁/dsm.lock.r5

**环境（必填）**
- 电脑操作系统:  mac
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010
- 相关模块:  米家App

**现象（必填）**
调用以下方法
Device.getBluetoothLE().securityLock.encryptMessage(data).then(eData => {
                console.log('encryptData', 'success');
            }).catch(err => {
                console.log('sendData', '加密数据异常', err);
            });
收到加密数据异常的信息：
{code: -1, msg: "请求失败"}

调用该方法同时查看logcat控制台输出，显示：
2019-06-19 19:14:15.486 30682-31626/com.xiaomi.smarthome:core E/miio-bluetooth: E6:3A:06:E9:4F:ED sessionKey is null or invalid

但是同样的代码在dsm.lock.q3上测试没有问题

**期望（必填）**
在dsm.lock.r5上能正常调用蓝牙加密的方法

**Comment by zanetti4** [comment]
@dingshaoran 请协助查看此问题

**Comment by dingshaoran** [comment]
是不是调用 connect 成功了，成功才能使用其他 api。
前面的 log 给一下。

**Comment by dessmann** [comment]
今天测试正常了
