### ISSUE TITLE
用户授权及隐私协议不能解析html文件？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#1035]
**关联的产品model**
ls123.headphone.t10

**企业名称（必填）**
猎声电子

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android /iOS]
- SDK分支: [eg.master/10011/...]
- 相关模块:[eg.Host]

**现象（必填）**
请帮忙看看我两处使用的代码，是有什么问题吗？
在插件绑定后进入时弹出的授权及隐私协议显示的内容不是我设置的文件。
<img width="888" alt="屏幕快照 2019-06-19 下午11 52 26" src="https://user-images.githubusercontent.com/12670497/59780963-7a673780-92ed-11e9-80a0-80f2198e7629.png">

在通用设置页面中的授权及隐私协议显示的是html文件的源码。
<img width="926" alt="屏幕快照 2019-06-19 下午11 53 01" src="https://user-images.githubusercontent.com/12670497/59780984-83580900-92ed-11e9-8903-43dc908ab058.png">

**期望（必填）**
能够正常显示我的授权及隐私协议。

**其他的上下文/日志/截图**
![屏幕快照-2019-06-19-下午11 31 02](https://user-images.githubusercontent.com/12670497/59780756-12185600-92ed-11e9-9355-37d1241d8d3c.gif)
![屏幕快照-2019-06-19-下午11 31 02](https://user-images.githubusercontent.com/12670497/59780770-1775a080-92ed-11e9-952b-bbfd700d57f6.png)

**Comment by blockdate** [comment]
1. html资源引用使用require，不要直接使用string字串
2. 检查下html文件的编码格式，请与demo中的格式保持一致为UTF-8

**Comment by dgutkai** [comment]
![device-2019-06-20-152537](https://user-images.githubusercontent.com/12670497/59829478-25203a00-9370-11e9-8faf-2f734e7507df.png)

在Android上，用户协议和隐私政策上面那行字“某些功能仅限于部分国际和地区”没有显示，在IOS可以显示。

**Comment by lvjie0519** [comment]
@dgutkai  问题已知，属于APP的问题， 修复及时反馈，谢谢。
