### ISSUE TITLE
新RN框架添加白名单测试会影响到旧框架插件的白名单测试吗？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#1036]
**现象（必填）**
目前旧框架的插件还在白名单测试中，如果测试上传新RN框架的插件到米家平台进行白名单测试，此时是否会使所有的白名单测试都更新为新插件？影响测试人员的测试？

**Comment by blockdate** [comment]
默认都开启白名单会优先加载新插件。

如需测试旧插件，在开发者设置-> 更多设置 -> 强制加载Server旧插件 开启，就不会使用新插件了，用于旧插件调试。
