### ISSUE TITLE
iPhone6s plus部分系统无法打开米家插件

### ISSUE THREAD

**Issue by reflectWay** [MiEcosystem/miot-plugin-sdk#1038]
**环境（必填）**
- 手机系统:[iOS 12.3.1]
- 米家APP版本: [v.4.9.2]

**现象（必填）**
iPhone6s plus 系统为12.3.1下，无法打开米家插件
升级了最新版的米家APP可以了

**期望（必填）**
无法打开米家插件，请给用户一个详细的提示

**其他的上下文/日志/截图**
![45878ab3-c077-4cb3-afa5-20c58a194ded](https://user-images.githubusercontent.com/17630706/59891790-19cd1d00-9409-11e9-9400-aba3cd781f78.jpg)

**尝试过的解决办法**
换蓝牙设备还是不行，搜索issue没有发现相同问题

**Comment by santcool** [comment]
打不开因为米家太老了，升级了可以打开，这有什么问题呢？

**Comment by zanetti4** [comment]
@santcool 他可能是想要一句提示语“请升级米家APP”之类的

**Comment by santcool** [comment]
@zanetti4  新的app是有更多提示的，他这个版本实在是太老了
