### ISSUE TITLE
相机权限

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1039]
希望增加相机使用权限管理，已授权、未授权

**Comment by zanetti4** [comment]
com.xiaomi.demo/Main/ThirdPartDemo/ReactNativeCameraDemo.js
SDK_10021分支，这个演示文件能否满足你的需求？

**Comment by YunzzzZ** [comment]
SDK10021、米家app最新
 小米note3，打开相机，点击询问弹框的拒绝按钮
try {
				const granted = await PermissionsAndroid.request(
					PermissionsAndroid.PERMISSIONS.CAMERA,
				);
				if (granted === PermissionsAndroid.RESULTS.GRANTED) {
					console.warn('现在你获得摄像头权限了');
					this.setState({
						haveAuthor: true
					})
				} else {
	#####没有走这里！！！其他手机正常
					this.props.navigation.goBack()
					console.warn('未获得权限);
				}
			} catch (err) {
				console.warn(err);
			}

@zanetti4

**Comment by zanetti4** [comment]
现在点击拒绝后走的哪里的代码？没有打出任何信息吗？

**Comment by YunzzzZ** [comment]
无论点击拒绝还是允许，三个地方的打印都没走，目前仅发现小米note3有这个问题

**Comment by fishle** [comment]
request没有反应，有没有试过check呢，有结果吗？

**Comment by YunzzzZ** [comment]
check有结果；但只有request才能出现询问弹框

**Comment by fishle** [comment]
> 无论点击拒绝还是允许，三个地方的打印都没走，目前仅发现小米note3有这个问题

意思会弹窗，但是没回调结果吗？

**Comment by fishle** [comment]
你的Android系统版本是多少，Android 6.0以下是默认授权的

**Comment by YunzzzZ** [comment]
更新米家APP和系统解决问题了，多谢
