### ISSUE TITLE
调用callMethod报错

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#104]
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统: [Windows/Mac OS/Linux]
- 手机系统: [Android 8.1/iOS 11.0]
- 相关模块: [Host/Service/Account]
- API或者常量: [readFile/isDebug]

#### 现象

新的RN框架，调用callMethod报错。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。
![wechatimg2025](https://user-images.githubusercontent.com/17919773/49493682-f17c3780-f897-11e8-9898-55bada9e914f.jpeg)

#### 尝试过的解决办法

尝试过哪些操作？

### ‼️‼️‼️
1. 不要贴大段代码！！！
2. 记得根据issue加上label label label！！！（加上label，有助于我们定位问题，相关负责人方便认领）

**Comment by dingshaoran** [comment]
超时了，和java 插件一样，过滤 log 你的methord，看一下

**Comment by dingshaoran** [comment]
如果是不是必现，可以认为是网络不好

**Comment by sikaiven** [comment]
> 如果是不是必现，可以认为是网络不好

是必现的，老的框架调用MHPluginSDK.callMethod是没问题的，现在我将代码迁移到新的RN框架，调用Device.callMethod就报这个错误，在新框架下我也试了调用MHPluginSDK.callMethod，也是报同样的错。

**Comment by LiuMengzhou** [comment]
@sikaiven 经过测试并没有发现问题，其他开发者也没有提出类似issue。
请check你的用法/网络/以及固件接口是否存在且传参无误。

**Comment by dingshaoran** [comment]
如果是 android 系统的报错请过滤 logcat     core D/MIIO  贴出来看看具体报错

**Comment by dingshaoran** [comment]
黄色警告是没有处理 catch(error=>console.log(error))，您付截图的报错信息不是我们需要的可以定位问题的 log。请使用 logcat 导出 apk 的 log 和 rn 的 log

**Comment by sikaiven** [comment]
> 黄色警告是没有处理 catch(error=>console.log(error))，您付截图的报错信息不是我们需要的可以定位问题的 log。请使用 logcat 导出 apk 的 log 和 rn 的 log


![wechatimg151](https://user-images.githubusercontent.com/17919773/49715066-3c2bf400-fc8a-11e8-803c-8d078d5b56f4.jpeg)

这是iOS手机上，rn报的错，和上面一样。logcat没用过，如果需要用它导出Android手机上的log，我还要研究下。

Device.getDeviceWifi().callMethod(method, JSON.stringify([info])).then((res) => {
      
    }).catch((error)=>{
        console.error(error);
    });

调用的接口如上，不管是调用callMethod，还是callMethodFromCloud，还是loadProperties，都是报同样的错误。

但是我通过Device. deviceID或者Device. isOnline，获取设备的属性，是正常的。

**这个问题我是迁移到新的RN框架才遇到的，在之前iOS和Android分开的老的RN框架上，是正常的。**

**Comment by Aub1nLin** [comment]
我和你一模一样，动不动就报错。但是偶尔设备是有响应的。

**Comment by Aub1nLin** [comment]
@LiuMengzhou 我手机用4G也会出现，你说的网络不好，是指设备还是手机？

**Comment by laohuang88** [comment]
调用方式错误， 不要JSON.stringify([info]) ..., 参数是什么json， 就传什么json的object，不要转换成string
Device.getDeviceWifi().callMethod(method, {v1:...,v2...}).then(...)

**Comment by sikaiven** [comment]
> 调用方式错误， 不要JSON.stringify([info]) ..., 参数是什么json， 就传什么json的object，不要转换成string
> Device.getDeviceWifi().callMethod(method, {v1:...,v2...}).then(...)

还是报一样的错

**Comment by LiuMengzhou** [comment]
Duplicate of #147

**Comment by sikaiven** [comment]
![wechatimg2070](https://user-images.githubusercontent.com/17919773/50411258-8c35b980-0839-11e9-91c9-879d0bff29c4.jpeg)
目前我已更新到最新的ipa，仍然报这个错，但是调用Device.model,Device.deviceID获取属性，是正常的。

**Comment by LiuMengzhou** [comment]
关于`callMethod`的新旧框架差异性问题，这里总结一下。

##### 老框架下使用方法：

```js
// 文档说明
MHPluginSDK.callMethod(method, params, extraInfo, (res, json) => {});

// 只有params的example
MHPluginSDK.callMethod("get_config_version", ["audio"], {}, (res, json) => {});

// 只有extraInfo的example
var params = { "operation": "query", "req_type": "alarm", "index": 0 };
MHPluginSDK.callMethod("alarm_ops", [], { "params": params }, (res, json) => {});
// 由于历史原因，extraInfo必须是params为key的json，里面包含真正的payload数据。
```

##### 新框架下使用方法：

```js
// 文档说明
Device.getDeviceWifi()
  .callMethod(method, params) // 新框架将params和extraInfo整合为一个参数
  .then(res => {//here is the success result})
  .catch(err => {//error happened})
    
// 相应的新写法
Device.getDeviceWifi()
  .callMethod("get_config_version", ["audio"])
  .then(json => {})
  .catch(res => {})

let params = { "operation": "query", "req_type": "alarm", "index": 0 };
Device.getDeviceWifi()
  .callMethod("alarm_ops", params) // 这里是主要变化，直接传入真正的payload
  .then(json => {})
  .catch(res => {})
```

##### callMethod方法的保护：

为了防止频繁调用rpc指令给服务器造成压力，`callMethod`底层做了保护机制。对于相同接口两次调用时间interval最好超过**1500ms**，不然大概率报错。附上实验测试结果（未进行大量实验）仅供参考。表格内容表示报错比率。

| interval（ms）                    | 250     | 500     | 1000   | 2000   | 5000  |
| --------------------------------- | ------- | ------- | ------ | ------ | ----- |
| `MHPluginSDK.callMethod`          | 406/540 | 202/400 | 55/457 | 16/300 | 0/100 |
| `Device.getDeviceWifi.callMethod` | 409/540 | 255/500 | 24/441 | 4/300  | 2/100 |

**interval < 2000**，大概率报错：`callMethod failedError Domain=MiHomeNetworkErrorLocal Code=-12 "(null)"`，请尽量避免。

**interval >= 2000**，极小概率报错：`callMethod failedError … error={↵    code = "-3";↵    message = timeout;↵}}"`，属于正常现象。

**Comment by LiuMengzhou** [comment]
@sikaiven @Aub1nLin 我这边测试已经没有问题了。你们还有问题的话，请及时反馈，并附上详细上下文和使用该方法的代码。

**Comment by Braveleon** [comment]
Device.getDeviceWifi().callMethod("get_prop", JSON.stringify(["run_status", "work_status", "mode"])).then((res) => {
			alert(res);
		  });
![image](https://user-images.githubusercontent.com/18184778/50632504-117c4500-0f83-11e9-9e5b-64336be882a5.png)
按照demo的示例获取属性为什么会出现这样的错误？(用不用JSON.stringify进行序列化都一样）

**Comment by reflectWay** [comment]
@LiuMengzhou 你好，我也遇到了callMethod，报-12的错误；看了你的总结，现在只能通过控制interval来避免这个问题吗
