### ISSUE TITLE
IOS米家添加设备报错无法添加

### ISSUE THREAD

**Issue by shudaonan** [MiEcosystem/miot-plugin-sdk#1040]
**是否为新品（必填）**
 在售

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
上海榉树智能有限公司

**环境（必填）**

- 手机:[iPhone6]系统:[iOS 12.3.1]米家APP:[V4.17.2]
- 手机:[iPhone6S]系统:[iOS 12.3.1]米家APP:[V4.18.2]

**现象（必填）**
1、iphone6在使用旧的插件页旧的固件添加设备时报code=2的错误，新的固件添加成功
2、iphone6S在使用新的插件页旧的固件添加成功，新的固件添加设备时报code=2的错误，添加成功后的旧版本使用米家升级新的固件出现蓝牙一直无法连接的现象
3、以上两个设备在退出后台重新打开APP后都无法解决，但重启手机后问题就会得到解决
4、安卓手机无此问题

**期望（必填）**
联调

**其他的上下文/日志/截图**
![5](https://user-images.githubusercontent.com/17584058/59896225-4b9aaf80-941a-11e9-875a-005bc0e4b212.jpg)
![1](https://user-images.githubusercontent.com/17584058/59896232-535a5400-941a-11e9-8d70-c5c03b8c1414.jpg)

**Comment by pencilCool** [comment]
这个是广播包出了问题。小米这边固件开发这已经配合修复这个问题了吧？
和这个问题是类似的：
https://github.com/MiEcosystem/miot-plugin-sdk/issues/892
