### ISSUE TITLE
华为手机绑定设备时，报错：扩展程序初始化失败

### ISSUE THREAD

**Issue by wenlai** [MiEcosystem/miot-plugin-sdk#1041]
---
**是否为新品（必填）**
新品

**关联的产品model**
hith.foot_bath.q2

**项目ID（必填）**
HITH智能足浴机器人Q2

**企业名称（必填）**
智米科技有限公司

**环境（必填）**
- 电脑操作系统:[]
- 手机系统:[Android 8.0/Android 8.0]
- SDK分支: [10011]
- 相关模块:[]

**现象（必填）**
华为品牌手机配设备，配网最后一步都失败，报错：
扩展程序初始化失败
手机网关异常，请检查手机网络连接后重试，

其实设备已经成功加入到家庭里面的，在米家tab能看到设备，但点击设备卡片，也报”扩展程序初始化失败“

**期望（必填）**
华为手机成功配网，正常控制

**其他的上下文/日志/截图**
![WechatIMG6](https://user-images.githubusercontent.com/7650650/59905750-98da4980-9439-11e9-88a0-4c274ca6af80.jpeg)

**尝试过的解决办法**

尝试过不同华为手机都是一样报错，其他小米，vivo,oppo, iphone手机都是正常的
华为P30 pro （Android 9.0）
华为MATE 10pro （Android 9.0）
华为荣耀V9（Android 9.0）
华为M5（Android 8.0）

）
--

**Comment by cfJand** [comment]
@wenlai  建议提供具体的报错日志。

**Comment by cfJand** [comment]
通过分析，是因为华为手机上下载Plugin失败，具体失败的原因，需要分析日志。

**Comment by cfJand** [comment]
长时间未回复，此issue暂时关闭。
