### ISSUE TITLE
Host.ui.checkStoreSupporttedOnAndroid() 返回错误

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#1043]
---
**是否为新品（必填）**
在售

**关联的产品model**
soocare.toothbrush.m1

**项目ID（必填）**
15366

**企业名称（必填）**
舒可士（深圳）科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: 10012
- 相关模块:Host

**现象（必填）**
切换到不支持商店的地区(米家没有商店Tar)，Host.ui.checkStoreSupporttedOnAndroid()还是返回YES

**期望（必填）**
返回正确值

**Comment by zanetti4** [comment]
请问你切换到的是哪个地区？

**Comment by JxXiaoXie** [comment]
俄罗斯

**Comment by huangjr126** [comment]
@zanetti4 您好，想问下这个问题有进展了吗？

**Comment by zanetti4** [comment]
@lvjie0519 我把米家 app 切换到俄罗斯，登录之后开发者模式不见了，设备列表也变了，无法测试。请你协助查看

**Comment by lvjie0519** [comment]
@JxXiaoXie   
1、你们怎么知道有checkStoreSupporttedOnAndroid方法的？我这边应该隐藏了哈，这个方法废弃了，请使用Host.ui.canOpenStorePage 这个方法；
2、canOpenStorePage 已修复，请使用最新apk进行测试

**Comment by lvjie0519** [comment]
@zanetti4   
1、切换到俄罗斯，该服务器环境下，当前账号不属于开发者账号导致开发者模式无法显示，需要找服务端开发人员；
2、由于服务环境都变了，设备列表页发生对应变化，这是正常的。

**Comment by zanetti4** [comment]
明白了，谢谢！
