### ISSUE TITLE
Android端智能跳转异常

### ISSUE THREAD

**Issue by mny459** [MiEcosystem/miot-plugin-sdk#1044]
**是否为新品（必填）**
在售

**关联的产品model**
M1智能锁/yunshi.lock.s2

**项目ID（必填）**
无项目ID

**企业名称（必填）**
陨石科技

**环境（必填）**
- 电脑操作系统:
- 手机系统:
- SDK分支: 
- 相关模块:

**现象（必填）**
前置条件：新建智能界面；
复现步骤：
  1、“如果”条件选择夏洛克“门锁“ 2、“开锁（所有人）或关锁（所有人）”；
实际结果：界面会跳转到“开锁（指定用户）”；
预期结果：“如果”条件正常设置成“开锁（所有人）或关锁（所有人）”，不会切换到“开锁（指定用户）”；
概率：Android端出现概率 5/5；iOS没有这个问题

**期望（必填）**
按照指定逻辑正常跳转

**其他的上下文/日志/截图**

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@mny459  没有太明白您的描述，请加微信（18750118631）详聊下。

**Comment by lvjie0519** [comment]
@mny459  
1、线下沟通，如果对于不需要跳转到插件的场景，无需在project.json中配置对应的id；
2、如果测试通过，没问题请关闭issue。
