### ISSUE TITLE
适配版本

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1045]
目前对安卓、iOS支持的最低版本是多少，有的低端安卓机型卡顿非常严重

**Comment by zanetti4** [comment]
你是指米家 app 吗？

**Comment by YunzzzZ** [comment]
进入插件非常卡，米家app也不是很流畅，仅对于低端安卓机，是否对安卓最低系统有性能要求

**Comment by zanetti4** [comment]
请按照模版填写更多详细信息，谢谢

**Comment by santcool** [comment]
暂时还支持iOS9，不过将要不支持了，你可以认为只支持iOS10及其以上

**Comment by YunzzzZ** [comment]
对于安卓呢

**Comment by lvjie0519** [comment]
Android  支持是在 Android4.4及以上，低端安卓机型卡顿，这个与手机性能也有关系。
