### ISSUE TITLE
新版的NavigationBar建议

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1046]
**是否为新品（必填）**
新品 
**企业名称（必填）**
飞彗智能照明

**现象（必填）**
NavigationBar的右侧按钮增加一个属性可以控制按钮显示或隐藏

**期望（必填）**
NavigationBar的right右侧按钮增加一个属性可以控制按钮显示或隐藏，
另外title和subtitle可以自定义样式

**Comment by LiuMengzhou** [comment]
详细说说

**Comment by devYoungyang** [comment]
1. NavigationBar的title和subtitle的文字可以自定义样式，因为有时候我们需要改变文字的大小和使用什么字体
2.NavigationBar右侧的按钮通过一个属性可以控制其是否显示，比如右侧有一个收藏的按钮，我需要在开灯的时候显示，关灯的时候隐藏，这样才合理

**Comment by devYoungyang** [comment]
@LiuMengzhou 还有什么不清楚的嘛
