### ISSUE TITLE
分享微博时，无法显示自定义文案

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#1047]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
非新产品

产品名称/Model（必填）
米家声波电动牙刷M1
soocare.toothbrush.m1

环境（必填）
手机系统:【Android 8.0、9.0】

现象（必填）
Host.ui.openShareListBar("", "自定义的分享文案", { uri: result }, null); 
这行代码设置了分享文案，Android分享不显示
![image](https://user-images.githubusercontent.com/48087638/59998162-51e69100-9691-11e9-9ad0-bd6995e733fc.png)

期望（必填）
可以正常显示自定义分享文案

**Comment by lvjie0519** [comment]
@huangjr126   已经发现问题，属于APP层的问题，我这边反馈到APP相关开发人员，有反馈会及时在这里更新，谢谢。

**Comment by huangjr126** [comment]
@lvjie0519 好的，辛苦了，谢谢

**Comment by huangjr126** [comment]
IOS的分享文案有误，开头多了两个#号，麻烦帮忙去除，谢谢。

**Comment by santcool** [comment]
ios的没问题。请参照demo，自行验证。我这边效果如下图：
![601563869645_ pic](https://user-images.githubusercontent.com/8580061/61694905-080eca80-ad65-11e9-8c09-66313b1d0bb3.jpg)
![611563869660_ pic](https://user-images.githubusercontent.com/8580061/61694906-080eca80-ad65-11e9-9cda-889905893d4a.jpg)

**Comment by lvjie0519** [comment]
@huangjr126  Android已修复， 请使用最新apk验证，谢谢。
