### ISSUE TITLE
`gl-react-blur`如何使用

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1048]
**是否为新品（必填）**新品

**企业名称（必填）**
飞利浦照明

**现象（必填）**
`<Surface ...set... >
<Blur factor={0.5} passes={2}>http://i.imgur.com/zJIxPEo.jpg</Blur>
</Surface>`
这样写仍然报错

**期望（必填）**
提供一个使用`gl-react-blur`库的demo

**尝试过的解决办法**
按照官方文档写`<Blur factor={0.5} passes={2}> http://i.imgur.com/zJIxPEo.jpg </Blur>`
报错

**Comment by santcool** [comment]
请提供报错的错误信息

**Comment by devYoungyang** [comment]
`invariant violation:gl.node elements can only be used as children of gl.surface / fl.node and should not be renderd`
吴磊看过，但他没有解决

**Comment by zanetti4** [comment]
我在网上搜到[一篇帖子](https://github.com/gre/gl-react/issues/185)，看看对你有用吗？

**Comment by devYoungyang** [comment]
并没有什么用处，你们在miot-sdk内置了`gl-react-blur`,你们难道不会用嘛？
这个[高斯模糊]('https://github.com/react-native-community/react-native-blur')库比较好用,建议内置这个

**Comment by devYoungyang** [comment]
https://github.com/react-native-community/react-native-blur

**Comment by devYoungyang** [comment]
请你们尽快解决这个问题，项目赶的紧。谢谢

**Comment by zanetti4** [comment]
@Woody2016 devYoungyang 提到的这个库是否可以内置？

**Comment by devYoungyang** [comment]
@Woody2016 劳烦兄弟把react-native-blur内置到miot-sdk中，这个库有人维护，简单易用。你们以前内置的高斯模糊的库gl-react-blur可以移除了，好久没有更新，也很少人用。谢谢，请尽快弄一下

**Comment by devYoungyang** [comment]
@Woody2016 劳烦兄弟把反应天然模糊内置到miot-SDK中，这个库有人维护，简单易用。你们以前内置的高斯模糊的库GL-反应模糊可以移除了，好久没有更新，也很少人用。谢谢，请尽快弄一下

**Comment by devYoungyang** [comment]
你们弄不弄给个信啊？我们好找其他的解决方案那

**Comment by devYoungyang** [comment]
@zanetti4

**Comment by zanetti4** [comment]
react-native-blur 将在下周内置到 miot-SDK 中

**Comment by devYoungyang** [comment]
@zanetti4 内置到miot-SDK完成后通知一声

**Comment by zanetti4** [comment]
正在进行内置，能够使用后会在这里回复的。

**Comment by devYoungyang** [comment]
这个有什么进展了嘛

**Comment by lvjie0519** [comment]
@devYoungyang   已经接入了，  请使用最新apk进行测试。

**Comment by devYoungyang** [comment]
为什么我在1022分支使用BlurView报`Invariant Violation:Native component for ‘blurview’ does not exist`
错误？  @lvjie0519  @zanetti4
