### ISSUE TITLE
关于安卓适配中ScrollView属性无用的问题

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#1049]
---
**是否为新品（必填）**
 在售

**关联的产品model**
17216.massage.ec1266a

**项目ID（必填）**
乐班电动智能升降台

**企业名称（必填）**
乐范健康有线公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: [eg.master/10020/...]

**现象（必填）**
ScrollView在苹果上可以正常使用，但是在安卓关于偏移量的属性无用，比如contentInset这个属性无法起到作用

**期望（必填）**
可以在安卓上正常使用，让滚轮的偏移量有效。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43639032/60032966-3ce22000-96da-11e9-8811-7f66a3fb0fd4.png)
![image](https://user-images.githubusercontent.com/43639032/60033004-4e2b2c80-96da-11e9-951e-aae3b2a61429.png)此为在安卓上  无法滚动到顶
![image](https://user-images.githubusercontent.com/43639032/60033035-600ccf80-96da-11e9-845c-b82a2a11f73e.png)此为在苹果上  滚动正常

**尝试过的解决办法**
试过所有属性

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
contentInset 是 ios 平台支持的属性，你有没有试过用 paddingTop 样式代替？

**Comment by 1076815296** [comment]
> contentInset是ios平台支持的属性，你有没有试过用paddingTop样式代替？

那请问下contentOffset要用什么样式代替   还有我的条，向下拖可以拖到顶部  可是向下拖，拖到这里就动不了  这个该用什么样式来设置？
![581561452474_ pic](https://user-images.githubusercontent.com/43639032/60083828-fee00d00-9768-11e9-9560-91f79b715c16.jpg)
![591561452475_ pic](https://user-images.githubusercontent.com/43639032/60083833-02739400-9769-11e9-9a28-ba23762150ad.jpg)

**Comment by zanetti4** [comment]
contentOffset 可以用 [scrollTo()](https://reactnative.cn/docs/scrollview/#scrollto) 方法代替。
你说的是给那个红色的尺子变成绿色吗？

**Comment by 1076815296** [comment]
> contentOffset可以用[scrollTo（）](https://reactnative.cn/docs/scrollview/#scrollto)方法代替。
> 你说的是给那个红色的尺子变成绿色吗？
红色的尺子是移动条  绿色是背景

**Comment by 1076815296** [comment]
红色的尺子是移动条 绿色是背景   移动条无法移动到底部

**Comment by zanetti4** [comment]
![标尺示意图](https://user-images.githubusercontent.com/12883959/60163971-49c45800-982f-11e9-9253-82540569aa30.jpg)
最后你说的这个问题，可能是因为我让你用 paddingTop 代替 contentInset 导致的。要实现你想要效果，我觉得不用 contentInset 就可以。如上图，scrollView 高度60，红色的尺子刻度140--200，尺子上下各添加绿色的色块，高度为 scrollView 的一半30，为了中间的箭头能够指向尺子的最大、最小值。你能明白我的意思吗？

**Comment by 1076815296** [comment]
那你这个绿色色块 是添加到scrollView的里面 还是在scrollView的外面

**Comment by zanetti4** [comment]
在 scrollView 的里面

**Comment by 1076815296** [comment]
老师 问您个问题
![image](https://user-images.githubusercontent.com/43639032/60277991-38637480-9931-11e9-9ab1-de486697679f.png)
当这个code=100的时候 我应该执行什么操作比较好

**Comment by zanetti4** [comment]
这个和 ScrollView 已经无关了，请提一个新的 issue 吧。
