### ISSUE TITLE
 长截屏、分享错误

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#105]
### SDK 最新

---

#### 环境
- 电脑操作系统: [Mac OS]
- 手机系统: [iOS 9、12]
- 相关模块: [Host]

#### 现象

- 1、Host.file.longScreenShot截ScrollView，普通View/Text这些可以截图，但是

 通过 `gl-react-native` 绘制的视图一片空白(黄色区域)（在旧插件SDK上是正常使用的）
![sss](https://user-images.githubusercontent.com/2043635/49496953-242b2d80-f8a2-11e8-8d15-14ada13ef6a7.png)

- 2、Host.file.longScreenShot

 截取的对象只能是ScrollView？尝试去截取scrollview内部的一个"总视图"直接报错 undefined

- 3、Host.file.longScreenShot截图后，scrollview上的容器View消失了。。。。scrollView本身还在

- 4、使用返回的imagePath，直接调用分享代码：

`Host.ui.openShareListBar('title', 'des', uri, null)`
![screen shot 2018-12-05 at 3 30 28 pm](https://user-images.githubusercontent.com/2043635/49497345-25a92580-f8a3-11e8-9dfa-71a40e7aae12.png)
 如按照DEMO代码：
`Host.ui.openShareListBar('title', 'des', require('../Resources/vc_run.png'), null)`
则直接插件报错：
![screen shot 2018-12-05 at 3 34 47 pm](https://user-images.githubusercontent.com/2043635/49497416-59844b00-f8a3-11e8-9d01-4faed235950e.png)

**Comment by LiuMengzhou** [comment]
1. 通过gl-react-native绘制的视图一片空白(黄色区域)（在旧插件SDK上是正常使用的）
----------------------
`longScreenShot`没有改动，如果老框架可以用，新框架不能，考虑`gl-react-native`或者其他问题。

2. Host.file.longScreenShot
截取的对象只能是ScrollView？尝试去截取scrollview内部的一个"总视图"直接报错 undefined
----------------------
对，原生端会判断是否是`ScrollView`，请传入`ScrollView`的`ref`

3. 原因不明，请进一步提供更多细节。

4. `openShareListBar`报错问题已经修复。
你打印一下图片地址`imagePath`，如果是本地绝对路径，使用方法如下：
`Host.ui.openShareListBar('title', 'des',{uri: imagePath}, null)`

**Comment by edwardair** [comment]
**SDK已更新，ipa 12.05号**

- Host.ui.openShareListBar('title', 'des', {uri:uri}, null);
  是本地绝对路径，按照这样写，会报  NSMutableDictionary无法转为NSArray
- 同时再测试了下  Host.ui.openShareListBar('title', 'des', require('../Resources/vc_run.png'), null)，仍然报错，NSString无法转为NSArray

**Comment by LiuMengzhou** [comment]
@edwardair 找到问题，正在解决中，等待新的ipa

**Comment by edwardair** [comment]
请问  `Host.file.longScreenShot` 与 `Host.file.screenShot` 截图的机制、代码是否类似？
测试 `Host.file.screenShot`  可以正常截图（gl-react-native绘制的能够正常截取到）
而 `Host.file.longScreenShot` 就无法正常截取gl-react-native绘制的部分

**猜想**： longScreenShot 只要截图过，Scrollview上的容器View就会莫名消失，不知道是不是因为这个消失时机导致的gl-react-native绘制的部分无法截图（测试：在截图过一次，容器View消失后，再截图一次，其实还是能正常截图，表示对象并未释放，就是View看不到了）

麻烦你们测试下  Host.file.longScreenShot  是否会导致容器View消失 @LiuMengzhou

**Comment by edwardair** [comment]
android上长截图，容器View不会消失，但是gl-react-native绘制的部分也是无法截取

**Comment by LiuMengzhou** [comment]
@edwardair  好的，我们测试一下这个问题。
方便调试，希望你能提供一下ScrollView这部分的简要代码。

不过这个问题应该需要耗费有点时间，请耐心等待。

**Comment by dingshaoran** [comment]
看了一下 gl-react-native 的实现  用了 GLSurfaceView，截图的逻辑是 new Canvas(bitmap); scrollView.draw(canvas); 暂时没有办法实现您说的需求 ，您看一下 svg lottie image 加载 gif 能不能满足您的需求
截图之后使用 {uri:'file://' imagePath}加载您的图片，

**Comment by edwardair** [comment]
截图：
`                    Host.ui.openShareListBar('title', 'des', {uri:'file://'+uri}, null);`
这样子用后，报错：Can't find variable: newUrl

请问是否需要更新ipa？ 12.05号的版本

**Comment by edwardair** [comment]
确认下，Image支持加载GIF的吧？我测试android可以正常加载gif

**Comment by dingshaoran** [comment]
android 可以加载 gif

**Comment by edwardair** [comment]
1、ScrollView截屏导致View不再绘制的问题是否解决？
2、Host.ui.openShareListBar分享报错
@LiuMengzhou

**Comment by LiuMengzhou** [comment]
> 1、ScrollView截屏导致View不再绘制的问题是否解决？
> 2、Host.ui.openShareListBar分享报错
> @LiuMengzhou

1. 暂时还没
2. 下载最新ipa（DB编号 30）

**Comment by edwardair** [comment]
最新ipa（DB编号 30）插件闪退，SDK已更新最新：
![screen shot 2018-12-12 at 1 59 56 pm](https://user-images.githubusercontent.com/2043635/49849844-45e26280-fe16-11e8-8d9b-7c3e71f703b4.png)

**Comment by laohuang88** [comment]
截图后应该使用这样的方式引用图片 {local:"mypicture"}

**Comment by laohuang88** [comment]
正确的用法是{local:"filenameonly.ext"}, 现在{uri:absoluteFilePath}能够起效是因为还没有对文件访问权限做严格限制，目前还只是不鼓励这么用。

**Comment by laohuang88** [comment]
const filename="myfile.png";
Host.shotScreen(filename).then(ok=>{
   const myimg = <Image source={{local:filename}}/>
   ...
})

**Comment by edwardair** [comment]
求长截屏导致View不再绘制的问题解决进度？预计什么时候能修复？实在不能修复，我们需要提前修改截屏方案，谢谢  @LiuMengzhou @dingshaoran

**Comment by edwardair** [comment]
@LiuMengzhou @dingshaoran @kyou 请问目前问题解决进度怎样？

**Comment by edwardair** [comment]
分享最新测试：
```
                        Host.ui.openShareListBar('小米智能家庭', '小米智能家庭', {local: "temp.png"}, null)
                            .then(result => this.setState({loading: false})).catch(err => this.setState({loading: false}));
```

问题：
1. 弹出的分享界面，没有预览图
1. 有个Alert错误信息弹出：Cannot read property 'then' of undefined

**Comment by edwardair** [comment]
@kyou 请问这个问题目前有进度么？

**Comment by blockdate** [comment]
已处理，更新下ipa。

**Comment by edwardair** [comment]
frame没问题了，但是这个右上角是什么问题？
![1](https://user-images.githubusercontent.com/2043635/51646310-03827880-1fb3-11e9-8aab-7f13c62097be.png)
上一版本没有这块黑色区域（注：圆圈是用ART绘制的）

**Comment by blockdate** [comment]
应该是scrollview的opaque属性导致的，更新APP，目前强制使用opaque=false进行截图，应该不会出现黑色背景了

**Comment by edwardair** [comment]
问题还是存在，容器view增加了背景色后就看不出这个斜角了，问题算是解决了，谢谢

**Comment by edwardair** [comment]
安卓端的长截屏仍存在问题（iOS端目前可以了）
![screenshot_2019-02-11-14-54-58-761_com xiaomi sma](https://user-images.githubusercontent.com/2043635/52549308-78f0a480-2e0d-11e9-9bfb-711405c3eec8.png)
如图，底部一条黑色区域
@blockdate

**Comment by blockdate** [comment]
@lvjie0519 确认下Android目前的问题是否还存在

**Comment by lvjie0519** [comment]
Android已经修复，请使用最新apk测试。
https://fir.im/MiHomeForAndroid
