### ISSUE TITLE
定时功能需求

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#1050]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
填 新品 or 在售
新品

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
qianqu.mosq.wx001

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID

**企业名称（必填）**
贵司的名称
东莞市纤趣电子科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS/Linux]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master/10021/...]
- 相关模块:[Scenes，UI]

**现象（必填）**
简单明了地描述一下实际的现象。

在我的产品上，有三个断电器（A，B，C），分别用来控制不同的开关。我想分别为不同的断电器开关，进行单独的定时功能设置和定时列表展示。
当我尝试用： Host.ui.openTimerSettingPageWithVariousTypeParams，Service.scene.loadScenes(Device.deviceID, SceneType.Timer) 这两个接口去设置和获取A继电器设置的定时信息时，我发现B，C两个继电器设置的信息也被展示出来了。

 例：
![image](https://user-images.githubusercontent.com/5464058/60065093-a1829680-973d-11e9-9218-09eb02b48c9f.png)
当我点击A的定时时，在定时列表当中（B和C）的内容同样被展示出来。
![image](https://user-images.githubusercontent.com/5464058/60065152-d1319e80-973d-11e9-9800-495eb1b9a60b.png)

**期望（必填）**
简单明了地描述一下期望的表现。
能对三个继电器分开设置和展示定时。
如果已经有，请告知使用哪个接口
如果没有，请进行添加。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@param {*} opt {identify,name} 同上面的identify，name
loadScenes(deviceID, sceneType, opt = null)
第三个参数能填入场景类别和名称，你有没有试过？

**Comment by fgb031102** [comment]
> @param {*} opt {identify,name} 同上面的identify，name
> loadScenes(deviceID, sceneType, opt = null)
> 第三个参数能填入场景类别和名称，你有没有试过？

你好！谢谢指导，我试一下。

**Comment by zanetti4** [comment]
OK，如果问题得到解决，请关闭此 issue。

**Comment by fgb031102** [comment]
> OK，如果问题得到解决，请关闭此 issue。

你好！我详细的阅读了一下文档内容。

loadScenes(deviceID, sceneType, opt = null) 这个接口，是获取设置的信息，

那当我添加定时的时候，我发现下面4个API中第2个可以实现分别显示和设置各个继电器的定时，但是这个API将被废除。
![image](https://user-images.githubusercontent.com/5464058/60146925-626c4800-9806-11e9-8cec-d2850bfcd992.png)

所以新的API中，并没有能实现此功能的API。

**Comment by santcool** [comment]
已修改，将上线版本SDK_10022。请使用openTimerSettingPageWithOpetions({identify:'xxxxx'})。文档将于最近同步

**Comment by fgb031102** [comment]
> 已修改，将上线版本SDK_10022。请使用openTimerSettingPageWithOpetions({identify:'xxxxx'})。文档将于最近同步

好的，谢谢！我测试后，会关闭此issue

**Comment by fgb031102** [comment]
> 已修改，将上线版本SDK_10022。请使用openTimerSettingPageWithOpetions({identify:'xxxxx'})。文档将于最近同步

利用这个接口

openTimerSettingPageWithOptions(options)

，设置定时，发现不成功，
具体代码如下：

Host.ui.openTimerSettingPageWithOptions({identify:'Relay', onMethod:"SetStateNew", onParam: ["1", " ", " "], offMethod: "SetStateNew", offParam: ["0", " ", " "], displayName:"设置插座定时"})
