### ISSUE TITLE
ios下蓝牙连接断开没作用

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#1051]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.2/iphone，IOS11.3/ipad]
SDK分支: [master]
相关模块:[Bluetooth]
现象（必填）
调用蓝牙连接，连接成功后，再调用断开，发现不能断开蓝牙。ios必现，在android下没有出现过。

期望（必填）
能正常使用连接，断开蓝牙操作。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/14890491/60066780-be699a80-973a-11e9-9773-a61fcc01cfbf.png)
![image](https://user-images.githubusercontent.com/14890491/60066803-ca555c80-973a-11e9-9ae6-9ad86cbf69e1.png)
![image](https://user-images.githubusercontent.com/14890491/60066825-d6411e80-973a-11e9-9fc1-1c98c1da84b2.png)

尝试过的解决办法

**Comment by zanetti4** [comment]
![image](https://user-images.githubusercontent.com/12883959/60068884-2f14b500-9743-11e9-86ef-9b612555368c.png)
文档里 delay 是整数，你把0.1改成整数能断开蓝牙吗？

**Comment by lijian9088** [comment]
你好，试过ble.disconnect(0)，ble.disconnect()，ble.disconnect(1000)。都没有作用。

**Comment by zanetti4** [comment]
@pencilCool 请协助查看此问题

**Comment by lijian9088** [comment]
刚才试了一下重新获取ble对象，已解决此问题。
![image](https://user-images.githubusercontent.com/14890491/60079728-187d5680-9761-11e9-80c1-d80de3da571d.png)
