### ISSUE TITLE
适配新版设置页报babelHelpers.objectDestructuringEmpty is not a function

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1052]
Debug模式下完全正常，打包到线上环境后，手机加载直接报错![进入设置页报错](https://user-images.githubusercontent.com/11864517/60067652-05a55a80-973e-11e9-8657-0bd765fe5e54.png)

**Comment by zanetti4** [comment]
请按照 issue 模版提问，谢谢

**Comment by LiuMengzhou** [comment]
此问题已经在群里反馈，群里消息摘抄如下：
可以参考：
https://github.com/facebook/react-native/issues/4831
