### ISSUE TITLE
扩展程序发上去不起作用

### ISSUE THREAD

**Issue by realize27** [MiEcosystem/miot-plugin-sdk#1054]
**是否为新品（必填）**
 新品 
**关联的产品model**
hzts.sensor_ht.trjc01
**项目ID（必填）**
 无项目ID

**企业名称（必填）**
贵州合纵天盛咨询有限公司

**环境（必填）**
- 电脑操作系统:[Windows7]
- 手机系统:[eg.Android 9.1/]
- SDK分支: [eg.master/10000/]
- 相关模块:[eg.云对云接入]

**现象（必填）**
云对云接入模式对接后，在其他平台设备中，成功在同步设备时候显示设备列表，但是设备列表里面点那个都没有反应，也进入不了扩展程序。

**期望（必填）**
云对云的文档太少，喜欢补充下这些资料，想清楚知道点设备为什么没反应。

**其他的上下文/日志/截图**

**Comment by lvjie0519** [comment]
@realize27   问题还存在吗？ 如果存在，请提供个视频看看，没太明白你的意思，谢谢。

**Comment by cfJand** [comment]
issue长时间未回复，先关掉。后续如果有问题，建议详细描述问题，添加截图，日志等相关信息，方便排查问题。
