### ISSUE TITLE
Spec doAction调用

### ISSUE THREAD

**Issue by xiaosheng-W** [MiEcosystem/miot-plugin-sdk#1055]
**是否为新品（必填）**
新品

**关联的产品model**
smith-blanket-cxma1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
艾欧史密斯（中国）环境电器有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Spec doAction 参数按照文档使用报错

**期望（必填）**
请示例正确调用方式

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
查看老版本action使用方式

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请给出具体的使用代码以及所报的错误

**Comment by xiaosheng-W** [comment]
> 请给出具体的使用代码以及所报的错误

调用:let result = Spec.doAction({did: Device.deviceID, siid: '2', aiid: '2', in: 'on'});
        result.then(value => {
            console.log('开机日志',value);
        });
错误:YellowBox.js:82 Possible Unhandled Promise Rejection (id: 0):
Object {
  "message": "callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-8 \"(null)\" UserInfo={message=data type not valid, result=null, code=-8}",
}

**Comment by zanetti4** [comment]
@santcool code -8 是参数错误，请你看一下具体哪个参数写错了？

**Comment by xiaosheng-W** [comment]
> @santcool code -8 是参数错误，请你看一下具体哪个参数写错了？

请问有没有使用示例,文档展示的不要清楚

**Comment by santcool** [comment]
请查看[文档](https://iot.mi.com/new/guide.html?file=07-%E4%BA%91%E5%AF%B9%E4%BA%91%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E5%BA%94%E7%94%A8%E4%BA%91%E5%AF%B9%E4%BA%91%E6%8E%A5%E5%85%A5/01-%E5%B0%8F%E7%B1%B3IOT%E6%8E%A7%E5%88%B6%E7%AB%AFAPI)里面的Invoke Action的描述。正确的参数传递为：{did: Device.deviceID, siid: 2, aiid: 2, in: ['on']}

**Comment by xiaosheng-W** [comment]
> 请查看[文档](https://iot.mi.com/new/guide.html?file=07-%E4%BA%91%E5%AF%B9%E4%BA%91%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E5%BA%94%E7%94%A8%E4%BA%91%E5%AF%B9%E4%BA%91%E6%8E%A5%E5%85%A5/01-%E5%B0%8F%E7%B1%B3IOT%E6%8E%A7%E5%88%B6%E7%AB%AFAPI)里面的Invoke Action的描述。正确的参数传递为：{did: Device.deviceID, siid: 2, aiid: 2, in: ['on']}

按照你说的格式调用报参数错误, 开机日志 {code: -704220035, siid: 2, did: "107157802", aiid: 1}
