### ISSUE TITLE
Host.file.screenShot可以指定截图路径么

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#1056]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0
- SDK分支: 10021
- 相关模块: Host.file.screenShot

**现象（必填）**
Host.file.screenShot可以指定截图的路径么？

![image](https://user-images.githubusercontent.com/2813239/60098719-bf291d80-9788-11e9-9cab-1dd119f2ff67.png)

Android端点击“截图保存”，可以将图片保存到普通用户可见的路径，这样用户下次可以再次查看他保存的图片。

早之前的版本我这样调用
```
Host.file.screenShot('/sdcard/' + Date.now() + '.png')
```
是可以将图片保存到sdcard中，现在这样调用**无效了**。

**期望（必填）**
因为iOS端截图分享页面有一个保存图片到本地的按钮，Android端没有，所有希望Android端截图保存功能，可以将图片保存到普通用户可见的路径，这样用户下次可以在本地直接查看到图片。

**Comment by zanetti4** [comment]
用系统自带的截屏功能是否可以满足你的需求？

**Comment by fengdexunmi** [comment]
@zanetti4 谢谢回复，如果可以调用系统自带的截屏功能，那更好。

**Comment by zanetti4** [comment]
我的意思是自己使用手机的截屏功能，[长图也能截](https://jingyan.baidu.com/article/3d69c5513fa752f0cf02d7ce.html)

**Comment by fengdexunmi** [comment]
@zanetti4 系统截屏只是满足了功能，但是这个地方我们还是需要点击“截图保存”按钮进行保存截图到本地。因为我们这里的临时密码是在门锁和手机蓝牙连接上才能再次看到，所以我们这里提供了一个“截图保存”的按钮，告知用户我们有这样的功能（以降低用户不在门锁附近没办法查看临时密码的概率）。

**Comment by Woody2016** [comment]
搞个文案提示说明下（让他使用手机截图保存下临时密码）不就行了

**Comment by fishle** [comment]
下个版本会新增一个保存图片到系统相册的接口，到时候就可以满足这个需求了

**Comment by fengdexunmi** [comment]
@fishle 你好，请问“下个版本会新增一个保存图片到系统相册的接口”这个接口已经有了么？在哪个分支可以使用？

**Comment by fishle** [comment]
sdk 10023, 下个版本发布
