### ISSUE TITLE
Device.extra 获取mcu_version,在安卓里正常，在ios里打印Device.extra返回的却是undefined，

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1057]
**是否为新品（必填）**
新品

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
优点cuber净水机

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android /iOS 
- SDK分支: 10002
- 相关模块:Device

**现象（必填）**
Device.extra 在安卓手机上获取到的是一个字符串，在ios设备上返回的确是undefined

**期望（必填）**
在页面展示插件固件版本号，想获取Device.extra里mcu_version属性，安卓下可以，ios获取不到

**其他的上下文/日志/截图**
下面两张图分别是安卓和ios手机上用alert()打印Device.extra的结果
![image](https://user-images.githubusercontent.com/28329423/60144692-f7b31080-97f5-11e9-8959-5c7c3d511f34.png)
![image](https://user-images.githubusercontent.com/28329423/60144707-07caf000-97f6-11e9-9406-1bff4f5937d6.png)

**Comment by santcool** [comment]
请分享设备到账号894158105上，我用其他设备，并没有看到mcu_version

**Comment by LZCaaT** [comment]
> 请分享设备到账号894158105上，我用其他设备，并没有看到mcu_version

分享给你了，帮忙看下

**Comment by santcool** [comment]
方便再分享一个嘛？昨天开了一天会，没有查问题，今天那个设备已经不在了。。
