### ISSUE TITLE
隐私协议弹框，点击同意并继续之后就退出插件了

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1058]
**是否为新品（必填）**
 新品

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
优点cuber净水机

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9]
- SDK分支: [master/10002/...]
- 相关模块:[Service]

**现象（必填）**
在插件绑定后进入时弹出的授权及隐私协议弹框，点击同意并继续之后就退后插件了，好像不能执行Service.smarthome.batchSetDeviceDatas()方法
![image](https://user-images.githubusercontent.com/28329423/60146227-5d55cb80-97fb-11e9-93d6-208ce366a27b.png)

**期望（必填）**
初次进入插件时，隐私协议弹框点击同意并继续应该是留在插件里的

**其他的上下文/日志/截图**

**Comment by zanetti4** [comment]
@since 10005
这个方法从10005以后才能使用

**Comment by LZCaaT** [comment]
> since 10005
> 这个方法从10005以后才能使用
你好，请问怎么升级sdk_api_level到10005呢

**Comment by zanetti4** [comment]
切换到 SDK_10005 分支，再拉取最新的代码

**Comment by LZCaaT** [comment]
> 切换到 SDK_10005 分支，再拉取最新的代码

好的，谢谢
