### ISSUE TITLE
定时开关模块需提供。隐藏 开启，关闭的属性接口，保留设置时间段条目

### ISSUE THREAD

**Issue by tangkun92** [MiEcosystem/miot-plugin-sdk#1059]
关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[ 苹果。 安卓]
SDK分支: [master]
相关模块:[  Service.scene.loadScenes(Device.deviceID, SceneType.Timer)]
现象（必填）
定时开关模块有 设置时间段选项，开启，关闭。三个选项

期望（必填）
米兔牙刷设置可玩游戏时间段，采用定时开关模块，有多余条目需要米家提供接口隐藏

希望提供可隐藏 开启 ，关闭。这两个选项的属性接口，只保留时间段设置条目
其他的上下文/日志/截图
![WechatIMG1](https://user-images.githubusercontent.com/16345833/60148102-53839680-9802-11e9-961e-759154d1688c.jpeg)

**Comment by Woody2016** [comment]
内部已在排期，请耐心等待

**Comment by tangkun92** [comment]
> 内部已在排期，请耐心等待

收到

**Comment by Woody2016** [comment]
需求已支持，请用SDK_10023中的接口：openTimerSettingPageWithOptions，具体使用请看考接口文档

此issue先close，之后如有问题，请再提新issue
