### ISSUE TITLE
离线状态下 titlebar的点击效果

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1060]
**是否为新品（必填）**
新品

**关联的产品model**
philips.light.cbulb

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10021]
- 相关模块:[]

**现象（必填）**
设备离线状态下，点击titlebar上的按钮还会响应，正常情况应该只有返回按钮可以响应。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
这是正常情况，不属于 bug

**Comment by mirse** [comment]
可能我表述有点问题，我离线状态下，titlebar有个收藏按钮，如果这时可以点击的话，就会弹出收藏弹框，并且可以进行收藏，这样的逻辑操作是否正确呢？
