### ISSUE TITLE
调用openCountDownPage接口报错

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#1061]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
填 新品 or 在售
新品 

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
qianqu.mosq.wx001

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID

**企业名称（必填）**
贵司的名称
东莞市纤趣电子科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master/10000/10020]
- 相关模块:[Host/]

**现象（必填）**
简单明了地描述一下实际的现象。
调用“openCountDownPage”这个接口报错。
![image](https://user-images.githubusercontent.com/5464058/60149696-8896e580-9810-11e9-989a-f61ae9b421a1.png)

**期望（必填）**
请协助解决这个问题

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我刚才用安卓手机测试，可以正常打开倒计时页面。你是怎么调用的 openCountDownPage 方法？报错中写着“拿到5个参数，期望是2个”。

**Comment by fgb031102** [comment]
> 我刚才用安卓手机测试，可以正常打开倒计时页面。你是怎么调用的 openCountDownPage 方法？报错中写着“拿到5个参数，期望是2个”。

不好意思忘记截图了
下面是我调用的方法
![image](https://user-images.githubusercontent.com/5464058/60159247-b8a0b180-982d-11e9-91af-e7292c3b4c5d.png)

**Comment by lvjie0519** [comment]
@fgb031102   
1、如你截图那样的调用方式报错吗？
2、apk版本是多少？ 用最新apk试试。

**Comment by fgb031102** [comment]
> @fgb031102
> 1、如你截图那样的调用方式报错吗？
> 2、apk版本是多少？ 用最新apk试试。

是的，如截图所示，报错。
APP版本：V-5.5.30.1
手机： MI5
OS: 8.0

**Comment by lvjie0519** [comment]
@fgb031102   你那边js部分是否之前有写过5个参数？  进入RN插件， 点击 “Debug 调试”， 重新reload一下。

**Comment by fgb031102** [comment]
> @fgb031102 你那边js部分是否之前有写过5个参数？ 进入RN插件， 点击 “Debug 调试”， 重新reload一下。

试过了，一直都出现这个错误。
一开始就是这样写的，我直接copy的文档中的实例代码。

**Comment by lvjie0519** [comment]
@fgb031102  用fir上最新apk测试下试试？

**Comment by fgb031102** [comment]
> @fgb031102
> 1、sdk使用10021分支。

你好！用10021可以了。
