### ISSUE TITLE
华为p30pro 指纹解锁界面异常

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1062]
**是否为新品（必填）**
在售

**项目ID（必填）**
xiaoxun.watch.v1

**企业名称（必填）**
上海小寻科技有限公司

**现象（必填）**
华为p30pro 密码解锁界面，取消和输入按钮界面重合

**期望（必填）**
按钮能分开

**其他的上下文/日志/截图**
![Screenshot_20190626_094324_com xiaomi smarthome](https://user-images.githubusercontent.com/34823528/60154597-64400680-981a-11e9-80de-37fba6ed4295.jpg)

**Comment by zanetti4** [comment]
请问你是怎么进入这个界面的？涉及到的模块、sdk 是什么？

**Comment by heping99** [comment]
@zanetti4 进入插件的  更多设置-》安全设置    设置安全密码后再此进入插件时，会出现这个解锁界面，就是在这时候出现的，sdk是10020

**Comment by zanetti4** [comment]
@LiuMengzhou 我的华为手机上，安全设置里只能设置数字密码，没有指纹。请你查看

**Comment by zanetti4** [comment]
@heping99 这个界面是是调用的系统ui，我们这边改不了。
