### ISSUE TITLE
米家IOS平台，Webview加载视频，点击无反应，无法播放

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/miot-plugin-sdk#1063]
---
**是否为新品（必填）**
在售

**关联的产品model**
rockrobo.vacuum.v1，rockrobo.sweeper.v2，rockrobo.sweeper.v1
roborock.vacuum.s5，roborock.sweeper.s5v2，roborock.sweeper.s5v3

**项目ID（必填）**
258089735

**企业名称（必填）**
北京石头科技股份有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[iOS 12.3.1]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**
我们插件中通过Webview的方式播放视频，但是在米家Android平台上可以正常播放，但是在米家IOS平台上不能点击，不能播放, 且项目已经切换至RN54，仍然存在此问题

**期望（必填）**
通过Webview的方式播放视频，在米家IOS平台上能正常播放视频

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by PioneerVM** [comment]
具体是这样实现的
![image](https://user-images.githubusercontent.com/22908326/60160213-74121780-9827-11e9-9ebb-aad16ba4cad8.png)

**Comment by zanetti4** [comment]
建议你做以下尝试，看能否解决问题。
1.给 WebView 添加属性 originWhitelist={['*']}
2. mediaPlaybackRequiresUserAction={false}
3. html 中增加 head 元素。
4. 改为 `<video></video>` 标签对写法。

**Comment by PioneerVM** [comment]
多谢多谢，是mediaPlaybackRequiresUserAction属性设置的问题
