### ISSUE TITLE
米家使用英文语言，但绑定是默认设备名称为中文，正确应该为英文

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1064]
**是否为新品（必填）**
在售

**关联的产品model**
xiaoxun.watch.v11

**企业名称（必填）**
上海小寻科技有限公司

**环境（必填）**
- 手机系统:[Android/iOS]
- SDK分支: [10020]

**现象（必填）**
米家使用英文语言，然后绑定设备，在绑定过程中默认出现的设备名称是中文，但是根据适配要求应该是英文才可以，设备在开放平上已经配置了中文和英文两种语言信息

**期望（必填）**
期望在英文环境下绑定是默认的名称也是英文

**Comment by Woody2016** [comment]
米家内部已知，后台支持，计划7.4上线（关联bug：ECOMIOT-1027）

**Comment by Woody2016** [comment]
@heping99 
米家后台已修复，请抽空验证，若验证通过，请close issue，谢谢
