### ISSUE TITLE
切换回手机主页后，回到插件-退出插件，米家首页横屏显示

### ISSUE THREAD

**Issue by tangkun92** [MiEcosystem/miot-plugin-sdk#1066]
关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[ 苹果iOS]
SDK分支: [master]
相关模块:[ 米家Beta256-米兔插件]
现象（必填）
[步骤]
1、进入米兔儿童牙刷插件

2、切换回手机主页，静置5秒

3、点击回到插件-退出插件

[结果]
米家首页横屏显示

期望（必填）

切换回手机主页，回米家首页竖屏正常显示，正常操作app

其他的上下文/日志/截图
![181648030128l9q](https://user-images.githubusercontent.com/16345833/60166517-eab51200-9833-11e9-9d96-6a8562add174.png)
![WechatIMG6](https://user-images.githubusercontent.com/16345833/60166778-5d25f200-9834-11e9-9e8b-d6c776b5408e.jpeg)

**Comment by santcool** [comment]
请分享设备到894158105

**Comment by tangkun92** [comment]
> 请分享设备到894158105

收到，测试已经共享米兔牙刷到894158105

**Comment by huangjr126** [comment]
@santcool 您好吖，想问下该问题进度如何了？

**Comment by santcool** [comment]
在需要横屏的页面，增加如下方法，即可解决。退出后台，回到前台做部分处理即可解决这种问题。
componentDidMount() {
    PackageEvent.packageDidResume.addListener(() => {
      console.log("packageDidLoaded------")
      Orientation.lockToLandscape();
    });

  }

**Comment by tangkun92** [comment]
> 在需要横屏的页面，增加如下方法，即可解决。退出后台，回到前台做部分处理即可解决这种问题。
> componentDidMount() {
> PackageEvent.packageDidResume.addListener(() => {
> console.log("packageDidLoaded------")
> Orientation.lockToLandscape();
> });
> 
> }

已收到，已测试，该问题处理已OK👌
