### ISSUE TITLE
Spec action方法调用报错

### ISSUE THREAD

**Issue by xiaosheng-W** [MiEcosystem/miot-plugin-sdk#1069]
是否为新品（必填）
新品

关联的产品model
smith-blanket-cxma1

项目ID（必填）
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

企业名称（必填）
艾欧史密斯（中国）环境电器有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.0]
SDK分支: [eg.master/10000/...]
相关模块:[eg.Host/Service/Account]
现象（必填）
Spec doAction 参数按照文档使用报错

期望（必填）
请示例正确调用方式

其他的上下文/日志/截图
调用:
let result = Spec.doAction({did: Device.deviceID, siid: 2, aiid: 2, in: ['on']});
        result.then(value => {
            console.log('开机日志',value);
        });;

错误日志:
调用报参数错误,  {code: -704220035, siid: 2, did: "107157802", aiid: 1}

尝试过的解决办法
查看老版本action使用方式

**Comment by zanetti4** [comment]
#1055

**Comment by xiaosheng-W** [comment]
Spec.doAction({did: Device.deviceID, siid: 2, aiid: 2, in: ['on']});
注:in所传参数并非方法定义里的参数,文档不清晰,请及时更新文档,目前已解决

**Comment by santcool** [comment]
我没太明白，麻烦截个图，并注明正确的描述，谢谢！

**Comment by xiaosheng-W** [comment]
![2271561686119_ pic](https://user-images.githubusercontent.com/37129996/60311289-21e90780-9989-11e9-81f8-13ef5bd70c76.jpg)
![2281561686173_ pic](https://user-images.githubusercontent.com/37129996/60311296-28777f00-9989-11e9-9e47-fda4921309e4.jpg)

**Comment by xiaosheng-W** [comment]
> 我没太明白，麻烦截个图，并注明正确的描述，谢谢！

action.params开始传了了协议的参数'on'

![2271561686119_ pic](https://user-images.githubusercontent.com/37129996/60311324-43e28a00-9989-11e9-9d10-145e09b9b431.jpg)
![2281561686173_ pic](https://user-images.githubusercontent.com/37129996/60311335-49d86b00-9989-11e9-97a3-a217210cac49.jpg)

**Comment by febird** [comment]
> Spec.doAction({did: Device.deviceID, siid: 2, aiid: 2, in: ['on']});
> 注:in所传参数并非方法定义里的参数,文档不清晰,请及时更新文档,目前已解决

请问最后是怎么调用成功的？  MIOT的文档跟垃圾没区别！！

**Comment by febird** [comment]
@xiaosheng-W

**Comment by xiaosheng-W** [comment]
> > Spec.doAction({did: Device.deviceID, siid: 2, aiid: 2, in: ['on']});
> > 注:in所传参数并非方法定义里的参数,文档不清晰,请及时更新文档,目前已解决
> 
> 请问最后是怎么调用成功的？ MIOT的文档跟垃圾没区别！！

传入的参数并非是协议里的参数,例如开关  协议是'on'  但是正确的传入方式:
Spec.doAction({did: Device.deviceID, siid: 2, aiid: 1, in: ['false']}) 或
Spec.doAction({did: Device.deviceID, siid: 2, aiid: 1, in: ['true']})
