### ISSUE TITLE
安卓导航栏沉浸

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#107]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Windows
- 手机系统:Android7.1

#### 现象

一加三导航栏不沉浸，测试其他小米机型能沉浸到状态栏

#### 期望

沉浸状态栏

#### 其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/5188922/49500118-e252b500-f8aa-11e8-81a7-6f1af77418db.png)

#### 尝试过的解决办法

将导航栏的position设为absolute

**Comment by mirse** [comment]
设置了TitleBarWhite的背景颜色，状态栏并无法沉浸上去，而且TitleBarWhite有空一条高度与状态栏大致一样（机型一加三）
如图：
![image](https://user-images.githubusercontent.com/5188922/49625249-c7e61c00-fa0f-11e8-9329-5d82895c3695.png)

**Comment by dingshaoran** [comment]
找不到7.0的一加手机 ，是设置了 titlebarwhite 才有的问题么，目前的实现方式你们是能看到的，您是怀疑  StatusBar.setBarStyle('dark-content'); 这个 api 不生效么

**Comment by mirse** [comment]
在TitleBarBlack，TitleBarWhite 都会出现这种情况，如下图为demo在一加手机上运行的界面：
![_20181211084959](https://user-images.githubusercontent.com/5188922/49770940-c07d8600-fd21-11e8-94df-92ab7cb2f57b.jpg)

StatusBar.setBarStyle这个api是生效的，目前在TitleBarWhite（Black）里添加如下代码，就不会出现此问题:
 <StatusBar
              translucent={true}
              animated={true}
              hidden={false}
              backgroundColor={'transparent'}
              barStyle={'default'}
          />
具体还请你们验证一下。

**Comment by mirse** [comment]
目前把TitleBarWhite复制到项目里， 使用
<StatusBar
translucent={true}
animated={true}
hidden={false}
backgroundColor={'transparent'}
barStyle={'default'}
/>
能实现沉浸上去，
把StatusBar.setBarStyle('dark-content');注释掉也可以沉浸上去
==****
