### ISSUE TITLE
TitleBar设置为dark时，顶部状态栏（运营商、信号）显示白色应该是黑色

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#1070]
**是否为新品（必填）**
在售

**关联的产品model**
inshow.watch.w1

**项目ID（必填）**
428
**企业名称（必填）**
深圳市隐秀科技

**环境（必填）**
Mac OS
- 手机系统:[iOS 12.3.1]
- SDK分支: [master]
- 相关模块:[UI]

**现象（必填）**
TitleBar设置为dark时，顶部状态栏（运营商、信号）显示成白色应该是黑色，dark是白底黑字，状态栏为白色就和背景颜色一样了表现就是就好像没有状态栏一样

**期望（必填）**
TitleBar设置为dark时，顶部状态栏是黑色

**其他的上下文/日志/截图**
![WechatIMG3](https://user-images.githubusercontent.com/11364809/60227689-dec46100-98c2-11e9-94be-f64cf8a2ec3e.png)
![WechatIMG2](https://user-images.githubusercontent.com/11364809/60227695-dff58e00-98c2-11e9-940e-aa7b5f7031e1.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zaxayn** [comment]
这是二级页面，一级页面的TitleBar是light，所以进入二级页面时会有一个颜色的切换，不知是否和这个有关

**Comment by mirse** [comment]
@zaxayn  你们的一级页面和二级页面都是设置的白底黑字吗？我也遇到了类似的问题

**Comment by zaxayn** [comment]
> @zaxayn 你们的一级页面和二级页面都是设置的白底黑字吗？我也遇到了类似的问题

我们一级是白色二级是黑色

**Comment by zanetti4** [comment]
请把一级和二级页面的 TitleBar 使用代码贴上来，我用苹果手机测试没发现此问题。

**Comment by zaxayn** [comment]
一级页面：
`static navigationOptions = ({navigation}) => {
        return {
            header: null
        };
    };`

`render() {
        return (
            <View style={{flex: 1}}>
                    <TitleBar
                        type='light'
                        style={{backgroundColor: "#121317"}}
                        title={Device.name}
                        />
            </view>
        );
    }
`
二级页面：
`    static navigationOptions = ({ navigation }) => {
        return {
            header:
                <TitleBar
                    type='dark'
                    title={'Test'}
                    onPressLeft={() => {
                        navigation.goBack();
                    }}
                />
        };
    };`

**Comment by mirse** [comment]
@zaxayn 还没解决，你们是用TitleBar还是用titlebarBlack/titleBarWhite？

**Comment by mirse** [comment]
@zanetti4 我这仅Android会出现这情况

**Comment by zanetti4** [comment]
@mirse 我在 master 上用华为荣耀9 Android 7.0 测试，一级页和二级页 TitleBar 都设置为 dark，状态栏都能正常显示。你的具体使用情况是什么？

**Comment by mirse** [comment]
> @mirse 我在 master 上用华为荣耀9 Android 7.0 测试，一级页和二级页 TitleBar 都设置为 dark，状态栏都能正常显示。你的具体使用情况是什么？

具体得在线上版才能复现，本地调试没问题。方便的话留个VX详聊。

**Comment by zaxayn** [comment]
@mirse @zanetti4 不好意思，回复晚了。

已经找到我遇到问题的原因，不单单是因为一级页面和二级页面，还因为我们一级页面的TitleBar需要定制，所以放在render里面了，并且一级页面还有一个timer在一直刷新，即使进入二级页面一级页面依旧会渲染白色的状态栏，所以才导致了这个问题，目前我们在尝试其他方案

**Comment by hao0000** [comment]
> @mirse @zanetti4 不好意思，回复晚了。
> 
> 已经找到我遇到问题的原因，不单单是因为一级页面和二级页面，还因为我们一级页面的TitleBar需要定制，所以放在render里面了，并且一级页面还有一个timer在一直刷新，即使进入二级页面一级页面依旧会渲染白色的状态栏，所以才导致了这个问题，目前我们在尝试其他方案

我们也有同样的问题

**Comment by zanetti4** [comment]
@mirse 你的问题似乎楼主说的不太一样，#954 不就是之前你提的有关状态栏的问题么，请你在那里回复

**Comment by mirse** [comment]
> @mirse @zanetti4 不好意思，回复晚了。
> 
> 已经找到我遇到问题的原因，不单单是因为一级页面和二级页面，还因为我们一级页面的TitleBar需要定制，所以放在render里面了，并且一级页面还有一个timer在一直刷新，即使进入二级页面一级页面依旧会渲染白色的状态栏，所以才导致了这个问题，目前我们在尝试其他方案

你们最后咋解决了，分享下方法吧

**Comment by zaxayn** [comment]
> > @mirse @zanetti4 不好意思，回复晚了。
> > 已经找到我遇到问题的原因，不单单是因为一级页面和二级页面，还因为我们一级页面的TitleBar需要定制，所以放在render里面了，并且一级页面还有一个timer在一直刷新，即使进入二级页面一级页面依旧会渲染白色的状态栏，所以才导致了这个问题，目前我们在尝试其他方案
> 
> 你们最后咋解决了，分享下方法吧

不是很高级的方法 =_=。进入二级页面暂停timer，返回一级页面回复timer

**Comment by mirse** [comment]
> > > @mirse @zanetti4 不好意思，回复晚了。
> > > 已经找到我遇到问题的原因，不单单是因为一级页面和二级页面，还因为我们一级页面的TitleBar需要定制，所以放在render里面了，并且一级页面还有一个timer在一直刷新，即使进入二级页面一级页面依旧会渲染白色的状态栏，所以才导致了这个问题，目前我们在尝试其他方案
> > 
> > 
> > 你们最后咋解决了，分享下方法吧
> 
> 不是很高级的方法 =_=。进入二级页面暂停timer，返回一级页面回复timer

感谢分享
