### ISSUE TITLE
离线状态下titleBar点击问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1071]
**是否为新品（必填）**
新品

**关联的产品model**
philips.light.cbulb

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10021]
- 相关模块:[]

**现象（必填）**
离线状态下，titlebar有个收藏按钮，如果这时可以点击的话，就会弹出收藏弹框，并且可以进行收藏，这样的逻辑操作是否正确呢？

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
#1060 如果原问题仍有疑虑，可再次打开。

**Comment by mirse** [comment]
@zanetti4 已添加说明，按道理，离线状态下应该是不能收藏情景的吧。

**Comment by zanetti4** [comment]
@LiuMengzhou 这种情况下的逻辑是怎样的？

**Comment by mirse** [comment]
Ios离线出现弹框时，收藏情况确定或取消都点不了，只能请调后台进程

**Comment by mirse** [comment]
离线状态下，点击收藏按钮，inputDialog确定或取消都点不了，只能清掉后台进程

**Comment by LiuMengzhou** [comment]
问题我们这边知道了。因为这个蒙层的需求是app端刚加上的，然后现在还在讨论解决方案。

**Comment by mirse** [comment]
我们建议离线状态栏，卡片中的关闭按钮为点击后退出插件或取消关闭按钮

![image](https://user-images.githubusercontent.com/5188922/60321902-af8c1d80-99b0-11e9-9d9f-195844c5ba6e.png)
