### ISSUE TITLE
openAddToDesktopPage()添加桌面快捷方式显示成功，实际并未成功

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1072]
**是否为新品（必填）**
 新品 

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
优点cuber净水机

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android /iOS ]
- SDK分支: [master/10005/]
- 相关模块:[Host/ui/openAddToDesktopPage()]

**现象（必填）**
Host.ui.openAddToDesktopPage() 添加桌面快捷方式，显示添加成功，实际却没有成功，再点一次添加才会成功，这是什么原因？
![image](https://user-images.githubusercontent.com/28329423/60228078-0d8f0700-98c4-11e9-8d02-981e72b3586b.png)

**期望（必填）**
Host.ui.openAddToDesktopPage() 期望调用一次就能实际添加成功

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**Comment by zanetti4** [comment]
我在安卓和苹果手机都测试了，没有发现你说的问题，也没见到截图的界面。你拉取最新的代码试试看

**Comment by lvjie0519** [comment]
@LZCaaT   添加添加桌面快捷方式，   每个手机系统有些不一样， 你这种情况是系统弹出的提示框，需要系统确认，这个APP没办法解决。
