### ISSUE TITLE
蓝牙发现服务

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#1073]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.2/Android 7.0]
SDK分支: [master]
相关模块:[Bluetooth]
现象（必填）
在设备开启工作的状态下，使用米家ble提供的connect方法去连接设备和发现服务：
1.ios下只能发现到FE95的米家服务，其他服务都不能发现。
2.android下连接失败，ble demo内显示-2，插件内显示-7。查看log，发现发起连接后蓝牙statusChange，且为true。

另外自己写的原生demo下，在设备开启时，连接正常并能完整发现服务。

期望（必填）
设备停止或者开启工作，都能正常连接并发现服务。

其他的上下文/日志/截图
android：
![image](https://user-images.githubusercontent.com/14890491/60228837-94dd7a00-98c6-11e9-9040-1abf5135c7dc.png)
![image](https://user-images.githubusercontent.com/14890491/60228876-ae7ec180-98c6-11e9-9608-0ae1471d486e.png)
![image](https://user-images.githubusercontent.com/14890491/60228893-bb031a00-98c6-11e9-9b5b-442950b5687f.png)

ios：
![image](https://user-images.githubusercontent.com/14890491/60228898-bd657400-98c6-11e9-8973-c3e5becfeb0c.png)
![image](https://user-images.githubusercontent.com/14890491/60229049-2ea52700-98c7-11e9-8105-67bdfbee2702.png)

尝试过的解决办法

**Comment by lijian9088** [comment]
我这边固件的同事确认了这个是固件的bug，打扰了

**Comment by dongyaxun** [comment]
> 我这边固件的同事确认了这个是固件的bug，打扰了

我这边也遇到了同样的问题，我用nRF Connect可以发现所有的服务，用小米sdk只能发现FE95服务，请问一下你们是怎么解决的啊？
