### ISSUE TITLE
蓝牙一次性发送的最大字节数疑问

### ISSUE THREAD

**Issue by codebeautiful** [MiEcosystem/miot-plugin-sdk#1074]
- 对于现在的蓝牙的最大字节数有些疑问，当前的Ble4.2以上版本已经可以发送超过20字节的数据包了

- 现在测试了iOS手机上，新版插件可以一次性收到超过20个字节的数据包，但是相同的插件放在Android上却收不到

- 想询问下，现在新版的插件是否可以支持每包的发送字节数超过20个

**Comment by zanetti4** [comment]
请按照  issue 模版提问，谢谢
