### ISSUE TITLE
IOS平台，新RN，万能遥控器进入米家添加界面后，返回，无法退出

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#1075]
**是否为新品（必填）**
在售

**关联的产品model**
米家万能遥控器/chuangmi.remote.v2

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
创米科技

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS]
- SDK分支: [10005]
- 相关模块:[Host/ui]

**现象（必填）**
进入米家添加遥控器界面，选择机顶盒，再返回，无法退出插件；设置里面，米家的跳转也有问题，看下视频操作；貌似经过一次跳转返回后，米家的界面跳转都不可用。

**期望（必填）**
1、能正常退出插件
2、设置菜单项能正常进入米家界面

**其他的上下文/日志/截图**
[20190627.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3332788/20190627.zip)

提供详细的操作录像文件见附件

**Comment by daoke666** [comment]
添加跳转代码如下
  /*添加*/
  _pressAdd() {
      let remotersArray = [];
      //Host.ui.openDevice('', 'mijia.ir.add', { type: 'add', gatewayID: Device.deviceID });

      if(Host.isIOS){
          Host.ui.addOrCopyIR(Device.deviceID,0,Device.model, { dismiss_current_plug: false })
      }else{
          Host.ui.addOrCopyIR(Device.deviceID, 0, remotersArray, { create_device: true });
      }
  }

**Comment by LiuMengzhou** [comment]
> 添加跳转代码如下
> 
> ```
>   /*添加*/
>   _pressAdd() {
>       let remotersArray = [];
>       //Host.ui.openDevice('', 'mijia.ir.add', { type: 'add', gatewayID: Device.deviceID });
> 
>       if(Host.isIOS){
>           Host.ui.addOrCopyIR(Device.deviceID,0,Device.model, { dismiss_current_plug: false })
>       }else{
>           Host.ui.addOrCopyIR(Device.deviceID, 0, remotersArray, { create_device: true });
>       }
>   }
> ```

@daoke666 
1. 本地调试有问题还是线上有问题？
2. 本地调试分支号？SDK_10005？
3. 线上打包分支号？
4. 代码没有必要分着写
```
/*添加*/
_pressAdd() {
  Host.ui.addOrCopyIR(Device.deviceID, 0, [], { create_device: true, dismiss_current_plug: false });
}

**Comment by daoke666** [comment]
@LiuMengzhou 
本地调试有问题还是线上有问题？
 本地调试正常，线上版本有此问题

本地调试分支号？SDK_10005？
线上打包分支号？
线上本地都一样：sdk_api_level:10005

代码没有必要分着写
这个是你们之前给的方案，参照如下issues，android上面这么写有问题
https://github.com/MiEcosystem/miot-plugin-sdk/issues/827

**Comment by LiuMengzhou** [comment]
既然安卓这么写有问题，那就分开写吧

**Comment by santcool** [comment]
这个问题是解决了吗？我看无法返回的主要原因是，点击A插件里面的按钮，新开了一个A插件。请问为什么不直接在当前A插件操作？

**Comment by daoke666** [comment]
还没解决啊，

这个应该跟之前的产品开发有关系吧

具体的操作就是
我们这边添加一个新的遥控器要跳转的米家的界面(这块实现是米家页面实现的)，然后返回就有问题了。

**Comment by daoke666** [comment]
@santcool 帮忙推进解决下，这个项目在提测中了

**Comment by santcool** [comment]
我懂了，这确实是一个bug，我来解决。预计上线SDK_10022

**Comment by santcool** [comment]
这儿还有个问题，我想知道。你们看看能不能通过log，或者断点来提供下。
你们先进入的米家万能遥控器的did和model，后面打开添加页面，调用         Host.ui.addOrCopyIR(Device.deviceID,0,Device.model, { dismiss_current_plug: false })时，传入的did和model

**Comment by daoke666** [comment]
这个是一样的，调用的都是当前设备的信息，log如下

constructor,did=91208359,model=chuangmi.remote.v2
_pressAdd,  did=91208359,model=chuangmi.remote.v2

**Comment by santcool** [comment]
这个问题我们找到原因了，但问题很太好解，我们弄了2天，还没搞定，等下周搞定了我再通知你。

**Comment by daoke666** [comment]
原计划7月9号更新的版本来得及吗

**Comment by santcool** [comment]
我今天一直在看，看我今晚能不能搞定了

**Comment by santcool** [comment]
改完了，你试试。https://fir.im/tes5?release_id=5d233182b2eb465497c0a991

**Comment by daoke666** [comment]
你好，刚刚验证下来，返回的问题确实解决了

不过有个新的问题点，具体操作如下
添加遥控器---机顶盒---定位成功后，不能显示出可选项。这时手动重新去选择下同样的地区就好了，看现象应该是，这个定位成功后没有去更新选项，改下就好了

![1](https://user-images.githubusercontent.com/49702230/60811136-40d56e00-a1c1-11e9-8465-991db12e5066.jpg)

![2](https://user-images.githubusercontent.com/49702230/60811160-4763e580-a1c1-11e9-8650-71d4c08557cd.jpg)

**Comment by daoke666** [comment]
@santcool 有段时间了，安排解决下吧，上次准备提测版本更新没上，赶在这次版本更新好提测

**Comment by LiuMengzhou** [comment]
定位成功之后，不刷新显示列表的问题吗？
今天看看

**Comment by daoke666** [comment]
是的，谢谢了

**Comment by LiuMengzhou** [comment]
已修改，请提供小米id，我加入白名单，你测试一下

**Comment by daoke666** [comment]
好的，小米账号ID：17602110704

**Comment by LiuMengzhou** [comment]
> 好的，小米账号ID：17602110704

不是手机号，是小米id

**Comment by daoke666** [comment]
嗯嗯，这个：1206895965

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/61362356-a2c65f80-a8b4-11e9-93fb-e01222f42e16.png)
已添加，稍等10分钟，app设置清除插件缓存

**Comment by daoke666** [comment]
验证OK，非常感谢。
