### ISSUE TITLE
iOS手机温湿度传感器插件内调用删除设备无法实际删除

### ISSUE THREAD

**Issue by MisterrWu** [MiEcosystem/miot-plugin-sdk#1076]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.sensor_ht.v1

**项目ID（必填）**
23954

**企业名称（必填）**
绿米

**环境（必填）**
电脑操作系统:[Mac OS]
手机系统:[iOS 12.1.4]
SDK分支: [10020]
相关模块:[Host]

**现象（必填）**
在iOS手机上进入插件，点击删除设备，网关没有提示删除成功。并且多次按下温湿度按钮后网关提示连接正常，进入网关设备列表界面，还会显示温湿度设备。

**期望（必填）**
在iOS上能够实际从网关删除设备。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请给出具体删除设备的代码

**Comment by MisterrWu** [comment]
Host.ui.openDeleteDevice();

**Comment by santcool** [comment]
备注：删除不掉设备是因为没给网关发送rpc：delete_device。已和你们同事聊过，需要你们统计网关/子设备通讯相关接口，我们一次性提供所有的。
