### ISSUE TITLE
被共享者无权限，右上角无设置项，功能不可用

### ISSUE THREAD

**Issue by liuling60LL** [MiEcosystem/miot-plugin-sdk#1077]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
新品 

**关联的产品model**
model: '180.plug.plug0001'

**项目ID（必填）**
无项目ID

**企业名称（必填）**
深圳市安信可科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [master_10021]
- 相关模块:[Service]

**现象（必填）**
1.被共享者，右上角无设置项；
 2 .功能不可用,提示"被分享设备无此权限"

**期望（必填）**
期望提供详细的文档说明，commonSetting控件下面关于分享的内容很少

**其他的上下文/日志/截图**

![image](https://user-images.githubusercontent.com/34119193/60232648-c6a70e80-98cf-11e9-8a8f-a51706800d85.png)

**尝试过的解决办法**
尝试调用
Service.security.shareSecureKey(deviceID, shareUid, {})
 .then(secureKey=>{
    ...
 })

**不要贴大段代码❗️**

**Comment by liuling60LL** [comment]
安卓跟IOS上都有这个问题，shareSecureKey 的第三个参数不知道改怎么填，有具体的案例可以参考下吗？

**Comment by liuling60LL** [comment]
> 此问题出现在安卓还是ios上？shareSecureKey的第三个参数，是否尝试过填入一些设置？
安卓跟IOS上都有这个问题，shareSecureKey的第三个参数不知道改怎么填，有具体的案例可以参考下吗？
看到可以回复一下吗？拜托了，谢谢

**Comment by zanetti4** [comment]
> @param {{status,activeTime,expireTime,weekdays,readonly}} [settings={}] readonly = true, 则被分享人不可接收锁push，false则被分享人可接收锁push，（family关系用户不受这个字段影响）。status:分享类别，1：暂时，2：周期，3：永久; weekdays 生效日期（星期几，例如周一和周三对应1和3，[1, 3]），仅在status=2时不可为空

可以根据文档和你的需求尝试设置

**Comment by zanetti4** [comment]
@santcool @lvjie0519 这是 js 使用问题吗？安卓和 ios 都有此问题，是 settings 未设置的原因吗？

**Comment by santcool** [comment]
你们的这个，本来就不支持共享，所以没有权限是很正常的，这个和代码无关。
![屏幕快照 2019-06-28 下午4 10 48](https://user-images.githubusercontent.com/8580061/60327792-65f6ff00-99bf-11e9-8f44-82f3a7de11f6.png)

**Comment by liuling60LL** [comment]
> 你们的这个，本来就不支持共享，所以没有权限是很正常的，这个和代码无关。
> ![屏幕快照 2019-06-28 下午4 10 48](https://user-images.githubusercontent.com/8580061/60327792-65f6ff00-99bf-11e9-8f44-82f3a7de11f6.png)

![image](https://user-images.githubusercontent.com/34119193/60328489-f5e97880-99c0-11e9-8025-e10cabaf482b.png)
这边选中的第一个选项

**Comment by santcool** [comment]
弄错了，自动化权限没有给被共享者开放。共享设备只支持被共享者操作，不支持定时，倒计时，智能场景等内容。

**Comment by liuling60LL** [comment]
你好，我不是很理解，
1.这个权限是可以给被共享者开放的吗？
2.是在后台产品共享选中：支持（用户可选共享权限）就可开通被共享者的定时，倒计时，智能场景的权限吗？
3.还是需要代码比如Service.security.shareSecureKey之类的接口去实现并开通权限
附加一个问题：28号后台上传提交了测试版本，SDK10021版本的，但是到今天30号获取的还是之前的10003版本的

**Comment by fengfeng0328** [comment]
![image](https://user-images.githubusercontent.com/34309825/60406608-59ee8580-9be9-11e9-9ce2-5cc46102eec9.png)
也就是说目前小米是没有办法解决上图问题？被共享对象APP插件上是无法支持定时。请问这个理解是否正确

**Comment by santcool** [comment]
对。如果你们确实有这方面的需求，可以联系对接你们的产品经理，让他考虑是否有必要支持此需求。如果有必要，他会推动后台和我们一起改。
