### ISSUE TITLE
Android端使用react-native-linear-gradient插件的问题

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#1078]
**是否为新品（必填）**
新品

**关联的产品model**
dsm.lock.q3

**项目ID（必填）**
暂无项目iD

**企业名称（必填）**
德施曼机电

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1
- SDK分支: master/10000
- 相关模块:

**现象（必填）**
项目导入了第三方插件react-native-linear-gradient用于实现渐变色效果，在iOS端可以正常运行，在Android提示BVLinearGradient不存在，想咨询下这个插件是不是需要在米家主程序中进行相关配置

**期望（必填）**
希望能帮忙查看一下

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
论坛方法基本都试过了，由于无法修改Androd配置，所以无法验证是否在修改了配置之后是否可用

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@lcyisgod  Android原生部分已集成，使用fir上最新apk， js sdk部分预计明天集成，届时选择10022分支即可。
