### ISSUE TITLE
打包后 iOS不能正常播放本地音频

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#1079]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
 在售

**关联的产品model**
“ksmb.walkingpad.v1”

**项目ID（必填）**
959174401

**企业名称（必填）**
北京金史密斯科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.2
- SDK分支: master
- 相关模块:Host

**现象（必填）**
Host.audio 模块，本地调试 iOS和安卓都可顺利播放本地音频，例如播放第一段音频，在没有播完的情况下，播放第二个音频，本地调试下都可顺利播放，打包后，安卓也可以顺利播放，iOS在这种情况下，第一段没播完，第二段就播放不出来了，

**期望（必填）**
打包后iOS播放正常播放本地音频。

**其他的上下文/日志/截图**

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by liduojun** [comment]
我播放第二段之前，先把第一段的音频 停止后 Host.audio.stopPlay().then(()=>{});，在执行播放第二段，iOS打包后就不播放了

**Comment by santcool** [comment]
我试了一下，打包了也是可以播放的，并没有复现你的问题。你下载最新的调试app后，打开开发者设置，添加package:com.xiaomi.demo,model:miot.plug.xm1,然后将IP设置为iot.plugin.hook。然后打开你们的设备，会跳转到demo程序.点击旧-设置页面 - 音频。录音并播放后，看看是否能够顺利播放第二段

**Comment by liduojun** [comment]
@santcool  走了catch:error:"Fail to create a audio player! error code:1685348671,domain:NSOSStatusErrorDomain,userinfo:{\n},localizedDescription:未能完成操作。("OSStatus"错误 1685348671。)"

**Comment by santcool** [comment]
参考下这篇文章试试：https://www.jianshu.com/p/3ca573fc4026。换一个播放的解码参数

**Comment by liduojun** [comment]
Thank you ~`
