### ISSUE TITLE
AsyncStorage在新的SDK中使用会感觉读取数据时间变长很多，之前的版本不会有这个情况

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/miot-plugin-sdk#108]
AsyncStorage读取值的时候时间变长了？

**Comment by wyc123456** [comment]
目前使用的版本"react-native": "^0.54.4"

**Comment by LiuMengzhou** [comment]
@wyc123456 
感谢你提出issue。
1. 不推荐使用AsyncStorage，在删除设备的时候可能没办法清除掉这部分数据。
2. 新旧版本的框架都没有对这个库做过任何处理。时间变化应该是RN升级的原因，与框架无关。
