### ISSUE TITLE
BluetoothEvent.bluetoothStatusChanged不回调（iOS）

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#1081]
- IPA/APK iOS:v4.18.2  Android:v5.5.30
- SDK master 10020

---
**是否为新品（必填）**
在售

**关联的产品model**
roidmi.btfm.m1

**企业名称（必填）**
 无锡睿米

**环境（必填）**
- 相关模块: BluetoothEvent

**现象（必填）**

- 此model为“非小米蓝牙协议”设备，BLE的scan都是依赖我们自主调用startScan；
- 发现BluetoothEvent.bluetoothStatusChanged在iOS上不回调（同时测试com.xiaomi.bledemo--NormalBle.js）同样不回调
- 另外测试其他产品，“小米蓝牙协议”的设备，此回调正常
- 测试Android端，能够正常回调（相同代码，iOS/Android测试结果不同）
- NormalBle.js，当使用 “小米蓝牙协议”的model进入测试时，iOS端可正常接收回调
- checkBluetoothIsEnabled、bluetoothSeviceDiscovered此类接口能够正常接收回调，唯独 bluetoothStatusChanged 无法接收回调

**期望（必填）**
帮忙测试下，在“非小米蓝牙协议”的插件中，为什么BluetoothEvent.bluetoothStatusChanged不回调

**代码**
```
        this._s5 = BluetoothEvent.bluetoothStatusChanged.addListener((data) => {
            console.warn("bluetoothStatusChanged", data);
            //... iOS上打开/关闭系统蓝牙，无法接收回调
        });
```

**Comment by edwardair** [comment]
进度咨询 @zanetti4 @blockdate

**Comment by pencilCool** [comment]
这个问题应该修复了。就是内部通知名字不匹配导致的。

**Comment by edwardair** [comment]
iOS版本  V4.24.2 问题仍然存在
