### ISSUE TITLE
打包包名问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#1082]
公司名称
青岛亿联客信息技术有限公司

是否为新产品
否

产品名称/Model
yeelink.light.ceiling12(应该不限于该model)

环境

电脑操作系统:[Mac OS]
手机系统:[Android 6.0]
SDK分支: [master]
相关模块:[Device]
现象
目前我司有几十个插件，目前计划包名公用一个，即project.json下package_path为相同值。不知道这样是否会影响各个插件的打包上传以及用户下载使用。

期望
允许多个插件用同一个包名

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码

**Comment by TheWalkingDead1024** [comment]
同一个插件不同版本可以使用不同包名吗？

**Comment by santcool** [comment]
如果所有插件放在同一个包里面，是没问题的。否则，不行，包名和model可以是一对一和一对多，但是绝对不能使多对一。
