### ISSUE TITLE
关于react-native-linear-gradient的集成

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#1084]
**是否为新品（必填）**
新品

**项目ID（必填）**
无项目ID

**企业名称（必填）**
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
macOs
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 8.1
- SDK分支: [eg.master/10000/...]
10021
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
项目中需要使用颜色渐变，使用react-native-linear-gradient来实现，Android端米家App原生未集成，iOS已经集成，导致Android上打开插件会闪退。

**期望（必填）**
期望Android上也能集成该组件，早点解决闪退的痛点。

**Comment by zanetti4** [comment]
#1078 这是同一个问题

**Comment by lvjie0519** [comment]
@evansherry   Android原生部分已集成，使用fir上最新apk， js sdk部分预计明天集成，届时选择10022分支即可。

**Comment by evansherry** [comment]
@lvjie0519 收到

**Comment by zanetti4** [comment]
@evansherry 如果问题得到解决，请关闭此 issue
