### ISSUE TITLE
Picker分割线

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1085]
目前安卓的Picker控件有选中分割线，iOS没有，希望iOS也保留分割线

**Comment by zanetti4** [comment]
请按照 issue 模版提问题，谢谢

**Comment by YunzzzZ** [comment]
iOS无分割线：
<img width="430" alt="FF66B97C-EA62-4423-B48B-652C0B9EF87A" src="https://user-images.githubusercontent.com/17631207/60255739-e0ae1480-9902-11e9-9653-1a7949c3ac8d.png">

安卓有分割线：
<img width="343" alt="50640AEC-0733-42BE-8239-BEAEF5418CA4" src="https://user-images.githubusercontent.com/17631207/60255863-181cc100-9903-11e9-8c8c-3b8246524bad.png">

期望iOS也有分割线
