### ISSUE TITLE
有固件升级时 固件升级栏需要有红点提示

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1086]
普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

是否为新品（必填）
不是

关联的产品名称（必填）
“米家小饭煲”

项目ID（必填）
项目ID

企业名称（必填）
上海纯米电子科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 8.00]
SDK分支: [10010]
相关模块:[UI]
现象（必填）
固件升级当有最新固件时  固件升级item一栏  需要有红点提示

期望（必填）
如图 当有最新固件时  固件升级item一栏  需要有红点提示
![IMG_20190627_171923](https://user-images.githubusercontent.com/34296463/60255353-37671e80-9902-11e9-9ed4-db34b33b4a79.jpg)

**Comment by LiuMengzhou** [comment]
`SDK_10021` 新增
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E5%8F%82%E6%95%B0-6

**Comment by LiuMengzhou** [comment]
#926

**Comment by joyami** [comment]
好的 谢了！
