### ISSUE TITLE
通用设置组件commonsetting右箭头部分红米手机不显示。另外包括ListItem, ListItemWithSwitch 等组件右箭头显示不出来

### ISSUE THREAD

**Issue by aLLLiyyy** [MiEcosystem/miot-plugin-sdk#1087]
commonsetting组件ListItem, ListItemWithSwitch 等组件，右箭头在部分红米手机上面不显示。
sdk版本20
![wrong](https://user-images.githubusercontent.com/36837316/60260160-72218480-990b-11e9-8b58-2d1a7a1dcce6.png)

**Comment by zanetti4** [comment]
Duplicate of #1018

**Comment by zanetti4** [comment]
现在这个问题解决了吗？请测试一下，如已解决，请关闭问题
