### ISSUE TITLE
ios系统更多设置界面点击帮助浏览问题界面，然后右滑返回，返回的界面出现黑色渲染，白色分割线夹在其中。

### ISSUE THREAD

**Issue by aLLLiyyy** [MiEcosystem/miot-plugin-sdk#1088]
sdk版本20
操作系统ios
问题界面，commonsetting里面使用帮助，点击查看一条帮助右滑返回。出现此情况，不必现。
![55555555555555556](https://user-images.githubusercontent.com/36837316/60260517-58347180-990c-11e9-85a8-7cf24b7436c5.jpg)

**Comment by zanetti4** [comment]
Duplicate of #1006

**Comment by zanetti4** [comment]
下载新的调试包后，问题是否得到解决？

**Comment by santcool** [comment]
这个我已经解决了哈，去下载最新的调试包吧。
