### ISSUE TITLE
高德地图显示问题

### ISSUE THREAD

**Issue by uuuust1111** [MiEcosystem/miot-plugin-sdk#1089]
是否为新品（必填）
在售

关联的产品model
midr.rv_mirror.v1

项目ID（必填）
615

企业名称（必填）
新案

环境（必填）

电脑操作系统:Windows
手机系统:.Android 8.0.0 MIX
SDK分支: master/10012
相关模块:高德地图
现象（必填）：
1，进入插件主页，高德地图的logo显示在左下角，有遮挡。
2，设置app语言为英语是，地图上的地点未显示成英文。

期望（必填）
高德地图logo能居中显示
切换语言时能地图上的地点能显示成对应的语言。

![微信图片_20190627194605](https://user-images.githubusercontent.com/50855772/60263838-45be3600-9914-11e9-9241-b93a2b7fca49.jpg)

**Comment by zanetti4** [comment]
@lvjie0519 我在点击 MoreMenu.js 中的高德地图是，报红屏错误: 

> Error while updating property 'centerCoordinate' of a view managed by: MHMapView

请你协助查看此问题

**Comment by zanetti4** [comment]
@uuuust1111 标题写得有点儿抽象……

**Comment by uuuust1111** [comment]
有更新吗？

**Comment by lvjie0519** [comment]
@uuuust1111    
1、地图中英文的支持；
2、高德地图文字logo显示；
 ios存在相同情况吗？
第一个问题，我看官方api已经支持中英文切换，这个我们也可以做支持；
第二个问题，我没在官方api中找到对应的接口，如果你了解麻烦知照一下，我这边可以做支持。

**Comment by uuuust1111** [comment]
![image](https://user-images.githubusercontent.com/50855772/61018753-78fbcd00-a3ca-11e9-8f66-f55021130afb.png)
试试这个api
ios问题同 issue 1021。

**Comment by zanetti4** [comment]
#1021

**Comment by lvjie0519** [comment]
@uuuust1111   已增加api支持， 请使用最新apk， sdk 选择10023分支，可参考demo。
