### ISSUE TITLE
iOS 蓝牙模块，BluetoothEvent.bluetoothConnectionStatusChanged 断开蓝牙连接时，没有收到消息

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#109]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:mac
- 手机系统:ios 12
- 相关模块: BluetoothEvent

#### 现象

连接上米家恒温水壶（蓝牙设备），能读取数据，也能写数据。此时，把水壶与底座分开（会断开蓝牙连接），BluetoothEvent.bluetoothConnectionStatusChanged的监听，没有收到消息。

#### 期望

在蓝牙断开时，BluetoothEvent.bluetoothConnectionStatusChanged能正确的收到蓝牙连接状态消息，这样才可以做蓝牙重连功能。

**Comment by LiuMengzhou** [comment]
@flingInTheSky 收到，我们看一下

**Comment by JxXiaoXie** [comment]
你会出现这个问题吗？#122

**Comment by edwardair** [comment]
+1  问题解决了么？目前iOS上同样有这问题

**Comment by caojunhua** [comment]
@flingInTheSky 你好，大兄弟，能交流一下你那边读写数据的情况吗，我调用写数据接口的时候，出现了request is not support的情况  -->  https://github.com/MiEcosystem/miot-plugin-sdk/issues/134

**Comment by caojunhua** [comment]
> +1 问题解决了么？目前iOS上同样有这问题

+1

**Comment by LiuMengzhou** [comment]
Duplicate of #134
