### ISSUE TITLE
IPad Pro倒计时设置成功后，时间轴上不能完整显示时间

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#1090]
---
**是否为新品（必填）**
新品

**关联的产品model**
chuangmi.plug.hmi208

**项目ID（必填）**
无项目ID

**企业名称（必填）**
创米科技

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] IOS 12
- SDK分支: [eg.master/10000/...] 10011
- 相关模块:[eg.Host/Service/Account] Host.ui

**现象（必填）**
IPad Pro倒计时设置成功后，时间轴上不能完整显示时间,显示区域被遮挡掉一部分

**期望（必填）**
IPad Pro倒计时设置成功后，时间轴上完整显示时间

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
无

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
能把时间轴被遮挡的截图贴上来吗？

**Comment by yanmin0220** [comment]
![87321561948263_ pic_hd](https://user-images.githubusercontent.com/8665213/60407123-fade4000-9beb-11e9-9d23-18d9be28fed0.jpg)

**Comment by santcool** [comment]
已完成，将进入7月9号的版本

**Comment by zhuxinleibandou** [comment]
想请教您一下，iOS这种倒计时页面是调用米家的还是自己写的？谢谢，因为最近也在开发倒计时的页面，好像米家没有提供这种圆圈拖动的倒计时页面，谢谢您了，期待您的回复！

**Comment by zhuxinleibandou** [comment]
> **是否为新品（必填）**
> 新品
> 
> **关联的产品model**
> chuangmi.plug.hmi208
> 
> **项目ID（必填）**
> 无项目ID
> 
> **企业名称（必填）**
> 创米科技
> 
> **环境（必填）**
> 
> * 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
> * 手机系统:[eg.Android 8.1/iOS 11.0] IOS 12
> * SDK分支: [eg.master/10000/...] 10011
> * 相关模块:[eg.Host/Service/Account] Host.ui
> 
> **现象（必填）**
> IPad Pro倒计时设置成功后，时间轴上不能完整显示时间,显示区域被遮挡掉一部分
> 
> **期望（必填）**
> IPad Pro倒计时设置成功后，时间轴上完整显示时间
> 
> **其他的上下文/日志/截图**
> 提供更多的上下文，有日志或者截图更好。
> 
> **尝试过的解决办法**
> 无
> 
> **不要贴大段代码❗️**

想请教您一下，iOS这种倒计时页面是调用米家的还是自己写的？谢谢，因为最近也在开发倒计时的页面，好像米家没有提供这种圆圈拖动的倒计时页面，谢谢您了，期待您的回复！
