### ISSUE TITLE
横屏翻转竖屏后，有一定几率状态栏无法显示

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#1091]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）
手机系统:[iOS 12.2]
SDK分支: [master]
相关模块:[Video]

现象（必填）
1、进入插件，点击家长控制按钮，设置好PIN码
2、填写PIN码进入家长控制页面后，无法查看到状态栏

期望（必填）
进入家长控制页面后，可以正常查看到状态栏

其他的上下文/日志/截图
正常：
![image](https://user-images.githubusercontent.com/48087638/60281681-f8ec5680-9937-11e9-9f3e-720f307383b0.png)

异常：
![image](https://user-images.githubusercontent.com/48087638/60281554-b0349d80-9937-11e9-8e7d-f35da6be2bfe.png)
![image](https://user-images.githubusercontent.com/48087638/60281570-b7f44200-9937-11e9-9255-cf1c5283551a.png)

**Comment by santcool** [comment]
这个复现概率有多大？能提供一个小视频吗？我尝试了下，并不能复现。

**Comment by huangjr126** [comment]
[米兔牙刷复现视频.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3338177/default.zip)
复现概率为：40%，可以提供小视频。

**Comment by huangjr126** [comment]
@santcool

**Comment by santcool** [comment]
输入家长pin码之后，试试调用Orientation.lockToPortrait.然后从下一页返回时，需要再调用Orientation.lockToLandscapeLeft。

**Comment by huangjr126** [comment]
@santcool 我们一直就是这样的调用方式。结果还是无法显示状态栏。经我们观察发现，状态栏的确旋转了，但貌似没有旋转到正确位置。还请麻烦您在查看下视频当中的复现操作。

**Comment by santcool** [comment]
你们是如何调用的，能上代码吗？

**Comment by heyupeng** [comment]
@santcool 这里输入完pin码后navigate到数据页面，并且在挂载后.lockToPortrait；goback之前.lockToLandscape。与你所说的调用方式并无不同吧？

**Comment by santcool** [comment]
因为我这边没法复现，所以需要直接看看代码，或许有什么我们都忽略了的地方。

**Comment by heyupeng** [comment]
这部分就是一个.navigate, 挂载后. lockToLandscape,没有其他的。
<img width="432" alt="image" src="https://user-images.githubusercontent.com/17895457/60939323-c8c68f80-a309-11e9-81b5-1916178a4620.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/17895457/60939362-e693f480-a309-11e9-8746-e8bffa6e2c56.png">

**Comment by santcool** [comment]
状态栏的问题已修复
