### ISSUE TITLE
StringSpinner控件设置unit单位不显示

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1092]
SDK10021
实际情况：rmc-picke控件，当前选中分割线，安卓有显示，iOS没有显示
期望：安卓iOS都显示分割线
如图（上面是安卓截图，下面是iOS截图）：
<img width="343" alt="50640AEC-0733-42BE-8239-BEAEF5418CA4" src="https://user-images.githubusercontent.com/17631207/60311214-e51d1080-9988-11e9-8ece-d2d5049f0fad.png">
<img width="430" alt="FF66B97C-EA62-4423-B48B-652C0B9EF87A" src="https://user-images.githubusercontent.com/17631207/60311217-ebab8800-9988-11e9-85db-b0adb996820a.png">

**Comment by LiuMengzhou** [comment]
[数字选择器-NumberSpinner](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E6%95%B0%E5%AD%97%E9%80%89%E6%8B%A9%E5%99%A8-numberspinner)
[通用选择器-StringSpinner](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E9%80%9A%E7%94%A8%E9%80%89%E6%8B%A9%E5%99%A8-stringspinner)
[时间选择器-MHDatePicker](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E6%97%B6%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8-mhdatepicker)

**Comment by YunzzzZ** [comment]
StringSpinner组件，小米note3未显示单位 @LiuMengzhou

**Comment by LiuMengzhou** [comment]
> StringSpinner组件，小米note3未显示单位 @LiuMengzhou

@YunzzzZ 
系统版本：
app 版本：
sdk 版本：
使用方法（代码片段）：

@lvjie0519

**Comment by lvjie0519** [comment]
@YunzzzZ  麻烦给出相关信息，我这边才好排查，谢谢。
系统版本：
app 版本：
sdk 版本：
使用方法（代码片段）：

**Comment by YunzzzZ** [comment]
SDK10020

<View style={{ flex: 1, justifyContent: 'center'}}>
           
            <StringSpinner
              style={{
                height: 216,
                backgroundColor: '#ffffff'
              }}
              dataSource={sortTheKeys}
              defaultValue={this.state.selectedHour}
             unit={LanguageLocal.strings.hour}
              pickerInnerStyle={{
                lineColor: '#cccccc',
                textColor: "#F5961C",
                selectTextColor: "#F5961C",
                selectBgColor: "#f5f5f5",
                unitTextColor: '#F5961C',
              }}
              onValueChanged={(data) => { this._p1(data) }}
            />

          </View>

StringSpinner控件设置unit单位，部分安卓手机不显示 @LiuMengzhou @lvjie0519 
![IMG_3569](https://user-images.githubusercontent.com/17631207/60492973-96e87400-9cde-11e9-8c7b-1f71a6acdfd8.JPG)

**Comment by lvjie0519** [comment]
@YunzzzZ    需要设置个宽度

**Comment by YunzzzZ** [comment]
*
 *
 * @property {bool}    visible 是否可见
 * @property {style} style - 开关样式，仅支持宽高
 * @property {array<string>}   dataSource 数据源
 * @property {string}  defaultValue 默认值
 * @property {func}    onValueChanged 值改变的回调
 * @property {string}    unit 单位 默认：无
 * @property {string}  pickerInnerStyle.textColor 文字颜色 默认值 #000000
 * @property {string}  pickerInnerStyle.selectTextColor 文字选中颜色 默认值 #00aa71
 * @property {string}  pickerInnerStyle.selectBgColor 文字选中背景 默认值 #ffffff
 * @property {string}  pickerInnerStyle.unitTextColor 单位字体颜色 默认值 #00aa71
 * @property {string}  pickerInnerStyle.lineColor 分割线颜色 默认值 #e5e5e5
 * @property {number}  pickerInnerStyle.fontSize 文字大小 默认值 22
 * @property {number}  pickerInnerStyle.selectFontSize 文字选中大小 默认值 22
 * @property {number}  pickerInnerStyle.unitFontSize 单位字体大小 默认值 12
 * @property {number}  pickerInnerStyle.rowHeight 行高 默认值 42
 */
并未提供设置单位宽度参数 @lvjie0519

**Comment by zanetti4** [comment]
你把宽度写在 style 里是否可以？

**Comment by lvjie0519** [comment]
@YunzzzZ 
StringSpinner
          style={{
            height: 216,
            width: 200,    // 是这里缺少宽度
            backgroundColor: '#ffffff'
          }}

**Comment by lvjie0519** [comment]
先关闭，如问题未解决，在reopen。
