### ISSUE TITLE
Host.getOperatorsInfo问题

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/miot-plugin-sdk#1093]
**是否为新品（必填）**
在售

**关联的产品model**
roborock.vacuum.t6,roborock.vacuum.t6v2,roborock.vacuum.t6v3

**项目ID（必填）**
258089735

**企业名称（必填）**
北京石头科技股份有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 9]
- SDK分支: [10021.]
- 相关模块:[Host]

**现象（必填）**
我们使用了最新的Host.getOperatorsInfo方法，
看接口给的参数是支持两个卡的，但是实际两个卡的时候，只返回了一个

**期望（必填）**
Host.getOperatorsInfo方法如果支持两个卡，请在手机双卡时返回两张卡的信息。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@PioneerVM  Android目前仅支持返回主卡信息。

**Comment by zanetti4** [comment]
@lvjie0519 这样的话最好把文档改一下，以免造成误导。
