### ISSUE TITLE
OTA固件升级不能成功

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#1094]
**是否为新品（必填）**
在售

**关联的产品model**
chuangmi.remote.h102c01

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
创米科技

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android/iOS ]
- SDK分支: [10005]

- 相关模块:[Host/ui]

**现象（必填）**
1、升级到50%以内的，不定百分比后，会直接进入到安装更新界面并一直停留，有时提示升级超时、有时下载失败
2、同时查看 设备端已正常进入到 闪蓝灯连接网络状态 

**期望（必填）**
正常升级成功

**其他的上下文/日志/截图**
![1](https://user-images.githubusercontent.com/49702230/60314031-c07a6600-9993-11e9-97d1-901d093d41b3.png)

**Comment by daoke666** [comment]
插件调用的是：Host.ui.openDeviceUpgradePage();

**Comment by pencilCool** [comment]
这个还有问题吗？

**Comment by daoke666** [comment]
固件升级了SDK，现在正常，关掉吧
