### ISSUE TITLE
米家小卡片开关按钮只能显示normal状态图片，不能切换到selected状态的图片

### ISSUE THREAD

**Issue by ross-1** [MiEcosystem/miot-plugin-sdk#1095]
**是否为新品（必填）**
 在售

**关联的产品model**
xjx.toilet.pro

**项目ID（必填）**

**企业名称（必填）**
小鲸洗

**环境（必填）**
- 手机系统:[iOS 12.0]

**现象（必填）**
米家快捷卡片的开关按钮cardType ： 1,设置好normal图片和selected图片，但是点击之后图片不会切换，而且下面的文字，永远显示第二个操作的文字

**期望（必填）**
图片在点击之后可以切换

**Comment by zanetti4** [comment]
这是在哪个分支？请提供使用卡片插件的具体代码

**Comment by ross-1** [comment]
[json.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3337880/json.txt)
请问分支怎么查

**Comment by zanetti4** [comment]
![image](https://user-images.githubusercontent.com/12883959/60325008-d64e5200-99b8-11e9-8d8d-c0db02fe7609.png)
vscode 里这个就是当前分支
你使用的具体是哪个插件？Card, MHCard, ModeCard? 使用该组件时的代码能提供给我吗？

**Comment by ross-1** [comment]
分支是10002
我根据官网教程，配置好json文件，黏贴到  我的-》设置-》调试入口-》支持本地卡片设置
[json.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3343591/json.txt)
![1561944180(1)](https://user-images.githubusercontent.com/17330001/60405299-dbdab080-9be1-11e9-82bc-95d0f3a7116c.jpg)

**Comment by ross-1** [comment]
json就是我上传的json.txt，忘记说了不好意思

**Comment by zanetti4** [comment]
@santcool 请你协助查看此问题，谢谢

**Comment by santcool** [comment]
请问能提供一个有此设备的账号吗？请发送到邮箱：zhangwenfeng@xiaomi.com。我们需要实际设备才能排查，谢谢！

**Comment by santcool** [comment]
无人回复，问题自动关闭，若还有问题，请重新提issue
