### ISSUE TITLE
StringSpinner在Android端选中项没有居中显示

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#1096]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0 
- 米家App:  5.5.30.6测试版
- SDK分支: 10021
- 相关模块: miot/ui/StringSpinner

**现象（必填）**
在Android端，StringSpinner选中项没有居中，在iOS端正常。

使用StringSpinnerDemo截图如下：

![image](https://user-images.githubusercontent.com/2813239/60315629-eacf2200-9999-11e9-858a-89e7fdb749f3.png)

![image](https://user-images.githubusercontent.com/2813239/60315572-9e83e200-9999-11e9-9af8-81b1eeea23ac.png)

**期望（必填）**
在Android端，StringSpinner选中项居中显示。

**Comment by evansherry** [comment]
android端的rowHeight行高设置无效，虚拟按键开放开关功能，或者直接关闭，mVirtualButtonPressedDrawable实在太丑了

**Comment by LiuMengzhou** [comment]
> android端的rowHeight行高设置无效，虚拟按键开放开关功能，或者直接关闭，mVirtualButtonPressedDrawable实在太丑了

android端的rowHeight行高固定了。
![image](https://user-images.githubusercontent.com/13726966/60637510-4cd1d080-9e4d-11e9-85b4-7efa147e800e.png)
```js
const rowHeight = 52;
const pickerContainerHeight = Platform.select({ android: rowHeight * 5, ios: 220 });
```
其余问题 @lvjie0519

**Comment by lvjie0519** [comment]
@fengdexunmi   已修复， 请使用最新apk进行测试
