### ISSUE TITLE
使用IPAD进入蓝牙搜索页面，背景图显示不全

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#1097]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）
手机系统:[iOS 12.2]
SDK分支: [master]
相关模块:[Video]

现象（必填）
1、使用IPAD进入米家APP，搜索“米兔声波电动牙刷”
2、点击“米兔声波电动牙刷”进入蓝牙搜索页面，背景图显示不全

期望（必填）
进入“米兔声波电动牙刷”蓝牙搜索页面，背景图显示完整

其他的上下文/日志/截图
正常：
![image](https://user-images.githubusercontent.com/48087638/60316589-bfe6cd00-999d-11e9-860b-7ce00f1c547f.png)
![image](https://user-images.githubusercontent.com/48087638/60316598-c70ddb00-999d-11e9-8d88-3cd2e05facdc.png)

异常：
![image](https://user-images.githubusercontent.com/48087638/60316608-cffeac80-999d-11e9-9a1f-c871d3bd9404.png)
![image](https://user-images.githubusercontent.com/48087638/60316612-d68d2400-999d-11e9-930c-177ff4e9c03d.png)

**Comment by Woody2016** [comment]
蓝牙设备快连页面在ipad上的适配问题

@pencilCool 抽时间修复下吧

**Comment by huangjr126** [comment]
@pencilCool 您好，想问下该问题的修复进度如何了？

**Comment by huangjr126** [comment]
@pencilCool 您好，因为项目准备封样，该问题属于必解问题，希望能尽快帮忙修复一下~感谢

**Comment by santcool** [comment]
已完成，在github首页下载最新调试包即可
