### ISSUE TITLE
Spec 获取属性值突然全部报错

### ISSUE THREAD

**Issue by xiaosheng-W** [MiEcosystem/miot-plugin-sdk#1098]
是否为新品（必填）
新品

关联的产品model
smith-blanket-cxma1

项目ID（必填）
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

企业名称（必填）
艾欧史密斯（中国）环境电器有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.0]
SDK分支: [eg.master/10000/...]
相关模块:[eg.Host/Service/Account]

现象（必填）
已经开发完毕进入测试阶段,下午开始全部报错

其他的上下文/日志/截图
错误日志:
{code: -704053100, siid: 2, did: "125183860", piid: 1}先收到100,无法设置设备状态
{code: -704053036, siid: 2, did: "125183860", piid: 1}接下来全部036超时,

尝试过的解决办法
确认app为preview环境,

**Comment by zanetti4** [comment]
这是在哪个分支？调用 Spec 获取属性值方法的具体代码能提供一下吗？

**Comment by xiaosheng-W** [comment]
> 这是在哪个分支？调用 Spec 获取属性值方法的具体代码能提供一下吗？

master 

调用:
let params = Spec.getPropertiesValue([
            {did: Device.deviceID, siid:2, piid:1},
            {did: Device.deviceID, siid:2, piid:2},
            {did: Device.deviceID, siid:2, piid:3},
            {did: Device.deviceID, siid:2, piid:4},
            {did: Device.deviceID, siid:2, piid:5},
            {did: Device.deviceID, siid:2, piid:6},
            {did: Device.deviceID, siid:4, piid:1},
        ]);

**Comment by santcool** [comment]
MIOT状态码（格式为: -70xxxyzzz）

xxx - HTTP标准状态码
y - 出现错误的位置
zzz - 执行错误码

所以，
第一个错误为：设备在当前状态下无法执行此操作
第二个错误为：设备操作超时

后续遇到这种问题，请在 [miot-spec文档](https://iot.mi.com/new/guide.html?file=07-%E4%BA%91%E5%AF%B9%E4%BA%91%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-%E5%BA%94%E7%94%A8%E4%BA%91%E5%AF%B9%E4%BA%91%E6%8E%A5%E5%85%A5/01-%E5%B0%8F%E7%B1%B3IOT%E6%8E%A7%E5%88%B6%E7%AB%AFAPI)的错误码部分查看。
