### ISSUE TITLE
Host.ui.openTimerSettingPageWithCustomIdentifier在iOS上使用问题

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1099]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 6/iOS 11.4.1]
SDK分支: [10021]
相关模块:[Host.ui.openCountDownPage]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
Host.ui.openTimerSettingPageWithCustomIdentifier传数组转化的string作为onParam和offParam的参数，创建的定时无法执行

期望（必填）
Host.ui.openTimerSettingPageWithCustomIdentifier在iOS上onParam和offParam能传数组为参数

在iOS和安卓上分别用以下代码创建定时：
Host.ui.openTimerSettingPageWithCustomIdentifier(
                PluginConfig.PlugTimerId,
                'toggle_plug',
                JSON.stringify([onoff, 'on']),
                'toggle_plug',
                JSON.stringify([onoff, 'off'])
              );

在安卓上**可以正常执行**，定时的参数为：
off_method:"toggle_plug"
**off_param: ["channel_0", "off"]**
off_time:"42 19 29 6 *"
on_method:"toggle_plug"
**on_param: ["channel_0", "on"]**
on_time:"42 19 29 6 *"

在iOS上**不能正常执行**，定时的参数为：
off_method:"toggle_plug"
**off_param:"["channel_0","off"]"**
off_time:"29 19 29 6 *"
on_method:"toggle_plug"
**on_param:"["channel_0","on"]"**
on_time:"29 20 28 6 *"

另外，如果是用openTimerSettingPageWithVariousTypeParams这个接口去创建定时的话，iOS可以用数组作为on_param和off_param的参数创建出正常的定时，但是这个接口不能自定义identify
代码如下：
Host.ui.openTimerSettingPageWithVariousTypeParams('toggle_plug', [onoff, 'on'], 'toggle_plug', [onoff, 'off']);

我们的旧设备会在定时以及倒计时里使用自定义的identify，为了兼容旧设备，我们希望可以自定义定时的identify。

其他：
1. 另外请问下应该怎么区分scene里的倒计时和定时呢?
    我们使用Device.loadTimerScenes()发现获取到的scene没有一些标志位用来区分倒计时和定时，所以除了我们在定时和倒计时上使用不同的自定义identify之外还能怎么区分倒计时和定时呢？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
这个位子只能传String。创造出来的定时没法用是什么意思？请提供抓包的结果，我们需要看看看看服务端返回的是什么错误。

**Comment by zanetti4** [comment]
文档里写着：

> deprecated 10004 开始废弃， 后续版本会移除该方法。
description 这个api 应该可以废弃了，使用下面的openTimerSettingPageWithVariousTypeParams

**Comment by zanetti4** [comment]
倒计时（openCountDownPage）和定时（openTimerSettingPageWithVariousTypeParams）传入的参数不同。

**Comment by xyliusun** [comment]
我更新了一下issue，增加了一些数据和描述，麻烦大家过目一下

@santcool 我们设备接口需要传多个参数，所以在onParam上是以数组的形式去传参，但是按照文档里将数组转成string后发现能正常创建定时，但是iOS的参数那里格式是不对的（参考上面描述）
在iOS上用openTimerSettingPageWithVariousTypeParams这个接口直接传数组的定时可以正常执行

@zanetti4 这个接口能不废弃吗？为了兼容一下旧插件我们想要自定义定时的identify，我们以前是根据这个identify去区分定时和倒计时的

**Comment by santcool** [comment]
我在openTimerSettingPageWithOptions里面增加了对identify的支持，加在了SDK_10022里面，今天将会发布。倒计时和定时本质上是同一个东西，所以我们这边包括服务端并没做一个区分，你可以按照你说的identify来做区分。
传参数，如果是string，需要传jsonString，在iOS上不能正常执行，你那个定时的参数不对，应该使用JSON.stringfy(xxxx).

**Comment by xyliusun** [comment]
const options = {
                onMethod: 'toggle_plug',
                onParam: JSON.stringify([onoff, 'on']),
                offMethod: 'toggle_plug',
                offParam: JSON.stringify([onoff, 'off']),
                displayName: '设置xxx定时',
                identify: PluginConfig.PlugTimerId
              };
Host.ui.openTimerSettingPageWithOptions(options);

已经切到了SDK_10022，代码如上，iOS效果如下：
![21_31_33__07_05_2019](https://user-images.githubusercontent.com/20435121/60725670-48e8a000-9f6c-11e9-9b8e-ba42bcaff2fc.jpg)

1. 自定义identify **PASS**
2. 传参数用JSON.stringify(xxxx) **FAIL**
3. 自定义name **FAIL**

可以麻烦支持一下传参数和自定义name吗

另附上安卓达到的正确预期效果:
![20190705213347](https://user-images.githubusercontent.com/20435121/60725809-97963a00-9f6c-11e9-9707-74304ae2a8e6.jpg)
