### ISSUE TITLE
miot/ui Dialog 相关组件疑问

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#110]
#### 环境
- 电脑操作系统: Mac
- 手机系统: Android iOS
- 相关模块: ui

#### 现象

使用时发现 MessageDialog 在 iOS 上没有任何展示；
LoadingDialog 在两端上实现有所差异，主要体现在 iOS 端大概 3 秒后自动 dismiss 了；
Android 的 ProgressDialog 看起来与 LoadingDialog 没啥区别 :confused:，iOS 则没有任何展示。

(ps: :eyes: 关于添加 label 的权限找谁申请呢？)

**Comment by JxXiaoXie** [comment]
同问

**Comment by pencilCool** [comment]
好的，我们正在修复

**Comment by LiuMengzhou** [comment]
@halloaw 十分抱歉，我以为label是公开权限的。

**Comment by dingshaoran** [comment]
ProgressDialog 可以显示进度 LoadingDialog不可以，  所有的 dialog 都加了 timeout属性，可以设置自动隐藏时间。

**Comment by halloaw** [comment]
文档没有 timeout 属性，可以更新一下。
`迁移手册.md` 中 Demo 有个错误。
```javascript
// new
 import {
   LoadingDialog,
   MessageDialog
-} from "miot/ui/MessageDialog";
+} from "miot/ui";
```
