### ISSUE TITLE
英文环境收到的烹饪完成推送是中文

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1100]
普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决
是否为新品（必填）
不是

关联的产品名称（必填）
“米家小饭煲”  “米家4L饭煲”

项目ID（必填）
项目ID

企业名称（必填）
上海纯米电子科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 8.00]
SDK分支: [10010]
相关模块:[UI]
现象（必填）
英文环境收到的烹饪完成推送是中文

期望（必填）
英文环境收到的烹饪完成推送是英文

**Comment by lvjie0519** [comment]
@joyami   
1、确认下推送的内容是否后台传递过来的？  后台推送的内容是否为英文？
2、截图看下具体显示。

**Comment by fishle** [comment]
请问推送这里是逻辑是怎样的：比如用的哪个接口来推送，推送的内容是怎么确定的，对于英文语言，是插件自己调客户端接口来判断吗？这里是拿到的系统语言不对还是什么问题，另外看客户端有一个配置表，但是不太清楚这里的推送逻辑，麻烦补充一下这些信息

**Comment by lvjie0519** [comment]
暂时关闭，如有问题再reopen。
