### ISSUE TITLE
iphone 6p 7p SE 播放视频出现黑影

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#1102]
**是否为新品（必填）**
在售

**关联的产品model**
此issue关联的产品model，如“philips.light.moonlight”

**项目ID（必填）**

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
mac os
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
master
- 相关模块:[eg.Host/Service/Account]
无

**现象（必填）**
播放视频时出现黑影如下图
![image](https://user-images.githubusercontent.com/17062182/60335540-c8a4c680-99d0-11e9-865b-4549c24d771c.png)

**期望（必填）**
播放视频时不出现黑影

**Comment by santcool** [comment]
看不出来啊，黑影在哪儿，能给个小视频吗？

**Comment by santcool** [comment]
请问问题还存在或者需要我们解决吗？

**Comment by santcool** [comment]
无人回复，此问题暂时关闭
