### ISSUE TITLE
【新品】【P19-0263】【云米】卡片概率性状态不更新，跟实际状态对应不上（概率约为10%）

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#1103]
新品

**关联的产品model**
viomi.vacuum.v7

**项目ID（必填）**
P19-0263

**企业名称（必填）**
云米

**环境（必填）**
- 手机系统:[eg.Android 8.1.0/iOS 10.3.3]
- SDK分支: [eg.master/10020/...]
- 相关模块:[卡片]
机型：红米6   MIUI版本： MIUI 10.2
机型：iphone6 plus

**现象（必填）**
前提条件：两台手机登录同一米家帐号，绑定设备
步骤：
两台手机都打开设备卡片页面，设备在充电中或待机状态；
等待3-5分钟左右，在一台手机上的设备卡片操作清扫，观察另一台手机上卡片状态

补充：该问题群里沟通过，根据log，反馈结果：没收到你这个设备的推送。
但是在该阶段，run_state属性是有上报到服务端的

**期望（必填）**
卡片状态能正常更新

log：
[卡片跟实际状态对不上.log](https://github.com/MiEcosystem/miot-plugin-sdk/files/3339561/default.log)

**Comment by flingInTheSky** [comment]
配置的卡片：[mijia_card_config.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3339635/mijia_card_config.txt)

**Comment by flingInTheSky** [comment]
补充：单纯只配置卡片状态显示，同一台设备，分享到多个账号，用多台手机打开APP 卡片，发现有的卡片更新状态，有的不更新。

更新后的卡片配置：
[mijia_card_config.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3357990/mijia_card_config.txt)

**Comment by lvjie0519** [comment]
Android  卡片问题，请 @丁绍然  看看

**Comment by flingInTheSky** [comment]
@lvjie0519 iOS 和Android都有几率出现这个问题

**Comment by santcool** [comment]
这个问题还存在吗？希望你这边能用三台手机调试。比如：1台iOS操作，另一台iOS和Android看是否能更新卡片。如果都无法更新，那肯定是上报失败了，如果有一端更新，另一端没更新，那应该就是其中某一端的问题。

**Comment by santcool** [comment]
没人回复，问题暂且关闭，如有需要，请重开issue
