### ISSUE TITLE
急！请教各位，TitleBarBlack组件怎么更改title的字体和颜色，为什么改不了？

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1104]
**是否为新品（必填）**
 新品 

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
优点cuber净水机

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9]
- SDK分支: [eg.master/10005/...]
- 相关模块:[Host/ui/TitleBarBlack]

**现象（必填）**
请问一下，TitleBarBlack组件怎么更改title的字体大小和颜色
![image](https://user-images.githubusercontent.com/28329423/60359350-6cab6380-9a0b-11e9-9535-3c3585c95323.png)

**期望（必填）**
希望可以更改组件的title的字体大小和颜色

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**Comment by LZCaaT** [comment]
![image](https://user-images.githubusercontent.com/28329423/60359774-9ca73680-9a0c-11e9-98d1-5e1cd4fc852a.png)
请问怎么更改title的字体大小和颜色，我在代码里更改了没有任何变化

**Comment by zanetti4** [comment]
> @deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.

这个组件已经不赞成使用了，TitleBar 能否满足你的需求？

**Comment by LZCaaT** [comment]
> > @deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.
> 
> 这个组件已经不赞成使用了，TitleBar 能否满足你的需求？

除了不能对title样式进行自定义，其他还行吧

**Comment by zanetti4** [comment]
@LiuMengzhou 该用户希望能够自定义 title 的样式，请查看

**Comment by LiuMengzhou** [comment]
**结论：title、subtitle不支持自定义样式**

你不是能看到组件的注释和源码吗？
注释
```js
/**
 * @export public
 * @doc_name 常用UI组件
 * @doc_index 23
 * @deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.
 * @module miot/ui/TitleBarBlack
 * @description 黑色标题栏
 * @property leftTextStyle 左侧文字样式，和 leftText 一起使用，不设置使用米家默认值
 * @property leftText 左侧文字
 * @property onPressLeft 左侧点击事件，设置了才显示左侧文字或图片，如果设置了leftText则显示设置的文字，否则显示默认的返回按钮。
 * @property onPressLeft2 左侧的第二个点击事件，设置了才显示默认的关闭按钮，
 * @property rightTextStyle 右侧文字样式，和 rightText 一起使用，不设置使用米家默认值
 * @property rightText 右侧文字
 * @property onPressRight 右侧点击事件，设置了才显示右侧文字或图片，如果设置了 rightText 则显示设置的文字，否则显示默认的更多按钮。
 * @property onPressRight2 右侧的第二个点击事件，设置了才显示默认的分享按钮
 * @property title 中间的标题
 * @property subTitle  中间的子标题
 * @property onPressTitle 点击标题的事件
 * @property showDot 是否显示右侧更多按钮的空点
 */
```
源码
```js
<View style={[styles.textContainer]}>
          <Text
            style={[styles.titleText]}
            onPress={this.props.onPressTitle}>{this.props.title}</Text>
          {
            this.props.subTitle ? <Text
              style={[styles.subtitleText]}
              onPress={this.props.onPressTitle}>{this.props.subTitle}</Text> : <View />
          }
        </View>
```

**Comment by LiuMengzhou** [comment]
之后将优化`NavigationBar`，允许自定义标题和副标题的样式。

**Comment by LZCaaT** [comment]
> 之后将优化`NavigationBar`，允许自定义标题和副标题的样式。

好的
