### ISSUE TITLE
Host.ui.openRoomManagementPage()在ios上打不开，调用没反应，安卓正常

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1105]
**是否为新品（必填）**
新品

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
优点cuber净水机

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9/iOS 11.0]
- SDK分支: [eg.master/10005/...]
- 相关模块:[eg.Host/ui/openRoomManagementPage]

**现象（必填）**
调用Host.ui.openRoomManagementPage();打开房间管理，安卓功能正常，ios打不开，调用没反应

**期望（必填）**
Host.ui.openRoomManagementPage()在ios上打不开，调用无效

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我用苹果手机测试，点击 miot-workspace/miot-sdk/ui/CommonSetting/CommonSetting.js 中的位置管理，能够成功跳转。你的手机测试这个 Demo 也打不开吗？打不开的时候有报错信息吗？

**Comment by santcool** [comment]
我这边Demo也是正常的，你可以跑一下demo看看，再就可以提供调用错误信息。
