### ISSUE TITLE
米家app里无法使用自定义的温控组件

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#1106]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
填 新品 or 在售

新品

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”

hisar.aircondition.klac

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
贵司的名称

杭州羿秦科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12
- SDK分支: [eg.master/10000/...] 10010
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。

自定义的组件无法使用

**期望（必填）**
简单明了地描述一下期望的表现。

希望能正常使用

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

![WechatIMG7](https://user-images.githubusercontent.com/8141398/60406567-11cf6300-9be9-11e9-9eb3-101c64d9f421.png)

[组件和调用js.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3343696/js.zip)

**尝试过的解决办法**
尝试过哪些操作？

尝试更新到最新的app和sdk也都是一样的情况

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
你的自定义组件是怎么使用的？报错信息里写着：
类型错误：试图分配只读属性。
可能是想要修改某个只读属性时，出了错。

**Comment by Aptx4869-xd** [comment]
就是正常的在render里面实现这个组件，然后就出错了，但是我在自己的demo里同样的代码和调用是没问题的，组件的调用和示例我在zip里有上传

**Comment by Aptx4869-xd** [comment]
@zanetti4

**Comment by Aptx4869-xd** [comment]
会不会和svg的版本有关系？我看米家里的svg版本是6.4.1，我demo里用的版本是9.4.0 @zanetti4

**Comment by zanetti4** [comment]
不好意思，之前没看见附件。有可能是版本问题，你在自己的 demo 里把 svg 降到6.4.1试试，看是否报同样的错误？

**Comment by Aptx4869-xd** [comment]
你好，我试了下6.4.1的版本，确实也是一样的问题，请问米家的svg版本可以升级吗？ @zanetti4

**Comment by Aptx4869-xd** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/8141398/60475733-60ddcc80-9cab-11e9-9090-3d8f22b92cbc.png)

我在6.4.1上调出现的是这个错误，好像是内部的问题

**Comment by Aptx4869-xd** [comment]
@zanetti4 请问这个问题目前是什么进度了？有什么解决方案吗？

**Comment by zanetti4** [comment]
我们将升级 react-native-svg，之后会回复你的

**Comment by Aptx4869-xd** [comment]
@zanetti4 好的

**Comment by Aptx4869-xd** [comment]
你好，我刚更新了下sdk，svg6.5.3的版本也还是一样的问题的，我是在svg9.5.1上跑是可以的 @zanetti4

**Comment by zanetti4** [comment]
@santcool 看样子版本升级的不够高，还能升级到更高版本吗？
