### ISSUE TITLE
Android界面卡死

### ISSUE THREAD

**Issue by JiuanZbf** [MiEcosystem/miot-plugin-sdk#1107]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

**是否为新品（必填）**
在售

**关联的产品model**
ihealth.bpm.kd5907

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
iHealth

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]              Android 8.1
- SDK分支: [eg.master/10000/...]                   master（10020）
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
插件上传到平台进行白名单测试时，使用线上版米家有时界面会卡死，返回按钮无效，反观ios版本不存在这种问题

**期望（必填）**
解决Android线上版卡死问题

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
切换过测试版app与正式版app,正式版会出现这个问题(Android)测试版没有这个问题

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@JiuanZbf  
1、线上版具体版本号多少？
2、开发者平台能否查看到对应的崩溃日志？

**Comment by JiuanZbf** [comment]
@lvjie0519 
1 线上版本为5.5.30
2 开发者平台查询不能只能看到老版插件

**Comment by lvjie0519** [comment]
1、线上版 5.5.30 支持的sdk api level  是10012；
2、目前线上包5.5.34支持的sdk api level 为10020；
3、你在开发者平台上打包的时候是不是选择了较低的 sdk api level？理论上，你选择10020版本打包，低版本apk是无法下载到你最新的插件包的。

**Comment by JiuanZbf** [comment]
@lvjie0519 我选择的sdk api level 为10020 打包平台显示的也是10020并且项目中的min_sdk_api_level也为10020

**Comment by JiuanZbf** [comment]
@lvjie0519 是否需要分享你一个设备？

**Comment by lvjie0519** [comment]
@JiuanZbf   可以，设备分享给 894158105， 同时说下设备名称

**Comment by JiuanZbf** [comment]
@lvjie0519 已共享，设备名称：九安智能血压计

**Comment by JiuanZbf** [comment]
@lvjie0519 额 有结果了吗。

**Comment by lvjie0519** [comment]
@JiuanZbf   我这边查询到， 使用线上版 5.5.30，下载的插件包是旧版原生插件，能够正常打开，你那边卡死是什么出现的？通过logcat查看下log日志看看。

**Comment by JiuanZbf** [comment]
@lvjie0519 应该是你这账号不在白名单中。我给你添加下我们设备的白名单，然后我这边尝试看看log日志 看看有没有结果

**Comment by lvjie0519** [comment]
@JiuanZbf   我的账号是白名单账号，上版 5.5.30  apilevel 为10012， 如果你开发者平台上没有打包过10012及低于改版本的插件包，5.5.30是下载不到的，只会下载到旧的原生插件。

**Comment by JiuanZbf** [comment]
@lvjie0519 我现在用的线上版本也是5.5.30 但是是可以下载到的 这个是否与我是开发者账号有关呢。

**Comment by JiuanZbf** [comment]
@JiuanZbf 我这边换了个低版本android设备(Mi MAX2;MIUI 9.6稳定版) 用的线上版米家5.5.30是会出现卡死状态的，我这边打了下log看到一个错误是

**Comment by lvjie0519** [comment]
@JiuanZbf   你这个log日志都是属于原生插件的范畴，如果没有复现，就关闭issue吧

**Comment by JiuanZbf** [comment]
@lvjie0519 最新的线上版确实是没有问题了
