### ISSUE TITLE
标记符：JT  状态栏不根据TitleBar的type改变而变化

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#1108]
- IPA/APK 是否更新到最新？ 是
- SDK 是否更新到最新？不是 10011
- Check 文档了吗？ 是的
- 是否尝试搜索issue？ 和其他情况不大一样，且没有好的方法。

---
**是否为新品（必填）**    不是
填 新品 or 在售     在售

**关联的产品model**
minij.washer.v8
此issue关联的产品model
minij.washer.v8

**项目ID（必填）**
minij.washer.v8

**企业名称（必填）**
小吉科技

**环境（必填）**
- 电脑操作系统:[eg.Window]
- 手机系统:[eg.Android 9.0/iOS 11.0]
- SDK分支: [eg.master/10011/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
当TitleBar写在render中从light => dark 顶部状态栏还是light下的状态栏，白色背景下显示不了。

**期望（必填）**
TitleBar的Type切换，状态栏也变化。或者统一成黑色。

**其他的上下文/日志/截图**

**尝试过的解决办法**
尝试过哪些操作？
不在render中设置TitleBar是正常的。
**不要贴大段代码❗️**
[视频.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3344480/default.zip)

**Comment by zanetti4** [comment]
既然不在render中设置TitleBar是正常的，为什么非要写在 render 中呢？

**Comment by hao0000** [comment]
> 既然不在render中设置TitleBar是正常的，为什么非要写在 render 中呢？

需要定制啊，背景图要包裹TitleBar,不然效果就我发你的正常视频那样，而且需要props来获取属性显示洗涤状态。不定制好像不行。

**Comment by hao0000** [comment]
这个明显有bug吗，刚看了下其他公司也有遇到。而且会有其他关联问题，有时状态变化太多页面刷新，状态栏会有闪烁问题，黑白切换。

**Comment by zanetti4** [comment]
Duplicate of #1070

**Comment by hao0000** [comment]
我们用replace进入其他页面也能解决状态栏为白色不变色的问题，但是会有其他问题出现，有时候状态栏会呈现出黑白文字切换闪烁的情况。

**Comment by hao0000** [comment]
[demo效果.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3400438/demo.zip)
把你们demo中的Title改成写在render中，返回后状态栏也不会切换。或许可以统一成黑色，就没有这些问题。
