### ISSUE TITLE
createProject error: the package is exist or invalid package name

### ISSUE THREAD

**Issue by LeslieMiau** [MiEcosystem/miot-plugin-sdk#111]
#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 12.1
- 相关模块:[eg.Host/Service/Account]

#### 现象

依据文档：[文档戳我] (https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/README.md#%E5%91%BD%E4%BB%A4) 

错误步骤：创建项目
`npm run create -- --id <plugin_id> --models xxx.xxx.x1|xxx.xxx.x2 xxx.yyy.zzz`

结果：错误显示
`the package is exist or invalid package name`

前置操作：
1. 在 *projects* 下新建项目 xxx.yyy.zzz（该项目名即为开放平台申请的扩展程序包名）
2. 在新项目下按照文档进行操作

#### 期望

期望项目创建成功，通过
启动调试

`npm start`

可以正确运行

#### 其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/14228343/49570761-79367480-f972-11e8-8dad-f9683232a62c.png)

#### 尝试过的解决办法

尝试过哪些操作？

在老项目中同样操作成功

**Comment by LiuMengzhou** [comment]
`the package is exist or invalid package name`

前置操作：

在 projects 下新建项目 xxx.yyy.zzz（该项目名即为开放平台申请的扩展程序包名）
在新项目下按照文档进行操作

----
@LeslieMiau 删除前置操作，就是说：把自己手动新建的文件夹 xxx.yyy.zzz 删掉，脚本会自动创建文件夹。

**Comment by LeslieMiau** [comment]
@LiuMengzhou 感谢 解决了
