### ISSUE TITLE
关于在米家通用设置CommonSetting中如何加入按钮的问题

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#1111]
---
**是否为新品（必填）**
在售

**关联的产品model**
com.lfwellness.LF_LT001

**项目ID（必填）**
乐班智能电动升降台

**企业名称（必填）**
乐范健康有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: 10020
- 相关模块:ui

**现象（必填）**
我需要在设置页面添加一个有关我我们儿童锁的开关。不知道在安卓中改如何添加

**期望（必填）**
在安卓的设置页面可以添加一行开关

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43639032/60438146-969a9b00-9c42-11e9-9f06-600cadca14d3.png)

**尝试过的解决办法**
不知道米家插件通用设置-CommonSetting可以完成这个要求吗

**不要贴大段代码❗️**

**Comment by 1076815296** [comment]
还有一个问题   CommonSetting中是否无法传值？

**Comment by LiuMengzhou** [comment]
1. +按钮的问题，请查阅文档说明[米家通用设置项](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

2. 传什么值？

**Comment by 1076815296** [comment]
传一些固件版本，是否更新的值到更新界面。  还有按钮对应的方法
![image](https://user-images.githubusercontent.com/43639032/60487508-71556d80-9cd2-11e9-9556-6dfabe1d257c.png)

**Comment by 1076815296** [comment]
传一些固件版本，是否更新的值到更新界面
![image](https://user-images.githubusercontent.com/43639032/60487667-98ac3a80-9cd2-11e9-8852-c8a3e87bf968.png)

**Comment by LiuMengzhou** [comment]
你先把文档看完吧

**Comment by 1076815296** [comment]
文档是看完了  他这里面只有关于跳转 没有传值到自定固件升级的能力  也就是没有？

**Comment by LiuMengzhou** [comment]
> 文档是看完了 他这里面只有关于跳转 没有传值到自定固件升级的能力 也就是没有？

我理解是有自己的固件升级页面？那你可以在固件升级页面获取这些值
