### ISSUE TITLE
图片分享modal在ios上取消回调问题

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#1112]
**是否为新品（必填）**
新品

**企业名称（必填）**
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
mac
- 手机系统:[eg.Android 8.1/iOS 11.0]
ios 12.1
- SDK分支: [eg.master/10000/...]
10020

**现象（必填）**
因业务需要，需要监听分享图片取消和失败在RN上的回调。目前不能监听回调

**期望（必填）**
期望能收到取消分享和分享失败的回调。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/11881751/60476548-9d5ef780-9cae-11e9-8bf7-f1a2ff4660f6.png)

android和ios都需要提供

**Comment by zanetti4** [comment]
请给出相关模块及使用代码

**Comment by evansherry** [comment]
@zanetti4 是的，使用Host.ui.openShareListBar接口会弹出分享modal，取消分享或者分享失败没有回调

**Comment by santcool** [comment]
现在微信分享是不会提示你成功还是失败的，所以我们统一没有给分享失败的回调。至于取消分享，因为分享结果本来就是拿不到的，所以我们认为这个事件让开发者知道的必要性也不大。当然你们如果真的有这方面的需求，可以跟对接你们的产品沟通下，让他给我们组提个需求。

**Comment by evansherry** [comment]
@santcool 我这边需求是这样的，分享的截图部分控件不应该显示，所以点击分享后需要先隐藏部分控件，然后再截图分享，如果用户分享取消，插件没办法获取取消的回调，这时候本来应该让隐藏的控件显示出来，现在没办法实现该功能。如果不能提供取消回调，你那边有什么好的建议吗？

**Comment by evansherry** [comment]
@santcool @zanetti4 麻烦给回复一下，谢谢
