### ISSUE TITLE
灯组中，更多设置点击后无反应（iOS和Android都会）

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1113]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [10020]
- 相关模块:[]

**现象（必填）**
灯组中，更多设置点击后无反应（iOS和Android都会）
![image](https://user-images.githubusercontent.com/5188922/60477818-00528d80-9cb3-11e9-943c-fb0099155791.png)
![image](https://user-images.githubusercontent.com/5188922/60477821-047eab00-9cb3-11e9-8d5f-3dcc1b373ee5.png)

Android中，调用编辑灯组接口（Host.ui.openEditDeviceGroupPage(array);），点击无反应
![image](https://user-images.githubusercontent.com/5188922/60477822-08aac880-9cb3-11e9-828f-34457d8dcbe7.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/60481032-5bd64880-9cbe-11e9-9814-fe30eab60e17.png)

[米家通用设置项说明](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

**Comment by LiuMengzhou** [comment]
> Android中，调用编辑灯组接口（Host.ui.openEditDeviceGroupPage(array);），点击无反应

这条需要询问 @lvjie0519

**Comment by Aub1nLin** [comment]
> ![image](https://user-images.githubusercontent.com/13726966/60481032-5bd64880-9cbe-11e9-9814-fe30eab60e17.png)
> 
> [米家通用设置项说明](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

就是调用你们的通用设置项，然后不能用。你们先看一下你们自己的这块接口有没有问题，
就是，设备是可以进入到更多设置，但是设备组不行。

**Comment by LiuMengzhou** [comment]
Duplicate of #951

**Comment by lvjie0519** [comment]
@mirse   
1、ios是否可以跳转？
2、设备分享给 894158105， 同时告知下参数，我这边测试下。

**Comment by fishle** [comment]
长时间没回复，先关单，如果还有问题麻烦先回复楼上的问题，特别是给出详细的调用参数
