### ISSUE TITLE
米家智能日志提示 智能不存在

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#1117]
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
“lumi.acpartner.v2”,“lumi.gateway.lmuk01”,“lumi.gateway.mgl03”

**项目ID（必填）**
22538, 15283, 21291

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
绿米插件内创建的智能，定时 执行成功后，在米家APP的 智能页 查看日志点击
会提示 当前智能不存在

此问题涉及绿米全系产品

**期望（必填）**
提示能够更友好，实际 智能在插件内是存在，且会继续执行

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/15864191/60480798-8a075880-9cbd-11e9-8c25-38756439a9df.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
这个是不是之前和你们聊过，因为你们创建的智能type和我们普通的不一样，造成在我的页面和智能页面的功能异常

**Comment by damiknows** [comment]
需要PM评估如何处理
