### ISSUE TITLE
TitleBarBlack标题2行英语时在红米K20 PRO上显示不全

### ISSUE THREAD

**Issue by TianGuisen** [MiEcosystem/miot-plugin-sdk#1118]
sdk:1.0.20
```
 <TitleBarBlack style={{zIndex: 99999}} title={Device.name}
                                   onPressLeft={() => {
                                       this.props.navigation.goBack();
                                   }}/>
```
title长度显示到2行时候,在红米K20 PRO上第二行下边会显示不全

在售

model:090615.plug.plus02

**Comment by zanetti4** [comment]
> @deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.

用 TitleBar 是否存在此问题？

**Comment by TianGuisen** [comment]
> > @deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.
> 
> 用 TitleBar 是否存在此问题？

titleBar是只有一行,超出一行的末尾用3个点代替

**Comment by zanetti4** [comment]
这样能否满足你的需求？

**Comment by TianGuisen** [comment]
> 这样能否满足你的需求？

![image](https://user-images.githubusercontent.com/19662707/60633046-81d52780-9e3b-11e9-9389-a6d6a7e3b988.png)
用titlebar,状态栏会这样.

**Comment by zanetti4** [comment]
Duplicate of #954 
你这个问题也是状态栏下移，看看954最后的方案能否解决你的问题？
