### ISSUE TITLE
IOS下， 蓝牙连接断开的接口 无效

### ISSUE THREAD

**Issue by Kimbleed** [MiEcosystem/miot-plugin-sdk#1119]
**是否为新品（必填）**
新品

**关联的产品model**
loock.lock.v5, loock.lock.v6....等直至loock.lock.v11，多款门锁

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
只列举两个  1170、1257

**企业名称（必填）**
云丁网络技术（北京）有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3.1
- SDK分支: [eg.master/10021/...]
- 相关模块:[Bluetooth]

**现象（必填）**
IOS 端，调用 Device.getBluetoothLE().disconnect(0)，不会断开蓝牙。Android无此问题

**期望（必填）**
能正常蓝牙断开

**尝试过的解决办法**
Device.getBluetoothLE().disconnect()试过不传参，传0，传1000 ，都没用

**Comment by WeizhiKong** [comment]
+1

**Comment by pencilCool** [comment]
请先排除蓝牙设备的实例是不是获取错了：
参考：https://github.com/MiEcosystem/miot-plugin-sdk/issues/1201
