### ISSUE TITLE
ipa包更新了，但是sdk好像还没有更新吧，我看还是10020😂

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1121]
是否为新品（必填）
在售

关联的产品model
miaomiaoce.thermo.t10

项目ID（必填）
913

企业名称（必填）
秒秒测

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 9/iOS 12]
SDK分支: [eg.master/10020/...]
现象（必填）
 在sdk代码中没有找到NavigationBar相关的代码，是不是没有更新呢？
如果sdk没有更新的话，是不是还是不能调用相关的代码，还有CommonSetting的红点设置
#1120 

期望（必填）
更新一下代码啦

**Comment by santcool** [comment]
github这个你需要切换到SDK_10022分支。现在这个分支并没有合入master

**Comment by Android-yzhang** [comment]
切换到10022分支，也能看到NavigationBar的源码了，但是运行还是报错，提示Cannot read property 'TYPE' of undefined,我的ipa包是今天早上下载的，能看到是上午10点才上传的

**Comment by Android-yzhang** [comment]
miot/ui/index没有加上NavigationBar，所以需要单独引用miot/ui/NavigationBar。
但是依然运行不了，提示Cannot read property 'light' of undefined，我这边还在排查

**Comment by Android-yzhang** [comment]
发现问题了：在'miot/resources/Images'，获取不到 Images.navigation，虽然在代码中有

**Comment by Android-yzhang** [comment]
commenSetting的showdot也没有

**Comment by santcool** [comment]
小红点10021上就开始支持了。

**Comment by Android-yzhang** [comment]
var showDot = [
        first_options.FIRMWARE_UPGRADE
      ]

<CommonSetting
            navigation={this.props.navigation}
            firstOptions={firstOptions}
            secondOptions={secondOptions}
            extraOptions={extraOptions}
            showDot={showDot}
          />

**Comment by Android-yzhang** [comment]
我的设置是直接挪过来的，应该没有写错吧

**Comment by zanetti4** [comment]
@LiuMengzhou 协助看一下小红点儿的问题，js 代码似乎没写错。

**Comment by LiuMengzhou** [comment]
@Android-yzhang 
你说的报错是线上报错还是本地调试报错？
@zanetti4 
在SDK_10022分支下，拉去最新代码，然后运行com.xiaomi.demo
点击右上角进入设置，可以看到列表项显示小红点；
点击「常用功能」-「新版导航栏」，可以看到正常运行显示；

**Comment by LiuMengzhou** [comment]
有啥问题，先运行一下demo看看

**Comment by Android-yzhang** [comment]
本地调试报错，我看了下代码都有，但是调试获取不到，可以看一下我上面提到的线索

**Comment by Android-yzhang** [comment]
刚用Android的试了一下，都是正常的，iOS还是不行，iOS图标上面的数字是2221 @LiuMengzhou

**Comment by LiuMengzhou** [comment]
> 刚用Android的试了一下，都是正常的，iOS还是不行，iOS图标上面的数字是2221 @LiuMengzhou

@santcool 和DB有关系？

**Comment by santcool** [comment]
我也试着没问题啊，你试试删除本地的SDK_10022分支，重新拉取，然后pod install后，再运行试试。
按照LiuMengzhou的方法，看看Demo里面的Navigationbar是否能正常执行

**Comment by LiuMengzhou** [comment]
> 我也试着没问题啊，你试试删除本地的SDK_10022分支，重新拉取，然后pod install后，再运行试试。
> 按照LiuMengzhou的方法，看看Demo里面的Navigationbar是否能正常执行

@santcool npm install...

**Comment by Android-yzhang** [comment]
刚才试了一下，已经可以了😂，我也不知道是为什么

**Comment by Android-yzhang** [comment]
我刚把sdk版本切回master，再切回10022，又不行了 @LiuMengzhou

**Comment by santcool** [comment]
切了后，执行下npm install。再要是报错了，给一下报错的错误信息
