### ISSUE TITLE
无RN插件跳转有品首页的api

### ISSUE THREAD

**Issue by LavieLumi** [MiEcosystem/miot-plugin-sdk#1122]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

**是否为新品（必填）**
在售

**关联的产品model**
lumi.gateway.v3

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
21291

**企业名称（必填）**
深圳市绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1/iOS 11.0
- SDK分支: 10020
- 相关模块:Host

**现象（必填）**
插件无添加子设备时，需要引导用户跳转到有品首页做一个引流

**期望（必填）**
提供一个RN插件跳转有品首页的api

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
@LavieLumi 
直接打开有品的一个购买页面行吗？

**Comment by LavieLumi** [comment]
@Woody2016
当前做的是网关插件，子设备挺多的，如可以的画话，可以提供跳转到如智能家庭这样的有品商城的购买页面，更有针对性

**Comment by LavieLumi** [comment]
@Woody2016
当前做的是网关插件，子设备挺多的，如可以的话，可以提供跳转到如智能家庭这样的有品商城的购买页面，更有针对性

**Comment by LavieLumi** [comment]
@Woody2016 
你好，请问现在进度怎么样了

**Comment by LavieLumi** [comment]
@Woody2016 
可以直接给一个热搜页面么，比如说我传人体传感器、无线开关、门窗传感器给你，然后就跳到有这三个产品的页面，相当于搜索后的页面

**Comment by Woody2016** [comment]
有热搜页，url形如：https://home.mi.com/search?keyword=扫地

**Comment by LavieLumi** [comment]
你的意思是让我们用WebView显示这个url?

**Comment by LavieLumi** [comment]
miot/host/ui.openWebPage(url)
打开H5页面 不对外提供

**Comment by LavieLumi** [comment]
@zanetti4 @Woody2016  
你好，这个网关插件这周四提测，现在就差这一个功能了，能不能帮忙尽快解决

**Comment by LavieLumi** [comment]
@zanetti4 @Woody2016 
新给出来的openShopSearchPage内容能够符合需求，但是存在适配问题
![image](https://user-images.githubusercontent.com/50569278/61801128-d713c000-ae60-11e9-8c61-a66cbb2e60a6.png)

**Comment by LiuMengzhou** [comment]
@LavieLumi SDK_10025 已经解决
fbbfcba

**Comment by LiuMengzhou** [comment]
你切换分支，测试一下。

**Comment by LavieLumi** [comment]
已验证OK
