### ISSUE TITLE
SDK_10020 Device->getLinkedBTDevices()无法获取数据 #815

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#1123]
公司名称（必填）
Yeelight

是否为新产品（必填）
是

产品名称/Model（必填）
Yeelight蓝牙网关/yeelink.gateway.v1

环境（必填）

电脑操作系统:[Windows/Mac OS/Linux]
手机系统:[Android 8.1/iOS 11.0]
SDK分支: [10020]
相关模块:[Device]
现象（必填）
无法获取蓝牙网关设备连接数

期望（必填）
提供能够分别获取连入蓝牙网关的普通蓝牙设备数和蓝牙mesh设备数的接口。

**Comment by RowingCaptainChen** [comment]
关联issues #815

**Comment by zanetti4** [comment]
你在使用 getLinkedBTDevices() 方法时，返回什么？是否报错？

**Comment by RowingCaptainChen** [comment]
<img width="436" alt="屏幕快照 2019-07-04 下午6 54 35" src="https://user-images.githubusercontent.com/17311448/60662072-fb960100-9e8d-11e9-8ca4-cd7d2fd8641d.png">
可以取到了 多谢啦

**Comment by RowingCaptainChen** [comment]
> 你在使用 getLinkedBTDevices() 方法时，返回什么？是否报错？



> 你在使用 getLinkedBTDevices() 方法时，返回什么？是否报错？

<img width="436" alt="屏幕快照 2019-07-04 下午6 54 35" src="https://user-images.githubusercontent.com/17311448/60662194-4dd72200-9e8e-11e9-8d42-6b37a46bbaee.png">
可能是固件问题 现在可以取到了 多谢啦
