### ISSUE TITLE
IOS 手机属性控制失败，会报code   -704090001 错误

### ISSUE THREAD

**Issue by caoguoli** [MiEcosystem/miot-plugin-sdk#1126]
**是否为新品（必填）**
 新品 

**关联的产品model**
deye.derh.u20a3

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
宁波德业日用电器科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[eg.iOS 12.2]
- SDK分支: [10004]
- 相关模块:[EMW3080BP]

**现象（必填）**
苹果手机，点击控制属性，会控制失败，固件接收不到数据，会报 code   -704090001。

**期望（必填）**
苹果手机，点击控制属性，固件接收到数据，成功将数据返回给页面。

**其他的上下文/日志/截图**
调用接口：Service.spec.setPropertiesValue
返回数据打印截图如下：http://loc.dingtalk.com/QzpcVXNlcnNcbXhjaGlwXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w0MzU5NDM1NzNfdjJcSW1hZ2VGaWxlc1wxNzQyMzJcMTU2MjE0NDY0NzAyNjI1RkMyQkY2LUVENjItNGMwNS04MzQ2LTA5QTEzNjhCQjFGRS5wbmc=

**Comment by santcool** [comment]
请参考[常见问题](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)里面：文档miot-spec属性获取或者设置失败的问题
