### ISSUE TITLE
Android手机显示文字异常

### ISSUE THREAD

**Issue by JiuanZbf** [MiEcosystem/miot-plugin-sdk#1127]
**是否为新品（必填）**
 在售

**关联的产品model**
ihealth.bpm.kd5907

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
iHealth

**环境（必填）**
电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
手机系统:[eg.Android 8.1/iOS 11.0] Android 6.0.1
SDK分支: [eg.master/10000/...] master（10020）
相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android上Text显示不全

**期望（必填）**
正常显示

**其他的上下文/日志/截图**
android手机不加空格
![image](https://user-images.githubusercontent.com/48681089/60636573-acc67800-9e49-11e9-9ebf-9c3bc209ab7f.png)
ios手机
![image](https://user-images.githubusercontent.com/48681089/60636599-c2d43880-9e49-11e9-98ad-579aa8d7cb67.png)
Android 手机加空格后
![image](https://user-images.githubusercontent.com/48681089/60636613-d2538180-9e49-11e9-9c54-fe4feba547ac.png)

**尝试过的解决办法**
在文字后面多加一个空格就能显示出来

**Comment by LiuMengzhou** [comment]
| 结论                          | 原因                                                         | 推荐做法                                                     | 测试case                     |
| ----------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ---------------------------- |
| lineHeight谨慎使用            | 某些字体的中、英、数字的baseline不同                         | 如果baseline差距不大，推荐加上lineHeight；否则不设置lineHeight，但是不能设置为0（Android上Text将不显示，iOS无碍） | ‘测试ABCabc123'              |
| 多行文案时line Height需要微调 | 设置line Height后，Android上多行文字的第一行和最后一行可能显示不全 | 手动微调                                                     | 一段长文案                   |
| color一定要设置               | 在Android平台上，不指定color将使用系统默认的字体颜色         | 使用「#+6位Hex」’#ffffff’                                    | 不同品牌型号的安卓手机       |
| 必要时设置width               | Android上Text如果没设置字体，那么较长的英文文案将显示不全，并不能自由撑开 | 如果不设置字体，那么最好设置wdith以规定文字显示区域。需要居中可以设置textAlign | ‘abcdefghijklmnopqrstuvwxyz’ |
| numberOfLines一定要设置       | 默认行为不可控，可能折行，可能溢出                           | 设置numberOfLines                                            | 一段长文案                   |
|                               |                                                              |                                                              |                              |

**Comment by JiuanZbf** [comment]
设置了一下width可以是可以了 但是这么写有点麻烦啊。。。

**Comment by zanetti4** [comment]
或许和你的安卓系统版本过低有关，能够解决问题才是最重要的，不是么
