### ISSUE TITLE
插件提示设备离线后，按Back键无反应

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#1128]
---
**是否为新品（必填）**
填  在售

**关联的产品model**
yueme.airmonitor.mhfd1

**企业名称（必填）**
Honeywell

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1

![IMG_2766](https://user-images.githubusercontent.com/37297126/60640903-e607e380-9e5b-11e9-9aba-9c1a8835096c.png)

]
- SDK分支: [10010]
- 相关模块:[离线弹框]

**现象（必填）**
1、进入插件页面后，系统提示设备离线，点击“关闭”后，Back键失效，无法退出插件页面。
2、设备离线弹框太快

**期望（必填）**
Back键可以退出插件页面

**其他的上下文/日志/截图**

[WeChatSight16.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3357692/WeChatSight16.mp4.zip)

**Comment by lvjie0519** [comment]
@EllisonYe  
1、看下log日志代码是否出现了异常？所有手机点击都无效吗？
2、设备分享给894158105，我这边看下。

**Comment by EllisonYe** [comment]
设备已经分享给894158105

**Comment by fishle** [comment]
这边重试了离线的情形，可以正常退出，请用最新的米家APP试一下
