### ISSUE TITLE
Video error

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#1129]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 8.0/小米5，ANdroid5.1/oppo r9m]
SDK分支: [master]
相关模块:[Video]
现象（必填）
加载视频回调onError。
小米5下设置视频资源为网络或者本地都显示'onError:', { error: { extra: 0, what: 100 } }
oppo r9m下设置视频资源为本地显示'onError:', { error: { extra: -2147483648, what: 1 } }，设置资源为网络资源则没有问题。

使用miotsdk中的videoDemo，播放demo默认视频都没有问题。

期望（必填）
可否提供错误码的文档查看错误和建议如何修改。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/14890491/60640918-f91ab380-9e5b-11e9-8e23-c09171944020.png)
![image](https://user-images.githubusercontent.com/14890491/60640923-0041c180-9e5c-11e9-91e3-d885f82c8fcd.png)

尝试过的解决办法

**Comment by zanetti4** [comment]
1. 建议换一个视频试试。
2. 仔细对比你的代码和 videoDemo 中的不同之处，进行排查。
若问题依旧，请贴出你的使用代码。没有找到错误码的文档。

**Comment by lijian9088** [comment]
在videoDemo中，替换url为我们自己的视频资源，在小米5下也是显示'onError:', { error: { extra: 0, what: 100 } }。在oppo r9m下，使用url网络播放可以正常显示。
在我们自己的插件中，小米5无论是url还是本地播放，都报'onError:', { error: { extra: 0, what: 100 } }。
oppo r9m下，使用url网络播放可以正常显示，但是下载到本地就不能使用，报'onError:', { error: { extra: -2147483648, what: 1 } }。
代码如下：
![image](https://user-images.githubusercontent.com/14890491/60662787-eb7f2100-9e8f-11e9-8034-dae2db277dcd.png)
![image](https://user-images.githubusercontent.com/14890491/60662829-018ce180-9e90-11e9-9070-158101bcd0d0.png)

**Comment by zanetti4** [comment]
@lvjie0519 请你协助查看一下，是不是他的视频资源有问题？

**Comment by lvjie0519** [comment]
@lijian9088   用com.xiaomi.demo中的视频资源是否有问题？

**Comment by lijian9088** [comment]
demo下的资源没有问题

**Comment by zanetti4** [comment]
建议你换一个你单位的其它视频试试，可能是你的视频资源有问题，如果真是如此，我们也无能为力……

**Comment by lvjie0519** [comment]
@lijian9088   建议你那边排查下视频资源，谢谢。
