### ISSUE TITLE
建议：APP内置更新自检测功能

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#113]
能确保APP实时更新到最新版，省去每天要去网站查询是否有新版本
@kyou @Copypeng

**Comment by dingshaoran** [comment]
android release 版本的 app 本身是有更新功能的，debug 版本没有，如果自动更新了，因为 app 的功能不完善导致插件有 bug不好排查

**Comment by LiuMengzhou** [comment]
@edwardair 十分抱歉，由于调整native代码，需要频繁更新APP。我们尽快使app稳定。

**Comment by edwardair** [comment]
说到android版，包名居然是跟上架版本相同的。。。然后，应用商店开了APP自动更新机制，隔天过来查来查去见不到“开发模式”，才想起可能APP被自动更新到了release版本
