### ISSUE TITLE
Android 调用 Host.ui.privacyAndProtocolReview 显示问题

### ISSUE THREAD

**Issue by JiuanZbf** [MiEcosystem/miot-plugin-sdk#1130]
**是否为新品（必填）**
 在售

关联的产品model
ihealth.bpm.kd5907

项目ID（必填）
【无项目ID】

企业名称（必填）
iHealth

环境（必填）
电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
手机系统:[eg.Android 8.1/iOS 11.0] Android 6.0.1
SDK分支: [eg.master/10000/...] master（10020）
相关模块:[eg.Host/Service/Account]

**现象（必填）**
调用Host.ui.privacyAndProtocolReview后进入的界面的titleBar没有标题

**期望（必填）**
希望与ios版本一致

**其他的上下文/日志/截图**
Android 上显示无标题
![image](https://user-images.githubusercontent.com/48681089/60641943-a1327b80-9e60-11e9-847e-3640a745a8a9.png)
Ios 上有标题
![image](https://user-images.githubusercontent.com/48681089/60641951-aa234d00-9e60-11e9-95b7-a284e672b41e.png)

**尝试过的解决办法**
更新到最新测试包

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
Duplicate of #1014 
该问题正在修复中……
