### ISSUE TITLE
sdk apiLevel(10020)  !== 米家 apiLevel (10021)

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#1131]
**是否为新品（必填）**
在售

**企业名称（必填）**
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.1
- SDK分支: [eg.master/10000/...]
10020
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
如题所示，米家线上apiLevel 为10021，但是sdk master分支apiLevel为10020。目前迁移插件需要在10021分支环境，请问什么时候可以合并master分支。

**期望（必填）**
当前master分支为10021和米家线上同步。

**Comment by zanetti4** [comment]
Duplicate of #1121

**Comment by santcool** [comment]
已合入
