### ISSUE TITLE
iOS 收到消息推送, 米家 app 里面的 "我的"->"消息中心" 不显示红点提醒, 安卓会有红点显示

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#1132]
---
**是否为新品（必填）**
填 新品 or 在售
新品
**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
dmaker.airfresh.a1
**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
贵司的名称
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。
我在米家 Iot 平台创建的消息推送, 推送给 app 后,  米家 app 里面的" 我的"---> "消息中心"( 后面并不会显示红点提醒),  安卓手机则有红点提醒.

**期望（必填）**
简单明了地描述一下期望的表现。
有消息推送时,  米家 app 里面的" 我的"---> "消息中心" 有红点提醒.
**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/16514238/60643221-f1abd800-9e64-11e9-8608-5fd2ec02a501.png)
![image](https://user-images.githubusercontent.com/16514238/60643226-f6708c00-9e64-11e9-86d6-cd4f7dd2039e.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
已有同事在处理这个，但因为不一个组，排期未知。暂且在此处同步下消息

**Comment by santcool** [comment]
已完成。
