### ISSUE TITLE
洗衣过程动画有时点击返回无效，其他按钮可正常点击

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#1133]
**是否为新品（必填）**
 在售

**关联的产品model**
minij.washer.v8

**项目ID（必填）**
minij.washer.v8

**企业名称（必填）**
小吉科技

**环境（必填）**
- 手机系统:Android 8.0.0/iOS 12.2
**现象（必填）**
洗衣过程动画中，有时点击返回键无效，此时其他按钮正常。

**期望（必填）**
每次点击返回都可以正常

**其他的上下文/日志/截图**

**尝试过的解决办法**
看了下打印，没有问题

**不要贴大段代码❗️**

**Comment by hao0000** [comment]
返回用的是Package.exit();

**Comment by hao0000** [comment]
[视频.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3357995/default.zip)

**Comment by lvjie0519** [comment]
@hao0000   Android有问题吗？

**Comment by hao0000** [comment]
暂时只有IOS出现过两次




------------------ 原始邮件 ------------------
发件人: "小米-吕杰"<notifications@github.com>; 
发送时间: 2019年7月5日(星期五) 下午4:26
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>; 
抄送: "hooo"<987158014@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MiEcosystem/miot-plugin-sdk] 洗衣过程动画有时点击返回无效，其他按钮可正常点击 (#1133)




@hao0000   Android有问题吗？

**Comment by santcool** [comment]
你用最新的包试一下，这个bug应该已经已经解决了

**Comment by hao0000** [comment]
好的------------------ 原始邮件 ------------------
发件人: "米家-iOS-张文锋"<notifications@github.com>
发送时间: 2019年7月11日(星期四) 下午3:12
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "hao0000"<987158014@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] 洗衣过程动画有时点击返回无效，其他按钮可正常点击 (#1133)



你用最新的包试一下，这个bug应该已经已经解决了
 
&mdash;

**Comment by santcool** [comment]
还有问题吗，如果没有，请关闭此问题
