### ISSUE TITLE
bluetooth connect 无返回值

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#1134]
**是否为新品（必填）**
在售

**关联的产品model**
yuemee.airmonitor.mhfd1

**企业名称（必填）**
Honeywell

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [eg.master10011/]
- 相关模块:[Bluetooth]

**现象（必填）**
初次添加蓝牙设备（“霍尼韦尔甲醛测试仪”）成功后，进入插件页面，页面卡死。
分析log发现其实是bt.connect()调用无任何返回。

**期望（必填）**
能解决bt.connect()无返回问题。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
[WeChatSight17.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3357925/WeChatSight17.mp4.zip)

**Comment by zanetti4** [comment]
请给出使用 connect 方法的代码，出现此状况时有报错吗？

**Comment by EllisonYe** [comment]
`connect() {
        myLog("start connect");
        if (this.showing) {
            let bt = Device.getBluetoothLE();
            if (bt === undefined) {
                // should do scanning or ble is already connected
                myLog("OTA: bt is null");
            }
            else {
                this.state.connectCount++;
                myLog("bt status "+bt.isConnect)
                if (bt.isConnected) {
                    myLog("connected");
                    bt.startDiscoverServices(this.state.deviceInfoServiceUUID,
                        this.state.batteryServiceUUID,
                        this.state.generalServiceUUID);
                } else {
                    bt.connect().then((data) => {
                        myLog("connected code:" + data.code);
                        bt.startDiscoverServices(
                            this.state.deviceInfoServiceUUID,
                            this.state.batteryServiceUUID,
                            this.state.generalServiceUUID);
                        this.state.bleConnected = true;
                        this.state.connectCount = 0;
                        disableTimer(this.getRuntimeDataFromCloudTimer);
                    }).catch((data) => {
                        myLog("connect failed code " + data.code);//链接失败的页面
                        if ((data.code === -7 || data.code === -1)
                            && this.state.connectCount <= 3) {
                            // 100, the bluetooth is connecting now
                            // -1, device not exist
                            // -7, timeout
                            this.state.connectCount++;
                            this.reconnectDevice();
                        } else {
                            getRuntimeDataFromCloud();
                            this.state.connectCount = 0;
                            this.state.bleConnected = false;
                            if (data.code != 100) {
                                showTip(this, 'offline', LocalizedStrings.deviceOffline);
                            }
                        }
                    }
                    );
                    myLog("bt.connect()");
                }
            }
        } else {
            myLog("BLE connect page is un-showing");
        }
    }`

**Comment by zanetti4** [comment]
> @param {json} option -附加参数, 格式 {timeout:12000, peripheralID:"..."}, timeout的单位为毫秒, peripheralID是iOS平台参数

connect(type = -1, option = 0)
你在 option 传入 peripheralID 试试呢？也是同样的情况吗？

**Comment by EllisonYe** [comment]
startScan returns {void}, 如何获取peripheralID？

/**
     * 开始扫描蓝牙设备
     * @method
     * @param {int} durationInMillis - 扫描时长
     * @param {...string} serviceUUIDs - 指定扫描, 为空时扫描全部
     * @returns {void}
     *
     * @example
     *      import Bluetooth from 'miot/Bluetooth'
     *      Bluetooth.startScan(3000, 'FE95','FE96')
     */
    startScan(durationInMillis, ...serviceUUIDs) {
    },

**Comment by zanetti4** [comment]
@blockdate 请协助查看此问题

**Comment by blockdate** [comment]
提供下完整的日志输出和代码调用栈

**Comment by EllisonYe** [comment]
此为偶现问题，早上尝试了多次，其中debug 版本未复现，Release版本（没有“开发者设置”选项）可以复现。Log无法抓取。


![IMG_2829](https://user-images.githubusercontent.com/37297126/60935617-0e309000-a2fd-11e9-9383-165307b9e5dd.jpg)


![WechatIMG18](https://user-images.githubusercontent.com/37297126/60933469-f3f2b400-a2f4-11e9-9755-1b9b61d31864.jpeg)

**Comment by pencilCool** [comment]
手机连上mac 。console app 能看到日志吧？
