### ISSUE TITLE
配网时提示网页无法打开

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#1135]
**是否为新品（必填）**
 新品 

**关联的产品model**
minij.washer.v8

**项目ID（必填）**
minij.washer.v8

**企业名称（必填）
小吉科技

**环境（必填）**
手机系统:[eg.Android 8.0
荣耀9i

**现象（必填）**
使用的新sdk框架，配网时提示网页无法打开

**期望（必填）**
配网页面正常显示

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
复现过几次，这个页面是传到米iot开发者平台上面的，插件端无法处理

**不要贴大段代码❗️**

**Comment by hao0000** [comment]
![微信图片_20190704144401](https://user-images.githubusercontent.com/28422366/60645043-3c7c1e80-9e6a-11e9-839d-5fa8506f08fe.jpg)

**Comment by dingshaoran** [comment]
我试了，你这个网址是有的，http://home.mi.com/views/deviceReset.html?model=minij.washer.v8&locale=zh_CH 手机的网络有问题
这个地方就是一个 webivew，没什么奇怪的。估计是你手机设置代理了

**Comment by cfJand** [comment]
再次检测上述地址是OK的，长时间无回复，关闭issue。
