### ISSUE TITLE
无法搜索到蓝牙FE95

### ISSUE THREAD

**Issue by wxy693172809** [MiEcosystem/miot-plugin-sdk#1136]
**是否为新品（必填）**
新品

**关联的产品model**
“aiqi.remote.xiaomimaze”

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
北京爱其科技有限公式

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1
- SDK分支: 10010
- 相关模块:蓝牙

**现象（必填）**
搜索蓝牙UUID = FE95，搜索不到蓝牙(米家中却能搜索到硬件设备并能绑定)；

**期望（必填）**
能根据FE95搜索到蓝牙并且不会自动断开

**其他的上下文/日志/截图**
这是搜索全部蓝牙的log日志
![IMG_20190704_155543](https://user-images.githubusercontent.com/11309056/60649376-7520f580-9e74-11e9-80aa-aae76037e4e2.jpg)

**尝试过的解决办法**
搜索全部蓝牙，找到对应的mac地址并连接，连接成功后几秒会自动断开，蓝牙芯片报错显示LOGIN_FAIL，错误代码-2；

Bluetooth.startScan(3000,"FE95")

**Comment by cfJand** [comment]
现象中：米家中却能搜索到硬件设备并能绑定， 如果米家是OK的，那么建议用米家操作设备。

**Comment by cfJand** [comment]
长期未回复，此issue关闭
