### ISSUE TITLE
Warning: Failed prop type: Invalid props.contentStyle key ‘fontSize’ supplied to ‘RKButton’

### ISSUE THREAD

**Issue by aLLLiyyy** [MiEcosystem/miot-plugin-sdk#1138]
![Screenshot_2019-07-05-10-04-47-962_com xiaomi sma](https://user-images.githubusercontent.com/36837316/60693458-ef9d5400-9f0c-11e9-9d75-ca91da021c80.png)

**Comment by zanetti4** [comment]
请按照模版提问，谢谢

**Comment by aLLLiyyy** [comment]
sdk 20
每次进入commonsetting 组件都会出现这个警告。能不能去除呀

**Comment by LiuMengzhou** [comment]
好的，采纳建议
