### ISSUE TITLE
LoadingDialog 的 timeout这个属性设置无效

### ISSUE THREAD

**Issue by WWJ1993** [MiEcosystem/miot-plugin-sdk#1139]
是否为新品（必填）
新品

关联的产品model
ihealth.bp.bpm1

项目ID（必填）
【无项目ID】

企业名称（必填）
iHealth

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 10.3.3]
SDK分支: [10020]
相关模块:[Service]
现象（必填）
给LoadingDialog 的 timeout这个属性设置数值来控制提示框的显示的时间。但是无论给timeOut设置什么数值（非零值），都无效，都是基本在10S左右自动消失

期望（必填）
LoadingDialog可以通过给timeout这个属性设置数值来控制提示框的显示时间
其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法

不要贴大段代码❗️

**Comment by zanetti4** [comment]
我用 ios 12.3.1测试 miot-workspace/projects/com.xiaomi.demo/Main/UIComponent/DialogTest.js，timeout 可以生效。你测试这个 demo 也是同样的问题吗？
