### ISSUE TITLE
隐藏虚拟导航栏时底部会出现白色闪屏

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1140]
**是否为新品（必填）**
在售

**关联的产品model**
viomi.hood.h3、viomi.hood.c2、viomi.hood.a10、viomi.hood.x2、viomi.hood.a9、viomi.hood.h1、viomi.hood.c1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
佛山云米电器科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:Android 8.1
- SDK分支: [eg.master/10020]
- 相关模块:[eg.Host]

**现象（必填）**
具体现象如gif所示，隐藏底部虚拟导航栏时，会有一白色块一闪而过

**期望（必填）**
隐藏虚拟导航栏时不出现白色的底部闪屏

![闪屏](https://user-images.githubusercontent.com/11864517/60695768-8110c400-9f15-11e9-9ea0-14933f987268.gif)

**页面布局代码示例**

return 
<View style={styles.page}>
      <View style={styles.bg}>
        <Svg width={Base.screenWidth} height={constants.indexHeight}>
          <Defs>
            <LinearGradient id="bg" x1="0" y1="0" x2="0" y2='100%'>
              <Stop offset="0" stopColor="#191B3B" stopOpacity="1" />
              <Stop offset="1" stopColor="#16132A" stopOpacity="1" />
            </LinearGradient>
          </Defs>
          <Rect x={0} y={0} width='100%' height='100%' strokeWidth={0} fill="url(#bg)"></Rect>
        </Svg>
      </View>
      <View style={{flex : 1}}>
        <ScrollView style={{flex : 1}}>
       </ScrollView>
      </View>
</View>

**Comment by zanetti4** [comment]
请按照模版提问，谢谢

**Comment by jimu380261652** [comment]
布局代码示例
return 
<View style={styles.page}>
      <View style={styles.bg}>
        <Svg width={Base.screenWidth} height={constants.indexHeight}>
          <Defs>
            <LinearGradient id="bg" x1="0" y1="0" x2="0" y2='100%'>
              <Stop offset="0" stopColor="#191B3B" stopOpacity="1" />
              <Stop offset="1" stopColor="#16132A" stopOpacity="1" />
            </LinearGradient>
          </Defs>
          <Rect x={0} y={0} width='100%' height='100%' strokeWidth={0} fill="url(#bg)"></Rect>
        </Svg>
      </View>
      <View style={{flex : 1}}>
        <ScrollView style={{flex : 1}}>
       </ScrollView>
      </View>
</View>

**Comment by jimu380261652** [comment]
issue上粘贴代码，代码显示不全的

**Comment by zanetti4** [comment]
你是用工具栏里 Insert code 贴的代码吗？

**Comment by jimu380261652** [comment]
`布局代码示例
return 
<View style={styles.page}>
      <View style={styles.bg}>
        <Svg width={Base.screenWidth} height={constants.indexHeight}>
          <Defs>
            <LinearGradient id="bg" x1="0" y1="0" x2="0" y2='100%'>
              <Stop offset="0" stopColor="#191B3B" stopOpacity="1" />
              <Stop offset="1" stopColor="#16132A" stopOpacity="1" />
            </LinearGradient>
          </Defs>
          <Rect x={0} y={0} width='100%' height='100%' strokeWidth={0} fill="url(#bg)"></Rect>
        </Svg>
      </View>
      <View style={{flex : 1}}>
        <ScrollView style={{flex : 1}}>
       </ScrollView>
      </View>
</View>`

**Comment by zanetti4** [comment]
如果你把虚拟导航栏设置为绝对定位，放在页面底部。隐藏时还有这种现象吗？
