### ISSUE TITLE
新品+无项目ID+上海稍息网络科技有限公司（摩摩哒）

### ISSUE THREAD

**Issue by sushuan** [MiEcosystem/miot-plugin-sdk#1141]
BlueNRG-1按米家蓝牙标准接入SDK，编译OK，烧入STEVAAL-IDB007V1开发板;
运行后Uart输出提示如下错误：Service add success with service handle 0xcAttr add Error, error code 0x48 Error while adding Chat；
能否帮忙确认一下错误的原因？
UART输出如下信息：
![image](https://user-images.githubusercontent.com/52527030/60698611-c8518180-9f22-11e9-9f43-2e2827622464.png)

**Comment by zanetti4** [comment]
请按照模版提问题，谢谢

**Comment by zanetti4** [comment]
Duplicate of #1145
