### ISSUE TITLE
RN 上传应用后ios正常使用，Android无法使用

### ISSUE THREAD

**Issue by maker9** [MiEcosystem/miot-plugin-sdk#1143]
**是否为新品（必填）**
新品

**项目ID（必填）**
com.qfeeltech.roboeye.swdk

**企业名称（必填）**
北京速感科技

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]

**现象（必填）**
使用miot-plugin-sdk开发， 上传应用后，ios可以正常使用，Android不能用，是什么原因？Android是用旧版开发，这个有影响？ 
应用上传后，怎么看日志？

**期望（必填）**
上传应用后，点测试，ios和Android可以正常使用

**Comment by lvjie0519** [comment]
@maker9  
1、Android apk 版本号多少？
2、在新框架下进行插件开发，无论Android或ios 都是同一个rn插件包，不存在Android还能用旧版框架进行原生开发；
3、debug包可以通过logcat 查看日志，无法加载插件，通常都是js代码存在问题，建议先通过日志查看下能否看出关键信息。

**Comment by lvjie0519** [comment]
@maker9  如果问题已解决，请关闭issue，谢谢。
