### ISSUE TITLE
打包时出现如下错误，如何排查

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1144]
是否为新品（必填）
在售

关联的产品model
miaomiaoce.thermo.t10

项目ID（必填）
913

企业名称（必填）
秒秒测

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 9/iOS 12]
SDK分支: [eg.master/10022/...]
现象（必填）

<img width="939" alt="image" src="https://user-images.githubusercontent.com/28639410/60707476-6b63c480-9f3e-11e9-9d91-255fbe870c86.png">

期望：给个排查方法

**Comment by zxd620** [comment]
我遇到的情况是：npm run create xxx.yyy.zzz出来的project里面，自己工程下面有个project.json，最后的一个英文逗号，是不需要的，去掉后就好了。
