### ISSUE TITLE
运行米家蓝牙标准出错，提示 error code 0x48 Error while adding Chat；

### ISSUE THREAD

**Issue by sushuan** [MiEcosystem/miot-plugin-sdk#1145]
---
**是否为新品（必填）**
填 新品 

**关联的产品model**
颈部按摩仪BLE Module

**项目ID（必填）**
无项目ID

**企业名称（必填）**
（摩摩哒）上海稍息网络科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS/Linux]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10020]
- 相关模块:[装置]

**现象（必填）**
按米家蓝牙标准接入SDK，编译OK，烧入STEVAAL-IDB007V1(ST)开发板;
运行后Uart输出提示如下错误：Service add success with service handle 0xcAttr add Error, error code 0x48 Error while adding Chat；
串口打印信息如下：
![image](https://user-images.githubusercontent.com/52527030/60712182-019ce800-9f49-11e9-91b7-57c11d90f8f1.png)

**期望（必填）**
运行初始化通过后，能搜索到蓝牙名称，能与手机正常通讯。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
与ST的代理商和原厂联系过，因为错误提示是米家蓝牙标准中的函数，请帮忙协助解决；

**不要贴大段代码❗️**

**Comment by sushuan** [comment]
@dingshaoran @blockdate 麻烦请帮忙解决一下，多谢各位了，目前因蓝牙问题卡在这了无法完成和app的对接调试

**Comment by dingshaoran** [comment]
看起来是固件问题

**Comment by cfJand** [comment]
看起来是固件的问题，关掉此issue。
