### ISSUE TITLE
米兔牙刷插件，无网络删除定时没有提示信息

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#1146]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）
手机系统:[Android 9.0]
SDK分支: [master]
相关模块:[游戏时间设置]

现象（必填）
1、进入插件，设置PIN码，进入家长模块
2、点击家长设置，进入游戏时间设置，关闭网络删除目标时间段，没有提示信息

期望（必填）
可以正常显示提示信息，内容与IOS一致，“删除定时失败”

**Comment by lvjie0519** [comment]
@huangjr126  文字描述不太清晰，拍个ios的视频看看，谢谢。

**Comment by lvjie0519** [comment]
@huangjr126   如果问题解决，请说明下解决方案，没有解决，请提供个视频文件，看下具体错误情况，谢谢。

**Comment by huangjr126** [comment]
[米兔儿童牙刷-视频.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3370974/-.zip)
@lvjie0519 不好意思，这是该问题的复现视频。

**Comment by huangjr126** [comment]
[米兔牙刷-IOS-删除定时.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3371001/-IOS-.zip)
@lvjie0519 上面那个是android的视频，这个是IOS的视频

**Comment by lvjie0519** [comment]
@huangjr126  APP那边的问题， 已经找人安排排查，谢谢。

**Comment by huangjr126** [comment]
@lvjie0519 收到，感谢

**Comment by lvjie0519** [comment]
@huangjr126  已修复， 使用fir上最新apk进行测试，谢谢。

**Comment by huangjr126** [comment]
@lvjie0519 好的，感谢
