### ISSUE TITLE
Host.locale.systemLanguage()获取系统语言

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/miot-plugin-sdk#1147]
**是否为新品（必填）**
在售

**关联的产品model**
com.roborock.s6,com.roborock.s6v2,com.roborock.s6v3

**项目ID（必填）**
258089735

**企业名称（必填）**
北京石头科技股份有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[Android 9]
- SDK分支: [eg.master/10022/...]
- 相关模块:[eg.Host/Locale/systemLanguage]

**现象（必填）**
我用最新的测试包  5.5.37.1测试版  
调用了下systemLanguage接口，获取系统语言，好像还不行，提示undefined
请问最新版的测试版app支持10022版本SDK吗？

**期望（必填）**
米家某个版本能够成功调用systemLanguage获取系统语言

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
Host.locale.systemLanguage   是一个变量，不是方法，打印下locale就明白了，谢谢。

**Comment by PioneerVM** [comment]
您好，我又重新试了下米家5.5.37.1测试版 ，打印的 api level也是10022，Host.locale.systemLanguage是undefined，打印Host.locale确实也没有systemLanguage这个字段，请问是需要我下个别的版本的米家吗？

**Comment by PioneerVM** [comment]
![image](https://user-images.githubusercontent.com/22908326/60789258-41eea700-a191-11e9-9ae1-a70f683c5e7f.png)

**Comment by zanetti4** [comment]
我用安卓7，米家5.5.30.6 测试版，Host.locale.systemLanguage 能打印出 zh_CN
