### ISSUE TITLE
安卓最新固件仍能点击升级

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1148]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8]
SDK分支: [10022]
相关模块:[Host.ui.openDeviceUpgradePage]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
安卓的固件升级页面，即使是最新固件了，底下还是有一个 立即更新 按钮，能否跟iOS统一，如果已经是最新固件，下面按钮为 返回键。

期望（必填）
如果已经是最新固件，底下按钮为 返回键

代码：
`Host.ui.openDeviceUpgradePage();`

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@lvjie0519 我用安卓7测试插座设备，当前已是最新版本，下方显示的是“确定”按钮，点击可以返回的。请你查看

**Comment by lvjie0519** [comment]
@xyliusun

**Comment by xyliusun** [comment]
我在5.5.37.2测试版和SDK10023上看到的还是 立即更新，请问你们的apk版本号是多少啊？

**Comment by lvjie0519** [comment]
@xyliusun   你这个版本就支持， 把设备分享给 894158105 账号，我这边测试下。

**Comment by xyliusun** [comment]
设备是分享给你了，但是因为我们对分享设备屏蔽了设置页，所以你这边应该是看不到更新设置项的
