### ISSUE TITLE
自定义倒计时的name

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1149]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8/iOS 12.3.1]
SDK分支: [10023]
相关模块:[Host.ui.openCountDownPage]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
倒计时不能自定义name

期望（必填）
倒计时可以自定义identify和name

可以参考定时接口Host.ui.openTimerSettingPageWithOptions的displayName参数
@param {string} options.displayName 配置场景日志显示的名称

**不要贴大段代码❗️**

**Comment by santcool** [comment]
displayName的问题已经解决了。我抓了两个包，应该可以满足你们的问题。
js传递参数到edit接口
``` 
Host.ui.openTimerSettingPageWithOptions({ onMethod: "power_on", onParam: "on", offMethod: "power_off", offParam: "off", timerTitle: "这是一个自定义标题", displayName: "自定义场景名称" })
```
最后生成名称为自定义场景名称的倒计时
[归档.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3380117/default.zip)

**Comment by xyliusun** [comment]
好的，谢谢。这个我直接下载最新的包就可以验证了是吗

**Comment by xyliusun** [comment]
@santcool 
1. 上面提供的那个接口是**定时**的，我们这个issue是**倒计时**的
定时的issue地址是这个https://github.com/MiEcosystem/miot-plugin-sdk/issues/1162
2. 在最新的测试包2311上这个接口的displayName还是没有解决，是还要更新的测试包吗？SDK是10023？

可以reopen一下issue吗？这个是倒计时的需求

**Comment by santcool** [comment]
用这个包。https://fir.im/tes5?release_id=5d26d8cab2eb46427ca7b0cd。
你可以抓包看看，定时和倒计时应该是一个接口

**Comment by xyliusun** [comment]
@santcool 这个包的定时displayName功能ok了
倒计时和定时是跳不同的页面，定时是用openTimerSettingPageWithOptions，倒计时是用openCountDownPage，可能里面的定时场景接口是一样的，但是openCountDownPage的参数并没有可以自定义name的字段

**Comment by xyliusun** [comment]
![15_59_27__09_18_2019](https://user-images.githubusercontent.com/20435121/65129151-54a51800-da2d-11e9-92eb-7ea64cd7ccf7.jpg)
![20190918160125](https://user-images.githubusercontent.com/20435121/65129311-9635c300-da2d-11e9-995c-af64ec602e4f.jpg)

在10026上，倒计时Host.ui.openCountDownPage仍然没有支持自定义名字
