### ISSUE TITLE
Host.ui.privacyAndProtocolReview调用报错

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#115]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1
- 相关模块:Host

#### 现象

Host.ui.privacyAndProtocolReview使用报错，安卓也有这个问题。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/11364809/49630477-4d29fa80-fa29-11e8-8e95-9f549e3dccdd.png)

PS：我们好像不能加label，没有权限

**Comment by LiuMengzhou** [comment]
Duplicate of #117
