### ISSUE TITLE
getUserStatistics月统计数据不准确

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#1150]
---
**是否为新品（必填）**   
新品

**关联的产品model**
msj.f_washer.m1

**项目ID（必填）**
pid： 1364

**企业名称（必填）**
宁波美高厨具有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] 
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
iOS 12.3
- SDK分支: [eg.master/10000/...]
10005
- 相关模块:[eg.Host/Service/Account]
Service

**现象（必填）**
获取的数据统计数据不是很准确，获取的月数据累计值和日数据值的累计不太一样。请看下面请求数据：

获取日统计：
请求参数：{did: "107118662", data_type: "stat_day_v3", key: "elec", time_start: 1559977024, time_end: 1562569024, limit:1000}
返回结果：
{message: "ok", result: Array(4), code: 0}
以下是Array内容：
0: {value: "[6]", time: 1562515200}
1: {value: "[1]", time: 1562428800}
2: {value: "[1]", time: 1562342400}
3: {value: "[6]", time: 1562256000}

获取月统计：
请求参数：{did: "107118662", data_type: "stat_month_v3", key: "elec", time_start: 1547016949, time_end: 1562568949,limit:1000}
返回结果：{value: "[1]", time: 1561910400}

综合上述请求可知，7月份数据从7月5日到7月8日，累计的数据应该是6+1+1+6=14
可是获取的月数据才是1

所以是不是统计的数据有点小问题，是不是配置错了？

**期望（必填）**
获取月的统计数据和日的统计数据能够准确 

**其他的上下文/日志/截图**

**尝试过的解决办法**
搜索issue，没有找到类似问题

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@santcool 10005分支这样填写 data_type 正确吗？

**Comment by zhuxinleibandou** [comment]
> @santcool 10005分支这样填写 data_type 正确吗？

我看方法的type上这样注释的
/**
     * 图表📈统计接口 /v2/user/statistics
     * @param {json} params 
     * {
            did: '', // 设备id
            // data_type 为 数据类型，包括：
            // 采样统计 日统计:stat_day / 周统计:stat_week / 月统计:stat_month
            // 计数统计 日统计:total_day_v2 / 周统计:total_week_v2 / 月统计:total_month_v2
            data_type: '',
            key: '', // 需要统计的字段，即统计上报对应的key
            time_start: 1543593599, // 开始时间
            time_end: 1541001601, // 结束时间
            limit: 1000 // 限制次数，0为默认条数
        }


但是新的方法好像是total_day_v3，我用total_day_v2试一下。

请求数据：
{did: "107118662", data_type: "total_day_v2", key: "elec", time_start: 1559981814, time_end: 1562573814, limit:1000}

返回数据：
"message": "callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-8 \"(null)\" UserInfo={message=invalid params, result=null, code=-8}

**Comment by zanetti4** [comment]
记得计数统计被删掉了

**Comment by zhuxinleibandou** [comment]
> 记得计数统计被删掉了

那想要统计耗电量的这种 该如何统计？？？？

**Comment by zanetti4** [comment]
@santcool 现在还能进行计数统计吗？

**Comment by santcool** [comment]
清楚隐私授权，重新绑定试试。zhi'qi之前配的有问题，新的wiki在这里，
[统计文档 (1)(1)(1).pdf](https://github.com/MiEcosystem/miot-plugin-sdk/files/3380644/1.1.1.pdf)

**Comment by zhuxinleibandou** [comment]
> 清楚隐私授权，重新绑定试试。zhi'qi之前配的有问题，新的wiki在这里，
> [统计文档 (1)(1)(1).pdf](https://github.com/MiEcosystem/miot-plugin-sdk/files/3380644/1.1.1.pdf)

收到  后台的同学已经配置好了，可以使用了，谢谢！
