### ISSUE TITLE
Android蓝牙调用getVersion（）需要1秒以上时间，期望和iOS一致

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#1151]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.nlight
**项目ID（必填）**
米家飞利浦蓝牙夜灯
**企业名称（必填）**
飞彗

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android蓝牙调用getVersion()接口回调结果超过1秒返回
**期望（必填）**
和iOS一致，降低延迟

**Comment by dingshaoran** [comment]
其他的 write 和 read 的时间长么

**Comment by 123start** [comment]
@dingshaoran 也都比iOS时间长，不过还能接受，但是这个接口getVersion（）回调时间超过一秒

**Comment by cfJand** [comment]
@123start 方便的话，共享一个设备给我，我试试这个getVersion的时间到底是多少？

**Comment by cfJand** [comment]
这里建了一个QQ群，可以加入，方便及时沟通：
![MIOT群二维码](https://user-images.githubusercontent.com/2038490/63013626-3775aa80-bebf-11e9-928f-8e409c5642af.png)

**Comment by Woody2016** [comment]
这个issue长时间无响应，先close
如果开发者还有问题，请去开发者平台提工单
