### ISSUE TITLE
进入插件页面之前，弹出设备消息框，导致执行miot.Package.exit() 返回不了设备列表页面

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#1152]
---
**是否为新品（必填）**
在售

**关联的产品model**
viomi.health_pot.v1

**项目ID（必填）**

**企业名称（必填）**
云米

**环境（必填）**
- 手机系统:[iOS 12.1.4]
- SDK分支: [100020]
- 相关模块:[Package]

**现象（必填）**
1、先打开卡片，这时候收到一个设备消息；
2、这时候点击“查看更多”，这时会跳转进入插件页面A，并且弹出了消息框；
3、点击“去看一下”，APP又一次跳转到了插件页B；
4、这个时候，点击B插件页左上角返回按钮，会返回到A插件页面；
5、点击A插件页左上角返回按钮，没有反应了。

**期望（必填）**
1、点击查看更多后，不要弹出消息框了
2、或者不要影响插件的页面逻辑，比如返回

**其他的
[复现步骤.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3367248/mp4.zip)
上下文/日志/截图**

**Comment by santcool** [comment]
这个问题已经解决了，在首页下载最新的包就好了

**Comment by flingInTheSky** [comment]
好
