### ISSUE TITLE
通用设置tilteBar文字变白

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1153]
**是否为新品（必填）**
在售

**关联的产品model**
“philips.light.hbulb”

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [master.]
- 相关模块:[]

**现象（必填）**
从通用设置跳转到原生界面（例如固件升级），点击返回通用设置titleBar的文字会变白。
我的主界面titleBar的style为light，通用设置的style为black。

![image](https://user-images.githubusercontent.com/5188922/60793082-85e5aa00-a199-11e9-8897-94f2d25e3077.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
Duplicate of #810

**Comment by mirse** [comment]
> Duplicate of #810

并未解决，现在又复现了
