### ISSUE TITLE
Android平台线上版图片显示模糊

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#1154]
**是否为新品（必填）**
新品

**关联的产品model**
msj.f_washer.m1

**项目ID（必填）**
pid: 1364

**企业名称（必填）**
宁波美高厨具有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]  Android9.1
- SDK分支: [eg.master/10000/...] 10005
- 相关模块:[eg.Host/Service/Account] host

**现象（必填）**
Android平台上打包到线上的版本有一张切图显示很模糊，出现锯齿，而开发版本和iOS版本没有相关问题,三个andoriod手机都显示这样，小米8也这样。

线上版本图：
![模糊图](https://user-images.githubusercontent.com/18374383/60793027-69497200-a199-11e9-9917-cdf1c77766b2.png)

debug版本图：
![debug版本图](https://user-images.githubusercontent.com/18374383/60793045-723a4380-a199-11e9-855f-15c7e85e7fbd.png)

切图：
![bg_yuanquan](https://user-images.githubusercontent.com/18374383/60793293-fb517a80-a199-11e9-9eff-a64b28d41511.png)

**期望（必填）**
线上版本不模糊

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
查询过issue，有一个类似的问题，但是没有回答

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
Duplicate of #1013

**Comment by zhuxinleibandou** [comment]
> Duplicate of #1013

问题已找到，从图片上来看，应该是明显的图片放大后出现的锯齿形状，所以我们断点了我们的代码调试，发现在设置图片之前先设置了图片大小为50，后来又调整了图片大小为正常大小，导致图片先缩小，后放大，导致了这种锯齿形状。我们正在修复，不劳烦各位大大了。至于为什么在debug模式下显示正常，线上版本显示龃齿形状还不得而知。

**Comment by lukes-mips** [comment]
试试在Image控件上设置一下resizeMethod: 'scale'
