### ISSUE TITLE
获取定时器信息

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#1156]
是否为新品（必填）
新品

关联的产品名称（必填）
乐秀电暖气

项目ID（必填）
无项目ID

企业名称（必填）
乐秀

环境（必填）
mac os
ios 11.0
10005
ui

现象（必填）
能否告知下，获取定时数组的接口的详细用法？
Device.loadTimerScenes().then((sceneArr) => {
Alert.alert(JSON.stringify(sceneArr));
})
我通过以上的接口获取，返回的是'{[]}'空json。

**Comment by zanetti4** [comment]
事先你是否利用 createTimerScene() 创建过定时场景？

**Comment by sikaiven** [comment]
没有用createTimerScene()创建过定时场景，但是在米家封装好的定时界面里面，有手动添加定时

**Comment by zanetti4** [comment]
请给出你手动添加定时的代码

**Comment by sikaiven** [comment]
![2571562638857_ pic](https://user-images.githubusercontent.com/17919773/60854555-44094200-a233-11e9-8f3e-6518a0e314c9.jpg)
这个界面添加定时不需要代码吧？

**Comment by zanetti4** [comment]
@sikaiven 不好意思，我理解错了。

**Comment by zanetti4** [comment]
@santcool 用 sikaiven 这种方式添加定时，loadTimerScenes() 能成功加载场景吗？

**Comment by santcool** [comment]
给出这两个接口的抓包信息吧，我们看看是不是因为传了过滤参数，导致不返回。

**Comment by sikaiven** [comment]
![屏幕快照 2019-07-17 下午1 47 58](https://user-images.githubusercontent.com/17919773/61350296-b2847a80-a899-11e9-81a7-d23cd9d4550d.png)

@santcool 好像是返回了，但是通过回调打印sceneArr还是为空

**Comment by santcool** [comment]
你抓下包试试？我这边抓包获取list，是有值的，最后chrome打出的log也是有值的。
![屏幕快照 2019-07-18 下午8 04 10](https://user-images.githubusercontent.com/8580061/61455867-45efa580-a997-11e9-8c67-965e6274ee6f.png)

**Comment by sikaiven** [comment]
@zxconan 不清楚抓包是指什么方式？上面的截图就是通过Android studio抓取的手机log，应该算是抓包吧，看log信息，手机是收到了反馈的信息了的，但是回调到上层为空，不知道什么原因。

**Comment by zanetti4** [comment]
这个问题解决了吗？

**Comment by sikaiven** [comment]
还没有

**Comment by Woody2016** [comment]
此问题长时间无响应，先close
开发者如果还有问题，请去小米开发者平台提工单，谢谢
