### ISSUE TITLE
订阅设备消息ios收到的监听数据为空，安卓可以收到数据

### ISSUE THREAD

**Issue by moneyinto** [MiEcosystem/miot-plugin-sdk#1157]
**是否为新品（必填）**
在售

**项目ID（必填）**
66113

**企业名称（必填）**
南京艾睿柯智能科技有限公司

**环境（必填）**
- 电脑操作系统:[MAC 10.14.5 (18F132)]
- 手机系统:[eg.Android 9.0/iOS 12.2]
- SDK分支: [eg.master]

**现象（必填）**
订阅了设备事件，在安卓上回调可以拿到数据，ios回调中数据为空。

**期望（必填）**
ios回调可以获取到数据。

**其他的上下文/日志/截图**
代码片段
![image](https://user-images.githubusercontent.com/7973369/60811762-86df0180-a1c2-11e9-9e2d-9c678e5985d2.png)

安卓回调截图
![image](https://user-images.githubusercontent.com/7973369/60811828-a83fed80-a1c2-11e9-9984-b74f781806c8.png)

ios回调截图
![image](https://user-images.githubusercontent.com/7973369/60811870-bc83ea80-a1c2-11e9-881a-854d2a2f7203.png)

**Comment by zanetti4** [comment]
请按照模版填入更详细的信息，谢谢

**Comment by moneyinto** [comment]
> 请按照模版填入更详细的信息，谢谢

这样可以吗，还需要哪些信息。

**Comment by santcool** [comment]
Device.getDeviceWifi().subscribeMessages('prop.2.1', 'prop.3.1').then(res => {
                    console.log('subscribeMessages', res)
                }).catch(res => {
                    console.log(res, 'catch')
                });

**Comment by moneyinto** [comment]
> 有没有调用此方法，此方法是否返回成功？
> Device.getDeviceWifi().subscribeMessages('prop.2.1', 'prop.3.1').then(res => {
> console.log('subscribeMessages', res)
> }).catch(res => {
> console.log(res, 'catch')
> });

调用了该方法，在ios上返回时成功的。

**Comment by moneyinto** [comment]
> 有没有调用此方法，此方法是否返回成功？
> Device.getDeviceWifi().subscribeMessages('prop.2.1', 'prop.3.1').then(res => {
> console.log('subscribeMessages', res)
> }).catch(res => {
> console.log(res, 'catch')
> });

我看到有issue说这个订阅有数量的问题，订阅多会有影响不，但是安卓上是正常的。
