### ISSUE TITLE
插件上如何获取以及设置消息推送开关的状态

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#1158]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
扫拖一体机/dreame.vacuum.mc1808

**现象（必填）**

在产品控制台配置推送消息时可选择支持用户关闭推送，在插件上如何获取用户消息推送开关的状态，以及如何设置该状态

**期望（必填）**
可以正常控制消息推送开关

**Comment by zanetti4** [comment]
[该文档](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/doc-md/20-%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1_%E6%99%BA%E8%83%BD%E5%AE%B6%E5%BA%AD%E6%A8%A1%E5%9D%97.md)中，getDeviceSettingV2 和 setDeviceSetting 方法能否满足你的需求？

**Comment by heigaga001** [comment]
@zanetti4 在消息配置的后台，可以选择用户自主关闭消息推送，在米家的设置中，也有针对某台设备的推送消息开关，所以咨询有没有给插件调用的消息开关接口

**Comment by santcool** [comment]
这个问题你可以自己抓包查看，接口我们都已经提供。
