### ISSUE TITLE
关于截屏和分享的问题

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#1159]
---
**是否为新品（必填）**
新品

**关联的产品model**
jyaiot.cm.ccj01

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android iOS
- SDK分支: master
- 相关模块:Host/file Host/ui

**现象（必填）**
先调用截屏API，成功之后调用分享API，iOS手机上可以弹出分享窗口，但是不能无法显示截屏图片
android手机无法弹出分享窗口

**期望（必填）**
均能正常弹出分享窗口并且可以正常显示截屏

**其他的上下文/日志/截图**
![1921562638122_ pic](https://user-images.githubusercontent.com/8509320/60854095-8e89bf00-a231-11e9-96ea-89b4d0839d4b.jpg)
因为android手机无法弹出窗口，所以没有截屏

**尝试过的解决办法**

**不要贴大段代码❗️**
`Host.file.screenShot("temp.png").then((result)=>{
                                console.log('截屏成功' + result)
                                Host.ui.openShareListBar('分享', '分享描述', {local: "temp.png"},'')
                            }).catch((err)=>{
                                console.log('截屏失败' + err)
                            })`

**Comment by zanetti4** [comment]
@santcool 我用 ios 测试，能够弹出分享窗口，但是第一排的媒体图标不能点击。请你查看

**Comment by zanetti4** [comment]
@killua4github `Host.ui.openShareListBar('小米智能家庭', '小米智能家庭1111', { local: "temp.png" }, 'http://www.mi.com')`
我在第四个参数填了 url，安卓可以弹出分享窗口并且能够成功分享。

**Comment by killua4github** [comment]
> @santcool 我用 ios 测试，能够弹出分享窗口，但是第一排的媒体图标不能点击。请你查看

我截图里面也是可以弹出分享窗口的，可以分享到微信和朋友圈，因为没有安装微博和LINE，所以那两个不可以点击，请问下分享的应用是否可选？还有，组要的问题是分享弹框里没有显示屏幕截图，我代码里写了截屏之后分享，图片使用的就是截屏

**Comment by zanetti4** [comment]
我的苹果手机没安微信、微博、LINE，所以都不可点……屏幕截图不在分享弹框里显示
![image](https://user-images.githubusercontent.com/12883959/60864757-146c3100-a257-11e9-8788-0272029ee2ea.png)
这是一个分享后的结果：Baby为title，朝阳区为description，右边图片为imagePath，点击它，能打开一个页面，就是url

**Comment by killua4github** [comment]
> 我的苹果手机没安微信、微博、LINE，所以都不可点……屏幕截图不在分享弹框里显示
> ![image](https://user-images.githubusercontent.com/12883959/60864757-146c3100-a257-11e9-8788-0272029ee2ea.png)
> 这是一个分享后的结果：Baby为title，朝阳区为description，右边图片为imagePath，点击它，能打开一个页面，就是url

了解了

**Comment by zanetti4** [comment]
咨询了同事，分享的应用不可选
