### ISSUE TITLE
设置页面的UI问题

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1160]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.zystrip

**企业名称（必填）**
飞彗智能照明

**现象（必填）**
1.安卓设备法律信息没有导航标题
2.iOS设备智能场景没有导航标题
3.设备时区安卓和iOS风格不一致

**期望（必填）**
如何好上述BUG

***优先级***
紧急紧急紧急

**Comment by devYoungyang** [comment]
又发现一个新的BUG，在安卓设备上以最快的速度双击智能场景和固件升级，会push进去两次。应该有个时间间隔。

**Comment by zanetti4** [comment]
Duplicate of #1014 
1.该问题已修复
3.我在安卓和 ios 测试，这两个页面风格是一致的。你指的是什么？可以贴个对比截图。

**Comment by devYoungyang** [comment]
智能场景iOS没有导航标题，而且UI也不一致

**Comment by devYoungyang** [comment]
更多设置里的设备时区安卓和iOS风格不一致

**Comment by devYoungyang** [comment]
在安卓设备上以最快的速度双击智能场景和固件升级，会push进去两次。

**Comment by devYoungyang** [comment]
法律信息的问题已经修复了

**Comment by zanetti4** [comment]
安卓：
![image](https://user-images.githubusercontent.com/12883959/60873836-95342880-a269-11e9-8c1d-e37ca6bde5c9.png)
ios:
![image](https://user-images.githubusercontent.com/12883959/60873875-a7ae6200-a269-11e9-8f64-b0ace9f237c4.png)
这是 master 设备时区的对比图，风格不一致是指哪里？安卓手机上是有分割线的，截屏后看不见了。

**Comment by devYoungyang** [comment]
iOS有导航栏标题，安卓没有，不过还好了，影响不大

**Comment by lvjie0519** [comment]
@devYoungyang     快速双击，  这个应该很多地方都没有做限制，后期在优化，优先级靠后；
麻烦你再总结下，Android ios  有哪些不一样的问题需要修复？谢谢

**Comment by santcool** [comment]
时区风格不一致的问题，是通过米家验收的，暂无统一计划。
iOS缺智能标题这个事，之前也有开发者提过，我们一致觉得勿需修改，望周知。

**Comment by lvjie0519** [comment]
看起来，针对这个issue，已经没问题了，如果是其他的问题，建议从新提issue，谢谢。
