### ISSUE TITLE
openTimerSettingPageWithOptions闪退问题

### ISSUE THREAD

**Issue by huangguojin1** [MiEcosystem/miot-plugin-sdk#1161]
---
**是否为新品（必填）**
新品

**关联的产品model**
soocare.toothbrush.mc

**项目ID（必填）**
1008467793

**企业名称（必填）**
舒可士

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 11.0
- SDK分支: master/10000/...
- 相关模块:Host/ui

**现象（必填）**
无网络下，长按删除定时器后，再次点击定时器APP闪退

**期望（必填）**
APP响应正常

**Comment by zanetti4** [comment]
> @since 10010 ,SDKLevel 10010 开始提供使用

你在10010分支使用，还有该问题吗？

**Comment by huangguojin1** [comment]
10010还是存在该问题

**Comment by zanetti4** [comment]
@santcool 我用 ios 12.3.1 测试，app 没有出现闪退现象，请你查看。

**Comment by santcool** [comment]
已修复，今天的版本提交appstore
