### ISSUE TITLE
Host.ui.openTimerSettingPageWithOptions在iOS上使用问题

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1162]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 6/iOS 12.3.1]
SDK分支: [SDK_10022]
相关模块:[Host.ui.openTimerSettingPageWithOptions]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
1. Host.ui.openTimerSettingPageWithOptions无法自定义displayName
2. Host.ui.openTimerSettingPageWithOptions创建的定时无法执行

期望（必填）
1. Host.ui.openTimerSettingPageWithOptions可以自定义displayName
2. Host.ui.openTimerSettingPageWithOptions创建的定时可以执行

代码：
const options = {
                onMethod: 'toggle_plug',
                onParam: **JSON.stringify([onoff, 'on']),**
                offMethod: 'toggle_plug',
                offParam: **JSON.stringify([onoff, 'off']),**
                displayName: **'设置xxx定时',**
                identify: PluginConfig.PlugTimerId
              };
Host.ui.openTimerSettingPageWithOptions(options);

代码如上，iOS效果如下：
![21_31_33__07_05_2019](https://user-images.githubusercontent.com/20435121/60725670-48e8a000-9f6c-11e9-9b8e-ba42bcaff2fc.jpg)

**1. 传参数用JSON.stringify(xxxx) FAIL
2. 自定义name FAIL**

可以麻烦支持一下传参数和自定义name吗

另附上安卓达到的正确预期效果:
![20190705213347](https://user-images.githubusercontent.com/20435121/60725809-97963a00-9f6c-11e9-9707-74304ae2a8e6.jpg)

1. 传参数用JSON.stringify(xxxx) **PASS**
2. 自定义name **PASS**

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
1.如果你在传参数时不用 JSON.stringify，写成 ["on", "title"] 的数组形式，是否可以？

**Comment by zanetti4** [comment]
@santcool 请你查看自定义name FAIL 的问题

**Comment by xyliusun** [comment]
@zanetti4 写成 ["on", "title"] 的数组形式是可以的，就是这样写要区分开安卓和iOS平台

**Comment by santcool** [comment]
displayName的问题，将会上appstore今天的版本，明天我也会更新调试包出来。
创建的定时不能执行，是因为android和ios参数的差异吗？也就是写成 ["on", "title"] 的数组形式是可以的，是指iOS创建的定时也能执行？

**Comment by xyliusun** [comment]
displayName的问题在2311测试包上还没解决；现在在openTimerSettingPageWithOptions 这个接口上，iOS需要传 ["on", "title"] 的数组形式，安卓传JSON.stringify([onoff, 'on'])作为参数的定时才可以正常执行，所以这里会有两个平台传的参数不一样的问题

**Comment by xyliusun** [comment]
定时接口openTimerSettingPageWithOptions在iOS上用[onoff, 'on']形式作为参数可以执行，displayName在新的测试包上已经可以使用，issue close掉
