### ISSUE TITLE
Host.ui.openCountDownPage添加状态变化后的倒计时状态回调

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1163]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8/iOS 12.3.1]
SDK分支: [10022]
相关模块:[Host.ui.openCountDownPage]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
倒计时添加状态变化后，没有回调能让插件去获取倒计时状态

期望（必填）
倒计时添加状态变化后，回调返回倒计时的状态
例如：
Host.ui.openCountDownPage在倒计时添加、删除、取消、更改时间等编辑操作后返回一个Promise.resolve(countdownScene)；将scene暴露出来

**不要贴大段代码❗️**

**Comment by santcool** [comment]
这个问题有两种解决方案：
1.你可以在页面出现的时候，去取一下后台数据，对比一下旧的，就能看出来哪些被更改了。
2. 你们可以用自定义的倒计时页面，接口都已经暴露了，可以自己增删改查，查询倒计时列表。
native来修改这个，一方面必要性不大，另一方面因为数据量和层级的关系，resolve的也只能是sceneId，你拿到后，依旧要去后台取数据。所以我们加一个意义不大的对比，还不如谁用谁加

**Comment by xyliusun** [comment]
好的，谢谢
