### ISSUE TITLE
打包失败 因为使用了moment这个文件

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#1164]
---
**是否为新品（必填）**
在售

**关联的产品model**
com.lfwellness.LF_DSD152

**项目ID（必填）**
乐范魔力贴四驱版

**企业名称（必填）**
乐范健康有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- SDK分支: 10020

**现象（必填）**
在npm中引入了moment这个关于时间的文件，打包上传无法成功

**期望（必填）**
希望能够成功使用，打包成功

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43639032/60865217-2ac6bc80-a258-11e9-9a1b-11df782f2458.png)
文件在node_modules中  
错误为
![image](https://user-images.githubusercontent.com/43639032/60865351-71b4b200-a258-11e9-97ed-4dc004cb413e.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
moment 模块是你自己安装的吗？在测试阶段（未打包），是否能正常使用？

**Comment by 1076815296** [comment]
是我自己安装的  在开发阶段可以正常使用  打包也没有问题 但是在打包上传到米家的时候就会报错

**Comment by santcool** [comment]
安装moment是否是在**com.lfwellness.LF_DSD152这个文件夹**下面npm install -g

**Comment by 1076815296** [comment]
全路径         /Users/LeFan/Desktop/miot-plugin-sdk/node_modules/moment 
package.json：
![image](https://user-images.githubusercontent.com/43639032/60956656-d265ec80-a335-11e9-9324-2be993e5a139.png)
![image](https://user-images.githubusercontent.com/43639032/60956668-d85bcd80-a335-11e9-87bb-817b09108f28.png)
![image](https://user-images.githubusercontent.com/43639032/60956676-dc87eb00-a335-11e9-9c25-a582953d978f.png)

**Comment by santcool** [comment]
安装moment是否是在com.lfwellness.LF_DSD152这个文件夹下面npm install -g
提供一下moment的路径的截图，和你们项目的package.json
-------------------------------------------------------------
注意我上面回的那段话，你们自己应该有个项目，名字叫做com.xxxx.xxxx.你们需要在这里面执行npm install -g moment，而不是在外面的miot-workspace里面执行！！！

**Comment by 1076815296** [comment]
安装在com.lfwellness.LF_DSD152下面执行npm install -g moment  无效   执行后  找不到moment
