### ISSUE TITLE
新版NavigationBar

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1165]
是否为新品（必填）
在售

关联的产品model
miaomiaoce.thermo.t10

项目ID（必填）
913

企业名称（必填）
秒秒测

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 9/iOS 12]
SDK分支: [eg.master/10020/...]
现象（必填）
使用新版NavigationBar，Android点击返回键，或使用手势返回，没有正常调用回调推出插件

期望（必填）

**Comment by Android-yzhang** [comment]
还有一个小问题，NavigationBar的title如果带空格的话，在Android回显示不全，例如‘batter 1’

**Comment by zanetti4** [comment]
NavigationBar 在10021分支才能使用，你在该分支下会出现上述问题吗？

**Comment by Android-yzhang** [comment]
会的，我在10022分支下开发的

**Comment by zanetti4** [comment]
我看你上面的 SDK分支写的10020，跟你确认一下。
我用安卓7测试，点击返回图标，能够退出插件。title 也能显示全。
![image](https://user-images.githubusercontent.com/12883959/60878637-a9305800-a272-11e9-8939-e3ef851e87df.png)
`<NavigationBar
            backgroundColor='transparent'
            left={[
              {
                key: NavigationBar.ICON.BACK,
                onPress: _ => Package.exit()
              }
            ]}
            right={[
              {
                key: NavigationBar.ICON.MORE,
                onPress: _ => console.log('onPress')
              }
            ]}
            title='batter 1'
            subtitle='标题超长/副标题超长/左右各两按钮标题超长/副标题超长/左右各两按钮'
            onPressTitle={_ => console.log('onPressTitle')}
          />`

**Comment by Android-yzhang** [comment]
上面的sdk 写错了，我是说按系统的返回键，或者全面屏手机的手势返回，不执行回调

**Comment by zanetti4** [comment]
我按系统的返回键也能退出插件

**Comment by zanetti4** [comment]
@LiuMengzhou 请你协助查看，是否能复现此问题

**Comment by LiuMengzhou** [comment]
不能复现

**Comment by LiuMengzhou** [comment]
> 使用新版NavigationBar，Android点击返回键，或使用手势返回，没有正常调用回调推出插件

@Android-yzhang  
这个和导航栏没啥关系吧。
RN可以监听系统返回键，你把设备断开蓝牙连接的操作放在里面即可。
至于全面屏手势的返回监听，你可以搜索一下。
