### ISSUE TITLE
新版本蓝牙网关进不去

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#1166]
---
**是否为新品（必填）**
是的

**关联的产品model**
philips.light.lnlrlight

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**

飞慧智能照明

**环境（必填）**

- 手机系统:[iOS 11.0]

**现象（必填）**

连接流年吸顶灯，在iOS机型中，点击通用设置中的蓝牙网关，无法进入蓝牙网关界面  测试机型：iphone XR

**期望（必填）**

能正常使用

**Comment by lxq93** [comment]
您好，我们最近这个产品即将提测上线，比较紧急，麻烦帮处理回复，感谢~

**Comment by pencilCool** [comment]
分享过来的设备，无法从插件进入蓝牙网关。请核对这一点。

**Comment by daoke666** [comment]
我这边也有同样的现象，Android能进，ios点击设置中的蓝牙网关无反应

**Comment by daoke666** [comment]
不是分享的设备 @pencilCool

**Comment by pencilCool** [comment]
> 不是分享的设备 @pencilCool

你发现有这个问题的设备 model 是多少？

**Comment by daoke666** [comment]
mode：chuangmi.remote.h102c01

**Comment by pencilCool** [comment]
好的

**Comment by pencilCool** [comment]
我这边试，发现是网络不好，造成的数据不一致。这个应该不是必现的bug吧。请检查网络状态。

**Comment by daoke666** [comment]
必现问题啊，不是网络原因，Android每次都能进去，ios一次都没进去过，没有任何反应

**Comment by pencilCool** [comment]
请这这个包上验证：
https://fir.im/mihomebypencilCool?release_id=5d38345623389f5a45404011
密码xiaomi2

**Comment by daoke666** [comment]
可以了
