### ISSUE TITLE
Mesh设备固件升级接口

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/miot-plugin-sdk#1168]
**是否为新品（必填）**
在售

**关联的产品model**
yeelink.light.dnlight2 | Yeelight LED筒灯
yeelink.light.meshbulb1 | Yeelight LED球泡
yeelink.light.meshbulb2 | Yeelight LED烛泡
yeelink.light.spot1 | Yeelight LED射灯

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
亿联客

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10022]
- 相关模块:[Bluetooth]

**现象（必填）**
未找到新框架mesh固件升级接口,下为老框架接口
MHBluetooth.openMeshDFU();

**期望（必填）**
现在设置界面都使用commonsetting,希望提供mesh固件升级接口,并集成到commonsetting,供插件端配置调用

**其他的上下文/日志/截图**

**尝试过的解决办法**
查找文档,demo 搜索关键字mesh 升级

**不要贴大段代码❗️**

**Comment by BaroneX** [comment]
微信已收到反馈,辛苦老师们尽快帮忙支持下,感恩

**Comment by lvjie0519** [comment]
@BaroneX    MHBluetooth.openMeshDFU();   是ios旧框架下的api吧？  Android旧框架是什么api ？

**Comment by santcool** [comment]
@lvjie0519 android下面没有对应的。这里面有一系列页面和逻辑。跟绿米的那些需求一样，得当成一个项目来处理。

**Comment by DennisJu007** [comment]
大佬们这个问题有进展了嘛，因为这个产品已经开售很长时间了，就插件上功能比较少一直被用户喷每天都承受居多的反馈，现在想在新RN框架上尽快适配该设备，还请大佬们提高优先级给处理一下哈 @

**Comment by santcool** [comment]
已处理，即将提供测试包

**Comment by BaroneX** [comment]
4.20.2 (Build 4.20.2.2359) - 186.84 MB
您好，上周测试发现，这个测试包依然不能进行固件的升级

**Comment by BaroneX** [comment]
4.20.3.6477 iOS能进行固件升级，但是大概率，报链接失败，试了下老框架链接成功，是不是新框架的链接蓝牙部分的问题
