### ISSUE TITLE
Record：miot/ui/Dialog/InputDialog 10022版本crash，miot/ui/InputDialog被OverLay嵌套需求默认调起输入法

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1169]
**是否为新品（必填）**
新品&在售

**关联的产品model**
yeelink.light.dnlight2等等等

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 7.0+/iOS 12.0+] 
- SDK分支: [eg.master/10022/...]
- 相关模块:[eg.miot/ui/Dialog/InputDialog|miot/ui/InputDialog]

**现象（必填）**
1、直接follow SDK开发文档在render里面调用百分百crash，已告知米家同学，在此记录一下
2、使用miot/ui/InputDialog的时候被OverLay嵌套设置autofocus属性无法调起输入法。
**期望（必填）**
1、不crash，被Overlay包裹可以默认调起输入法

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
用TextInput试过，设置AutoFocus就可以调起输入法

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
Dialog/InputDialog crash 已经解决，SDK_10022/SDK_10023最新代码即可
