### ISSUE TITLE
Host.ui.privacyAndProtocolReview('软件许可及服务协议', licenseURL, '隐私协议', policyURL)报错

### ISSUE THREAD

**Issue by shanchaojie** [MiEcosystem/miot-plugin-sdk#117]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
调用Host.ui.privacyAndProtocolReview('软件许可及服务协议', licenseURL, '隐私协议', policyURL)这个接口的时候报错:newUrl is not defined.com.xiaomi.demo下的查看使用条款和隐私协议操作也会有这种情况.

#### 期望
可以正常进入相关界面.

#### 其他的上下文/日志/截图

![679db6eafa5ac526a2aa4d45de3a9cf1](https://user-images.githubusercontent.com/13048291/49631582-8c5a4a80-fa2d-11e8-9304-23d392194e39.png)

#### 尝试过的解决办法

重复刷新不好使

**Comment by LiuMengzhou** [comment]
@shanchaojie 正在修复
