### ISSUE TITLE
UI.MHDatePicker的问题

### ISSUE THREAD

**Issue by lingzhiwen** [MiEcosystem/miot-plugin-sdk#1170]
**是否为新品（必填）**
新品

**关联的产品model**
所有model

**项目ID（必填）**
无项目ID

**企业名称（必填）**
深圳绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 9
- SDK分支: 10021
- 相关模块:UI

**现象（必填）**
MHDatePicker重复使用，不能动态更新 副标题subtitle 和 默认选中current的值

**期望（必填）**
MHDatePicker重复使用，能够动态更新 副标题subtitle 和 默认选中current的值

**其他的上下文/日志/截图**
这里不会执行state的更新操作
![image](https://user-images.githubusercontent.com/9277509/60935914-ff96a880-a2fd-11e9-900f-463b956b068c.png)

**尝试过的解决办法**
自己改造MHDatePicker,加上动态更新state的操作；在插件内使用。
![image](https://user-images.githubusercontent.com/9277509/60935648-328c6c80-a2fd-11e9-8ad1-dc98c3f42080.png)

希望提供更加完善的DatePicker.

**Comment by LiuMengzhou** [comment]
caa96abe20a7474a7f70c0663fef5018a8031e57

拉取SDK_10023最新代码
