### ISSUE TITLE
Mesh设备创建灯组，Android可选设备显示不完整，IOS正常

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1171]
**是否为新品（必填）**
在售

**关联的产品model**
yeelink.light.dnlight2 | Yeelight LED筒灯
yeelink.light.meshbulb1 | Yeelight LED球泡
yeelink.light.meshbulb2 | Yeelight LED烛泡
yeelink.light.spot1 | Yeelight LED射灯
**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
 - 从Mesh单灯插件进入设置页面，选在创建灯组功能，IOS和Android可选的设备不一致，IOS正常，Android不正确。
 - 调用的接口：  Host.ui.openMeshDeviceGroupPage("add",did);
![WechatIMG122](https://user-images.githubusercontent.com/42829167/60936964-76817080-a301-11e9-9753-749e700860dc.jpeg)

**期望（必填）**
期望同IOS一样能够正确显示

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@DennisJu007   麻烦将设备分享给 8944158105账号，同时说下设备设备model及api对应的参数，我这边调试下，谢谢。

**Comment by DennisJu007** [comment]
是想分享给894158105这个账号对不（已分享），分享的设备看不到米家的通用设置界面且这个产品还未在新RN框架上传过，你那边也可以调试是吧，要传递的接口参数是设备的did，设备model：yeelink.light.dnlight2 @lvjie0519

**Comment by fishle** [comment]
@DennisJu007 能给下截图的那个iPhone上登录的小米账号及密码（可以的话发到fishle2016@qq.com）？只是分享设备过来没法定位，我们的账号没有你那个房间。

**Comment by DennisJu007** [comment]
@fishle 感谢大佬支持，已线下沟通，等米家发版本解决
