### ISSUE TITLE
StringSpinner时候Android报错 divide by zero

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1174]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    
是否为新品（必填）
不是

关联的产品名称（必填）
“米家饭煲类” 

项目ID（必填）
项目ID

企业名称（必填）
上海纯米电子科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 8.00]
SDK分支: [10010]
相关模块:[UI]
现象（必填）
使用StringSpinner时候，iOS没有问题，但是安卓的当你的dataSource传的是["00"]时候，会报错divide by zero,    我使用的2个StringSpinner来选择小时和分钟， 当滚动分钟没问题， 当滚动小时时候  如果我这个小时对应只有一个‘00’分钟， 安卓会报错

期望（必填）
Android也不报错

**Comment by zanetti4** [comment]
我用安卓7测试没发现这个问题。你怎么使用的 StringSpinner？请贴上你的代码

**Comment by joyami** [comment]
好的
return (
	<View	
		style={{ 
			width: ScreenUtil.screenWidth,
			height: ScreenUtil.scaleViewSize(196),
			backgroundColor: '#ffffff',
			flexDirection: 'row',
				}}>
					<View style={{flex: 1, 
								  borderRightColor: 'rgba(0, 0, 0, 0.15)', 
								  borderRightWidth: StyleSheet.hairlineWidth}}>
						<StringSpinner
							style={{flex: 1}}
							dataSource={item1}
							unit={getString('theHourText')}
							defaultValue={dSelectedH.toString()}
							pickerInnerStyle={styles.innerStyle}
							onValueChanged={(data) => { this.changeH(data.newValue) }}
						/>
					</View>
					<StringSpinner
						style={{flex: 1}}
						dataSource={["00"]}  // 这里固定为00， iOS可以Android直接崩溃的
						unit={getString('theMinuteText')}
						defaultValue={dSelectedM.toString()}
						pickerInnerStyle={styles.innerStyle}
						onValueChanged={(data) => { this.changeM(data.newValue) }}
					/>
				</View>
			)

**Comment by joyami** [comment]
`return (
				<View	
					style={{ 
						width: ScreenUtil.screenWidth,
						height: ScreenUtil.scaleViewSize(196),
						backgroundColor: '#ffffff',
						flexDirection: 'row',
				}}>
					<View style={{flex: 1, 
								  borderRightColor: 'rgba(0, 0, 0, 0.15)', 
								  borderRightWidth: StyleSheet.hairlineWidth}}>
						<StringSpinner
							style={{flex: 1}}
							dataSource={item1}
							unit={getString('theHourText')}
							defaultValue={dSelectedH.toString()}
							pickerInnerStyle={styles.innerStyle}
							onValueChanged={(data) => { this.changeH(data.newValue) }}
						/>
					</View>
					<StringSpinner
						style={{flex: 1}}
						dataSource={["00"]}  // 这里固定为00， iOS可以Android直接崩溃的
						unit={getString('theMinuteText')}
						defaultValue={dSelectedM.toString()}
						pickerInnerStyle={styles.innerStyle}
						onValueChanged={(data) => { this.changeM(data.newValue) }}
					/>
				</View>
			)`

**Comment by joyami** [comment]
```
return (
				<View	
					style={{ 
						width: ScreenUtil.screenWidth,
						height: ScreenUtil.scaleViewSize(196),
						backgroundColor: '#ffffff',
						flexDirection: 'row',
				}}>
					<View style={{flex: 1, 
								  borderRightColor: 'rgba(0, 0, 0, 0.15)', 
								  borderRightWidth: StyleSheet.hairlineWidth}}>
						<StringSpinner
							style={{flex: 1}}
							dataSource={item1}
							unit={getString('theHourText')}
							defaultValue={dSelectedH.toString()}
							pickerInnerStyle={styles.innerStyle}
							onValueChanged={(data) => { this.changeH(data.newValue) }}
						/>
					</View>
					<StringSpinner
						style={{flex: 1}}
						dataSource={["00"]}  // 这里固定为00， iOS可以Android直接崩溃的
						unit={getString('theMinuteText')}
						defaultValue={dSelectedM.toString()}
						pickerInnerStyle={styles.innerStyle}
						onValueChanged={(data) => { this.changeM(data.newValue) }}
					/>
				</View>
			)
```

**Comment by joyami** [comment]
`return (
				<View	
					style={{ 
						width: ScreenUtil.screenWidth,
						height: ScreenUtil.scaleViewSize(196),
						backgroundColor: '#ffffff',
						flexDirection: 'row',
				}}>
					<View style={{flex: 1, 
								  borderRightColor: 'rgba(0, 0, 0, 0.15)', 
								  borderRightWidth: StyleSheet.hairlineWidth}}>
						<StringSpinner
							style={{flex: 1}}
							dataSource={item1}
							unit={getString('theHourText')}
							defaultValue={dSelectedH.toString()}
							pickerInnerStyle={styles.innerStyle}
							onValueChanged={(data) => { this.changeH(data.newValue) }}
						/>
					</View>
					<StringSpinner
						style={{flex: 1}}
						dataSource={["00"]}  // 这里固定为00， iOS可以Android直接崩溃的
						unit={getString('theMinuteText')}
						defaultValue={dSelectedM.toString()}
						pickerInnerStyle={styles.innerStyle}
						onValueChanged={(data) => { this.changeM(data.newValue) }}
					/>
				</View>
			)`

**Comment by joyami** [comment]
```
return (
				<View	
					style={{ 
						width: ScreenUtil.screenWidth,
						height: ScreenUtil.scaleViewSize(196),
						backgroundColor: '#ffffff',
						flexDirection: 'row',
				}}>
					<View style={{flex: 1, 
								  borderRightColor: 'rgba(0, 0, 0, 0.15)', 
								  borderRightWidth: StyleSheet.hairlineWidth}}>
						<StringSpinner
							style={{flex: 1}}
							dataSource={item1}
							unit={getString('theHourText')}
							defaultValue={dSelectedH.toString()}
							pickerInnerStyle={styles.innerStyle}
							onValueChanged={(data) => { this.changeH(data.newValue) }}
						/>
					</View>
					<StringSpinner
						style={{flex: 1}}
						dataSource={["00"]}  // 这里固定为00， iOS可以Android直接崩溃的
						unit={getString('theMinuteText')}
						defaultValue={dSelectedM.toString()}
						pickerInnerStyle={styles.innerStyle}
						onValueChanged={(data) => { this.changeM(data.newValue) }}
					/>
				</View>
			)
```

**Comment by zanetti4** [comment]
@LiuMengzhou 我未能复现此问题，请你协助查看。

**Comment by Banjiemin** [comment]
NumberSpinnerDemo在ios上（测试机：iphone6）滚动的时候大概率的crash （米家app退出），

我猜测
是播放滚动声音报错，

log line：2712
Jul 10 16:04:02 Banjiemins-iPhone MiHome[14057] <Notice>: [Bugly]  Trapped uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]' 

[NumberSpinner-crash.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3381187/NumberSpinner-crash.txt)

**Comment by zanetti4** [comment]
@Banjiemin 你遇到的是另一个问题，请你新建一个 issue。我们另做处理

**Comment by YunzzzZ** [comment]
稍微滑快点就会报错，希望尽快解决 @zanetti4

**Comment by joyami** [comment]
> @LiuMengzhou 我未能复现此问题，请你协助查看。

@zanetti4 @LiuMengzhou 

我们今天测试后发现此问题又复现了，以下是测试数据/步骤，麻烦帮忙看下如何解决StringSpinner的Android报错问题，谢谢。

产品model：chunmi.cooker.k1pro1
模组型号：ESP-WROOM-32D
模组版本：1.3.1
手机系统：安卓miui10.3
APP版本：5.5.37
异常的uid：442376660
异常的did：85619306
异常的现象描述（测试步骤）：
1.进入插件
2.点击煮粥模式
3.点击烹饪时长，选择自定义烹饪时长
4.先选择4小时，再选择分钟数
5.米家app崩溃
异常的时间点：7/16号13:53:00
连接网络环境：无线网络H3C

**Comment by joyami** [comment]
![7fiyk-u4uge](https://user-images.githubusercontent.com/34296463/61273056-30358100-a7db-11e9-8954-4caa8812dc2f.gif)

**Comment by joyami** [comment]
![stringspinner安卓报错](https://user-images.githubusercontent.com/34296463/61273435-18aac800-a7dc-11e9-9abc-bcc4c4ceff66.gif)

请查收测试反馈的录屏gif

**Comment by zanetti4** [comment]
@lvjie0519 我快速滑动也没有出现异常，请你协助查看

**Comment by lvjie0519** [comment]
@joyami  已修复，测试apk 给了你那边如上微信人员，我这边测试ok，有问题及时反馈，谢谢。

**Comment by joyami** [comment]
好了  谢了！
