### ISSUE TITLE
三星s8 Host.getwifiInfo()获取不到正确信息

### ISSUE THREAD

**Issue by shidaiyue1** [MiEcosystem/miot-plugin-sdk#1175]
**是否为新品（必填）**
在售

**关联的产品model**
ksmb.treadmill.v1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
金史密斯科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
三星s8在调用wifi接口时返回unknown ssid ；BSSID返回:00

**期望（必填）**
三星s8可以接收正确WiFi信息

**其他的上下文/日志/截图**
![b45d2a0235af7015c55c44ce7eccdab](https://user-images.githubusercontent.com/46240651/60952742-66cc5100-a32e-11e9-9923-a77449247215.png)

**尝试过的解决办法**
暂时绕过s8

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@shidaiyue1   你本地电脑有搭建Android开发环境吗？
WifiManager mWifiManager = (WifiManager) getApplicationContext().getSystemService(Context.WIFI_SERVICE);
WifiInfo mWifiInfo = mWifiManager.getConnectionInfo();
麻烦你那边通过原生代码测试下  mWifiInfo 的内容，我这边没有三星s8的手机，不太方便测试，谢谢。

**Comment by shidaiyue1** [comment]
2019-07-11 14:56:44.011 14783-14783/com.example.a18531.appdemo E/TAG: SSID: , BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, Supplicant state: COMPLETED, RSSI: -36, Link speed: 104Mbps, Frequency: 2427MHz, Net ID: 5, Metered hint: false, GigaAp: false, VenueName: null, WifiMode: 4, score: 60
（这是用原生代码打印出来的）

**Comment by lvjie0519** [comment]
![image](https://user-images.githubusercontent.com/22487747/61029261-3a2b3e80-a3ed-11e9-9fa6-362e50cebdf3.png)
看下这个返回值， 看代码你那边返回WifiSsid.NONE了，检查下你那边wifi情况，谢谢。

**Comment by shidaiyue1** [comment]
我们的WiFi是有名称的，ssid是有的，

**Comment by lvjie0519** [comment]
@shidaiyue1  麻烦再调试下RN， 我这边就是把mWifiInfo.getSSID() 返回给js的。

**Comment by shidaiyue1** [comment]
刚才查到问题原因
![5ac1a5edb7fd805383d30f5514827a5](https://user-images.githubusercontent.com/46240651/61031237-a90a9680-a3f1-11e9-81ff-b53d51896b27.png)
请参考上图

**Comment by shidaiyue1** [comment]
必须开启定位授权才能获取到相关信息

**Comment by lvjie0519** [comment]
@shidaiyue1  麻烦添加下微信（微信号：18750118631），详细讨论下，谢谢。

**Comment by lvjie0519** [comment]
@shidaiyue1  已修复，请使用最新apk测试，谢谢。
