### ISSUE TITLE
Host.locale.getLocation  此接口Android和iOS 请求响应速度不一样

### ISSUE THREAD

**Issue by Monkey0803** [MiEcosystem/miot-plugin-sdk#1176]
紧急优先级

SDK ： 10021
电脑操作系统: Mac OS
手机系统: iOS  、 Android
相关模块:
API或者常量:
现象 ：
Android响应速度很快， iOS响应速度很慢

**Comment by santcool** [comment]
因为iOS使用的是最高精度的定位，所以会比较慢。你可以使用RN自己提供的定位来进行定位，此定位可自定义定位精度参数：
var Geolocation = require('Geolocation');
 
      Geolocation.getCurrentPosition(
          location => {
              var result = "速度：" + location.coords.speed +
                          "\n经度：" + location.coords.longitude +
                          "\n纬度：" + location.coords.latitude +
                          "\n准确度：" + location.coords.accuracy +
                          "\n行进方向：" + location.coords.heading +
                          "\n海拔：" + location.coords.altitude +
                          "\n海拔准确度：" + location.coords.altitudeAccuracy +
                          "\n时间戳：" + location.timestamp;
              alert(result);
          },
          error => {
            alert("获取位置失败："+ error)
          }
      );
  }

**Comment by Monkey0803** [comment]
此接口获取的只是经纬度，我们需要进行逆地理编码，这就需要去调用百度或者高德的api，就需要去注册账户，申请api 的可以，很麻烦。你只需把你们的定位精度修改下，就解决了这个问题，或者把这个选择精度的api暴露给开发者

**Comment by Monkey0803** [comment]
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/11564933/63145379-da4a3800-c029-11e9-82fc-b67def04436b.png">

**Comment by Monkey0803** [comment]
@santcool
