### ISSUE TITLE
图片资源加载异常

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#1178]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 9.0]
SDK分支: [master]
相关模块:[Image]
现象（必填）
内测用户反馈偶现图片资源加载异常。
基本上是除了首页的图片加载正常，其他页面的图片都显示异常。
退出插件后再次进入则全都显示正常。

期望（必填）
图片加载正常

其他的上下文/日志/截图
![5031562815428_ pic_hd](https://user-images.githubusercontent.com/14890491/61020409-3e952e80-a3d0-11e9-9ae9-ef779bf1b158.jpg)
![5041562815429_ pic_hd](https://user-images.githubusercontent.com/14890491/61020417-4523a600-a3d0-11e9-8038-bbe6aeb25105.jpg)
![5051562815430_ pic_hd](https://user-images.githubusercontent.com/14890491/61020428-49e85a00-a3d0-11e9-9d23-aaaac6f3d8b3.jpg)

尝试过的解决办法
临时解决：在Image的onError方法返回的时候提示用户提出插件重新进入。

**Comment by zanetti4** [comment]
以上三张图片如果加载正常，是什么样子？

**Comment by huangjr126** [comment]
![image](https://user-images.githubusercontent.com/48087638/61032455-11f30e00-a3f4-11e9-87b5-0ff38997b55d.png)
![image](https://user-images.githubusercontent.com/48087638/61032484-1e776680-a3f4-11e9-87a8-e6574478acdd.png)
![image](https://user-images.githubusercontent.com/48087638/61032538-34852700-a3f4-11e9-9a81-bb2f6d68d6cb.png)
@zanetti4 您好，这是三张正常运作时的截图

**Comment by zanetti4** [comment]
onError 回调函数有参数`{nativeEvent: {error}}`，打印这个参数能得到什么错误信息？

**Comment by tangkun92** [comment]
> onError 回调函数有参数`{nativeEvent: {error}}`，打印这个参数能得到什么错误信息？

开发已添加打印日志error代码，等待测试重现后打印日志，再反馈

**Comment by zanetti4** [comment]
好的

**Comment by zanetti4** [comment]
我先把这个问题关闭了，如果测试重现，请提供打印日志，再打开
