### ISSUE TITLE
打包上传开发平台后只有iOS能下载， Android不能下载。

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#1179]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

---
**是否为新品（必填）**
新品

**关联的产品model**
yeelink.gateway.v1

**项目ID（必填）**
mesh网关
**企业名称（必填）**
yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android /iOS ]
- SDK分支: [10022]
- 相关模块:[]

**现象（必填）**
打包上传开发平台后只有iOS能下载， Android不能下载。

**期望（必填）**
iOS， Android都能下载

**Comment by zanetti4** [comment]
Android不能下载时，提示什么错误？

**Comment by TheWalkingDead1024** [comment]
> Android不能下载时，提示什么错误？

大佬你好，昨天已经和米家开发同事确认了是因为代码问题，代码中存在Object的属性重定义问题（错误截图如下）。
![image](https://user-images.githubusercontent.com/9053681/61099571-613d4b00-a495-11e9-9ded-3fa60b5ab3ed.png)

目前iOS是有容错机制，安卓则没有。如果存在重定义问题的话，调试的时候，米家安卓下不能进入插件，一直卡在缓冲界面，用Android Studio也没有看到任何错误提示，React Native Debugger下没有看到任何warning和crash情况。记得之前如果存在重定义问题，在插件上会有红色错误提示窗口，开启远程调试的话，也能在React Native Debugger看到相关错误信息，不知道为什么现在版本（5.5.37测试版，下载地址https://pan.mioffice.cn:443/#/link/A6B887A51C110D071903C435781584FA）看不到这些错误信息了。

**Comment by fishle** [comment]
看不到错误信息，是因为安装的是release版；如果是debug版就可以看到

**Comment by TheWalkingDead1024** [comment]
> 看不到错误信息，是因为安装的是release版；如果是debug版就可以看到

你好，我们用的就是在github下载的debug版本
