### ISSUE TITLE
关于米家恒温水壶蓝牙固件升级问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#118]
---

#### 环境
- 电脑操作系统:ma c
- 手机系统:ios 12
- 相关模块:蓝牙

#### 现象

米家恒温水壶的蓝牙固件升级模块，iOS是米家app单独提供了一个模块MHViomiOTAModule来提供升级功能的。看了新框架的相关文档与问题系列，似乎并没有类似的相关说明，不知道类似这些功能，在新框架里，怎么接入呢。Android又是否支持了呢。

#### 期望

希望在这方便有个说明，提供下解决方案

**Comment by Copypeng** [comment]
iOS 上已有的模块，可保持不变。不过安卓上 RN 没有相关 Lib。

如果能力允许的话，我们推荐不依赖Lib，插件内用 js 重构，利用SDK提供的蓝牙读写能力来OTA。
不行就先升级 iOS，安卓使用老插件。等使用 js 重构完成，安卓平台再切换。

**Comment by flingInTheSky** [comment]
OK，明白

**Comment by flingInTheSky** [comment]
@Copypeng 我在调试iOS固件升级的MHViomiOTAModule模块，在写入数据时，BluetoothEvent.bluetoothCharacteristicValueChanged并没有收到对应消息，但是也没用报错，其他的设备控制数据的写入是没问题的。以前旧的SDK，写入数据的是base64格式，新的SDK，似乎是16进制字符串，不知道是不是写入的数据格式有问题。能否告知下iOS 的写入数据支持什么数据格式？bt.getService('...').getCharacteristic('...').write(value)接口，到原生的[self.peripheral writeValue : value
              forCharacteristic :characteristic
                           type : CBCharacteristicWriteWithoutResponse];之间，value经过了怎么样的变化？

**Comment by LiuMengzhou** [comment]
@flingInTheSky #134
