### ISSUE TITLE
ios WebView使用不了，RN版本54

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1180]
Unhandled JS Exception: Error: Error: `WebView` has no propType for native prop `RCTWebView.onScrollChange` of native type `BOOL`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

**Comment by zanetti4** [comment]
请按照模版提问，谢谢

**Comment by santcool** [comment]
<WebView style={{flex:3}} onScrollChange={(res)=>{
                    console.log(res.nativeEvent);
                }} source={{uri:'https://www.baidu.com'}} />
我这边调试是好的。你再检查下用法？

**Comment by hc520messi** [comment]
一直有这个错误，一直不修复？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
