### ISSUE TITLE
高频率调用Service.smarthome.getDeviceData回调返回顺序会乱掉

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#1181]
---
**是否为新品（必填）**
在售

**关联的产品model**
philips.light,nlight
**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
飞彗
**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 5.5.37/iOS 12.3.1]
- SDK分支: [master/10021/...]
- 相关模块:[Service/smarthome]

**现象（必填）**
高频率调用接口Service.smarthome.getDeviceData，未按照调用顺序返回结果，两条请求调用间隔短，数据量大的可能返回晚一点
**期望（必填）**
按照接口调用顺序返回回调结果

**其他的上下文/日志/截图**
正常返回顺序（黑色数字时间戳，一行是一次请求，蓝色数字返回查询到的数据条数）
![屏幕快照 2019-07-11 下午2 18 11](https://user-images.githubusercontent.com/9348270/61026931-6c39a200-a3e7-11e9-9a7d-be5661927b66.png)
异常返回顺序
![屏幕快照 2019-07-11 下午2 18 01](https://user-images.githubusercontent.com/9348270/61026965-7f4c7200-a3e7-11e9-931f-81be311c672b.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请把上面的**环境**信息填写完整

**Comment by zanetti4** [comment]
@santcool @lvjie0519 getDeviceData() 返回 Promise 对象，

> Promise 对象用于表示一个异步操作的最终状态（完成或失败），以及该异步操作的结果值。

所以*123start*说的这种情况应该是正常现象吧？和你们确认一下

**Comment by santcool** [comment]
这有什么问题呢，异步你是无法控制返回顺序的，如果想控制，你可以选择把promise串起来，请求完一个之后，再请求另一个
