### ISSUE TITLE
设备主删除被分享的用户，在被分享的用户的设备列表里，仍能看到被分享的设备

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#1182]
**是否为新品（必填）**
填 新品 

**关联的产品model**
dsm.lock.r5

**项目ID（必填）**
com.dsm.q3
**企业名称（必填）**
德施曼
**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: [master/10000/...]
- 相关模块:[Service.security]

**现象（必填）**
米家App 已更新到最新版本
设备主删除被分享的用户，在被分享的用户的设备列表里，仍能看到被分享的设备

调用：ISecureKey.remove()   方法成功后  再调用loadSecureKeys（），方法，确实已经没有刚刚被remove  的key了，为什么被分享的用户还是能够看到设备的呢？

设备主的账号：15851265543 
被分享的用户的账号：15851265543 

**期望（必填）**
设备主调用删除key的接口后，被分享的用户列表中看不到设备主分享的设备

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
设备主的账号和被分享的用户的账号是一样的，自己分享给自己？

**Comment by changgongxinshi** [comment]
不好意思，被分享的用户号码粘贴错了
被分享的用户号码:18557536371

**Comment by lvjie0519** [comment]
@changgongxinshi 
看代码走的都是网络请求，  ios存在此问题吗？

**Comment by changgongxinshi** [comment]
1.已经反复多次尝试，也多次杀死应用重新进入，效果相同
2.ios也存在相同的问题

**Comment by lvjie0519** [comment]
@changgongxinshi   了解， 我们这边排查下，修复及时回复。

**Comment by lvjie0519** [comment]
@changgongxinshi   麻烦添加下微信（sky-boy-0519）详聊下。

**Comment by lvjie0519** [comment]
@changgongxinshi   经沟通，服务端设计如此。分享钥匙会带着锁一起过去，主要是为了被分享人的app能展示插件，进到插件里，但是锁和钥匙权限关系不关联，所以就形成这个现象了。
