### ISSUE TITLE
【Android】开启安全码后，在进入插件时手机白屏。

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#1184]
---
**是否为新品（必填）**
在售

**关联的产品model**
viomi.hood.v1

**项目ID（必填）**
P18-0301

**企业名称（必填）**
云米

**环境（必填）**
- 手机系统:[eg.Android]
- SDK分支: [eg.10020/10021]
- 相关模块:[插件加载]

**现象（必填）**
开启安全码后，在进入插件时手机白屏。

补充信息：
1、不开启安全码，进入插件正常；
2、iPhone 手机，正常；
3、其他插件正常。
4、出现该问题的机型：小米8，红米k20，vivo z1和华为畅玩5A，几率：约40%

**期望（必填）**
正常加载显示插件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**Comment by lvjie0519** [comment]
@flingInTheSky  
 1、一直处于白屏状态吗？
2、设备分享给 894158105 ，我这边试下看看。

**Comment by flingInTheSky** [comment]
@lvjie0519 更新了Card组件后，发现没问题了。猜测是因为旧版Card组件导致的问题。
