### ISSUE TITLE
NumberSpinnerDemo在IOS上滚动时大概率crash（米家app退出）

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#1185]
环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 10.3.3]
SDK分支: [master/10021/]
相关模块:[Host.ui.MHDatePicker]
ios米家app版本： buildid 为256

【描述】
NumberSpinnerDemo在ios上（测试机：iphone6）滚动的时候大概率的crash （米家app退出），

我怀疑是播放滚动声音报错，请看log line：2712
 Jul 10 16:04:02 Banjiemins-iPhone MiHome[14057] <Notice>: [Bugly]  Trapped uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'

【附件】
[NumberSpinner-crash.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3384785/NumberSpinner-crash.txt)

**Comment by zanetti4** [comment]
@santcool 我用 ios 12.3.1 测试，并未发现此问题。请你协助查看

**Comment by santcool** [comment]
你怎么使用的，贴一下代码看看

**Comment by Banjiemin** [comment]
就是把com.xiao.demo下的NumberSpinnerDemo.js拷贝一份到我们插件项目中来引用（没有任何改动）

**Comment by santcool** [comment]
已修复，请用此包验证：https://fir.im/tes5?release_id=5d31b0baf945487c06b46f4a
