### ISSUE TITLE
android分享截屏内容不完整

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1186]
**是否为新品（必填）**
在售

**关联的产品model**
xiaoxun.ro_skates.v1

**企业名称（必填）**
上海小寻科技有限公司

**环境（必填）**
- 手机系统:[Android ]
- SDK分支: [10020]
- 相关模块:[CommonModules/Chart]

**现象（必填）**
android分享截屏时Linechart组件内的这些线丢失，截屏内容不正确，ios分享截屏正常

**期望（必填）**
分享截屏正常

**其他的上下文/日志/截图**
正确内容截屏
![WechatIMG12](https://user-images.githubusercontent.com/34823528/61101584-e8da8800-a49c-11e9-9b79-bae7a9c7a023.png)
Android分享截屏
![WechatIMG13](https://user-images.githubusercontent.com/34823528/61101657-2a6b3300-a49d-11e9-89cf-436cc38776db.jpeg)

**Comment by fishle** [comment]
能具体说下截图的时机吗？我这边用ChartView可以正常截图

**Comment by heping99** [comment]
@fishle 我们这边测试好几个Android机型都有这个问题

**Comment by heping99** [comment]
截图时机就是界面有折线后，点击调到分享界面时截图的图，分享调用的代码：
onPressRight2={()=>{                 
                    Host.file.screenShot("temp.png").then(result => {
                    Host.ui.openShareListBar('小米智能家庭', '小米智能家庭', {uri: result},null);
                    })}}

**Comment by fishle** [comment]
目前的截图接口对LineChart支持不是很好，可以用ChartView来实现你想要的效果吗，ChartView截图是OK的

**Comment by heping99** [comment]
@fishle 你说的ChartView是哪个控件？没有找到

**Comment by fishle** [comment]
可以看看这里：com.xiaomi.demo/main/ThirdPartyDemo/Victory-Native/views/char-view.js
