### ISSUE TITLE
在米家中添加设备时找不到我们设定的产品

### ISSUE THREAD

**Issue by jacob929** [MiEcosystem/miot-plugin-sdk#1187]
---
**是否为新品（必填）**
 新品  

**关联的产品model**
duoqin.safe.pbfv01

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
深圳市多亲科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [SmartHome_Dev_62910_5.5.37.1_sdk.apk] 

**现象（必填）**
在米家中添加设备时找不到我们设定的产品，
git clone git@github.com:MiEcosystem/miot-plugin-sdk.git
下载米家插件SDK失败，返回：

Cloning into 'miot-plugin-sdk'...
Warning: Permanently added the RSA host key for IP address '52.74.223.119' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zanetti4** [comment]
请检查在 git 连接 github 时，公钥是否配置正确

**Comment by jacob929** [comment]
在米家APP中添加设备时找不到我们设定的产品，怎么办？我的小米开发ID是：173930516 @zanetti4

**Comment by cfJand** [comment]
@jacob929  添加设备找不到，是 附近设备 中扫描不到，还是手动添加里面没有你们的设备？请详细描述问题。

**Comment by cfJand** [comment]
如果是附近设备里面没有扫描到你的设备，可能是广播协议有问题；
如果在手动添加设备里面，没有发现你的设备，那么可能是因为没有正式上线的设备，需要将你的账号添加到设备的白名单里面去，才能显示出来。

**Comment by cfJand** [comment]
issue长时间未回复，close。
