### ISSUE TITLE
从Package.version获取的iOS，Android插件版本号不一致

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#1188]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

---
**是否为新品（必填）**
 在售

**关联的产品model**
common

**项目ID（必填）**
米家插件

**企业名称（必填）**
yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android iOS]
- SDK分支: [10022]
- 相关模块:[Package]

**现象（必填）**
从Package.version获取的iOS，Android插件版本号不一致

**期望（必填）**
返回相同的版本号

**Comment by RowingCaptainChen** [comment]
现象：打包完成后Android端从Package.version获取的版本号与project.json文件中version_code版本相同，iOS端从Package.version获取的版本号与lot开发平台相同。
主要有以下疑问：
1.Android为什么从project.json文件中获取版本号。而且与iOS从Package.version中获取的不一致。
2.Package.version能获取版本号，为什么还要在project.json中配置version_code。

**Comment by TheWalkingDead1024** [comment]
有人能帮忙看一下这个问题吗？

**Comment by lvjie0519** [comment]
@RowingCaptainChen   我们这边排查下，请稍后。

**Comment by TheWalkingDead1024** [comment]
> @RowingCaptainChen 我们这边排查下，请稍后。

好的，感恩

**Comment by TheWalkingDead1024** [comment]
> @RowingCaptainChen 我们这边排查下，请稍后。

大佬，现在有结论么？

**Comment by lvjie0519** [comment]
@RowingCaptainChen  @TheWalkingDead1024   已修复，使用最新apk测试下，5.5.37.6版本。
