### ISSUE TITLE
新版RN插件提交白名单测试后用不了

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1189]
---
**是否为新品（必填）**
在售

**关联的产品model**
“jiqid.mistory.ipen1”

**项目ID（必填）**
不清楚

**企业名称（必填）**
南京机器岛科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/iOS 12.0
- SDK分支:10022

- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
在小米IOT开发者平台提交插件，并开启白名单调试，重新进入米家发现依然加载的是老版插件内容

**期望（必填）**
展示新版插件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/17521937/61109056-868e8100-a4b6-11e9-895d-4dbb2e67a2d3.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
需要半小时左右才能使用，记得清除缓存。如果再不行，抓包fetch_plugin接口，贴在这儿，谢谢。

**Comment by Aphrodite123** [comment]
> 需要半小时左右才能使用，记得清除缓存。如果再不行，抓包fetch_plugin接口，贴在这儿，谢谢。

fetch_plugin接口时机调用，我从米家APP开启到点击我的插件进入并没有抓到该接口，

#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
1	200	HTTP	Tunnel to	ib.snssdk.com:443	0						
2	 - 	HTTP	Tunnel to	clients1.google.com:443	-1			chrome:7652			
3	200	HTTP	Tunnel to	shopapi.io.mi.com:443	0						
4	200	HTTP	Tunnel to	tp.hd.mi.com:443	0						
5	200	HTTP	Tunnel to	shopapi.io.mi.com:443	0						
6	200	HTTP	Tunnel to	api.m.mi.com:443	0						
7	200	HTTP	android.bugly.qq.com	/rqd/async?aid=53ea472e-47fa-4626-90af-3ae7cc995aa5	147						
8	200	HTTP	Tunnel to	api.io.mi.com:443	0						
9	 - 	HTTP	Tunnel to	graph.facebook.com:443	-1						
10	 - 	HTTP	Tunnel to	graph.facebook.com:443	-1						
11	200	HTTP	Tunnel to	api.io.mi.com:443	0						
12	200	HTTP	Tunnel to	api.io.mi.com:443	0						
13	200	HTTP	Tunnel to	ypsupport2.kefu.mi.com:443	0						
14	200	HTTP	Tunnel to	api.map.baidu.com:443	0						
15	200	HTTP	Tunnel to	api.map.baidu.com:443	0						
16	200	HTTP	data.mistat.xiaomi.com	/mistats/v2	112		application/json;charset=UTF-8				
17	200	HTTP	Tunnel to	api.account.xiaomi.com:443	0						
18	200	HTTP	Tunnel to	api.io.mi.com:443	0						
19	200	HTTP	Tunnel to	api.io.mi.com:443	0						
20	200	HTTP	Tunnel to	api.io.mi.com:443	0						
21	200	HTTP	Tunnel to	api.io.mi.com:443	0						
22	200	HTTP	Tunnel to	api.io.mi.com:443	0						
23	200	HTTP	Tunnel to	api.account.xiaomi.com:443	0						
24	200	HTTP	Tunnel to	api.account.xiaomi.com:443	0						
25	200	HTTP	api.m.mi.com	/v1/eshop/list	296		application/json; charset=utf-8				
26	200	HTTP	Tunnel to	api.ad.xiaomi.com:443	0						
27	200	HTTP	Tunnel to	shopapi.io.mi.com:443	0						
28	200	HTTP	Tunnel to	api.io.mi.com:443	0						
29	200	HTTP	Tunnel to	mimc.chat.xiaomi.net:443	0						
30	200	HTTP	Tunnel to	account.xiaomi.com:443	0						
31	200	HTTP	Tunnel to	account.xiaomi.com:443	0						
32	200	HTTP	Tunnel to	shopapi.io.mi.com:443	0						
33	200	HTTP	Tunnel to	home.mi.com:443	0						
34	200	HTTP	Tunnel to	ypsupport2.kefu.mi.com:443	0						
35	200	HTTP	data.mistat.xiaomi.com	/mistats/v2	112		application/json;charset=UTF-8				
36	200	HTTP	data.mistat.xiaomi.com	/mistats/v2	112		application/json;charset=UTF-8				
37	200	HTTP	Tunnel to	api.map.baidu.com:443	0						
38	 - 	HTTP	Tunnel to	graph.facebook.com:443	-1						
39	200	HTTP	study.jiqid.net	/mitu/tongji/quiz?requestId=1_1_19700119101233_623341&channel=1&clientType=1&version=1&timestamp=1563153960&appVersion=1.0.7&appType=4&tokenId=375674&babyId=0&page_num=0&page_size=5&level=2&sign=ZmQwNmQzYmI3NWE0ODViZjMwMWNhMGM4NmZiYzVhOGY1MTEwODc2MA==	50		application/json				
40	200	HTTP	study.jiqid.net	/mitu/tongji/quiz?requestId=1_1_19700119101233_852898&channel=1&clientType=1&version=1&timestamp=1563153960&appVersion=1.0.7&appType=4&tokenId=375674&babyId=0&page_num=0&page_size=5&level=1&sign=Njc1MTVlMTEzNGIzMDUzMjk3ZjMyMTY4NTUyM2MzZjIyNTgzNTcwNA==	50		application/json				
41	200	HTTP	study.jiqid.net	/mitu/tongji/period/duration?requestId=1_1_19700119101233_598166&channel=1&clientType=1&version=1&timestamp=1563153960&appVersion=1.0.7&appType=4&tokenId=375674&babyId=0&sign=NjA0Y2RjMDIzNzY5MDI5NjEyMjg0OGQ2NzFkNzI5ZmYzZjM2OGQwMw==	50		application/json				
42	200	HTTP	study.jiqid.net	/mitu/tongji/period/duration?requestId=1_1_19700119101233_553236&channel=1&clientType=1&version=1&timestamp=1563153960&appVersion=1.0.7&appType=4&tokenId=375674&babyId=0&sign=MzBiODk1MzlmMzE1MWQ4OGQ5YTY0ZDg0YzQ0MTRiMDQ4NjU3YzFkZA==	50		application/json				
43	200	HTTP	Tunnel to	api.io.mi.com:443	0						
44	200	HTTP	study.jiqid.net	/user/login?requestId=1_1_19700119101233_203388&channel=1&clientType=1&version=1&timestamp=1563153961&appVersion=1.0.7&appType=4&sign=ZTUyOTJjZjk1NmE4ZWZiZDgxNWE1NGU5NzRkNmQzYWFjYTE4MTNkOQ==	154		text/plain; charset=utf-8				
45	200	HTTP	study.jiqid.net	/user/userDeviceAndBaby?requestId=1_1_19700119101233_759090&channel=1&clientType=1&version=1&timestamp=1563153961&appVersion=1.0.7&appType=4&tokenId=375676&deviceType=4&babyType=4&sign=M2ZlYzQ1ZDhhNjIxODdlZjMzYWZjYTdiODAzNGNjYTc3ZTMyODViNQ==	657		text/plain; charset=utf-8				
46	200	HTTP	study.jiqid.net	/mitu/tongji/week_info?requestId=1_1_19700119101233_176873&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&start_at=0&end_at=0&sign=NDQ2NDA1OWNiZTg4ZGQ1YmY3ZmU0YTQ1ZWY2MjFhZmEwZDQ4ODZhZQ==	227		application/json				
47	200	HTTP	study.jiqid.net	/mitu/tongji/history?requestId=1_1_19700119101233_623857&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=7&sign=ZDMwMjNhZWYyOGE0ZmI5Yjg2ZjFkNzIwMjI4MWZmYjFhMjk1N2Q2OQ==	301		application/json				
48	200	HTTP	study.jiqid.net	/mitu/tongji/packets?requestId=1_1_19700119101233_574661&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=3&category=0&sign=MTA0MzY1Y2Y3NTI1MjM3YTFiYWZkMGUyOTFmMWExNTcwM2FhMjdlOA==	1,815		application/json				
49	200	HTTP	study.jiqid.net	/mitu/tongji/quiz?requestId=1_1_19700119101233_585233&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=5&level=2&sign=NTY3YzMxNzYzMmZmNjVmOGE1MTNhZTI0YTIzMDJmMGJiZGZmYWEyOQ==	41		application/json				
50	200	HTTP	study.jiqid.net	/mitu/tongji/quiz?requestId=1_1_19700119101233_669341&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=5&level=1&sign=Mzg0OGE2MTliMmJmMWU1NDMzN2UwNWI0MDI4NzQ2NzhiMDE3MGM2ZA==	41		application/json				
51	200	HTTP	study.jiqid.net	/mitu/tongji/period/duration?requestId=1_1_19700119101233_654064&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&sign=NTZkYjVkZWMyYWU2YzVjMWZkZTUxZGQ0ZmM2NWM0Mzg3MTgwMjY2YQ==	155		application/json				
52	200	HTTP	study.jiqid.net	/mitu/tongji/period/duration?requestId=1_1_19700119101233_728812&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&sign=NzdkNjFmNGY5Yzc2MWQyYzZkZGU4YTU5M2ZiNmUwMmQxMTIyODVlMw==	155		application/json				
53	200	HTTP	data.mistat.xiaomi.com	/mistats/v2	112		application/json;charset=UTF-8				
54	200	HTTP	study.jiqid.net	/mitu/tongji/week_info?requestId=1_1_19700119101233_649500&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&start_at=0&end_at=0&sign=NjE3OWIxZWZkY2Q3OGFmNDhmZGI1NGRhMmJjMjQ0ODI0NTFkYzY2Yg==	227		application/json				
55	200	HTTP	study.jiqid.net	/mitu/tongji/history?requestId=1_1_19700119101233_291481&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=7&sign=MmMyMTEwNjUxMDlhNzNjNjQ5YzE2ZTZiODAyNjJlNjg5MDkxNjdhOQ==	301		application/json				
56	200	HTTP	study.jiqid.net	/mitu/tongji/packets?requestId=1_1_19700119101233_532013&channel=1&clientType=1&version=1&timestamp=1563153962&appVersion=1.0.7&appType=4&tokenId=375676&babyId=44629&page_num=0&page_size=3&category=0&sign=NDFlNTM5MmVhNDI2YjI1ZTgxM2I3YjVkOTZkY2ExYjQ5N2Y3MmRlOA==	1,815		application/json				
57	200	HTTP	media.jiqid.com	/scanner_pen/cards/digit.jpg	149,731		image/jpeg				
58	200	HTTP	media.jiqid.com	/scanner_pen/cartoon_book/1.jpg	923,346		image/jpeg				
59	200	HTTP	media.jiqid.com	/scanner_pen/cartoon_book/2.jpg	1,075,908		image/jpeg				
60	 - 	HTTP	Tunnel to	clients1.google.com:443	-1			chrome:7652
