### ISSUE TITLE
Host.ui.openNewMorePage() undefined is not a function  on Android

### ISSUE THREAD

**Issue by UnaMattinaDev** [MiEcosystem/miot-plugin-sdk#119]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android 9.0
- 相关模块:Host

#### 现象

Android 调用Host.ui.openNewMorePage() 报undefined，iOS 端正常

**Comment by dingshaoran** [comment]
android 没有这个 api

**Comment by dingshaoran** [comment]
请使用以下三个 api 代替
openHelpPage
openFeedbackInput
openSecuritySetting
