### ISSUE TITLE
产品离线提示问题

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#1190]
---
**是否为新品（必填）**
新品

**关联的产品model**
jyaiot.cm.ccj01

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
产品离线提示 设置为否的情况下，IOS和Android系统手机上，依旧显示出离线提示

**期望（必填）**
产品离线提示 设置为否的情况下，IOS和Android系统手机上，不显示离线提示

**其他的上下文/日志/截图**
![1261562921195_ pic_hd](https://user-images.githubusercontent.com/8509320/61115267-aaf15a00-a4c4-11e9-97db-4a8344412f7b.jpg)
![1271562921288_ pic_hd](https://user-images.githubusercontent.com/8509320/61115362-e3913380-a4c4-11e9-8a30-da6f80f94a15.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@santcool   你了解扩展程序里面这个配置的作用吗？我了解的这个离线提示是在support平台进行配置的，如下图：
![image](https://user-images.githubusercontent.com/22487747/61192373-647b4580-a6e6-11e9-8b83-131f4e573744.png)

**Comment by maxuesong1990** [comment]
https://iot.mi.com/productDetail_new.html#/plugin/material?model=jyaiot.cm.ccj01
我在这个链接中，只能配置下图的设置
![image](https://user-images.githubusercontent.com/42369212/61192788-9fcb4380-a6e9-11e9-8081-4ac193d0cfae.png)
没有找到入口你前面回复的这个地方

**Comment by santcool** [comment]
这个是推送方面的设置，有些设备，离线了会给app发送推送。那个地方的离线，是没法去掉的。

**Comment by maxuesong1990** [comment]
你好，离线提示推送可以存在，但是要把IOS的蒙版去掉，跟安卓一样的方式即可

**Comment by maxuesong1990** [comment]
> 这个是推送方面的设置，有些设备，离线了会给app发送推送。那个地方的离线，是没法去掉的。

你好，离线提示推送可以存在，但是要把IOS的蒙版去掉，跟安卓一样的方式即可
