### ISSUE TITLE
getLinkedBTDevices()接口，iOS与Android获取的设备类型数不一致

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#1191]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

是否为新品（必填）
是

关联的产品model
yeelink.gateway.v1

项目ID（必填）
Mesh网关

企业名称（必填）
yeelight

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android iOS]
SDK分支: [10022]
相关模块:[Device -> getLinkedBTDevices]
现象（必填）
getLinkedBTDevices()接口，iOS与Android获取的设备类型不一致。如下图：
android:
<img width="1126" alt="屏幕快照 2019-07-12 下午4 43 27" src="https://user-images.githubusercontent.com/17311448/61115542-44207080-a4c5-11e9-8b05-1bdeec140a90.png">
ios:
<img width="985" alt="屏幕快照 2019-07-12 下午4 48 09" src="https://user-images.githubusercontent.com/17311448/61115591-61553f00-a4c5-11e9-903f-3ad9225fa5c6.png">

期望（必填）
两端获取相同的设备类型数

**Comment by zanetti4** [comment]
哪个系统获取的是正确的？

**Comment by RowingCaptainChen** [comment]
> 哪个系统获取的是正确的？

iOS是正确的

**Comment by lvjie0519** [comment]
@RowingCaptainChen  您好，需要您那边提供个账号，我这边进行测试，麻烦添加下微信（微信号：18750118631）详聊，谢谢。

**Comment by lvjie0519** [comment]
@RowingCaptainChen   问题已知，经排查属于APP问题，我这边反馈给APP组，有回复及时反馈，请耐心等待，谢谢。

**Comment by lvjie0519** [comment]
@RowingCaptainChen  
Android是通过这里 配置获取信息的，@santcool  可以和王冲沟通。
![image](https://user-images.githubusercontent.com/22487747/61694071-515e1a80-ad63-11e9-87f7-7ebc6b9174d7.png)

**Comment by santcool** [comment]
此问题系后台配置问题导致，经修改配置后，文案/功能等全部恢复正常，问题关闭。
