### ISSUE TITLE
米家卡片配置，首页宫格样式有问题

### ISSUE THREAD

**Issue by LZCaaT** [MiEcosystem/miot-plugin-sdk#1192]
**是否为新品（必填）**
 新品

**关联的产品model**
ydzl.waterpuri.t1

**项目ID（必填）**
无项目ID

**企业名称（必填）**
深圳优点智联科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android/iOS]
- SDK分支: [master/10021]
- 相关模块:[米家卡片配置]

**现象（必填）**
为什么会出现这种情况？有没有不简化名称的情况下，修改样式的方法？
![image](https://user-images.githubusercontent.com/28329423/61193436-f8044480-a6ed-11e9-8737-a1e561d7b54a.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LZCaaT** [comment]
文字叠在了图片上面

**Comment by LiuMengzhou** [comment]
@zanetti4 宫格卡片显示问题，请联系客户端开发。

**Comment by zanetti4** [comment]
好的，正在联系

**Comment by santcool** [comment]
跟我们这边同事讨论了，这个没有可支持的余地，你们可以考虑把这些内容放在卡片上，而不是放在宫格上。毕竟宫格能显示的内容就那么多，后面加省略号是没意义的。
