### ISSUE TITLE
智能场景设置成功不退出插件问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#1193]
公司名称（必填）
青岛亿联客信息技术有限公司

是否为新产品（必填）
否

产品名称/Model（必填）
米家LED吸顶灯/yeelink.light.ceiling5
米家床头灯/yeelink.light.bslamp1
米家床头灯2代/yeelink.light.bslamp2

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7.1.1]
SDK分支: [master/10022]
相关模块:[Device]
现象（必填）
智能场景（开启并延时关灯）设置成功后（设置Package.exitInfo=action）iOS可以正常退出，而安卓则不能。

以下是iOS的action

payload:
command: "yeelink.light.ceiling5.set_scene"
did: "116374657"
id: 3072
model: "yeelink.light.ceiling5"
plug_id: "GET_YEELINK_DELAY_SETTING"
scene_type: 2
value: (3) ["auto_delay_off", 6, 15]

以下是安卓的action

payload:
command: "yeelink.light.ceiling5.set_scene"
did: "116374657"
extra: null
id: 3072
model: "yeelink.light.ceiling5"
name: "开灯并延时关灯"
package_msgType: 3
plug_id: "GET_YEELINK_DELAY_SETTING"
scene_type: 2
tr_id: "201"
value: (3) ["auto_delay_off", 6, 15]

期望（必填）
安卓设置完智能场景后也能正常退出。

其他的上下文/日志/截图
无

尝试过的解决办法
看过之前的issue

**Comment by lvjie0519** [comment]
@TheWalkingDead1024  你调用的是哪个退出方法？   请使用  Package.exit(info) 这个方法。

**Comment by TheWalkingDead1024** [comment]
> @TheWalkingDead1024 你调用的是哪个退出方法？ 请使用 Package.exit(info) 这个方法。

感谢大佬
