### ISSUE TITLE
锁屏之后插件已经在后台被杀死，但是蓝牙连接未断开（Mi8测试）

### ISSUE THREAD

**Issue by badsdy** [MiEcosystem/miot-plugin-sdk#1194]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 如果有报错，一定要贴出报错的错误信息，否则米家无法排查
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？是
- SDK 是否更新到最新？是
- Check 文档了吗？是
- 是否尝试搜索issue？是
- 是否尝试搜索“常见问题” 是

---
**是否为新品（必填）**
在售

**关联的产品model**
miaomiaoce.sensor_ht.t1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
秒秒测

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0] android9
- SDK分支: [eg.master/10000/...] 10022
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
手机锁屏，过10分钟之后插件已被杀死，但是蓝牙链接并没有断开。改现象在Mi8上必现

**期望（必填）**
米家或RN锁屏的时候有回调函数给插件使用吗？

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
可以通过监听  PackageEvent.packageWillPause  或 PackageEvent.packageWillExit 事件来处理。

**Comment by cfJand** [comment]
建议使用：PackageEvent.packageWillExit 解决上述问题。
此issue 长时间未回复，先关闭。
