### ISSUE TITLE
Host.ui.openPrivacyLicense在Android端，点击取消没有回调

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1195]
是否为新品（必填）
在售

关联的产品model
miaomiaoce.sensor_ht.t1

项目ID（必填）
1115
企业名称（必填）
秒秒测

环境（必填）

电脑操作系统:[eg.Windows/Mac OS/Linux]
手机系统:[eg.Android 8.1/iOS 11.0] android9
SDK分支: [eg.master/10000/...] 10022
相关模块:[eg.Host/Service/Account]
现象（必填）
Host.ui.openPrivacyLicense在Android端，点击取消没有回调，点击同意，返回true

期望（必填）
点击取消的时候可以返回false

**Comment by fishle** [comment]
取消的回调的用处是什么？

**Comment by fishle** [comment]
iOS是有的吗？

**Comment by lvjie0519** [comment]
@Android-yzhang    Android点击取消 会自动退出插件吧，不会有返回。

**Comment by Android-yzhang** [comment]
原因是这样的，因为添加设备后，设备会是连接状态，这时进入插件点击取消，设备没有断连，如果没有返回的话，这块怎么处理？

**Comment by fishle** [comment]
在onHostDestroy里面断开连接是不是就可以了

**Comment by Android-yzhang** [comment]
这个onHostDestroy是Java层的，我们改不了吧

**Comment by fishle** [comment]
在js层处理一下“packageWillExit”这个事件
