### ISSUE TITLE
IBluetooth.getVersion()接口，iOS和Android的结果不一致

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#1196]
**是否为新品（必填）**
在售

**关联的产品model**
ninebot.scooter.v2

**项目ID（必填）**
名称叫：米家滑板车Pro

**企业名称（必填）**
纳恩博（北京）科技有限公司

**环境（必填）**
- 电脑操作系统: Mac
- 手机系统: Android 8.0 / iOS 12.0
- SDK分支: 10021
- 相关模块: IBluetooth

**现象（必填）**
IBluetooth.getVersion()接口，iOS和Android的结果不一致：
Android:      "1.0.1_�O�o"
iOS:      "1.1.0_0002"

**期望（必填）**
IBluetooth.getVersion()接口，iOS和Android的结果一致

**其他的上下文/日志/截图**
现象里的值就是debug日志中拿到的

**尝试过的解决办法**

**Comment by pencilCool** [comment]
iOS 上修改了接口，改成直接从蓝牙设备上读版本号。之前用的是从云端拉取的版本号。
在SDK_10024  上可验证

**Comment by lvjie0519** [comment]
@dan-huang  你们这设备使用的是小米蓝牙协议吧，找产品需要将   蓝牙设备是否使用安全芯片  配置为是
![image](https://user-images.githubusercontent.com/22487747/61515697-d1b80f00-aa35-11e9-80a9-7d39cb807303.png)

**Comment by dan-huang** [comment]
10024还有问题，但10023没问题，目前先用10023了。 协议上，connect传入的值是3，应该是普通蓝牙协议吧

@lvjie0519

**Comment by lvjie0519** [comment]
@dan-huang   参数都一样吗？  10024 对这个模块并没有做修改， 普通蓝牙协议， connect传入的值是3。

**Comment by dan-huang** [comment]
10024已修复
