### ISSUE TITLE
位置管理问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1197]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master.]
- 相关模块:[]

**现象（必填）**
ios：连接路由器为空。房间显示（null）|（null），点击进入管理房间，修改灯组所在房间显示成功，实际移动失败。在管理房间界面点击左上角返回键，弹窗提示是否保存本次修改。
android：修改灯组所在房间显示成功，返回米家主界面再进灯组插件，实际移动房间失败。

位置管理为必选项，无法勾选取消

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
灯组是不支持房间的，你们看看能不能不让进入管理房间？

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/61339031-84d60c00-a86e-11e9-92b1-b78b1eba5568.png)

**Comment by santcool** [comment]
好的，这个问题我来推一下

**Comment by santcool** [comment]
https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10023/projects/com.xiaomi.demo/Main/tutorial/Setting.js
这里面有一个字段：excludeRequiredOptions 
传入想隐藏的key即可。

**Comment by mirse** [comment]
> https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10023/projects/com.xiaomi.demo/Main/tutorial/Setting.js
> 这里面有一个字段：excludeRequiredOptions
> 传入想隐藏的key即可。

我使用了如下代码，并不能生效
excludeRequiredOptions: [secondAllOptions.SECURITY,firstAllOptions.LOCATION]

**Comment by mirse** [comment]
@santcool

**Comment by LiuMengzhou** [comment]
@mirse 你们在用哪个分支？

**Comment by mirse** [comment]
> @mirse 你们在用哪个分支？

master

**Comment by LiuMengzhou** [comment]
好。我修复一下。稍等

**Comment by LiuMengzhou** [comment]
cbc54648bd1a649773eea1505bc4c8e7cd8d16fc

**Comment by Aub1nLin** [comment]
> SDK_10023
用SDK_10023验证可用，谢谢，请问你们什么时候会更新到Master中？

**Comment by Aub1nLin** [comment]
@LiuMengzhou 请问你们什么时候会更新到Master中？现在所有的版本都用不了，只能debug的时候可以用。
