### ISSUE TITLE
安卓灯组管理

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1198]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [master]
- 相关模块:[]

**现象（必填）**
安卓灯组点击无响应。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by fishle** [comment]
是灯组设备点击没反应？录个视频看下

**Comment by mirse** [comment]
> 是灯组设备点击没反应？录个视频看下
如下图，点击后只有点击效果。
![image](https://user-images.githubusercontent.com/5188922/61268785-273eb280-a7cf-11e9-9c77-8747b4b850b8.png)

**Comment by fishle** [comment]
你这个用java写的插件吗？把设备分享到这个账号：894158105

**Comment by mirse** [comment]
关键是iOS可以用，没问题，就Android不能用。
现在的灯组不支持共享， 我调的是这个方法：

//获取虚拟设备组里的设备数组
Device.getVirtualDevices().then(json=>{

            let  didArray = [];

            for (let i = 0;i<json.length;i++){
                didArray.push(json[i].deviceID)
            }
        this.setState({didArray:didArray})
        })

//灯组管理接口
 Host.ui.openEditDeviceGroupPage(this.state.didArray);

**Comment by fishle** [comment]
你加下我的微信吧，fishle123

**Comment by fishle** [comment]
这边试了下，Android是可以正常打开的，如果还有问题，请提供测试账号

**Comment by mirse** [comment]
> 这边试了下，Android是可以正常打开的，如果还有问题，请提供测试账号

还是打不开，测试账号已邮件发送

**Comment by fishle** [comment]
登录你的测试账号，这边看到是正常的，试试最新的安装包

![image](https://user-images.githubusercontent.com/17643700/61675814-666b8700-ad2c-11e9-9945-aabb405417b0.png)

**Comment by mirse** [comment]
更新使用最新的测试apk还是不行
现象视频：
[灯组管理.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3419973/default.zip)

**Comment by fishle** [comment]
这个你们之前是怎么做的，这个是一直都有问题还是切RN之后才遇到的

**Comment by Aub1nLin** [comment]
> 这个你们之前是怎么做的，这个是一直都有问题还是切RN之后才遇到的

之前是Android和iOS分开。iOS一直可以用，都是RN。Android原来是Java，所以还是看你们那边这么做吧？
现在Android一直不能用，iOS可用。

**Comment by fishle** [comment]
已经定位到原因，新版本会修复；你可以试试这个包
https://pan.mioffice.cn:443/#/link/839B02DFE95C0C4DAE13D6974BEB3F3C

**Comment by Aub1nLin** [comment]
> 已经定位到原因，新版本会修复；你可以试试这个包
> https://pan.mioffice.cn:443/#/link/839B02DFE95C0C4DAE13D6974BEB3F3C

我们下载安装后试了下，可以点击，但点击进入的也是是创建灯组，不是编辑灯组。

然后，我看了下上面你的回复。。。。emmm。。。你那张图也是创建灯组，不是编辑。

**Comment by fishle** [comment]
你们之前用java写的时候，是跳转到那个页面的？可能是编辑页这里有问题吧

**Comment by Aub1nLin** [comment]
Java调用的是这个方法，是跳转到编辑灯组的，不是创建。


XmPluginHostApi.instance().addRecord(pluginPackage(), ConstantUtils.RECORD_GROUP, ConstantUtils.RECORD_GROUP_VALUE, null);
                        Intent intent = new Intent();
                        intent.setClassName(activity(), "com.xiaomi.smarthome.device.ModifyGroupActivity");
                        intent.putExtra("group_model", "philips.light.virtual");
                        intent.putExtra("masterDid", mBulbDevice.getDid());
                        startActivity(intent);

**Comment by fishle** [comment]
这个可以了
https://pan.mioffice.cn:443/#/link/784B318980D65496EBC73943B97F8412

**Comment by Aub1nLin** [comment]
> 这个可以了
> https://pan.mioffice.cn:443/#/link/784B318980D65496EBC73943B97F8412

测试后可用，符合需求。你们什么时候会发布，我跟我们测试吱一声。。。。

**Comment by fishle** [comment]
八月初

**Comment by mirse** [comment]
> 八月初

IOS手机进入灯组管理选中其中一个或多个单灯取消或添加，退出灯组管理后再进入灯组管理，灯组管理单灯勾选状态显示没改变（取消的单灯勾选状态还在，添加的单灯显示没有勾选）

**Comment by fishle** [comment]
Android这里正常吗

**Comment by mirse** [comment]
> Android这里正常吗

android 是正常的

**Comment by fishle** [comment]
你给iOS提个issue吧
