### ISSUE TITLE
创建灯组成功跳转现象不同

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1199]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android / Ios]
- SDK分支: [master]
- 相关模块:[]

**现象（必填）**
创建灯组成功后，跳转现象不同
Android:点击完成返回设置界面，提示'创建分组成功'。
Ios:点击完直接跳转到灯组插件

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
期望：必填。
这个位子你们是需要我们的产品来统一吗？

**Comment by mirse** [comment]
> 期望：必填。
> 这个位子你们是需要我们的产品来统一吗？

对的，ios跟android的跳转现象应该一致吧

**Comment by santcool** [comment]
这个位子，因为Android RN插件多开有问题，所以没法和iOS统一，但是明显iOS这边合理一些。所以暂时保持原样吧，等Android支持插件多开了，再来统一。
