### ISSUE TITLE
米家搜索栏

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1200]
**是否为新品（必填）**
 在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
贵司的名称

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
米家App添加设备，搜索栏找不到飞利浦智睿系列灯组

![image](https://user-images.githubusercontent.com/5188922/61206824-184ff580-a726-11e9-95de-1b4178d48614.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
安卓和 ios 都有这个问题吗？

**Comment by mirse** [comment]
> 安卓和 ios 都有这个问题吗？

是的

**Comment by pencilCool** [comment]
没有搜索到这个model ，请确认model 的名字和上线的服务器

**Comment by mirse** [comment]
> 没有搜索到这个model ，请确认model 的名字和上线的服务器

model名：philips.light.virtual
上线服务器：大陆
帮忙再确认一下

**Comment by pencilCool** [comment]
你们的快联状态没上线。请联系帮你们配置设备状态的同事

**Comment by pencilCool** [comment]
![image](https://user-images.githubusercontent.com/8254543/62202104-3fabf100-b3bb-11e9-94e3-f03b44ca9919.png)

**Comment by mirse** [comment]
配置的同事说灯组本来就没有快连状态。 @pencilCool
