### ISSUE TITLE
【仅iOS，紧急】蓝牙断开后，Bluethooth的isConnected()接口，返回结果不对

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#1201]
**是否为新品（必填）**
 在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12]
- SDK分支: [SDK_10023]
- 相关模块:[miot/Bluetooth]

**现象（必填）**
只有iOS平台会，Android平台不会。
蓝牙断开，在收到bluetoothConnectionStatusChanged的结果isConnected=false后，调用Bluethooth的isConnected()接口，返回为true。

**期望（必填）**
蓝牙断开后，Bluethooth的isConnected()返回false

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
`ble.isConnected`
你是按照属性的方式获取的结果吗？

**Comment by WeizhiKong** [comment]
@zanetti4 收到bluetoothConnectionStatusChanged的结果isConnected=false后，我会去进行蓝牙连接，
在蓝牙连接前有个蓝牙是否连接的判断：
先用Bluethooth的createBluetoothLE(macOrPeripheralID)接口创建一个ble设备，然后再调用Bluethooth的isConnected()接口进行判断，发现返回为true

**Comment by pencilCool** [comment]
macOrPeripheralID  这个参数要用设备的uuid ，而不是service  的uuid
