### ISSUE TITLE
获取蓝牙版本时，iOS下偶发的出现获取的版本号是最新的，可以确定固件版本不是最新的

### ISSUE THREAD

**Issue by codebeautiful** [MiEcosystem/miot-plugin-sdk#1202]
---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
lcrmcr.safe.ms30b

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
宁波小匠物联网

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg./iOS 11.0]
- SDK分支: [eg.master.]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
遇到一个很奇怪的现象，在插件首页时，拿到的蓝牙固件版本是33的，在更新页面调同样的方法拿到的就是35，而且只有在iOS下才存在，Android下是正常的

该现象在iOS版米家App4.19.1上必现，在4.19.2上没有出现

#1002 之前Android先遇到这个问题，后来好像在云端配了些什么东西就好了

**期望（必填）**
在不同的界面调用相同的方法表现一致

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by pencilCool** [comment]
请问题是否修复？ 找帮你们配置云端信息的同事对一下？

**Comment by pencilCool** [comment]
版本号的获取iOS 这边有一些改动。之前是通过云端获取的。后来改成了通过蓝牙直接读取的固件版本号。

**Comment by pencilCool** [comment]
js sdk_10024 之后的版本应该修复了这个问题。

**Comment by pencilCool** [comment]
js sdk_10024 之后的版本应该修复了这个问题。
