### ISSUE TITLE
关于获取米家APP版本号问题

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#1203]
文档显示调用Host.version可以获取到米家APP当前版本号，IOS端可以成功，但在Android端获取到的是手机系统的版本号。Android使用测试版本APP，版本号为5.5.37.5

**Comment by zanetti4** [comment]
请按照模版提问，谢谢

**Comment by zanetti4** [comment]
@lvjie0519 我用安卓手机测试，米家5.5.37.6测试版，Host.version 获取到的是7.0，请你查看。

**Comment by fishle** [comment]
去下载最新的版本，5.5.43, 这个可以拿到
