### ISSUE TITLE
插件法律信息弹窗

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1204]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.hbulb

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [master]
- 相关模块:[]

**现象（必填）**

安卓米家5.5.37法律信息弹窗显示为：我已阅读User Agreement和Privacy Policy。
安卓米家5.5.37.5测试版法律信息弹窗显示为：我已阅读用户协议和隐私政策。

![image](https://user-images.githubusercontent.com/5188922/61269489-60782200-a7d1-11e9-8e2b-4c651b8de500.png)

![image](https://user-images.githubusercontent.com/5188922/61269530-856c9500-a7d1-11e9-96b5-96765f3a8177.png)

![image](https://user-images.githubusercontent.com/5188922/61269626-c795d680-a7d1-11e9-83a3-6100e0c33590.png)

**期望（必填）**
应该显示英文字段，我的多语言里并没有放中文字段

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我用安卓7.0测试，米家 app 5.5.37.6 测试版
`Host.ui.openPrivacyLicense('User Agreement', licenseURL, 'Privacy Policy', policyURL)`
当我把语言设置为英语时，弹窗里可以显示**User Agreement和Privacy Policy**

**Comment by mirse** [comment]
> 我用安卓7.0测试，米家 app 5.5.37.6 测试版
> `Host.ui.openPrivacyLicense('User Agreement', licenseURL, 'Privacy Policy', policyURL)`
> 当我把语言设置为英语时，弹窗里可以显示**User Agreement和Privacy Policy**

我的默认语言是英语，在设置里直接使用默认即可，但是弹窗显示的是中文

**Comment by fishle** [comment]
如果想显示自定义的title，需要传递有效的licenseUrl和policyUrl

**Comment by mirse** [comment]
> 如果想显示自定义的title，需要传递有效的policyUrl

我传入的policyUrl生效了，但是自定义title在测试版上就是不生效

**Comment by fishle** [comment]
发下你调用的详细参数，以及相应的效果截图

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/61339715-9b319700-a871-11e9-83a5-a0528f93e8af.png)

![image](https://user-images.githubusercontent.com/5188922/61339788-fc596a80-a871-11e9-8f61-90f7ae325de4.png)

具体效果如一楼截图

**Comment by fishle** [comment]
有看过iOS的表现吗，Android已经不支持自定义title了

**Comment by lvjie0519** [comment]
@mirse   
1、法律信息及隐私政策模块最近有改版， Android ios都不支持自定义title了，建议使用新的api
Host.ui.alertLegalInformationAuthorization
Host.ui.previewLegalInformationAuthorization
具体参数参考api注释或xiaomi.demo的privacy.js代码；sdk选择10023分支。
2、关于语言包问题，应该是支持多语言的，使用最新apk进行测试，谢谢。

**Comment by mirse** [comment]
> privacy

有具体文档说明吗，比如options的意义。

**Comment by lvjie0519** [comment]
@mirse   可以先看api的代码注释，文档更新稍微滞后。
