### ISSUE TITLE
在米家中设备列表中找不到我们的产品

### ISSUE THREAD

**Issue by jacob929** [MiEcosystem/miot-plugin-sdk#1205]
**是否为新品（必填）**
 新品 

**关联的产品model**
duoqin.safe.pbfv01

**项目ID（必填）**

**企业名称（必填）**
深圳市多亲科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0] 

**现象（必填）**
在米家中添加设备时找不到我们设定的产品

**期望（必填）**
怎么解决，否则我们调试环境还搭建不起来

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
按照文档上的要求试了好几遍，还是不行，使用的开发者账号是173930516，请问我们配置那里配错了？

**Comment by santcool** [comment]
操作好了。15分钟左右生效，记得清除缓存。
