### ISSUE TITLE
iOS Alert弹框锁屏再亮屏后消失

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#1206]
- IPA/APK 是否更新到最新？ 是
- SDK 是否更新到最新？ 是
- Check 文档了吗？是
- 是否尝试搜索issue？是
- 是否尝试搜索“常见问题” 是

---
**是否为新品（必填）**   
   新品&在售

**关联的产品model**
   loock.lock.v6 、loock.cateye.v01  等都存在
**项目ID（必填）**
  1257
**企业名称（必填）**
云丁网络（北京）有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.2]
- SDK分支: [10021]
**现象（必填）**

   iOS版米家插件
   RN开发（AlertIOS）和原生开发的 Alert弹框 都存在弹框后锁定屏幕后然后打开屏幕，之前显示的弹框消失；因为弹框为让用户强制更新固件，所以导致用户可以通过这种方式跳过强制更新，所以希望尽快给解答一下

**期望（必填）**
  iOS 锁屏再亮屏 Alert弹框不消失

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@santcool 我用 ios 手机测试 AlertIOS，确实存在这个问题，请你查看。

**Comment by santcool** [comment]
此处为app端的一个需求，暂时不可改动。
在需要强制弹框的页面，增加如下方法，即可解决。退出后台，回到前台做部分处理即可解决这种问题。
componentDidMount() {
PackageEvent.packageWillPause.addListener(()=>{
      this.setState({showAlert:true})
})
PackageEvent.packageDidResume.addListener(() => {
     if(this.state.showAlert)  showAlert();
});

}
