### ISSUE TITLE
关于android米家开发者设置使用反馈

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#1207]
下面描述的情况都是在米家开发者设置里面。
工具应该是帮助提升效率的，但是目前使用下来觉得手好累。
当前米家版本5.5.30.6测试版

**现象（必填）**
1.android中相同model不同包名都可以同时选中，但是只有最新添加的有用（注意是添加新选项），取消最新添加的，选择开始添加的，不能调试，这样选中功能就没什么作用了。
2.不支持点击进入编辑。
3.关闭开发者模式后重新打开，所有选项全被选中。

**期望（必填）**
开发插件过程中经常需要切换到demo包，ios使用逻辑很正常，期望修改上述反馈。

**Comment by lvjie0519** [comment]
问题1：相同model不同包名都可以同时选中，同时选中只会选择第一个model的选项，列表支持左滑删除；
问题2： 不支持点击进入编辑， 编辑和新增工作量上没什么很大区别，目前支持item删除和新增两项操作；
问题3：关闭开发者模式到打开开发者模式，列表选项之前是什么状态，之后也是什么状态，不应该存在之前是未选中状态，关闭再打开后，变为选中状态。
最后说明一点，代码都是通过model来检索的，会从列表的第一项开始检索，匹配到了model，不会再继续匹配下去，所以您的这种一个model对应多个插件，建议通过新增或删除的方式解决。
请使用最新apk测试，谢谢。

**Comment by evansherry** [comment]
@lvjie0519 
正确的逻辑应该是model为key，选中新的会取消其它选中。目前的情况是我觉得通过model来检索，应该判断列表的一个被选中状态来匹配。
举个例子model1分别对应了两个包名p1,p2, 最新添加的是p2,现有的逻辑是只有选中p2才能进入p2包调试模式，选中p1不能进入调试模式，只能删除p1重新添加p1。在开发过程中经常出现就是会使用p1的包环境，所以个人觉得通过删除再重新添加得重新输一遍model和包名，偶感手累，这样历史列表也没起到应有的作用。
旨在能让android开发者快乐的调试。

**Comment by evansherry** [comment]
@lvjie0519 关于问题3好像不是我反馈的会全选，是比较混乱的，我也不知道具体结果，你可以试一下改变选中的个数，然后关掉开发者选项，再打开看一下，如果没有出现可以多尝试几次

**Comment by lvjie0519** [comment]
@evansherry   问题3的情况， 我这边一直无法复现，如果你那边复现可以拍个视频，压缩下上传到这里，我这边看看，谢谢。

**Comment by evansherry** [comment]
@lvjie0519 已经私聊发你微信了，反馈的问题1希望修改一下，使用起来确实不方便，谢谢

**Comment by lvjie0519** [comment]
@evansherry   已经修复，使用选中项及model来判断，使用列表中第一个选中项作为插件调试。
