### ISSUE TITLE
Device.getDeviceWifi().checkFirmwareUpdateAndAlert(); Error Code=401 checkFirmwareUpdate pemission deny

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1208]
**是否为新品（必填）**
新品 & 在售

**关联的产品model**
yeelink.light.lamp9 

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
follow API 调用接口
       //首先屏蔽默认弹窗
        Package.disableAutoCheckUpgrade = true;
        //....
        //在合适的时间触发
        Device.getDeviceWifi().checkFirmwareUpdateAndAlert();
Android和IOS报错(网太慢了图片传不上来，已在开发群描述过哈)：
code: 401, message：checkFirmwareUpdate pemission deny...
**期望（必填）**
希望能正常工作，实现检查固件升级自动弹框的提示功能

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
切换多个设备，在Android和IOS中同步测试观察

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@santcool 我用 ios 手机测试，也是同样的错误，请你查看。

**Comment by santcool** [comment]
问题已修复，在SDK_10023上，可以下载最新的调试app，切换到SDK_10023上测试。10023将于后天发布，将于7月25左右正式上线。
