### ISSUE TITLE
ListItemWithSwitch存在问题

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1209]
**是否为新品（必填）**
在售

**关联的产品model**
miaomiaoce.sensor_ht.t1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
秒秒测

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10022/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
ListItemWithSwitch设置titlestyle无效，看了一下源码，有定义但是未引用。
Android会显示不全

**期望（必填）**
可以定义style或者像普通ListItem设置Android默认字体

**Comment by zanetti4** [comment]
@LiuMengzhou 我用安卓手机测试，titleStyle 确实无效，请你查看。

**Comment by zanetti4** [comment]
@Android-yzhang 

> Android会显示不全

这是指哪里？

**Comment by Android-yzhang** [comment]
如果不设置英文字体，那么外文字符串将显示不全（Android）
    let fontFamily = {};
    if (Platform.OS === 'android') {
      fontFamily = { fontFamily: 'Kmedium' }
      valueStyle.height = THIN_HEIGHT;
    }

这个是你们在ListItem里写的[偷笑]

**Comment by LiuMengzhou** [comment]
已修复，SDK_10023最新代码。
