### ISSUE TITLE
characteristic不能正常使用

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#121]
before issue：（不用回答）
### 是否尝试搜索issue？是，有相关issue，但用法不一样

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]  iOS 12.0.1
- 相关模块:[eg.Host/Service/Account] Device

#### 现象

发现characteristic后，characteristic的isDiscovered为undefined，在使用characteristic时(如：setNotify(true))，会报characteristic or service not found，具体见截图
![1544181037538](https://user-images.githubusercontent.com/12531667/49644741-4c5a8e00-fa54-11e8-8c89-ae7814abfabc.jpg)

#### 期望

期望可以正常使用

#### 其他的上下文/日志/截图

在基于已经连接上设备的情况下，使用代码如下：
![1544181105303](https://user-images.githubusercontent.com/12531667/49644775-7ad86900-fa54-11e8-8259-d5d4010a75a2.jpg)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by edwardair** [comment]
bluetooth.startDiscoverServices之后，应该是不能直接“同步”执行 getService、getCharacteristic的，得在监听回调中使用吧，DEMO的这些get****前提肯定是基于已经  discover****** 并且正确回调过的

**Comment by dzonel** [comment]
@edwardair 同步执行，service、characteristic都能获取到，service可以用，characteristic拿到了，但是不清楚为什么characteristic 的isDiscovered为undefined。我再试下异步的。

**Comment by dzonel** [comment]
您好，每次更新sdk是否可以出一份更新文档，说明一下哪里有变更，如Device.bluetooth变为Device.getBluetoothLE()，不然只能等用的时候报错了才发现。

**Comment by laohuang88** [comment]
新增了beta版本接口变迁日志，请及时查看

**Comment by dzonel** [comment]
@laohuang88 感谢🙏。
