### ISSUE TITLE
MHDatePicker可见的情况下，按返回键不消失

### ISSUE THREAD

**Issue by flztsxsy** [MiEcosystem/miot-plugin-sdk#1210]
**是否为新品（必填）**
新品

**关联的产品model**
无

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
秒秒测科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- SDK分支: 10022
- 相关模块:Host/ui

**现象（必填）**
1、MHDatePicker可见的情况下，按返回键MHDatePicker不消失，并且返回键功能被“阻塞”住。
2、另外MHDatePicker 时间选择器，在滑动的时候，右上角的单位 “时”和“分”会有一次向左移动位置

**期望（必填）**
1、MHDatePicker可见的情况下，按返回键MHDatePicker可以消失，返回键功能不被“阻塞”住。
2、MHDatePicker 时间选择器，在滑动的时候，右上角的单位不发生偏移

**尝试过的解决办法**
对于返回键，尝试用BackHandler.addEventListener('hardwareBackPress', this.onBackAndroid);期望可以在
onBackAndroid中处理，改变MHDatePicker的visible状态，不过没有任何效果，在onBackAndroid的第一行加log没有任何输出，说明根本没有执行到。

**Comment by LiuMengzhou** [comment]
https://www.jianshu.com/p/d1c26d4c646e

你参考这个试试呢

**Comment by LiuMengzhou** [comment]
不对，应该是我来改。返回键隐藏modal的问题已经修改好了。SDK_10023最新代码。
第二个问题你再具体描述一下。

**Comment by flztsxsy** [comment]
![image](https://user-images.githubusercontent.com/49407658/61345521-1aca6080-a888-11e9-9740-f7616d61f18c.png)
就是这个右上角的单位，在滑动选择时间的时候，会发生偏移

**Comment by LiuMengzhou** [comment]
iOS Android都有此问题吗？

**Comment by flztsxsy** [comment]
我目前只测试了Android，ios的我还没有测试。

**Comment by LiuMengzhou** [comment]
> 我目前只测试了Android，ios的我还没有测试。
> 2、另外MHDatePicker 时间选择器，在滑动的时候，右上角的单位 “时”和“分”会有一次向左移动位置

@lvjie0519

**Comment by flztsxsy** [comment]
你好，ios的我测试了一下，没有问题，只有Android存在该问题

**Comment by lvjie0519** [comment]
@flztsxsy  已修复，请使用最新apk进行测试，谢谢。

**Comment by flztsxsy** [comment]
您好，下载了最新的apk，经测试已经修复，谢谢
