### ISSUE TITLE
调用ui/openBtGatewayPage页面，iOS与Android页面文案、样式不一致。

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#1211]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

**是否为新品（必填）**
新品

**关联的产品model**
yeelink.gateway.v1

**项目ID（必填）**
mesh网关

**企业名称（必填）**
青岛亿联客

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android iOS]
- SDK分支: [10022]
- 相关模块:[ui/openBtGatewayPage]

**现象（必填）**
打开mesh网关-->点击‘查看连接设备’-->连接设备页面 iOS与安卓样式不一致。

**期望（必填）**
 iOS与安卓样式一致，统一改成安卓的样式。
android:
![WechatIMG35](https://user-images.githubusercontent.com/17311448/61342813-257ff800-a87e-11e9-954b-1eb376bd24c4.jpeg)
ios:
![WechatIMG43](https://user-images.githubusercontent.com/17311448/61342822-29ac1580-a87e-11e9-8ff9-b06071ac7c33.jpeg)

**Comment by santcool** [comment]
经我方产品确认，此处要求android修改，与iOS保持一致。

**Comment by lvjie0519** [comment]
@RowingCaptainChen   Android这里的文字会根据 列表内容不同而不同，经APP组回复，已经修改为一致，
先跟踪 https://github.com/MiEcosystem/miot-plugin-sdk/issues/1191  ,  这里暂时先关闭。
