### ISSUE TITLE
React-Native-Blur使用问题

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1213]
**是否为新品（必填）**
新品

**企业名称（必填）**
飞彗

**现象（必填）**
说是1022分支以后都内置了React-Native-Blur高斯模糊库,`为什么我在1022分支使用BlurView报Invariant Violation:Native component for ‘blurview’ does not exist
错误？`

**期望（必填）**
正常使用

**Comment by zanetti4** [comment]
#1048

**Comment by zanetti4** [comment]
已经内置了，在 package.json 里有 `"@react-native-community/blur": "^3.3.1"`
你 `npm i` 了吗？
