### ISSUE TITLE
紧急，android 5.5.41 正式版，用户协议不显示，测试版正常，iOS版也正常

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1215]
**是否为新品（必填）**
在售

**关联的产品model**
miaomiaoce.sensor_ht.t1

**项目ID（必填）**
1115

**企业名称（必填）**
秒秒测

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10022/...]
- 相关模块:[eg.Host]

**现象（必填）**
android 5.5.41 正式版，Host.ui.openPrivacyLicense 用户协议不显示，测试版正常，iOS版也正常

**期望（必填）**
可以显示用户协议

**Comment by zanetti4** [comment]
用户协议不显示时，是否有报错？页面呈现什么样子？

**Comment by Android-yzhang** [comment]
![26311563335141_ pic_hd](https://user-images.githubusercontent.com/28639410/61356077-2a59a180-a8a8-11e9-91a1-8307836f7bb4.jpg)

**Comment by Android-yzhang** [comment]
今天刚刚应用商店更新的，不知道是什么问题，在之前的测试版，是可以正常显示的

**Comment by lvjie0519** [comment]
@Android-yzhang    请给出您的关键代码

**Comment by Android-yzhang** [comment]
if (Host.locale.language == 'zh') {
            var licenseURL = require("../resources/license_zh.html");
            var policyURL = require("../resources/policy_zh.html");
          } else {
            var licenseURL = require("../resources/license_en.html");
            var policyURL = require("../resources/policy_en.html");
          }
          Host.ui.openPrivacyLicense(strings.device_more_activity_license, licenseURL, strings.device_more_activity_privacy, policyURL)
          .then(val => {...

**Comment by Android-yzhang** [comment]
现在fir上的版本，版本号比小米应用商店上下载的正式版要低，fir上的版本测试没有问题

**Comment by lvjie0519** [comment]
@Android-yzhang   请把设备分享到 894158105，同时说下设备名称， 我这边测试下试试

**Comment by Android-yzhang** [comment]
@lvjie0519 设备共享了，叫米家电子温湿度计Pro

**Comment by lvjie0519** [comment]
@Android-yzhang   想起来，分享的设备进入插件是不会有弹窗的， 添加下微信（微信号：18750118631）详聊下。

**Comment by gaopingfly** [comment]
@lvjie0519 
请问这个有什么结论吗？
我今天也发现这个问题了。

我用的sdk基线是 10022
用的米家版本是 5.5.42.2测试版本

**Comment by lvjie0519** [comment]
@Android-yzhang    最新apk已经修复了，  请使用fir上最新apk或线上apk测试，都可以。
