### ISSUE TITLE
首页宫格处，文字显示不完整

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1216]
是否为新品（必填）
新品，米系产品

关联的产品model
viomi.dishwasher.m01

项目ID（必填）
项目ID：P18-0300

企业名称（必填）
佛山云米电器科技有限公司

环境（必填）

电脑操作系统:Windows
手机系统:Android 8.1/iOS 11.0
SDK分支: [eg.master/10021/...]
相关模块:[eg.Host/Service/Account]
现象（必填）
首页宫格处，文案未显示完整。。文案示例如图：Completed、Sanitizing
![image](https://user-images.githubusercontent.com/11864517/61356260-8cb2a200-a8a8-11e9-8d3f-631ae8fbc7ec.png)

期望（必填）
文案能显示完整

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好

**Comment by zanetti4** [comment]
Duplicate of #1192

**Comment by LiuMengzhou** [comment]
@zanetti4 首页宫格不是插件框架的UI组件。。。

**Comment by LiuMengzhou** [comment]
@jimu380261652 
![image](https://user-images.githubusercontent.com/13726966/61458704-b6012a00-a99d-11e9-9b98-e6646c30c736.png)
这个地方也是需要好好填写的。。。到底是安卓的卡片有问题还是iOS，或者both？

**Comment by santcool** [comment]
麻烦提供一个有此设备且存在问题的测试账号，发送到zhangwenfeng@xiaomi.com。 我们查查看

**Comment by jimu380261652** [comment]
已邮件发送

**Comment by santcool** [comment]
经测试，问题在Android这边，请 @lvjie0519 查看

**Comment by lvjie0519** [comment]
@jimu380261652   属于APP问题，我这边知照APP相关开发人员进行修复，修复及时反馈。

**Comment by lvjie0519** [comment]
@jimu380261652   APP反馈， 这种巨无霸字体，暂时不好支持，建议你那边将字体缩小，谢谢。
