### ISSUE TITLE
米家APP智能TAB和插件智能场景入口的if条件不一致

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1217]
是否为新品（必填）
新品，米系新品

关联的产品model
viomi.dishwasher.m01

项目ID（必填）
项目ID：P18-0300

企业名称（必填）
佛山云米电器科技有限公司

环境（必填）
电脑操作系统:Windows
手机系统:Android 8.1/iOS 11.0
SDK分支: [eg.master/10021/...]
相关模块:[eg.Host/Service/Account]

**现象（必填）**
通过米家APP首页的TAB页智能一项中点击右上角的添加和进入插件设置页里智能场景入口右上角添加if条件。。会发现条件数量不一致（Tab入口有3个，智能场景入口只有2个），截图如下
![image](https://user-images.githubusercontent.com/11864517/61359446-e5853900-a8ae-11e9-8612-878d0ec9d7cd.png)
![image](https://user-images.githubusercontent.com/11864517/61359457-ea49ed00-a8ae-11e9-946a-06c62ce120dd.png)

**期望（必填）**
两个入口的条件应一致。。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**Comment by zanetti4** [comment]
我安卓手机在10021测试，Tab入口的界面和你的一样，智能场景入口的界面和你的不一样。
![image](https://user-images.githubusercontent.com/12883959/61367967-66e4c780-a8bf-11e9-8944-a64cf96787c2.png)

**Comment by santcool** [comment]
外面多加了一个手动执行，设备里面是只允许创建自动触发的。在里面添加的手动执行会没有入口，此为当时的产品逻辑。

**Comment by jimu380261652** [comment]
![image](https://user-images.githubusercontent.com/11864517/61443834-d8cf1680-a97c-11e9-91c8-5caa9ecce6fc.png)
米家app上日志上提示说条件有增加到10个。。实际未见到有10个，麻烦这个也核查下，谢谢
