### ISSUE TITLE
自定义通用设置，检测版本升级问题

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1218]
---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
jiqid.mistory.ipen1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
南京机器岛科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/iOS 12.0
- SDK分支: 10022
- 相关模块:Host/Service/Account

**现象（必填）**
自定义设置，如何检测版本升级

**期望（必填）**
自定义设置，如何检测版本升级

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
com.xiaomi.demo/Main/tutorial/Setting.js
你可以看一下这个演示文件，其中就有固件升级。是否对你有帮助？

**Comment by Aphrodite123** [comment]
> com.xiaomi.demo/Main/tutorial/Setting.js
> 你可以看一下这个演示文件，其中就有固件升级。是否对你有帮助？

这个文件我看了，界面上的实现用次方法可以实现，但目前还有个疑问，因为我是自定义检测固件升级，所以小红点的显示/隐藏需要自己控制，那么如何才能获取到该设备是否有最新固件需要更新呢？有没有接口可以调
