### ISSUE TITLE
Device.requestAuthorizedDeviceListData() 调用返回 could not find any authordized model

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#1219]
**是否为新品（必填）**
否

**关联的产品名称（必填）**
Aqara 多功能网关

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10023
- 相关模块:Device

**现象（必填）**
Device.requestAuthorizedDeviceListData(model) 调用返回 could not find any authordized model (尝试过很多 model 结果都是一样)

**期望（必填）**
Device.requestAuthorizedDeviceListData() 调用返回正确数据

**其他的上下文/日志/截图**
![WechatIMG67](https://user-images.githubusercontent.com/8938524/61358949-ff724c00-a8ad-11e9-87a9-f77390f63a68.png)

**Comment by zanetti4** [comment]
@santcool 用 ios 手机测试 DeviceControl.js 指定model设备列表，也是同样的问题，请你查看。
