### ISSUE TITLE
Device.getBluetoothLE().connect()问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#122]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Bluetooth

#### 现象

第一次执行
 ```
ble.connect(3).then((response) => {
        console.log("蓝牙连接成功");
        ble.startDiscoverServices(ServiceUUID);
      }).catch((error) => {
      });
```
能连接成功蓝牙，也能搜索到服务ServiceUUID，进行数据读写操作，完成后断开蓝牙。
不退出插件。
再进行蓝牙操作，执行上方代码，能连接蓝牙成功，但是搜索不到服务ServiceUUID，一直没有通知过来，只要没有退出插件，第三次、第四次、第五次都不行了。
但是第二次执行ble.connect(3)的时候有下方通知返回
<img width="997" alt="image" src="https://user-images.githubusercontent.com/7885251/49646283-9d20b580-fa59-11e8-8212-df46152db584.png">

第一次没有：
<img width="909" alt="image" src="https://user-images.githubusercontent.com/7885251/49646341-b7f32a00-fa59-11e8-8e60-2889150037b5.png">

#### 期望

每次 ble.startDiscoverServices(ServiceUUID);都能正常通知我找到服务

**Comment by Copypeng** [comment]
应该是 js miot-sdk  缓存了，认为你之前发现过 Services ，就不再调用系统的发现接口。我协调一下看能不能去掉。
