### ISSUE TITLE
智能场景-设置生效时间段为全天，每天重复，过一天后，所有创建的智能都不见了

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1221]
是否为新品（必填）
新品，米系新品

关联的产品model
viomi.dishwasher.m01

项目ID（必填）
项目ID：P18-0300

企业名称（必填）
佛山云米电器科技有限公司

环境（必填）
电脑操作系统:Windows
手机系统:Android 8.1/iOS 11.0
SDK分支: [eg.master/10021/...]
相关模块:[eg.Host/Service/Account]

现象（必填）
云米测试发现的问题：智能场景-设置生效时间段为全天，每天重复，过一天后，所有创建的智能都不见了

**Comment by santcool** [comment]
我抓包，传的参数如下，执行多次后一直还在。
{"identify":"","authed":["118648552","259160459"],"us_id":"1088572807","st_id":"15","sr_id":"0","accessKey":"IOS00026747c5acafc2","setting":{"enable":true,"enable_push":false,"action_list":[{"tr_id":201,"model":"chuangmi.plug.m3","payload":{"command":"chuangmi.plug.m3.set_power","did":"118648552","value":"on"},"sa_id":"1149","type":0,"keyName":"开","name":"吕杰-插座"}],"launch":{"express":1,"attr":[{"device_name":"空气净化器","did":"259160459","extra":"[(null)]","src":"device","tr_id":101,"sc_id":"812","key":"prop.zhimi.airpurifier.v6.power","value":"on","default_value":0,"name":"开机","device_abbr":"空气净化器"}]}},"name":"武汉(勿删)灯开－吕杰插座-1开"}

如果你们还有问题，请提供scene/editv2接口的抓包信息。
