### ISSUE TITLE
智能场景，点击右上角查看日志，日志显示几秒后消失

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1223]
是否为新品（必填）
新品，米系新品

关联的产品model
viomi.dishwasher.m01

项目ID（必填）
项目ID：P18-0300

企业名称（必填）
佛山云米电器科技有限公司

环境（必填）
电脑操作系统:Windows
手机系统:Android 8.1/iOS 11.0
SDK分支: [eg.master/10021/...]
相关模块:[eg.Host/Service/Account]

现象（必填）
【米家IOS端】智能场景，点击右上角查看日志，日志显示几秒后消失，如下gif所示
![下载](https://user-images.githubusercontent.com/11864517/61366963-3e5bce00-a8bd-11e9-93e6-e8e38b214bd3.gif)

**Comment by zanetti4** [comment]
我用 ios 12.3.1 测试，没有发现这个问题。你测一下试试

**Comment by santcool** [comment]
@jimu380261652 我发现了，首次进入有这个问题，展示了一小会儿缓存，请求成功后，第二次，第三次进入就没这个问题了，感觉影响不大，后续我问问PM有没有必要优化吧。
