### ISSUE TITLE
read报错Error Domain=CBATTErrorDomain Code=2 "Reading is not permitted."

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#1224]
---
**是否为新品（必填）**
r 在售

**关联的产品model**
17216.magic_touch.d150

**项目ID（必填）**
乐范魔力贴温情版

**企业名称（必填）**
乐范健康有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- SDK分支: 10021
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
在使用read()方法的时候报错！报Reading is not permitted.
我的模组不是小米的模组，是自家的，不过上个项目这个模组不会出现该错误，这个项目中却报出这个错误

**期望（必填）**
read()方法使用成功。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43639032/61426495-292e8000-a94d-11e9-9738-25dd39ed65a5.png)
![image](https://user-images.githubusercontent.com/43639032/61426501-2d5a9d80-a94d-11e9-9b3e-58f7bcfd21d6.png)

**Comment by zanetti4** [comment]
此问题涉及到的手机系统是什么？

**Comment by 1076815296** [comment]
ios

**Comment by blockdate** [comment]
使用lightblue检查下对应特征值的Property是否支持读写

**Comment by 1076815296** [comment]
@blockdate 正常
![image](https://user-images.githubusercontent.com/43639032/61679018-6755e600-ad37-11e9-8ad2-ee3bb969dda8.png)

**Comment by 1076815296** [comment]
@blockdate 请问能不能解决下  设备是没有问题的 用旧框架可以使用 就是处在新框架上

**Comment by pencilCool** [comment]
我这边目前只有model 为:17216.magic_touch.d152 的设备，目前的状态是无法快联成功。
能扫描到设备，但是一直让你长按m键。长按m 键，没有任何反应。你那边能快联上吗。我先排除一下是不是固件的问题。我这边iOS 和安卓都连不上设备。

**Comment by pencilCool** [comment]
你们的插件还没上线，请先白名单上线，方便白名单测试。

**Comment by 1076815296** [comment]
已上线白名单  在老版本可以连接使用  新版本就是报此错误

**Comment by pencilCool** [comment]
这个请固件开发者检查固件内部状态转换是否符合预期。
