### ISSUE TITLE
切换印度地区后特定url无法跳转

### ISSUE THREAD

**Issue by Donkey-Kurt** [MiEcosystem/miot-plugin-sdk#1226]
**是否为新品（必填）**
新品

**关联的产品model**
yunmi.waterpuri.lx10

**项目ID（必填）**
P18-0299

**企业名称（必填）**
云米科技

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- SDK分支: master
- 相关模块:Host.ui

**现象（必填）**
         跳转的目标链接是：https://www.mi.com/in/
         现在使用的api是：米家sdk提供的  【Host.ui.openWebPage(url)】 api

         现状：
         米家app把地区设置为中国：能正常跳转（原生页面装载目标页面）
         米家app把地区设置为印度：点击按钮无任何反应。连【跳进新页面】的动作也没有」
         - - - - - - - - - - - - - - -
         以上为Android的情况。
         iOS：中国地区或印度地区都能正常跳转

**期望（必填）**
         Android设备切换到印度地区时正常跳转到https://www.mi.com/in/

**Comment by lvjie0519** [comment]
@Donkey-Kurt   麻烦下加下微信 (微信号:sky-boy-0519）, 需要你那边提供个账号测试下，谢谢。

**Comment by fishle** [comment]
试试这个安装包 https://pan.mioffice.cn:443/#/link/86F2D56EF7A09CC81D27DFA1354CF88A

**Comment by Donkey-Kurt** [comment]
> 试试这个安装包 https://pan.mioffice.cn:443/#/link/86F2D56EF7A09CC81D27DFA1354CF88A

试验了下好像不行

**Comment by Donkey-Kurt** [comment]
> > 试试这个安装包 https://pan.mioffice.cn:443/#/link/86F2D56EF7A09CC81D27DFA1354CF88A
> 
> 感谢帮助。
> 不过试验了下好像不行

可以了。谢谢。

**Comment by hanzhida** [comment]
米家现在海外暂时还不支持跳转商城。目前跳转链接商城正在评估中，后续研发进展会在进一步同步。
