### ISSUE TITLE
WebView  html 加载本地图片不显示问题

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#1227]
**是否为新品（必填）**
在售

**关联的产品model**
dmaker.airfresh.t2017

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
浙江星月电器

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。
应米家要求, 插件中不允许加载外部链接. 所以把之前的外部网页移到项目本地了, 本地调试正常显示图片, 但是打包到米家平台发现图片无法正常加载.  尝试着把包解压,发现包里面有图片资源, 但就是加载不出来.

**期望（必填）**
简单明了地描述一下期望的表现。
正常加载本地 html 的图片.

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/16514238/61445835-b9d28380-a980-11e9-882f-ad3f6c61f9a6.png)
![image](https://user-images.githubusercontent.com/16514238/61446068-2c436380-a981-11e9-8946-f6241a5a3abb.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
https://liruwei.github.io/2017/08/02/ReactNative-%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6/

1.你们为什么不能使用远程图片呢？2.你们为什么不直接RN来实现页面吗？
RN加载本地js和图片资源坑都比较多，暂时不计划解决此类问题，建议采用上面两种方式。

**Comment by coderrocks** [comment]
> https://liruwei.github.io/2017/08/02/ReactNative-%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6/
> 
> 1.你们为什么不能使用远程图片呢？2.你们为什么不直接RN来实现页面吗？
> RN加载本地js和图片资源坑都比较多，暂时不计划解决此类问题，建议采用上面两种方式。

IOT质量部现在要求插件里不能有外部链接，必须本地访问。无法加载本地图片的话我们就用rn来实现。

**Comment by fengdexunmi** [comment]
@coderrocks hello，我们这边也有这样的需求，也是同样的问题，你们那边现在如何解决html加载本地图片的问题？图片单独使用外部链接么？

**Comment by DaquanZhou** [comment]
@fengdexunmi 我们是用 rn 重写 html
