### ISSUE TITLE
进入CommonSetting页面，页面渲染的时间过长，Android手机有明显的卡顿感

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1228]
**是否为新品（必填）**
新品& 在售

**关联的产品model**
yeelink.light.lamp9

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
点进进入CommonSetting页面，在部分Android手机上要停留一两秒，才能进入，这里试过小米手机MI MAX2 、红米5 plus、三星 盖世note4,用com.xiaomi.demo也可以复现, api_level 10022

**期望（必填）**
进入CommonSetting页面优先相应点击事件操作展示界面，不卡顿

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@LiuMengzhou    麻烦梦舟帮忙看看，能否从UI层做些优化？

**Comment by LiuMengzhou** [comment]
好的

**Comment by TheWalkingDead1024** [comment]
> 好的

大佬你好，请问现在这个问题解决了么？

**Comment by zhouliangshun** [comment]
我们也遇到了，明显卡顿。请小米同学优化一下哦！

**Comment by TheWalkingDead1024** [comment]
> 好的

大佬你好，请问现在这个问题解决了么？

**Comment by LiuMengzhou** [comment]
确实有一点卡顿，通过打点也没发现问题，没有多余的渲染。暂时没有优化方案。
