### ISSUE TITLE
小米8手机在测试包中调试弹出  ' detected problems with API compatibility ' 提示。

### ISSUE THREAD

**Issue by caoguoli** [MiEcosystem/miot-plugin-sdk#1229]
**是否为新品（必填）**
 新品 

**关联的产品model**
deye.derh.u20a3

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
宁波德业日用电器科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[MI8，Android 版本：9]
- 测试包版本:[5.5.25.5、5.5.41.1]
- SDK分支: [10004]
- 相关模块:[EMW3080BP]

**现象（必填）**
小米8手机在测试包中调试发现，从我的设备页，选择设备，进入详情页后，会立马弹出  ' detected problems with API compatibility ' 提示。【必现，测试包版本】

**期望（必填）**
小米8手机，从我的设备页，选择设备，进入详情页后，跟其他手机一样不会弹出  ' detected problems with API compatibility ' 提示。

**其他的上下文/日志/截图**
返回数据打印截图如下：
http://loc.dingtalk.com/QzpcVXNlcnNcbXhjaGlwXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w0MzU5NDM1NzNfdjJcSW1hZ2VGaWxlc1wxNzQyMzJcMTY5OTI0ODE0OV83Mjk0NjQwMzE4X0lNRzIwMTkwNzE5MTQ0NjAwX1tCQDViZDljOGEuanBn

**Comment by zanetti4** [comment]
你提供的数据打印截图链接无法访问，换一种方式提供吧。我用华为荣耀9安卓7.0测试，没有这个问题，看来与特定机型有关。
