### ISSUE TITLE
LoadingDialog 相关

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#123]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account]

#### 现象

本问题是LoadingDialog UI相关疑问，基于issue #67  的最后回答（只设置title）。
只设置title的话，UI截图如下，LoadingDialog的右半部分无任何作用，一片空白，后面是否会处理呢？

![1544182901222](https://user-images.githubusercontent.com/12531667/49646045-eb818480-fa58-11e8-89cd-0239d0abc891.jpg)

#### 期望

可以正常显示

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Handby** [comment]
LoadingDialog设置timeout无效，并且在自动消失的时候不会调onDissmiss函数，MessageDialog可以在onDissmiss里设置visible为false，建议LoadingDialog也加上

**Comment by blockdate** [comment]
正在处理中，需要等待ipa更新。

**Comment by dzonel** [comment]
@blockdate 您好，请问这个是解决了吗？

**Comment by blockdate** [comment]
@dzonel 更新ipa，timeout与dismiss回调已解决

**Comment by dzonel** [comment]
@blockdate 收到，谢谢。

**Comment by dzonel** [comment]
@blockdate 您好，刚更新ipa以及最新SDK后试了一下，LoadingDialog可能还存在两个问题：
手机：iPhone 6 系统：12.0.1
1、未设置timeout还是会自动隐藏
2、title不能及时显示，不能及时显示的具体用法如下：
![1544600251077](https://user-images.githubusercontent.com/12531667/49854032-f4d96b00-fe23-11e8-9095-ae7201506cc7.jpg)

![1544600283296](https://user-images.githubusercontent.com/12531667/49854044-fd31a600-fe23-11e8-92ee-bab262aa31d2.jpg)
第二张图片中，如图所示使用时，title不会显示，如果将下面的注释打开，将loadingDialogVisible: true注释，先给loadingDialog_title赋值，过500ms后再让其显示，title有值。
title无值：即LoadingDialog显示后文字区域没有任何文字显示。
title有值：即LoadingDialog显示后文字区域有相应的文字显示。

**Comment by dzonel** [comment]
@blockdate 您好，MessageDialog的title和message有和上面第二条相似的问题。

**Comment by dzonel** [comment]
@blockdate 您好，感谢您的回复，文档上对于timeout的定义是“超时自动隐藏，设置0或者不设置不会自动隐藏”。

**Comment by dzonel** [comment]
@Handby 我这边试了下，onDismiss当主动设置visible为false让它消失的时候会调用，当等它自己消失的时候不会被调用。

**Comment by Handby** [comment]
是的  但是MessageDialog消失的时候会调用onDismiss @blockdate

**Comment by LiuMengzhou** [comment]
Duplicate of #110

**Comment by LiuMengzhou** [comment]
Duplicate of #67

**Comment by dzonel** [comment]
![1544759948506](https://user-images.githubusercontent.com/12531667/49982480-b2d13600-ff97-11e8-9acb-b108da2a2059.jpg)
目前这样做，可以解决文字信息不能及时显示的问题。

**Comment by blockdate** [comment]
相关操作请更新最新IPA尝试。

**Comment by dzonel** [comment]
好的
