### ISSUE TITLE
iphone 蓝牙连着门锁时，双重验证开锁 或 被授权蓝牙开锁 ，都会连续收到两条推送

### ISSUE THREAD

**Issue by Kimbleed** [MiEcosystem/miot-plugin-sdk#1230]
**是否为新品（必填）**
双重验证开锁的是新品  M1 loock.lock.v5
被授权蓝牙开锁的不是新品  

**关联的产品model**
被授权蓝牙开锁：loock.lock.v1  loock.lock.v3  loock.lock.v4
双重验证开锁：loock.lock.v5

**项目ID（必填）**
这个不大清楚

**企业名称（必填）**
云丁网络技术（北京）有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3.1

**现象（必填）**
前提条件：门锁支持双重验证开锁，有蓝牙网关，门锁处于双重验证开锁的状态
步骤：iphone手机蓝牙连接着门锁，然后用双重验证（密码+指纹）的方式开门，IOS手机会连续收到两条推送。
而且其中一条推送的文案是“16:22门锁被双重验证开锁”而另一条文案为“16:22我的双重验证开锁“
后者文案正确。
当iphone手机与门锁断开蓝牙连接，再双重验证开锁，此时收到一条推送。

被授权蓝牙开锁是同样的现象（收到两条推送，且一条推送名字对，另一条不对）

**期望（必填）**
只收到一条推送。

**其他的上下文/日志/截图**
![6161563526097_ pic](https://user-images.githubusercontent.com/22016697/61522483-097a8300-aa45-11e9-8215-9dfa15fc7294.jpg)

**Comment by zanetti4** [comment]
请填写详细信息，比如：SDK分支、手机系统……弹框失败是指什么？没有显示弹框？还是弹框提示了什么失败信息？方便我们进行排查，谢谢

**Comment by zanetti4** [comment]
#935

**Comment by pencilCool** [comment]
请问这个问题是否还存在？

**Comment by zhaolios** [comment]
仍存在此问题
