### ISSUE TITLE
智能场景提示"异常错误 "

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#1231]
**是否为新品（必填）**
新品

**关联的产品model**
dicook.cooker.wfz4003

**项目ID（必填）**

**企业名称（必填）**
浙江杭州无人炊

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
智能场景执行异常，以前执行是ok，今天执行的时候有时候是ok的，有时候是异常错误，是不是米家服务器不稳定？？
执行的这个方法没有参数，填写的没问题，是model+方法名
dicook.cooker.wfz4003.cancel_cook

**期望（必填）**
智能场景执行成功

**其他的上下文/日志/截图**
![IMG_6611](https://user-images.githubusercontent.com/18374383/61521574-1bf3bd00-aa43-11e9-9742-e3021929b5ce.PNG)

![IMG_6612](https://user-images.githubusercontent.com/18374383/61521583-21510780-aa43-11e9-957d-df7dac7b76ea.PNG)

![339E5BEFA6600B39071B07F6C50D4FF2](https://user-images.githubusercontent.com/18374383/61521624-3b8ae580-aa43-11e9-88c8-524f09045f76.png)

**尝试过的解决办法**
重新创建智能化，还是不行，没有参数

**不要贴大段代码❗️**

**Comment by zhuxinleibandou** [comment]
用户ID：147278657
执行场景：定时-16:38  无人炊智能煮饭机器人4取消烹饪
时间：19年16:38

**Comment by santcool** [comment]
提供抓包信息，看看失败的原因。或者提供账号密码，发送到zhangwenfeng@xiaomi,com。

**Comment by zhuxinleibandou** [comment]
> 提供抓包信息，看看失败的原因。或者提供账号密码，发送到zhangwenfeng@xiaomi,com。

已经将账户密码发送至邮箱，今天执行又是执行异常，周五晚上6点左右还挺稳定的，麻烦您帮忙看一下，谢谢了

**Comment by zhuxinleibandou** [comment]
> 提供抓包信息，看看失败的原因。或者提供账号密码，发送到zhangwenfeng@xiaomi,com。

目前项目在提审，这个问题可能会被拒绝，所以麻烦您了！谢谢

**Comment by zhuxinleibandou** [comment]
> 提供抓包信息，看看失败的原因。或者提供账号密码，发送到zhangwenfeng@xiaomi,com。

传回native的参数为： {"payload":{"command":"dicook.cooker.wfz4003.cancel_cook","plug_id":"","value":"","model":"dicook.cooker.wfz4003","did":"120681980","id":3250,"scene_type":2}}

**Comment by santcool** [comment]
问题暂且已解决，因value的方括号引起。需要服务端的同事排查，后续有最新进展，在微信群同步
