### ISSUE TITLE
执行开关其他的多条智能的自动化后智能开关状态未能同步到安卓APP端

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1232]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 6]
SDK分支: [10022]
相关模块:[Scene]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
创建手动智能，action为开关其他的智能；执行创建的智能，其他的智能状态未更新

期望（必填）
执行后智能的开关按钮状态同步变化

操作步骤：
1、创建手动智能（执行结果为开关某条智能）
2、比如创建手动智能1（执行结果：智能ABC 开、智能D 关），手动智能2(执行结果：ABC关、智能D开)
3、轮流执行这两条手动智能

期望效果：执行后智能的开关按钮状态同步变化

实际结果：安卓智能列表中的智能开关按钮状态未同步，需下拉刷新

操作视频：
[1.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3410394/1.mp4.zip)

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@xyliusun   ios有如上问题吗？

**Comment by xyliusun** [comment]
测试反馈没有在iOS看到这个问题，目前只有在安卓上有看到

**Comment by lvjie0519** [comment]
@xyliusun  问题已知，属于APP问题， 请通过内部提jira到米家这边，此处关闭。
