### ISSUE TITLE
设备绑定成功后没有跳转到插件首页

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#1234]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼R5智能锁/dsm.lock.r5

**环境（必填）**
- 电脑操作系统:  Windows
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010

**现象（必填）**
设备绑定成功后跳转到了设备搜索页，没有跳转到插件首页，见附件：
[1563529489339758.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3410505/1563529489339758.mp4.zip)

**期望（必填）**
设备绑定成功后跳转到到插件首页

**Comment by lvjie0519** [comment]
apk版本号是多少？   使用最新apk是否有问题？

**Comment by dessmann** [comment]
还在测试中，下周给结果

**Comment by cfJand** [comment]
@dessmann 测试的结果怎么样？

**Comment by dessmann** [comment]
目前没有接到反馈，持续跟踪中
