### ISSUE TITLE
大陆地区设备打开定时 无 法定工作日，法定节假日 选项

### ISSUE THREAD

**Issue by lingzhiwen** [MiEcosystem/miot-plugin-sdk#1235]
**是否为新品（必填）**
新品 和 在售

**关联的产品model**
lumi.gateway.aqhm01

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
深圳绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9.0]
- SDK分支: [10023]
- 相关模块:[Host/Service/ui]

**现象（必填）**
打开定时 周期性 无 法定工作日，法定节假日 选项

**期望（必填）**
打开定时有 法定工作日，法定节假日 选项

**其他的上下文/日志/截图**
手机服务器是选择的大陆地区，调用方式如下：
Host.ui.openTimerSettingPageWithOptions({
            onMethod: 'set_arming',
            onParam: 'on',
            offMethod: 'set_arming',
            offParam: 'off',
            identify: 'lumi_gateway_arming_timer'
          });

**尝试过的解决办法**
在另外一个设备调用有此选项。

**Comment by zanetti4** [comment]
@lvjie0519 我用安卓7.0测试，设置定时重复中有这两个选项。请你查看

**Comment by lvjie0519** [comment]
@lingzhiwen 
1、检查下 ios 是否有法定工作日，法定节假日 选项？
2、确认下使用的服务环境是否为国内服务环境？看代码国外服务环境不支持如上两个选项

**Comment by lingzhiwen** [comment]
> @lingzhiwen
> 1、检查下 ios 是否有法定工作日，法定节假日 选项？
> 2、确认下使用的服务环境是否为国内服务环境？看代码国外服务环境不支持如上两个选项

验证结果：
1.ios也没有
2.服务器环境是国内环境
3.我这边测试跟设备有关系：
> 这个模型值（lumi.gateway.aqhm01）的设备 没有 ,
> 这个模型值（lumi.plug.mmeu01）的设备 有

如果需要测试的话：
账号：840907289
密码：D()#j4ty4{O$jhi

房间：Lavie
设备：网关Lavie 【lumi.gateway.aqhm01】

房间：AllenLiu
设备：智能插座（Zigbee)【lumi.plug.mmeu01】

**Comment by lvjie0519** [comment]
@lingzhiwen   排查， lumi.gateway.aqhm01 这个model，配置在了 APP config 里面的 local_timer_config字段中，该字段里面配置的model， 是不会显示 法定工作日，法定节假日的，如果有需求 ，可以与我们这边产品沟通，谢谢。

**Comment by lvjie0519** [comment]
@lingzhiwen   这里先关闭，与产品沟通还存在问题再reopen。
