### ISSUE TITLE
插件不在前台时，setTimeout()和setInterval()不运行？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#1236]
**是否为新品（必填）**
新品

**关联的产品model**
ls123.headhone.t10

**企业名称（必填）**
猎声电子

**现象（必填）**
插件在前台运行，这时候手机出现弹窗占用前台，这时候插件中的setTimeout()和setInterval()方法不会运行，只有将弹窗点掉之后才能继续运行。
如下图所示的情况，插件中的setTimeout()和setInterval()不会运行。
![device-2019-07-19-200320](https://user-images.githubusercontent.com/12670497/61534073-291fa480-aa61-11e9-9f57-31f210fce169.png)

**期望（必填）**
短时间处于后台能够正常运行。

**Comment by LiuMengzhou** [comment]
是的，你可以看看其他解决方案

**Comment by dgutkai** [comment]
> 是的，你可以看看其他解决方案

你好，能否请问一下我想要达到setTimeout同样的效果，我有什么方案？

**Comment by dgutkai** [comment]
@LiuMengzhou 你好，能否请问一下我想要达到setTimeout同样的效果，我有什么方案？
