### ISSUE TITLE
智能场景Android正常IOS却无法进入界面

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#1237]
**是否为新品（必填）**
 在售

**关联的产品model**
chuangmi.ir.v2

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
创米科技

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS]
- SDK分支: [10010]
- 相关模块:[Entrance.Scene]

**现象（必填）**
智能场景Android正常IOS无法却进入界面

**期望（必填）**
IOS无法正常进入界面

**其他的上下文/日志/截图**
具体配置如下
![111111](https://user-images.githubusercontent.com/49702230/61574149-be687a80-aaed-11e9-9367-f4ef0c295672.png)

操作流程视频如下
[1.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3413240/1.zip)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
`Package.entrance` 在 ios 返回的结果是什么？

**Comment by daoke666** [comment]
![微信图片_20190722193915](https://user-images.githubusercontent.com/49702230/61629769-6d58b200-acb8-11e9-9ea2-ce28673ffa8d.png)

你好，用小米demo的也不行

android :Entrance.Scene= scene

ios ：packageDidLoaded 就没执行，没走进来

**Comment by santcool** [comment]
用SDK_10023试试？这个位子我记得中间某个版本有修改。

**Comment by daoke666** [comment]
还不行，要不我把设备共享给你帮忙看下

**Comment by daoke666** [comment]
@santcool 帮忙看看，这个项目在提测中了，

**Comment by santcool** [comment]
已指导解决，系project.json没配置好的原因。
