### ISSUE TITLE
创建智能成功后，app端1分钟后才显示

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1238]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8.1、iOS 12.3.1]
SDK分支: [10022]
相关模块:[app config]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
网关在线情况下添加智能，app端点击保存，提示添加成功， 智能在智能列表未显示，刷新页面也无返回；之后一分钟才出现。安卓和iOS，国内和国外服务器都会出现这种情况

期望（必填）
添加智能后，能够显示刚刚添加的智能

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我用安卓手机测试，米家 app 测试版，智能-我的 添加了一个定时智能，保存后在智能列表最下方马上就能找到。

**Comment by zanetti4** [comment]
@santcool @lvjie0519 你们能复现此问题吗？

**Comment by lvjie0519** [comment]
@xyliusun   未能复现，检查下是否在列表的其他位置，不一定在最顶端。

**Comment by santcool** [comment]
为能复现，请给出接口scene/editv2和scene/list抓包信息。我们让服务端的同学排查

**Comment by santcool** [comment]
经沟通，后续没人能复现，包括提问人员，问题关闭
