### ISSUE TITLE
快捷卡片上显示的状态与实际不一致

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#1239]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8.1、iOS 12.3.1]
SDK分支: [10022]
相关模块:[快捷卡片]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）

操作步骤一：
1、长按插座按键5s,删除设备，再按网关按键3下，在本地添加添加该子设备
2、添加成功后，查看APP首页

预期结果：首页上插件的快捷方式与实际插座状态一致

实际结果：首页上插件的快捷方式与实际插座状态不符

操作步骤二：
1、打开插座设备卡片，间隔1s点击两下卡片开关
2、看卡片状态是否有跟设备同步

预期结果：实际插座状态更新后，卡片开关状态也能更新

实际结果：首页上插件的快捷方式与实际插座状态不符

视频：
[1 (1).mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3416375/1.1.mp4.zip)

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@xyliusun   Android卡片问题，请先搜索下已关闭issue，寻找下解决方案，如未解决 请@dingshaoran 来看看。

**Comment by xyliusun** [comment]
测试已提jira，关闭此issue
