### ISSUE TITLE
iOS平台，import任何sdk相关资源闪退

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#124]
### SDK 最新

---

#### 环境
- 电脑操作系统:[eg. Mac OS]
- 手机系统:[eg. iOS]
- 相关模块:[eg. 所有模块]

#### 现象

import 任何sdk模块，如 `import res, {Language} from "miot/resources"`

直接报错
![screen shot 2018-12-08 at 9 48 12 am](https://user-images.githubusercontent.com/2043635/49680345-6769e400-face-11e8-96c8-e3cfdd21cb87.png)
![screen shot 2018-12-08 at 9 53 43 am](https://user-images.githubusercontent.com/2043635/49680438-2cb47b80-facf-11e8-8659-689b5fb64480.png)

android端更新了12.07 8点的包测试无问题，感觉是ipa包跟不上sdk的版本？
#### 期望

能正常import sdk

**Comment by flingInTheSky** [comment]
我这边也是，原本好好的，更新之后就不行了。现在都没法进行工作了。
