### ISSUE TITLE
loadProperties返回数据问题

### ISSUE THREAD

**Issue by balddonkey** [MiEcosystem/miot-plugin-sdk#1240]
**是否为新品（必填）**
新品

**关联的产品model**
opple.light.bydceiling

**项目ID（必填）**
无项目ID

**企业名称（必填）**
Opple

**环境（必填）**
- 电脑操作系统:Mac OS 10.14.3
- 手机系统:iOS 12.0
- SDK分支: master/10005/44e53d9
- 相关模块:miot/Device

**现象（必填）**
调用loadProperties时，传入此设备未支持的property时，返回数据会错误。
比如传入brightness和switch两个参数，其中switch支持，brightness不支持，此时返回的map数据中，brightness的值为switch的值，switch的值为undefined

**期望（必填）**
返回的值在map中与对应的key一致。

**Comment by santcool** [comment]
经与服务端的同学沟通，这个问题应该是在设备端。比如我抓取第一个rpc，存在不支持的key的情况，会用null占位。
https://api.io.mi.com/app/home/rpc/118648552
{"id":12,"method":"get_prop","accessKey":"IOS00026747c5acafc2","params":["props.2.1","props.2.2","props.2.3"]}

{
 "code": 0,
 "id": 12,
 "result": [null, null, null]

有问题的，直接返回空了，而且，因为result是一个array，客户端也没有办法去判断哪个值不存在。所以，需要你们的固件端的同学来做一下处理。
https://api.io.mi.com/app/home/rpc/124660227
{"id":11,"method":"get_prop","accessKey":"IOS00026747c5acafc2","params":["props.2.1","props.2.2","props.2.3"]}

{
 "code": 0,
 "id": 11,
 "result": []
}


}
