### ISSUE TITLE
Storge.setThirdUserConfigs用法

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#1241]
![171563791208_ pic](https://user-images.githubusercontent.com/18459414/61626145-0be01580-acaf-11e9-8760-3b72afd22ffc.jpg)
你好，我想请教一下，我这个key，我想用时间戳（1563782201这种格式的数字）做key,但是我发现，这个key，如果是大于5位数的number，存进去后再读取，就读取不到对应的数值，这个key是有什么限制的吗？
谢谢！

**Comment by zanetti4** [comment]
这个问题出现在什么手机系统？请给出更多信息

**Comment by zanetti4** [comment]
@lvjie0519 我用安卓手机测试
```javascript
Service.storage.setThirdUserConfigs('zimi.mosq.v1', 123456, '6位数').then(res => {
      console.log(res);

      Service.storage.getThirdUserConfigs('zimi.mosq.v1', 123456).then(data => {
        console.log(data);
      });
    });
```
打印出 data: `{uid: null, component_id: null, key: null, data: "", update_time: null}`
用3位数的 key，可以获取到相应信息。请你查看

**Comment by lvjie0519** [comment]
@caojunhua   已知，  我咨询下服务端，是否对key的大小做了限制，有回复及时反馈。

**Comment by lvjie0519** [comment]
@caojunhua  经服务端反馈， key的最大值为32767(2^15 -1)，谢谢。

**Comment by caojunhua** [comment]
> @caojunhua 经服务端反馈， key的最大值为32767(2^15 -1)，谢谢。

谢谢
