### ISSUE TITLE
语音授权页面 文字显示重叠

### ISSUE THREAD

**Issue by WangWeiYi185** [MiEcosystem/miot-plugin-sdk#1242]
**是否为新品（必填）**
 在售

**关联的产品model**
midr.rv_mirror.v1 小米米家后视镜

**项目ID（必填）**
615

**企业名称（必填）**
新案数字科技

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
米家app中设置-多语言-设置为英文 -插件首页点击底部语音授权按钮-进入授权界面

**期望（必填）**
正常显示

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![文字重叠](https://user-images.githubusercontent.com/17384529/61633681-31c2e580-acc2-11e9-9a7b-33e2f4f31cbe.png)

**尝试过的解决办法**
米家原生页面,无法修改

**不要贴大段代码❗️**

**Comment by santcool** [comment]
已完成，后续提供的包将不会有此问题。
