### ISSUE TITLE
Host.getPhoneScreenInfo()接口获取的全面屏高度有时候正确，有时候不正确

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#1243]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0 Mix2
- SDK分支: 10023
- 相关模块: Host.getPhoneScreenInfo()

**现象（必填）**
Host.getPhoneScreenInfo()接口获取的全面屏高度有时候正确，有时候不正确。

**第一次** Host.getPhoneScreenInfo()获取的高度为785，**正确**

![4141563824270_ pic_hd](https://user-images.githubusercontent.com/2813239/61660452-6ce20a80-acfc-11e9-9803-6587492d2e85.jpg)

**第二次** Host.getPhoneScreenInfo()获取的高度为738，**不正确**

![4151563824483_ pic_hd](https://user-images.githubusercontent.com/2813239/61660455-6f446480-acfc-11e9-8398-973b5add7215.jpg)

**期望（必填）**
Host.getPhoneScreenInfo()接口获取正确的全面屏高度

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@lvjie0519 我用非全面屏手机测试，没问题。请你查看全面屏手机

**Comment by fishle** [comment]
麻烦按照miot-rn-plugin这个tag过滤一下log，然后发出来看看

**Comment by fengdexunmi** [comment]
@fishle 目前和 @lvjie0519 正在微信群里讨论这个问题，可以进群讨论下

![4021563865735_ pic_hd](https://user-images.githubusercontent.com/2813239/61694105-689d0800-ad63-11e9-8a45-8c8c44b31b5d.jpg)

---

![4031563865735_ pic_hd](https://user-images.githubusercontent.com/2813239/61694113-6aff6200-ad63-11e9-9359-e3d130443cdd.jpg)

**Comment by fishle** [comment]
下个版本修复，调试的可以试试这个包https://pan.mioffice.cn:443/#/link/5090FEF2AF1E7652A8D215E75E20CFCA

**Comment by fengdexunmi** [comment]
@fishle 好的，谢谢。我先验证下。
