### ISSUE TITLE
关于支持spec协议的扫地机快捷卡片的开启

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#1244]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米家扫拖机器人1C/dreame.vacuum.mc1808

**现象（必填）**
1、打开快捷卡片开关后，点开设备显示设备暂不支持快捷操作，在https://miot-spec.org/miot-spec-v2/instances?status=all 文档中，是有加入此卡片的model的
2、在米家app-》我的--》设备耗材中，如何显示米家扫拖机器人1C的耗材卡片
**期望（必填）**
可以正常显示快捷卡片，进行操控调试

**Comment by zanetti4** [comment]
该问题出现在哪个手机系统？

**Comment by heigaga001** [comment]
@zanetti4 目前这边试的几个手机都不行，是否可以提供用户id，我分享一个设备给你

**Comment by zanetti4** [comment]
我正在联系负责此类问题的同事

**Comment by dingshaoran** [comment]
你的spec 配置还没上线，release 接口拉取不到，需要在米家-我的-设置-服务器环境 切换成 preview
