### ISSUE TITLE
miot/ui/Dialog/InputDialog Android和IOS上调用弹框均被键盘遮挡

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1245]
**是否为新品（必填）**
 新品 or 在售

**关联的产品model**

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yelight

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
调用apilevel=10023 miot/ui/Dialog/InputDialog 组件在布局中使用，默认弹框被键盘遮挡，复现手机Android红米5 plus IPhone6

**期望（必填）**
弹框和输入法位置适配，不被遮挡

**其他的上下文/日志/截图**
![68961563796109_ pic_hd](https://user-images.githubusercontent.com/42829167/61675629-b269fc00-ad2b-11e9-9ffa-b37fc5653657.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@LiuMengzhou 我用华为手机进行测试，取消、确定按钮会被输入法挡住，只有隐藏输入法后才能点击。请你查看

**Comment by LiuMengzhou** [comment]
#1374

**Comment by LiuMengzhou** [comment]
这个今天解决

**Comment by dan-huang** [comment]
最新的iOS集测包仍未解决 @LiuMengzhou
