### ISSUE TITLE
设备宫格图界面名称显示不全

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1246]
**是否为新品（必填）**
在售

**关联的产品model**
xiaoxun.tracker.v1

**企业名称（必填）**
上海小寻科技有限公司

**环境（必填）**
Android手机

**现象（必填）**
设备名称是“米兔定位456”，但在米家Android APP的宫格界面显示成“定位456”，ios显示正常

**期望（必填）**
希望在宫格界面显示成“米兔定位456”

**其他的上下文/日志/截图**
正确名称：
![WechatIMG2](https://user-images.githubusercontent.com/34823528/61679751-d3394e00-ad39-11e9-81de-446a2dfc8f22.png)
**宫格界面显示的名称**：

![WechatIMG1](https://user-images.githubusercontent.com/34823528/61679766-e2b89700-ad39-11e9-8444-f60b6bd549c4.png)

**Comment by lvjie0519** [comment]
@dingshaoran  丁绍然麻烦帮忙看看这个问题吧

**Comment by lvjie0519** [comment]
@heping99   设计如此， 设备名称中含有某些特殊的名称会自动去掉，谢谢。
