### ISSUE TITLE
iBluetooth.maximumWriteValueLength是否有替代方案

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#1247]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼R5智能锁/dsm.lock.r5

**环境（必填）**
- 电脑操作系统:  Windows
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010

**现象（必填）**
根据文档介绍，iBluetooth.maximumWriteValueLength这个方法在ios上存在适配问题，是否有其他接口可以协商到ble的mtu呢？

**期望（必填）**
iBluetooth.maximumWriteValueLength方法可以稳定获取到数据，或者有其他替代方案

**Comment by santcool** [comment]
请仔细看备注，这个是iOS系统的接口，意思是系统的接口不准确，我们是没办法的。需要你们通过比如android，或者固件端自己测试这个长度，然后和iOS获取的对比，再决定是否使用此方法。
一般情况下应该没问题，特殊情况，目测只能写死了。
