### ISSUE TITLE
安卓快捷卡片配置问题

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#1248]
![1951563858347_ pic](https://user-images.githubusercontent.com/14158970/61685268-cffc8d00-ad4e-11e9-8144-2420ed3173b1.jpg)
安卓的卡片配置 cardType 似乎把7和8弄反了

iOS上用cardType 7的类型是正常的，但是安卓不行。安卓改为8以后可以显示，但iOS就不行了。当安卓为8时，后面的“L”单位也没有正常显示

![2431563849538_ pic_hd](https://user-images.githubusercontent.com/14158970/61685244-b4918200-ad4e-11e9-8b8d-32ebcd4cfd23.jpg)
上图为 iOS 正常的情况

![IMG_7801](https://user-images.githubusercontent.com/14158970/61685400-3aadc880-ad4f-11e9-8bca-b6798f44c017.JPG)
上图是cardType为7时，安卓的显示情况

安卓版本为5.5.42.1测试版，本地SDK为10023

**Comment by lvjie0519** [comment]
@dingshaoran   丁绍然帮忙看看卡片问题吧

**Comment by lvjie0519** [comment]
@RengeRenge    好像看你在微信群 问到了这个问题，  问题是否解决？如果解决请关闭下issue，同时说一下 解决方法，谢谢。

**Comment by RengeRenge** [comment]
你好，问题未解决




| |
李迪
邮箱：lidrkuft123@163.com
|

签名由 网易邮箱大师 定制

在2019年07月26日 16:34，小米-吕杰 写道：

@RengeRenge 好像看你在微信群 问到了这个问题， 问题是否解决？如果解决请关闭下issue，同时说一下 解决方法，谢谢。

**Comment by dingshaoran** [comment]
请查看文档，https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/03-%E7%B1%B3%E5%AE%B6%E5%8D%A1%E7%89%87%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E/00-%E7%B1%B3%E5%AE%B6%E5%8D%A1%E7%89%87%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E  找一下 主要参数 format 相关的说明并配置。
