### ISSUE TITLE
MHDatePicker 部分日期不能被选中

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1249]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？
- 是否尝试搜索“常见问题”

---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
jiqid.mistory.ipen1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
南京机器岛智能科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:.Android 8.1/iOS 12.0
- SDK分支: 10022
- 相关模块:Host/Service/Account

**现象（必填）**
使用MHDatePicker作为生日选择器时，选择生日：月份和日期只能选择部分，若今天日期是2019-07-23，日期不能选择2004-07-23之前和2034-07-23之后的日期；

**期望（必填）**
时间选择器上的日期应该都能被选中

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
可以通过 min 和 max 属性设置最大、最小值。
比如：
`min={[1996]}`
就可以选择至1996年了。

**Comment by Aphrodite123** [comment]
> 可以通过 min 和 max 属性设置最大、最小值。
> 比如：
> `min={[1996]}`
> 就可以选择至1996年了。

已解决，多谢！
