### ISSUE TITLE
iOS 设备离线获取不到固件最新版本

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1250]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？
- 是否尝试搜索“常见问题”

---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
jiqid.mistory.ipen1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
南京机器岛智能科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/iOS 12.0
- SDK分支: 10022
- 相关模块:Host/Service/Account

**现象（必填）**
iOS 离线状态下，进入固件升级页面，页面不显示最新固件版本，获取不到固件最新版本；

**期望（必填）**
离线状态下，进入固件升级页面，正常获取固件的最新版本；

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
你们是蓝牙设备？

**Comment by Aphrodite123** [comment]
> 你们是蓝牙设备？
双模WiFi，双模当做单模用的

**Comment by Aphrodite123** [comment]
> 你们是蓝牙设备？
双模WiFi，双模当做单模用的

**Comment by santcool** [comment]
因为升级本来是一个依赖网络的操作，就算从本地读取了版本，也是没法下载固件安装包并进行固件升级的，所以并没有支持此功能。

**Comment by Aphrodite123** [comment]
> 因为升级本来是一个依赖网络的操作，就算从本地读取了版本，也是没法下载固件安装包并进行固件升级的，所以并没有支持此功能。

android上面是可以的，所以看要不要统一下，这样我也能依据这个来统一自己插件相关的逻辑
