### ISSUE TITLE
米家拉不到最新版插件

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#1252]
---
**是否为新品（必填）**
在售
**关联的产品model**
philips.light.nlight
philips.light.zystrip
**项目ID（必填）**
夜灯 灯带
**企业名称（必填）**
飞彗
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
使用米家（iOS V4.19.2)加载不到最新版插件（maser10021最新sdk打包）。刷新或者清除缓存，会交替加载新旧本版插件。
**期望（必填）**

稳定加载新版插件
**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
重装米家；清除缓存；刷新列表
**不要贴大段代码❗️**

**Comment by santcool** [comment]
是新传上去的插件包吗？如果是，那么我们也没有什么办法，这个位子我们多次推动，服务端的同学说没有办法改……它只会交替半小时左右，然后就可以正常使用了。
