### ISSUE TITLE
ios上回调周期异常

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#1254]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼R5智能锁/dsm.lock.r5

**环境（必填）**
- 电脑操作系统:  mac
- 手机系统:  iPhone 7 plus 12.3.1
- SDK分支:   10010

**现象（必填）**
如题，ios上蓝牙连接回调有时候收不到回调消息：
1、安卓上没有问题
2、ios上回调消息不稳定，有时候上午没有，下午有，有时候今天没有，明天有，有时候开发者模式有，非开发者模式没有

尝试在业务最外层设置全局setTimeout定时器，发现在收不到蓝牙回调消息的时候，定时器也无法正常工作.

备注：代码都完全一样

**期望（必填）**
ios上蓝牙连接能稳定收到回调消息，或者定时器可以正常工作

**Comment by zanetti4** [comment]
1.收不到蓝牙回调消息的时候，有报错信息吗？
2. connect(type = -1, option = 0)

> param {json} option -附加参数, 格式 {timeout:12000, peripheralID:"..."}, timeout的单位为毫秒, peripheralID是iOS平台参数

如果填入 peripheralID，是否能解决问题？

**Comment by dessmann** [comment]
1、没有报错消息，页面UI都正常，可以正常响应点击事件
2、我试一下

**Comment by dessmann** [comment]
peripheralID这个参数如何获取呢？
文档上关于扫描获取peripheralID的描述如下：

> iBluetooth.connect(type, option) ⇒ Promise.<IBluetooth>

打开蓝牙链接. option参数peripheralID为iOS 平台的可选参数，因为iOS平台无法获取普通 BLE 蓝牙设备的 Mac peripheralID 可通过 startScan（）搜索周边蓝牙设备获取（如设备OTA中，设备固件切换，无小米蓝牙协议相关服务时需建立连接），或通过retrievePeripheralsWithServicesForIOS（）搜索已连接设备获取（如可穿戴长连接设备，无法发送 mibeacon） 建立连接后，SDK 会用 peripheralID 充当 Mac 地址 error code : 0 - 成功

上面描述的，通过startScan方法搜索周围的蓝牙设备获取peripheralID，但是可能存在多个设备，扫描过滤条件怎么写呢？

**Comment by zanetti4** [comment]
> startScan(durationInMillis, ...serviceUUIDs)
param {...string} serviceUUIDs - 指定扫描, 为空时扫描全部

可以指定扫描当前设备

**Comment by dessmann** [comment]
serviceUUIDs只能限定一类设备吧，如果扫描到多个此类设备，如何区分是当前设备呢？

**Comment by zanetti4** [comment]
@pencilCool 请你协助查看此问题，该如何解决？

**Comment by pencilCool** [comment]
收不到回调信息。你们之前是怎么调用的。可以上传一下console 的日志吗？

**Comment by dessmann** [comment]
主要是这个问题只在release模式下出现，debug模式下出现不了，console日志看不到啊，我尝试把日志写入到了文件，但是ios的文件系统需要越狱才能看到，手上没有越狱过的手机啊

**Comment by pencilCool** [comment]
无法复现这个问题，请在sdk10023 以上版本上尝试。
