### ISSUE TITLE
设置Android插件调试环境

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/miot-plugin-sdk#1255]
**是否为新品（必填）**
  新品  

**关联的产品model**
 duoqin.safe.pbfv01

**项目ID（必填）**
 【无项目ID】

**企业名称（必填）**
深圳多亲科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 9.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
下载了开发版的米家，在相关位置并没有找到RN设备插件调试设置
 首页“我的”tab -> 设置 -> 开发者选项 -> RN设备插件调试设置

**期望（必填）**
怎么设置Android插件调试环境
 

**尝试过的解决办法**
下载很多次米家APP，都是这样，APK现在的界面请看附件 

![011](https://user-images.githubusercontent.com/52914317/61732183-a0ca3800-adaf-11e9-8a78-cfdf000faf11.jpg)
![012](https://user-images.githubusercontent.com/52914317/61732190-a3c52880-adaf-11e9-8396-5a4efa1d42d1.jpg)
![013](https://user-images.githubusercontent.com/52914317/61732195-a758af80-adaf-11e9-9dd5-229ba8d6ecd6.jpg)

**不要贴大段代码❗️**

**Comment by JiuanZbf** [comment]
位置找错了。在主界面导航栏我的那一页最后面

**Comment by zanetti4** [comment]
是的，在**我的**选项卡中，最下方有**开发者设置**。
