### ISSUE TITLE
设备停留控制界面，更新设备状态时，界面未刷新

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1256]
**是否为新品（必填）**
填 新品 

**关联的产品model**
model:lumi.plug.mmeu01

**项目ID（必填）**
项目ID: 21100

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[eg.Windows10
- 手机系统:[eg.Android 8.1]
- SDK分支: [10022]
- 相关模块:[欧标插座首页]

**现象（必填）**
操作步骤：
1、iOS和安卓登录同个账号，并都停留在设备控制页面（设备为：米家智能插座（zigbee版））

2、在iOS上控制插座及控制电器使功率发生变化，观察安卓机插座首页的状态

预期结果：界面刷新，并且同步插座和电量功率的状态

实际结果：开关和功率未刷新，状态不变
（高概率出现，操作20次出现10次；退出插座首页再重新进入数据才更新）

**Comment by lvjie0519** [comment]
@dengdeng223  
1、反之ios是否存在相同问题？
2、代码中，你是怎样监听设备属性发生变化的？

**Comment by xyliusun** [comment]
![1563968898613](https://user-images.githubusercontent.com/20435121/61791280-23083a00-ae4c-11e9-8740-e49f266d72dd.jpg)
订阅的代码大概是这样，主要就是订阅了一些插座的属性和事件

**Comment by lvjie0519** [comment]
@dengdeng223 
1、 麻烦复现一下， 然后通过  miot-rn-plugin 过滤下log日志， 可以看到  原生层是否向js发送了数据；
2、 如果没有对应日志，就需要找服务端排查下，是否push了对应消息。

**Comment by xyliusun** [comment]
欧洲服务器的插座订阅消息，测试20次一次都收不到，看PushManager打印也是没有log消息

**Comment by lvjie0519** [comment]
@dengdeng223   跟ios对比下，  ios是否有收到消息？

**Comment by xyliusun** [comment]
ios能收到，刚刚测试的没用到海外版的安卓系统
用台湾版的安卓系统红米note6重新测试欧洲服务器下插座的状态订阅，20次的订阅数据全部收到，就是有5次延迟比较高

**Comment by xyliusun** [comment]
@dengdeng223 麻烦安排一下海外版的安卓系统的测试，评估一下问题是否解决

**Comment by fishle** [comment]
测试结果如何？

**Comment by dengdeng223** [comment]
> 测试结果如何？

使用海外版安卓机与iOS对标，发现开关的订阅状态能收到，但是有延迟0.4s左右；另外开启插座开关后，iOS&Android功率经常订阅不到（查看网关日志，已上报功率数据），需重新进入插座首页才更新

**Comment by dengdeng223** [comment]
该问题为服务端的，暂关闭，后续提到jira中
