### ISSUE TITLE
插座接入电器，网关已上报足够的电量但未APP端未显示

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1257]
是否为新品（必填）
填 新品

关联的产品model
model:lumi.plug.mmeu01

项目ID（必填）
项目ID: 21100

企业名称（必填）
绿米

环境（必填）

电脑操作系统:[eg.Windows10
手机系统:[eg.Android 8.1]
SDK分支: [10022]
相关模块:[欧标插座电量]
**现象（必填）**
操作步骤一：
1、将插座数据清除（解除授权），重新添加插座后，接入电器（笔记本电脑），观察几天

预期结果：APP上会显示电量

实际结果：查看网关日志，一天上报的电量（cost）的累计值大于100，及电量应大于0.1kwh；但APP端电量显示为0（高概率复现）

操作步骤二：
1、网关添加一个新的欧标插座并接入电器
2、查看电量显示

预期结果：正常显示电量数值

实际结果：今日用电显示0.0  当月用电显示0.1（实际为使用插座的第一天，电量统计的数据应一致；概率：只出现一次）

**其他的上下文/日志/截图**
问题一日志：
[session-Serial-COM10-20190719.log](https://github.com/MiEcosystem/miot-plugin-sdk/files/3424784/session-Serial-COM10-20190719.log)

问题二截图：![image](https://user-images.githubusercontent.com/43058257/61760589-a00cc280-adfe-11e9-9e9c-6e203bae0880.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@dengdeng223   
1、ios有问题吗？
2、这个数据的获取具体是调用哪个api获取的？抓包看下网络请求数据是否正常？

**Comment by lvjie0519** [comment]
线下已沟通，不属于框架问题，暂且关闭。
