### ISSUE TITLE
react-navigation 页面切换不能正常显示左右切换动画

### ISSUE THREAD

**Issue by xhsYL** [MiEcosystem/miot-plugin-sdk#1258]
**是否为新品（必填）**
   新品

**关联的产品model**
   yeelink.ven_fan.vf2

**项目ID（必填）**
   无项目ID

**企业名称（必填）**
   Yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.0以上]
- SDK分支: [master/10022]
- 相关模块:[react-navigation]

**现象（必填）**
1. 实现目标：实现页面跳转，并切伴有页面的左右切换动画
2. 操作逻辑：在页面中使用react-navigation的方法navigate()或push()
3. 实际效果：
-- 3.1 在iphone手机上能正常页面跳转并显示左右切换动画
-- 3.2 在Android设备上
---- 3.2.1 小米9se(9.0)，一加6(9.0) 上能正常跳转并显示左右切换动画
---- 3.2.2 华为P9(8.0) 上能正常跳转，不能显示左右切换动画

**期望（必填）**
   实现页面跳转，并切伴有页面的左右切换动画

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
我用安卓7测试 com.xiaomi.demo，能显示左右切换动画。网上搜到[一篇帖子](https://www.jianshu.com/p/49f538456b8e)，看看是否对你有帮助？

**Comment by xhsYL** [comment]
![error](https://user-images.githubusercontent.com/52951363/62177509-b921f000-b377-11e9-9e5e-48620ed5153f.png)

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，如问题未解决，在reopen。
