### ISSUE TITLE
无网络情况下反馈页面加载出错显示问题

### ISSUE THREAD

**Issue by xhsYL** [MiEcosystem/miot-plugin-sdk#1259]
**是否为新品（必填）**
   新品

**关联的产品model**
   yeelink.ven_fan.vf2

**项目ID（必填）**
   无项目ID

**企业名称（必填）**
   Yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.0以上]
- SDK分支: [master/10022]
- 相关模块:[react-navigation]

**现象（必填）**
   在英文模式下，进入“使用帮助”页，如果网络存在异常，页面中存在中文字符

**期望（必填）**
  当网络异常时，页面根据当前语言显示具体提示

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
最好能贴上错误截图

**Comment by lvjie0519** [comment]
@xhsYL   麻烦附上截图或视频的压缩包，方便排查，谢谢。

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，如有问题，在reopen。

**Comment by xhsYL** [comment]
![error](https://user-images.githubusercontent.com/52951363/62177558-e8386180-b377-11e9-835b-262a54e89bb4.png)

**Comment by xhsYL** [comment]
![1](https://user-images.githubusercontent.com/52951363/62177629-39485580-b378-11e9-8968-4dd288c424ea.jpg)

**Comment by xhsYL** [comment]
@lvjie0519 你好，这是在英文模式下，打开帮助页，网络出现异常时，页面的显示样式

**Comment by lvjie0519** [comment]
@xhsYL   这个是系统默认的，  你将系统切换为英文， 应该显示的是英文。

**Comment by xhsYL** [comment]
嗯嗯 现在可以了 @lvjie0519 . 感谢感谢。  不过网页错误提示显示了具体的请求地址，太暴露了，这个可以优化下吗

**Comment by lvjie0519** [comment]
@xhsYL   ios是上如何显示的？

**Comment by xhsYL** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/52951363/62281291-1608cd80-b480-11e9-8ddc-fa4c0637babb.jpeg)

**Comment by xhsYL** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/52951363/62281317-23be5300-b480-11e9-8c15-3e4faeb27307.jpeg)

**Comment by xhsYL** [comment]
@lvjie0519 ios直接显示空白页

**Comment by lvjie0519** [comment]
@xhsYL   这个属于APP那边的问题，咨询了，说对方会进行优化，如果你那边提测因该问题受到阻塞，可以通过内部jira平台提bug反馈到米家这边，这里暂且关闭，谢谢。

**Comment by xhsYL** [comment]
> @xhsYL 这个属于APP那边的问题，咨询了，说对方会进行优化，如果你那边提测因该问题受到阻塞，可以通过内部jira平台提bug反馈到米家这边，这里暂且关闭，谢谢。

多谢多谢
