### ISSUE TITLE
插件后台升级后，iOS/android无更新

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1260]
是否为新品（必填）
填 新品

关联的产品model
model:lumi.plug.mmeu01

项目ID（必填）
项目ID: 21100

企业名称（必填）
绿米

环境（必填）

电脑操作系统:[eg.Windows10
手机系统:[eg.Android 8.1]
SDK分支: [10022]
相关模块:[欧标插座-插件升级]

**现象（必填）**
操作步骤：
1、开发在后台提交了几个插件版本
2、查看iOS/Android插件版本号

预期结果：都更新到最新的版本
实际结果：iOS和Android（已开启插件自动更新）未更新到最新版本（概率：高概率出现）

**尝试过的解决办法**
尝试重新添加设备，或者清除APP数据与缓存都无效

**不要贴大段代码❗️**

**Comment by santcool** [comment]
1.新提交的版本需要半个小时左右才能生效，期间新旧插件会一直跳，系后台的bug，后台的人说无法解决。。半小时之后基本就稳定了
2.如果app支持的SDK是SDK_10022，但是你的插件是基于SDK_10023打包的，这样也是没法更新到最新插件的。iOS可以通过打开：我的 - 设置 - 调试入口 - 测试设置 - 插件信息展示 ，然后再打开插件，就会提示SDK信息来查看SDK版本。或者直接抓包fetch_plugin和fetch_sdk来查看
