### ISSUE TITLE
RN色盘吸色实现

### ISSUE THREAD

**Issue by LavieLumi** [MiEcosystem/miot-plugin-sdk#1261]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.gateway.mieu01

**项目ID（必填）**
21291

**企业名称（必填）**
深圳市绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
RN无图片吸色的api

**期望（必填）**
期望能有吸色api或者其他的技术方案

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/50569278/61765244-d5b9a780-ae0e-11e9-942a-5f691089c28a.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
目前没提供，自己用rn实现吧
