### ISSUE TITLE
iOS—‘我的’-‘设备共享’中有插座共享入口

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1262]
是否为新品（必填）
填 新品

关联的产品model
model:lumi.plug.mmeu01

项目ID（必填）
项目ID: 21100

企业名称（必填）
绿米

环境（必填）

电脑操作系统:[eg.Windows10
手机系统:[eg.iOS 12.1]
SDK分支: [10022]
相关模块:[我的——设备共享]

**现象（必填）**

操作步骤：1、进入iOS APP，点击底部‘’我的‘——‘设备共享’，查看可共享的设备

预期结果：只显示网关，无子设备

实际结果：显示了网关和插座’（概率：必现）

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43058257/61762847-e1ed3700-ae05-11e9-956f-5c4bdac1ec8f.png)

**不要贴大段代码❗️**

**Comment by santcool** [comment]
更改support平台的产品定义配置，将是否允许分享改为不可分享即可解决
