### ISSUE TITLE
添加设备时倒计时与图片部分重合（兼容）

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1263]
是否为新品（必填）
填 新品

关联的产品model
model:lumi.plug.mmeu01

项目ID（必填）
项目ID: 21100

企业名称（必填）
绿米

环境（必填）

电脑操作系统:[eg.Windows10
手机系统:[eg.Android 8.1]
SDK分支: [10022]
相关模块:[添加设备]
**现象（必填）**
1、进入APP，点击‘米家’栏右上角的‘+’号，添加设备，如‘米家人体传感器’，查看界面

预期结果：界面与UI设计一致
实际结果：倒计时图标与图片重合（初步判断与手机分辨率有关，出现该现象的手机为iPhone8,）

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/43058257/61764676-9e49fb80-ae0c-11e9-883c-541e931070c3.png)

**不要贴大段代码❗️**

**Comment by santcool** [comment]
我看了其他一些公司的连接，很多都是用稍微窄一点的图片，整体下移会影响整体的显示效果。经与设计师沟通，暂不修改。你们在后台配置窄图片即可
