### ISSUE TITLE
固件升级提示"更新失败，点击重试"，多次点击依然提示

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#1264]
**是否为新品（必填）**
 新品

**关联的产品model**
dicook.cooker.wfz4003

**项目ID（必填）**
66444

**企业名称（必填）**
杭州点厨科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
固件升级提示"更新失败，点击重试"，多次点击依然提示，返回上一个页面，在进入就能看到固件在更新的页面了

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**

![Kapture 2019-07-24 at 12 23 01](https://user-images.githubusercontent.com/18374383/61765024-e1589e80-ae0d-11e9-9c98-35a855dcaac5.gif)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
该问题出现在哪个手机系统？

**Comment by zhuxinleibandou** [comment]
> 该问题出现在哪个手机系统？
出现在Android手机系统中，在提审测试的时候测试人员发给我们的，不容易复现，不知道是当时网络原因还是什么原因

**Comment by cfJand** [comment]
建议下次复现后，通过米家的用户反馈，把日志上传给我们后台，我们好分析一下，目前单纯从现象无法看出哪里有问题。
