### ISSUE TITLE
用应用商店版本加载不了新插件？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#1265]
**是否为新品（必填）**
新品

**关联的产品model**
ls123.headphone.t10

**项目ID（必填）**

**企业名称（必填）**
猎声电子

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
使用应用商店上最新的米家加载的是旧插件，没有加载新插件。而使用FIR上的测试版米家则可以加载到新框架的插件。
旧框架的插件和新框架的插件都处在白名单测试中。
**期望（必填）**
用线上版本能够正确加载新框架的插件。

**Comment by zanetti4** [comment]
这是指安卓还是 ios?

**Comment by dgutkai** [comment]
是Android，版本号是5.5.43

**Comment by lvjie0519** [comment]
@dgutkai  版本号是5.5.43，支持的apilevel 为 10022， 你的新插件 用到的sdk版本是多少？ 10023是不支持的。

**Comment by dgutkai** [comment]
我的用到的是10023的，那意思就是5.5.43一下的版本我这个插件不支持吧。

**Comment by lvjie0519** [comment]
> 我的用到的是10023的，那意思就是5.5.43一下的版本我这个插件不支持吧。

是的，线上版本，目前只支持到10022， 你可以用fir上最新的debug 版本apk进行测试。支持10023的apk，目前在灰度中，预计一个星期左右会上线。
