### ISSUE TITLE
IOS设置智能场景报错

### ISSUE THREAD

**Issue by fergus825** [MiEcosystem/miot-plugin-sdk#1266]
是否为新品（必填）
新品(在售)
关联的产品model
chuangmi.lock.hmi501

项目ID（必填）
【无项目ID】

企业名称（必填）
创米科技

环境（必填）
电脑操作系统:Mac OS 10.14.5
手机系统:IPhone7 IOS12.3.1
SDK分支: 10021

相关模块:[智能场景]

现象（必填）
小米IoT开发者平台配置了小米IoT开发者平台配置了 任意正常开锁、任意异常开锁、电量低于5%、电量低于10%、指定开锁、门前有人按铃共6项作为用户可选的触发条件。其中任意正常开锁、任意异常开锁和指定开锁需要进入我们自定义的选择页面。其余三项点击即可设置。
**重现流程：选择任意正常开锁、任意异常开锁和指定开锁其中之一的作为触发条件，然后修改这个触发条件为电量低于5%、电量低于10%和门前有人按铃其中之一，随即便会崩溃。**
如果是任意正常开锁、任意异常开锁和指定开锁之间来回设定和修改 或在电量低于5%、电量低于10%和门前有人按铃之间设置和修改均不会报错。

**期望（必填）**
上述六项智能选项中可以正常地设置和修改。

**其他的上下文/日志/截
![image](https://user-images.githubusercontent.com/25863361/61773993-8c765180-ae28-11e9-9ca0-e4758629550a.png)
图**

**尝试过的解决办法**
在米家正式版 V4.19.2和Beta版2412上均会重现该问题，IPad上亦然。

**Comment by santcool** [comment]
已更新文档，着重强调了action_id和trigger_id的配置注意点。
<img width="774" alt="屏幕快照 2019-07-24 下午4 30 49" src="https://user-images.githubusercontent.com/8580061/61777960-78cee900-ae30-11e9-9ddd-8a5201321e7b.png">

**Comment by fergus825** [comment]
我在project.json文件中删除了没有自定义页面的triggers_ids后，恢复正常。谢谢指点！
