### ISSUE TITLE
获取设备状态数据，iOS偶现获取失败，安卓未出现

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1267]
miot-sdk 10021
米家app最新
model: chunmi.cooker.k1pro1
公司：纯米科技

小米jira 1133

Device.getDeviceWifi().callMethod(method, params)
    .then(json => {
        
        if (json.code == 0) {
            callback(true, json)
        } 
        
    })
    .catch(res => {
        console.warn('res', res)
        callback(false, res.error)
        
    });

![IMG_3642](https://user-images.githubusercontent.com/17631207/61775765-1d026100-ae2c-11e9-843d-c5fee5a5820c.PNG)

**Comment by santcool** [comment]
需提供抓包信息，本地RPC我们这边没法调试，除非你们给这边寄设备。但是这样不如你们给我们抓包来得简单

**Comment by santcool** [comment]
经沟通，发现是调用太频繁，触发了本地的最小间隔限制，此处应尽量避免用轮询，后续可改为订阅。问题关闭
