### ISSUE TITLE
希望智能有延时关闭功能

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#1268]
**是否为新品（必填）**
 新品 

**关联的产品model**
philips.light.cbulb

**项目ID（必填）**
米家飞利浦彩光灯泡

**企业名称（必填）**
Philips

**现象（必填）**
目前在智能--新建智能 可以选择定时功能，但是没有延时关闭的功能。

**期望（必填）**
内侧用户希望可以提供延时关闭的功能。

**Comment by zanetti4** [comment]
新建智能，通用-**点击手动执行**或**室外天气发生变化**后，在选择执行结果页，都有**延时**选项。能否满足你的需求？
