### ISSUE TITLE
导航栏和状态栏问题

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#1269]
是否为新品（必填）
新品

关联的产品名称（必填）
乐秀电暖气

项目ID（必填）
无项目ID

企业名称（必填）
乐秀

环境（必填）
mac os
ios 12.3.1
10021
ui

现象（必填）

![WechatIMG259](https://user-images.githubusercontent.com/17919773/61780330-ee3cb880-ae34-11e9-920d-8ca0ec120ddf.jpeg)
![WechatIMG260](https://user-images.githubusercontent.com/17919773/61780347-f1d03f80-ae34-11e9-8789-aa2d40ea7902.jpeg)
![WechatIMG261](https://user-images.githubusercontent.com/17919773/61780717-9a7e9f00-ae35-11e9-8ae3-8344ddd6b93e.jpeg)

1.如图1所示，在进入设置页后，状态栏先是显示为黑色字体，一会儿后自动变为白色字体。
2.如图2所示，iOS端在进入更多设置页面后，安全设置一栏被导航栏遮住，Android端正常。

备注：如图3，因为要显示透明导航栏，同时自定义title样式，所以我隐藏了主页的导航栏，并在隐藏的位置添加了自定义的导航视图。

**Comment by zanetti4** [comment]
你使用的是哪个导航栏组件？

**Comment by santcool** [comment]
1.设置页面，是使用CommonSetting吗？
2.不隐藏主页的导航栏也会有此两个问题吗？

**Comment by sikaiven** [comment]
@zanetti4 导航栏还是之前的。

@santcool 
1.是用的CommonSetting，更多设置页面被导航栏遮住的原因找到了，是因为在index.js文件中，把导航栏的headerTransparent设置为true的原因，只要在这个文件设置成true，不管主页隐不隐藏导航栏，都会出现这个问题。
但是如果主页隐藏了导航栏，index.js文件中的headerTransparent不设置为true的话，退出插件，会在米家app设备列表界面的导航栏位置，闪现白条，持续1s时间。

2.在主页不隐藏导航栏，状态栏就是正常的。隐藏是指在主页不设置navigationOptions，或者将header置为null。

**Comment by santcool** [comment]
看样子问题已经解决了是吧？闪现白条是个已知问题，为了适配其他问题导致的，暂时还不太好改。

**Comment by sikaiven** [comment]
@santcool 闪现白条如果是允许的bug，那更多设置页面被导航栏遮住的问题就解决了。但是状态栏自动切换颜色的问题还没有解决。
只要在主页隐藏了导航栏，进入设置页面后，状态栏就会自动切换颜色。因为要自定义导航栏样式，所以原导航栏是必须要隐藏的。

**Comment by santcool** [comment]
状态栏的问题已修复，半小时后去首页下载并使用最新的测试app即刻
