### ISSUE TITLE
InputDialog 求助求助求助

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#127]
before issue：（不用回答）
### 是否尝试搜索issue？

--- #64 

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account]

#### 现象

无

#### 期望

1、怎么获取输入框的值？
2、怎么给输入框传一个默认值？

#### 其他的上下文/日志/截图

无

#### 尝试过的解决办法

尝试过输出onConfirm中的参数。如图
![1544409560738](https://user-images.githubusercontent.com/12531667/49707807-f2caad00-fc67-11e8-857d-ae482e6ae6fe.jpg)
输出结果如下：
 {target:520}

### 不要贴大段代码❗️

**Comment by blockdate** [comment]
IPA与文档已更新

**Comment by dzonel** [comment]
@blockdate 收到，谢谢。
