### ISSUE TITLE
被共享设备 Host.ui.openPrivacyLicense 方法调用异常

### ISSUE THREAD

**Issue by coderLM** [MiEcosystem/miot-plugin-sdk#1270]
---
**是否为新品（在售）**

**关联的产品model**
此issue关联的产品model，如“zhimi.humidifier.ca1”
实际产生影响的model：RN版本的 智米上线产品和在测试产品

**项目ID（P011902024）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（智米科技）**
智米科技

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9]
- SDK分支: [10011、10021]
- 相关模块:[Host.ui]

**现象（必填）**
Host.ui.openPrivacyLicense
设备被共享时，在被共享的账号的插件页面，调用这个方法，没有返回值，也没有cath到异常
在 设备所有者的米家账号的插件页面，调用这个方法正常。

**期望（必填）**
返回值正常，或给出异常

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46736981/61785908-3eb91380-ae3f-11e9-9004-3a5168a93269.png)

**尝试过的解决办法**
升级Api，无用

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@coderLM  共享的设备是不支持 隐私协议弹窗的，该api在 sdk 10023版本开始废弃， 请更新sdk到10023， 使用alertLegalInformationAuthorization 进行替换， 谢谢。

**Comment by coderLM** [comment]
1.从开发角度上讲，必须在用户确认隐私协议后才能请求数据，所以我们会根据隐私协议的返回结果判断是否请求数据。共享设备我们之前是显示隐私协议的。所以就导致我们的插件在新版米家上，出现异常--没有提示也没拉去数据。
2.在提这个issus之前，怀疑是方法过时，去wiki看了一下，发现并没有过时标注。
