### ISSUE TITLE
在插件中通过Host.locale.timeZone获取手机时区的问题

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#1271]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米家扫拖机器人1C/dreame.vacuum.mc1808

**现象（必填）**
1、在插件页面时退出后台，手动修改手机时区切回插件页面，此时在插件中通过Host.locale.timeZone获取的手机时区还是修改前的时区，
**期望（必填）**
可以实时获取手机当前时区

**Comment by zanetti4** [comment]
此问题出现在安卓，还是 ios 系统？

**Comment by heigaga001** [comment]
@zanetti4 两个平台都有问题，需要重新退出插件再进入才会获取到最新的时区

**Comment by zanetti4** [comment]
@santcool @lvjie0519 经安卓手机测试，确实存在此问题，请你们查看。

**Comment by lvjie0519** [comment]
@heigaga001   还有这种操作， 因为数据已经保存在了js层，不会再通知更改，退出插件再次进来应该就ok， 否则就得提供一个 方法， 插件方主动调用方法来获取时区信息。

**Comment by lvjie0519** [comment]
@heigaga001   麻烦加下微信详聊下，微信号（sky-boy-0519）

**Comment by heigaga001** [comment]
我们这边的产品希望能实现该功能，希望能帮忙安排加一个实时获取时区的接口

**Comment by lvjie0519** [comment]
@heigaga001   Android已至此， 请使用fir上最新apk进行测试， sdk选择10024分支，谢谢。

**Comment by heigaga001** [comment]
@lvjie0519 安卓测试OK
