### ISSUE TITLE
微博分享无文案

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#1272]
---
**是否为新品（必填）**
在售

**关联的产品model**
soocare.toothbrush.m1

**项目ID（必填）**
15366

**企业名称（必填）**
舒可士（深圳）科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS
- SDK分支:10022
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
微博分享设置了分享文案，如图
<img width="812" alt="image" src="https://user-images.githubusercontent.com/7885251/61842118-a3b94b80-aec9-11e9-983b-7abc983a2425.png">

IOS分享后没有文字
![image](https://user-images.githubusercontent.com/7885251/61842198-e713ba00-aec9-11e9-8259-75ba4da035dd.png)
![image](https://user-images.githubusercontent.com/7885251/61842202-e9761400-aec9-11e9-96f0-e89627ef5c7c.png)

Android分享后有文字
![image](https://user-images.githubusercontent.com/7885251/61842227-fe52a780-aec9-11e9-8224-d20526a999df.png)
![image](https://user-images.githubusercontent.com/7885251/61842270-2b06bf00-aeca-11e9-88a0-038c482c9187.png)

**期望（必填）**
Android 和 IOS 表现一致，都能按设置的文案进行分享

**Comment by santcool** [comment]
亲测，这样是可以的：
Host.ui.openShareListBar('小米智能家庭', '小米智能家庭', { uri: 'https://avatars3.githubusercontent.com/u/13726966?s=40&v=4' }, 'https://iot.mi.com/new/index.html');
请检查你的使用方式
