### ISSUE TITLE
多语言翻译问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#1274]
---
**是否为新品（必填）**
在售

**关联的产品model**
yunmi.kettle.v1\yunmi.kettle.v2\yunmi.kettle.v3\yunmi.kettle.v5

**项目ID（必填）**
米家恒温水壶

**企业名称（必填）**
云米

**环境（必填）**
- 手机系统:[eg.Android/iOS]
- SDK分支: [100021]
- 相关模块:[多语言]

**现象（必填）**
1、隐私授权弹窗，标题的多语言未翻译。比如繁体时，标题显示简体（iOS）；西班牙、俄文等语言时，显示英文（iOS和Android）
2、法律信息页面（CommonSetting里跳转的法律信息页面），标题和用户协议的翻译，中文、英文之外的语言翻译，显示为英文（iOS和Android）

**期望（必填）**
多语言正确显示

**其他的上下文/日志/截图**

![WechatIMG2811](https://user-images.githubusercontent.com/22782965/61847246-893c9d80-aedc-11e9-9435-c1cfa2e3b8f4.jpeg)
![WechatIMG2826](https://user-images.githubusercontent.com/22782965/61847247-893c9d80-aedc-11e9-8ca4-6015e42f7cf1.jpeg)
![WechatIMG2831](https://user-images.githubusercontent.com/22782965/61847248-89d53400-aedc-11e9-8a54-951ac598a2e1.jpeg)
![WechatIMG2835](https://user-images.githubusercontent.com/22782965/61847250-89d53400-aedc-11e9-8b4b-6473a4447d85.jpeg)

**Comment by zanetti4** [comment]
第一张截图：
你是指**法律信息**那四个字不对吗？繁体字也是那么写
最后两张图是一样的吗？

**Comment by santcool** [comment]
这个位子没什么问题，法律信息只和地区有关，和app语言关系不大。详询我们的产品：胡祥达
