### ISSUE TITLE
相机权限问题

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#1278]
条件：sdk10021  米家app最新

问题：小米MIX2手机，第一次使用相机，选择不再提示并拒绝，然后手动设置为允许或拒绝或询问，调用PermissionsAndroid.request一直是"never_ask_again"，PermissionsAndroid.check一直是false
期望: 能跟随手动设置结果

其他安卓手机占未发现，iOS正常

**Comment by fishle** [comment]
Android 系统的版本是多少？

**Comment by YunzzzZ** [comment]
![Screenshot_2019-07-29-09-37-22-118_com android se](https://user-images.githubusercontent.com/17631207/62017383-fefc7e00-b1e8-11e9-9475-f4f026daf314.png)

**Comment by fishle** [comment]
同样了8.0的系统测试，发现是正常的，其他的APP有类似问题吗

**Comment by YunzzzZ** [comment]
其他手机未发现此问题

**Comment by fishle** [comment]
这个应该是系统层的bug，MIX 2 上的其他APP应该也有类似的问题吧

**Comment by fishle** [comment]
设置为拒绝或者询问的时候，调用request的时候会弹框吗

**Comment by YunzzzZ** [comment]
不会，回调一直是“ never_ask_again”，不会再弹出了，手动设置是无效的，你们可以用MIX2试一下

**Comment by fishle** [comment]
系统层的bug，APP也没太多办法，等MIUI修复吧
