### ISSUE TITLE
新创建的model在米家蓝牙搜索页搜索不到（新品）

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#1279]
---
**是否为新品（必填）**
新品

**关联的产品model**
ninebot.scooter.v3

**项目ID（必填）**
小米电动滑板车1S

**企业名称（必填）**
纳恩博（北京）科技有限公司

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: iOS 12.4
- SDK分支: 10023
- 相关模块:

**现象（必填）**
米家的蓝牙搜索，搜不到该Model对应的设备。

**期望（必填）**
期望能搜索到对应设备。

**其他的上下文/日志/截图**
<img width="887" alt="Screen Shot 2019-07-25 at 6 30 15 PM" src="https://user-images.githubusercontent.com/1590420/61867650-4396c980-af0a-11e9-9f13-1962d89eb284.png">
<img width="970" alt="Screen Shot 2019-07-25 at 6 30 35 PM" src="https://user-images.githubusercontent.com/1590420/61867667-4e515e80-af0a-11e9-811e-8b4f01aaf37e.png">
<img width="946" alt="Screen Shot 2019-07-25 at 6 31 32 PM" src="https://user-images.githubusercontent.com/1590420/61867731-6e811d80-af0a-11e9-9f65-c0a87cc25d2d.png">

**Comment by pencilCool** [comment]
登录的账号需要是白名单账号，而且请注意app 登录的服务器是不是和你注册的model 的服务器是匹配的。
另外安卓能搜到吗？

**Comment by dan-huang** [comment]
创建model的时候，没有让选择服务器。

 白名单账号用app登录的服务器是中国。

安卓也搜索不到。

@pencilCool

**Comment by pencilCool** [comment]
ninebot.scooter.v3 这个设备有没有正常重置哦。

**Comment by dingshaoran** [comment]
手动添加里没有这个设备，应该是没有创建成功，请找一下您这个设备对接的产品同学，从开放平台看一下是不是缺少必要配置
