### ISSUE TITLE
Device.getBluetoothLE().disconnect(0)无效（iOS）

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#128]
### SDK 最新

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS  9.1
- 相关模块: Bluetooth

#### 现象
按返回键，调用`Package.exit()`
之后在`componentWillUnmount`中调用`Device.getBluetoothLE().disconnect(0)`，蓝牙并不会断开

- **android测试可以断开**
- **`PackageEvent.packageWillExit`监听中disconnect也是无效**
- **如果在`Package.exit()`之前调用`disconnect(0)`是可以正常断开蓝牙的**

请确认disconnect的调用时机规则是否正确

**Comment by Copypeng** [comment]
两个接口本身都没有问题。是调用 Package.exit() 后，意味着这个插件就退出了，disconnect是一个异步方法，系统还没来得及执行，相关模块就释放了。

1，推荐的做法是收到 disconnect 的回调，确保设备已经断开连接后，再调用 exit()，这样显得更专业，毕竟即使不存在释放的问题， disconnect 本身有可能会失败，放在 componentWillUnmount 中，万一失败了，插件已经退出了，保留了一个不必要的蓝牙连接，下次再进入插件都搜不到设备的广播，会造成BUG。

2，同时为了防错，新 IPA 中，我在插件退出时加入了蓝牙连接检查功能，如果插件退出时，蓝牙连接还在，会再断一次。可以试试。
