### ISSUE TITLE
米家搜索不到蓝牙设备

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/miot-plugin-sdk#1280]
**是否为新品（必填）**
  新品  

**关联的产品model**
 duoqin.safe.pbfv01

**项目ID（必填）**
 【无项目ID】

**企业名称（必填）**
深圳多亲科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 9.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
我们在米家添加设备列表中找到了我们设定的设备，点击后APP会自动搜索设备，总是找不到设备，米家这边我们需要什么设置吗，还是必须把插件包做好后上传，才能搜索到，设备端的小米相关的C文件已经刷入到设备中了，用别的APP是可以搜索到我们设备的。

**期望（必填）** 
怎么设定才能在米家中搜索到我们的产品
 

**尝试过的解决办法**
设备端刷入很多次系统还是有问题

**不要贴大段代码??**

**Comment by lvjie0519** [comment]
@bwc2019  
1、ios能否搜索到？
2、附近设备 能够扫描到您的设备吗？
3、麻烦录个视频，弄个压缩包上传到issue里面。

**Comment by bwc2019** [comment]
ios没有试过，明天我们找一个ios来试一下，用附近设备也扫描不到，我用笔记本win10下的蓝牙都能扫描到我们的设备，附件中是我刚刚录制一个视频，请参考一下
[11.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3434846/11.zip)

**Comment by bwc2019** [comment]
请问大神有帮忙看一下吗，没有头绪了！！！

**Comment by lvjie0519** [comment]
@dingshaoran   新设备需要经过什么处理才能搜索到吗？  麻烦帮忙排查下，谢谢。

**Comment by dingshaoran** [comment]
估计是固件的广播没识别，没有设备不好看出来

**Comment by bwc2019** [comment]
@dingshaoran  我们用手机自带的蓝牙扫描都可以扫描到这个设备，固件的广播是怎么开启或识别的？

**Comment by cfJand** [comment]
@bwc2019  我估计米家有扫到你们的设备，只是你们的设备满足米家的相关协议，导致被过滤掉，建议仔细阅读相关的接入文档，检查设备的接入是否正确。

**Comment by cfJand** [comment]
另外，请确认下iOSAPP 能否展示你们的设备?  @bwc2019

**Comment by cfJand** [comment]
issue 长时间未回复，close it .
