### ISSUE TITLE
灯组管理状态问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1281]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[iOS]
- SDK分支: [master]
- 相关模块:[]

**现象（必填）**
IOS手机进入灯组管理选中其中一个或多个单灯取消或添加，退出灯组管理后再进入灯组管理，灯组管理单灯勾选状态显示没改变（取消的单灯勾选状态还在，添加的单灯显示没有勾选）

**期望（必填）**
可以正常显示状态

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
我并没有复现这个问题，能提供图片或者小视频吗，最好还加上调用方法

**Comment by mirse** [comment]
[灯组管理.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3445858/default.zip)

**Comment by mirse** [comment]
具体调用方法可以查看https://github.com/MiEcosystem/miot-plugin-sdk/issues/1198

**Comment by santcool** [comment]
你们抓包看看，添加设备和进入页面分别涉及到一个网络请求，查看下网络请求是否成功了。返回什么错误

**Comment by mirse** [comment]
> 你们抓包看看，添加设备和进入页面分别涉及到一个网络请求，查看下网络请求是否成功了。返回什么错误

方便留个VX吗?具体沟通一下

**Comment by mirse** [comment]
> 你们抓包看看，添加设备和进入页面分别涉及到一个网络请求，查看下网络请求是否成功了。返回什么错误

有具体抓包过程、工具吗，ios并不太熟悉这个流程

**Comment by santcool** [comment]
使用charles 。教程：https://cloud.tencent.com/developer/article/1333172，请确认问题位置后，再打开issue，谢谢！
