### ISSUE TITLE
希望提供一个主动刷新米家设备列表的方法

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#1282]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家智能多模网关

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10024
- 相关模块:Device

**现象（必填）**
因为我们的网关支持物理按键添加子设备(意思是不需要app就可以添加子设备)，当用户物理按键手动添加子设备后，在插件内的子设备列表无法跳转到对应的子设备插件内。

ps: 原生插件其实也有这个问题，不过原生已经提供了一个 refreshWithSuccess 的方法主动刷新设备列表。

**期望（必填）**
iOS 和 Android 都可以提供一个刷新设备列表的方法

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
物理按键添加了子设备，插件端也不知道啥时去刷新列表啊

**Comment by santcool** [comment]
已完成
