### ISSUE TITLE
CommonSetting页面，添加到桌面功能

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#1283]
- IPA/APK 是否更新到最新？
已经更新到最新
- SDK 是否更新到最新？
已经更新到最新
- Check 文档了吗？
已经Check文档
- 是否尝试搜索issue？
已经尝试搜索issue
- 是否尝试搜索“常见问题”

---
**是否为新品（必填）**
新品

**关联的产品model**
此issue关联的产品model，如“lumi.curtain.hagl05”

**项目ID（必填）**
无项目ID

**企业名称（必填）**
绿米联创

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
iphone5s
- SDK分支: [eg.master/10000/...]
10011
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。
android端没有问题，iphone其他系列都没有问题，只有5s不会出现
**期望（必填）**
简单明了地描述一下期望的表现。
希望5s的主页能出现

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
请提供截图，是点击了无反应，还是safari页面里面无添加按钮，还是别的什么原因
