### ISSUE TITLE
Service.account.ID 获取不正确

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/miot-plugin-sdk#1284]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？
- 是否尝试搜索“常见问题”

---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
jiqid.mistory.ipen1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
南京机器岛科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/iOS 12.0
- SDK分支:10022
- 相关模块:Host/Service/Account

**现象（必填）**
简单明了地描述一下实际的现象。

**期望（必填）**
每次切换账号后第一次进入插件 Service.account.ID 获取到的用户ID仍然为上个用户的

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
此问题出现在哪个手机系统？我用 ios 12.3.1 测试，没有复现。

**Comment by Aphrodite123** [comment]
> 此问题出现在哪个手机系统？我用 ios 12.3.1 测试，没有复现。

我用的手机是iPhonex，版本12.0，不知道你操作步骤是怎样的，有可能步骤不一样

**Comment by zanetti4** [comment]
进入插件获取 id，退出插件，退出当前账号。登录另一个账号，进入插件获取 id。
你是这么操作的吗？

**Comment by Aphrodite123** [comment]
> 进入插件获取 id，退出插件，退出当前账号。登录另一个账号，进入插件获取 id。
> 你是这么操作的吗？

步骤是对的，多测试还不能复现？米家版本用的哪个？用的是com.xiaomi.demo？

**Comment by Aphrodite123** [comment]
> 进入插件获取 id，退出插件，退出当前账号。登录另一个账号，进入插件获取 id。
> 你是这么操作的吗？

补充一下，目前我是先把插件提交到平台，然后通过白名单账号测试的，而开发dedug调试情况下并没有出现这个问题

**Comment by Aphrodite123** [comment]
> 进入插件获取 id，退出插件，退出当前账号。登录另一个账号，进入插件获取 id。
> 你是这么操作的吗？

还有安卓机上面同样的操作步骤第一次获取到 accountID 为 0

**Comment by Aphrodite123** [comment]
> 进入插件获取 id，退出插件，退出当前账号。登录另一个账号，进入插件获取 id。
> 你是这么操作的吗？

我直接create 一个demo测试了一把
![IMG_0440](https://user-images.githubusercontent.com/17521937/62019488-a382be00-b1f1-11e9-8198-3588d99dda2b.PNG)
![IMG_0441](https://user-images.githubusercontent.com/17521937/62019490-a382be00-b1f1-11e9-8c80-8941c758acdf.PNG)
图一为第一次进入accountID为1318724110，第二次进入，如图二为1342417719 这个才是我自己的账号

**Comment by zanetti4** [comment]
我是用 beta 版本测试的

**Comment by Aphrodite123** [comment]
> 我是用 beta 版本测试的

方便把你的米家beta版本发我试下，另外插件是需要上传到控制平台，不能连接本地调试

**Comment by zanetti4** [comment]
https://fir.im/mijiadevelopment
从这里下载到的应该就是 beta 版本，你可以试一下。

**Comment by Aphrodite123** [comment]
> https://fir.im/mijiadevelopment
> 从这里下载到的应该就是 beta 版本，你可以试一下。

我用了这个版本试了以后效果还是一样的，录了视频，可以加个微信什么的，我发你看吧

**Comment by fishle** [comment]
https://pan.mioffice.cn:443/#/link/AC14EDE28CD81F64646522B23898AB68
试试这个包

**Comment by Aphrodite123** [comment]
> https://pan.mioffice.cn:443/#/link/AC14EDE28CD81F64646522B23898AB68
> 试试这个包

这个包第一次的话会一直停留在加载页面，进不了插件里头，第二次才正常进去

**Comment by fishle** [comment]
第一次是指安装后第一次打开吗？是覆盖安装还是卸载安装？
另外切换账号后account.id每次都能拿到正确的吗？

**Comment by Aphrodite123** [comment]
> 第一次是指安装后第一次打开吗？是覆盖安装还是卸载安装？
> 另外切换账号后account.id每次都能拿到正确的吗？

切换账号后第一次打开插件出现一直等待界面，只能退出第二次进去才能正常，我是卸载安装的

**Comment by fishle** [comment]
这边一直没办法复现这个问题呢，你加下我微信：fishle123

**Comment by fishle** [comment]
Android如果是为0，可以提示退出重进，但iOS这边还需要 @santcool 看一下

**Comment by santcool** [comment]
iOS已修复。
