### ISSUE TITLE
(Android) 切换国家后，设备未清除，且进入后蓝牙连接读不到任何数据

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#1286]
是否为新品（必填）
否

关联的产品model
ninebot.scooter.v1

项目ID（必填）
米家滑板车

企业名称（必填）
纳恩博（北京）科技有限公司

环境（必填）

电脑操作系统: Mac OS
手机系统: Android 9.0
SDK分支: 10023
相关模块:
现象（必填）
(Android) 切换国家后，设备未清除，且进入后蓝牙连接读不到任何数据。
而iOS切换国家后，设备会清除掉，重新注册添加后蓝牙通讯正常。

期望（必填）
Android行为和iOS一致，切换国家后，设备会清除掉，重新注册添加后蓝牙通讯正常。

**Comment by zanetti4** [comment]
@dingshaoran 我用安卓手机测试，切换国家后设备列表有明显变化。请你查看

**Comment by dingshaoran** [comment]
帮忙提供一个测试账号，没有借到测试设备

**Comment by dingshaoran** [comment]
我在894158105的测试账号上绑定了一个ninebot.scooter.v1 设备，切换到德国未出现设备未清除的问题。app 版本是最新上线的代码，请更新最新版本试试 https://pan.mioffice.cn/#/link/053FD1BDAF677512BED5B9ED5295DD95/SmartHome_master_MiAppStore_62921_5.5.48_655_release.apk

**Comment by cfJand** [comment]
暂时没有反馈，关掉此issue。
