### ISSUE TITLE
大型酒店应用，APP里面的家庭房间管理-新建家庭功能，最多能创建多少个家，创建2000个家APP是否支持，一个账号能否支持5000设备量？

### ISSUE THREAD

**Issue by fengfeng0328** [MiEcosystem/miot-plugin-sdk#1287]
公司：深圳市安信可科技有限公司

问题：大型酒店应用，APP里面的家庭房间管理-新建家庭功能，最多能创建多少个家，创建2000个家APP是否支持，一个账号能否支持5000设备量？

**Comment by zanetti4** [comment]
@pencilCool @dingshaoran 这个问题你们是否了解？

**Comment by pencilCool** [comment]
同一账号支持1000个设备，10个家庭500个房间
