### ISSUE TITLE
米家Android设置进入的二级界面顶部title字体大小不一，样式不整齐

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#1288]
**是否为新品（必填）**
 新品 or 在售

**关联的产品model**

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android APIlevel10023 版本米家，设置界面-进入到二级界面（例如：定时开关、位置管理、设备共享、法律信息等等）顶部title的字体大小和样式都不统一

**期望（必填）**
有统一的样式体验

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
通用设置的二级页面，除了「更多设置」由SDK开发，其余都是跳转到APP的原生页面，所以需要推动APP端做统一。
@zanetti4 @Woody2016
