### ISSUE TITLE
RN新框架Android debug包切换海外版服务器 没有显示开发者选项 不能进行海外服务器测试

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1289]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

是否为新品（必填）
不是

关联的产品名称（必填）
“米家饭煲类”

项目ID（必填）
项目ID

企业名称（必填）
上海纯米电子科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 9.00]
SDK分支: [10010]
相关模块:[UI]
现象（必填）
RN新框架Android debug包切换海外版服务器 没有显示开发者调试 不能进行海外服务器测试

期望（必填）
RN新框架Android debug包切换海外版服务器 能进行海外服务器测试

**Comment by lvjie0519** [comment]
@joyami  
1、ios是否有相同问题？
2、Android  使用  rn-debug  过滤下日志，看看log输出或core进程看看网络请求的log日志，判断该账号是否为开发者账号？

**Comment by joyami** [comment]
@lvjie0519
iOS没有问题 可以切换到海外
Android的是开发者账号  
```
["code":0, "message":"ok", "result": false]
```

**Comment by lvjie0519** [comment]
@joyami   目前在安排服务端支持， 请耐心等待，有消息及时通知。

**Comment by lvjie0519** [comment]
@joyami   我这边查看已支持。
