### ISSUE TITLE
retrievePeripheralsForIOS(…UUIDs)使用疑问

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#129]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1
- 相关模块: Bluetooth

#### 现象

疑问1：如何调用？

尝试过通过Bluetooth、Device.getBluetoothLE()调用

疑问2：传什么参数？

尝试过传入设备的serviceUUID，retrievePeripheralsForIOS({services:[设备的serviceUUID]})

疑问3：返回值在哪里接收？

尝试过retrievePeripheralsForIOS({services:[设备的serviceUUID]}).then((data)>{})

都有问题，建议添加一个示例

**Comment by Copypeng** [comment]
等待 @laohuang88 更新js sdk即可。

**Comment by Handby** [comment]
ok
