### ISSUE TITLE
ScrollView 和里面的内容点击有冲突

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#1290]
是否为新品（必填）
新品

关联的产品model
miaomiaoce.thermo.t10

项目ID（必填）
913

企业名称（必填）
秒秒测

环境（必填）

电脑操作系统:[eg.Windows/Mac OS/Linux]
手机系统:[eg.Android 8.1/iOS 11.0]
SDK分支: [eg.master/10022/...]
相关模块:[eg.Host/Service/Account]
现象（必填）
ScrollView 和里面的内容点击有冲突，如何解决，我看了下米家体脂秤很完美的解决了这个问题，想请教一下

期望（必填）

**Comment by zanetti4** [comment]
此问题出现在哪个手机系统？我用安卓手机测试 com.xiaomi.demo/Main/tutorial/TitleBarDemo.js，滑动屏幕和点击按钮不冲突。你可以看一下这个演示文件。

**Comment by Android-yzhang** [comment]
我是在scrollview中嵌套了svg，点击使用svg画的点，无反应，都被scrollview的touchmove响应

**Comment by zanetti4** [comment]
按照你说的我测了一下，点击 svg 元素和滚动视图不冲突。
`<ScrollView>
                <Svg
                    height="1000"
                    width="100"
                >
                    <Circle
                        cx="50%"
                        cy="50"
                        r="50"
                        fill="red"
                        onPress={() => console.log('Press on Circle')}
                    />
                </Svg>
            </ScrollView>`
这个问题涉及的是什么系统？是不是因为你画的点太小了，所以无响应？

**Comment by Android-yzhang** [comment]
在各处打log后发现，好想却是是因为点太小了，周围还有svg画的线，点击事件被画线响应了
