### ISSUE TITLE
the device is not initialized

### ISSUE THREAD

**Issue by bwc2019** [MiEcosystem/miot-plugin-sdk#1291]
**是否为新品（必填）**
  新品  

**关联的产品model**
 duoqin.safe.pbfv01

**项目ID（必填）**
 【无项目ID】

**企业名称（必填）**
深圳多亲科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 9.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
运行提供蓝牙demo，报设备没有初始化，怎么进行初始化,我看到类似issues有提到设置uuid ，请问在哪里设置，目前米家没办法添加扫描到我们设备，也在等待大神指导，谢谢！

**期望（必填）** 
![300](https://user-images.githubusercontent.com/52914317/61939703-6ab2d100-afc6-11e9-83ca-8e8d680b7e89.jpg)
<img width="803" alt="301" src="https://user-images.githubusercontent.com/52914317/61939710-70101b80-afc6-11e9-8d0d-69002afc3afa.png">

 

**尝试过的解决办法**
运行很多次都是类似错误！

**不要贴大段代码??**

**Comment by bwc2019** [comment]
@zanetti4  大神还能帮忙分析一下，是什么原因？？？

**Comment by lvjie0519** [comment]
@bwc2019 你运行 蓝牙demo 目的是？  可以尝试先运行  com.xiaomi.demo

**Comment by bwc2019** [comment]
com.xiaomi.demo 运行成功，其中有一个错误，我把那部分代码屏蔽就可以了，运行蓝牙demo,是因为我们设备也是通过蓝牙接入的，

**Comment by lvjie0519** [comment]
@bwc2019   如上图错误， 估计是 XiaomiBle.js文件， 看18行， 将18行移到构造函数中执行，试试，

**Comment by cfJand** [comment]
麻烦 @lvjie0519  看看。

**Comment by lvjie0519** [comment]
issue 不活跃， 暂且关闭，如有问题，在reopen。
