### ISSUE TITLE
设备配网时，vivo Xplya6在选择路由器界面 搜不到路由器，其他手机均可正常搜到路由器，配网正常

### ISSUE THREAD

**Issue by maxuesong1990** [MiEcosystem/miot-plugin-sdk#1294]
是否为新品（必填）
新品

关联的产品model
jyaiot.cm.ccj01

项目ID（必填）
1251

企业名称（必填）
九阳

环境（必填）

手机系统:[Android 7.1.1]
手机机型：vivo Xplya6
vivo ROM:Funtouch OS_3.1

现象（必填）
设备配网时，vivo Xplya6在选择路由器界面 搜不到路由器，其他手机均可正常搜到路由器，配网正常

期望（必填）
vivo Xplya6可正常搜到路由器，配网正常

其他的上下文/日志/截图
手机系统照片：
![1](https://user-images.githubusercontent.com/42369212/62015492-a1fbca80-b1de-11e9-8686-5531e4126dbe.jpg)
![3](https://user-images.githubusercontent.com/42369212/62015493-a2946100-b1de-11e9-9ea5-89a65993cf78.jpg)
![2](https://user-images.githubusercontent.com/42369212/62015494-a2946100-b1de-11e9-9c19-cbfa4513aeaa.jpg)

**Comment by fishle** [comment]
手机的WiFi界面能显示这个路由器吗

**Comment by maxuesong1990** [comment]
> 手机的WiFi界面能显示这个路由器吗

手机WIFI界面是可以显示的，也可以连上WIFI ，但是到米家app上之后就搜不到路由器了

**Comment by fishle** [comment]
可以手动下拉刷新一下试试看

**Comment by maxuesong1990** [comment]
> 可以手动下拉刷新一下试试看

刷新之后也是空白的。如果可以的话，可以视频给你

**Comment by fishle** [comment]
你加下我的微信：fishle123

**Comment by lvjie0519** [comment]
@maxuesong1990   问题解决了吗？ 如解决，请说明下解决方案并关闭issue，谢谢。

**Comment by maxuesong1990** [comment]
感谢各位，问题已经解决，是因为没有设置白名单权限的问题导致
