### ISSUE TITLE
iOS调试提示此model还未上线或者白名单测试

### ISSUE THREAD

**Issue by twinkle66** [MiEcosystem/miot-plugin-sdk#1295]
**是否为新品（必填）**
新品

**关联的产品model**
huohe.lock.m1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
北京火河科技有限公司

**环境（必填）**
- 电脑操作系统: Mac OS 10.14.4
- 手机系统: iOS 12.2
- SDK分支: master
- 相关模块: 开发者设置-直接调试

**现象（必填）**
在开发者设置那里调试新建的扩展程序提示“此model还未上线或者白名单测试，请检查后重试”，安卓是可以调试的，就是iOS不行。package、model和IP都是对的，com.xiaomi.demo是可以跑通的。

**期望（必填）**
希望可以跟安卓一样可以调试，不然连代码都写不了。

**其他的上下文/日志/截图**
![IMG_0029](https://user-images.githubusercontent.com/12607511/62018628-10945480-b1ee-11e9-894d-011986ec73d7.PNG)
![10_42_57__07_29_2019](https://user-images.githubusercontent.com/12607511/62018631-15f19f00-b1ee-11e9-9148-0744d062b8e9.jpg)
![10_44_43__07_29_2019](https://user-images.githubusercontent.com/12607511/62018633-19852600-b1ee-11e9-9b1b-29f1b90489c7.jpg)

**Comment by santcool** [comment]
已处理。请10分钟左右，清除缓存后重试

**Comment by twinkle66** [comment]
还是不可以呢
