### ISSUE TITLE
点击进入插件提示客户端版本过低,已经更新到最新版本,其他插件正常

### ISSUE THREAD

**Issue by TianGuisen** [MiEcosystem/miot-plugin-sdk#1296]
model:090615.switch.switch04
测试中,未上线.
![image](https://user-images.githubusercontent.com/19662707/62019139-1ee37000-b1f0-11e9-8966-19d02ec83074.png)
![image](https://user-images.githubusercontent.com/19662707/62019144-21de6080-b1f0-11e9-945e-5d8b2633077a.png)

**Comment by zanetti4** [comment]
此问题只涉及到安卓系统吗？

**Comment by TianGuisen** [comment]
> 此问题只涉及到安卓系统吗？

ios也不行
![image](https://user-images.githubusercontent.com/19662707/62019696-9d411180-b1f2-11e9-838a-f9be8144570c.png)

**Comment by santcool** [comment]
请查看[常见问题](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
