### ISSUE TITLE
模组启动不正常

### ISSUE THREAD

**Issue by zouzhe1** [MiEcosystem/miot-plugin-sdk#1297]
**是否为新品（必填）**
 新品

**环境（必填）**
- 相关模块:ESP-WROOM-32D

**现象（必填）**
启动log串口显示如下图片信息

**其他的上下文/日志/截图**
![aa1](https://user-images.githubusercontent.com/13077962/62022958-3119da00-b201-11e9-828b-53b57b7b12f9.png)

**尝试过的解决办法**
尝试过哪些操作？重启好几次

**Comment by zanetti4** [comment]
这个问题请你找对接的嵌入式工程师咨询，这里我就关掉了。

**Comment by Woody2016** [comment]
这里是RN插件的问题提问及处理场所
嵌入式模组问题，请去这里提问：https://github.com/MiEcosystem/MIoT-ESP32-SDK

**Comment by zouzhe1** [comment]
@zanetti4 @Woody2016 怎么找到你们嵌入式的人？
https://github.com/MiEcosystem/MIoT-ESP32-SDK这个我打开显示404，是不是不对外开放？？
