### ISSUE TITLE
自主品牌新品无法在添加设备中找到对应产品

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#1299]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**项目ID（必填）**
无项目ID

**产品名称/Model（必填）**
追觅无线吸尘器/dreame.cleaner.p0702

**现象（必填）**
无法在添加设备页面找到该产品，后台已添加该设备并配置图片，在Android和IOS上均无法找到该设备

**期望（必填）**
能在添加设备页面找到该产品

**Comment by santcool** [comment]
请查看[常见问题](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by heigaga001** [comment]
@santcool 常见问题中未找到原因，目前已用DEMO代码打包上传了，手机上的还是无法看到该设备，账号是开发账号，同时也加入了白名单
