### ISSUE TITLE
callMethod的具体API文档在哪里呢

### ISSUE THREAD

**Issue by flztsxsy** [MiEcosystem/miot-plugin-sdk#1300]
**是否为新品（必填）**
新品 

**关联的产品model**
miaomiaoce.blanket.s01

**项目ID（必填）**
无

**企业名称（必填）**
秒秒测科技（北京）有限公司

**环境（必填）**
- 电脑操作系统:[Windows7]
- 手机系统:[Android 8.0]
- SDK分支: [10022]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Device.getDeviceWifi().callMethod('method_name', params)
.then(res => {//here is the success result})
 .catch(err => {//error happened})
这儿的'method_name'都有哪些呢？插件设备模块中提到具体使用请参考API文档，这个文档在哪里呢？

**期望（必填）**
这个具体的API文档在哪里能够找到呢，以便知道'method_name'都有哪些

**Comment by zanetti4** [comment]
@lvjie0519 [文档](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/06-%E6%8F%92%E4%BB%B6%E8%AE%BE%E5%A4%87%E6%A8%A1%E5%9D%97#/module_miot/Device--module.exports.IDeviceWifi+callMethod)中没有具体列出方法名都有哪些，还是说是由开发者自己定义的？

**Comment by fishle** [comment]
method_name是设备自己定义的

**Comment by flztsxsy** [comment]
设备自己定义，那是应该在哪定义啊？是随意定义还是需要遵循一定的规范呢？另外get_prop,和getProps是特定的关键字吗？

**Comment by flztsxsy** [comment]
比如说在开发者平台上配置的功能定义里面，配置了属性on,那么callMethod的method_name是不是就是set_on和get_on呢（分别对应设置该属性值，获取该属性值）？我的意思是说，set_和get_是特定的关键字前缀么？还是说这个method_name要在什么地方配置？
![image](https://user-images.githubusercontent.com/49407658/62046959-cfc32c80-b23b-11e9-9396-73eaf9d0c3d0.png)

**Comment by fishle** [comment]
这里支持的局域网内的RPC调用，设备那边要和手机在同一个局域网内，设备监听54321端口来接受手机端通过callMethond发起的RPC调用，这里使用的是udp

**Comment by flztsxsy** [comment]
![image](https://user-images.githubusercontent.com/49407658/62049721-698dd800-b242-11e9-9e94-a0c129b68f5c.png)
![image](https://user-images.githubusercontent.com/49407658/62050331-a0b0b900-b243-11e9-9caa-a7d34fbe1c25.png)

除了上图中的内容，在开发者平台上没有找到其他相关介绍。这个callMethond是设备自定义的，那是需要在哪定义或者配置呢？是在功能定义中配置还是在固件开发中配置，还是在其他什么地方配置呢？
![image](https://user-images.githubusercontent.com/49407658/62050483-e1103700-b243-11e9-9b98-79a10f9b4a85.png)

**Comment by fishle** [comment]
这个是跟设备通信，肯定是要固件支持的

**Comment by flztsxsy** [comment]
好的，谢谢。还有一个问题，我看 loadProperties(...propNames) 内部直接调用了callMethod("get_prop", propNames)，也就是说get_prop应该是固定的应该满足的规范吧。不过现在存在一个新老协议映射，我们应该用哪个呢，还是两个都可以？
![image](https://user-images.githubusercontent.com/49407658/62094081-67616300-b2ae-11e9-9fd1-2a3368e4fc79.png)
