### ISSUE TITLE
红米note 4X手机扩展程序无法启动

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1301]
**是否为新品（必填）**
新品

**关联的产品model**
xiaoxun.watch.SW560

**企业名称（必填）**
上海小寻科技有限公司

**环境（必填）**
- 手机系统:[Android 7.0   MIUI Global 10.2]

**现象（必填）**
红米note 4X手机在米家设备列表中点击绑定的设备，一直提示“扩展程序启动失败，请稍后再试”，其他手机正常

**期望（必填）**
正常启动插件

**其他的上下文/日志/截图**
adb log 文件：
[mihome_android7.0_miui_global_10.2.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3442255/mihome_android7.0_miui_global_10.2.zip)

**Comment by fishle** [comment]
插件下载失败了，试试其他的插件能打开吗，另外确认下网络和iOS能不能打开

**Comment by heping99** [comment]
米家更新到最新版本就正常了，非常抱歉，这个问题可以关掉。
