### ISSUE TITLE
安卓检测不到版本更新

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#1303]
您好，
      我昨天发布了新版本，iOS都有检测到新版本，但是安卓版本一直检测不到新版本，不知道怎么回事，能帮忙看看吗，谢谢！
      models:trios1.bleshoes.v02

**Comment by zanetti4** [comment]
能按照模版提供更多信息吗？比如：分支、安卓版本……

**Comment by caojunhua** [comment]
可以了
