### ISSUE TITLE
iOS 飞行模式下，访问 Device.getSubDevices() 必现crash

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#1304]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家智能多模网关

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10024
- 相关模块:Device

**现象（必填）**
iOS 飞行模式下，访问 Device.getSubDevices() 必现 crash（android 不会）

**期望（必填）**
iOS 飞行模式下，访问 Device.getSubDevices() 不会 crash

**其他的上下文/日志/截图**
![WechatIMG78](https://user-images.githubusercontent.com/8938524/62119963-4a02b800-b2f3-11e9-8ed4-6a882f75eaf4.png)

**Comment by zanetti4** [comment]
我用 ios 测试，先在正常模式下调用 Device.getSubDevices()，能走进 then。此时打开飞行模式，切回插件，会报红屏错误，如果点击 dismiss，再调用 Device.getSubDevices()，会走进 catch。
在飞行模式下 reload，会报红屏错误。
没有看到你截图的界面。

**Comment by santcool** [comment]
@zanetti4 你是本地联调吗？如果是本地联调，肯定报红屏错误，因为没法和node 服务器通讯了

**Comment by zanetti4** [comment]
是本地联调

**Comment by santcool** [comment]
老版本才有问题，已修复
