### ISSUE TITLE
新版WiFi模组的插件是如何和设备进行通信的

### ISSUE THREAD

**Issue by flztsxsy** [MiEcosystem/miot-plugin-sdk#1306]
是否为新品（必填）
新品

关联的产品model
miaomiaoce.blanket.s01

项目ID（必填）
无

企业名称（必填）
秒秒测科技（北京）有限公司

环境（必填）

电脑操作系统:[Windows7]
手机系统:[Android 8.0]
SDK分支: [10022]
相关模块:[eg.Host/Service/Account]

**现象（必填）**
新版WiFi模组的插件是如何和设备进行通信的？Device.getDeviceWifi().callMethod('method_name', params)如何自定义，需要满足一定的规范吗？具体使用方法是怎样的？ 

**期望（必填）**
希望知道新版插件Device.getDeviceWifi().callMethod('method_name', params)在哪定义的，如何定义的，需要满足什么规范。以便完成和设备的通信。另外，我就这个问题提过一个issue，还没有弄明白就给我close了。说让我自己去开发者平台看，我把开发引导从头到尾找遍了，也没有找到有用的介绍。你们有技术支持群吗？这样提issue沟通效率太低了

**Comment by zanetti4** [comment]
#1300

**Comment by zanetti4** [comment]
我们有一个微信群：米家扩展程序统一框架讨论组，我先加你好友，再把你拉进群里。你的微信号是什么？

**Comment by mirse** [comment]
> 我们有一个微信群：米家扩展程序统一框架讨论组，我先加你好友，再把你拉进群里。你的微信号是什么？

还有位置吗？

**Comment by flztsxsy** [comment]
好的，我的微信号是flztsxsy

**Comment by flztsxsy** [comment]
你好，什么时候可以拉进群呢

**Comment by zanetti4** [comment]
已添加

**Comment by flztsxsy** [comment]
好的，谢谢

**Comment by zanetti4** [comment]
@mirse 有贵司其他开发者在群里吗？一个公司的开发者人数有限制

**Comment by mirse** [comment]
> @mirse 有贵司其他开发者在群里吗？一个公司的开发者人数有限制

应该没有，v: wdz951022

**Comment by zanetti4** [comment]
微信已添加你为好友

**Comment by zanetti4** [comment]
@flztsxsy 如果此问题已解决，请关闭 issue

**Comment by EdifierX** [comment]
@zanetti4 你好,请问目前还能加进去吗,v:jacketEdifier

**Comment by EdifierX** [comment]
@zanetti4 你好,我主要弄不清楚,是用Device的APi还是用spec协议里面的和设备通信.我用Device是可以发送接收,但是spec是不行的.

**Comment by zanetti4** [comment]
已将你加入群聊， #1351 已有工程师回复了，请查看。

**Comment by Woody2016** [comment]
此问题长时间未响应

如果开发者还有疑问，可去小米开发者平台提工单

此issue先close
