### ISSUE TITLE
Device.checkIsHomeKitDevice 不同iOS手机返回结果不一样

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#1307]
---
**是否为新品（必填）**
新品

**关联的产品model**
lumi.gateway.mgl03

**项目ID（必填）**
22538

**企业名称（必填）**
深圳市绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3]
- SDK分支: [10024]
- 相关模块:[Device]

**现象（必填）**

同一多模网关在不同的iOS手机上Device.checkIsHomeKitDevice()方法返回的结果不一样，se和8上面返回true, x上面返回false （APP 2450）

**期望（必填）**
同一多模网关在任何设备上返回一致的结果

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
并没有复现，请保证包/账号一致并清除缓存试试。如果还不行，请提供service/appconfig抓包结果：其中，name为homekit_config_preview或者homekit_config

**Comment by santcool** [comment]
已私下沟通解决，因环境不对所导致
