### ISSUE TITLE
固件升级界面UI不一致

### ISSUE THREAD

**Issue by lufengleo** [MiEcosystem/miot-plugin-sdk#1308]
---
**是否为新品（必填）**
新品

**关联的产品model**
viomi.fridge.m1

**项目ID（必填）**
TBD

**企业名称（必填）**
佛山市云米电器科技有限公司

**环境（必填）**
- 电脑操作系统:Windows/Mac OS
- 手机系统:Android 8.1/iOS 11.0
- SDK分支:.master/10021/
- 相关模块:miot/ui/CommonSetting

**现象（必填）**
1、	断网进入固件升级，安卓页面一直转圈圈，ios页面提示失败
2、	断网，进入插件使用帮助页面，安卓端显示网页无法打开，ios页面显示空白没有任何提示

**期望（必填）**
IOS和Android能统一UI而且有比较美观的效果

**其他的上下文/日志/截图**
插件通用设置进去即可看到

**尝试过的解决办法**
换了不同的手机尝试一样

**Comment by santcool** [comment]
第一个问题，iOS勿需修改，请 @fishle 修改为提示失败
第二个问题，iOS增加了一个加载失败，请重试的错误提示。

**Comment by fishle** [comment]
问题1--Android已修改，可用这个apk看一下效果：
https://pan.mioffice.cn:443/#/link/468B769849B720DF5AD0CA560FA901A4

**Comment by lufengleo** [comment]
> 第一个问题，iOS勿需修改，请 @fishle 修改为提示失败
> 第二个问题，iOS增加了一个加载失败，请重试的错误提示。

第二个问题用SDK10023验证不通过@santcool@ @fishle  Android网络加载失败界面显示太不美观，IOS依旧空白一块

**Comment by santcool** [comment]
用最新的包去试试？

**Comment by fishle** [comment]
“Android网络加载失败界面显示太不美观”----设计师已经在排期优化了
