### ISSUE TITLE
ChoiceDialog 单选弹窗打包后左边的选中箭头在iPhone x/xr上会变形

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#1309]
---
**是否为新品（必填）**
新品

**关联的产品model**
lumi.gateway.mgl03

**项目ID（必填）**
22538

**企业名称（必填）**
深圳市绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.iOS 12.3]
- SDK分支: [eg.master/10024/...]
- 相关模块:[eg.miot/ui/Dialog/ChoiceDialog]

**现象（必填）**
ChoiceDialog 单选弹窗打包到线上后左边的选中箭头在iPhone x/xr上会变形，开发调试的时候没有问题

**期望（必填）**
ChoiceDialog 单选弹窗打包到线上后左边的选中箭头在iPhone x/xr上不变形

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
能提供箭头变形的截图吗？

**Comment by qinliduan** [comment]
> 能提供箭头变形的截图吗？

![IMG_1330](https://user-images.githubusercontent.com/41932871/62181993-afa08400-b387-11e9-8649-9168e811c822.PNG)

**Comment by qinliduan** [comment]
icon类定义的样式 {
    width: 10,
    height: 10,
  }
select_icon图片的宽是6，高是10
比例不对吧？

**Comment by LiuMengzhou** [comment]
> icon类定义的样式 {
> width: 10,
> height: 10,
> }
> select_icon图片的宽是6，高是10
> 比例不对吧？

 这个数值你是怎么知道的？

**Comment by qinliduan** [comment]
> > icon类定义的样式 {
> > width: 10,
> > height: 10,
> > }
> > select_icon图片的宽是6，高是10
> > 比例不对吧？
> 
> 这个数值你是怎么知道的？

看图片的大小啊

**Comment by LiuMengzhou** [comment]
这个应该解决了。。在SDK_10024上 重新打包试试呢

**Comment by wanggoingdown** [comment]
@LiuMengzhou 我在SDK_10024上打的包，ios和android效果分别是这样的，ios显得变形，android显得很小
<img width="1060" alt="WeChatb169e4a9763570eb099a52dc3588e03d" src="https://user-images.githubusercontent.com/10232787/62913425-90a9e500-bdbe-11e9-8a2c-5e2a223f07b9.png">

**Comment by heigaga001** [comment]
同样碰到这个问题，在SDK_10024分支打包后使用IOS最新版并未能解决图片被拉伸的问题，实际Debug时就算是10023版本，也没有这个问题，自定义图片使用的和SDK中的select_icon@2x.png 、select_icon@3x.png 同样的尺寸，使用过默认选择图片，同样存在这个问题

**Comment by LiuMengzhou** [comment]
> 同样碰到这个问题，在SDK_10024分支打包后使用IOS最新版并未能解决图片被拉伸的问题，实际Debug时就算是10023版本，也没有这个问题，自定义图片使用的和SDK中的[select_icon@2x.png](mailto:select_icon@2x.png) 、[select_icon@3x.png](mailto:select_icon@3x.png) 同样的尺寸，使用过默认选择图片，同样存在这个问题
> 本地打包版本的min_sdk_api_level是10024时，在后台上传publish.mpkg文件，服务端是否就是在10024版本的基础上进行打包

说实话，可以重新组织一下这段话吗，没怎么看懂

**Comment by LiuMengzhou** [comment]
@heigaga001 @wanggoingdown @qinliduan 
我这边看后台，改动过后的SDK已经发布了。

所以，你们拉取到插件之后，先等sdk静默更新，然后退出插件重新进入试试看。

**Comment by heigaga001** [comment]
@LiuMengzhou 插件版本是否需要在SDK_10024分支上打包

**Comment by LiuMengzhou** [comment]
是的

**Comment by heigaga001** [comment]
![release版本单选弹窗](https://user-images.githubusercontent.com/4754633/63068495-e6f56000-bf45-11e9-8631-cc9ae6c0dbc7.jpg)
![Debug版本单选弹窗](https://user-images.githubusercontent.com/4754633/63068504-ec52aa80-bf45-11e9-83ab-52bf4c26e084.jpg)
手机型号7P，SDK版本10024，第一张是release版本的弹窗显示，第二张是Debug版本的弹窗显示
自定义图片是以下两张图片
![select_icon@2x](https://user-images.githubusercontent.com/4754633/63068611-6420d500-bf46-11e9-8d93-285685bcceab.png)
![select_icon@3x](https://user-images.githubusercontent.com/4754633/63068615-68e58900-bf46-11e9-954a-774f10e7c391.png)
