### ISSUE TITLE
判断设备连接状态疑问

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#131]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account] Device

#### 现象

先连接蓝牙，之后开发板和手机蓝牙断开连接，但是通过
`
const bluetooth = Device.getBluetoothLE();
console.log('deviceIsConnected', bluetooth.isConnected);
`
检查蓝牙连接状态，仍然为true

#### 期望

期望为false

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by edwardair** [comment]
我这边是去监听通知，但是收不到回调，你直接去检测bluetooth.isConnected应该是同理问题 see #109

**Comment by dzonel** [comment]
@edwardair 是的，看到过 #109 ，我这边也有监听，但是收不到消息。我是执行蓝牙操作前，直接用bluetooth.isConnected判断下是否已经连接，比较方便。但目前看，连过一次后，一直是true。还遇到了 #122 的问题。

**Comment by dingshaoran** [comment]
android 更新 sdk，修复此问题

**Comment by dzonel** [comment]
@laohuang88 您好，这比是iPhone 6   iOS 12.0.1，还是存在这个问题的， @dingshaoran 说的android修复了。
