### ISSUE TITLE
米家插件定时开关模块，接到新需求，需要米家开发同学协助提供接口更改

### ISSUE THREAD

**Issue by tangkun92** [MiEcosystem/miot-plugin-sdk#1310]
关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[ 苹果。 安卓]
SDK分支: [master]
相关模块:[ Service.scene.loadScenes(Device.deviceID, SceneType.Timer)]

需求
产品提供的需求：
1.默认晚9点到早6点，也可自定义设置时间;

现象（必填）
1.添加时间段定时的时候无默认时间晚9点到早6点，
2.设置定时时间段明天，若当前时间到了后天，该昨天的定时条目不会关闭。

期望（必填）
1.实现需求第一条：时间段定时有默认晚9点到早6点，也可自定义设置时间;
2.设置定时时间段明天，若当前时间到了后天，当前时间之前设置的定时条目会自动关闭状态

其他的上下文/日志/截图
![WechatIMG1](https://user-images.githubusercontent.com/16345833/62182067-ebd3e480-b387-11e9-8541-b4f377ac2947.jpeg)
![WechatIMG2](https://user-images.githubusercontent.com/16345833/62182109-06a65900-b388-11e9-9e59-5d710dcfcbe8.jpeg)
![WechatIMG3](https://user-images.githubusercontent.com/16345833/62182118-0d34d080-b388-11e9-907d-723d49ba1599.jpeg)
![WechatIMG4](https://user-images.githubusercontent.com/16345833/62182135-19b92900-b388-11e9-9122-a8a53f88cd48.jpeg)

**Comment by santcool** [comment]
米家PM推荐将此需求配置成功能，不依靠定时实现。
