### ISSUE TITLE
开发工具

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1311]
**现象（必填）**
你们开发miot-sdk是用vscode还是webstrom？
如果使用vscode可以告知装了什么好用的插件嘛？
是否使用了代码美化插件？
代码智能提示使用什么插件？
能否给一份vscode的setting.json的配置信息

**Comment by zanetti4** [comment]
[开发简介](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E5%BC%80%E5%8F%91%E7%AE%80%E4%BB%8B#/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B7)里有关于开发工具的介绍
