### ISSUE TITLE
iOS定时时间段无法设置第二天

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/miot-plugin-sdk#1314]
**是否为新品（必填）**
在售

**关联的产品model**
yeelink.light.lamp1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
青岛亿联客

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3]
- SDK分支: [master]
- 相关模块:[定时]

**现象（必填）**
iOS定时开关,设置时间段定时,第二个时间无法选择第二天的时间,android端可以选择第二天时间

**期望（必填）**
iOS/Android一致

**其他的上下文/日志/截图**
![51564625875_ pic](https://user-images.githubusercontent.com/6743367/62260740-a544bf80-b445-11e9-9d6c-ce1e424804b5.jpg)

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by santcool** [comment]
已修改为，当只执行一次时，关闭时间不可早于开启时间。而每天执行，可以早于开启时间
