### ISSUE TITLE
StringSpinner 在Android上的bug

### ISSUE THREAD

**Issue by Monkey0803** [MiEcosystem/miot-plugin-sdk#1315]
安卓设备
 在设置pickerInnerStyle属性值时，lineColor 此属性既可以设置'rgba(0,0,0)'和'#000000', 
selectTextColor和selectBgColor属性 只能设置'#ffffff' 格式，如果设置为'#fff'安卓下就会出现错误提示设置的值为null，而且不能设置'rgba()'格式的 这bug太坑了

**Comment by zanetti4** [comment]
请你按照模版提供更多信息，谢谢！
我们将对问题进行处理

**Comment by lvjie0519** [comment]
@Monkey0803    通过#ffffff   类似这种方式设置，有什么不满足的吗？  暂不支持 rgba() 设置方式。
