### ISSUE TITLE
执行自动化成功，但插件智能场景的自动化日志列表不显示

### ISSUE THREAD

**Issue by zhongdenglee** [MiEcosystem/miot-plugin-sdk#1316]
是否为新品（必填）
在售

关联的产品名称（必填）
米家人体传感器/lumi.sensor_motion.v2

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 7.0、iOS 12.0]
SDK分支: [10024]
相关模块:[快捷卡片]

项目ID（必填）
米家传感器插件
model:com.lumi.remoteSensor
项目ID: 无

现象（必填）

操作步骤：
进入首页，点击智能或设置的‘智能场景’，智能页创建自动化，并执行

预期结果：执行成功后，有缓存日志，加载的日志列表为空

实际结果：执行成功后，有缓存日志，加载的日志列表不为空

**Comment by zanetti4** [comment]
@santcool @lvjie0519 执行智能自动化成功后，加载的日志列表应该为空吗？

**Comment by santcool** [comment]
你们和谷豪商量下这个问题，我记得因为你们自动化类型的问题，是不显示在日志区的。
