### ISSUE TITLE
米家App字体大小跟随手机系统调整，导致部分插件布局显示异常，可否和微信类似，字体大小，app本身控制

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#1317]
---
**是否为新品（必填）**
 新品 and 在售

**关联的产品model**
all model
**项目ID（必填）**
all
**企业名称（必填）**
飞彗
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
代码控制的font会随着手机系统设置的字体大小而变化，导致部分UI出现异常，文字区域超出边界，或者字体过小。
**期望（必填）**
做到和微信一样，字体大小在米家内部控制，不跟随手机系统。或者提供别的解决方案。
**其他的上下文/日志/截图**

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
@santcool 

把“插件端支持动态字体”这个功能给禁掉吧（搜监听“UIContentSizeCategoryDidChangeNotification”通知的地方，移除掉监听或不做任何处理即可）

**Comment by santcool** [comment]
不能随便禁用，这个涉及到视力障碍的用户的使用问题。微信的处理办法是，禁止系统的字体调节，但自身提供了字体大小调节功能。我们只禁用，又不提供大小调节，会被上诉的

**Comment by santcool** [comment]
我看IOS中并没有这个问题，应该是只和android有关

**Comment by lvjie0519** [comment]
@123start   
1、你说的是米家APP的字体还是插件里面的字体？ 米家APP的字体大小不能随便禁用的；
2、如果是插件中的字体，想不受系统的影响，可使用allowFontScaling = false 属性。

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，如有疑问在reopen。
