### ISSUE TITLE
蓝牙数据加密API报错

### ISSUE THREAD

**Issue by maizui** [MiEcosystem/miot-plugin-sdk#1318]
是否为新品（必填）
新品

关联的产品model
viomi.lock.link1

**企业名称（必填）**
云米科技

**环境（必填）**
- 电脑操作系统:mac
- 手机系统:iOS12
- SDK分支: 10021
- 相关模块:米家App

**现象（必填）**
API接口iBluetoothLock.encryptMessage(message) 的message参数如果传HEX data string，设备端接收解密之后数据不正常。
比如message='4106',设备接收解密后为16进制数{0x41，0x06}
请提供此接口的详细说明，并给出用例。

**期望（必填）**
设备端收到数据解密之后为4106的16进制数：100a

**Comment by zanetti4** [comment]
iot 开发者平台的[蓝牙模块](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/05-%E8%93%9D%E7%89%99%E6%A8%A1%E5%9D%97#/module_miot/Bluetooth--module.exports.IBluetoothLock+encryptMessage)有此接口的文档

**Comment by zanetti4** [comment]
你如果用 encryptMessageWithToken(data) 方法是否可以？

> param {string} data Hex Data String

**Comment by maizui** [comment]
iBluetoothLock.encryptMessageWithToken(data)按文档调用不成功，请提供此接口的详细说明，并给出用例。

**Comment by zanetti4** [comment]
#1319 我在这个 issue 回复了，请查看

**Comment by pencilCool** [comment]
加密和解密传入的数据，都会被认为是hexstring。
如果你传入 "4106"， 不会被认为是4016 这个数字，而是0x4106 这个用16 进制表示的数据。
