### ISSUE TITLE
蓝牙API接口调用不成功

### ISSUE THREAD

**Issue by maizui** [MiEcosystem/miot-plugin-sdk#1319]
**是否为新品（必填）**
新品 

关联的产品model
viomi.lock.link1

企业名称（必填）
云米科技

环境（必填）
- 电脑操作系统:Mac OS
- 手机系统:Mac OSiOS 12.0
- SDK分支: 10021
- 相关模块:米家App

现象（必填）
API接口iBluetoothLock.encryptMessageWithToken(data)按文档调用不成功，请提供此接口的详细说明，并给出用例。

**Comment by zanetti4** [comment]
com.xiaomi.demo -> Main -> Device -> DeviceControl.js，**蓝牙token加密**就是用例。我用 ios 手机测试成功了。
