### ISSUE TITLE
characteristic.setNotify 回调问题

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#132]
### SDK 最新

---

#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 9.0
- 相关模块:[eg.Bluetooth]

#### 现象
BluetoothEvent.bluetoothCharacteristicDiscovered回调中，比如有5个Characteristic，
```
                characters.forEach(c => {
                    this.state.chars[c.UUID] = c;

                    console.log(("GGGGGG setNotify 1 :" + c.UUID));

                    c.setNotify(true).then( data => {
                        console.log(("GGGGGG setNotify 2 :" + c.UUID + " RESULT: "+ data));
                    }).catch( error => {
                        console.log(('GGGGGG setNotify 2 error:'+c.UUID+"  error:"+ error));
                    });
                })
```
循环setNotify只会有最后一个 有结果回调，前面4个都没有回调

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by dingshaoran** [comment]
android 是否有同样的问题如果有，请在 logcat 中过滤miio-bluetooth贴出来

**Comment by edwardair** [comment]
android上测试，setNofity回调没问题，都回调的，但是发现个新问题：
比如，有5个Characteristic，                        service.startDiscoverCharacteristics('FFD1','FFD2','FFD3','FFD4','FFD5'); ( **startDiscoverCharacteristics打印检测仅调用一次**)
但在 `BluetoothEvent.bluetoothCharacteristicDiscovered`回调中，接收了2批次的Characteristics，
打印每个c.UUID发现，这2批的c.UUID格式不同：如
第一轮：FFD1对应返回的是FFD1
第二轮：FFD1对应返回的是0000ffd1-0000-1000-8000-00805f9b34fb

_**期望：BluetoothEvent.bluetoothCharacteristicDiscovered仅回调一次**_
@dingshaoran

**Comment by dingshaoran** [comment]
android 的内部实现discoverServices discoverCharacteristics两个方法无论传什么值都会直接调用相应的 bluetoothServicesDiscovered  bluetoothCharacteristicDiscovered，没有任何逻辑，您可以试试随便传几个字符串试试，收到两次回调很可能是因为您调用了两次。
请在startDiscoverCharacteristics和bluetoothCharacteristicDiscovered处打 log，看是否成对出现

**Comment by edwardair** [comment]
上面问题里面我说清楚了，start打印只调用了一次

**Comment by edwardair** [comment]
再者，就算（**_如果_**）我真调用了2次startDiscoverService，那么怎么解释，2次返回的characteristic.UUID格式不同问题？我肯定是不可能自己去模拟得出0000ffd1-0000-1000-8000-00805f9b34fb这样子的字符串的啊

**Comment by edwardair** [comment]
android上使用DEMO代码调试发现，仅`bt.connect`，之后不做任何处理，不执行`startDiscoverServices、startDiscoverCharacteristics`，都能被动接收到 `bluetoothSeviceDiscovered、bluetoothCharacteristicDiscovered`，且返回的这些UUID就是128位的；
然后当加上 `bt.startDiscoverServices("FFD0");` 返回的UUID就是16位的

**Comment by edwardair** [comment]
同样代码，在iOS上测试，

1. 插件第一次进入，也会被动接收到 `bluetoothSeviceDiscovered`，只不过service数组是空的；
2. 当直接在当前插件页面reload插件，也跟android一样，被动接收到 `bluetoothSeviceDiscovered、bluetoothCharacteristicDiscovered`，发现的数量比android少，并且characters.UUID  是诸如：`["0001","0002","0004","0007","0010","0013","0014","1001"]` 这些UUID我并不认识
3. 发现reload插件时，蓝牙本身是`已连接`的，但是检测  `bt.isConnected` 返回是  `undefined`，这个问题不是说已经修复了么 `（iOS、Android都有问题）（测试过 第一次添加插件流程，进入插件后检测`bt.isConnected`同样返回`undefined`）`

**Comment by edwardair** [comment]
麻烦能否在此更新下目前问题解决进度，问题是否已确认？ @LiuMengzhou

**Comment by edwardair** [comment]
@LiuMengzhou @dingshaoran @kyou 请问目前问题解决进度怎样？

**Comment by edwardair** [comment]
此问题 截止到当前时间 12月20日下午（SDK、ipa/apk都为最新版本），测试问题仍旧存在

**Comment by blockdate** [comment]
这个问题现在我来follow，这个问题进行了修改，更新app查看是否修复
