### ISSUE TITLE
用户隐私授权成功后，如果有强制升级，不会触发

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#1320]
**是否为新品（必填）**
填 新品 or 在售
新品
**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
lumi.curtain.hagl05
**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID
**企业名称（必填）**
贵司的名称
绿米联创
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
MAC OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.0
- SDK分支: [eg.master/10000/...]
10023
- 相关模块:[eg.Host/Service/Account]
Service.smarthome.batchGetDeviceDatas
**现象（必填）**
简单明了地描述一下实际的现象。
目前是隐私授权以后,没有进行升级逻辑，但是如果当前遇到的版本为强制升级版本，则不会进行强制升级逻辑

**期望（必填）**
简单明了地描述一下期望的表现。
隐私授权以后能进行升级逻辑

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请给出隐私授权+升级的具体代码，没有进行升级逻辑，有报错信息吗？
