### ISSUE TITLE
取消隐私授权ios会退出插件，android只会回退到上一页

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#1322]
**是否为新品（必填）**
填 新品 or 在售
新品

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
lumi.curtain.hagl05

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID

**企业名称（必填）**
贵司的名称
绿米联创

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
mac os

- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.0

- SDK分支: [eg.master/10000/...]
10023

- 相关模块:[eg.Host/Service/Account]
Host.ui.privacyAndProtocolReview

**现象（必填）**
简单明了地描述一下实际的现象。
目前现象是：
android：退回上一页
ios：退出整个插件

**期望（必填）**
简单明了地描述一下期望的表现。
android：退出整个插件

ios：退出整个插件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
> deprecated 10023废弃， 请使用 previewLegalInformationAuthorization

使用 previewLegalInformationAuthorization 接口，还存在此问题吗？

**Comment by wanggoingdown** [comment]
@zanetti4 我在文档里面没有看到previewLegalInformationAuthorization，没法验证啊
