### ISSUE TITLE
[紧急]插件进入闪退

### ISSUE THREAD

**Issue by mny459** [MiEcosystem/miot-plugin-sdk#1323]
**是否为新品（必填）**
在售

**关联的产品model**
yunshi.lock.s2

**项目ID（必填）**

**企业名称（必填）**
陨石科技

**环境（必填）**
- 电脑操作系统: mac
- 手机系统:小米8、小米6、IQOO
- SDK分支: 10023
- 相关模块: 

**现象（必填）**
进入插件，插件奔溃退出（大概率偶现）

**期望（必填）**
不会奔溃（本来好好的，突然就就这样，实在很懵逼）

**其他的上下文/日志/截图**
尝试用AS抓到的错误日志
```
E/MIOTPackageModule: RN init activity is null
```

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@mny459   插件包上传到开发者平台了吗？  如果上传了， 麻烦把设备分享给894158105账号，谢谢。

**Comment by cfJand** [comment]
建议提供具体的crash日志 @mny459

**Comment by mny459** [comment]
> @mny459 插件包上传到开发者平台了吗？ 如果上传了， 麻烦把设备分享给894158105账号，谢谢。

插件已经上传，可是无法进入插件内分享

**Comment by mny459** [comment]
> 建议提供具体的crash日志 @mny459

能说一下插件crash 的日志关键词吗？一打开日志好多，我也不确定是哪一个

**Comment by mny459** [comment]
> 建议提供具体的crash日志 @mny459

同一个账户，使用苹果手机登陆以后，不会出现这个情况，然后再在Android手机上操作，也不会出现了。这种两端不一样的情况我已经提了两个issue了

**Comment by lvjie0519** [comment]
@mny459   只需要查看插件进程的log日志即可，插件进程名含有plugin 的，例如plugin0,等等。

**Comment by lvjie0519** [comment]
@mny459  问题如果没有排除出来，可以添加微信(sky-boy-0519)详聊。

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭。
