### ISSUE TITLE
openTimerSettingPageWithOption配置信息未生效

### ISSUE THREAD

**Issue by heyupeng** [MiEcosystem/miot-plugin-sdk#1324]
**是否为新品（必填）**
新品

**关联的产品model**
soocare.toothbrush.mc1

**项目ID（必填）**
PRJ18-SOOCA-X-003

**企业名称（必填）**
舒可士

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 11.0
- SDK分支: master
- 相关模块:Host/ui/

**现象（必填）**
1.Host/ui.js 文件报错
2.调用ui. openTimerSettingPageWithOption(opt), bothTimerMustBeSet设置为true，结果界面显示无变化，依旧显示三个条目选项。 

**期望（必填）**
 界面能够按照配置信息正常显示。

**其他的上下文/日志/截图**
1.Host/ui.js
<img width="444" alt="image" src="https://user-images.githubusercontent.com/17895457/62343856-4606ae00-b51e-11e9-9566-286fbc57b76e.png">

2.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/17895457/62344180-93cfe600-b51f-11e9-9fa5-4d58524d2005.png">

**尝试过的解决办法**
修改定时器类型相关的4个字段键值，界面均无变化。

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
1. 我这里 openDeleteDevice 和你的截图不同，你重新拉取代码也是那样吗？
![image](https://user-images.githubusercontent.com/12883959/62350205-96890600-b534-11e9-997f-7f70c8c599d9.png)
2. master 分支 openTimerSettingPageWithOptions(options)，options 没有 bothTmerMustBeSet, showOnTimerType, showOffTimerType, showPeriodTimerType。你用的是哪个分支？
![image](https://user-images.githubusercontent.com/12883959/62350525-87ef1e80-b535-11e9-961f-a39c9c1dd1ac.png)

**Comment by heyupeng** [comment]
拉取的最新代码就是这样。现在GitHub上的master分支已经合并了10023分支了，你可以看下GitHub的文件。master/10023我都试了，结果都一样。

**Comment by zanetti4** [comment]
10023分支测试：
1. 查看 openDeleteDevice，也是上面的截图那样。
2. openTimerSettingPageWithOptions(options)，看到了你写的那些参数说明。更改 bothTmerMustBeSet, showOnTimerType, showOffTimerType, showPeriodTimerType 属性，确实没有变化。

**Comment by zanetti4** [comment]
@santcool 请你协助查看此问题

**Comment by santcool** [comment]
忘了合入代码到master，一会儿提供最新包。

**Comment by heyupeng** [comment]
@santcool 请问新包提供了吗？ 最新的beta2523还是没有效果
