### ISSUE TITLE
ios绑定设备时修改名称失败

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#1325]
**是否为新品（必填）**
新品

**关联的产品model**
xiaoxun.watch.sw560

**企业名称（必填）**
上海小寻科技有限公司

**环境（必填）**
iOS 11.0

**现象（必填）**
iphone手机通过米家app绑定已经有owner的儿童手表成功后，修改名称时提示“修改设备名称失败，请重试”的错误。Android手机可以正常修改。

**期望（必填）**
iphone手机绑定儿童手表成功后，可以正常修改名称。

**其他的上下文/日志/截图**
![51564718655_ pic](https://user-images.githubusercontent.com/34823528/62343860-4bfc8f00-b51e-11e9-8296-cfd602eb0624.jpg)

**Comment by santcool** [comment]
请提供抓包信息，谢谢！

**Comment by heping99** [comment]
@santcool 是指网络抓包信息吗？还是指什么信息？

**Comment by santcool** [comment]
肯定了，网络抓包信息，看看点击改名按钮后，那个网络请求的内容

**Comment by heping99** [comment]
[儿童手表不能修改名称(xiaoxun.watch.v11).zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3480774/xiaoxun.watch.v11.zip)
这个是抓包文件@santcool

**Comment by santcool** [comment]
能弄charles抓包嘛……你这个数据量太大，格式也无法识别。[教程](https://www.cnblogs.com/mawenqiangios/p/8270238.html) 在此，比wireshark方便很多的

**Comment by santcool** [comment]
请及时回复，否则问题可能会被关闭，谢谢

**Comment by santcool** [comment]
多日未回复，问题关闭
