### ISSUE TITLE
使用nordic52系列蓝牙芯片平台，OTA升级包数据格式有什么要求？

### ISSUE THREAD

**Issue by maizui** [MiEcosystem/miot-plugin-sdk#1327]
是否为新品（必填）
新品

关联的产品model
viomi.lock.link1

企业名称（必填）
云米科技

现象（必填）
描述：使用nordic52系列蓝牙芯片平台，OTA升级包数据格式有什么要求？是否按芯片原厂的格式就可以？

**Comment by pencilCool** [comment]
没什么要求，可以按芯片原厂的格式。
