### ISSUE TITLE
后台运行多个应用程序，隐藏LoadingDialog会卡死

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#1328]
**是否为新品（必填）**
填 新品 or 在售
新品

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”
lumi.curtain.hagl05

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID

**企业名称（必填）**
贵司的名称
绿米联创

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
IOS 12

- SDK分支: [eg.master/10000/...]
10023

- 相关模块:[eg.Host/Service/Account]
miot/ui/LoadingDialog
**现象（必填）**
简单明了地描述一下实际的现象。
目前发现一个情况：
如果后台开20～30个应用程序，再打开米家运行插件，调用LoadingDialog隐藏的时候整个页面会卡住并且点击应用无反应，必须杀进程才正常

**期望（必填）**
简单明了地描述一下期望的表现。
期望是：
无论打开多少个应用，隐藏loadingdialog，插件使用正常

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
未能复现，请运行demo查看是否能复现，并请贵方技术优先排查。另外，如果是必须打开20-30个应用才卡住，那此问题解决的必要性不大，请尝试是否有别的条件下会卡出。

**Comment by santcool** [comment]
无人回复，问题关闭，若还有问题，请重新提issue
