### ISSUE TITLE
在插件首页点击左上角返回按钮，会退出米家APP

### ISSUE THREAD

**Issue by Monkey0803** [MiEcosystem/miot-plugin-sdk#1329]
是否为新品（必填）
在售

关联的产品model
tokit.oven.tk12l01

项目ID（必填）

企业名称（必填）
纯米

环境（必填）

SDK分支: [100023]
相关模块:[Package]
**现象（必填）**

在插件首页点击左上角返回按钮，会退出米家APP

![8E7D2C24-8AAE-485C-B2A0-9700E3346B1F](https://user-images.githubusercontent.com/11564933/62436020-d9cfb880-b770-11e9-83ef-587af319825e.png)
![7C5A8A35-65D7-457A-9846-85CA9679A1FB](https://user-images.githubusercontent.com/11564933/62436051-f835b400-b770-11e9-9b57-9429c9f21447.png)

**Comment by joyami** [comment]
@zanetti4 您好，因为此产品计划今天提测，按MIOT验收组的要求，遗留米家问题需要提供排期才可以提测。请问今天是否可以先给一个解决问题的排期？否则若今天无法提测，会影响产品上小米网售卖的时间。谢谢您的支持和理解！

**Comment by zanetti4** [comment]
> deprecated 10005; since 10005 TitleBarBlack was deprecated, use TitleBar instead.

我平时无论用安卓还是 ios 进行测试，都没有出现过此问题。如果用 TitleBar 还有这个问题吗？
