### ISSUE TITLE
高斯模糊

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1330]
**是否为新品（必填）**
新品 

**企业名称（必填）**
飞彗

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
react-native-blur对安卓的兼容不是很好，只能模糊图片，不能对view进行模糊

**期望（必填）**
希望用css或js实现一个高斯模糊且兼容好的组件

急急急

**Comment by zanetti4** [comment]
@lvjie0519 我测试了一下，也查了一些[资料](https://blog.csdn.net/u010389309/article/details/82710887)，确实存在这个问题。能让安卓支持的更好吗？或者还有更好的模块吗？

**Comment by zanetti4** [comment]
@devYoungyang 请问此问题涉及的产品 model 是什么？

**Comment by lvjie0519** [comment]
@devYoungyang    可以对View进行模糊，需要确保BlurView 中 viewRef的正确性。

**Comment by devYoungyang** [comment]
@zanetti4 是新品圆饼台灯，产品model暂未确定，硬件和插件都在进行中，

**Comment by devYoungyang** [comment]
@lvjie0519 安卓的模糊图片是可以，但我是想模糊一个view、iOS可以，但安卓不可以，

**Comment by lvjie0519** [comment]
@devYoungyang   Android为啥不可以模糊一个view？  只是上面添加一个蒙层， 用BlurView 可以实现，Android确实没有VibrancyView。

**Comment by devYoungyang** [comment]
你怎么写的可以安卓模糊一个View?copy出来让我学习一下

**Comment by devYoungyang** [comment]
@lvjie0519

**Comment by lvjie0519** [comment]
![image](https://user-images.githubusercontent.com/22487747/62520343-fb5b9d80-b85f-11e9-98d3-3dced926f987.png)
不知道是否满足要求，效果上确实没有 image上好， 你也可以去官网issue上看看，
https://github.com/react-native-community/react-native-blur/issues/163

**Comment by devYoungyang** [comment]
你看看安卓跟iOS效果一样吗，我测试的是iOS是有模糊效果的，安卓只是加了一个蒙版没有模糊
@lvjie0519

**Comment by devYoungyang** [comment]
@lvjie0519  怎么说

**Comment by lvjie0519** [comment]
@devYoungyang  这是react-native-blur已有的问题，测试了下，如果ref是image，确实具有模糊效果，你可以尝试将image的ref赋值给BlurView， BlurView使用绝对定位，也可以等待我这边修复，估计没那么快，谢谢。

**Comment by devYoungyang** [comment]
好的，修复好，在这里回复我一下，谢谢

**Comment by devYoungyang** [comment]
@lvjie0519 高斯模糊有进展了吗？

**Comment by lvjie0519** [comment]
@devYoungyang  看了下这个库的源码实现，不太好做修改，  建议你那边采取其他方案。

**Comment by devYoungyang** [comment]
安卓高斯模糊不好弄吗？封装一个原生的提供给我使用呀

**Comment by lvjie0519** [comment]
@devYoungyang   你截个效果图，具体是怎样的效果？如下gif图，难道没体现出模糊 效果吗？
![GIF](https://user-images.githubusercontent.com/22487747/63209404-db0ac900-c112-11e9-9ecf-890774c7ba54.gif)

**Comment by devYoungyang** [comment]
就是要view控件模糊那种效果，有一个属性值可以控制模糊程度，模糊类型分dark和light

**Comment by devYoungyang** [comment]
@lvjie0519

**Comment by lvjie0519** [comment]
@devYoungyang   可以实现View的模糊的， downsampleFactor   具有模糊效果， blurAmount是控制蒙层的效果， 你可以去看看react-native-blur的原生代码实现。

**Comment by devYoungyang** [comment]
你把你实现view模糊的代码复制一下，我看学习一下，我不懂安卓原生

**Comment by lvjie0519** [comment]
自己看看，再改造下。

[ReactNativeBlurDemo.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3514023/ReactNativeBlurDemo.zip)

**Comment by devYoungyang** [comment]
我看了你的demo，跟我的需求不太符合。我需要用Modal组件呈现一个高斯模糊的视图，透过高斯模糊的视图，后面的文字和图片都被模糊了 @lvjie0519

**Comment by lvjie0519** [comment]
你给一个 你那边的UI图吧，文字说也说不清

**Comment by devYoungyang** [comment]
这样跟你说吧。例如一个MessageDialog，点击弹出，我需要背景蒙版是高斯模糊的 这样总能明白了吧  @lvjie0519

**Comment by devYoungyang** [comment]
@lvjie0519 回个话呀

**Comment by lvjie0519** [comment]
别急，我写个demo

**Comment by lvjie0519** [comment]
modal， 使用绝对布局，两层view重叠，对第一层的view做高斯模糊，不能实现吗？

**Comment by devYoungyang** [comment]
我用的就是modal，绝对布局，堆叠在iOS可以，安卓只是一个黑色蒙层 @lvjie0519

**Comment by lvjie0519** [comment]
ok ,   我这边测试下，看是否需要提供其他方式解决，这周给回复。

**Comment by devYoungyang** [comment]
今天周五了，不会忘记了吧 @lvjie0519

**Comment by lvjie0519** [comment]
reopen吧，不好意思，忙着其他的事情，上次查看写个demo测试了下，react-native-blur对安卓的支持确实不好，你这种情况，需要我这边自定义一个view来实现高斯模糊，麻烦提供个你那边的ui设计图做个参考，谢谢。

**Comment by devYoungyang** [comment]
你给我个邮箱吧，为了保密，UI设计图不能公开

**Comment by devYoungyang** [comment]
[img_01](http://px1fh00yq.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-08-30%20%E4%B8%8B%E5%8D%883.03.14.png)

[img_02](http://px1fh00yq.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202019-08-30%20%E4%B8%8B%E5%8D%883.03.04.png)

@lvjie0519

**Comment by lvjie0519** [comment]
@devYoungyang    已修复， 请使用最新apk进行测试， js代码可参考如下：

[BlankDemo.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3565189/BlankDemo.txt)

**Comment by devYoungyang** [comment]
好的，我试一下

**Comment by devYoungyang** [comment]
@lvjie0519 米家测试版能正常运行，正式版点击崩溃，是不是正式版米家没有集成这一点？
