### ISSUE TITLE
iOS，海外服务器插件，Host.ui.openShareListBar问题

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#1331]
- IPA/APK 最新
- SDK 最新

---
**是否为新品（必填）**
新品

**关联的产品model**
roidmi.vacuum.v1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
无锡睿米

**环境（必填）**
- 相关模块: Host

**现象（必填）**
插件内，调用  `Host.ui.openShareListBar` 分享截图时，米家内部貌似区分大陆/海外服务器(测试使用德国)，而显示不同的分享页面，当为海外服务器时，由于底部菜单过多，在iPhone5尺寸的屏幕上，截图部分会被压缩至很小，导致出现UI显示效果bug，麻烦解决下

![Screen Shot 2019-08-01 at 4 08 32 PM](https://user-images.githubusercontent.com/2043635/62443613-e9112f00-b78d-11e9-8fe8-a10dcabbadca.png)
![Screen Shot 2019-08-01 at 4 10 34 PM](https://user-images.githubusercontent.com/2043635/62443614-e9112f00-b78d-11e9-8a3c-acb380fba857.png)

**Comment by edwardair** [comment]
麻烦能否先给出解决方案，我们好评估插件后续的进度，谢谢

**Comment by santcool** [comment]
这个只是预览图太小了吧？实际分享出去的图应该是正常的才对。如果是预览图太小，没什么好办法。如果是实际分享出去的图太小，我们再看看

**Comment by edwardair** [comment]
就是预览图大小问题，问题是，插件审核测试时，米家测试提出的问题啊，插件过不了审核

**Comment by edwardair** [comment]
我们只能移除分享功能了，结贴
