### ISSUE TITLE
[紧急] 提交新版本插件, iOS 无法加载新插件而是加载之前的老插件, 安卓正常加载新插件

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#1333]
急  急  很紧急!! SOS  
---
**是否为新品（必填）**
在售

**关联的产品model**
aden.aircondition.a2

**项目ID（必填）**

**企业名称（必填）**
珠海亚丁科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
提交新版本插件, iOS 无法加载新插件而是加载之前的老插件, 安卓正常加载新插件, 尝试控制台打印, 参照下面的截图.

**期望（必填）**
iOS正常加载新插件

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/16514238/62445748-a8b4af80-b793-11e9-83c5-b13ae5a6a226.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
Duplicate of #1252 
之前有过类似问题，请查看。问题是否得到解决？

**Comment by DaquanZhou** [comment]
@zanetti4  现在已解决, 是服务器的配置问题, 谢谢!
