### ISSUE TITLE
米家插件上沒出現設備

### ISSUE THREAD

**Issue by royshow0316** [MiEcosystem/miot-plugin-sdk#1334]
公司名称
女媧創造

是否为新产品
是

产品名称/Model
女媧機器人二代/nuwa.robot.nb1

环境
电脑操作系统: mac
手机系统: Redmi 5 Plus
SDK分支: 10011
相关模块: 米家App 5.4.62 测试版

现象（必填）
設備使用Didkey方式認證, 插件已在小米IOT開發者平台上傳擴展程序, 狀態為測試中

期望（必填）
手機小米插件上, 應該要找到設備

**Comment by cfJand** [comment]
@royshow0316 建议详细描述问题，提供相关的APP截图，方便我们排查问题。

**Comment by cfJand** [comment]
如果是附近设备里面没有扫描到你的设备，可能是广播协议有问题；
如果在手动添加设备里面，没有发现你的设备，那么可能是因为没有正式上线的设备，需要将你的账号添加到设备的白名单里面去，才能显示出来。

**Comment by royshow0316** [comment]
帳號是使用開發帳號，所以應該是會顯示出來，設備是使用Didkey方式和小米認證。
插件上登入帳號，應該要會自動出現已連接的設備，如下圖，但沒有出現。
![IMAG0824](https://user-images.githubusercontent.com/11886806/62998335-c4a80780-be9d-11e9-9fd7-ba35582e27f9.jpg)

使用的方法和另一個設備一樣的方式，另一個設備有出現在插件上，如下圖。
![IMAG0825](https://user-images.githubusercontent.com/11886806/63000745-7ba78180-bea4-11e9-9bb3-791e19c072e7.jpg)

**Comment by cfJand** [comment]
从图中来看，设备应该是没有和登录的账户绑定。方便的话，你可以提供一下你的didkey ,我会根据这个did key 查一下该设备和哪个用户id绑定。

**Comment by royshow0316** [comment]
didkey：11672117T0GQl8KrQfcPUOk3

**Comment by cfJand** [comment]
![微信截图_20190814160949](https://user-images.githubusercontent.com/2038490/63004879-02ad2780-beae-11e9-9de2-8e8813448944.png)
这是当前设备所对应的账户信息，请查看一下是否正确。

**Comment by royshow0316** [comment]
應該是這樣
MiDid: 11672117
XiaomiId: 1628308742
miotToken: mxhfqa7bhe
miotSession: 33_11672117_1565769521269420526
Wifi MAC: 90:4e:91:60:1c:7f

**Comment by royshow0316** [comment]
我重置了設備, 這樣比較好找, 時間應該在4:30左右。
didkey: 11672117T0GQl8KrQfcPUOk3
MiDid: 11672117
XiaomiId: 1628308742
miotToken: jx9irwob2t
miotSession: 33_11672117_1565771457084887031

**Comment by cfJand** [comment]
我给你发的图中，设备的did 和你后面发的xiaomiid不一致。建议重新绑定设备后，查看设备是否出现在米家APP的首页。
而xiaomi id 1628308742 所对应的did是：45497316 和 47265726。

**Comment by royshow0316** [comment]
重新绑定设备后，依然沒有出現。
didkey: 11672117T0GQl8KrQfcPUOk3
MiDid: 11672117
XiaomiId: 1628308742
miotToken: q6nuz2wnc5
miotSession: 33_11672117_1565773650839511981
wifimac: 90:4e:91:60:1c:7f

我附上设备的log, 设备是android 9.0。
[Nuwa_Device.log](https://github.com/MiEcosystem/miot-plugin-sdk/files/3500619/Nuwa_Device.log)

**Comment by cfJand** [comment]
日志文件，没有有用的信息。建议在米家APP中退出当前账号，重新登录，重新绑定设备试试。
另外这两个号：1849330660  和 1628308742  是什么关系？

**Comment by cfJand** [comment]
这样吧，我建立的一个QQ群，方便及时沟通。
![MIOT群二维码](https://user-images.githubusercontent.com/2038490/63011200-676e7f00-beba-11e9-8fc0-a539f08322be.png)

**Comment by cfJand** [comment]
经过QQ沟通，是因为设备绑定了其他账号的问题，需要先解绑，现在问题已解决，close issue。
