### ISSUE TITLE
灯组修改设备名称异常

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1335]
**是否为新品（必填）**
 在售

**关联的产品model**
philips.light.virtual

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [master]
- 相关模块:[]

**现象（必填）**
ios进入灯组插件点击设备名称，不修改名称点击确定，提示一堆字符异常（如下图）。

**期望（必填）**
可以正常提示

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/5188922/62448983-aeae8e80-b79b-11e9-993b-11763f5b616c.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@santcool 我测试驱蚊器没有这个问题，请你查看。

**Comment by santcool** [comment]
已修复。将会随着今天的发版一起发出
