### ISSUE TITLE
智能场景重命名问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#1336]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulb

**企业名称（必填）**
philips

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android在智能里创建一个智能并重命名修改名称/不修改名称，不显示是否成功，（修改名称后）智能名称大概率不同步刷新，必须下拉才能刷新名称。
Ios在智能里创建一个智能并重命名，不修改名称点击确定显示重命名成功。

**期望（必填）**
Ios与Android的表现情况一致。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
安卓：
我使用米家5.5.42.8，在下方**智能选项卡**新建场景后，重命名时如果不修改名称，不能点击确定，只能点击取消，没有提示应该是合理的。如果修改名称，点击确定，没有提示，回到智能场景列表，名称是可以自动更新的。
ios:
米家4.20.1，重命名不修改名称点击确定，没有提示。修改名称点击确定，才会返回上一级页面并显示重命名成功。
您使用的米家是什么版本？如果使用我说的版本，是否还存在相同问题？

**Comment by zanetti4** [comment]
安卓：
我使用米家5.5.42.8，在下方**智能选项卡**新建场景后，重命名时如果不修改名称，不能点击确定，只能点击取消，没有提示应该是合理的。如果修改名称，点击确定，没有提示，回到智能场景列表，名称是可以自动更新的。
ios:
米家4.20.1，重命名不修改名称点击确定，没有提示。修改名称点击确定，才会返回上一级页面并显示重命名成功。
您使用的米家是什么版本？如果使用我说的版本，是否还存在相同问题？

**Comment by zanetti4** [comment]
@santcool @lvjie0519 对于智能的重命名操作，安卓和 ios 表现有不一致，请你们查看。

**Comment by mirse** [comment]
> 安卓：
> 我使用米家5.5.42.8，在下方**智能选项卡**新建场景后，重命名时如果不修改名称，不能点击确定，只能点击取消，没有提示应该是合理的。如果修改名称，点击确定，没有提示，回到智能场景列表，名称是可以自动更新的。
> ios:
> 米家4.20.1，重命名不修改名称点击确定，没有提示。修改名称点击确定，才会返回上一级页面并显示重命名成功。
> 您使用的米家是什么版本？如果使用我说的版本，是否还存在相同问题？

我是在插件设置页面的智能场景里设置的
Android使用的米家版本为最新测试版 5.5.48.1
Ios使用的米家版本为最新测试版 4.20.0

**Comment by santcool** [comment]
这种不一致的问题，我们很难处理~因为我们两个平台的开发和测试验收是完全分开的，所以我们这边完全无法把控这种不一致。如果你们确实不能接受某一端的交互，请提需求给你们的PM然后同步到我们的PM。当然，如果是某一端有bug，欢迎随时提出。

**Comment by mirse** [comment]
> 这种不一致的问题，我们很难处理~因为我们两个平台的开发和测试验收是完全分开的，所以我们这边完全无法把控这种不一致。如果你们确实不能接受某一端的交互，请提需求给你们的PM然后同步到我们的PM。当然，如果是某一端有bug，欢迎随时提出。

好的，谢谢

**Comment by mirse** [comment]
> 这种不一致的问题，我们很难处理~因为我们两个平台的开发和测试验收是完全分开的，所以我们这边完全无法把控这种不一致。如果你们确实不能接受某一端的交互，请提需求给你们的PM然后同步到我们的PM。当然，如果是某一端有bug，欢迎随时提出。

好的，但是关于android下拉才能刷新名称的问题，帮忙看看

**Comment by santcool** [comment]
好的. @fishle @lvjie0519

**Comment by lvjie0519** [comment]
@mirse   是米家APP， 智能tab ->我的  项里，长按某个智能，重命名，不能及时更新名称吗？ 我这测试是可以及时更新的，  请使用fir上最新apk试试，谢谢。如果操作步骤不一样，请上传个视频看看你的操作流程。

**Comment by mirse** [comment]
我是在插件里的智能场景里点击重命名的。使用的是最新的测试apk 5.5.48.1

[重命名.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3474866/default.zip)

**Comment by lvjie0519** [comment]
@mirse   ok,  已知问题， 已通知到APP那边修改，修改完成及时反馈，谢谢。

**Comment by lvjie0519** [comment]
@mirse  属于APP组问题，我这边已经帮反馈，如急需解决， 请通过内部提jira到米家这边，此处关闭，谢谢。
