### ISSUE TITLE
更多设置-安全设置，更改密码时，输入过快会多次进入更改密码页面。

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1337]
**是否为新品（必填）**
在售

**关联的产品model**
chunmi.ihcooker.v1、chunmi.pre_cooker.eh1

**企业名称（必填）**
上海纯米电子科技有限公司

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [SDK_10023]
- 相关模块:[更多设置-安全设置]

**现象（必填）**
更多设置-安全设置，更改密码时，输入过快会多次进入更改密码页面。

**期望（必填）**
不会多次进入更改密码页面。

**其他的上下文/日志/截图**
源生Android的插件也有这样的问题
![两个新密码页面](https://user-images.githubusercontent.com/34296463/62458605-ed4e4400-b7af-11e9-8c5d-8f8d2ce04c88.gif)

**Comment by fishle** [comment]
更改密码，要求先输入原密码，再输入新密码，看你上传的动画也是这样的，并没有你时候的输入过快会多次进入更改密码页面；请再确认一下，如果还有问题，麻烦上传更详细的视频操作，及文字说明

**Comment by joyami** [comment]
[更改密码跳转.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3470148/default.zip)
在修改密码时，原密码(1111)输入密码过快会进入多次输入新密码的页面，多个不同产品的插件都能必然复现。请帮忙确认下，谢谢！

**Comment by fishle** [comment]
麻烦试试这个安装包
https://pan.mioffice.cn:443/#/link/82144DEF4668282CA3906497F3FFD0EC

**Comment by joyami** [comment]
@fishle 你好，试过这个安装包，问题还是存在，和之前是一样的，麻烦再帮忙看下

**Comment by fishle** [comment]
卸载重新安装一下试试，这边验证是正常的

**Comment by joyami** [comment]
@fishle 已验证OK了，谢谢。请问5.5.48及以上的版本都已解决了此问题吗？

**Comment by fishle** [comment]
这个会跟下个版本修复，预计月底发布
