### ISSUE TITLE
米家设置 检查固件更新 UI 遮挡

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#1339]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？
- 是否尝试搜索“常见问题”

---
**是否为新品（必填）**
填 新品 or 在售

**关联的产品model**
此issue关联的产品model，如“xiaomi.demo.v1”

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
贵司的名称

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
米家APP-我的——设置——检查更新 ，页面全部更新按钮遮挡了下面的UI

**期望（必填）**
全部更新按钮不要遮挡下面的UI

![IMG_0336](https://user-images.githubusercontent.com/6056276/62505091-cb93a200-b82d-11e9-980b-51149038989f.PNG)

**Comment by zanetti4** [comment]
涉及的手机系统是什么？是哪个米家版本？请填写具体信息
