### ISSUE TITLE
关于发送数据到蓝牙硬件的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#134]
![snip20181211_8](https://user-images.githubusercontent.com/18459414/49796164-ec772680-fd76-11e8-8fd4-4a3283ad91ce.png)

![image](https://user-images.githubusercontent.com/18459414/49796035-8d191680-fd76-11e8-8cca-64b6fa9d69b5.png)

**Comment by dingshaoran** [comment]
看的 log 是 ios 的，android 是不是也有同样的问题

**Comment by caojunhua** [comment]
@Copypeng 你好，我参考bledemo，设备连接，服务，和特征值的发现都可以，我现在是参照文档里做向设备write数据操作，在write数据的时候，报的这个-->The request is not supported问题。

**Comment by flingInTheSky** [comment]
@caojunhua  参考这里吧：#98

**Comment by caojunhua** [comment]
@flingInTheSky 兄弟，谢谢，但是我的不是他的这个问题，报undefined只需要在connect(-1).then()..在这个then里面去调用一个方法，在方法里面打印ble.isConnected，就可以看到输出是一个布尔值了。。。 但是我的是在write方法的时候，向蓝牙硬件发送数据的时候报的错误。

**Comment by caojunhua** [comment]
@Copypeng 
我同一份代码，连接同一个蓝牙设备，分别在安卓和iOS平台上运行的获取的服务的UUID的值不一样呢，下面是iOS上的打印信息
![image](https://user-images.githubusercontent.com/18459414/49853133-2997f300-fe21-11e8-9475-4e42f1827a98.png)
下面是安卓上的打印信息
![image](https://user-images.githubusercontent.com/18459414/49853138-2f8dd400-fe21-11e8-83d6-d64a02b91dd7.png)
调用write方法向蓝牙硬件发送数据，在安卓和ios平台上都会失败，下面是在安卓上的打印发送失败的信息
![image](https://user-images.githubusercontent.com/18459414/49853252-8398b880-fe21-11e8-8045-36fb8bc57360.png)

**Comment by edwardair** [comment]
仔细看 android的UUID，第4条，0000fe95-***************  它就是你的FE95 问题我也问过 see #90

**Comment by caojunhua** [comment]
@edwardair 哥们，加我微信吧，caojunhua001

**Comment by edwardair** [comment]
我不是小米的，这问题SDK方面没做统一处理，那就只能自己处理了，虽然用String.indexOf() >= 0（demo是使用的大于0，但其实应该是 >=0）也能判断，但是如果是要通过UUID去获取缓存characterstic那就会乱了

**Comment by edwardair** [comment]
通过平台来判断，其实并不安全的，指不定SDK方面什么时候统一好了。。。再者，因为android上其实并不是所有UUID都是长UUID，而是比如didDiscoverService是短的，而到了didDiscoverCharacteristic就变成长的了，其实可以把长的截取，再处理成短的就好了

**Comment by caojunhua** [comment]
@edwardair 嗯，谢谢，你说的有道理。。。后面的write数据的问题，你有没有遇到过类似的？

**Comment by dzonel** [comment]
@caojunhua 我试过蓝牙收发数据，我这边是可以的。建议你确认一下上面Copypeng说的，你那个characteristic是否支持notify或者write数据。

**Comment by caojunhua** [comment]
@

> @caojunhua 我试过蓝牙收发数据，我这边是可以的。建议你确认一下上面Copypeng说的，你那个characteristic是否支持notify或者write数据。

好的，谢谢，我这有个群，有兴趣可以进来共同交流一下
![wechatimg261](https://user-images.githubusercontent.com/18459414/49863147-9b306b00-fe3a-11e8-8f07-b3471372c235.jpeg)

**Comment by caojunhua** [comment]
@dzonel

**Comment by dingshaoran** [comment]
@caojunhua 请不要私下交流。有问题统一反馈到 issue，您说的 Example 写错了，这几个方法都翻会 Promise，serviceId 有可能是128位的有可能是16位的，判断字符串的时候用 indexOf>=0 比较方便，读取不到数据的问题请更新到最新的 ipa/apk，如果还读取不到值 您有 android 机的话 logcat 过滤 miio-bluetooth 附上来

**Comment by edwardair** [comment]
write数据问题，我今天也测试了一天，iOS上感觉无法写数据，Android上正常

**Comment by Copypeng** [comment]
https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518747-writevalue?language=objc

write 方法对应：
writeValue:data forCharacteristic:characteristic type: CBCharacteristicWriteWithResponse

writeWithoutResponse 方法对应：
writeValue:data forCharacteristic:characteristic type: CBCharacteristicWriteWithoutResponse

**Comment by edwardair** [comment]
内部原生肯定是只有这2个方法写蓝牙数据啊，关键在于，RN SDK方面，传的data到底是什么格式，文档写的 *（表示任何类型？） ，但是实测下来其实是16进制字符串，而到了iOS上，我们第三方集成人员也不清楚是否是ipa临时bug？iOS数据格式不统一等等原因，只能自己摸索测试

**Comment by flingInTheSky** [comment]
@caojunhua #98 问题里下面的交流中，我是有回复我这边是怎么读数据、写数据的呀

**Comment by edwardair** [comment]
@flingInTheSky 读写数据目前就是确定为16进制字符串，我android可以正常读写，但是iOS上只能setNofity后被动接收，写的数据没反应（相同代码，双平台对比测试得出）

**Comment by caojunhua** [comment]
> @flingInTheSky 读写数据目前就是确定为16进制字符串，我android可以正常读写，但是iOS上只能setNofity后被动接收，写的数据没反应（相同代码，双平台对比测试得出）

是转换为了16进制，我是安卓和ios都失败，确定写特征支持notify

**Comment by edwardair** [comment]
失败的话用最简单的DEMO代码来测试单个UUID的读写，代码越简单越好的那种，因为我之前就遇到iOS无论如何无法连接蓝牙的问题，最后发现是在连接蓝牙前调用了Device相关的API导致的，花了我2周时间去测试、反馈、调试，最简代码也能方便SDK人员审核

**Comment by caojunhua** [comment]
> 这个 CBATTErrorDomain 是系统蓝牙返回的错误，是这个 characteristic 本身不支持 notify 或者 write 操作吗？
> 
> 另外可以参考 bledemo 做设备连接和服务、特征值发现。

确定写特征支持notify操作，但是读特征不支持notify操作，应该怎么写？example的demo，读方法也是setNotify(true).read()这么个形式。

**Comment by dzonel** [comment]
我这边是用的iOS测试，收发都没问题。
接收数据是在BluetoothEvent.bluetoothCharacteristicValueChanged监听里面。
发数据代码如下：
![1544672714059](https://user-images.githubusercontent.com/12531667/49914536-9a481980-fecc-11e8-9e86-d2fef1c4fdb0.jpg)

**Comment by edwardair** [comment]
我这边iOS写数据确认是 writeWithoutResponse误判成使用writeWithResponse导致的写失败问题，不知道android上为什么是正确的

**Comment by dzonel** [comment]
BluetoothEvent中没发现writeWithResponse 对应的 didWriteValueForCharacteristic相应的监听事件

**Comment by flingInTheSky** [comment]
我发现，固件升级模块，写入数据，也收不到消息。其他的设备控制命令没问题

**Comment by caojunhua** [comment]
> 我这边是用的iOS测试，收发都没问题。
> 接收数据是在BluetoothEvent.bluetoothCharacteristicValueChanged监听里面。
> 发数据代码如下：
> ![1544672714059](https://user-images.githubusercontent.com/12531667/49914536-9a481980-fecc-11e8-9e86-d2fef1c4fdb0.jpg)

写数据我现在可以写，但是我是这样写的
![image](https://user-images.githubusercontent.com/18459414/49929629-e2cbfb00-fefd-11e8-8db1-25189eecd0a2.png)
在接收数据是在BluetoothEvent.bluetoothCharacteristicValueChanged监听里面我没有接受到任何数据，
![image](https://user-images.githubusercontent.com/18459414/49929706-10b13f80-fefe-11e8-924e-689e33027a6b.png)

**Comment by edwardair** [comment]
先确定是  write  还是 writeWithoutResponse
目前我双平台都能读写，就差一下小功能等SDK完善解决

**Comment by dzonel** [comment]
@caojunhua 你可以和你们硬件工程师联调一下，看看蓝牙设备有没有给你发数据。接收数据我也是在这个监听里面，可以收到数据。你的msgData数据长度多少？每次发送的数据包大小是有限制的，是不是没发完，蓝牙设备没返回。

**Comment by dzonel** [comment]
@flingInTheSky 你断开连接后，还能连接上？

**Comment by caojunhua** [comment]
> 问下，iOS 蓝牙断开连接，bluetoothConnectionStatusChanged 收不到消息，这个问题修复了吗？我试了下，iOS还是不行。其他问题都调试OK了。

我调用断开，看打印有来到断开方法，但是发送断开后，硬件串口调试没有接收到断开命令。
if (bluetooth.isConnected) {
        Util.log('调用断开');
        bluetooth.disconnect(0);
    }

**Comment by edwardair** [comment]
我遇到的重连问题 see #150   @dzonel

**Comment by flingInTheSky** [comment]
@caojunhua 我没有接串口调试，需要确认硬件方面的什么数据呢

**Comment by flingInTheSky** [comment]
@dzonel 我这边的重连操作是这样：监测到断开连接时，调用connect，然后判断错误码，data.code=-6时才重新connect，Android这样操作，目前没发现问题

**Comment by flingInTheSky** [comment]
@dzonel iOS 你可以收到蓝牙连接状态断开（bluetoothConnectionStatusChanged）的消息？

**Comment by edwardair** [comment]
+1
`bluetoothConnectionStatusChanged` 蓝牙设备主动断电导致蓝牙连接中断，但是iOS端收不到通知，无法触发重连操作

**Comment by flingInTheSky** [comment]
@caojunhua android以及旧版本rn没问题，这说明硬件方面没问题的吧

**Comment by caojunhua** [comment]
> @caojunhua android以及旧版本rn没问题，这说明硬件方面没问题的吧

是的

**Comment by blockdate** [comment]
问题不活跃，目前关闭。

使用最新版本APP以及SDK，如任然有问题，可追加回复或者重新建立issue。
