### ISSUE TITLE
米家APP首页宫格内设备状态显示异常

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#1340]
**是否为新品（必填）**
在售

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [SDK_10023]

**现象（必填）**
米家APP 5.5.13以上版本设备宫格内显示不出设备状态, 以下为相关截图&卡片JSON文件（已增加宮格配置）。
![26b0505ec87bbd9cc34a96d51c95777](https://user-images.githubusercontent.com/49632045/62517520-217e3f00-b85a-11e9-9cab-1ed5687e8b2a.png)

[mijia_card_config.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3470742/mijia_card_config.zip)

**期望（必填）**
正常显示。

**Comment by dingshaoran** [comment]
https://github.com/MiEcosystem/NewXmPluginSDK/tree/master/card_config
问题2，看一下是不是获取到了配置的属性值

**Comment by joyami** [comment]
@dingshaoran 你好，是可以正常获取到配置的属性值，但是APP还是不显示本地的卡片内容。
![日志截图](https://user-images.githubusercontent.com/34296463/62669892-e7c94780-b9c3-11e9-978e-3628650481bb.png)

**Comment by zhangxu7** [comment]
原因已找到，8.20版本修复。
