### ISSUE TITLE
智能条件添加成功后智能列表不显示

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#1341]
**是否为新品（必填）**
在售

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android /iOS]
- SDK分支: [SDK_10023]

**现象（必填）**
智能条件添加成功后智能列表不显示
Step1: 智能中设置如定时到XX，就执行向手机发送通知，设置成功
Step2: 查看智能列表并无这条信息，到时间后，仍可收到智能推送

[操作视频.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3470789/default.zip)
 
**期望（必填）**
正常显示。

**Comment by zanetti4** [comment]
此问题只发生在安卓系统吗？使用的米家版本是什么？

**Comment by CJackKao** [comment]
Android & iOS都有相同情况
iOS：4.20.1
android：5.5.49

**Comment by zanetti4** [comment]
@santcool @lvjie0519 我用两个系统进行测试，都没有复现，请你们查看。

**Comment by fishle** [comment]
从插件的通用设置进去到智能场景是可以复现的 @zanetti4

**Comment by fishle** [comment]
添加智能的时候，你的智能动作要与你的设备相关才能显示到这里，比如是灯设备，你的智能就要包含一个针对这个灯的操作（如开灯），这样添加成功后就会显示在列表了；如果与设备部相关，退出插件，在首页的“智能” tab下“我的”那一页可以看到你成功添加的智能场景
