### ISSUE TITLE
图片绑定的state值变化时，图片进行替换会闪烁

### ISSUE THREAD

**Issue by jimu380261652** [MiEcosystem/miot-plugin-sdk#1342]
**是否为新品（必填）**
新品,米家系列

**关联的产品model**
viomi.dishwasher.m01

**项目ID（必填）**
P18-0300

**企业名称（必填）**
佛山云米电器科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 9.0
- SDK分支: 10023
- 相关模块:Account

**现象（必填）**
童锁状态只有开和关两种，点击童锁按钮直接setState置反child_lock属性切换相应状态的图片时，童锁按钮图片会闪一下
![下载](https://user-images.githubusercontent.com/11864517/62524171-bb98b400-b867-11e9-9559-7d65badcfc6d.gif)

**期望（必填）**
setState切换状态值时，与之绑定的图片不会闪烁，图片能柔和过渡(小米UI负责人反馈过来的要求)

**不要贴大段代码❗️**
现在的实现代码如下
```
getSwitchIcon() {
        if (this.state.child_lock === 0)//童锁功能关闭
            return (require('../Resources/key_gray.png'));
        else {
            if (this.state.wash_process === Global.PR_NO_RUN)
                return (require('../Resources/key_cyan.png'));
            else if (this.state.wash_process === Global.PR_YUXI)
                return (require('../Resources/key_cyan.png'));
            else if (this.state.wash_process === Global.PR_ZHUXI)
                return (require('../Resources/key_blue.png'));
            else if (this.state.wash_process === Global.PR_PIAOXI)
                return (require('../Resources/key_green.png'));
            else if (this.state.wash_process === Global.PR_HONGGAN)
                return (require('../Resources/key_red.png'));
        }
    }
<Image source={this.getIcon()}/>
```

**Comment by zanetti4** [comment]
@LiuMengzhou 我在10025分支修改了 com.xiaomi.demo/Main/UIComponent/CardPage.js，添加了一个可以切换图片的卡片。但是点击时图片也会闪烁，能做到更柔和地过度吗？请帮忙查看

**Comment by jimu380261652** [comment]
不符合小米的要求，在安卓手机上闪烁得很厉害
