### ISSUE TITLE
Android平台上调起软键盘，整个页面都会随着软键盘被往上推

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#1343]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 8.1]
- SDK分支: [SDK_10023]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android平台上，当调起软键盘，整个页面都会被软键盘往上推，iOS页面会往上推，但导航栏固定不动。
尝试过使用scrollview包裹，iOS是可以的，但Android还是不行。
试了一些方法，Android在manifest文件里加上：`android:windowSoftInputMode=“adjustResize|stateHidden”`
就可以了。

**期望（必填）**
提供一个属性或者接口，当Android调起软键盘时，可以设置页面不会被往上推。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46777658/62524639-90629480-b868-11e9-92c6-0cd37adfd093.png)
![image](https://user-images.githubusercontent.com/46777658/62524660-98bacf80-b868-11e9-8209-bb13125ed5b6.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by mirse** [comment]
想知道怎么解决

**Comment by lvjie0519** [comment]
@WeizhiKong   @mirse   如果支持整个页面不往上推， 岂不是存在软键盘会挡住输入框的可能？ 整个页面推上去，有什么不好的情况吗？

**Comment by mirse** [comment]
我的理解是页面可以上推，但是状态栏位置应该不动   @WeizhiKong 你的理解呢？

**Comment by lvjie0519** [comment]
@WeizhiKong  @mirse   情况了解了，  我这边修复，考虑用scrollview包裹，修复及时反馈。

**Comment by WeizhiKong** [comment]
好的，多谢老板

**Comment by lvjie0519** [comment]
@WeizhiKong @mirse   已修复，请使用最新apk， sdk 选择10027分支， Host.pageShouldAdapterSoftKeyboard，  可以参考 SoftKeyboardAdapterTestDemo.js 文件
