### ISSUE TITLE
被分享的用户调用  Host.ui.openPrivacyLicense，弹出隐私确认弹框无反应

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#1344]
**是否为新品（必填）**
 新品 

**关联的产品model**
lock.dsm.h3

**项目ID（必填）**
com.dsm.q3

**企业名称（必填）**
德施曼

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: master]
- 相关模块:[Host]

**现象（必填）**
被分享的用户在首页调用Host.ui.openPrivacyLicense   这个接口完全没有反应，正常应该弹出那个隐私协议确认弹窗的。设备主的话是能够弹出的。。。。
看了core进程下的日志，什么也没有打印。

**期望（必填）**
被分享的用户调用这个接口应该像设备主一样，能够正常的弹出隐私确认弹窗

**Comment by lvjie0519** [comment]
@changgongxinshi   被分享的用户， 是不会弹出 隐私对话框的，设计如此。
