### ISSUE TITLE
新版本的打包上线流程跟之前的步骤一致吗?

### ISSUE THREAD

**Issue by shanchaojie** [MiEcosystem/miot-plugin-sdk#135]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

需要打包上线进行白名单测试,是否当前版本的打包上线流程与之前的一致.使用python packagePluginAndSign com.xxx.yyy.zzz private.pempublic.cer 123456 这样的命令进行打包操作.

#### 期望

需要打包上线进行白名单测试,但不知道是否当前版本的打包上线流程与之前的一致.

#### 尝试过的解决办法

无

**Comment by blockdate** [comment]
目前暂不支持上线进行白名单测试，我们会尽快处理。
