### ISSUE TITLE
反馈问题页面内容输入为空可提交成功

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#1358]
**是否为新品（必填）**
在售

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android/iOS]
- SDK分支: [SDK_10023]
- 相关模块:[CommonSetting]

**现象（必填）**
反馈问题为空，可提交成功
Step1: 通用设置--使用帮助–反馈问题
Step2: 反馈问题页面内容输入为空，点击提交，提交成功

**期望（必填）**
增加空值提交的判断逻辑，具体交互定义请米家相关产品经理确定。

**Comment by fishle** [comment]
看这里的逻辑，如果勾选了"发送问题日志"，反馈描述可以为空的~

**Comment by lvjie0519** [comment]
@CJackKao  反馈模块之前设计如此，以勾选了"发送问题日志" 为主，内容可以为空，如果感觉设计不合理，可以与我们这边产品进行沟通，提需求，这里暂且关闭，谢谢。
