### ISSUE TITLE
SDK里未找到打开Toast相应方法

### ISSUE THREAD

**Issue by Aub1nLin** [MiEcosystem/miot-plugin-sdk#136]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- 相关模块:[ui]

#### 现象

简单明了地描述一下实际的现象。
SDK内未找到旧版SDK内的 弹出Toast的方法，例如： 
MHPluginSDK.showFailTips 
showFinishTips，
showLoadingTips

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by dingshaoran** [comment]
请参考 messageDialog,文案按您的需求设置

**Comment by LiuMengzhou** [comment]
@Aub1nLin 为了两个平台的统一，之后将不再提供`showFailTips`, `showFinishTips`和`showLoadingTips`这三个接口。可以按需求使用`miot/ui`中的`InputDialog`, `LoadingDialog`和`MessageDialog`。
