### ISSUE TITLE
在首页选择两个插座并添加桌面快捷方式，实际只添加了一个插座的快捷方式

### ISSUE THREAD

**Issue by dengdeng223** [MiEcosystem/miot-plugin-sdk#1361]
---
是否为新品（必填）
填 新品

关联的产品model
model:lumi.plug.mmeu01

项目ID（必填）
项目ID: 21100

企业名称（必填）
绿米

环境（必填）
欧洲服务器

电脑操作系统:[eg.Windows10
手机系统:[eg.Android]
SDK分支: [10022]
相关模块:【桌面快捷方式】

操作步骤：1、在手机APP的设置中已开启添加快捷方式的权限

2、安卓手机进入米家APP，在首页长按欧标插座，并选择两个欧标插座后再点击添加桌面快捷方式

 

预期结果：添加两个桌面快捷方式

实际结果：只添加了一个快捷方式（最后选择的那个）

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by dengdeng223** [comment]
[1.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3475559/1.zip)

**Comment by lvjie0519** [comment]
@dengdeng223    设备名称是否相同了？  如果相同确实只能添加一个，这个是系统决定了。

**Comment by dengdeng223** [comment]
> @dengdeng223
> 1、我这边测试两个不同设备时正常的，请使用最新apk测试下；
> 2、设备名称是否相同了？ 如果相同确实只能添加一个，这个是系统决定了。

设备名称是相同的

**Comment by lvjie0519** [comment]
@dengdeng223   设备名称相同，确实只能添加一个，这个系统决定了，无法实现，已知问题，之前也有开发者提issue，无法支持，谢谢。
