### ISSUE TITLE
Dialog扩展

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#1362]
**是否为新品（必填）**
新品 

**企业名称（必填）**
飞彗

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Dialog类的所有组件点击蒙版不会消失

**期望（必填）**
所有的Dialog组件，增加一个点击蒙版就会消失的功能，没必要非要点击确定或者取消才会消失

**Comment by LiuMengzhou** [comment]
老铁，点空白处是可以dismiss的

**Comment by devYoungyang** [comment]
老铁，1023版本MessageDialog点击空白并不会dismiss啊。也没有见点击空白处的回调啊  @LiuMengzhou

**Comment by devYoungyang** [comment]
@LiuMengzhou 说个话呀，xiongdi

**Comment by LiuMengzhou** [comment]
`miot/ui/Dialog/xxxDialog`
你再试试吧。
