### ISSUE TITLE
在欧洲服务器下，米家访问了一个新加坡服务器（http://sg.stat.appmifile.com）

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#1363]
**是否为新品（必填）**
新品

**关联的产品model**
soocare.toothbrush.m1s

**项目ID（必填）**
P18-0138

**企业名称（必填）**
舒可士（深圳）科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android国际版
- SDK分支: master
- 相关模块:

**现象（必填）**
（测试反馈）在欧洲服务器下（法国），插件访问了一个新加坡服务器（http://sg.stat.appmifile.com）

访问新加坡服务器路径复现步骤如下：
【预置条件】：Android手机国际版，用chales设置好端口，Android国际版手机设置好代理
【步骤】:进入T500插件内部——点击右上角进入设置页——进入“法律信息”查看“用户协议/隐私政策”——chales界面出现新加坡域名http://sg.stat.appmifile.com
![image](https://user-images.githubusercontent.com/7885251/62603186-f19d6d00-b927-11e9-955b-65aba3378f63.png)

注：
1、进入法律信息我们插件调用的是 Host.ui.privacyAndProtocolReview 加载的本地Html文件
2、米家登录、首页进入插件也会出现访问新加波域名的情况

**期望（必填）**
产品软件、固件只能和当前设备绑定的MIOT服务器交互。

**Comment by fishle** [comment]
1) 请给出完整的请求和响应信息
2）“产品软件、固件只能和当前设备绑定的MIOT服务器交互”----这个是小米IoT的规则？

**Comment by JxXiaoXie** [comment]
1、 请给出完整的请求和响应信息
------------------------------------------------------------------------
<img width="900" alt="image" src="https://user-images.githubusercontent.com/7885251/62684588-8b7e1c00-b9f3-11e9-94e7-c6560a99047b.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/7885251/62683396-e82c0780-b9f0-11e9-9df9-8a7ed0fe22c1.png">

<img width="900" alt="image" src="https://user-images.githubusercontent.com/7885251/62684682-c6804f80-b9f3-11e9-8aa0-1416c2531c13.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/7885251/62684708-d861f280-b9f3-11e9-9333-6165a16c7c2a.png">

2、“产品软件、固件只能和当前设备绑定的MIOT服务器交互”----这个是小米IoT的规则？
----------------------------------------------------------------------------------------------
这句话是米家测试邮件说的，我只是转述。
<img width="645" alt="image" src="https://user-images.githubusercontent.com/7885251/62684822-12cb8f80-b9f4-11e9-87af-f03e5f77ef5c.png">

**Comment by fishle** [comment]
麻烦把设备分享给894158105

**Comment by JxXiaoXie** [comment]
> 麻烦把设备分享给894158105

设备已共享

**Comment by fishle** [comment]
还没收到；
设备名是是什么？；米家APP的设置里面，地区是“中国”吗

**Comment by fishle** [comment]
打不开你的插件

**Comment by JxXiaoXie** [comment]
我已经把你加进产品白名单了，你再试试

**Comment by fishle** [comment]
Android手机国际版 是指Google原生rom吗，还是只用改手机系统语言？
国内的Android手机有这个问题吗？

**Comment by JxXiaoXie** [comment]
Android手机国际版 是指Google原生rom吗，还是只用改手机系统语言？
------------------------------------------------------------------------------
小米手机，直接在小米官网下载的国际版MIUI系统（有谷歌商店）

国内的Android手机有这个问题吗？
------------------------------------------------------------------------------
测试小米手机国内版MiUI系统没有出现

**Comment by fishle** [comment]
这边抓包看，应该是米家的一个上报的请求，别的插件也有这个请求发出来，国内版MIUI一样会发出来，只要地区设置为法国

**Comment by JxXiaoXie** [comment]
这样，那你们能处理这个问题吗？

**Comment by fishle** [comment]
你们先跟米家测试解释一下试试

**Comment by fishle** [comment]
你让米家的测试测一下别的公司的设备，切换服务器是不是也存在这个问题。如果都有这个问题，就让他们推动小米统计的人改了

**Comment by JxXiaoXie** [comment]
好的
