### ISSUE TITLE
蓝牙mesh开关的通用设置中的”按键设置“功能异常

### ISSUE THREAD

**Issue by fergus825** [MiEcosystem/miot-plugin-sdk#1364]
**是否为新品（必填）** 
新品(在售) 
**关联的产品model** 
chuangmi.switch.mesh、chuangmi.switch.meshb01、chuangmi.switch.meshc01
项目ID（必填） 
【无项目ID】
**企业名称**
 创米科技
**环境**
 电脑操作系统:Mac OS 10.14.5 
手机系统:Android 9.0 SDK分支: 10025
相关模块:[UI/CommonSetting]

**现象** 
本产品为蓝牙mesh开关，上面三个model分别为单开，双开，三开的开关。因此对应产品的”按键设置“应该可以分别设置每个开关的名称。目前打开三个产品的按键设置都是如下图所示，并且没法修改按键名称。
期望（必填）
单开、双开、三开的开关”按键设置“中可以显示对应的开关并且可以编辑开关的名称。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/25863361/62606851-a4bd9480-b92f-11e9-89db-5ca6a571b1ee.png)

**尝试过的解决办法**
升级到最新的debug版米家，IOS版本的也测过，现象一样。

**Comment by fishle** [comment]
把这三个设备分享到 894158105

**Comment by fergus825** [comment]
> 把这三个设备分享到 894158105

已经分享。谢谢！

**Comment by fishle** [comment]
按键设置的入口在哪里？

**Comment by fergus825** [comment]
> 按键设置的入口在哪里？
在右上角的设置里，不过米家的设置对分享用户是隐藏的...

**Comment by fergus825** [comment]
> 按键设置的入口在哪里？
在右上角设置中的通用设置里。之前的版本有问题，刚刚新传了个版本。麻烦你再看看 。

**Comment by fishle** [comment]
多开关的还是看不到通用设置

**Comment by fergus825** [comment]
我把双开的分享给我同事了，但是通用设置中的”按键设置“是直接对分享用户隐藏的。所以得用主账号绑定调试。

**Comment by fergus825** [comment]
> 多开关的还是看不到通用设置

我把”开关设置“挪到设置-功能设置中了。刚刚传了一个新的版本。等会你再看下。点击主页的设备名称，版本号应该为5。

**Comment by fishle** [comment]
这边看到那个双键的开关，获取到的设备信息只有一个开关

{
    "page_pic": "http://static.home.mi.com/app/image/get/file/developer_1561965729p355qor4.png",
    "members": [
        {
            "id": 1,
            "name": "empty",
            "icon": "",
            "ai_desc": ""
        }
    ]
}

**Comment by fishle** [comment]
麻烦先检查配置，确认无误后，如果还不正常，再打开~
