### ISSUE TITLE
泰语弹出法律信息只显示用户协议 不显示隐私政策 其他语言都显示

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#1365]
高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决

是否为新品（必填）
在售

关联的产品model
chunmi.kcooker.normal2

企业名称（必填）
上海纯米电子科技有限公司

环境（必填）

电脑操作系统:[Mac]
手机系统:[iOS 12]
SDK分支: [SDK_10022]
现象（必填）
泰语弹出法律信息只显示用户协议 不显示隐私政策 其他语言都显示

期望（必填）
泰语弹出法律信息能同时显示用户协议和隐私政策 

![image-2019-08-02-13-27-27-327](https://user-images.githubusercontent.com/34296463/62610781-ebfb5380-b936-11e9-9eec-f661da20c7d6.png)

**Comment by santcool** [comment]
我看这个，泰语的用户协议和隐私政策文字显示出来了，应该是中间少一个”和“

**Comment by joyami** [comment]
那麻烦帮忙加下 谢了！

**Comment by santcool** [comment]
已修复，预计今天会出新包
