### ISSUE TITLE
Image控件支持设置图片放大插值策略

### ISSUE THREAD

**Issue by kyou** [MiEcosystem/miot-plugin-sdk#137]
---

#### 环境
- 相关模块:[UI]Image

#### 现象

路径Image放大后显示效果不好

#### 期望

Image能支持类似iOS的CALayerContentsFilter类型的magnificationFilter

**Comment by santcool** [comment]
已提供，参见MHImage
```
 layerScaleFilter: PropTypes.oneOf([
      'Nearest',
      'Linear',
      'Trilinear'
    ]),
```
