### ISSUE TITLE
MHXiaomiBLE.secureTokenMD5 缺失

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#138]
#### 现象

新版 sdk 是否不再提供？什么原因？

**Comment by caojunhua** [comment]
非官方技术交流群，有兴趣的小伙伴可以进来共同探讨问题
![wechatimg261](https://user-images.githubusercontent.com/18459414/49862396-11cc6900-fe39-11e8-8975-48692ce24c42.jpeg)

**Comment by dingshaoran** [comment]
请说明你的用途

**Comment by halloaw** [comment]
之前提供这个接口是为了标识设备从绑定到解绑的生命周期。与 `MHPluginSDK. getUserConfigs` 配合来存设备的自定义数据。那时候还没有 `MHPluginSDK. deviceToken`，也没有 `MHPluginSDK. callSmartHomeAPI('/device/setsetting', params, callback)`。

有个解决方案是更新旧插件来迁移数据。有个问题是只能迁移活跃用户的数据。

**Comment by Copypeng** [comment]
使用 Device 中的 session 属性
