### ISSUE TITLE
关于deviceStatusChanged事件问题

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#14]
该事件deviceStatusChanged可以指定要监听的设备property么？类似旧SDK的设计。https://github.com/MiEcosystem/ios-rn-sdk/blob/c72038bd70f8cbbd7935abf420fb123dc87893d9/MiHomePluginSDK/docs/MHPluginSDK.md

// 假设采用订阅方式，需在 key 之前加前缀，属性为 prop.xxx, 事件为 event.xxx
MHPluginSDK.registerDeviceStatusProps(["prop.rgb","prop.power","event.isOn"]);

// 若采用轮询方法，则无法轮询事件，只能查询 prop，直接填入 key
// MHPluginSDK.registerDeviceStatusProps(["rgb","power"]);

// 记得初始化 DeviceEventEmitter
const {DeviceEventEmitter} = require('react-native');
// 监听
let subscription = DeviceEventEmitter.addListener(MHPluginSDK.deviceStatusUpdatedEventName,(notification) => {

 // 从device属性的内存缓存中拿到轮询的状态结果，同样，订阅需要添加前缀，轮询不用
 MHPluginSDK.getDevicePropertyFromMemCache(["prop.rgb","prop.power","event.isOn"], (result) => {
   console.log(result);
 });

});

**Comment by JobenTian** [comment]
@TheWalkingDead2 你的deviceStatusChanged监听，有事件过来吗？我改变设备状态时（播放/暂停/禁用/启用麦克风），都没有事件过来。可以把你的这段代码贴出来看一下吗？谢谢！
