### ISSUE TITLE
IOS连接问题

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#140]
检查过文档了
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]

#### 现象

我是iOS开发，
在获取系统的BLE设备时候以前是这个接口
retrieveConnectedPeripheralsWithServices(identifiersk,callback(peripherals))
通过服务ID拉取的

现在就提供了
 Bluetooth.retrievePeripheralsForIOS(["PeripheralUUID1","PeripheralUUID2","PeripheralUUID3"])
通过外设拉取，没有找到获取外设的接口
#### 期望
提供retrieveConnectedPeripheralsWithServices接口，并有相关的demo，谢谢

**Comment by Handby** [comment]
+1

**Comment by caojunhua** [comment]
非官方技术交流群，有兴趣的小伙伴可以进来共同探讨问题
![wechatimg261](https://user-images.githubusercontent.com/18459414/49862396-11cc6900-fe39-11e8-8975-48692ce24c42.jpeg)

**Comment by Copypeng** [comment]
开放出来也可以，本周再增加一个对应方法吧。

**Comment by Handby** [comment]
@kasparovfeng @Copypeng 长连接可以连接成功但是没有发现service和chara.

**Comment by Copypeng** [comment]
拿到 ID 的同时，返回了相关数据吧。是后续调用什么接口没符合预期？

**Comment by Handby** [comment]
拿到identify里面是一个字典。我的想法是拿到以后再连接蓝牙外设，跟普通连接一样，发现service和character，但是后续调用startdiscoverservice之后在监听里没有发现service，不知道是不是我的用法有问题？

**Comment by Handby** [comment]
现在可以发现services了吗？

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/50746245-0ec26e00-1269-11e9-9a76-bc2cdd0f84dd.png)

**Comment by kasparovfeng** [comment]
没有服务。。。。走不下去了

**Comment by kasparovfeng** [comment]
@Copypeng

**Comment by blockdate** [comment]
之前蓝牙连接仅支持rootdevice，现在已开放该限制，更新SDK与iPA使用。
该issue版本过旧，现关闭。如任然有问题，请重新创立issue处理。

可能查看 #178
