### ISSUE TITLE
Host.file.screenShotInRect 问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#142]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 
- 相关模块:Host

#### 现象

<img width="792" alt="image" src="https://user-images.githubusercontent.com/7885251/49909872-9790f880-febb-11e8-8a71-a375bbab02cd.png">
执行上方代码，没有回调结果，而是报了一个警告，如下：

![image](https://user-images.githubusercontent.com/7885251/49910416-98c32500-febd-11e8-8617-9a0b8d8a955e.png)

#### 期望

正常截取图片并保存，正常回调保存的路径。

**Comment by LiuMengzhou** [comment]
Duplicate of #143
