### ISSUE TITLE
Host.ui.openShareListBar 问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#143]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Host

#### 现象

**1、执行代码**
<img width="851" alt="image" src="https://user-images.githubusercontent.com/7885251/49910123-78469b00-febc-11e8-830f-0b9e4147bbbe.png">
alert有打印图片保存的路径，但是执行Host.ui.openShareListBar方法的时候报下方警告，也没有分享界面弹出。
![image](https://user-images.githubusercontent.com/7885251/49910202-c360ae00-febc-11e8-966c-8425ea9bd548.png)

**2、执行代码**
<img width="647" alt="image" src="https://user-images.githubusercontent.com/7885251/49910364-65809600-febd-11e8-9d90-5a634f268c2d.png">
报错：
![image](https://user-images.githubusercontent.com/7885251/49910373-716c5800-febd-11e8-8a2c-6769f73505f8.png)

#### 期望
不报错，正常弹出分享页面。

**Comment by LiuMengzhou** [comment]
@JxXiaoXie 1. 是最新的SDK吗？

**Comment by JxXiaoXie** [comment]
嗯，试了下Host.file.screenShot可以了，但是Host.file.screenShotInRect还不行，没有回调，报下方警告，最新SDK。
![image](https://user-images.githubusercontent.com/7885251/49980603-173bc780-ff8f-11e8-8edf-08d674ee0689.png)
