### ISSUE TITLE
Host.ui.openShopPage 问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#144]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Host

#### 现象

执行代码：
<img width="537" alt="image" src="https://user-images.githubusercontent.com/7885251/49910622-5817db80-febe-11e8-82a6-9c208113602c.png">

报错：
![image](https://user-images.githubusercontent.com/7885251/49910652-7da4e500-febe-11e8-832a-f7ec54e5da12.png)

#### 期望

正常打开商品购买页

**Comment by blockdate** [comment]
duplicate with #63 ,更新SDK使用
