### ISSUE TITLE
从云端加载属性数据

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#145]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[.Windows]
- 手机系统:[Android 7.1]
- 相关模块:[Device]

#### 现象

从云端获取数据是否有设置循环的方法
目前在文档中找到loadPropertiesFromCloud(…propNames) → {Promise.<Map>}
但好像只能获取一次。

#### 期望

希望可以每隔N(秒)，从云端获取数据

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by laohuang88** [comment]
请使用getDeviceWifi().subscribeMessage(...)来订阅属性变化事件，而不是轮询。如果轮询，可自行实现。

**Comment by mirse** [comment]
getDeviceWifi().subscribeMessage(...)  这个方法是属性变化时才能获取吗？
还有getDeviceWifi()貌似用不了
![img_20181213_150212](https://user-images.githubusercontent.com/5188922/49921367-4c410f00-fee8-11e8-8b6b-7f7e725b89d8.jpg)

**Comment by mirse** [comment]
getDeviceWifi().subscribeMessage(...) 这个方法是属性变化时才能获取吗？

**Comment by laohuang88** [comment]
是的，在此之前应该做一次loadProperties

**Comment by Aub1nLin** [comment]
> 是的，在此之前应该做一次loadProperties

请问你们这个方法需要怎么做？文档写的不明白。是否是如下这样？
先定义prop
Device.getDeviceWifi().subscribeMessages("power");
然后
this._getDeviceStatus = DeviceEvent.deviceReceivedMessages.addListener(
         (device, messages)=>{
       Device.getDeviceWifi().loadProperties
 });

**Comment by laohuang88** [comment]
loadProperties就是callMethod("get_props", ...), 是主动拉取属性数据， 而订阅是可以之后监听属性变化以更新属性，返回的消息会带有你需要的数据， 当然这个时候你主动再拉取数据也可以的，就是多了一次请求。

**Comment by mirse** [comment]
Device.getDeviceWifi().subscribeMessages("power").then(subcription=>{
              msgSubscription = subcription;
         });

     const subscription = DeviceEvent.deviceReceivedMessages.addListener(
             (device, messages)=>{
           if(messages.has('power')){
                  const power = messages.get('power');
                  console.warn(power)
                //  ...
               }

         })


使用了如上代码，在变化时并未受到消息，是什么问题呢？

**Comment by laohuang88** [comment]
subscribeMessages("prop.power").then(...)

因为还存在自定义的event.myeventname

**Comment by mirse** [comment]
目前试了一下，就prop.power可以监听到变化，其余属性如prop.dv，prop.bright 等都监听不到变化

**Comment by laohuang88** [comment]
本质上prop.xxx是一个事件，需要你们的固件实现了相关功能才可以，所以请先跟你们的硬件工程师们沟通一下？

**Comment by mirse** [comment]
DeviceEvent.deviceReceivedMessages.addListener监听事件目前只能监听到几个属性得变化，并且在ios上能完美监听到那几个属性，但是在安卓上只有部分机型可以监听到（小米5，红米4x），一加3和努比亚Z17s监听不到任何数据变化。

**Comment by UnaMattinaDev** [comment]
> DeviceEvent.deviceReceivedMessages.addListener监听事件目前只能监听到几个属性得变化，并且在ios上能完美监听到那几个属性，但是在安卓上只有部分机型可以监听到（小米5，红米4x），一加3和努比亚Z17s监听不到任何数据变化。

我的问题刚好相反..Android上都能收到，iOS上收不到任何消息

**Comment by nealelin** [comment]
我也遇到同样问题,更新SDK后, Android上都能收到，iOS上收不到任何消息,

甚至在IOS分享给Android后, Android上都能收正常监听设备,但当IOS操作APP后,数据能传到设备,但会造成Android 数据无法再同步更新监听,须退出再重进就可恢复监听

**Comment by blockdate** [comment]
属性订阅问题已修复，参考 #224 。

@nealelin 属性订阅采用push订阅，不支持多端同时订阅。
