### ISSUE TITLE
网络连接问题

### ISSUE THREAD

**Issue by Aub1nLin** [MiEcosystem/miot-plugin-sdk#147]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- 相关模块:[Service]

#### 现象
调用Deveice的callMathod，常常会报错，如下图。
 Device.getDeviceWifi().callMethod("set_bright", 100).then( json => { });

![image](https://user-images.githubusercontent.com/45021910/49924125-5ff07380-fef0-11e8-9918-3c5aba4d1e88.png)

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Aub1nLin** [comment]
还有一个就是，
我原来用的这个方法
   MHPluginSDK.callSmartHomeAPI('/user/get_user_coll', params, (response) =>{})

现在用哪个？Service.smarthome.getDeviceData ？用这个？

**Comment by blockdate** [comment]
1.处理中，需要等待ipa更新
2.请说明下user/get_user_coll 接口的用处，我们这边需要确认如何提供

**Comment by blockdate** [comment]
@Aub1nLin 确认个问题，您使用的设备是属于什么设备呢，是由网关控制的子设备，还是其他类型的。

**Comment by Aub1nLin** [comment]
> @Aub1nLin 确认个问题，您使用的设备是属于什么设备呢，是由网关控制的子设备，还是其他类型的。

我的是灯泡，用来获取用户收藏的情景。点击情景，灯会执行相应的色温与亮度。

**Comment by blockdate** [comment]
@Aub1nLin 您的设备应该是属于子设备，向子设备发送rpc请求，最终会发送到配网父设备，根据父设备协议不一样，参数会有变化，例如有些父设备需要参数第一个为子设备的did，有一些需要特别定制，请您提供下旧版本下使用方式，同时确认下父设备交互子设备的参数设定。

2. user/get_user_coll 该方法已添加至smarthome，文档已更新，使用getUserColl。

**Comment by LiuMengzhou** [comment]
Duplicate of #104

**Comment by Aub1nLin** [comment]
@blockdate 已更新SDK（APP与开发环境），但是运行仍然会报错（如下图）。另外，除了读取收藏，还要创建收藏（代码如下）的需求
原SDK中 
 MHPluginSDK.callSmartHomeAPI('/user/set_user_coll',  {"did":MHPluginSDK.deviceId, //设备id
            "name":name, //收藏名称
            "content":sub , //收藏的内容，可自行定义，只要保证整体是string，否则接受不到数据
        })

和以及删除收藏（代码如下）的需求
原SDK中
MHPluginSDK.callSmartHomeAPI('/user/del_user_coll', {
            "coll_id":coll_id, //收藏id
            "did":MHPluginSDK.deviceId
        })


也请麻烦加入这些功能。
![image](https://user-images.githubusercontent.com/45021910/50129483-10c18e80-02b4-11e9-9c77-43aef81c11b7.png)

![image](https://user-images.githubusercontent.com/45021910/50129496-23d45e80-02b4-11e9-8d3d-357713cc8be4.png)

![image](https://user-images.githubusercontent.com/45021910/50129523-42d2f080-02b4-11e9-96c6-2f9088148424.png)

**Comment by blockdate** [comment]
@Aub1nLin 
剩余的几个收藏接口已添加。

同时，我这边使用使用接口是ok的，请确认SDK已更新，或者尝试 ``` npm start --reset-cache ```  
一下是我的测试情况
```
Service.smarthome.getUserColl({did:Device.deviceID})
      .then(val => console.log("getUserColl success: ", val))
      .catch(err => console.log("getUserColl failed:", err))
```
日志：
![image](https://user-images.githubusercontent.com/4339364/50152519-c6193400-02fe-11e9-8df3-63688b7c8d99.png)

**Comment by Aub1nLin** [comment]
@blockdate 收藏、删除、获取情景已经可用。感谢。能否麻烦增加在方法执行后的回调呢，我们的业务逻辑需要判断是否执行成功，再进行下一步操作。
原来的SDK中，
MHPluginSDK.callSmartHomeAPI('/user/get_user_coll', get_user_coll_params, (response) =>{
                    if (response.message == 'ok'){
                    //code

})

**Comment by Aub1nLin** [comment]
@blockdate  set的时候会报错。。。Android iOS都有！
![image](https://user-images.githubusercontent.com/45021910/50336669-a9bd0780-0549-11e9-9840-22b280196e70.png)
![image](https://user-images.githubusercontent.com/45021910/50336713-c5c0a900-0549-11e9-90e6-c68f0223a839.png)

**Comment by blockdate** [comment]
@Aub1nLin 根据错误提示为did未设置，deviceID 的获取请使用Device.deviceID。参见相应接口文档https://miecosystem.github.io/miot-plugin-sdk/module-miot_Device-IDevice.html

同时 接口的成功promise一般情况下都是操作ok并返回result了，如果的确出现了操作失败却进入成功的then回调，请及时反馈我们会进行确认以及调整
