### ISSUE TITLE
安卓蓝牙模块 bluetoothStatusChanged 和 bluetoothConnectionStatusChanged  连续收到两次通知。

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#148]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- 相关模块:Bluetooth

#### 现象

BluetoothEvent.bluetoothConnectionStatusChanged 监听收到了两次通知。发现监听蓝牙开关接口 BluetoothEvent.bluetoothStatusChanged 也有同样的问题。

#### 期望
安卓这边的设计就是如此吗？
因为按照我的理解，如果断开直接返回一条带 false 结果应该就行了。

#### 其他的上下文/日志/截图
添加监听
```
BluetoothEvent.bluetoothConnectionStatusChanged.addListener((mac, isConnect) => {
            console.log("bluetoothConnectionStatusChanged", isConnect);
        })

```
今天记录的日志内容
```
12-13 16:34:22.692 32357   659 I ReactNativeJS: 'bluetoothConnectionStatusChanged', false
12-13 16:34:22.839 32357   659 I ReactNativeJS: 'bluetoothConnectionStatusChanged', false
```

**Comment by dingshaoran** [comment]
回调同一个值的情况，比如您附加的日志两次 false，这种问题从app 里已经屏蔽了。

**Comment by ftc300** [comment]
我的意思是，我需要第二次的返回值，这样可以处理连接蓝牙断开或者连接的相关业务逻辑，现在的返回值都是 {} 。
而且我也需要蓝牙开关状态的通知**bluetoothStatusChanged** 这个好像还没有处理。

**Comment by lvjie0519** [comment]
@ftc300  您好，使用目前最新版本apk，  还有如上问题吗？
https://fir.im/MiHomeForAndroid

**Comment by ftc300** [comment]
还是存在

**Comment by blockdate** [comment]
这个问题应该在SDK上处理了，这边建议更新apk与SDK，如果问题任然存在，及时回复

**Comment by edwardair** [comment]
bluetoothStatusChanged Android端连续收到2次通知 问题+1
apk：5.5.30 线上版
SDK为master 最新（10020）

比如关闭蓝牙，会收到2次false，
打开蓝牙，会收到一次 false ，然后一次true

麻烦再次确认下米家APP是否已做处理
@blockdate

**Comment by edwardair** [comment]
android V5.5.37测试 bluetoothStatusChanged 回调仍旧执行2次，请问修复进入如何？

**Comment by lvjie0519** [comment]
@edwardair  计划这周排期解决。

**Comment by lvjie0519** [comment]
@dingshaoran   帮忙看看蓝牙问题，谢谢。

**Comment by lvjie0519** [comment]
@ftc300  @edwardair  请使用最新apk进行测试，如果问题仍然存在，请使用 “miot-rn-plugin” 过滤下原生层打印出的log日志，谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，如果有问题再reopen。
