### ISSUE TITLE
iOS蓝牙重连错误

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#150]
### SDK 最新

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12]
- 相关模块:Bluetooth

#### 现象

iOS平台（android测试正常）：
当蓝牙处于连接状态，关闭“系统蓝牙开关”，蓝牙断开，然后再打开“系统蓝牙开关”，当接收到BluetoothEvent.bluetoothStatusChanged为enable后，开始重连 bt.connect(-1)，返回连接成功，**_但其实蓝牙并没有连上_**

#### 期望

重连能正确连接

**Comment by Copypeng** [comment]
我们测试一下。

**Comment by edwardair** [comment]
这个测试怎么样了？ @Copypeng

**Comment by edwardair** [comment]
@LiuMengzhou @dingshaoran @kyou @Copypeng 请问目前问题解决进度怎样？

**Comment by Copypeng** [comment]
一天前两端测试均可以，更新一下SDK。

**Comment by edwardair** [comment]
新版本测试正常了
