### ISSUE TITLE
Dialog标题多语言显示不全

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#1500]
---
**是否为新品（必填）**
新品

**关联的产品model**
lumi.gateway.mgl03

**项目ID（必填）**
22538

**用户ID（必填）**
840907289

**企业名称（必填）**
深圳市绿米联创科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10025/...]
- 相关模块:[eg.miot/ui/Dialog/ChoiceDialog]

**现象（必填）**
Dialog标题多语言显示不全，看AbstractDialog代码里面指定numberOfLines={1}，但是多语言时的文案很长，超过一行，显示成省略号了

**期望（必填）**
Dialog标题能全部显示

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/41932871/63903932-d9f66780-ca41-11e9-8d08-b015554920a0.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
UI设计师规定一行
