### ISSUE TITLE
iOS点击通知栏通知跳转插件提示“拉取资源包配置信息的网络请求的没有得到响应”

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#1502]
---
**是否为新品（必填）**
新品

**关联的产品model**
lumi.sensor_smoke.acn01

**项目ID（必填）**
无项目ID

**用户ID（必填）**
840907289

**企业名称（必填）**
贵司的名称

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.iOS 12.4]
- SDK分支: [eg.master/10025/...]

**现象（必填）**
点击通知栏的推送消息，跳转到插件页，会出现提示“拉取资源包配置信息的网络请求的没有得到响应”，实际上已经成功跳转到插件内了

**期望（必填）**
点击通知栏的推送消息，跳转到插件页，没有异常提示

**其他的上下文/日志/截图**
![IMG_7DF04A4D2C91-1](https://user-images.githubusercontent.com/41932871/63909548-a4f41000-ca55-11e9-952f-3178a83450ea.jpeg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
请提供抓包信息，谢谢！

**Comment by santcool** [comment]
有网络请求失败了，Debug下才有这个问题，线上包不会有这个问题。
