### ISSUE TITLE
Android正式版米家apk设置界面缺少设备共享、智能场景、固件升级三项，Android测试版正常

### ISSUE THREAD

**Issue by flztsxsy** [MiEcosystem/miot-plugin-sdk#1503]
**是否为新品（必填）**
新品

**关联的产品model**
miaomiaoce.blanket.d02

**项目ID（必填）**
【无项目ID】

**用户ID（必填）**
1262449973

**企业名称（必填）**
秒秒测科技(北京)有限公司
**环境（必填）**
- 电脑操作系统:[Windows10]
- 手机系统:[Android 8.1]
- SDK分支: [10022]
- 相关模块:[.Host/Service/Account]

**现象（必填）**
Android正式版米家apk设置界面，通用设置下面缺少设备共享、智能场景、固件升级三项，Android的测试版apk正常。见下图。IOS的正式版和测试版均正常
![Android正式版apk](https://user-images.githubusercontent.com/49407658/63914427-c2c97100-ca65-11e9-9e73-e1282c7a9cdc.png)
![Android测试版apk](https://user-images.githubusercontent.com/49407658/63914435-c8bf5200-ca65-11e9-8b68-b1915da9a2ad.jpg)

**期望（必填）**
希望了解Android正式版米家apk通用设置缺少“设备共享、智能场景、固件升级”这三项是什么原因呢？在测试版apk上就正常。是因为项目还未上线，如果上线了就可以了么？还是因为什么原因？在ios上正式版也是正常的，希望andriod的正式版apk也是正常的

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by fishle** [comment]
这个不都是插件自己定制的吗

**Comment by flztsxsy** [comment]
插件里面用的是同一套代码，正式版apk上的设置项缺少三项，米家测试版apk就正常

**Comment by flztsxsy** [comment]
找到原因了，我代码里面有个判断，
if(Device.owner.ID == Service.account.ID){
     firstOptions = [
        first_options.SHARE,
        first_options.IFTTT,
        first_options.FIRMWARE_UPGRADE,
      ];  
     }else {
       firstOptions = []
    }
ios的米家测试版app和正式版app的Device.owner.ID与Service.account.ID均相等。andriod测试版apk的Device.owner.ID与Service.account.ID也相等，唯独正式版的米家apk的Device.owner.ID为空。

**Comment by fishle** [comment]
SDK升级到10025

**Comment by LiuMengzhou** [comment]
> 找到原因了，我代码里面有个判断，
> if(Device.owner.ID == Service.account.ID){
> firstOptions = [
> first_options.SHARE,
> first_options.IFTTT,
> first_options.FIRMWARE_UPGRADE,
> ];
> }else {
> firstOptions = []
> }
> ios的米家测试版app和正式版app的Device.owner.ID与Service.account.ID均相等。andriod测试版apk的Device.owner.ID与Service.account.ID也相等，唯独正式版的米家apk的Device.owner.ID为空。

@flztsxsy 我理解你是要判断分享设备，然后屏蔽掉一些选项对吧，你可以用`Device.isOwner`
