### ISSUE TITLE
[紧急] 使用 Spec 方式 获取设备数据统计,返回 参数无效

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#1506]
紧急!!!紧急!!!!!!!!!
**是否为新品（必填）**
新品 

**关联的产品model**
dmaker.airpurifier.f20

**项目ID（必填）**
无项目ID

**用户ID（必填）**
发现问题的账号id，**强烈建议**在提交issue之前，现在米家APP的“帮主和反馈”中提交问题的说明，并**勾选上传问题日志**，那么我们后台就会根据
当前的用户ID，来查询出现问题的日志，方便大家更快速的解决问题。

**企业名称（必填）**
浙江星月电器
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
硬件已采用 spec 方式, 能正常使用 spec 获取上报属性.  但是在获取上报属性(prop.3.4)的统计数据时候,改用 spec 方式,  报错: 参数无效.

提供的接口图片:
![image](https://user-images.githubusercontent.com/16514238/63918949-54d67700-ca70-11e9-9b56-f73dd0a16ef3.png)

改用spec 方式 接口参数:
![image](https://user-images.githubusercontent.com/16514238/63919008-7172af00-ca70-11e9-9424-069efa705027.png)

报错:
![image](https://user-images.githubusercontent.com/16514238/63919036-7e8f9e00-ca70-11e9-8ab9-1119cab30a54.png)

**期望（必填）**
正常获取统计数据

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请问该问题出现在什么手机系统？
另外，错误返回参数无效，是否是因为 data_type 写错了？写成 stat_day_v3 可以吗？

**Comment by DaquanZhou** [comment]
@zanetti4  安卓和 iOS 都不能加载出数据, 修改 data_type为stat_day_v3也不行.
![image](https://user-images.githubusercontent.com/16514238/63984908-d5908400-caff-11e9-8e00-26b8f4f825fd.png)

**Comment by lvjie0519** [comment]
@DaquanZhou     请参考下com.xiaomi.demo  试试？
![image](https://user-images.githubusercontent.com/22487747/64005021-0f827a00-cb42-11e9-837b-fffad87cde67.png)

**Comment by DaquanZhou** [comment]
@lvjie0519  key 现在是使用 spec 的方式

**Comment by zanetti4** [comment]
由于涉及到服务端的问题，我已经把工单系统中的这个问题，分配给服务端的同事了。这个 issue 我就关闭了

**Comment by zhuxinleibandou** [comment]
> @lvjie0519 key 现在是使用 spec 的方式

请问spec方式的统计解决了吗？我目前也卡在这里了，key填写'prop.2.2'也是报参数错误～希望您指教一下

**Comment by zhuxinleibandou** [comment]
@DaquanZhou  请问spec方式的统计解决了吗？我目前也卡在这里了，key填写'prop.2.2'也是报参数错误～希望您指教一下

**Comment by zhuxinleibandou** [comment]
请问spec方式的统计解决了吗？我目前也卡在这里了，key填写'prop.2.2'也是报参数错误～希望您指教一下

**Comment by DaquanZhou** [comment]
@zhuxinleibandou key去掉 prop换成 2.2  试试

**Comment by zhuxinleibandou** [comment]
@DaquanZhou   谢谢您能帮助我，感谢！   key去掉是什么意思？您的意思是把prop.2.2 换成2.2的形式是吗？ 哎，米家的spec协议更新后 别的API更新不及时，提工单好久才反馈，急死人～ 无奈只能麻烦您了～

 let params = {
            "did": Device.deviceID,
            "data_type": type,
            "key": '2.2',
            "time_start": Date.parse(new Date()) / 1000 - (30 * 24 * 60 * 60) * (type == 'stat_day_v3' ? 1 : 6),  //日统计，默认前30天的,月统计默认半年
            "time_end": Date.parse(new Date()) / 1000,
            "limit": 1000,
        };

**Comment by lvjie0519** [comment]
@DaquanZhou    
1、现在有问题提issue 不是都走工单系统吗？
2、getUserStatistics 对应的请求服务是 user/statistics， 你需要确定下设备端上报数据走的是哪个服务请求？通常都是一一对应关系的，设备端上报应该也会传递key吧？ 这些都和设备端确认下
3、基于spec的，key 规范上来说都是  prop.sid.pid, 如果未解决，通过工单系统提工单吧，因为这涉及到服务端，需要服务端提供支持。

**Comment by DaquanZhou** [comment]
@zhuxinleibandou 你去提工单吧, 格式没错, 可能还需要小米后台配合, 所以你最好去提工单, 他们会有人跟进的
let params = {
"did": Device.deviceID,
"data_type": type,
"key": '2.2',
"time_start": Date.parse(new Date()) / 1000 - (30 * 24 * 60 * 60) * (type == 'stat_day_v3' ? 1 : 6), //日统计，默认前30天的,月统计默认半年
"time_end": Date.parse(new Date()) / 1000,
"limit": 1000,
};

**Comment by zhuxinleibandou** [comment]
已提，还是非常感谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DaquanZhou"<notifications@github.com&gt;; 
发送时间: 2019年11月11日(星期一) 下午2:24
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com&gt;; 
抄送: "朱信磊"<447456419@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MiEcosystem/miot-plugin-sdk] [紧急] 使用 Spec 方式 获取设备数据统计,返回 参数无效 (#1506)




@zhuxinleibandou 你去提工单吧, 格式没错, 可能还需要小米后台配合, 所以你最好去提工单, 他们会有人跟进的
 let params = {
 "did": Device.deviceID,
 "data_type": type,
 "key": '2.2',
 "time_start": Date.parse(new Date()) / 1000 - (30 * 24 * 60 * 60) * (type == 'stat_day_v3' ? 1 : 6), //日统计，默认前30天的,月统计默认半年
 "time_end": Date.parse(new Date()) / 1000,
 "limit": 1000,
 };
