### ISSUE TITLE
MCU的升级和WiFi模组的升级是共用的通用设置中固件升级的界面么

### ISSUE THREAD

**Issue by flztsxsy** [MiEcosystem/miot-plugin-sdk#1507]
**是否为新品（必填）**
新品 

**关联的产品model**
miaomiaoce.blanket.d02

**项目ID（必填）**
【无项目ID】

**用户ID（必填）**
1262449973
**企业名称（必填）**
秒秒测科技（北京）有限公司

**环境（必填）**
- 电脑操作系统:[Window10]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10022]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
如题，MCU的升级和WiFi模组的升级是共用的通用设置中固件升级的界面么？是合并在一起进行升级的么？点击”立即更新“进行升级之后，mcu是否会接收到升级指令?
![image](https://user-images.githubusercontent.com/49407658/63920432-6d945c00-ca73-11e9-80c6-daa6a3b0a9f5.png)

**期望（必填）**
希望了解mcu升级的入口在哪里，如果有新的mcu固件版本时，点击”立即更新“之后，mcu是否会接收到升级指令?

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by dingshaoran** [comment]
mcu 是什么设备，wifi 设备升级的页面和别的升级不是公用的
