### ISSUE TITLE
如何使用retrievePeripheralsWithServicesForIOS接口？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#1508]
**是否为新品（必填）**
新品

**关联的产品model**
ls123.headphone.t10

**项目ID（必填）**

**用户ID（必填）**

**企业名称（必填）**
猎声电子

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[IOS]
- SDK分支: [10023]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
在IOS中连接出现-7错误，按照文档的说明使用retrievePeripheralsWithServicesForIOS获取系统已连接的BLE设备，然后创建设备，将它断开之后重连。但我在使用retrievePeripheralsWithServicesForIOS这个接口的时候，不知道它返回来的是一个什么值，按照文档的例子代码，得到的都是undefined。

**期望（必填）**
能够获取到系统连接的BLE，并进行断开。

**其他的上下文/日志/截图**
<img width="759" alt="屏幕快照 2019-08-29 16 31 32" src="https://user-images.githubusercontent.com/12670497/63924313-a3890e80-ca7a-11e9-9ddc-b6af60506a55.png">
上面是我的使用代码，这时候的LOG打印如下：
<img width="646" alt="屏幕快照 2019-08-29 16 33 26" src="https://user-images.githubusercontent.com/12670497/63924391-c5829100-ca7a-11e9-9ccf-d5db0bc0c199.png">

**Comment by pencilCool** [comment]
请问你们传的service 的uuid 是多少？

**Comment by dgutkai** [comment]
我传的ServiceUUID是：
const serviceUUID = "4c494553-4845-4e47-5401-004d49414952";

**Comment by pencilCool** [comment]
retrievePeripheralsWithServicesForIOS 这个方法是你的目标蓝牙设备还连在手机上才有用。如果蓝牙已经没有连在手机上了。 调用这个方法是没用的。请在手机设置页中确认蓝牙是否是连上的状态。

**Comment by dgutkai** [comment]
我看了在蓝牙设置界面中有显示连接上了。

**Comment by pencilCool** [comment]
那确实就有问题了。我弄个设备测一下

**Comment by pencilCool** [comment]
result 应该是一个数组，你这console.log 有问题。
