### ISSUE TITLE
Device.getBluetoothLE().isConnected不正确

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#151]
before issue：（不用回答）
### 是否尝试搜索issue？
参考issue #131 
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS 
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account]

#### 现象

第一次连接成功后，断开硬件设备电源或者等超时设备与手机断开连接后，Device.getBluetoothLE().isConnected依然为true

#### 期望

期望为false

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

### 不要贴大段代码❗️

**Comment by Copypeng** [comment]
更新到最新的 js sdk 应该就不会了。

**Comment by dzonel** [comment]
@Copypeng 您好，更新后还是和之前的一样

**Comment by dingshaoran** [comment]
加了一些 log，请把 logcat 过滤一下Bluetooth 发出来看看

**Comment by dzonel** [comment]
@dingshaoran 您好，只要连接上设备，就发生下面的错误
![1545016947050](https://user-images.githubusercontent.com/12531667/50065118-b959ea80-01ef-11e9-851b-3b57643ab1bc.jpg)

**Comment by dingshaoran** [comment]
在试一下

**Comment by dzonel** [comment]
@dingshaoran 可以了，你说的“把 logcat 过滤一下Bluetooth”是指安卓的日志吗？

**Comment by dzonel** [comment]
我详细描述下我的操作：
第一次连接成功后，发现服务，发现特征，收发数据都没问题，只要不断开，继续别的蓝牙操作也没问题，然后将硬件设备断电，此时蓝牙连接肯定是断开的了，但Device.getBluetoothLE().isConnected仍然为true，bluetoothConnectionStatusChanged也没有收到监听（第一次连接成功时，可以收到监听）。然后给设备上电，之后调用Device.getBluetoothLE().connect(-1)去连接设备，然后.then立马就有回调了（回调中的数据见图2，图1是正常情况下的数据），接着进行startDiscoverServices操作，在bluetoothSeviceDiscovered和bluetoothSeviceDiscoverFailed中都收不到监听。

第一次连接成功和断开后再次调用Device.getBluetoothLE().connect(-1).then中数据对比
第一次：
图1:
<img width="429" alt="wechatimg84" src="https://user-images.githubusercontent.com/12531667/50069056-55d9b800-0203-11e9-99a3-58280edfc047.png">
断开重新调用Device.getBluetoothLE().connect(-1).then
图2:
<img width="420" alt="wechatimg85" src="https://user-images.githubusercontent.com/12531667/50069072-65590100-0203-11e9-9cc6-5529248fafec.png">
调用方式（即bluetooth和bluetooth_inner数据来源）：
图3
![wechatimg86](https://user-images.githubusercontent.com/12531667/50069088-74d84a00-0203-11e9-81e6-77d100b7e509.png)


不知道我说的是否清楚？

**Comment by dingshaoran** [comment]
您说的问题很清晰，我已经理解了，由于 android 和 ios 的 app 逻辑存在差异，有可能是 app 中存在 bug，也有可能是 js 的 sdk 中存在 bug，看您描述的情况 很有可能是 bluetoothConnectionStatusChanged没回调，我加了一些 log，您帮忙抓个 log 看看。

**Comment by dingshaoran** [comment]
暂时我只能找到一个手边的蓝牙设备，没办法复现断电的情况，如果您抓 log 不方便，我在想想其他办法复现一下

**Comment by dzonel** [comment]
@dingshaoran 您好，我这边过滤Bluetooth，只有两条。我的操作是，连接设备，执行开锁（成功），手动给设备断电，上电，然后再连接。
<img width="798" alt="image" src="https://user-images.githubusercontent.com/12531667/50072051-d81ba980-020e-11e9-8cfd-61906d41a9ba.png">

**Comment by dzonel** [comment]
869版本状态显示正确了。
