### ISSUE TITLE
建议开放蓝牙连接超时设置

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#152]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1
- 相关模块:

#### 现象

看到demo里有对蓝牙连接超时（err.code === -7）的处理，但是我们不知道蓝牙连接多久超时，也不能自己设置时长，建议开放超时时间设置

#### 期望

希望可以自定义蓝牙连接超时时长

**Comment by dzonel** [comment]
+1

**Comment by Copypeng** [comment]
现在固定时间会造成的问题是？
之前是开放的，导致很多垃圾 issue 问为什么超时，结果是因为他们都设成了1，2秒，不胜其扰。

**Comment by dzonel** [comment]
插件页业务设计上会有指定的连接超时时间。如果这个不开放的话，是否可以提供一个取消连接的接口？不然的话，就只能等超时了。

**Comment by Copypeng** [comment]
嗯 @laohuang88 看看

**Comment by Copypeng** [comment]
已开放，请查看 connect 方法的文档。
