### ISSUE TITLE
安卓调用蓝牙写函数 IBluetoothCharacteristic.write 传值解析有误

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#153]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- 相关模块:Bluetooth

#### 现象
在安卓端写的值与设备端接收到的值不一致，具体表现为：一旦出现 16进制特有字符(A,B,C,D,E,F)，该byte 就会变成 0xFF 传给设备端。

#### 其他的上下文/日志/截图
手机端日志
```
 ReactNativeJS: 'Bluetooth write: ', 'c99a3201-7f3c-4e85-bde2-92f2037bfd42', '010200010024CC0000’
```

设备端日志
```
data changed:[0]=01 [1]=02 [2]=00 [3]=01 [4]=00 [5]=24 [6]=ff  [7]=00 [8]=00
```

注意  byte[6]， 手机端写的是 **0xCC** ，设备端接收到的是 **0xFF**，且尝试过其他接口写值出现16进制特有字符均有该现象。
#### 尝试过的解决办法
现在传参使用的是字符串，后来尝试使用 Array 、ArrayBuffer 写给设备，均不能成功。

**Comment by dingshaoran** [comment]
找了半天才发现只处理了小写16进制，网上找的方法真是不靠谱，最总还要自己写，并且还要劳烦您更新下 apk

**Comment by ftc300** [comment]
感谢，已经修复 了。
