### ISSUE TITLE
关于导航栏react-navigation的切换期间显示默认导航图标问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#154]
---

#### 环境
- 电脑操作系统:mac
- 手机系统:ios12
- 相关模块:react-navigation

#### 现象

在主页面MainPage，static navigationOptions 里header设置为null,具体的导航栏在render()里实现，大概代码为：
static navigationOptions = ({ navigation }) => {
    return {
        header:null
    };
};
在二级页面header设为TitleBarBlack，在点击返回按钮时，导航栏会出现这种情况：一闪而过的另一个UI样式（应该是react-navigation的默认样式）（查看录制视频时，很明显的看到，返回按钮变了），不知道有什么办法解决这个问题。

#### 期望

希望能屏蔽掉这个一闪而过的另一个UI样式

#### 其他的上下文/日志/截图

![wechatimg121](https://user-images.githubusercontent.com/22782965/50089208-18dfe680-0240-11e9-892a-ff23fe73b9d6.jpeg)
![wechatimg122](https://user-images.githubusercontent.com/22782965/50089222-24331200-0240-11e9-9327-b16c205162ed.jpeg)

**Comment by LiuMengzhou** [comment]
@flingInTheSky 我也发现了，然而找了好久都没找到

**Comment by flingInTheSky** [comment]
找到了几个解决方案：
1、所有页面的header统一设为null或统一不为null,要统一；
2、改源码，把react-navigation-stack/dist/views/Header/HeaderBackButton.js的64行：source: defaultBackImage 注释掉，不加载图片

**Comment by flingInTheSky** [comment]
用了下新框架的打包机制，发现改本地源码的方式应该走不通。新框架的打包流程，应该是copy一份代码上传到云端打包～。要改的话，也只能米家方面改。

**Comment by LiuMengzhou** [comment]
@flingInTheSky 下周我们fix 这个问题

**Comment by mirse** [comment]
> @flingInTheSky 下周我们fix 这个问题

这个问题解决了吗？

**Comment by LiuMengzhou** [comment]
@flingInTheSky 闪现返回图标的问题，已经在10001分支fix，今日之内同步到10000和10002分支上。

**Comment by LiuMengzhou** [comment]
@mirse 你说的「菜单文案」无法复现。在SDK内也没有找到。

**Comment by mirse** [comment]
> @flingInTheSky 闪现返回图标的问题，已经在10001分支fix，今日之内同步到10000和10002分支上。

请问是否修复，更新至最新sdk还是存在这个问题。

**Comment by flingInTheSky** [comment]
验证已OK

**Comment by mirse** [comment]
10010分支还存在问题
