### ISSUE TITLE
安卓调用 Service.getServerName() 异常

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#155]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- 相关模块:Service

#### 现象
获取不到  ServerName ，

`Service.getServerName().then(res=>{ }).catch(err=>{console.log(err)});`

代码走到了catch 分支。

#### 其他的上下文/日志/截图
```
[TypeError: undefined is not a function (evaluating 'r.default.MIOTService.getServerName(function (r) {
"us_true" === r.countryCode && (r.countryCode = 'us'), e(r);
})')]

```

**Comment by jackcodeone** [comment]
检查下apk和sdk是否更新到最新？

**Comment by mirse** [comment]
#163 我这边测试的安卓的debug还是有问题

**Comment by ftc300** [comment]
我现在是使用之前一个版本的apk来调试的，昨天好像还有一个兄弟出现了同样的问题。

**Comment by mirse** [comment]
是Debug JS Remotely有问题，进不了debug模式

**Comment by ftc300** [comment]
测试已经有数据，感谢！
