### ISSUE TITLE
Can't find variable:MHMapSearch

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#158]
---

#### 环境
- 电脑操作系统:mac
- 手机系统:ios 12
- 相关模块:未知

#### 现象

更新了miot-plugin-sdk，更新了iOS 米家Beta（819）app,开启调试，报：Can't find variable:MHMapSearch

#### 期望

~

**Comment by Copypeng** [comment]
这个issue提的有点让人摸不着头脑。知道这个错误是代码中调用了什么接口吗？

**Comment by flingInTheSky** [comment]
不清楚哦。试了新更新的sdk demo，也一样报错。这个调试报的错误
![1545278139773](https://user-images.githubusercontent.com/22782965/50262925-6c278400-044e-11e9-88bf-984773de89b5.jpg)

**Comment by Copypeng** [comment]
找不到模块，是旧插件没改直接用新框架了？看看迁移文档和新API吧，需要修改适配的。

**Comment by edwardair** [comment]
这问题更新下SDK，已经好了

**Comment by blockdate** [comment]
已处理，更新SDK

**Comment by flingInTheSky** [comment]
OK了
