### ISSUE TITLE
缺少MHBluetoothLE.event.centralManager_didDiscoverPeripheral_advertisementData_RSSI对应接口

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#159]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Bluetooth

#### 现象

新SDK中缺少这个事件

**Comment by Copypeng** [comment]
不少，调用蓝牙搜索接口后，会收到 bluetoothDeviceDiscovered 事件。
