### ISSUE TITLE
高斯模糊iOS适配问题

### ISSUE THREAD

**Issue by tangkun92** [MiEcosystem/miot-plugin-sdk#1593]
高斯模糊iOS适配问题
是否为新品（必填）
是新品

用户ID（必填）
小米ID 144042616

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[ 苹果iOS13.1]
SDK分支: [master]
相关模块:[import {BlurView} from "@react-native-community/blur"]
现象（必填）
1.高斯模糊在iOS13系统上BlurView设置blurAmount参数值无效
2.高斯模糊在iOS13系统上模糊效果过高，无法降低模糊度
期望（必填）
1.需要高斯模糊在iOS13系统上适配，可调节模糊度

其他的上下文/日志/截图
![1569500657339](https://user-images.githubusercontent.com/16345833/65687694-5c536500-e09c-11e9-9692-c724723a7e0e.jpg)

![1569500577646](https://user-images.githubusercontent.com/16345833/65687890-b05e4980-e09c-11e9-89f4-78ee72b0f8e7.jpg)

**Comment by santcool** [comment]
看了下，这个是第三方库，更为关键的是，blurAmount用的是系统的隐藏属性，我们完全没办法。不过可以曲线救国：设置opacity，效果可以自己调。

**Comment by tangkun92** [comment]
> 看了下，这个是第三方库，更为关键的是，blurAmount用的是系统的隐藏属性，我们完全没办法。不过可以曲线救国：设置opacity，效果可以自己调。

好的，我这边设置opacity为0.5，图片背景为白色和黑色 各截图，效果如下图

等待产品UI确定 是否选用半透明效果
![WechatIMG2](https://user-images.githubusercontent.com/16345833/66388436-b5a28900-e9f8-11e9-8259-2379ff87e83c.jpeg)
![WechatIMG1](https://user-images.githubusercontent.com/16345833/66388438-b5a28900-e9f8-11e9-84a2-0210371e1301.jpeg)
