### ISSUE TITLE
原来框架MHXiaomiBLE下的API在新框架对应实现没有

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#16]
MHXiaomiBLE下的，
1.loginXiaoMiBLE(did,mac, timeout, callback)
2.toggleLockXiaoMiBLE(cmd,timeoutInterval,callback) AL-[125,)
3.oneTimePassword(interval, digits, callback)AL-[137,)
等接口的对应实现API没有发现

**Comment by Copypeng** [comment]
第一条直接使用 connect 方法即可；
2和3和安卓统一之后尽快提供。
