### ISSUE TITLE
ISecureKey下remove函数异常

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#160]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account] ISecureKey

#### 现象

使用报错，如图
![wechatimg91](https://user-images.githubusercontent.com/12531667/50265579-389f2680-045b-11e9-955f-5dc4d2436474.jpeg)

#### 期望

可以正常使用

#### 其他的上下文/日志/截图

具体使用代码如下：
![wechatimg92](https://user-images.githubusercontent.com/12531667/50265590-40f76180-045b-11e9-898a-ed627487c170.jpeg)
获取到的钥匙数据如图：
![wechatimg93](https://user-images.githubusercontent.com/12531667/50265605-4eace700-045b-11e9-9086-4ff3a3d0b659.jpeg)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by dzonel** [comment]
@blockdate 您好，试了下，结果如下：
remove err {message: "ok", result: "", code: 0}
为什么结果会出现在catch中，而不是then中？

**Comment by blockdate** [comment]
@dzonel 
- reject 与 resolve 问题已解决，系result为空导致
- nickname问题已解决
- 至于loadSecureKeys尚在排查中
请更新sdk尝试

**Comment by dzonel** [comment]
@blockdate 前两个，确认可以了。

**Comment by blockdate** [comment]
@dzonel Service.security.shareSecureKey 我在测试中使用手机号分享后，一直返回是uid，中途并未返回手机号，如果可以，请您提供更详细的操作过程与用例。

**Comment by dzonel** [comment]
@blockdate 您好，没有什么特殊操作路径，就是用手机号分享出现的。现在我这边也不出现了，我再观察几天，如果没出现，我就关了。
