### ISSUE TITLE
 transformer.js 文件里  n.default.MIOTService.addLog is not a function   

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#161]
ExceptionsManager.js:65 TypeError: n.default.MIOTService.addLog is not a function

This error is located at:
    in CustomSliderView (at MainPage.js:427)
    in RCTView (at View.js:78)
    in View (at MainPage.js:426)
    in RCTView (at View.js:78)
    in View (at MainPage.js:422)
    in RCTView (at View.js:78)
    in View (at MainPage.js:519)
    in RCTView (at View.js:78)
    in View (at MainPage.js:515)
    in RCTView (at View.js:78)
    in View (at MainPage.js:493)
    in MainPage (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:481)
    in RCTView (at View.js:78)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:41)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:505)
    in RCTView (at View.js:78)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:399)
    in RCTView (at View.js:78)
    in View (at StackViewLayout.js:398)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:40)
    in RCTView (at View.js:78)
    in View (at Transitioner.js:141)

**Comment by blockdate** [comment]
这个是已知问题，请等待IPA更新，到时会关闭该issue，请关注。

**Comment by blockdate** [comment]
请更新最新的IPA重试
