### ISSUE TITLE
Service.security.shareSecureKey相关疑问

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#162]
before issue：（不用回答）
### 是否尝试搜索issue？
是，都已被关闭，发现已被关的很少会过问，特此总结一下相关问题

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account] Service.security

#### 现象

1、Service.security.shareSecureKey分享后，返回值中keyID、shareUserID、isOutOfDate三个都是undefined 见 #92 
2、Service.security.loadSecureKeys总的钥匙对象对应的remove()函数，成功会触发.catch而不是.then，见 #160 最新评论
3、Service.security.shareSecureKey函数的参数shareUid，用手机号，然后Service.security.loadSecureKeys，发现钥匙数据中的shareUserID有时是手机号，有时是手机号对应的小米账号。见 #160 

另外：不是本模块的问题，期望可以关注下
1、调试智能场景问题 #116 
2、Service.smarthome.getUserInfo数据不完整问题 #70 最新评论

#### 期望

期望可以关注下已关闭的评论。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
已关闭的issue下的comment我们任会关注，如果较紧急可以多次comment，我们会尽快处理。
同时issue尽量focus一个问题，这样便于处理问题。该issue此处先先关闭
