### ISSUE TITLE
Bluetooth.startScan后，收不到发现设备回调

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#164]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account] Bluetooth

#### 现象

Bluetooth.startScan后在BluetoothEvent.bluetoothDeviceDiscovered.addListener和BluetoothEvent.bluetoothDeviceDiscoverFailed.addListener中均没有回调。

#### 期望

有回调

#### 其他的上下文/日志/截图
启动后，发现确实扫描到设备了，日志如图
![image](https://user-images.githubusercontent.com/12531667/50321044-ecf78600-0509-11e9-82d7-0b53b5c87302.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Handby** [comment]
请问你是这样调用的么？Bluetooth.startScan(3000, 'FE95');我只样调直接报错，can't find variable: mac

**Comment by dzonel** [comment]
@Handby 我传参只传了扫描时长。

**Comment by Handby** [comment]
你是最新的SDK和最新的Beta819么?我只传时长也报错

**Comment by dzonel** [comment]
@Handby sdk今天还没更新过，app是819；

**Comment by dzonel** [comment]
@Handby 更新后，报错了。mac is not defined

**Comment by Handby** [comment]
#169 再更新一下

**Comment by dzonel** [comment]
@Handby 好了。

**Comment by dzonel** [comment]
可以收到回调了。
