### ISSUE TITLE
如何扫描，连接任意的ble设备

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#165]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android 8.0
- 相关模块:bluetooth

#### 现象

我们这有个项目（蓝牙车充）是无设备的蓝牙插件（类似wifi的ap模式），所有设备相关的操作在插件里进行，且不会同步云端。
尝试了下Bluetooth.startScan(3 * 1000)方法，通过日志可以看到扫描是执行了的，但是js端没有收到任何信息
BluetoothEvent.bluetoothDeviceDiscovered.addListener((bluetooths) => {
            bluetooths.forEach(bluetooth => {
                console.log("bluetoothDeviceDiscovered111", bluetooth);
            })
        })
我用的是bluetoothDeviceDiscovered的监听器来接的，不知道对不对

#### 期望

插件内部可以扫描连接任意的蓝牙ble设备

#### 其他的上下文/日志/截图

12-21 10:41:40.371 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: start scan
12-21 10:41:40.403 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onSearchStarted
12-21 10:41:40.578 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:40.578 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:40.590 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: 'Bluetooth', 'bluetoothDeviceDiscovered', '31:21:AF:F0:2A:DD'
12-21 10:41:41.729 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:41.734 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: 'Bluetooth', 'bluetoothDeviceDiscovered', '31:21:AF:F0:2A:DD'
12-21 10:41:42.474 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:42.486 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: 'Bluetooth', 'bluetoothDeviceDiscovered', 'E4:DB:6D:49:C1:CB'
12-21 10:41:42.634 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:42.643 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: 'Bluetooth', 'bluetoothDeviceDiscovered', '31:21:AF:F0:2A:DD'
12-21 10:41:42.854 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onDeviceFounded
12-21 10:41:42.866 27176-24437/com.xiaomi.smarthome:plugin1 I/ReactNativeJS: 'Bluetooth', 'bluetoothDeviceDiscovered', '31:21:AF:F0:2A:DD'
12-21 10:41:43.572 27176-27176/com.xiaomi.smarthome:plugin1 W/miio-bluetooth: app onSearchStopped

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Copypeng** [comment]
应该不能。

1，接入米家必须有个设备，遵守小米蓝牙协议，用户通过添加这个设备，才会生成对应插件，插件sdk中提供的大部分接口都是针对这个设备的。

2，确实可以扫描周边普通BLE设备广播和建立连接。是为设备 OTA 时抹掉原固件后无法发出小米蓝牙广播准备的。

**Comment by edwardair** [comment]
我们的设备也是这个情况，请问有没有什么解决方案？`已上线的硬件`
