### ISSUE TITLE
Bluetooth.startScan报错

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#169]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS 12.1
- 相关模块:[eg.Host/Service/Account]Bluetooth

#### 现象

调用Bluetooth.startScan(3000, 'FE95')报错"can't find variable:mac"，最新的SDK，最新的Beta819。

#### 期望

没有报错

**Comment by laohuang88** [comment]
问题已修复，请更新SDK。
