### ISSUE TITLE
关于创建项目的包名问题

### ISSUE THREAD

**Issue by shanchaojie** [MiEcosystem/miot-plugin-sdk#17]
我看创建项目的时候,会使用我们在小米申请的包名,但是我们的安卓和iOS端的包名不一样,应该使用哪一个包名进行创建呢?

**Comment by laohuang88** [comment]
新项目统一包名即可，不需要区分ios或android

**Comment by shanchaojie** [comment]
有安卓和ios版本的

**Comment by laohuang88** [comment]
ios版本在2018年底前会上线新框架，因此ios版本将强制升级到新版，安卓原生的插件在不发布RN版本的情况下还可以继续使用，如有RN版本将运行与ios同样的代码。

**Comment by dingshaoran** [comment]
以前的 android 包名是 java 的，如果继续使用 java 开发不用考虑统一问题。 如果android ios要使用一份 rn 代码要使用 ios 的包名

**Comment by LiuMengzhou** [comment]
@Handby 你提出的这点很好，我们在新框架中也考虑到了这点，对于平台差异性很大的地方（比如你说的手势交互），可以在代码里面通过判断平台进行区分，至于其他地方可以使用统一的UI和代码逻辑。
