### ISSUE TITLE
如何跳转到米家的语音授权界面

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#170]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

XmPluginHostApi.instance().gotoAuthManagerPage
原生的接口现在在RN里有映射出来吗？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
原生UI跳转请参考
[Host.ui](https://miecosystem.github.io/miot-plugin-sdk/module-miot_host_ui.html)
```
Host.ui.openVoiceCtrlDeviceAuthPage()
```
