### ISSUE TITLE
更新后的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#171]
ios版本ipa:4.10.1
安卓版本apk:5.4.37
-----
问题描述：
一.安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播 。
二.ios版本更新了后，我连接蓝牙的逻辑：
我连接下位机蓝牙成功后，1，发送1234同步时间命令--->下位机收到命令了，并且返回同步时间成功了.  2，再发送请求前2周的1237的历史数据，发送出去了，下位机就死机了。                                 这个逻辑，我上周5更新前都没问题，并且下位机会返回对于的历史数据信息，今天就死机了。。。

**Comment by jackcodeone** [comment]
@caojunhua 安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播。
==================================================
能否提供详细的log输出或代码调用？

**Comment by caojunhua** [comment]
> # @caojunhua
> 安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播。
> 能否提供详细的log输出或代码调用？

安卓版的扫描就是米家app系统的添加设备的按钮来扫描啊，又不会报错

**Comment by caojunhua** [comment]
> # @caojunhua
> 安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播。
> 能否提供详细的log输出或代码调用？
系统扫描设备相关的log我这里也没的提供啊

**Comment by jackcodeone** [comment]
> @caojunhua
> 安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播。
> 能否提供详细的log输出或代码调用？
> 
> 安卓版的扫描就是米家app系统的添加设备的按钮来扫描啊，又不会报错

这个与RN已经没关联，请用下面地址对应的apk ，试试能否扫描到设备，如果无法扫描到，请在下面的github上提issue，谢谢！
https://github.com/MiEcosystem/NewXmPluginSDK

**Comment by caojunhua** [comment]
> > @caojunhua
> > 安卓版本的更新了后，我的蓝牙设备扫描不到了，确定了下位机有发送广播。
> > 能否提供详细的log输出或代码调用？
> > 安卓版的扫描就是米家app系统的添加设备的按钮来扫描啊，又不会报错
> 
> 这个与RN已经没关联，请用下面地址对应的apk ，试试能否扫描到设备，如果无法扫描到，请在下面的github上提issue，谢谢！
> https://github.com/MiEcosystem/NewXmPluginSDK

RN版本可以扫描到蓝牙啊，但是第二点问题也在上面提到了，麻烦帮忙分析一下，也没有报错，就是上位机发送数据给下位机后，下位机死机了，不工作了，但上周没有出现这个情况。

**Comment by blockdate** [comment]
使用最新版本的APP以及SDK，看下问题是否还存在

**Comment by blockdate** [comment]
不活跃
