### ISSUE TITLE
如何在miot/ui/AMapView 上添加一个Marker，并将中心点移到这个marker的坐标上

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#172]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

如何在miot/ui/AMapView 上添加一个Marker，并将中心点移到这个marker的坐标上

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

centerCoordinate函数入参是单个number，没法传一对的坐标啊。还有没找到添加marker的方法

**Comment by blockdate** [comment]
您好，SDK `AmapView`的`centerCoordinate`传入参数为Object，格式如下：  
> SDK 定义有误，但是不影响使用，会有警告。稍后我会更新。
  
```
{'latitude': number,'longitude': number}
```

Marker是Android下的俗称，在iOS平台下叫做`Annotation`，设置`AmapView`的'annotations'属性值即可，格式如下：

```
[
{
'coordinate':{'latitude': number,'longitude': number}, 
'title':'string', 
'subtitle':'string', 
'id':'string', 
'image':'imagePath'
}
]
```
希望能解决您的问题。

**Comment by smalld2006** [comment]
![image](https://user-images.githubusercontent.com/5235769/50410134-fa767e00-0831-11e9-92d8-fba582754cee.png)
使用centerCoordinate这个方法后报错了，如下图所示
![screenshot_20181225-104050](https://user-images.githubusercontent.com/5235769/50410156-1417c580-0832-11e9-856d-b52ac4dddf41.jpg)

**Comment by blockdate** [comment]
这个正在修复中，请等待apk更新

**Comment by smalld2006** [comment]
好的，大概什么时候更新？

**Comment by jackcodeone** [comment]
>           好的，大概什么时候更新？

Android APK 已更新， 请更新Android APK试试。
https://fir.im/MiHomeForAndroid

**Comment by smalld2006** [comment]
多谢

**Comment by smalld2006** [comment]
![image](https://user-images.githubusercontent.com/5235769/50415400-b5fcd980-0855-11e9-945a-a72753c65604.png)
设置annotations时，图片加载出错了，如下图所示
![screenshot_20181225-150015](https://user-images.githubusercontent.com/5235769/50415444-f6f4ee00-0855-11e9-877a-e810edf06054.jpg)

**Comment by jackcodeone** [comment]
@smalld2006  已修复，更新下sdk.

**Comment by smalld2006** [comment]
![image](https://user-images.githubusercontent.com/5235769/50444876-ddcb6a80-0945-11e9-8dd4-3637d640e515.png)
这个版本的centerCoordinate接口又不行了，报错
