### ISSUE TITLE
Android MoreDialog不隐藏

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#174]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 7.1]
- 相关模块:[MoreDialog]

#### 现象

安卓端开启MoreDialog，选择更多设置，进入重命名确定后，返回主界面，dialog不隐藏。
运行开发板demo也是相同情况。（机型：一加三）

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by mirse** [comment]
点击通用设置，然后左上角返回按钮或实体返回按钮，通常情况返回至主页面，moreDialog会自动隐藏，但是当重命名之后，在点击返回，moreDialog还是照常显示。

**Comment by jackcodeone** [comment]
MoreDialog的实现代码在demo里面，你可以按照你的需求来改动MoreDialog的实现。
需要让MoreDialog自动隐藏，调用dismissDialog方法即可，希望能够帮到您。

**Comment by mirse** [comment]
打了个log发现点击通用设置后dismissDialog()，隐藏状态栏，当重命名确定后，会在MoreDialog里的componentWillReceiveProps(nextProps) 里的nextProps.visible会变成true,导致dialog又弹出来。是否有好的建议？

**Comment by jackcodeone** [comment]
>           打了个log发现点击通用设置后dismissDialog()，隐藏状态栏，当重命名确定后，会在MoreDialog里的componentWillReceiveProps(nextProps) 里的nextProps.visible会变成true,导致dialog又弹出来。是否有好的建议？

`<MoreDialog
            visible={typeof navigation.state.params === 'undefined' ? false : navigation.state.params.showDialog}
            navigation={navigation} />
`
注意此处visible的赋值。

**Comment by lvjie0519** [comment]
>           你们的重命名点击确认操作时，应该时将showDialog的参数重新设为了True，导致弹窗重新弹出。能否在源码中修改一下。

MoreDialog的实现没有调用到原生的代码，直接用RN实现的，调用Host.ui.openChangeDeviceName()点击确认后，整个UI会重新刷新，由于之前在TitleBarBlack中设置了showDialog为true，所以会导致MoreDialog再次显示出来，你可以修改MoreDialog中的代码，在执行openChangeDeviceName后将avigation.state.params.showDialog设置为false即可。

**Comment by lvjie0519** [comment]
问题1：
![image](https://user-images.githubusercontent.com/22487747/50534916-b1e6f980-0b7e-11e9-9fe9-0d1e1f21953e.png)

问题2：
![image](https://user-images.githubusercontent.com/22487747/50534928-dd69e400-0b7e-11e9-92f0-d21d5e151318.png)

**Comment by mirse** [comment]
ok ， 谢谢！
