### ISSUE TITLE
最新SDK React Native环境配置问题

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#175]
#### 环境
- 电脑操作系统:[Linux]
node:v10.14.2
npm:6.5.0
- 手机系统:[iOS 10.2.1]

#### 现象

使用npm run create命令创建一个项目，在APP上调试时，页面报错了，“Super expression must either be null or a function, not undefined”。

#### 期望

能正常显示页面

#### 尝试过的解决办法

尝试过import { Component } from 'react'; 还是报一样的错误。

**Comment by blockdate** [comment]
希望能提供更详细的说明，例如：
- project 目录下的 demo 程序是否能正常打开
- 是否改动过生成的项目
- react 使用版本

**Comment by JobenTian** [comment]
1，project目录下的demo程序也不能正常打开，报一样的错误；
2，没有改动过生成的项目；
3，react使用版本是V0.54.4。

尝试过绕过bin/runproject.js，直接使用RN自带的打包脚本，就可以正常在手机上显示。

**Comment by JobenTian** [comment]
尝试过在虚拟机上安装了linux和OS X，搭建React Native环境打包时都会报上述错误。后面直接在window上搭建React Native环境，打包正常。不建议在虚拟机中的系统中搭建React Native环境。

**Comment by JobenTian** [comment]
尝试过在虚拟机上安装了linux和OS X，搭建React Native环境打包时都会报上述错误。后面直接在window上搭建React Native环境，打包正常。不建议在虚拟机中的系统中搭建React Native环境。
