### ISSUE TITLE
灵异bug

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#176]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:

#### 现象

代码执行两遍，就像同时进了两个插件。
我的代码：
![Uploading image.png…]()
控制台的输出，输出了两次。偶现，但概率比较高。
![Uploading image.png…]()

#### 期望

不要出现执行两次的情况。

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/50420953-4bf42c80-0875-11e9-918f-31a0e94e6b92.png)
图片看不到

**Comment by JxXiaoXie** [comment]
图片一：
`class App extends React.Component {
  render() {
    console.log('设备Mac: ' + MiDevice.mac);
    console.log('userId: ' + MiService.account.ID);
    console.log('BSSID: ' + MiDevice.BSSID);
    console.log('小米deviceID: ' + MiDevice.deviceID);
    console.log('model: ' + MiDevice.model);
    console.log('SSID: ' + MiDevice.SSID);
    console.log('type: ' + MiDevice.type);
    console.log('Time1: ' + (new Date()).getTime());
    console.log('Time2: ' + Date.parse(new Date()));
  }
}`

图片二：
<img width="595" alt="image" src="https://user-images.githubusercontent.com/7885251/50421200-aee6c300-0877-11e9-8e55-1c0c9f7b114b.png">

**Comment by laohuang88** [comment]
render正常返回点东西还会两次吗？

**Comment by JxXiaoXie** [comment]
今天还没出现过，出现了我再试试。

**Comment by LiuMengzhou** [comment]
@JxXiaoXie 在react native框架里面，render多次被调用实属正常（每次setState都会触发render），你看看是不是多次setState
