### ISSUE TITLE
Device.getBluetoothLE().connect连接其他普通BLE设备。

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#178]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- 相关模块:[eg.Host/Service/Account]

#### 现象

假设A是我当前添加的设备，B是我想要去连接的其他普通BLE设备

使用代码：
![image](https://user-images.githubusercontent.com/12531667/50429386-1002ab00-08f9-11e9-990f-1b7f8cf390a0.png)

1、当前已经连接到A
调用上述截图的使用代码时，无论peripheralID是何值，立即返回连接成功。log如下图：
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12531667/50429420-3de7ef80-08f9-11e9-85d5-4d095403b3e9.png">

2、当前未连接到A
调用上述截图的使用代码时，无论peripheralID是何值，立即返回连接失败，log如下图
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12531667/50429440-5f48db80-08f9-11e9-95c0-52cc44f3839f.png">

#85 中最后的回复说是已支持连接普通BLE设备，目前测试看有点问题。

#### 期望

可以正常使用

#### 尝试过的解决办法

尝试过哪些操作？

### 不要贴大段代码❗️

**Comment by dzonel** [comment]
我这个问题是不存在（只有我这边出现）？还是我使用上不正确（代码使用有误）？还是我提供的信息不够？还是正在处理中？哪位可以给个回复？

**Comment by blockdate** [comment]
目前连接普通设备仅支持连接RootDevice，即你描述的设备A，不能通过A插件去连接设备B，预计这周会开放这个连接限制，请等待SDK更新

**Comment by blockdate** [comment]
更新app， 现在已经支持连接其他普通蓝牙设备

**Comment by blockdate** [comment]
getBluetoothLE()用于获取连接默认设备的蓝牙对象。
连接其他蓝牙设备，使用Bluetooth.createBluetoothLE(macOrPeripheralID)创建对应蓝牙对象后进行操作

**Comment by blockdate** [comment]
同时，在连接其他蓝牙设备时，需要先进行scan操作。

**Comment by ldezho** [comment]
@blockdate 可以连上了，谢谢。
