### ISSUE TITLE
iOS 移植到新的SDK后，虚拟设备和真实设备都看不到

### ISSUE THREAD

**Issue by asdfeng** [MiEcosystem/miot-plugin-sdk#179]
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.1.2]
- IPA包版本: 869 
- 服务器：大陆

### node 服务器启动后，能看到Dev标签，但是没有创建虚拟设备，另外绑定的真实设备也不显示。

![wechatimg5](https://user-images.githubusercontent.com/17334138/50430142-522deb80-08fd-11e9-98f8-7e02b89dd2be.jpeg)

**Comment by blockdate** [comment]
你好，我这边使用是正常的。

虚拟设备的创建和真实设备的显示与node服务器并没有直接关联，只有加载插件界面时才会连接node服务器读取RN插件。

建议重启APP或者重新登录 刷新查看设备列表。

**Comment by asdfeng** [comment]
貌似找到原因了。我这个model以前已经用资源包方式加载图片资源了，换个model就可以了。
