### ISSUE TITLE
安卓最新版apk ，undefined is not an object (evaluating 'NativeModules["SQLite"][method]')

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#180]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- 相关模块:

#### 现象
使用最新版 apk 和sdk ，使用 react-native-sqlite-storage 库，调用 SQLite.openDatabase 方法崩溃。

#### 其他的上下文/日志/截图
`undefined is not an object (evaluating 'NativeModules["SQLite"][method]')`

#### 尝试过的解决办法
使用旧版本 apk 表现正常，但是旧版本 apk ，调用  Device.getBluetoothLE().connect 崩溃 
`com.facebook.react.bridge.NativeArgumentsParseException: MIOTBluetooth.connect got 4 arguments, expected 3
`

**Comment by jackcodeone** [comment]
该库目前正在改造过程中，请等待更新，谢谢~

**Comment by ftc300** [comment]
已经正常 ，感谢
