### ISSUE TITLE
三指截屏崩溃

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#184]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[？]

#### 现象

三指截屏问题还是存在，机型(一加，部分小米手机)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
麻烦提供下崩溃日子，这样方便为您解决问题。

**Comment by mirse** [comment]
操作流程：三个手指头点击屏幕，出现下图情况 ，你们在 #73 说已解决，但还是会出现崩溃现象
![_20190102103447](https://user-images.githubusercontent.com/5188922/50578834-fffb4600-0e79-11e9-8547-e13404ca95cf.jpg)

**Comment by lvjie0519** [comment]
查了下，好像是RN的问题，有没有试过在相同的RN版本下，其他的RN应用程序是否有问题，例如 init一个新的RN应用，三指截屏是否有问题？

**Comment by mirse** [comment]
是的，这是RN框架自身的问题
你们那边的相关人员在 #73 给出了解决方案，目前看来并不奏效

**Comment by dingshaoran** [comment]
我们在 bin/fixbug 文件夹下替换了会报错的四个文件 
ReactFabric-dev
ReactFabric-prod
ReactNativeRenderer-dev
ReactNativeRenderer-prod， 你看看你的sdk里是不是有这几个文件，如果三只截屏还是会崩溃请把你的 bundle 文件上传了，我们看一下是不是还有其他报错的地方。
bundle 文件可以在浏览器加载 http://localhost:8081/projects/你插件的包名/index.bundle?platform=android&dev=true&minify=false 保存成文件

**Comment by mirse** [comment]
上传方式呢，留个邮箱还是？

**Comment by lvjie0519** [comment]
>           上传方式呢，留个邮箱还是？

首先请检查下您的react-native版本，请使用0.54.4版本。

第一步：查看一下bin/fixbug下是否有如上几个文件，如果三指截屏还有问题，请操作第二步；

第二步： 打开bin/fixbug/index.js，尝试手动将如上几个文件的内容拷贝到node_modules/react-native对应的文件中，内容做一个替换，如果三指截屏还有问题，请操作第三步；

第三步： 将bundle文件发送至 lvjie1@xiaomi.com 邮箱，谢谢。

**Comment by lvjie0519** [comment]
嗯，这说明脚本没有将这几个文件做替换，我们这边继续排查原因。

**Comment by dingshaoran** [comment]
你上面的红色 error 上线之后会变成 crash，黄色的 warn 是上线之后会隐藏，不会有任何报错。
如果你还有红色的 error 需要发送 bundle文件，warn 是正常的  close issues 就行了

**Comment by dingshaoran** [comment]
也可以把 warn 改成 log或其他的提示，只要不是 error 上线之后都不会影响用户的
