### ISSUE TITLE
新版本的API文件为什么没有“关键词”搜索功能

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#186]
我做小米电源插件，咱们新版本的api文档我昨天，真心找了。
两个小时。
之前我们公司对接人，告诉我说咱们新的SDK，“定时”和“倒计时”已经分开两部分处理了。
倒计时操作我并没有在api文档中找到新的接口可以处理，我真心是一条一条的，看的，没有关键词搜索，太麻烦了。
新SDK项目的友好度太低了。是不是最少提供一个新老对应文档。减少为一条一套看内容的时间，我一天工作下来几乎什么都没有干，就在这里，翻找api文档中我需要的接口了。

**Comment by blockdate** [comment]
新版本API为静态HTML页面，上线迁入IoT平台后会有检索功能。
很抱歉给你带来的困扰，新版API是根据功能模块分类来进行编写的，如果短时间内未能在相关模块找到你需要的api功能，可以直接在此创建issue，供你需要的旧版本API调用方式，以及使用用途，我们会及时帮你解决问题。
文档是持续更新的，我们会根据收到的问题，尽力完善。
