### ISSUE TITLE
MessageDialog 在android不显示confirm按钮

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#187]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]   windows
- 手机系统:[eg.Android 8.1/iOS 11.0]  android 7.0
- 相关模块:[eg.Host/Service/Account]  HOST.ui

#### 现象

简单明了地描述一下实际的现象。
在ios能正常显示的弹出框, 在android平台上不能正常显示

#### 期望

简单明了地描述一下期望的表现。
能正常显示.

#### 其他的上下文/日志/截图

 <MessageDialog title={this.state.notify.title}
                    message={this.state.notify.message}
                    
                    onCancel={() => {
                      vm.hideDialog();
                    }}
                    onConfirm={() => {
                      vm.hideDialog();
                    }}
                    onDismiss={()=>{
                      vm.hideDialog();
                    }}
                    cancel={localStrings.cancelStr}
                    confirm={localStrings.confirmStr}
                  
                    visible={this.state.notify.visible}/>

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
是否 确保localStrings.confirmStr  不能为空

**Comment by RobinLike** [comment]
localStrings.confirmStr不为空，有的时候会显示出来
