### ISSUE TITLE
did you run react-native link

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#19]
![image](https://user-images.githubusercontent.com/5188922/48298306-50979800-e4f6-11e8-920e-4f72ea5658f0.png)

**Comment by ftc300** [comment]
+1  
https://github.com/stefalda/ReactNativeLocalization/issues/61

**Comment by jimu380261652** [comment]
你的问题有解决么，我这边win10环境下跑米家安卓的Demo也同样报这个错误

**Comment by dingshaoran** [comment]
请 暂时使用 lunix 或者 mac 开发调试

**Comment by ftc300** [comment]
mac下测试OK

**Comment by mirse** [comment]
近期会修复windows下的开发调试吗

**Comment by ftc300** [comment]
@mirse 建议搞个Linux虚拟机吧 ，我测试也是ok的，但是就是用上webstorm开发有点卡。

**Comment by jimu380261652** [comment]
VMware下虚拟机装Ubuntu18.04,报错信息如下
![test](https://user-images.githubusercontent.com/11864517/48542670-be7aff80-e8fa-11e8-94fc-85cc975cb21c.png)

**Comment by ftc300** [comment]
@LiuMengzhou 感谢推荐，jetbrain全家桶用惯了

**Comment by LiuMengzhou** [comment]
@mirse @jimu380261652 @ftc300 
windows环境问题已解决，请更新SDK试试。

**Comment by mirse** [comment]
> @mirse @jimu380261652 @ftc300
> windows环境问题已解决，请更新SDK试试。

经测试，可以在windows下运行
