### ISSUE TITLE
PackageEvent.packageAuthorizationCancel 收不到监听

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#190]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 7.1]
- 相关模块:[PackageEvent]

#### 现象

在撤销使用条款和隐私政策授权的时候并接收不到回调监听（Android）

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
已修复，更新下sdk，谢谢！

**Comment by mirse** [comment]
提个建议：能不能别急着close问题？能等我们测试成功后在close问题吗？
已更新sdk，遇到如图问题
![_20190103093451](https://user-images.githubusercontent.com/5188922/50620545-d1916f80-0f3a-11e9-885f-7fedba28b9aa.jpg)
