### ISSUE TITLE
Host.ui.openDeleteDevice()

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#191]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 7.1]
- 相关模块:[Host]

#### 现象

执行Host.ui.openDeleteDevice()方法，显示删除成功，实际设备并未删除。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
已修复，请使用最新apk，谢谢！

**Comment by mirse** [comment]
经测试，点击删除设备，虽然设备item从我的设备列表中移除，但是设备并未重置。

**Comment by lvjie0519** [comment]
已确认，下周更新apk，会修复问题，给您带来不便非常抱歉。

**Comment by lvjie0519** [comment]
已修复，请使用最新apk。
