### ISSUE TITLE
moreMenu布局

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#192]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 7.1]
- 相关模块:[MoreMenu]

#### 现象

moreMenu界面，每个item下方都有分割线，但是在部分手机（一加三）上分割线并不完全显示（每两个item显示一条分割线）
![screenshot_2018-12-26-10-12-57-446_com xiaomi smarthome](https://user-images.githubusercontent.com/5188922/50584408-64ce9480-0eaa-11e9-9571-60e91b61cf8e.png)
![_20181226101702](https://user-images.githubusercontent.com/5188922/50584409-65672b00-0eaa-11e9-96f9-9234e2d23ca5.jpg)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

separator: {
    height: 1 / PixelRatio.get(),
    backgroundColor: '#e5e5e5',
    marginLeft: 20,
  },
源代码布局 height:1/PixelRatio.get(), 改成height:1分割线能显示出来
一加三PixelRatio.get()为2.625

**Comment by lvjie0519** [comment]
对于所有demo里面的UI及逻辑，用户都是可以自行修改的，这个不在维护范畴。
