### ISSUE TITLE
callMethod错误

### ISSUE THREAD

**Issue by Braveleon** [MiEcosystem/miot-plugin-sdk#194]
在callMethod专题里面没解决我的问题，下载并且更新了最新的sdk，按照demo调用方法
Device.getDeviceWifi().callMethod("get_prop", JSON.stringify(["run_status", "work_status", "mode"])).then((res) => {
alert(res);
});

![image](https://user-images.githubusercontent.com/18184778/50669928-30bab700-1003-11e9-9656-6434a05a88e7.png)
按照demo的示例获取属性为什么会出现这样的错误？(用不用JSON.stringify进行序列化都一样）

**Comment by blockdate** [comment]
已解决，iOS与Android未同步导致，更新SDK即可

**Comment by Braveleon** [comment]
更新了bin文件夹还是这个错误，你们测试了吗？

**Comment by Braveleon** [comment]
> 已解决，iOS与Android未同步导致，更新SDK即可

还是报错的

**Comment by blockdate** [comment]
本地测试ok的，你是Android还是iOS平台下的

**Comment by Braveleon** [comment]
> 本地测试ok的，你是Android还是iOS平台下的

ios平台，型号是6s，刚更新了bin这个文件夹，但是还是报这个错误

**Comment by Braveleon** [comment]
> 本地测试ok的，你是Android还是iOS平台下的

还没fixed么？

**Comment by blockdate** [comment]
已fix，更新SDK测试看是否ok

**Comment by Braveleon** [comment]
> 已fix，更新SDK测试看是否ok

已经解决，谢谢

**Comment by jimu380261652** [comment]
![image](https://user-images.githubusercontent.com/11864517/50823085-1b7cba00-136e-11e9-8bf6-e9a6ab935877.png)
下载最新SDK，Win10环境下安卓也报这个错误了

**Comment by lvjie0519** [comment]
此问题等同于 [#207](https://github.com/MiEcosystem/miot-plugin-sdk/issues/207)
现在还存在问题吗？

**Comment by lvjie0519** [comment]
使用最新的sdk和apk。
