### ISSUE TITLE
RN创建Bitmap

### ISSUE THREAD

**Issue by ttsaite375** [MiEcosystem/miot-plugin-sdk#195]
我们插件需要做画地图的功能，地图文件里面字节数据代表不同的坐标色值，由于rn没有创建bitmap的接口，想问下原生能不能提供一个接口，创建地图的bitmap。

**Comment by dingshaoran** [comment]
现有的高德地图 api  circles polylines annotations 是否能支持您地图上添加自定义标记的需求，如果不能支持，请具体描述一下您的需求，并把您那边已经实现了需求功能的 oc 和 java 代码贴一下，给我们一个示例

**Comment by ttsaite375** [comment]
我指的画地图是扫地机的地图，是设备上传的一个轨迹地图文件。
代码如下:
  /**
     * base64文件转成图片
     *@param content 地图文件
     * @param colorMStr 墙色值
     * @param color0Str 背景色值
     * @param color1Str 已发现区域色值
     * @param callback
     */
    @ReactMethod
    public void colorsToImageBase64(final String content, final String colorMStr, final String color0Str, final String color1Str, final Callback callback) {

        Observable.just(content).map(s -> {
            log.d(TAG, content);
            log.d(TAG, "colorM-->" + colorMStr + "   color0-->" + color0Str + "   color1-->" + color1Str);
            byte[] testBs = Base64.decode(content, Base64.NO_WRAP);

            log.myE(TAG, Arrays.toString(testBs));
            int sizeX = bytesToInt(testBs, 58);
            int sizeY = bytesToInt(testBs, 62);
            log.myE(TAG, "sizeX==" + sizeX + "   sizeY==" + sizeY);
            int colorM = Color.parseColor(colorMStr);
            int color0 = Color.parseColor(color0Str);
            int color1 = Color.parseColor(color1Str);

            int[] colors = new int[sizeX * sizeY];
            int index = 86;
            for (int i = 0, size = colors.length; i < size; i++) {
                switch (testBs[index]) {
                    case -1:
                        colors[i] = colorM;
                        break;
                    case 0:
                        colors[i] = color0;
                        break;
                    case 1:
                        colors[i] = color1;
                        break;
                }
                index++;
            }


            Matrix m = new Matrix();
            m.setScale(-1, 1);//水平翻转
            Bitmap bmp = Bitmap.createBitmap(colors, sizeX, sizeY, Bitmap.Config.ARGB_8888);
            Bitmap bmpNew = Bitmap.createBitmap(bmp, 0, 0, sizeX, sizeY, m, true);
            String result = BitmapUtil.bitmapToBase64(bmpNew, 100);
            bmp.recycle();
            bmpNew.recycle();

            return result;
        }).compose(SchedulerProvider.applySchedulers()).subscribe(result -> callback.invoke(result)
                , throwable -> {
                    throwable.printStackTrace();
                    callback.invoke(null);
                });
    }

**Comment by dingshaoran** [comment]
你的 bitmap 干嘛用了，是显示到 image 上了还是保存了jpg，有一个 react-native-svg 的库，你看看 demo 里的SVGDemo.js 可以画点 线 渐变 和 photoshop 上导出的 .svg 文件

**Comment by dingshaoran** [comment]
并且你想保存成文件使用 svg的引用 .toDataURL();
参考这个库的源码,应该是和你bitmapToBase64一样的
https://github.com/react-native-community/react-native-svg/blob/37f07050e4867da33b58ece871881efdb4cd1123/android/src/main/java/com/horcrux/svg/SvgView.java

**Comment by weeksun23** [comment]
@dingshaoran 我们希望是原生能提供一个方法，传入bitmap的宽度和高度，以及一个数组表示bitmap上每一个点的颜色值，生成一张bitmap并返回这张bitmap的base64字符串。您看这样可以吗？

**Comment by dingshaoran** [comment]
您说明一下这个方法的使用场景，可以提供这个方法，为了保证在 ios 和 android 上的效果一致，我们会根据你的使用场景衡量如果实现

**Comment by dingshaoran** [comment]
之前你说的扫地机设备的轨迹地图，是可以通过 svg <d>标签实现的，可以展示到界面，也可以使用toDataURL 生成一个 jpg。
如果像你说的那样去操作像素数据量太大 js 和 native 传递很耗时，虽然实现简单，但是性能差

**Comment by weeksun23** [comment]
用svg的话，怎么根据地图数据数组(一般是800*800=640000个元素，依次表示地图上每一个点的颜色值)描绘出扫地机的地图？

**Comment by dingshaoran** [comment]
您的意思是 最终还是要显示到界面上，即使我返回给您 jpg 的 base64 也展示不了，我们像个合适的方案解决您说的问题

**Comment by flingInTheSky** [comment]
react-native是可以根据图片的base64编码来显示图片的

**Comment by weeksun23** [comment]
请问这个问题现在如何了，能支持吗？

**Comment by lvjie0519** [comment]
> 请问这个问题现在如何了，能支持吗？

1、colorsToImageBase64(final String content, 
这个函数content的内容通常有多大？

2、colorsToImageBase64这个函数的几个参数具体值能否给一个？我这边做下测试

联系邮箱：lvjie1@xiaomi.com

**Comment by weeksun23** [comment]
@lvjie0519 您好 已发邮件 请查收

**Comment by lvjie0519** [comment]
@weeksun23  Android已支持，请使用最新apk和sdk，Host.crypto.colorsToImageBase64试试，

**Comment by weeksun23** [comment]
@lvjie0519 谢谢
