### ISSUE TITLE
Service.smarthome.reportRecords异常问题

### ISSUE THREAD

**Issue by RobinLike** [MiEcosystem/miot-plugin-sdk#196]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows/Mac OS/]
- 手机系统:[Android 7.0/iOS 11.0]
- 相关模块:[Service/Smarthome]

#### 现象
调用这个接口是，Promise报异常错误

#### 期望
期望能正常完成功能

**Comment by lvjie0519** [comment]
1、首先确定一下是哪个平台或两个都有？
2、确定下records参数是否正确？
Promise报异常错误，具体有什么异常信息吗，麻烦提供下，这样方便为您排查。

**Comment by blockdate** [comment]
参数使用请参考API文档，
example：
```
Service.smarthome.reportRecords("deviceID", [{type:"a",key:"b",value:"c"}])
```

**Comment by RobinLike** [comment]
按照新的参数设置了，还是报错
Service.smarthome.reportRecords("deviceID",[{type:"user",key:"com.philips.light.zyceiling.button.page.ios",value:4}])

**Comment by blockdate** [comment]
type填写 event 再次尝试
