### ISSUE TITLE
在Host.ui中没有 与安卓原生对应的"设备时区"设置和获取"网络信息"的功能

### ISSUE THREAD

**Issue by RobinLike** [MiEcosystem/miot-plugin-sdk#198]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
在Host.ui中没有 与安卓原生对应的"设备时区"设置和获取"网络信息"的功能

#### 期望
希望增加这个功能

**Comment by blockdate** [comment]
处理中，请等待app与SDK更新

**Comment by blockdate** [comment]
同时网络信息在设备信息中已提供：
[参考](https://miecosystem.github.io/miot-plugin-sdk/module-miot_Device-IDevice.html)
```
var wifiName = Device.SSID;
var wifiMac = Device.BSSID;
var deviceMac = Device.mac;
var deviceIP = Device.IP
```

**Comment by lvjie0519** [comment]
Android  请使用最新apk及更新sdk到最新版本；
时区设置：Host.ui.openDeviceTimeZoneSettingPage()；
时区改变事件：DeviceEvent.deviceTimeZoneChanged。
