### ISSUE TITLE
插件端与独立APP端的蓝牙连接兼容问题

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#200]
iOS平台（android暂未测试）

#### 现象

比如插件端，添加过蓝牙设备A，退出插件，断开蓝牙，使用独立APP端去连接设备A，通过重新注册可以连接成功，之后再换回米家APP，进入插件，蓝牙一直无法连接成功

以前的米家版本，当使用独立APP连接过设备，在米家设备列表里面，这个设备会自动消失，也就不会造成插件一直无法连接蓝牙问题

### **_（二选一）_**
1、被独立APP连接过的蓝牙设备，插件能够再次连接成功
2、被独立APP连接过的蓝牙设备，重新进入米家设备列表能够自动消失

**Comment by edwardair** [comment]
由于米家测试，提审时，测出同样问题，望米家方面能够解决

**Comment by pencilCool** [comment]
请按照issue 模板来：
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/.github/ISSUE_TEMPLATE/issue.md

填写必要的信息。

**Comment by edwardair** [comment]
**IPA/APK 最新
    SDK 最新**

**新品 + 在售 都存在问题**

**关联的产品model**: roidmi.vacuum.ios

**【无项目ID】**

**企业名称**：无锡睿米

**现象**

比如插件端，添加过蓝牙设备A，退出插件，断开蓝牙，使用独立APP端去连接设备A，通过重新注册可以连接成功，之后再换回米家APP，进入插件，蓝牙一直无法连接成功

以前的米家版本，当使用独立APP连接过设备，在米家设备列表里面，这个设备会自动消失，也就不会造成插件一直无法连接蓝牙问题
**期望
（二选一）**

1、被独立APP连接过的蓝牙设备，插件能够再次连接成功
2、被独立APP连接过的蓝牙设备，重新进入米家设备列表能够自动消失
不要贴大段代码❗️

**Comment by pencilCool** [comment]
反馈的model 应该不对，在平台上没有找到这个产品。
但是能查到 model 为  roidmi.vacuum.v1 的产品。
请确认是不是这个model

**Comment by edwardair** [comment]
是  roidmi.vacuum.v1，所有拥有独立APP+米家插件的都会遇到这个问题，所以请不要纠结model问题，你们自己随便搞个蓝牙设备测试就知道了

**Comment by pencilCool** [comment]
已经在米家中绑定的蓝牙设备，是不能再在独立sdk 中注册绑定的。
