### ISSUE TITLE
Service.smarthome.reportRecords()按照api参数填写了，仍旧报错

### ISSUE THREAD

**Issue by RobinLike** [MiEcosystem/miot-plugin-sdk#201]
before issue：（不用回答）
### 是否尝试搜索issue？

---
1、首先确定一下是哪个平台或两个都有？
【答复】两个平台都有
2、确定下records参数是否正确？
【答复】参数两个：第一个是deviceID，第二个是 [{"mypackagename":4}]
Promise报异常错误，具体有什么异常信息吗，麻烦提供下，这样方便为您排查。
【答复】异常信息：
Possible Unhandled Promise Rejection(id:0):
Object{
"message":"callSmartHomeAPI failedError
Domain=MiHomeNetworkErrorRemote
Code=-7 "(null)" UserInfo={message=invalid device type,result=,code=-7}",}

根据你的建议，参考API文档重新填写了参数：
Service.smarthome.reportRecords(Device.deviceID, [{type:"user",key:"com.philips.light.zyceiling.button.page.ios",value:4}])
还是报一样的错误。

**Comment by RobinLike** [comment]
根据你的建议，type值改成"event"了，还是报错：[{type:"event",key:"com.philips.light.zyceiling.button.page.ios",value:4}]

**Comment by lvjie0519** [comment]
1、type有两种类型，prop或event；
2、key的取值；
这两者是有关联的，需要检查你设备的协议包括的信息。
