### ISSUE TITLE
安卓固件升级发现缺少蓝牙连接接口

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#203]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- 相关模块:Bluetooth

#### 现象
了解到 IOS 端好像使用的是 peripheralID 来连接的，原来安卓端使用的蓝牙连接接口形如：Bluetooth.connect(mac)，传参是 mac地址。
现在固件升级涉及到的问题是，安卓这边会先给设备写值使设备进入DFU状态，这个时候设备的mac地址会加一。如原蓝牙设备mac地址为 xx:xx:xx:xx:xx:01 会变为 xx:xx:xx:xx:xx:02。然后再连接地址变化后的设备即 xx:xx:xx:xx:xx:02 进行后续升级操作，所以入参 mac 在安卓端尤为重要。

#### 期望
增加蓝牙连接接口（入参指定 mac 地址）

**Comment by dingshaoran** [comment]
后续操作都有什么，是不是需要在添加一个接口connectDFU，链接 mac+1后的设备

**Comment by ftc300** [comment]
是的，确实如此。我需要持有这个连接成功后的对象，往设备来进行写操作。

**Comment by dingshaoran** [comment]
Bluetooth.createBluetoothLE(mac).connet(type) 你可以这样链接，稍等我们改一下框架的限制

**Comment by ftc300** [comment]
今天更新到最新的apk和sdk后确实多了createBluetoothLE(mac) 方法，但是目前只支持**RootDevice** 的 mac 地址。这个 **RootDevice** 指的是什么？目前调用该方法，报错 

`
Error：the bluetooth of sub device is not supported now 
`

**Comment by blockdate** [comment]
RootDevice表示你进入插件所关联的设备

**Comment by ftc300** [comment]
好的，谢谢回复。但是现在mac地址变了已经不是那个设备了哦，亲。

**Comment by lvjie0519** [comment]
@ftc300   使用最新SDK和最新apk，  确定下是否有问题？

**Comment by ftc300** [comment]
无法进入插件 见 #250
