### ISSUE TITLE
Service.smarthome请求添加'/user/get_device_auth'接口

### ISSUE THREAD

**Issue by dongyaxun** [MiEcosystem/miot-plugin-sdk#204]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

原先的MHPluginSDK.callSmartHomeAPI('/user/get_device_auth')接口丢失。

#### 期望

希望在Service.smarthome里添加'/user/get_device_auth'接口。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by dingshaoran** [comment]
请把请参数说一下，是干嘛用的，我们加一下

**Comment by dongyaxun** [comment]
> 请把请参数说一下，是干嘛用的，我们加一下

参数：did
用途：我们前端和后端的交互需要通过此接口拿到的authCode来做第一步的鉴权

**Comment by blockdate** [comment]
更新SDK使用
```
Service.smarthome.getDeviceAuth(did).then(authCode => console.log("authCode",authCode))
```

**Comment by lvjie0519** [comment]
已支持，请使用最新sdk

**Comment by blockdate** [comment]
接口更名为如下getUserDeviceAuth
```
Service.smarthome.getUserDeviceAuth(did).then(authCode => console.log("authCode",authCode))

```
