### ISSUE TITLE
新api中有定时器的创建，找不到，定时器的删除操作呀

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#205]
老api中 MHPluginSDK.callSmartHomeAPI('/scene/edit' 这种删除定时器操作，在心的api接口找不到，我仅仅找到了  createTimerScene 不运行删除吗？

**Comment by blockdate** [comment]
https://miecosystem.github.io/miot-plugin-sdk/module-miot_service_scene.html

参考上述api文档，重新加载scene或者获取之前create的scene对象，执行scene.remove()即可
