### ISSUE TITLE
在退出插件页面componentWillUnmount调用Host.storage.save(info) 无效

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#206]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android /iOS
- 相关模块:Host/storage]

#### 现象

退出插件储存当前插件状态时，在componentWillUnmount 里调用Host.storage.save(info) ，Host.storage.save(info)不能执行

#### 期望

在退出插件时保存APP状态到本地，进入插件再从本地读取数据。

**Comment by lvjie0519** [comment]
已排查，请等待apk更新

**Comment by lvjie0519** [comment]
已修复，请使用最新apk，谢谢！
