### ISSUE TITLE
下午刚更新的sdk，安卓平台上callMethod报错

### ISSUE THREAD

**Issue by RobinLike** [MiEcosystem/miot-plugin-sdk#207]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

用Win10系统下载插件到Android手机上报错 
![image](https://user-images.githubusercontent.com/46372375/50827175-baa6af00-1378-11e9-8a59-f6abb9f11768.png)
在更新今天的sdk之前没报这个错误。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、检查下你的apk是否为最新？
2、你那边传递的参数格式是怎样的？
我这边试了下 Device.getDeviceWifi().callMethod("get_prop", ["humidity", "rgb", "temperature"]).then
这样没发现问题。

**Comment by dingshaoran** [comment]
需要下载新版米家

**Comment by lvjie0519** [comment]
https://fir.im/MiHomeForAndroid   这里下载，或者上方点击code项，下面有相关下载地址链接。

**Comment by RobinLike** [comment]
我看到的版本是5.4.37 对吗？我用的就是这个版本

**Comment by RobinLike** [comment]
刚才升级了新的米家安卓版本，可以运行，但报了另外的错误。
"org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject\n\tat org.json.JSON.typeMismatch(JSON.java:111)\n\tat org.json.JSONObject.<init>(JSONObject.java:160)\n\tat org.json.JSONObject.<init>(JSONObject.java:173)\n\tat com.xiaomi.smarthome.framework.plugin.rn.nativemodule.MIOTDeviceModule.callMethod(MIOTDeviceModule.java:147)
代码如下：
![image](https://user-images.githubusercontent.com/46372375/50880187-77038200-1418-11e9-911b-f23546363b3f.png)

**Comment by lvjie0519** [comment]
请使用最新sdk，谢谢！
