### ISSUE TITLE
saveInfo 新版本的sdk是不是不能用了？

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#208]
saveInfo(info)
使用 NSUserDefaults 缓存一个字典
我在老版本存放了一个值，新版本中，我就看到了一个Host.storage.load类似，但是无法获取之前的设置。

**Comment by kfjihailong** [comment]
我测试，用android  Host.storage.save（） 之后，iphone Host.storage.load（）无法读取。

**Comment by lvjie0519** [comment]
您好，Host.storage.save 是将数据保存在手机本地的，更换手机是无法读取到数据的。

**Comment by kfjihailong** [comment]
那请问您，老的api中的 MHPluginSDK.loadInfoCallback 是那个对应新sdk接口是那个呀，我要做老版本的内容匹配，请您告诉我呀。

**Comment by blockdate** [comment]
@kfjihailong loadInfoCallback老版本用于读取iOS的UserDefault中数据，新版本与Android统一，不再提供loadInfoCallback对应的方法，使用storage读写键值对即可。

**Comment by kfjihailong** [comment]
> @kfjihailong loadInfoCallback老版本用于读取iOS的UserDefault中数据，新版本与Android统一，不再提供loadInfoCallback对应的方法，使用storage读写键值对即可。

您说的是，Host.storage.save 和 Host.storage.load方法吗，我测试，并不能，android和ios同步数据同步呀，那么我用户有一个ios手机和一个android手机，数据不能同步呀。怎么做到数据同步呢？

**Comment by blockdate** [comment]
Android 与 iOS 手机数据同步对应不同厂家有不同的解决方案，如果你们之前的版本有实现该功能，请提供下原实现方案。
> loadInfoCallback 也仅适用于本地数据存取，并不能多端同步。
