### ISSUE TITLE
android 如何像ios一样添加虚拟设备调试？

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#21]
如题

**Comment by dingshaoran** [comment]
首页->我的->开发者选项->是否开启无设备开发模式 （选中）->进入添加设备页面选择手动添加，长按想要添加的设备

**Comment by dingshaoran** [comment]
请使用测试帐号
894158105
helloxiaomi2

**Comment by ftc300** [comment]
请问是点击蓝牙设备吗？进入插件后崩溃如图：
![image](https://user-images.githubusercontent.com/12816061/48408097-71b8ec80-e773-11e8-9faf-9850854f1959.png)
