### ISSUE TITLE
关于安卓的一点小建议

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#210]
前提：从目前调试安卓的情况看，_**时常要更新调试 apk**_。

将 apk 托管于 fir.im ，相较于直接放在项目中虽然能略微提高下载速度但是很不利于管理。
综合来看，像老版本sdk一样放置于项目根目录做法更加合理。
(1) git pull 直接拉取最新的sdk代码和apk ，省事，效率高；
(2) 文件可以追溯历史，若新版本出问题，我们还能使用旧的版本干活；
(3)  fir.im 本来也是对 ios应用安装带来了便利，但是这个对我们安卓开发者，目前来看感觉反而麻烦。

**Comment by lvjie0519** [comment]
可以，谢谢您的建议！
