### ISSUE TITLE
获取手机Wifi信息问题

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#212]
未找到类似老版本的这个API信息：（获取手机wifi信息）
MHPluginSDK.getConnectedWifi((isSuccess,message) =>{
	if(isSuccess){
        let ssid = message["SSID"];
        let bssid = message["BSSID"];
	}
});
请给与提供，谢谢；

**Comment by blockdate** [comment]
device信息中都有
file:///Users/lex/Project/rn-plugin/exports/miot-plugin-sdk/docs/module-miot_Device-IDevice.html
```
Device.SSID
Device.BSSID
```

**Comment by blockdate** [comment]
不好意思，上面是设备wifi信息

**Comment by liduojun** [comment]
你好。感谢回复，我认为这个是设备连接的wifi信息，我想要的是手机当前连接的wifi信息，目前遇到的问题是Device. location 始终返回2，这个Device.getDeviceWifi().localPing() 始终走catch；谢谢

**Comment by dingshaoran** [comment]
走到 catch 里的 log 发一下，报错的原因很多，不在同一个局域网只是其中一种

**Comment by liduojun** [comment]
你好，iOS最新的971版本（4.10.1.789）多部苹果手机无法安装，请查找原因，苹果手机6p、7p，12.1.2版本、12.0版本

**Comment by blockdate** [comment]
处理中，版本暂时回退
