### ISSUE TITLE
蓝牙数据包的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#213]
RN版本号869
接收数据的方法，如图
![snip20190108_3](https://user-images.githubusercontent.com/18459414/50954700-1ea0b300-14f2-11e9-9fe1-ec4951e2f384.png)

安卓版本接收到的数据包里面有多条数据，如图
![snip20190109_5](https://user-images.githubusercontent.com/18459414/50954677-10529700-14f2-11e9-99b8-7217a253c913.png)

RN版本接收到的数据包里面只有一条数据，如图

![snip20190108_2](https://user-images.githubusercontent.com/18459414/50954765-41cb6280-14f2-11e9-98d8-8f66f72e78b5.png)
请问这个是什么情况导致的，谢谢。

**Comment by dingshaoran** [comment]
看您的 log 文案 和 您截图的代码上输出的文案 对不上，并且您截图的 android 版本 log 看不出来是多条数据。请描述一下上下或者粘一下代码和 logcat 的 log，您这一点点截图信息量太少，不好理解

**Comment by dingshaoran** [comment]
两种框架的内部实现都是一样的，过滤 ‘miio-bluetooth’ 看看是不是设备返回的数据我们都收到了

**Comment by caojunhua** [comment]
> 看您的 log 文案 和 您截图的代码上输出的文案 对不上，并且您截图的 android 版本 log 看不出来是多条数据。请描述一下上下或者粘一下代码和 logcat 的 log，您这一点点截图信息量太少，不好理解

上面的截图是一个完整的数据包的数据，aaaa是这个数据包的包头，下面的数据包的包头也是aaaa,但是长度很短，长度应该和上面的一样长，就是说我RN里面的数据包，都是很短的，只有一条数据

**Comment by caojunhua** [comment]
> 两种框架的内部实现都是一样的，过滤 ‘miio-bluetooth’ 看看是不是设备返回的数据我们都收到了

我就是把接收到的数据包原封不动的打印出来的，发现接收到的数据包都好短，都是一条，实际上不止这么短的。

**Comment by lvjie0519** [comment]
Android  Studio Logcat 过滤‘miio-bluetooth 看一下，看看数据是否传递到了Android这边？

**Comment by lvjie0519** [comment]
@caojunhua   问题是否已经解决？

**Comment by caojunhua** [comment]
> @caojunhua 问题是否已经解决？

暂时还没有

**Comment by lvjie0519** [comment]
> > @caojunhua 问题是否已经解决？
> 
> 暂时还没有

APP层已经收到数据了，但是到RN这边数据就出问题了是吧？
安卓版本接收到的数据包里面有多条数据，如图。那个图是Android Studio LogCat里面输出的数据是吧？

**Comment by lvjie0519** [comment]
确定已经更新为最新的apk和sdk了

**Comment by caojunhua** [comment]
> 确定已经更新为最新的apk和sdk了
我刚更新了试试，还是一样的。。。
有多条数据的是安卓用java写的旧的项目，RN的项目收到的只有一条数据

**Comment by lvjie0519** [comment]
> > 确定已经更新为最新的apk和sdk了
> > 我刚更新了试试，还是一样的。。。
> > 有多条数据的是安卓用java写的旧的项目，RN的项目收到的只有一条数据

Android Studio  LogCat  用 miio-bluetooth 过滤下输出日志，应该会看到
onCharacteristicChanged for %s: value = %s, service = 0x%s, character = 0x%s   这样的log输出，看下value是否为正常的数据，和RN这边的数据是否一致。

**Comment by blockdate** [comment]
无新反馈
