### ISSUE TITLE
缺少callMethodForceWay接口

### ISSUE THREAD

**Issue by jianbin-rockrobo** [MiEcosystem/miot-plugin-sdk#215]
callMethodForceWay的功能具体请看0.25RN的文档

**Comment by blockdate** [comment]
duplicate #216 
参考接口迁移参考 ： [wiki](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/02-%E9%85%8D%E7%BD%AE%E4%B8%8E%E8%B0%83%E8%AF%95)
