### ISSUE TITLE
Host.ui.openWebPage报错（iOS）

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#218]
最新ipa、SDK

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Host

#### 现象

- iOS平台，调用 Host.ui.openWebPage 插件报错
- android上测试正常

**Comment by edwardair** [comment]
![screen shot 2019-01-11 at 5 36 48 pm](https://user-images.githubusercontent.com/2043635/51025609-7ceb9580-15c7-11e9-8bfc-94fda8b379b2.png)

**Comment by edwardair** [comment]
@kyou @Copypeng 这问题应该很容易修复的，麻烦更新下SDK

**Comment by blockdate** [comment]
@edwardair 经商讨后确认该API不提供，新SDK中已去除，如需使用webView请参考ReactNative的[Webview](https://facebook.github.io/react-native/docs/webview)
