### ISSUE TITLE
有没有定时器监听？

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#219]
例如
我在A手机对设置定时器 12点开启。B手机如何设置监听获取这个定时器设置。

**Comment by kfjihailong** [comment]
没有人回复吗？定时器实时的监听，，怎么设置呀，这个参数我如何填写？

**Comment by dingshaoran** [comment]
定时器监听是什么，您发一下哪个 api

**Comment by kfjihailong** [comment]
我就是，不知道，怎么设置监听才提问的呀：
我要实现这个功能:
我在A手机对设置定时器 12点开启。B手机如何设置监听获取这个定时器设置。

定时器的数据同步难道不是，监听器实现的吗？

**Comment by dingshaoran** [comment]
插件不能监听插件的，只能监听设备，您那边的固件开发需要开发订阅 定时器的功能 插件里调用 subscribeMessages 才能收到消息

**Comment by kfjihailong** [comment]
老版本的api中监听有一种轮询方式（6s一次轮旋），我可以在任何一个轮旋方式主动获取我定时器中的定时列表的。

**Comment by dingshaoran** [comment]
以前 ios 有，现在要插件里自己实现轮询的代码

**Comment by kfjihailong** [comment]
我自己实现轮询，会不会被测试提出，是数据泄露，后者，内存消耗过大的问题。

**Comment by kfjihailong** [comment]
咱们测试和开发不是思路，我老版本时候，吃了很多亏。反复的修改代码。

**Comment by dingshaoran** [comment]
您可以看看订阅怎么用，轮询在新版的 sdk 中，不推荐使用。

**Comment by dingshaoran** [comment]
我觉得您刚才说的问题，两个手机同时在插件页面，设置定时功能是否真的需要两个手机的数据同步呢，如果不同步也不会有任何问题，后设置的会覆盖之前设置的

**Comment by kfjihailong** [comment]
这也是我问的 另一个问题，一台设备是否允许，多个用户操作。因为之前老版本的api接口参数中有一个，us_id 参数，我查看是数据返回，这个参数没有了。如果我们允许用户一台设备多个用户操作，那么必定同步问题就会出现了。不然界面数据会紊乱。

**Comment by dingshaoran** [comment]
us_id 参数没有了，是米家的接口么，那个 api。如果怕数据紊乱 可以在插件里设置数据的地方，判断是设备的 Device.isOwner 才能控制设备。

**Comment by kfjihailong** [comment]
那么定时器，怎么设置修改呢？咱们接口中对有create和load操作，我有个需求，要对定时器进行修改，修改的唯一id是那个？方法是什么？

**Comment by dingshaoran** [comment]
米家只是为了 插件和设备固件 通讯的，通讯传递的数据内容你们自己商量就好了

**Comment by kfjihailong** [comment]
我们在老版本的中有一个，MHPluginSDK.callSmartHomeAPI('/scene/edit' 这个方法可以做定时器修改，我们有一个功能，不能在通用接口中使用。

**Comment by kfjihailong** [comment]
这个功能不能调用通用页面操作，要实现一个倒计时解决方案，如果界面一样用户就懵了。

**Comment by dingshaoran** [comment]
你这个接口是自动化里的，现有的 Service.scene.save 就是这个接口。不使用通用的自动化定时 可以自定义页面，看 demo 中 switch case Entrance.Scene 就是处理场景的
