### ISSUE TITLE
定时器修改如何实现？

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#220]
老sdk中我是通过d_id作为主键修改的，那么现在如何修改呢？

第二个问题 定时器中已经没有us_id这个字段了吗？是现在所有设置只和设备有关系，和用户没有关系了是吗？

**Comment by lvjie0519** [comment]
设备定时器的设置请参考 ui.js文件中的openTimerSettingPageWithVariousTypeParams方法。

**Comment by blockdate** [comment]
定时是设备上的定时，例如将设备分享之后，定时跟用户是没有强关系的。

定时器现不支持自行修改。如有这方面需求可以使用定时场景，Device.createTimerScene或者Service.Scene.creatTimerScene
