### ISSUE TITLE
MessageDialog  为什么只显示一次？

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#222]
#### 现象

```
<MessageDialog 
          cancel={LS.btn_cannel}
          cancelable={true}
          confirm={LS.filter_btn_replaceSure}
          onConfirm={()=>{
          }}
          title = {this.actionSheetTitle?this.actionSheetTitle:''}
          visible = {this.state.actionSheetShowable}
          />
```
使用 `            this.setState({
              actionSheetShowable: true,
            });
` 控制 MessageDialog 显示，但为什么第一次显示，点击 `"取消"`自动消失后，第二次Dialog不再显示？
#### 期望

MessageDialog能够多次显示

**Comment by lvjie0519** [comment]
1、请说明一下是哪个平台，Android、IOS或都存在？
2、确定使用的是否是最新的apk？
3、demo中是否存在同样的问题？

**Comment by edwardair** [comment]
知道原因了，是必须在  onDismiss 回调中，设置 this.state.actionSheetShowable为false才有效果，在onConfirm中设置没效果

**Comment by edwardair** [comment]
不过iOS上有点不爽，取消和确认按钮，手指碰上去就直接消失了？没有任何按钮效果，希望能够改进，安卓上没问题
