### ISSUE TITLE
Device.getDeviceWifi().subscribeMessages 不太好用，是我写错了吗

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/miot-plugin-sdk#224]
before issue：（不用回答）
### 是否尝试搜索issue？yes

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[/iOS 12.0]
- 相关模块:[Device]

#### 现象

简单明了地描述一下实际的现象。

利用Device 监听属性的改变，监听的回调方法始终没有结果

#### 期望
 Device.getDeviceWifi().subscribeMessages("on","usb_on","props.on","props.usb_on",)
        .then((subcription) => {
            //call this when you need to unsubscribe the message
             console.log('订阅消息' +JSON.stringify(subcription));
        })
        .catch(() => console.log('subscribe failed'));

代码如下，插座，当我利用app，控制插座的开关， 监听插座的 on 和usb_on 属性的时候，无论这两个属性如何改变，该监听无响应

**Comment by blockdate** [comment]
subscribeMessages功效相当于开启订阅，then中返回的值用于取消属性订阅。
实际的属性变更任然需要通过监听DeviceEvent.deviceReceivedMessages来获取。
具体使用可参考project/com.xiaomi.demo中的ControlDemo.js的componentDidMount的具体使用

同时我发现我们的文档说明描述的确不当，稍后我们会修改文档。

**Comment by hunter858** [comment]
可能还是有bug，我按照这个写法写了，并没有监听到设备属性的改变


 Device.getDeviceWifi().subscribeMessages("prop.on","prop.usb_on")
        .then((subcription) => {
            console.log('开启订阅消息' );
        });

        this._deviceStatusListener = DeviceEvent.deviceReceivedMessages.addListener(
            (device, map, res) => {
                console.log('Device.addListener:', JSON.stringify(device),
                JSON.stringify(map),
                JSON.stringify(res),
                JSON.stringify(this.state.timerRun));
              
        });

**Comment by JobenTian** [comment]
我也是这样用的，但是设备属性改变时，监听都没有反应，请帮忙关注一下这个问题，谢谢！

**Comment by hunter858** [comment]
@blockdate 那现在这个功能确定ok吗,我是按照你project/com.xiaomi.demo中的ControlDemo.js的componentDidMount的代码仿写的，
@JobenTian  这个开发者也遇到了同样的问题

**Comment by maker9** [comment]
关于DeviceEvent.deviceReceivedMessages这个问题，一直收不到消息
event.xxx 是开发平台-功能定义-事件?
日志出现subscribe called、receive device sub info 581321805.942268:(null)
