### ISSUE TITLE
Service.security.shareSecureKey 接口异常

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#225]
#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 12
- 相关模块: Service

#### 现象

Service.security.shareSecureKey 参数 settings 中 weekdays 属性处理有误。

Demo:
```javascript
const settings = {
  activeTime: 1547424000,
  expireTime: 1547471160,
  readonly: true,
  status: 2,
  weekdays: [1, 2, 5, 6],
};

Service.security.shareSecureKey(Device.deviceID, shareUid, settings);
```
从 `Service.security.loadSecureKeys(Device.deviceID)` 拿到该 key，属性 weekdays 值为 `[1]`;
在旧插件上查看该 key，weekdays 为 `"1?2?5?6"`;

#### 期望

key 的 weekdays 属性应该为数组；
希望补充 shareSecureKey 文档，比如 settings 参数具体属性以及说明。

**Comment by blockdate** [comment]
感谢您的反馈，问题已修复，更新SDK后删除该问题SecureKey，再次创建分享即可正常使用。
相关文档已进行更新。setting各项设置也可以直接查看如下：

```
@param readonly readonly = true, 则被分享人不可接收锁push，false则被分享人可接收锁push，（family关系用户不受这个字段影响）
@param status 分享类别，1：暂时，2：周期，3：永久
@param activeTime 生效时间 UTC时间戳，单位为s
@param expireTime 过期时间 UTC时间戳，单位为s
@param week 生效日期（星期几，例如周一和周三对应1和3，[1, 3]），仅在status=2时不可为空
```
