### ISSUE TITLE
Device.getDeviceWifi().callMethodFromCloud相关问题

### ISSUE THREAD

**Issue by fosen** [MiEcosystem/miot-plugin-sdk#226]
#### 环境  
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.0
- 相关模块:Device

#### 现象
调用
Device.getDeviceWifi().callMethodFromCloud("getProps", JSON.stringify(["battery"]))
            .then((res) => {
             console.log('success:', res);})
            .catch(err => console.error('failed:', err));
报错

#### 期望

请求设备电量

#### 其他的上下文/日志/截图
![wechatimg18](https://user-images.githubusercontent.com/15226994/51102598-891b6100-181a-11e9-806f-45cb391d3103.jpeg)

提供更多的上下文，有日志或者截图更好。

**Comment by blockdate** [comment]
别用console.error，在RN下会直接进入error界面。同时不要使用JSON.stringify，直接传入对应数组参数

**Comment by fosen** [comment]
不使用console.error和JSON.stringify，但是报错内容还是一样的。

**Comment by fosen** [comment]
> 别用console.error，在RN下会直接进入error界面。同时不要使用JSON.stringify，直接传入对应数组参数



> 别用console.error，在RN下会直接进入error界面。同时不要使用JSON.stringify，直接传入对应数组参数

不使用console.error和JSON.stringify，但是报错内容还是一样的。

**Comment by blockdate** [comment]
是直接进入crash界面，还是代码进入了catch分支

**Comment by fosen** [comment]
未进入crash界面，但是没有请求成功，返回的是failed：

**Comment by fosen** [comment]
请问 这个问题是哪里的原因，是调用方式的问题吗？

**Comment by fosen** [comment]
代码进入了catch分支

**Comment by blockdate** [comment]
这个错误是ot返回的 设备长链断了，可以认为和离线差不多，请检查下设备状态再尝试

**Comment by fosen** [comment]
已经检查设备在线状态，设备在线时返回error具体信息如下
![wechatimg19](https://user-images.githubusercontent.com/15226994/51164369-abbf7f80-18d7-11e9-911b-699235c03a69.jpeg)

**Comment by blockdate** [comment]
检查这个issue 是否有你的问题 #104 
同时参照下callMethod变化 [常见问题](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/33-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#callmethod-%E8%B6%85%E6%97%B6%E7%AD%89%E9%97%AE%E9%A2%98)

**Comment by fosen** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/15226994/51166439-6eaabb80-18de-11e9-8ec8-6de523d17785.png">

我想具体问下图中的method和params的定义方式是什么？例如：get_config_version和alarm_ops 这些method是硬件定义的吗？
let params = { "operation": "query", "req_type": "alarm", "index": 0 };这些也是硬件来定义的吗？

**Comment by blockdate** [comment]
对，需要和你们的硬件工程师沟通确定。

**Comment by fosen** [comment]
> 对，需要和你们的硬件工程师沟通确定。

<img width="725" alt="image" src="https://user-images.githubusercontent.com/15226994/54904173-b8d09e80-4f18-11e9-9618-930b66f93006.png">
![image](https://user-images.githubusercontent.com/15226994/54904193-c8e87e00-4f18-11e9-8b28-0bf32c257fb7.png)
硬件那边设置为图1
我按图二这种方式获取，这样对吗？

**Comment by fosen** [comment]
> 对，需要和你们的硬件工程师沟通确定。

<img width="647" alt="image" src="https://user-images.githubusercontent.com/15226994/54904284-106f0a00-4f19-11e9-975c-201df2170801.png">
![image](https://user-images.githubusercontent.com/15226994/54904291-1664eb00-4f19-11e9-9c39-90e0adf3e227.png)
图一是硬件的设置，图二是获取相关属性，这样处理有什么问题吗？

**Comment by fosen** [comment]
> 对，需要和你们的硬件工程师沟通确定。

<img width="548" alt="image" src="https://user-images.githubusercontent.com/15226994/54904387-5d52e080-4f19-11e9-831a-18e04a2f299e.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/15226994/54904427-7b204580-4f19-11e9-8ef2-68e0d8b7d8d2.png">


图一是硬件的设置，图二是获取相关属性，这样处理有什么问题吗？
