### ISSUE TITLE
android不能正常进入插件页

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#227]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]  Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] android 9
- 相关模块:[eg.Host/Service/Account]

#### 现象

前提相关说明：本插件页是我在iOS端迁移基本完成后，开始调试android发现不能进入插件页。

点击设备进入插件就报错：
终端日志：
![wechatimg116](https://user-images.githubusercontent.com/12531667/51103065-596d5880-181c-11e9-8b82-350f27920651.png)
远程调试日志：
<img width="822" alt="wechatimg115" src="https://user-images.githubusercontent.com/12531667/51103096-786bea80-181c-11e9-9d5f-a3cb3a4ed6db.png">

打开米家app有一个提示框，不确定是否影响插件页，截图如下：
![wechatimg119](https://user-images.githubusercontent.com/12531667/51103178-c41e9400-181c-11e9-843e-d00b68dff5d9.png)

进入插件页报错截图（进入插件页后，也有一个和刚进入app时一样的弹框，如下图）：
![wechatimg118](https://user-images.githubusercontent.com/12531667/51103187-ce409280-181c-11e9-99f6-e28c075cf9d0.jpeg)

![1547455916850](https://user-images.githubusercontent.com/12531667/51103233-ed3f2480-181c-11e9-9588-df2c0088f243.jpg)

#### 期望

期望可以正常进入插件页

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
首先确定一下提供的demo能够正常进入吗？

**Comment by dzonel** [comment]
demo没设备不能进入，android怎么创建虚拟设备？iOS勾选创建一个相应的虚拟设备，但并没有创建。

**Comment by dzonel** [comment]
这套代码，在iOS端可以正常进入插件页。

**Comment by lvjie0519** [comment]
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/调试说明.md
先看一下Android部分的调试文档，Android不需要创建虚拟设备，只需要对apk 开发者选项配置下就可以。

**Comment by dzonel** [comment]
不需要创建虚拟设备吗？没有设备怎么点击进入插件页？参见：Android插件调试 第4步

**Comment by dzonel** [comment]
是的啊，你不是说让我试试demo吗？但是我账号没有demo设备啊

**Comment by lvjie0519** [comment]
demo与设备并没有绑定啊，  您在开发者选项中将model修改为你自己设备的model就可以了，调试说明文档只是一个示例，希望可以帮到您。

**Comment by dzonel** [comment]
设备只和model关联？与包名无关吗？

**Comment by dzonel** [comment]
demo没问题

**Comment by lvjie0519** [comment]
你是Android 9.0及以上的系统吗？试试低版本的Android系统看看？
https://github.com/react-native-community/react-native-image-picker/issues/978
https://www.jianshu.com/p/f87fe39caf1d

**Comment by blockdate** [comment]
@dzonel 设备只与model关联，包名用于注册RN模块，跟插件关联

**Comment by dingshaoran** [comment]
Cannot find entry file projects/null/index.js 这个不是运行你当前项目的报错，米家一打开会提前初始化 rn 环境，进入到你的插件会重新 load com.shjszn.lock 的代码，看你的已经 bundle 成功了，应该是你代码里用的 api 有 ios 专属的

**Comment by dingshaoran** [comment]
你的报错红盒子说的很明显 MainPage.js :72,看一下这行是不是用了 SwitchIOS 之类的 ios 特有的 reactnative 属性。

**Comment by ldezho** [comment]
解决了
