### ISSUE TITLE
Ble setNotify直接报错

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#228]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Windows
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 8.0
- 相关模块:[eg.Host/Service/Account]
Bluetooth

#### 现象
获取到Characteristic后调用setNotify直接报MIOTBluetooth.setNotifyWithCallback got 4arguments, expected5.

之前版本是没问题的，更新了miot sdk开发环境后稳定出现。

![screenshot_2019-01-14-18-46-47-102_com xiaomi smarthome_ b f3130ba](https://user-images.githubusercontent.com/15820075/51108749-1c11c680-182e-11e9-881f-5c5539afa409.png)

**Comment by lvjie0519** [comment]
确定一下 是否为最新的 sdk和apk？

**Comment by lvjie0519** [comment]
确定下是否为最新sdk和apk？

**Comment by ding209** [comment]
@lvjie0519 
sdk和apk都已是目前最新。
transformer.js文件中我直接复制出来了：n.default.MIOTBluetooth.setNotifyWithCallback(u.id,e,c,s,function(e,o){e?r(t):i(o)})

是5个参数

**Comment by lvjie0519** [comment]
是刚更新sdk然后出现的问题吗？  清除下npm缓存及重启package服务试试？

**Comment by lvjie0519** [comment]
旧版是什么时候发布的版本？  我对比下是什么问题造成的，谢谢告知下。

**Comment by ding209** [comment]
@lvjie0519 刚才弄错了，，我这就把本也会出现。这错一会出现一会不出现。。我再研究研究
