### ISSUE TITLE
固件升级功能有文档说明吗？

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#229]
请问新版插件固件升级功能米家App会提供统一入口吗？是否区分平台？
目前未看到固件升级的相关api，也没看到相关的文档说明。

**Comment by blockdate** [comment]
这个目前没有提供，目前请自行使用蓝牙读写功能实现

**Comment by ding209** [comment]
@blockdate 我看到可以使用Host.ui.openDeviceUpgradePage()打开升级页面，但是没有找到如何刷新升级页面的Api，这个现在有提供吗？

**Comment by blockdate** [comment]
刷新升级页面的Api 是指什么操作
