### ISSUE TITLE
ble设备进入插件connected状态一直false

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#230]
#### 现象

米家App和设备的ble是已连接状态，并且米家主页面设备列表显示设备为在线状态， 但进入该设备调用 Device.getBluetoothLE().connected  得到的结果稳定false

#### 期望

期望可以正常得到设备连接状态，需要连接状态做不同的处理。

**Comment by lvjie0519** [comment]
在米家APP米家首页显示的设备在线仅仅表示设备wifi有连接或者蓝牙有效，并没有发生蓝牙相关连接操作，进入设备插件页面如果需要做蓝牙相关的操作需要先调用蓝牙连接api即connect方法。

**Comment by lvjie0519** [comment]
嗯，你理解的是对的。
在退出插件的时候需要调用disconnect断开连接，由于蓝牙连接发生在插件层，蓝牙连接的信息并不会保存到APP层，所以再次进入插件，相当于变量重新初始化了。

**Comment by dingshaoran** [comment]
退出插件后 js 的链接状态变量 已经从内存中销毁了，再次进入插件要判断是不是已经链接了必须要调用原生代码。现在你调用 connect 的时候在原生判断了链接状态如果链接了就直接返回给你成功。相当于两个方法合并成一个。
你的调用从
 bluetooth.isconnect.then(result=>{
   if(result){
        startDiscoverService()
   }else{
        bluetooth.connect().then(()=>startDiscoverService());
   }
})
简化为
 bluetooth.connect().then(()=>startDiscoverService());

并且一定要在插件退出的时候调用 disconnect,否则你的插件不能释放系统资源，有可能测试审核不通过。

**Comment by ding209** [comment]
@lvjie0519 @dingshaoran 非常感谢，还有个问题望解答：
新版本插件要如何获取当前的路由 栈内页面数量，因为需要监听Android系统的物理返回键，当监听到为插件首页面返回时退出插件并断开ble，当监听到插件其他页面返回时关闭页面。
现在的情况是我无法获取到栈内页面数量，也没找到办法去判断当前按返回键的是插件首页面。所以没法执行断开ble的代码。

**Comment by lvjie0519** [comment]
1、您可以自行查看下react-navigation是否提供获取栈内页面数量（我暂时没看到有相关方法）；
2、可以通过navigation传参，进入您的插件首页，设置一个标记flag，表示为插件首页；
3、您也可以通过事件监听PackageEvent.packageWillExit.addListener来实现。
