### ISSUE TITLE
secureKey 更新问题

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#231]
#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 12
- 相关模块: Service

#### 现象

把一个 status === 1 且 secureKey.isOutOfDate() 返回 true 的 secureKey 修改为 status === 3 后，secureKey.isOutOfDate() 仍然返回 true。

#### 期望

此时 secureKey.isOutOfDate() 应该返回 false。

**Comment by halloaw** [comment]
status === 3 的 secureKey，activeTime、expireTime 设置为
```javascript
secureKey.activeTime = Math.floor(Date.now() / 1000);
secureKey.expireTime = secureKey.activeTime;
```
是否与这个设置有关联？因为我直接分发 status === 3 的 secureKey 时，secureKey.isOutOfDate() 也是返回 true。

**Comment by blockdate** [comment]
目前的isOutOfDate是根据expireTime来计算的，status===3的状态是否会影响expireTime这个我们在确认中。

**Comment by blockdate** [comment]
两者暂时没有直接互相影响
