### ISSUE TITLE
检查固件升级

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#232]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[Device]

#### 现象

sdk是否有提供判断固件是否是最新的方法，
目前在文档中只找到Device.getDeviceWifi().startUpgradingFirmware()这个方法，但是一执行就有新版本就马上升级。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
可以尝试获取可用固件信息，并对比设备verision。
```
//获取可用固件信息
Service.smarthome.getAvailableFirmwareForDids([did]).then(res => {})
//获取设备固件版本
Device.getDeviceWifi().getVersion()
```

**Comment by mirse** [comment]
使用Service.smarthome.getAvailableFirmwareForDids([did]).then(res => {})返回的res不论有无新版本回调信息都是{“hasNewFirmware":true}

**Comment by blockdate** [comment]
返回信息中curVersion和newVersion有正常获取到吗

**Comment by mirse** [comment]
Service.smarthome.getAvailableFirmwareForDids([Device.deviceID]).then(res => {console.warn(res)})  信息就只有{“hasNewFirmware":true}，难道参数不是Device.deviceID吗？

**Comment by blockdate** [comment]
参数是ok的，这个接口不应该只返回这一个数据，我这边排查一下，你也可以再尝试smarthome.getLatestVersion(model)接口获取该类型设备的最新固件版本。

**Comment by blockdate** [comment]
确认下Device.model有值并且拥有固件信息，可以查看demo中 教程->与服务器交互->查询固件版本信息 能否正常获取固件版本信息

**Comment by mirse** [comment]
查看demo发现 参数并不需要加[ ]， 这样就可以获得最新固件版本

**Comment by blockdate** [comment]
对，getVersion用于获取某一种设备，参数传入单个model。

getAvailableFirmwareForDids接口已修正，demo中添加相应示例 教程->与服务器交互->查询当前设备版本信息

**Comment by mirse** [comment]
当我使用Device.getDeviceWifi().getVersion()来获取设备固件版本的时候 得到的信息是{”_40“:0,”_65“:0,”_40“:0,”_55“:null,”_72“:null}，使用Service.smarthome.getLatestVersion可以得到version：1.35.5__xxxx,这二者该如何对比。

**Comment by blockdate** [comment]
更新sdk，使用getAvailableFirmwareForDids，查看返回的newVersion和curVersion即可。

**Comment by mirse** [comment]
ok
