### ISSUE TITLE
Service.smarthome.getDeviceData 重复调用，只会返回一次

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/miot-plugin-sdk#234]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- 相关模块:[Service]

#### 现象
多次调用一个接口，之执行了一次block回调

#### 期望

调用5次，应该回调5次

#### 其他的上下文/日志/截图

componentDidUnmount（){
     this.getPowerData(params1);
     this.getPowerData(params2);
     this.getPowerData(params3);
     this.getPowerData(params4);
     this.getPowerData(params5);
}
getPowerData(params){

 Service.smarthome.getDeviceData(params)
        .then((response) => {
            console.log('response'+JSON.stringify(response))
        })
        .catch(err=>{
            console.log('callSmartHomeAPI.err:'+JSON.stringify(err))
        });
}

大概就是这样的代码，
那我多次调用 Service.smarthome.getDeviceData() 这个方法，只会有一次返回

**Comment by blockdate** [comment]
经测试未复现该问题，可使用最新APP以及SDK使用。

如果还有问题，请附上具体的请求参数以及输出结果。

> js中如果连续输出内容一致会合并输出，只输出一条信息，在信息前会有次数提示，请确认日志输出的确只有一次。
