### ISSUE TITLE
Host.audio.startPlay()调用执行不成功

### ISSUE THREAD

**Issue by shidaiyue1** [MiEcosystem/miot-plugin-sdk#235]
before issue：（不用回答）
### 是否尝试搜索issue？
Host.audio.startPlay(require('../Resources/audio/auto_acc.mp3'), params).then((response)=>{
            if (response) {
                var duration = response.duration;
            }
            else {
                // alert(JSON.stringify(response))
                console.log(response);
            }
        }).catch(error =>console.log('error',error));
---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:ios
- 相关模块:[eg.Host.audio]

#### 现象

error Fail to create a audio player! error code: 2003334207, domain:NSOSStatusErrorDomain, userInfo:{
}, localizedDescription:未能完成操作。（“OSStatus”错误 2003334207。）

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
更新SDK，已修复
