### ISSUE TITLE
DeviceProperties.notifyPropertiesChanged();报错

### ISSUE THREAD

**Issue by coderLM** [MiEcosystem/miot-plugin-sdk#236]
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- 相关模块:[Properties]

#### 现象
DeviceProperties.notifyPropertiesChanged();报错
错误类型：
undefined is not an function(... filter ...)...

我自定义了notifyPropertiesChanged（）方法，并将
 const changed = props.filter(p=>this.isPropertyChanged(p));
改为
 const changed = [...props].filter(p=>this.isPropertyChanged(p));
不再报错

**Comment by lvjie0519** [comment]
已修复，请更新下sdk。

**Comment by lvjie0519** [comment]
已修复，请更新下sdk。
