### ISSUE TITLE
蓝牙固件升级页面有提供统一接口吗？

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#237]
请问蓝牙固件升级在不同平台有统一的固件升级页面吗？之前Android有统一的接口BleUpgrader，在新版插件里我看到有打开固件升级页面的Api：Host.ui.openDeviceUpgradePage()；但是没找到该页面的升级回调及如何刷新该页面各种升级状态的相关文档或Api。

所以固件升级页面应该由自己自定义完成吗？

**Comment by lvjie0519** [comment]
没有统一的蓝牙固件升级，Host.ui.openDeviceUpgradePage() 是实现wifi固件升级的；
蓝牙的升级要通过 characters 写数据，每个蓝牙都不一样，由插件方自定义完成。
