### ISSUE TITLE
DeviceProperties.addListener(names, callback)回调参数问题

### ISSUE THREAD

**Issue by coderLM** [MiEcosystem/miot-plugin-sdk#239]
- 手机系统:[Android]
#### 现象
sdk 的问题：
DeviceProperties.addListener(names, callback);方法的例子如下：
`const eventSubscription = DeviceProperties.addListener("prop1", (deviceProperties)=>{...}) `
实际上deviceProperties为空。
因为sdk中没有传入props:

![image](https://user-images.githubusercontent.com/46736981/51300234-27e7cd80-1a66-11e9-916f-9e396d604453.png)

这就导致，如果我在调用DeviceProperties.addListener(names, callback)方法时传入多个参数，回调时不知道到底是哪个参数发生了变化。
除非针对不同的prop，add不同的listener，这样又太麻烦。
#### 期望
能不能在触发回调时传入对应的prop。

**Comment by lvjie0519** [comment]
已修复，将当前对象返回来了，请更新下sdk。

**Comment by coderLM** [comment]
返回当前对象没有意义，因为一般情况下，DeviceProperties就是当前对象。
也没解决现在的问题：
如果我在调用DeviceProperties.addListener(names, callback)方法时传入多个参数，回调时不知道到底是哪个参数发生了变化。
除非针对不同的prop，add不同的listener

**Comment by coderLM** [comment]
![image](https://user-images.githubusercontent.com/46736981/51306950-718de380-1a79-11e9-8424-bb3a246493e5.png)

你看这样改是否可行

**Comment by coderLM** [comment]
还有问题，我再改改

**Comment by coderLM** [comment]
![image](https://user-images.githubusercontent.com/46736981/51307763-73f13d00-1a7b-11e9-88fe-05c6f8610559.png)

**Comment by lvjie0519** [comment]
已修复，如下调用方式。
this.eventSubscription = DeviceProperties.addListener(["on", "mode"], (deviceProps, changeProps)=>{
            console.log("changeProps", changeProps.getChangeProps())
      })
