### ISSUE TITLE
callMethod 错误

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#240]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图
![wechatimg18](https://user-images.githubusercontent.com/13000673/51361839-41dbeb80-1b0c-11e9-83b5-41b55bf6965e.jpeg)

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
参考[常见问题](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/33-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)， -7表示设备ID有问题

**Comment by betterFuture** [comment]
iOS端 ，创建的虚拟设备，有设备ID吗

**Comment by blockdate** [comment]
。。。虚拟设备仅用于UI调试
