### ISSUE TITLE
新版米家扩展程序

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#241]
新版米家扩展程序，创建虚拟设备，为何com.xiaomi.demo 我跑不了， 返回的是the device is no initialized
![5436a9906e17e2f442fb5bbad04ad9c4](https://user-images.githubusercontent.com/38349220/51368713-8925a480-1b2b-11e9-8374-272fe13de640.png)

**Comment by blockdate** [comment]
检查下是否调用了Device.getBluetoothLE()，该方法在虚拟设备中使用会报错。

**Comment by blockdate** [comment]
因为Android不支持虚拟设备，SDK中并未对此作兼容，建议使用真实设备连接后修改为对应model测试插件。

**Comment by liuhaixu666** [comment]
我是ios项目

**Comment by liuhaixu666** [comment]
我用的是自己的手机，下的是他给的debug米家调试的

**Comment by liuhaixu666** [comment]
> 1、请说明下平台，Android或IOS?
> 2、跑一个RN 扩展程序，请先阅读 调试说明文档
> [https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/调试说明.md](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E8%B0%83%E8%AF%95%E8%AF%B4%E6%98%8E.md)
> 希望可以帮到您。

我自己创建的ios扩展程序，用虚拟设备可以跑，跑他的demo。就报the device is not inittialized,而且项目根本就没运行，就出现这个页面了

**Comment by liuhaixu666** [comment]
> 检查下是否调用了Device.getBluetoothLE()，该方法在虚拟设备中使用会报错。



> 检查下是否调用了Device.getBluetoothLE()，该方法在虚拟设备中使用会报错。

是不是他给的demo里还需要按配置一下什么属性啊

**Comment by liuhaixu666** [comment]
> > 我自己创建的ios扩展程序，用虚拟设备可以跑，跑他的demo。就报the device is not inittialized,而且项目根本就没运行，就出现这个页面了
> 
> 运行demo不需要额外配置，主要就是在开发者选项中配置对应的插件包名和设备model，您尝试配置一个真实设备的model试试。

这个怎么配置啊，我一直不太清楚，真实项目的model 咱也不知道啊

**Comment by lvjie0519** [comment]
> > > 我自己创建的ios扩展程序，用虚拟设备可以跑，跑他的demo。就报the device is not inittialized,而且项目根本就没运行，就出现这个页面了
> > 
> > 
> > 运行demo不需要额外配置，主要就是在开发者选项中配置对应的插件包名和设备model，您尝试配置一个真实设备的model试试。
> 
> 这个怎么配置啊，我一直不太清楚，真实项目的model 咱也不知道啊

1、你们做开发没有一个真实设备吗？
2、怎么配置请先阅读 调试说明文档，在米家APP中进行配置，文档中有关于Android和IOS 配置说明。
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/调试说明.md

**Comment by liuhaixu666** [comment]
> 因为Android不支持虚拟设备，SDK中并未对此作兼容，建议使用真实设备连接后修改为对应model测试插件。

那也就是说，我创建的虚拟设备，用手机是无法调试bledemo的啊，必须要用真实连接米家的设备才可以调
