### ISSUE TITLE
Service.scene.loadTimerScenes() 返回结果不正确

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/miot-plugin-sdk#242]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- 相关模块:[Service]

#### 现象

Service.scene.loadTimerScenes(Device.deviceID, TimerQuestData) 回调的response 的数据无法json 解析

#### 期望
返回的数据正常，且可以解析
简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

var self = this;
        var TimerQuestData = {
            "did": this.state.did,
            "st_id": "8",
            "identify": this.state.did,
        };
        Service.scene.loadTimerScenes(Device.deviceID, TimerQuestData)
        .then((sceneArr) => {
            console.log('loadScenes:sceneArr:'+JSON.stringify(sceneArr));
            if(sceneArr.length > 0){
                
            }
        })
        .catch(()=>{
            console.log('error:'+JSON.stringify(error));
        });

这个是之前新框架之前的代码和返回的数据；
![wechatimg157](https://user-images.githubusercontent.com/16034056/51371219-824f5f80-1b34-11e9-8963-cfa9685ccae5.jpeg)

这个是现在用的新框架的代码和返回的数据；
![wechatimg160](https://user-images.githubusercontent.com/16034056/51371228-8aa79a80-1b34-11e9-957a-45714436543f.jpeg)

API 文档写的不够详细，都没有说明入参到底需要传哪些参数，demo里也没有案例，希望后期进行优化提供给开发者的demo

**Comment by blockdate** [comment]
这个在文档中应该都是有描述的，[loadTimerScene](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/15-%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1_%E5%9C%BA%E6%99%AF%E6%A8%A1%E5%9D%97#moduleexportsloadtimerscenesdeviceid-opt--promisearrayiscene)接口获取scene列表，参数opt为{identify,name}文档中有说明，返回[IScene](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/15-%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1_%E5%9C%BA%E6%99%AF%E6%A8%A1%E5%9D%97#module_miot/service/scene--module.exports.IScene)对象，该对象的属性及方法在文档中皆有描述。
如果文档中仍然有疑问，请及时提问。

**Comment by hunter858** [comment]
好的，谢谢，已经解决，知道了是【IScene】对象，就知道里面的东西怎么取了
