### ISSUE TITLE
Host.file.screenShotInRect截屏失败

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#243]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Host

#### 现象

截屏失败，alert没有执行
<img width="915" alt="image" src="https://user-images.githubusercontent.com/7885251/51376207-b9c50880-1b42-11e9-917d-fbcc03c24d8e.png">
而出现黄色警告
<img width="394" alt="image" src="https://user-images.githubusercontent.com/7885251/51376328-0872a280-1b43-11e9-9077-f1952c43e500.png">

#### 期望

正常回调截图保存地址

**Comment by JxXiaoXie** [comment]
就报 save image failed

**Comment by hunter858** [comment]
Host.file.screenShot('share.png').then((res)=>{

                        Host.ui.openShareListBar('小米智能家庭', '小米智能家庭', { uri: res },'');
});

我这么写的没问题，截屏后 分享，res 就是返回的image的路径

**Comment by JxXiaoXie** [comment]
> Host.file.screenShot('share.png').then((res)=>{
> 
> ```
>                     Host.ui.openShareListBar('小米智能家庭', '小米智能家庭', { uri: res },'');
> ```
> });
> 
> @JxXiaoXie 我这么写的没问题，截屏后 分享，res 就是返回的image的路径

嗯，我用屏幕截屏也没有问题，但是用screenShotInRect就有问题。

**Comment by blockdate** [comment]
打印下你的rect具体数据，screenshot内部使用的就是screenShotInRect，大小是全屏幕。

**Comment by JxXiaoXie** [comment]
rect格式
<img width="826" alt="image" src="https://user-images.githubusercontent.com/7885251/51523294-57337b80-1e66-11e9-8003-1ce7e71263fd.png">

**Comment by blockdate** [comment]
系双平台对frame格式不同处理问题，已解决，更新SDK即可
