### ISSUE TITLE
Cannot read property 'navigate' of undefined

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#244]
this.props.navigation.navigate 报错 Cannot read property 'navigate' of undefined

- 
<img width="930" alt="7b4d310e-a376-4c39-b29a-294162915842" src="https://user-images.githubusercontent.com/38349220/51377238-58eaff80-1b45-11e9-9e57-a9463c816813.png">

**Comment by liuhaixu666** [comment]
这个语法是废弃了吗

**Comment by lvjie0519** [comment]
1、请说明一下平台，Android或IOS？
2、是通过navigation.navigate打开的界面吗 ？可以参考com.xiaomi.demo 这个扩展程序。
我这边是Android平台，没发现问题。
![image](https://user-images.githubusercontent.com/22487747/51377929-0579b100-1b47-11e9-84f3-249338cbd8c3.png)

**Comment by liuhaixu666** [comment]
> 1、请说明一下平台，Android或IOS？
> 2、是通过navigation.navigate打开的界面吗 ？可以参考com.xiaomi.demo 这个扩展程序。
> 我这边是Android平台，没发现问题。
> ![image](https://user-images.githubusercontent.com/22487747/51377929-0579b100-1b47-11e9-84f3-249338cbd8c3.png)

ios, 就是跑的com.xiaomi.demo ，出现的这个问题

**Comment by liuhaixu666** [comment]
> > 1、请说明一下平台，Android或IOS？
> > 2、是通过navigation.navigate打开的界面吗 ？可以参考com.xiaomi.demo 这个扩展程序。
> > 我这边是Android平台，没发现问题。
> > ![image](https://user-images.githubusercontent.com/22487747/51377929-0579b100-1b47-11e9-84f3-249338cbd8c3.png)
> 
> ios, 就是跑的com.xiaomi.demo ，出现的这个问题

我的rn版本是2.0，跟版本有关系吗
<img width="306" alt="ea4941a1-362c-4708-a615-b1a327b37089" src="https://user-images.githubusercontent.com/38349220/51379900-791dbd00-1b4b-11e9-94ff-f823c5a95717.png">

**Comment by blockdate** [comment]
确认一下react-native的版本，我们使用的是0.54.4

**Comment by liuhaixu666** [comment]
> 确认一下react-native的版本，我们使用的是0.54.4

那我怎么把本地的回退到0.544啊

**Comment by blockdate** [comment]
我是指react-native的版本，不是react-native-cli的版本。
可以尝试删除本地nodemodule，随后重新npm install

**Comment by liuhaixu666** [comment]
> 我是指react-native的版本，不是react-native-cli的版本。
> 可以尝试删除本地nodemodule，随后重新npm install

我就是重新npminstall 的， 在哪看这个版本啊

**Comment by blockdate** [comment]
在项目根目录执行react-native -v，
```
$ react-native -v
react-native-cli: 2.0.1
react-native: 0.54.4
```
