### ISSUE TITLE
Host.file.longScreenShot问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#245]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:Host

#### 现象

scrollview截屏成功，alert有打印保存路径，但是，显示在界面上的scrollview 区域变成了一片空白
<img width="877" alt="image" src="https://user-images.githubusercontent.com/7885251/51377311-8f287f00-1b45-11e9-84ca-4976a9c55105.png">

截屏后的效果图：
<img width="396" alt="image" src="https://user-images.githubusercontent.com/7885251/51377417-d151c080-1b45-11e9-9d46-d8e8a688d296.png">

#### 期望

截屏成功，截屏的内容也还在。

**Comment by blockdate** [comment]
能提供一下页面样式以及scrollview关键代码示例吗，便于我们排查问题。

**Comment by edwardair** [comment]
@blockdate 我能说这个问题其实已经提了一个多月了嘛~~ #105

**Comment by blockdate** [comment]
非常抱歉，这个问题之前该问题我没有follow。

本地测试发现会对该功能的确会对scrollView的frame进行变动，现在本地测试已经OK，更新app查看问题是否修复。

**Comment by JxXiaoXie** [comment]
试了下，已修复。
