### ISSUE TITLE
DialogTest

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#246]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[Dialog]

#### 现象

在官方demo里的DialogTest，除了最后两个时RN自带的，其余的dialog都是调用原生的吗?原生的就比较难定制化了，能考虑添加一些RN的dialog吗？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、对，都是调用原生的；
2、调用原生的Dialog是因为能够做到与原生扩展程序UI一致，您需要做哪些方面的定制化呢？
3、暂时还没有添加的计划，您可以先提供一些需求或建议，可以帮您反馈。

**Comment by mirse** [comment]
你们可以考虑将以下需求添加：
1、InputDialog中的TextInput的输入字数限制  
2、Dialog的显示位置 
3、Dialog的样式，例如：颜色，圆角等等

**Comment by lvjie0519** [comment]
>           你们可以考虑将以下需求添加：
> 1、InputDialog中的TextInput的输入字数限制
> 2、Dialog的显示位置
> 3、Dialog的样式，例如：颜色，圆角等等

您好，这边暂时不会提供其他样式的Dialog，主要是为了与米家APP的样式统一，建议贵方UI设计能与米家APP一致，如果因为某些原因设计的不一致，可能需要贵方自己实现了。
