### ISSUE TITLE
新平台新建拓展程序名称有什么要求么？

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#248]
#### 现象
新平台新建拓展程序名称没有看到相关的要求，不敢随便取，请问有什么要求么？

#### 期望 
知道新拓展程序命名规则

#### 其他的上下文/日志/截图

![131548127831_ pic_hd](https://user-images.githubusercontent.com/18681867/51513865-00b74480-1e48-11e9-8ad9-d7a9a8a24ce1.jpg)

**Comment by blockdate** [comment]
没有限制，建议与你们设备取一样的名字，例如 `小米智能闹钟`这样，这里仅用于管理使用。
