### ISSUE TITLE
米家App(ios)闪退

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#249]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS 11.0]
- 相关模块:[?]

#### 现象

使用ios开发插件时，常常会遇到闪退，整个App闪退，，而且没有任何提示，在安卓端却不会闪退。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供下版本，或尝试更新iPA升级至最新，有一个版本会因为某个通知导致异常。

同时可以连接mac，通过xcode->window->device ->console 查看闪退日志，并提供给我们。

**Comment by mirse** [comment]
最新版依旧会遇到闪退，通知具体指？

**Comment by blockdate** [comment]
@Handby 如果有蓝牙的的问题，请单开一个issue，然后描述你的问题，具体操作和日志输出。

**Comment by blockdate** [comment]
无反馈
