### ISSUE TITLE
更新最新sdk和apk后发现无法进入插件

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#250]
#### 环境
- 电脑操作系统:Windows7
- 手机系统:Android 8.1

#### 现象
完整错误日志
```
error: bundling failed: NotFoundError: Cannot find entry file projects/com.inshow.watch.io/index.js in any of the roots: ["D:\\workspace\\Frontend\\inso\\miot-plugin-sdk","D:\\workspace\\Frontend\\inso\\miot-plugin-sdk\\miot-sdk"]
    at DependencyGraph.getAbsolutePath (D:\workspace\Frontend\inso\miot-plugin-sdk\node_modules\metro\src\node-haste\DependencyGraph.js:316:11)
    at D:\workspace\Frontend\inso\miot-plugin-sdk\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:280:416
    at Generator.next (<anonymous>)
    at step (D:\workspace\Frontend\inso\miot-plugin-sdk\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:445)
    at D:\workspace\Frontend\inso\miot-plugin-sdk\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:605
```

请检查下发布的调试apk是否有问题，因为我使用之前的某个版本apk调试是好的。2019年01月23日留。

**Comment by lvjie0519** [comment]
Android RN的入口应该是index.js文件，不是index.android.js，检查一下你的项目是否正确？

**Comment by ftc300** [comment]
没有错，一直就是index.js

**Comment by lvjie0519** [comment]
>           没有错，一直就是index.js

Cannot find entry file projects/com.inshow.watch.io/index.js
看错误是缺少index.js文件， 我刚才把我项目中的index.js文件改为其它名，跟你报错是一样的，你尝试运行下提供的demo看是否能够正常，我这边在看看。

**Comment by ftc300** [comment]
说到提供的demo，ios可以添加蓝牙开发板，但是安卓手动添加里没有设备。不知道有没有什么方便的调试方法。

**Comment by lvjie0519** [comment]
>           说到提供的demo，ios可以添加蓝牙开发板，但是安卓手动添加里没有设备。不知道有没有什么方便的调试方法。

ios可以添加蓝牙开发板，是指从哪添加？
Android可以通过米家首页右上角点击 “+”进入到添加设备页，其他项 下有蓝牙开发板，我的账号下有显示。

**Comment by ftc300** [comment]
方便加个联系方式吗？这样效率有点差。wechat？

**Comment by lvjie0519** [comment]
>           方便加个联系方式吗？这样效率有点差。wechat？

![image](https://user-images.githubusercontent.com/22487747/51599276-2c1a5c00-1f3a-11e9-8dea-d86e123da536.png)
