### ISSUE TITLE
更新后想看demo显示the device is not initialized

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#251]
before issue：（不用回答）
### 是否尝试搜索issue？搜索了，有相同的，但是没有解决问题

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 11.0
- 相关模块:[eg.Host/Service/Account]

#### 现象

想看小米demo里面的UI，之前869版本是可以跑的，但是今天更新了API和SDK,想临时看一下demo，发现进不去了，页面提示“the device is not initialized”，自己项目可以跑，应该是demo哪里出了点bug。（跑com.xiaomi.demo 是创建的虚拟设备）

#### 期望

能运行起来就好了，学习一下UI

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/18374383/51594448-6b8f7b00-1f2f-11e9-9785-59ac18dacba1.png)

#### 尝试过的解决办法

1.使用之前的sdk 
2.使用之前869版本的API（但是没地方下载了）
3.删除index.js及Main.js相关代码，只显示一个textview（进去还是提示“the device is not initialized”）

### 不要贴大段代码❗️

希望可以得到回复，谢谢！

**Comment by zhuxinleibandou** [comment]
跪求开发大大来此帮助偶解决问题～非常感谢～

**Comment by blockdate** [comment]
更新下SDK吧，因为之前在demo中引入了蓝牙模块，蓝牙模块现在是不支持虚拟设备的，所以报错了。
现在去除了，应该可以了。

**Comment by zhuxinleibandou** [comment]
> 更新下SDK吧，因为之前在demo中引入了蓝牙模块，蓝牙模块现在是不支持虚拟设备的，所以报错了。
> 现在去除了，应该可以了。

效率好高啊你们！赞！刚提交不就就看到sdk有更新，描述是“移除了蓝牙模块”，我就知道肯定是这个问题，赞！！6666，谢谢！
已更新，可以进去了
