### ISSUE TITLE
Android系统返回键怎么处理

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#252]
自己的项目中不管在哪个页面按返回键都会直接退出插件，但是米家demo中是正常的，按返回键会回到上个页面。
目前没找到原因，请指点一下。

**Comment by lvjie0519** [comment]
没有什么特殊的地方，请问您使用的是navigation进行页面跳转的吗？我刚才尝试用命令创建一个新项目，使用navigation进行页面跳转，按物理返回键都会回到上一个页面。

**Comment by ding209** [comment]
是使用的navigation，我也检查很久了，跳转方式都是和demo中一样的，但自己的项目中一直都是直接退出插件。。

**Comment by lvjie0519** [comment]
检查一下react  native版本是否一致？navigation版本等等？

**Comment by lvjie0519** [comment]
1、请尝试自己创建一个新项目，使用navigation跳转，是否有问题？
2、如果还未解决，可以将您的项目裁剪给我一份，帮您调试看看。
