### ISSUE TITLE
更新最新的SDK和App后，iOS找不到service

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#253]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS12
- 相关模块:[eg.Host/Service/Account]Bluetooth

#### 现象

更新后可以connect成功，但是在发现service和character的监听里收不到扫描到的service和character，更新前可以。

#### 期望

可以发现service和character。

**Comment by blockdate** [comment]
请检查下你测试使用的model是否是属于蓝牙设备，目前只有注册申请为蓝牙设备的的外设才可以正常使用蓝牙功能，其他设备，例如wifi设备，进入调试模式时是无法正常获取蓝牙通知等功能的。

**Comment by Handby** [comment]
检查过了属于蓝牙设备，应该是没问题的，我们这个产品已经上线了

**Comment by blockdate** [comment]
帮确认下，调用Bluetooth.startScan(...)，能收到蓝牙外设discover的通知吗。
```
BluetoothEvent.bluetoothDeviceDiscovered.addListener((data) => {
            console.log("bluetoothDeviceDiscovered:", data);
        });
```

**Comment by blockdate** [comment]
如果当前无法接收到外设发现消息的话，更新下最新的APP(61)重试，目前已开放蓝牙模块的model限制

**Comment by Handby** [comment]
> 帮确认下，调用Bluetooth.startScan(...)，能收到蓝牙外设discover的通知吗。
> 
> ```
> BluetoothEvent.bluetoothDeviceDiscovered.addListener((data) => {
>             console.log("bluetoothDeviceDiscovered:", data);
>         });
> ```

可以收到蓝牙外设通知

**Comment by Handby** [comment]
> 如果当前无法接收到外设发现消息的话，更新下最新的APP(61)重试，目前已开放蓝牙模块的model限制

我更新了，logo上显示63，还是没有收到service和character，请问你那边都是正常的吗？

**Comment by blockdate** [comment]
这个是能正常使用的，可以的话提供下你的具体使用方式

**Comment by zaxayn** [comment]
@blockdate  我刚又更新了最新的，现在已经可以了，谢谢。
