### ISSUE TITLE
Warning: Failed prop type: Invalid props.contentStyle key `color` supplied to `RkButton

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#255]
Warning: Failed prop type: Invalid props.contentStyle key `color` supplied to `RkButton`.
Bad object: {
  "flexDirection": "column",
  "backgroundColor": "#0000",
  "color": "#00000088",
  "fontSize": 14,
  "alignItems": "center",
  "justifyContent": "center",
  "textAlignVertical": "center",
  "textAlign": "center"
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
  "end",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginEnd",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingEnd",
  "borderWidth",
  "borderTopWidth",
  "borderStartWidth",
  "borderEndWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderStartColor",
  "borderEndColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomEndRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in RkButton (created by i)
    in i (at index.js:14)
    in RCTView (at View.js:78)
    in View (at index.js:13)
    in App (created by a)
    in a (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
请描述下是运行demo出现的错误还是你自己的项目中出现的错误？ 
Failed prop type: Invalid props.contentStyle key color supplied to RkButton
看错误是RkButton的contentStyle样式中使用了color ，检查下是否使用错误。

**Comment by blockdate** [comment]
‘#88’ 就不是可用颜色。使用 ‘black’或者‘#ffffff’这种符合规则的color

**Comment by ldezho** [comment]
用到TitleBarBlack的地方都出出现这种警告。建议检查一下SDK中的RkButton

**Comment by blockdate** [comment]
该问题为误报错误，不影响使用
