### ISSUE TITLE
android 解压文件失败

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#256]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] 
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account] Host.file

#### 现象

调用Host.file.downloadFile(fileUrl, 'dfu_file.zip')下载升级文件，下载成功后，调用Host.file.unzipFile('dfu_file.zip')解压失败，catch里面的error为false，没有其他信息了。
iOS可以解压成功，android是否存在路径问题？或者是其他问题？

继续调试，调用Host.file.isFileExists('dfu_file.zip')发现.then返回为true，可以说明文件是存在的。解压失败

#### 期望

解压成功

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
确保用的是最新SDK和APK？

**Comment by ldezho** [comment]
是的

**Comment by lvjie0519** [comment]
测试我这边正常，使用最新sdk，应该会返回错误日志，
麻烦给一下您压缩包的下载地址或者尝试使用如下地址，看下是否有问题？
http://cdn.cnbj0.fds.api.mi-img.com/miio_fw/8229041d5532e4c8389cce0469299ef3_upd_inshow.watch.w1.bin?GalaxyAccessKeyId=5721718224520&Expires=1550972034000&Signature=yCSX06T+IKQ0RHkAznK+H8PRtlc=

**Comment by ldezho** [comment]
可以了，sdk是最新的，apk不是，更新了下apk就好了，抱歉。

**Comment by weeksun23** [comment]
我也是遇到了类似的问题：
调用Host.file.downloadFile(fileUrl, 'maptempdata')下载地图文件，下载成功后，调用Host.file.ungzFile('maptempdata')解压失败，catch里面的error为false，没有其他信息了。
sdk是最新的，apk昨天刚装的。

**Comment by lvjie0519** [comment]
> @lvjie0519 我也是遇到了类似的问题：
> 调用Host.file.downloadFile(fileUrl, 'maptempdata')下载地图文件，下载成功后，调用Host.file.ungzFile('maptempdata')解压失败，catch里面的error为false，没有其他信息了。
> sdk是最新的，apk昨天刚装的。

Host.file.downloadFile(fileUrl, 'maptempdata.zip') 试试

**Comment by weeksun23** [comment]
@lvjie0519 试过不行，我用的是ungzFile，maptempdata.gz和maptempdata.tar都不行

**Comment by lvjie0519** [comment]
@weeksun23 麻烦 fileUrl具体值给我，我这边测试下看看

**Comment by weeksun23** [comment]
@lvjie0519 https://cnbj2.fds.api.xiaomi.com/viomi-device/888819681/85406492/0?Expires=1550656727000&GalaxyAccessKeyId=5811787359989&Signature=Hvea8YVgfFZpBwkgpImdT3gjoAg=

**Comment by lvjie0519** [comment]
> @lvjie0519 https://cnbj2.fds.api.xiaomi.com/viomi-device/888819681/85406492/0?Expires=1550656727000&GalaxyAccessKeyId=5811787359989&Signature=Hvea8YVgfFZpBwkgpImdT3gjoAg=

您这个链接对应的是一个压缩文件吗？浏览器输入不是一个文件额，是否与参数有关
请更新下sdk，已经将错误信息返回

**Comment by weeksun23** [comment]
@lvjie0519  不好意思，原来这个文件需要另外的解压方法处理，已发需求邮件，请查收，谢谢。
