### ISSUE TITLE
setUserColl和getUserColl数据排序方式

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#257]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[Service]

#### 现象

当调用setUserColl后，使用getUserColl拿到数据，想知道数据排序方式是什么方式？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
目前来看是依据时间排序

**Comment by mirse** [comment]
> 目前来看是依据时间排序
但是我这边看来应该是按名称排序的吧
