### ISSUE TITLE
求Android 设备Wi-Fi强度计算公式

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#259]
---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- 相关模块:[Device]

#### 现象

原Android 通用设置里面有网路信息条目 ，点进去需要显示网路强度，现在不知道Wi-Fi强度的计算公式

#### 期望

最好能有直接进入网络信息的接口，
如果没有，请告知Wi-Fi强度计算借口

#### 其他的上下文/日志/截图

![151548727837_ pic](https://user-images.githubusercontent.com/18681867/51879393-2c897b80-23ae-11e9-8653-f7ea5282cae5.jpg)

**Comment by lvjie0519** [comment]
已增加api，Device.readDeviceNetWorkInfo，请使用最新sdk和apk，谢谢。
