### ISSUE TITLE
界面横屏问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#260]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS
- 相关模块:

#### 现象

米家首页横屏没有适配

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/7885251/51881909-ec2efb00-23b7-11e9-87c9-22723a60c803.png">

我们插件有些界面的横屏的，虽然在界面上使用了 Orientation.lockToLandscape(); 让界面强制横屏，但是界面的能响应手势区域只有左半部分，我估计是承载插件的原生界面View在插件Orientation.lockToLandscape(); 后并未真正的改变宽高导致。麻烦看下

注：只有米家首页是竖屏进去才有这种情况，如果米家首页横屏，再进插件，则所有区域可点击。

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/7885251/51882126-d3731500-23b8-11e9-9488-524ff6416e3d.png">

#### 期望

插件横屏后全屏幕可响应手势。

**Comment by blockdate** [comment]
更新ipa至目前最新版86尝试是否解决问题

**Comment by JxXiaoXie** [comment]
点击是可以点了，但是我从横屏的插件界面返回米家界面，不会自动竖屏回去，而是如下图这样，设备列表也看不到。

![image](https://user-images.githubusercontent.com/7885251/52680020-fa614780-2f71-11e9-8154-303d8aedd71a.png)

**Comment by blockdate** [comment]
这个建议退出时自行处理下，之后我们会在插件退出时恢复处理横屏问题
