### ISSUE TITLE
打包上传后navigation 导航头的两侧的图片无法出现

### ISSUE THREAD

**Issue by hunter858** [MiEcosystem/miot-plugin-sdk#262]
before issue：（不用回答）
#### 现象
打包上传的包，在线上是没有左右按钮的，功能是ok的，可以返回和跳转到设置页面，
但是本地调试的时候 ，navigation 是一切正常的，这个大概是什么问题？能否解答一下

#### 其他的上下文/日志/截图

![1691548754395_ pic](https://user-images.githubusercontent.com/16034056/51898608-3cc04b80-23ec-11e9-8778-6ba144ab982c.jpg)

**Comment by blockdate** [comment]
这个是SDK资源路径的问题，现在更新IPA即可解决
