### ISSUE TITLE
扩展程序要在新平台发布时,打包上传后出现打包失败,要如何处理

### ISSUE THREAD

**Issue by nealelin** [MiEcosystem/miot-plugin-sdk#263]
before issue：（不用回答）
### 是否尝试搜索issue？YES

---

#### 环境
- 电脑操作系统:[eg.Windows10
- 手机系统:[eg.Android 8.1 & iOS 12.1.1
- 相关模块:

#### 现象

产生publish.mpkg,并按新版扩展程序管理台,上传档案后,出现”打包中”讯息很久没反应,按重新整理后出现”打包失败”,如下图,应该如何处理呢
![image](https://user-images.githubusercontent.com/44886762/51955038-55c50d00-247d-11e9-8d3a-9cd9e7973f70.png)

#### 期望

发布后可进行“白名单测试”

**Comment by flingInTheSky** [comment]
我的也是zhey

**Comment by flingInTheSky** [comment]
按照上面的方式处理后，有个设备OK了。但是另外一款设备出了问题：
1、上传包时提示服务器错误，然后关掉上传窗口，发现已经有了一条打包中的记录，但是等了很久很久，还是显示打包中，还删除不了。
2、新增支持产品模块，选择产品时，有些产品名称比较长，看不到model，容易选错，似乎还删除不了。

**Comment by flingInTheSky** [comment]
uid:1085269910,
detailid:不太清楚这个指什么
包名：com.viomi.hotKettle

**Comment by UnaMattinaDev** [comment]
> 因为目前错误信息显示还未上线，如果出现打包失败问题，先尝试以下操作
> 
> 1. 未添加新的三方库的，删除本地node_module，重新npm install后打包上传。
>    2.添加新的三方库的，修改com.xx.xx的工程目录里的package.json，不要修改根目录的package.json，然后打包上传尝试
> 
> 如果以上方法任然失败，提供uid以及插件连接的detail/xxx 的detailid，我们再来查询问题。

添加新三方库，需要在com.xx.xx目录下npm install 生成 node_modules 目录，然后再打包上传吗

**Comment by flingInTheSky** [comment]
@blockdate 
uid:1085269910,
detailid:不太清楚这个指什么
包名：com.viomi.hotKettle

这个过了一天，昨天上传的几个包还显示“打包中”（那几个包应该是有问题），今早我做了调整，上传后直接显示失败，不知道什么原因。

项目情况：根目录的package.json没有修改，在com.viomi.hotKettle项目里的package.json，加了一个第三方库，调试没有问题。根目录和项目目录里的node_module，都删掉过并重新 npm install。

不知道什么时候可以把错误信息显示上线，要不然挺麻烦的。

**Comment by chenhaoge** [comment]
一直显示打包失败，也不知道原因，有人打包成功的吗

**Comment by flingInTheSky** [comment]
@chenhaoge 我创建了一个demo，并打包，是成功的。但是到了实际项目，就不行，区别在：1、代码结构不一样；2、项目里安装了第三方库。

失败，也不知道什么原因。

**Comment by flingInTheSky** [comment]
应该是跟代码结构有关，就是不知道具体是哪一点。因为他们是在云端打包的，所以本地可以，打包不一定可以。

**Comment by flingInTheSky** [comment]
@blockdate 打包失败问题，什么时候可以把错误信息显示出来呢？现在一直卡在打包这一个步骤了。

**Comment by sikaiven** [comment]
同样的问题，删除本地node_module后，重新打包也不行，这个需要怎么解决？ @blockdate

**Comment by blockdate** [comment]
统一回复，打包失败问题在打包失败界面，将鼠标移动到失败旁边的感叹号上可以查看错误
