### ISSUE TITLE
测试显示“13603”

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#264]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.1]
- 相关模块:[eg.Host/Service/Account]

#### 现象

对已经提交的版本进行白名单测试的时候，点击设备显示  “Requiring unknown module '13603'”,本地测试时没有这个问题；

#### 期望

恢复正常。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
之前打包服务不太稳定，可以尝试重新提交打包。

如果自己添加了一些三方库，确认三方库已正常安装到项目目录下并打包。
