### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by laughmaker** [MiEcosystem/miot-plugin-sdk#266]
您好，想咨询一下，插件是否支持开启eslint呢？如何开启？
感谢！

**Comment by blockdate** [comment]
目前没有内置ESLint，需要自行配置。
之后我们可能会内置ESLint配置

**Comment by laohuang88** [comment]
建议根据你的IDE使用相关插件, 比如vscode就有很好的这类插件可用. 如 https://www.jianshu.com/p/76d0aac20715

**Comment by laughmaker** [comment]
> 建议根据你的IDE使用相关插件, 比如vscode就有很好的这类插件可用. 如 https://www.jianshu.com/p/76d0aac20715

好的，谢谢。
