### ISSUE TITLE
whitetitlebar适配

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#267]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] ios 12
- 相关模块:[eg.Host/Service/Account] ui

#### 现象
使用了whitetitlebar 但是在iphonex啥并不兼容, 这个问题是偶然性的有时会发生有时不会

#### 期望
能够正常适配

#### 其他的上下文/日志/截图
以下上iphonex 截图
![image](https://user-images.githubusercontent.com/17062182/51972236-eae3f800-24b5-11e9-878d-29b240d829cf.png)

#### 尝试过的解决办法

尝试过哪些操作？
看了上面的issue, 感觉问题并没有解决, 回答里的title的变更日志现在无法查看

**Comment by Mmpc1994** [comment]
正常的情况
![image](https://user-images.githubusercontent.com/17062182/51973584-ec62ef80-24b8-11e9-96cd-530be58191ee.png)
不正常的情况
![image](https://user-images.githubusercontent.com/17062182/51973605-f684ee00-24b8-11e9-8670-222b2dbb0df6.png)
有一个多出来的paddingbottom 不知道是哪里来的

**Comment by blockdate** [comment]
本地未能复现该问题，whitetitlebar 以统一为TitleBar，建议更换之后使用。

如果任然出现问题，在下方回复
