### ISSUE TITLE
BlackTitleBar或WhiteTitleBar在各种手机上的位置起点不一样

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#268]
#### 环境
- 电脑操作系统: Mac OS/Linux
- 手机系统: Android & IOS
- 相关模块: BlackTitleBar 、WhiteTitleBar

#### 现象
在各种手机上titleBar的位置不一样

#### 期望
检查大部分型号的手机，看布局起点是在左顶点还是statusBar下方的左顶点，然后做统一处理 。

#### 其他的上下文/日志/截图
![titlebar](https://user-images.githubusercontent.com/44045029/52026280-3217ca80-2542-11e9-8bb4-218bd4511e6a.png)

**Comment by lvjie0519** [comment]
已修复，请更新下sdk试试。

**Comment by Banjiemin** [comment]
你好，我已经简单验证了一下，android上目前是可以的，

但IOS上，这个函数不支持---- StatusBar.setTranslucent(true)

请继续解决，谢谢了 ！

**Comment by lvjie0519** [comment]
已修复，请更新sdk。

**Comment by Banjiemin** [comment]
if(Platform.OS == 'android'){
	        StatusBar.setTranslucent(true);
	    }

兄弟，你这个只是加了个判断而已，没有解决在IOS上的问题啊 ！
