### ISSUE TITLE
时间组件Picker在IOS上使用有问题

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#269]
- 电脑操作系统:Mac OS/Linux
- 手机系统: Android / iOS
- 相关模块: picker 

#### 现象
时间组件Picker在Android上使用还算正常，除了有点滑动不太顺畅；
在IOS上使用有问题，间隔线没了 。

#### 期望
更新Picker组件或用其他组件替代。

#### 其他的上下文/日志/截图
![picker](https://user-images.githubusercontent.com/44045029/52026450-dbf75700-2542-11e9-8ee5-650d44a9aa13.png)

**Comment by blockdate** [comment]
可以参考demo中 UI能力->UIKitHome-> Pickers的实现，源文件为PickerScreen.js。

**Comment by kfjihailong** [comment]
这个流畅度，咱们测试过吗？我在android上测试了卡的不敢直视。RXPicker一样卡的不敢直视。

**Comment by blockdate** [comment]
本地调试的卡顿是可以理解的，如果打包上传之后使用任然有问题可以再次反馈
