### ISSUE TITLE
新年好，通过插件A连接设备B，可以连接但是没有发现服务的问题依然存在。

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#270]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] MAC
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS
- 相关模块:[eg.Host/Service/Account] Bluetooth

#### 现象

SDK和App都是最新的，在固件升级的场景中，即插件A连接设备B。看log设备B是连接成功了但是后续没有服务，这个问题之前有issue跟进，但是目前仍然不行，麻烦关注下 #140 #85 

#### 期望

可以发现服务

**Comment by blockdate** [comment]
1. B设备是普通蓝牙设备吗。
2.更新下ipa至目前最新版85，我们增加了一些日志输出方便排查问题，如果可以将对应日志提供一下。
3.如果可以，描述下该问题的操作过程，以便于我们这边进行复现。

**Comment by zaxayn** [comment]
1.B设备属于普通蓝牙
2.已更新

**Comment by zaxayn** [comment]
1.B属于普通蓝牙
2.更新后打印日志如下
`
centralManager didDisconnectPeripheral:582A2A34-0572-984D-F6A1-08D80EFCB8ED error:Error Domain=CBErrorDomain Code=6 "The connection has timed out unexpectedly." UserInfo={NSLocalizedDescription=The connection has timed out unexpectedly.}
blob:http://192.168.…-7b329285b236:53906 Error Domain=CBErrorDomain Code=6 "The connection has timed out unexpectedly." UserInfo={NSLocalizedDescription=The connection has timed out unexpectedly.}
console.warn @ blob:http://192.168.…-7b329285b236:53906
logToConsole @ blob:http://192.168.…-7b329285b236:24565
logIfNoNativeHook @ blob:http://192.168.…-7b329285b236:24548
__callFunction @ blob:http://192.168.…4-7b329285b236:7863
(anonymous) @ blob:http://192.168.…4-7b329285b236:7633
__guardSafe @ blob:http://192.168.…4-7b329285b236:7825
callFunctionReturnFlushedQueue @ blob:http://192.168.…4-7b329285b236:7632
(anonymous) @ debuggerWorker.js:72
blob:http://192.168.…-7b329285b236:24565 centralManager didDisconnectPeripheral:582A2A34-0572-984D-F6A1-08D80EFCB8ED error:Error Domain=CBErrorDomain Code=6 "The connection has timed out unexpectedly." UserInfo={NSLocalizedDescription=The connection has timed out unexpectedly.}
blob:http://192.168.…-7b329285b236:53906 Error Domain=CBErrorDomain Code=6 "The connection has timed out unexpectedly." UserInfo={NSLocalizedDescription=The connection has timed out unexpectedly.}
console.warn @ blob:http://192.168.…-7b329285b236:53906
logToConsole @ blob:http://192.168.…-7b329285b236:24565
logIfNoNativeHook @ blob:http://192.168.…-7b329285b236:24548
__callFunction @ blob:http://192.168.…4-7b329285b236:7863
(anonymous) @ blob:http://192.168.…4-7b329285b236:7633
__guardSafe @ blob:http://192.168.…4-7b329285b236:7825
callFunctionReturnFlushedQueue @ blob:http://192.168.…4-7b329285b236:7632
(anonymous) @ debuggerWorker.js:72
blob:http://192.168.…-7b329285b236:64348 Bluetooth bluetoothConnectionStatusChanged 70:58:96:00:01:54
blob:http://192.168.…7b329285b236:108271 bluetoothConnectionStatusChanged false
blob:http://192.168.…7b329285b236:108271 =========DUF start========
blob:http://192.168.…-7b329285b236:64368 Bluetooth bluetoothDeviceDiscovered {uuid: "6E842425-9714-E999-6C20-C90A1CAE00A2", RSSI: -56, peripheral: {…}, mac: "6E842425-9714-E999-6C20-C90A1CAE00A2", advertisementData: {…}}
blob:http://192.168.…7b329285b236:108271 bluetoothDeviceDiscovered {uuid: "6E842425-9714-E999-6C20-C90A1CAE00A2", RSSI: -56, peripheral: {…}, mac: "6E842425-9714-E999-6C20-C90A1CAE00A2", advertisementData: {…}}
blob:http://192.168.…7b329285b236:108271 bluetoothDeviceDiscovered:  {uuid: "6E842425-9714-E999-6C20-C90A1CAE00A2", RSSI: -56, peripheral: {…}, mac: "6E842425-9714-E999-6C20-C90A1CAE00A2", advertisementData: {…}}
2blob:http://192.168.…-7b329285b236:24565 centralManager didConnectPeripheral:6E842425-9714-E999-6C20-C90A1CAE00A2
blob:http://192.168.…-7b329285b236:64348 Bluetooth bluetoothConnectionStatusChanged 6E842425-9714-E999-6C20-C90A1CAE00A2
blob:http://192.168.…-7b329285b236:64396 Bluetooth bluetoothSeviceDiscovered 6E842425-9714-E999-6C20-C90A1CAE00A2
blob:http://192.168.…7b329285b236:108271 connect success  {services: Array(0)}
blob:http://192.168.…-7b329285b236:24565 start discoverServices :(
	FE59
)
 with peripheral:6E842425-9714-E999-6C20-C90A1CAE00A2
blob:http://192.168.…-7b329285b236:24565 peripheral:6E842425-9714-E999-6C20-C90A1CAE00A2 didDiscoverServices:(null)
blob:http://192.168.…-7b329285b236:64396 Bluetooth bluetoothSeviceDiscovered 6E842425-9714-E999-6C20-C90A1CAE00A2
`
3.大概流程是设备A进入DFU模式变成普通蓝牙设备B,此时设备A断开，扫描到设备B然后连接

**Comment by zaxayn** [comment]
1.是普通蓝牙设备
2.更新后日志如下
![wechatimg253](https://user-images.githubusercontent.com/11364809/52608988-a9404d80-2eb6-11e9-988a-20450643fc9f.png)
3.大致流程：进入固件升级模式，小米蓝牙设备A变成普通蓝牙设备B，开始扫描，在发现设备的监听里，连接设备，然后在发现服务的监听里没有收到监听。
`Bluetooth.startScan(10000, 'FE59');`
`        // 连接
        let find = false;
        this._didDiscoverPeripheralListener = BluetoothEvent.bluetoothDeviceDiscovered.addListener((blu) => {
            L.d('bluetoothDeviceDiscovered: ',blu);
            if (blu && !find){
                find = true;
                Device.getBluetoothLE().connect(3,{peripheralID:blu.uuid, timeout:12000}).then((data) => {
                    L.d("connect success ", data);
                    Device.getBluetoothLE().startDiscoverServices('FE59');
                }).catch((err) => {
                    L.d("connect error ", err);
                });
            }
        });`

**Comment by blockdate** [comment]
从日志看，原生发送了service的发现通知，但是因为外设的id变化，导致通知被内部拦截了。
如果需要使用普通蓝牙设备或者外设id变化了的设备，需要自行创建一个新的蓝牙对象，否则该设备的一些蓝牙通知会被sdk认为是不相关的信息而屏蔽掉。

解决方法为使用 Bluetooth.createBluetoothLE(macOrPeripheralID)，获得该对象之后进行后续蓝牙操作。

如果以上方法尝试无效，请及时提问，最好也附带上日志。

**Comment by zaxayn** [comment]
好的，我马上试试

**Comment by colayet** [comment]
> 好的，我马上试试

您好，我也正在做米家插件蓝牙DFU功能，能请教几个问题吗？ 设备进入DFU模式后，mac加1，用米家的Bluetooth.createBluetoothLE(PeripheralID)需要pid值， 请问ios端是如何获取pid的， 因为Bluetooth.startScan方法返回数据中没有工厂数据（manufacturer data），无法通过mac确认PeripheralID具体是哪个 @zaxayn  方便留个联系方式吗

**Comment by zaxayn** [comment]
> > 好的，我马上试试
> 
> 您好，我也正在做米家插件蓝牙DFU功能，能请教几个问题吗？ 设备进入DFU模式后，mac加1，用米家的Bluetooth.createBluetoothLE(PeripheralID)需要pid值， 请问ios端是如何获取pid的， 因为Bluetooth.startScan方法返回数据中没有工厂数据（manufacturer data），无法通过mac确认PeripheralID具体是哪个 @zaxayn 方便留个联系方式吗

正如上面我的截图，通过bluetoothDeviceDiscovered监听可以获取
![image](https://user-images.githubusercontent.com/11364809/52623149-8fb6fa00-2ee6-11e9-97ff-5be46e26215c.png)

**Comment by colayet** [comment]
> 正如上面我的截图，通过bluetoothDeviceDiscovered监听可以获取

通过你截图里面的代码来看，好像是在监听里面直接去connect了第一台扫描到的设备吧,如果有多台设备进入dfu模式，或者说如果有多个设备具有FE59这个服务， 那就有可能connect到其他设备去了。不知道我理解的对不对
下图这个是旧版本的ios确定连接哪台DFU设备，是需要有工厂数据去比对mac的：
<img width="623" alt="screen shot 2019-02-12 at 17 12 01" src="https://user-images.githubusercontent.com/8639365/52624580-00134a80-2eea-11e9-8634-1b873ea2ed9e.png">

**Comment by colayet** [comment]
@zaxayn 搞定 感谢！
