### ISSUE TITLE
锯齿问题

### ISSUE THREAD

**Issue by Braveleon** [MiEcosystem/miot-plugin-sdk#271]
安卓手机画圆形边框的时候，边框会有很明显的锯齿问题

**Comment by lvjie0519** [comment]
请粘贴下您的关键代码和截图看看，我这边对比下。

**Comment by Braveleon** [comment]
![image](https://user-images.githubusercontent.com/18184778/52608103-c9bad880-2eb3-11e9-8315-3a373812d140.png)

**Comment by Braveleon** [comment]
半圆的这种圆角，锯齿很明显，如果是一个圆圈的话锯齿就更明显了

**Comment by lvjie0519** [comment]
这个应该不是我们这边控制的啊，是否与手机分辨率有关？  您尝试运行com.xiaomi.demo，点击 UI能力-->UIKitHome-->Buttons  看看对应的Button是否有锯齿，请参考这里面的Button使用方式，具体代码在ButtonScreen.js中。

**Comment by Braveleon** [comment]
你用的是react-native-ui-kitten这个第三方封装好的button，我是直接用的react-native内置的TouchableOpacity组件然后自定义的样式，要不你直接自己用TouchableOpacity定义一个可点击的圆圈在安卓手机上看下，这个我查了和react-native版本有关

**Comment by Braveleon** [comment]
<TouchableOpacity activeOpacity={1} style={{ width: 44, height: 24, backgroundColor: '#EEEEEE' , borderRadius: 12, borderStyle: "solid", borderWidth: 1 / PixelRatio.get(), borderColor:  'rgba(0,0,0,0.15)' }} onPress={() => {
 }}>
 </TouchableOpacity>

**Comment by lvjie0519** [comment]
![_20190212161103](https://user-images.githubusercontent.com/22487747/52620886-d3a70080-2ee0-11e9-85f5-088e66abd8cf.png)

**Comment by lvjie0519** [comment]
我这边看起来正常，不知道您那边视觉效果怎样，建议您换个高分辨率手机再试试？

**Comment by Braveleon** [comment]
你看不出你的那个圆圈边框有问题?线都不是光滑的了，

**Comment by lvjie0519** [comment]
您有尝试过其他RN版本吗？

**Comment by Braveleon** [comment]
https://github.com/facebook/react-native/issues/17267

**Comment by lvjie0519** [comment]
> facebook/react-native#17267

测试，发现确实存在一定的问题，RN 49版本视觉效果要比54及以上版本都好，54及以上版本效果都存在问题，目前我们这边一时不会更新RN版本更不会往低版本走，建议您看是否能够通过其他方案实现圆角等，我们这边是否提供native的按钮供RN使用需要另行沟通，有沟通结果，我会及时通知，谢谢您的提问。

**Comment by aizuzi** [comment]
![device-2019-04-25-152708](https://user-images.githubusercontent.com/3455979/56720428-654eac00-6775-11e9-8710-9152f9959a26.png)
在Android手机上出现了很明显的锯齿问题，而RN官方已经在0.57版本Fix了这个问题[https://github.com/facebook/react-native/issues/21085](facebook/react-native#21085) 请问这个问题什么时候能解决呢？ @lvjie0519

**Comment by lvjie0519** [comment]
@aizuzi   ok，我看下官方的解决方案，最近一个星期进行修复，请耐心等待，修复了及时回复，谢谢。

**Comment by zanetti4** [comment]
Duplicate of #990

**Comment by fishle** [comment]
试试这个包，看看没有好一点：
https://pan.mioffice.cn:443/#/link/235346B5E14A4F41577F29FFB08AC348
