### ISSUE TITLE
请问安卓端，有没有粒子系统支持？

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#272]
如iOS可以用GPHParticleView，请问安卓上有没有原生粒子系统支持开放

**Comment by lvjie0519** [comment]
IOS已经取消对GPHParticleView的支持了，我们提供了gl-react-native这个库，看是否满足您粒子系统的开发。

**Comment by edwardair** [comment]
gl-react-native 那就是得自己绘制粒子了，iOS上可以实现，但是跑到安卓上，效率太差，基本卡死无法使用，就想问下有没有什么现成优化好的粒子系统，主要安卓上得不卡

**Comment by lvjie0519** [comment]
目前没有提供现成的粒子系统实现，您可以看看 react-native-particles 这个开源库。
