### ISSUE TITLE
请问IOS最新的米家beta版本为什么没有dev了，这么调试啊？

### ISSUE THREAD

**Issue by hc520messi** [MiEcosystem/miot-plugin-sdk#273]
请问IOS最新的米家beta版本为什么没有dev了，这么调试啊？

**Comment by blockdate** [comment]
dev是跟登录账号有关的，请检查你登录的账号是否是白名单账号，有必要同时检查是否设置了旧插件框架需要的秘钥MD5值。

我使用最新的beta版检验过，可以成功看到dev设置

**Comment by hc520messi** [comment]
> 
> 
> dev是跟登录账号有关的，请检查你登录的账号是否是白名单账号，有必要同时检查是否设置了旧插件框架需要的秘钥MD5值。
> 
> 我使用最新的beta版检验过，可以成功看到dev设置

- 我自己create的项目可以，但是跑那个示例的demo就没有dev，这个可咋办

**Comment by hc520messi** [comment]
> 
> 
> dev是跟登录账号有关的，请检查你登录的账号是否是白名单账号，有必要同时检查是否设置了旧插件框架需要的秘钥MD5值。
> 
> 我使用最新的beta版检验过，可以成功看到dev设置




![img_0640](https://user-images.githubusercontent.com/47098962/52693210-0adce680-2fa1-11e9-8b35-b36f6935655b.PNG)

![img_0641](https://user-images.githubusercontent.com/47098962/52693235-1a5c2f80-2fa1-11e9-910a-bab697d2d6d0.PNG)

**Comment by zhuxinleibandou** [comment]
米家beta app（icon上显示76）,配上年前最后一次更新的sdk，账号登录后是有模拟设备的

今天更新的sdk后，用老版本(76)的app，就无法显示虚拟设备了，麻烦看一下，谢谢～

ps:使用最新的beta版本的app，不能显示dev，也没有虚拟设备

![7c54a247-f75b-4b6d-a537-453f92d7c4e2](https://user-images.githubusercontent.com/18374383/52695743-4202c600-2fa8-11e9-92c5-3c06381a0379.png)

**Comment by blockdate** [comment]
dev 模式跟插件包名、测试服务器IP、插件SDK，没有任何关系，仅跟开发者账号是否具有dev权限以及设置的调试插件model是否合规有关。

经本地测试之后确认当前最新版本(89)的app可以设置并正常显示dev虚拟设备。如不行可以尝试多次刷新，重启app或者重新登录等操作
![img_0041](https://user-images.githubusercontent.com/4339364/52700324-b8a4c100-2fb2-11e9-8273-c01a4c330c55.PNG)
![img_0040](https://user-images.githubusercontent.com/4339364/52700351-bb9fb180-2fb2-11e9-8507-022db7bc5397.PNG)

**Comment by blockdate** [comment]
验证无问题
