### ISSUE TITLE
你好 关于新版插件的问题

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#275]
你好 新插件现在提供第三方接入了吗，为什么小米IoT开发者平台没有添加的地方。
还有readme里面的 
git clone git@github.com:MiEcosystem/miot-plugin-sdk.gitpkg
也不能下载

**Comment by RengeRenge** [comment]
<img width="1220" alt="wechatimg20" src="https://user-images.githubusercontent.com/14158970/52758321-c6a22280-3042-11e9-990b-d242749da41c.png">

**Comment by blockdate** [comment]
这是表示你的账号没有相关的管理权限，有权限的账号在应用栏操作即可。如下图

<img width="1630" alt="wx20190214-103411 2x" src="https://user-images.githubusercontent.com/4339364/52758714-47155300-3044-11e9-9cf9-4694a0be9a05.png">

**Comment by lvjie0519** [comment]
readme 有误，马上修改， git拉取代码如下
git clone git@github.com:MiEcosystem/miot-plugin-sdk.git

**Comment by RengeRenge** [comment]
> readme 有误，马上修改， git拉取代码如下
> git clone [git@github.com](mailto:git@github.com):MiEcosystem/miot-plugin-sdk.git

你好，新sdk下载好启动了。但是米家App似乎调试不了，路径和旧插件不一样了，看到现在的包是放在projects下的

请问插件包名需要填什么


调试设备：iPhone
测试环境：AppStore版本的米家、新创建的米家新版插件

![img_6004](https://user-images.githubusercontent.com/14158970/52773612-61682480-3076-11e9-9e62-454f95bfa836.PNG)
![img_6005](https://user-images.githubusercontent.com/14158970/52773616-64631500-3076-11e9-9804-bef7f24fb337.PNG)

**Comment by blockdate** [comment]
请使用github首页readme中提供的测试已下载连接进行新框架的测试。目前新插件框架还未上线到appstore。

**Comment by blockdate** [comment]
问题为app未使用测试版本
