### ISSUE TITLE
新版RN工程Demo 运行报错 缺少index.android.js

### ISSUE THREAD

**Issue by unmagic** [MiEcosystem/miot-plugin-sdk#277]
使用该项目，执行npm start 运行com.xiaomi.demo，报错

![691550110964_ pic](https://user-images.githubusercontent.com/11581627/52758978-403b1000-3045-11e9-8d27-610104a33306.jpg)

**Comment by lvjie0519** [comment]
检查下您react-native 版本是否为0.54.4， 高版本入口是index.js

**Comment by unmagic** [comment]
这个在哪里修改啊

**Comment by lvjie0519** [comment]
> 我的是0.54.4，入口这个在哪里修改啊
我的意思是现在高版本的RN，已经没有index.android.js了。

使用该项目，执行npm start 运行com.xiaomi.demo
1、您是在哪个目录下执行npm start 的？
2、运行com.xiaomi.demo， 您是怎么运行的？

需要使用我们提供的apk安装到手机或模拟器上，具体参见调试文档。

**Comment by unmagic** [comment]
我现在的问题是说没有index.android.js，程序的运行都是按照调试文档上一步一步做的。现在是不知道该如何解决没有index.android.js的问题
