### ISSUE TITLE
插件打包问题求解

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#278]
我们插件，引用了几个第三方插件，会在自己插件路径下，使用 `yarn install`命令安装三方依赖，这样子，系统会在插件路径下新增  `node_modules` 文件夹，并且会多出很多系统本身的依赖库，导致插件打包的`publish.mpkg` 很大，请问这种情况怎么打包？

**Comment by lvjie0519** [comment]
引用的几个第三方插件中package.json文件的dependencies中是否依赖了系统本身的依赖库？尝试去掉多余的试试？

**Comment by edwardair** [comment]
哦 原来是谷歌DevTools的锅，依赖了很多系统库，删了就好了
