### ISSUE TITLE
Host.ui.openShopPage在IOS上无效

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#279]
#### 环境
* 电脑操作系统: Mac OS/Linux
* 手机系统: Android & IOS
* 相关模块: Host.ui.openShopPage("102277");

#### 现象
android能调用小米商城接口，但IOS不行，听说商城SDK屏蔽了IOS什么的.....

#### 期望
请调试IOS上Host.ui.openShopPage

**Comment by blockdate** [comment]
为了编译以及调试方便，iOS端的商城SDK并未集成，因此无法使用是正常现象，该接口线上会功能正常，无须担心

**Comment by Banjiemin** [comment]
OK， 谢谢 ！
