### ISSUE TITLE
iphone XR/XS/XS MAX等机型适配问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#28]
用iPhoneX跑了下提供的demo，发现iPhoneX的适配有些问题，状态栏显示一条黑色。查看了TitleBarBlack、TitleBarWhite的适配方式，似乎就是这个效果。
目前是不是还需要判断iPhoneX机型做另外的适配？
![wechatimg434](https://user-images.githubusercontent.com/22782965/48387972-c6884300-e732-11e8-8cad-b413573c81e3.png)

**Comment by flingInTheSky** [comment]
查看TitleBarBlack的代码，发现使用了react-navigation的SafeAreaView，而react-navigation的SafeAreaView，实际上是使用了react-native-safe-area-view，查看对应的版本，使用的是react-native-safe-area-view@0.8.0,并不是最新版本，而它的版本，似乎是随着react-navigation的，只适配了iPhoneX，没有适配iphone XR/XS/AX等机型。

这个问题应该怎么处理呢？更新react-navigation？

**Comment by LiuMengzhou** [comment]
@flingInTheSky 感谢你阅读源码并给出很好的建议，我们会酌情采纳。对于iPhone 新机型的导航适配，我们已列入优化计划，敬请期待。

**Comment by UnaMattinaDev** [comment]
在iPhone X 上也遇到了这个问题，请问什么时候能解决？

**Comment by LiuMengzhou** [comment]
@flingInTheSky @UnaMattinaDev 
check [导航栏更新日志](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/beta%20%E7%89%88%E6%9C%AC%E6%8E%A5%E5%8F%A3%E5%8F%98%E8%BF%81%E6%97%A5%E5%BF%97.md#2018-12-19)
