### ISSUE TITLE
请问如何获取正确的屏幕尺寸？

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#281]
请问SDK是否有什么接口能获取到最终用户显示的屏幕尺寸；

原因：比如我用MIX2测试，手机开的是全面屏模式，通过`var screenHeight = Dimensions.get('window').height`获取到高度其实缺少了底部一条虚拟菜单的高度，如果通过动态计算父视图的高度，再刷新页面的话，第一次进来，用户能明显看到界面跳顿一下

**Comment by lvjie0519** [comment]
目前没有提供接口
希望能提供个gif图看下具体效果？

**Comment by edwardair** [comment]
![demo](https://user-images.githubusercontent.com/2043635/52829336-54474600-3107-11e9-9fa7-5862be568824.gif)
@lvjie0519

**Comment by lvjie0519** [comment]
@edwardair

**Comment by edwardair** [comment]
这种方式在全面屏模式下，获取的高度，缺了一截的，得等组件layout后，才能重新拿到真正的高度

**Comment by lvjie0519** [comment]
> @lvjie0519
> 这种方式在全面屏模式下，获取的高度，缺了一截的，得等组件layout后，才能重新拿到真正的高度

麻烦加我微信，18750118631，咱们微信讨论下。
