### ISSUE TITLE
插件打包生产环境测试情况疑问

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#282]
before issue：（不用回答）
### SDK 最新

---

#### 环境
- 电脑操作系统: Mac OS

#### 现象

**_Android_**
1、正常进入插件，然后退出插件，再次进入，这时候感觉插件并没有重新初始化，因为我的ScrollView退出时，滑动到哪里，重新进来仍旧显示在哪里；这个导致的问题是，我蓝牙并没有连接

**_iOS_**
1、进入插件一会，APP就闪退，而使用测试环境并不会闪退，能够正常运行，（插件进入后，会下载固件文件）
闪退日志显示：
```
2   libsystem_c.dylib             	0x00000001983806d8 _gettemp + 520
3   libsystem_c.dylib             	0x00000001983c60c4 mkstemps + 32
4   CFNetwork                     	0x000000018271b2c0 -[__NSCFLocalDownloadFile initTempFileWithDirectory:] + 216
5   CFNetwork                     	0x000000018266aa6c -[__NSCFLocalDownloadTask setupForNewDownload:] + 232
6   CFNetwork                     	0x000000018266ab94 -[__NSCFLocalDownloadTask initWithSession:request:filePath:ident:] + 112
7   CFNetwork                     	0x00000001826543e4 -[__NSURLSessionLocal downloadTaskForRequest:downloadFilePath:resumeData:completion:] + 276
8   MiHome                        	0x0000000101208b4c 0x100054000 + 18565964
9   MiHome                        	0x000000010120805c 0x100054000 + 18563164
```

**Comment by blockdate** [comment]
如果可以，将设备分享给小米账号894158105，我这边在正式环境下尝试复现问题

**Comment by blockdate** [comment]
同时可以的话将crashlog 发送到邮箱 wulei7@xiaomi.com

**Comment by edwardair** [comment]
iOS上大概知道原因了，我的账户是有测试权限的，但是进入 插件，显示的仍旧是旧版的RN插件，闪退问题，把网络关掉就不会闪了，应该是新旧RN插件的兼容问题，现在问题是，为什么新版本的插件没生效？
![default](https://user-images.githubusercontent.com/2043635/52827574-5063f580-3100-11e9-9f85-d45f8f876ef8.png)

**Comment by edwardair** [comment]
测试了另外一个插件，首次添加设备50%就闪退掉了（iOS平台），前几天刚上班时测试过旧版本，是可以测试的（我这边的差异是：原本三方依赖我是修改的根目录的package.json，后来才看到说明里面，得在各自插件路径下依赖三方库，然后测试环境测试没问题，打包到线上版本，2个插件都无法正常测试（iOS））

**Comment by edwardair** [comment]
android第一次进入没问题，退出插件，第二次进入，出现问题：
插件A：感觉插件未重新初始化，导致蓝牙未连接；
插件B：进入后一片空白，蓝牙也未连接上

**Comment by edwardair** [comment]
android，插件A，今天测试（apk未更新，插件未更新），第二次进入也是一片空白了

**Comment by dingshaoran** [comment]
刚修复了白屏的问题，请更新 https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/SmartHome_Dev_62839_5.4.52_sdk.apk

**Comment by edwardair** [comment]
MIX1  测试，白屏问题仍旧存在啊（第一次进入，没问题，退出插件到首页，然后再次进入就会白屏）

**Comment by blockdate** [comment]
对于crash问题，希望可以将设备共享给小米账号894158105。
同时在有mac电脑的情况下，连接手机到xcode，随后如下操作，将导出的crash日志以及使用的ipabuild编号通过邮件提供给我wulei7@xiaomi.com。以便于我解决问题。
<img width="692" alt="wx20190215-151805 2x" src="https://user-images.githubusercontent.com/4339364/52840693-f6315780-3134-11e9-86fb-cdcc1de6a516.png">

**Comment by edwardair** [comment]
@blockdate 
iOS的已分享，并发送邮件
现在测试安卓版本，添加设备也是无法添加，麻烦看看这是什么问题
![screenshot_2019-02-16-09-57-58-226_com xiaomi sma](https://user-images.githubusercontent.com/2043635/52892862-9b9a0900-31d1-11e9-8564-25bcc6520ef7.png)
