### ISSUE TITLE
M2-APP-RN移植，加密芯片的蓝牙设备，调用新框架方法出错

### ISSUE THREAD

**Issue by AMI-zz** [MiEcosystem/miot-plugin-sdk#283]
## Bug Report

**方法调用**
![image](https://user-images.githubusercontent.com/27339224/52772494-9161f880-3073-11e9-9fa3-6e170f950d75.png)

![image](https://user-images.githubusercontent.com/27339224/52770573-7476f680-306e-11e9-8b36-697c001e0665.png)

![image](https://user-images.githubusercontent.com/27339224/52770452-16e2aa00-306e-11e9-9f9a-38cfaadc7aca.png)

方法的调用过程如上图，

**期望表现**

麻烦看一下这个方法怎么会引用错误，API上的例子如下：
![image](https://user-images.githubusercontent.com/27339224/52772910-ab500b00-3074-11e9-9dac-98ef3688eb34.png)

**环境**
- app版本:M2-APP移植
- 相关模块和API: miot/Bluetooth.IBluetoothLock

**尝试过的解决办法**
把Bluetooth.createBluetoothLE()替换成Device.getBluetoothLE()
<!-- 请添加准确的label>

**Comment by blockdate** [comment]
1. Bluetooth.createBluetoothLE(...)是需要mac或者外设id的
2.尝试输出一下Device.getBluetoothLE或者Bluetooth.createBluetoothLE(...)的对象，查看是否正确创建了蓝牙对象，以便于我们排查问题。

**Comment by dingshaoran** [comment]
getBluetoothLE().securityLock.encryptMessage('aaa') 请把 securityLock 后面的括号去掉，这是一个属性不是方法
