### ISSUE TITLE
smarthome.js 存在语法错误

### ISSUE THREAD

**Issue by weimanleung** [MiEcosystem/miot-plugin-sdk#284]
在miot-plugin-sdk\miot-sdk\service\smarthome.js 第37-38行存在语法错误，查看修改记录，是由于删除方法时，删漏了。

/**
     * 上报gps信息 /location/set
     * @param {string} deviceID
     * @param {GPSInfo} gpsInfo
     * @returns {Promise<json>}
     *
     */
    reportGPSInfo(deviceID, gpsInfo){
         return Promise.resolve(null);
    },
         return Promise.resolve({});
    },

**Comment by lvjie0519** [comment]
已修复，谢谢提醒！
