### ISSUE TITLE
局域网问题

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#285]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1.4
- 相关模块:[eg.Host/Service/Account]

#### 现象
你好，在判断设备是否处在同一局域网内，我做了一下3种尝试：
iOS 12.1.4 系统、米家Beta 4.12.0 (Build 4.12.0.100) 最新版，sdk最新
1、Host.getWifiInfo() 获取手机的wifi信息 走了 catch 且err 为 undefined
2、Device.getDeviceWifi().localPing() 走了catch 且err 为 undefined
3、Device.location;//0未知 1本地 2远程    均返回2远程
Device.SSID 获取设备的连接信息是成功的。

请问怎么处理这种情况

**Comment by liduojun** [comment]
手机、电脑、设备是处在同一个局域网的

**Comment by liduojun** [comment]
安卓有同样的问题，但有一个不同：
1、Host.getWifiInfo() 获取手机的wifi信息 走了 catch 但err有信息
{"line":106404,"column":32,"sourceURL":"http://192.168.1.125:8081/projects/com.ksmb.treadmill/index.delta?platform=android&dev=true&minify=false"}

**Comment by blockdate** [comment]
一下为iOS端的情况解答 
1. 经过测试确认接口Host.getWifiInfo 可用。请确认app版本在91(图标上的数字)及以上
2.catch 目前表示localping 失败，该错误目前并未抛出给js，所以为undefine，这个我们会稍后调整jssdk，走resolve流程
3. 通常情况下的设备基本上都是location 为2

如果没有特殊需求rpc请求在iOS端基本上都是走的remote，如果有强制本地的需求，我们近期会开放callLocal的rpc方法。

**Comment by liduojun** [comment]
你好，iOS端   1. 使用 Host.getWifiInfo 还是走了catch，但这次不报 undefine了，报了一个空
checkNetwork_failed,err: {}

**Comment by liduojun** [comment]
请给跟进一下吧，我们是走步机，出于安全不能远程操控设备，就这一个问题就可以提测了，万分感谢~·

**Comment by blockdate** [comment]
这个目前正在推进中，预计使用方法为 `Device.getDeviceWifi().callMethodFromLocal('method', [args])`

**Comment by L-Z-Q** [comment]
> 一下为iOS端的情况解答
> 
> 1. 经过测试确认接口Host.getWifiInfo 可用。请确认app版本在91(图标上的数字)及以上
>    2.catch 目前表示localping 失败，该错误目前并未抛出给js，所以为undefine，这个我们会稍后调整jssdk，走resolve流程
> 2. 通常情况下的设备基本上都是location 为2
> 
> 如果没有特殊需求rpc请求在iOS端基本上都是走的remote，如果有强制本地的需求，我们近期会开放callLocal的rpc方法。

用最新的105版本测试，Host.getWifiInfo 接口还是不可用，请再确认下。 @blockdate
