### ISSUE TITLE
新版打包上传后，无法进入插件页

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#286]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

开发环境可以正常进入。
新版打包上传后，无法进入插件页
Android 表现为白屏
iOS 现象为：
![wechatimg23](https://user-images.githubusercontent.com/12531667/52832432-78108900-3113-11e9-8a69-20502cb0aa99.jpeg)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

### 不要贴大段代码❗️

**Comment by edwardair** [comment]
我也是，安卓第一次能进入，第二次白屏
iOS，用iOS12测试，没问题，用iOS9测试，会闪退（另外找了个iPhone4s 9.3.5测试，米家APP都开不了，打开，卡一会，闪退）
@blockdate @lvjie0519

**Comment by liuhaixu666** [comment]
我也是这问题

**Comment by lvjie0519** [comment]
@edwardair  @liuhaixu666 
1、安卓第一次能进入，第二次白屏问题
请使用最新apk和sdk在试试

**Comment by blockdate** [comment]
对于上传之后下载插件报错无法进入的，提供下上传选择的sdklevel，同时如果可以将设备分享至894158105的小米账号下，协助我们排查问题。

**Comment by blockdate** [comment]
对于crash问题，再有mac电脑的情况下，连接手机到xcode，随后如下操作，将导出的crash日志以及使用的ipabuild编号通过邮件提供给我wulei7@xiaomi.com。以便于我们解决问题。
<img width="692" alt="wx20190215-151805 2x" src="https://user-images.githubusercontent.com/4339364/52840693-f6315780-3134-11e9-86fb-cdcc1de6a516.png">

**Comment by ldezho** [comment]
> 对于上传之后下载插件报错无法进入的，提供下上传选择的sdklevel，同时如果可以将设备分享至894158105的小米账号下，协助我们排查问题。

已分享

**Comment by ldezho** [comment]
> 对于crash问题，再有mac电脑的情况下，连接手机到xcode，随后如下操作，将导出的crash日志以及使用的ipabuild编号通过邮件提供给我[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)。以便于我们解决问题。
> <img alt="wx20190215-151805 2x" width="692" src="https://user-images.githubusercontent.com/4339364/52840693-f6315780-3134-11e9-86fb-cdcc1de6a516.png">

@blockdate 提供的信息已发送至您的邮箱。

**Comment by blockdate** [comment]
对于 _reactnative.View.propTypes.style 这个错误，经过排查发现应该是项目中有控件使用了`View.propTypes.style`，这是个已知问题可能会导致release环境下的错误，解决方法为改用 `ViewPropTypes.style`解决。原问题issue可以参考：
https://github.com/facebook/react-native/issues/16542

如还有其他疑问请及时反馈。

**Comment by ldezho** [comment]
@blockdate 感谢支持，iOS 确实是这个地方的问题，已解决。android遇到了和 #282相同的问题，退出重进，并为初始化。第二次进入，还是上次退出时的状态

**Comment by lvjie0519** [comment]
> @blockdate 感谢支持，iOS 确实是这个地方的问题，已解决。android遇到了和 #282  相同的问题，退出重进，并为初始化。第二次进入，还是上次退出时的状态

第二次进入，还是上次退出时的状态
Android这边对RN的启动做了优化，退出插件实际并未退出，保存在内存中的，第二次进来仍然显示上次退出时的状态，这有什么问题吗？

**Comment by ldezho** [comment]
如果是特意这样做的就没什么问题。因为和之前不一样，没看到说优化了这个地方，所以产生了疑问。
