### ISSUE TITLE
新扩展程序打包失败，大佬看看啥问题

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#287]
{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":6485,"Complete":true,"Exit":1,"Error":null,"StartTs":1550212107188154998,"StopTs":1550212119452634702,"Runtime":12.264479719,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/temp_892cb5fc_96e8_4a6e_8377_262444711c3f","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/bin/buildBundle.js --android --target /tmp/1550212107188090659/release/android linqi.projector.td01lq","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile","","[MIOT]start to build android bundle for linqi.projector.td01lq","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/linqi.projector.td01lq","output /tmp/1550212107188090659/release/android","","Loading dependency graph, done.","","","error：","","error：Unable to resolve module `../../com.xiaomi.demo/Main/MHLocalizableString` from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/linqi.projector.td01lq/Main/BlePage.js`: The module `../../com.xiaomi.demo/Main/MHLocalizableString` could not be found from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/linqi.projector.td01lq/Main/BlePage.js`. Indeed, none of these files exist:",""," * `/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/com.xiaomi.demo/Main/MHLocalizableString(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`"," * `/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1550212099649964543/compile/projects/com.xiaomi.demo/Main/MHLocalizableString/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`","","error：",""],"Stderr":[]}

**Comment by blockdate** [comment]
你这个是不是引用错文件了 `Unable to resolve module `../../com.xiaomi.demo/Main/MHLocalizableString``

**Comment by blockdate** [comment]
调整正确引用文件应该就没问题了，不要引用自己项目以外的依赖文件
