### ISSUE TITLE
给蓝牙写数据的方法怎么调用，write

### ISSUE THREAD

**Issue by AMI-zz** [MiEcosystem/miot-plugin-sdk#288]
---

#### 环境
- 电脑操作系统:Windows
- 手机系统:IOS最新
- 相关模块:蓝牙写数据

#### 现象

API提示给的案例方法如下：
![1550221087](https://user-images.githubusercontent.com/27339224/52845912-3c8db300-3143-11e9-9fb8-a944451e4376.png)
![image](https://user-images.githubusercontent.com/27339224/52845949-55966400-3143-11e9-97c3-5476e078f597.png)

实际的代码调用如下：
![image](https://user-images.githubusercontent.com/27339224/52846039-8e363d80-3143-11e9-940c-79d57aa20fe7.png)
我把write后面的（）去掉报错的是then()错误
![image](https://user-images.githubusercontent.com/27339224/52846209-069cfe80-3144-11e9-80eb-5e6f1195bd72.png)

![image](https://user-images.githubusercontent.com/27339224/52846180-ec632080-3143-11e9-82b8-b1856cdc97f6.png)

#### 期望

麻烦看下怎么给蓝牙写数据

**Comment by blockdate** [comment]
😓write带上一个参数吧，可能示例代码没有表达出来这个意思。。。

**Comment by AMI-zz** [comment]
带什么参数呢

**Comment by blockdate** [comment]
参数是你要写给蓝牙设备的二进制数据的十六进制字符串(HexString)

**Comment by AMI-zz** [comment]
刚试了一下，
![image](https://user-images.githubusercontent.com/27339224/52847947-8a58ea00-3148-11e9-9449-651df176ba21.png)
带参数不行

**Comment by blockdate** [comment]
提供下详细信息的日志和错误信息吧

**Comment by AMI-zz** [comment]
![image](https://user-images.githubusercontent.com/27339224/52848377-837ea700-3149-11e9-8b18-03ee9df77367.png)
打印了data和packages，然后带入这两个数据不对，是写入明文还是密文？

**Comment by blockdate** [comment]
不好意思没看仔细，setnotify返回的是一个promise对象，在这个promise的then函数的返回值里面才是可操作的蓝牙对象
```
ble.setNotify(true).then(bluetooth => { bluetooth.write(hexStringData).then(...) })
```

**Comment by AMI-zz** [comment]
data不对，我刚才看了，data是网络状态，不对，

**Comment by AMI-zz** [comment]
![image](https://user-images.githubusercontent.com/27339224/52893493-b7a0a900-31d7-11e9-9094-793646a67f60.png)
![image](https://user-images.githubusercontent.com/27339224/52893502-cedf9680-31d7-11e9-9a42-43d0e0651b7f.png)
ble.setNotify(true).then(bluetooth => { bluetooth.write(hexStringData).then(...) })
这个方法好像不行呀 ，大佬帮忙再看下

**Comment by AMI-zz** [comment]
> 不好意思没看仔细，setnotify返回的是一个promise对象，在这个promise的then函数的返回值里面才是可操作的蓝牙对象
> 
> ```
> ble.setNotify(true).then(bluetooth => { bluetooth.write(hexStringData).then(...) })
> ```



> 不好意思没看仔细，setnotify返回的是一个promise对象，在这个promise的then函数的返回值里面才是可操作的蓝牙对象
> 
> ```
> ble.setNotify(true).then(bluetooth => { bluetooth.write(hexStringData).then(...) })
> ```

这个好像不对，麻烦再帮忙看下

**Comment by blockdate** [comment]
你的`ble`对象是如何初始化的呢，方便截个图看下吗

**Comment by AMI-zz** [comment]
> 你的`ble`对象是如何初始化的呢，方便截个图看下吗

const ble = Device.getBluetoothLE();

**Comment by AMI-zz** [comment]
> 你的`ble`对象是如何初始化的呢，方便截个图看下吗

麻烦看下这个问题

**Comment by blockdate** [comment]
不好意思你，这两天的确有点忙，回复的有点慢了，请问你参考了 project/com.xiaomi.bledemo中的样例了吗。

如果确实无法解决，把你的微信号发到wulei7@xiaomi.com，做好相应备注，我在微信上帮助你解决这个问题。因为蓝牙模块使用是ok的，不少厂商已经完成了新框架蓝牙功能的接入。

**Comment by AMI-zz** [comment]
> 不好意思你，这两天的确有点忙，回复的有点慢了，请问你参考了 project/com.xiaomi.bledemo中的样例了吗。
> 
> 如果确实无法解决，把你的微信号发到[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)，做好相应备注，我在微信上帮助你解决这个问题。因为蓝牙模块使用是ok的，不少厂商已经完成了新框架蓝牙功能的接入。

蓝牙demo我参考过了

**Comment by AMI-zz** [comment]
> wulei7@xiaomi.com

**Comment by AMI-zz** [comment]
> > 不好意思你，这两天的确有点忙，回复的有点慢了，请问你参考了 project/com.xiaomi.bledemo中的样例了吗。
> > 如果确实无法解决，把你的微信号发到[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)，做好相应备注，我在微信上帮助你解决这个问题。因为蓝牙模块使用是ok的，不少厂商已经完成了新框架蓝牙功能的接入。
> 
> 蓝牙demo我参考过了，邮件已发，请大佬在微信上指导

**Comment by AMI-zz** [comment]
> > > 不好意思你，这两天的确有点忙，回复的有点慢了，请问你参考了 project/com.xiaomi.bledemo中的样例了吗。
> > > 如果确实无法解决，把你的微信号发到[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)，做好相应备注，我在微信上帮助你解决这个问题。因为蓝牙模块使用是ok的，不少厂商已经完成了新框架蓝牙功能的接入。
> > 
> > 
> > 蓝牙demo我参考过了，邮件已发，请大佬在微信上指导

请问大佬，看邮件了吗 ，在线等解决疑问
