### ISSUE TITLE
新版扩展程序 本地图片 2倍3倍的图怎么适配啊，求代码！感谢

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#289]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by LiuMengzhou** [comment]
项目下有：
back@1x.png
back@2x.png
back@3x.png

代码：
require('../back.png');

refrence:https://facebook.github.io/react-native/docs/images
