### ISSUE TITLE
Animated.ImageBackground undefined疑惑

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#29]
“迁移手册”中提到：
[https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/%E8%BF%81%E7%A7%BB%E6%89%8B%E5%86%8C.md](url)

> <Animated.ImageBackground>
  <Animated.Text></Animated.Text>
</Animated.ImageBackground>

但查询到 [https://github.com/facebook/react-native/issues/16939](url)
Animated.ImageBackground 其实是undefined的，无法使用，请问是米家内部支持了Animated.ImageBackground么？现在就是需要用这个组件，但插件里面运行奔溃

**Comment by LiuMengzhou** [comment]
@edwardair 
文档原文：
```html
// new
<ImageBackground>
  <Text></Text>
</ImageBackground>
// not allowed,❌
<Animated.ImageBackground>
  <Animated.Text></Animated.Text>
</Animated.ImageBackground>
// alternative solution,👌
<Animated.ImageBackground />
<Animated.View style={{position:'absolute'}}>
  <Animated.Text></Animated.Text>
</Animated.View>
```
文档上写的是 not allowed，正确用法是：
```html
<Animated.Image />
<Animated.View style={{position:'absolute'}}>
  <Animated.Text></Animated.Text>
</Animated.View>
```
文档没有及时更新，抱歉。
