### ISSUE TITLE
新版米家扩展程序，与设备端通信，这个怎么使用啊，什么原理，求大佬指点，跪求！！！

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#292]
<img width="919" alt="923547d3-2185-4c10-8cf1-5f4695ba05be" src="https://user-images.githubusercontent.com/38349220/52893925-b756dc80-31dc-11e9-9293-fd43ea07c5e6.png">

**Comment by liuhaixu666** [comment]
怎么读写设备的数据啊

**Comment by blockdate** [comment]
callmethod是通过米家服务器或者局域网wifi向配网设备发送RPC指令。具体指令请咨询相关硬件开发工程师
