### ISSUE TITLE
新版米家扩展程序上传固件的问题

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#293]
这个固件是什么固件啊，还有MD5 是随便写的吗
<img width="732" alt="d7f197de-955c-44b7-9858-708d3132a716" src="https://user-images.githubusercontent.com/38349220/52895710-f85cea00-31f8-11e9-98eb-4cf32f0ec954.png">

**Comment by blockdate** [comment]
固件是用于给设备进行固件更新使用的，md5就是文件md5，这个不知道是哪不明白？
