### ISSUE TITLE
iOS平台线上版本共享设备问题

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#294]
最新ipa、SDK

---

#### 环境
- 电脑操作系统:Mac OS

#### 现象

当我插件内，调用过  `alert` 弹窗提示文字，然后进入插件的设备分享页面，点击确定分享，在对方未接受邀请状态，米家本身会有一个Dialog提示“ `已发送邀请xxxxxxx` ”的提示文字，但在这个Dialog下面，会出现之前的alert界面，并且跟随米家的Dialog一起消失；等到对方接受设备后，再次点击 确定分享，则提示` 已共享给对方 `，这时候不会有alert界面（正常），麻烦帮忙检查下这是哪里的问题（`测试环境无问题`）

**Comment by liuhaixu666** [comment]
你好，能加个微信吗？刚接入米家，好多问题不懂，能指教一下不，谢谢

**Comment by blockdate** [comment]
@edwardair 使用上传好的插件包，尝试重现你描述的操作，但是并未出现你描述的dialog下出现之前的alertUI， 这边是否有稳定的复现方式，或者方便录制一个视频
