### ISSUE TITLE
旧框架的一些监听“XXXname”名字，新框架的哪些对象可以替换？？？？？？

### ISSUE THREAD

**Issue by AMI-zz** [MiEcosystem/miot-plugin-sdk#295]
### 望大佬指导

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS]
- 相关模块:[蓝牙Ble]

#### 现象

简单明了地描述一下实际的现象。
![image](https://user-images.githubusercontent.com/27339224/52898130-44b62300-3215-11e9-9027-b3394006b5c3.png)
![image](https://user-images.githubusercontent.com/27339224/52898136-54ce0280-3215-11e9-83ea-64e3871b30df.png)
变量名1： const EVENT_RECEIVE_DATA = MHBluetooth.peripheral_didUpdateValueForCharacteristic_error
 变量名2：const EVENT_DISCONNECT_DATA = MHBluetooth.centralManager_didDisconnectPeripheral_error

变量名3：MHBluetoothLE.event.centralManagerDidUpdateState

变量名4：MHBluetoothLE.event.centralManager_didConnectPeripheral_error
#### 期望

因为一些逻辑要使用该变量，我不知道从API文档中拿什么替换？？？

**Comment by blockdate** [comment]
参考

1. [在线API文档](https://miecosystem.github.io/miot-plugin-sdk/module-miot_Bluetooth-BluetoothEvent.html#.event:bluetoothCharacteristicDiscoverFailed)中的Event事件的描述和example

2.  [wiki](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/03-%E8%93%9D%E7%89%99%E6%A8%A1%E5%9D%97#module_miot/Bluetooth--module.exports..BluetoothEvent)中对于BluetoothEvent的描述。

**Comment by AMI-zz** [comment]
OK
