### ISSUE TITLE
关于安卓平台和iOS平台接口获取蓝牙特征值的错误

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#296]
您好，我这边关于在iOS平台和安卓平台，接口获取蓝牙的特征值的时候，出现的问题。
版本是这两天更新的最新版本。

在iOS平台正常运行，在安卓平台有错误。情况描述如下：
1、注册监听特征的代码
![snip20190217_2](https://user-images.githubusercontent.com/18459414/52910602-c751e780-32d4-11e9-940b-2371723573dd.png)
2、在iOS平台运行的时候，调试正常，可以获取对应特征值
![snip20190217_4](https://user-images.githubusercontent.com/18459414/52910612-f5372c00-32d4-11e9-8012-1bb4b657c011.png)
3、在安卓平台运行的时候，调试错误，获取对应特征值失败
![snip20190217_5](https://user-images.githubusercontent.com/18459414/52910621-1bf56280-32d5-11e9-8c20-24813bde1247.png)

感谢！

**Comment by lvjie0519** [comment]
看log,调用setNotify就报错了。
Android Studio Logcat 使用关键字 miio-bluetooth 过滤下日志看看？

**Comment by caojunhua** [comment]
> miio-bluetooth

[android_log.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/2873999/android_log.txt)

**Comment by lvjie0519** [comment]
看日志输出，是该服务下没有对应的特征值。
![image](https://user-images.githubusercontent.com/22487747/52931020-ccbb3a80-3385-11e9-9873-014ee175328d.png)

**Comment by caojunhua** [comment]
> 看日志输出，是该服务下没有对应的特征值。
> ![image](https://user-images.githubusercontent.com/22487747/52931020-ccbb3a80-3385-11e9-9873-014ee175328d.png)

谢谢，但是我iOS平台运行可以啊 。。 而且我安卓平台打印信息里有发现该特征值呀
![snip20190218_7](https://user-images.githubusercontent.com/18459414/52942991-11a39900-33a7-11e9-8526-53c8efdfc0dc.png)

**Comment by lvjie0519** [comment]
@caojunhua 问题解决了吗？  要看该服务下是否有对应的特征值，看你的log日志，部分setNotify是成功的，部分是因为该服务下没有对应的特征值而失败的，您可以详看下log日志。

**Comment by caojunhua** [comment]
> @caojunhua 问题解决了吗？ 要看该服务下是否有对应的特征值，看你的log日志，部分setNotify是成功的，部分是因为该服务下没有对应的特征值而失败的，您可以详看下log日志。

谢谢，暂时还没有解决，我想问一点，在安卓平台和iOS平台特征值的大小写会区分吗？因为我的打印iOS里面的是大写，安卓里面的小写的。
