### ISSUE TITLE
新框架iOS端调试问题

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#297]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

新框架iOS端调试看不了界面，现象如下图

![1661550458921_ pic](https://user-images.githubusercontent.com/17919773/52925493-a3da7b80-336c-11e9-83fa-bfb34a92a819.jpg)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
你所谓的看不了界面是指什么？你这个界面是刚创建的插件吧，UI就长这样。。。
