### ISSUE TITLE
怎么调用获取临时文件接口？

### ISSUE THREAD

**Issue by weeksun23** [MiEcosystem/miot-plugin-sdk#298]
请问/v2/home/get_interim_file_url和/home/getfileurl 这两个获取临时文件和获取文件下载地址 接口新框架怎么调用？以前直接callSmartHomeAPI就行了，现在的miot/service/smarthome 不支持。

**Comment by lvjie0519** [comment]
请告知一下您那边之前的具体代码使用，例如参数等，我这边为您添加。

**Comment by weeksun23** [comment]
以下是请求参数：
get_interim_file_url  : {obj_name : '{ownerId}/{deviceId}/{index}'}

getfileurl : {obj_name : '2018/06/08/123456/xiaomi123_181030106.mp3'}

**Comment by lvjie0519** [comment]
已添加，请更新sdk.

**Comment by weeksun23** [comment]
请问怎么使用呢，api文档有更新吗？没看到....

**Comment by lvjie0519** [comment]
> 请问怎么使用呢，api文档有更新吗？没看到....

您更新sdk，应该可以看到git提交记录吧？ 
smarthome.js 中 getInterimFileUrl   getFileUrl 两个。

**Comment by weeksun23** [comment]
可以了，谢谢

**Comment by RideShi** [comment]
@lvjie0519 我想用 Service.smarthome.getFileUrl 获取文件地址，上传本地文件，应该如何操作呢
![image](https://user-images.githubusercontent.com/15190511/57290870-e8b2ba80-70f0-11e9-8936-3a59af7b3cd6.png)
<img width="808" alt="image" src="https://user-images.githubusercontent.com/15190511/57290892-f0725f00-70f0-11e9-9e2c-b3007ae42446.png">

**Comment by blockdate** [comment]
参考 Host.file 中的文件上传操作。demo中文件存储部分已提供示例

**Comment by RideShi** [comment]
> 参考 Host.file 中的文件上传操作。demo中文件存储部分已提供示例

 老框架使用下面这个方法
<img width="676" alt="image" src="https://user-images.githubusercontent.com/15190511/57294757-3d5b3300-70fb-11e9-88a7-6dc0fdec1833.png">

新框架按照demo中调用generateObjNameAndUrlForFDSUpload，报错信息 "message": "fds config for third  chuangmi.lock.hmi501 not found!", 老框架正常，是调用方法不对么？
<img width="803" alt="image" src="https://user-images.githubusercontent.com/15190511/57294826-70052b80-70fb-11e9-9c32-d3baf3d0830b.png">

![image](https://user-images.githubusercontent.com/15190511/57294701-11d84880-70fb-11e9-9a05-4c45518ddd46.png)

**Comment by blockdate** [comment]
现有提供的接口需要权限申请才可用，genfilepresignedurl 这个暂未提供，这边需要讨论后看是否提供。

**Comment by blockdate** [comment]
更新SDK 10011 ，使用 Host.file.generateObjNameAndUrlForLogFileFDSUpload

**Comment by RideShi** [comment]
> 更新SDK 10011 ，使用 Host.file.generateObjNameAndUrlForLogFileFDSUpload.
> 如果还有问题，及时回复

第一次使用时，能获取到URL，但是我继续测试时却获取不到值了

**Comment by RideShi** [comment]
> 更新SDK 10011 ，使用 Host.file.generateObjNameAndUrlForLogFileFDSUpload.
> 如果还有问题，及时回复
获取不到值 
![image](https://user-images.githubusercontent.com/15190511/57367162-09dfdd80-71bb-11e9-8b91-73d473409963.png)

<img width="817" alt="image" src="https://user-images.githubusercontent.com/15190511/57367130-fd5b8500-71ba-11e9-9b79-c7623f7e73d1.png">

**Comment by RideShi** [comment]
> 更新SDK 10011 ，使用 Host.file.generateObjNameAndUrlForLogFileFDSUpload.
> 如果还有问题，及时回复
安卓上日志如下
![image](https://user-images.githubusercontent.com/15190511/57367722-1e70a580-71bc-11e9-816b-dcf55cef912d.png)

**Comment by blockdate** [comment]
1. 你上传的文件名称路径是否正确
2. 在iOS下使用是否正常

**Comment by RideShi** [comment]
> * 你上传的文件名称路径是否正确
> * 在iOS下使用是否正常
路径名称没问题，
iOS上也不行,报错403，签名不匹配 uploadFileToFDS 以及uploadFile都不行
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/15190511/57669504-c7e0ec80-763d-11e9-8e7d-294e98b55bd4.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/15190511/57673132-7e989900-764d-11e9-915e-b233dbbdd677.png">
![image](https://user-images.githubusercontent.com/15190511/57673155-8f490f00-764d-11e9-8d48-5e0cdaec739a.png)

**Comment by blockdate** [comment]
1. Android下可能是文件路径读写存在问题，我这边让相关同学排查下。
2. 这边尝试试用下Host.file.uploadFile(xx)这个接口进行文件上传试试。

**Comment by RideShi** [comment]
Host.file.uploadFile方法已经试过，也是一样的，不能使用

**Comment by blockdate** [comment]
你们在旧版本下的使用时怎样的，我看下是不是迁移中出错了

**Comment by RideShi** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/15190511/57678251-62035d80-765b-11e9-9224-cb7f27732c30.png">
旧版如上图所示，可以正常使用

**Comment by blockdate** [comment]
这边排查了旧插件下的uploadFile与新插件下的Host.file.uploadFile是一致的。
提供下MiCloudApi.getDownUrlByKey这个实现。
顺便建议将两边的实现参数等都统一下？

**Comment by RideShi** [comment]
目前使用 Host.file.generateObjNameAndUrlForLogFileFDSUpload获取文件上传地址 ，可以获取到地址
<img width="689" alt="image" src="https://user-images.githubusercontent.com/15190511/57680073-5ca81200-765f-11e9-809c-e0d44a126129.png">

**Comment by blockdate** [comment]
你把两边的upload参数统一下？这一块的实现是直接从旧插件迁移过来的，并没有调整

**Comment by RideShi** [comment]
OK 可以了，谢谢🙏
