### ISSUE TITLE
监听蓝牙的变化状态的时间常量，新旧框架怎么替换，例如：BluetoothEvent.bluetoothConnectionStatusChanged 

### ISSUE THREAD

**Issue by AMI-zz** [MiEcosystem/miot-plugin-sdk#299]
---

#### 环境
- 电脑操作系统:[.Windows]
- 手机系统:[IOS]
- 相关模块:[蓝牙监听状态改变相关事件]

#### 现象

简单明了地描述一下实际的现象。
![image](https://user-images.githubusercontent.com/27339224/52937788-09456100-339b-11e9-96e4-1286823f15f7.png)
红框为旧框架的监听值，绿框为我替换的，好像不对，同样的问题，如下图：
![image](https://user-images.githubusercontent.com/27339224/52937928-51648380-339b-11e9-912a-77948092cf3c.png)

![image](https://user-images.githubusercontent.com/27339224/52938013-896bc680-339b-11e9-8cd8-354d35a60931.png)

#### 期望

麻烦看一下，我是根据API修改的，估计是引用不对，还是什么问题，帮忙看下是什么原因，绑定的事件不起作用

**Comment by AMI-zz** [comment]
![image](https://user-images.githubusercontent.com/27339224/52942293-b1602780-33a5-11e9-9b03-ecb885555703.png)
报错如下：
![image](https://user-images.githubusercontent.com/27339224/52942343-ca68d880-33a5-11e9-81ac-5fa2b375b677.png)
eventType.lastIndexOF is not a function

**Comment by AMI-zz** [comment]
没有找到这个要监听的对象

**Comment by lvjie0519** [comment]
看您的蓝牙api使用好像有问题，关于蓝牙的基本使用，您可以先参考下我们提供的
demo：  com.xiaomi.bledemo  其中的MainPage.js 中的具体使用，希望能帮到您。

**Comment by AMI-zz** [comment]
> 看您的蓝牙api使用好像有问题，关于蓝牙的基本使用，您可以先参考下我们提供的
> demo： com.xiaomi.bledemo 其中的MainPage.js 中的具体使用，希望能帮到您。

那个event.centralManager_didConnectPeripheral_error 设备连接成功，这个监听用那个呢 ，蓝牙demo已经参考，还是有疑问

**Comment by AMI-zz** [comment]
> 看您的蓝牙api使用好像有问题，关于蓝牙的基本使用，您可以先参考下我们提供的
> demo： com.xiaomi.bledemo 其中的MainPage.js 中的具体使用，希望能帮到您。
我这个还有问题，麻烦看下这个怎么替换，实在是不知道替换什么监听名字，打印出来还是undefined

**Comment by AMI-zz** [comment]
> 看您的蓝牙api使用好像有问题，关于蓝牙的基本使用，您可以先参考下我们提供的
> demo： com.xiaomi.bledemo 其中的MainPage.js 中的具体使用，希望能帮到您。

demo也已经参考过了，现在目前是在constructor（）下面添加监听，监听的名字/名词最好跟旧版本的相似呢，
 const EVENT_RECEIVE_DATA = MHBluetooth.peripheral_didUpdateValueForCharacteristic_error
 const EVENT_DISCONNECT_DATA = MHBluetooth.centralManager_didDisconnectPeripheral_error，还有const EVENT_DISCONNECT_DATA = MHBluetoothLE.event.centralManager_didDisconnectPeripheral_error
MHBluetoothLE.event.centralManagerDidUpdateState
MHBluetoothLE.event.centralManager_didConnectPeripheral_error，一共就五个，麻烦看用什么代替这些对象名词

**Comment by AMI-zz** [comment]
> 看您的蓝牙api使用好像有问题，关于蓝牙的基本使用，您可以先参考下我们提供的
> demo： com.xiaomi.bledemo 其中的MainPage.js 中的具体使用，希望能帮到您。

或者看下有什么可以规避的方法，绑定监听bind
