### ISSUE TITLE
AMapView 如何动态设置中心

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#302]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
页面的mapview 初始情况下加载了一个默认的中心点，网络数据过来之后希望把中心点移到新的坐标点上。现象是中心点移到位了，但是zoomlevel 不对了（不是我自己设置18）

代码如下
<AMapView
                    ref={(c) => this._aaa = c}
                    style={styles.map}
                    distanceFilter={100}
                    zoomLevel={this.state.zoomLevel}
                    centerCoordinate={{latitude: this.state.centerLatitude,longitude: this.state.centerLongitude}}
                    showsCompass={false}
                    showsScale={false}
                    annotations={this.state.annotations}
                    mapType={2}
                    />

数据异步变更
var annotation = {
                            id: 'annotation' + latitude + longitude,
                            title: '目标位置',
                            image: require( '../Resources/map/003.png'),
                            size: {
                              width: 64,
                              height: 64,
                            },
                            canShowCallout: false,
                            lockedScreenPoint:{x:0.5,y:1},//控制图标绘制起点相对点击的位置，android 测了
                            coordinate: {
                              latitude: parseFloat(latitude),
                              longitude: parseFloat(longitude),
                            },
                        };
                        this.setState({
                            zoomLevel: 18,
                            centerLatitude: parseFloat(latitude),
                            centerLongitude: parseFloat(longitude),
                            annotations: new Array(annotation),
                            showLocation : true
                        })

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、看了下我们这边有对zoomLevel做判断，防止大于zoomLevel最大值和小于最小值，您测试下其他值看是否有对应的效果？

**Comment by smalld2006** [comment]
试了下初始zoomLevel 18，动态设置zoomLevel 17时效果是对的。但是初始 17 动态设置17或者初始18动态设置18就有问题

**Comment by lvjie0519** [comment]
但是初始 17 动态设置17或者初始18动态设置18就有问题
RN自身有优化，初始17，动态设置17，是不会触发相关方法执行的，必须要设置为不同的值，才会触发。

**Comment by smalld2006** [comment]
那我不动态设置zoomLevel，只动态设置centerCoordinate的时候效果不对啊，地图被缩放了

**Comment by lvjie0519** [comment]
@smalld2006 已修复，请使用最新apk和sdk

**Comment by smalld2006** [comment]
现在初始加载没问题了
但是还有另外个需求，在地图被拖动后，可以通过复位键重新移动到之前的中心点并将zoomlevel还原成初始值18，实现如下
    _doLocation() {
        if (carLatitude && carLongitude) {
            console.log("_doLocation " + carLatitude + " " + carLongitude);
            this.setState({
                zoomLevel: 18,
                centerLatitude: carLatitude,
                centerLongitude: carLongitude
            })
        }
    }
但是这个方法目前没有效果

**Comment by smalld2006** [comment]
试了没效果，是centerCoordinate的值没有变化rn没有传递事件？如果是这种情况的话，map组件有响应的中心点变化的监听接口吗？

**Comment by lvjie0519** [comment]
> 试了没效果，是centerCoordinate的值没有变化rn没有传递事件？如果是这种情况的话，map组件有响应的中心点变化的监听接口吗？

没有其他监听接口，您可以尝试centerCoordinate中增加其他变量修改其值，只需保证latitude和longitude不变就可以，能起到刷新AMapView的作用。

**Comment by smalld2006** [comment]
ok,可以了！多谢！

**Comment by smalld2006** [comment]
mihome线上5.4.61版本还是有问题，问下什么时候更新线上版本？
