### ISSUE TITLE
MiService.smarthome.callThirdPartyAPI问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#303]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

同一个网络请求，请求参数相同，但是Ios请求来的结果和Android请求来的结果不同，Ios的结果是正常的，android结果错误。

请求方法：
<img width="802" alt="image" src="https://user-images.githubusercontent.com/7885251/52986237-0e092400-3432-11e9-809a-db86c4ef976f.png">

ios: 
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/7885251/52986173-ce423c80-3431-11e9-8ab6-957ea14be4ea.png">

android:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/7885251/52986128-a2bf5200-3431-11e9-9a06-607481a28979.png">

#### 期望

两端请求结果一致

**Comment by lvjie0519** [comment]
@JxXiaoXie  更新下sdk 试试

**Comment by JxXiaoXie** [comment]
信息可以请求到了，可是Android端还是跟IOS端有区别，区别如下：

IOS 
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/7885251/53312458-0f35c780-38f0-11e9-819f-812d5751e7c4.png">

Android
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/7885251/53312632-c9c5ca00-38f0-11e9-897d-4f355a2099c7.png">

Android 多包了一层{"code":0,"message":"ok","result":

这两层代表的含义不同吗？

**Comment by lvjie0519** [comment]
@JxXiaoXie    Android是把服务端返回的response原封不动的返回回来了，ios解析了一次，将外层的result返回来的。我这边修改下，保持和ios一致。

**Comment by lvjie0519** [comment]
@JxXiaoXie   更新下sdk试试

**Comment by JxXiaoXie** [comment]
更新了，试了还是包了两层code

**Comment by lvjie0519** [comment]
你把你的设备分享给我，账号：1404467753,  告诉一下设备名称及model， 我这边调试下试试。

我这边返回格式如下：
![image](https://user-images.githubusercontent.com/22487747/53320292-2d132480-3910-11e9-97ef-31659c58e935.png)

**Comment by JxXiaoXie** [comment]
我又试了下，确实可以了，多谢。

**Comment by JxXiaoXie** [comment]
您好，我发现还是不一样，你改完后还是比ios多了一层，之前的多了两层，你只去掉一层。

**Comment by JxXiaoXie** [comment]
你好，还需要再去一层才跟IOS一致。

ios返回格式如下：
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/7885251/53386903-3effd080-39bf-11e9-9166-a64501d996f9.png">

**Comment by lvjie0519** [comment]
@JxXiaoXie  你把你的设备分享给我，账号：1404467753, 告诉一下设备名称及model， 我这边调试下试试。

**Comment by lvjie0519** [comment]
@JxXiaoXie  问题是否还存在？  如果存在请将设备分享给如上账号，这里暂先关闭。
