### ISSUE TITLE
新版扩展程序蓝牙搜索到的服务为什么都是空啊

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#304]
Bluetooth.checkBluetoothIsEnabled()
            .then(result => {

                Bluetooth.startScan(3000, '')

            });
        BluetoothEvent.bluetoothDeviceDiscovered.addListener((bluetooh,service) => {
            console.log('服务');
            console.log(service);
<img width="1202" alt="2a3214da-c44e-48c5-be2d-9c999c963937" src="https://user-images.githubusercontent.com/38349220/52987469-3561f000-3436-11e9-868d-7c2cb5f29766.png">

**Comment by lvjie0519** [comment]
看您打印的state为disconnected，处于断开状态，需要先连接蓝牙。

**Comment by blockdate** [comment]
默认不会再发现设备时进行扫描，需要startDiscoverServices进行扫描
