### ISSUE TITLE
服务器端数据统计功能

### ISSUE THREAD

**Issue by facexxyz** [MiEcosystem/miot-plugin-sdk#305]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 9.0]
- 相关模块:[eg.Host/Service/Account]

#### 期望

新插件端需要做图表统计，数据设备每小时上报后，在哪里做年、月、日汇总？能否给点思路？

#### 尝试过的解决办法
1. 小米不允许接入私有服务器，是不是可以做云云对接？
2. 小米后台提供数据统计功能，目前没有。

**Comment by lvjie0519** [comment]
@facexxyz  麻烦加下我微信号 18750118631，这个需要详细讨论下。

**Comment by facexxyz** [comment]
> @facexxyz 麻烦加下我微信号 18750118631，这个需要详细讨论下。

已经加了

**Comment by lvjie0519** [comment]
@facexxyz  先暂时关闭，如果后期需要做支持，再重新打开。
