### ISSUE TITLE
Device.getDeviceWifi().callMethod 在安卓（最新的APK）下调用失败，iOS上可行

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#306]
【一】你好 我的新插件开发完成了
但是打包上传平台后测试无法运行

安卓端打开是白屏一段时间然后闪退
iOS端显示如下图

![511550498794_ pic](https://user-images.githubusercontent.com/14158970/53001604-02cfeb80-3466-11e9-89cf-19f2dc378009.jpg)

【二】设备订阅属性后，属性改变收不到通知

【三】隐私政策弹出后，点击同意没有回调，如下图
![531550550014_ pic_hd](https://user-images.githubusercontent.com/14158970/53002520-d3ba7980-3467-11e9-845d-1600c59f141c.jpg)

【四】现在米家不允许接入自己的服务器，我们的设备会上报历史数据到米家服务端
请问米家服务端能提供历史数据的年月日分组吗。如果不行的话我们该如何实现。

**Comment by dingshaoran** [comment]
android 白屏问题等更新 apk

**Comment by blockdate** [comment]
1.  这个问题可以的话将问题设备分享至 894158105 账号，这边查看下iOS的问题。
2. 设备订阅属性是可以收到通知的，如果可以请提供下你的使用方法和当时的rn日志输出。
3. 问题出现在iOS还是Android。
4. 这个数据上报是通过现有的服务端接口调用的吗。

**Comment by RengeRenge** [comment]
> * 这个问题可以的话将问题设备分享至 894158105 账号，这边查看下iOS的问题。
> * 设备订阅属性是可以收到通知的，如果可以请提供下你的使用方法和当时的rn日志输出。
> * 问题出现在iOS还是Android。
> * 这个数据上报是通过现有的服务端接口调用的吗。

你好
1. 已经分享， 名字是 「佳尼特600G全包机2」
2.在更新最新版测试App后可以收到通知了 （已解决）
3.经测试两个平台都没有回调 
4.这个还不确定，好像你们的人已经和我们对接开发了（解决中）

谢谢

**Comment by blockdate** [comment]
1. 我们检查后应该是资源引用的问题，我们也会更新sdk避免这个rn的crash。具体可以看下方修正SDK后的截图。是否是红框处资源使用有误。
<img width="377" alt="wx20190220-200247 2x" src="https://user-images.githubusercontent.com/4339364/53090866-94655900-354b-11e9-8a4a-d49f53920541.png">

3.这个方法使用错误，`openPrivacyLicense` 返回的是一个promise<BOOL>，在这个promise的then中去判断是否授权。

**Comment by RengeRenge** [comment]
> 1. 我们检查后应该是资源引用的问题，我们也会更新sdk避免这个rn的crash。具体可以看下方修正SDK后的截图。是否是红框处资源使用有误。
> 
> <img alt="wx20190220-200247 2x" width="377" src="https://user-images.githubusercontent.com/4339364/53090866-94655900-354b-11e9-8a4a-d49f53920541.png">
> 
> 3.这个方法使用错误，`openPrivacyLicense` 返回的是一个promise，在这个promise的then中去判断是否授权。

1. 关于图片资源问题，一开始设备状态没查询出来，我给Image组件的source传了一个null，本地测试是没有问题的。考虑到不想布局变化，所以就这么做了。
3. 修改后可以了使用的，你们的demo上的写法有问题，可以更新一下。（已决解）

再提个建议，能否引入 [react-native-echarts-demo](https://github.com/entronad/react-native-echarts-demo) 这个图表库，现在提供的 victory-native 图表样式无法满足需求，而且滑动时非常卡顿（这边数据显示需要x轴滑动）。我尝试后发现 iOS可以直接导入 echarts ，但是安卓需要在项目 assets 下放一个 html 文件

**Comment by lvjie0519** [comment]
@RengeRenge   Device.getDeviceWifi().callMethod 在安卓（最新的APK）下调用失败

1、看错误是timeout，是必现吗？
2、麻烦给设备分享给1404467753这个账号，callMethod中的参数也麻烦告知下，我这边调试下看看。

**Comment by RengeRenge** [comment]
> @RengeRenge Device.getDeviceWifi().callMethod 在安卓（最新的APK）下调用失败
> 
> 1、看错误是timeout，是必现吗？
> 2、麻烦给设备分享给1404467753这个账号，callMethod中的参数也麻烦告知下，我这边调试下看看。

你好。不好意思昨天没看到。
是必现的，已分享。

```
Device.getDeviceWifi().callMethod('rGetSysState', null)
      .then(res => {
        let deviceState = res.result
        that.setState({
          deviceCurrentState: deviceState
        })
      })
      .catch(err => {
        alert('获取设备信息失败' + err.toString())
      })
```

**Comment by lvjie0519** [comment]
@RengeRenge  我这边好像没看到，具体说一下设备的名称和model吧，谢谢！

**Comment by RengeRenge** [comment]
> @RengeRenge 我这边好像没看到，具体说一下设备的名称和model吧，谢谢！

你好前几天别的事耽搁了，我现在更新了最新的sdk和apk还是执行失败

model 是 smith.waterpuri.jnt600， 是beta版的apk里共享给你的

**Comment by lvjie0519** [comment]
@RengeRenge 
1、beta版的apk，是git库中的apk吗？下面这个链接，自己调试请使用git库中的apk；
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/SmartHome_debug_2_26.apk
2、我这边没收到您分享的设备，米家设置中的地区是大陆地区吗？地区一致才能收到；

**Comment by RengeRenge** [comment]
> @RengeRenge
> 1、beta版的apk，是git库中的apk吗？下面这个链接，自己调试请使用git库中的apk；
> https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/SmartHome_debug_2_26.apk
> 2、我这边没收到您分享的设备，米家设置中的地区是大陆地区吗？地区一致才能收到；

是用的这个apk
我这边也显示你没有接收
是环境不一致吗，我是在正式环境分享给你的

smith.waterpuri.jnt600
名字开头是 佳尼特

**Comment by lvjie0519** [comment]
@RengeRenge 
方法不存在，确定下是否有该方法。
![image](https://user-images.githubusercontent.com/22487747/53628370-d9714580-3c45-11e9-9c4f-f348fe744000.png)

**Comment by RengeRenge** [comment]
> @RengeRenge
> 方法不存在，确定下是否有该方法。
> ![image](https://user-images.githubusercontent.com/22487747/53628370-d9714580-3c45-11e9-9c4f-f348fe744000.png)

你好 有的
![438435d9-4068-48f5-89f7-c5b08f649904](https://user-images.githubusercontent.com/14158970/53628765-dc206a80-3c46-11e9-9855-da728cdf2009.png)
 iOS 都可以调用到
如图所示代码，有调用错误的地方吗
![dcafa238-035d-48c3-a21c-93f4a904bab5](https://user-images.githubusercontent.com/14158970/53628617-792ed380-3c46-11e9-907b-267036e1639d.png)

**Comment by lvjie0519** [comment]
@RengeRenge 
设备分享是不是取消了，进程选择如下图，看下log日志吧，更清楚些。
![image](https://user-images.githubusercontent.com/22487747/53629364-543b6000-3c48-11e9-86ae-4bae98e33142.png)

**Comment by RengeRenge** [comment]
> @RengeRenge
> 设备分享是不是取消了，进程选择如下图，看下log日志吧，更清楚些。
> ![image](https://user-images.githubusercontent.com/22487747/53629364-543b6000-3c48-11e9-86ae-4bae98e33142.png)

你好 刚刚掉线了 重新添加了一下。已分享
log 在哪里看 这边只能看到RN的报错

**Comment by lvjie0519** [comment]
@RengeRenge  设备又掉线了，log日志看到确实是网络超时；
1、确定下手机与设备是否在一个局域网？
Device.getDeviceWifi().callMethod  设备与手机必须在同一个网段；
请使用callMethodFromCloud试试，该方法走的是云端。

**Comment by RengeRenge** [comment]
> @RengeRenge 设备又掉线了，log日志看到确实是网络超时；
> 1、确定下手机与设备是否在一个局域网？
> Device.getDeviceWifi().callMethod 设备与手机必须在同一个网段；
> 请使用callMethodFromCloud试试，该方法走的是云端。

你好 这个方法还是不行。
日志如下图
![588bb065-725a-4ab8-b75a-b0b97e315d8b](https://user-images.githubusercontent.com/14158970/53779443-16398700-3f3b-11e9-81f0-343d70e82ceb.png)

**Comment by lvjie0519** [comment]
@RengeRenge   麻烦将您的截图给您那边设备方开发人员沟通下看看，看是否设备有什么问题或我们这边发起的rpc请求有问题？

**Comment by RengeRenge** [comment]
> @RengeRenge 麻烦将您的截图给您那边设备方开发人员沟通下看看，看是否设备有什么问题或我们这边发起的rpc请求有问题？

测试同一个设备，iOS 端是正常的，麻烦检查一下问题，谢谢

**Comment by RengeRenge** [comment]
Device.getDeviceWifi().callMethod('rGetSysState', null)
此处空参数不能传null, 应该传 {}
