### ISSUE TITLE
如何使用iOS原生组件、原生模块

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#307]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 11.0
- 相关模块:[eg.Host/Service/Account]

#### 现象
RN调用iOS原生组件，新版SDK支持吗？原生组件导出的静态库放在RN项目的哪个目录下？有没有相关文档？

#### 期望

最好有相关文档可供参考

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
rn自带的原生组件可随意使用，如果需要接入某些三方SDK中需要lint原生代码到项目中，这个需要提交评估，建议找一下纯js的实现替代方案。
