### ISSUE TITLE
android 非刘海屏导航栏疑问

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#309]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

首次进入插件页时，第一页导航栏高度不正确，进入下一页再返回后，变为正常。（这边有录屏，如果需要视频，需要提供一下邮箱）（非刘海屏）
如图：
首次进入插件页：
![1550648134036](https://user-images.githubusercontent.com/12531667/53074365-86044680-3525-11e9-994e-815e8f1e1b27.jpg)
进入下一页：
![1550648129477](https://user-images.githubusercontent.com/12531667/53074370-8866a080-3525-11e9-85b3-2bf0753b8601.jpg)
返回首页变正常了：
![1550648122835](https://user-images.githubusercontent.com/12531667/53074374-8a306400-3525-11e9-9c57-e629e888b7b4.jpg)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

### 不要贴大段代码❗️

**Comment by lvjie0519** [comment]
1、具体是什么机型，必现吗？
2、麻烦尝试运行下com.xiaomi.demo，是否同样出现？

**Comment by ldezho** [comment]
目前测了两款非刘海屏手机都出现了。
锤子 Android 7.1.2
华为 mate 8 Android 7.0

**Comment by ldezho** [comment]
@lvjie0519 demo没问题，找到问题了，TitleBarBlack源码有更新，我们是基于这个源码重新自定义的。
加上
if(Platform.OS == 'android'){
        StatusBar.setTranslucent(true);
    }
就好了。
