### ISSUE TITLE
安卓手机, 修改deviceName后app死机, 测试手机1+, 小米6

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#310]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

安卓手机, 修改deviceName后app死机, 测试手机1+, 小米6

#### 期望

修改名称后不死机

#### 其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/17062182/53079210-e6e54c00-3530-11e9-9bef-447fdfaa915b.png)
没有监听事件, 点击确定后就会死机
提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
我这边没发现问题，希望能提供下详细日志，方便排查，谢谢！
