### ISSUE TITLE
IOS MessageDialog不设置cancel按钮，但还是出现，请和android一致 。

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#311]
* 电脑操作系统:Mac OS/Linux
* 手机系统: Android / iOS
* 相关模块: MessageDialog

#### 现象
MessageDialog，没有设置cancel属性和onCancel函数，
在android手机上是正常的，就没有“取消”的button，
但在ios上还是有，怎么去除 ？

#### 期望
能和android表现一直

#### 其他的上下文/日志/截图
![_20190220182738](https://user-images.githubusercontent.com/44045029/53085159-3d588780-353d-11e9-9650-d080bcdf30d9.png)

**Comment by blockdate** [comment]
已更新，选择设置或者换不设置cancletitle和confirmtitle即可

**Comment by liuhaixu666** [comment]
> 已更新，选择设置或者换不设置cancletitle和confirmtitle即可

问题解决了？我试还是不好使
