### ISSUE TITLE
如果在获取数据之后，在显示插件首页，求大佬帮我看看，技术问题

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#312]
我们的插件首页分为有个2个页面，一个是登录授权页，一个是设置WiFi，支付的页面。现在我要判断设备是否授权过，如果授权过就跳到设置WiFi支付页面，如果没有授权，就跳到登录授权页面。现在我是否授权登录的数据可以拿到，但是是异步的，我应该在哪判断，才能让我再获取数据以后，在显示具体加载哪个首页。
插件首页代码，我想通过constants.logintype 判断显示哪个首页，因为数据是异步的，等我获取数据以后，都已经加载完成了
![wechatimg873](https://user-images.githubusercontent.com/38349220/53085230-611bcd80-353d-11e9-953a-3cd9818117d5.jpeg)

**Comment by edwardair** [comment]
自己加个Loading 、LOGO过渡动画/过渡页不就好了嘛

**Comment by blockdate** [comment]
已经有技术回复该问题
