### ISSUE TITLE
新框架运行报错，Unable to resolve module 

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#313]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

npm start后，运行项目报错，信息如下图，react native版本0.54.4，react版本16.3.0；删除node_modules后，重新npm install，运行还是一样。

![wechatimg168](https://user-images.githubusercontent.com/17919773/53146031-a1cb2380-35dd-11e9-81d7-c4a7b4e4458f.jpeg)

**Comment by blockdate** [comment]
你这个module导入路径`./../../../../../../`有问题吧。检查下导入路径是否出错
