### ISSUE TITLE
新版Ipa无法添加设备

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#314]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

IOS，更新了最新版的ipa(版本 113)包后，就无法再添加设备了， 一直报添加超时，望尽快修复。

#### 期望

正常添加设备

**Comment by blockdate** [comment]
更新测试版本尝试是否修复

**Comment by JxXiaoXie** [comment]
好了
