### ISSUE TITLE
ble扫描设备服务崩溃

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/miot-plugin-sdk#315]
今天晚上下载的sdk，打算开始新项目开发，发现ble扫描设备服务崩溃。

尝试用小米自带的demo（com.xiaomi.bledemo），修改工程目录下的progect.json文件（models和developer_id），更改app的开发人员设置项，还是相同的问题导致崩溃。

蓝牙连接设备正常，发起扫描服务（bt.startDiscoverServices）时就会出现参数匹配问题。

由于问题发生在未开放的代码，请帮忙看一下。感谢

MIOTBluetooth.discoverServices was called with 2 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

**Comment by lvjie0519** [comment]
1、请说明下平台，Android or IOS?
2、MIOTBluetooth.discoverServices was called with 2 arguments but expects 1 arguments，看这个错误是参数的问题，请使用最新的apk或ipa

**Comment by blockdate** [comment]
IPA 更新下吧，这边最新的ipa本地MIOTBluetooth.discoverServices是两个参数的，可能很久以前的版本是一个参数的

**Comment by gaopingfly** [comment]
> 1、请说明下平台，Android or IOS?
> 2、MIOTBluetooth.discoverServices was called with 2 arguments but expects 1 arguments，看这个错误是参数的问题，请使用最新的apk或ipa

感谢，是ipa问题，用了最新的就好了

**Comment by gaopingfly** [comment]
> IPA 更新下吧，这边最新的ipa本地MIOTBluetooth.discoverServices是两个参数的，可能很久以前的版本是一个参数的

感谢，用了最新的ipa就好了
