### ISSUE TITLE
导航栏react-navigation的切换期间显示文字 ‘ 菜单’

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#316]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS 11.0]
- 相关模块:[react-navigation]

#### 现象

使用自定义TitleBarBlack，在前进到下一个页面时左上角的返回按钮会跳变成 ‘菜单’  ，只有ios上会出现。
#154 也提到了这个问题。
#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

![img_0021](https://user-images.githubusercontent.com/5188922/53216153-a7347680-368e-11e9-8584-3435f578dcbb.PNG)
![img_0022](https://user-images.githubusercontent.com/5188922/53216159-aa2f6700-368e-11e9-93c3-30e891bd1a07.PNG)
如图是慢速播放的截图效果

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by LiuMengzhou** [comment]
你这是设置页面，检查一下设置页面的代码，是否有「菜单」的文案。

**Comment by mirse** [comment]
你好，并没有看到有菜单的文案，
`  static navigationOptions = ({ navigation }) => {
        nav=navigation
        return {
            header:
                null
        };
    };`
只有把 header 设置为null时，在下面render 添加TitleBarBlack，才会出现这种情况，

**Comment by mirse** [comment]
![_20190307141126](https://user-images.githubusercontent.com/5188922/53935726-6bfc6380-40e2-11e9-9ba8-ed8b84dcf091.jpg)
还会有一个返回的图标跟‘菜单’

**Comment by mirse** [comment]
’菜单‘文字是我这边出现的问题，但是蓝色返回图标还是存在

**Comment by LiuMengzhou** [comment]
> ’菜单‘文字是我这边出现的问题，但是蓝色返回图标还是存在

@mirse 分支10001 和 分支10002
