### ISSUE TITLE
IBluetooth接口里的UUID（蓝牙设备的 UUID）为null

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#317]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS
- 相关模块:[eg.Host/Service/Account]Bluetooth

#### 现象

这个接口现在拿不到数据。提个迂回的建议，我查看日志可以看到在iOS端bluetoothConnectionStatusChanged的监听小米的log能看到identifier，但是我们拿到的监听只有isConnect，希望在这个监听里把identifier也返回给我们。

这个字段对我们来说比较重要，举例：当前手机同时和多个蓝牙设备保持长连接，通过retrievePeripheralsWithServicesForIOS就会拿到多个identifier，我们需要知道哪个identifier是当前设备的，我之前的做法是本地存储一个key-value，保存mac地址和identifier的对应关系，所以需要拿到这个identifier。

#### 期望

可以获取当前设备的identifier

**Comment by blockdate** [comment]
bluetoothConnectionStatusChanged这个通知只跟当前插件的设备有关，直接使用ble.UUID是否满足你的需求

**Comment by zaxayn** [comment]
可以满足需求，但这个值我这边打印为null，你那里可以看到这个值吗

**Comment by blockdate** [comment]
这个值在bluetoothDeviceDiscovered之后才会存在

**Comment by zaxayn** [comment]
如果它只能在bluetoothDeviceDiscovered之后才会存在，那就满足不了需求，我想直接获取当前插件的设备的UUID，bluetoothDeviceDiscovered根本不会被触发，应该是设备扫描才会触发。

另外发现在旧SDK上可以通过MHBluetoothLE.event.centralManager_didConnectPeripheral_error这个回调拿到UUID

**Comment by zaxayn** [comment]
设备长连接场景中，如果当前手机同时和多个蓝牙设备保持长连接，通过retrievePeripheralsWithServicesForIOS就会拿到多个identifier，我们怎么知道哪个identifier是当前设备的呢？

**Comment by zaxayn** [comment]
@blockdate

**Comment by blockdate** [comment]
1. 在iOS原生层面，当前插件设备的PeripheralUUID是只有在connect成功之后才会被确认的，在插件退出时我们并不会保存这个uuid，这个可能需要你自行保存一下。  
2. 在JS层面，当前设备的UUID只会在bluetoothDeviceDiscovered接收到设备通知，通知的设备mac与本设备匹配时，PeripheralUUID才会被确认。

对于你的情况，希望你能描述清楚使用场景，以及希望我们如何配合。

**Comment by zaxayn** [comment]
场景如下：
米家App现在是可以添加多块米家手表的，假如用户添加了两块手表，并且手表A和手表B都开启了长连接，然后我想连接手表B并进行读写，目前的连接方法是先调用retrievePeripheralsWithServicesForIOS，这时会拿到两个2个PeripheralUUID，我怎么确定哪个PeripheralUUID是手表B的呢？

因为处于长连接的手表必须知道PeripheralUUID，才能使用下面的方法连接
let bt = Bluetooth.createBluetoothLE(key);
bt.connect(3,{"peripheralID":XXXX});

**Comment by blockdate** [comment]
这个PeripheralUUID只有你在第一次连接的时候做一次缓存了，目前没有提供该类长连接的解决方案。

**Comment by zaxayn** [comment]
在旧SDK上，在手表连接成功的回调里[centralManager_didConnectPeripheral_error](https://github.com/MiEcosystem/ios-rn-sdk/blob/9cfad29a2c1205217180e6054b8247e7e2773c7b/MiHomePluginSDK/docs/MHBluetoothLE.md#eventcentralmanager_didconnectperipheral_error)可以拿到PeripheralUUID，你们可以看下和第一次连接做缓存哪种方便一点，我们也曾向米家建议过同一用户不能添加多块手表，不过后来没有回音了

**Comment by blockdate** [comment]
更新ipa到124版本，同时更新SDK。我在bluetoothConnectionStatusChanged 增加了外设uuid的通知和设置

**Comment by zaxayn** [comment]
我测试了几次，连接成功的时候插件接收不到这个
bluetoothConnectionStatusChanged监听，看日志连接成功的时候米家是有的
![image](https://user-images.githubusercontent.com/11364809/53537557-55d02f80-3b45-11e9-8c21-fb429c016220.png)

**Comment by blockdate** [comment]
你可以输出一下当前ble对象的mac吗，对比一下Bluetooth bluetoothConnectinStatusChanged 后方输出的mac地址。看日志是native发送了通知，但是被js层拦截了。

**Comment by zaxayn** [comment]
看了一下，是同一个
![image](https://user-images.githubusercontent.com/11364809/53539049-f70db480-3b4a-11e9-852b-05a6371ee474.png)

**Comment by zaxayn** [comment]
这个问题好解决吗

**Comment by zaxayn** [comment]
@blockdate 这周有可能解决么？

**Comment by blockdate** [comment]
这边排查了下问题，应该是你的ble.isConnected状态在接收到bluetoothConnectionStatusChanged时的状态已经是true或者false，导致js端处理成不继续下发通知，这个是因为你调用connect成功的时候isConnected会被置为true，所以这边不会继续有bluetoothConnectionStatusChanged的状态通知。我这边会调整在connect的时候返回peripheralUUID，这个需要APP以及SDK的更新，预计明天可用。
  预计使用方式为在connect之后直接使用ble.UUID即可，支持的SDKLevel为10001。

**Comment by zaxayn** [comment]
收到，感谢

**Comment by blockdate** [comment]
更新IPA包至最新的128，在connect成功之后的promise返回值中可以获取外设的uuid

**Comment by zaxayn** [comment]
可以看到，谢谢
![image](https://user-images.githubusercontent.com/11364809/53789733-1ac46680-3f60-11e9-8721-03001482d92e.png)

**Comment by kasparovfeng** [comment]
@zaxayn 你好，你这个可以发现到服务吗

**Comment by zaxayn** [comment]
> @zaxayn 你好，你这个可以发现到服务吗

可以的

**Comment by edwardair** [comment]
connect()之后可以拿到UUID，但是有个问题，设备第一次添加进入插件时，并不会走connect，那第一次进入插件就拿不到UUID了？有没有开放其他接口拿去这个UUID？最好是直接给BluetoothLE开放这个API
@blockdate
