### ISSUE TITLE
miot-sdk/Pachage.js 导入错误

### ISSUE THREAD

**Issue by weimanleung** [MiEcosystem/miot-plugin-sdk#318]
miot-plugin-sdk/miot-sdk/Package.js  第三十三行 
import resolveAssetResource from "./native/common/node/resolve"; 
没有 “./native/common/node/resolve”的文件路径。

**Comment by lvjie0519** [comment]
import sdk相关的api，不是这样import的，请参考我们提供的demo，例如com.xiaomi.demo
