### ISSUE TITLE
新版蓝牙ble与远程安卓ble连接，能连接，发现不了服务service

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#320]
before issue：（不用回答）
### 是否尝试搜索issue？搜过了
苹果手机 真机调试
<img width="545" alt="8c6a4f17-e8ce-40c4-887f-9e8c1138e9d9" src="https://user-images.githubusercontent.com/38349220/53280905-efb96600-375a-11e9-9815-e1d4caede84d.png">

**Comment by liuhaixu666** [comment]
打卡

**Comment by liuhaixu666** [comment]
求大佬关照

**Comment by liuhaixu666** [comment]
感谢感谢

**Comment by blockdate** [comment]
1. Devcie.getBluetootLE() 用于获取自身小米协议设备，连接时不用重新指定uuid。
2. 指定uuidconnect时，表示普通蓝牙设备，需要自行手动创建CreateBluetootLE或者classic，否则通知会被屏蔽。
