### ISSUE TITLE
Android MoreDialog 非常难隐藏和非常难打开

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#321]
我移植了项目demo的 moreDialog 打开和关闭都非常麻烦，需要多次点击才能显示出来或者关闭

**Comment by lvjie0519** [comment]
MoreDialog 是我们自行提供的一个demo，您可以自行修改，可以自己实现一个类似的MoreDialog，谢谢！

**Comment by kfjihailong** [comment]
咱们可以提供提供一个高效率的MoreDialog吗？既然都提供了demo了。那么这个demo不是标准吗？

**Comment by lvjie0519** [comment]
> 咱们可以提供提供一个高效率的MoreDialog吗？既然都提供了demo了。那么这个demo不是标准吗？

Demo只是一种参考，对SDK 中 API的使用提供示例，Demo中提供的UI只是参考，第三方可以根据自己的需求修改的，如果调用的是SDK提供的UI出现问题应当由我们这边修改，谢谢，希望能够帮到您。
