### ISSUE TITLE
我在Android MoreDialog 设置了一个参数 如果在下面被遮挡的界面获取更新的数据？

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#322]
componentWillUpdate 这个方法确实可以获取到，但是该方法，更新速度超级快，后台我关注了一下，比我写一个定时器刷新速度都快，这个样我感觉不太合理。请问什么更好的方法吗？

**Comment by lvjie0519** [comment]
看了下，按照Demo中提供的使用方式，通过navigation来设置header，MoreDialog向外部的Component传参确实不太容易，您可以尝试将navigation的header设置为null，将header中的view移至Component的render函数中，然后通过函数回调即可，希望可以帮到您。
