### ISSUE TITLE
BluetoothEvent.bluetoothDeviceDiscovered 通知Ios和Android返回的数据格式不一致

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#323]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
BluetoothEvent.bluetoothDeviceDiscovered.addListener((bluetoohData) => {
});
发现设备的通知返回的数据bluetoohData格式Ios跟Android不一致，

Ios 是：
<img width="592" alt="image" src="https://user-images.githubusercontent.com/7885251/53313923-a140ce80-38f6-11e9-9983-1657ad6d43b6.png">

Android 是：
<img width="884" alt="image" src="https://user-images.githubusercontent.com/7885251/53313643-507ca600-38f5-11e9-9c80-621968c1b760.png">

#### 期望

Android能否像Ios一样，直接返回搜索到的原数据，不做处理，因为我们插件用到了 kCBAdvDataServiceData 和 kCBAdvDataManufacturerData 里面的数据

**Comment by dingshaoran** [comment]
kCBAdvDataServiceData 和 kCBAdvDataManufacturerData 数据具体是什么含义，android 目前没有这样的数据，android 现在你截图里的就是最原始的数据了。
现在哪里不能满足需求，可以说说你们的实现方式

**Comment by JxXiaoXie** [comment]
好，是原始数据就行。我看我需要的东西都在scanRecord字段里。
