### ISSUE TITLE
自定义自动化配置

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#325]
#### 环境
- 电脑操作系统: Mac
- 手机系统: iOS

#### 现象
旧版 config.list 已废弃，自定义自动化相关的 customSceneTriggerIds 和 customSceneActionIds 应该怎么配置？目前开发下能进入自定义自动化页面，打包到线上测试进入不了。

**Comment by blockdate** [comment]
这个现在不需要自行配置了，这边希望可以将设备分享到894158105账号下，我们这边尝试复现问题

**Comment by halloaw** [comment]
@blockdate 已分享。
最新 iOS IPA 开发模式下直接就闪退了，自定义场景id 573。

**Comment by blockdate** [comment]
自动化相关建议更新测试app至最新，使用SDK 10010。

参考 #647 #542
