### ISSUE TITLE
Device.getBluetoothLE().securityLock.toggle()成功后无返回值

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#326]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

我们是锁类设备，开门成功后，锁会返回一些数据，这些数据我们用到了，新插件页开门成功后无任何返回值。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
toggle() 返回的是一个Promise类型，请使用Device.getBluetoothLE().securityLock.toggle().then  这种方式来获取返回值。

**Comment by ldezho** [comment]
@lvjie0519 没有任何返回值
![image](https://user-images.githubusercontent.com/12531667/53328734-981b2600-3925-11e9-8b1b-3eb66b6e1900.png)
这个写法没问题吧？

**Comment by lvjie0519** [comment]
@ldezho 用法没问题。
1、没有任何的回调吗？无论成功与错误；
2、具体是哪个平台？Android或IOS，是Android麻烦看下logcat的输出日志；

**Comment by ldezho** [comment]
@lvjie0519 不是没有回调，是回调里面没有返回数据。比如旧版本开锁成功后会返回一些数据供判断当前锁是否是双重验证等。

**Comment by lvjie0519** [comment]
> @lvjie0519 不是没有回调，是回调里面没有返回数据。比如旧版本开锁成功后会返回一些数据供判断当前锁是否是双重验证等。

已修复，请更新下sdk。

**Comment by ldezho** [comment]
@lvjie0519 多谢，可以了。
