### ISSUE TITLE
Service.smarthome.getDeviceData, 现在返回的最大限制是多少，原来1000 正好够用，现在好像不行了

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#327]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 这个是直接使用的服务端接口，你的之前是指什么时间点以前。
2. 你的使用方式以及具体的预期是什么。

**Comment by Android-yzhang** [comment]
之前指的旧版插件MHPluginSDK.callSmartHomeAPI('/user/get_user_device_data'）这个方法，我们的插件需要取一个月的数据，大约800条，如果要分批取的话，可能会造成用户长时间的等待，可不可以想之前一样，最大值设置为1000

**Comment by blockdate** [comment]
这个我们这边并没有做限制，以前可以使用，现在也是可用的，要不你提供下新旧插件的具体使用参数，并且分享可获取数据的设备到894158105的账号下，我们这边看下问题出在哪。

**Comment by blockdate** [comment]
不活跃
