### ISSUE TITLE
没有发现获取智能列表的接口

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#328]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
你好，之前老版SDK可以通过米家app插件获取到 米家app创建的智能列表的list，老版的代码截图如下
![image](https://user-images.githubusercontent.com/13309478/53405332-953a3700-39f2-11e9-9384-ac5fdfdba610.png)

#### 期望

简单明了地描述一下期望的表现。

希望新版SDK添加

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by kasparovfeng** [comment]
里面的字段大概是这个样子的
var dataArr = new Array();
            for (var i= 0; i < result.length; i ++) {
                var originData = result[i];
                // name
                var name = originData.name;
                // enable
                var enable = originData.enable;

                // launchList
                var launchList = originData.launchList;

                // launchName
                var launchName = launchList[0].name;
                // objectValue
                var objectValue = launchList[0].value;
                // objectID
                var keyString = launchList[0].key;
                var keyStringArr = keyString.split('.');

                var objectID = keyStringArr[keyStringArr.length - 1];

                // hmEventType
                var hmEventType = this._getHmEventType(objectValue);

**Comment by kasparovfeng** [comment]
名字，开关的状态，以及lanchList ,lanchList里面有name value id 等

**Comment by kasparovfeng** [comment]
谢谢

**Comment by blockdate** [comment]
使用 Service.scene.loadScenes(Device.deviceID,SceneType.Automatic), 获取即可，返回的结构类型可能和之前不太一致，但是数据是一致的

**Comment by kasparovfeng** [comment]
获取好像是空的
![image](https://user-images.githubusercontent.com/13309478/53546869-778ede00-3b68-11e9-82db-f7502660a504.png)
![image](https://user-images.githubusercontent.com/13309478/53546948-a2793200-3b68-11e9-81cf-9c585f78c5d7.png)
麻烦帮忙看看

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53613746-0277e300-3c12-11e9-9c4b-87db484a68c1.png)
