### ISSUE TITLE
IOS长连接设备发现不了服务

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#329]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

通过长连接连接成功的
![image](https://user-images.githubusercontent.com/13309478/53462866-3d4a1180-3a80-11e9-91c1-124534d9c9ef.png)
![image](https://user-images.githubusercontent.com/13309478/53462886-4fc44b00-3a80-11e9-81c8-1440f47f83fd.png)

#### 期望
我看那个center manager 没有调取发现服务吧

简单明了地描述一下期望的表现。

期望可以发现服务

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by zaxayn** [comment]
#270

**Comment by blockdate** [comment]
从日志看，原生发送了service的发现通知，但是因为外设的id变化，导致通知被内部拦截了。
如果需要使用普通蓝牙设备或者外设id变化了的设备，需要自行创建一个新的蓝牙对象，否则该设备的一些蓝牙通知会被sdk认为是不相关的信息而屏蔽掉。

解决方法为使用 Bluetooth.createBluetoothLE(macOrPeripheralID)，获得该对象之后进行后续蓝牙操作。

如果以上方法尝试无效，请及时提问，最好也附带上日志。

-----------------
这是关联问题的解决方法，看你的日志，发现service是有通知的，最下面两行既是。采用同样的解决方法可解决

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53539450-9aab9480-3b4c-11e9-9b23-3f67be1787fc.png)

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53539463-a6975680-3b4c-11e9-98ef-8d317692ab74.png)

**Comment by kasparovfeng** [comment]
感觉不太对吧，都连接不上了

**Comment by kasparovfeng** [comment]
ios 连接成功了，有没有通知center manage 去发现服务啊 ，原生的要传 外设id  服务uuid 的 ，现在就startDiscoverServices(AmaziftWatchMiHomeServiceUUID)

**Comment by kasparovfeng** [comment]
你好，创建ble 设备 好像是undefined 吧

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53539973-a13b0b80-3b4e-11e9-8a07-9548806229ac.png)
我看连接的时候有center manager打印 发现服务的时候好像没有打印center manager 是不是没有调用原生的
