### ISSUE TITLE
旧SDK有提供一些通用图标，如返回按钮，新SDK有吗？

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#33]

**Comment by LiuMengzhou** [comment]
新的SDK不提供通用图标，在`TitleBarBlack.js`里面有返回按钮和更多按钮，你也可以修改`TitleBarBlack.js`满足需求。
[查看源码](https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/miot-sdk/ui/TitleBarBlack.js#L47)
