### ISSUE TITLE
更新完最新sdk后，跳转动画

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#330]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[Ui]

#### 现象

更新完当前最新的sdk和apk后，Android端在moreDialog选择跳转到下个页面的时候，使用sdk提供的接口与自定义跳转的动画效果不一样（自定义动画比较突兀），比如：Host.ui.openIftttAutoPage(); 和 this.props.navigation.navigate（自定义）
想知道下sdk中api的跳转动画逻辑以达到一致的效果。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@mirse  Android原生这边activity的跳转没有添加任何动画，都是Android默认的跳转动画。您在页面跳转的时候同时让moreDialog dismiss了吗？  如果是可以考虑让moreDialog 延迟500毫秒 dismiss ， 我刚才对比了下，跳转的同时dismiss  moreDialog ，RN确实会闪一下，感觉与性能有关。

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/53473880-9331b000-3aa6-11e9-9fdd-dec4bb0af865.png)

所有的跳转操作后都添加了如上逻辑操作，跳转现象还是存在的，今天更新了sdk出现了这个现象，以前没发现这个现象啊（或者说没有这么明显）

**Comment by lvjie0519** [comment]
@mirse 请更新下apk，使用最新apk再次测试下是否还存在此问题？谢谢。

**Comment by mirse** [comment]
> @mirse 请更新下apk，使用最新apk再次测试下是否还存在此问题？谢谢。

经测试，问题依旧存在

**Comment by lvjie0519** [comment]
@mirse   请添加微信（微信号：18750118631），详聊。

**Comment by lvjie0519** [comment]
@mirse   问题解决了吗？ 如果已解决，请说明一下解决方案，同时关闭下issue，谢谢。

**Comment by mirse** [comment]
由于统一通用设置样式，取消MoreDialoog，所以问题解决了
