### ISSUE TITLE
米家App闪退(ios平台)

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#331]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[ ？]

#### 现象
如#249 中提到了，ios闪退现象还是会出现
如图为xcode日志
![image](https://user-images.githubusercontent.com/5188922/53471678-74301f80-3aa0-11e9-9b2b-f35a78843664.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
对于crash问题，希望可以将设备共享给小米账号894158105。
同时在有mac电脑的情况下，连接手机到xcode，随后如下操作，将导出的crash日志以及使用的ipabuild编号通过邮件提供给我wulei7@xiaomi.com。以便于我解决问题。

导出crashlog如下：
![image](https://user-images.githubusercontent.com/4339364/53472123-c0c82a80-3aa1-11e9-9606-9b430295ccab.png)

**Comment by mirse** [comment]
crash日志找不着最新时间的文件，另外设备已共享过去, 昵称 Zh

**Comment by mirse** [comment]
在Android平台上会出现闪烁现象，在打开插件主页不做任何操作，过一段时间会突然闪到App主页一下，然后还是显示插件页面。（Android平台，小概率）

**Comment by blockdate** [comment]
这个插件目前还处于本地调试状态吧，这个可以的话希望能找到插件的crash日志，然后提供给我们，非常感谢

**Comment by mirse** [comment]
> 这个插件目前还处于本地调试状态吧，这个可以的话希望能找到插件的crash日志，然后提供给我们，非常感谢

好的，感谢，IOS端我在试试看。现在安卓端，小概率也会出现闪退，操作可能是放置在插件主页一段时间不操作或者点击返回按钮调用 Package.exit() 会直接退出整个App，很郁闷。

**Comment by mirse** [comment]
> 这个插件目前还处于本地调试状态吧，这个可以的话希望能找到插件的crash日志，然后提供给我们，非常感谢

日志已发送，请查收一下，谢谢了

**Comment by mirse** [comment]
经刚刚测试，打开你们那边的demo，进入到插件主页，放置一段时间后，也会出现闪退现象（整个app退出至桌面），还请你们那边排查一下。

**Comment by blockdate** [comment]
你好，根据你提供的crash日志，定位至RN的RCTInspectorPackagerConnection 的 socket连接的内存释放问题。我们会尝试解决这个问题
希望你能确认下问题
1.本地是否开启remoteDebug

**Comment by mirse** [comment]
> 你好，根据你提供的crash日志，定位至RN的RCTInspectorPackagerConnection 的 socket连接的内存释放问题。我们会尝试解决这个问题
> 希望你能确认下问题
> 1.本地是否开启remoteDebug

你好，本地并未开启remoteDebug

**Comment by blockdate** [comment]
问题已处理，该问题系RN内部的crash问题，该问题的PR已经合并至当前项目中，参考[RN 静置一段时间crash 初始Issue] 以及 (https://github.com/facebook/react-native/issues/6117) [RN 静置一段时间crash PR](https://github.com/facebook/react-native/pull/22439)

**Comment by mirse** [comment]
> 问题已处理，该问题系RN内部的crash问题，该问题的PR已经合并至当前项目中，参考[RN 静置一段时间crash 初始Issue](https://github.com/facebook/react-native/issues/6117) 以及 [RN 静置一段时间crash PR](https://github.com/facebook/react-native/pull/22439)

是否已经fix?更新最新sdk，apk还是复现crash

s

**Comment by blockdate** [comment]
更新ipa至目前的最新版本147，如果任然出现crash，请及时提供crash文件至邮箱wulei7@xiaomi.com，非常感谢。

**Comment by mirse** [comment]
> 更新ipa至目前的最新版本147，如果任然出现crash，请及时提供crash文件至邮箱[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)，非常感谢。

闪退现象还是存在，最新crash文件已发送过去
