### ISSUE TITLE
Device.isOwner疑问

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#332]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

状态为已上线的设备，添加成功后自动跳转到插件页后获取Device.isOwner为true，这个是正常的。
状态为开发中的设备，添加成功后自动跳转到插件页后获取Device.isOwner为false。（不应该为true吗？）退出插件页，再次进入插件页，获取Device.isOwner为true。只有在添加成功后自动跳转到插件页会出现这个问题。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、请说明一下平台？Android或IOS；
2、麻烦帮忙输出一下出现错误情况时的Device中permitLevel值为多少
方便问您排查，谢谢。

**Comment by ldezho** [comment]
@lvjie0519 
1、iOS
2、出现错误情况时的Device中permitLevel值为0
正常时值为16

**Comment by halloaw** [comment]
#238

**Comment by ldezho** [comment]
请问这个解决了吗？

**Comment by blockdate** [comment]
这个还在排查中

**Comment by blockdate** [comment]
这边方便提供下你们的设备么，我们这边测试了几个设备没有复现现该问题

**Comment by blockdate** [comment]
提供一下设备model，并且分享设备到小米账号894158105

**Comment by ldezho** [comment]
@blockdate 设备model：shjszn.lock.kx，已分享至小米账号：894158105

**Comment by ldezho** [comment]
请问怎么样了？

**Comment by blockdate** [comment]
@ldezho 邮件发送微信号到 wulei7@xiaomi.com，微信快速定位下问题吧。

**Comment by ldezho** [comment]
@blockdate 已发送到您的邮箱。

**Comment by ldezho** [comment]
感谢帮助，已解决。
