### ISSUE TITLE
扩展程序，访问自由功能时，出现timeout异常

### ISSUE THREAD

**Issue by MarsHuangPing** [MiEcosystem/miot-plugin-sdk#333]
使用Device.getDeviceWifi().loadProperties方法，出现timeout异常，详情请查看图片：
<img width="675" alt="screen shot 2019-02-27 at 11 49 38 pm" src="https://user-images.githubusercontent.com/38786331/53503314-c72ec480-3aea-11e9-9228-0f183d226aa5.jpeg">

代码：
<img width="458" alt="screen shot 2019-02-27 at 11 46 34 pm" src="https://user-images.githubusercontent.com/38786331/53503311-c5650100-3aea-11e9-854b-83e275edbb3d.png">

设备功能定义：
<img width="675" alt="screen shot 2019-02-27 at 11 49 38 pm" src="https://user-images.githubusercontent.com/38786331/53503313-c6962e00-3aea-11e9-86e2-9923b1eb40a6.png">

**Comment by blockdate** [comment]
这个确认下设备在线状态，这个不是app以及SDK的使用问题，而是设备的连通性问题

**Comment by MarsHuangPing** [comment]
> 这个确认下设备在线状态，这个不是app以及SDK的使用问题，而是设备的连通性问题

多谢您的回复，您的意思是设备没有真正连接到小米的Iot平台吗？
但是，我在扩展程序中，使用 iDevice.isOnline : boolean 方法，返回来true。
接下来，我应该怎么办？

**Comment by MarsHuangPing** [comment]
@lvjie0519 请看上面的我的追问，多谢！

**Comment by MarsHuangPing** [comment]
@lvjie0519 
我使用方法：batchGetDeviceProps 
代码：
<img width="548" alt="screen shot 2019-03-03 at 12 11 09 pm" src="https://user-images.githubusercontent.com/38786331/53690878-cda09300-3dad-11e9-8188-54c874560d55.png">
log时，co2返回null：
<img width="672" alt="screen shot 2019-03-03 at 12 11 01 pm" src="https://user-images.githubusercontent.com/38786331/53690877-cd07fc80-3dad-11e9-9452-624abf8028fe.png">

使用loadPropertiesFromCloud方法：
代码：
<img width="617" alt="screen shot 2019-03-03 at 12 10 33 pm" src="https://user-images.githubusercontent.com/38786331/53690886-ee68e880-3dad-11e9-9c7f-31a77e2da862.png">
log时，抛异常
<img width="886" alt="screen shot 2019-03-03 at 12 10 44 pm" src="https://user-images.githubusercontent.com/38786331/53690887-ef017f00-3dad-11e9-87c3-9045dede9487.png">

可以帮助看一下吗？

**Comment by lvjie0519** [comment]
@blockdate  这应该是ios平台，帮忙看看

**Comment by MarsHuangPing** [comment]
@blockdate @lvjie0519 谢谢各位，问题已经解决
