### ISSUE TITLE
如何获取设置的云定时功能列表？

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#334]
我现在通过小米提供的SDK，来开发扩展应用程序。（https://github.com/MiEcosystem/miot-plugin-sdk.git）
我现在通过SDK的接口设置云定时功能（ Host.ui.openTimerSettingPageWithVariousTypeParams）
我现在想通过接口获取到设置的云定时数据列表。但是我并没有发现相关的API接口。
（https://iot.mi.com/new/guide.html?file=05-米家扩展程序开发指南/01-新扩展程序开发指南/15-系统服务_场景模块。）

**Comment by blockdate** [comment]
使用 `Service.scene.loadScenes(Device.deviceID, SceneType.Timer) `应该可以满足你的需求
