### ISSUE TITLE
error: bundling failed: Error: ENOENT: no such file or directory, lstat '~/miot-sdk/native'

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#335]
error: bundling failed: Error: ENOENT: no such file or directory, lstat '~/miot-sdk/native'

**Comment by RideShi** [comment]
Error: Unable to resolve module `.././native` from `~~~~/miot-sdk/ui/LoadingDialog.js`

**Comment by blockdate** [comment]
你这是本地CodeIDE报的错误，还是开启调试的时候报的RN错误。
如果是IDE的错误，可以忽略，并不影响使用

**Comment by RideShi** [comment]
开启调试的时候报的RN错误，现在没出现了

**Comment by CeresY** [comment]
请问你解决了吗，我也遇到了这个问题
