### ISSUE TITLE
米家进入插件，会显示白屏

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#336]
---

#### 环境

- 手机系统:[Android /iOS ]

#### 现象

从APP设备列表界面，进入插件界面，页面刷新较慢，中间会有白色页面跳转，白屏几秒，特别是在吸顶灯离线后，安卓手机进入插件会一直白屏（安卓还有时会一直出现必须杀进程才好；iOS会好一些，白屏时间短）

#### 期望

能够正常进入插件页面

**Comment by blockdate** [comment]
白屏过程主要是是加载RN js代码的过程
1. 提供下你使用的app版本，线上版本或是测试版本（提供下构建编号）
2. 是否开启了remote debug

**Comment by xuanxuandaoren** [comment]
小米 mix3米家版本  5.4.57 release 80  版本 下载地址。https://pan.mioffice.cn/#/link/3F05647BD4EDAA101A96EE9ADD3F4455

**Comment by lvjie0519** [comment]
> 小米 mix3米家版本  5.4.57 release 80  版本 下载地址。https://pan.mioffice.cn/#/link/3F05647BD4EDAA101A96EE9ADD3F4455

1、请问一下，RN插件开发选择的apk，这个下载地址是谁知照您的哈？
2、RN插件开发选择的apk就在git库中，目前最新的是SmartHome_debug_2_26.apk 
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/SmartHome_debug_2_26.apk

**Comment by lxq93** [comment]
您好，我们目前的测试版本是线上的，也会有问题。Android是5.4.61，iOS是V4.13.101

**Comment by blockdate** [comment]
你们本地调试是进入的旧插件框架测试还是新框架插件测试，iOS目前线上版本在debug旧插件框架时会有一些问题，我们在下一版会修复。
但是新插件框架并没有这个问题，如果新插件框架测试任然有问题，可以尝试本项目主页readme中提供的测试版ipa下载地址，希望及时向我们反馈。

**Comment by lxq93** [comment]
我们是在线上版本是支持新框架RN的APP上验证的，安卓和iOS额白屏问题统一发邮件给wulei的邮件了，可以复现。晚些时候我们再下载新版APP验证一下啊

**Comment by blockdate** [comment]
如果可以复现的话，将设备分享到小米账号894158105，这边我们看看问题是否属于正常现象

**Comment by blockdate** [comment]
方便的话同步下验证结果

**Comment by xuanxuandaoren** [comment]
目前仍然存在 存在，已分享 灯

**Comment by blockdate** [comment]
本地测试并未复现白屏问题。（最新测试版159，APPStore版），是否有更具体的问题复现流程。

**Comment by lxq93** [comment]
已将视频发到wulei7@xiaomi.com的邮箱，请知悉，用安卓的debug5.5.3版本，点击进入插件即可出现

**Comment by lxq93** [comment]
已将卧室吸顶灯分享给你的这个小米账号894158105

**Comment by blockdate** [comment]
更新app后如还有问题，在下方回复，暂时关闭issue
