### ISSUE TITLE
定时开关灯功能无效（Android MI 6X），（IOS正常）

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#337]
#### 现象

定时开关灯功能无效（Android MI 6X），所有Android 都无效，（IOS正常）
#### 期望

定时开关在Android上也能正常工作

**Comment by lvjie0519** [comment]
@xuanxuandaoren 请说明详细一点并截图看看你的关键部分代码，我这边方便排查。

**Comment by mirse** [comment]
同遇到此问题（Android上定时关闭失败，ios正常），调用的方法为Host.ui.openTimerSettingPageWithVariousTypeParams

**Comment by lvjie0519** [comment]
@mirse  截个图，看下您具体参数格式

**Comment by mirse** [comment]
> @mirse 截个图，看下您具体参数格式

![image](https://user-images.githubusercontent.com/5188922/53707637-c12e4000-3e6a-11e9-9a9d-26a4c03d1e6b.png)

**Comment by mirse** [comment]
> @mirse 截个图，看下您具体参数格式

请问解决了吗，怎么解决的？

**Comment by laohuang88** [comment]
更新sdk, 已解决
