### ISSUE TITLE
已将设备修改名称，但是点击重命名后输入框仍旧显示默认设备名

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#338]
#### 环境

- 手机系统:[Android ]

#### 现象

调用重命名界面，修改设备名称，成功之后再次调用重命名界面 ，显示的是之前的设备名称

#### 期望

名称能实现同步

**Comment by lvjie0519** [comment]
@xuanxuandaoren
