### ISSUE TITLE
手动重置设备端，app能否收到重置通知

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#339]
#### 现象

由于app存有设备的信息，手动重置设备后再次重新连接 ，还能显示设备以前的信息

#### 期望

当设备重置时收到回调，我们在app 端清除数据

**Comment by blockdate** [comment]
APP应该是不会存储设备的信息的。能举一个详细点的例子，例如是设备的名称还是某些状态之类的，以及你的预期。

**Comment by xuanxuandaoren** [comment]
#### 现象
以灯为例 ，
灯的重置亮度为100，
用户连接后，把亮度调到46 ，然后手动重置灯，灯的亮度恢复为100，
再连接灯然后进入，app先从缓存中获取信息，灯的亮度显示是46，但实际是100，

举例只是说明，灯里还有很多其他设置保存在本地中 灯，比如是否是第一次登陆
#### 预期

当人工重置灯时，app收到回调，然后删除本地的信息

**Comment by blockdate** [comment]
1. 如果手机做了缓存，那么进入插件，缓存属性和读取到的实际属性存在差异是正常的。
2. 设备属性重置时，相关的属性是否会上报并触发属性变化通知，插件端注册属性监听后可以解决在插件页面停留时的设备重置事件，然后更新属性。但是任然无法解决插件外重置属性。

建议是从缓存读取属性后，任然会进行实际属性读取，以及属性的订阅。

**Comment by xuanxuandaoren** [comment]
但是判断设备是否是第一次使用是存在缓存里的，这涉及到是否弹隐私协议和插件使用引导，这个影响还是很大的。

**Comment by blockdate** [comment]
设备是否使用的隐私协议等应该只和使用者关联，这个和设备是否重置没有关系。
