### ISSUE TITLE
国际化语言问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#34]
本地化字符串
const Basic = res.createI18n({
	en:{
		//英文
    tip_bluetoothNotOpen: "Bluetooth is off",
    tip_networkError: "Check your network connection and try again",
		alert_title_attention: "Attention",
	},
	zh:{
		//简体中文
		tip_bluetoothNotOpen: "蓝牙未打开",
		tip_networkError: "网络异常，请检查网络后重试",
		alert_title_attention: "提醒",
	},
});

然后我米家APP语言设置为简体中文，执行代码
console.log("测试语言显示：" + Basic.strings.tip_bluetoothNotOpen);

还是输出的英文字符。帮我看一下，是不是我哪里写错了？

**Comment by JxXiaoXie** [comment]
iOS上

**Comment by dingshaoran** [comment]
您使用的res.createI18n 不是米家标准的国际化 api，请参考 demo 中 LocalizedStrings.js 和MHLocalizableString.js。如果想直接获取语言 Host.locale.language 会返回 zh,zh_tw,zh_hk,zh_bo,en,es,ko,ru,it,fr,de,id,pl,vi,ja,th,ar 这几种语言

**Comment by JxXiaoXie** [comment]
好了
