### ISSUE TITLE
小卡片色温不能同步

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#340]
#### 环境

- 手机系统:[Android]

#### 现象

保持小卡片调节页不动，使用另一手机调节色温，小卡片中的色温一直不能同步，需要退出小卡片再点击进入小卡片才能同步

#### 期望

色温也能同步

**Comment by blockdate** [comment]
是进入插件内的问题还是首页宫格模式的设备打开的小卡片问题

**Comment by xuanxuandaoren** [comment]
是首页宫格模式的设备打开的小卡片问题

**Comment by wongzy** [comment]
您好，卡片是这样拉取数据的：1.打开卡片会主动拉取服务器数据 2.当设备属性发生变化时卡片订阅服务会再次拉取数据更新卡片。您的情况属于第二种，但是第二种情况发生延迟的可能性比较大，现在的情况是属于正常的。

**Comment by lxq93** [comment]
您好，您是说当设备属性发生变化是小卡片会自动再拉取数据才是正常的对吗？我们确实实际情况下停在当前界面很久都不会拉取，但是退出小卡片再进去就能拉取，可以再帮忙看看吗，多谢啦

**Comment by blockdate** [comment]
卡片目前已不属于统一插件框架内容，close
