### ISSUE TITLE
ios 发现不了服务，已用关联问题方案，但是没有解决

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#341]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
mac  iphoneXR

#### 现象

通过retrive到列表后创建bledevice , 连接提示设置不存在，有的时候是存在的但是也发现不了服务
![image](https://user-images.githubusercontent.com/13309478/53613420-f8a1b000-3c10-11e9-8789-f0e10e032cd4.png)

![image](https://user-images.githubusercontent.com/13309478/53613380-e45db300-3c10-11e9-9c7e-43a4cad0c10a.png)

**Comment by kasparovfeng** [comment]
@kyou @kangkai @zxconan @Copypeng 各位大佬，你们好，什么情况了啊

**Comment by blockdate** [comment]
这个绝大多是情况是属于设备蓝牙为断开导致，检查下你connect的时候，设备蓝牙的连接状态

**Comment by kasparovfeng** [comment]
各位大佬，我是retivive到设备了，已经拿到设备，然后还让我去创建，我ios蓝牙页面是连接的啊，4581这个设备，原生oc里面都是centermanger操作的，现在是设备在操作，到底怎么解决，都快崩溃了啊 @kyou @kangkai @zxconan @blockdate @kyou 大佬帮忙看看，各位大爷
![image](https://user-images.githubusercontent.com/13309478/54350445-5067fe80-4688-11e9-9d99-ef5314206e7c.png)

**Comment by blockdate** [comment]
device not found 这个错误是在连接小米协议设备的时候才会返回的。方便提供下对应的操作地方的代码吗，以及更加完善一点的日志。

如果比较紧急，把微信号发送到wulei7@xiaomi.com, 我们这边用微信沟通下

**Comment by blockdate** [comment]
已解决，连接普通蓝牙时，需要手动创建蓝牙对象，否则相关通知(服务发现，特征发现等)会被拦截
