### ISSUE TITLE
拉取智能列表失败

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#342]
![image](https://user-images.githubusercontent.com/13309478/53613688-d5c3cb80-3c11-11e9-8093-031e74f52b85.png)

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53613757-0b68b480-3c12-11e9-9d9c-3222d5ff894f.png)

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/53613781-1d4a5780-3c12-11e9-9aa6-92fc168f6e68.png)

**Comment by lvjie0519** [comment]
@kasparovfeng 数据返回成功，我们将数据包装在IScene对象里面，这有什么问题吗？
