### ISSUE TITLE
能否提供手机是否是全面屏的方法.

### ISSUE THREAD

**Issue by Mmpc1994** [MiEcosystem/miot-plugin-sdk#343]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
已经搜过提供的方法, 没有找到对应解决方案, 因为是否是全面屏对布局影响很大.

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by dingshaoran** [comment]
目前 android 系统 api 没有这个方法，如果想判断全面屏，请通过机型匹配解决Host.systemInfo.mobileModel

**Comment by dingshaoran** [comment]
您布局适配最好通过 window.width/window.height的比例处理。全面屏手机对通知栏的处理参照 demo，通过 StatusBar 可以完成适配
