### ISSUE TITLE
Android蓝牙连接一直返回REQUEST_ONGOING(蓝牙已断开情况下)

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#344]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android 7.0
- 相关模块:Bluetooth

#### 现象

Android：蓝牙连接 Device.getBluetoothLE().connect();
如果在回调返回之前点击左上角Reload插件（或者退出插件），下一次调用蓝牙连接就会一直返回错误信息{msg: "REQUEST_ONGOING", code: -13}，但此时蓝牙已确定是断开了（设备断电）。

在持续3分钟不等的时间后回复正常

#### 期望

希望对异常情况的处理容错性能高一点

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@zhaolios 退出插件的时候是否调用了ble.disconnect()？

**Comment by zhaolios** [comment]
> @zhaolios 退出插件的时候是否调用了ble.disconnect()？
调用和不调用 ble.disconnect() ，都会REQEUST_ONGOING

**Comment by lvjie0519** [comment]
@zhaolios 先暂时关闭，之后还有问题，再重新打开issue。
