### ISSUE TITLE
能否提供可获取手机信息的API

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#345]
#### 现象

有些特殊机型对RN的事件响应或者View绘制方面表现和其他机型不一致。
例如 华为p9 下面有黑色导航条。
三星s7 View滑动事件会抢走覆盖在上面`TouchableOpacity`的点击事件，我们需要获取特定机型进行适配

#### 期望

能获取手机的型号

**Comment by lvjie0519** [comment]
Host.systemInfo，  打印一下这里面的信息，应该满足您的需要。

**Comment by xuanxuandaoren** [comment]
好的 谢谢
