### ISSUE TITLE
插件运行失败bug

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#346]
不知道做了什么操作，好像不小心导入了什么包了，然后运行失败了
<img width="1297" alt="2019-03-02 6 05 02" src="https://user-images.githubusercontent.com/18459414/53680424-52d86900-3d16-11e9-8195-70c5ec1c404b.png">
<img width="1365" alt="2019-03-02 6 05 27" src="https://user-images.githubusercontent.com/18459414/53680425-52d86900-3d16-11e9-8995-f75b9a1914f8.png">
请问这个应该怎么处理，很急很关键。。。谢谢了。。。

**Comment by blockdate** [comment]
检查下你的插件路径配置是否正确，是不是错误启动了旧版本的插件，尝试重启node服务器。

**Comment by blockdate** [comment]
不活跃
