### ISSUE TITLE
快速点击返回键两次，虽然当前页面消失，但还会执行他的componentWillMount

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#347]
#### 环境

- 手机系统:[iOS]

#### 现象

IOS快速点击返回键两次，执行`navigation.goBack()` 当前页面消失，但又执行当前页面的componentWillMount和componentDidMount

**Comment by blockdate** [comment]
我本地尚未复现，会持续跟进

**Comment by santcool** [comment]
这个问题我这边也无法复现，鉴于此问题长时间未更新，先关闭了
