### ISSUE TITLE
日志分页拉取疑问

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#348]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android/iOS]
- 相关模块:[eg.Service]

#### 现象

没有找到支持日志分页拉取接口

#### 期望

希望增加分页拉取日志接口支持

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@qinliduan 麻烦告诉下您之前调用的是哪个接口？具体需要哪些参数，代码截个图，我们这边为您添加，谢谢。

**Comment by qinliduan** [comment]
> @qinliduan 麻烦告诉下您之前调用的是哪个接口？具体需要哪些参数，代码截个图，我们这边为您添加，谢谢。

我们用的接口是
api:/v2/user/getuserdevicedatatab
params:
did
key
type
timestamp
limit

**Comment by lvjie0519** [comment]
@qinliduan  已增加，sdk分支切换到SDK_10001,并更新。
Host.smarthome.getUserDeviceDataTab()

**Comment by qinliduan** [comment]
> @qinliduan 已增加，sdk分支切换到SDK_10001,并更新。
> Host.smarthome.getUserDeviceDataTab()

谢谢，是Service.smarthome.getUserDeviceDataTab()，已验证ok
