### ISSUE TITLE
iOS 开启“Debug JS Remotely”问题

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#35]
![1542160612400](https://user-images.githubusercontent.com/22782965/48455607-d2d5d400-e7f6-11e8-9882-53c9c731796d.jpg)
开启“Debug JS Remotely”调试，偶尔可以，但大部分都报上图问题。不知道怎么回事。

**Comment by LiuMengzhou** [comment]
@flingInTheSky 
很抱歉，这个问题确实存在，我们正在修复中。

你可以尝试以下步骤：
1. 摇动手机，关闭`debug js remotely`
2. 重新进入插件
3. 摇动手机，再次打开`debug js remotely`

**Comment by pencilCool** [comment]
这个是已知问题，安卓上没有这种问题，我们正在努力修复

**Comment by LiuMengzhou** [comment]
@flingInTheSky 插件远程调试问题已修复。请等待ipa更新。
