### ISSUE TITLE
安卓子元素布局超出父元素的区域会被裁剪

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#350]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[Android]

#### 现象

安卓子元素布局超出父元素的区域会被裁剪

#### 期望

子元素布局超出父元素的区域也能显示

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

[react native 相关issues]( https://github.com/facebook/react-native/issues/16951)

[react-native-view-overflow 插件](https://github.com/entria/react-native-view-overflow)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@qinliduan RN官方clipChildren默认为true，目测也没有提供相关属性进行设置。
请问您那边子布局超出父布局是出于什么场景？能否通过调整父布局大小来解决？

**Comment by qinliduan** [comment]
> @qinliduan RN官方clipChildren默认为true，目测也没有提供相关属性进行设置。
> 请问您那边子布局超出父布局是出于什么场景？能否通过调整父布局大小来解决或让父布局自适应？

目前遇到的场景没那么复杂，可以通过改变布局方式来解决。就是发现这个问题反馈一下，看sdk能否有一些好的解决方案

**Comment by lvjie0519** [comment]
嗯，好的，我们这边也可以通过react-native-view-overflow 的方式封装一套，但是意义可能不大，对于非必要条件下，建议还是通过调整布局来确保父布局适应子布局，谢谢~
