### ISSUE TITLE
新建一个项目，连接上硬件后报错

### ISSUE THREAD

**Issue by zcl997136048** [MiEcosystem/miot-plugin-sdk#351]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 8.1]

#### 现象

利用npm run create -- --models xxx.xxx.x1 xxx.yyy.zzz创建项目之后，连接上硬件报错。
报错内容是：Super expression must either be null or a funtion， not undefined

#### 期望

不报错，正常运行

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。
表现。
#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供下你的错误截图以及对应的错误代码和日志

**Comment by zcl997136048** [comment]
报错信息是Super expression must either be null or a funtion， not undefined
下面是index.js中的代码
    import React from 'react';
    import { API_LEVEL, Package, Device, Service, Host } from 'miot';
    import { PackageEvent, DeviceEvent } from 'miot';
    import { View, Text } from 'react-native';

    class App extends React.Component {
        render() {
            return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text>hello, this is a tiny plugin project of MIOT</Text>
            <Text>API_LEVEL:{API_LEVEL}</Text>
            <Text>NATIVE_API_LEVEL:{Host.apiLevel}</Text>
            <Text>{Package.packageName}</Text>
            <Text>models:{Package.models}</Text>
            </View>
            )
        }
    }
    Package.entry(App, () => {
        
    })

**Comment by blockdate** [comment]
本地并未复现你描述的问题，请检查下本地reactnative、node的版本，以及所使用的Android APP 的版本。

**Comment by lvjie0519** [comment]
@zcl997136048 请使用最新的apk

**Comment by blockdate** [comment]
不活跃
