### ISSUE TITLE
未上线锁类产品，android不能开锁

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#352]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

对于我们一款即将上线的锁类产品：
1、android不能开锁
     调用 Device.getBluetoothLE().securityLock.toggle(0).then.catch后，android会在catch中返回{msg: "REQUEST_FAILED", code: -1, result: null}

#### 期望

可以成功开锁

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@ldezho  Android Studio Logcat 使用关键字 miio-bluetooth 过滤下日志看看

**Comment by ldezho** [comment]
@lvjie0519 日志见miio-bluetooth.txt
[miio-bluetooth.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/2934143/miio-bluetooth.txt)

**Comment by lvjie0519** [comment]
@ldezho    请加微信，微信号：18750118631， 微信沟通下，谢谢。

**Comment by ldezho** [comment]
Device.getBluetoothLE().connect()  connect中 type参数为1可以，之前是-1。
