### ISSUE TITLE
网关设备，android上Device.lastVersion为空。

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#353]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

Android上Device.lastVersion为空，iOS有值。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@ldezho  已修复，请更新sdk.

**Comment by ldezho** [comment]
@lvjie0519 更新sdk后还是空的。

**Comment by lvjie0519** [comment]
> @lvjie0519 更新sdk后还是空的。

您sdk的代码是使用哪个分支的？  请使用10000分支

**Comment by ldezho** [comment]
@lvjie0519 不是用master吗？

**Comment by lvjie0519** [comment]
> @lvjie0519 不是用master吗？

第一版刚开始开发的时候都是在master分支，对于以后的版本，会创建新的分支，在新的分支做修改，发布对应分支的代码。

**Comment by ldezho** [comment]
@lvjie0519 好的，已经试过了，在SDK_10000分支是可以的。
