### ISSUE TITLE
插件能依赖NativeBase吗

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#354]
不知道native-base算不算纯js实现。

**Comment by lvjie0519** [comment]
@dan-huang 看它的官方文档，是否涉及到需要增加原生依赖的aar或需要增加原生的代码，如果需要就不是纯js实现，插件不能进行依赖，反之可以。

**Comment by dan-huang** [comment]
只要使用该库时，不需要引入原生代码或aar，就可以吗？

它本身依赖了其他三方库，其他三方库中有原生代码。但使用该库时，我的代码是纯js代码。 

@lvjie0519

**Comment by blockdate** [comment]
如果这个库本身或者其依赖库依赖了原生的代码引入等功能，都是不支持使用的
