### ISSUE TITLE
进入插件，报错

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#355]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
![image](https://user-images.githubusercontent.com/5188922/53723182-19ccff80-3ea2-11e9-871f-717c320b6d01.png)

IOS和Android 都报这个错误。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@mirse  您是运行我们提供的demo报错还是您们自己的project，请先尝试下运行我们提供的demo，是否会出现同样的错误?

**Comment by mirse** [comment]
运行的时你们提供的demo，下载完sdk后，运行npm install -> npm start，载入插件进度条到100%，就报上面那个错误。

**Comment by uSmile-Y** [comment]
一样遇到过类似问题

**Comment by blockdate** [comment]
看日志是HMR的问题，确认下你们是不是开启了hot loading（HMR）的功能，如果开启了，建议关闭，目前不支持这种使用方式
