### ISSUE TITLE
快捷方式进入插件再退出会crash

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#356]
before issue：（不用回答）

#### 环境

- 手机系统:[Android]

#### 现象

创建设备的桌面快捷方式后，打开米家APP，进入插件-->点击Home键將APP在后台运行-->点击桌面快捷方式进入插件-->退出插件，提示米家APP停止运行（小米5s与小米Max2)

#### 期望

不crash

#### 其他的上下文/日志/截图

![1](https://user-images.githubusercontent.com/18681867/53732152-f3b25a00-3eb7-11e9-8bcf-c7566c353121.png)

**Comment by uSmile-Y** [comment]
我也遇到了这个问题

**Comment by laohuang88** [comment]
修复的新版本将发布
