### ISSUE TITLE
InputDialog 设置placeholder在Android 不显示

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#357]
#### 环境
- 手机系统:[Android]

#### 现象

InputDialog 设置placeholder在Android 不显示

#### 期望

能在Android 也显示 

#### 其他的上下文/日志/截图

![1](https://user-images.githubusercontent.com/18681867/53732986-80f6ae00-3eba-11e9-97b1-72d74f113c93.png)

**Comment by lvjie0519** [comment]
@xuanxuandaoren  已修复，请等待apk更新。

**Comment by lxq93** [comment]
好的，多谢。请问预计是什么时候更新有啊？

**Comment by lvjie0519** [comment]
> 好的，多谢。请问预计是什么时候更新有啊？

通常不超过一个星期，看native层修改量，修改量大apk更新周期更短，请时常更新sdk，关注我们的git提交日志，谢谢。

**Comment by lxq93** [comment]
好的，多谢啦

**Comment by lvjie0519** [comment]
@xuanxuandaoren  新的apk以支持， 请更新下apk；
git 的 10001分支或https://fir.im/MiHomeForAndroid 下载。
