### ISSUE TITLE
MessageDialog ios 不设置取消文本，但是取消按钮还存在

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#358]
#### 环境
- 手机系统:[iOS]

#### 现象

MessageDialog ios 不设置取消文本，但是取消按钮还存在
![wechatimg1615](https://user-images.githubusercontent.com/18681867/53734893-45f77900-3ec0-11e9-97db-a44c9cc642f7.jpeg)

#### 期望

和Android 一样 

![wechatimg1616](https://user-images.githubusercontent.com/18681867/53734933-5c053980-3ec0-11e9-9216-cfb2662fb7bb.jpeg)

**Comment by blockdate** [comment]
这个问题在测试包中已修复，线上app会在下一版本修复

**Comment by liuhaixu666** [comment]
> 这个问题在测试包中已修复，线上app会在下一版本修复

我才下了一个最新的SDK。还是不行啊，ios还是有取消的位置啊

**Comment by liuhaixu666** [comment]
你现在好了吗？ ios没问题了吗
