### ISSUE TITLE
openPrivacyLicense函数中的result回调无效

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#359]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS]
- 相关模块:[Host/ui]

#### 现象

使用openPrivacyLicense函数打开license弹出后，点击同意后，result回调不会被调用(即result中的警告弹出不会打印)。

#### 期望

result回调会被调用。

#### 其他的上下文/日志/截图

Host.ui.openPrivacyLicense('软件许可及服务协议', licenseURL, '隐私协议', policyURL, (result) => {
            if (result === 'ok') {
              alert('同意授权');
            } else {
              alert('取消授权，默认退出插件');
            }
          });

**Comment by blockdate** [comment]
可能是我们的demo或者文档没有及时更新，使用方法如下为promise使用，不是callback
```
Host.ui. openPrivacyLicense("","","","").then(res => {
}).catch(err => {
})
```
