### ISSUE TITLE
关于不继续支持basePath的问题，怎么获取插件html等文件的URL？

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#36]
由于之前的几个插件的隐私条款，是把html文件内置在插件里的，涉及到海外版本。现在不支持basePath了，那么怎么获取到插件的html文件的URL呢？或者这不支持这种方式了？需要把html放到云端吗，海外版怎么处理？

**Comment by dingshaoran** [comment]
使用 require加载本地的资源，隐私条款可以直接传 require( ……) 或者 {uri:""}
