### ISSUE TITLE
英文模式下显示中文字符

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#360]
#### 环境
- 手机系统:[Android]

#### 现象

英文模式下第一次进入插件，插件中全部显示中文，点击隐私协议的取消键再进入，全部显示英文，再次点击取消进入又全部显示中文（50%的重现率）

**Comment by lvjie0519** [comment]
@xuanxuandaoren  使用最新的apk是否还存在此问题？

**Comment by blockdate** [comment]
无新回复
