### ISSUE TITLE
智能开关执行过后右边button 未置灰

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#361]
#### 环境
- 手机系统:[iOS]

#### 现象

添加定时的智能动作，if条件选为定时且重复选为执行一次，灯执行完成后，右边的Button键不会置灰，刷新后仍然保持开启的状态，没有变为关闭状态

**Comment by blockdate** [comment]
你是指右侧的switch开关状态，这个表示的智能开关状态，不表示智能是否还会执行的逻辑，不知道你的问题是否是这个意思。

**Comment by blockdate** [comment]
not a bug
