### ISSUE TITLE
来回切换界面时会有阴影

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#362]
#### 环境

- 手机系统:[iOS]
#### 现象

iOS机型
进入插件，点击右上角"..."-->点击"设备设置"进入设备设置界面，点击左上角返回按钮，反复来回操作，有时界面会有阴影出现（点击吸顶灯设置以及吸顶灯设置界面的自动调节色温等按钮，也会有此现象）

**Comment by lxq93** [comment]
您好，因为我们今天需要提测，所以麻烦帮确认看看是否可以优化，多谢啦

**Comment by blockdate** [comment]
如果可以希望能提供下对应操作的截图，我们确认下问题是否被成功复现

**Comment by lxq93** [comment]
我们有拍视频，方便给个邮件我们给你发视频吗，只要按这个操作一定可以复现：“点击右上角"..."-->点击"设备设置"进入设备设置界面，点击左上角返回按钮，反复来回操作”

**Comment by blockdate** [comment]
方便的话发送视频到wulei7@xiaomi.com

**Comment by santcool** [comment]
> 我们有拍视频，方便给个邮件我们给你发视频吗，只要按这个操作一定可以复现：“点击右上角"..."-->点击"设备设置"进入设备设置界面，点击左上角返回按钮，反复来回操作”

还有这个问题吗？
