### ISSUE TITLE
Android 手动添加设备，当多个设备存在时，无法选定指定设备

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#363]
#### 环境

- 手机系统:[Android]

#### 现象

1.重置多个客厅吸顶灯
2.打开米家APP-->点击米家APP主界面右上角"+"添加设备-->手动添加-->在"照明"栏选择"飞利浦智睿客厅吸顶灯"
3.勾选"已确认上述操作"，点击"下一步"
4.没有出现设备扫描界面，直接进入路由器选择界面，点击"下一步"后，APP随机在重置的多个吸顶灯中选择一个进行连接，无法选择指定的灯进行连接

**Comment by lvjie0519** [comment]
@xuanxuandaoren  目前设计如此，手动添加设备，先扫描到哪个设备就连接哪个。
