### ISSUE TITLE
APP下发中文名字问题

### ISSUE THREAD

**Issue by deny2010** [MiEcosystem/miot-plugin-sdk#364]
使用新架构开关解密程序，新增加中文名字下发到设备上，用后台调试功能发送是正常的。但是用APP编辑的中文名字下发就变成乱码了。请问你们汉字处理使用什么编码规则的。我APP要怎么处理这些汉字才能正确下发到设备。如下图所示：
后台下发的：
![image](https://user-images.githubusercontent.com/32917979/53777590-de2f4580-3f34-11e9-88a3-5f226e71beeb.png)
![image](https://user-images.githubusercontent.com/32917979/53777623-04ed7c00-3f35-11e9-8b63-70e32d4e5ab4.png)
APP下发的名称，设备接收的：
![image](https://user-images.githubusercontent.com/32917979/53777608-f0a97f00-3f34-11e9-826e-25443f643bce.png)

**Comment by blockdate** [comment]
提供下你的调用方式，我这边排查下

**Comment by blockdate** [comment]
确认为非新插件框架问题
