### ISSUE TITLE
iOS中，点击撤销隐私协议时会先回到通用设置页，再回到设备列表页,设备被删除成功

### ISSUE THREAD

**Issue by lxq93** [MiEcosystem/miot-plugin-sdk#365]
#### 环境
APP：iOS4.13.101

#### 现象
iOS中，点击撤销隐私协议时会先回到通用设置页，再回到设备列表页,设备被删除成功

#### 期望

直接退回到我的设备界面

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
建议在插件中监听packageAuthorizationCancel事件，随后直接exit插件即可

**Comment by lxq93** [comment]
设置监听后还是有这个问题

**Comment by xuanxuandaoren** [comment]
@blockdate  是的 ，就是撤销后直接跳到设备列表

**Comment by edwardair** [comment]
安卓 小米应用商店下载的米家APP V5.5.6，测试撤销隐私结果：
1、撤销后，设备退回到插件首页？而不是直接退出到米家首页？（iOS是直接退到米家首页，希望安卓也是如此）
2、撤销虽然提示成功，但是手动退到米家首页，这个设备并未真正删除
---------------------
3、（iOS、Android），当设备使用“添加到桌面”后，再撤销设备授权，成功后，通过桌面图标仍然可以进入这个设备，并且“我的设备”中重新显示这个设备，请问这种情况是否违反用户数据未真正清除的规则？

@blockdate
