### ISSUE TITLE
Device支持获取设备重置引导页Url

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#366]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Device]

#### 期望

希望Device能提供iOS原生中，MHDevice的获取设备重置引导页URL的方法如下图：

![image](https://user-images.githubusercontent.com/15864191/53785695-6113c880-3f54-11e9-929f-6abff54b2dd8.png)

用作开发网关子设备的快联页面

**Comment by blockdate** [comment]
参见SDK 10010 中 Device.loadRealDeviceConfig
