### ISSUE TITLE
根据model取得此model的设备默认名和设备iconURL

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#367]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg. Device]

#### 期望

1.拿到model值的时候，希望能通过model值取得 此model值的默认名，主要用于开发 网关设备的 可添加子设备列表
2.通过model值取得 Device 的iconURL ，目前这个属性 需要拿到 Device 对象，如能提供一个通过model构造Device 的方法也OK

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
参考 SDK 10010 Device.loadRealDeviceConfig
