### ISSUE TITLE
获取需要展示在快连入口的所有model列表接口

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#368]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 期望

希望能提供一个接口获取需要展示在快连入口的所有model列表，主要用于 开发 网关设备的 可添加子设备列表
iOS原生接口如下图：
![image](https://user-images.githubusercontent.com/15864191/53786514-e4ceb480-3f56-11e9-8ed8-610c4cecf19c.png)

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by zanetti4** [comment]
@santcool 请问这个接口已经加上了吗？

**Comment by Woody2016** [comment]
这个issue长时间无响应，先close
如果开发者还有问题，请去开发者平台提工单
