### ISSUE TITLE
IOS 蓝牙 ：”米家自定义特征值“ value变化，监听却不回调的问题

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#369]
用的最新的app

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:IOS 12
- 相关模块:Bluetooth

#### 现象

IOS上，例如：监听锁体状态特征值（米家自定义的特征值  uuid:00001002-0065.......），remote debug能看到有这个日志"didUpdateValueForCharacteristic "后面跟着的service 和 characteristic的确是属于锁体状态特征值，但是问题在于怎么都不走BluetoothEvent.bluetoothCharacteristicValueChanged 的监听回调。

这个问题仅限于米家自定义的特征值，所有我公司自定义的特征值的变化则正常，可以监听得到char value变化。

Android上没有这样的问题。

#### 期望

米家自定义特征值的变化也可以监听到。

#### 其他的上下文/日志/截图
特征值变化的问题日志：
![image](https://user-images.githubusercontent.com/13412744/53796116-667e0c80-3f6e-11e9-9634-7e56b090326c.png)

特征值变化的正常日志：
![image](https://user-images.githubusercontent.com/13412744/53796603-7b0ed480-3f6f-11e9-9ef2-9b141db908f7.png)

下方的日志的didUpdateValueForCharacteristic比上方日志多了两行关于特征值变化的日志。
下方截图中“特征值变化”的那行则是BluetoothEvent 回调打印的日志。

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这些特征值的属性属于锁类操作的特定值，因此会在底层被拦截，开锁与上报。
我们会与Android确认是否需要开放限制

**Comment by blockdate** [comment]
这边回复结果为不对外提供，建议使用对应的方法操作，不要自行操作这写内置的特征
