### ISSUE TITLE
获取手机系统相关API

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#37]
产品中会优先支持MIUI9以上的小米手机，需要判断当然手机的系统信息。在《MIOT SDK API》中并没有找到相关的API，希望提供支持。

**Comment by dingshaoran** [comment]
Host.systemInfo 中有mobileModel 和 sysName 应该能满足您的需求

**Comment by ftc300** [comment]
分别使用了两款手机调用 Host.systemInfo 测试结果如下：
{ hostApiLevel: 100, sysVersion: '8.1.0', mobileModel: 'MI 5X' }，
{ hostApiLevel: 100, sysVersion: '7.0', mobileModel: 'MI 5s' }，
或许能使用mobileModel来判断是否是小米手机，但是无法获取 MIUI 版本，原来插件来电提醒只支持MIUI9以上手机。@dingshaoran

**Comment by dingshaoran** [comment]
您原来的 java 插件都需要哪些系统信息，请提供一下java 代码可以一并加上。

**Comment by ftc300** [comment]
感谢您的回复。
参考的是开发文档 https://dev.mi.com/doc/?p=254
文档中有如下文字：

> 如何检测MIUI V5：
> 查询property: ro.miui.ui.version.name ，值是”V5″ 就是MIUI V5系统；值是”V6″就是MIUI 6系统。
> 

所以有如下检测 MIUI 版本大于9的方法，先获取 property，然后处理结果。核心获取方法如下：
```
    public static String getProp() {
        String line = null;
        BufferedReader input = null;
        try {
            Process p = Runtime.getRuntime().exec("getprop ro.miui.ui.version.name");
            input = new BufferedReader(new InputStreamReader(p.getInputStream()), 1024);
            line = input.readLine();
            input.close();
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        } finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return line;
    }
```

**Comment by dingshaoran** [comment]
在 systemInfo.miuiVersion可以读取到 V9

**Comment by dingshaoran** [comment]
更新 apk

**Comment by dingshaoran** [comment]
如果已经可以正常使用请 close issue

**Comment by ftc300** [comment]
感谢！
