### ISSUE TITLE
线上最新版Android端的定时开关无法执行

### ISSUE THREAD

**Issue by lxq93** [MiEcosystem/miot-plugin-sdk#370]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
线上最新版APP：Android5.4.61的定时开关无法执行。

#### 期望

Android端的定时开关能正确执行

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
正在排查，请耐心等待

**Comment by lxq93** [comment]
您好，我们wk13周需要封样提测，请在这之前帮解决，多谢多谢啦

**Comment by lvjie0519** [comment]
@lxq93  请使用如下地址的apk测试试
https://fir.im/MiHomeForAndroid

**Comment by laohuang88** [comment]
请更新sdk
