### ISSUE TITLE
android 开发版本中 左上角dev按钮 提测的时候，怎么去掉

### ISSUE THREAD

**Issue by kfjihailong** [MiEcosystem/miot-plugin-sdk#371]
![image](https://user-images.githubusercontent.com/5388430/53864327-2890ef00-4027-11e9-97d3-3bf94f0d9c83.png)
如果所示，就是这个，美工哪里能过吗？还是我提测的时候可以去掉。

**Comment by lvjie0519** [comment]
设置-->开发者选项-->RN设备插件调试设置   页面的复选框取消选择就行。
