### ISSUE TITLE
如何使用webstrom或者android stdio开发miot-plugin-sdk

### ISSUE THREAD

**Issue by zouzhe1** [MiEcosystem/miot-plugin-sdk#373]
1，我用小米文档给的命令行说明，可以完成程序下载显示。
但是开发也不能手动打app.js文件啊，需要IDE啊，文档没有说任何IDE的相关文字。

2，我是电脑win10/手机android

3，我想使用webstrom或者android stdio来开发miot-plugin-sdk

4，当我使用webstrom时候，有下图错误
![11a](https://user-images.githubusercontent.com/13077962/53923908-c0dea200-402e-11e9-991e-1f26fe53dd04.png)

![11b](https://user-images.githubusercontent.com/13077962/53923930-d5bb3580-402e-11e9-9732-d78b870af9db.png)

5，当我使用android stdio时候，有下图问题
![22a](https://user-images.githubusercontent.com/13077962/53924082-7c9fd180-402f-11e9-9259-ae61e4c2eccf.png)
![22b](https://user-images.githubusercontent.com/13077962/53924088-80335880-402f-11e9-944f-242aaf80fa66.png)

6，请问你们都是怎么使用的？能不能推出一个IDE版本的测试你们例子的教程。

感谢。

**Comment by liuhaixu666** [comment]
米家是要真机调试的，模拟器不行

**Comment by lvjie0519** [comment]
@zouzhe1 
1、开发React Native，任意哪款IDE都行，Android Studio默认情况写js代码没提示，Windows系统通常建议用WebStorm；
2、您使用webstrom时候，有下图错误，我不知道您是输入什么命令后出现的错误还是其他情况，只需要在根目录下npm install， 然后npm start能够正常启动package服务就行；
3、请使用我们提供的apk进行相关开发和调试，建议使用真机；

**Comment by zouzhe1** [comment]
> 米家是要真机调试的，模拟器不行

不知道你这句话是哪来的，我从头到尾也没说我用模拟器。。。

**Comment by zouzhe1** [comment]
> @zouzhe1
> 1、开发React Native，任意哪款IDE都行，Android Studio默认情况写js代码没提示，Windows系统通常建议用WebStorm；
> 2、您使用webstrom时候，有下图错误，我不知道您是输入什么命令后出现的错误还是其他情况，只需要在根目录下npm install， 然后npm start能够正常启动package服务就行；
> 3、请使用我们提供的apk进行相关开发和调试，建议使用真机；

我写一下我是用webstrom的详细步骤，请帮忙看一下哪里有问题，谢谢了。
1，在https://github.com/MiEcosystem/miot-plugin-sdk页面直接点击download zip
2，解压后在我的E:\root\mi\miot-plugin-sdk-master目录下运行cmd，执行npm install语句
![1](https://user-images.githubusercontent.com/13077962/53959219-e5bb2f80-4097-11e9-8cf3-635bcf96f8a4.png)
3，修改demo下面的project.json文件
默认是
![2](https://user-images.githubusercontent.com/13077962/53959423-74c84780-4098-11e9-9860-aee8141596df.png)
修改为
![3](https://user-images.githubusercontent.com/13077962/53959437-7eea4600-4098-11e9-82cb-c98943b20b25.png)
4，然后，cmd执行npm start
![4](https://user-images.githubusercontent.com/13077962/53960154-5bc09600-409a-11e9-8ee4-0fc0df7c1843.png)
手机上正常出现demo界面。
5，然后，打开webstrom，
![5](https://user-images.githubusercontent.com/13077962/53960208-89a5da80-409a-11e9-8013-12035b3b0d00.png)
点击open，定位到如下位置后点ok。
![6](https://user-images.githubusercontent.com/13077962/53960271-b0641100-409a-11e9-9646-67d5857698f2.png)
6，打开后，edit默认是空的，没有被配置，如下图
![7](https://user-images.githubusercontent.com/13077962/53960358-f5884300-409a-11e9-8a3b-9e97f0d0cfcd.png)
我不会配置这个edit，我就按如下这样配置了。
![8](https://user-images.githubusercontent.com/13077962/53960428-29fbff00-409b-11e9-8fa4-aed6080f5ebb.png)
7，然后没动webstrom显示的然后代码，我直接点击run按钮，如下图
![9](https://user-images.githubusercontent.com/13077962/53960962-62500d00-409c-11e9-999b-781b4221a0d3.png)
然后下面就出现2个标签页如下内容
![10](https://user-images.githubusercontent.com/13077962/53961067-a2af8b00-409c-11e9-970f-d0c95f983cc7.png)
![11](https://user-images.githubusercontent.com/13077962/53961081-a7743f00-409c-11e9-8f34-128ddf4a93e0.png)
8，然后我进入米家APP设备页面，晃动点击reload
之后手机出现红色err界面，错误代码500
webstrom标签页出现如下信息
![12](https://user-images.githubusercontent.com/13077962/53961284-10f44d80-409d-11e9-9b83-18062fdc5160.png)
请问我哪里操作有问题呢？
备注：app已经设置了ip和port还有包名和model名。
9，最后一个问题，npm start明明是再根目录下执行的，他怎么知道要执行demo，而不去执行bledemo呢？

非常感谢，期待你的回答。开发资料少，我还是新手，请见谅。
@lvjie0519

**Comment by lvjie0519** [comment]
@zouzhe1 
1、在您步骤6及之后的步骤都是不需要的，启动package服务建议直接在根目录下输入npm start命令。
2、对于第9点，我们框架做了处理，因为您不是在APP开发者选项中配置了插件包名吗，例如com.xiaomi.demo， 因此会自动加载这个插件包。
