### ISSUE TITLE
使用条款和隐私政策缺少标题

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#375]
#### 环境
- 电脑操作系统:Windows
- 手机系统:Android 8.1

#### 现象
使用条款和隐私政策缺少标题

#### 其他的上下文/日志/截图
![default](https://user-images.githubusercontent.com/12816061/53946603-1a160680-40ff-11e9-8732-ee8713bf12ee.png)

**Comment by lvjie0519** [comment]
目前设计为这样，之后会找一个合适的短标题，或者其他的方式统一双端
