### ISSUE TITLE
setUserConfigs希望添加示例代码，与旧SDK传参不一致

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#376]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]MAC
- 手机系统:[eg.Android 8.1/iOS 11.0]IOS
- 相关模块:[eg.Host/Service/Account]Service

#### 现象
旧SDK的存储：
MHPluginSDK.setUserConfigs(20000,{0:{"data":"value"},100:{"data100":"value100"}},() => {})
旧SDK的读取：
MHPluginSDK.getUserConfigs(20000, [0,100], ()=>{})

新SDK中：
读取时getUserConfigs第二个参数的描述是@param {...string} keys 保存的数据索引从0开始，是传字典，旧SDK中是传数组。

#### 期望

有可用的示例。

**Comment by lvjie0519** [comment]
@zaxayn  如下使用方式
![image](https://user-images.githubusercontent.com/22487747/54107381-ed6e3180-4413-11e9-80cc-a7646dfb04f1.png)

**Comment by zaxayn** [comment]
测试可以使用，多谢
