### ISSUE TITLE
当集成RNCamera时,报错：**Undefined is not an object (evaluating 'CameraManager.Aspect')**

### ISSUE THREAD

**Issue by prince-d-sky** [MiEcosystem/miot-plugin-sdk#377]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android 8.0.0
- 相关模块: 第三方框架 - react-native-camera

#### 现象

当集成RNCamera时,报错：**Undefined is not an object (evaluating 'CameraManager.Aspect')**

#### 期望
期望能尽快处理这个bug，或告诉我如何避免这个现象

#### 其他的上下文/日志/截图

![1741552013423_ pic](https://user-images.githubusercontent.com/36910825/54004380-55144a80-4190-11e9-8388-31c0afef8f03.jpg)

#### 尝试过的解决办法

无

**Comment by lvjie0519** [comment]
1、react-native-camera，依赖该库，需要增加native层代码，您们是无法增加native层代码的；
2、目前我们暂时还不支持相机模块，之后会有对应功能增加；

**Comment by prince-d-sky** [comment]
请问预计什么时候会增加相机模块？这个功能对我的应用来说非常重要，如果新扩展程序没有这个模块的话，ios旧扩展程序有吗？

**Comment by blockdate** [comment]
旧扩展程序 支持 react-native-camera 以及 react-native-image-picker
