### ISSUE TITLE
灯泡的设备组调用出错

### ISSUE THREAD

**Issue by Aub1nLin** [MiEcosystem/miot-plugin-sdk#378]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] macOS
- 手机系统:[eg.Android 8.1/iOS 11.0] 都有
- 相关模块:[eg.Host/Service/Account] Device

#### 现象

灯组调用这个接口，来获取设备组里面的设备ID
![image](https://user-images.githubusercontent.com/45021910/54004581-03b88b00-4191-11e9-8205-6f62801a2837.png)

但是，一直报这个错误。

![image](https://user-images.githubusercontent.com/45021910/54004632-42e6dc00-4191-11e9-9247-0078a0626e75.png)

**Comment by lvjie0519** [comment]
@Aub1nLin 
您好，这不是错误， console.warn()  会弹出警告框。

**Comment by Aub1nLin** [comment]
我知道我打的是警告，我的意思是，我要的拿不到。我要拿json的信息，而且我打印json.length。也是报这么长一大串。

**Comment by lvjie0519** [comment]
@Aub1nLin  已修复，SDK分支选择SDK_10001,并更新下sdk

**Comment by Aub1nLin** [comment]
halo,
调用编辑灯组接口，并传入设备ID，页面无法选中灯组内的设备。
同时，我也试了接口中传入数组的item类型为srting也不行。
![image](https://user-images.githubusercontent.com/45021910/54330038-2c3bfb80-464f-11e9-9a7d-6788fd1c61f0.png)
![image](https://user-images.githubusercontent.com/45021910/54330073-51c90500-464f-11e9-93a9-d8e94f9c38bb.png)

**Comment by Aub1nLin** [comment]
这个问题到现在也还没解决，问题就关闭啦？？？？？？

**Comment by blockdate** [comment]
对于组设备的问题，这边提供下详细的问题描述，我们这边找相关的开发同学来处理。

**Comment by blockdate** [comment]
如还有问题请回复，或者发送微信号至wulei7@xiaomi.com。

**Comment by Aub1nLin** [comment]
halo,
  是这样的，我需要做一个灯组管理这个功能，功能需求是打开该页面，会选中当前灯组内的灯泡。根据你们的建议我调用了你们的 Host.ui.openEditDeviceGroupPage(dids) 这个接口，我将dids（设备ID的数组）传入，但是在进入页面编辑灯组这个页面的时候，不会选中我传入数组中的设备，而且标题显示为【创建设备分组】，经试验，这个接口是创建灯组的接口，不是编辑灯组。

**Comment by Aub1nLin** [comment]
> 如还有问题请回复，或者发送微信号至[wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)。

halo,
是这样的，我需要做一个灯组管理这个功能，功能需求是打开该页面，会选中当前灯组内的灯泡。根据你们的建议我调用了你们的 Host.ui.openEditDeviceGroupPage(dids) 这个接口，我将dids（设备ID的数组）传入，但是在进入页面编辑灯组这个页面的时候，不会选中我传入数组中的设备，而且标题显示为【创建设备分组】，经试验，这个接口是创建灯组的接口，不是编辑灯组。

**Comment by Aub1nLin** [comment]
另外，在调用  Host.ui.openAddDeviceGroupPage(); 这个方法的时候，Android会弹出Toast【米家：无可编辑分组设备】，而iOS是没问题的。
