### ISSUE TITLE
新手求助，如何运行SDK里面的两个demo扩展程序

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#379]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1.4
- 相关模块:[eg.Host/Service/Account]

#### 现象

新手刚下载了mito的SDK,按照米家扩展程序开发概述进行进行了操作，无法运行xiaomiDemo这个扩展程序

#### 期望

怎么才能进入SDK扩展程序呀

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by yulimik** [comment]
同求

**Comment by lvjie0519** [comment]
请将错误日志截图出来，不然没法排查，谢谢~

**Comment by lcyisgod** [comment]
![IMG_0367](https://user-images.githubusercontent.com/22785828/54094304-e7a82a00-43da-11e9-9eea-e66584de3150.PNG)
![Uploading IMG_0368.PNG…]()

**Comment by blockdate** [comment]
提供下使用的ipa版本。同时检查一下：
1. 是否在开发者通用设置中开启了插件debug功能
2.这是未能连接上调试socket报的错误，检查node 服务是否正常启动，能否使用chrome正确打开 http://yourlocalip:8081/debugger-ui 这个网页，如果不能，建议清理Chrome缓存，重启node。
3.使用 [IPA测试连接](https://fir.im/mijiadevelopment) 该链接下的最新测试包，并及时更新。
