### ISSUE TITLE
Host/UI缺少快联成功页面接口

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#380]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host]

#### 现象

Host/UI模块缺少快联成功页面接口，
![image](https://user-images.githubusercontent.com/15864191/54011255-c9f57d80-41ac-11e9-8a1b-f683b03437da.png)

#### 期望

希望能提供统一接口，iOS端和安卓都可用，

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
接口已添加，目前iOS可用，Android需要等待原生支持。
