### ISSUE TITLE
固件升级的时候，解压缩失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#383]
很急~  先谢谢各位小伙伴了~

解压缩：
<img width="487" alt="2019-03-08 5 15 55" src="https://user-images.githubusercontent.com/18459414/54019695-c5d65980-41c6-11e9-8e3b-8bae9547c613.png">
解压失败：
<img width="1530" alt="2019-03-08 5 1701" src="https://user-images.githubusercontent.com/18459414/54019671-b7883d80-41c6-11e9-8a2e-61f570ae341b.png">

**Comment by lvjie0519** [comment]
@caojunhua 提问题的时候麻烦说一下具体是哪个平台，Android/IOS/全部

**Comment by caojunhua** [comment]
> @caojunhua 提问题的时候麻烦说一下具体是哪个平台，Android/IOS/全部，这样方便对应的负责人去排查，谢谢。

ios平台，目前发现是url下载下来的文件解压缩，用本地归档都打不开，疑似文件损坏了，zip文件解压后成 了.cpgz格式的了，而不是一个文件夹

**Comment by zaxayn** [comment]
iOS  只传一个文件名就行了，不用传路径

**Comment by blockdate** [comment]
这个固件升级文件是你们自己上传的吧，下载下来之后有问题还是上传的时候就有问题

**Comment by caojunhua** [comment]
我后来发现这个不用解压了，谢谢
