### ISSUE TITLE
上传新版本包遇到的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#384]
看文档上截图，右上角有“新建扩展程序”
<img width="959" alt="屏幕快照 2019-03-09 下午1 36 41" src="https://user-images.githubusercontent.com/18459414/54066749-a4ca4300-4270-11e9-9cb3-3308cc3db56c.png">
我的打开网页
<img width="1541" alt="屏幕快照 2019-03-09 下午1 35 17" src="https://user-images.githubusercontent.com/18459414/54066757-ca574c80-4270-11e9-8bce-767eea14d724.png">
右上角没有新建扩展程序

还有，请问新版本打包流程和旧版本有什么区别吗？我之前旧版本打包成功测试了，新版本按照之前的步骤打包的时候，输入的命令行就给我报错了啊。。。

**Comment by lvjie0519** [comment]
@caojunhua  
1、检查下您的账号是否有对应的权限；
2、对于新版本，请按新版的打包步骤来，具体步骤参见开发者平台文档或git中的readme

**Comment by caojunhua** [comment]
> @caojunhua
> 1、检查下您的账号是否有对应的权限；
> 2、对于新版本，请按新版的打包步骤来，具体步骤参见开发者平台文档或git中的readme

你好，开发者平台文档或git的readme中我没有找到具体步骤，麻烦你能不能发个链接，谢谢~

**Comment by caojunhua** [comment]
> @caojunhua
> 1、检查下您的账号是否有对应的权限；
> 2、对于新版本，请按新版的打包步骤来，具体步骤参见开发者平台文档或git中的readme

权限的话，之前的旧版本就是这个账号，是不是要从哪里重新设置

**Comment by lvjie0519** [comment]
@caojunhua 让你们老大给你账号修改为管理员
https://iot.mi.com/new/guide.html?file=03-平台使用指南/01-账号权限管理/03-权限管理

**Comment by lvjie0519** [comment]
![image](https://user-images.githubusercontent.com/22487747/54099595-087d7900-43f5-11e9-9dc2-372e49ef7bb5.png)

**Comment by blockdate** [comment]
如果设置了权限之后，任然看不到管理设置，请提供小米账号ID并及时联系我们
