### ISSUE TITLE
RkSwitch 在iOS手机上，value为false时，显示异常

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#386]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

现象如图：
<img width="154" alt="WechatIMG343" src="https://user-images.githubusercontent.com/12531667/54110714-12b36d80-441d-11e9-9a3f-5a45ec481025.png">

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by qinliduan** [comment]
thumbTintColor属性传个null过去应该能解决，在iOS上设置此颜色会丢失按钮的投影。
`thumbTintColor={Platform.select({
            ios: null,
            android: '#ffffff'
          })}`

**Comment by ldezho** [comment]
@qinliduan 可以解决，多谢。
