### ISSUE TITLE
无法运行SDK里面的两个demo

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#387]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[.Android 8.1]
- 相关模块:[下载的SDK中的demo]

#### 现象

下载完SDK后，不知道如何能够运行SDK中的两个demo。
没有在新扩展开发程序指南中找到类似的说明

#### 期望

希望确认
1.想要运行着两个SDK中的demo程序，是否一定需要搜索到测试设备。
2.本地开发用的ide是webstorm，导入demo后提示不是react-native项目无法运行，想确认如何才能运行
3.demo程序是不是要按照正常的开发模式，需要生成mpkg文件，然后上传到lot平台，才能进行调试呢？

**Comment by lvjie0519** [comment]
@changgongxinshi 
1、demo也是一个插件，因此需要一个设备与之对应，在米家APP首页的设备列表中首先需要存在一个设备，即进入插件的入口；
2、在根目录下npm install, npm start，ide只是用来开发编写js代码用；
3、demo 可以本地调试；
相关调试参考（开发者平台也有相关开发调试文档）：
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/调试说明.md

**Comment by uSmile-Y** [comment]
@lvjie0519  请问 这个设备是随便什么样的都可以吗？ 现在处于开发阶段 目前还没有真实的设备 哪该怎么弄？
