### ISSUE TITLE
搜索到设备如何绑定

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#388]
简单明了地描述一下期望的表现。
想要确认，搜索到设备后，如何进行设备的绑定？
文档上面说，“绑定设备后点击米家首页对应的设备，进入到 rn 插件页面”，搜索到设备后，还未绑定成功，也无法进入到RN代码，那么本地客户端是如何知道搜索到了设备并发送绑定设备的指令了？
未在文档中找到明确的说明，盼复！！

**Comment by blockdate** [comment]
[平台使用指南](https://iot.mi.com/new/guide.html?file=03-%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/02-%E6%99%BA%E8%83%BD%E7%A1%AC%E4%BB%B6%E7%9B%B4%E8%BF%9E%E6%8E%A5%E5%85%A5/01-%E6%A6%82%E8%BF%B0)

如何接入设备 参考平台使用指南 -> 智能硬件直接连入
