### ISSUE TITLE
关于设备绑定流程与业务接口请求的相关问题咨询

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#389]
#### 现象
1、添加设备的流程是否需要与插件交互？

2、接第1个问题，如果需要与插件交互，添加设备时米家App扫描设备的规则是怎样的？怎么判断扫描到了目标设备？扫描到设备之后，如何跳转到插件的扫描状态提示页面，进而在插件的页面提示用户进行下一步操作？

3、接第2个问题，设备绑定成功之后，在米家App的首页会看到这个设备，点击设备图标后进入到插件首页，然后插件页面里面的一些业务数据如何获取，能否就以下几个场景举个调用的例子：
(1)、设备蓝牙开门后，开门记录如何上报？
(2)、开门记录上报之后如何查询历史开门记录数据？
(3)、调用哪个接口进行设备分享？
(4)、设备分享后如何查询已分享的用户列表？如何删除已分享的用户？

#### 期望

盼复以上问题

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？
已看过下面章节的描述：
https://iot.mi.com/new/guide.html?file=08-云服务开发指南/03-存储/02-数据存储-SDS

**Comment by blockdate** [comment]
1. 目前对外的设备扫描连接主要通过原生功能完成，不需要插件。
2. 具体如何连接需要参考[智能硬件接入](https://iot.mi.com/new/guide.html?file=03-%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/02-%E6%99%BA%E8%83%BD%E7%A1%AC%E4%BB%B6%E7%9B%B4%E8%BF%9E%E6%8E%A5%E5%85%A5/01-%E6%A6%82%E8%BF%B0)
3. 蓝牙设备的事件通过硬件端进行上报，插件端通过service.smarthome.getdevcedata()获取设备的事件历史。
4. 设备分享不需要插件端内部处理，使用host.ui.openShareDevicePage().
