### ISSUE TITLE
多语言设置不显示

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#390]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[Language]

#### 现象

测试多语言时，多语言设置印度尼西亚语的key是否为id，使用‘id’在android显示的还是默认的，ios上可正常显示印尼语。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
现在是否还存在问题，如果任然存在，我去联系相关同学解决，暂时关闭

**Comment by mirse** [comment]
> 现在是否还存在问题，如果任然存在，我去联系相关同学解决，暂时关闭

问题依旧存在

**Comment by zanetti4** [comment]
该问题已经定位，正在修复，将在 SDK_10011 修复。

**Comment by zanetti4** [comment]
@mirse @yanmin0220 
该问题已修复

**Comment by Woody2016** [comment]
@mirse 请在SDK_10011上验证，验证通过的话请反馈结论，并close issue

**Comment by mirse** [comment]
> @mirse 请在SDK_10011上验证，验证通过的话请反馈结论，并close issue

验证ok，谢谢。
