### ISSUE TITLE
米家测试app (andorid) 总是会自动更新

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#391]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]

#### 现象

米家测试app，在设置好开发者选项后，关闭客户端，再打开，多试几次开发者选项就不见了，app自动更新了。设置不自动更新一样的出现类似问题。

#### 期望
不自动更新
简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@uSmile-Y  
1、您是从哪下载的apk？
2、请使用最新的apk，下载地址如下：
  https://fir.im/MiHomeForAndroid或者10001分支的apk，以后即将取消apk上传到git上。

**Comment by lvjie0519** [comment]
同时请检查是否开启了应用商店的自动升级功能，如果开启了，请关闭。
