### ISSUE TITLE
最新的安卓beta版，插件升级后白屏

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#392]
在安卓版升级新插件包会出现的问题
![1001552448505_ pic](https://user-images.githubusercontent.com/14158970/54252283-2548b680-4585-11e9-9703-5b23d10e1f5b.jpg)

连接安卓studio后的错误日志显示

> 03-13 10:05:34.224 28858-28922/com.xiaomi.smarthome:plugin0 E/ReactNativeJS: TypeError: TypeError: undefined is not a function (evaluating '_smarthome2.default.getUserStatistics')

系统设置里清除米家数据后可解决
插件Api Level 10001

**Comment by lvjie0519** [comment]
@RengeRenge 目前apk有更新，请使用最新apk测试下问题是否还存在，谢谢。

**Comment by christophermitchell070** [comment]
Go The Fuck Away Stupid Ass People

**Comment by blockdate** [comment]
看日志是SDK的问题，这边建议使用 master 分支中表明的sdk 版本来测试开发与提测。
