### ISSUE TITLE
ios版本里怎么获取蓝牙的deviceInformation问题 

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#393]
你好，这是通过lightblue获取的蓝牙硬件版本信息，请问我在新版本框架里应该怎么获取这个版本信息啊，谢谢
![image](https://user-images.githubusercontent.com/18459414/54259070-854c5680-459f-11e9-9a0d-38de249a5e2b.png)

**Comment by blockdate** [comment]
这个目前没有支持获取的方法

**Comment by Woody2016** [comment]
我们RN SDK提供了蓝牙读写的通道。

固件端支持蓝牙“特定命令”读取这些硬件信息，插件端发送“特定命令”去读取，这样就可以了吧
