### ISSUE TITLE
插件打包上传，服务器错误，一直处于打包中

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#395]
插件打包上传，包已经上传成功了。但是一点击确定，报服务器出错，提交失败，试了好几次，都是这样，状态也不会改变
<img width="1550" alt="0E876CEA-7553-4674-B978-802B236293EC" src="https://user-images.githubusercontent.com/38349220/54280386-556a7680-45d2-11e9-8b36-6202c53664a9.png">

**Comment by liuhaixu666** [comment]
今天早上看了一下，还是不行。服务器出错

**Comment by liuhaixu666** [comment]
<img width="1540" alt="376398F4-4A46-47B7-AB6E-874AAFA6378E" src="https://user-images.githubusercontent.com/38349220/54326868-04df3180-4643-11e9-9e49-d2a4b9fe267a.png">

**Comment by liuhaixu666** [comment]
米家工作人员能不能帮看看啊

**Comment by liuhaixu666** [comment]
我用以前传成功的包，上传也还是不行！！！！！

**Comment by blockdate** [comment]
该问题系 后端某些关键服务离线导致，遇到该问题，及时反馈，我们会联系后端人员处理

**Comment by 4what** [comment]
@blockdate 我们也出现了同样的问题，处理问题需要提供我们的账号ID吗？

**Comment by blockdate** [comment]
提供uid以及扩产程序的ID(在iot扩产程序详情页面的url中的detail id)

**Comment by 4what** [comment]
> 提供uid以及扩产程序的ID(在iot扩产程序详情页面的url中的detail id)

uid: 1509678460
detailId: 1000034

**Comment by MauZuo** [comment]
@blockdate 扩展程序管理页面没找到上传的地方，是什么原因？
![Screenshot_2019-04-11-00-19-40-077_com android chrome](https://user-images.githubusercontent.com/32515697/55896229-6669d000-5bf0-11e9-8085-703ee509dcbb.png)
_

**Comment by blockdate** [comment]
@MauZuo 这个需要找公司管理员开权限，如果管理员也无法操作，那么及时联系我们

**Comment by MauZuo** [comment]
@blockdate 我已经发邮件了，但是一直没回复。需要怎么向管理员申请？
![%7 K6N{O 5R7 }(847T4TU](https://user-images.githubusercontent.com/32515697/55928639-0ef94d80-5c4c-11e9-9b14-dfe28fdadaca.png)

**Comment by blockdate** [comment]
@MauZuo 是找你们公司的管理员账号开权限，如果没有用的话，把你的企业信息和你的小米账号发给我wulei7@xiaomi.com。

**Comment by MauZuo** [comment]
@blockdate 我的账号就是企业账号的拥有者，企业信息和账号已经发到你邮箱了，麻烦你帮忙看看，多谢啦！

**Comment by blockdate** [comment]
后台反馈已处理，你检查下

**Comment by MauZuo** [comment]
@blockdate 已经可以用了，非常感谢！
