### ISSUE TITLE
TouchableOpacity OnPress 事件 无法响应

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#397]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Linux
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 8.0
- 相关模块:[eg.Host/Service/Account]

#### 现象

使用多个 TouchableOpacity 组件只有第一个组件能响应oPress事件
![image](https://user-images.githubusercontent.com/11848308/54337988-8ba80480-466b-11e9-9327-1ee9d0e77623.png)
****
如图，只有第一个会响应oPress事件 这是怎么回事啊？
#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by uSmile-Y** [comment]
感觉 是屏幕只有上半区域很小一块可以点击

**Comment by uSmile-Y** [comment]
刚刚换了框架里面的com.xiaomi.demo这个项目来测试，发现确实是这个问题，只有屏幕顶部区域按钮能响应事件，其他地方完全没反应
![image](https://user-images.githubusercontent.com/11848308/54339474-ef343100-466f-11e9-9c40-00420fbbfef2.png)

**Comment by lvjie0519** [comment]
@uSmile-Y  保证设备是在线状态，离线设备进入插件页面点击无效。

**Comment by uSmile-Y** [comment]
@lvjie0519 谢谢，这个问题 我弄了一天多 一直以为是自己代码问题。。。。 谢了
