### ISSUE TITLE
撤销同意隐私条款后有数据未删除

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#398]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

![image](https://user-images.githubusercontent.com/7885251/54404231-c3678880-470d-11e9-949a-80409489a094.png)

点击撤销 隐私条款后会退出插件，删除设备，但是重新绑定该设备，进行网络数据请求，还是能拿到历史数据。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这个地方的却存在问题，我们会在确认后进行处理，感谢你的反馈

**Comment by blockdate** [comment]
@JxXiaoXie 这边提供下你们使用的网络请求接口信息以及调用的方法，我们这边确认下是否属于需要删除的数据。

**Comment by blockdate** [comment]
使用SDK10005下的 `Service.smarthome.batchSetDeviceDatas` 以及`Service.smarthome.batchGetDeviceDatas` ，该方法设置的属性数据会在设备删除之后清空。
