### ISSUE TITLE
AMapView 如何动态设置中心

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#399]
before issue：（不用回答）
### 是否尝试搜索issue？

[#302](https://github.com/MiEcosystem/miot-plugin-sdk/issues/302)
请问什么时候翻到线上版本

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@smalld2006 这个月21号会有一个版本

**Comment by lvjie0519** [comment]
@smalld2006  请使用目前线上5.5.0版本验证，issue暂时关闭，如有问题，reopen。
