### ISSUE TITLE
<MessageDialog/>中的timeout属性,在IOS中不生效,android中生效

### ISSUE THREAD

**Issue by georgeChina** [MiEcosystem/miot-plugin-sdk#400]
`       <MessageDialog
          title={''}
          message={this.state.msgDMessage}
          cancelable={false}
          cancel={getString('cancel')}
          confirm={getString('entry')}
          timeout={1000}
          onCancel={(e) => {
            console.log('onCancel', e);
            this.setState({visMessage: false});
          }}
          onConfirm={(e) => {
            console.log('onConfirm', e);
          }}
          onDismiss={() => {
            console.log('onDismiss');
            this.setState({visMessage: false});
          }}
          visible={this.state.visMessage}/>`
这段代码,在android中timeout是生效的,在IOS中不生效.

**Comment by santcool** [comment]
此属性为android多余属性，已去掉，MessageDialog不应该自动消失。
