### ISSUE TITLE
使用条款加隐私， 点击使用条款， 标题显示的还是使用条款和隐私协议，点击隐私条款，是正常的，显示的是隐私协议

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#402]
新版扩展程序，忘开发者及时改正
使用条款加隐私， 点击使用条款， 标题显示的还是使用条款和隐私协议，点击隐私条款，是正常的，显示的是隐私协议

**Comment by lvjie0519** [comment]
@liuhaixu666 
1、请说明下平台，IOS/Android/ALL？
2、使用条款和隐私协议两个界面显示的是您传递过来的html文件，请检查下您的html文件。

**Comment by liuhaixu666** [comment]
> @liuhaixu666
> 1、请说明下平台，IOS/Android/ALL？
> 2、使用条款和隐私协议两个界面显示的是您传递过来的html文件，请检查下您的html文件。

跟HTML文件没关，我说的是导航栏的标题， ios，安卓都一样。
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/38349220/54512822-68919380-4990-11e9-9b77-3f2cdc2bbf23.png">

**Comment by blockdate** [comment]
这个标题是你们自己定义的：

```
Host.ui.privacyAndProtocolReview('License Page Title', licenseURL, 'Policy Page Title', policyURL);
```

其中两个字符串分别表示你们进入各自Page的title
