### ISSUE TITLE
安卓新版米家扩展程序 删除显示不全，望改进

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#403]
![WechatIMG37](https://user-images.githubusercontent.com/38349220/54473051-ac0fc480-480d-11e9-8a07-6bfcfce6380b.jpeg)

**Comment by lvjie0519** [comment]
@liuhaixu666  已修复，请使用最新apk，谢谢。
https://fir.im/MiHomeForAndroid
