### ISSUE TITLE
iOS某些本地原生业务页面导航栏会自动隐藏

### ISSUE THREAD

**Issue by Jezong** [MiEcosystem/miot-plugin-sdk#404]
before issue：
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[ Mac OS Mojave 10.14.3 ]
- 手机系统:[ iOS 12 ]
- 相关模块:[ Host.ui ]

#### 现象

RN调用`Host.ui.openXXX`跳转到原生业务页面时，某些原生页面的导航栏会消失。该现象在iOS中必现（只试了iOS12，其他版本未验证），安卓是正常的，同时开发的多个项目中，只有一个会出现这种现象。

以下列出存在问题的页面：
 - 定时开关页面（`Host.ui.openTimerSettingPageWithVariousTypeParams()`）: 点击"+"号icon时，导航栏才消失，无法创建定时。
 - 反馈问题页面（`Host.ui.openFeedbackInput()`）: 进入页面即消失。
 - 安全设置->开启密码（`Host.ui.openSecuritySetting()`）：进入开启密码页面，弹出键盘时消失。

#### 期望

导航栏正常显示

#### 其他的上下文/日志/截图

- 定时页面:
 ![6551](https://user-images.githubusercontent.com/6898755/54484677-09efeb00-48a6-11e9-9a69-b8f9c3103f39.gif)

 - 反馈问题页面:
![反馈](https://user-images.githubusercontent.com/6898755/54484782-b54d6f80-48a7-11e9-86b7-2cb31dc13d9c.PNG)

- 开启密码页面：
![6549](https://user-images.githubusercontent.com/6898755/54484688-4d4a5980-48a6-11e9-8349-b18bec21c531.gif)

#### 尝试过的解决办法

现象出现在原生页面中，猜测与RN的`RootStack`导航栏无关。且`RootStack`中并没有定义的导航栏，而是在页面中布局导航栏：
```javascript
const RootStack = createStackNavigator(
    {
        Home: HomePage,
    },
    {
        initialRouteName: 'Home',
        navigationOptions: ({ navigation }) => {
            return {
                header: null
            };
        },
    }
);
```

**Comment by blockdate** [comment]
我们已定位该问题，正在处理中，跟插件代码无关，app更细后即可解决该问题
