### ISSUE TITLE
Android 快捷卡片和快捷开关问题

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#405]
#### 环境

- 手机系统:[Android 8.1]

#### 现象

安卓小卡片的开关不能同步，配置了色温和亮度但是没有色温，同时设备界面的快捷开关也不能使用

#### 期望

快捷开关能正常使用

**Comment by M201370367** [comment]
您好，需要您提供下卡片配置及设备model信息，请联系15623527737（微信同号）

**Comment by lvjie0519** [comment]
@xuanxuandaoren  该问题不属于RN范畴，有问题请自行联系如上开发人员，issue暂关闭。
