### ISSUE TITLE
smarthome api提供

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#406]
请帮忙提供旧框架smart home api:
1、/v2/home/range_get_open_config
2、/v2/device/set_extra_data

**Comment by lvjie0519** [comment]
@TheWalkingDead2 提供下相关参数说明

**Comment by TheWalkingDead2** [comment]
hi，你好，这是接口描述。[kv_open_config_API_v6.pdf](https://github.com/MiEcosystem/miot-plugin-sdk/files/2976611/kv_open_config_API_v6.pdf)

**Comment by TheWalkingDead2** [comment]
hi，你好。该文档里面有/v2/device/set_extra_data描述。[KV存储.pdf](https://github.com/MiEcosystem/miot-plugin-sdk/files/2976640/KV.pdf)

**Comment by lvjie0519** [comment]
已增加，请更新sdk， 分支选择：SDK_10002分支

**Comment by TheWalkingDead2** [comment]
> 已增加，请更新sdk， 分支选择：SDK_10002分支

感恩
