### ISSUE TITLE
Service.smarthome.callThirdPartyAPI 遇到的问题

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#407]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
多次尝试 这个接口  均走catch 报code：-8，
一下为参数配置，也多次尝试调整参数
const json = {
            'dids': [Device.deviceID],
            'app_id': "我的id",
            'params': {
                'api_name': 'insure',
                'method': 'post',
                'data':data,
            },
        };
简单明了地描述一下实际的现象。

#### 期望
请问此处如何配置符合参数要求；谢谢
简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by liduojun** [comment]
iOS和Android 均报这个错误；iOSbeta版 最新141 sdk master分支

**Comment by lvjie0519** [comment]
@liduojun  请将设备分享给账号： 2202116824， 同时告知下设备model，我这边帮您调试下看

**Comment by liduojun** [comment]
你好已经共享，model：com.ksmb.walkingpad.mijia

**Comment by liduojun** [comment]
> @liduojun 请将设备分享给账号： 2202116824， 同时告知下设备model，我这边帮您调试下看

你好已经共享，model：com.ksmb.walkingpad.mijia

**Comment by lvjie0519** [comment]
@liduojun   您的设备目前没有上线吧，不好意思， 我这个账号不是白名单账号，请分享给894158105这个账号，谢谢

**Comment by liduojun** [comment]
> @liduojun 您的设备目前没有上线吧，不好意思， 我这个账号不是白名单账号，请分享给894158105这个账号，谢谢
你好已经共享，设备还没有上线，等着处理这个问题在上线， 设备名：走步机011，model:   com.ksmb.walkingpad.mijia    谢谢

**Comment by lvjie0519** [comment]
@liduojun   Device.deviceID 是long行， 需要转换为string类型，  “”+Device.deviceID

**Comment by liduojun** [comment]
@lvjie0519 还是不行，走了catch code：-8，之前尝试过转成字符串也不行，貌似我的id好像没有配置，用其他app_id,能够返回正常的 json信息 例如返回‘没有绑定这个设备’之类的，我的id：10071，请帮忙给检查下，谢谢

**Comment by lvjie0519** [comment]
@liduojun  你们的app_id 从哪获取的？   我用的10030可以，这个是我们这边服务器访问你那边服务器请求出现报错，检查下你那边app_id与api_name之间的关系吧

**Comment by liduojun** [comment]
@lvjie0519 我们以前用的接口地址：'app/v2/third/synccall'，现在是‘app/third/api’,目前现在接口返回还是 走catch：-8，麻烦给查看下

**Comment by blockdate** [comment]
暂时关闭，如需新增api接口`app/v2/third/synccall`, 建议新开issue处理
