### ISSUE TITLE
/user/edit_user_coll在smarthome没有对应接口

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#408]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 123start** [comment]
/user/edit_user_coll在smarthome没有对应接口

**Comment by lvjie0519** [comment]
@123start   提供下对应的参数说明

**Comment by 123start** [comment]
@lvjie0519  编辑用户收藏  coll_id :string    newname:string   content:string

**Comment by lvjie0519** [comment]
已增加， 请更新sdk， 分支选择： SDK_10002分支。
