### ISSUE TITLE
Service.smarthome.callThirdPartyAPI返回errorCode: -1100的问题

### ISSUE THREAD

**Issue by zyh427** [MiEcosystem/miot-plugin-sdk#409]
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- 相关模块:[Host/Service/smarthome]

#### 现象
调用下面的callThirdPartyAPI接口，返回ErrorCode：-1000。但是通过日志查看中间过程，有日志打印：third api: firstep success，应该已经有数据返回的了。
调用代码：
Service.smarthome.callThirdPartyAPI(parasDic).then((response) => {
            console.log("返回结果 response = " + JSON.stringify(response));
            callback(response);
        }).catch((err) => console.log('返回结果 failed:', err));

#### 期望

正常情况下应该返回结果 response

#### 其他的上下文/日志/截图
[REACT][-]-: '发出数据parasDic = %@', { app_id: 10025,
  dids: [ 'xiaoxun.46B4D9B721AC9244266025CB0CA04547' ],
  params: 
   { CID: 60051,
     model: 'xiaoxun.watch.v8',
     SN: 1552895091,
     PL: 
      { Keys: { '0': 'watch_status', '1': 'battery_level' },
        EID: '46B4D9B721AC9244266025CB0CA04547' } } }

third api: firstep success {
    code = 0;
    message = ok;
    result =     {
        CID = 60052;
        PL =         {
            "battery_level" = 99;
            "update_time" = 20190110170753012;
            "watch_status" = "20180803102825172_1";
        };
        RC = 1;
        SN = 1552895091;
    };
}

[REACT][-]-: '返回结果 failed:', { errorCode: -1100 }

**Comment by blockdate** [comment]
看日志，这是第一次请求数据返回，由于数据中没有带retrycount，导致直接返回失败了。我会先与相关人员确认问题

**Comment by zyh427** [comment]
@blockdate 这个问题是需要你们sdk修改更新吗？

**Comment by blockdate** [comment]
这个需要修改原生app层以及JSSDK层，预计明天会发布测试版。

**Comment by blockdate** [comment]
这边请分享设备至894158105账号下，我们验证能正确解决你这边的问题，如果没问题，今天下午可以提供使用。

**Comment by zyh427** [comment]
@blockdate 已经分享了设备：小寻儿童手表。你那边试一试看。

**Comment by blockdate** [comment]
尝试更新SDK看是否能正常work，在分支10003中，如果正确使用，之后会合入主线以及

**Comment by zyh427** [comment]
这是使用分支10003获得的返回结果 response = {"PL":{"watch_status":"20190326071737585_1","battery_level":"20190326071737585_0","update_time":"20190326071722539"},"SN":1553592109,"RC":1,"CID":60052}。

**Comment by zyh427** [comment]
@blockdate

**Comment by blockdate** [comment]
@zyh427 

对比了以前提供的API返回结果，如果结果正确，是直接返回result中的结果

**Comment by zyh427** [comment]
@blockdate  好的，基本验证可以。烦请及时更新到正式分支。
