### ISSUE TITLE
Service.smarthome. setDeviceData问题

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#41]
Service.smarthome. setDeviceData(did, uid, type, key, time, value)，如果我的数据是一个数组怎么办？

以前是数组中每个value都拼装一个{did: "did", uid: "uid", type: "type", key: "key", time: "time", value: ar r[0]}，现在接口怎么上传数组？

**Comment by dingshaoran** [comment]
已改为Service.smarthome. setDeviceData(params)

**Comment by JxXiaoXie** [comment]
是不是还没有部署？我传params方式报参数错误 -8

**Comment by dingshaoran** [comment]
应该是服务器报错了，在 logcat 中过滤接口名，查看服务器返回的具体数据

**Comment by dingshaoran** [comment]
android 还是 ios

**Comment by Braveleon** [comment]
我的是ios

**Comment by Braveleon** [comment]
yes返回-8

**Comment by JxXiaoXie** [comment]
请求：Service.smarthome.getDeviceData(Device.deviceID,
                                  XM_TYPE_CONFIG,
                                  XM_KEY_MODEL_PARAMS,
                                  0,
                                  Date.parse(new Date()) / 1000,
                                  1).then((response) => {
                                  });

报警告Object {"message": "callSmartHomeAPI failedErrorDemain=MiHomeNetworkErrorRemote Code=-8 UserInfo={message=device id unknown, result=, code=-8}"}

可是我Device.deviceID传的是正确的值。
