### ISSUE TITLE
代码集成到插件包后，android设备无法响应点击事件

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#410]
#### 环境
- 电脑操作系统:Windows]
- 手机系统:[.Android 7.0]

#### 现象
1.代码集成到插件包后，android设备无法响应点击事件
在我们自己的react native 测试项目中是有响应的。但是把代码集成到SDK下的插件包中，就无法继续响应，也没有日志输出
 想问下，SDK是对android这边的点击事件做了什么限制吗？

2.SDK 中的，RefreshListView这个控件，集成到插件包后在ios设备上可以正常滑动，但是在android设备中也无法滑动

**Comment by lvjie0519** [comment]
@changgongxinshi  您的设备是否处于离线状态？设备处于离线状态，只有界面的header部分有点击能力。

**Comment by changgongxinshi** [comment]
我们的设备是离线状态的，那么为什么设备离线时，ios的设备可以响应点击事件呢？

**Comment by blockdate** [comment]
如果在IOT平台上配置了离线进入，则在iOS进入插件之后可以正常点击。

**Comment by changgongxinshi** [comment]
![image](https://user-images.githubusercontent.com/16306138/54576059-a09ce300-4a31-11e9-865c-f58a38c8903f.png)


请问在哪里配置可以离线进入呢？在lot平台的基础配置中没有找到，如上图

**Comment by lvjie0519** [comment]
@changgongxinshi   建议使用在线设备，否则无法与设备进行相关操作。
设置页面如下：
http://support.io.mi.srv/new/page/develop/plugin.html
