### ISSUE TITLE
使用RN插件，连接的时候产品名称是哪获取的，理论上应该是后台管理平台上配置的那个名称。可是目前我们两个产品用了同一个RN插件，连接的时候，zhimi.airpurifier.ma4的设备总是显示zhimi.airpurifier.va1的名称，是不能用同一个插件吗？

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#411]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
你是两个model公用的一个插件么

**Comment by betterFuture** [comment]
是的

**Comment by betterFuture** [comment]
这个问题可以解决吗？

**Comment by blockdate** [comment]
方便的话提供下演示信息，以及是那两个设备的连接过程会出现这个问题，我这边排查下问题

**Comment by blockdate** [comment]
本地验证发现并未复现

**Comment by betterFuture** [comment]
"models": "zhimi.airpurifier.ma4|zhimi.airpurifier.va1",
 "package_path": "com.zhimi.airpurifier",
上面是project.json文件

**Comment by blockdate** [comment]
是这样的，扩展程序只涉及到设备连接成功之后的 设备详情页面以及自定义场景页面。快连过程的显示跟扩展程序是没有关联的
