### ISSUE TITLE
升级ble成功后，连接设备始终失败，提示"mi ble login fail"。

### ISSUE THREAD

**Issue by gaopingfly** [MiEcosystem/miot-plugin-sdk#412]
before issue：
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 12.1.4
- 相关模块: Device.getBluetoothLE().connect(-1)

#### 现象

升级ble成功后，连接设备始终失败，提示"mi ble login fail"，code=2。
app删除设备，设备重置成功后再添加设备，添加失败，提示code=2

操作步骤：
1、移植旧框架下的ble升级功能。（旧框架的ble升级都是由我们自己实现的）
2、在新框架下移植成功并开始升级ble版本
3、提示ble升级成功，重启设备后
4、采用Device.getBluetoothLE().connect(-1)时提示error：{message: "mi ble login fail", code: 2}

#### 期望

ble升级后可正常连接设备

**Comment by blockdate** [comment]
code 为 2 ，代表连接认证时数据读写失败。
请确认此情况下设备是否处于正常work的状态，怀疑是设备OTA出错，导致设备进入了某种状态无法正常work。检查下设备是否有固件有对应 services 和 characteristics。

**Comment by gaopingfly** [comment]
> code 为 2 ，代表连接认证时数据读写失败。
> 请确认此情况下设备是否处于正常work的状态，怀疑是设备OTA出错，导致设备进入了某种状态无法正常work。检查下设备是否有固件有对应 services 和 characteristics。

感谢，帮大忙了。果然是硬件出现了问题。
