### ISSUE TITLE
字符串“>” 自动显示为 "->"，部分模块显示不全

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#413]
这个现象是从3月14日下午开始出现的，中午还是正常的。
字符串“>” 显示为 "->"，
小米note3出现部分模块显示不全。

小米5s：
<image src="https://user-images.githubusercontent.com/14890491/54514889-3c791100-4996-11e9-833f-e6de86cc2c07.png" width="360" height="640">
<image src="https://user-images.githubusercontent.com/14890491/54514939-68949200-4996-11e9-891b-d6888ea62ae6.png" width="360" height="640">

红米note3：
<image src="https://user-images.githubusercontent.com/14890491/54515662-b362d980-4997-11e9-8541-05927346251b.png" width="360" height="480">
<image src="https://user-images.githubusercontent.com/14890491/54515671-bb227e00-4997-11e9-930f-6cf7e12997a0.png" width="360" height="480">

**Comment by lvjie0519** [comment]
1、小米note3部分显示不全问题，请检查文字颜色是否跟背景色一致了？或通过开发者选项开启显示布局边界查看是否有对应的占位符？
2、字符串“>” 显示为 "->"，只会在小米5S的手机上显示吗？其他手机是否有问题？

**Comment by lijian9088** [comment]
1、小米note3部分显示不全问题，请检查文字颜色是否跟背景色一致了？或通过开发者选项开启显示布局边界查看是否有对应的占位符？
图2，图4，是同一份代码，不同手机的显示。暂时只有小米note3会显示不全，其他正常。
图3在其他手机是正常显示，小米note3显示不全。

2、字符串“>” 显示为 "->"，只会在小米5S的手机上显示吗？其他手机是否有问题？
所有机型都会。

以上问题代码相同情况下，在ios端不会出现。

**Comment by lvjie0519** [comment]
@lijian9088  您好，Android系统不一样，可能显示不一样，麻烦您使用小米note3按我上面的步骤检查下，方便排查，谢谢。

**Comment by lijian9088** [comment]
好的，字体设定颜色后已经显示正常了。
字符串的问题我还是不清楚什么原因。

**Comment by lvjie0519** [comment]
@lijian9088 
字符串“>” 显示为 "->"，只会在小米5S的手机上显示吗？其他手机是否有问题？
所有机型都会。

-----------------------------------------------------------------

这个所有机型都会？  您确定使用的是字符不是图片？

**Comment by lvjie0519** [comment]
字体设置问题。
