### ISSUE TITLE
引入第三方库后，无法加载到"module:metro-react-native-babel-preset“配置

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#414]
#### 环境
- 电脑操作系统:[.Windows]
- 手机系统:.Android 7.0]

#### 现象

集成react-native-raw-bottom-sheet  库后，报 bundling failed: Error: Couldn't find preset "module:metro-react-native-babel-preset" 

在https://github.com/facebook/metro/issues/242    这个链接中说是让把，根目录下的.babelrc配置文件换成bable.config.js 配置文件，并在里面导出module:metro-react-native-babel-preset，但是并没有效果

#### 期望

想要确定SDK下的目录结构中，如何才能引用到metro-react-native-babel-preset这个库

**Comment by lvjie0519** [comment]
@changgongxinshi   插件中不允许加入设计到修改native层代码的开源库，看了下react-native-raw-bottom-sheet ，涉及到native代码修改，说明下下您需要使用该库的原因？
https://iot.mi.com/new/guide.html?file=05-米家扩展程序开发指南/01-新扩展程序开发指南/01-开发简介
![image](https://user-images.githubusercontent.com/22487747/54572994-32eaba00-4a25-11e9-9a98-71ee6b46fa62.png)

**Comment by blockdate** [comment]
如果有native端功能具体需求，请再开启一个需求issue，我们会评估是否添加

**Comment by changgongxinshi** [comment]
谢谢！已经找到了替换的方法，不需要那个开源库了
