### ISSUE TITLE
设备上的aqi数据和APP数据不同步，APP端获取到的数据滞后

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#416]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1.提供下你的数据获取方式，是通过数据上报的形式还是RPC请求的方式获取
2.如果是设备数据上报的话，确认下设备的数据状态及时上报了

**Comment by betterFuture** [comment]
Service.spec.getPropertiesValue(specPropsArr)
            .then(res => {
                if (res)  {
                }

            })
            .catch(err => console.log('getPropertiesValue: err', err));

**Comment by betterFuture** [comment]
这个问题可以解决吗？

**Comment by blockdate** [comment]
是这里返回的res与设备的当前状态不一致么？

**Comment by blockdate** [comment]
该问题为已存在的问题，因为服务端获取设备数据存在缓存，所以会存在差异，当前已经在寻找解决方案，该问题不是插件代码与硬件代码的问题。

**Comment by betterFuture** [comment]
好的 谢谢

**Comment by Bijiabo** [comment]
这个问题解决了么？
