### ISSUE TITLE
BLE扫描无法得到广播数据

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#417]
在使用startScan方法后，在BluetoothEvent.bluetoothDeviceDiscovered事件中搜索到了特定设备，但是scanRecord的值为null，这是为什么呢？
下面是扫描到设备的LOG。
`'Bluetooth', 'bluetoothDeviceDiscovered', { eventName: 'bluetoothDeviceDiscovered_36621',
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   address: '1C:52:16:00:03:0A',
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   isConnected: false,
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   scanRecord: null,
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   rssi: 0,
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   name: null,
03-19 10:58:21.398  3457  7064 I ReactNativeJS:   deviceType: 2 }`

我的设备是有广播数据包的。

![Screenshot_20190319_110606_no nordicsemi android mcp](https://user-images.githubusercontent.com/12670497/54577959-bf52a800-4a38-11e9-836c-db486191300f.jpg)

**Comment by blockdate** [comment]
1.提供下你的代码使用以及日志截图
2.看使用平台你应该是用的是Android设备吧。

**Comment by dgutkai** [comment]
代码使用的是SDK中的BLEDEMO插件，下面的代码段是修改的部分。
`componentDidMount() {
        this.showing = true;
        
        Bluetooth.checkBluetoothIsEnabled().then(result => {
            alert(result)
            this.state.isEnable = result;
            if (result) {
                // this.connect();
                Bluetooth.startScan(30000);
            } else {
                this.setState({ buttonText: "Bluetooth Status = " + result })
            }
        });
        this.s7 = BluetoothEvent.bluetoothDeviceDiscovered.addListener((bluetoohData) => {
            var address = bluetoohData["address"];
            var sData = bluetoohData["scanRecord"];
            // if (address === Device.mac){
              console.log("扫描设备", address, sData);
            // }
          })

        this._s5 = BluetoothEvent.bluetoothStatusChanged.addListener((data) => {
            console.log("bluetoothStatusChanged", data);
            if (!data) {
                this.setState({ buttonText: "Bluetooth Status = " + data })
            }
        });
    }`

扫描到的LOG如下图所示：
<img width="1440" alt="屏幕快照 2019-03-20 14 44 53" src="https://user-images.githubusercontent.com/12670497/54664458-3d897a00-4b1f-11e9-9477-8f3d60bf82c6.png">
截图中MAC是1C:52:16:00:04:1C的设备是我的设备，它的scanRecord值为null。

**Comment by lvjie0519** [comment]
@dgutkai 已修复，请使用最新apk，谢谢。
https://fir.im/MiHomeForAndroid
