### ISSUE TITLE
安卓平台调用openTimerSettingPageWithCustomIdentifier打开定时器页面所有的customTimerIdentifier都在定时器列表中

### ISSUE THREAD

**Issue by 329695834** [MiEcosystem/miot-plugin-sdk#418]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[Host]

#### 现象

安卓平台调用openTimerSettingPageWithCustomIdentifier打开定时器页面所有的customTimerIdentifier都在定时器列表中;iOS平台正常,定时器列表只显示customIdentifier的定时;器
#### 期望
和iOS平台一样只显示参数传入的customTimerIdentifier 的定时器

#### 其他的上下文/日志/截图
安卓显示如下:
![image](https://user-images.githubusercontent.com/13617241/54595814-58e87c80-4a6e-11e9-8672-20002100503e.png)
iOS显示如下
![image](https://user-images.githubusercontent.com/13617241/54595833-669e0200-4a6e-11e9-87f5-e148a4af5409.png)

**Comment by lvjie0519** [comment]
@329695834  已修复，请使用最新apk，谢谢。
https://fir.im/MiHomeForAndroid

**Comment by 329695834** [comment]
多谢,已经修复
