### ISSUE TITLE
设备共享微信好友比较慢

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#419]
#### 环境
- 手机系统:[Android /iOS]

#### 现象

设备共享微信好友比较慢，有时候一直停留在loading界面

#### 期望

微信分享能正常使用

**Comment by blockdate** [comment]
提供下具体使用的JS端代码，我们准备排查下

**Comment by xuanxuandaoren** [comment]
```javascript
 Host.ui.openShareDevicePage();
```

调用分享，选择分享给微信好友

**Comment by santcool** [comment]
此问题我们正在跟踪，请耐心等待

**Comment by zanetti4** [comment]
我用安卓手机在10020分支测试，通用设置中的设备共享，分享给微信好友功能现在很顺畅了。
