### ISSUE TITLE
锁类蓝牙设备，开锁相关接口未能找到

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#42]
请问开锁接口在哪？比如之前MHXiaomiBLE.toggleLockXiaoMiBLE，现在对应的是哪个？

**Comment by dingshaoran** [comment]
需要哪个 api 列一下。
以前 android 和 ios 调用的 api

**Comment by dzonel** [comment]
MHXiaomiBLE
    toggleLockXiaoMiBLE
    encryptMessageXiaoMiBLE

**Comment by dingshaoran** [comment]
这几个 api 刚刚添加在 Bluetooth.js，更新代码和 rn 调试的米家 app 后 使用 Device.bluetooth.securityLock.(你需要的方法) 调用。
