### ISSUE TITLE
IOS如何跳转到米家的语音授权界面

### ISSUE THREAD

**Issue by zhangpqan** [MiEcosystem/miot-plugin-sdk#420]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
调用 Host.ui.openVoiceCtrlDeviceAuthPage();  跳转语言授权页  Android正常跳转 
IOS 点击没反应
IOS 该怎么实现 请告知

**Comment by blockdate** [comment]
确认下你的设备不是分享的，分享设备无法打开语音授权
