### ISSUE TITLE
IOS 使用AMapView 

### ISSUE THREAD

**Issue by zhangpqan** [MiEcosystem/miot-plugin-sdk#421]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
1.IOS 地图上缩放图标 不显示

2.添加一个Marker 图片不显示
   if (carLatitude && carLongitude) {
                        var annotation = {
                            id: 'annotation' + carLatitude + carLongitude,
                            title: '目标位置',
                            image: require( '../Resources/banyac_car_location.png'),
                            size: {
                              width: 64,
                              height: 64,
                            },
                            canShowCallout: false,
                            lockedScreenPoint:{x:0.5,y:1},//控制图标绘制起点相对点击的位置，android 测了
                            coordinate: {
                              latitude: carLatitude,
                              longitude: carLongitude
                            },
                        };
                        this.setState({
                            zoomLevel: 18,
                            centerCoordinate: {
                                latitude: carLatitude,
                                longitude: carLongitude
                            },
                            annotations: new Array(annotation),
                            showLocation : true
                        })
                    }

按上述添加Marker Android能正常显示  IOS不能

**Comment by blockdate** [comment]
更新app https://fir.im/mijiadevelopment ，验证问题是否解决

**Comment by zhangpqan** [comment]
图标有了 
其他问题 
1.IOS 地图上缩放图标 不显示 + - 界面上没有
2.高德地图log 能提供居中方法？

**Comment by zhangpqan** [comment]
还有一个地图语言设置 我这边切换到英文后地图语言没变

**Comment by blockdate** [comment]
更新下进度：
1. + - 是不提供的建议自己实现，如果有问题或者需要支持及时反馈
2. 这个不提供
3. 英文设置问题已处理，预计明天更新

**Comment by zhangpqan** [comment]
IOS 地图上缩放图标 不显示 + - 界面上没有. Android上面有的

**Comment by zhangpqan** [comment]
图标的修改 没有合入最新？  现在还是不显示 
英文设置页也依然在 

另外 地图手动放大缩小时：onMapWillZoomByUser onMapDidZoomByUser 这两个方法没执行

**Comment by blockdate** [comment]
已处理，更新SDK与APP检查问题
