### ISSUE TITLE
一次性密码问题

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/miot-plugin-sdk#422]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Mac OS]
- 手机系统:[eg.iOS 11.4.1]
- 相关模块:[eg.Bluetooth]

#### 现象

简单明了地描述一下实际的现象。
调用getOneTimePassword()方法获取一组一次性密码,不提示成功也不提示失败.在更新最新的bateApp和sdk之前是可以的.最新的没法获取到

#### 期望

简单明了地描述一下期望的表现。
可以正常获取一组数字密码
#### 其他的上下文/日志/截图
    Device.getBluetoothLE().securityLock.getOneTimePassword(30, 8)
      .then(pwd => {
        console.log('pwd', pwd)
        this.setState({ dataArr: pwd })
      })
      .catch(err => {
        console.log('err', err)
      })
提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法
尝试了旧框架的方法,同样也没获取到
尝试过哪些操作？

**Comment by blockdate** [comment]
这一部分功能并没有过调整，这边提供下设备分享到894158105，我们这边尝试复现下问题

**Comment by nevermore-jia** [comment]
已分享,感谢

**Comment by blockdate** [comment]
更新下SDK，确认下问题是否修复

**Comment by nevermore-jia** [comment]
> 更新下SDK，确认下问题是否修复

更新了master分支,app也用的最新版本,还是获取不到,没有成功失败的回调

**Comment by blockdate** [comment]
先使用10002分支，master分支稍后跟新完成
