### ISSUE TITLE
android 底部虚拟导航键

### ISSUE THREAD

**Issue by Braveleon** [MiEcosystem/miot-plugin-sdk#423]
安卓页面的虚拟导航键显示和隐藏切换的时候影响到了布局，现在有开放获取安卓底部虚拟导航键高度的sdk吗？搜到的方案都需要原生的支持。

**Comment by lvjie0519** [comment]
1、目前没有开放的sdk，请说明一下具体的影响范围？
2、目前没有官方的api来判断全面屏及虚拟导航键高度等方法，建议从布局的角度去思考，尝试看是否可以使用flex来解决

**Comment by heping99** [comment]
这个能力什么时候能够接入，我们这边开发的一个插件使用ScrollView向下滑动共有3屏，现在根据window.height设置每屏的高度，但部分机型底部的Soft Menu会挡住一些界面。从布局的方面我们尝试了，达不到需要的效果。

**Comment by lvjie0519** [comment]
@Braveleon 
目前fir上的apk已经提供获取view宽高的api，请参考 
https://github.com/MiEcosystem/miot-plugin-sdk/issues/837
