### ISSUE TITLE
从固件升级界面回到通用设置界面收不到回调

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#424]
#### 环境

- 手机系统:[Android/iOS]

#### 现象

```javascript
this._didFocusListener = this.props.navigation.addListener('didFocus', payload => {
  console.log(payload);
} 
```
在通用设置页跳到固件升级页
从固件升级页面返回之后，该监听收不到回调

#### 期望

从固件升级页面回来之后 ，立即检测当前版本，如果有新版本，就用红点提示，如果没有新版本，取消红点。

**Comment by blockdate** [comment]
固件升级页面属于native提供的页面，不会触发RN的navigation事件，可以监听`PackageEvent.packageViewWillAppear` 事件，用于判断插件是否从native界面返回
