### ISSUE TITLE
Writing is not permitted

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#425]
环境
- 手机系统:[iOS 12.0]
- 相关模块:[BLE]

##现象

蓝牙Characteristics write，提示“Writing is not permitted”，我查了下对应Characteristics的Prof，是可以写入的。

Prof：
...
Characteristics UUID
2B07
Writable
support notify

##期望

可以正确写入，并收到value changed的notify。

## 其他的上下文/日志/截图

peripheral:35189247-FDEE-B572-A042-7CD1B6F44BCC didWriteValueForCharacteristic:2B07 error:Error Domain=CBATTErrorDomain Code=3 "Writing is not permitted." UserInfo={NSLocalizedDescription=Writing is not permitted.}
blob:http://10.81.13…-3a8d391019da:86820 changeInterval write error

### 代码
`mythis.state.chars[mythis.state.bleConnectParaCharacterUUID].write(data).then(characteristic => {
            myLog("write BLE interval " );
        }).catch( err =>{
            myLog("changeInterval write error");
        })
`

**Comment by blockdate** [comment]
猜测你的写入方式为WithResponse，建议尝试WithOutResponse。
