### ISSUE TITLE
分享用户的时候，在settings 里面加入weekdays 会报错

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#427]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统[:Android 8.1]
- 相关模块:[Service.security]

#### 现象

分享用户的时候，在settings 里面加入weekdays 会报错，{ code: -8, msg: 'invalid timelimit' }
![image](https://user-images.githubusercontent.com/16306138/54793801-34afba00-4c7f-11e9-881a-1229676e42d3.png)

传入的参数如下图

![image](https://user-images.githubusercontent.com/16306138/54793827-50b35b80-4c7f-11e9-8228-037b13469b15.png)

参数里时开始时间的时间戳转化时间后为：2019-03-22 08:00:00
结束时间时间戳转化为时间后为：2019-06-22 08:00:00
间隔时间超过了一周，status为2，加入weekdays,就报错，如果更改时间，status为1，去掉weekdays，可正常添加

#### 期望

简单明了地描述一下期望的表现。
能正常的分享用户

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
如果时间保持不变，status为1，去掉weekdays，任然可正常添加么？

**Comment by changgongxinshi** [comment]
刚试了下,“时间保持不变,status为1，去掉weekdays”，是可以正常添加的。
但是我们这边的逻辑是时间间隔时间超过一周，就要设置weekdays的

时间间隔超过一周，status应该是2的

**Comment by changgongxinshi** [comment]
还有个问题，status为3，永久的时候，开始和结束的时间戳应该是多少呢，我从2010-01-01 08:00 到 2200-01-01 08:00  也是无法添加成功的

**Comment by changgongxinshi** [comment]
求回复，进行不下去了！！

**Comment by lvjie0519** [comment]
如果状态是3，永久，开始时间和结束时间的时间戳都是当前时间
如果状态是2，开始时间，结束时间的时间戳，是固定的date如“2019-03-28”,加上用户选择的时间，组成的时间戳

**Comment by changgongxinshi** [comment]
好的，已经解决了吗，谢谢
