### ISSUE TITLE
React native  FlatList，在state里面初始化数据的时候，列表无法显示数据

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#428]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[JS操作被限制]

#### 现象
React native  FlatList，在state里面初始化数据的时候，列表无法显示数据

![image](https://user-images.githubusercontent.com/16306138/54794511-d8e73000-4c82-11e9-9df6-ef94b33a2324.png)

如上图，只有在FlatList里面初始化数据的时候才能在列表看到数据，当把数据放到state里，如下图：
![image](https://user-images.githubusercontent.com/16306138/54794554-0cc25580-4c83-11e9-89f3-037b15a1f4a7.png)
，就无法加载到数据
![image](https://user-images.githubusercontent.com/16306138/54794572-282d6080-4c83-11e9-8155-36822591198a.png)
log,11111也能正常的打印数组数据
![image](https://user-images.githubusercontent.com/16306138/54794614-498e4c80-4c83-11e9-9eb6-a43893dcc7ed.png)

同样的界面，放到SDK外面的demo中，在state中初始化数据的时候是能加载到的，在SDK中就不可以，想问下，SDK是否对数据加载做了限制？？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
SDK没做限制，看你的代码，`date = xxx`, 不是 `data` ???
