### ISSUE TITLE
iOS MessageDialog 在标题或副标题缺省的情况下界面上依然会空出对应位置

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#429]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[iOS 11.0]
- 相关模块:[eg.miot/ui/MessageDialog]

#### 现象

iOS MessageDialog 在标题或副标题未配置的情况下界面上依然会空出对应位置。另外，取消按钮的文字颜色跟给过来的规范也不一致

#### 期望

希望未配置的项在界面上不要空出位置

#### 其他的上下文/日志/截图

如下图是未配置message的情况，但是界面会留出message位置。标题未配置也是会留出标题位置

![IMG_0091](https://user-images.githubusercontent.com/41932871/54797075-b1e22b80-4c8d-11e9-9cf2-567951b47f2d.PNG)

调用代码：

`<MessageDialog
          visible={showTips}
          title="是否将本次报警进行消音？"
          cancel="取消"
          onCancel={() => {}}
          confirm="确定"
          onConfirm={() => {}}
        />`

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
已处理，稍后更新测试app即可
