### ISSUE TITLE
MHPluginSDK.saveInfo == Host.storage.save？

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#43]
原来的本地存储MHPluginSDK.saveInfo是否与现在的Host.storage.save对应？

**Comment by LiuMengzhou** [comment]
@dzonel 
`MHPluginSDK.saveInfo`和现在的`Host.storage.set`对应，用于单个kv的存储，一次性存储多个kv可以使用`Host.storage.save`。
[文档](https://miecosystem.github.io/miot-plugin-sdk/module-miot_host_storage.html)

**Comment by LiuMengzhou** [comment]
Duplicate of #11 
Duplicate of #10

**Comment by dzonel** [comment]
@LiuMengzhou 旧接口可以一次性获取所有值，但新接口必须指定key？是否考虑会增加获取所有值的接口？

**Comment by dzonel** [comment]
旧MHPluginSDK.loadInfoCallback()，新的是否有与这个对应的？

**Comment by dingshaoran** [comment]
必须指定

**Comment by dzonel** [comment]
👌
