### ISSUE TITLE
是否有计划提供Toast组件？

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#430]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]

没发现有Toast组件，sdk是否考虑提供？还是插件自行开发各自的Toast组件？

**Comment by lvjie0519** [comment]
@qinliduan  我们这边评估下，有消息及时回复。

**Comment by blockdate** [comment]
已纳入通用组件开发计划，有更新会及时通知

**Comment by LiuMengzhou** [comment]
@qinliduan 
[react-native-root-toast](https://github.com/magicismight/react-native-root-toast)可以满足需求。
建议在自己项目的根目录下安装该组件。
我们将提供一份使用示例在`com.xiaomi.demo`中(>=SDK_10012)，当然你可以参考该组件的[README](https://github.com/magicismight/react-native-root-toast/blob/master/README.md)
