### ISSUE TITLE
调用setDeviceData(params) 

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#431]
Service.smarthome.setDeviceData({
            did:Device.deviceID,
            uid:Device.ownerId,
            type:1,
            key:"pwSetNormal",
            time:"321",
            value:{"passwordType":1,
                "password":"123456",
                "passwordName":"测试"
            }
        }).

调用这个方法时返回code=-4，服务器错误
message: "callSmartHomeAPI failedError Domain=MiHomeNetworkE…nfo={message=server error, result=false, code=-4}"}
请问是什么原因呢

**Comment by dingshaoran** [comment]
-4是服务端返回的，麻烦您在 android 手机过滤 logcat， core D/MIIO 贴出来

**Comment by lcyisgod** [comment]
我这边是在iOS手机上请求的接口，iOS端上如何过滤这个信息呢？

**Comment by lvjie0519** [comment]
@lcyisgod   参考 [issue 434](https://github.com/MiEcosystem/miot-plugin-sdk/issues/434)
