### ISSUE TITLE
TitleBarBlack和TitleBarWhite切换导致页面抖动

### ISSUE THREAD

**Issue by xiongbo3** [MiEcosystem/miot-plugin-sdk#433]
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.1.4]
- 相关模块:[miot/ui]

#### 现象

TitleBarBlack和TitleBarWhite切换导致页面抖动

#### 期望

不要抖动

#### 尝试过的解决办法

只使用TitleBarBlack或者TitleBarWhite，再手动设置StatusBar.setBarStyle 就不会抖动，但是标题栏的文字颜色没法变化

**Comment by lvjie0519** [comment]
@xiongbo3 如果需要进行切换，建议使用TitleBar，已修复，SDK10003分支。
