### ISSUE TITLE
新SDK有没有老版本getDevicePropertyFromSrvCache的替代方法，android需要从云端获取属性

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#435]
before issue：（不用回答）
### 是否尝试搜索issue？ 搜索过

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象
在新的sdk中没有找到老版本getDevicePropertyFromSrvCache的替代方法，无法从云上获取当前设备的属性，在新的sdk中使用此方法，Android上无法运行。 请问有没有替代方法？

#### 期望
Android能够从云服务器上获取设备属性。目前在新sdk中使用getDevicePropertyFromSrvCache方法，Android上会提示 红色警告，”识别不了iOS的方法“。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

查看issues，查找文档

**Comment by lvjie0519** [comment]
@zhuxinleibandou

**Comment by zhuxinleibandou** [comment]
> @zhuxinleibandou
> 请使用如下方法
> Service.smarthome.batchGetDeviceDatas

收到，我们马上尝试一下，非常感谢！

**Comment by hj0407** [comment]
> @zhuxinleibandou
> 请使用如下方法
> Service.smarthome.batchGetDeviceDatas

你好，是这个方法吗batchGetDeviceProps，可是我返回错误，
`//从云端获取数据 
    Service.smarthome.batchGetDeviceProps([{did:"",props:["prop.dec_lnk","prop.dec_mot","prop.dec_sta","prop.dec_wal","prop.dec_gas","prop.dec_com","prop.dec_dor","prop.dec_tmp"]}]).then((result) => {
      
    })
   .catch(err => {
      alert("error:",err)
  })`

**Comment by icedu8910** [comment]
你好，能提供一下 该方法的使用例子吗？
Service.smarthome.batchGetDeviceDatas

**Comment by icedu8910** [comment]
> @zhuxinleibandou
> 请使用如下方法
> Service.smarthome.batchGetDeviceDatas

你好，能提供一下 该方法的使用例子吗？
Service.smarthome.batchGetDeviceDatas

**Comment by blockdate** [comment]
参考 [wiki](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/18-%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1_%E6%99%BA%E8%83%BD%E5%AE%B6%E5%BA%AD%E6%A8%A1%E5%9D%97#module_miot/service/smarthome.batchGetDeviceDatas)
