### ISSUE TITLE
Device.getDeviceWifi().loadProperties 请求超时

### ISSUE THREAD

**Issue by hj0407** [MiEcosystem/miot-plugin-sdk#436]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- 相关模块:[eg.Host/Service/Account]

#### 现象

Device.getDeviceWifi().loadProperties("dec_lnk","dec_mot","dec_sta","dec_wal","dec_gas","dec_com","dec_dor","dec_tmp").then(map => {
      alert("12344")
    })

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
1、请说明一下平台 Android or  ios or  all？
2、请输出一下log日志，方便排查。

**Comment by hj0407** [comment]
> 1、请说明一下平台 Android or ios or all？
> 2、请输出一下log日志，方便排查。

1.ios平台
2.
Possible Unhandled Promise Rejection (id: 6):
Object f
"message". "callMethod failedError ' lalta
Domain= MiHomeNetworkErrorRemote Code= -3
l"(nuIl)" Userlnfo=(code=-3, id=13,
message-timeout, error=(
code = "-3";
message = timeout;
)",
]

**Comment by blockdate** [comment]
timeout错误系服务端返回错误。
1. 检查下参数是否都是合法并且可以通过callMethod('get_prop',xxx) 进行获取。
2. 检查下设备状态，尝试重新绑定配网。
