### ISSUE TITLE
调用Device.getDeviceWifi().callMethodDevice.getDeviceWifi().callMethod()发送控制指令时，回调函数中的结果有时会报错，获取不到正确的返回值。

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#437]
问题描述

在界面加载时，我调用了获取设备状态的方法，之后开启一个定时器，每个3S获取当前设备状态。代码如下：
![image](https://user-images.githubusercontent.com/5464058/54961939-ac6d3580-4f5a-11e9-9d0e-129bdd02ac3b.png)

获取设备状态代码如下：
![image](https://user-images.githubusercontent.com/5464058/54961980-e807ff80-4f5a-11e9-85b9-243f7744856a.png)

我发现在最初界面加载的时候我并不能获取正确的返回值。
res报如下错误：
![image](https://user-images.githubusercontent.com/5464058/54962060-5056e100-4f5b-11e9-8abb-cd401556fa2c.png)

但是经过几次查询之后，会返回正确的结果。（这说明我的设备返回是正确的。）

**Comment by blockdate** [comment]
这个错误看提示是代码的语法错误，在方法ComponentDidMount中。

**Comment by fgb031102** [comment]
希望能尽快帮忙解决。
