### ISSUE TITLE
设备离线时 获取设备相关方法属性--callMethodFromCloud

### ISSUE THREAD

**Issue by fosen** [MiEcosystem/miot-plugin-sdk#438]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.iOS 12.0]
- 相关模块:[eg.Device]

#### 现象
<img width="548" alt="image" src="https://user-images.githubusercontent.com/15226994/54904387-5d52e080-4f19-11e9-831a-18e04a2f299e.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/15226994/54904427-7b204580-4f19-11e9-8ef2-68e0d8b7d8d2.png">

图一是硬件的设置，图二是获取相关属性，这样处理有什么问题吗？按照提供的插件开发文档传参数，提示参数错误，请问是不是你们的开发文档是不是没有更新，能不能给一个正确的写法。现在提示Method not Found，有时会提示timeout。

**Comment by blockdate** [comment]
获取属性可以直接使用loadProperty方法或者callMethod('get_prop',....)。  
你上面的截图中的props是用于设备上报用的，不是给插件端获取属性用的method，能明白么。

**Comment by fosen** [comment]
> 获取属性可以直接使用loadProperty方法或者callMethod('get_prop',....)。
> 你上面的截图中的props是用于设备上报用的，不是给插件端获取属性用的method，能明白么。

callMethodFromCloud呢，不能使用？ 设备离线时，怎么获取属性？

**Comment by blockdate** [comment]
callMethodFromCloud('get_prop,...)

**Comment by fosen** [comment]
> callMethodFromCloud('get_prop,...)

@blockdate 

按照您说的方式调用如图
![image](https://user-images.githubusercontent.com/15226994/54970942-3a7b0780-4fbf-11e9-8619-2bb94e7878fc.png)

返回结果如图，提示设备没有在线
![image](https://user-images.githubusercontent.com/15226994/54970931-2d5e1880-4fbf-11e9-8300-c0c4cb34e9c1.png)

**Comment by fosen** [comment]
> callMethodFromCloud('get_prop,...)

@blockdate  如果让设备保持在线状态的话，返回的错误如下图

![101553574069_ pic](https://user-images.githubusercontent.com/15226994/54971531-c8f08880-4fc1-11e9-8575-0aa7cc20b975.jpg)

请问该怎么处理这个问题

**Comment by blockdate** [comment]
method not found 表示服务器在与设备交互时并没有找到get_prop方法，建议咨询硬件工程师是否支持了这个通用方法或者使用什么方法获取属性。
