### ISSUE TITLE
最新5.3.3安卓测试版 图片失真

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#439]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- 相关模块:[？]

#### 现象

更新完最新安卓测试版，大部分图片都出现了失真现象，原来的apk就不会出现这种情况。

![image](https://user-images.githubusercontent.com/5188922/54968350-4d88da00-4fb5-11e9-8560-ca415dafa980.png)

#### 期望

建议每次更新apk，能适当添加更新日志

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@mirse 请给出以下具体示例代码，我这边测试下，谢谢。

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/55042205-71a6f280-506b-11e9-9be4-a8f8ccda6117.png)

这是demo中TitleBarBlack的代码，并未改动

**Comment by lvjie0519** [comment]
已经优化， 使用最新sdk和最新apk。

**Comment by mirse** [comment]
更新过后可以了。
