### ISSUE TITLE
miot/Service/storage getUserConfigs 与原 MHPluginSDK.getUserConfigs 返回数据及格式不一致

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#44]
```javascript
MHPluginSDK.getUserConfigs(COMPONENT_ID, [100], (success, config, error) => {
  console.log(config);
});
```
返回：
![image](https://user-images.githubusercontent.com/8953556/48834367-9ab33000-edb8-11e8-8cb6-6aa6075fc5b6.png)

```javascript
import { Service } from 'miot';

const { storage } = Service;

storage.getUserConfigs(COMPONENT_ID, 100).then(data => {
  console.log(data);
});
```
返回：
![image](https://user-images.githubusercontent.com/8953556/48834555-17dea500-edb9-11e8-84ed-59402b7a9d47.png)

**Comment by laohuang88** [comment]
这个数据是透传出来的，有缺什么没有？如果没有的话就按照现在返回的数据继续后面的处理。

**Comment by qinliduan** [comment]
遇到了同样的问题，这个如果无法兼容，一旦切换到新sdk会丢失大量用户数据，望兼容一下，谢谢

**Comment by blockdate** [comment]
@qinliduan 邮件提供下 componentID以及keys，我们这边确认下接口使用问题

**Comment by blockdate** [comment]
在分支10003更新SDK至最近一次提交，验证是否还有问题

**Comment by qinliduan** [comment]
> 在分支10003更新SDK至最近一次提交，验证是否还有问题

您好，切到1003分支，调用报错了，控制台报 j is not defined

**Comment by blockdate** [comment]
提供一下调用方法

**Comment by qinliduan** [comment]
> 提供一下调用方法

调用方法在3月28号发送的邮件里有，邮件标题：使用miot-plugin-sdk调用getUserConfigs接口时发现数据出现丢失。切到1003分支后，iOS控制台报 j is not defined，安卓没有回调也不报错

**Comment by fengdexunmi** [comment]
> 提供一下调用方法

@blockdate 我和@qinliduan一个公司的，28号发了封相关邮件给你，有收到么？
今天下午用Android原生代码调用getUserConfigV5接口、用rn调用getUserConfigs接口返回数据都缺失了很多数据。

**Comment by blockdate** [comment]
@fengdexunmi hi， 这边排查了下，做了一些调整，iOS直接更新SDK使用即可，Android需要等待新的app提供native的一些支持。

使用结果如果任然有问题，请及时反馈

**Comment by blockdate** [comment]
@fengdexunmi 微信号提供到wulei7@xiaomi.com, 这边和Android内部同步一下，确认接口返回数据一致

**Comment by blockdate** [comment]
与Android下保持一致，直接提供get_user_config以及get_third_user_config
