### ISSUE TITLE
更新完米家APP后，设备消失

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#440]
#### 环境

- 手机系统:[Android]

#### 现象

更新完米家APP后，在米家设备列表界面找不到客厅吸顶灯和卧室吸顶灯，设备数量从32变成25，连接的其他设备有的也找不到，將米家所有数据清空再登陆，消失的设备又出现了

**Comment by lvjie0519** [comment]
@xuanxuandaoren  可能是缓存问题，有没有尝试下拉刷新列表试试？

**Comment by xuanxuandaoren** [comment]
@lvjie0519    下拉刷新几次仍然显示设备缺少，杀掉米家app进程再进入就有了。

**Comment by lvjie0519** [comment]
@xuanxuandaoren    这是白名单账号对于白名单设备没有更改时间戳的问题，非白名单账号不会有此问题。
