### ISSUE TITLE
Android点击返回按钮会自动返回到桌面

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#441]
#### 环境

- 手机系统:[Android]

#### 现象

安卓机型，从米家设备列表界面进入插件，在插件界面正常操作一段时间，点击主界面左上角的返回按钮，就自动退到桌面了，没有返回米家设备列表界面，也没有提示米家APP无响应

#### 返回按钮进行了一下操作
```javascript
 let savedInfo={
      "isFirst":this.isFirst,
      "lastBri":this.state.currentBright,
      "lastCct":this.state.currentCCT,
      "lastPower":this.state.powerStatus,
      "lastScene":this.state.currentScene,
      "lastDelay":this.state.currentDelay,
      "hasRC":this.hasRC,
      "isTouch": this.isTouch
    };

 storage.saveItem(savedInfo);

 this.timer && clearTimeout(this.timer);
 this.interval && clearInterval(this.interval);

 Package.exit() 
```

**Comment by lvjie0519** [comment]
@xuanxuandaoren  
1、 必现还是偶现？
2、storage.saveItem(savedInfo); 做了些什么操作？
3、仅仅调用Package.exit() ，是否复现？

**Comment by xuanxuandaoren** [comment]
1、是高频率复现，
2、存了几个数值到本地

**Comment by lvjie0519** [comment]
@xuanxuandaoren   我这边无法复现，logcat查看下  是否有错误日志出现。

**Comment by xuanxuandaoren** [comment]
@lvjie0519 
<img width="1645" alt="WeChatee9f137edf790b4901b73ddeb7fd84a9" src="https://user-images.githubusercontent.com/18681867/55143267-5924fe00-5179-11e9-91b9-728eb3ae494d.png">

**Comment by lvjie0519** [comment]
@xuanxuandaoren   这个日志无法体现，希望可以提供一份点击返回按钮后执行完整的代码，或者您直接在xiaomi.demo中MainPage.js文件中进行修改，将该文件发送给我，我这边复现下。

**Comment by xuanxuandaoren** [comment]
@lvjie0519 

在返回键就做了三个操作 ，
1、清除定时器 timer 和 interval 
2、保存信息到本地 
3、退出插件 
看日志 是不是退出的时候没有关闭 写入本地字节流没有关闭导致的 ？

```javascript
   onPressLeft={() => { 
              this._writeToUserInfo();
              this.timer && clearTimeout(this.timer);
              this.interval && clearInterval(this.interval);
              Package.exit() 
            }}


//退出插件时保存当前状态
  _writeToUserInfo(){
    let savedInfo={
      "isFirst":this.isFirst,
      "lastBri":this.state.currentBright,
      "lastCct":this.state.currentCCT,
      "lastPower":this.state.powerStatus,
      "lastScene":this.state.currentScene,
      "lastDelay":this.state.currentDelay,
      "hasRC":this.hasRC,
      "isTouch": this.isTouch
    };
    storage.saveItem(savedInfo);
    console.log("saved userInfo:"+savedInfo);
  }
```

**Comment by lvjie0519** [comment]
@xuanxuandaoren 尝试下数据写入完成回调后再Package.exit() 试试，我这边无法复现，应该要看下APP进程的log日志。

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请从新提issue，谢谢。

**Comment by Monkey0803** [comment]
`static navigationOptions = ({ navigation }) => {
        return {
            header:
                <View>
                <TitleBarBlack
                    title={navigation.state["params"] ? navigation.state.params.name : Device.name}
                    style={{ backgroundColor: '#fff' }}
                    onPressLeft={() => { Package.exit() }}

                    onPressRight={() => {

                        navigation.navigate('Setting')
                        // navigation.navigate('CMAnimation')
                    }}

                    />
                </View>
        };
    };`

<img width="2086" alt="image" src="https://user-images.githubusercontent.com/11564933/57935464-6e561780-78f4-11e9-8ef3-3f70c18c177d.png">


[test1.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3191944/test1.txt)
