### ISSUE TITLE
Android 升级界面存在问题

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#442]
#### 环境

- 手机系统:[Android]

#### 现象

有新版本更新时，点击升级，升级界面停留在100%的进度状态一直不动，灯也没有变化，几分钟后，界面直接跳转到有新版本升级界面，没有提示升级失败，此时再次点击升级，有可能会导致灯会灭亮两次，升级两次象。

#### 调一下代码进入操作界面
```javascript
 Host.ui.openDeviceUpgradePage();
```

**Comment by lvjie0519** [comment]
@xuanxuandaoren  apk有更新，请使用当前最新apk，是否还存在问题？

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请从新提issue，谢谢。
