### ISSUE TITLE
Android 点击快捷方式 会卡顿

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#443]
#### 环境

- 手机系统:[Android]

#### 现象

1.连接设备后，建立桌面快捷方式（灯为通电开灯的状态）
2.在米家APP设备列表界面，点击设备进入插件，点击home键，將APP在后台运行
3.小米5s机型，点击该设备的桌面快捷方式，有时会点击一次没有反应，再点击第二次，灯关闭（通电关灯的情况下，点击桌面快捷方式，会开灯）；小米6X机型，点击该设备的桌面快捷方式，有时会一直停留在空白界面；vivo X9机型，点击桌面快捷方式，无响应

**Comment by lvjie0519** [comment]
@xuanxuandaoren   请用当前最新apk，再进行测试下试试，谢谢。

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请从新提issue，谢谢。
