### ISSUE TITLE
无法支持调用地址 /app/v2/third/synccall 

### ISSUE THREAD

**Issue by smallzhan** [MiEcosystem/miot-plugin-sdk#444]
before issue：（不用回答）
### 是否尝试搜索issue？ 是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

我们的插件使用中用到了服务器的一个接口，接口地址为 /app/v2/third/synccall
在老 RN sdk 和 Android Java 原生 SDK 中， 可以使用 callSmartHomeAPI(api, params, callback) 的方式，自己填入 /app/v2/third/synccall 来实现, 目前新版的 RN 插件中仅有 callThirdPartyApi 接口，这个接口固定只能调用 /app/third/api, 经与小米服务器方开发人员沟通，确定 /app/third/api 无法支持目前我们的接口需求，因此希望支持 /app/v2/third/synccall 调用。

#### 期望
SDK 提供方法，能够支持调用 /app/v2/third/synccall 。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供API参数与返回值结构，我们会为你添加

**Comment by smallzhan** [comment]
api 地址 是 /app/v2/third/synccall,  参数 params 是一个json 字符串，返回值也是 json 字符串，一个典型的 调用示例如下：

**Comment by blockdate** [comment]
更新SDK 至branch 10003 最新提交。
使用方式为：
```
Service.smarthome.thirdSyncCall(params).then(res => {...}).catch(err =>{...})
```

**Comment by liduojun** [comment]
@blockdate 你好，刚才用了最新的iOS-167版本  最新的SDK-10003分支，报错 thirdSyncCall is not a function,

**Comment by smallzhan** [comment]
@blockdate 已经调试正常，感谢添加！
