### ISSUE TITLE
如何将编译期的变量打进包里

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#445]
before issue：（不用回答）
### 是否尝试搜索issue？

如何将编译期的变量打进包里
例如编译时间如何打到包里，内部获取这变量

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
JS是即时编译的，不知道你说的编译期是指哪个时间。。。
麻烦描述详细点。

**Comment by smalld2006** [comment]
我想要在js里拿到我发布该包时的时间

**Comment by blockdate** [comment]
这个是没有的，建议自己在发布mpkg时，自行内置一个时间。
