### ISSUE TITLE
安卓端刘海屏适配问题，目前发现红米6Pro和小米8的导航栏有问题 ，挡住了title 其他机型尚不清楚

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#446]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@betterFuture   截图看下您TitleBar相关的用法，我这边使用TitleBarBlack or  TitleBarWhite  没发现问题。

**Comment by lvjie0519** [comment]
@betterFuture  已修复TitleBar适配Android， 更新下sdk， 10003分支。
