### ISSUE TITLE
迁移手册里面第9个组件相关里面的Picker跨平台解决方案在Android系统上异常卡顿

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#448]
#### 环境
- 手机系统:[Android]
#### 现象
Picker在Android系统上异常卡顿
#### 期望
Android和iOS都可以流畅使用

**Comment by lvjie0519** [comment]
@joyami  不建议使用Picker， 我们已经提供  StringSpinner 和 NumberSpinner， 请使用这两个组件。
