### ISSUE TITLE
蓝牙门锁绑定失败需要添加pid1170

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#449]
before issue：（不用回答）
### IPA/APK 是否更新到最新？
iOSAPP 163版本
---

#### 环境
iOS 163版本   pid：1170
#### 现象
iOS绑定门锁输入安全码后提示绑定失败code=12
跟我们嵌入式一起debug，然后和你们技术也沟通过，发现问题出在 iOS app 不支持 蓝牙2.2.0 绑定，需要添加支持
我们设备的pid：1170

**Comment by blockdate** [comment]
更新IPA至167版本以上查看问题是否解决

**Comment by blockdate** [comment]
不活跃
