### ISSUE TITLE
SignleChoseDialog安卓端点击行之后 弹框会重复弹出

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#451]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@betterFuture  请截图看下您代码的具体使用，同时请参考com.xiaomi.demo的使用方式，我这边测试没发现。

**Comment by lvjie0519** [comment]
@betterFuture  已修复，请使用最新的apk。
