### ISSUE TITLE
Android  ART库画的图形锁屏解锁后会消失

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#452]
#### 环境

- 手机系统:[Android]
- SDK分支: [master/10002.]

#### 现象

小米MAX2,vivo X9，OPPO A5 画的图形，锁屏解锁后消失

**Comment by lvjie0519** [comment]
@xuanxuandaoren   发现确实部分手机  ART画的图形确实存在消失的情况，看了RN issue，属于RN的问题，建议使用svg画图。

**Comment by xuanxuandaoren** [comment]
因为要画倒计时空间，要画很多线条 ，用svg画会更卡顿。

**Comment by fishle** [comment]
对于有问题的机型：是不是可以监听一下APP的状态，如果APP从不可见状态切换为可见状态就重新绘制一下？
通过AppState.currentState来获取状态变化，具体参考 https://reactnative.cn/docs/appstate/

**Comment by xuanxuandaoren** [comment]
@fishle 重绘也是不行的。

**Comment by fishle** [comment]
试试这个包：https://pan.mioffice.cn:443/#/link/C31A942AAF0FE52D5427A16E75FAC178
可能需要卸载安装

**Comment by fishle** [comment]
现在应该是正常的，如果有问题再打开吧
