### ISSUE TITLE
SingleChoiceDialog更新Check属性后无法更新选中项目（iOS表现正常）

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#454]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

SingleChoiceDialog中，check={this.state.activeRing}
绑定一个变量。
check的state变量更新后，重新show这个Dialog，check项无法选中新值。
forceupdate也没用，请问是否可以改进一下这个控件，增加一个监测prop变更的方法。

iOS上表现正常。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@febird  已修复， 请使用最新apk，试试。

**Comment by febird** [comment]
@lvjie0519 已更新最新的APK，好像还是没有生效。

我这边代码片段如下：
其中每次设置绑定的states后，通过设置visable来调出选择框。
其中，title绑定的state变化，title可以体现出来更新。
但是 check绑定的state变化，在Android上还是无法重选，iOS正常。


            <SingleChoseDialog ref={(c) => this._refSCDlg = c}  title={this.activeTitle}
                                dataSource={RingList}
                                cancel={getString('ui_dlg_cancel')}
                                confirm={getString('ui_dlg_confirm')}
                                cancelable={false}
                                timeout={0}
                                check={this.state.activeRing}
                                //check = {1}
                                onCancel={(e) => {
                                  console.log('onCancel Choose', e);
                                }}
                                onConfirm={(e)=>{this._onSenderChangeDid(e);}}
                                onCheck={(e)=>{this._onSenderCheckDid(e);}}
                                onDismiss={() => {
                                  console.log('onDismiss Choose');                                  
                                  this.setState({visSingle: false});
                                }}
                                visible={this.state.visSingle}/>

**Comment by lvjie0519** [comment]
1、你是打开弹窗后，代码在背后默默的修改check然后更新弹窗的选中状态？为什么会有这种需求？占不能支持；
2、在第一次显示弹窗的时候，给予check一个默认值，是会显示第几个item的吧，然后接下来的选中状态就让用户来决定了。

**Comment by febird** [comment]
@lvjie0519   我的使用场景是这样的： 扩展程序主界面，有若干个子设备（动态，比如5个）都可以分别设置铃声，每个子设备一个按钮。这些子设备共用一个列表选择框通过id来区分。按钮被点击的时候根据id得到check值，设置SingleChoiceDialog的状态，然后设置visable show出来，设置完成后hide，点击其他id的按钮重新show不同的设置。不是在后台默默地更新状态。这么做目前Android只是第一次会正确选中，hide后再切换其他的就保持上次的值。 但是iOS就没有问题。

> 1、你是打开弹窗后，代码在背后默默的修改check然后更新弹窗的选中状态？为什么会有这种需求？占不能支持；

> 2、在第一次显示弹窗的时候，给予check一个默认值，是会显示第几个item的吧，然后接下来的选中状态就让用户来决定了。

**Comment by febird** [comment]
@lvjie0519 这个问题可以再帮看一下吗？
