### ISSUE TITLE
怎么创建虚拟设备调UI呢，在官方文档里面没有发现有教程

### ISSUE THREAD

**Issue by jhflovehqy** [MiEcosystem/miot-plugin-sdk#455]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@jhflovehqy  
1、Android目前还不支持创建虚拟设备，调试UI参见调试文档，只需要配置米家APP首页设备列表中的任一设备model及插件包名，即可；
2、ios可以支持创建虚拟设备，参见调试文档。
https://github.com/MiEcosystem/miot-plugin-sdk/blob/master/调试说明.md

**Comment by jhflovehqy** [comment]
@lvjie0519 你好，请问我怎么知道米家APP首页设备列表中的设备Model以及插件包名呢
![image](https://user-images.githubusercontent.com/45353516/55124608-c61ca180-5141-11e9-8327-56bb8dd45443.png)

**Comment by jhflovehqy** [comment]
![image](https://user-images.githubusercontent.com/45353516/55124923-fadd2880-5142-11e9-9887-cab7663b711e.png)
首页也没有看到有设备
