### ISSUE TITLE
ScrollView滑动问题

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#456]
before issue：（不用回答）
### IPA/APK 是否更新到最新？
是
### SDK 是否更新到最新？
是
### Check 文档了吗？
是
### 是否尝试搜索issue？
是
---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
mac os
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.1
- SDK分支: [eg.master/10000/...]
master
- 相关模块:[eg.Host/Service/Account]

#### 现象
ScrollView snapToInterval 属性设置在android上无法生效，ios上是可以的。

简单明了地描述一下实际的现象。
[官方说0.53.0](https://github.com/facebook/react-native/releases/tag/v0.53.0) 版本支持snapToInterval 属性
现在插件RN版本是0.54.4，貌似并没什么用！

#### 期望
另发现onScrollEndDrag 和 onMomentumScrollEnd 有时候滑动停止不会出现回调，**有什么方法可以监听滑动停止吗？**

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
onMomentumScrollEnd 就是在scrollView停止滑动的事件。

在Android下snapToInterval 无效 @lvjie0519 支持下

**Comment by evansherry** [comment]
@blockdate 
在scrollView内包裹TouchableHighlight的时候，只要你滑动到TouchableHighlight内容部分，onMomentumScrollEnd和onScrollEndDrag回调不会出现，不论android还是ios。

**Comment by evansherry** [comment]
@lvjie0519  我们尝试了用rn去实现，效果都不理想，能否提供原生控件供rn调用？具体效果是将view上划到一定位置，就整体向上吸附到顶端；向下滑动到一定位置，就整体向下吸附到底端。如下所示：
<img src="https://user-images.githubusercontent.com/11881751/56339747-0c659d80-61e2-11e9-90f5-d276e92d6760.gif" width = "272" height = "480" alt="scrollView" />

**Comment by lvjie0519** [comment]
@evansherry 尝试了用rn去实现，效果都不理想， 主要是存在哪方面的不理想？看gif图，不太明白您具体需求，可以加微信（微信号：18750118631）,详聊，谢谢。

**Comment by blockdate** [comment]
可以参考最新的demo中的UI能力-> ScrollView吸附效果demo，如果效果任不理想，可以单提一个UI组件需求的issue并说明原因
