### ISSUE TITLE
关于配置米家APP首页设备列表中的任一设备model及插件包名

### ISSUE THREAD

**Issue by jhflovehqy** [MiEcosystem/miot-plugin-sdk#457]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

目前因为硬件还没完成，所以想先调试UI，但是在米家测试版APP登录我的开发者账号，在米家首页并没有发现有设备，如下图所示，

![image](https://user-images.githubusercontent.com/45353516/55125103-a25a5b00-5143-11e9-92f3-d73a7c28a910.png)

而我在平台创建的硬件已经出现在手动添加页面，但是点这个会进去蓝牙扫描页面，而我又没有设备，导致不能添加到米家测试版APP首页，请问我应该怎么做，才能调试UI呢

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@jhflovehqy   Android目前还不提供创建虚拟设备的功能；
1、建议找一个拥有设备的账号来进行UI开发；
2、或者在IOS平台上进行开发，ios目前支持创建虚拟设备，供调试UI。
