### ISSUE TITLE
iOS真机无法远程调试JS（已拦截跨源请求）

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#458]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

在iOS开发者App里面填入node服务器地址，开启调试，电脑上打开debugger ui。
无法调试，android是可以的。

![2019-03-28 11-45-58屏幕截图](https://user-images.githubusercontent.com/1283681/55128876-20bcfa00-5150-11e9-915b-b9de69beab8e.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
localhost 改为你电脑的IP地址，与手机Debug页面填写保持一致
