### ISSUE TITLE
关于IOS 米家测试版APP创建虚拟设备

### ISSUE THREAD

**Issue by jhflovehqy** [MiEcosystem/miot-plugin-sdk#459]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:iOS 12.1.4]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
在开发者模式中选择创建虚拟设备，但是首页并没有出现虚拟设备

![image](https://user-images.githubusercontent.com/45353516/55133739-a5fcda80-5161-11e9-9615-00477c773ea0.png)

![image](https://user-images.githubusercontent.com/45353516/55133743-a8f7cb00-5161-11e9-8fc5-21b2e53f56d2.png)

![image](https://user-images.githubusercontent.com/45353516/55133748-ac8b5200-5161-11e9-9166-aa7a2b3e01dc.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 确认填写的model为已经申请并且没有上线设备的model。
2.查看房间列表中是否有dev栏。
