### ISSUE TITLE
隐私政策和使用条款无法正常使用

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#460]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
米家版本5.5.3测试版
使用Host.ui.privacyAndProtocolReview打开隐私政策页后出现：
1.标题栏无标题
2.使用条款和隐私政策均无法使用

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@evansherry 
1、privacyAndProtocolReview打开的页面确实没有title部分，这个设计如此；
2、使用条款和隐私政策均无法使用 是什么意思？ 请描述详细，谢谢。

**Comment by evansherry** [comment]
@lvjie0519 无法使用是点击使用条款和隐私政策均不跳转具体页面，对比iOS可以正常跳转

**Comment by lvjie0519** [comment]
@evansherry 测试下xiaomi.demo  在您那边是否可以跳转？ 如果可以参考下有什么区别，谢谢。

**Comment by evansherry** [comment]
@lvjie0519  demo上android只支持本地加载，建议支持url加载

**Comment by DaquanZhou** [comment]
@lvjie0519 demo上android只支持本地加载，建议支持url加载

**Comment by lvjie0519** [comment]
@evansherry  由于使用条款和隐私政策需要经过我们这边的审核，目前不支持url加载，ios支持url加载吗？

**Comment by DaquanZhou** [comment]
@lvjie0519 iOS 支持 url 加载

**Comment by lvjie0519** [comment]
@evansherry  已沟通，我们这边是不允许加载网页url的，ios目前支持之后会取消，不要使用http 的url来显示使用条款和隐私政策。
