### ISSUE TITLE
MiHomeNetworkErrorLocal code=-12

### ISSUE THREAD

**Issue by chenj1ahui** [MiEcosystem/miot-plugin-sdk#461]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
![image](https://user-images.githubusercontent.com/33817754/55139531-f3347880-5170-11e9-9d53-4fa8935202ba.png)

ios连续点击2～3下 也就是调用控制方法，会出现该错误。android则正常。
然后看文档，平台说请求频繁。但如果频繁，android那边应该也同样会出现才对。

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

### 不要贴大段代码❗️

**Comment by blockdate** [comment]
这个是内部逻辑的处理问题，iOS与Android的CallMethod内部逻辑并不是完全一致的。
建议在收到这个错误的时候忽略不显示即可。
