### ISSUE TITLE
订阅设备事件无法收到设备上报数据

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#464]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] android 9.0
- SDK分支: [eg.master/10000/...] 10002
- 相关模块:[eg.Host/Service/Account]  DeviceEvent Device

#### 现象

简单明了地描述一下实际的现象。

模块上报数据后平台上能看到数据，app上无法接收到改数据

#### 期望

期望能正常接收

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。
![1553763048960](https://user-images.githubusercontent.com/8141398/55143430-b325c380-5179-11e9-8a99-5b7f95da3c40.jpg)

![1553763234814](https://user-images.githubusercontent.com/8141398/55143643-1adc0e80-517a-11e9-9588-4cff3effa228.jpg)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
可以尝试在iOS下使用测试，查看是否有通知推送，iOS下的推送会在debug时打印出来

**Comment by Aptx4869-xd** [comment]
@blockdate 我试过ios和安卓的，控制台上都是没看到有日志打印出来

**Comment by lvjie0519** [comment]
@Aptx4869-xd   ios平台下是否存在同样问题，无法监听到属性变化或事件响应？

**Comment by Aptx4869-xd** [comment]
@lvjie0519 是的ios上也有同样的问题

**Comment by Aptx4869-xd** [comment]
@lvjie0519 你好，我这边设备的上报数据是模块这边模拟发到平台的，平台上能看到这条模拟的数据，然后app设备就是监听不到这个数据

**Comment by blockdate** [comment]
确认下设备的属性以及事件已经成功正确定义，并且数据上报成功无误。

native端该功能检查后并未发现问题，如有问题请咨询设备接入人员。
