### ISSUE TITLE
MiHome CrashReport 

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#465]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Mac OS]
- 手机系统:[eg.iOS]
- SDK分支:
- 相关模块:

#### 现象

MiHome 闪退

<img width="629" alt="image" src="https://user-images.githubusercontent.com/7885251/55147484-6e058f80-5181-11e9-983e-b3047719039d.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/7885251/55147505-7b227e80-5181-11e9-83d1-32dff1b373a6.png">

#### 期望

简单明了地描述一下期望的表现。

**Comment by blockdate** [comment]
反馈crash：
1. crash文件导出
2. app 构建编号
通过邮件发送至wulei7@xiaomi.com

**Comment by sofichael** [comment]
IPA/APK为最新版，遇到使用com.xiaomi.demo时，闪退问题
