### ISSUE TITLE
启动扩展程序插件的时候经常报错。（andrdoid）

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#466]
小米安卓手机，加载扩展应用程序时，经常崩溃。

报：android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

无语，求解决方案。

**Comment by lvjie0519** [comment]
@fgb031102 
1、是目前最新的apk吗？
2、告知下您的机型，运行com.xiaomi.demo是否出现同样的问题？

**Comment by fgb031102** [comment]
> @fgb031102
> 1、是目前最新的apk吗？
> 2、告知下您的机型，运行com.xiaomi.demo是否出现同样的问题？

1、是的，我在是github上直接下载的。
2、小米Demo我没有运行。我运行其它项目也会出现这个问题。

**Comment by lvjie0519** [comment]
1、GitHub上直接下载？ 从  https://fir.im/MiHomeForAndroid这里下载最新apk；
2、检查下Demo是否有相同问题或者一个空项目是否有相同问题，有可能与你们自己的项目有关，具体是在哪一步出现错误，希望给完整的log日志。

**Comment by fgb031102** [comment]
> [https://fir.im/MiHomeForAndroid这里下载最新apk](https://fir.im/MiHomeForAndroid%E8%BF%99%E9%87%8C%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0apk%EF%BC%9B)

您好！用您给到的链接出现如下错误
![image](https://user-images.githubusercontent.com/5464058/55222626-b8edd880-524f-11e9-978f-818eea73be09.png)

完整报错信息如下：
![image](https://user-images.githubusercontent.com/5464058/55223491-a1afea80-5251-11e9-8168-57d5023c3d3e.png)

**Comment by lvjie0519** [comment]
https://fir.im/MiHomeForAndroid

**Comment by fgb031102** [comment]
> https://fir.im/MiHomeForAndroid

![image](https://user-images.githubusercontent.com/5464058/55224592-33205c00-5254-11e9-846e-d0831f34342e.png)

 密码？

**Comment by lvjie0519** [comment]
git库中的readme，或开发平台的文档也有；
下载密码: keliyuan
https://github.com/MiEcosystem/miot-plugin-sdk

**Comment by fgb031102** [comment]
> git库中的readme，或开发平台的文档也有；
> 下载密码: keliyuan
> https://github.com/MiEcosystem/miot-plugin-sdk

谢谢！换了新APP目前没有发现问题
