### ISSUE TITLE
订阅没有推送成功的问题

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#467]
订阅没有推送成功的问题
你好，这边测试发现在频繁变更状态（这边是掰动龙头切换制水和待机），会有几率发生推送没有过来的问题。iOS 和 安卓都有几率发生。

图片是在两个插件界面都打开的状态下频繁掰动龙头后
再次切换结果是正确的
![WechatIMG807](https://user-images.githubusercontent.com/14158970/55204050-a0a69b00-5208-11e9-9432-1c6ee9e8a05d.jpeg)

**Comment by blockdate** [comment]
这个问题系推送的延迟以及推送数据丢失导致，我们会持续优化推送的送达率，该issue暂时关闭。
