### ISSUE TITLE
快捷卡片param_range参数不生效的问题

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#469]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1.0]
- SDK分支: [master/10000/...]
- 相关模块:快捷小卡片

#### 现象

调试米家快捷小卡片时，对"cardType": 4的card_items设置了param_range，点击加减按钮时，还是会超出这个设置的范围。

#### 期望

点击+时若超过最大范围直接设置成最大，点击-时若超过最小范围直接设置成最小。

#### 其他的上下文/日志/截图

{
        "cardType": 4,
        "prop_key": "prop.SpeakerVolume",
        "param_range": {
          "min": 0,
          "max": 100
        },
        "param_delta": 10,
        "param_type": [
          {
            "index": 0,
            "type": "JSONArray"
          },
          {
            "type": "int"
          }
        ],
        "operation": [
          {
            "method": "set_speaker_SpeakerVolume"
          }
        ]
      }

![image](https://user-images.githubusercontent.com/46127660/55208013-8aeca200-5217-11e9-98c1-7cf51dd6f93b.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by JobenTian** [comment]
调试APP版本：5.4.58 测试版

**Comment by M201370367** [comment]
卡片问题请添加微信方便沟通，此处不方便沟通。
微信15623527737
