### ISSUE TITLE
PackageEvent.packageAuthorizationCancel 收不到这个通知

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#47]
1、openPrivacyLicense进行软件政策和隐私协议授权；
2、privacyAndProtocolReview打开软件政策和隐私协议页面，取消授权；
3、在MainPage.js里的componentDidMount监听packageAuthorizationCancel消息，收不到这个消息

代码：
import {PackageEvent} from 'miot';
.....   
const subscription = PackageEvent.packageAuthorizationCancel.addListener(()=>{
            alert(222222);
        })

**Comment by dingshaoran** [comment]
android or ios

**Comment by flingInTheSky** [comment]
iOS

**Comment by flingInTheSky** [comment]
@dingshaoran 问下，这个问题解决了吗

**Comment by blockdate** [comment]
更新SDK重试

**Comment by flingInTheSky** [comment]
@blockdate 还是不行

**Comment by blockdate** [comment]
更新SDK，本地测试已通过。
