### ISSUE TITLE
关于 video加载视频问题

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#470]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
使用 react-native-video, 发现在安卓上面, 加载本地视频显示不出来, iOS 上面可以.
使用 uri 加载网络视频, 在安卓和iOS 都可以加载出来.

提供的 VideoDemo 里面使用的是uri 加载网络视频, 暂无加载本地视频的示例.

#### 期望

简单明了地描述一下期望的表现。
加载本地视频, 在安卓和iOS 都可以加载出来!

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？
1.更新react-native-video到4.2.0版本还是不行

**Comment by lvjie0519** [comment]
请使用   source={require('../Resources/mp4/broadchurch.mp4')}   这种方式。

**Comment by DaquanZhou** [comment]
现在就是使用的这种加载方式.
![image](https://user-images.githubusercontent.com/16514238/55310209-7831d180-5492-11e9-82f6-d566ad179d90.png)

**Comment by lvjie0519** [comment]
@DaquanZhou  我在xiaomi.demo中测试是可以的，  您在我们提供的demo先测试试试。

**Comment by DaquanZhou** [comment]
我刚按照您说的, 在提供的 demo 中加载本地视频, 安卓手机上还是不能显示, 结果如下:
![image](https://user-images.githubusercontent.com/16514238/55391595-4725cf80-556c-11e9-82ff-4f8872c3e76b.png)
![image](https://user-images.githubusercontent.com/16514238/55391636-5c026300-556c-11e9-9e9d-7c7488f31b33.png)
![image](https://user-images.githubusercontent.com/16514238/55391650-61f84400-556c-11e9-9b5d-e014c930692f.png)
能否提供您测试成功的例子?

**Comment by lvjie0519** [comment]
更新下sdk， 点击屏幕，就会播放。
![image](https://user-images.githubusercontent.com/22487747/55402634-7e08df00-5586-11e9-82e0-a3855194342e.png)

**Comment by DaquanZhou** [comment]
我刚查看了 master 及分支代码,都是加载网络视频
![image](https://user-images.githubusercontent.com/16514238/55445894-0cfe1180-55f0-11e9-8c5f-c1bd8f423fed.png)

**Comment by DaquanZhou** [comment]
能否提供一个加载本地视频的 demo

**Comment by lvjie0519** [comment]
sdk  切换到 10003分支。

**Comment by DaquanZhou** [comment]
我刚尝试了1003分支, 运行xiaomi.demo, 加载本地视频, 还是无效, 跟之前的情况一样
![image](https://user-images.githubusercontent.com/16514238/55455214-66c50280-5615-11e9-9c8c-1884ecbafc45.png)

**Comment by lvjie0519** [comment]
@DaquanZhou   不好意思，上传文件的时候，本地视频文件没上传成功，再次更新下sdk，你这手机显示黑色，点击屏幕也没有反应吗？ 可以添加微信：18750118631，详聊。
