### ISSUE TITLE
Device.getDeviceWifi().callMethod 报错 （只在安卓上面出现，ios无问题）

### ISSUE THREAD

**Issue by MingNingJian** [MiEcosystem/miot-plugin-sdk#471]
return Device.getDeviceWifi()
      .callMethod(method, params)
      .then(res => {
        console.log('res', res);
      })
      .catch(error => {
        alert("err：",error);
      });
   err 的错误信息：没有内容

**Comment by blockdate** [comment]
1. 提供设备model并且分享设备至894158105账号下，提供设备名称信息供我们识别。
2. 提供一下你的调用参数

**Comment by MingNingJian** [comment]
问题解决，第二个参数如果没值，需要传一个空的 { }
