### ISSUE TITLE
Device.getDeviceWifi().callMethod 报错

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#472]
我试图调用这个接口给设备发送开、关控制命令，然后通过回调函数获取返回值，但是发现，回调函数res中返回的信息经常出现如下错误
![C_735OL%K){D2RF4~)P5MVF](https://user-images.githubusercontent.com/5464058/55223591-dfad0e80-5251-11e9-9d87-46d05eac4fdd.png)

（备注：我的设备是可以正常响应开、关命令的。）获取返回值的时候报错。
操作系统：小米5 OS：8.0

**Comment by lvjie0519** [comment]
1、请粘贴下您的具体代码；
2、回调成功的时候res携带如上信息还是失败后error携带如上信息？

**Comment by fgb031102** [comment]
> 1、请粘贴下您的具体代码；
> 2、回调成功的时候res携带如上信息还是失败后error携带如上信息？

具体代码如下：

程序没有走到catch，在then中，res携带上面截图的错误信息。

![image](https://user-images.githubusercontent.com/5464058/55225343-bee6b800-5255-11e9-8c0e-20d0b67c3e17.png)

**Comment by lvjie0519** [comment]
1、麻烦logcat查看下core进程的日志输出？
2、第二个参数为空传递{}试试？

**Comment by fgb031102** [comment]
> 1、麻烦logcat查看下core进程的日志输出？
> 2、第二个参数为空传递{}试试？

针对第一点：
我现在是用的浏览器调试。所有的关于这个接口的操作全部返回这个信息。

针对第二点，我这边功能定义的主是数组。
![image](https://user-images.githubusercontent.com/5464058/55339518-6aea0680-54d5-11e9-99b6-464e3002f5a4.png)

**Comment by blockdate** [comment]
这个错误看上去是代码code问题，这边更新SDK后是否还有问题呢，同时建议尝试下iOS下使用是否任然有问题，暂时关闭
