### ISSUE TITLE
后续是否会提供规范中的公共组件供使用？

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#473]
给过来的规范中有一些公共组件，其跟rn提供的组件样式不一样，如slider组件，使用rn的Slider，在iOS上跟规范接近，但是在安卓上跟规范差别很大；这类组件后续是否会统一封装供使用？

**Comment by blockdate** [comment]
这个已经在开发计划当中，我们会逐步推进
