### ISSUE TITLE
关于虚拟设备调试的问题

### ISSUE THREAD

**Issue by jhflovehqy** [MiEcosystem/miot-plugin-sdk#474]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

请问一下我开启调试xiaomi.demo的程序的时候报了这个错误，怎么解决呢

![image](https://user-images.githubusercontent.com/45353516/55298765-0cd00b80-5462-11e9-9546-5ea7e3654d8f.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供一下使用app的版本（icon编号）

**Comment by chenzhuojie** [comment]
版本号是167

**Comment by blockdate** [comment]
duplicate #488 

统一在488中提供自身的配置以及日志截图
