### ISSUE TITLE
打包上传失败显示的错误

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#475]
各位同学好，我打包上传后出现如下错误，麻烦给看看，谢谢了

{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":10244,"Complete":true,"Exit":1,"Error":null,"StartTs":1554037259631056147,"StopTs":1554037275819702729,"Runtime":16.188646634,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1554037252280694580/compile/projects/temp_a737d786_615c_41c6_90a6_611b74e2ff9b","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1554037252280694580/compile/bin/buildBundle.js --android --target /tmp/1554037259631016327/release/android com.trios.freetie.ios","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1554037252280694580/compile","","[MIOT]start to build android bundle for com.trios.freetie.ios","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1554037252280694580/compile/projects/com.trios.freetie.ios","","output /tmp/1554037259631016327/release/android","","Loading dependency graph, done.","","","error：","","error：ENOSPC: no space left on device, mkdir '/tmp/metro-cache-11612fa656f8ab39e1027973be4b15fbb7abcc37/cache/2f'","",""],"Stderr":[]}

**Comment by blockdate** [comment]
这是我们这边后端的问题，可以尝试重新上传
