### ISSUE TITLE
TitleBarBlack和TitleBarWhite subTitle引起安卓报错

### ISSUE THREAD

**Issue by xiongbo3** [MiEcosystem/miot-plugin-sdk#476]
#### 环境
- 手机系统:[Android 小米6x]
- SDK分支: [master/10003/...]
- 相关模块:[miot/ui]

#### 现象

页面副标题设为'' 空字符串时，报错，导致页面打不开
错误信息为：Cannot Add a child that doesn’t have a YogaNode to...

#### 期望

无bug

临时解决方案是，将空subTitle 设为' ',一个空格

原理可参考以下文章
https://blog.csdn.net/wapchief/article/details/79917190

做法是，将render 中的 && 这种操作换掉

**Comment by lvjie0519** [comment]
@xiongbo3   已修复，更新sdk  10003分支。
