### ISSUE TITLE
查询当前设备固件版本信息。运行报错

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#477]
Service.smarthome.getAvailableFirmwareForDids运行报错，提示Unhandled JS Exception: Cannot read property ‘list’ of null

SDK已更新到最新。

这几个的值均正常：Device.model, Device.deviceID, Device.getDeviceWifi().deviceID 。

Service.smarthome.getLatestVersion也有正常的返回值，url、md5、version、changeLog。

```
    Service.smarthome.getAvailableFirmwareForDids([Device.deviceID])
      .then((result) => {
        console.log('result: ', result)
      })
      .catch(err => {
        console.log('error: ', err)
      })

    Service.smarthome.getLatestVersion(Device.model).then(res => {
      console.log('model, latest version', res)
    }) 

    console.log('device model', Device.model, Device.deviceID, Device.getDeviceWifi().deviceID)
```

Demo也是同样的报错：教程->与服务器交互->查询当前设备固件版本信息。

**Comment by blockdate** [comment]
已修复，更新SDK。这个系服务端返回为空的逻辑异常。

**Comment by dan-huang** [comment]
@blockdate 刚更新到SDK_10003，现在会走到catch，携带的error信息是null。

device model: ninebot.scooter.v2 
device id: blt.3.sto79nic8o00
