### ISSUE TITLE
Android 刘海屏区域黑色

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#478]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
在android 刘海区域未启用，应用是竖屏且不是全屏(没有hide statusbar)，在原生中就会使用默认的刘海区域，但是现在却没达到预期的效果，希望告知解决办法和原因。
**当前已更新到最新的10003分支，手机是华为荣耀10.**
```
static navigationOptions = ({ navigation }) => {
        return {
            header:null
        };
    };
```
自定义标题栏后，就会出现刘海区域黑屏！

效果图如下：
<img src="https://user-images.githubusercontent.com/11881751/55312344-e2994080-5497-11e9-8661-7d25e3254907.jpg" width = "300" height = "200" alt="刘海1" />
<img src="https://user-images.githubusercontent.com/11881751/55312346-e331d700-5497-11e9-875a-5b440afbc6ca.jpg" width = "300" height = "200" alt="刘海2" />

希望能使用刘海区域，如图：
<img src="https://user-images.githubusercontent.com/11881751/55312347-e331d700-5497-11e9-9d06-f14ccdc454c6.jpg" width = "300" height = "200" alt="刘海3" />

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by mirse** [comment]
怎么解决的呢？

**Comment by lvjie0519** [comment]
@evansherry   参考TitleBar或TitleBarBlack的实现方式。
