### ISSUE TITLE
调用 StatusBar.setBarStyle('light-content')小米5手机状态栏显示黑色

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#479]
#### 环境

- 手机系统:[Android]

#### 现象

调用 `StatusBar.setBarStyle('light-content')`小米5手机状态栏显示黑色

**Comment by lvjie0519** [comment]
1、检查下其他手机是否存在同样问题？
2、您是使用我们提供的TitleBar 还是 自定义的TitleBar？

**Comment by xuanxuandaoren** [comment]
其他手机还没遇到过 ，用你们提供的和自定义的都存在这种现象的 。
@lvjie0519 

### 小米手机5
![Screenshot_2019-04-02-16-59-24-172_com xiaomi sma](https://user-images.githubusercontent.com/18681867/55389946-cd401700-5568-11e9-9a65-303302fddb1d.png)

### iPhone XS

![IMG_84B1578F4AF0-1](https://user-images.githubusercontent.com/18681867/55390020-ed6fd600-5568-11e9-85d2-0ec10007dc44.jpeg)

**Comment by lvjie0519** [comment]
@xuanxuandaoren  
其他手机还没遇到过 ，用你们提供的和自定义的都存在这种现象的 

------------------------------------------------------------

相同的代码，只有小米5出现这种情况？其他手机不会是吧？

**Comment by xuanxuandaoren** [comment]
@lvjie0519 目前适配的几个手机就小米5 有这种情况

**Comment by lvjie0519** [comment]
@xuanxuandaoren   状态栏问题进行过优化， 用最新apk，看看问题是否存在？

**Comment by xuanxuandaoren** [comment]
@lvjie0519  用最新的还是存在的。

**Comment by lvjie0519** [comment]
@xuanxuandaoren   我这边测试 小米5， 设置为light-content， 会显示白色文字的，如果未解决，加微信（微信号：sky-boy-0519）,详聊下。
