### ISSUE TITLE
WebView 问题

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#48]
```javascript
import { WebView } from 'react-native';
```
使用 RN 自带的 WebView 在 iOS 下会导致插件崩溃。
![img_a10fe240440f-1](https://user-images.githubusercontent.com/8953556/48891332-07d8cb00-ee76-11e8-820f-ec27e56dbda7.jpeg)

**Comment by LiuMengzhou** [comment]
Duplicate of #50
