### ISSUE TITLE
能否提供从RN跳到原生界面时的事件

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#480]
#### 现象

当有新的版本可以升级时，在提醒升级的dialog 弹出前快速点击自定义的dialog ，会导致弹出两个dialog ，点击确定升级时，会在升级界面显示自定义的dialog。

**Comment by blockdate** [comment]
这个目前没有提供，我们会讨论下看如何提供这一通知

**Comment by Woody2016** [comment]
加通知不是解决此问题的根本方法啊

插件自己做流程控制，比如“检查是否需要升级”这个完整的操作结束前不让点击“自定义dialog”

**Comment by xuanxuandaoren** [comment]
@Woody2016 检查是否需要升级是IOS进入插件默认自己带的，目前我的做法是只能是屏蔽它进入界面就自动检测升级。
