### ISSUE TITLE
react-native-swipeout在Android系统上不是很流畅

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#482]
#### 现象

react-native-swipeout在Android系统上不是很流畅

#### 期望

在安卓上能实现流畅的左滑效果

**Comment by damiknows** [comment]
@lvjie0519 请问有优化的排期，有个新产品有使用需求

公司名称（必填）
绿米

是否为新产品（必填）
是

产品名称/Model（必填）
lumi.gateway.mgl03

**Comment by lvjie0519** [comment]
优化的优先级通常要低一些，最近一周暂无排期计划

**Comment by fishle** [comment]
是不是在滑动的时候做了一些耗时的操作？单纯的滑动这边看并没什么问题

**Comment by Woody2016** [comment]
这个issue长时间无响应，先close
如果开发者还有问题，请去开发者平台提工单
