### ISSUE TITLE
关于苹果端调用一次性密码显示版本不支持的问题

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#484]
苹果版本ipa包进入一次性密码界面提示当前版本不支持，请问是否有最新的ipa包还是需要更新sdk
当前调用方式如下
<img width="743" alt="屏幕快照 2019-04-02 09 07 12" src="https://user-images.githubusercontent.com/22785828/55368892-bd074800-5526-11e9-99a5-c4363408a900.png">
当前ipa包版本号为168
ipa包地址为:https://fir.im/mijiadevelopment

**Comment by blockdate** [comment]
问下，你这边出现问题提示是本地调试时出现的还是在下载服务端插件包加载时出现的。

**Comment by lcyisgod** [comment]
本地调试时出现的问题，这是控制台的输出
<img width="852" alt="屏幕快照 2019-04-02 11 17 31" src="https://user-images.githubusercontent.com/22785828/55373937-61928580-5539-11e9-95b5-6c3df5b75637.png">

**Comment by lcyisgod** [comment]
新测试发现调用了Host.ui.openOneTimePassword();方法
在IOS端无法跳转,但是在Android端是可以正常跳转的

**Comment by blockdate** [comment]
问题已解决，更新app至最新测试版即可（线上版本也已经处理该问题）。
