### ISSUE TITLE
缺少MHDeviceGroup在新框架对应类

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#485]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
缺少MHDeviceGroup在新框架对应类。文档链接
[Mijia-Mesh-1.0-iOS-api-device_group.pdf](https://github.com/MiEcosystem/miot-plugin-sdk/files/3032216/Mijia-Mesh-1.0-iOS-api-device_group.pdf)
该项目名称为“miiot-mesh-doc”，是私有项目。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
处理中，在SDK 10004 中提供，届时会通知到你。

**Comment by blockdate** [comment]
iOS 使用分支sdk_10004可以使用。

Android需要natiive桥接支持之后才可以使用， @lvjie0519 完成后及时更新状态
