### ISSUE TITLE
录制语音无法录制

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/miot-plugin-sdk#486]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eMac OS]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [master/10000/...]
- 相关模块:[Host/Audio]

#### 现象

简单明了地描述一下实际的现象。
1.调用Host.file.storageBasePath 返回的结果是undefined,导致无法播放语音文件
2.调用Host.audio.startRecord 返回 The audio recorder is running.录音权限已开启,但是如果文件名字用MHPluginFS.storageBasePath+name.wav,调用Host.audio.startRecord是可以正常录音的
#### 期望

简单明了地描述一下期望的表现。
1.返回正确的文件路径2.可以正常录音
#### 其他的上下文/日志/截图
1.Host.file.storageBasePath  undefined
2.The audio recorder is running
提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法
搜索了issue未找到相关问题,
尝试过哪些操作？

### 不要贴大段代码❗️

**Comment by blockdate** [comment]
1. 音频模块的录音和使用不需要提供全路径，直接使用fileName的形式即可，内部会自己处理路径关系。参考文档[录音模块](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/08-%E5%8E%9F%E7%94%9F_%E9%9F%B3%E9%A2%91%E6%A8%A1%E5%9D%97) 的example

2. 这个问题我们会排查是否存在录音失败导致下次录音任然失败的问题

**Comment by nevermore-jia** [comment]
下午试了下10002分支的代码,Host.file.storageBasePath这个方法会返回路径,并且com.xiaomi.demo里Host.audio.startRecord方法,传的filename传的是Host.file.storageBasePath + 'test.wav',可以录音成功. 但是改用'test.wav'同样会提示错误

**Comment by blockdate** [comment]
app的版本是多少（icon 编号）

**Comment by nevermore-jia** [comment]
还有一个问题需要请教. 
调用Host.audio.startRecord这个录音模块，同样的配置参数，ios录音5秒的大小132816，安卓的大小是7256，文件大小差异比较大
![98101554190702_ pic_hd](https://user-images.githubusercontent.com/25736441/55385871-b3023b00-5560-11e9-9877-e7c50a3876a2.jpg)

**Comment by nevermore-jia** [comment]
168

**Comment by blockdate** [comment]
1. SDK 10003 可正常使用。
2. 文件大小这一块差异由系统差异引起的，建议单开一个issue讨论是否需要特殊处理。
