### ISSUE TITLE
iOS如何在插件中唯一确定该设备的蓝牙连接标识

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#487]
#### 环境
- 电脑操作系统:  Mac OS
- 手机系统:  iOS 12.1.4
- SDK分支:   master
- 相关模块:  miot/Bluetooth

#### 现象

平台文档介绍，ios蓝牙连接前需要先扫描，然后根据uuid连接，以下是文档中的demo：
      Bluetooth.startScan(30000,"1000000-0000-0000-00000000000");//扫描指定设备
      BluetoothEvent.bluetoothDeviceDiscovered.addListener((result)=>{
          bt = Bluetooth.createBluetoothLE(result.uuid||result.mac);//android 用 mac 创建设备，ios 用 uuid 创建设备
          this.connect();
      })
但是如果周围有多个同类设备，服务的uuid是一样的，就会扫描到多个设备，取最先扫描到的设备吗？
备注：android不存在这个问题，进入插件就能根据Device.mac拿到确定的mac地址然后连接

#### 期望

ios设备上，从首页进入某个确定的设备后，能在插件中唯一确定该设备的蓝牙连接标识，类似android Device.mac唯一标识一样.

**Comment by blockdate** [comment]
1.看你的提问，你们是普通蓝牙设备吗。
2.对于从来没有连接过的设备，iOS没有好的办法，因为无法获取到mac。(小米蓝牙协议中有这个的解决，在广播中带上mac)
3. 对于连接过的设备，可以存储设备的uuid，因为iOS在连接过一次之后，对于这一台手机，某个蓝牙设备的uuid便是固定的。

**Comment by dessmann** [comment]
问题1回复：是低功耗蓝牙设备
问题2回复：那这样的话，就有可能出现下面的情况：
我附近有两个设备，设备1和设备2，同时在线，我进入设备1用ios手机执行开门操作，有可能最终开门的是设备2.
请确认该现象是否正常
问题3回复：连接过的设备是可以保存uuid，但是在ios设备的插件里，并没有一个标识设备唯一性的参数与uuid建立映射关系，这样再次进入插件，是没法获取到uuid的
