### ISSUE TITLE
IOS创建虚拟设备之后，运行程序报错index.html找不到

### ISSUE THREAD

**Issue by chenzhuojie** [MiEcosystem/miot-plugin-sdk#488]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows]
- 手机系统:[iOS 12.0]
- SDK分支: [10002]
- 相关模块:[eg.Host/Service/Account]

#### 现象

IOS创建虚拟设备之后，运行程序报错index.html找不到，报错404，包括小米的Demo也是如此

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/49181603/55378511-d1aa0700-554b-11e9-99a0-e9456a88f5d9.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
确认下你使用的app版本编号是多少（icon上的数字）。

**Comment by chenzhuojie** [comment]
![image](https://user-images.githubusercontent.com/49181603/55383106-f3aa8600-5559-11e9-9dec-e72063ecc1b5.png)

是这个版本号吗，167

**Comment by blockdate** [comment]
我们这边尝试了167，可以正常使用。
建议提供一下信息：
1. 运行报错时手机端的错误信息截图
2. 运行报错时node js 端的日志截图
3. 手机端dev开发者设置的截图

**Comment by blockdate** [comment]
无反馈
