### ISSUE TITLE
能否提供时间选择控件

### ISSUE THREAD

**Issue by DaquanZhou** [MiEcosystem/miot-plugin-sdk#490]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
尝试使用(static) openTimerSettingPageWithVariousTypeParams(onMethod, onParam, offMethod, offParam)添加定时, 但是并不符合需求. 我们就自己开发定时界面, 使用rmc-date-picker和rmc-picker, 但是写出来发现安卓手机上很卡, 效果不理想.

#### 期望
能否提供一个时间选择的公用控件

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？
我尝试过使用rmc-date-picker和rmc-picker, 但是写出来发现安卓手机上很卡

**Comment by DaquanZhou** [comment]
![image](https://user-images.githubusercontent.com/16514238/55381749-716c9280-5556-11e9-95d8-36868617d216.png)

**Comment by DaquanZhou** [comment]
我想问下, 关于这个时间选择控件能否提供? 有计划吗?

**Comment by blockdate** [comment]
时间选择器正在排期开发中

**Comment by santcool** [comment]
上了SDK_10021，请体验。
