### ISSUE TITLE
蓝牙开门指令设置超时无效

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#492]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [eg.master/10000/...]
- 相关模块:[蓝牙]

#### 现象

没有连接到设备时，toggle，设置蓝牙响应时间无效
![image](https://user-images.githubusercontent.com/16306138/55391740-894f1100-556c-11e9-8475-7376fa6f72e5.png)

![image](https://user-images.githubusercontent.com/16306138/55391820-af74b100-556c-11e9-9aa0-981ada5f79b1.png)
连接到设备后，这条命令可以正常的开门，但是超时设置始终是没有效果的，

想确认，没有连接到设备的时候，调用开门的指令，这个超时的方法设置是否有效果
#### 期望

没有连接到设备的时候，调用开门的指令，超时的方法设置能够有效果，有响应

**Comment by blockdate** [comment]
这一个逻辑应该是在蓝牙未连接时直接返回错误，而不是走超时逻辑。

我们会做以下更新：
1. Android下支持超时操作。
2.JS端会在蓝牙未连接时直接返回错误

**Comment by lvjie0519** [comment]
@changgongxinshi   已修复，请使用最新apk进行测试，谢谢。
