### ISSUE TITLE
Service.security.loadSecureKeys接口数据异常

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#493]
Service.security.loadSecureKeys 方法在使用手机号调用Service.security.shareSecureKey方法添加分享用户后返回数据异常，使用userid添加的数据Service.security.loadSecureKeys返回是正常的，异常数据如下：
![image](https://user-images.githubusercontent.com/15190511/55399850-d3d98900-557e-11e9-8015-486edf72de22.png)

使用手机号调用Service.security.shareSecureKey方法添加分享用户时，Service.security.shareSecureKey的返回数据正常，如下图：
![image](https://user-images.githubusercontent.com/15190511/55399967-2b77f480-557f-11e9-8e70-718ea806eb5c.png)

**Comment by blockdate** [comment]
这个在接口参数和文档中应该体现的很明显了需要使用UID参数。
如果需要手机号获取UID的方发，请新开一个issue来进行讨论
