### ISSUE TITLE
一个非常奇怪的Bug，求协助！

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#494]
标题没法说清，这里详细描述一下：
项目中使用到了google-protobuf进行蓝牙数据包封装，将编译好的pb.js文件放到项目中并引用后，Android平台上会稳定出现不管在哪个界面按系统返回键都会直接退出插件的现象，但是蓝牙所有数据是可以正常传输和解析的，去掉引用后按返回键会立马正常。
出现的原因大概是这样，但是无法解释，所以无法解决。

之后我在com.xiaomi.demo这个官方demo中放入一个test_pb.js文件并引用后也会稳定出现返回键的问题。。
复现步骤如下，希望协助一下，感谢！
1:com.xiaomi.demo下安装protobuf module： npm install --save "google-protobuf"
2:下载protobuf编译工具：https://github.com/protocolbuffers/protobuf
    随便写一个test.proto进行编译;
    指令：protoc --js_out=import_style=commonjs,binary:. test.proto
    syntax = "proto3";
    message Test {
	    uint32 ch_no		= 1;
	    uint32 ch_type     	= 2;	
	    uint32 ch_power          = 3;	
   }

3:编译后会生成test_pb.js，将test_pb.js放入com.xiaomi.demo项目中，在MainPage.js中引用，
  const message = require('./test_pb');

加上这个引用后所有界面按返回键都会直接退出插件，注释引用后一切正常。
抱歉写了这么多，因为自己也花了好长时间，各种引用方式也试过了。希望米家开发人员可以协助一下。感谢！

**Comment by lvjie0519** [comment]
@ding209   把 test_pb.js  文件  修改下后缀为txt，上传下，我这边试试

**Comment by ding209** [comment]
[test_pb.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3036782/test_pb.txt)
@lvjie0519

**Comment by ding209** [comment]
@lvjie0519 你好，请问这个问题有进展吗？

**Comment by ding209** [comment]
@lvjie0519 @kyou @kangkai @zxconan 这个问题可以协助一下吗，我这边自己能想到的办法都试过了，感觉和米家App有关系。麻烦按我上面的步骤在com.xiaomi.demo中试一下，谢谢

**Comment by lvjie0519** [comment]
@ding209   你使用的是最新apk吗？  我这边测试，没发现问题啊

**Comment by ding209** [comment]
@lvjie0519 用的是最新的apk，我刚试了一下，在com.xiaomi.demo下安装google-protobuf并引用test_pb.js返回键的确还是有问题。

**Comment by lvjie0519** [comment]
@ding209 微信聊吧，微信号：18750118631

**Comment by lvjie0519** [comment]
测试发现，google-protobug貌似有监听hardwareBackPress事件，导致直接退出，你可以将你的Component继承至我们提供的 BaseCompoenet，或者在自己的Component中监听hardwareBackPress​
