### ISSUE TITLE
iOS打开插件调试，重启App，会直接报错

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#496]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS
- SDK分支: [eg.master/10000/...]master
- 相关模块:[eg.Host/Service/Account]

#### 现象

iOS打开插件调试，重启App，会直接报错，截图如下。测试App和SDK都是最新的。

#### 期望

没有报错

#### 其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/11364809/55457158-aa226f80-561b-11e9-85eb-00a8374edaa2.png)

**Comment by zaxayn** [comment]
猜测是App重启时，会先预加载RN模块？所以错误截图里面的地址localhost应该是开发者设置的IP地址，应该就行了

**Comment by blockdate** [comment]
这是商城模块共同使用了RN54导致的，我稍后会将商城模块禁用出一个新包。

**Comment by sofichael** [comment]
@blockdate IOS新的米家app包更新了吗？

**Comment by blockdate** [comment]
更新很久了

**Comment by sofichael** [comment]
从给的fir地址上下载下来的，还是有这个问题，还有个问题连接设备连上了，一会app就闪退了，也没相关日志信息
