### ISSUE TITLE
小米手机出现text显示英文时候显示不全

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/miot-plugin-sdk#498]
#before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[]
- 手机系统:  小米手机
- SDK分支: []
- 相关模块:[]

#### 现象

 ##小米手机出现text显示英文时候显示一半，中文正常。如图：
![6631554276808_ pic](https://user-images.githubusercontent.com/19943186/55467569-29bc3880-5634-11e9-803a-e5ed02cf6d91.jpg)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@wyc123456   
1、开发者选项打开  显示布局边界，查看下是否因为字符串超过控件大小导致？
2、如果没有解决请加微信，微信号：18750118631，详聊，谢谢。

**Comment by wyc123456** [comment]
解决了。Text要设置fontFamily属性，小米手机才能够完整显示字符串。不然就是要指定Text的宽度，具体原因不知道，应该是控件宽度不够引起的
