### ISSUE TITLE
Android 分享问题咨询，

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#499]
#### 现象

Android 分享设备给别人时有两个选项，其中有仅可查看，当选择这一项时我们改怎么处理呢 ？交互正常响应，但是不向设备发送指令么。 

#### 期望

期望SDK在内部给处理下

**Comment by lvjie0519** [comment]
@xuanxuandaoren   我这边测试，最新apk，对分享模块已经改版，不存在多个选项。
