### ISSUE TITLE
新的SDK中暂未找到“自定义场景”相关的接口

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#5]
新的SDK中暂未找到“自定义场景”与旧SDK中相对应接口，https://github.com/MiEcosystem/ios-rn-sdk#%E5%BC%80%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%87%AA%E5%8A%A8%E5%8C%96

**Comment by laohuang88** [comment]
自定义自动化参见入口
 https://miecosystem.github.io/miot-plugin-sdk/module-miot_Package-Entrance.html, 
https://miecosystem.github.io/miot-plugin-sdk/module-miot_Package.html

Entrance.Scene为自动化处理入口类型， Package.entryInfo为入口参数，请参照处理。
