### ISSUE TITLE
无法创建项目

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#500]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

无法用命令行直接下载SDK，下载提示权限不足，  文件直接下载后 无法创建项目
提示错误
20 error code ELIFECYCLE
21 error errno 1
22 error miot-workspace@1.0.2 create: `node bin/createProject.js "xxx.lfzwj.ios"`
22 error Exit status 1
23 error Failed at the miot-workspace@1.0.2 create script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. SDK项目为public的github项目，无法下载请检查自己的git使用指令问题。
2. 无法创建项目和脚本执行失败，建议删除node module文件夹之后重新运行 npm install。

如还有问题，及时回复
