### ISSUE TITLE
ios官网的米家启动插件报错，偶现，debug版本暂时没出现

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#503]
米家版本  4.14.102
![WechatIMG200](https://user-images.githubusercontent.com/38349220/55526240-d47d3700-56c6-11e9-9b61-a6994f88cdde.jpeg)
![Uploading WechatIMG201.jpeg…]()

**Comment by liuhaixu666** [comment]
请米家开发人员解释下，，为啥会出现啊这个问题，基本再点一次就好了

**Comment by liuhaixu666** [comment]
请米家开发人员解释下，，为啥会出现啊这个问题，基本再点一次就好了

**Comment by blockdate** [comment]
将设备分享至894158105，我们排查下问题。

**Comment by blockdate** [comment]
已处理
