### ISSUE TITLE
iOS 的蓝牙连接 有时收到 code -7 或 100，有时明明没连接接口isConnected ==true

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#504]
#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 11.0
- SDK分支: SDK10003
- 相关模块: Device Bluetooth

#### 现象

iOS 的蓝牙连接有两个问题：
### 1.  有时候明明没在连接中，调用 connect(0) 是告诉我

>  {code: 100, msg: "the bluetooth is connecting now, please waiting for a moment"}
### 或者是 设备就在附近，有广播，却得到：

> {message: "device not found", code: -7}

而我收到-7 时，用其他手机是可以看到设备的广播就在附近；
我收到100时，他可能并没有在 connecting 中，因为我等好久好久都没收到连接成功，再connect 还是 100 （很可能是先收到一次-7，一旦收到100之后每一次都会收到100了。）

### 2. 有时候明明未连接，调用 isConnected == true。

这个时候，我再调用 connect ，会立即进入then里，但是让它发现服务却没有任何回应。
这个时候，用其他手机是可以看到设备的广播就在附近的，而且可以连。
即时调用disconnect()后再连接也一样。

-----------------------

第一种情况偶尔发生，第二种情况发生在 OTA结束以后。
我们的OTA是在正常状态下发一个命令后设备重启，进入另一个状态OTA 结束后又回答正常状态

#### 期望

1. 应该可以连上。
就算有时候有问题，过一会再试也应该可以连接；
如果没有在连接中，不应该告诉我正在连接 （code 100）

2. 如果设备主动断开连接，isConnected == false，并可以连接设备。

#### 其他的上下文/日志/截图

{message: "device not found", code: -7}
{code: 100, msg: "the bluetooth is connecting now, please waiting for a moment"}

#### 尝试过的解决办法

重启蓝牙无效。好像 code 100 就是在 重启蓝牙 后开始收到
kill app再进入可以
Android 插件，相同代码，没有类似问题

### 正常情况下 设备主动断开连接 会收到 ：
centralManager didDisconnectPeripheral:  的日志。
但好像我们再OTA时在正常状态下发一个命令后设备重启后，没收到这个。

**Comment by dubiao** [comment]
我们的设备是OTA是MAC地址会变的那种。刚才发现个问题，正常模式下，设备UUID是 51Fxxx55E，这是对的（图1）。
![52301554373315_ pic_hd](https://user-images.githubusercontent.com/4001793/55548974-59884080-5707-11e9-9235-bbfc188aad7b.jpg)

我们进入OTA后，UUID 变成了 7C6xxxB62，这也是对的（图2）。
![52291554373315_ pic_hd](https://user-images.githubusercontent.com/4001793/55548978-5d1bc780-5707-11e9-8fc0-930471ac7338.jpg)

OTA结束后，还是有原来连接设备的代码：
bt = Device.getBluetoothLE() 
这时 bt 上打印出的详情里没有 UUID，但是执行 startDiscoverServices 后，log 里会显示 我是在  7C6xxxB62 上执行了DiscoverServices （图3）。

![52311554373315_ pic_hd](https://user-images.githubusercontent.com/4001793/55548988-6016b800-5707-11e9-9aa5-bd921e42b639.jpg)

但 7C6xxxB62 实际已经不在了，正常模式下 UUID 应该是 51Fxxx55E。

**Comment by dubiao** [comment]
目前 我是用 bt = Device.getBluetoothLE(); 取得正常模式下的设备，
用 var dfuble = Bluetooth.createBluetoothLE(this.dfuMac) 取得OTA模式下的设备，dfuMac 是通过scan 得到的一个确定是我们的设备的UUID
现在的感觉好像是 得到 dfuble 后，影响了原来 getBluetoothLE 得到的设备的UUID，导致问题（？）。

**Comment by blockdate** [comment]
1. 小米协议设备处于连接中时，会出现device not found错误
2. 错误100表示上一次连接未timeout，直接进行了下一次连接。
3. isConnected 为true表示没有接收到蓝牙断开连接的通知，常见操作是断连之后立马重连，此时原生断连通知还没有触发。
