### ISSUE TITLE
关于固件升级的问题

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#505]
#### 环境
- 电脑操作系统:  Mac OS
- 手机系统:  iOS 12.1.4
- SDK分支:   SDK_10003
- 相关模块:  miot/Bluetooth
-米家App：5.5.3测试版

#### 现象
关于固件升级，根据issue#497沟通的内容，该分支已经集成编译了Pilloxa/react-native-nordic-dfu插件，根据其官网介绍，进行dfu升级的代码如下：
`import { NordicDFU, DFUEmitter } from "react-native-nordic-dfu";

NordicDFU.startDFU({
  deviceAddress: "C3:53:C0:39:2F:99",
  name: "Pilloxa Pillbox",
  filePath: "/data/user/0/com.nordicdfuexample/files/RNFetchBlobTmp4of.zip"
})
  .then(res => console.log("Transfer done:", res))
  .catch(console.log);`
插件已经集成在SDK_10003分支了，但是亲测该代码执行后then与catch都收不到任何响应

#### 期望
当前环境使用Pilloxa/react-native-nordic-dfu插件能正常执行dfu升级功能

**Comment by RideShi** [comment]
你好，你们import { NordicDFU, DFUEmitter } from "react-native-nordic-dfu";进入插件又遇到了Native module cannot be null么？

**Comment by dessmann** [comment]
> 你好，你们import { NordicDFU, DFUEmitter } from "react-native-nordic-dfu";进入插件又遇到了Native module cannot be null么？

ios有这个问题，android的不报错，也没有任何响应，据官方回复，米家的app还没有集成dfu库，预计这周支持

**Comment by LiuMengzhou** [comment]
#497

**Comment by LiuMengzhou** [comment]
#497

**Comment by LiuMengzhou** [comment]
#497

**Comment by dessmann** [comment]
该问题仍然没有解决，调用后，固件升级进度的回调始终没有执行

特别说明：用android手机测试时，状态栏已经出现了升级通知

**Comment by LiuMengzhou** [comment]
统一在 #497 下面讨论，开那么多issue没意义

**Comment by dessmann** [comment]
#497 已经被关闭了，我这边没有重新打开的权限，你们打开下吧
