### ISSUE TITLE
苹果端如何下载离线测试包

### ISSUE THREAD

**Issue by lcyisgod** [MiEcosystem/miot-plugin-sdk#506]
我们的代码已经完成，现在需要让我们内部测试人员测试一下，请问该如何发布离线下载包，测试人员该如何进行下载测试。
这个问题出现在iOS端

**Comment by lcyisgod** [comment]
麻烦看到的大佬回复一下

**Comment by dessmann** [comment]
ios插件，如果不在同一局域网下面，无法访问页面，是否可以像android一样，通过线刷的方式刷入测试包？

**Comment by blockdate** [comment]
上传插件包到IOT网页平台上，开启白名单测试，使用对应的白名单账户即可以下载测试。
