### ISSUE TITLE
蓝牙设备需增加接口：判断蓝牙网关是否在线

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#507]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
蓝牙设备，上传信息到网关，快捷卡片上显示设备在线或离线，是怎么判断的？

#### 期望
能有一个接口，即app透一个接口出来，用于判断蓝牙设备是否网关在线，以便插件内网关状态和app一致 ！

#### 尝试过的解决办法
从服务器获取网关信息，判断时间戳，超过1天的就认为不在线，但总跟app不一致，不清楚app的判断机制，所以请提供接口最佳！

**Comment by Woody2016** [comment]
app端也是从服务器获取属性，判断时间戳，超过“12小时”就认为不在线的

现在app端没这么个通用的接口

**Comment by Banjiemin** [comment]
好的，这样的话，我就修改一下判断时间戳，不超过12小时的。
