### ISSUE TITLE
lot开发者平台上传.mpkg  文件一直显示在打包中

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#508]
#### 现象

lot开发者平台上传.mpkg  文件一直显示在打包中，
![image](https://user-images.githubusercontent.com/16306138/55540454-9cd9b380-56f5-11e9-9809-84235b3da5b1.png)

之前上传成功过，现在想要上新的版本，一直打包中
#### 期望

能正常上传，.mpkg  文件

**Comment by qinliduan** [comment]
最后有上传成功吗？我也遇到了一样的问题，刷新后显示打包失败！

**Comment by blockdate** [comment]
重新尝试上传，如果任然有问题，在此处回复，我们联系相关人员解决问题

**Comment by qinliduan** [comment]
> 重新尝试上传，如果任然有问题，在此处回复，我们联系相关人员解决问题

打包失败：
`{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":19386,"Complete":true,"Exit":22,"Error":null,"StartTs":1554707938372985816,"StopTs":1554707940116979732,"Runtime":1.74399398,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/projects/temp_c4b97945_5d42_4ff6_a4fc_8adda5516a0b","{ Error: ENOENT: no such file or directory, rename '/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/projects/temp_c4b97945_5d42_4ff6_a4fc_8adda5516a0b' -\u003e '/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/projects/Mijia-SensorDevice-Plugin/Plugins/device.plugin.smoke'"," at Object.fs.renameSync (fs.js:766:18)"," at compressing.zip.uncompress.then._ (/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/bin/makeBundleFromZip.js:118:16)"," at \u003canonymous\u003e"," errno: -2,"," code: 'ENOENT',"," syscall: 'rename',"," path: '/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/projects/temp_c4b97945_5d42_4ff6_a4fc_8adda5516a0b',"," dest: '/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1554707929985473692/compile/projects/Mijia-SensorDevice-Plugin/Plugins/device.plugin.smoke' }"],"Stderr":[]}`
