### ISSUE TITLE
希望 Service.smarthome.getUserInfo提供userid参数

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#509]
添加好友分享这部分，目前只能使用userid进行添加，希望可以使用手机号添加，提升用户体验

**Comment by blockdate** [comment]
处理中

**Comment by Woody2016** [comment]
这个目前就支持传手机号，请直接传手机号试试

**Comment by RideShi** [comment]
@Woody2016 已经试过，可以添加，但是使用手机号添加的分享用户，使用 Service.security.loadSecureKeys接口无法获取到该用户信息

**Comment by blockdate** [comment]
getUserInfo 目前以支持uid返回
