### ISSUE TITLE
打开debug手机就白屏，浏览器控制台打印如下

### ISSUE THREAD

**Issue by TianGuisen** [MiEcosystem/miot-plugin-sdk#510]
Access to fetch at 'http://localhost:8081/projects/com.xmsmart.xmswitch03/index.delta?platform=android&dev=true&minify=false' from origin 'http://192.168.1.102:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Uncaught (in promise) TypeError: Failed to fetch

谷歌浏览器

**Comment by blockdate** [comment]
跨域请求，修改浏览器访问地址和手机上设置的ip地址一致

**Comment by TianGuisen** [comment]
app-Dev Settings-Debug server host &port for device-写入为192.168.1.102:8081
是说这个ip要跟浏览器一样吗。我一直是一样的，不然都运行不起来。
开启debug后浏览器的地址是http://192.168.1.102:8081/debugger-ui/
