### ISSUE TITLE
安卓进不了插件

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#511]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

Android 最新版米家，插件用着用着就进不去了，一直停在这个界面，很多部手机都出现了这个问题。
![image](https://user-images.githubusercontent.com/7885251/55549823-5e4df400-5709-11e9-945d-0e2ff69cc36a.png)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@JxXiaoXie  麻烦提供下无法进入过程中的log日志

**Comment by lijian9088** [comment]
[log.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3053213/log.txt)

**Comment by lijian9088** [comment]
@lvjie0519

**Comment by lvjie0519** [comment]
检查下您的代码，是否与如下错误有关：
![image](https://user-images.githubusercontent.com/22487747/55850098-8d3eec80-5b85-11e9-927e-b357fabbf6dc.png)
