### ISSUE TITLE
SwRefreshListView添加renderSectionHeader相关问题

### ISSUE THREAD

**Issue by fosen** [MiEcosystem/miot-plugin-sdk#512]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Mac OS]
- 手机系统:[eg.iOS 12.0]
- SDK分支: [eg.master]
- 相关模块:[eg.    t]

#### 现象

使用xiaomi.demo中 SwRefreshListView 添加renderSectionHeader，报错

#### 其他的上下文/日志/截图
如图

![41554377396_ pic](https://user-images.githubusercontent.com/15226994/55554149-a888a280-5714-11e9-8425-e988f8052e75.jpg)

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

尝试去掉renderSectionHeader部分，显示正常了。

麻烦帮忙看下，是SwRefreshListView不支持SectionHeader吗？

**Comment by blockdate** [comment]
看日志是你的使用参数错误。

**Comment by fosen** [comment]
> 看日志是你的使用参数错误。

参数使用和xiaomi.demo中一致
 
![image](https://user-images.githubusercontent.com/15226994/55694279-10294100-59e6-11e9-82c0-0c8575a23e10.png)


![image](https://user-images.githubusercontent.com/15226994/55694296-26cf9800-59e6-11e9-9a26-b3ba426fc29e.png)

我想确认下SwRefreshListView支持SectionHeader吗？

**Comment by blockdate** [comment]
SwRefreshListView 系我们的同学从github上拉下来的项目代码，这一段仅作为demo展示使用，并不属于JSSDK的建议内容，如果有listview和scrollview的需求，建议在github上搜寻更加可靠的项目代替使用。
