### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#513]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1  米家版本 beta V4.15.101
- SDK分支: [eg.master/10003
- 相关模块:[eg.Host/Service/Account] dfu 升级

#### 现象

import { NordicDFU, DFUEmitter } from "react-native-nordic-dfu";

进入插件报错 Native module cannot be null

**Comment by RideShi** [comment]
@blockdate 你好，我查了下，这边报这个问题是需要手动完成Linking，iOS和安卓原生端需要配置的，请问这边需要如何处理呢

**Comment by LiuMengzhou** [comment]
@RideShi 安卓link完成，iOS正在

**Comment by RideShi** [comment]
好的，可以使用的时候，麻烦通知一下

**Comment by dessmann** [comment]
我们今天用最新的iOS包，SDK_10004分支的sdk也出现了这个问题

**Comment by LiuMengzhou** [comment]
#497

**Comment by LiuMengzhou** [comment]
@dessmann 
https://github.com/MiEcosystem/miot-plugin-sdk/issues/497#issuecomment-483113720

**Comment by dessmann** [comment]
好的 ，多谢
