### ISSUE TITLE
缺少获取设备自动化模板

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#514]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 12.1]
- SDK分支: [eg.master/10002/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

没有获取设备自动化模板的接口

#### 期望

提供获取设备自动化 动作或者条件 模板的接口，用于开发插件自定义自动化，类似iOS：
![image](https://user-images.githubusercontent.com/15864191/55676814-097bca80-590f-11e9-9488-c22b8c691eb4.png)

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by santcool** [comment]
已增加在SDK_10022，请更新SDK后使用。因此接口没有提供给其他人使用，故没有文档和demo。
使用方法如下：
Service.scene.loadSceneTemplate().then((res)=>{
    console.log(res);
}),catch((err)=>{
    console.log(err);
})
