### ISSUE TITLE
提供获取开发模式下preview,release,dev的环境接口

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#515]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

没有获取开发模式下preview,release,dev的环境接口

#### 期望

希望提供获取开发模式下preview,release,dev的环境接口，可以参考iOS：
![image](https://user-images.githubusercontent.com/15864191/55677295-a93d5680-5917-11e9-8f2e-41bc0fb5ceba.png)

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Woody2016** [comment]
需要此接口做什么？

**Comment by santcool** [comment]
经与PM沟通，暂无此必要
