### ISSUE TITLE
禁止直接访问自己的网络服务，需要进行后台对接，否则无法通过审核，详情请咨询米家后台工作人员。这个怎么对接呢

### ISSUE THREAD

**Issue by chenzhuojie** [MiEcosystem/miot-plugin-sdk#516]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

这个后台对接是如何对接的呢

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
发送邮件到wulei7@xiaomi.com 并附上你们要加的三方接口说明和用途
