### ISSUE TITLE
新框架这个接口(MHPluginSDK.callSmartHomeAPI("/user/del_user_device_data")用哪个

### ISSUE THREAD

**Issue by dylearning** [MiEcosystem/miot-plugin-sdk#517]
老的的框架上有这个接口，新的框架上没找到，只有，set，get，没有del，帮忙看看，谢谢
MHPluginSDK.callSmartHomeAPI("/user/del_user_device_data", params, (props) => {
  if (callback) {
    callback(props.code);
  };
});

(static) setDeviceData(params) → {Promise}
添加设备属性和事件历史记录，/user/set_user_device_data

(static) getDeviceData(params) → {Promise}
获取设备属性和事件历史记录，订阅消息直接写入到服务器，不需要插件添加.通下面的set_user_device_data的参数一一对应， /user/get_user_device_data

**Comment by blockdate** [comment]
更新sdk10004分支，delDeviceData 已添加
