### ISSUE TITLE
无法查询到设备上报记录

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#519]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

设备已经按照对象ID 0x000B和0x0007 分别上报了锁事件和门事件，但是在插件中获取不到对应的事件数据，以下是获取锁事件的代码片段：
![image](https://user-images.githubusercontent.com/28518884/55699588-001d5b80-59fe-11e9-8e6b-ad6c3b6ae19b.png)
Service.smarthome.getDeviceData(params)
            .then(result => {
                console.log(result);
})

#### 期望
在插件中能正常获取锁上报的事件数据

#### 尝试过的解决办法
尝试过将key的值修改为‘0x0007’、0x0007、7、'0x000B'、0x000B、11，都获取不到设备上报记录

**Comment by blockdate** [comment]
尝试更新SDK到10004，并使用getUserDeviceLog 接口

**Comment by blockdate** [comment]
暂无回复
