### ISSUE TITLE
蓝牙连接成功，但是services为空

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#52]
iOS，如题，连接方式完全仿照demo里蓝牙连接，我们的蓝牙设备是小米蓝牙协议设备

**Comment by dingshaoran** [comment]
demo 里链接成功之后 调用了 bt.startDiscoverServices  发现之后会在回调里收到 services

**Comment by Handby** [comment]
使用console可以打印出来services，alert就出不来，不过iOS这边打开远程调试老是崩溃呀😂
