### ISSUE TITLE
根目录modules中缺少“buffer” module

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#521]
#### 现象

项目中使用到了iconv-lite来对GBK中文解码，iconv-lite这个库我看到根目录modules中是有的，但是iconv-lite中引用了safe-buffer，safe-buffer又引用了buffer，根目录modules中却没有“buffer”这个module，导致平台打包会失败，
![1111](https://user-images.githubusercontent.com/15820075/55702403-1381f400-5a09-11e9-8269-4aa8011f7b2b.jpg)

#### 尝试过的解决办法

开发的时候为了调试一直在根目录modules中手动引用的“buffer”，但是这样会打包失败，所以尝试在自己项目目录下引用iconv-lite、safe-buffer、buffer，但是怎么尝试都行不通，本地调试都会报和上面一样的错误。

期望米家能在根目录modules中引用buffer。

**Comment by blockdate** [comment]
如果引用了三方的js库，不要安装在sdk的nodemodule下，而是要安装在自己的com.xx.xx的项目目录下，然后打包上传即可使用

**Comment by ding209** [comment]
@blockdate 你好，并不是我想引用buffer，iconv-lite这个库在sdk的nodemodule下本来就是安装的，但是这个module本身需要引用buffer，而sdk的nodemodule却没有安装buffer，所以才导致的打包失败。

我已经试过了在自己项目的根目录下分别或者全部安装iconv-lite、safe-buffer、buffer这几个module，但是依旧会报sdk的nodemodule的根目录下没有buffer，

这个问题我试好久了，并不是我没认真看开发文档造成的。

**Comment by blockdate** [comment]
将你上传的mpkg发送到邮箱wulei7@xiaomi.com

**Comment by blockdate** [comment]
确认是SDK打包部分忽略了Buffer部分的库，这边正在处理

**Comment by blockdate** [comment]
目前在10004上处理了该问题，建议在10004上测试使用，该版本app发布暂定于4月23日周二

**Comment by ding209** [comment]
OK，收到
