### ISSUE TITLE
关于云定时问题

### ISSUE THREAD

**Issue by fgb031102** [MiEcosystem/miot-plugin-sdk#522]
利用SDK中提供的定时功能，设置云定时操作
![image](https://user-images.githubusercontent.com/5464058/55702935-1aadff80-5a13-11e9-9ef1-9267ddd7783f.png)

当设置区间定时的时候，发现只有打开操作被执行了，关闭操作没有正常执行。

但是我单独设置开操作，或者关操作设备都可以正常执行。

请帮忙解决。

**Comment by lvjie0519** [comment]
1、请说明下平台，IOS or Android？

**Comment by fgb031102** [comment]
IOS or Android两个平台都是一样的。

**Comment by zanetti4** [comment]
设备开和关的指令命令字符串怎么是一样的？开的命令后面还有一个空格。

**Comment by santcool** [comment]
这种问题可通过抓包，对比参数的一致性来解决。
