### ISSUE TITLE
readFile读取文件失败问题

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#523]
下载ota升级文件，解压后 使用 Host.file.isFileExists发现文件存在，调用Host.file.readFile在catch中返回false，无失败msg

**Comment by RideShi** [comment]
![image](https://user-images.githubusercontent.com/15190511/55710652-a2007080-5a1d-11e9-8474-f76c5d1d24dc.png)
iOS上无法打开，安卓上测试可以读取出来

**Comment by blockdate** [comment]
提供下接口使用的调用方法

**Comment by RideShi** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/15190511/55711847-2ce26a80-5a20-11e9-833e-47d9d64509bd.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/15190511/55711829-205e1200-5a20-11e9-8b7f-f42c43a45e44.png">

**Comment by blockdate** [comment]
经检查，该问题系iOS下限制了读取文件的多层级问题，稍后会更新app。

**Comment by RideShi** [comment]
好的，麻烦了

**Comment by RideShi** [comment]
经验证，demo中可用，但是项目中还是不能读取文件，安卓和iOS上都是，iOS上txt文件可读取内容，.bin文件不行，安卓上都不能读取到内容
