### ISSUE TITLE
Android手机华为P9 Modal的颜色不能和状态栏同步

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#525]
#### 环境

- 手机系统:[Android 8.1]

#### 现象

![Screenshot_20190408-173518](https://user-images.githubusercontent.com/18681867/55714296-fd822c80-5a24-11e9-9327-7942317456aa.png)

#### 期望

状态栏背景和modal的背景一样

#### 尝试过的解决办法

https://github.com/listenzz/react-native-modal-translucent 

但不行，

**Comment by lvjie0519** [comment]
@xuanxuandaoren  其他手机一样吗？  附上一个正确的截图看看

**Comment by xuanxuandaoren** [comment]
@lvjie0519  
![Screenshot_2019-04-09-09-41-36-709_com xiaomi sma](https://user-images.githubusercontent.com/18681867/55767601-28639380-5aac-11e9-8367-189e816057b7.png)

这个是正常的 ，小米五

**Comment by lvjie0519** [comment]
@xuanxuandaoren    这个与Modal有关系吗？  不显示Modal的时候，是否一致？

**Comment by xuanxuandaoren** [comment]
@lvjie0519  和Modal 有关系的，不显示modal的时候是一样的，搜了下解决方案，就是modal 存在问题，但是需要在app上操作 下面是解决方案
https://github.com/listenzz/react-native-modal-translucent

**Comment by lvjie0519** [comment]
@xuanxuandaoren  react-native-modal-translucent依赖到原生的修改，您那边是不能直接 npm install的，我这边看下rn提供的modal。

**Comment by lvjie0519** [comment]
@xuanxuandaoren    你截的两个图是否截错了？  我没看出有什么区别，麻烦把问题描述详细些吧，谢谢。

**Comment by xuanxuandaoren** [comment]
### 看两个的状态栏 

<img width="1788" alt="WeChat8f5ffbdf26a01cdb0693ee5aa74d7b38" src="https://user-images.githubusercontent.com/18681867/61423022-bfa87480-a940-11e9-81ac-4f458a52d574.png">

**Comment by lvjie0519** [comment]
@xuanxuandaoren    麻烦添加下微信（微信号：sky-boy-0519），详聊下。
