### ISSUE TITLE
安卓里面tableView菜单跳转失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#526]
一个tableView菜单列表，代码如下
![WechatIMG1327](https://user-images.githubusercontent.com/18459414/55715652-c3665a00-5a27-11e9-8fd5-6371946aa883.jpeg)
界面如下
![WechatIMG1332](https://user-images.githubusercontent.com/18459414/55715688-d842ed80-5a27-11e9-87ee-677700c9209d.jpeg)
在ios里面点击跳转正常，但是在安卓里面点击跳转就崩溃，出现如下界面
![WechatIMG1330](https://user-images.githubusercontent.com/18459414/55715741-f7da1600-5a27-11e9-840e-b291be73b2bb.jpeg)

**Comment by lvjie0519** [comment]
请检查下是否与OTAPage 有关，例如在其他页面通过按钮点击方式来跳转到该页面试试，谢谢。
