### ISSUE TITLE
Android 最新安装包提示解析错误

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#527]
版本：SmartHome_Dev_62860_5.5.7_sdk.apk
下载地址：https://fir.im/MiHomeForAndroid

安装提示“解析失败”

**Comment by lvjie0519** [comment]
@EllisonYe  谢谢提醒，已从新上传，试试最新apk，谢谢。

**Comment by EllisonYe** [comment]
我找了你们最后一次commit的apk，使用正常，最新上传的我稍后再看看

发自我的 iPhone

在 2019年4月10日，上午9:02，小米-吕杰 <notifications@github.com<mailto:notifications@github.com>> 写道：


@EllisonYe<https://github.com/EllisonYe> 谢谢提醒，已从新上传，试试最新apk，谢谢。
