### ISSUE TITLE
安卓录制音频问题

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/miot-plugin-sdk#528]
before issue：（不用回答）
### IPA/APK 是否更新到最新？
是
### SDK 是否更新到最新？
是
### Check 文档了吗？
是
### 是否尝试搜索issue？
是
---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: [/10002]
- 相关模块:[Host/audio]

#### 现象

简单明了地描述一下实际的现象。
调用Host.audio.startRecord录制语音,设置采样频率AVSampleRateKey为14k和55k,录制出来的音频大小一样,没有区别. ios端没有此问题,猜测是安卓端录制音频的频率是固定的,没有根据设置的频率来录制

#### 期望
简单明了地描述一下期望的表现。
不同的才有频率录制出来不同的文件

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。
<img width="901" alt="image" src="https://user-images.githubusercontent.com/25736441/55772037-1fc78900-5abd-11e9-8194-d0f6d55696b5.png">

<img width="869" alt="image" src="https://user-images.githubusercontent.com/25736441/55772075-45549280-5abd-11e9-9be9-a48a8ba6d864.png">

#### 尝试过的解决办法

尝试过哪些操作？
尝试改变采样频率没有效果

**Comment by nevermore-jia** [comment]
查看文件属性后,安卓录制的音频文件采样速率都是8Khz,并非用设置的采样频率去录制的
<img width="838" alt="image" src="https://user-images.githubusercontent.com/25736441/55777825-b56e1300-5ad3-11e9-9e6d-a8aeef2dc732.png">

**Comment by lvjie0519** [comment]
@nevermore-jia  将 AVFormatIDKey设置为audioFormatMPEG4AAC  试试

**Comment by nevermore-jia** [comment]
AVFormatIDKey设置为audioFormatMPEG4AAC 直接录音抛出异常
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/25736441/55854425-40641180-5b97-11e9-9a7b-2d336de4793d.png">

**Comment by lvjie0519** [comment]
错误是权限问题造成的，已修复，请使用最新apk，同时你那边js需要主动获取对应权限，具体可以参考MHAudioDemo

**Comment by nevermore-jia** [comment]
更新了apk,不会抛异常,但是频率变了,不是设置的;并且文件变小了很多(相比ios录制的和安卓原生录制的)
<img width="665" alt="image" src="https://user-images.githubusercontent.com/25736441/56717046-65977900-676e-11e9-8479-64bbf140fa4f.png">

**Comment by lvjie0519** [comment]
@nevermore-jia 请加微信号：18750118631，详聊下，谢谢。

**Comment by lvjie0519** [comment]
@nevermore-jia   如果需要自定义 采用速率，请设置如下：AVEncoderAudioQualityKey: 'audioQualityMin',

**Comment by lvjie0519** [comment]
录音问题可参加如下issue。
https://github.com/MiEcosystem/miot-plugin-sdk/issues/811

**Comment by gaopingfly** [comment]
> 录音问题可参加如下issue。
> #811

你好，我看了#811和#528的回答，但问题依然存在。求解决。

主要原因是14000的采样频率不是标准频率，大部分Android设备无法支持，但ios却支持。
能不能提供一个将现有音频文件降频的方法？ 

例如录制了44100HZ的文件，转换成14000HZ的文件
用android的native方法实现可以参考如下网址
https://www.jb51.net/article/47132.htm
