### ISSUE TITLE
iOS Device.getSubDevices()报错

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#529]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[iOS]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Device]

#### 现象

iOS调用Device.getSubDevices()报错：TypeError: o.default.MIOTDevice.loadSubDevices is not a function

#### 期望

跟安卓一样能正常获取子设备列表

**Comment by blockdate** [comment]
fixed，稍后更新ipa至185，即可

**Comment by qinliduan** [comment]
> fixed，稍后更新ipa至185，即可

`更新ipa至185以后，调用不报错，但是并没有获取到子设备列表，而是走了失败的回调函数`Device.getSubDevices().then((res) => {
      console.log(res); // 没有进入这个回调
    }, (err) => {
       console.log(err); // 这里返回true
    })`
