### ISSUE TITLE
同一个手机连接多台机器，定时功能只能定一台

### ISSUE THREAD

**Issue by Jezong** [MiEcosystem/miot-plugin-sdk#530]
before issue：
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android & iOS]
- SDK分支: [master]
- 相关模块:[Host.ui]

#### 现象

我们使用`Host.ui.openTimerSettingPageWithVariousTypeParams()`方法跳转的原生的定时页面来给机器定时，已确定定时功能正常，能准时发送正确的指令，但是定时的机器有误：即同一个手机连接多台机器，定时功能只能定一台。

#### 期望

同一个手机能分别给不同机器定时，且互不交叉影响。

**Comment by lvjie0519** [comment]
1、请说明下平台，ios or Android or all？
2、一个手机连接多台机器，具体是什么意思？是分别进入不同的插件进行定时还是？

**Comment by Jezong** [comment]
1、iOS和Android都会
2、一台手机连接多台相同model的机器，用相同的插件控制定时。只要有一台定时了之后所有相同model的机器都会设置了对应的定时时间。但是定时时间到达后只有设置的定时时间的机器会响应。

**Comment by LWEN999** [comment]
请问下现在这个问题处理了吗？
