### ISSUE TITLE
iOS调用SingleChoseDialog控件无响应

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#531]
#### 环境
- 电脑操作系统: Mac OS
- 手机系统: iOS 11.0
- SDK分支: 10003
- 相关模块: ui模块
- 米家App版本：V4.13.102（登录地区：大陆地区）

#### 现象
iOS调用SingleChoseDialog控件无响应

#### 期望
iOS能正常调用SingleChoseDialog控件

**Comment by blockdate** [comment]
提供下JS使用方式，并尝试更新APP后尝试

**Comment by dessmann** [comment]
同样的代码，Android正常，iOS不正常，我尝试更新iOS安装包再试试

**Comment by blockdate** [comment]
无更多反馈
