### ISSUE TITLE
Detected problems with api compatibility

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#532]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

启动插件页面出现Detected problems with api compatibility dialog，使用非sdk 接口警告提示。

简单明了地描述一下实际的现象。

#### 期望
避免使用非APi接口，启动插件不会谈框提示。

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
不处理
