### ISSUE TITLE
Android 快捷卡片本地调试不生效的问题，如何看Log？

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#533]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

测试手机Redmi Note7

按照文档配置了mijia_card_config.txt 到手机根目录，最新的debug mijia Apk，启用了开发设置的调试。重启手机，但是还是不生效，负一屏卡片还是显示该设备暂无快捷操作。

config见附件。
[mijia_card_config.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3062621/mijia_card_config.txt)

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
有关卡片问题 请参见， 添加相关负责人微信进行沟通，谢谢！
https://github.com/MiEcosystem/miot-plugin-sdk/issues/469
