### ISSUE TITLE
新框架里MHPluginSDK.callSmartHomeAPI( '/yaokan/insertunmodel',....）用哪个接口？

### ISSUE THREAD

**Issue by dylearning** [MiEcosystem/miot-plugin-sdk#534]
以前的接口如下，帮忙解决，谢谢。
      
 MHPluginSDK.callSmartHomeAPI(
          '/yaokan/insertunmodel',
          {
            'device': MHPluginSDK.extraInfo.deviceType,
            'id': ++this.mCount,
            'brand': MHPluginSDK.extraInfo.brandName,
            'model': this.state.text,
          },
          (result)=>{
            //MHPluginSDK.showFinishTips('感谢您的反馈！');
            //MHPluginSDK.closeCurrentPage();
            Package.exit();
          }
          )

**Comment by blockdate** [comment]
已处理
