### ISSUE TITLE
ios 固件升级后回到设置界面，红点不能消失，因为读取的版本号还是老的，更新之前的

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#535]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

点击设置---通用设置---检查固件升级 ，升级固件成功，点击返回，回到 通用设置页面，检查固件升级红点还在，ios会出现这种情况，android 不会。

#### ios 固件升级成功后，可以立刻更新固件信息，

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by santcool** [comment]
请使用最新的RN里面的CommonSetting控件。旧的CommonSetting控件的bug不再处理。

**Comment by liuling60LL** [comment]
用了新的通用设置控件，固件更新回到设置页面，小红点还是不会消失，要刷新插件才能读取到最新的固件版本，还需要完成哪一步呢😂


 
---原始邮件---
发件人: "米家-iOS-张文锋"<notifications@github.com>
发送时间: 2019年6月17日(星期一) 中午11:37
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "Manual"<manual@noreply.github.com>;"liuling60LL"<1372111608@qq.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] ios 固件升级后回到设置界面，红点不能消失，因为读取的版本号还是老的，更新之前的 (#535)



Closed #535.

**Comment by zhuxinleibandou** [comment]
> 用了新的通用设置控件，固件更新回到设置页面，小红点还是不会消失，要刷新插件才能读取到最新的固件版本，还需要完成哪一步呢😂
> […](#)

老哥，这个问题解决了吗？100021版本，更新后红点不消失

**Comment by liuling60LL** [comment]
所有问题都已经解决了，产品也已经上线😄------------------ 原始邮件 ------------------
发件人: "zhuxinleibandou"<notifications@github.com>
发送时间: 2019年7月29日(星期一) 上午10:49
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "Ai-Thinker liuling"<1372111608@qq.com>;"Manual"<manual@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] ios 固件升级后回到设置界面，红点不能消失，因为读取的版本号还是老的，更新之前的 (#535)

**Comment by zhuxinleibandou** [comment]
> CommonSetting

最新的是100021版的吗？

**Comment by liuling60LL** [comment]
是100021版本的



---原始邮件---
发件人: "zhuxinleibandou"<notifications@github.com>
发送时间: 2019年7月29日(星期一) 中午11:04
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "Manual"<manual@noreply.github.com>;"Ai-Thinker liuling"<1372111608@qq.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] ios 固件升级后回到设置界面，红点不能消失，因为读取的版本号还是老的，更新之前的 (#535)


 
CommonSetting
  
最新的是100021版的吗？

**Comment by zhuxinleibandou** [comment]
> 是100021版本的
> […](#)

我也有这个问题，100021 升级后 小红点还有 - - 您是如何解决的最后？

**Comment by liuling60LL** [comment]
![image](https://user-images.githubusercontent.com/34119193/62020283-f316b900-b1f4-11e9-9945-59f565030ea9.png)
我用的是这个

**Comment by zhuxinleibandou** [comment]
> ![image](https://user-images.githubusercontent.com/34119193/62020283-f316b900-b1f4-11e9-9945-59f565030ea9.png)
> 我用的是这个

这个小红点需要手动判断的呀？ - - 好尴尬 - - 谢谢了老哥！
