### ISSUE TITLE
服务器上传测试包失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#536]
时间：2019-4-10  17：40  左右
 
问题： 插件打包后上传失败，提示服务器错误，试过几次都不行。。

**Comment by caojunhua** [comment]
今天又试了一下：出现超时
<img width="726" alt="屏幕快照 2019-04-11 上午11 00 54" src="https://user-images.githubusercontent.com/18459414/55927871-33075f80-5c49-11e9-8381-e6a9332614df.png">

**Comment by blockdate** [comment]
已反馈处理

**Comment by huanghaibing** [comment]
你好，请问这问题修复了吗？我这边还是 打包失败
