### ISSUE TITLE
Host.ui.openPrivacyLicense，安卓无法进入插件，米家卡死

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#537]
调用Host.ui.openPrivacyLicense，安卓无法进入插件，米家卡死
![901554902711_ pic_hd](https://user-images.githubusercontent.com/15190511/55883303-ab820800-5bd8-11e9-89e4-ca8d9ba7024b.jpg)
![921554902763_ pic_hd](https://user-images.githubusercontent.com/15190511/55883310-ade46200-5bd8-11e9-8c55-fd3cc6368f83.jpg)

**Comment by lvjie0519** [comment]
1、Host.ui.openPrivacyLicense 您是在哪里进行调用的？
2、有没有尝试通过一个按钮点击来执行该方法，是否存在问题？

**Comment by RideShi** [comment]
是在进入之后，首页的componentDidMount里面，使用按钮点击也是一样会出现这个问题，调用代码如下：
<img width="918" alt="image" src="https://user-images.githubusercontent.com/15190511/55948960-2c4a0e00-5c84-11e9-9b15-8b53a975ccef.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/15190511/55948983-35d37600-5c84-11e9-8ecc-009e0da330f7.png">
