### ISSUE TITLE
未找到MHPluginSDK.getDevicePropertyFromSrvCache和MHPluginSDK.getUserDeviceData等接口

### ISSUE THREAD

**Issue by shanchaojie** [MiEcosystem/miot-plugin-sdk#54]
如题,未找到MHPluginSDK.getDevicePropertyFromSrvCache和MHPluginSDK.getUserDeviceData等接口已经相关的替代性接口.请提供相关的替代接口或解决方案,谢谢!

**Comment by shanchaojie** [comment]
> 如题,未找到MHPluginSDK.getDevicePropertyFromSrvCache和MHPluginSDK.getUserDeviceData等接口已经相关的替代性接口.请提供相关的替代接口或解决方案,谢谢!

**Comment by zhuxinleibandou** [comment]
> 如题,未找到MHPluginSDK.getDevicePropertyFromSrvCache和MHPluginSDK.getUserDeviceData等接口已经相关的替代性接口.请提供相关的替代接口或解决方案,谢谢!

请问有MHPluginSDK.getDevicePropertyFromSrvCache相关替代的接口吗？或者有从云端获取数据的方法吗？
