### ISSUE TITLE
Host.ui.addOrCopyIR接口调用报错

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#540]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [master/10003]
- 相关模块:[host/ui/addOrCopyIR]

#### 现象

调用addOrCopyIR接口时报错“Can‘t find variable: isAndroid”。

#### 期望

能正常调用。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
更新SDK即可

**Comment by JobenTian** [comment]
我已经更新到主分支最新提交了，但是还是会出现这个问题。
commit 05ecd0342dd5f6cb254c38ffa1c98dbbe9f95335
Merge: 7ff4ba2 5b70925
Author: 吴磊 <wulei7@xiaomi.com>
Date:   Thu Apr 4 09:58:00 2019 +0800

    Merge branch 'SDK_10003'

**Comment by blockdate** [comment]
先在10003 操作，稍后更新到master
