### ISSUE TITLE
SDK_10004分支启动报错：Can't find variable: getStrings

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#541]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1
- SDK分支: SDK_10004
-米家App版本：5.5.7 (Build 62861) 

#### 现象

启动插件报错，报错截图如下：
<img width="611" alt="image" src="https://user-images.githubusercontent.com/28518884/55956670-109c3300-5c97-11e9-8fa4-ab7582feef47.png">

#### 期望

米家App版本：5.5.7 (Build 62861) 能正常启动SDK_10004分支的插件

**Comment by dessmann** [comment]
同样的环境，SDK_10004分支，用iOS手机测试，报错信息如下：
<img width="470" alt="image" src="https://user-images.githubusercontent.com/28518884/55966799-a9d54480-5cab-11e9-92d8-d7a4255ce53c.png">
iOS米家App版本号：4.15.101 (Build 4.15.101.1335)

**Comment by blockdate** [comment]
已处理，更新下SDK

**Comment by dessmann** [comment]
更新后还是有问题，报一样的错
