### ISSUE TITLE
智能场景进入失败，只有转圈动画

### ISSUE THREAD

**Issue by zyh427** [MiEcosystem/miot-plugin-sdk#542]
- 电脑操作系统:[/Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [10003.]
- 相关模块:[Package]

#### 现象

智能场景进入界面失败，只有转圈，没有其他报错：
Terminal提示如下：
error: bundling failed: NotFoundError: Cannot find entry file com.xiaoxun.imibabyios/Scene/index.ios.js in any of the roots: ["/Users/apple/Downloads/miot-plugin-sdk-SDK_10003","/Users/apple/Downloads/miot-plugin-sdk-SDK_10003/miot-sdk"]
    at DependencyGraph.getAbsolutePath (/Users/apple/Downloads/miot-plugin-sdk-SDK_10003/node_modules/metro/src/node-haste/DependencyGraph.js:316:11)
    at /Users/apple/Downloads/miot-plugin-sdk-SDK_10003/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:280:416
    at Generator.next (<anonymous>)
    at step (/Users/apple/Downloads/miot-plugin-sdk-SDK_10003/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:445)
    at /Users/apple/Downloads/miot-plugin-sdk-SDK_10003/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:11:605
    at process._tickCallback (internal/process/next_tick.js:68:7)

 BUNDLE  [ios, dev] com.xiaoxun.imibabyios/Scene/index.ios.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

#### 期望

正常进入Scene界面。

#### 其他的上下文/日志/截图
界面只有转圈，没有其他报错。
![image](https://user-images.githubusercontent.com/6069935/56009321-01a69680-5d12-11e9-8009-f81c765b228b.png)

#### 代码使用
参考的Demo，基本结构如下
index.js 中
switch (Package.entrance) {
    case Entrance.Scene:
        Package.entry(require('./Main/SceneMain'), _ => {
        });
        break;
    default:
        Package.entry(App, _ => {
        });
        break;
}

在Main目录下，有SceneMain.js文件。

**Comment by zyh427** [comment]
@LiuMengzhou

**Comment by blockdate** [comment]
这个是调试旧插件么

**Comment by zyh427** [comment]
@blockdate  是调试新插件哦。miot-plugin-sdk 10003分支

**Comment by blockdate** [comment]
我这边排查一下。

**Comment by zyh427** [comment]
@blockdate  这个问题可以了解到原因了吗？ 如果需要其他信息，可以微信沟通。微信号：zhuang42900

**Comment by ldezho** [comment]
![image](https://user-images.githubusercontent.com/12531667/56627968-9dbd8f80-667a-11e9-8518-cd34a96ad27e.png)
调试智能为什么会找这个文件啊，没有这个文件的。

**Comment by zyh427** [comment]
@ldezho

**Comment by zyh427** [comment]
感觉是目前的com.xiaomi.demo中的Scene写法似乎不能进入SceneMain界面。

**Comment by ldezho** [comment]
@zyh427 我之前是好的，最近进不去了。

**Comment by zyh427** [comment]
我这边是一直进不去的哦。参考我上面用SDK_10003的报错信息。和你说的报错应该是一致的。

**Comment by ldezho** [comment]
@zyh427 我说的之前是三四个月前可以，最近再试就不行了，应该是改代码了。

**Comment by zyh427** [comment]
嗯 麻烦继续查下原因了。

**Comment by blockdate** [comment]
自动化相关建议更新测试app至最新，使用SDK 10010。

参考 #647 #325
