### ISSUE TITLE
如何访问网络请求，需要访问open.io.mi.com服务器

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#543]
before issue：（不用回答）
### 是否尝试搜索issue？是
发现一个相关的MIService issue,但是我在新的sdk中没有找到。
---

#### 环境
- 电脑操作系统:Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [10002]
- 相关模块:[eg.Host/Service/Account]

#### 现象
目前有一个《厂商纬度kv配置存储》，app需要访问open.io.mi.com服务器，所以请教一下用sdk中的哪个网络请求模块？我搜素相关issue有一个MiService.smarthome.callThirdPartyAPI，但是不知道如何调用，希望可以请教一下，谢谢！

#### 期望

能顾访问open.io.mi.com服务器的接口

#### 其他的上下文/日志/截图
![QQ20190412-112305](https://user-images.githubusercontent.com/18374383/56010222-60214400-5d15-11e9-9041-da372538e62a.png)

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
将所有需要用到的接口以及说明发送一下

**Comment by zhuxinleibandou** [comment]
> 将所有需要用到的接口以及说明发送一下
API说明
接口:/app/v2/home/range_get_open_config
说明：
![说明](https://user-images.githubusercontent.com/18374383/56011247-4aae1900-5d19-11e9-9109-f8ca3c425156.png)

接口说明已附图片，麻烦您看下，谢谢！

**Comment by zhuxinleibandou** [comment]
> 将所有需要用到的接口以及说明发送一下

请问目前可以访问了吗？麻烦帮忙看一下，谢谢了～

**Comment by blockdate** [comment]
这个需要等到SDK_10005, 我们会尽快提供测试SDK,届时会在此通知

**Comment by zhuxinleibandou** [comment]
> 这个需要等到SDK_10005, 我们会尽快提供测试SDK,届时会在此通知

好的，希望能快一点提供，时间比较紧迫，非常感谢您～谢谢

**Comment by blockdate** [comment]
因版本发布延迟至下周二，目前SDK 10004已添加该接口，请更新尝试使用 

`Service.smarthome.getRangeOpenConfig(params)`

**Comment by blockdate** [comment]
因某些发版变更，该接口移动到版本10005下使用，App发布版本日期不变
