### ISSUE TITLE
如何让锁上报的事件跟推送相关联？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#545]
#### 现象
.配置好推送申请模板后如何，让锁上报的事件跟推送相关联？比如，我们上报了开锁事件，并且发送了如下邮件，配置好了模板，那么如何让米家app可以收到推送呢？还需要配置什么，让锁上报事件跟推送相关联吗？

#### 期望

能够让锁上报的事件跟推送相关联

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/16306138/56015525-ed6f9300-5d2b-11e9-9dd9-c7dd6e78d875.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这个请与产品接入的人员联系，这一块并不属于插件开发的部分了。
