### ISSUE TITLE
如何订阅设备事件？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#546]
#### 现象

无法订阅设备的上报事件，在sdk中看到如下代码，如果我想订阅锁的开门事件，该如何操作？我这边订阅的参数传“11”，是收不到订阅消息的。
![image](https://user-images.githubusercontent.com/16306138/56015610-31fb2e80-5d2c-11e9-9b1a-d9c171c64e0a.png)

#### 期望

能够成功订阅到设备上报的事件

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
确认下锁是否会上报event.xxx这种形式的事件至服务端。

**Comment by Banson-ZHANG** [comment]
锁是按照以下形式上传开门等事件，插件已收到开门消息，请问  订阅设备事件，锁是否也是按如下形式上报

 lock_event_t obj_lock_event;
    obj_lock_event.action = opcode;
    obj_lock_event.method = 0;
    obj_lock_event.user_id= get_mi_key_id();
    obj_lock_event.time   = time(NULL);

    mibeacon_obj_enque(MI_EVT_LOCK, sizeof(obj_lock_event), &obj_lock_event);
