### ISSUE TITLE
调用addOrCopyIR进入添加遥控器页面后无法完成遥控器的添加？

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#547]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10003]
- 相关模块:[Host/ui/addOrCopyIR]

#### 现象

调用addOrCopyIR进入添加遥控器页面后，按照指引匹配遥控器，确认设备有反应3次后仍无法添成功添加遥控器，而且一直在这个页面，设备端每次收到插件发送过来的ir_play后直接回复ok。请问是设备端需要特殊回复吗？还需要服务器后台进行什么配置吗？

#### 期望

能正常添加遥控器。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/46127660/56016281-4dffcf80-5d2e-11e9-8f4f-3f64c5ce7967.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by JobenTian** [comment]
这个问题目前是什么情况？需要更新米家APP吗？

**Comment by JobenTian** [comment]
现在已经确认是安卓APP的BUG是吧？估计什么时候可以更新测试版米家APP呢？

**Comment by JobenTian** [comment]
请问估计什么时候可以更新？

**Comment by lvjie0519** [comment]
@JobenTian   请给出您调用addOrCopyIR 具体代码，及将设备分享到894158105账号，告知下设备model，我这边调试下试试。

**Comment by JobenTian** [comment]
具体代码如下：
{
                'name': getString('device_more_add_remote'), 'func': () => {
                    Host.ui.addOrCopyIR(Device.deviceID, 0, [],  { create_device: true });
                },
            }, {
                'name': getString('device_more_duplicate_remote'), 'func': () => {
                    Host.ui.addOrCopyIR(Device.deviceID, 1, [],  { create_device: true });
                },
            }

设备model：moer.plug.mp32

设备已分享。

**Comment by christophermitchell070** [comment]
Go The Fuck Away Stupid Ass People

**Comment by JobenTian** [comment]
@lvjie0519 设备已经分享到指定账号，目前调试的情况怎样？有确认问题了吗？

**Comment by lvjie0519** [comment]
@JobenTian  请使用最新apk，试试？  我这边可以正常跳转

**Comment by JobenTian** [comment]
@lvjie0519 我使用5.5.13测试版apk，SDK也更新到0a6c18275c7b216625db8e048cf93ef5c98b928b，但是还是不能正常跳转。

**Comment by lvjie0519** [comment]
@JobenTian  刚更新了下apk， 下载最新apk再试试

**Comment by JobenTian** [comment]
@lvjie0519 apk更新到5.5.15测试版，SDK也更新到今天最新的了，还是一样的不能正常跳转。

**Comment by JobenTian** [comment]
@lvjie0519 更新后还是不能正常跳转，今天能帮忙再看一下吗？感谢

**Comment by lvjie0519** [comment]
@JobenTian  请添加微信（微信号：18750118631），详聊。

**Comment by JobenTian** [comment]
@lvjie0519 已经添加了，请通过一下。

**Comment by lvjie0519** [comment]
@JobenTian  线下已沟通，问题是否已解决？如已解决，请更新下解决方法，谢谢。

**Comment by JobenTian** [comment]
@lvjie0519 配置还未上线，待上线测试完成后，再总结解决方法。

**Comment by JobenTian** [comment]
问题已解决。
1.米家插件SDK更新到10003以上，米家APP更新到5.5.15以上；
2.保证设备端收到插件发送过来的ir_play后正确回复；
3.新增加的红外网关设备，需要向小米对应的项目经理申请添加红外遥控子设备到米家设备列表的权限，需要在服务器后台进行配置（重点）。
