### ISSUE TITLE
把锁具分享给别人，别人也算是锁具管理者吗？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#548]
#### 现象

简单明了地描述一下实际的现象。

我把锁具分享给B，B也算锁的管理者吗？，刚才测试了一下，B去开门，然后获取锁事件下的key ID，显示B也是锁具管理者。
![image](https://user-images.githubusercontent.com/16306138/56018489-d84b3200-5d34-11e9-8685-2d4023852f06.png)

分享用户是走的如下接口
![image](https://user-images.githubusercontent.com/16306138/56018604-2c561680-5d35-11e9-927e-e92805c08edb.png)

#### 期望

希望确认被分享人是否也算锁具管理者

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
普通用户的分享 不会是管理员。

**Comment by changgongxinshi** [comment]
Service.security.shareSecureKey
我是用的这个接口分享的用户，还有别的分享用户的接口吗？在lot平台上只找到这个接口可以分享用户

**Comment by blockdate** [comment]
接口是只有这一个，貌似你这应该是固件那边的问题。帮你转一下

**Comment by Copypeng** [comment]
应该是你们的嵌入式工程师把开锁事件配错了，自己 fix 即可。被分享者使用蓝牙连接开锁（ share secure key ）的事件不应该是锁管理员开锁事件。
