### ISSUE TITLE
iOS下调用发现服务的方法，找服务的回调无法执行

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#549]
#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 11.0
- SDK分支: SDK_10003
- 相关模块:蓝牙模块
- iOS米家App版本：4.15.101 (Build 4.15.101.1335)

#### 现象
iOS下调用发现服务的方法，调用方式如下：
ble.startDiscoverServices(ServiceUUID)
方法同步返回调用成功，但是找到服务的回调无法执行，回调方法如下：
BluetoothEvent.bluetoothSeviceDiscovered.addListener((blut, services) => {
        **//无法走到这里**
        console.log("bluetoothSeviceDiscovered", blut.mac, services.map(s => s.UUID), ble.isConnected);
    });
同样的代码，android是正常的

#### 期望

iOs调用发现服务的方法，能正常走到发现服务的回调方法里

#### 其他的上下文/日志/截图

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/28518884/56022318-f36e6f80-5d3d-11e9-929d-ce5a0d7b9c7d.png">
卡在画红线的那一步了

#### 尝试过的解决办法
同样的代码，用android手机测试，发现服务的回调正常，可以排除回调监听器注册的问题

**Comment by blockdate** [comment]
普通蓝牙使用，如需要监听蓝牙的相关事件，需要手动创建蓝牙uuid对应的设备，否则会被SDK部分拦截处理。
`const ble = Bluetooth.createBluetoothLE("a.b.c...")`
