### ISSUE TITLE
从米家服务器下载文件，没有找到对应的接口

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#55]
我们有一个配置文件放在米家服务器，之前是通过：
let getParams = {"name":"config_version","version":1,"lang":"en","app_id":"XXX"};
MHPluginSDK.callSmartHomeAPI("/device/getThirdConfig", getParams, (response) => {});
从米家服务器上获取需要的文件地址和版本号。

现在在新的SDK上通过callSmartHomeAPI的对应接口Service.smarthome.getDeviceData(getParams)拿不到我们想要的数据，麻烦看一下是不是还缺少对应的接口。

**Comment by pencilCool** [comment]
您好，请问您遇到的问题是iOS 和安卓两个平台都有出现吗？

**Comment by Handby** [comment]
@pencilCool   安卓iOS都不行，我自己的理解是缺少对应的方法，我们传的Params在SDK中没有方法是需要是上传这样的params。

**Comment by dingshaoran** [comment]
缺少这个的接口，刚刚添加了上传到 github，请更新后使用 getThirdConfig

**Comment by Handby** [comment]
@pencilCool 刚更新了SDK，进插件报了两个错误

1. evaluating _require(dependencyMap)RootDevice.mac
2.AppRegistry is not a registered callable module

**Comment by Handby** [comment]
@dingshaoran  看提交日志好像是bin/config下的transformer.js里能搜到关键字RootDevice.mac

**Comment by laohuang88** [comment]
请更新sdk，报错问题已修复。
