### ISSUE TITLE
react-native-nordic-dfu 无法使用

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#550]
使用react-native-nordic-dfu，iOS还需要配置一下 https://github.com/Pilloxa/react-native-nordic-dfu/issues/17
![2141555053952_ pic](https://user-images.githubusercontent.com/15190511/56022675-d25a4e80-5d3e-11e9-967f-177a38d10d29.jpg)

**Comment by LiuMengzhou** [comment]
统一在 #497 下面讨论，开那么多issue没意义
