### ISSUE TITLE
打包错误

### ISSUE THREAD

**Issue by gengzx** [MiEcosystem/miot-plugin-sdk#552]
打包错误：
{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":9528,"Complete":true,"Exit":1,"Error":null,"StartTs":1555135928030969090,"StopTs":1555135945029960489,"Runtime":16.99899144,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1555135917627030617/compile/projects/temp_8335f912_daf5_4ec6_925b_cd91c1b0fd29","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1555135917627030617/compile/bin/buildBundle.js --android --target /tmp/1555135928030917838/release/android com.fowad.airrtc","/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1555135917627030617/compile","","[MIOT]start to build android bundle for com.fowad.airrtc","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1555135917627030617/compile/projects/com.fowad.airrtc","","output /tmp/1555135928030917838/release/android","","Loading dependency graph, done.","","","error：","","error：Unable to resolve module `@api` from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1555135917627030617/compile/projects/com.fowad.airrtc/src/views/Main.js`: Module does not exist in the module map","","This might be related to https://github.com/facebook/react-native/issues/4968","To resolve try the following:"," 1. Clear watchman watches: `watchman watch-del-all`."," 2. Delete the `node_modules` folder: `rm -rf node_modules \u0026\u0026 npm install`."," 3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`. 4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","","error：",""],"Stderr":[]}

用到 第三方开发库：babel-plugin-module-resolver
.babelrc
{
  	"presets": ["react-native"],
  	"plugins": [
      	["module-resolver", {
			"cwd": "babelrc",
			"root": ["./src"],
			"extensions": [".js", ".ios.js", ".android.js"],
          	"alias": {
				"@components": "./src/components",
				"@api": "./src/api",
				"@config": "./src/config",
				"@resources": "./resources",
				"@views": "./src/views"
          	}
      	}]
  	]
}

package.json
{
    "name": "project-com-fowad-airrtc",
    "version": "1.0.2",
    "scripts": {
        "start": "node ../../bin/runProject.js"
    },
    "license": "ISC",
    "dependencies": {},
    "devDependencies": {
        "babel-plugin-module-resolver": "^3.2.0"
    }
}

**Comment by blockdate** [comment]
该库是否安装在自己的项目目录下并打包到mpkg文件中？
