### ISSUE TITLE
无法获取设备上报数据 字符串类型的获取不到

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#553]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] android 9.0
- SDK分支: [eg.master/10000/...] 10002
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

无法获取设备上报的数据值（类型为字符串时无法正常获取，其他的枚举类型能正常获取）

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

![1555153193178](https://user-images.githubusercontent.com/8141398/56078838-0c028680-5e1f-11e9-9def-659492c93727.jpg)
![1555153243664](https://user-images.githubusercontent.com/8141398/56078839-0c9b1d00-5e1f-11e9-8173-1538934ae5a8.jpg)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
看日志上上报的数据是存在value的，你的使用方法截全一点，并且将返回的对象都打印一下。
