### ISSUE TITLE
Loading Dialog 在iOS上无法手动取消

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#554]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

Andorid版本可以设置Cancelable，增加一个按钮，但是iOS除了超时，怎么取消呢？
另外，Android上虽然后手动取消按钮，但是却没有定义onCancel方法。
=====

miot/ui/LoadingDialog~cancelable
是否允许点击空白区域取消显示
Android Only

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
Loading的本意就是程序自己取消或者超时取消，如果需要手动消失，建议使用MessageDialog

**Comment by febird** [comment]
@blockdate Loading本身应该不带这样的本意。比如设备添加，除了超时、程序自身，用户突然不想等待了，应该有个取消（Android也是有的）。MessageDialog没有转圈的动画需要自己改吧。
