### ISSUE TITLE
#505 固件升级的问题还是存在 

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#555]
#505 关于固件升级的问题仍然存在，请重视，盼复！！！！！

特别说明：用android手机跑插件，SDK_10003分支，5.5.7的测试版本米家App，调用RN固件升级的接口，mac地址传入的是设备进入固件升级模式+1之后的mac地址，固件更新进度和状态的回调方法没有任何响应，但是接口执行之后，手机顶部状态栏已经出现了固件升级的转圈进度通知...

**Comment by LiuMengzhou** [comment]
统一在 #497 下面讨论，开那么多issue没意义
