### ISSUE TITLE
锁具重新注册后，did为什么不变？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#556]
#### 现象

把已经绑定的锁具，删除，再重新添加注册，进入到插件代码后，发现重新注册的锁具的did跟之前的一样，导致所有的数据都没有被删除。

#### 期望

重新绑定锁具后，能够生成不同的did

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
目前同一个设备解绑再绑定did并不会修改。

**Comment by changgongxinshi** [comment]
那用户把锁具删除了，如何能够清除之前  调用setDeviceData  接口保存的数据呢？

**Comment by blockdate** [comment]
SDK 10004 中增加了接口 `delDeviceData` 用于删除`setDeviceData`中的数据

**Comment by changgongxinshi** [comment]
那如果在米家app里面删除的设备，不是在插件里面，如何清空数据呢？每次重新绑定完，进入插件判断是否是第一次绑定，如果是绑定后进入，再调用 delDeviceData接口清空数据吗？

**Comment by dessmann** [comment]
我们现在遇到的问题是：
所有业务数据都是与设备绑定的，同一个设备解绑后再次绑定，did一样，查询到的数据是上次绑定的

想到的可能的解决方法：
是否有接口可以获取到设备绑定的时间？插件里每个请求的key都带上这个时间

**Comment by blockdate** [comment]
1. 通过`Service.smarthome.batchGetDeviceDatas(parmas)` 可以获取当前设备的属性，删除设备之后，数据会被清空。
2. 通过`Service.smarthome.getDeviceData(parmas)` 可以获取历史设备的所有属性，设备删除之后，数据不会清除。

目前 batchGetDeviceDatas 接口还未补全，稍后会补全剩余操作api提供使用。
