### ISSUE TITLE
readFileToBase64 android和iOS平台数据不一致

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#558]
#### 环境
ios 和android

#### 现象
Host.file.readFileToBase64的结果和iOS不一致，ios平台在76个byte后加入‘\n’字符，android则没有。

#### 期望
二个平台表现结果一致
 Host.file.downloadFile(response.url, fileName).then((result) => {
                if (result.path) {
                    Host.file.readFileToBase64(result.filename).then((base64Content) => {
                         ### **//base64Content 不一致**
                 }
               }
}

**Comment by blockdate** [comment]
这个是Android下没有使用[RFC2045](https://www.ietf.org/rfc/rfc2045.txt)中的规定 `The encoded output stream must be represented in lines of no more than 76 characters each.`  ，这边换行符应该不影响使用，如果存在对功能使用的影响，请再开一个bug问题的issue我们来处理。
