### ISSUE TITLE
关于Setting Demo使用问题

### ISSUE THREAD

**Issue by epaaskd17a4** [MiEcosystem/miot-plugin-sdk#559]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [SDK_10004]

#### 现象

使用以下网址进行Setting页Demo发生崩溃问题
https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10004/projects/com.xiaomi.demo/Main/tutorial/Setting.js

![IMG_0701](https://user-images.githubusercontent.com/15211057/56109704-46d1ff00-5f84-11e9-901d-7e5efd2b929e.PNG)

**Comment by LiuMengzhou** [comment]
你是直接复制整个`Setting.js`粘贴到你的项目工程里面？

**Comment by LiuMengzhou** [comment]
你运行`com.xiaomi.demo`看看吧
![image](https://user-images.githubusercontent.com/13726966/56119710-3e3af200-5f9f-11e9-9324-82c30dd234e8.png)
![image](https://user-images.githubusercontent.com/13726966/56119723-43983c80-5f9f-11e9-832a-df24c00ce507.png)
![image](https://user-images.githubusercontent.com/13726966/56119733-498e1d80-5f9f-11e9-9d12-dfc8b783bb2c.png)

是仿造 `Setting.js` 写，不是直接拿来用，可以直接拿来用的组件是 `CommonSetting`
