### ISSUE TITLE
smarthome接口问题

### ISSUE THREAD

**Issue by Braveleon** [MiEcosystem/miot-plugin-sdk#56]
miot/service/smarthome 这个模块下面的方法例如getDeviceData等调用，一直是reject，是不是接口还没开放？

**Comment by pencilCool** [comment]
您好，请问您遇到的问题是iOS 和安卓两个平台都有出现吗？

**Comment by dingshaoran** [comment]
已经很多开发者在用了，如果您不能理解 reject 的报错，请附上报错的log

**Comment by Braveleon** [comment]
就是一直什么都没返回，然后报了一个warning说可能是reject

**Comment by JxXiaoXie** [comment]
你的问题解决了吗？

**Comment by Braveleon** [comment]
还是报错

**Comment by JxXiaoXie** [comment]
我之前是因为传参方式错了导致的报错，改成下面这种就好了：
let data = {"did": Device.deviceID,
              "uid": Device.ownerId,
              "type": "type",
              "key": "key",
              "time": Date.parse(new Date()) / 1000,
              "value": "value"};
  Service.smarthome.setDeviceData(data).then(response => {
  }).catch(error => {
  });

**Comment by Braveleon** [comment]
谢谢，我里面去试试

**Comment by Aub1nLin** [comment]
@JxXiaoXie  你好，我原来的用
MHPluginSDK.callSmartHomeAPI('/user/get_user_coll', params, (response) =>{})来获取里面的数据，现在应该用哪个？怎么传参？

**Comment by Braveleon** [comment]
@Aub1nLin Service.smarthome. getUserColl调这个接口
