### ISSUE TITLE
不发送源码，怎么让用户体验到程序，在没上线前，而且用户不能连接我的源码

### ISSUE THREAD

**Issue by hc520messi** [MiEcosystem/miot-plugin-sdk#560]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
上传插件IOT平台，然后开启白名单测试，将用户加入你们的企业白名单即可

**Comment by hc520messi** [comment]
好的感谢，请问，我在苹果手机上运行正常，为什么在安卓机器上就会出现这个错误，




------------------ 原始邮件 ------------------
发件人: "wulei"<notifications@github.com>;
发送时间: 2019年4月15日(星期一) 下午5:19
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "云想衣裳花想容"<1395455317@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MiEcosystem/miot-plugin-sdk] 不发送源码，怎么让用户体验到程序，在没上线前，而且用户不能连接我的源码 (#560)




上传插件IOT平台，然后开启白名单测试，将用户加入你们的企业白名单即可

**Comment by zhuxinleibandou** [comment]
> 上传插件IOT平台，然后开启白名单测试，将用户加入你们的企业白名单即可

开启白名单测试后，点击设备 会提示“请升级至最新app”，可是app已经是最新的了。 我是iOS设备
