### ISSUE TITLE
异常提醒需要把接口封装下

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#561]
这是异常提醒走的接口：   @"/scene/idfy_get";

**Comment by blockdate** [comment]
已添加，使用 `Service.smarthome. getIDFY(params)`

**Comment by blockdate** [comment]
因某些发版变更，该接口移动到版本10005下使用，App发布版本日期不变 为下周二

**Comment by betterFuture** [comment]
Service.smarthome. getIDFY(params)这个借口怎么用 有文档吗 参数具体传什么
