### ISSUE TITLE
打包错误！

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#562]
{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":11791,"Complete":true,"Exit":1,"Error":null,"StartTs":1555310956409865426,"StopTs":1555310967055069338,"Runtime":10.645203971,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1555310949246208883/compile/projects/temp_7f330e88_b648_49c3_b512_6c363e2fadd3","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1555310949246208883/compile/bin/buildBundle.js --android --target /tmp/1555310956409826809/release/android com.miaomiaoce.thermo.t10","/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1555310949246208883/compile","","[MIOT]start to build android bundle for com.miaomiaoce.thermo.t10","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1555310949246208883/compile/projects/com.miaomiaoce.thermo.t10","output /tmp/1555310956409826809/release/android","","Loading dependency graph, done.","","","error：","","error：Unable to resolve module `react-navigation/src/views/StackView/StackViewStyleInterpolator` from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10000_1555310949246208883/compile/projects/com.miaomiaoce.thermo.t10/Main/index.js`: Module does not exist in the module map","","This might be related to https://github.com/facebook/react-native/issues/4968","To resolve try the following:"," 1. Clear watchman watches: `watchman watch-del-all`."," 2. Delete the `node_modules` folder: `rm -rf node_modules \u0026\u0026 npm install`."," 3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`. 4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","","error：",""],"Stderr":[]}

我已经尝试过后面提示的解决步骤，仍然不能解决问题。

**Comment by blockdate** [comment]
1. `StackView `是否依赖了native代码，如果有，那么是否是使用带有原生代码的SDK版本打包的
2. 如果没有依赖native，那么该库代码是否安装在project目录下，并且成功打包到mpkg中
