### ISSUE TITLE
获取室外aqi数据不对

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#563]
获取室外aqi， Service.smarthome.getAreaPropInfo()  返回数据不对

**Comment by blockdate** [comment]
该方法为获取location/weather，如果该接口不满足需求的话，之前是否有满足需求的接口？

**Comment by betterFuture** [comment]
是这样的 之前我们就用这个接口 是可以用的 最近才不可以用的

**Comment by blockdate** [comment]
这个接口目前没有过任何改动，你这边提供下接口参数与设备model，did，和预期的返回结果，我去咨询下后端开发人员
