### ISSUE TITLE
为什么在米家，app里面共享的设备用户无法通过 Service.security.loadSecureKeys，接口加载出来？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#564]
#### 现象

在米家app，里面分享用户，不能通过 Service.security.loadSecureKeys，接口加载出来

如下图：
用户1，是在米家app里直接分享的，
用户2，是在插件里调用  Service.security.shareSecureKey，分享的
![image](https://user-images.githubusercontent.com/16306138/56115943-2e1f1480-5f97-11e9-84ad-5f22d81c6bcd.png)

![image](https://user-images.githubusercontent.com/16306138/56116041-6292d080-5f97-11e9-9ade-320dd549b72c.png)

然后调用Service.security.loadSecureKeys接口，只能加载到共享的用户2，无法加载到共享用户1

#### 期望
如何加载到在米家app里共享的设备用户

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 确认下在iOS下使用native的分享与接口的分享数据也不同步

@lvjie0519 查看下这个问题，看是否native使用了其他接口实现

**Comment by changgongxinshi** [comment]
ios也是同样的问题，刚确认过

**Comment by changgongxinshi** [comment]
请问有什么进展吗？这个问题

**Comment by blockdate** [comment]
经确认后，app端原生的分享是分享设备，而shareSecureKey 是锁类安全设备使用的分享功能，后者不可以获取到前者的分享人员。
