### ISSUE TITLE
andorid 体验太差

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#565]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.1
- SDK分支: [eg.master/10000/...]
10003
- 相关模块:[eg.Host/Service/Account]

#### 现象

用sdk写了一个简单的页面，纯界面没有其他任何逻辑，发现只要有按钮点击的地方，卡顿非常明显，点下去大概要一秒左右才会响应点击事件

#### 期望

能流畅的完成操作

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
插件调试的时候没有必要建议关闭remote debug，hotreload等所有跟远端更新相关的功能，确保局域网环境畅通，这些都会影响调试流畅度。

可以自己尝试打包上传之后测试白名单下载插件之后的流畅度。
