### ISSUE TITLE
MIoT返回的错误代码在文档中的错误代码列表上找不到

### ISSUE THREAD

**Issue by 70maililei** [MiEcosystem/miot-plugin-sdk#566]
#### 环境
- 电脑操作系统:[其他-网络访问API]
- 手机系统:[其他-网络访问API]
- SDK分支: [其他-网络访问API]
- 相关模块:[其他-网络访问API]

#### 现象

MIoT返回的错误代码在错误代码列表中找不到。
错误代码列表参考：
https://iot.mi.com/new/guide.html?file=07-云对云开发指南/02-应用云对云接入/02-小米IOT控制端API#/
（四.状态码   zzz-错误代码）

例如：
情况1：
https://api.home.mi.com/api/v1/devices
使用错误的accesstoken：
返回：
96008  token无效或已经过期

情况2：
https://api.home.mi.com/api/v1/action
使用不在用户名下的设备DID（设备已经从该用户名下移除）
返回：
-704010000 "generic unauthorized

以上两种情况，与文档中相差很大

#### 期望

返回的错误代码在文档中可以查到具体含义。

**Comment by blockdate** [comment]
这个问题去云对云接入的项目提问吧，这里不处理非插件开发的问题
