### ISSUE TITLE
蓝牙开门后，设备端接收到的用户id无法对应小米账号

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#567]
#### 现象

蓝牙开门后，设备端收到的用户ID为：1441738445
但是该用户ID却不是当前登录米家App的用户ID

#### 期望

1、蓝牙开门后，设备端收到的用户ID是当前登录米家App的用户ID
2、帮忙查询一下1441738445这个ID在米家系统中是否存在

**Comment by blockdate** [comment]
通过Service.getUserInfo(idortel)可以获取用户基本信息
