### ISSUE TITLE
查询设备上报的锁事件，只有keyID，没有对应的名称

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#568]
#### 现象

设备上报的锁事件，协议如下：
<img width="421" alt="image" src="https://user-images.githubusercontent.com/28518884/56177066-ee583b80-602f-11e9-9c56-1ec40efb55be.png">
协议中只有keyID，没有对应的指纹、密码、用户的名称，插件里显示开门记录时，无法显示相应的名称

#### 期望

有个接口可以替代getDeviceData现有的功能，能获取到带有keyID名称的记录

#### 尝试过的解决办法

保存指纹密码时，已按照约定的协议

<img width="685" alt="image" src="https://user-images.githubusercontent.com/28518884/56177458-49d6f900-6031-11e9-90a7-880f0c3f2d8a.png">

向服务器保存过指纹和密码对应的名称

**Comment by blockdate** [comment]
1. 你需要的数据应该通过setDeviceSetting 设置到米家服务器中
2. 根据keyid的标识符，通过getDeviceSetting 获取之前设置的配置，并用于显示处理

**Comment by changgongxinshi** [comment]
不太理解，如果用户是蓝牙开锁，下图红框内的四个字节是用户的id，那么我怎么根据用户的id来获取用户的昵称呢？
根据上面的回复，我要把每一个用户的昵称跟id，都用setDeviceSetting 来存起来？？如果要存，又什么时候存？每次分享用户的时候存吗？太麻烦了吧？？
![image](https://user-images.githubusercontent.com/16306138/56179461-64f93700-6038-11e9-9134-0095e7358b32.png)

**Comment by blockdate** [comment]
如果你有用户的uid，根据Service.getUserInfo(id) 可以获取用户简略信息

**Comment by changgongxinshi** [comment]
那如果一个开门记录列表，有200条数据，要调用200次这个Service.getUserInfo(id) 接口吗？不会太卡顿吗？

**Comment by blockdate** [comment]
目前还没有提供批量获取用户数据信息的接口，这边如果对这个接口有需求的话，可以新建一个issue提需求

**Comment by dessmann** [comment]
需求是这样的，开门记录页面，需要显示 开门人的身份  开门方式 开门时间 这三个信息
开门人的身份需要显示中文昵称，但是查询锁上报的事件里面，开门人的身份是一个Key ID，满足不了页面显示的需要，如果对每一条记录都调用Service.getUserInfo(id) 来获取昵称，性能会很差，一般也不会这样处理列表数据的吧
希望有个接口可以获取可读的开门人的身份  开门方式 开门时间 这三个信息
