### ISSUE TITLE
Service.smarthome.getUserInfo返回的数据不完整

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#569]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

![1555389735544](https://user-images.githubusercontent.com/12531667/56182548-48afc700-6045-11e9-98a5-99eb9cecd02e.jpg)
通过截图可以看到你们接口内部是拿到了userid的，但是返回给我们的时候，没有了这个参数。

上面的第一段log是小米SDK中的打印，下面的第二段log是我通过Service.smarthome.getUserInfo获取的数据的打印

#### 期望

可以返回userid

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
userid在10004版本下添加了返回

**Comment by blockdate** [comment]
#509
