### ISSUE TITLE
开灯进入插件后再退出插件，来回进入多次后出现关灯页面，此时点击按钮均无反应，且页面不会主动获取属性信息

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#570]
#### 环境

- 手机系统:[iOS:4.15.101]
- SDK分支: [eg.master/10003/...]

#### 现象

开灯进入插件后再退出插件，来回进入多次后出现关灯页面，此时点击按钮均无反应，且页面不会主动获取属性信息，掉用米家底层相关api都不起作用了

#### 期望

反复进入rn sdk 可以适用

**Comment by blockdate** [comment]
分享设备至894158105，并在此表明一下设备。

**Comment by blockdate** [comment]
长时间无反馈
