### ISSUE TITLE
撤销"使用条款和隐私协议"，页面报错

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#571]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.IOS:4.15.101
插件：5
iPhone6s Plus]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.灯重置后与米家APP建立连接 
2.进入插件主界面，点击"..."-->"使用条款和隐私政策"-->撤销"使用条款和隐私协议"授权-->选择"确定"撤销授权
3.页面显示报错信息

#### 期望

页面可以正常撤销隐私

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这个是已知问题，请更新测试app以及SDK
