### ISSUE TITLE
在设备列表页面给相同设备名称的设备创建快捷方式，提升创建成功，但是桌面只有一个

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#572]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android:5.5.10]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

1.使用米家APP连接1号台灯，修改设备名字为"读写台灯"，创建快捷方式成功，桌面有相应的快捷方式
2.再次使用米家APP连接2号台灯，修改名字为"读写台灯"，此时创建快捷方式提示成功，但桌面实际无相应的快捷方式

简单明了地描述一下期望的表现。

不同的设备，但是名称相同，都可以创建各自都快捷方式

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
请等待米家native端解决，如解决会及时反馈，谢谢。

**Comment by lvjie0519** [comment]
经排查，这是系统问题，不允许相同的名称存在，不在解决范围，谢谢。
