### ISSUE TITLE
立即体验"进入插件的过程中会先出现一次黑屏再进入插件

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#573]
1.灯待连接状态，点击米家连接设备
2.成功后，按引导操作点击"立即体验"进入插件的过程中会先出现一次黑屏再进入插件

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[三星S7手机，VNS-AL00]
- SDK分支: [eg.master/10003/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
1.灯待连接状态，点击米家连接设备
2.成功后，按引导操作点击"立即体验"进入插件的过程中会先出现一次黑屏再进入插件

**Comment by lvjie0519** [comment]
@annageng  请使用最新apk，再次进行测试，谢谢。

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请新提issue，谢谢。
