### ISSUE TITLE
连接设备的时候，选择路由器列表中，同一个wifi出现在可用列表和不可用列表中

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#574]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android:5.5.6]
- SDK分支: [eg.master/10003/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.点击APP首页右上角添加设备按钮
2.扫描到设备后，点击设备进入选择路由器页
3.点击连接其他路由器，在"附近路由器"列表中出现的wifi也会出现在下方置灰列表中

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng 请使用目前最新apk，是否有此问题？我这边无法复现

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请新提issue。
