### ISSUE TITLE
第一次成功连接设备成功后，修改设备名称，删除全部文字，点击下一步无反应

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#575]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android:5.5.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.灯待连接状态，点击米家连接设备
2.成功后，按引导进入第二步修改名称，点击右侧x删除全部文字，此时名称为空无任何提示，并且点击下一步无反应

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这个问题并不不属于插件范围内。
