### ISSUE TITLE
反馈问题内容为空，可以提交成功

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#576]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android:5.5.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

在Android端点击反馈问题，当反馈的内容全部为空也可以点击提交并显示提交成功

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng 反馈页面，只要发送问题日志勾选上，就会提交，联系方式和内容是可选性，设计如此。
