### ISSUE TITLE
设置开启时间后点击取消，再点击右上角确定，定时可以成功保存

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#577]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.点击插件右上角…，再点击台灯设置
2.点击自动开关，点击下方添加定时，设置开启时间后点击取消，显示未设置时间
3.再点击右上角确定，定时可以成功保存，时间为次日的当前时间

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 定时是使用的SDK提供的`openTimerSettingxxxx`这个方式么
2. 是双平台还是单平台出现这个问题

**Comment by blockdate** [comment]
无反馈
