### ISSUE TITLE
添加定时，首次设置重复为'每天'成功，之后重复切换为“法定工作日”或者“法定节假日”，每天不起作用

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#578]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android:5.5.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.点击插件右上角…，再点击台灯设置
2.点击自动开关，点击下方添加定时，首次设置重复为'每天'
3.切换重复频率为“法定工作日”或者“法定节假日”后点击确定，返回上一页显示正常；
4.再切换重复频率为“每天”时，点击确定回到上一页，只显示频率为“法定工作日”或“法定节假日”，"每天"不生效

Android:5.5.0

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng  apk有更新，请使用当前最新apk，再次进行测试，谢谢。

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请新提issue，谢谢。
