### ISSUE TITLE
设置定时开关成功后，可以看清提示内容

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#579]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.点击插件右上角…，再点击台灯设置
2.点击自动开关，设置一个定时开关
3.定时生成后，右侧开关打开，点击关闭/开启已设置的定时，下方会有一个弹框，但是消失太快，无法看清提示内容
Android:5.5.0
#### 期望

可以看清提示内容

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng  请给出关键代码，我这边测试下

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，如有问题，再次reopen。
