### ISSUE TITLE
Service.account.ID相关

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#58]
![wechatimg71](https://user-images.githubusercontent.com/12531667/49056053-e8a2ba80-f234-11e8-8a02-0a7712b602e3.jpeg)
![wechatimg73](https://user-images.githubusercontent.com/12531667/49056171-7e3e4a00-f235-11e8-8619-916db74b3a12.jpeg)

Service.account.ID在load之前可以拿到，load内部反而是undefined，这样正常吗？
且nickName有时可以正确获取，有时为0长度字符串。

**Comment by dingshaoran** [comment]
android 未发现你说的问题，请用 log 输出，不要打断点看数据，有可能不准确


  Service.account.load().then((res)=>{
        console.log(res,Service.account.ID,Service.account.nickName)
    })

11-27 11:27:55.679 29402-30886/com.xiaomi.smarthome:plugin0 I/ReactNativeJS: {}, '894158105', 'test_nick_name'

**Comment by dzonel** [comment]
我用的是iPhone6，没有打断点，就是用的log输出。

**Comment by pencilCool** [comment]
该问题已经修复。稍后更新iOS 的ipa 包

**Comment by pencilCool** [comment]
该问题已经修复。我们从js 里面更新。直接拉取最新的github中的sdk 就可以了

**Comment by dzonel** [comment]
ID有了，但是nickName还是会有高概率为0长度字符串

**Comment by pencilCool** [comment]
有些账号的nickName 从服务端返回的就是空的

**Comment by dzonel** [comment]
@pencilCool  nickName正常不应该有值就一直有，没值就一直空吗？像这种偶尔有，偶尔为空的该怎么处理？

**Comment by laohuang88** [comment]
标识为匿名或其展示帐号ID如何？

**Comment by dzonel** [comment]
@laohuang88 您好，nickName有值的话不能一直返回相应的值吗？

**Comment by laohuang88** [comment]
我们检查一下相关逻辑，一般来说我们是透传的。

**Comment by dzonel** [comment]
@laohuang88 旧SDK也有这个问题，只不过旧SDK发生率极低，新的很高。

**Comment by dzonel** [comment]
MIOT SDK中miot/host/file下的Example中有多处错误，直接用了Host.而不是Host.file.进行调用。

**Comment by blockdate** [comment]
@dzonel 谢谢提醒，我们会尽快修正

**Comment by dzonel** [comment]
@laohuang88 您好，这个问题还是存在的，怎么被关了？
