### ISSUE TITLE
修改设备名称，不修改内容，提示修改成功

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#580]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.进入插件，点击右上角…
2.进入通用设置页后，点击设备名称
3.弹出修改设备名称提示框，不做任何修改点击确定，提示修改名称成功

ios  V4.14.101

#### 期望

没有修改内容，不应该提示修改名称成功

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by santcool** [comment]
已修改，将近版本SDK_10021。另外，推荐使用RN的CommonSetting控件，老的通用设置页即将废弃。
