### ISSUE TITLE
进入设备时区，选择某一时区后(如北京)，此时自动返回至上一页，设备时区后显示Asis/Shanghai

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#581]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.设置米家APP语言为简体中文
2.进入插件后，点击右上角…，点击通用设置并选择进入设备时区，选择某一时区后(如北京)，此时自动返回至上一页，设备时区后显示Asis/Shanghai

Android:5.5.0

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng  修改设备时区后，我们会发送一个事件deviceTimeZoneChanged，携带时区更改后的信息，具体请参加xiaomi.demo中的MoreMenu.js文件。

**Comment by lvjie0519** [comment]
issue不活跃，暂时先关闭，如还有问题，再reopen。

**Comment by TongAlisa** [comment]
@lvjie0519 我们飞利浦的开发人员有调用你说的这个接口，但是选择北京后仍旧显示Shanghai,而不是Beijing
