### ISSUE TITLE
点击桌面创建的快捷方式，此时整个系统界面卡住，桌面变黑，几秒后才能进入插件

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#582]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1.进入插件后点击右上角…,再点击通用设置
2.选择添加到桌面，提示创建快捷方式成功
3.点击Home键回到桌面，点击桌面快捷方式此时整个系统界面卡住，桌面变黑，几秒后才能进入插件

Android:5.5.0
MIX3、小米8、小米6X

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@annageng 请再次使用最新apk试试，是否还存在问题，我这边无法复现。

**Comment by lvjie0519** [comment]
issue不活跃，此处关闭，如还存在问题，请从新提issue，谢谢。
