### ISSUE TITLE
关于固件升级在安卓上的bug

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#583]
各位好，我现在的固件升级过程中，在ios上是可以顺利升级完成的。但是在安卓上升级中会遇到一个bug。
升级通信发送数据包（共分成3000多个数据包）的核心代码如下：
![image](https://user-images.githubusercontent.com/18459414/56189258-10ff4a00-605a-11e9-932b-e404ab631c37.png)
在ios上的打印一切正常，；部分如下：
![image](https://user-images.githubusercontent.com/18459414/56191155-69384b00-605e-11e9-91ab-765f6f21a12c.png)
在安卓上的打印，在发送第一个数据包的时候有一个警告信息，后面没有打印这个警告信息。
Possible Unhandled Promise Rejection (id: 0):
如下：
![image](https://user-images.githubusercontent.com/18459414/56191260-a0a6f780-605e-11e9-994f-3b6288452ffb.png)

最后在安卓整个升级过程中，数据包发送完毕了，中间每次都会回复成功信号，升级已经完成99%了，然后再发送endSignal给下位机，这个时候，下位机回复升级失败的信号。

不知道是RN这个机制在安卓平台和ios平台导致的问题还是其他问题呢？

谢谢！

**Comment by lvjie0519** [comment]
@caojunhua 升级已经完成99%了，然后再发送endSignal给下位机，这个时候，下位机回复升级失败的信号。

---------------------------------------------------

有具体的失败信息吗？关于蓝牙这一模块，建议使用 Android Studio Logcat 关键字 miio-bluetooth 过滤下日志看看，会输出原生层的log日志。

**Comment by caojunhua** [comment]
> @caojunhua 升级已经完成99%了，然后再发送endSignal给下位机，这个时候，下位机回复升级失败的信号。
> 
> 有具体的失败信息吗？关于蓝牙这一模块，建议使用 Android Studio Logcat 关键字 miio-bluetooth 过滤下日志看看，会输出原生层的log日志。

您好，回复的信息是04，根据和硬件工程师讨论的结果的是，下位机对文件crc校验失败，我今天抽时间过滤一下log看看，谢谢

**Comment by caojunhua** [comment]
> @caojunhua 升级已经完成99%了，然后再发送endSignal给下位机，这个时候，下位机回复升级失败的信号。
> 
> 有具体的失败信息吗？关于蓝牙这一模块，建议使用 Android Studio Logcat 关键字 miio-bluetooth 过滤下日志看看，会输出原生层的log日志。

![Snip20190417_1](https://user-images.githubusercontent.com/18459414/56269686-ce577380-6126-11e9-83ed-7cc486b70dae.png)

您好，我这是发送数据在Android studio上的截图log,红色框内是最后收到的04，根据蓝牙升级协议，04是下位机校验结果失败的意思。
其中：value = 0000000000000000000000000000000000000000fc 
是发送的最后一条信息，fc是文件crc校验后拼接上去的值。
value = 000000fe 是endSignal

目前ios升级没有问题，升级速度也只需要20秒左右。

**Comment by cfJand** [comment]
请按照要求格式发issue，不然想联系你也没法联系，不利于解决问题。

**Comment by cfJand** [comment]
请按照issue模板提交issue，此issue由于未按照要求发issue，暂时关闭。
