### ISSUE TITLE
新框架里MHPluginSDK.callSmartHomeAPI( '/user/getpdata',....）用哪个接口

### ISSUE THREAD

**Issue by aizuzi** [MiEcosystem/miot-plugin-sdk#584]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

旧接口找不到调用的方法

#### 期望

以前的接口如下，帮忙解决，谢谢

    Service.smarthome.callSmartHomeAPI('/user/getpdata’, {
      {
        key: 'body_info_yunmai',
        time_start: 0,
        time_end: 0,
      },
    }, (response) => {})

**Comment by blockdate** [comment]
user/getpdata 是针对用户维度进行kv存储。

如果不是跟用户强关联的信息而是跟设备关联的，我们建议使用`Service.smarthome.batchSetDeviceDatas`以及`Service.smarthome.batchGetDeviceDatas`。

如果是针对用户维度进行操作，请描述你的操作数据用途，我们会讨论是否增加接口满足使用需求。

**Comment by aizuzi** [comment]
@blockdate 比如用户填写完身高年龄体重等信息后，重新绑定另一台设备，我们希望用户不需要再重新填写信息

现有的接口无法跨设备保存用户填写的信息

**Comment by aizuzi** [comment]
请问该接口有没有发布的计划？

**Comment by blockdate** [comment]
计划在10010发布，SDK发布计划在五月八日，提供测试的sdk更新关注此issue关闭动态即可

**Comment by blockdate** [comment]
已更新，使用 `Service.smarthome.getUserPDData and Service.smarthome.setUserPDData`
