### ISSUE TITLE
展开小卡片，从设置进入使用帮助或通用设置，进入页面会出现页面叠加

### ISSUE THREAD

**Issue by annageng** [MiEcosystem/miot-plugin-sdk#585]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1..打开米家设置中的快捷操作卡片
2.点击设备列表首页的台灯图标，会展开小卡片
3.从设备列表进入插件，点击右上角…
[4.再点击使用帮助或通用设置，此时在进入或退出页面时，新出现的白色页面下会在插件上闪现设备列表页的内容](url)

#### 期望

简单明了地描述一下期望的表现。
![image](https://user-images.githubusercontent.com/6056276/56197124-c0441d00-606a-11e9-90e2-cc885ce16a07.png)

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by annageng** [comment]
在页面切换的时候还可以看到设备列表页面展开的小卡片

**Comment by lvjie0519** [comment]
@annageng  请使用最新apk，sdk选择10010分支，进行测试，如有问题，请加微信（微信号：18750118631）详聊，谢谢。
