### ISSUE TITLE
MHTableView Android是否兼容？

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#586]
小米的demo里有这个控件，只支持ios，android运行报错

我们以前的一个老项目用到了这个组件，android之前是原生的，现在要更改到统一用小米的RN新框架，问下是否这个控件能否兼容android，或者有其它组件支持分组索引的效果。

**Comment by blockdate** [comment]
这个Android目前是不支持的。

Demo有一部分是从旧插件demo平迁过来的，可能存在误导，非常抱歉，我们会及时更新。

如果对此UI有强烈需求，建议新开一个issue描述需求与样式说明，我们这边评估安排开发计划。
