### ISSUE TITLE
mijia_ble_secure 绑定问题

### ISSUE THREAD

**Issue by liurongaidou** [MiEcosystem/miot-plugin-sdk#587]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

我是做嵌入式开发的，使用mijia_ble_secure的代码，nordic分支
编译下载后，广播正常，但是使用测试的米家app(android) ，但是不能扫描到设备？

#### 期望

蓝牙设备被米家绑定，需要填写数据？只能开发米家端的页面才能测试通信？
有没有资料告诉我怎么做？

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 设备类型是什么
2. 扫描的具体过程描述下，是在快连过程中无法发现设备么

**Comment by liurongaidou** [comment]
1.我用的就是mijia_ble_secure 官方代码在官方开发板上调试的，计划要做的类型是锁
2.开发板启动广播后，我用米家提供的测试app扫描，但是不会显示我要测试的设备，
PID已经改了，
![image](https://user-images.githubusercontent.com/48199125/56258512-5aa36f80-6102-11e9-8652-5f8ca883582b.png)
![image](https://user-images.githubusercontent.com/48199125/56258542-70b13000-6102-11e9-8fc1-37e4c14648d5.png)

**Comment by blockdate** [comment]
设备支持被发现，还需要在iot平台上配置产品信息等数据，同时使用者的账号需要是白名单账号。
