### ISSUE TITLE
getDeviceSetting等方法的废弃是否可以考虑加入到CHANGELOG.md中

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#588]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

如果不仔细看警告，还不知道这些方法后面会废弃掉。
希望可以加入到CHANGELOG.md中。
这种如果没有及时看到，没有及时更改，越晚知道，更改的成本会越高，也会耽误上线时间。

《MIOT SDK API》说明文档中也没有说明哪些接口即将废弃，废弃后用哪些接口代替？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
感谢你的提议，我们会在文档上进行更加详细的废弃说明与替代方法，同时也会加入ChangeLog.md说明文档

**Comment by blockdate** [comment]
可以参见github中的release记录

**Comment by ldezho** [comment]
github中的release记录太精简
比如Package.entryInfo.payload中的一个字段sc_id什么时候改为id了都不知道
原本写好的功能，不知道从哪个版本开始就不能用了

**Comment by ldezho** [comment]
如果可能的话，建议还是写全一点，尤其是不兼容的更改。
这样很多问题可以不用麻烦你们，我们自己就解决了。
因为可能之前功能都写好也测好了，但是之后不知道哪个版本有了改动，出现问题后，我们不好查，就需要提issue麻烦你们。如果这些改动有个文档可参考，基本上我们就知道该怎么进行相应的改变了。

**Comment by blockdate** [comment]
收到，这边会完善变更日志。

> 至于sc_id 变成 id 这个，我也不清楚

**Comment by ldezho** [comment]
多谢您的回复。
