### ISSUE TITLE
Android底部虚拟键盘高度怎么获取

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#589]
大佬， RN中Android底部虚拟键盘怎么获取？ 现在会有遮挡的  麻烦告知！谢谢！

**Comment by lvjie0519** [comment]
这边正在安排增加api，请耐心等待。

**Comment by lvjie0519** [comment]
请参考  https://github.com/MiEcosystem/miot-plugin-sdk/issues/640， 有屏幕相关问题，在此issue统一讨论，这里先关闭。
