### ISSUE TITLE
快捷卡片文字太大太长 会超出宽度范围 能否调整UI

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#590]
大佬， 快捷卡片文字太大太长 会超出宽度范围 能否调整UI
如图：
![WechatIMG15](https://user-images.githubusercontent.com/34296463/56263516-d35ff700-6115-11e9-9184-3aa16c789d1f.png)

**Comment by lvjie0519** [comment]
有关卡片问题 请参见， 添加相关负责人微信进行沟通，谢谢！
#469

**Comment by jimu380261652** [comment]
**是否为新品（必填）**
新品，米系产品

**关联的产品model**
viomi.dishwasher.m01

**项目ID（必填）**
项目ID：P18-0300

**企业名称（必填）**
佛山云米电器科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/iOS 11.0
- SDK分支: [eg.master/10021/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
首页宫格处，文案未显示完整。。文案示例如图：Completed、Sanitizing
![image](https://user-images.githubusercontent.com/11864517/61355317-af43bb80-a8a6-11e9-980b-c0455c4ee560.png)


**期望（必填）**
文案能显示完整

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
