### ISSUE TITLE
新版插件如何发布？

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#591]
#### 现象

npm run publish ***后，生产publish.mpkg文件，后期如何发布到miot平台，老插件可以在android或ios的插件管理中提交，但新插件管理页面无任何提交按钮。

#### 期望

说明下publish.mpkg 的提交方式

#### 其他的上下文/日志/截图
![Screen Shot 2019-04-17 at 2 03 19 PM](https://user-images.githubusercontent.com/37297126/56264771-1754fb00-611a-11e9-8d5d-8a99b2ee56b7.png)

**Comment by blockdate** [comment]
这个权限不足问题，你的账户是公司账户下的管理员或者开发者权限账户么，如果是的话，提供下用户uid和公司的id。

**Comment by EllisonYe** [comment]
企业id550
uid：125782766

发自我的 iPhone

在 2019年4月17日，下午2:12，wulei <notifications@github.com<mailto:notifications@github.com>> 写道：


这个权限不足问题，你的账户是公司账户下的管理员或者开发者权限账户么，如果是的话，提供下用户uid和公司的id。

**Comment by blockdate** [comment]
已处理
