### ISSUE TITLE
开门记录中如何获取，用户的名称 和指纹，密码的昵称？

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#592]
#### 现象

简单明了地描述一下实际的现象。
![image](https://user-images.githubusercontent.com/16306138/56268400-d3ff8a00-6123-11e9-9b0b-1fecaa29e956.png)

如上图，解析getDeviceData,   锁上报的开门记录。

蓝牙开门需要获取用户的昵称，
指纹和密码开门需要获取，指纹和密码的昵称。

如果通过id再调用别的接口获取，会严重卡顿吧。
之前说，指纹和密码的昵称，调用setDeviceSetting和getDeviceSetting,来让key和昵称相关联，但是我每一条开门记录，不能都调用一次getDeviceSetting吧?如果是300条记录，调用300次，应该不行。

还有，上图的Key ID 是否就是用户的id?如果是蓝牙开门，要根据这个key Id，调用接口Service.getUserInfo(id)获取用户的昵称吗？同上这种方式会调用太多次接口，不可取

#### 期望

能有不需要每一条数据都调用接口获取昵称的方式。
这个问题很急，希望能尽快解决，感谢！！

**Comment by blockdate** [comment]
1. 用户信息获取参见 #597 
2. set和getDeviceSetting是支持批量的，但是这个接口是不推荐使用并且可能会被废弃的，建议使用10005分支中新增的方法`batchGetDeviceDatas` 和 `batchSetDeviceDatas`

**Comment by changgongxinshi** [comment]
刚试了10005分支下的batchGetDeviceDatas 和 batchSetDeviceDatas   这两个方法，没有效果

设置代码如下：

                        let params = {'did': Device.deviceID, 'props': {"prop.80011234": "4444"}};
                        Service.smarthome.batchSetDeviceDatas(params).then(result => {
                                console.log('保存成功')
                            }
                        );
无法打印log。

获取代码如下：
let parm = [{did: Device.deviceID, props: ["prop.80011234"]}];
            Service.smarthome.batchGetDeviceDatas(parm).then(result => {
                console.log('获取指纹昵称列表成功,result=' + result);
            });

可以打印log,但是数据为null ，如下图：
![image](https://user-images.githubusercontent.com/16306138/56359330-d7723e80-6213-11e9-9a46-f8458a9d4ddd.png)

还有一个问题如下图，props最多20个不满足我们的需求啊，如果有50个指纹昵称，我都要用Service.smarthome.batchSetDeviceDatas存的话，显然是不够的。
![image](https://user-images.githubusercontent.com/16306138/56359400-0983a080-6214-11e9-995d-b6bd9d5ac920.png)

希望能尽快解决这个问题

**Comment by blockdate** [comment]
文档上有说名，属性需要以`prop.s`开头，即你需要修改为 `prop.s80011234`或者`prop.s_80011234`

**Comment by blockdate** [comment]
代码使用 参考如下：

```

Service.smarthome.batchSetDeviceDatas([{ did: Device.deviceID, props: { "prop.s_string": 'name', "prop.s_json": JSON.stringify({ 'jname': 'test' }) } }])

Service.smarthome.batchGetDeviceDatas([{ did: Device.deviceID, props: ["prop.s_string", "prop.s_json"] }])

```

**Comment by changgongxinshi** [comment]
密码昵称的，问题已经解决了。

但是用户昵称的问题还没有解决，现在有一个批量获取用户的接口获取不到数据的问题。


 参考了#597，现在用户用蓝牙开锁，转小端后转成十进制的信息如下，用这个转好的用户id号，无论是是调用单独获取用户信息的接口（Service.smarthome.getUserInfo）还是批量获取用户信息的接口（ Service.smarthome.getUserInfoList）都无法获取到用户信息。


![image](https://user-images.githubusercontent.com/16306138/56412379-7c455800-62b6-11e9-9090-5d067b42ddba.png)
      
![image](https://user-images.githubusercontent.com/16306138/56412247-1bb61b00-62b6-11e9-9d7c-a2723be958f6.png)

**Comment by blockdate** [comment]
能否提供下API的返回结果的日志？

**Comment by changgongxinshi** [comment]
![image](https://user-images.githubusercontent.com/16306138/56413370-db589c00-62b9-11e9-93b3-11e069345bfb.png)
红框分别为单独获取和批量获取的日志
