### ISSUE TITLE
Host.ui.openChangeDeviceName();

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#593]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

Host.ui.openChangeDeviceName() 能不能回调告知用户修改后的名称是什么？

**Comment by blockdate** [comment]
监听 `DeviceEvent.deviceNameChanged` 事件即可
