### ISSUE TITLE
DeviceEvent.deviceNameChanged

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#594]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
// 设备名称改变
DeviceEvent.deviceNameChanged.addListener((device) => {
alert(JSON.stringify(device));
});

我这样写有调用，但是device里面没内容，为{}

**Comment by lvjie0519** [comment]
1、请说明下平台，ios or Android？

**Comment by JxXiaoXie** [comment]
ios  android 都这样

**Comment by blockdate** [comment]
本地两个平台验证无误，可以正常使用，验证方式为demo中main.js中的改名修改title逻辑。

**Comment by JxXiaoXie** [comment]
好，我看下
