### ISSUE TITLE
iOS如何获取需要连接的蓝牙设备的UUID

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#595]
#### 现象

在插件中获取ble管理对象，是通过下面的代码实现的：
Device.getBluetoothLE()

现在iOS使用Pilloxa/react-native-nordic-dfu框架升级固件时，示例代码如下：
NordicDFU.startDFU({
  deviceAddress: "C3:53:C0:39:2F:99",
  name: "Pilloxa Pillbox",
  filePath: "/data/user/0/com.nordicdfuexample/files/RNFetchBlobTmp4of.zip"
})
  .then(res => console.log("Transfer done:", res))
  .catch(console.log);

其中deviceAddress参数需要传递目标设备的UUID（安卓上传入的是一个进入固件更新模式的mac地址），那么iOS在插件中该如何获取目标设备的UUID呢？

#### 期望

插件中，iOS设备可以有接口可以获取到目标设备的UUID

**Comment by blockdate** [comment]
iOS 中需要先使用connect(), 连接上对应的蓝牙设备之后才可以获取到UUID.
