### ISSUE TITLE
进入插件时报-8错误

### ISSUE THREAD

**Issue by libopu** [MiEcosystem/miot-plugin-sdk#598]
#### 环境
- 手机系统:MIUI 10.2 （小米mix2）
- 手机系统2: ios12.2 （iphone8p）
- 一只未绑定的素士声波电动牙刷

#### 现象
- 添加设备
> 添加成功后进入插件时插件界面报-8错误
- 点击首页的设备图标
> 显示进入插件的蓝牙界面，并且报-8
>（使用多个miId测试，只有一个是正常的，其他都报这个错。）

#### 期望

能正确进入插件。

#### 其他的上下文/日志/截图

1. 安卓端调试时发现： {"code":-8,"msg":"invalid retry_time"}
2. 素士云端日志未发现异常
3. 与miot开发沟通结论：retry_time​ - 请求没有设置这个字段
4. 素士的安卓开发无法设置这个字段

![微信图片_20190418102042](https://user-images.githubusercontent.com/49738310/56332632-b08c1c00-61c3-11e9-9fde-d162da9c8b20.png)

**Comment by lvjie0519** [comment]
@libopu  请加微信（微信号：18750118631）详聊，谢谢。

**Comment by libopu** [comment]
> @libopu 请加微信（微信号：18750118631）详聊，谢谢。

已发请求，备注：github 598号错误。

**Comment by libopu** [comment]
补充：
2019年4月30日，ios/android均更新到最新版米家APP后，测试发现只有白名单用户才会出现-8错误，普通用户一切正常。

**Comment by blockdate** [comment]
@lvjie0519 如果已处理，同步下结果

**Comment by JxXiaoXie** [comment]
测试了下，已解决
