### ISSUE TITLE
新版扩展程序插进读设备数据是报错

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#599]
ios 米家debug版本 4.15.101
 Device.getDeviceWifi().callMethod("act_login_getUrl", []).then((res) => {
                      console.log('读取');
                  }).catch(err => {console.log('error:', err)

                  
                  });
<img width="1032" alt="A8C5D497-14F8-4EFB-AA45-6EBE84AFBBBC" src="https://user-images.githubusercontent.com/38349220/56332686-ed581300-61c3-11e9-818e-39c614a7206b.png">

**Comment by liuhaixu666** [comment]
这个错误信息code=-3 的值我可以取出来吗，方便的判断错误类型

**Comment by liuhaixu666** [comment]
这个错误信息code 的值我可以取出来吗，方便的判断错误类型

**Comment by blockdate** [comment]
建议检查测试app版本（icon编号）， 目前在callmethod中的返回上是有error错误code返回的。
