### ISSUE TITLE
TitleBarBlack

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#60]
TitleBarBlack左右按钮支持自定义按钮图片吗？

**Comment by dingshaoran** [comment]
支持，leftText和rightText支持设置为任意 component.
leftText={<Image   source={require('../Resources/common/clock_home_icon_forward_normal.png')}
                             style={{width:50,height:50}}/>}

**Comment by dzonel** [comment]
@dingshaoran 只能修改左右第一个按钮图片，第二个没办法修改
