### ISSUE TITLE
从“有品”页面返回插件页面后，无法触发所有点击事件

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#600]
#### 环境
- 手机系统:Android 9

#### 现象

进入米家牙刷插件，点击“刷头剩余天数”，点击“购买“跳转至有品。点击返回后，页面卡死，无法触发点击事件。

#### 期望

返回后，可以正常点击。

#### 其他的上下文/日志/截图

![QQ图片20190418154108](https://user-images.githubusercontent.com/48087638/56344687-99afee80-61f0-11e9-987e-070ec4fa11c7.jpg)

**Comment by huangjr126** [comment]
您好，这个问题目前拖延我们插件的提测进度，能否帮忙看一下呢？ @blockdate

**Comment by blockdate** [comment]
好，我让相关同学尽快看下。

**Comment by lvjie0519** [comment]
@huangjr126  请加微信(微信号：18750118631)，详聊，谢谢！

**Comment by lvjie0519** [comment]
@huangjr126  是否解决？ 如解决，请关闭issue，谢谢。
