### ISSUE TITLE
切换语言版本，需要第二次进入插件才生效

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#601]
#### 环境
- 手机系统:[iOS 12.2/APP版本 4.15.102]

####操作步骤

当前地区为：中国，语言为：简体
1、APP语言设置为英语
2、清除缓存进入插件
3、查看内容文案语言

#### 现象
1、更换语言后第一次进入，内容文案为简体；退出插件再次进入则为英语

#### 期望
1、设置语言版本后，第一次进入插件即为生效

**Comment by huangjr126** [comment]
@blockdate 早上好吖~这个问题您能协助解决吗？

**Comment by blockdate** [comment]
在处理中了

**Comment by blockdate** [comment]
已处理更新app
