### ISSUE TITLE
Device.latitude 返回的数据为0

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#602]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by betterFuture** [comment]
Device.latitude,Device.longitude 这两个值获取到的是0

**Comment by betterFuture** [comment]
我这边在测三台ProH va1 两台在公司 一台在外地 公司的两台设备都获取不到经纬度（Device.latitude,Device.longitude）

**Comment by blockdate** [comment]
DUP #629
