### ISSUE TITLE
插件首页，设备图标上没有显示蓝牙图

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#603]
#### 环境
- 手机系统:[eg.Android 9]

#### 现象

插件首页，设备图标上没有显示蓝牙图。

#### 期望

插件首页上，设备图标可以正常显示蓝牙图，参考IOS

#### 其他的上下文/日志/截图

![1](https://user-images.githubusercontent.com/48087638/56350369-37111f80-61fd-11e9-9951-c7ab4262b0f6.png)
![2](https://user-images.githubusercontent.com/48087638/56350373-39737980-61fd-11e9-980a-a7ed107988a8.png)

**Comment by lvjie0519** [comment]
@huangjr126  退出应用，杀掉进程或下拉刷新，仍然如此吗？

**Comment by huangjr126** [comment]
@lvjie0519 退出插件，杀掉进程，下拉刷新这些都试过，结果都没有。

**Comment by lvjie0519** [comment]
@huangjr126 请等待米家native端解决，我这边继续跟踪。

**Comment by huangjr126** [comment]
@lvjie0519 您好阿，想问下该问题解决进度如何了？

**Comment by Woody2016** [comment]
此问题已有ECO bug跟踪：https://jira.n.xiaomi.com/browse/ECOMIOT-903
android不用改，iOS app端会改（不展示蓝牙图标），随6.4发版
