### ISSUE TITLE
修改牙刷标签时，Android和IOS调用同个方法但返回的结果不一致

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#604]
#### 环境
- 手机系统:[eg.Android 9]

#### 现象

Host.ui.openChangeDeviceName();
ios  、Android调用这个方法后，iOS有提示“修改成功”，但是安卓没有。

#### 期望

调用同个方法后，Android端也提示“修改成功”。

#### 其他的上下文/日志/截图

![1](https://user-images.githubusercontent.com/48087638/56352732-6a09e200-6202-11e9-8682-3ba86e98f463.png)

**Comment by lvjie0519** [comment]
@huangjr126 Android这边目前默认没有提示，APP层也一样，请等待我确认需求后再做修改。

**Comment by huangjr126** [comment]
@lvjie0519 好的，谢谢

**Comment by lvjie0519** [comment]
已修复，今晚会更新apk，届时请关注更新apk再进行测试，谢谢。
