### ISSUE TITLE
打包上传到iot平台并且开启了白名单测试，可是在app上提示“请升级至最新app”

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#606]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Mac OS] 
- 手机系统:[eg.iOS 11.0]
- SDK分支: [eg. 10004]
- 相关模块:[eg.Host/Service/Account]

#### 现象

打包上传到iot平台并且开启了白名单测试，且账号在企业白名单内，可是在app上提示“请升级至最新app”

#### 期望

可以进行白名单测试

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by zhuxinleibandou** [comment]
![IMG_5777](https://user-images.githubusercontent.com/18374383/56354323-fa95f180-6205-11e9-88e9-0061dc6fb593.PNG)

**Comment by blockdate** [comment]
DUP #560 

再上传插件源码之后，需要在下面关联设备对应的model，才可以成功获取插件

**Comment by zhuxinleibandou** [comment]
> DUP #560
> 
> 再上传插件源码之后，需要在下面关联设备对应的model，才可以成功获取插件

已经关联了，debug版本可以测试。但是米家官方版本好像不行，提示更新最新版本的app

**Comment by blockdate** [comment]
你选的level是10004或者10005吧，这个iOS目前还没提交上架，预计在下周二
