### ISSUE TITLE
android MHTableView组件开发

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#607]
1、问题另提  https://github.com/MiEcosystem/miot-plugin-sdk/issues/586
2、可以参考ios的代码：projects\com.xiaomi.demo\CommonModules\MHTableView.js
3、效果图如下
![微信图片_20190418201040](https://user-images.githubusercontent.com/49702230/56360111-1acdac80-6216-11e9-8d0a-e270225548c4.png)

**Comment by blockdate** [comment]
该功能经讨论后建议自行实现(最常见的搜索国家列表，有很多demo)，Android暂不提供实现
