### ISSUE TITLE
关于获取云端属性的问题。

### ISSUE THREAD

**Issue by icedu8910** [MiEcosystem/miot-plugin-sdk#608]
####简单明了地描述一下实际的现象。

MIIO直接接入设备，已经通过Prop指令将数据上传到云端。
新版本扩展插件需要通过什么指令获取云端上的属性数据？

#### 尝试过的解决办法

我们使用了
iDevice.getDeviceWifi().loadProperties("Ps").then(map=>{
 const Ps = map.get("Ps")
console.log("data:"+Ps)
})
控制台得到的信息是:data:error。
使用
iDeviceWifi.loadPropertiesFromCloud(...propNames)
也会得到一样的结果。

**Comment by blockdate** [comment]
loadProperty 是通过 RPC请求 'get_prop' 获取设备的当前属性。
1. 检查下get_prop的RPC指令是否能正确在硬件上工作
2. 提供下你们Prop指令上传数据的具体操作
