### ISSUE TITLE
Service.tjinfra.searchOfficial android返回为空,ios正常

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#610]
调用如下：
 
 /**
   * 搜索官方库
   * pageDic的使用具体可参考TJRemotePage
   **/
  searchOfficial(pageDic, callback) {
	  TJInfra.searchOfficial(g_TJClientName, pageDic).then((result) => {
		  console.log("searchOfficial,pageDic="+JSON.stringify(pageDic)+",result=", result);

		  if (callback != undefined) {
			  callback(result.code,result.result);
		  };
	  }).catch(error=>{
		  console.log("searchOfficial,"+g_TJClientName, error);
	  });
  }

log如下：
searchOfficial,pageDic={"appliance_type":0,"keyword":"","page":1},result= []

帮忙解决，谢~

**Comment by lvjie0519** [comment]
@daoke666  排查发现，贵司提供的TJInfra红外库，使用米家APP层依赖的JSON转化库解析失败，希望贵司能从新提供TJInfra红外库，增加自己实现的解析库能够正常解析json数据，谢谢！

**Comment by daoke666** [comment]
你好，请提供米家APP层依赖的JSON库的版本，我们尝试下反编译修改，调用新的版本的api

**Comment by daoke666** [comment]
@lvjie0519

**Comment by lvjie0519** [comment]
@daoke666   您好， 我们使用的json解析库 版本为 fastjson-1.1.68.android.jar；
![image](https://user-images.githubusercontent.com/22487747/56420823-1c5caa80-62d2-11e9-85c3-baf9cd2c83c1.png)

**Comment by daoke666** [comment]
@lvjie0519
我们下载了米家APP层依赖的JSON库的版本(fastjson-1.1.68.android)和tiqiaa库反编译出来的JSON库对比发现，api是一样的
![1](https://user-images.githubusercontent.com/49702230/56454951-0f4fc200-638b-11e9-9b73-fe66bb793c89.png)
然后我们在反编译的代码了加了log,把这两个参数打印出来，
![2](https://user-images.githubusercontent.com/49702230/56454953-1676d000-638b-11e9-95f4-6d45914ac133.png)
重新打了个库，这个库做了两点修改
1、删除json库，防止与米家的库冲突
2、TQResponse.java 加了log，帮忙排查下有什么异常
    public <T> T getData(TypeReference<T> type) {
    ........
        try {
        	LogUtil.i("imi", "data="+this.data.toString()+",type="+type);
     .......
    }

**Comment by lvjie0519** [comment]
已修复，请更新sdk 到 10010分支，同时请使用最新apk。
