### ISSUE TITLE
Service.tjinfra.xxx 接口 ios 和 android 返回不一致

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#611]
举例其中一个
 Service.tjinfra.loadBrands

iOS如下
![ios](https://user-images.githubusercontent.com/49702230/56402932-f44d5700-6291-11e9-8d8f-3923238614c7.png)

Android如下
![andorid](https://user-images.githubusercontent.com/49702230/56402974-1050f880-6292-11e9-8081-12b5f77590f4.png)

=====================================
大部分接口返回的形式如下,ios应该有做处理：请统一规范，谢谢
ios:
result = {result: [], code: 0}

andrioid:
result= []

**Comment by Woody2016** [comment]
好，我们统一下这块的返回数据格式

**Comment by lvjie0519** [comment]
@daoke666  已修复，请更新sdk 到 10010分支，同时请使用最新apk。
