### ISSUE TITLE
TitleBarBlack 的小红点显示位置不对

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#614]
#### 环境
- 手机系统:[iOS 12.0] Iphone 8 Iphone XS

#### 现象
TitleBarBlack 的小红点显示位置不对。

#### 期望

能正常显示

#### 其他的上下文/日志/截图
<img width="311" alt="Screen Shot 2019-04-19 at 2 08 22 PM" src="https://user-images.githubusercontent.com/37297126/56409646-a003a080-62ac-11e9-8efe-97dd79110c1f.png">

**Comment by LiuMengzhou** [comment]
722f335
[demo](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10011/projects/com.xiaomi.demo/Main/tutorial/TitleBarDemo.js)

**Comment by LZCaaT** [comment]
兄弟，你这个背景图延伸到导航栏和状态栏，沉浸式的效果是怎么实现的，可以贴段代码看下吗？感谢
