### ISSUE TITLE
padStart方法报错

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#616]
米家app：最新的4.15.101（4月16日）
iOS版本：9.3.3
机型：iPhone SE
SDK版本：10004和10010均试过，都有该问题

开发者通用设置：开启了离线进入，关闭了插件调试。

直接使用com.xiaomi.demo，Main/MainPage.js的render()中，第一行添加：    
console.log('test', '0'.padStart(3, '0'));
即报错：TypeError: '0'.padStart is not a function.

打包完用白名单测也是同样的错误。

但如果开启了插件调试，就会正常。

Android也有同样的问题。
Android 7.0
机型：ZUK Z2

<img width="733" alt="Screen Shot 2019-04-19 at 2 56 19 PM" src="https://user-images.githubusercontent.com/1590420/56412110-b5c99380-62b5-11e9-99e1-1936a9eaeb2c.png">

![IMG_0069](https://user-images.githubusercontent.com/1590420/56412443-bdd60300-62b6-11e9-80b2-5c3af3e42468.PNG)

**Comment by blockdate** [comment]
该方法在ES7中声明使用，但是仅在iOS10之后才能正常支持，参考 [podStart](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)
