### ISSUE TITLE
页面所有元素的点击事件都无效

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#617]
#### 环境
- 手机系统:[eg.Android 8.1 小米7]
- SDK分支: [10005]

#### 现象
小米7，当设备提示“设备已经离线，链接”的弹框后，关闭弹框，当前页面所有元素的点击事件都无效。

#### 期望
可以点击，事件可以正确响应。

**Comment by lvjie0519** [comment]
@EllisonYe

**Comment by xiaofulon** [comment]
iOS上可以点击,安卓上就是不行,整整折腾了一天,在文档中怎么没有标明这个策略

**Comment by Woody2016** [comment]
离线时，iOS上进插件页应该也是不能操作的啊，请确认下

**Comment by xiaofulon** [comment]
ios上蓝牙离线可以点击啊
