### ISSUE TITLE
安卓RN原生image优化，解决换图片时候控件闪烁问题

### ISSUE THREAD

**Issue by jianbin-rockrobo** [MiEcosystem/miot-plugin-sdk#618]
就是ReactImageView每次执行maybeUpdateView的时候, 会调用到AbstractDraweeController的init方法, 在GenericDraweeHierarchy的reset里面显示透明颜色, 这样ImageView每次切换图片就会闪一下

解决方案已经在线下沟通，并持续在线下沟通。需要原生app优化。

**Comment by lvjie0519** [comment]
@jianbin-rockrobo   使用米家APP，image切换图片会出现闪烁吗？  我这边无法复现。
