### ISSUE TITLE
是否可以提供下Device.getBluetoothLE().connect失败的所有错误码及相关说明

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#619]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
文档中已提供，请仔细阅读 [蓝牙 connect](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/03-%E8%93%9D%E7%89%99%E6%A8%A1%E5%9D%97#module_miot/Bluetooth--module.exports.IBluetooth+connect)

**Comment by ldezho** [comment]
抱歉，我不是看的markdown格式那份文档，所以没看到，谢谢。
