### ISSUE TITLE
iOS 上提示用户打开蓝牙的动画

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#620]
![ScreenRecording_04-03-2019 17-26-30_2019年4月19日 下午4 48 32](https://user-images.githubusercontent.com/4001793/56416287-fa0f6080-62c2-11e9-87f8-e6d76df968aa.png)

iOS 上有一个这样的提示，体验比较好。在旧框架下有接口可以 show 和dismiss，希望在新框架里也可以使用。

**Comment by blockdate** [comment]
参考 `Host.ui.showBLESwitchGuide()` , SDK_level 10004
