### ISSUE TITLE
SingleChoseDialog在iOS上显示异常（Android正常）

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#621]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[iPhone 6s  iOS 12.2]
- SDK分支: [master]
- 相关模块:[miot/ui]

#### 现象

iOS上显示中间留空过高

#### 期望

正常显示

#### 其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/46777658/56418225-e2d37180-62c8-11e9-924e-16934afeeb0c.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by LiuMengzhou** [comment]
原生组件改动较麻烦，纯JS版正在开发中。推荐：
1. 等不及自己实现
2. 等（大约本月输出）
