### ISSUE TITLE
Android端点击更多后，再回到主页面，产品名称消失；Android端隐私协议显示乱码

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#622]
![2211555896685_ pic](https://user-images.githubusercontent.com/17919773/56478368-69629b80-64e1-11e9-920e-cfde2a851ab9.jpg)
![2201555896684_ pic](https://user-images.githubusercontent.com/17919773/56478372-7089a980-64e1-11e9-8b4b-8975adabee69.jpg)

#### 现象

1. Android端点击更多后，再回到主页面，产品名称消失，调用的是demo中的moreDialog;

2. Android端隐私协议显示乱码，iOS端正常

**Comment by lvjie0519** [comment]
问题1、我们这边本地在测试下；
问题2、您是本地调试显示乱码还是打包上传插件包到服务器上后，下载下来显示乱码？
方便的话希望能将您那边的隐私协议html发送一份给我，邮箱：lvjie1@xiaomi.com

**Comment by sikaiven** [comment]
问题2已经解决，问题1还麻烦看看，感谢。

**Comment by lvjie0519** [comment]
@sikaiven  麻烦能说一下乱码的原因，方便以后排查谢谢；
问题1 麻烦 @LiuMengzhou 看看

**Comment by sikaiven** [comment]
因为我是用的doc文件直接另存为html，转换过来的html里面的编码格式是GB，之前改编码格式都是在ide上选择编码格式保存，没有改到里面的标签<meta http-equiv=Content-Type content="text/html; charset=utf8">，把charset改成utf8就好了。

**问题1还麻烦尽快看看，麻烦了！**

**Comment by lvjie0519** [comment]
@sikaiven  请参考10010分支的Xiaomi.demo中mainpage.js中的用法，看是否有问题，我这边无法复现，谢谢。

**Comment by sikaiven** [comment]
将demo中导航栏的用法拷贝到自己的项目，还是一样的，而且在10010分支中，没有找到MoreDialog.js文件，我是用的之前的moredialog.js文件，同时在demo中的导航栏控件下面加了以下代码：
<MoreDialog
            visible={typeof navigation.state.params === 'undefined' ? false : navigation.state.params.showDialog}
            navigation={navigation} />

**Comment by blockdate** [comment]
无法复现
