### ISSUE TITLE
TitleBarBlack 标题太长显示问题

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#623]
#### 现象
TitleBarBlack 标题太长时，显示成3行

#### 期望

单行，实现不了的使用“...”

#### 其他的上下文/日志/截图
![Screenshot_2019-04-19-15-20-17-442_com xiaomi smarthome](https://user-images.githubusercontent.com/37297126/56478637-62d52380-64e3-11e9-8a8e-6ca1cb1fecf7.png)

**Comment by LiuMengzhou** [comment]
TitleBar的问题，五一假期过后的4个工作日被统一解决

**Comment by LZCaaT** [comment]
> SDK_10011
> [722f335](https://github.com/MiEcosystem/miot-plugin-sdk/commit/722f33570f274c9803927d420d19736ce672121a)
> [com.xiaomi.demo-「首页」-「教程」-「导航栏 TitleBar Demo」](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10011/projects/com.xiaomi.demo/Main/tutorial/TitleBarDemo.js)

请问一下，titleBar怎么更改title标题的字体大小和颜色，设置了color和fontsize显示属性无效
