### ISSUE TITLE
新版米家扩展程序上传成功后，app无法启动该扩展程序

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#624]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] android 9.0
- SDK分支: [eg.master/10000/...] 10004
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

扩展程序上传后app上无法打开

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

![1555900780346](https://user-images.githubusercontent.com/8141398/56480039-ff4ef400-64ea-11e9-9113-b6a13fdc55ac.jpg)
![WechatIMG2](https://user-images.githubusercontent.com/8141398/56480085-2f969280-64eb-11e9-91ac-dfc2f2374203.png)

以下为app所有日志

[log.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3101958/log.txt)

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
@Aptx4869-xd  看你这log日志还不完整，只能看到APP进程的日志，希望能看看插件进程中输出的日志，如还未解决，请加微信（微信号：18750118631），详聊。

**Comment by lvjie0519** [comment]
@Aptx4869-xd  问题是否解决？如解决，麻烦说明下解决方案，谢谢。

**Comment by Aptx4869-xd** [comment]
@lvjie0519 你好，已经解决了，我后来在sdk10004上重新生成了下插件包再上传就又好了
