### ISSUE TITLE
关于RN上的SQLite数据库使用性能优化问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#626]
您好，
      目前项目由于RN机制语言本身的问题，会导致在安卓上比ios上运行慢一些，用户体验就会不好。尤其是涉及到大量数据库操作问题的时候，在安卓上更显得运行速度慢，数据读写速度慢。
如果安卓手机配置高一点的话，速度会有一定程度的提升。
      然而目前我们的产品准备出海到印度市场，印度市场上的手机普遍手机配置偏低，那么在安卓上运行的效果可能会更加慢。
      我目前使用的数据库是
      import SQLite from 'react-native-sqlite-storage';
      
      我们的产品，涉及到历史数据读写，在进入插件的时候，会有频繁的数据库操作。
      我想请问一下，怎么才能追求这个数据库使用最佳性能？谢谢！

**Comment by blockdate** [comment]
这一块并没有太好的建议，只能建议优化数据库表设计，只返回需要的字段，减少交互次数批量操作等。

如果性能问题的却存在较大的隐患，可以尝试开一个需求issue，这边尝试加入单独开启数据库线程进行数据库的操作，毕竟RN的js是单线程操作。
