### ISSUE TITLE
Android 上 创建智能条件时，返回（放弃），会跳转到 下一步，应该回到上一步

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#627]
5.5.10 (Build 62863) - 82.35 MB

Updated at: 2019-04-22 10:07
#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 8.1]
- SDK分支: [10005]
- 相关模块:[Package]

#### 现象

Android 上 创建智能还有个问题，到了选择界面（我们是条件设备，if ），如果点完成执行Package.exit(info) 没问题了，可以成功，不过如果点返回（放弃创建）的话，会有问题，会跳转到 选择执行操作（then），会跳转到 下一步，应该回到上一步

#### 期望

应该想iOS 一样，返回（放弃创建）时，回到重新选择条件类型，或重新选择条件设备，即，应该回到上一步。

#### 其他的上下文/日志/截图

仅发生在创建场景页面由插件自己实现时。如果是app自带带创建没有问题。

**Comment by lvjie0519** [comment]
@dubiao 已修复，请使用最新apk进行测试，谢谢。
