### ISSUE TITLE
连接蓝牙一直提示超时

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#628]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Mac OS]
- 手机系统:[eg.iOS 11.0]
- SDK分支: [eg.10000]
- 相关模块:[eg.]

#### 现象

Device.getBluetoothLE().connect(0, {timeout: 15000}) 方法一直报超时错误（ -7）
情况：
1、硬件设备蓝牙灯会亮
2、新的硬件，状态开发中
3、硬件那边说已写入正确的Model
4、旧硬件可正常连接，新硬件与旧硬件的区别就是 更新了开发板，
新硬件信息：
芯片：nordic 52832
嵌入式软件开发的sdk版本为 15.2，
应用的米家服务lib版本为 mijia_std_authen_keil_nrf52_1_1_3_8f564473.lib

#### 期望

正常连接，不再提示 -7

**Comment by ldezho** [comment]
+1 最近经常-7

**Comment by Copypeng** [comment]
-7 代表找不到目标设备合法的蓝牙广播，找到广播才能建立连接。你提供的信息中说旧硬件可以，而新硬件不行，所以建议你们固件开发人员抓一下设备的蓝牙广播，同时固件开发应该会有一份蓝牙广播格式的文档，看下实际广播与文档上对照，是不是什么字段错误。

**Comment by JxXiaoXie** [comment]
可是硬件蓝牙等有亮，有亮应该是有进行连接了吧。

**Comment by JxXiaoXie** [comment]
好了，是硬件问题。
