### ISSUE TITLE
iOS绑定的设备无法获取经纬度

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#629]
分别使用安卓手机米家客户端和苹果手机米家客户端 蓝牙扫描绑定同一台空净va1 ，安卓端绑定的设备可以获取设备经纬度信息 ，iOS端绑定的设备不可以获取经纬度信息。

**Comment by blockdate** [comment]
目前排查结果暂时定位为 手机端在快连时上传位置信息失败，之后并不会跟新位置信息，这个正在处理中
