### ISSUE TITLE
Host 和 Package 包里各种不统一和不达意，求解释，求统一。

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#630]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- SDK分支: [eg.10005.]
- 相关模块:[eg.Host/Package]

#### 现象

1.  `Host.version`  在文档中说是`app的版本`，而在Android 上 `Host.version = 8.1.0`，iOS 上 `Host.version = 12.2` ，明显是系统版本的意思，目前不知道app 版本怎么读取
2. `Host.apiLevel` 文档说是APP 的 apiLevel，我理解是app的 SDK 版本。Android 上取到 `Host.apiLevel = 10003`， 我理解是对的，但是iOS 上 `Host.apiLevle = 33000`， 不明白这个是什么意思
3. `Package.minApiLevel`， Android 是 undefined ，iOS 上是 140。 无法明白。

#### 期望

1. `Host.version = 5.5.10`   // App 的版本
2. `Host.apiLevel = 10003`  // Android 目前是这样的，iOS 是 33000 ， 不理解。
3. `Package.minApiLevel = 10005` // package 支持的 SDK 版本。

#### 其他的上下文/日志/截图

￼iOS:
![image](https://user-images.githubusercontent.com/4001793/56487866-346d3d80-650f-11e9-878e-66d9a788e74a.png)

Android:
￼
![image](https://user-images.githubusercontent.com/4001793/56487983-8e6e0300-650f-11e9-9d40-f5ccf35e8c51.png)

**Comment by dubiao** [comment]
4. `Package.version = 0` (开发模式下)

**Comment by blockdate** [comment]
已处理。目前剩余Android导出native app版本待更新
