### ISSUE TITLE
dataLengthOfBase64Data在iOS和安卓返回长度不一样

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#631]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/15190511/56492579-d21c3900-651e-11e9-95ce-76e30d4ef9e8.png">
下载相同文件，在iOS读取base64文件长度和安卓上文件长度不一样，iOS读取到的长度是正确的

**Comment by lvjie0519** [comment]
@RideShi   长度不一致，内容是一样的吗？ios具有自动换行的作用，Android这边是整个文件内容的读取。

**Comment by RideShi** [comment]
内容是一样的

**Comment by lvjie0519** [comment]
长度的不一致对您产生什么影响吗？

**Comment by RideShi** [comment]
我们蓝牙固件升级，透传数据，长度是我们生成数据验证的一部分，长度不对会导致验证失败

**Comment by lvjie0519** [comment]
@RideShi  建议你们不要用数据长度作为验证的一部分，不同平台不同系统版本有可能存在base64编解码格式不一样的情况。

**Comment by RideShi** [comment]
![51555982574_ pic_hd](https://user-images.githubusercontent.com/15190511/56545205-67640f80-65a9-11e9-8b72-88a8f90db214.jpg)
我们以前安卓端这样处理，长度是没有问题，改这个对我们的影响挺大的，软硬件都需要进行改动，希望能支持一下

**Comment by RideShi** [comment]
没问题了，这边自己处理长度，俩端都可以使用了
