### ISSUE TITLE
IOS 使用AMapView 缩放地图回调不响应

### ISSUE THREAD

**Issue by zhangpqan** [MiEcosystem/miot-plugin-sdk#632]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

地图手动放大缩小时：onMapWillZoomByUser onMapDidZoomByUser 这两个方法没执行

**Comment by blockdate** [comment]
检查后发现功能并无问题，建议检查下SDK是否更新至最新。使用分支 10005 或者 10010.
![image](https://user-images.githubusercontent.com/4339364/56722561-edcf4b80-6779-11e9-9fde-31a9f70c1f7b.png)

![image](https://user-images.githubusercontent.com/4339364/56722548-e4de7a00-6779-11e9-8f12-79521d886fcd.png)
