### ISSUE TITLE
安卓录音权限

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/miot-plugin-sdk#633]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: [10003]
- 相关模块:[Host/audio]

#### 现象
在设置里面,关闭掉米家的录音权限后,调用Host.audio.isAbleToRecord()会返回true,但是调用Host.audio.startRecord会直接抛异常. ios可以正常检测录音权限

#### 期望

没有开启权限,Host.audio.isAbleToRecord()应返回false

**Comment by lvjie0519** [comment]
@nevermore-jia  已修复，请使用最新apk，同时你那边js需要主动获取对应权限，具体可以参考MHAudioDemo

**Comment by nevermore-jia** [comment]
@lvjie0519  代码切换到10010,并且更新了最新的app,调用新的获取权限的方法PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, null),还是不能正确获取录音权限,导致没有开权限的时候调用录音方法Host.audio.startRecord,抛出异常

**Comment by lvjie0519** [comment]
@nevermore-jia  获取权限的时候回弹出提示框吗？ logcat 使用 miot-rn-plugin过滤下日志看看？

**Comment by nevermore-jia** [comment]
@lvjie0519  关闭权限后没有弹框,使用adb logcat |grep miot-rn-plugin查看日志,录音没有输出,使用浏览器抛异常
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/25736441/56719599-a5149400-6773-11e9-8718-71bf24e7e773.png">

**Comment by lvjie0519** [comment]
@nevermore-jia  请加微信（微信号：18750118631），详聊。

**Comment by lvjie0519** [comment]
是否存在问题，如有问题请加微信详聊，我这边无法复现。

**Comment by zhaowei1357** [comment]
在android上，不管在手机设置中 权限设置成“询问”、“禁止”、“允许”，任何情况下Host.audio.isAbleToRecord()均返回true，

**Comment by zhaowei1357** [comment]
在android上，不管在手机设置中 权限设置成“询问”、“禁止”、“允许”，任何情况下Host.audio.isAbleToRecord()均返回true，

**Comment by lvjie0519** [comment]
android 是动态获取权限的，Host.audio.isAbleToRecord()无效，使用录音请参考xiaomi.demo，关于录音问题，在
https://github.com/MiEcosystem/miot-plugin-sdk/issues/528 进行讨论。
