### ISSUE TITLE
设置页导入CommonSetting崩溃问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#634]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [SDK_10004]

#### 现象
在设置页导入CommonSetting => import {CommonSetting} from "miot/ui/CommonSetting"; 
执行APP出现下图情况
![IMG_0703](https://user-images.githubusercontent.com/49632045/56556794-7bb90400-65cb-11e9-9172-a9a45d3c22cd.PNG)

**Comment by LiuMengzhou** [comment]
根据你的信息，我猜测是你本地调试没问题，本地打包上传后台，然后用测试白名单拉取插件，进入插件的时候报错？

**Comment by CJackKao** [comment]
问题已解, 谢谢。
