### ISSUE TITLE
batchGetDeviceDatas/batchSetDeviceDatas使用疑问

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#636]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

1、对于需要传did，是否可以理解为，只要知道本账号上的其他设备的did，就可以获取到其他设备的数据？
2、每个prop.s_xxx_<uid>，uid是必须的吗，属性必须要uid结尾吗？（因为看文档说，属性需要以prop.s 开头，没说以uid结尾，但是例子中却是以uid结尾，所以不确定）
3、每个属性可存的数据量有多大，比如prop.s_example_key可以存一个字符串，字符串是否可以很大很大（比如大到占用几M的存储空间），如果有限制，是怎么限制的？

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
1. 是的，只要有设备did就可以获取
2. 只需要以prop.s开头即可，后续无要求
3. 这个长度问题我需要去确认一下

**Comment by blockdate** [comment]
长度问题建议限制大小在4K左右，过大的数据会影响响应速度。
