### ISSUE TITLE
Android隐私协议，乱码

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#638]
#### 现象

Android端隐私协议在本地调试时显示正常，上传后下载插件安装显示乱码，iOS正常，编码格式用的GB，html文件是通过doc文件转换过来的。

#### 尝试过的解决办法

尝试更改其他编码也不行。

![3671556025280_ pic](https://user-images.githubusercontent.com/17919773/56587545-4f75a580-6614-11e9-8186-1aff85190749.jpg)

**Comment by lvjie0519** [comment]
您是本地调试显示乱码还是打包上传插件包到服务器上后，下载下来显示乱码？
方便的话希望能将您那边的隐私协议html发送一份给我，邮箱：lvjie1@xiaomi.com

**Comment by sikaiven** [comment]
已经解决了，谢谢。

**Comment by CyrilChen** [comment]
@sikaiven 麻烦问一下怎么解决的，遇到一样的问题
