### ISSUE TITLE
设备名称没有变更

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#639]
#### 环境
- 手机系统:[Android ]
- SDK分支: [10005]

#### 现象
初次绑定“甲醛测试仪”设备步骤过程，修改设备名称，并没有起效。
在主页面设备列表和设备详情页面的名称还是默认名称。

#### 期望
修改名称成功

**Comment by lvjie0519** [comment]
@EllisonYe 您使用的是哪个版本的apk，我这边测试了下，没有发现问题，请使用最新apk再次测试下，谢谢。

**Comment by lvjie0519** [comment]
先关闭issue，有问题再reopen。
