### ISSUE TITLE
InputDialog的输入值？

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#64]
怎么获取输入的值？

`
onConfirm={(e) => {
         console.log('onConfirm', e);
 }}
`

e: {target:520}

**Comment by dzonel** [comment]
@pencilCool 抱歉，我就是想问一下，怎么获取InputDialog的输入框的值？在onConfirm里面打印log看不到。请问点击确定怎么获取输入框的值？
![1543546072747](https://user-images.githubusercontent.com/12531667/49265532-6d881100-f48d-11e8-929d-5189f04071bc.jpg)

**Comment by dzonel** [comment]
@pencilCool 您好，关于InputDialog还有一个问题，就是我怎么给输入框传入一个默认值？

**Comment by dzonel** [comment]
您好，哪位大神指点迷津：
1、怎么获取输入框的值？
2、怎么给输入框传一个默认值？

**Comment by dzonel** [comment]
@pencilCool @LiuMengzhou @laohuang88 @dingshaoran 您好，哪位帮忙说明一下怎么使用？十分感激。
1、怎么获取输入框的值？
2、怎么给输入框传一个默认值？

**Comment by LiuMengzhou** [comment]
Duplicate of #127
