### ISSUE TITLE
Dimensions.get('window').height，获取屏幕高度问题

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#640]
#### 现象

全屏幕手机通过Dimensions.get('window').height获取屏幕高度，好像少了上方导航栏加上状态栏的高度，非全屏幕手机是正常的。

#### 期望
![2611556069728_ pic](https://user-images.githubusercontent.com/17919773/56627455-72d23c00-6678-11e9-946e-2b8e5003a0d4.jpg)
![4301556070021_ pic](https://user-images.githubusercontent.com/17919773/56627465-782f8680-6678-11e9-9f5c-f8834b096f5c.jpg)

**Comment by ftc300** [comment]
Dimensions.get(‘’screen") 试试

**Comment by lvjie0519** [comment]
Dimensions.get(‘’screen")是可以获取到全面屏的高度，但是对于非全面屏手机，Dimensions.get(‘’screen")和Dimensions.get(‘window")的值貌似不一样，同时当全面屏手机开启虚拟导航栏了，可能与你们需要的高度又不一致，目前我这边正在安排处理这一问题，请耐心等待。

**Comment by sikaiven** [comment]
好的，谢谢

**Comment by lvjie0519** [comment]
请使用最新apk，sdk更新到10011分支，host.getPhoneScreenInfo().then()...   获取数据

**Comment by mirse** [comment]
> 请使用最新apk，sdk更新到10011分支，host.getPhoneScreenInfo().then()... 获取数据

我在全面屏上（mix 2s），上获取屏幕高度用host.getPhoneScreenInfo().then()... 和Dimensions.get(‘window")时一样的，还是存在问题
