### ISSUE TITLE
ListItemWithSwitch 开关问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#641]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android/iOS]
- SDK分支: [SDK_10004]

#### 现象
在设置页面使用ListItemWithSwitch, 每次进入设置页时会在componentDidMount跟设备拿开关状态, 取得成功后使用this.setState更新状态, 但无论在这取得的是true或false, 更新后ListItemWithSwitch开关状态都没有变化, 一直都是constructor内this.state的初始值。

#### 尝试过的解决办法

在同样的流程上使用Switch做显示是正常的。

**Comment by LiuMengzhou** [comment]
收到，问题已定位，下午更新。

**Comment by LiuMengzhou** [comment]
@CJackKao [https://github.com/MiEcosystem/miot-plugin-sdk/commit/50edf4d734fb5c851321046773bd22b326f6b883#diff-82c83cf164e59727b50fa3a8419c19ba](commit)
