### ISSUE TITLE
希望提供一个判断当前Android手机是否是[带有NFC功能的小米手机]的接口

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#642]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[Android 5.0+]
- SDK分支: [master]
- 相关模块:[eg.Host/Service/Account]

#### 现象

需要用到一个判断Android手机是否是[带有NFC功能的小米手机]的接口。
#### 期望

希望有这个接口，需要判断是带NFC功能的小米手机后，然后从门锁插件点击跳转小米钱包APP开门卡。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/46777658/56631409-c26c3400-6687-11e9-86db-d6ad95ff42b4.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by lvjie0519** [comment]
确认一下，您这里是两个需求对吗？
1、提供一个api，判断手机是否具有NFC功能？（只需要针对小米手机吗？）
2、提供一个api，跳转到小米钱包页面？

**Comment by WeizhiKong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi,1、是的，首先需要判断当前手机是小米手机，然后再判断是否具有NFC功能（这个可能需要写成两个API）；2、还有一个跳转小米钱包的API,原来原生的接口提供如下：Uri uri = Uri.parse("https://tsmclient.miui.com?action=issue_mifare&type=1&product_id=66666-00211&source_channel=mijia”);跳转前还需要判断小米钱包版本是否支持：tsmPackageInfo = context.getPackageManager().getPackageInfo("com.miui.tsmclient", 0);
int tsmClientVersionCode = tsmPackageInfo.versionCode;这个tsmClientVersionCode>=41才支持。
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
Best Regards 孔维志 Kung研发部 深圳绿米联创科技有限公司  Lumi United Technology Co., LtdMobile：(86) 13530995201Add：深圳市南山区桃源街道留仙大道塘岭路1号金骐智谷大厦801-806.8th Floor, JinQi Wisdom Valley, No.1 Tangling Road, Liuxian Ave, Taoyuan Residential District, Nanshan District, Shenzhen.


        
    
     
    

    On 04/25/2019 09:12，小米-吕杰<notifications@github.com> wrote： 


确认一下，您这里是两个需求对吗？
1、提供一个api，判断手机是否具有NFC功能？（只需要针对小米手机吗？）
2、提供一个api，跳转到小米钱包页面？

**Comment by WeizhiKong** [comment]
你好，问一下这个接口可以什么时候上线提供使用？

**Comment by Woody2016** [comment]
android这块人力较紧张，估计最快也要到5.22之后了

**Comment by WeizhiKong** [comment]
@Woody2016 好的，THX

**Comment by WeizhiKong** [comment]
@Woody2016 @lvjie0519  hi，我们插件马上就要测试了，问下这个接口什么时候能提供呀，已经一个月了( ⊙ o ⊙ )

**Comment by WeizhiKong** [comment]
@Woody2016 @lvjie0519 各位老板，这几个接口有排期么，我们插件马上要提测了

**Comment by lvjie0519** [comment]
@WeizhiKong   ok，最晚下周提供debug包。

**Comment by WeizhiKong** [comment]
@lvjie0519 今天能提供么😭😭😭

**Comment by lvjie0519** [comment]
@WeizhiKong   请加微信(18750118631)，详聊下。

**Comment by Woody2016** [comment]
@lvjie0519 @WeizhiKong  此问题正在支持中，初步估计明下班前给测试包

**Comment by lvjie0519** [comment]
@WeizhiKong   请使用最新apk进行测试， rn sdk选择 10021分支；
判断是否为小米手机： Host.systemInfo.isXiaomiPhone 
判断是否支持NFC:  Host.phoneHasNfcForAndroid().then
跳转到小米钱包： Host.ui.openMiPayPageForAndroid

**Comment by WeizhiKong** [comment]
@lvjie0519 Host.systemInfo.isXiaomiPhone这个接口在10021分支上没找到，另外两个有

**Comment by lvjie0519** [comment]
> @lvjie0519 三个接口都已经验证OK了；
> 但Host.systemInfo.isXiaomiPhone这个接口在10021分支上没找到，另外两个有。

Host.systemInfo.isXiaomiPhone  只是一个变量，   不是方法。

**Comment by WeizhiKong** [comment]
@lvjie0519 嗯，是变量，已经验证OK，issue可以close了
