### ISSUE TITLE
Host.storage.get(key) 同一个key在不同的插件里面取出的值不一样

### ISSUE THREAD

**Issue by hualaikeji** [MiEcosystem/miot-plugin-sdk#644]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:Mac OS
- 手机系统:iOS 12
- SDK分支: master/10001
- 相关模块:Host/storage

#### 现象

let key = '007';
我在调试的时候发现的这个问题:
使用Host.storage.get(key)获取的值为空,
具体场景是>>> 我有两个以上的同一个款产品,分别先后进入不同的插件(同一款产品),在一个插件中设置Host.storage.set(key,val),之后进入另一个插件Host.storage.get(key)取出的值为空,
目前只在iOS上发现这个问题

#### 期望
尽快回复

**Comment by blockdate** [comment]
目前iOS与Android存在一定差异，iOS的key是根据did来区分的(Android）并没有区分，这个后续会有更新，不建议跨设备使用这个方法。

如果需要同一个插件跨越did来操作数据，建议使用文件读写的格式。
