### ISSUE TITLE
更新miot-plugin-sdk后startDiscoverServices不能发现Services，开关手机蓝牙米家APP会闪退

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#645]
#### 现象
更新miot-plugin-sdk后调用startDiscoverServices不能发现Services，也收不到bluetoothConnectionStatusChanged通知，在插件中开关IOS手机蓝牙会导致米家APP会闪退，但是没有任何错误打印出来。更新之前蓝牙调试一直是正常的。startDiscoverServices调用方法如下：
```java
MHBluetoothLE.connect(-1).then((data) => {
                    ble = Bluetooth.createBluetoothLE(data.uuid);
                ble.startDiscoverServices(UUID_SERVICE,SPOTA_SERVICE_UUID,AUDIO_SERVICE_UUID);
                }).catch((data) => {
                    console.log("error", data);
                });
```

**Comment by blockdate** [comment]
正在处理中，startDiscoverServices 请更新SDK 10005或者10010后使用

开关蓝牙闪退问题正在处理中稍后更新app

**Comment by blockdate** [comment]
APP已更新，请更新后再试

**Comment by fengdexunmi** [comment]
@blockdate SDK升级到10010还存在以上的问题

**环境**
iOS iPhone 8 Plus
SDK 10010

**现象** 
```JavaScript
Device.getBluetoothLE.connect(1, { timeout: 10000 }).then((data) => {
      console.log('connected', data);
      DeviceBluetoothLE.startDiscoverServices(UUID_SERVICE);
    }).catch((data) => {
      console.log('err', data);
    });
  }
```
上述代码返回
{message: "bluetooth is connecting", code: 100}

关掉蓝牙直接闪退

**Comment by heping99** [comment]
我这边验证还是有这个问题，环境：
iOS iPhone 8 Plus
SDK 10005

**Comment by blockdate** [comment]
请确认app 的icon 编号大于等于194

**Comment by fengdexunmi** [comment]
@heping99 你那边iOS iPhone 8 Plus可以正常蓝牙连接了么？

@blockdate 我这边
米家app 194版本
 iOS iPhone 8 Plus
SDK 10010
调用connect还是一直返回{message: "bluetooth is connecting", code: 100}

**Comment by heping99** [comment]
@blockdate 你好，这里说的”app 的icon 编号“不清楚指的是什么，在哪里可以查看？

**Comment by fengdexunmi** [comment]
@heping99 米家App icon上面有一个编号

@blockdate 我这边找到我这个iPhone 8 plus一直无法连接蓝牙的原因了，我这个iPhone 8 plus是新手机，从来没有走过安全验证的过程（我们这边是门锁相关的业务，有一个输入安全码校验的过程）但是测试App跑本地插件没有这个过程，我切到线上然后跑了下安全验证的过程就正常可以连上蓝牙了。
