### ISSUE TITLE
在智能页面中添加自动化“播放指定文字”时，无法跳转了文字输入界面。

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#647]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1 iOS 11.0]
- SDK分支: [10000]
- 相关模块:[Host/ui/openIftttAutoPage]

#### 现象

在最新米家APP上的智能页面中，添加自动化“播放指定文件”时，iOS和安卓都无法跳转到文字输入界面。但是如果不使用现在新框架的米家插件，就都能正常跳转。

#### 期望

iOS和安卓都能跳转到文字输入界面。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/46127660/56655121-78557380-66c4-11e9-8a71-9c90d625cec9.png)
![image](https://user-images.githubusercontent.com/46127660/56655156-8dca9d80-66c4-11e9-9dba-47e719ef4166.png)

**Comment by JobenTian** [comment]
第一张图是安卓的，一直在这个加载页面；第二张图是iOS的，点击播放指定文字，跳转不到文字输入的界面。

**Comment by blockdate** [comment]
这个是 自定义自动化目前存在问题导致的，现在正在积极处理中，预计在sdk10010中修复正常使用。

Related to #542

**Comment by JobenTian** [comment]
@blockdate 目前的SDK_10010是否已经修复了该问题了？

**Comment by blockdate** [comment]
这个正在更新测试包。同时插件需要更新project.json 配置，添加红框中的新增配置。
![image](https://user-images.githubusercontent.com/4339364/57187888-814a0e80-6f28-11e9-9b8a-3c3fd40d23c0.png)

**Comment by blockdate** [comment]
APP已更新， 编号200

**Comment by blockdate** [comment]
REF #325 #542

**Comment by JobenTian** [comment]
@blockdate 更新APP编号200，也更新project.json 配置，但还是跳转到文字输入界面。
![image](https://user-images.githubusercontent.com/46127660/57191475-cd14ac00-6f58-11e9-9250-2fb7ffe7527b.png)

**Comment by JobenTian** [comment]
@blockdate 更新APP编号200，也更新project.json 配置，但还是不能正常跳转到文字输入界面。
![image](https://user-images.githubusercontent.com/46127660/57203501-2e815d00-6fe3-11e9-9f80-7a68fe580a8f.png)

**Comment by blockdate** [comment]
设备分享到894158105， 同时描述下trigger的入口名称

**Comment by JobenTian** [comment]
设备已分享，trigger的入口是从开发者平台配置的吗？
红色框内的这两个参数，是不是要与project.json配置中一致？
![image](https://user-images.githubusercontent.com/46127660/57203694-dea39580-6fe4-11e9-840b-2262287e3125.png)

**Comment by JobenTian** [comment]
@blockdate 看到分享的设备了吗？是否有复现问题？

**Comment by blockdate** [comment]
分享设备无法调试自动化功能，这边提供下微信号吧，发送到wulei7@xiaomi.com

**Comment by santcool** [comment]
这个bug iOS和android均已解决，请下载最新的ipa测试。

**Comment by ldezho** [comment]
![IMG_167EF11199C8-1](https://user-images.githubusercontent.com/12531667/57269247-43c8bb00-70b9-11e9-9eb6-18ecf0a34e97.jpeg)
@JobenTian 你解决了吗？
@santcool 我这边调试点击进入自定义自动化页面，就出现截图所示页面。
刚下载的最新的ipa以及sdk_10010，project.json也已经配置：
`"entrance_scene": {
        "action_ids": [],
        "trigger_ids": [
            648,
            647,
            1099,
            1100
        ]
    }`

**Comment by JobenTian** [comment]
@ldezho 你这是debug环境都有问题，无法加载自定义自动化页面。

**Comment by ldezho** [comment]
@JobenTian  是的啊，你那边可以吗？

**Comment by JobenTian** [comment]
@ldezho 我这里是可以的。你这个属于开发环境的问题，先把开发环境调好。

**Comment by ldezho** [comment]
![IMG_0033](https://user-images.githubusercontent.com/12531667/57280649-c3678180-70db-11e9-910b-77eda2addcd7.jpg)
1、通过米家自带的智能入口进入，可以跳到自定义智能页面。通过Host.ui.openIftttAutoPage();这个api在插件页里面进入智能页面就出现上述问题。
2、下图中的id，没记错的话，之前应该是sc_id。希望改动可以加入到CHANGELOG.md中（这个好像很久没人维护了）。 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/12531667/57280815-2eb15380-70dc-11e9-80e5-75b24ebf61b2.png">
@blockdate @santcool 希望可以帮忙看下

**Comment by ldezho** [comment]
@JobenTian 你的自定义自动化页面，两个入口都可以正常进入吗？
1、Host.ui.openIftttAutoPage();
2、上面截图中米家自带的智能页面。
我目前2可以正常进入，1会出问题。

**Comment by ldezho** [comment]
这个issue是不是关了后就不怎么看了啊

**Comment by blockdate** [comment]
一个issue只讨论一个问题，衍生问题新建issue处理

**Comment by ldezho** [comment]
好的
