### ISSUE TITLE
创建定时器返回permission denied

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#648]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
centos 7.5
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8.1
- SDK分支: [eg.master/10000/...]
10003
- 相关模块:[eg.Host/Service/Account]
Service
#### 现象
简单明了地描述一下实际的现象。
创建一个定时器场景 调用 scene.save() 返回 permission denied （设备处于离线状态，是因为这个原因吗？）
#### 期望
简单明了地描述一下期望的表现。
返回正确，能正确创建定时器
#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
一般出现这个问题很可能是设备是分享过来的，请检查下设备的owner
