### ISSUE TITLE
上传扩展程序出错-打包失败

### ISSUE THREAD

**Issue by huanghaibing** [MiEcosystem/miot-plugin-sdk#650]
如图所示
![image](https://user-images.githubusercontent.com/17466149/56703509-bd68bc80-673b-11e9-91af-d6626bbba6fb.png)

上传成功后，状态一直显示“打包中”，刷新后状态显示“打包失败”。重试了好多次都是打包失败

**Comment by blockdate** [comment]
在感叹号上查看下打包错误原因，发送一下

**Comment by huanghaibing** [comment]
{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":14782,"Complete":true,"Exit":1,"Error":null,"StartTs":1556170304281469264,"StopTs":1556170326638110011,"Runtime":22.356640814,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/temp_b56121e5_23ee_4f64_900d_0e00a2ea8e7a","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/bin/buildBundle.js --android --target /tmp/1556170304281429449/release/android com.xiaomi.mjqj","/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile","","[MIOT]start to build android bundle for com.xiaomi.mjqj","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/com.xiaomi.mjqj","output /tmp/1556170304281429449/release/android","","Loading dependency graph, done.","","","error：","","error：Unable to resolve module `../../../../com.xiaomi.demo/CommonModules/LocalizedStrings` from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/com.xiaomi.mjqj/src/pages/home/Home.js`: The module `../../../../com.xiaomi.demo/CommonModules/LocalizedStrings` could not be found from `/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/com.xiaomi.mjqj/src/pages/home/Home.js`. Indeed, none of these files exist:",""," * `/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/com.xiaomi.demo/CommonModules/LocalizedStrings(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`"," * `/home/ocean/mesos/sandbox/data/MIOT_SDK_10002_1556170295438435575/compile/projects/com.xiaomi.demo/CommonModules/LocalizedStrings/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`","","error：",""],"Stderr":[]}

**Comment by blockdate** [comment]
别引入自身项目之外的文件，错误信息很明确了，你引入了demo中的文件

**Comment by huanghaibing** [comment]
谢谢！！
