### ISSUE TITLE
关于：国内插件无法同步至海外服务器

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#651]
#### 环境
- 手机系统:Android  和 iOS 

#### 现象

新框架下的海外服务器同步是每一小时自动同步一次，可是目前我已经超过一小时仍然未查看到有成功同步。

#### 期望

想问下这个机制应该如何实现？是否还要操作什么？

**Comment by huangjr126** [comment]
@blockdate 您好吴磊，帮忙看一下~比较着急。谢谢！

**Comment by blockdate** [comment]
提供下公司id和插件id，插件id可以在插件页面的网址中获取

**Comment by huangjr126** [comment]
@blockdate 
公司ID：10099
插件ID：417

**Comment by blockdate** [comment]
已修复
