### ISSUE TITLE
BluetoothEvent.bluetoothCharacteristicDiscovered.addListener((bluetooh, service, characters)中characters在iOS平台下为0长度的数组？

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#652]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...] 1004
- 相关模块:[eg.Host/Service/Account]

#### 现象

BluetoothEvent.bluetoothCharacteristicDiscovered.addListener((bluetooh, service, characters)中characters在iOS平台下为0长度的数组
在android下有值

之前是有值的，不知道最近怎么没了。。。

#### 期望

期望和之前一样正常。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
请提供下使用过程中的详细日志输出。

**Comment by ldezho** [comment]
![image](https://user-images.githubusercontent.com/12531667/56711004-696dd000-675b-11e9-847f-da6e8bc8dc03.png)
![image](https://user-images.githubusercontent.com/12531667/56711031-8e624300-675b-11e9-8c19-8ce851eb537e.png)
@blockdate 看日志是找到了characteristic，但是没有传出来。。。

**Comment by blockdate** [comment]
你发送的日志中红框1 的日志 是你发送给app端要扫描的 特征值，并不是native端扫描到的特征值。

从红框1 下面第二行日志来看，native发现的特征值为空，所以发送给js端的特征值是个空数组。

**Comment by blockdate** [comment]
方便用lightblue 这个app查看下iOS下该设备 Service FE59下面的特征值列表么，截个图看一下。

**Comment by ldezho** [comment]
> 你发送的日志中红框1 的日志 是你发送给app端要扫描的 特征值，并不是native端扫描到的特征值。
> 
> 从红框1 下面第二行日志来看，native发现的特征值为空，所以发送给js端的特征值是个空数组。

@blockdate 多谢提示，看了您的回复后我对比了一下Service FE59下的特征值，确实没有这两个特征。

**Comment by ldezho** [comment]
但是这个好奇怪啊，是不是之前无论我要扫描的 特征值是多少，都不会影响返回给js的特征值？是不是这个地方的逻辑改了？

**Comment by blockdate** [comment]
这个地方的逻辑应该没有调整，iOS 上如果指定的特征的uuid，则只会扫描指定的uuid。

**Comment by ldezho** [comment]
好的，谢谢。有点奇怪...😂
