### ISSUE TITLE
推送消息无法获取指纹密码的昵称（已按照要求配置）

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#653]
#### 现象

根据文档要求，用batchSetDeviceDatas   替代setDeviceSetting   进行了配置，
![image](https://user-images.githubusercontent.com/16306138/56710273-da12ed80-6757-11e9-918c-e71960f4a942.png)

用batchSetDeviceDatas  能够成功存数据，用batchGetDeviceDatas也能成功取数据。
存数据的截图如下

![image](https://user-images.githubusercontent.com/16306138/56710351-44c42900-6758-11e9-88c0-335adecce787.png)
我用“测试0”这个密码开门，收到的推送消息中，并没有“指纹0”的昵称
#### 期望

成功设置后，指纹的昵称能够在推送消息中显示

**Comment by blockdate** [comment]
这个两个接口是用于在app端存储数据信息用的，如果需要定制推送消息，请调整固件端，参考 [消息推送](https://iot.mi.com/new/guide.html?file=03-%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/02-%E6%99%BA%E8%83%BD%E7%A1%AC%E4%BB%B6%E7%9B%B4%E8%BF%9E%E6%8E%A5%E5%85%A5/07-%E9%85%8D%E7%BD%AE%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81)

**Comment by changgongxinshi** [comment]
我们不需要定制的推送消息，之前的邮件沟通，让我们按照推送模板发邮件如下图：
![image](https://user-images.githubusercontent.com/16306138/56719705-e1e08b00-6773-11e9-88a0-29d3a6b63ea3.png)
我们已经能收到这种通用模板的推送了，但是如果用指纹或者密码开门，推送上是不会显示指纹和密码的昵称的。
之前沟通的邮件的附件如下
![image](https://user-images.githubusercontent.com/16306138/56720110-a5615f00-6774-11e9-9ec2-56775ba56e24.png)
我们走的是蓝牙网关推送，蓝牙网关推送，不也是蓝牙网关解析好数据后，上报给你们的服务器，你们的服务端再推送的吗？
还是说如果我们要带着指纹密码昵称的推送，必须要使用“定制推送消息”的方式？
