### ISSUE TITLE
设置页CommonSetting时区问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#654]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android/iOS]
- SDK分支: [SDK_10004]

#### 现象

设置页面中并没有设置secondOptions.TIMEZONE, 但是进入更多设置页后还是会显示设备时区, 请问设备时区是必选吗?

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/56716635-6c71bc00-676d-11e9-8527-8cf6257a87ad.png)

**Comment by CJackKao** [comment]
但是我并没有设置secondOptions.TIMEZONE, 时区也显示了, 同样的问题在second_options.AUTO_UPGRADE也有发生。

**Comment by LiuMengzhou** [comment]
@CJackKao 已定位问题，明天之前更新

**Comment by LiuMengzhou** [comment]
@CJackKao f7fd3e3e0d95b63e8be7e0e688f9a89299793909
