### ISSUE TITLE
Device.getDeviceWifi().callMethod 抛出异常

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#657]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
linux
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 8
- SDK分支: [eg.master/10000/...]
10000
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。
Device.getDeviceWifi().callMethod("command",params).then(res=>{
      if(res.result[0]==1){
        let refCfg = {}
        this._refreshWindSpeed(refCfg);
        this._refreshMode(refCfg);
        refCfg.powerStatus = this.state.powerStatus,
        refCfg.turnOff=this.status.turnOff
        this.setState(refCfg);
        Alert.alert(JSON.stringify(res));
      }
    }).catch(exp=>{
        this.setState({errorstr:JSON.stringify(exp)})
    });
返回如下异常
![image](https://user-images.githubusercontent.com/11848308/56742853-1a9a5780-67a8-11e9-8374-11b96a931460.png)

#### 期望
正确调用

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by uSmile-Y** [comment]
更新app及sdk后出现如下问题
![image](https://user-images.githubusercontent.com/11848308/56744820-c8f3cc00-67ab-11e9-8a3a-e26629ec8dd0.png)

**Comment by lvjie0519** [comment]
@uSmile-Y  我这边一直无法复现如上问题，请加微信（微信号：18750118631），详聊下，谢谢。

**Comment by blockdate** [comment]
getWifiInfo这个问题，请将详细的错误信息提供下。

**Comment by uSmile-Y** [comment]
已经解决了，是同一个问题
