### ISSUE TITLE
更新SDK后插件就不能用了,紧急

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#658]
#### 环境

- SDK分支: [MIOT SDK API_LEVEL is 10005  ]

#### 现象

早上pull了一下SDK之后，在手机客户端重新加载则直接退出，显示白屏 ，错误是由于重新定义`setDeviceProp`  ，全局搜了下，发现smarthome.js 里面 486 和464 定义了两个相同的方法 
```javascript
setDeviceProp(params) {
         return Promise.resolve(null);
    },
```

**Comment by uSmile-Y** [comment]
#657 一样的问题

**Comment by lvjie0519** [comment]
@xuanxuandaoren  @uSmile-Y   刚修复， 更新下sdk，选择10010分支试试，谢谢
