### ISSUE TITLE
请提供“获取文件的MD值”的功能函数，以便校验文件的完整性！

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#659]
#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/file]

#### 现象
host.file.downloadFile可能会意外下载不完整的文件

#### 期望
提供一个函数获取下载文件的MD5值，以校验文件是否完整 。

**Comment by dgutkai** [comment]
请问最新版本的有增加这个功能吗？我也遇到需要读取文件的MD5值的问题。使用第三方库都只能对字符串进行MD5。

**Comment by Banjiemin** [comment]
好像没有

**Comment by Banjiemin** [comment]
蓝牙OTA升级，下载文件还是存在风险，请提供“获取文件的MD值”的功能函数，以便校验文件的完整性 ！

**Comment by Banjiemin** [comment]
npm install crypto-js --save

Host.file.readFileToHexString(path).then((hexString) => {			
		var len = hexString.length;
		var byte = [];
		for (var i = 0; i < len; i += 8) {
			byte[i / 8] = parseInt(hexString.substr(i, 8), 16);
		}

		var CryptoJS = require("crypto-js");
		//var wordArray = CryptoJS.lib.WordArray.create([0x00010203, 0x04050607])
		var wordArray = CryptoJS.lib.WordArray.create(byte);
		var md5 = CryptoJS.MD5(wordArray);
	})
