### ISSUE TITLE
Device.bluetooth.securityLock 加解密方法疑惑

### ISSUE THREAD

**Issue by halloaw** [MiEcosystem/miot-plugin-sdk#66]
```javascript
Device.bluetooth
  .connect(1)
  .then(bt => {
    console.log('connect success', bt);
    Device.bluetooth.securityLock
      .encryptMessage('hello world')
      .then(s => {
        console.log('encryptMessage success', s);
      })
      .catch(e => {
        console.log('encryptMessage fail', e);
      });

    Device.bluetooth.securityLock
      .decryptMessage('foobar')
      .then(s => {
        console.log('decryptMessage success', s);
      })
      .catch(e => {
        console.log('decryptMessage fail', e);
      });
  })
  .catch(e => {
    console.log('connect fail', e);
  });
```
安卓对应的 log：
![image](https://user-images.githubusercontent.com/8953556/49146681-a44f1180-f33d-11e8-8fb1-9b4e31575767.png)
看起来加密方法返回的结果不符合预期；解密方法没有返回值。

iOS 对应的 log：
![image](https://user-images.githubusercontent.com/8953556/49146970-5555ac00-f33e-11e8-99d5-a6621f600922.png)
最新的 DB 包测试结果。

**Comment by Copypeng** [comment]
用来加解密的数据应该是 "001122EEFF" 这种 hex string 吧。

**Comment by dzonel** [comment]
@Copypeng 您好，我这边也有相同的情况，我这边是这种数据，就是之前的MHXiaomiBLE.encryptMessageXiaoMiBLE和MHXiaomiBLE.decryptMessageXiaoMiBLE

**Comment by halloaw** [comment]
最新测试，iOS 加解密可以了，Android 解密方法失败。
