### ISSUE TITLE
希望米家0.54框架增加原生接口获取手机所连接路由器的mac地址

### ISSUE THREAD

**Issue by jianbin-rockrobo** [MiEcosystem/miot-plugin-sdk#660]
希望米家0.54框架增加原生接口获取手机所连接路由器的mac地址

用于比较设备连接的路由器的地址，来判断手机和设备是否在同一局域网

需要安卓、iOS分别添加这个接口

**Comment by blockdate** [comment]
该功能已提供， Host.getWiFiInfo

**Comment by Woody2016** [comment]
这个接口现在就有
miot/Host.getWifiInfo() 
ssid是Wi-FI名称，bssid是Wi-Fi的mac地址
