### ISSUE TITLE
Service.tjinfra.getIRCode Android调用错误

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#661]
错误如下
com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String

这个涉及到另外一个接口downloadRemote，返回的数据中data就是一个数组类型，然后传入getIRCode，传入的data需要的是一个字串类型

如下图
![1](https://user-images.githubusercontent.com/49702230/56788509-44985c00-6832-11e9-9f86-fbe53e01b637.png)

![2](https://user-images.githubusercontent.com/49702230/56788514-4a8e3d00-6832-11e9-9703-70391b051c9a.jpg)

**Comment by lvjie0519** [comment]
@daoke666 问题如已解决，请关闭下issue，谢谢。

**Comment by christophermitchell070** [comment]
Go The Fuck away Stupid Ass People
