### ISSUE TITLE
设置页面更多设置崩溃问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#663]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [SDK_10004]

#### 现象

设置页中使用CommonSetting, 在secondOptions中设置second_options.AUTO_UPGRADE, 点击更多设置直接崩溃
![IMG_0705](https://user-images.githubusercontent.com/49632045/56791097-da36ea00-6838-11e9-9e72-5da67388f253.PNG)

**Comment by LiuMengzhou** [comment]
下个issue的描述详细点吧。
每次都要猜测。
你这个是本地调试没问题，打包上传后，云端拉取的插件内有问题？

**Comment by LiuMengzhou** [comment]
还有本地调试和iot后台打包都是用的SDK_10004？

**Comment by LiuMengzhou** [comment]
已经定位到问题，下午解决

**Comment by LiuMengzhou** [comment]
c8b4cb60c31aa0cf6a4c940f836ad4fe6280255f
