### ISSUE TITLE
设置页"使用帮助"设置项问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#664]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [SDK_10004]

#### 现象

有关目前设置页"使用帮助"设置项, 根据收到的最新文挡问题如下
1. 此选项会显示在更多设置内, 但目前是显示在一级页面。
2. 文案显示有误, 应为"常见问题"。

**Comment by LiuMengzhou** [comment]
我这边是跟产品同步过的
