### ISSUE TITLE
蓝牙读值慢

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#665]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS
- SDK分支: [eg.master/10000/...]master
- 相关模块:[eg.Host/Service/Account]蓝牙

#### 现象

测试工程师反馈开启长连接后，设备连接的慢，经过查看本地日志发现在长连接下（使用type3普通的BLE蓝牙设备方式连接的设备)，先发现Characteristic然后读值，之后接收到返回值监听bluetoothCharacteristicValueChanged，这一过程耗时比直接连接的蓝牙设备耗时要长，麻烦看下是不是长连接做的处理不一样？

PS:调试时还发现一个问题，插件退出后Native端可能没有销毁蓝牙监听，在日志里会看到随着打开插件的次数增多原生端返回的监听依次增多。

#### 期望

长连接下，缩短读值过程耗时

长连接：
![image](https://user-images.githubusercontent.com/11364809/56794962-f55a2780-6841-11e9-95ea-b20b2b8ff04d.png)
直接连接：
![image](https://user-images.githubusercontent.com/11364809/56795008-0efb6f00-6842-11e9-9567-dc6b44de6b1c.png)

**Comment by blockdate** [comment]
1. 监听问题我们会处理。
2. 蓝牙的连接上我们并没做特殊的处理，都是透传系统提供的蓝牙api。
