### ISSUE TITLE
设备端控制调用方式优化

### ISSUE THREAD

**Issue by Bijiabo** [MiEcosystem/miot-plugin-sdk#667]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] macOS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.2
- SDK分支: [eg.master/10000/...] master
- 相关模块:[eg.Host/Service/Account] Service/spec, Device

#### 现象

API 调用里面要写 siid, piid 感觉很难受

```
const data = await Service.spec.getPropertiesValue([{
    did: Device.deviceID,
    siid: 1,
    piid: 4,
}])
```

#### 期望

```
const data = await Service.spec.getPropertiesValue([{
    did: Device.deviceID,
    siid: DeviceDefinition.Environment.Temperature.siid,
    piid: DeviceDefinition.Environment.Temperature.piid,
}])
```

#### 尝试过的解决办法

目前是从后台的 spec 产品定义界面复制 JSON 配置，转换成一个新的 JSON 格式引用到扩展程序开发中，直接通过属性名传入 `DeviceDefinition.服务名.属性名.piid`。

### 不要贴大段代码❗️

格式转换逻辑：https://gist.github.com/Bijiabo/b0bac9941533da96edf7092330da15ff

**Comment by Woody2016** [comment]
这个问题属于接口使用优化，优先级不高，等人力不紧张时再考虑排期

**Comment by Bijiabo** [comment]
👌

**Comment by Woody2016** [comment]
此问题先close
有问题请去小米开发者平台提工单
谢谢

**Comment by Bijiabo** [comment]
什么情况？按照这个逻辑，所有问题现在都可以关闭，然后让大家再去开发这平台提一遍？
