### ISSUE TITLE
debug米家 协议加载出问题了，把标签都加载出来了

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#668]
安卓 ios 一样。193米家Ios debug 
![8661556420857_ pic_hd](https://user-images.githubusercontent.com/38349220/56858110-ab8b5180-69a7-11e9-9d47-b5b272663d62.jpg)
![8441556419174_ pic](https://user-images.githubusercontent.com/38349220/56858111-af1ed880-69a7-11e9-8627-7a44a0876dd8.jpg)
![8661556420857_ pic_hd](https://user-images.githubusercontent.com/38349220/56858115-b47c2300-69a7-11e9-992f-aad27bb1fe2c.jpg)
![Uploading 8541556419677_.pic_hd.jpg…]()

**Comment by blockdate** [comment]
米家协议文件 建议使用编码格式 utf8bom， 使用 vscode 右下角点击编码格式，选择使用格式另存为utf8bom
