### ISSUE TITLE
iOS新app无法开锁

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#669]
before issue：（不用回答）
### IPA/APK 是否更新到最新？
最新iOS包194版本
### SDK 是否更新到最新？
SDK是10003分支最新
---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[iOS 12.2]
- SDK分支: [10003]
- 相关模块:[Bluetooth]

#### 现象

更新了最新app，出现无法开锁现象，之前都是OK的，查看过手机日志提示开锁失败蓝牙未连接，Device.getBluetoothLE().isConnected  true，手机也显示蓝牙已连接，BluetoothEvent.bluetoothConnectionStatusChanged.addListener  也是连接状态；

#### 期望

蓝牙开锁正常

#### 其他的上下文/日志/截图

<img width="1016" alt="WechatIMG4657" src="https://user-images.githubusercontent.com/13412744/56858161-5c91ec00-69a8-11e9-847f-4c373aeb8a48.png">

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供下toggle 方法返回的具体错误信息

**Comment by blockdate** [comment]
看你的使用方式应该是下载插件包进行测试，建议更新app至最新测试版200.
