### ISSUE TITLE
LoadingDialog不显示message？

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#67]
LoadingDialog设置title和message，只显示title不会显示message

**Comment by pencilCool** [comment]
你好，请在提bug 的时候，说明一下是iOS还是安卓上面出现的问题，以及你是怎么使用的

**Comment by dzonel** [comment]
@pencilCool 抱歉，提供的信息不够。
机型：iPhone 6
![1543462102256](https://user-images.githubusercontent.com/12531667/49197457-eaea4d80-f3c9-11e8-9cb3-c0fedcf3953d.jpg)
使用：
![1543462308574](https://user-images.githubusercontent.com/12531667/49197599-66e49580-f3ca-11e8-9576-dcb60f8dd587.jpg)
结果：
![img_094ddee8b826-1](https://user-images.githubusercontent.com/12531667/49197610-6ea43a00-f3ca-11e8-9fbc-239dd932f611.jpeg)

this.loadingDialog.message无论是初始时就设置值，还是使用时设置值，都无法显示。title则是有的。

**Comment by dzonel** [comment]
MessageDialog 也有同样的问题

**Comment by dzonel** [comment]
MessageDialog 第一次显示的时候，message为空，再次让它显示就有值了。可以确定第一次显示之前已经给message赋值

**Comment by pencilCool** [comment]
你好，安卓和iOS这边统一成 只设置title可

**Comment by dzonel** [comment]
好的，收到。
