### ISSUE TITLE
线上版米家海外服务器无法进入插件

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#670]
before issue：（不用回答）
### IPA/APK 是否更新到最新？YES

---

#### 现象

model为chuangmi.plug.hmi206,调试过新RN插件后开发平台上取消了新RN支持，应当海外国内服务器都可以下载老插件进行使用，但验证下来，海外服务器无法下载插件进入使用

海外android版本15，ios版本20
新RN插件版本9（暂已去除该产品model）

#### 期望

海外服务器能下载老插件进行使用

#### 其他的上下文/日志/截图

![1111556419197_ pic_hd](https://user-images.githubusercontent.com/8665213/56858122-c8c02000-69a7-11e9-8d91-07087042f53d.jpg)
![1556421841258](https://user-images.githubusercontent.com/8665213/56858169-6b789e80-69a8-11e9-8be9-a175648c1903.jpg)
![1556422007072](https://user-images.githubusercontent.com/8665213/56858181-8d722100-69a8-11e9-9bea-74f296eb8ac6.jpg)

#### 尝试过的解决办法

删除米家重新下载无效

**Comment by blockdate** [comment]
这个问题系 海外插件 同步时，存储插件的服务节点映射错误，导致插件下载404错误，这个问题目前预计在五一节后修复

**Comment by blockdate** [comment]
已修复
