### ISSUE TITLE
线上版本【撤销隐私协议授权】插件报错

### ISSUE THREAD

**Issue by RengeRenge** [MiEcosystem/miot-plugin-sdk#671]
线上版本撤销隐私协议授权插件报错
beta版本没有问题

api level： 10001
环境： iOS

![4691556432202_ pic_hd](https://user-images.githubusercontent.com/14158970/56860080-e2bc2b80-69c4-11e9-8680-98db87b0d9be.jpg)

**Comment by blockdate** [comment]
修正版app已在审核中。
