### ISSUE TITLE
关于用正式版米家测试蓝牙连接问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#672]
您好，
      我这边把小米账号添加到测试白名单了，用正式版的米家app去连接测试
       在安卓平台上没有这个问题，但是在ios上遇到的问题如下：
      第一次连接可以连接成功，但是断开之后，第二次连接就连接失败了。必须要把app重启，才可以连接。
      
      但是这个问题，在目前米家beta版194版本是没有的，可以多次断开连接。
      所以不知道这是什么情况呢。。。

**Comment by blockdate** [comment]
断开是指退出插件还是断开蓝牙连接。
这边提供下关键节点的代码，和设备日志吧。

**Comment by caojunhua** [comment]
> 断开是指退出插件还是断开蓝牙连接。
> 这边提供下关键节点的代码，和设备日志吧。

断开是指退出插件，然后再次进入连接就连接不上。
由于是用米家正式版的，所以也没法打印日志信息。
在ios手机上，iPhone8和iPhone xs都有遇到这种情况。

**Comment by blockdate** [comment]
建议确认下退出插件时，是否手动断开了蓝牙连接。

至于查看日志，将手机连接到电脑上,通过 xcode->window->device 选择open console可以查看设备时时日志。

**Comment by blockdate** [comment]
不活跃
