### ISSUE TITLE
chuangmi.plug.m1 IOS无法使用新RN插件线上测试

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#673]
#### 现象

model:chuangmi.plug.m1 IOS无法使用新RN插件线上测试，一直进老原生代码，
开发本地测试android和ios新RN没问题

#### 期望

chuangmi.plug.m1 IOS能使用新RN插件

**Comment by blockdate** [comment]
1. 插件已上传iot 平台并开启测试
2. 插件在上传页面中已关联对应model
3. 确认测试账号是属于公司企业下的白名单用户

**Comment by yanmin0220** [comment]
> 1. 插件已上传iot 平台并开启测试
> 2. 插件在上传页面中已关联对应model
> 3. 确认测试账号是属于公司企业下的白名单用户
> 
> 请确认以上内容

1.新RN插件版本9已开启测试
2.新RN插件已管理m1的model
3.测试账号是企业白名单

测试人员用android是可以测新RN插件的

**Comment by blockdate** [comment]
开发的SDKLevel是否是高于 10004 并且打包选择的level 是 10004， 目前10004已发布，但是对应的iOS app尚处于审核中，因此线上的正式版本尚不能加载该版本的插件(Andrdoi 已发布)， 建议使用测试app。

**Comment by yanmin0220** [comment]
> 开发的SDKLevel是否是高于 10004 并且打包选择的level 是 10004， 目前10004已发布，但是对应的iOS app尚处于审核中，因此线上的正式版本尚不能加载该版本的插件(Andrdoi 已发布)， 建议使用测试app。


新RNsdk是10003，上传也是选择的10003，是要使用10004吗
