### ISSUE TITLE
Host.ui.openDevice(did, model,params)接口调用导致插件应用崩溃问题

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#674]
before issue：（不用回答）
### 是否尝试搜索issue？是

---

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac
- 手机系统:[eg.Android 8.1/iOS 11.0] Android 8.1.0
- SDK分支: [eg.master/10000/...] master
- 相关模块:[eg.Host/Service/Account] Host

#### 现象

简单明了地描述一下实际的现象。
我在处理业务逻辑的时候需要调用openDevice接口，
1.Host.ui.openDevice传入具体参数
2.插件奔溃

#### 期望
1.插件不崩溃
2.能跳转进入指定插件

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
提供下使用的具体场景参数以及插件的错误信息

**Comment by wanggoingdown** [comment]
情况是这样的：
1.我在插件里面执行 console.log(Host.ui.openDevice('1010204045', 'lumi.lock.mcn01', null));
2.发生的现象是应用直接退出到米家app的首页设备列表
3.查看日志得到了反馈为Promise {_40: 0, _65: 0, _55: null, _72: null}
正常预期是执行完Host.ui.openDevice直接跳往指定门锁设备插件页面

**Comment by zanetti4** [comment]
1.请提供安卓系统的米家APP版本。
2.确认执行 openDevice 方法传入的参数是否正确。

**Comment by lingzhiwen** [comment]
> 1.请提供安卓系统的米家APP版本。
> 2.确认执行 openDevice 方法传入的参数是否正确。

1.米家APP版本：5.5.21.1 (Build 62874) - 84.66 MB
更新于: 2019-05-20 20:35

2.确认参数正确，分别为：did，model，null
执行代码如下：
```
var result = Host.ui.openDevice('lumi.158d0002337fa8', 'lumi.sensor_switch.aq2', null);
console.log(result);

//打印日志：  Promise {_40: 0, _65: 0, _55: null, _72: null}
```

**Comment by zanetti4** [comment]
请把 lumi.sensor_switch.aq2 对应的门锁设备分享给我，我的米家 id: 894158105.
另外，openDevice 第三个参数是否试过 {}，因为注释里写的是对象类型。

**Comment by lingzhiwen** [comment]
> 请把 lumi.sensor_switch.aq2 对应的门锁设备分享给我，我的米家 id: 894158105.
> 另外，openDevice 第三个参数是否试过 {}，因为注释里写的是对象类型。

1.第三个参数试过{}也是一样的报错日志

**Comment by lingzhiwen** [comment]
> 请把 lumi.sensor_switch.aq2 对应的门锁设备分享给我，我的米家 id: 894158105.
> 另外，openDevice 第三个参数是否试过 {}，因为注释里写的是对象类型。

1.第三个参数试过{}，也是一样的报错日志
2.设备对应的网关已经分享给你，网关的model是：lumi.gateway.iragl01

**Comment by zanetti4** [comment]
@blockdate 我对此问题进行了复现，按照 openDevice 的注释填入了正确的参数，但是未能跳转到相应插件，而是返回设备列表，没有返回错误信息。请你查看

**Comment by lvjie0519** [comment]
@wanggoingdown  问题已修复， 请使用最新apk进行测试，谢谢。
