### ISSUE TITLE
RN本地化里面，只有获取语言和时区，如何获取登录地区countryCode(国家码)？

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#675]
RN本地化里面，只有获取语言和时区，如何获取登录地区countryCode(国家码)？
let language = Host.locale.language
let timeZone = Host.locale.timeZone

**Comment by blockdate** [comment]
`Host.getCurrentCountry().then(...)`, 更新SDK以及APP 使用
