### ISSUE TITLE
CommonSetting 必选内容和《小米IoT产品开发书模版（非小米生态链公司版）》里面的必选项不一致

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#676]
[https://iot.mi.com/new/guide.html?file=03-平台使用指南/02-智能硬件直连接入/09-上线产品#/](url)

产品开发书  =>  非小米生态链公司产品请使用《小米IoT产品开发书模版（非小米生态链公司版）》 
**文档中规定：**
必选设置：
「设备名称」、「按键设置（仅开关品类产品需要）」、「位置管理」、「更多设置-安全设置」、「更多设置-常见问题」、「更多设置-反馈问题」、「更多设置-添加桌面快捷方式」、「法律信息-隐私政策」、「删除设备」。

这个和CommonSetting里面标注的必选项不一致，以哪一个为准？

**Comment by LiuMengzhou** [comment]
以sdk为准
