### ISSUE TITLE
安卓的JsExecutor这个模块在执行js函数时候如果传入的数据过大会执行失败

### ISSUE THREAD

**Issue by jianbin-rockrobo** [MiEcosystem/miot-plugin-sdk#678]

**Comment by jianbin-rockrobo** [comment]
JsExecutor这个模块在执行js函数时候如果传入的数据过大会执行失败

建议JsExecutor的原生实现使用v8引擎而不是RN的jscore

**Comment by lvjie0519** [comment]
@jianbin-rockrobo   我这边尽快安排处理，预计这周处理，请耐心等待。

**Comment by blockdate** [comment]
根据新回复，已处理，涉及到native更新，预计发布SDK Level为10020

**Comment by lvjie0519** [comment]
debug包已修复。
