### ISSUE TITLE
请问什么时候可以解决android 使用react-native-camera库的问题

### ISSUE THREAD

**Issue by prince-d-sky** [MiEcosystem/miot-plugin-sdk#680]
请问什么时候可以解决android 使用react-native-camera库的问题，谢谢！
主要是我们公司需要实现扫二维码的功能，现在ios已经实现了，android还没有完成native的修改，不能使用！

**Comment by lvjie0519** [comment]
@prince-d-sky  刚看了下，Android这边还没有集成react-native-camera库，预计五一后一星期内完成集成。

**Comment by lvjie0519** [comment]
@prince-d-sky  已集成，请下载最新apk进行测试，谢谢。
