### ISSUE TITLE
米家Beta-187版 CommonSetting页面

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#681]
开发者模式下commonsetting 点击“更多设置”不会报错，
白名单后点击“更多设置“会crash”

![IMG_0163](https://user-images.githubusercontent.com/8743690/56877559-7c491300-6a81-11e9-907b-1f31724403c5.PNG)

**Comment by LiuMengzhou** [comment]
正在解决

**Comment by CyrilChen** [comment]
用10004版本的sdk开发者模式下没有问题，上到白名单之后关闭开发者模式，点击更多设置会crash

**Comment by LiuMengzhou** [comment]
@CyrilChen 使用SDK_10005分支本地调试，以及后台打包再测试下吧
