### ISSUE TITLE
ios无法获取设备的WiFi信号强度，无数据

### ISSUE THREAD

**Issue by chenj1ahui** [MiEcosystem/miot-plugin-sdk#682]
before issue：（不用回答）
### 是否尝试搜索issue？

android可以正常获取设备的WIFi信号强度，ios获取无数据。
属性是：
<img width="368" alt="image" src="https://user-images.githubusercontent.com/33817754/56882669-db655280-6a96-11e9-92a5-0d91279903f4.png">

---

#### 公司名称

贵司的简称

#### 项目名称 / 项目ID

此 issue 关联的项目名称或项目ID，如您不清楚，请咨询贵司的项目经理。

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
处理中

**Comment by blockdate** [comment]
已处理，请更新最新测试app
