### ISSUE TITLE
CommonSetting页面，添加到桌面功能

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#683]
Android手机-三星note8 点击后回显示一个弹出框，和其他Android手机行为不一致。其他型号Android手机弹出提示toast ，note8弹框如下
![793DD059E51DFE27FD89492690972265](https://user-images.githubusercontent.com/8743690/56885440-081d6800-6a9f-11e9-863e-35d9a3f84670.jpg)

**Comment by lvjie0519** [comment]
@CyrilChen  三星note8，在米家APP  首页 设备列表，长按-->桌面快捷，会出现如上弹窗吗？

**Comment by CyrilChen** [comment]
@lvjie0519 三星note8 按照你的描述操作，显示如下
![3A67B62B0676286930F0529D2DA01ACC](https://user-images.githubusercontent.com/8743690/56939435-e1ad0a80-6b3a-11e9-87b8-0a03ec9fe9bd.jpg)

**Comment by lvjie0519** [comment]
经排查，这个是系统原因，不在解决范围，谢谢。
