### ISSUE TITLE
接口支持咨询

### ISSUE THREAD

**Issue by sofichael** [MiEcosystem/miot-plugin-sdk#684]
接口支持咨询

你好，新版的扩展rn插件，能支持打开外部第三方应用吗？或者是否支持打开网页，自行去引导下载。目前没在文档里面找到相应的描述。

**Comment by blockdate** [comment]
这个功能目前是不支持的。如果要使用网页，可以使用RN的的webview功能

**Comment by sofichael** [comment]
@blockdate 谢谢回答，webview里面嵌入的下载网页，滑动，点击下载都有问题。
