### ISSUE TITLE
使用Rkpicker显示问题

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#689]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 公司名称

贵司的简称 杭州羿秦科技

#### 项目名称 / 项目ID

此 issue 关联的项目名称或项目ID，如您不清楚，请咨询贵司的项目经理。

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac
- 手机系统:[eg.Android 8.1/iOS 11.0] 安卓9.0 ios 12
- SDK分支: [eg.master/10000/...] 10004
- 相关模块:[eg.Host/Service/Account] ui/rkpicker

#### 现象

简单明了地描述一下实际的现象。

使用Rkpicker在安卓上无法显示选中的值，iOS上可以正常显示 selectedOptions

#### 期望

简单明了地描述一下期望的表现。

希望Rkpicker能在安卓和ios正常显示选中状态

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by Aptx4869-xd** [comment]
这个是我传入了当前时间在安卓和ios上的效果，安卓上实际也是选中了的，就是没有自动滚动到选中的视图上


![WechatIMG8](https://user-images.githubusercontent.com/8141398/56941273-16728f00-6b46-11e9-8019-107948694699.png)
![WechatIMG9](https://user-images.githubusercontent.com/8141398/56941274-170b2580-6b46-11e9-98e7-e2ca14801cec.png)

**Comment by LiuMengzhou** [comment]
@Aptx4869-xd 
我们在将在下周导出一个时间选择组件（基于原生UI开发）

**Comment by Aptx4869-xd** [comment]
到时候我这是不是更新下sdk就可以用了? @LiuMengzhou

**Comment by LiuMengzhou** [comment]
> 到时候我这是不是更新下sdk就可以用了? @LiuMengzhou

是的
