### ISSUE TITLE
锁类产品，开锁异常

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#69]
![1543461890476](https://user-images.githubusercontent.com/12531667/49197322-744d5000-f3c9-11e8-8ccf-dbe24f2ab032.jpg)
米家beta和miot sdk都是最新的
iPhone 6

`
Device.bluetooth.securityLock.toggle(0).then(response=>{
            console.log('open result', response);
        }).catch(err=>{
            console.log('open err', err);
        });
`

**Comment by dingshaoran** [comment]
ios 上发现的？

**Comment by dzonel** [comment]
@dingshaoran 您好，iPhone 6，这个问题觉得和 issue #66 是相同性质的。
