### ISSUE TITLE
IOS米家测试APP无法连接到本地RN环境

### ISSUE THREAD

**Issue by reflectWay** [MiEcosystem/miot-plugin-sdk#690]
#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS 12.1-16B92]
- App版本: [4.16.1]

#### 现象

按照新扩展程序-开发简介-安卓插件调试步骤已调试成功
按照iOS插件调试步骤，无法连接到本地rn环境

#### 日志/截图
**1、下载的app源文件**
![ios1](https://user-images.githubusercontent.com/17630706/56943238-2643a080-6b51-11e9-88e8-00698dc7460a.png)

**2、登录的用户信息**
![ios2](https://user-images.githubusercontent.com/17630706/56943253-38254380-6b51-11e9-8821-cf913cc472be.png)
![49613C0BBC83C9C4420B92A96C373ABA](https://user-images.githubusercontent.com/17630706/56943257-3d828e00-6b51-11e9-92ab-fc6dee9762ea.png)

**3、设置的调试属性**
![B922B8E3E00757FC0AC5017C9C61A8F5](https://user-images.githubusercontent.com/17630706/56943275-58550280-6b51-11e9-8b4c-24fc91053927.png)

**4、蓝牙连接并打开插件页面**
![879FB0D3CC84A0811A3D1DC63959F2CD](https://user-images.githubusercontent.com/17630706/56943388-daddc200-6b51-11e9-8fb0-1fbe37b519a7.png)
![BCF43C4636B60D6AF6A6EC2D08ED0F19](https://user-images.githubusercontent.com/17630706/56943389-dca78580-6b51-11e9-8bdb-14c9a36b086f.png)

**5、执行Reload操作**
![36933EDC05B65374BED82BA3476B2EF7](https://user-images.githubusercontent.com/17630706/56943318-7fabcf80-6b51-11e9-8e4c-1d19f3c779f7.png)

**6、执行Debug JS Remotely**
![A99E2DCF29E45779394DDDF6FB587D59](https://user-images.githubusercontent.com/17630706/56943402-f8ab2700-6b51-11e9-9110-48da3849c7f3.png)

**7、控制台信息**
![QQ截图20190430141959](https://user-images.githubusercontent.com/17630706/56943656-1af17480-6b53-11e9-9e08-eda7f6d888fd.png)

**Comment by blockdate** [comment]
看错误提示，你似乎没有进入本地插件的调试环境，加载的疑似是线上插件包，因此reload会报错。

在打开插件前，是否有alert提示是本地调试插件，如果不是请检查下model的设置情况，如果提示了请及时反馈

**Comment by crane0** [comment]
> 看错误提示，你似乎没有进入本地插件的调试环境，加载的疑似是线上插件包，因此reload会报错。
> 
> 在打开插件前，是否有alert提示是本地调试插件，如果不是请检查下model的设置情况，如果提示了请及时反馈

看起来是的

**Comment by reflectWay** [comment]
> 看错误提示，你似乎没有进入本地插件的调试环境，加载的疑似是线上插件包，因此reload会报错。
> 
> 在打开插件前，是否有alert提示是本地调试插件，如果不是请检查下model的设置情况，如果提示了请及时反馈

@blockdate 打开插件前没有alert提示是本地调试；model、ip、包名确认已设置正确（安卓调试成功）

**Comment by blockdate** [comment]
没有提示表示输入有问题，检查下model是否输入了空格等字符。

**Comment by reflectWay** [comment]
> 没有提示表示输入有问题，检查下model是否输入了空格等字符。

@blockdate 空格检查了没有问题，还是不能连接上；我再找找其他版本iOS调试下，好了的话我再回复你

**Comment by zanetti4** [comment]
你好，这个问题解决了吗？ @reflectWay

**Comment by reflectWay** [comment]
> 你好，这个问题解决了吗？ @reflectWay

@zanetti4 那个iOS版本的米家不可以后来没试了，之后看到有更新新版本是可以的

**Comment by zanetti4** [comment]
新版本的米家 app 没问题的话，我就先关闭了。
