### ISSUE TITLE
通用设置中如何去除 「固件升级，「法律信息」

### ISSUE THREAD

**Issue by smalld2006** [MiEcosystem/miot-plugin-sdk#692]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 公司名称

贵司的简称

#### 项目名称 / 项目ID

此 issue 关联的项目名称或项目ID，如您不清楚，请咨询贵司的项目经理。

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

通用设置中如何去除 「固件升级」，「法律信息」
另外「更多设置」点击无效

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by LiuMengzhou** [comment]
`固件升級` 和 `法律信息` 根据产品要求必选。后续 `固件升级`改为可选。

`更多设置` 点击无反应，请详细阅读[CommonSetting参数说明](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/23-CommonSetting)

**Comment by smalld2006** [comment]
![image](https://user-images.githubusercontent.com/5235769/56947101-b63c1700-6b5e-11e9-8757-b22bcde26a91.png)
![image](https://user-images.githubusercontent.com/5235769/56947122-c05e1580-6b5e-11e9-821b-2098a23e37c0.png)
这中情况不是应该显示必选项吗，为什么点击没反应

**Comment by LiuMengzhou** [comment]
更多设置页面导出放在了rootStack里面了吗

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/56947521-09629980-6b60-11e9-9164-a59a3dcc5646.png)

**Comment by blockdate** [comment]
不活跃
