### ISSUE TITLE
Host.ui.openPrivacyLicense协议页面，安卓未显示自带文字内容

### ISSUE THREAD

**Issue by YunzzzZ** [MiEcosystem/miot-plugin-sdk#693]
Host.ui.openPrivacyLicense打开协议页面，iOS导航栏下方显示“某些功能仅限于部分国家和地区”，安卓未显示，插件本身不包含这段文字

**Comment by blockdate** [comment]
问题确认中

**Comment by YunzzzZ** [comment]
问题确认了吗

**Comment by YunzzzZ** [comment]
问题还存在

**Comment by zanetti4** [comment]
#1035

**Comment by lvjie0519** [comment]
@YunzzzZ   该模块正在优化，预计下周解决，谢谢。

**Comment by lvjie0519** [comment]
@YunzzzZ  经确认，已经去掉 导航栏下方显示“某些功能仅限于部分国家和地区”， 请用最新apk或IPA进行测试，谢谢，如有不一致问题，再reopen。
