### ISSUE TITLE
固件升级之后，重新连接startDiscoverServices会报service 4A6E4000-... is invalid

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#694]
步骤及现象如下：1、使用NordicDFU升级  2、升级成功后重连设备，调用 startDiscoverServices
此时会报service 4A6E4000-... is invalid，且升级成功时iOS上未收到bluetoothConnectionStatusChanged通知事件，安卓正常
![image](https://user-images.githubusercontent.com/15190511/56952673-6add3500-6b6d-11e9-9559-d4872e31546a.png)

**Comment by blockdate** [comment]
`service %@ is invalid` 这个错误信息表示当前使用的peripheral中找不到指定uuid的service。

**Comment by blockdate** [comment]
这边建议提供下更加完善的日志以及你的使用代码逻辑

**Comment by RideShi** [comment]
代码逻辑如下：
1、添加BluetoothEvent.bluetoothDeviceDiscovered以及升级成功的监听事件
2、升级成功时发送成功通知事件，执行断开蓝牙连接、扫描蓝牙设备事件
3、BluetoothEvent.bluetoothDeviceDiscovered监听到当前设备时，执行连接设备操作
相关部分代码如下
1、升级成功之后执行如下代码
<img width="517" alt="image" src="https://user-images.githubusercontent.com/15190511/57187904-9888fc00-6f28-11e9-9b8a-ee1c6a74b2f9.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/15190511/57187918-ce2de500-6f28-11e9-91bf-f4ce16e37cc2.png">
2、监听扫描部分代码如下
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/15190511/57187928-eef63a80-6f28-11e9-86a9-fc245ac363a5.png">
连接部分如下：
<img width="921" alt="image" src="https://user-images.githubusercontent.com/15190511/57187943-249b2380-6f29-11e9-99b0-960bde6f5671.png">

**Comment by RideShi** [comment]
已经知道什么原因了，iOS上dfu升级之前需要先手动断开蓝牙连接，这样dfu升级之后重新连接才能找到services
