### ISSUE TITLE
Android端 设备断电离线后 进入插件页面，此时供电 使设备在线后 ，插件页面卡死无法操作

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#695]
---

#### 公司名称

云米

#### 项目名称 / 项目ID

P18-0301

#### 环境
- 手机系统:[Android]
- SDK分支: [eg.master/10003.]
- 相关模块:设备离线在线逻辑

#### 现象

Android端 设备断电离线后 进入插件页面，此时供电 使设备在线后 ，插件页面卡死无法操作

#### 期望

Android端 设备断电离线后 进入插件页面，此时供电 使设备在线后 ，插件页面可以正常操作

**Comment by blockdate** [comment]
目前逻辑下，这个情况属于正常现象。

设备离线之后进入插件，插件页面是不可操作的，设备在线之后，目前没有在插件页刷新的逻辑
