### ISSUE TITLE
设备上报的数据能删除吗？

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#697]
#### 公司名称

德施曼

#### 项目名称 / 项目ID

com.dsm.q3

#### 现象

设备上报的数据现在可以查询，但无法删除

#### 期望

设备上报的数据支持删除

**Comment by blockdate** [comment]
目前设备上报数据不建议使用app端删除，在设备解绑或者删除后会清空数据。
如果的确有相关需求，请单独开启一个需求issue，描述你的使用场景和用途。
