### ISSUE TITLE
Service.smarthome.getUserPDData 接口返回404错误

### ISSUE THREAD

**Issue by aizuzi** [MiEcosystem/miot-plugin-sdk#698]
#### 公司名称

云麦科技

#### 项目名称 / 项目ID

云麦好轻mini2智能体脂秤

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象

使用Service.smarthome.getUserPDData 接口返回404错误
![image](https://user-images.githubusercontent.com/3455979/57187111-d718b980-6f1c-11e9-9a68-e8d4afb5c308.png)

返回：
{ code: 404, msg: '' }

#### 期望

可以正常调用

**Comment by blockdate** [comment]
仔细查看使用文档。
![image](https://user-images.githubusercontent.com/4339364/57187261-45aa4700-6f1e-11e9-8075-0682945ac9b0.png)

**Comment by aizuzi** [comment]
![image](https://user-images.githubusercontent.com/3455979/57187620-62e21400-6f24-11e9-903c-d7b45f740ab7.png)

我尝试过多种参数值，都是得到{ code: 404, msg: '' }，看起来这个错误和参数没有关系

**Comment by blockdate** [comment]
请确认已使用setUserPDData设置属性字段

**Comment by aizuzi** [comment]
![image](https://user-images.githubusercontent.com/3455979/57191277-38a94a00-6f56-11e9-9142-75bd877b6354.png)
调用setUserPDData也是报{ code: 404, msg: '' }错误
使用的米家APP版本是5.5.15测试版

**Comment by aizuzi** [comment]
我对比了一下旧版本，旧接口使用的是/user/getpdata，而新接口使用的是/app/user/getpdata？

**Comment by blockdate** [comment]
我这边查询相关接口文档得到的是/app/user/getpdata， 稍后我去掉/app，你这边再尝试一下

**Comment by aizuzi** [comment]
本地测试ok了，但是在打包上传米家后台进行白名单测试时，该接口无法使用了，选的API Level是10010

**Comment by aizuzi** [comment]
是否要等待你们后台更新，才能打包测试呢？

**Comment by aizuzi** [comment]
@blockdate

**Comment by blockdate** [comment]
SDK 依法不更新，手机端会静默更新，在打开几次插件后会正常。如果任然有问题再回复。

**Comment by aizuzi** [comment]
昨天就在后台打包了，进行白名单测试，现在多次打开还是出现{ code: 404, msg: '' }错误。
而在本地测试是没问题的
