### ISSUE TITLE
设备授权管理页面点击保存后不会退出到更多设置菜单页面

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#699]
#### 公司名称

万魔

#### 项目名称 / 项目ID

小米小爱音箱HD。

#### 环境
- 电脑操作系统:[Windows]
- 手机系统:[iOS 12.2]
- SDK分支: [10010]
- 相关模块:[Host/ui/openVoiceCtrlDeviceAuthPage]

#### 现象

在设备授权管理页面勾选授权设备后，点击页面右上角保存按钮，提示授权成功，但是不会退出授权页面，并返回到设置菜单页面。

#### 期望

保存后会自动退出授权页面，并返回到设置菜单页面。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/46127660/57187731-1ac3f100-6f26-11e9-9ce4-788d8af28102.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
这个在原生设计上就不会自动退出，这个暂时不处理。
