### ISSUE TITLE
未能完成的操作。（“load source error”错误 -2468）

### ISSUE THREAD

**Issue by hongshuangzhu** [MiEcosystem/miot-plugin-sdk#701]
before issue：（不用回答）
### IPA/APK 是否更新到最新？
ios 米家版本 4.15.101
### 是否尝试搜索issue？

---

#### 公司名称

小吉科技

#### 项目名称 / 项目ID

此 issue 关联的项目名称或项目ID，如您不清楚，请咨询贵司的项目经理。

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

#### 现象
测试期间出现
打未能完成的操作。（“load source error”错误 -2468）

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/18510541/57188544-397cb480-6f33-11e9-8375-dec1df36dbb6.png)
![image](https://user-images.githubusercontent.com/18510541/57188550-5618ec80-6f33-11e9-9481-9d4bc54e6c81.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by blockdate** [comment]
使用的是测试版还是线上版，如果是线上版，建议升级到4.15.102，如果是测试版提供下测试版icon编号

**Comment by hongshuangzhu** [comment]
是这个代码吗？
![image](https://user-images.githubusercontent.com/18510541/57189900-96ce3100-6f46-11e9-9804-33a2403844b4.png)

**Comment by blockdate** [comment]
这个建议更新下，最新的编号是200了。

**Comment by hongshuangzhu** [comment]
好的，我们这面再试一试

**Comment by blockdate** [comment]
有新进展再回复
