### ISSUE TITLE
用线上iOS米家，偶尔加载不出来插件

### ISSUE THREAD

**Issue by zaxayn** [MiEcosystem/miot-plugin-sdk#703]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 公司名称

隐秀

#### 项目名称 / 项目ID

inshow,watch.w1

#### 环境
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS
- SDK分支: [eg.master/10000/...]10005
- 相关模块:[eg.Host/Service/Account]

#### 现象

从首页点击进入插件偶尔加载不出来只显示一个转圈圈（差不多每3次中有1次)，给插件加了日志后发现，加载不出来的时候根本就没有进入插件

#### 期望

能稳定加载插件，另外请关注一下#665

**Comment by blockdate** [comment]
将设备分享到894158105下

**Comment by zaxayn** [comment]
> 将设备分享到894158105下

不好意思，我们的设备不能共享，共享按钮是灰色的😂

**Comment by zaxayn** [comment]
> 将设备分享到894158105下

还有没有其他方法？或者你们测试有没有米家手表可以试一下呢

**Comment by blockdate** [comment]
提供下你们设备的全称，我这边看有没有

**Comment by zaxayn** [comment]
> 提供下你们设备的全称，我这边看有没有

米家石英表

**Comment by blockdate** [comment]
该问题排查结果系 加载插件代码时发生了会导致native app crash 的异常， 因为catch了该异常，所以进入插件后会白屏。这边我们会优化该体验，让用户可以正常退出。

**Comment by zaxayn** [comment]
👌

**Comment by blockdate** [comment]
已处理，随5.8号版本更新

**Comment by zaxayn** [comment]
> 已处理，随5.8号版本更新

我们在5.8号版本测试中依然发现有这个问题，请问是不是还没有合并到线上版本？
