### ISSUE TITLE
Service.tjinfra.fetchAirRemoteInfrared android平台调用报错

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#706]
错误信息如下，请帮忙解决，谢谢

![3](https://user-images.githubusercontent.com/49702230/57203714-009d1800-6fe5-11e9-9ec8-2c1ea52e78d4.png)

**Comment by daoke666** [comment]
之前的传参是另外一个接口返回的result格式不对，要result.result。。。，改过来之后，返回为空。

fetchAirRemoteInfrared,result= {code: 0, result: Array(0)}」

fetchAirRemoteInfrared,remoteDict={"app_ver":"86","author_id":1,"brand":{"brand_cn":"格力","brand_en":"Gree","brand_tw":"格力","id":1103806845733,"pinyin":"geli","remarks":"air,fan"},"brand_id":1103806845733,"deleted":false,"diy_device":0,"down_count":0,"download_count":0,"id":"00002000d2a80019","keys":[{"id":1594506403840,"infrareds":[],"name":"","protocol":680,"remoteId":"00002000d2a80019","type":832},{"id":1594506403841,"infrareds":[],"name":"","protocol":680,"remoteId":"00002000d2a80019","type":811},{"id":1594506403842,"infrareds":[],"name":"","protocol":680,"remoteId":"00002000d2a80019","type":800},{"id":1594506403843,"infrareds":[],"name":"","protocol":680,"remoteId":"00002000d2a80019","type":812}],"lang":0,"layout_id":20,"model":"YBOF2","modifier_id":0,"type":2,"up_count":0},keyDict={"id":1594506403841,"infrareds":[],"name":"","protocol":680,"remoteId":"00002000d2a80019","type":811},stateDict={"anion":"ANION_OFF","caculate_number":0,"comfort":"COMFORT_OFF","current_key":0,"flash_air":"FLASH_OFF","hot":"AIDHOT_OFF","last_key":0,"light":"LIGHT_ON","mode":"AUTO","mute":"MUTE_OFF","power":"POWER_OFF","power_saving":"POWER_SAVING_OFF","protocol":0,"remote_id":"00002000d2a80019","sleep":"SLEEP_OFF","super_mode":"SUPER_OFF","temp":"T26","temp_display":"DISPLAY_NONE","time_limit":0,"wet":"WET_OFF","wind_amount":"AUTO","wind_direction":"AUTO","wind_hoz":"HOZ_OFF","wind_ver":"VER_OFF"}

**Comment by daoke666** [comment]
调用的参数如下打印

**Comment by lvjie0519** [comment]
问题已解决。
