### ISSUE TITLE
蓝牙门锁：订阅通过网关上报的数据的变化

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#707]
#### 问题

订阅 门锁通过网关上报的属性变化和事件响应

DeviceEvent.deviceReceivedMessages.addListener ,这个接口能支持 user_device_data 的数据的监听吗

#### 期望

蓝牙门锁设备通过网关上报 电量 、锁状态、门状态等数据（user_device_data），希望能有一个订阅这类网络数据的变化，从而更快的刷新UI 。 

现在用的10秒轮询的方法，体验不够好。

**Comment by blockdate** [comment]
这个是可以的，建议尝试使用后有问题在开启issue处理
