### ISSUE TITLE
Android插件接收到通知后退出当前插件，回到米家首页

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#708]
系统：Android 系统
米家插件版本：5.5.15测试版
SDK 分支： 10005
描述：Android端收到智能通知后通知栏里会受到通知，但是
不会显示提示框，并且会跳出当前插件，回到米家主页。iOS端正常显示通知和提示框。
分析：可能的原因是 提示框调用的是iOS原生提示框，Android没做相应处理，导致crash到米家首页

![IMG_0167](https://user-images.githubusercontent.com/8743690/57214390-71135b80-701c-11e9-8f39-28b6a91524a7.PNG)
![BE34DD392BCA91AB778E0624BADC90A6](https://user-images.githubusercontent.com/8743690/57214447-93a57480-701c-11e9-958f-1253e3291ede.png)

**Comment by lvjie0519** [comment]
@CyrilChen  请告知下具体使用的是哪个api？

**Comment by CyrilChen** [comment]
@lvjie0519 当前插件里面没有做任何操作，只是进入到插件内，然后去开启其他别的设备，当收到通知后，Android端的插件会调回米家主页，iOS端则弹出弹框（如图所示）

**Comment by lvjie0519** [comment]
@CyrilChen    已修复，请使用最新apk进行测试，谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，如有问题，再reopen，谢谢。
