### ISSUE TITLE
关于米家app检查固件更新的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#710]
你好，
      我这边发现一个问题，我在发布了一个插件的新版本后，在安卓上点击检查更新，会发现新版本，但是在ios上，不会发现新版本，需要清除缓存，重新拉取最新插件，才能获取最新版本，请问这个问题该怎么解决？
      谢谢！

**Comment by blockdate** [comment]
iOS下不会主动检查插件更新，需要用户手动打开插件之后才会检查更新，在开关几次插件之后，插件会自动更新到最新版本。
