### ISSUE TITLE
需要添加一个新的接口，替代旧版插件MHDeviceList.requestAuthorizedDeviceListData

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#711]
**公司名称（必填）**
秒秒测科技
**项目名称（必填）**
米家温湿监测电子表

**环境（必填）**
- 电脑操作系统Mac OS
- 手机系统:iOS 12.2
- SDK分支:master/10000/
- 相关模块:未知

**现象（必填）**
缺少一个接口

**期望（必填）**
提供一个接口，替代旧版插件MHDeviceList.requestAuthorizedDeviceListData
返回账号内，可以进行蓝牙互联的设备列表，设备信息，pid，mac等信息

**Comment by blockdate** [comment]
检查下Device.requestAuthorizedDeviceListData 接口是否满足

**Comment by Android-yzhang** [comment]
好像不对，现在输入一个model，返回的是这个model的图片？
我需要的是返回账号内，其他的可以进行蓝牙互联功能的设备列表
类似这样：
0:
deviceListOpen: false
devices: [{…}]
model: "miaomiaoce.thermo.t01"
product_icon: "http://cdn.fds.api.xiaomi.com/miio.files/commonfile_png_d64885b920962f6cf023a3a3f02f5999.png"
product_name: "秒秒测智能体温计"
__proto__: Object
1:
deviceListOpen: false
devices: [{…}]
model: "miaomiaoce.thermo.t10"
product_icon: "http://static.home.mi.com/app/image/get/file/developer_1552468453ycjahmu2.png"
product_name: "米家电子体温计"

**Comment by blockdate** [comment]
该方法返回的就是你要求的格式，检查下代码使用或者将你自己的代码与日志贴上来

**Comment by Android-yzhang** [comment]
接口调用和格式都没问题了，就是还是没有pid，旧版也没有，也需要添加。

**Comment by Android-yzhang** [comment]
已验证，OK，谢谢
