### ISSUE TITLE
能否提供插件sdk接口返回的错误码对照表

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#713]
**公司名称（必填）**
德施曼

**项目名称（必填）**
com.dsm.q3

**现象（必填）**
接口报错的时候，返回的信息里有code和msg的信息，目前插件直接用了msg的信息输出给用户，但是有些msg的信息对用户来说并不友好

**期望（必填）**
如题，希望能提供一份错误码对照表，以方便插件统一处理异常情况下的报错信息

**Comment by blockdate** [comment]
建议提供下需要完善的接口名称

**Comment by dessmann** [comment]
跟单个接口没有关系，只是需要一份错误码映射表，0x01表示网络异常，0x02表示服务器响应失败这种，错误码表示的书面用语我们需要自己定义

**Comment by blockdate** [comment]
https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/26-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#/%E5%90%8E%E5%8F%B0API%E8%BF%94%E5%9B%9E%E7%9A%84%E9%94%99%E8%AF%AF%E7%A0%81
