### ISSUE TITLE
Android卡片功能正常，iOS模式选择类卡片，状态不能更改

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#715]
---
**公司名称（必填）**
邦先生

**项目名称（必填）**
晾衣机

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac
- 手机系统:[eg.Android 8.1/iOS 11.0]
iOS
[mijia_card_config.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3150431/mijia_card_config.txt)

**现象（必填）**
iOS模式选择类卡片，状态不能更改

**期望（必填）**
模式选择类卡片，状态能够随着属性值的变化更改。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
卡片问题不属于插件开发范畴，建议找相关产品推动app的同学查找问题
