### ISSUE TITLE
锁类产品开锁，报try to toggleLockXiaoMiBLE:(null), but no bluetooth holder was founded, please connect first，holder:(null),peripheral:(null)

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#716]
- IPA/APK 是否更新到最新？是
- SDK 是否更新到最新？是 10010
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
上海榉树智能科技有限公司

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否"
否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
shjszn.lock.c1

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- SDK分支: [eg.master/10000/...] 10010
- 相关模块:[eg.Host/Service/Account]Device

**现象（必填）**
简单明了地描述一下实际的现象。
<img width="870" alt="image" src="https://user-images.githubusercontent.com/12531667/57269717-111fc200-70bb-11e9-9b75-a5410880766c.png">
连接成功后开锁，会报如图所示问题。

<img width="846" alt="image" src="https://user-images.githubusercontent.com/12531667/57269757-3ca2ac80-70bb-11e9-9d20-ba04021b95a1.png">
查找services时会有如图所示警告

**期望（必填）**
简单明了地描述一下期望的表现。

期望可以像之前一样正常使用

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
1. 检查下SDK是否正确更新到最新。
2. 看日志输出中的uuid 皆为null， 这边提供下你的toggle以及sidcoverServices的js代码

**Comment by blockdate** [comment]
正确使用最新的sdk， 所有传递到native 的uuid 都应该是 mac地址，看这种情况极大可能性是SDK尚未更新到最新

**Comment by ldezho** [comment]
切换分支切出问题了
@blockdate 多谢。
