### ISSUE TITLE
title组件的设备名称过长时会换行

### ISSUE THREAD

**Issue by marsWu1989** [MiEcosystem/miot-plugin-sdk#717]
**公司名称（必填）**
青萍科技

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米米家空气检测仪/cgllc.airmonitor.b1

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 9
- SDK分支: 10010
- 相关模块: miot/ui/TitleBarBlack, miot/ui/TitleBarWhite

**现象（必填）**
当设备名称过长时title当文字会换行

***其他的上下文/日志/截图**
![70141557200025_pic](https://user-images.githubusercontent.com/22907551/57270828-7f668380-70bf-11e9-9bb0-5634b70e27b0.jpg)
**期望（必填）**
一行内显示，多余内容省略号代替

**Comment by lvjie0519** [comment]
@LiuMengzhou  帮忙看看这个问题，thanks。

**Comment by LiuMengzhou** [comment]
#623 
https://github.com/MiEcosystem/miot-plugin-sdk/issues/614#issuecomment-491720599

**Comment by LiuMengzhou** [comment]
SDK_10011
722f335
[com.xiaomi.demo-「首页」-「教程」-「导航栏 TitleBar Demo」](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10011/projects/com.xiaomi.demo/Main/tutorial/TitleBarDemo.js)

**Comment by marsWu1989** [comment]
另外，发现安卓主界面卡片有类似的问题
问题：安卓截掉了最前面的“小米”两个字
ios：
![image](https://user-images.githubusercontent.com/22907551/57826991-2b9f1d00-77d8-11e9-8a73-6df7e2086e66.png)

安卓：
![image](https://user-images.githubusercontent.com/22907551/57826936-f8f52480-77d7-11e9-9b42-6621f4c4539f.png)
期望：和ios表现一致

**Comment by LiuMengzhou** [comment]
@lvjie0519 @blockdate 宫格显示的问题是不是要找APP开发

**Comment by blockdate** [comment]
卡片问题Android下会截断小米开头是已知设计，因为屏幕适配问题，很多设备默认是带小米前缀的，所以Android下回默认去掉。
