### ISSUE TITLE
旧接口delDeviceSetting更改为新接口batchSetDeviceDatas的疑问

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#718]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
"小米米家智能门锁/lumi.lock.mcn01"

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1/iOS 11.0]
SDK分支: master
- 相关模块:Service/smarthome

**现象（必填）**

删除设备属性时，新接口参数如何填写？还是有新接口？

**期望（必填）**

接口正常使用。

**其他的上下文/日志/截图**

### **删除设备属性时，原来老接口使用delDeviceSetting**

![image](https://user-images.githubusercontent.com/46777658/57271192-1b44bf00-70c1-11e9-8f8a-dfec1fa35ba2.png)

### **还有个疑问，比如属性是"push_device",那参数是“prop.spush_device”,还是“porp.s_push_device”?(前缀是“prop.s”还是“prop.s_”)**

![image](https://user-images.githubusercontent.com/46777658/57271332-af168b00-70c1-11e9-80b0-000a73757f4a.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
这里解释下，两个接口功能相近，但是数据并不同步，如果可以建议使用batchxxx的方法，数据需要自行写一个过渡的方式进行转移。

考虑到有些同学依赖旧接口的时间字段，这个接口不会被删除，可以正常使用，属于不建议使用，这个文档之后会更新。

**Comment by WeizhiKong** [comment]
还有个疑问，比如属性是"push_device",那参数是“prop.spush_device”,还是“porp.s_push_device”?(前缀是“prop.s”还是“prop.s_”)
