### ISSUE TITLE
各种 Dialog 的各种问题

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#719]
**公司名称（必填）**
ClearGrass

**是否为新产品（必填）**
否

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: 【10010】
- 相关模块:[Host.ui]

**现象（必填）**
1. iOS 上无法显示出 MessageDialog 代码：【严重】
![image](https://user-images.githubusercontent.com/4001793/57272958-8f369580-70c8-11e9-9e3e-3904111b22b4.png)

2. Android 显示 MessageDialog 时，
如果没有按钮，message 太靠下了，希望优化一下。图：
![image](https://user-images.githubusercontent.com/4001793/57272965-9fe70b80-70c8-11e9-9af4-ae83dbfd503d.png)

3. MessageDialog 仅有 MESSAGE 或 仅有 Title 的情况下，也有点丑，希望优化一下。如上图。

4. timeout 参数有点奇怪：代码：
```
<LoadingDialog
            message={strings.alert_near}
            confirm="OK"
            onDismiss={() => {
              console.warn("onDismiss");
              this.setState({
                alert_ble: false
              })
            }}
            visible={this.state.alert_ble}
            cancelable={true}
            timeout={6}
          />
```
通过 alert_ble 控制 Dialog 显示，
timeout 似乎是界面 DOM 加载后的6秒。
如果是在界面加载6秒内显示（如：过了4秒才set alert_ble=true），会在2秒后 dismiss
之后如果是在界面加载6秒后显示（过了6秒才set alert_ble=true），会立即 dismiss，无法显示出来。

5. 显示各种 Dialog 后，插件退出（可能是意外退出），Dialog 依然显示，且无法关闭。应该关闭。
![image](https://user-images.githubusercontent.com/4001793/57273296-cbb6c100-70c9-11e9-9f87-a8b5f96c0adc.png)

Android 设置 `cancelable={true}` 可以在区域外点击闭关，但不设置也会无法关闭。iOS 无法设置`cancelable` 

**期望（必填）**
如上

**Comment by LiuMengzhou** [comment]
原生组件改动较麻烦，纯JS版正在开发中。推荐：

1. 等不及，自己实现
2. 等（大约本月输出）
