### ISSUE TITLE
bluetooth.getService('...').getCharacteristic('...').write(value, ok=>{})， write方法中参数value, 对value格式有什么要求吗？

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#72]

**Comment by laohuang88** [comment]
没有限定

**Comment by JxXiaoXie** [comment]
IOS:
[_peripheral writeValue:data forCharacteristic:writeCharacteristic
                                  type:CBCharacteristicWriteWithResponse];
你们拼装data的时候是用的NSData的哪个方法？ 是initWithBase64EncodedString还是dataWithBytes还是其它方法？

**Comment by JxXiaoXie** [comment]
好了
