### ISSUE TITLE
Service.smarthome.getUserInfo 接口安卓上无法获取uid

### ISSUE THREAD

**Issue by RideShi** [MiEcosystem/miot-plugin-sdk#721]
创米
**是否为新产品（必填）**
否
**产品名称/Model（必填）**
chuangmi.lock.hmi501
**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1
- SDK分支:10005
- 相关模块:[eg.Host/Service/smarthome]

**现象（必填）**
安卓上无法获取到用户的uid

**期望（必填）**
安卓上正常获取到用户的uid

![image](https://user-images.githubusercontent.com/15190511/57289824-b30cd200-70ee-11e9-816a-7b58f79a0720.png)

**Comment by lvjie0519** [comment]
@RideShi    已修复，请更新sdk到10011分支，谢谢。

**Comment by blockdate** [comment]
10005 与 10010 已发布修复版本，如果对uid强依赖，建议使用10011分支
