### ISSUE TITLE
关于scrollView在安卓上的效果不理想的情况

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#722]
你好，
       我的希望的主界面是这样的，在加载后，自动滚动到今天，然后最上面一行的“今天”的字符大小会变大，颜色也会改变，在ios上没有问题，但是在安卓上，加载完后不会自动变大，在手动滚动一下后变大，不知道是什么原因，能否帮忙看看，谢谢。
       这是刚加载完界面的时候，字体大小不变，
![image](https://user-images.githubusercontent.com/18459414/57293370-1bf84800-70f7-11e9-9cf7-d4cf40223538.png)
       然后手滑动后，字体大小会变
![image](https://user-images.githubusercontent.com/18459414/57293414-464a0580-70f7-11e9-8e74-73c2877214c4.png)
![image](https://user-images.githubusercontent.com/18459414/57293422-4944f600-70f7-11e9-904d-577e5939b4a0.png)

这是部分相关代码

![Snip20190507_5](https://user-images.githubusercontent.com/18459414/57293462-65e12e00-70f7-11e9-94dd-128770e0e7e1.png)
![Snip20190507_6](https://user-images.githubusercontent.com/18459414/57293635-de47ef00-70f7-11e9-8f38-3e1db3213e78.png)

**Comment by caojunhua** [comment]
有没有人帮忙看看

**Comment by fishle** [comment]
你好，这边看到加载完之后  "今天" 的样式是正常的（放大+紫色），麻烦下载最新的米家APP再看一下

**Comment by caojunhua** [comment]
> 你好，这边看到加载完之后 "今天" 的样式是正常的（放大+紫色），麻烦下载最新的米家APP再看一下

你好，这个问题已修复，谢谢

**Comment by fishle** [comment]
> > 你好，这边看到加载完之后 "今天" 的样式是正常的（放大+紫色），麻烦下载最新的米家APP再看一下
> 
> 你好，这个问题已修复，谢谢

那麻烦把issue状态改为关闭，谢谢~
