### ISSUE TITLE
绑定设备时，报错：初始化失败

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#723]
**公司名称（必填）**
舒可士（深圳）科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家声波电动牙刷 插件   （soocare.toothbrush.m1）

**环境（必填）**
- 手机系统:Android 9/iOS 12.2
- SDK分支: 10003
- 相关模块:绑定设备

**现象（必填）**
1、使用Android手机进入插件，选择欧洲国家进行绑定牙刷时，无法成功绑定，报错：“扩展程序初始化失败”
2、使用IOS手机进入插件，选择任意海外国家进行绑定牙刷时，无法成功绑定，报错：“初始化失败（3）”

**期望（必填）**
希望可以成功绑定设备。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/48087638/57294076-14d23980-70f9-11e9-8ea5-289bd5b2877f.png)
![image](https://user-images.githubusercontent.com/48087638/57293993-db99c980-70f8-11e9-91f5-da217e633094.png)

**尝试过的解决办法**
1、更换设备进行绑定
2、更换账号进行绑定

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
海外插件同步昨晚才完成问题修复，已验证正常，建议重新上传插件后等待更新。
