### ISSUE TITLE
Service.smarthome.callThirdPartyAPI 接口报-8错误

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#724]
---
**公司名称（必填）**
舒可士（深圳）科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
素士声波电动牙刷/soocare.toothbrush.x3

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS
- SDK分支: 10010
- 相关模块:Service

**现象（必填）**
Service.smarthome.callThirdPartyAPI 接口报-8错误码
android 和 ios测试，都报这个错

参数格式如下：
<img width="792" alt="image" src="https://user-images.githubusercontent.com/7885251/57296191-f707d300-70fe-11e9-8634-3463a55aaadf.png">

KAppId： 10030

**期望（必填）**
接口返回正常数据

**Comment by blockdate** [comment]
该错误系参数错误，建议将参数详细发一下，我们这边排查一下问题。

**Comment by JxXiaoXie** [comment]
详细参数：let param = {"app_id":"10030","dids":["blt.3.sejqgcdg4o00"],"params":{"api_type":"deviceBind","method":"get","data":null}};

**Comment by JxXiaoXie** [comment]
@blockdate 你好，请问进度怎么样了？

再提供个信息，我插件JS日志有这个打印：
<img width="966" alt="image" src="https://user-images.githubusercontent.com/7885251/57501795-7ffb5600-731b-11e9-8cf9-ea66fa65d324.png">

**Comment by zanetti4** [comment]
请把 素士声波电动牙刷/soocare.toothbrush.x3 分享给我，我的帐号：894158105，我进行调试。

**Comment by JxXiaoXie** [comment]
你好，我们设备是在线进入的，我分享给你你也进不去插件吧？

**Comment by zanetti4** [comment]
我直接用你写的参数调试，提示没有权限，设备未绑定。你直接分享给我就好了

**Comment by JxXiaoXie** [comment]
已共享

**Comment by zanetti4** [comment]
@blockdate 我在安卓系统进行了测试，smarthome.js
`
callThirdPartyAPI(params) {
        //@native :=> promise
        //这个接口在iOS原生下处于无人维护了，直接切换到纯JS使用
        return new Promise((resolve, reject) => {
            native.MIOTRPC.nativeCall("/third/api", params, (ok, res) => {
                if (!ok) {
                    return reject(res);
                }
                // 和 ios统一
                if (res.code !== undefined && res.code === 0 && res.result !== undefined) {
                    let result = res.result;

                    if (result.interval !== undefined && result.interval > 0) {
                        console.log(result);
                        this.callThirdApiResult({ "sid": result.sid, "retry_time": result.retry_time }, 1, 1, result.max_retry).then(r => {
                            resolve(r);
                        }).catch(e => {
                            reject(e);
                        });
                    } else {
                        resolve(result);
                    }
                } else {
                    reject(res);
                }
            });
        });
        //@native end
    }
`
result.retry_time 是 undefined，所以才报-8的错误，请你协助查看。

**Comment by blockdate** [comment]
该情况已处理，修复SDK为 10011 及以上

**Comment by JxXiaoXie** [comment]
测试了下，是解决了。
