### ISSUE TITLE
封样要填的版本，是这俩个哪个啊，是105还是1.0.0

### ISSUE THREAD

**Issue by liuhaixu666** [MiEcosystem/miot-plugin-sdk#725]
<img width="1894" alt="0B2A73ED-91F2-49D8-8850-0A28364DB290" src="https://user-images.githubusercontent.com/38349220/57344402-b1d4b700-7179-11e9-908d-5804d2eee790.png">

**Comment by blockdate** [comment]
以平台上的版本为主
