### ISSUE TITLE
使用miot新协议如何监听设备端的事件推送数据（Android&IOS）

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#726]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
扫拖一体机/dreame.vacuum.mc1808

**现象（必填）**
设备端通过spec协议发送一个事件，APP上如何监听事件内容
设备端发送协议
```
{"id":1100661313,"method":"event_occured","params":{"did":"11674181","siid":22,"eiid":8}}
```

**期望（必填）**
APP上能正常订阅到该数据

**尝试过的解决办法**
尝试通过订阅属性的方式订阅 event_occured或者event.22.8,但是均无法收到数据，也未找到相关文档

**Comment by heigaga001** [comment]
再咨询一个事件相关的问题，插件如何通过https://api.io.mi.com/app/v2/user/get_device_data_raw接口获取SDS中的历史事件

**Comment by blockdate** [comment]
1. 订阅问题这边写法没问题，确认下是否是设备的事件上报失败了。
2. 这个接口目前没有提供，建议新建一个需求issue，我们进行更新

**Comment by heigaga001** [comment]
@blockdate 订阅事件就是通过event.siid.eiid吗？

**Comment by blockdate** [comment]
对的

**Comment by heigaga001** [comment]
发现是由于设备端未写argument参数导致的
