### ISSUE TITLE
NumberSpinner 在安卓上下滑动 不流畅

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#728]
- IPA/APK 是否更新到最新？
 最新
- SDK 是否更新到最新？
是
- Check 文档了吗？
是的
- 是否尝试搜索issue？
搜索过

---
**公司名称（必填）**
云丁&鹿克

**是否为新产品（必填）**
是
**产品名称/Model（必填）**
loock.lock.v5
**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
   安卓手机使用起来 上下滑动特别不流畅  大部分机型是这样
**期望（必填）**
改进一下使用体验
**其他的上下文/日志/截图**
  
![E6631FD928FE7945DC144CCB818718CA](https://user-images.githubusercontent.com/13412744/57348672-91acf400-7189-11e9-8097-9c5dda53cf46.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@zhaolios  我这边无法复现，请检查是否事件冲突或具体实现请参考xiaomi.demo 中 NumberSpinnerDemo，谢谢。
