### ISSUE TITLE
Card 组件默认显示建议

### ISSUE THREAD

**Issue by qinliduan** [MiEcosystem/miot-plugin-sdk#729]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米家智能多模网关/lumi.gateway.mgl04

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10010/...]
- 相关模块:[eg.Host/ui/Card]

**现象（必填）**
1、Card默认可配置选项较少，如阴影颜色、右侧图标、主副标题等
2、现在的点击高亮颜色好深，视觉效果不好

**期望（必填）**
Card默认可配置选项支持如阴影颜色、右侧图标、主副标题等

**其他的上下文/日志/截图**
![卡片1](https://user-images.githubusercontent.com/41932871/57349176-bace8400-718b-11e9-907d-32bbb2571547.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
@qinliduan 
可以选择不使用默认的内部视图（左图标右文字的样式）
[通过`props.innerView`传入自定义的内部视图。](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10010/miot-sdk/ui/Card/Card.js#L20)


> 现在的点击高亮颜色好深，视觉效果不好

这个我之后改成可传参数配置的吧

**Comment by qinliduan** [comment]
> @qinliduan
> 可以选择不使用默认的内部视图（左图标右文字的样式）
> [通过`props.innerView`传入自定义的内部视图。](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10010/miot-sdk/ui/Card/Card.js#L20)
> 
> > 现在的点击高亮颜色好深，视觉效果不好
> 
> 这个我之后改成可传参数配置的吧

谢谢，我这边有个项目很需要那个阴影颜色可配置，望支持一下；
这个innerView有在使用，只是感觉首页这种类型的卡片比较通用，感觉可以考虑做成配置项直接使用，您这边确定不做的话，我可以自己封装，问题不大，望支持一下阴影颜色配置

**Comment by qinliduan** [comment]
Card组件cardStyle配置marginTop或marginLeft等在安卓上会报错：Error: You attempted to set the key `marginTop` with the value `10` on an object that is meant to be immutable and has been frozen.

demo中CardPage.js
`<Card
              text={this.state.text}
              onPress={_ => this.toggle()}
              cardStyle={{ marginTop: 10, width: 100, height: 66, backgroundColor: Styles.common.MHGreen, borderRadius: 15 }}
            />`

**Comment by LiuMengzhou** [comment]
@qinliduan 
75026c4dd8f2a88caf282902ad2ae737bb47f1c0
