### ISSUE TITLE
进入插件还是会弹出旧版本的插件

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#730]
您好，
       前几天我提到过一个问题，进入插件的时候，会进入旧版本的插件，当时您们这边回复说是服务器的问题。
       但是现在还是会出现这个问题。不知道什么情况呢？
       谢谢！

**Comment by blockdate** [comment]
分享设备至894158105，并在这里说明设备名称

**Comment by caojunhua** [comment]
设备名称是freetie智能鞋垫

**Comment by caojunhua** [comment]
![image](https://user-images.githubusercontent.com/18459414/57354515-36d1c780-719e-11e9-8073-bf3fb4ad1914.png)

**Comment by blockdate** [comment]
这边多次测试，打开的插件 更新日志是 "测试23"， 不知是否正确

**Comment by caojunhua** [comment]
正确，我们内部测试是偶尔出现旧版本，也不是每次都出现。

**Comment by blockdate** [comment]
这个大概率是因为服务器白名单状态波动造成的。正式上线后应该不会出现了
