### ISSUE TITLE
设备离线后app上无法监听到离线通知

### ISSUE THREAD

**Issue by Aptx4869-xd** [MiEcosystem/miot-plugin-sdk#731]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。预期48h内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。预期1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。预期1周-1月内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
贵司的简称

杭州羿秦科技

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否"

是

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)

hzyqkj.aircondition.kl

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] mac os
- 手机系统:[eg.Android 8.1/iOS 11.0] android 9.0
- SDK分支: [eg.master/10000/...] 10004
- 相关模块:[eg.Host/Service/Account]

DeviceEvent

**现象（必填）**
简单明了地描述一下实际的现象。

添加deviceStatusChanged监听后，把模块断电进入离线状态，然后app上的deviceStatusChanged方法未进入回调

**期望（必填）**
简单明了地描述一下期望的表现。

希望能监听到离线的动作

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

![1557292724182](https://user-images.githubusercontent.com/8141398/57351271-d5a4f680-7193-11e9-83cf-b9e3783a8c5a.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@Aptx4869-xd    问题还存在吗？  ios是否有相同问题？

**Comment by Aptx4869-xd** [comment]
@lvjie0519 这个问题还是有的，之前好像说是离线后是没有提供什么方法监听的

**Comment by lvjie0519** [comment]
@Aptx4869-xd   据服务端反馈，  设备订阅了event.dev_offline  事件， 是会收到消息的， 你有订阅该事件吗？

**Comment by Aptx4869-xd** [comment]
@lvjie0519 好的，我一会订阅下这个事件看看，目前文档里没有有关离线监听的内容的

**Comment by fishle** [comment]
监听deviceRecievedMessages这个事件试试

**Comment by Aptx4869-xd** [comment]
@lvjie0519 @fishle 你好，我的sdk是10010的版本，请问这个版本是不是也可以测上面说的订阅事件的？还是我要下载最新的sdk测？

**Comment by fishle** [comment]
应该不用升级，可以先试试

**Comment by Aptx4869-xd** [comment]
![1564043948590](https://user-images.githubusercontent.com/8141398/61859475-c4e66000-aefa-11e9-8604-828f4099684c.jpg)
@lvjie0519 @fishle 你好，我加了这个监听后设备离线了也还是没有进来这个回调

**Comment by fishle** [comment]
设备离线后，你能收消息吗，试试把所有收到的message都打印出来

**Comment by Aptx4869-xd** [comment]
![1564044574418](https://user-images.githubusercontent.com/8141398/61860241-370b7480-aefc-11e9-9905-0681e62c062f.jpg)
[设备状态监听日志.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3430597/default.txt)
@fishle 你好，我有添加订阅，附件是设备状态监听的日志,设备离线后是一直没有进回调的

**Comment by lvjie0519** [comment]
@Aptx4869-xd 
1、验证下ios是否有问题？
2、通过 miot-rn-plugin或PushManager 过滤下log日志， 可以看到 原生层是否接收到push消息及向js发送了数据；

**Comment by Aptx4869-xd** [comment]
额，刚刚的这个就是ios上测的 @lvjie0519

**Comment by Aptx4869-xd** [comment]
[安卓设备状态日志.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3430811/default.txt)
@fishle 你好，我试了安卓的也是一样的情况，附件为安卓的日志

**Comment by Aptx4869-xd** [comment]
![1564047927754](https://user-images.githubusercontent.com/8141398/61864467-0f200f00-af04-11e9-8b18-a6c150548bd8.jpg)
你好，安卓这边目前测了5次，有两次能收到离线的状态，但是内容是空的，还有这两次都是大约等了3分钟以上收到消息

**Comment by fishle** [comment]
wifi设备离线状态的判断不是说一掉线就立即判断为离线的，每次测试都等3-4分钟试试，能收到说明这里逻辑是OK的

**Comment by Aptx4869-xd** [comment]
@fishle 嗯，不过ios确实是收不到，我每次都是等了3分钟以上的

**Comment by santcool** [comment]
@Aptx4869-xd iOS需要升级SDK，请升级到最新SDK后再试试。另外，注意订阅的写法，一定要采用文档的写法。

**Comment by Aptx4869-xd** [comment]
@santcool 请问是10023这个版本吗？我看主分支上是10023的版本，然后还有个分支写着10024的

**Comment by santcool** [comment]
升级到SDK_10023，10024还没发布

**Comment by santcool** [comment]
这个位子还有问题吗？
