### ISSUE TITLE
使用miot新协议如何通过sds接口获取历史记录

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#732]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
扫拖一体机/dreame.vacuum.mc1808

**现象（必填）**
https://iot.mi.com/new/guide.html?file=08-%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/03-%E5%AD%98%E5%82%A8/02-%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8-SDS
该文档只列出了老的协议获取历史事件的传参，新的spec协议如何获取

**期望（必填）**
可以获取设备上报的历史事件

**Comment by heigaga001** [comment]
@blockdate 有没有接口支持获取事件中某个属性的累加值

**Comment by santcool** [comment]
如果是直接按spec上报的， 如果是上报的prop.[sid].[pid] 查询的type: prop, key: [sid].[pid]。其他参数含义不变

你说的某个属性的累加值，是什么意思？

**Comment by heigaga001** [comment]
@santcool  事件上报时的
```json
{
	"id" : 123,
	"method" : "event_occured",
	"params" : {
		"did" : "1234",
		"siid" : 2,
		"eiid" : 1，
		"arguments" : [
			{
				"piid" : 1,
				"value" : 17
			},
			{
				"piid" : 2,
				"value" : 3
			}
		]

	}
}
```
arguments 中的value值有没有求和的接口

**Comment by blockdate** [comment]
这个目前没有累加的接口

**Comment by heigaga001** [comment]
@blockdate @santcool 
```
     Service.smarthome.getDeviceData({
            did:did,
            uid:Service.account.ID,
            key:"event",
            type:"22.1",
            time_start:0,
            time_end:Math.floor(Date.now()/1000),
            limit:20
        }).then(res=>{
            console.log("getDeviceData",res)
        }).catch(err=>{
            console.log("getDeviceData err ",err)
        })
```
每次获取的数据都是空数组，主机通过事件上报的数据，APP通过event.22.1可以订阅到数据
