### ISSUE TITLE
Nordic升级接口存在兼容性问题

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#733]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼Q3智能锁/dsm.lock.q3

**环境（必填）**
- 电脑操作系统:  Windows
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010
- 相关模块:  Nordic固件升级接口

**现象（必填）**
该接口在部分手机上无法正常完成升级过程，调用接口返回4096异常，如下：
{
    "framesToPop":1,
    "code":"4096"
}
测试的手机参考【环境】中的手机系统信息
相关issue：#497

**期望（必填）**
在MI 5C Android 7.1.2手机上可以正常使用Nordic的升级接口

**其他的上下文/日志/截图**
因日志信息较多，不在此贴出，logcat关于执行固件升级过程的全量日志已通过邮件发送给
tss-miot@xiaomi.com

**Comment by lvjie0519** [comment]
Nordic 是直接使用的第三方库，建议先去官方查看出错的原因，是否能够解决。

**Comment by dessmann** [comment]
官网也没有找到解决方案，另外，最近又新出现了以下错误：
DFU DEVICE DISCONNECTED
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:400)
    at MessageQueue.js:139
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
    at debuggerWorker.js:72
已在官网提交issue，也请帮忙协查一下，谢谢！

**Comment by lvjie0519** [comment]
@dessmann   您好， 请问该问题解决了吗？  如果解决请关闭下，如未解决，可加微信(sky-boy-0519)详聊下，谢谢。

**Comment by dessmann** [comment]
问题还是存在，大概有10%左右的失败率，先关了，再想想其他方案，多谢！

**Comment by dlutfrank** [comment]
@dessmann 我们也遇到这个问题了，你们找到解决方案了么

**Comment by dessmann** [comment]
没有，应该是原生框架兼容性的问题，考虑自己定协议实现
