### ISSUE TITLE
Host.ui.openCountDownPage接口的一些问题

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#734]
**公司名称（必填）**
江苏紫米电子技术有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家智能插线板/zimi.powerstrip.v2

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 7/iOS 10.3.3]
- SDK分支: [master/10000/]
- 相关模块:[Host/ui/openCountDownPage]

**现象（必填）**
openCountDownPage(this.state.power == 'on', 
				{
					onMethod: "power_on",
					offMethod: 'power_off',
					onParam: 'on',
					offParam: 'off'
				})
1, 这个页面主标题android和ios不统一：
	android： 设置倒计时/Set timer
	ios:	  倒计时/Schedule
	
2，倒计时假设设了2分钟，每次退出重进倒计时，都是从2分钟开始倒计时走表；
	
3, 以下都是IOS上的问题：
	a，自定义的倒计时条目不能删除(Android可以删除);
	
	b，openCountDownPage第一个参数不论是true还是false，
	   页面上都显示 “xx分钟后开启” (Android上是能对应的);
	   
	c，在app语言是英文时，倒计时页面点击按钮“stop”，“pause”，“resume”，
	   都是中文提示，“正在(开始、暂停、停止)倒计时” 。

**期望（必填）**
修正所提bug

**其他的上下文/日志/截图**

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by Banjiemin** [comment]
1, 这个页面主标题android和ios不统一：
	android： 设置倒计时/Set timer
	ios: 倒计时/Schedule
	===> 标题统一应该容易吧？
	
2，以下是IOS上的问题：
	a，自定义的倒计时条目不能删除(Android可以删除, 长按删除);
	===> 请加上这个删除功能
	
	b，倒计时假设设了2分钟，每次退出重进倒计时，都是从2分钟开始倒计时走表；
	===> android单位是秒，IOS单位是分钟，所以很快重进入的话，感觉时间没变，希望能统一成秒为单位

**Comment by Banjiemin** [comment]
还有个问题：ios倒计时设置1分钟，倒计时页UI到点后退出倒计时页面再进入倒计时页面，会出现一个几个小时的倒计时走表

**Comment by zanetti4** [comment]
@Banjiemin  10021分支，请测试
android, ios 页面标题已经统一了
ios:
单位变为秒了
openCountDownPage第一个参数为 true 时，页面上能显示 “xx分钟后关闭”了。
在app语言是英文时，已经不提示中文了。
倒计时1分钟结束后，再进入倒计时页面，没有出现一个几个小时的倒计时走表。

**Comment by zanetti4** [comment]
@Woody2016 ios 自定义倒计时条目的删除功能还没有

**Comment by Woody2016** [comment]
好，我去找相关人给补上

**Comment by Banjiemin** [comment]
这个问题真的很难搞定吗 ？

**Comment by Woody2016** [comment]
倒计时这块问题很多，不光是你说的这个问题。我们内部正在排期整改，估计要到8月中了。

我的建议是：这个问题，严重性还好，不要因为这个block你们插件开发，等我们整改上线了，你们插件里自动就有这个功能了

**Comment by santcool** [comment]
倒计时问题的issue，我暂时先关了，8月份修改后，我们会提供新的包让大统一验证
