### ISSUE TITLE
调试自定义智能页面失败

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#735]
- IPA/APK 是否更新到最新？是
- SDK 是否更新到最新？是
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
上海榉树智能科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
shjszn.lock.c1

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]iOS 12.0.1
- SDK分支: [eg.master/10000/...]10010
- 相关模块:[eg.Host/Service/Account]Package

**现象（必填）**
1、在插件页内，通过Host.ui.openIftttAutoPage()打开智能设置，进入不到自定义智能页面，出错如下图：

![](https://user-images.githubusercontent.com/12531667/57269247-43c8bb00-70b9-11e9-9eb6-18ecf0a34e97.jpeg)

2、在米家app自带的智能设置（如下图），可以正常进入到自定义智能页面。

![](https://user-images.githubusercontent.com/12531667/57280649-c3678180-70db-11e9-910b-77eda2addcd7.jpg)

**期望（必填）**
通过Host.ui.openIftttAutoPage()打开智能设置，也可以正常进入自定义智能页面

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by ldezho** [comment]
#647

**Comment by santcool** [comment]
请问你后来复现了吗？我这边多次尝试，均可以打开智能页面，无任何问题。请去github下载最新app，使用最新SDK_10010重试下，如果还有问题，请继续在此处留言。

**Comment by ldezho** [comment]
@santcool 我这边刚刚更新的最新SDK_10010和ipa，效果和之前一样。

**Comment by ldezho** [comment]
有什么办法可以让我给你提供一些详细的日志吗？

**Comment by santcool** [comment]
你的node sever跑起来了吧？如果跑起来了，检查开发者设置ip是否正确，是否开启调试，它提示server没跑起来，这种问题没什么好的办法去提供日志，一般是js运行起来后，js里面出现功能问题，我们才能提供日志。

**Comment by ldezho** [comment]
@santcool 从米家自带的那个智能入口，可以正常进入，调试日志什么的都可以看到。

**Comment by ldezho** [comment]
请问这个地方查出是什么问题了吗？

**Comment by ldezho** [comment]
这个问题还有人关注吗？

**Comment by ldezho** [comment]
请求关注，请求处理，谢谢🙏

**Comment by ldezho** [comment]
[1558077208372688.mp4.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3190300/1558077208372688.mp4.zip)
这是我们录的视频，以供参考，希望有用，谢谢。

**Comment by santcool** [comment]
关闭开发者设置-其他设置-插件调试，摇一摇手机，关闭Debug JS Remotely，即可解决问题。主要原因是RN不支持调试多个RN插件。视频中的操作，需要打开多个RN插件。

**Comment by ldezho** [comment]
多谢帮助解决问题。
