### ISSUE TITLE
米家新扩展程序开发是否支持 MobX ？

### ISSUE THREAD

**Issue by Bijiabo** [MiEcosystem/miot-plugin-sdk#736]
MobX for React Native 需要升级 jsc-android，感觉蛮好用的，请问是否支持呢？

**公司名称（必填）**
MXCHIP

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
产品无关

**环境（必填）**
- SDK分支:10003

**Comment by blockdate** [comment]
这个在SDK中未支持，可以自行在项目中集成。

**Comment by devYoungyang** [comment]
我在项目中集成mobx，总是报各种错误
