### ISSUE TITLE
使用miot新协议如何配置APP推送

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#737]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
扫拖一体机/dreame.vacuum.mc1808

**现象（必填）**
在产品后台的推送配置上，仅支持老的iot协议的配置，新版Spec协议如何配置推送

**期望（必填）**
可以配置事件推送

**Comment by Bijiabo** [comment]
> 你说的就是miot-spec的订阅吧，文档正在更新中。先贴一小段：
> 方法：Device.getDeviceWifi().subscribeMessages('prop.siid.piid')
> 具体使用[如图](http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_png_a93fcb00412b411aa6b72c4320ce1222.png)

这个试了一下收不到，请尽快更新文档吧

**Comment by heigaga001** [comment]
@santcool 不是这个，是通知栏的推送

**Comment by heigaga001** [comment]
@Bijiabo 可以收到的，设备端得通过properties_changed 这个method发送数据

**Comment by Bijiabo** [comment]
@heigaga001 找到愿意了似乎，我们通过后台创建的设备型号相关数据有问题，他们云端团队在处理 :)

**Comment by santcool** [comment]
一样的。我们的订阅用的是MIPush，在app活跃时，一般是长连接,在后台，或者app关闭了，就是推送。你看我给的图片，miot-spec的订阅同理。只不过订阅的属性由prop.properName，变为prop.siid.piid。

**Comment by heigaga001** [comment]
@santcool  通知栏的推送不是应该在网页后台配置么，
[图1](http://cnbj2.fds.api.xiaomi.com/sweeper.clean.logs/1.png)
[图2](http://cnbj2.fds.api.xiaomi.com/sweeper.clean.logs/2.png)

**Comment by heigaga001** [comment]
@santcool 推送的配置问题能帮忙确定一下怎么配置吗？

**Comment by blockdate** [comment]
仔细看文档 [配置消息推送](https://iot.mi.com/new/guide.html?file=03-%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/02-%E6%99%BA%E8%83%BD%E7%A1%AC%E4%BB%B6%E7%9B%B4%E8%BF%9E%E6%8E%A5%E5%85%A5/07-%E9%85%8D%E7%BD%AE%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81)

**Comment by heigaga001** [comment]
@blockdate 文档和后台都是用的老的iot协议，不支持新的spec协议的配置，

**Comment by blockdate** [comment]
@heigaga001 确认了，需要发送邮件申请配置，邮件发送给wangxiaofan@xiaomi.com。说明要需求。

**Comment by heigaga001** [comment]
好的，谢谢
