### ISSUE TITLE
蓝牙断不开

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#738]
**公司名称（必填）**
舒可士（深圳）科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家声波电动牙刷/soocare.toothbrush.m1

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS
- SDK分支: master
- 相关模块:Device

**现象（必填）**
IOS 米家Beta 205发现存在这个问题，之前的Beta版本未发现。

执行蓝牙断开操作，却未断开成功。
<img width="464" alt="image" src="https://user-images.githubusercontent.com/7885251/57366924-950ca380-71ba-11e9-82b5-2bf2c22ebed0.png">

**期望（必填）**
正常断开蓝牙

**Comment by blockdate** [comment]
提供下JS端的日志信息

**Comment by JxXiaoXie** [comment]
日志

[MiHome 日志.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3156912/MiHome.txt)

**Comment by JxXiaoXie** [comment]
你在demo里的加上这段试试：
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7885251/57422873-51f71280-7244-11e9-8f30-fa6d55df5d7f.png">

操作步骤：
1、走米家绑定流程绑定设备，这个时候设备蓝牙灯是亮的，进入插件。
2、进入插件后我想断开蓝牙，执行 bt.disconnect(); 操作蓝牙断不开。bt.isConnected 返回的也是未连接。实际蓝牙是连着的。

**Comment by blockdate** [comment]
说明下你的情况，在蓝牙处于连接状态下进入插件，插件底层是没有peripheral 实例对象的，你直接去断连，系统并不知道你要断开那一个蓝牙连接。

这种情况如果需要断开连接，请先使用 `retrievePeripheralsForIOS` 或者 `retrievePeripheralsWithServicesForIOS` 获取已连接的蓝牙对象，然后手动创建蓝牙对象`Bluetooth.createBluetoothLE(result.uuid || result.mac);`，之后再进行断连操作才可以

**Comment by JxXiaoXie** [comment]
可以断开了，多谢🙏。

**Comment by caojunhua** [comment]
> 可以断开了，多谢🙏。

您好，
       我也遇到了类似的问题，能否贴一段demo参考你的是怎么解决的呢？不胜感激！

**Comment by JxXiaoXie** [comment]
> > 可以断开了，多谢🙏。
> 
> 您好，
> 我也遇到了类似的问题，能否贴一段demo参考你的是怎么解决的呢？不胜感激！

<img width="893" alt="image" src="https://user-images.githubusercontent.com/7885251/57915686-e6581980-78c3-11e9-8b6b-71dd8597a580.png">

**Comment by caojunhua** [comment]
> > > 可以断开了，多谢🙏。
> > 
> > 
> > 您好，
> > 我也遇到了类似的问题，能否贴一段demo参考你的是怎么解决的呢？不胜感激！
> 
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/7885251/57915686-e6581980-78c3-11e9-8b6b-71dd8597a580.png">

爱你么么哒

**Comment by dgutkai** [comment]
> > > > 可以断开了，多谢🙏。
> > > 
> > > 
> > > 您好，
> > > 我也遇到了类似的问题，能否贴一段demo参考你的是怎么解决的呢？不胜感激！
> > 
> > 
> > <img alt="image" width="893" src="https://user-images.githubusercontent.com/7885251/57915686-e6581980-78c3-11e9-8b6b-71dd8597a580.png">
> 
> 爱你么么哒

你好，我照着这个代码没有效果，没有进入for循环

**Comment by potatoes0521** [comment]
> > > 可以断开了，多谢🙏。
> > 
> > 
> > 您好，
> > 我也遇到了类似的问题，能否贴一段demo参考你的是怎么解决的呢？不胜感激！
> 
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/7885251/57915686-e6581980-78c3-11e9-8b6b-71dd8597a580.png">

您好可以加您一个联系方式吗
