### ISSUE TITLE
导航栏白色系统文字和图标无法显示

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#739]
**公司名称（必填）**
万魔

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米小爱音箱HD/onemore.wifispeaker.sm4"

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10010]
- 相关模块:[miot/ui/TitleBar]

**现象（必填）**
导航栏白色系统文字和图片不会根据TitleBar的背景颜色改变而改变。当TitleBar的type='dark'时，白色系统文字和图片无法显示。

**期望（必填）**
当TitleBar的type='dark'时，白色系统文字和图片反正为黑色，并能正常显示。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46127660/57375814-f93a6200-71d0-11e9-86d6-b09be3bf1b72.png)
![image](https://user-images.githubusercontent.com/46127660/57375824-00617000-71d1-11e9-85ae-779a2bbf27b4.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
> 现象（必填）
导航栏白色系统文字和图片不会根据TitleBar的背景颜色改变而改变。当TitleBar的type='dark'时，白色系统文字和图片无法显示。
> 
> 期望（必填）
当TitleBar的type='dark'时，白色系统文字和图片反正为黑色，并能正常显示。

不好意思，没看懂

**Comment by JobenTian** [comment]
对比两张截图，第一张为type='dark'时的截图，白底黑字，导航栏的系统图标“4G信号图标”、“wifi图标”、“蓝牙图标”、“电池图标”和“当前时间”等白色图标和文字就看不见了；第二张截图，没有设置type='dark，黑底白字，上述的那些白色图标就可见。我这样描述，你看懂了吗？期望能像ios那样，设置type='dark'时，白色的图标和文字等反转成黑色，这样就可见了。

**Comment by LiuMengzhou** [comment]
SDK_10011
722f335
[com.xiaomi.demo-「首页」-「教程」-「导航栏 TitleBar Demo」](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10011/projects/com.xiaomi.demo/Main/tutorial/TitleBarDemo.js)
可参考demo

**Comment by JobenTian** [comment]
@LiuMengzhou 已经更新SDK_10011，但是demo也有一样的问题啊。第一张黑底白字，正常显示，第二张白底黑字，就显示不了了。
![image](https://user-images.githubusercontent.com/46127660/57612503-8a318480-75a7-11e9-8724-f7c851e81b9a.png)
![image](https://user-images.githubusercontent.com/46127660/57612515-8f8ecf00-75a7-11e9-9d1c-9aaad7472643.png)

**Comment by LiuMengzhou** [comment]
导航栏 3 4 5 6都有问题？

**Comment by JobenTian** [comment]
白底的就有问题

**Comment by LiuMengzhou** [comment]
啥问题？
你把导航栏 3 4 5 6截图
然后说一下手机型号吧

**Comment by JobenTian** [comment]
不会吧，到现在你还没清楚我的问题吗？导航栏设为白底黑字，导航栏的系统图标“4G信号图标”、“wifi图标”、“蓝牙图标”、“电池图标”和“当前时间”等白色图标和文字就看不见了。从前面的截图可以清楚的看到。
我的手机型号是：华为荣耀8X

**Comment by JobenTian** [comment]
@LiuMengzhou 你那边有复现这个问题吗？

**Comment by JobenTian** [comment]
@LiuMengzhou 如果问题还是不清楚的话，能否加微信详聊。

**Comment by JobenTian** [comment]
这个问题，求关注啊。

**Comment by lvjie0519** [comment]
@JobenTian   如果问题未解决，请加微信（18750118631），进行详聊。

**Comment by JobenTian** [comment]
已解决。部分安卓手机TitleBar的style.backgroundColor属性设置不生效，需要在在页面的render里面用StatusBar的API StatusBar.setBackgroundColor强制设置。但是这个API强制设置一次后，所有的页面都会改变。

**Comment by zaxayn** [comment]
iPhone6 12.3.1 目前也遇到了这个问题
