### ISSUE TITLE
从智能自定义页面退出返回到主插件后，主插件无法正常退出

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#740]
**公司名称（必填）**
万魔

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米小爱音箱HD/onemore.wifispeaker.sm4

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10010]
- 相关模块:[Host/ui/openIftttAutoPage]

**现象（必填）**
从主插件设置中进入智能页面，添加智能时打开自定义页面添加文字，保存后退出自定义页面返回主插件的智能页面，继续返回到主插件的主页面，再返回时无法正常退出主插件。

**期望（必填）**
从自定义页面返回主插件后，主插件也能正常退出。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
已修复， 请使用最新apk。
自动化测试这块有几个注意点：
1、如果是下载线上的插件包进行测试，无法进入插件自动化界面，先检查下project.json文件的问题，具体在手机里面的位置使用 logcat   通过project_json_path 过滤下日志，会输出文件的具体位置；
2、如果是本地调试，由于project.json是我们代码默认写一份到手机本地的，同理，查看下文件的具体位置，进行下替换即可；
3、从插件页面进入到APP层的智能列表再次进入到插件自动化页面，不要开启浏览器调试，否则会出现莫名的错误，暂未解决。
