### ISSUE TITLE
openTimerSettingPageWithVariousTypeParams的列表排序android和ios不一致

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#741]
**公司名称（必填）**
创米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
chuangmi.plug.m3，chuangmi.plug.v3，chuangmi.plug.m1等

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]   Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]                Andorid 9/IOS 12.2
- SDK分支: [eg.master/10000/...]                     master/10003
- 相关模块:[eg.Host/Service/Account]             openTimerSettingPageWithVariousTypeParams

**现象（必填）**
openTimerSettingPageWithVariousTypeParams的列表排序android和ios不一致

**期望（必填）**
简单明了地描述一下期望的表现。
openTimerSettingPageWithVariousTypeParams的列表排序android和ios一致

**其他的上下文/日志/截图**
<img width="898" alt="WX20190509-094546@2x" src="https://user-images.githubusercontent.com/8665213/57421814-cc716380-723f-11e9-834d-dc619e1a112b.png">

**尝试过的解决办法**
使用最新线上版米家

**不要贴大段代码❗️**

**Comment by santcool** [comment]
已修复
