### ISSUE TITLE
Service.smarthome.getDeviceData获取的数据，value格式有变化？

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#742]
- IPA/APK 是否更新到最新？是
- SDK 是否更新到最新？是
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
上海榉树智能科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
shjszn.lock.c1

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] iOS 12.0.1
- SDK分支: [eg.master/10000/...] 10010
- 相关模块:[eg.Host/Service/Account] Service

**现象（必填）**
<img width="824" alt="image" src="https://user-images.githubusercontent.com/12531667/57423936-7bb23880-7248-11e9-9396-b9acc126784c.png">

Service.smarthome.getDeviceData获取的数据，value之前一直是固定长度20，最近发现有些数据长度为18，导致不能正确解析。我们想知道这种新格式的数据要怎么解析，有什么文档可以参考吗？

**期望（必填）**
如果数据有了新的格式，期望给一份文档
如果数据是因为某些原因造成的有问题的数据，期望可以查明原因

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
这里的数据都是设备端上传的数据。并不是我们提供的。建议查询下对应设备的事件上报记录

**Comment by ldezho** [comment]
@blockdate  这个是手机蓝牙开门，而且使用老插件页开门是好的，并且这个问题是偶现，概率还不低。

**Comment by blockdate** [comment]
提供下你们掉用的js端操作代码

**Comment by ldezho** [comment]
@blockdate 
1、开锁代码是调用米家提供的接口，获取数据是title中的接口，不太明白提供js代码有什么用
2、您指的是开锁代码？还是其他什么地方的调用代码？

**Comment by blockdate** [comment]
分别提供下你在新旧插件下使用的方法。

**Comment by ldezho** [comment]
新： Device.getBluetoothLE().securityLock.toggle
旧：MHXiaomiBLE.toggleLockXiaoMiBLE
目前还没发现开锁有其他接口！

**Comment by blockdate** [comment]
这边找相关同学咨询了下：
1. 这个数据是完全由固件端进行上报的，不是app端上传的。
2. 这个数据应该是可以由ble.securityLock.decryptMessage来解析。

**Comment by ldezho** [comment]
1、ble.securityLock.decryptMessage，以及.encryptMessage，这个是给锁发送或者接收数据加解密用的。不是解析这个地方的数据的吧？
2、新：Service.smarthome.getDeviceData
      旧：MHPluginSDK.callSmartHomeAPI("/user/get_user_device_data" 
这两个接口获取的数据有时候是不一样的。
3、（偶现）密码开门
米家app-->我的-->右上角消息中心可以看到密码开锁记录，但是通过上面接口无法获取到这个密码的开锁记录。

**Comment by blockdate** [comment]
1. 加密解密在toggle内部蓝牙读写时的数据使用这个方法转出来的
2. 这两个接口内部实现逻辑是基本一致的，只有返回的结构可能不一致，这边方便分享下设备到uid:894158105下，我们这边确认下问题。

**Comment by ldezho** [comment]
已分享

**Comment by ldezho** [comment]
@blockdate 数据不一致问题，我们查清了，是因为固件广播的锁事件格式由0x0005变更为0x000B
（参考：https://github.com/MiEcosystem/miio_open/blob/master/ble/04-米家BLE%20Object定义.md）

锁通过升级固件，锁事件由0x0005变为0x000B后，通过0x0005没有拿到密码开锁记录（可以拿到蓝牙开锁的）。 通过0x000B去拿数据的时，老数据获取不到
目前Service.smarthome.getDeviceData这个接口参数中key只能传一个，只能是0x0005或者0x000B，是否会提供一个都能获取的接口？或者对于出现的这种问题，建议该怎么做？

**Comment by blockdate** [comment]
这个目前貌似没有支持多key混合查询的接口，因为对服务端而言你是上传的两个不同的事件了。

鉴于你们是固件升级之后变更了key造成的，是否优先获取最新的key的事件，随后 再获取旧的key对应的记录

**Comment by ldezho** [comment]
@blockdate 好的，且多谢您的建议。
