### ISSUE TITLE
创建桌面快捷方式错误提示有误

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#743]
**公司名称（必填）**
万魔

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米小爱音箱HD/onemore.wifispeaker.sm4

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10010]
- 相关模块:[Host/ui/openAddToDesktopPage]

**现象（必填）**
在关闭米家APP创建桌面快捷方式权限时，从插件中调用openAddToDesktopPage创建桌面快捷方式时，提示“成功添加快捷方式”，实际上并没有添加。

**期望（必填）**
在未开启相关权限时创建桌面快捷方式时，提示尚未开启创建桌面快捷方式权限。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46127660/57426618-7f4abd00-7252-11e9-8aad-3df65dc9a22a.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@JobenTian  APP反馈，快捷方式判断不出来，暂时不支持。
