### ISSUE TITLE
NumberSpinner在安卓上滑动时会显示奇怪的边缘颜色

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#744]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
米家智能门锁/lumi.lock.mcn01

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: 红米Note7 Android9.0
- SDK分支: master
- 相关模块: miot/ui  NumberSpinner

**现象（必填）**
红米Note7上，滑动NumberSpinner过程中会出现边缘颜色。

**期望（必填）**
希望能去掉边缘颜色

**其他的上下文/日志/截图**
![Screenshot_2019-05-07-12-03-26-308_com xiaomi smarthome](https://user-images.githubusercontent.com/2813239/57427098-01d47c00-7255-11e9-8644-958910d76f7e.png)

**Comment by lvjie0519** [comment]
这个是按下具有的颜色，目前APP原生端实现也是如此。

**Comment by fengdexunmi** [comment]
@lvjie0519 吕老板，这个Spinner滑动边缘颜色，我们设计师表示接受不了😂，这个能否去掉滑动边缘颜色呢？

**Comment by qinliduan** [comment]
StringSpinner 一样的问题，触摸就会出现

**Comment by lvjie0519** [comment]
@fengdexunmi   可以， 得下个版本作支持，修复及时通知。

**Comment by lvjie0519** [comment]
@fengdexunmi   已经修复，可以使用最新apk测试。
