### ISSUE TITLE
MessageDialog的内容无法设置对齐方式

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#745]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
米家智能门锁/lumi.lock.mcn01

**环境（必填）**
- 电脑操作系统: MacOS
- 手机系统: 红米Note7 Android9.0
- SDK分支: master
- 相关模块: miot/ui/MessageDialog

**现象（必填）**
MessageDialog内容无法设置居左对齐

**期望（必填）**
希望MessageDialog提供对齐方式的参数设置

**其他的上下文/日志/截图**
![Screenshot_2019-05-09-11-45-59-105_com xiaomi smarthome](https://user-images.githubusercontent.com/2813239/57427448-85429d00-7256-11e9-8da9-9c4674796155.png)

**Comment by LiuMengzhou** [comment]
`MessageDialog`是原生组件，目前暂不支持设置对齐方式。目前正在用JS开发新的MessageDialog，敬请期待。
