### ISSUE TITLE
IOS 联动 进入 插件页，不用输入安全码即可进入，而Android 上需要输入安全码才进入。请两端统一

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#746]
**公司名称（必填）**
云丁

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
loock.lock.v5   蓝牙门锁

**现象（必填）**
IOS 米家Beta (205版本)，在设备列表点击进入插件需要输入安全码，但在创建智能联动时，点击自定义联动（会进入插件页）时，却不用输入安全码。

**期望（必填）**
同样的操作Android上 是需要输入安全码的，希望两端统一。

**Comment by lvjie0519** [comment]
@zhaolios  问题已解决，请使用最新apk进行测试，谢谢。
