### ISSUE TITLE
Nubia X手机subscribeMessages失败

### ISSUE THREAD

**Issue by JobenTian** [MiEcosystem/miot-plugin-sdk#747]
**公司名称（必填）**
万魔

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米小爱音箱HD/onemore.wifispeaker.sm4

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10010]
- 相关模块:[Device/getDeviceWifi/subscribeMessages]

**现象（必填）**
Nubia X手机加载插件时Device.getDeviceWifi().subscribeMessages失败，但是其他手机都能正常订阅。

订阅相关代码：
let msgSubscription = null;
		Device.getDeviceWifi().subscribeMessages('prop.SpeakerVolume', 'prop.SpeakerRate', 'prop.SpeakerMute', 'prop.MicrophoneMute').then(subcription=>{
			console.log('subscribe success');
			msgSubscription = subcription;
		}).catch(subcription=>{
			console.error('subscribe failed');
		});    

错误提示“subscribe failed”，具体如下图所示。

**期望（必填）**
Nubia X手机加载插件时能正常订阅。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46127660/57440290-54745f00-727a-11e9-9472-b00dd94609a6.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
提供下手机的日志输出

**Comment by JobenTian** [comment]
@blockdate 日志如文件，请帮忙分析一下，谢谢！
[logcat.txt](https://github.com/MiEcosystem/miot-plugin-sdk/files/3164845/logcat.txt)

**Comment by lvjie0519** [comment]
该问题已知， 该手机会自动将mi push service杀死，这边暂无法支持，如需要支持，建议贵方通过产品或jira上提bug来推动，谢谢。
