### ISSUE TITLE
如何往蓝牙设备写入Descriptor？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#749]
**是否为新产品（必填）**
是

**产品名称/Model（必填）**
ls123.headphone.t10

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 8.1
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Bluetooth]

**现象（必填）**
如何往蓝牙设备中写入Descriptor？
在Android原生代码中，可以使用
mBluetoothGatt.writeDescriptor(descriptor);
往设备写入Descriptor，那么在框架中，要怎么操作呢？
**期望（必填）**
能够像原生代码那样读写Descriptor。

**Comment by blockdate** [comment]
这边提供下使用的用途，我们确认后会进行功能添加

**Comment by dgutkai** [comment]
我这边使用高通的一款芯片作BLE OTA功能，在注册Notification的时候，需要往该Characteristic写入Descriptor，才能正常接收到数据。
如代码所示的是我的注册监听方法。
`public static final byte[] ENABLE_NOTIFICATION_VALUE = {0x01, 0x00};
    public static final byte[] DISABLE_NOTIFICATION_VALUE = {0x00, 0x00};
    public static final UUID CLIENT_CHARACTERISTIC_CONFIG = UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");
    public boolean requestCharacteristicNotification(BluetoothGattCharacteristic characteristic, boolean register) {
        BluetoothGattDescriptor descriptor = characteristic.getDescriptor(CLIENT_CHARACTERISTIC_CONFIG);
        byte[] data = register ? ENABLE_NOTIFICATION_VALUE
                : DISABLE_NOTIFICATION_VALUE;
        descriptor.setValue(data);
        boolean result1 = mBluetoothGatt.setCharacteristicNotification(characteristic, register);
        boolean result2 = mBluetoothGatt.writeDescriptor(descriptor);
        return result1 && result2;
    }`

**Comment by blockdate** [comment]
这个初步确认信息为 暂时不需要自己处理Descriptor，app自动处理了这些操作。建议再使用过程中有问题再提。
