### ISSUE TITLE
撤销隐私授权后，设备无法再次添加绑定

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#750]
---
**公司名称（必填）**
克莱文

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
空调线控器网关/vrviot.airrtc.vrvb01xrt

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
linux
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 5.5
- SDK分支: [eg.master/10000/...]
10010
- 相关模块:[eg.Host/Service/Account]
Account
**现象（必填）**
在做更多设置功能的时候，无意间点中了撤销隐私协议及授权后，设备被删除了无法添加，在后台查看产品发现产品信息为空了，这个该怎么办
![image](https://user-images.githubusercontent.com/11848308/57463900-47716300-72ae-11e9-95a6-9fd0d0afcafc.png)
但是chan'p产品列表里面是有产品信息的

![image](https://user-images.githubusercontent.com/11848308/57463958-63750480-72ae-11e9-9fb5-c863065d0158.png)

**期望（必填）**
希望能有相应的补救办法

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
撤销隐私并不会导致产品信息受影响，这边建议排查下是否有人修改过这些信息，或者找对接的产品确认问题。

**Comment by uSmile-Y** [comment]
那我们现在的产品 还是有效的吗？

**Comment by uSmile-Y** [comment]
那我们现在的产品 还是有效的吗？

**Comment by blockdate** [comment]
撤销隐私仅仅是某个用户对他自己的某个设备进行撤销隐私授权，并不会影响产品。

**Comment by uSmile-Y** [comment]
我是说这种情况 
![image](https://user-images.githubusercontent.com/11848308/57496772-4a4c7200-7307-11e9-99ec-3f6dc8c317c0.png) 我们的这个产品 还能继续使用吗  现在无法添加设备了 该怎么弄

**Comment by uSmile-Y** [comment]
app上无法绑定

**Comment by uSmile-Y** [comment]
我确认了下，出现这个信息空白的问题，并不是我一家，看来并不是由于撤销隐私授权导致的，可能是个bug？

**Comment by blockdate** [comment]
我这边找相关人员确认下问题

**Comment by blockdate** [comment]
这边设备添加的时候有任何错误信息提示可以提供下么。

另外iot信息空白建议清理下浏览器缓存

**Comment by uSmile-Y** [comment]
1、平台设备信息为空的问题，清理了浏览器缓存 一样的是空白
2、在绑定设备的时候，提示:无法发现设备

**Comment by blockdate** [comment]
绑定设备的过程方便录个视屏发送到wulei7@xiaomi.com，也可以带上微信号，方便快速沟通确认问题

**Comment by uSmile-Y** [comment]
好的

**Comment by uSmile-Y** [comment]
设备绑定上了，产品信息也出来了。。。
