### ISSUE TITLE
Detected problems with API compatibility' in Mi 8

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#751]
**环境 **
MiHome 5.5.15

**是否为新产品（必填）**
"是"

**现象（必填）**
Detected problems with API compatibility' in Mi 8

**期望（必填）**

**其他的上下文/日志/截图**
![Screenshot_2019-05-08-14-17-56-731_com xiaomi smarthome](https://user-images.githubusercontent.com/37297126/57494927-3d775080-72fe-11e9-9425-d3153a570e32.png)

**Comment by blockdate** [comment]
这是因为google检测到某些函数的属性映射之后弹出的提示窗，仅在debug下会出现，不影响上线。
