### ISSUE TITLE
调试设备提示请升级App至最新版本

### ISSUE THREAD

**Issue by balddonkey** [MiEcosystem/miot-plugin-sdk#752]
iOS下载了fir的调试app，开启了开发者模式，设置了调试选项，然后返回设备列表点击设备提示请升级App至最新版本，请问怎么解决。

附加：
iPhone6sp iOS12.1

**Comment by blockdate** [comment]
你是要本地调试还是下载插件测试。
如果本地调试的话，检查下设置项目是否设置正确。
如果是下载插件测试，检查下插件是否关联了model以及使用人员是否是白名单

**Comment by balddonkey** [comment]
@blockdate

**Comment by balddonkey** [comment]
> 你是要本地调试还是下载插件测试。
> 如果本地调试的话，检查下设置项目是否设置正确。
> 如果是下载插件测试，检查下插件是否关联了model以及使用人员是否是白名单

是本地调试的，package设置的是 npm run create xxx 的 xxx，model设置的iot平台注册的设备model，设备也配网成功了，点击设备就提示这个，点击直接调试是可以进入界面的。

**Comment by blockdate** [comment]
把你的配置model发上来，同时将设备分享到894158105

**Comment by balddonkey** [comment]
> 把你的配置model发上来，同时将设备分享到894158105

model: opple.light.demo

**Comment by balddonkey** [comment]
> 把你的配置model发上来，同时将设备分享到894158105

model: opple.light.demo

**Comment by balddonkey** [comment]
> 把你的配置model发上来，同时将设备分享到894158105

model: opple.light.demo
已分享

**Comment by blockdate** [comment]
你们设备的正确model 是 opple.light.cablelamp

**Comment by balddonkey** [comment]
@blockdate 
好的，多谢，麻烦你了，为了安全起见，我先删除掉有model的回复了～
