### ISSUE TITLE
芯片连接认证失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#753]
![image](https://user-images.githubusercontent.com/18459414/57498974-75878f00-7310-11e9-85c2-dd33d57418b3.png)

**Comment by blockdate** [comment]
设备是新设备还是已经上线过的设备呢

**Comment by caojunhua** [comment]
新设备，内测中的，这个现象不是每次都有，是内测中遇到的问题。

**Comment by caojunhua** [comment]
> 设备是新设备还是已经上线过的设备呢

您好，这个问题是什么原因导致的呢，有什么办法可以解决吗

**Comment by cfJand** [comment]
请按照issue模板提交issue，此issue由于未按照要求发issue，暂时关闭。
