### ISSUE TITLE
如何在设备删除时，删除指定本地存储数据

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#754]
在做隐私协议弹框的时候需要判断当前是否第一次使用。

目前用的是 Host.storage.get(didKey) 和  Host.storage.set(didKey)方法。但是这样存储的数据删除设备时如何删除？
以便下次重新添加的时候能够再次弹出。

===代码
  _showLicense(){

    let didKey = 'isFirstUse'+Device.deviceID;
    Host.storage.get(didKey)
    .then(val => {
          console.log(didKey, val);
          if(val){
            //load val success do nothing
          }else{
          Host.ui.openPrivacyLicense(getString('device_more_activity_license'),require('./resources/license_zh.html'),
          getString('device_more_activity_privacy'),require('./resources/privacy_zh.html'))
          .then(()=>{
            Host.storage.set(didKey,'true');
            console.log('save firstUse value:', didKey)
          });
          }
     })
    .catch(err => {
    //load val error 
    if (err === 'expired') {console.log('value for key already expired')}
    });
  }

**Comment by blockdate** [comment]
```
PackageEvent.packageAuthorizationCancel.addListener(() => {
    // 用户撤销授权,需要清除缓存
    console.log("packageAuthorizationCancel");
    let licenseKey = "license-" + Device.deviceID;
    Host.storage.set(licenseKey, false);
    Package.exit();
})
```
Demo 程序的index中就有实例

**Comment by blockdate** [comment]
可以尝试使用batchSetDeviceDatas 接口存储在服务端，这个接口在删除设备时会清空设置

**Comment by febird** [comment]
@blockdate 我们提交测试，反馈一个问题是，在一台手机A撤销授权后删除设备，在另一台手机B上（同一个帐号，以前也授权过）再次添加设备，不会再弹出授权框，说需要改。
  但是按照现在这个本地仅修改本地存储的方案，撤销A手机的授权，并不会撤销B的授权，改怎么修改呢？

**Comment by blockdate** [comment]
隐私协议弹框需求：
a. 所有接入米家的设备，绑定成功后第一次进插件，都需要隐私弹框，后续再进不需弹框
b. 取消隐私授权/解绑设备后，重新绑定设备，仍需遵循规则a

插件端可按如下方案实现：
1. 使用batchSetDeviceDatas存储一个标志位，用来记录是否“隐私弹框”过
2. 进入插件时batchGetDeviceDatas获取此标志位，若为NO，弹框，同时设置标志位为YES；若为YES，不弹框
3. 设备取消授权或解绑设备时，此标志位米家后台会自动清除，故遵循了上述需求b
4. 异常处理：进插件时，如果网络异常等原因导致batchGetDeviceDatas失败，就不弹框（此时99%情况是第2+次进插件）

**Comment by febird** [comment]
@blockdate SetDeviceDatas 数据是云端的吗？
这样是否会有另一个问题，A  手机上授权一次后，B手机第一次 打开不会出现授权提示。

**Comment by blockdate** [comment]
如果是同一个用户，授权一次就不需要再弹出了。就如同撤销授权都会被撤销一样、

**Comment by WWJ1993** [comment]
我同一个手机同一个账号，按照您上边的代码添加用户撤销授权的监听；用户撤销授权时，打断点调试，授权的监听方法走了，确实监听到了，但是还没来得及执行Host.storage.set(licenseKey, false)这行代码，程序就退出了，导致false 状态没有存进去，再次绑定就不会再弹了？这种问题又遇到吗？

**Comment by blockdate** [comment]
@WWJ1993 这个问题是双平台下都有的问题还是？

**Comment by WWJ1993** [comment]
目前发现苹果有问题
