### ISSUE TITLE
基于新RN框架开发的插件在小米手机及红米系列手机上显示异常

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#755]
**公司名称（必填）*上海小吉科技有限公司*
贵司的简称：小吉

**是否为新产品（必填）*否*
若是旧框架插件迁移相关，请填"否"

**产品名称/Model（必填）**
产品名称：米家洗烘一体机10kg，model：minij.washer.v8
产品名称：米家互联网洗烘一体机Pro 10kg，model：minij.washer.v5
产品名称：小吉智能迷你滚筒洗衣机，model：minij.washer.v1
**环境（必填）**
- 电脑操作系统:[eg.Windows/
- 手机系统:小米、红米系列所有手机
- SDK分支: [eg.master/10005/...]
- 相关模块:[eg.Host/Service/Account] v5和v8的模块是32u，v1是生态链公司模块

**现象（必填）**
简单明了地描述一下实际的现象。
部分文字无法显示出来。如钟、℃等等。英文页面下英文只显示一半，情况如下图：

**期望（必填）**
希望文字可以显示正常

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？
其他手机机型没有这种现象

**Comment by hao0000** [comment]
![image](https://user-images.githubusercontent.com/28422366/57507794-54379a80-7332-11e9-91b9-b3b71fe343a3.png)
![微信图片_20190510143939](https://user-images.githubusercontent.com/28422366/57507810-66b1d400-7332-11e9-811c-da5987e49822.jpg)
![1](https://user-images.githubusercontent.com/28422366/57507838-7df0c180-7332-11e9-8190-ee6409947088.jpg)

**Comment by hao0000** [comment]
> **公司名称（必填）_上海小吉科技有限公司_
> 贵司的简称：小吉
> 
> **是否为新产品（必填）_否_
> 若是旧框架插件迁移相关，请填"否"
> 
> **产品名称/Model（必填）**
> 产品名称：米家洗烘一体机10kg，model：minij.washer.v8
> 产品名称：米家互联网洗烘一体机Pro 10kg，model：minij.washer.v5
> 产品名称：小吉智能迷你滚筒洗衣机，model：minij.washer.v1
> **环境（必填）**
> 
> * 电脑操作系统:[eg.Windows/
> * 手机系统:小米、红米系列所有手机
> * SDK分支: [eg.master/10005/...]
> * 相关模块:[eg.Host/Service/Account] v5和v8的模块是32u，v1是生态链公司模块
> 
> **现象（必填）**
> 简单明了地描述一下实际的现象。
> 部分文字无法显示出来。如钟、℃等等。英文页面下英文只显示一半，情况如下图：
> 
![1](https://user-images.githubusercontent.com/28422366/57508042-03747180-7333-11e9-8aea-3fa5e3e5e7d9.jpg)


> **期望（必填）**
> 希望文字可以显示正常
![2](https://user-images.githubusercontent.com/28422366/57507975-d627c380-7332-11e9-99f0-c691848d834d.jpg)


> 
> **其他的上下文/日志/截图**
> 提供更多的上下文，有日志或者截图更好。
> 
> **尝试过的解决办法**
> 尝试过哪些操作？
> 其他手机机型没有这种现象

**Comment by JxXiaoXie** [comment]
没显示出来文字的地方，样式里面设置下字体试试。

**Comment by lvjie0519** [comment]
@hao0000

**Comment by hao0000** [comment]
> 没显示出来文字的地方，样式里面设置下字体试试。

更换字体后可以显示，但在ios上有些丑，有啥推荐的字体

**Comment by JxXiaoXie** [comment]
> > 没显示出来文字的地方，样式里面设置下字体试试。
> 
> 更换字体后可以显示，但在ios上有些丑，有啥推荐的字体

https://github.com/MiEcosystem/miot-plugin-sdk/issues/755#issuecomment-491700085
