### ISSUE TITLE
关于更新后进入旧版本插件的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#756]
您好，
       上次遇到的出现旧版本插件的问题，这几次也都遇到过，现在发现出现问题的情景，
       就是我现在的新版本更新后，点击更新新版本后，再次进入插件，就会出现旧版本的插件，可能过一段时间后，就会恢复到新版本的插件。

**Comment by blockdate** [comment]
不是回复过你很多次是因为服务器缓存还没稳定导致的么，正常上线是不存在问题

**Comment by caojunhua** [comment]
好吧
