### ISSUE TITLE
蓝牙读写不能正常工作

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#757]
**公司名称（必填）**
Honeywell

**是否为新产品（必填）**
"否"

**产品名称/Model（必填）**
yuemee.airmonitor.mhfd1

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 5.1]
- SDK分支: [1005]
- 相关模块:[BLE]

**现象（必填）**
蓝牙Write和Notify都失败，但是其它机型手机都可以正常使用。
具体手机型号见图

![device-2019-05-10-170446](https://user-images.githubusercontent.com/37297126/57515698-d7162080-7345-11e9-857c-2e541ef8d8be.png)

**期望（必填）**
能正常Write和Notify

**其他的上下文/日志/截图**
start connect
Bluetooth.js:1 Bluetooth bluetoothConnectionStatusChanged 22:93:F2:2D:C2:10
MainPage.js:1509 writeRTCTime error
MainPage.js:1509 readRTCTime error
MainPage.js:1509 getRealtimeDataByTimer read humidity error
MainPage.js:1509 getRealtimeDataByTimer read temperature error
MainPage.js:1509 getRealtimeDataByTimer read gas error
MainPage.js:1509 changeInterval write error
MainPage.js:1509 read firmware error 
Bluetooth.js:1 Bluetooth bluetoothConnectionStatusChanged 22:93:F2:2D:C2:10
MainPage.js:1509 bluetoothConnectionStatusChanged  true
MainPage.js:1509 00002b04-0000-1000-8000-00805f9b34fb character notify error
MainPage.js:1509 00002b07-0000-1000-8000-00805f9b34fb character notify error
MainPage.js:1509 00002b04-0000-1000-8000-00805f9b34fb character notify error
MainPage.js:1509 00002b07-0000-1000-8000-00805f9b34fb character notify error

**Comment by lvjie0519** [comment]
@EllisonYe   请提供下原生层产生的log日志，蓝牙模块，  请使用logcat， 关键字 miio-bluetooth 过滤下查看下日志。

**Comment by lvjie0519** [comment]
issue不活跃，如还存在问题，在reopen。
