### ISSUE TITLE
Service.smarthome接口range_get_open_config问题

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/miot-plugin-sdk#758]
**公司名称（必填）**
Yeelight

**是否为新产品（必填）**
"否"

**产品名称/Model（必填）**
yeelink.light.color1

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1
- SDK分支: master(10005)
- 相关模块:Service

**现象（必填）**
`/v2/home/range_get_open_config`,接口对应的新SDK方法有两个
`miot/service/smarthome.getRangeOpenConfig(params)`
`miot/service/smarthome.rangeGetOpenConfig(params) ⇒ Promise`
但是两个方法返回的数据,数组都为空,用老SDK直接调试接口是有数据的

**期望（必填）**
确认接口对应的调用方法,并准确返回值

**其他的上下文/日志/截图**
两个接口返回都为空
![image](https://user-images.githubusercontent.com/6743367/57518244-2dd22900-734b-11e9-9a08-809a9bad36b8.png)

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
检查后该接口并无问题，而且只有一个 `miot/service/smarthome.rangeGetOpenConfig(params) ⇒ Promise`  的method。建议检查下参数使用

**Comment by BaroneX** [comment]
我们使用的传参和老接口一样
参数如下
![image](https://user-images.githubusercontent.com/6743367/57601468-226f3f80-758f-11e9-87f7-d0e3561951f1.png)
换成推荐接口rangeGetOpenConfig,依然获取到的值为空,
我们和这个https://github.com/MiEcosystem/miot-plugin-sdk/issues/543
用的接口是一个,这边推荐了两个接口?
请麻烦确认下,此问题

**Comment by blockdate** [comment]
这边的问题是新旧接口使用同样的参数，但是在新接口下获取到的数据为空？

**Comment by BaroneX** [comment]
恩是的,一样的参数,老街口是有数据的

**Comment by blockdate** [comment]
把设备分享到uid:894158105下面，我这边来排查下

**Comment by blockdate** [comment]
建议检查下参数，我这边同样的参数在旧插件下获取到的数据是一样的，都是空。

同时再次确认了该方法实现代码在新旧插件下是一样的使用效果
