### ISSUE TITLE
MHPluginSDK.callSmartHomeAPI接口移植问题

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#759]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。预期48h内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。预期1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。预期1周-1月内解决

**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
米家智能门锁/lumi.lock.mcn01

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: 红米Note7 Android 9
- SDK分支: master
- 相关模块: callSmartHomeAPI

**现象（必填）**
替换和重置SE密钥的接口在新SDK没有找到对应的替换方法

- MHPluginSDK.callSmartHomeAPI('/v2/nfckey/create_se_session',  param, callback）
- MHPluginSDK.callSmartHomeAPI('/v2/nfckey/replace_se_isdkey',param, callback)
- MHPluginSDK.callSmartHomeAPI('/v2/nfckey/reset_lock_primarykey',param, callback)
- MHPluginSDK.callSmartHomeAPI('/v2/nfckey/handle_se_response', param, callback)

**期望（必填）**
希望新SDK能提供以上四个接口的替换方法

**Comment by blockdate** [comment]
参考Service.smarthome
```
Service.smarthome.createSeSession
Service.smarthome.replaceSEISDkey
Service.smarthome.resetLockPrimaryKey
Service.smarthome.handleSEResponse
```

**Comment by fengdexunmi** [comment]
@blockdate 好的，非常感谢。
