### ISSUE TITLE
刚创建好项目，然后真机调试报错

### ISSUE THREAD

**Issue by kasparovfeng** [MiEcosystem/miot-plugin-sdk#76]
刚创建好项目，然后真机调试报错  bundling failed: SyntaxError: /Users/liuxing/Desktop/米家新插件/miot-plugin-sdk/miot-sdk/service/scene.js: setter function argument must not be a rest parameter (169:4)

**Comment by laohuang88** [comment]
不好意思，已修正，请更新。
