### ISSUE TITLE
CommonSetting中 更多功能及固件升级功能 崩溃

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#760]
**公司名称（必填）**
克莱文

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
空调线控器网关/vrviot.airrtc.vrvb01xrt

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
linux
- 手机系统:[eg.Android 8.1/iOS 11.0]
andorid 8.0
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
调用CommonSetting 控件，点击更多功能 跟 固件升级功能 都报错，小米demo一样报错
更多功能 报如下错误
![image](https://user-images.githubusercontent.com/11848308/57565139-915f6380-73ea-11e9-9207-2b329a2c6aa0.png)

固件升级功能报如下错误

![image](https://user-images.githubusercontent.com/11848308/57565145-a936e780-73ea-11e9-9038-5c218ce76729.png)

**期望（必填）**
都能正常打开二级页面

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
请在>=SDK_10005分支上测试

**Comment by uSmile-Y** [comment]
已经解决了升级sdk版本
