### ISSUE TITLE
插件崩溃

### ISSUE THREAD

**Issue by LWEN999** [MiEcosystem/miot-plugin-sdk#761]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。预期48h内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。预期1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。预期1周-1月内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
贵司的简称

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否"

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
??
