### ISSUE TITLE
Main下的index.js和MainPage.js 的componentWillUnmount在退出插件时都没有执行.,在com.xiaomi.demo也测试了，同样问题。

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#762]
---
**公司名称（必填）**
云米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
非专有model问题

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 8.1和iOS 12.1.4]
- SDK分支: [10005]
- 相关模块:[]

**现象（必填）**
Main下的index.js和MainPage.js 的componentWillUnmount在退出插件时都没有执行.,在com.xiaomi.demo也测试了，同样问题。

**期望（必填）**
componentWillUnmount能正确执行

**Comment by lvjie0519** [comment]
@flingInTheSky 请说明下具体是哪个平台？Android or IOS or ALL ?

**Comment by blockdate** [comment]
这个目前是这样的，因为是将RN作为局部UI接入项目中，因此在rootView被销毁时并不会触发unmount逻辑。

建议在MainPage时在 调用 Package.exit 之前做处理操作
