### ISSUE TITLE
在插件里，如何存储大量的跟用户关联的列表数据？

### ISSUE THREAD

**Issue by laughmaker** [MiEcosystem/miot-plugin-sdk#763]
---
**公司名称（必填）**
北京猫猫狗狗

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
猫猫狗狗宠物饮水机/mmgg.feeder.petfeeder

**环境（必填）**
- 电脑操作系统: Mac
- 手机系统:iOS 12.0
- SDK分支: master
- 相关模块:Host/Service/Account

**现象（必填）**
如何存储大量的跟用户关联的列表数据？
我们有需求，在用户持续使用我们喂食机的过程中，会每天记录跟用户相关的喂食记录(时间、数量)，如何存储此类型的大量列表数据？每日的数据条数大在3-5条。

**期望（必填）**
期望能将随着使用时长，存储用户个人数据，最后形成统计。

**其他的上下文/日志/截图**

**尝试过的解决办法**
看过相关文档和接口，暂未找到解决办法。

**Comment by blockdate** [comment]
可以尝试使用 `Service.smarthome.get/setDeviceData`

**Comment by laughmaker** [comment]
您好，我看`setDeviceData(params)` 这个接口目前已标记为Deprecated了，后面会移除掉。
另外我看有另一个类似的接口，`miot/service/smarthome.batchSetDeviceDatas(params)`，但这个接口限制太多：`设置设备属性, 属性设置会在设备被删除时清空 备注： props最多20个，最多同时300个设备（目前max设备数)，属性需要以prop.s 开头`。
我刚看到，最新1010版，更新了一个新的接口`miot/service/smarthome.setUserPDData(params)`，您看是否可用呢？另外PD是什么意思？

**Comment by blockdate** [comment]
你好，检查后发现 setDeviceData 为误标，该接口可正常使用，我会及时更新文档。

setUserPDData 是用于设置用户相关信息的接口，并不适用的你的场景

**Comment by laughmaker** [comment]
好的，那我就先用这个接口测试一下，感谢解答。😄
