### ISSUE TITLE
打开米家app,插件自己消失了

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#764]
您好，
       我这边内测发现，打开米家app，之前绑定连过的插件消失了，需要重新搜索，有时候重新搜索也不一定能马上搜索的到，请问一下这个怎么解决呀。
      谢谢！

**Comment by blockdate** [comment]
请按照issue模板提问

**Comment by caojunhua** [comment]
你好，我们这个打开米家app,界面里面没有插件
![image](https://user-images.githubusercontent.com/18459414/57591855-22a71500-7566-11e9-9a48-aa20e48b3c72.png)
正常应该有这个插件的卡片的，如下图
![image](https://user-images.githubusercontent.com/18459414/57592010-ef18ba80-7566-11e9-8b4c-678f088b26a7.png)

**Comment by blockdate** [comment]
登陆的地区服务器是同一个么

**Comment by caojunhua** [comment]
> 登陆的地区服务器是同一个么
是的，没有人为主动切换过任何服务器，最多可能是在wifi环境和4g网络环境的区别。

**Comment by blockdate** [comment]
同一个账号在Android下和iOS下都存在这个问题吗

**Comment by caojunhua** [comment]
> 同一个账号在Android下和iOS下都存在这个问题吗

两个平台，都会偶尔出现这个问题，不是说每一次打开都会出现这个问题

**Comment by blockdate** [comment]
这个设备是处于开发中么，如果是开发中的设备可能会有这种情况。

**Comment by caojunhua** [comment]
> 这个设备是处于开发中么，如果是开发中的设备可能会有这种情况。

嗯，是开发中的

**Comment by blockdate** [comment]
这个咨询了后端同学之后，反馈是对于这种访问高修改少的数据会存在缓存节点上的问题，白名单用户会存在多节点访问，线上正常用户是单节点，所以白名单会有这种问题属于正常现象。
