### ISSUE TITLE
NumberSpinner兼容性问题

### ISSUE THREAD

**Issue by GuZilin** [MiEcosystem/miot-plugin-sdk#765]
**公司名称（必填）**
上海纯米电子科技有限公司

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
tokit.oven.tk32pro1

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.1
- SDK分支: master/10005/
- 相关模块/miot-sdk/ui/NumberSpinner.js

**现象（必填）**
目前NumberSpinner这个控件的参数值只支持数值类型，不支持字符串类型。
如参数为：[上管，下管，热风，冷风，上下管，上管+热风，上管+冷风，...]

**期望（必填）**
我们期望米家能提供一套同时兼容字符串类型的选择器控件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![WechatIMG1](https://user-images.githubusercontent.com/15968442/57590985-a14d8380-7561-11e9-9757-b6115031c845.jpeg)

**尝试过的解决办法**
1，我是先用的米家迁移手册里提供的 import Picker from "rmc-picker";进行处理的，但是当多个Picker同时出现时在Android上性能很差，
2，所以我们项目经理给米家发了一封邮件希望能够优化，最终米家给提供了一个NumberSpinner控件，但是这个控件的参数不兼容字符串类型，依然无法解决我们的问题。

**Comment by heigaga001** [comment]
同求，目前用的RkPicker，但是Android上会有无法设到选择项上的bug

**Comment by santcool** [comment]
我们集成了[react-native-picker](https://github.com/beefe/react-native-picker)给大家试用。iOS调试包下载地址：https://fir.im/tes5?release_id=5cde331bca87a873d20a2905。使用方法：在**miot-plugin-sdk**下执行：npm install react-native-picker --save。然后 import Picker from 'react-native-picker'
，然后按照react-native-picker一步步集成就好。如果能满足需求，我们将会将此库上线master。

**Comment by fengdexunmi** [comment]
@santcool 你好，请问下有集成了react-native-picker的Android调试包么？

**Comment by santcool** [comment]
> @santcool 你好，请问下有集成了react-native-picker的Android调试包么？

我们将会提供StringSpinner给大家使用，用法同NumberSpinner，将于SDK_10020版本发出。

**Comment by santcool** [comment]
包的地址：https://fir.im/tes5?release_id=5ce7a318959d6915fd142bd8。rn分支：SDK_10020

**Comment by santcool** [comment]
已上线SDK_10020，可以使用最新集测包测试：https://www.pgyer.com/IT8EA

**Comment by joyami** [comment]
你好， 我下载试过 还要三个问题：
1、设置单位后 安卓的不显示单位，iOS的显示
2、iOS的如果你慢慢的滚动  滚动到选中框 文字有概率不会变大或者变颜色
3、麻烦模拟官方pickerIOS新增selectedValue这个属性

**Comment by lvjie0519** [comment]
@joyami   
1、Android用的是哪个版本apk？
2、不显示单位具体是哪个控件，检查下颜色是否和背景色一致？

**Comment by joyami** [comment]
@santcool @lvjie0519    SDK版本用的是10020的  能否帮忙优化 像官网组件一样加个selectedValue 不然多个picker联动更新不怎么好弄呀  多谢多谢！！
