### ISSUE TITLE
ios，通用设置侧滑返回上一级

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#767]
**公司名称（必填）**
Philips

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
飞利浦彩泡灯/philips.light.cbulb

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[iOS 12]
- SDK分支: [master10005]
- 相关模块:[？]

**现象（必填）**
ios在通用设置侧滑返回上一页面时，会直接返回app首页。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
这个是测试版本app下为了方便出错之后能返回主页，开放了滑屏返回的限制，这个在正式app上是不会出现的，属于正常现象，请放心。
