### ISSUE TITLE
正确打包，上传后米家app无法正常打开扩展程序

### ISSUE THREAD

**Issue by uSmile-Y** [MiEcosystem/miot-plugin-sdk#768]
---
**公司名称（必填）**
克莱文

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
空调线控器网关/vrviot.airrtc.vrvb01xrt

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
linux
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android 8.0
- SDK分支: [eg.master/10000/...]
10010
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**

1、打包后，上传平台
2、打开米家app，
3、点击设备列表中的设备，
4、提示无法启动扩展程序。

米家app已经是最新5.5.15，然后换用debug的米家app版本号为 5.5.16.1 结果就能正常打开，android跟ios都是这样，请问这是什么问题啊

**期望（必填）**
在最新版的米家app上能正常打开插件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
提供下错误的具体信息，比如iOS下的错误码什么的。

看描述应该是SDKLeve与线上app不匹配

**Comment by uSmile-Y** [comment]
我的apilevel设置的就是10010 这样对吗？

**Comment by blockdate** [comment]
1. 提供下插件上传页面的插件上传记录截图
2. 提供下app端打开插件时的错误信息UI截图

**Comment by uSmile-Y** [comment]
![image](https://user-images.githubusercontent.com/11848308/57603893-6d8c5100-7595-11e9-96d0-28b2144a2b4d.png)
![image](https://user-images.githubusercontent.com/11848308/57603925-7715b900-7595-11e9-9f64-c7d28c3711d2.png)

**Comment by blockdate** [comment]
设备分享到894158105，我们排查测试一下

**Comment by uSmile-Y** [comment]
微信吗？

**Comment by blockdate** [comment]
小米账号

**Comment by uSmile-Y** [comment]
分享了 你看下呢

**Comment by blockdate** [comment]
@lvjie0519 处理中

**Comment by uSmile-Y** [comment]
这个问题 有进展了吗？

**Comment by lvjie0519** [comment]
@uSmile-Y   你使用的是哪个版本apk？ 使用最新apk试试， 如下界面是你插件的吧，我这边没发现问题。
![image](https://user-images.githubusercontent.com/22487747/57896843-50050300-7885-11e9-83c6-00bf078165a0.png)

**Comment by uSmile-Y** [comment]
你是不是用的debug版本的apk哦，现在小米应用商城里面 最新的 也就是
![image](https://user-images.githubusercontent.com/11848308/57898778-04eeee00-788d-11e9-8275-3e3e720810dc.png)
这个版本，我们就是在这个版本上打不开

**Comment by lvjie0519** [comment]
@uSmile-Y  请使用最新版本试试，5.5.15只能下载sdk为 10004版本的插件，或者去fir上下载db包进行测试。

**Comment by lvjie0519** [comment]
暂时关闭，如有问题，再reopen。
