### ISSUE TITLE
关于安全设备通信(锁类)开发模板问题

### ISSUE THREAD

**Issue by tyjh-china** [MiEcosystem/miot-plugin-sdk#770]
我们的做米家插件开发的同事，想咨询一下 安全设备通信(锁类) 有没有提供模板，
我们需要使用提供的原始接口，读写特性的方式实现？
包含通信协议和加密和解密哪里有介绍呢？

**Comment by blockdate** [comment]
@Copypeng 彭教练支持下

**Comment by blockdate** [comment]
加密通讯使用
`Bluetooth.getBluetoothLE().securityLock.encryptMessage ` 
和 
`Bluetooth.getBluetoothLE().securityLock.decryptMessage `
