### ISSUE TITLE
通用设置(CommonSetting)在魅蓝手机中显示不完整

### ISSUE THREAD

**Issue by LWEN999** [MiEcosystem/miot-plugin-sdk#771]
**公司名称（必填）**
德尔玛

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
deerma.humidifier.mjjsq

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: 魅蓝note, Android 5.1
- SDK分支: SDK_10010
- 相关模块: miot/ui/CommonSetting

**现象（必填）**
引入的CommonSetting，在魅族魅蓝手机上显示不正常，列表有显示出来，但是item title并没有显示，如截图所示。切换到英文环境，也是没有显示出来。
目前测试小米、华为及其他均正常，iOS也正常。

**期望（必填）**
正常显示列表及列表的item title

**其他的上下文/日志/截图**

![魅蓝note Android 5.1 Screenshot](https://user-images.githubusercontent.com/21273764/57600934-bfc97400-758d-11e9-9d0c-9fcc02111832.jpeg)

**尝试过的解决办法**
无

**Comment by LiuMengzhou** [comment]
@LWEN999 问题已复现，title没有指定color。其他手机默认黑色，这个沙雕手机默认白色。

**Comment by LiuMengzhou** [comment]
你点击 item，仔细看文字是可以看到的

**Comment by LiuMengzhou** [comment]
@LWEN999 问题已经定位并解决。
