### ISSUE TITLE
 NumberSpinner在滑动过程中，单位的位置发生了偏移

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#773]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)
米家智能门锁/lumi.lock.mcn01

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: 红米Note7 Android 9.0
- SDK分支: master
- 相关模块: NumberSpinner

**现象（必填）**
NumberSpinner在滑动过程中，单位的位置发生了偏移

**期望（必填）**
希望NumberSpinner在滑动过程中，单位的位置展示正确

**其他的上下文/日志/截图**
![Screenshot_2019-05-13-17-02-39-117_com xiaomi smarthome](https://user-images.githubusercontent.com/2813239/57609785-28bae700-75a2-11e9-9eb0-cdf298a2fde2.png)

![Screenshot_2019-05-13-17-03-59-678_com xiaomi smarthome](https://user-images.githubusercontent.com/2813239/57609791-2bb5d780-75a2-11e9-810b-d77aded91c7f.png)

**Comment by lvjie0519** [comment]
@fengdexunmi  
1、请问是所有手机都会出现此情况吗？
2、请粘贴一下你的代码，我这边无法复现，谢谢。

**Comment by fengdexunmi** [comment]
@lvjie0519 我们用NumberSpinner实现日期选择器，当滑动year、month的时候，我们会计算一个最大的day更新NumberSpinner的maxValue(比如2019年2月份的最大day为28)

问题：

Android平台的NumberSpinner在滑动过程中出就会触发onNumberChanged（还没有滑动到中间位置就触发了，快速滑动会一直触发），不像iOS平台的是滑动到中间的位置才会触发onNumberChanged，以及快速滑动的时候也是等到停下的时候才会触发onNumberChanged。

大致流程是这样的：

render NumberSpinner（显示完毕） => 滑动(从2019年份切到2020年份) => 2020还没有到中间位置的时候就触发了onNumberChanged =>我根据当前的year和month计算day的最大值然后更新NumberSpinner的maxValue => 导致又执行了render NumberSpinner ，然后单位的位置发生了偏移

期望：
希望Android平台的NumberSpinner的onNumberChanged触发机制可以像iOS一样

**Comment by Woody2016** [comment]
@fengdexunmi 这些技术细节，你在提交issue时就应该带上了

**Comment by fengdexunmi** [comment]
@Woody2016 好的，下次提交issue的时候会把问题和操作步骤都说明清楚

**Comment by lvjie0519** [comment]
@fengdexunmi   已完成优化，使用最新apk进行测试，谢谢。

**Comment by fengdexunmi** [comment]
@lvjie0519 谢谢回复，验证可以了
