### ISSUE TITLE
CommonSetting 的固件更新一栏可以加一个参数显示一个小红点

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/miot-plugin-sdk#775]
**公司名称（必填）**
ClearGrass

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
*

**期望（必填）**
CommonSetting 的固件更新一栏可以加一个参数显示一个小红点，像这样：
![image](https://user-images.githubusercontent.com/4001793/57666345-3455ee80-7632-11e9-82c3-392b5b9b8646.png)

**Comment by LiuMengzhou** [comment]
https://github.com/MiEcosystem/miot-plugin-sdk/commit/890728ffa7928967eeccb57c79c48fe57564a920#diff-e1335c7d3848d3134b9eb6c4ea4e4fe4R135

**Comment by codebeautiful** [comment]
@LiuMengzhou 现在看到这个功能还没有提交到master分支上，我怎么才能使用到这个功能呢

**Comment by codebeautiful** [comment]
@blockdate 你好，想问下 SDK10021版本计划什么时候可以合并到master分支上，现在就差这个功能了

**Comment by zanetti4** [comment]
@codebeautiful 现在已经合并了，请进行测试
