### ISSUE TITLE
iOS米家APP主程序206 beta版本侧滑返回异常

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#776]
**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [master]
- 相关模块:[米家APP主程序 https://fir.im/mijiadevelopment]

**现象（必填）**
**在插件里侧滑返回的时候异常，会一下子直接返回到首页，且侧滑的时候只显示插件里的最上两个页面，原来186，196版本正常。使用iPhone 6s ,iphone 8p,iphone xs试过都一样。
在主程序中操作是正常的，只有进插件才会真有。**

**期望（必填）**
**插件内能正常侧滑返回。**

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46777658/57668986-e9d96f80-763b-11e9-800c-2a2cf8fae1fb.png)

**之前的196，186版本正常如下：**

![image](https://user-images.githubusercontent.com/46777658/57669074-2f963800-763c-11e9-9a44-2029b4f034ed.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
这个跟插件的代码没关系，仅在测试下会出现，这边今天会发一个修复版本。
