### ISSUE TITLE
Android 定时开关➡️时间段定时➡️重复执行dialog背景有横线

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#778]
**公司名称（必填）**
飞慧智能照明

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米家飞利浦读写台灯/philips.light.rwread

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 8.1]

**现象（必填）**
背景多了条横线

**期望（必填）**
背景状态正常

**其他的上下文/日志/截图**

<img width="364" alt="image" src="https://user-images.githubusercontent.com/18681867/57742132-77779680-76f2-11e9-91c6-4fe682750401.png">

**Comment by lvjie0519** [comment]
@xuanxuandaoren   请问所有手机都会有白色横线吗？  我这边无法复现， 请使用最新apk试试。

**Comment by xuanxuandaoren** [comment]
@lvjie0519  小米5就有

**Comment by lvjie0519** [comment]
@xuanxuandaoren   你使用的是最新apk吗？  或者使用线上版本试试？  我这边用小米5 没发现问题。

**Comment by xuanxuandaoren** [comment]
@lvjie0519 最新版本已不存在
