### ISSUE TITLE
Device.parentDevice为undefined

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#779]
公司名称（必填）
绿米

是否为新产品（必填）
否

产品名称/Model（必填）
米家智能插座/lumi.plug.v1
环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8.1/iOS 12.2]
SDK分支: [10011]
相关模块:[Device]
现象（必填）
1. Device.parentDevice为undefined

期望（必填）
可以获得Device的父设备

其他的上下文/日志/截图

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码❗️

**Comment by zanetti4** [comment]
请把 米家智能插座/lumi.plug.v1 分享给我，我的帐号：894158105，我进行调试。

**Comment by xyliusun** [comment]
你好，已经共享了米家多功能网关给你，网关下有米家智能插座

**Comment by zanetti4** [comment]
@blockdate 此问题可以复现，应该是原生的问题，请你进行调试。

**Comment by xyliusun** [comment]
请问这个问题的进度怎么样了啊？

**Comment by blockdate** [comment]
正在处理中。

**Comment by blockdate** [comment]
iOS 更新 app至最新的测试版，SDK更新至10020最新，验证问题是否解决

**Comment by xyliusun** [comment]
问题解决了，谢谢
