### ISSUE TITLE
getDeviceData 返回的数据格式不一致

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#780]
---
**公司名称（必填）**
Honyewell

**是否为新产品（必填）**
"否"

**产品名称/Model（必填）**
yuemee.airmonitor.mhfd1

**环境（必填）**
- 电脑操作系统:[Mac OS/]
- 手机系统:[Vivo Android 5.1.1] 见附件
- SDK分支: [10005]
- 相关模块:[Service]

**现象（必填）**
Service.smarthome.getDeviceDat在Vivo手机上返回的response直接是result，没有code。
正常返回
{
code:0,
result:[...]
}

VIVO上返回
[...]

**期望（必填）**
1、是否不同Adnroid手机系统的返回数据格式不一致，需要特殊处理
2、若要求一致，请确认下具体原因和正确的返回格式

**其他的上下文/日志/截图**

![device-2019-05-10-170446](https://user-images.githubusercontent.com/37297126/57752323-58d9c580-771b-11e9-8844-ac20083a11e1.png)

**Comment by lvjie0519** [comment]
1、不同的Android手机返回数据格式不一致吗？
2、应该所有Android都只会返回result部分内容吧？

**Comment by lvjie0519** [comment]
我们测试，数据格式是一致的，暂时关闭，如有问题再reopen，谢谢。
