### ISSUE TITLE
进入通用设置页面空白，应用卡死

### ISSUE THREAD

**Issue by LWEN999** [MiEcosystem/miot-plugin-sdk#783]
**公司名称（必填）**
德尔玛

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
`deerma.humidifier.mjjsq`

**环境（必填）**
- 电脑操作系统: **macOS**
- 手机系统: **Android**
- SDK分支: **master(SDK_10010)**
- 相关模块: `miot/ui/CommonSetting`
- 米家APP版本：`5.5.15`

**现象（必填）**

我们设置页面用了SDK_10010的`CommonSetting`组件，页面也基本是demo的代码。
 - 米家`5.5.15`的正式版本：进入到设置页面一片空白，点击无响应，后退无响应，APP呈现卡死状态，只能强制杀掉，**此现象在安卓手机必现**，iOS正常。如图所示。
- 升级米家到`5.5.20`正式版（灰度升级）：能正常进入设置页，设置项正常显示，点击正常，iOS正常。

**期望（必填）**
因为我们打算这几天提交审核，而目前商店版本还是`5.5.15`，审核用这个版本的话，现在提交肯定会被拒的。
所以想请教一下，导致上面所说现象的原因是APP问题还是我们插件问题？

**其他的上下文/日志/截图**

5.5.15问题版本录屏：
![问题版本录屏](https://user-images.githubusercontent.com/21273764/57754891-15cf2080-7722-11e9-8653-1a0d2b7c0930.gif)

**尝试过的解决办法**

**不要贴大段代码❗️**

以下是我们设置页面布局代码：
```javascript
export default class Setting extends React.Component {

  static navigationOptions = ({ navigation }) => {
    return {
      header:
        <TitleBar
          type='dark'
          title={strings.setting}
          style={{ backgroundColor: '#fff' }}
          onPressLeft={_ => navigation.goBack()}
        />
    };
  };

  render() {
    const { first_options, second_options } = SETTING_KEYS;
    // 显示部分一级菜单项
    const firstOptions = [
      first_options.SHARE,
      first_options.IFTTT,
      first_options.FIRMWARE_UPGRADE
    ]
    // 显示部分二级菜单项
    const secondOptions = [
      second_options.AUTO_UPGRADE,
      // second_options.TIMEZONE,
    ]
    // 显示固件升级二级菜单
    const extraOptions = {
      // showUpgrade: true,
      licenseUrl: require('../Resources/html/license_zh.html'),
      policyUrl: require('../Resources/html/privacy_zh.html'),
      deleteDeviceMessage: '真的要删除？你不再考虑考虑？'
    }

    return (
      <View style={styles.container}>
        <StatusBar barStyle='dark-content' />
        <Separator />
        <ScrollView
          showsVerticalScrollIndicator={false}>
          <View style={styles.blank} />
          <CommonSetting
            navigation={this.props.navigation}
            firstOptions={firstOptions}
            secondOptions={secondOptions}
            extraOptions={extraOptions}
          />
          <View style={{ height: 20 }} />
        </ScrollView>
      </View>
    );
  }
}
```

**Comment by blockdate** [comment]
这个apk版本系 SDK 10005， commonSetting在10010下才开始支持(Android灰度中)，问下你的插件打包level是多少。

**Comment by LWEN999** [comment]
@blockdate 打包的SDK level是10010

**Comment by LiuMengzhou** [comment]
共享这个设备给`894158105`(test_nick_name)

**Comment by LiuMengzhou** [comment]
@LWEN999

**Comment by LWEN999** [comment]
已经共享了，麻烦看下

**Comment by LiuMengzhou** [comment]
问题已经定位并解决。
本来按照常理来说，5.5.15的安卓米家（内置SDK_10005）应该是不能拉取到你打包的插件（SDK_10010）
不过 bug 已经 fixed，SDK也已经发布了

**Comment by LWEN999** [comment]
> 问题已经定位并解决。
> 本来按照常理来说，5.5.15的安卓米家（内置SDK_10005）应该是不能拉取到你打包的插件（SDK_10010）
> 不过 bug 已经 fixed，SDK也已经发布了

@LiuMengzhou  感谢，请问修复的分支是哪个？

**Comment by LiuMengzhou** [comment]
@LWEN999 修复的分支是10005，你就按照你之前的操作，再试一次就行。
首次进入插件，问题还是会复现。退出插件，清除缓存之后重进就没问题了。
