### ISSUE TITLE
一次性密码错乱问题

### ISSUE THREAD

**Issue by nevermore-jia** [MiEcosystem/miot-plugin-sdk#784]
---
**公司名称（必填）**
深圳市优点科技

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
ydhome.lock.m2silver

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.4.1]
- SDK分支: [10010]
- 相关模块:[Host.ui]

**现象（必填）**
用户小米账号里,绑定多把门锁,调用这个Host.ui.openOneTimePassword() A打开一次性密码界面.点击生成的一次性密码,在B门锁的一次性密码列表中会显示A锁生成的. 同样B锁生成的A锁也会显示. 显示错乱

**期望（必填）**
A锁调用Host.ui.openOneTimePassword()后,只会显示A锁自己生成的密码

**不要贴大段代码❗️**

**Comment by santcool** [comment]
请问这个问题还存在吗？如果存在，请回复我并分享两个锁到894158105.如果不存在，请关闭issue

**Comment by santcool** [comment]
问题不活跃，暂时关闭，若有需求，重开一个issue
