### ISSUE TITLE
多个国家下无法进入插件主页

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#786]
中国一切正常。

切换至其他国家，如英国，西班牙，芬兰，意大利，俄罗斯，波兰，法国，葡萄牙，无法进入插件主页。

model: ninebot.scooter.v2 || ninebot.scooter.v1
几天前已经通过了米家的插件上线验收流程。

现象1（iOS）：连接车辆时，出现该图提示框，但是车辆上面显示的蓝牙是已经连接的状态，进不到车辆主页
![411557822825_ pic_hd](https://user-images.githubusercontent.com/1590420/57845650-fd840200-7804-11e9-83db-a0a15aa300ce.jpg)

现象2（Android）：添加车辆的过程中出现如图所示，但是实际车辆上面的蓝牙状态是已连接的状态
![421557822830_ pic_hd](https://user-images.githubusercontent.com/1590420/57845718-24423880-7805-11e9-924e-498f85362a13.jpg)

现象3（iOS）：连接车辆时该图中的进度条一直没反应
![401557822817_ pic_hd](https://user-images.githubusercontent.com/1590420/57845733-299f8300-7805-11e9-9141-8b312f3a0898.jpg)

现象4（Android）
![431557822835_ pic_hd](https://user-images.githubusercontent.com/1590420/57845756-302dfa80-7805-11e9-9c87-ec18bc4de84d.jpg)

**Comment by santcool** [comment]
第一幅图和第二幅图图片都看不清楚，麻烦给更清晰一些的图片。第一张图片，需要提示语后面的code，第二张图片，需要打x的那句话

**Comment by dan-huang** [comment]
@santcool 更新了，麻烦再看一下

**Comment by dan-huang** [comment]
@blockdate @Woody2016  
可以帮忙加急看一下吗- - 这个影响了插件的上线流程，米家审核人员说不能上线。

**Comment by blockdate** [comment]
设备能否分享到 894158105 的小米账号下面

**Comment by dan-huang** [comment]
共享了三个 @blockdate

**Comment by blockdate** [comment]
说明下设备名和国家区域吧，我这边好查看

**Comment by dan-huang** [comment]
名称：米家滑板车 / 米家滑板车Pro

国家：英国，西班牙，芬兰，意大利，俄罗斯，波兰，法国，葡萄牙

中国是正常的。 @blockdate

**Comment by dan-huang** [comment]
@blockdate @Woody2016 

两位下午好～请问下这个事情有进展吗^_^

**Comment by Woody2016** [comment]
插件下载这块，国外服务器之前是米家后台有bug，已经修复
所以麻烦去 米家->我的->设置->清理缓存 然后再进插件试试

**Comment by dan-huang** [comment]
好的。我们试一下之后在这里反馈

**Comment by dan-huang** [comment]
已解决
