### ISSUE TITLE
关于连接蓝牙设备出现device not found 报错问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#787]
您好，
       我这边有个问题，就是连接附近的蓝牙设备，已经绑定过。
       正常情况：
      进入插件，连接成功；退出插件，断开连接。多次操作都正常。
       异常情况：
       进入插件，连接失败，看打印信息报错：device not found。
       然后或许过一段时间，不做任何操作，再连接，又可以连接成功，或者把手机蓝牙重新开启，也可以连接成功。
       那么请问一下，这种连接异常应该怎么处理？谢谢！

**Comment by blockdate** [comment]
常见问题，你的蓝牙设备处于连接状态，再尝试链接的时候就会出现这个问题。

**Comment by caojunhua** [comment]
> 常见问题，你的蓝牙设备处于连接状态，再尝试链接的时候就会出现这个问题。

按照正常情况，我退出了就断开了设备，为什么蓝牙设备处于连接状态呢？

**Comment by blockdate** [comment]
这时候查看下系统蓝牙，可能没有完全断开。此时可以尝试retrievedxxxxx获取已连接的蓝牙设备，然后再断开

**Comment by blockdate** [comment]
REF #738
