### ISSUE TITLE
关于搜索蓝牙设备，搜索不到的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#788]
您好，
      假设周围半米范围内有10个设备，点击米家app的蓝牙搜索按钮，有可能搜到10个，有可能搜到8个。
      在周围只有1个设备的时候，有时候可以搜到，有时候搜索不到。
     请问这种情况，应该怎么解决呢。谢谢！
![image](https://user-images.githubusercontent.com/18459414/57821663-e5d85980-77c3-11e9-92f2-d2487d4a3a18.png)
![image](https://user-images.githubusercontent.com/18459414/57821669-e8d34a00-77c3-11e9-9e47-b42ecd45ae98.png)
![image](https://user-images.githubusercontent.com/18459414/57821672-ec66d100-77c3-11e9-9024-cc4aaaf15190.png)

**Comment by blockdate** [comment]
确认下设备处于待连接状态
