### ISSUE TITLE
智能化滚轴显示问题

### ISSUE THREAD

**Issue by peaceblues** [MiEcosystem/miot-plugin-sdk#789]
**公司名称（必填）**
Honeywell

**是否为新产品（必填）**
是
**产品名称/Model（必填）**
霍尼韦尔甲醛监测仪/yuemee.airmonitor.mhfd1

**环境（必填）**
- 手机系统: Android 6.0, IOS 12.2

**现象（必填）**
智能化滚轴后台配置如下：
“max_val": 1.5,
"min_val": 0.01,
"interval": 0.01,
"degree": "mg/m^3",
"default_val":0.1
然而在米家app->"智能" -> “我的” -> + ->选择”霍尼韦尔甲醛监测仪“ -> "高于指定甲醛浓度“后出现的滚轴，问题如下：
IOS，只有0/1两档
Android，量程0.0~1.5，0.0有5档，0.1到1.5每个都有10档，但是这十档均未显示0.00~0.09。

**期望（必填）**
米家app按照后台配置显示。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/16602129/57821666-e7098680-77c3-11e9-8775-7e5cd5f818a9.png)
![image](https://user-images.githubusercontent.com/16602129/57821726-289a3180-77c4-11e9-918a-af3699196be4.png)

**尝试过的解决办法**
咨询miot研发人员，定位米家app问题

**Comment by santcool** [comment]
<NumberSpinner
                    style={{ width: 300, height: 200 }}
                    maxValue={1.5}
                    minValue={0.01}
                    interval={0.01}
                    defaultValue={0.1}
                    valueFormat={"%.2f"}
                    unit={"km"}
                    onNumberChanged={data => {
                        console.log(`newValue:${data.newValue},oldValue:${data.oldValue}`);
                    }} />

**Comment by santcool** [comment]
ios和andriod这么处理均没问题
