### ISSUE TITLE
打包上传后，图片UI不一致

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#792]
**公司名称（必填）**
Philips

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
飞利浦彩泡灯/philips.light.cbulb

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[iOS 12]
- SDK分支: [master/10010]
- 相关模块:[？]

**现象（必填）**
打包上传后的ui图与本地调试的ui图不一致（ios）,在Android平台上是没问题的。
如图为本地debug版本与线上版本。
![微信图片编辑_20190516145503](https://user-images.githubusercontent.com/5188922/57833095-d967f700-77eb-11e9-9082-6d18a0dedcba.jpg)
![微信图片编辑_20190516145524](https://user-images.githubusercontent.com/5188922/57833117-e84ea980-77eb-11e9-8ba9-9fe58ae9f38e.jpg)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
图片设置 resizeMode:contain，这个明显是图片放大了

**Comment by LiuMengzhou** [comment]
> 图片设置 resizeMode:contain，这个明显是图片放大了

@mirse @santcool 
是的，或者 ‘center’

**Comment by mirse** [comment]
使用了 resizeMode:'center'， 但是为什么在本地debug时不会出现这个问题? @LiuMengzhou  @santcool

**Comment by mirse** [comment]
不使用 resizeMode:'center' 这个属性，在本地debug调试时，在部分安卓手机上会出现图片边缘显示不出来的问题（例如红米4x）
如图：
使用 resizeMode:'center' 
![image](https://user-images.githubusercontent.com/5188922/57905276-886a0880-78a8-11e9-80a4-7a1fec5ff0f1.png)

不设置 resizeMode属性
![image](https://user-images.githubusercontent.com/5188922/57905307-9fa8f600-78a8-11e9-9f08-f7382466423e.png)

**Comment by LiuMengzhou** [comment]
@mirse 你可以尝试把 `Android` 尺寸多设置1-3个值
```js
const ICON_SIZE = Platform.select({ android: 26, ios: 24 });
<Image
  style={{ width: ICON_SIZE, height: ICON_SIZE }}
  resizeMode='center'
  source={requrie('...')}
/>
```

**Comment by LiuMengzhou** [comment]
个人经验，仅供参考。It works for me.

**Comment by mirse** [comment]
@LiuMengzhou  
resizeMode='center' 属性不能用吗？  刚刚试了多加/减尺寸还是会出现这种情况

**Comment by LiuMengzhou** [comment]
看看你的图片尺寸还有你的代码

**Comment by mirse** [comment]
@LiuMengzhou  
留个V或者邮箱？

**Comment by LiuMengzhou** [comment]
就发在这就行

**Comment by mirse** [comment]
图片尺寸180x180
//图片样式（ImageButton）
` 
featureBtnStyle: {
        width: 60 * MHGlobal.ratio,
        height: 60 * MHGlobal.ratio,
        //resizeMode:'center'
    },
`
//外层view样式（Animated.View 动画效果）
`
featureItemStyle: {
        width: 60 * MHGlobal.ratio,
        position: 'absolute',
        top: 0,
    },
`

**Comment by LiuMengzhou** [comment]
` MHGlobal.ratio`这是啥？图片尺寸180 * 180 如果是3x图的话，就写
```
width: 60, height: 60,
```
就行

**Comment by mirse** [comment]
`
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
const ratio = width/375;
`

ratio是屏幕宽度/设计稿宽度的系数

**Comment by LiuMengzhou** [comment]
> ` MHGlobal.ratio`这是啥？图片尺寸180 * 180 如果是3x图的话，就写
> 
> ```
> width: 60, height: 60,
> ```
> 
> 就行

@mirse 按照这么写试试吧

**Comment by mirse** [comment]
成这样了 @LiuMengzhou 
![image](https://user-images.githubusercontent.com/5188922/57917795-0ab5f500-78c8-11e9-8b9f-e2d5e5670cfe.png)

**Comment by zanetti4** [comment]
请把这一排图标的相关代码和图片发给我，我进行测试。intermilan4@aliyun.com

**Comment by mirse** [comment]
> 请把这一排图标的相关代码和图片发给我，我进行测试。[intermilan4@aliyun.com](mailto:intermilan4@aliyun.com)

代码已发送

**Comment by zanetti4** [comment]
我回复了邮件，附件是我测试的代码和图片。
我对一些图片名称做了修改，180x180的图片名称里增加了@3x，引用图片时还是用的原本图片名（colorOff.png）。
在给 ImageButton 设置尺寸时，没有使用 ratio。
在 ios, android 测试都没有出现图片显示不全的问题。你可以试一下，看能否解决。

**Comment by mirse** [comment]
> 我回复了邮件，附件是我测试的代码和图片。
> 我对一些图片名称做了修改，180x180的图片名称里增加了@3X，引用图片时还是用的原本图片名（colorOff.png）。
> 在给 ImageButton 设置尺寸时，没有使用 ratio。
> 在 ios, android 测试都没有出现图片显示不全的问题。你可以试一下，看能否解决。

关于代码的测试分析已经邮箱回复，帮忙在看一下

**Comment by mirse** [comment]
刚刚又在线上试了下，去除resizeMode属性，目前测试了下在红米4x上会出现图片失真问题

![image](https://user-images.githubusercontent.com/5188922/58391295-dda3d800-8067-11e9-95a2-9fcf875248ab.png)
@LiuMengzhou @zanetti4

**Comment by mirse** [comment]
@LiuMengzhou  @zanetti4
