### ISSUE TITLE
SingleChoiceDialog在iPhone 6 Plus上显示紊乱卡顿

### ISSUE THREAD

**Issue by febird** [MiEcosystem/miot-plugin-sdk#793]
**公司名称（必填）**
领普科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
linp.doorbell.g03

**环境（必填）**
- 电脑操作系统:[NA]
- 手机系统:[iOS 11.2.1]
- SDK分支: [master/10005/...]
- 相关模块:[UI]

**现象（必填）**
提交验收测试发现兼容性问题，表现见视频。
目前仅在iPhone6 plus，IOS11.2.1、最新米家软件
（空间列表内容36条左右）
链接:https://pan.baidu.com/s/1TpH2BpPc1c_lIN4QCKCCHA 提取码:mn6i 复制这段内容后打开百度网盘手机App，操作更方便哦

**期望（必填）**
不卡顿。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
将设备分享至894158105，我这边尝试复现下。

**Comment by febird** [comment]
@blockdate 已分享

**Comment by santcool** [comment]
问题已解决，更新了native代码，稍后我将在此处给你们提供一个包。

**Comment by blockdate** [comment]
更新fir上最新的测试app，同时该修复在下周的版本提交审核
