### ISSUE TITLE
iOS本地调试扩展程序，加载项目index.ios.js报错

### ISSUE THREAD

**Issue by wenlai** [MiEcosystem/miot-plugin-sdk#794]
**公司名称（必填）**
佛山市星曼信息科技有限公司

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
hith.foot_bath.q2

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统:iOS 12.2
- SDK分支: [master]
- 相关模块: 进入插件页保存

**现象（必填）**
本地调试扩展程序，从米家APP卡片页点击进入扩展程序页面，报错：
Failed to load bundle, EPERM operation not permitted

**期望（必填）**
希望能正常加载渲染index.ios.js文件，正常显示插件页

**尝试过的解决办法**
把调试选项的“选中-H5/取消-React,能正常加载index.html页面”

![1](https://user-images.githubusercontent.com/7650650/57843863-9022a200-7801-11e9-860a-2288fde120ef.jpeg)
![2](https://user-images.githubusercontent.com/7650650/57843875-93b62900-7801-11e9-92ad-b7e8b3afbdcc.jpeg)

**Comment by santcool** [comment]
去github下载最新的ipa，并拉去新代码，检查电脑npm服务器地址和路径，按照iot平台的[开发简介](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E5%BC%80%E5%8F%91%E7%AE%80%E4%BB%8B)一步步检查。
