### ISSUE TITLE
相同账户，苹果手机可以分享，安卓不能分享设备

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#795]
**公司名称（必填）小吉科技
贵司的简称    
小吉
**是否为新产品（必填）**   是
若是旧框架插件迁移相关，请填"否"

**产品名称/Model（必填）**    新品/com.minij.jumpv8

**环境（必填）Android手机
- 电脑操作系统:[eg.Windows/Mac OS]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10005/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
相同账户，苹果手机可以分享，安卓不能分享。

**期望（必填）**
Android/ios都能分享设备

**尝试过的解决办法**

**Comment by lvjie0519** [comment]
@hao0000  
1、请具体说明一下，Android不能分享是插件内调用api不能分享还是米家首页设备列表长按不能分享？
2、请确定下米家首页设备列表长按是否能够分享？

**Comment by lvjie0519** [comment]
暂时关闭，有问题再reopen。
