### ISSUE TITLE
miot-sdk怎么支持mobx？

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#797]
最新版本的rn安装好使用es6装饰器的依赖，由于miot-sdk版本较低一直弄不好，能给予技术支持吗？

**Comment by devYoungyang** [comment]
什么意思？

**Comment by LiuMengzhou** [comment]
1. 按照issue 模版提问
2. 问题描述更详细点，比如：
`使用es6装饰器的依赖`是什么？
`miot-sdk版本较低` 什么版本低？React version？React native version？还是SDK的LEVEL？

**Comment by devYoungyang** [comment]
react-native版本低，在使用mobx不知如何配置

**Comment by devYoungyang** [comment]
miot-sdk是对rn0.54.4的封装，babel是6.xx 。而使用mobx4需要babel版本是7.xx ，

**Comment by devYoungyang** [comment]
error:com.mijia.demo/index.ios.js:requires babel '7.0.0'. but was loaded with '6.26.3'

**Comment by zanetti4** [comment]
我看了一下 [React Native 中文更新日志](https://bbs.reactnative.cn/topic/6094/0-56-react-native-%E4%B8%AD%E6%96%87%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)，0.56 使用 babel 7。所以你能否使用较老的 mobx，以降低对 babel 的版本要求。

**Comment by devYoungyang** [comment]
大兄弟啊，我在0.54.4的RN工程里配置成功了，同样的方法我在miot-sdk里怎么配不成功，这就很尴尬了，你们的miot-sdk里可以内置一下吗？

**Comment by blockdate** [comment]
这边检查了下，0.54.4  的react-native 依赖babel版本为 6.26，我们这边并不能贸然升级。以后如果有更新，我们会通知。

同时，我们这边本地实验了下，不使用注解也可以正常使用mobx，如果你的需求比较强烈，暂时建议你使用非注解的方式。
