### ISSUE TITLE
缺少"/v2/device/bledevice_info"对应接口

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#798]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
小米米家智能门锁 lumi.lock.mcn01

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
缺失一个上报蓝牙设备当前固件版本(上报后，才能获取到必经版本)的接口，原来是：

`/v2/device/bledevice_info`，

原来iOS的RN旧插件使用如下：

`const param = {
      did: Device.deviceID,
      fw_ver: currVer
    };
    MHPluginSDK.callSmartHomeAPI('/v2/device/bledevice_info', param, (response) => {
       
    });`

**期望（必填）**
希望提供这个接口

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by WeizhiKong** [comment]
@blockdate 你好，问下这个接口什么时候可以提供

**Comment by blockdate** [comment]
SDK 10020 中已更新 Service.smarthome.reportBLEDeviceInfo()

**Comment by WeizhiKong** [comment]
@blockdate 麻烦看下，接口使用出现异常
![image](https://user-images.githubusercontent.com/46777658/59183967-b4bf2f00-8b9f-11e9-8989-379a76ab7e78.png)

**Comment by blockdate** [comment]
result为null也表示成功的意思是吗。

**Comment by WeizhiKong** [comment]
看着回调结果没毛病，但为啥走catch异常不走then

**Comment by blockdate** [comment]
默认需要返回 result才算成功，这个接口可能比较奇葩，我这边调整下SDK吧。

**Comment by WeizhiKong** [comment]
@blockdate 问下这个可以什么时候提供新的SDK
