### ISSUE TITLE
暂未在新SDK中找到与旧SDK中firmwareNotCheckUpdate相对应的方法

### ISSUE THREAD

**Issue by TheWalkingDead2** [MiEcosystem/miot-plugin-sdk#8]
https://github.com/MiEcosystem/ios-rn-sdk/blob/master/MiHomePluginSDK/docs/MHPluginSDK.md 有firmwareNotCheckUpdate此方法的描述

**Comment by blockdate** [comment]
参考 Device.getDeviceWifi().setFirmwareNotCheckUpdate(bool)
