### ISSUE TITLE
IPHONE X 用开发者账号登录app之后，无法进入开发者模式。

### ISSUE THREAD

**Issue by nealelin** [MiEcosystem/miot-plugin-sdk#80]
1.	下载后IOS IPA后, 用小米开发者账号登录app之后，无法进入开发者模式。要如何修改设置呢?
2.	我的手机型号信息截图如下:
![ios](https://user-images.githubusercontent.com/44886762/49266415-1d12b280-f491-11e8-8cfd-ce82df08f228.png)

**Comment by nealelin** [comment]
是的,權限設定如下:
![image](https://user-images.githubusercontent.com/44886762/49272062-23ae2380-f4ab-11e8-992e-bb8eecb3076c.png)

**Comment by LiuMengzhou** [comment]
@nealelin 你app登录的是大陆地区还是台湾地区，我看你的字体是繁体。
我想确认一下是不是app的地区问题。

**Comment by nealelin** [comment]
地区是设”大陆”,不是APP问题,同一手机,我改用原始拥有值账号登入就正常了
我移除再装,还是没用

**Comment by edwardair** [comment]
那就是你账户的权限有问题，记得是需要向米家方面申请，让他们操作的，旧SDK文档里有提到

**Comment by nealelin** [comment]
> 那就是你账户的权限有问题，记得是需要向米家方面申请，让他们操作的，旧SDK文档里有提到

有申请过,且己被认证才能加入开发群中,ANDROID用的好好的,就IOS有问题
还是有什么要再特别申请的吗?

可否贴个旧文件连结,让我参考
