### ISSUE TITLE
CommonSetting 撤销授权的文字Android和iOS端有差异

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#801]
验收部门提的反馈，图片如下：
![WechatIMG1](https://user-images.githubusercontent.com/8743690/57932030-7ad67200-78ec-11e9-8ba7-039d5626fa23.jpeg)

**Comment by Monkey0803** [comment]
![05C06D4AD04EC88C33AD295A81207497](https://user-images.githubusercontent.com/11564933/57935916-6cd91f00-78f5-11e9-9d98-b247e8240f79.png)

**Comment by blockdate** [comment]
已让产品去推动相关同学修改了。

**Comment by blockdate** [comment]
可以向验收人员说明下这个授权页的内容部分不是由插件控制的。

**Comment by blockdate** [comment]
native 端已开始排期处理，暂时关闭。
