### ISSUE TITLE
新框架UI样式问题

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#802]
**公司名称（必填）**
乐秀

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
leshow.feater.bs1

**环境（必填）**
mac
ios 11.0
10005
ui

**现象（必填）**
![踢脚线-上划](https://user-images.githubusercontent.com/17919773/57962604-7c835280-794b-11e9-9dc7-cfd8f3eef5c7.png)
![踢脚线-开机-按钮变化1](https://user-images.githubusercontent.com/17919773/57962605-7d1be900-794b-11e9-825d-6b946007d591.png)

**期望（必填）**
1.上图红框圈起来的样式是否可以实现？一个定制slider，一个导航栏上显示的温度用两种字体。关于slider，设置了minimumTrackImage和maximumTrackImage无效。

2.另外还有个问题，新框架的containerView是在导航栏之下，如果想将一张背景图设置成全屏幕显示，如图2所示，需要怎么设置？

**Comment by LiuMengzhou** [comment]
@sikaiven 
1. 通用`slider`设置`minimumTrackImage`和`maximumTrackImage`也不能满足设计需求。而且这两个属性是iOS特有的，不通用。对于这种定制`slider`，`miot-sdk`将提供通用的UI组件，目前还在排期尚未开发。你也可以动手自己实现（不难）。
2. 在导航栏上显示一个比较大的文字，比如图中的温度，看起来并不符合插件首页UI导航栏规范，你可以找设计师确认一下。如果确认设计无误，只能由自己实现（不难）。`miot-sdk`提供的通用`TitleBar`无法设置这种样式。
3. 想要设置全屏背景图，有两种方案可以尝试：
- 设置`TitleBar`的背景色为透明
- 屏蔽默认导航，自己实现一个导航栏UI（不难）
