### ISSUE TITLE
关于米家正式版和beta版连接蓝牙的问题

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#803]
您好，
       我这边用测试版米家连接蓝牙芯片，情况是这样的：
       进入插件，连接正常；退出插件，断开正常。
       用正式版的米家，情况是这样的：
       首次启动米家app,进入插件，连接正常；退出插件，再次连接，报错连接失败，返回的错误码是100；需要把米家app整个应用彻底退出，再次连接，才可以连接。
       在测试版的时候，通过打印信息，只遇到过报错-7，意思device not found;但是还没有遇到过报错100
       请问这个报错100是什么意思呢？应该怎么解决呢?谢谢！

**Comment by blockdate** [comment]
在打印-7 时，检查系统蓝牙是否还和设备处于连接中。

**Comment by caojunhua** [comment]
> 在打印-7 时，检查系统蓝牙是否还和设备处于连接中。

您好，打印-7的问题，我这边已经解决了，目前就是打印100的错误码，我不知道是什么意思，不知道怎么解决，谢谢！

**Comment by blockdate** [comment]
100 表示蓝牙正处于连接中

**Comment by zanetti4** [comment]
请问使用的手机系统和相关模块是什么？
