### ISSUE TITLE
定时器页面回调

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#804]
**公司名称（必填）**
乐秀

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
leshow.heater.bs1

**环境（必填）**
mac os
ios 11.0
10005
ui

**现象（必填）**
openTimerSettingPageWithVariousTypeParams(onMethod, onParam, offMethod, offParam)

**期望（必填）**
1.调用以上接口进入定时页面，设置定时后，是否有回调接口，获取到设置的定时时间段？

2.是否有接口可以更改定时页面switch开关的颜色，比如将默认的绿色改为红色？

**Comment by blockdate** [comment]
1. 目前并没有直接的回调告诉你删除|增加|修改了哪些，可以通过Scene相关的接口自行查询。

2.目前这个页面不支持UI定制修改

**Comment by sikaiven** [comment]
@blockdate 能否告知下，获取定时数组的接口的详细用法？
Device.loadTimerScenes().then((sceneArr) => {
      Alert.alert(JSON.stringify(sceneArr));
})
我通过以上的接口获取，返回的是'{[]}'空json。
