### ISSUE TITLE
设备配网失败的相关疑问

### ISSUE THREAD

**Issue by heigaga001** [MiEcosystem/miot-plugin-sdk#805]
**公司名称（必填）**
追觅科技

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
扫拖一体机/dreame.vacuum.mc1808

**现象（必填）**
设备在配网时，又出现过以下失败的现象
1、APP显示配网失败，返回设备列表后，设备已存在。
2、APP显示配网成功，返回设备列表后，偶现设备不存在。
3、Android APP端扫描不到机器热点，IOS 手机WiFi热点可看到机器热点。（测试手机型号：红米7，小米8，小米9SE）
**期望（必填）**
能够尽量降低配网失败的概率

**Comment by dingshaoran** [comment]
问题2，配网过程中会请求 device_new接口，配网完成会刷新首页设备列表 device_list。请过滤 logcat 关键词 MIIO ,看一下两个接口是不是都有你的设备的 did。
问题3，如果扫不到机器热点请查看手机设置中的 wifi 列表是不是有热点 “dreame_vacuum_mc1808_miap_mac后四位 ” 由于手机系统扫描 wifi 的差异有可能发现有延迟

**Comment by dingshaoran** [comment]
如果不能定位问题

**Comment by dingshaoran** [comment]
如果不能自己定位问题，请附上 logcat 的所有 log。我们查一下
