### ISSUE TITLE
Animated.Image本地调试正常，线上的包不显示

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#807]
公司名称（必填）
江苏紫米电子技术有限公司

是否为新产品（必填）
否

产品名称/Model（必填）
小米小爱智能闹钟/zimi.clock.myk01

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10000/]
相关模块:[Animated.Image]

现象（必填）

android手机，凡是用到 Animated.Image（动态缩放宽、高）的地方, 主要是指气泡：

1，本地服务器调试正常，线上的就包都有问题；

2，换成静态Image有小问题，图片虚边，断断续续的 ；

3，IOS都正常 。

刘梦舟猜测，可能打包出错，请检查，谢谢 ！

![微信图片_20190520100238](https://user-images.githubusercontent.com/44045029/57992479-f13ec400-7ae6-11e9-8eea-8fd8a261e070.png)

**Comment by lvjie0519** [comment]
@Banjiemin   我这边排期解决，预计下周，谢谢。

**Comment by zanetti4** [comment]
@lvjie0519 这个问题怎么样了？

**Comment by Banjiemin** [comment]
1， 图片 setState(img_width，img_height)，如果直接设置到目标值，图片是可以显示的；
       但如果是从初始值慢慢设置到目标值（setTimer方式），就是不显示（本地调试OK，线上版本不行）
       做了很久，放弃了；

2， 把View（img+text）一起缩放，看上去现在可以，只是有些虚边，可能跟分辨率相关，再调整 ！


虽然用第二种方式做了差不多了，但第一条为何就是不行，原因实在搞不清楚。

**Comment by Banjiemin** [comment]
暂时先搞一段落吧，我已经用第二种方式搞定了。

第一种方式我做了很多实验，线上版本就是不行，我已经无力追究下去了 。

也行后来人还会遇到这种“气泡”的问题吧 ！！！

**Comment by lvjie0519** [comment]
@Banjiemin    嗯，ok，  我这边也抽时间探索下Animated.Image不行的原因。
