### ISSUE TITLE
Host.audio.startPlay不能播放网络资源mp3文件（android&ios）

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#808]
公司名称（必填）
江苏紫米电子技术有限公司

是否为新产品（必填）
否

产品名称/Model（必填）
小米小爱智能闹钟/zimi.clock.myk01

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10000/]
相关模块:[Host.audio.startPlay]

android米家app版本： 5.5.16.3测试版
ios米家app版本：         buildid 为211

现象（必填）

播放一个网络资源 
http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_mp3_32f0d697b3aaedd012e144fa148d29c7.mp3

1，android提示：
Host.audio.startPlay catch a err = java.io.IOException: Prepare failed.: status=0x1

2，ios提示：
No audio player is running

**Comment by lvjie0519** [comment]
问题已知，请耐心等待我这边排期解决，预计最近一到两周，谢谢。

**Comment by blockdate** [comment]
这边经过确认，所有资源文件播放都需要内置在SDK中，暂时不支持播放任意三方资源文件。

这边可以尝试使用文件下载的方式将FDS文件下载之后进行播放。

**Comment by Banjiemin** [comment]
OK，已经把网络资源下载到本地，然后require，播放 。
