### ISSUE TITLE
提供获取倒计时内容的接口

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#809]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
lumi.plug.mmeu01

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统: iOS 12.2
- SDK分支: 10011
- 相关模块: Host

**期望（必填）**
烦请提供个接口获取倒计时的属性
目前新设备有个需求是在首页显示倒计时的时间，但是目前倒计时的接口只有打开倒计时页面(Host.ui.openCountDownPage)，能否提供个接口可以获取倒计时的剩余时间和开关等属性呢

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
参考Service.scene文档中的timerScene
