### ISSUE TITLE
从native页面返回RN页面，导航栏问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#810]
**公司名称（必填）**
Philips
**是否为新产品（必填）**
否

**产品名称/Model（必填）**
com.philips.light.bulb

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10010]
- 相关模块:[UI]

**现象（必填）**
从native页面（固件升级页面）返回至通用设置页面，导航栏白底黑字会变成白字，导致导航栏文字看不见，android/ios都会复现。
android:
![image](https://user-images.githubusercontent.com/5188922/57997950-daf23180-7b01-11e9-9d5e-9d573ec9f4df.png)
从native页面（固件升级）返回通用设置
![image](https://user-images.githubusercontent.com/5188922/57997962-e3e30300-7b01-11e9-91d6-7cd31d8713e4.png)

ios:
![image](https://user-images.githubusercontent.com/5188922/57997971-ec3b3e00-7b01-11e9-9318-e690ca8f5edf.png)
从native页面（固件升级）返回通用设置
![image](https://user-images.githubusercontent.com/5188922/57997973-f1988880-7b01-11e9-9d0f-ab57ecf25398.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
@mirse 红米Note4X真机 / iPhone8真机 / iPhone Xs Max 模拟器 都无法复现。

**Comment by JobenTian** [comment]
华为荣耀8X会出现这个问题，导航栏中的系统图标都不见了。

**Comment by mirse** [comment]
> @mirse 红米Note4X真机 / iPhone8真机 / iPhone Xs Max 模拟器 都无法复现。

留个邮箱，我发个视频给你看下把

**Comment by LiuMengzhou** [comment]
> > @mirse 红米Note4X真机 / iPhone8真机 / iPhone Xs Max 模拟器 都无法复现。
> 
> 留个邮箱，我发个视频给你看下把

@mirse liumengzhou@xiaomi.com

**Comment by mirse** [comment]
视频已发送 @LiuMengzhou

**Comment by LiuMengzhou** [comment]
![image](https://user-images.githubusercontent.com/13726966/58393058-7f7af300-806f-11e9-9ad0-f0070cbf74c1.png)

@mirse @JobenTian 我们这边没有荣耀系列的手机，红米4X太旧了也没有，我用`iPhone XR`真机在本地调试下用我们的demo（`com.xiaomi.demo`）测试，表现正常，无法复现。

用你们可以复现问题的手机测试一下我们的demo，如果有问题再回复，并提供一下详细的手机系统、app 版本和SDK版本。

**Comment by mirse** [comment]
@LiuMengzhou   主页的titlebar 设置是黑底白字StatusBar.setBarStyle("light-content")，当点击到moremenu是白底黑色StatusBar.setBarStyle('dark-content');，在moremenu页面返回主页面时，titleBar还是白底黑字，你们的demo是因为两个界面都是白底黑字才不会出现这种情况。

**Comment by LiuMengzhou** [comment]
> @LiuMengzhou 主页的titlebar 设置是黑底白字StatusBar.setBarStyle("light-content")，当点击到moremenu是白底黑色StatusBar.setBarStyle('dark-content');，在moremenu页面返回主页面时，titleBar还是白底黑字，你们的demo是因为两个界面都是白底黑字才不会出现这种情况。

你这一段在说啥？
你觉得demo验证你的问题，那你改一下，看能不能复现啊。。。

你这样提问问题，我没办法解答

**Comment by mirse** [comment]
已解决，谢谢

**Comment by JobenTian** [comment]
@mirse 您好！您是怎么解决的？可以分享一下解决方法吗？非常感谢！

**Comment by mirse** [comment]
> @mirse 您好！您是怎么解决的？可以分享一下解决方法吗？非常感谢！

一开始本地调试的时候发现<TitleBar>必须放在navigationOptions里就不会出现这个问题，但是上线之后测试还是会出现这个问题，你的情况的什么样的？ @JobenTian
