### ISSUE TITLE
android录音文件大小问题

### ISSUE THREAD

**Issue by zhaowei1357** [MiEcosystem/miot-plugin-sdk#811]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？apk：version:5.5.16.2
- SDK 是否更新到最新？10010
- Check 文档了吗？Y
- 是否尝试搜索issue？Y

---
**公司名称（必填）**  深圳优点科技
贵司的简称：物联网企业

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否" 否

**产品名称/Model（必填）**
优点智能门锁M2
ydhome.lock.m2silver
**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android6.0/Android7.0]
- SDK分支: [master/10010]
- 相关模块:[Host/audio]

**现象（必填）**
简单明了地描述一下实际的现象。
录制5秒左右的语音，android下和ios下语音文件大小相差数十倍。
测试环境：android6.0和android7.0

**期望（必填）**
androi和ios录制语音后文件大小相差不大

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/29081956/58011126-36cdb200-7b24-11e9-8227-798a6642240e.png)

**尝试过的解决办法**
尝试过哪些操作？
尝试用android原生API录制语音，结果和ios大小相近。

**不要贴大段代码❗️**
![image](https://user-images.githubusercontent.com/29081956/58011452-da1ec700-7b24-11e9-8aee-44bd40a4d25a.png)
![image](https://user-images.githubusercontent.com/29081956/58011501-fa4e8600-7b24-11e9-8f05-d45c8d53c10c.png)

**Comment by zanetti4** [comment]
1.你这样的方式对比文件大小是不准确的，还是查看文件的占用空间更准。
2.安卓、ios 毕竟是不同的系统，即便你穿入相同的参数，也会生成不同大小的文件。
3.现在文件大小相差较大的情况，对于产品使用造成了什么影响？

**Comment by zhaowei1357** [comment]
1.文件空间大小占用和代码读出来的数据相差无几
2.我用android源生的录制5秒，大小和ios基本相近
3.文件大小差异导致我上传到设备上，设备无法读取，尝试用android源生的录制5秒，上传设备成功读出
下图为用米家Host.audio.startRecord录制的文件大小
![image](https://user-images.githubusercontent.com/29081956/58414533-38f8b900-80ae-11e9-8367-d2d2eb96acd1.png)

**Comment by lvjie0519** [comment]
@zhaowei1357   Android之前提供的是MediaRecorder录音，MediaPlayer	进行播放，MediaRecorder对录音文件具有压缩作用，现在增加提供AudioRecord和 AudioTrack。具体使用请参考：

http://note.youdao.com/noteshare?id=e0dc3aa5fa37da184d3f8e1e5d29c232&sub=D7DF782D4A5D46F882D6BA60EE644759

后续会增加到demo中。

**Comment by zanetti4** [comment]
@zhaowei1357 如果问题得到解决，请关闭，谢谢
