### ISSUE TITLE
缺少蓝牙Mesh相关的文档

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#813]
---
**公司名称（必填）**
     亿联客

**是否为新产品（必填）**
      否

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)

yeelink.light.dnlight2 | Yeelight LED筒灯
yeelink.light.meshbulb1 | Yeelight LED球泡 
yeelink.light.meshbulb2 | Yeelight LED烛泡
yeelink.light.spot1 | Yeelight LED射灯 

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac
- 手机系统:[eg.Android 8.1/iOS 11.0] Android 4.4+/IOS 9.0+
- SDK分支: [eg.master/10000/...] master
- 相关模块:[eg.Host/Service/Account] 未找到相关模块，这个属于蓝牙mesh模块

**现象（必填）**
简单明了地描述一下实际的现象。
之前做Mesh产品的时候有相关的IOS RN开发文档和Java相关的Android开发文档，但是在Github上并未找到这两者相关的模块功能，例如，固件升级的接口：MHBluetooth.openMeshDFU()；
**期望（必填）**
简单明了地描述一下期望的表现。
希望补全一下Mesh相关设备的RN开发文档，同时在旧版框架上IOS和Android的固件升级实现方式有出入，请标明在新RN框架下，接口是否同时支持两个平台，如果不支持解决方案是什么。
**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
翻阅github蓝牙和MiotSpec模块并未找到相关文档
**不要贴大段代码❗️**

**Comment by DennisJu007** [comment]
大佬们咱这个什么时候补充一下呢，因为关系到改版新框架后线上mesh产品的使用问题，我们越快拿到文档越好哈

**Comment by blockdate** [comment]
这边因为上的api都是双端支持的，这边有很多积压需求，这边方便将你们旧框架下用到的，在新框架下没有找到的，或者你们不确认更换api怎么用的接口，在这里列一下，我们来安排处理。

**Comment by DennisJu007** [comment]
IOS接口在新框架上没找到这几个接口功能，如果新框架能够适配Android和IOS应该就可省去Android部分的开发
mesh创建灯组 MHDeviceGroup.create(did);
mesh编辑灯组 MHDeviceGroup.edit(did);
mesh固件升级 MHBluetooth.openMeshDFU();

**Comment by blockdate** [comment]
1. 尝试使用 Host.ui.openAddDeviceGroupPage 和 Host.ui.openEditDeviceGroupPage，看是否满足要求，如果不满足再回复
2. openMeshDFU 这个接口需要再和Android端确认如何开放，这边知道你们在之前Android旧框架下调用的API是哪一个么。

**Comment by DennisJu007** [comment]
1、好的1我们试一下
2、Android这边调用的固件升级逻辑是米家同事封装的一个升级类：
```
/**
 * Created by wangchong3@xiaomi.com on 2018/6/22
 *
 * 管理固件升级
 */
public class BleMeshFirmwareUpgrader extends BleUpgrader 
```
里面用的API较多部分接口如下：
  - public abstract void getBleMeshFirmwareUpdateInfo(String var1, String var2, Callback<BleMeshFirmwareUpdateInfo> var3);
  -  public abstract void downloadFirmware(String var1, FirmwareUpgradeResponse var2);
  - public abstract void bleMeshConnect(String var1, String var2, BleConnectResponse var3);
  - public abstract void startBleMeshUpgrade(String var1, String var2, String var3, String var4, BleUpgradeResponse var5);
   - public abstract void cancelDownloadBleFirmware(String var1);
   - public abstract void startScan(int var1, int var2, XmBluetoothManager.BluetoothSearchResponse var3);
   ...如有必要我可以提供该类的java文件

**Comment by DennisJu007** [comment]
> 1. 尝试使用 Host.ui.openAddDeviceGroupPage 和 Host.ui.openEditDeviceGroupPage，看是否满足要求，如果不满足再回复
嗯IOS同事验证了一下也不行，进去是空白界面
![WechatIMG1269](https://user-images.githubusercontent.com/42829167/58616449-44d3bd80-82f0-11e9-9f23-8d5393f7891c.jpeg)

**Comment by santcool** [comment]
已修改，将上线SDK_10021，明早你们可以更新github上的SDK，进行验证。

**Comment by DennisJu007** [comment]
好的，多谢，有任何问题会在这里反馈哈
