### ISSUE TITLE
isBtGateWaySubDeviceWithMac 返回不及时

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [MiEcosystem/miot-plugin-sdk#814]
---
**公司名称（必填）**
霍尼韦尔

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
yuemee.airmonitor.mhfd1

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.2
- SDK分支: master
- 相关模块:MHPluginSDK.isBtGateWaySubDeviceWithMac

**现象（必填）**
一个设备，是连在网关下面的，做下面操作
1.设备拿远，超出蓝牙的工作距离。
2.设备关机
但是isBtGateWaySubDeviceWithMac 永远返回true

**期望（必填）**
正常返回

**其他的上下文/日志/截图**
getDevicePropertyFromMemCache**_0E:34:91:FF:8D:1C_**
17:10:38.710 MainPage.js:1442 **_isBtGateWaySubDeviceWithMac  false_**

**尝试过的解决办法**
看之前的issue，反复退出插件，重启app，段蓝牙，都没用

**不要贴大段代码❗️**

**Comment by Smart-XiaoLeiGe** [comment]
产品已经到用户手中，比较紧急。

**Comment by blockdate** [comment]
这个是旧插件下的API使用？

**Comment by Smart-XiaoLeiGe** [comment]
对的

**Comment by Woody2016** [comment]
@blockdate 

isBtGateWaySubDeviceWithMac这个函数在RN25框架上的实现有bug，请用RN54框架下的实现覆盖即可

**Comment by Smart-XiaoLeiGe** [comment]
> @blockdate
> 
> isBtGateWaySubDeviceWithMac这个函数在RN25框架上的实现有bug，请用RN54框架下的实现覆盖即可

是说这个api 在新插件平台上正常，是吗？

**Comment by Woody2016** [comment]
@Smart-XiaoLeiGe 是的

**Comment by blockdate** [comment]
使用最新的github 上发布的测试 app 测试，旧框架下已处理。

**Comment by blockdate** [comment]
https://fir.im/mijiadevelopment
