### ISSUE TITLE
获取蓝牙网关连接的设备数(包括普通蓝牙设备数，蓝牙mesh设备数）

### ISSUE THREAD

**Issue by RowingCaptainChen** [MiEcosystem/miot-plugin-sdk#815]
**公司名称（必填）**
Yeelight

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
Yeelight蓝牙网关/yeelink.gateway.v1

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS/Linux]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master]
- 相关模块:[MHPluginSDK.openBtGatewayPage()]

**现象（必填）**
无法获取蓝牙网关设备连接数

**期望（必填）**
提供能够分别获取连入蓝牙网关的普通蓝牙设备数和蓝牙mesh设备数的接口。

**Comment by blockdate** [comment]
更新测试app与10020的SDK，使用 `Device.getLinkedBTDevices()`
