### ISSUE TITLE
撤销用户协议授权后，数据不清除问题！

### ISSUE THREAD

**Issue by liduojun** [MiEcosystem/miot-plugin-sdk#816]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**公司名称（必填）**
金史密斯

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
ksmb.walkingpad.v1/v2/v3

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Service.smarthome.getDeviceData(params).then((ret)=>{console.log(ret)});
撤销用户协议授权后，再次绑定,  从上面这个接口上拉取数据，设备会从服务器拉到之前的数据~！
**期望（必填）**
之前撤销用户协议授权，用户的数据记录会被清除，再次绑定后，从0开始；

**其他的上下文/日志/截图**
目前我们SDK处在master主干的4.4号分支上；

**尝试过的解决办法**
跟SDK没有关系，是不是服务器有变动？谢谢

**不要贴大段代码❗️**

**Comment by liduojun** [comment]
app Beta 是最新版本

**Comment by blockdate** [comment]
使用 batchGetDeviceData.
