### ISSUE TITLE
isBtGateWaySubDeviceWithMac 接口废弃

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#817]
在最新的蓝牙接口模块中，isBtGateWaySubDeviceWithMac(mac, callback)**废弃**，请问替代接口有吗？

**Comment by blockdate** [comment]
参考 Bluetooth.isBleGatewayConnected

**Comment by peaceblues** [comment]
设备断电后，isBleGatewayConnected仍然报true。Log如下：

isBleGatewayConnected:true, time: 10:47:25 AM（开始断电）

isBleGatewayConnected:true,time: 12:37:15 PM （断电后）
