### ISSUE TITLE
Android平台，新RN框架，遥控器主界面，点击已添加的空调遥控器后会直接退出插件

### ISSUE THREAD

**Issue by daoke666** [MiEcosystem/miot-plugin-sdk#818]
调用的是这个接口：Host.ui.openDevice(rowData.did,rowData.model,passProps);
帮忙解决，谢谢

**Comment by blockdate** [comment]
按照模板来提issue，尽量吧事件描述清晰。避免来回追问导致浪费时间。
提供下使用平台，sdk版本，app版本信息

**Comment by daoke666** [comment]
不好意思，更新补充一下信息

Android平台，使用的是新RN框架，目前最新版本的debugAPK(5.5.21.2 (Build 62874))

如下界面操作，调用的接口是：Host.ui.openDevice(rowData.did,rowData.model,passProps);

![微信图片_20190523135507](https://user-images.githubusercontent.com/49702230/58228814-7550b000-7d62-11e9-91cf-275b81d56918.png)

**Comment by lvjie0519** [comment]
@daoke666  已修复，请下载最新apk进行测试， 谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，如还存在问题，再reopen。
