### ISSUE TITLE
FDS下载文件

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#820]
**公司名称（必填）**
舒可士(深圳)科技有限公司

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米兔儿童声波牙刷/soocare.toothbrush.mc1

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 7.0]
- SDK分支: [master]
- 相关模块:[Host.file]

**现象（必填）**
在fds后台手动上传的文件，在插件内调用getFDSFileInfoWithObjName(obj_name)来下载文件。
其中obj_name不知道传什么。文档中说明使用generateObjNameAndUrlForFDSUpload来生成，但是这样就必须要在插件内上传了文件才能下载。

**期望（必填）**
提供方法可以直接下载fds后台手动上传的文件。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/14890491/58146311-0acb4180-7c88-11e9-886e-b4f27a8332d9.png)

**尝试过的解决办法**
直接填写fds后台的objName，显示objectname invalid

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
手动上传到fds的文件，可直接设置成public，生成url。插件端需要用这个文件时，用通用下载接口下载此url即可。

getFDSFileInfoWithObjName -- 这个接口只是用来下载“通过插件上传到FDS”的文件

**Comment by Woody2016** [comment]
这个issue先转回给开发者了，开发者自行先验证，如果没问题了请回来反馈结论并close issue

**Comment by lijian9088** [comment]
你好，我这边使用了Host.file.downloadFile这个接口来下载资源文件，现在有两个问题：
