### ISSUE TITLE
关于写入时特征无效问题

### ISSUE THREAD

**Issue by 1076815296** [MiEcosystem/miot-plugin-sdk#822]
**公司名称（必填）**
乐范健康科技

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
乐班智能电动升降台/com.lfwellness.LF_LT001

**环境（必填）**
- 电脑操作系统:Mac OS

**现象（必填）**
输入了通知和写入的UUID   如果两个都写入 或者只是输入写入的UUID  会报无法写入的错误，
如果只输入通知的  会报UUID无效的错误

**期望（必填）**
可以正常的写入数据

**其他的上下文/日志/截图**
![26121558506027_ pic_hd](https://user-images.githubusercontent.com/43639032/58156812-92757800-7ca9-11e9-9164-bf9d93881e44.jpg)
![26151558506057_ pic_hd](https://user-images.githubusercontent.com/43639032/58156835-9f926700-7ca9-11e9-811f-b2ebeac07957.jpg)
![26171558506079_ pic](https://user-images.githubusercontent.com/43639032/58156843-a620de80-7ca9-11e9-8bb9-8f98d170dad7.jpg)
![26181558506087_ pic](https://user-images.githubusercontent.com/43639032/58156861-ac16bf80-7ca9-11e9-825c-86c4b1e5b48d.jpg)

**尝试过的解决办法**
特征的UUID都试过了,UUID是正确的，在旧框架中可以运行。

**Comment by blockdate** [comment]
service与characteristic是否都进行了scan操作

**Comment by 1076815296** [comment]
> 服务与特征是否都进行了扫描操作

已经进行扫描了  都扫描到了   在安卓里面比较稳定一点 但是苹果里面的特征值无效。

**Comment by 1076815296** [comment]
> 服务与特征是否都进行了扫描操作

![image](https://user-images.githubusercontent.com/43639032/58311853-8d94fd80-7e3c-11e9-9531-f10e1269c42b.png)
这一段在安卓中可以成功写入  在苹果中LFLiftTabelWriteCharacteristicUUIDString写入特征无效

**Comment by blockdate** [comment]
characteristic or service not found 错误表示没有找到可以读写操作的characteristic

1. 发送你的uuid的具体值
2. 通过lightBlue或者蓝牙的demo，将你的设备的所有service和characteristic 截图发出来
这边查看下是否有问题。

**Comment by 1076815296** [comment]
![301559525882_ pic](https://user-images.githubusercontent.com/43639032/58770784-81026900-85e3-11e9-9e1e-8b0e1995d9f2.jpg)
![311559525882_ pic](https://user-images.githubusercontent.com/43639032/58770788-83fd5980-85e3-11e9-859f-fa97dab5b2da.jpg)
![321559525883_ pic](https://user-images.githubusercontent.com/43639032/58770792-86f84a00-85e3-11e9-8ec6-c1c397d984ec.jpg)

**Comment by 1076815296** [comment]
> 未找到特征或服务错误表示没有找到可以读写操作的特征
> 
> 1. 发送你的UUID的具体值
> 2. 通过lightBlue或者蓝牙的demo，将你的设备的所有服务和特征截图发出来
>    这边查看下是否有问题。

请老师帮忙查看下

**Comment by blockdate** [comment]
字面意思，你写入的特征是只支持 writeWithOutResponse 的， 使用 writeWithoutResponse 来写入数据。
![image](https://user-images.githubusercontent.com/4339364/58771282-d475b680-85e5-11e9-884c-deab8175925d.png)
