### ISSUE TITLE
手机设为希腊，Host.locale.language返回'zh'

### ISSUE THREAD

**Issue by yanmin0220** [MiEcosystem/miot-plugin-sdk#823]
---
**公司名称（必填）**
创米科技

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
chuangmi.plug.hmi206

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux] Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0] Android 9/iOS 12.2
- SDK分支: [eg.master/10000/...] 10003
- 相关模块:[eg.Host/Service/Account] Host.locale.language

**现象（必填）**
手机设为希腊语，Host.locale.language返回'zh'

**期望（必填）**
手机设为希腊语，Host.locale.language能返回对应代码

**Comment by zanetti4** [comment]
#390
