### ISSUE TITLE
RN运行效率较低

### ISSUE THREAD

**Issue by icedu8910** [MiEcosystem/miot-plugin-sdk#824]
扩展程序UI中，我们使用SVG path画弧线，并将弧线的角度值绑定在animate动画中，达到动态进度条的效果。
出现问题：当这种进度条数量达到8条后，iphone6实体机出现稍微掉帧，华为mate9之类的一些较旧的机子出现明显的延迟及掉帧。
也就是说，RN对一些较旧的设备支持不是很友好。

**Comment by weeksun23** [comment]
8条你是8个动画，还是只有1个动画？

**Comment by icedu8910** [comment]
你好。8条弧线中4条弧线会根据数据变化而变化，另外4条是固定显示的。

**Comment by zanetti4** [comment]
请提供您的 svg 具体使用代码

**Comment by weeksun23** [comment]
答非所问。。
