### ISSUE TITLE
Device.getSubDevices，返回值中 iconUrl 为空

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#825]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
lumi.gateway.iragl01

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:Service

**现象（必填）**
使用 Device.getSubDevices 该请求的时候，返回值中 iconUrl 为空，
虽然有 Device.loadRealDeviceConfig 可以进行获取设备的 iconUrl，但是该命令为异步命令，并且当我有例如 20 个不一样的子设备的时候，就需要发 20 次该命令去进行获取图片信息，而且也不清楚是否会存在获取失败的情况，如果获取失败，该设备的 icon 就为空了。所以这样是非常不符合设计逻辑的。

**期望（必填）**
Device.getSubDevices 中的 iconUrl 不为空

**其他的上下文/日志/截图**
![WechatIMG44](https://user-images.githubusercontent.com/8938524/58221613-cf8f4800-7d45-11e9-807d-917e720b563a.png)

**尝试过的解决办法**
异步发送多次命令进行获取

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请把 lumi.gateway.iragl01 分享给我，我进行调试，我的米家 id: 894158105

**Comment by blockdate** [comment]
这个我已经处理了，稍后更新app即可

**Comment by Pandalzm** [comment]
@blockdate
 iconURL的问题好了，更新app之后 Host.ui.openZigbeeConnectDeviceList(did) 又不行了。
