### ISSUE TITLE
自定义倒计时页面的identifier

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#826]
公司名称（必填）
绿米

是否为新产品（必填）
否

产品名称/Model（必填）
米家智能插座/lumi.plug.v1
环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 8.1/iOS 12.2]
SDK分支: [10011]
相关模块:[Host.ui]

现象（必填）
倒计时页面不能指定identifier
接口为：openCountDownPage(isCountDownOn, setting)
接口用例：Host.ui.openCountDownPage(true, {onMethod:"power_on", offMethod:'power_off', onParam:'on', offParam:'off'})

期望（必填）
倒计时页面可以新建、获取、显示自定义identifier的倒计时

其他的上下文/日志/截图

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码❗️

**Comment by zanetti4** [comment]
你所说的指定 identifier 是什么意思？比如：打开倒计时页面默认显示着“17时44分”？
我在 iOS 测试，通过自定义功能是可以指定任意时间的。
你能说的再具体一点儿吗？并且把你的使用代码发过来。

**Comment by xyliusun** [comment]
你好，identifier就是timer的identify属性，在旧插件上我们创建的倒计时都会将identify修改为特定值，显示的时候也是用这个来筛选出倒计时定时。我们就是想要兼容下旧插件，可以在新插件上显示特定identify的倒计时

**Comment by xyliusun** [comment]
目前的identify默认是设备id，导致旧插件创建的倒计时在新插件上没显示，希望能在页面上显示特定identify的倒计时，接口可以弄成这样：Host.ui.openCountDownPage(true, **identify**,  {onMethod:"power_on", offMethod:'power_off', onParam:'on', offParam:'off'})

**Comment by zanetti4** [comment]
@blockdate openCountDownPage 接口的新需求，请你协助

**Comment by blockdate** [comment]
这个需要新增AP以及Native功能更新支持，我们这边讨论看如何支持下。

**Comment by blockdate** [comment]
SDK 10021 已支持，测试app正在打包中。

预计Android 版本号为5.5.25.5， iOS预计构建号为254。

![image](https://user-images.githubusercontent.com/4339364/59671028-8a98ed00-91ef-11e9-917c-10d409a398e7.png)

**Comment by lvjie0519** [comment]
@xyliusun   Android可以在fir上下载最新apk，sdk选择10021分支进行测试，谢谢。

**Comment by xyliusun** [comment]
iOS和安卓上都验证了，OK，谢谢了

**Comment by xyliusun** [comment]
我想请问一下你们是怎么区分倒计时和定时场景的呢？有没有什么字段可以区分开来呢？

**Comment by zanetti4** [comment]
用法不同
倒计时：从现在开始一段时间后开启或关闭。
定时：指定一个时间或时间段
