### ISSUE TITLE
Host.ui.addOrCopyIR和Host.ui.openDevice页面跳转问题

### ISSUE THREAD

**Issue by Simon-M770** [MiEcosystem/miot-plugin-sdk#827]
**公司名称（必填）**
上海创米科技有限公司

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家万能遥控器/chuangmi.remote.v2

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.2
- SDK分支: [10005]
- 相关模块:[Host/ui]

**现象（必填）**
从遥控器列表插件页面点击 添加遥控器，复制遥控器 或者点击一个已添加的遥控器，跳转页面的时候都会先退出遥控器列表页面 然后再进入新的插件页面。
调用的是下面两个接口
miot/host/ui.addOrCopyIR  跳转添加或复制遥控器
miot/host/ui.openDevice  跳转已添加遥控器

**期望（必填）**
期望直接跳转新的页面而不是退出遥控器列表页面，android上是正常的。

**其他的上下文/日志/截图**
有录屏

**尝试过的解决办法**
无

**不要贴大段代码❗️**

**Comment by Simon-M770** [comment]
[RPReplay_Final1558590662.m4v.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3210663/RPReplay_Final1558590662.m4v.zip)
录屏文件

**Comment by blockdate** [comment]
更新 测试app， 使用 
`Host.ui.openDevice(did,model, { dismiss_current_plug: false })`
或者
`Host.ui.addOrCopyIR(did,type,models, { dismiss_current_plug: false })`

**Comment by Simon-M770** [comment]
验证ok，谢谢！
