### ISSUE TITLE
固件升级完成后，连接不上蓝牙了

### ISSUE THREAD

**Issue by JxXiaoXie** [MiEcosystem/miot-plugin-sdk#828]
**公司名称（必填）**
舒可士

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
soocare.toothbrush.m1s

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS
- SDK分支: 10005
- 相关模块:

**现象（必填）**
固件升级完成，设备蓝牙灯也灭了。退出固件升级页，进行蓝牙操作
Device.getBluetoothLE().isConnected 值为 true，所以我就直接进行 Device.getBluetoothLE().startDiscoverServices(ServiceUUID); 操作了，但是一直没有发现设备的通知回调过来，我确定是有监听蓝牙事件的。

注：
1、固件升级之前，我写了个指令进设备，写完后我没有断开蓝牙（因为我们这边要求写入DFU校验指令后不能断开蓝牙），直接进行的升级操作。
2、退出插件再进入插件，蓝牙操作又正常

**期望（必填）**
固件升级完后能正常进行蓝牙操作

**尝试过的解决办法**
Device.getBluetoothLE().isConnected 值为 true，我尝试过执行断开蓝牙操作，可还是不行。
测试断开方式一：
Device.getBluetoothLE().disconnect(0);
测试断开方式二：
Bluetooth.retrievePeripheralsWithServicesForIOS(ServiceUUID).then((uuid) => {
        for (var key in uuid) {
          console.log('已连接设备：' + key);
          // let bt = Bluetooth.createBluetoothLE(key);
          let bt = Device.getBluetoothLE(key);
          bt.disconnect();
        }
});
这里似乎并没有检测到有连接着设备。

**Comment by blockdate** [comment]
可以尝试 connect(type,{forceReconnect:true})

**Comment by Copypeng** [comment]
固件升级完成后，出现如上问题，去设置-蓝牙-我的设备看下是否手机真实跟设备有连接。

**Comment by JxXiaoXie** [comment]
> 固件升级完成后，出现如上问题，去设置-蓝牙-我的设备看下是否手机真实跟设备有连接。

没有，我的设备列表都是未连接的设备

**Comment by JxXiaoXie** [comment]
> 可以尝试 connect(type,{forceReconnect:true})

加了可以连接上了

**Comment by Woody2016** [comment]
问题已经解决，此issue关闭

**Comment by 123start** [comment]
connect(type,{forceReconnect:true}).   返回结果code=-7.   然后connect()方法回调有个最短时间，在这期间获取获取Device.getBluetoothLE().isConnected都为true，然后用户这期间的操作都是无效的
