### ISSUE TITLE
新框架iOS端和Android端 有固件版本跟新时 弹出框差异

### ISSUE THREAD

**Issue by CyrilChen** [MiEcosystem/miot-plugin-sdk#829]
新框架 10010版本，当有新固件版本更新后，
iOS端会在进入插件后弹出提示框 显示“检测到设备有最新固件版本****，是否升级”，
但是Android不会显示这个提示框。
请确认此处逻辑，保持两个平台一致，谢谢
![WechatIMG7](https://user-images.githubusercontent.com/8743690/58312316-a18d2f00-7e3d-11e9-8740-168002b0fc41.jpeg)

**Comment by lvjie0519** [comment]
已安排产品确认，正在排期中，请耐心等待。

**Comment by Woody2016** [comment]
@CyrilChen  请按issue模板补齐必要信息，谢谢

**Comment by CyrilChen** [comment]
@Woody2016 

**是否为新品（必填）**
新品

**项目ID（必填）**
所有使用新框架项目

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android/iOS]
- SDK分支: [10011]
- 相关模块:[Account]

**现象（必填）**
Q: 简单明了地描述一下实际的现象。
A: 使用新框架，当有固件需要更新时，iOS端会在进入插件后弹出提示框 显示“检测到设备有最新固件版本****，是否升级”，但是Android不会显示这个提示框。

**期望（必填）**
Q: 简单明了地描述一下期望的表现。
A: 确认当前逻辑，使Android和iOS端保持一致

**其他的上下文/日志/截图**
Q:提供更多的上下文，有日志或者截图更好。
A:截图请参照之前回复内容

**尝试过的解决办法**
Q:尝试过哪些操作？
A:提示框调用原生系统的提示框，查过文档，没有解决方案

**Comment by Woody2016** [comment]
需求更新：

iOS：给开发者接口，去自定义是否允许弹“固件升级提示框”
android：需求和iOS保持一致，1. 增加弹框支持 2. 支持自定义

**Comment by blockdate** [comment]
SDK 10021 已更新。

![image](https://user-images.githubusercontent.com/4339364/59914409-eb713100-944c-11e9-985d-99c1a547368e.png)
