### ISSUE TITLE
新的sdk，SVG中的Text，添加  fill="#ffffff"就会报错？是怎么回事

### ISSUE THREAD

**Issue by wyc123456** [MiEcosystem/miot-plugin-sdk#83]
<Text fill="#ffffff"></Text>这样会报错，那应该如何改变SVG中的text的字体颜色？
![293d54adabb18ff4d8628adbc7c39b77](https://user-images.githubusercontent.com/19943186/49278571-2f581500-f4c0-11e8-93fe-13eab52c6407.jpg)

**Comment by wyc123456** [comment]
ios的没有问题，Android 的不行会报错

**Comment by edwardair** [comment]
我用 SVG Android上也会报错 #96

**Comment by dingshaoran** [comment]
混淆的问题，已经修改，请下载最新 apk
