### ISSUE TITLE
【新品】【P19-0263】miot.Device.getDeviceWifi().callMethodFromCloud调用报错

### ISSUE THREAD

**Issue by weeksun23** [MiEcosystem/miot-plugin-sdk#830]
公司名称：佛山市云米电器科技有限公司
是否为新产品：是
手机系统:安卓9/IOS 12.2
SDK分支：10020
相关模块：miot.Device.getDeviceWifi()
现象：
调用callMethodFromCloud方法的时候 经常会报错，具体错误如下
```
callMethodForceWay failedError Domain=MiHomeNetworkErrorRemote Code=-104 "(null)" UserInfo={code=-104, id=0, message= no did, error={
    code = "-104";
    message = " no did";
}}
```

**Comment by weeksun23** [comment]
1

**Comment by weeksun23** [comment]
补充：
1、不止是10020分支出这个问题，尝试了master分支（10010）也出现这个问题；APP独立SDK也出现这个问题；
2、其他模组设备没有出现该问题
3、iot平台上查询设备的日志，没有发现该失败记录
4、设备上监控相关指令，没发现该失败指令

**Comment by weeksun23** [comment]
2

**Comment by blockdate** [comment]
no did 这个不是插件部分的问题，这个系服务端的问题，提供下出现过问题的用户 uid， 设备did， 设备model。

**Comment by weeksun23** [comment]
uid:888819681
did:277930123
model:viomi.vacuum.v7

**Comment by blockdate** [comment]
该问题系服务端OT层问题，已联系相关同事处理，如任然有问题，建议发送问题邮件至 wulei7@xiaomi.com，方便我们这边转送到相关责任人
