### ISSUE TITLE
倒计时页面时间错误

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#831]
**公司名称（必填）**
绿米

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家智能插座/lumi.plug.v1

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.2]
- SDK分支: [10011]
- 相关模块:[Host]

**现象（必填）**
1. 创建倒计时后，重复进入页面，时间显示错误
2. 倒计时结束后，页面停留在00:00:00时间，退出重新进才恢复成添加倒计时页面

**复现步骤**
添加一个1分钟的倒计时，然后重复退出进入倒计时页面，大约一分钟后，点进来看到有个3小时的倒计时

**期望（必填）**
1. 倒计时页面显示正确的倒计时时间
2. 倒计时结束后页面返回成添加倒计时的状态

**其他的上下文/日志/截图**
正常显示页面：
![IMG_0174](https://user-images.githubusercontent.com/20435121/58327831-2fc7dc00-7e63-11e9-936d-6e4ace44782d.PNG)

倒计时结束后页面：
![IMG_0175](https://user-images.githubusercontent.com/20435121/58327829-2fc7dc00-7e63-11e9-814e-24142d171797.PNG)

倒计时时间错误页面：
![IMG_0176](https://user-images.githubusercontent.com/20435121/58327821-2b032800-7e63-11e9-9b36-5151ebe03075.PNG)

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
已通知相关同学处理中

**Comment by santcool** [comment]
倒计时的问题预计会在8月初的版本上，鉴于后面很多开发者提了相关问题，此问题暂且关闭了
