### ISSUE TITLE
Android本地调试Debug JS Remotely时报跨域错误

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#832]
错误信息：
Access to fetch at 'http://localhost:8081/projects/com.joyoung.ccj01/index.delta?platform=android&dev=true&minify=false' from origin 'http://192.168.5.101:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
(index):190 Uncaught (in promise) TypeError: Failed to fetch
操作步骤：
1、运行 npm start
2、打开米家
3、点击绑定的调试设备
4、在流浪器上看到上述报错
现象：iOS 正常  ，android才会报错

**Comment by weeksun23** [comment]
http://192.168.5.101:8081 改成 http://localhost:8081/ 刷新下 就行了 哥

**Comment by killua4github** [comment]
如何免去手机通过USB连接电脑进行RN调试？
    1. 用力摇动手机出现的弹框 -> Dev Settings -> Debug server host & port for device,设置您电脑的ip地址及端口号,端口号默认为8081。如：192.168.1.2:8081,最后运行 npm start ，点击手机上的 Reload。

上面这段是你们平台米家扩展程序里Android调试里的一段，我上面提到的问题只有在开启”Debug JS Remotely“的时候才会报错，不开起的话是可以正常调试的。那里的域名本质上来说就是localhost，所以才会出现跨域问题的吧？弟

**Comment by killua4github** [comment]
> http://192.168.5.101:8081 改成 http://localhost:8081/ 刷新下 就行了 哥

如何免去手机通过USB连接电脑进行RN调试？
1. 用力摇动手机出现的弹框 -> Dev Settings -> Debug server host & port for device,设置您电脑的ip地址及端口号,端口号默认为8081。如：192.168.1.2:8081,最后运行 npm start ，点击手机上的 Reload。

上面这段是你们平台米家扩展程序里Android调试里的一段，我上面提到的问题只有在开启”Debug JS Remotely“的时候才会报错，不开起的话是可以正常调试的。那里的域名本质上来说就是localhost，所以才会出现跨域问题的吧？弟

**Comment by lvjie0519** [comment]
1、辛苦之后提issue，能够按照标准模板来，谢谢；
2、无论是通过usb连接电脑来使用浏览器调试或通过设置ip地址及端口号来使用浏览器调试，浏览器上的域名必须都是localhost，RN默认是这样的，谢谢。
