### ISSUE TITLE
InputDialog字数限制

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#833]
**公司名称（必填）**
Philips

**是否为新产品（必填）**
否

**产品名称/Model（必填）**

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [master]
- 相关模块:[？]

**现象（必填）**
能否InputDialog控件中，提供字数限制功能？

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
可以考虑自己实现一个。一直到现在都没有人力支持此问题。。。
