### ISSUE TITLE
原来的旧插件中的APNS推送监听事件,没有了,新插件中有替代方案吗?

### ISSUE THREAD

**Issue by georgeChina** [MiEcosystem/miot-plugin-sdk#836]
从旧插件升级到新插件,发现没有了APNS推送监听事件,原来有个功能,需要用到这个,现在没有了,请问有新的替代方案吗?
需求:蓝牙锁,需要在设备报警异常的时候,推送一个报警异常的信息给手机,需要实时的显示新的异常报警

**Comment by blockdate** [comment]
按照issue模板提问，并且说明详细一点。
