### ISSUE TITLE
获取屏幕高度

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#837]
**公司名称（必填）**
Philips

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
philips.light.bulb

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 8.1]
- SDK分支: [10010]
- 相关模块:[?]

**现象（必填）**
Dimensions.get('window').height获取的屏幕高度不对，使用10011分支host.getPhoneScreenInfo().then()...方法获取全面屏的高度也是不对，跟Dimensions.get('window').height一样。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@mirse   已修复，去掉了是否有虚拟导航栏的判断，直接返回view能够显示的宽高，宽高是包括状态栏及界面header部分，不包括虚拟导航栏因此无需关注是否有虚拟导航栏，请下载最新apk进行测试，谢谢。

**Comment by lvjie0519** [comment]
如还存在问题，再reopen，暂时关闭，谢谢。
