### ISSUE TITLE
iOS BLE连接状态获取异常

### ISSUE THREAD

**Issue by ding209** [MiEcosystem/miot-plugin-sdk#839]
**公司名称（必填）**
西安蜂语（小米生态链）

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
fengyu.intercom.sealv1，fengyu.intercom.sharkv1

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[iOS 11.0]
- SDK分支: [10010]
- 相关模块:[BluetoothLE]

**现象（必填）**
iOS添加ble设备，添加并设置完设备后米家App会自动进入插件页面，这时候系统层ble已经提前连接上了，但是在进入插件后获取 Device.getBluetoothLE().isConnected 一直是false，并且发现ble服务startDiscoverServices也会回调失败。
退出插件断开ble后再重新进入插件重连接连才会正常。

**期望（必填）**
期望修复这个问题，需要提测

**尝试过的解决办法**
iOS平台下在进入插件后不管是否已经连接都直接先调用disconnect断开ble，在重新走正常连接流程。这样是会正常。但是我们设备有ble连接断开的提示音，所以用户能明显听到添加ble设备的时候设备会发出连上、断开、再连上的提示音

**Comment by blockdate** [comment]
先使用 `retrievePeripheralsForIOS` 或者 `retrievePeripheralsWithServicesForIOS` 获取已连接的蓝牙对象，然后手动创建蓝牙对象`Bluetooth.createBluetoothLE(result.uuid || result.mac);`，然后 `ble.connect(3)`
