### ISSUE TITLE
进入插件直接报错

### ISSUE THREAD

**Issue by dongyaxun** [MiEcosystem/miot-plugin-sdk#84]
iOS真机调试，进入插件直接报错：
Failed to load bundle(http://192.168.3.243:8081/projects/com.jiqid.mistory.ios/index.ios.bundle?platform=ios&dev=true&minify=false)
with error:(projects/com.jiqid.mistory.ios/index.js:Cannot read property 'bindings' of null(null))
无论是官方demo，还是调用npm run create新创建的插件，都一样报这个错。

**Comment by edwardair** [comment]
iOS、android都没问题，试试把SDK、ipa更新到最新，甚至：尝试重新clone一下SDK
PS: 我这边蓝牙连接有问题，一直等不到官方人员帮忙解决，只能大家互相帮助了

**Comment by dongyaxun** [comment]
重新clone了一下SDK就好了
