### ISSUE TITLE
安卓平台Device.owner.ID返回为空字符串“”

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#840]
公司名称
青岛亿联客信息技术有限公司

是否为新产品
否

产品名称/Model
yeelink.light.ceiling12(应该不限于该model)

环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 6.0]
- SDK分支: [master]
- 相关模块:[Device]

现象
同一账号下调试，安卓平台Device.owner.ID为空字符串“”（发现isOwner为true），而iOS则显示正确。

期望
安卓Device.owner.ID返回正确值。

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码

**Comment by lvjie0519** [comment]
排查发现APP层的device信息就为空，请等待排查。

![image](https://user-images.githubusercontent.com/22487747/58623121-d565ca00-82ff-11e9-899f-d462e13ac767.png)

**Comment by TheWalkingDead1024** [comment]
> 排查发现APP层的device信息owenerId和ownerName就为空，请等待排查。
> 
> ![image](https://user-images.githubusercontent.com/22487747/58623202-0645ff00-8300-11e9-9441-0594050805bd.png)

收到，感谢

**Comment by lvjie0519** [comment]
@TheWalkingDead1024   问题已修复，  请使用最新apk进行测试，谢谢。
