### ISSUE TITLE
固件升级页获取不到新的固件版本号

### ISSUE THREAD

**Issue by chenzhuojie** [MiEcosystem/miot-plugin-sdk#842]
**公司名称（必填）**
贵司的简称

骑记

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否"

是新框架

**产品名称/Model（必填）**
此issue关联的产品名称和model,如"小米开发板/xiaomi.demo.v1"。(若您不清楚，请咨询贵司的项目经理)

qicyc.bike.xmdzlzxc01qj

**环境（必填）**
- 电脑操作系统:[Windows10 ]
- 手机系统:[eg.Android 8.1/iOS 12.0]
- SDK分支: [eg.master/10003]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
简单明了地描述一下实际的现象。

点击固件升级调用米家提供的接口，但是获取不到新的版本信息，请问这个版本信息从哪里来的
![image](https://user-images.githubusercontent.com/49181603/58445590-cc260300-812f-11e9-8b39-d710b53f8390.png)

**期望（必填）**
简单明了地描述一下期望的表现。

请提供版本信息接口或者告诉我们在哪里配置

**Comment by santcool** [comment]
你去抓包v2/device/multi_check_device_version.这里面的版本就是这个接口来的。最终来源于iot平台里面的固件版本

**Comment by chenzhuojie** [comment]
我们已经在iot平台上传并配置了固件版本，但是这里仍然为空呀

**Comment by santcool** [comment]
请求提供抓包信息，我们好去后天查，谢谢。

**Comment by chenzhuojie** [comment]
我们抓包没有发现v2/device/multi_check_device_version这个接口的请求

![image](https://user-images.githubusercontent.com/49181603/58620417-9d5b8880-82f9-11e9-9646-4cb599920117.png)

**Comment by santcool** [comment]
你们给我分享一个设备吧：894158105，分享了知会一声，我来抓包看看

**Comment by chenzhuojie** [comment]
已经把你添加到白名单里了，谢谢

**Comment by chenzhuojie** [comment]
也分享给你了

**Comment by chenzhuojie** [comment]
分享给你了，谢谢

**Comment by huanghaibing** [comment]
你好，请问这问题解决了吗。我这边也遇到了同样的问题

**Comment by santcool** [comment]
最近比较忙，争取明天有时间看看

**Comment by chenzhuojie** [comment]
你好，请问这个问题有时间解决了吗

**Comment by chenzhuojie** [comment]
你好，请问这个问题有解决吗？？

**Comment by santcool** [comment]
现在看，今天给回复，稍等

**Comment by chenzhuojie** [comment]
好的谢谢

**Comment by santcool** [comment]
方便重新给分享一个设备吗？

**Comment by chenzhuojie** [comment]
好的，马上分享给你

**Comment by chenzhuojie** [comment]
已经分享给你们了

**Comment by chenzhuojie** [comment]
![image](https://user-images.githubusercontent.com/49181603/59183904-90fbe900-8b9f-11e9-83ee-db16d21d195d.png)

安卓是显示这样的，点击更新之后会报错


![FCA7439BD0748FF7B817DB9436C2257E](https://user-images.githubusercontent.com/49181603/59183937-a4a74f80-8b9f-11e9-9ccb-7efe6cc100a6.jpg)

**Comment by santcool** [comment]
https://api.io.mi.com/app/v2/device/multi_check_device_version
{
    data : {"app_level":"4.18.1","check_reqs":[{"did":"blt.3.veera28gkk00"}],"platform":"ios"}
}

response:{
 "code": 0,
 "message": "",
 "result": {
  "list": []
 }
}
我已经让后台的同时在查了

**Comment by chenzhuojie** [comment]
好的，请问能顺便看看Android的吗

**Comment by santcool** [comment]
[我最开始弄错了，你们这个是蓝牙设备，不走上面的v2/device/multi_check_device_version这个接口。我给你们打了一个特殊的[调试包](https://fir.im/tes5?release_id=5cfe3223ca87a853fc5c0f5a)，你们在设置页，点击图中
![381560166150_ pic](https://user-images.githubusercontent.com/8580061/59192919-8ef15480-8bb6-11e9-8597-49fd7fd86f47.jpg)
的反馈问题，会弹出来一个alert，你看看有没有设备的升级信息，如果有，你们就需要使用此接口来获取升级信息，如果没有，请给我提供一个有设备的测试账号和密码，发送到邮箱：zhangwenfeng@xiaomi.com。我再查查

**Comment by santcool** [comment]
你查一查，项目中有：蓝牙OTA步骤.md	 这个文档，这里面有获取版本的接口，另外，蓝牙ota需要你们自己实现，你们可以参考：https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/03-%E8%93%9D%E7%89%99%E8%AE%BE%E5%A4%87%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97 这篇里面的nordic库升级常见问题，nordic库是用来做蓝牙OTA的库，已经集成到项目里。你们可直接参考github： https://github.com/Pilloxa/react-native-nordic-dfu

**Comment by chenzhuojie** [comment]
你好，那我想请问一下，我们是不是需要通过小米Iot平台上的上传固件接口上传升级包呢，如果是的话，我们之前尝试过，在iot平台的上传固件版本页面上传了一个ZIP文件，然后用平台上面提供的下载链接下载回来的是一个bin文件，这不符合DFU nordic升级文件的格式吧，那请问一下这个我们的固件包是通过什么接口上传的呢

**Comment by santcool** [comment]
你是通过固件更新的接口去取的文件吧？正确的方式应该是通过Host.file. filedownloadFile()去下载。

**Comment by huanghaibing** [comment]
**文档里面是这个接口。我调用了报错**
![image](https://user-images.githubusercontent.com/17466149/59236609-9b62c500-8c29-11e9-84e9-352f7620167b.png)


**报这个错**

![image](https://user-images.githubusercontent.com/17466149/59236665-d7962580-8c29-11e9-987f-ac010769cff0.png)

**Comment by santcool** [comment]
写错了，应该是Host.file. downloadFile()

**Comment by huanghaibing** [comment]
调用这个监听方法报错
DFUEmitter.addlistener("DFUProgress",({percent, currentPart, partsTotal, avgSpeed, speed}) => {
            console.log("DFU progress: " + percent +"%");
        });

报错内容
![image](https://user-images.githubusercontent.com/17466149/59238988-9b1af780-8c32-11e9-9c08-86fa3dcc7fa2.png)

**Comment by chenzhuojie** [comment]
你好，我想请问一下，以下代码，在Android端能正常运行，但是在IOS端会报如下错误：

NordicDFU.startDFU({
deviceAddress: "C3:53:C0:39:2F:99",
name: "Pilloxa Pillbox",
filePath: "/data/user/0/com.nordicdfuexample/files/RNFetchBlobTmp4of.zip"
})

**错误如下**
![image](https://user-images.githubusercontent.com/49181603/59255814-3927b580-8c65-11e9-8c98-c1b54bae733d.png)

我们蓝牙已经连接上了，并且有正常的数据收发，请问这个怎么解决呢？？？

**Comment by chenzhuojie** [comment]
你好，请问一下问题能看一下吗

**Comment by santcool** [comment]
deviceAddress需要传uuid，不应该传mac地址。

**Comment by chenzhuojie** [comment]
![image](https://user-images.githubusercontent.com/49181603/59414049-64d8a600-8df3-11e9-9c85-bcbbfc9d4f79.png)

还是报错，报了一个无法找到设备

**Comment by chenzhuojie** [comment]
你好，请问这个问题怎么解决呢

**Comment by blockdate** [comment]
贴一下你的使用代码

**Comment by chenzhuojie** [comment]
你好，主要代码如下：

![image](https://user-images.githubusercontent.com/49181603/59574758-0c532280-90eb-11e9-98e1-4a0a6b89d915.png)

**Comment by chenzhuojie** [comment]
现在这一段相同的代码，Android是可以正常运行的，IOS运行会报错，就是上面的代码

**Comment by blockdate** [comment]
字面意思，指定uuid的设备并没有找到，你可以尝试下 Bluetooth.retrievePeripheralsForIOS 将你的uuid传入，看能否获取的到该设备。

**Comment by chenzhuojie** [comment]
我们IOS的设备已经是连接上，并且能正常收发数据，但是一开始DFU升级的流程就提示没有找到设备，然后现在用uuid找设备也是不行的，还是找不到

**Comment by blockdate** [comment]
Bluetooth.retrievePeripheralsForIOS 将你的uuid传入,提供下日志

**Comment by chenzhuojie** [comment]
![image](https://user-images.githubusercontent.com/49181603/59594682-dd5aa200-9126-11e9-96de-81add4029850.png)


![image](https://user-images.githubusercontent.com/49181603/59594707-ec415480-9126-11e9-88a4-e6c8a8f7f07c.png)

**Comment by blockdate** [comment]
这个看上去的确是没能通过指定的uuid获取到已连接的蓝牙设备。你这个uuid是如何获取的？

**Comment by chenzhuojie** [comment]
我们是根据BluetoothEvent.bluetoothCharacteristicDiscovered这个方法获取的

**Comment by blockdate** [comment]
bluetoothCharacteristicDiscovered这个是特征值的uuid，你要传递的是蓝牙的uuid,在bluetoothConnectionStatusChanged事件中的uuid，或者蓝牙连接成功之后的ble.UUID

**Comment by chenzhuojie** [comment]
问题已经解决了，谢谢
