### ISSUE TITLE
绑定锁具时出现“扩展程序启动失败，请稍后重试”的现象

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#843]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼Q3智能锁/dsm.lock.q3

**环境（必填）**
- 电脑操作系统:  Windows
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010
- 相关模块:  米家App

**现象（必填）**
测评用户，有3个客户反馈绑定锁具时出现“扩展程序启动失败，请稍后重试”的现象，无法绑定锁具，退出再登录也不行，把APP卸载再重装就可以；

**期望（必填）**
能正常启动扩展程序

**Comment by lvjie0519** [comment]
@dessmann  确定下出问题的APP是哪个版本，这样方便排查，谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，有问题再reopen。
