### ISSUE TITLE
从App里添加锁具时会出现get passwrod failed

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#846]
**公司名称（必填）**
德施曼

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
德施曼Q3智能锁/dsm.lock.q3

**环境（必填）**
- 电脑操作系统:  Windows
- 手机系统:  MI 5C Android 7.1.2
- SDK分支:   10010
- 相关模块:  米家App

**现象（必填）**
添加锁时出现get password failed

**期望（必填）**
添加锁时不出现get password failed

**Comment by lvjie0519** [comment]
经分析确认是android app的bug, 请耐心等待米家native端解决，修复会及时回复。

**Comment by dessmann** [comment]
![111](https://user-images.githubusercontent.com/28518884/58687961-b32e8380-83b5-11e9-8dcd-fea0684c7eac.jpeg)

**Comment by lvjie0519** [comment]
@dessmann   用最新apk试试，问题是否存在，谢谢。

**Comment by dessmann** [comment]
没有了，多谢！
