### ISSUE TITLE
三星手机米家app搜索不到智芯设备

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#847]
你好，
      我在小米6x手机上可以搜索到智芯设备，但是在三星手机上搜索不到，大约过了5min，三星的手机又可以搜索到。同一个测试账号。
![image](https://user-images.githubusercontent.com/18459414/58447158-24f89a00-8136-11e9-9a0a-a6250ce3a500.png)
![image](https://user-images.githubusercontent.com/18459414/58447164-2c1fa800-8136-11e9-9d20-c0ad0ac59b1b.png)
![image](https://user-images.githubusercontent.com/18459414/58447175-317cf280-8136-11e9-977b-04897bfddb83.png)
请问这个bug,应该怎么处理？

**Comment by lvjie0519** [comment]
经分析确认是android app的bug, 请耐心等待米家native端解决，修复会及时回复。

**Comment by caojunhua** [comment]
好的，谢谢

**Comment by lvjie0519** [comment]
@caojunhua   使用最新apk进行测试下，谢谢。
