### ISSUE TITLE
小爱训练计划页面左上角有个x的按钮，点击无效，请去除

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#849]
环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10011/]
相关模块:[Host.ui.openXiaoAiLearnPage]

android米家app版本： 5.5.21.2测试版
ios米家app版本： buildid 为221

现象（必填）
左上角有个x的按钮，点击无效，希望能去除。
![小爱训练计划按钮无效](https://user-images.githubusercontent.com/44045029/58454577-7cf0ca00-8151-11e9-880a-949ae2f7b463.png)

**Comment by Banjiemin** [comment]
IOS线上版本没问题，

Android上米家app（5.5.21）还是有此问题 。

**Comment by Banjiemin** [comment]
补充一个问题：

同一账号下，在android上创建的训练计划，并没有同步到IOS上的插件里 ！

![20190528_1600](https://user-images.githubusercontent.com/44045029/58461741-f3e28e80-8162-11e9-9276-cdda1a901267.png)

**Comment by LiuMengzhou** [comment]
android上点击无效算是app的一个bug，当初做这个关闭按钮，就是为了在H5页面中跳转多次以后可以直接返回原生的上一个界面。

**Comment by fishle** [comment]
> 补充一个问题：
> 
> 同一账号下，在android上创建的训练计划，并没有同步到IOS上的插件里 ！
> 
> ![20190528_1600](https://user-images.githubusercontent.com/44045029/58461741-f3e28e80-8162-11e9-9276-cdda1a901267.png)

我这边看到两边修改好像是相互独立，互相不同步

**Comment by fishle** [comment]
点击退出无效会在新版修复~

**Comment by fishle** [comment]
左上角 X 点击无效的问题已修复，等新版发布后更新即可

**Comment by Banjiemin** [comment]
IOS上是好了，android最新版上还没好 。

![20190716_1046](https://user-images.githubusercontent.com/44045029/61262242-3285e400-a7b7-11e9-8869-7b9817df32a9.png)

**Comment by fishle** [comment]
是最新版的？

**Comment by Banjiemin** [comment]
是的

**Comment by fishle** [comment]
去fir下个最新包试试，可能上个版本没跟上

**Comment by Banjiemin** [comment]
Android手机：

1，我用测试版的app（刚去更新的）；
2，我用正式版的app（也是刚更新的）。

都有这样的问题，你们确定测试过吗？

**Comment by fishle** [comment]
![image](https://user-images.githubusercontent.com/17643700/61262730-d0c67980-a7b8-11e9-826f-a9e8dfdbc33e.png)

**Comment by Banjiemin** [comment]
QA手上的更新的最新版本是5.5.39,
其他开发同事手上的版本是5.5.40,
测试结果，都是有问题的（左上角多了X的图标，位置偏上，跟我截图一样） 。

**Comment by fishle** [comment]
点 X 新版是可以关闭页面的

**Comment by Banjiemin** [comment]
先不管有没有 效，这个位置也比较奇怪，请去除掉 （跟IOS一致）。
