### ISSUE TITLE
MHBluetoothLE.connect缺少对应接口

### ISSUE THREAD

**Issue by Handby** [MiEcosystem/miot-plugin-sdk#85]
startScan(durationInMillis, …serviceUUIDs)、stopScan() 也不能使用

**Comment by LiuMengzhou** [comment]
@Handby 
先查看一下[文档呢](https://miecosystem.github.io/miot-plugin-sdk/module-miot_Bluetooth.html)

**Comment by Handby** [comment]
@LiuMengzhou 
嗨。梦舟，我又仔细翻阅了一下文档确定是缺少对应的接口。MHBluetoothLE.connect这个旧接口是需要传入参数连接指定的蓝牙设备（iOS里是传identify），在固件升级中蓝牙设备进入DFU固件升级模式此时蓝牙设备的Mac地址以及serveces都发生了变化，很明显新SDK的connect方法满足不了连接指定蓝牙设备的功能的

**Comment by Copypeng** [comment]
有这个需求。两个平台蓝牙存在差异，比如安卓不能使用 identifier 。我们考虑之后给出接口。

**Comment by Copypeng** [comment]
我们预计开发至12月12日输出一个新模块来应对这个需求。

**Comment by dzonel** [comment]
请问新模块什么时候开放出来？

**Comment by Handby** [comment]
+1

**Comment by Copypeng** [comment]
更新 SDK 试一试。

**Comment by dzonel** [comment]
@Copypeng 是不输出新模块了，在当前的相关接口改是吗？

**Comment by Handby** [comment]
因为米家可以添加多个同一类型的蓝牙设备，如果都开启了长连接retrievePeripherals回来的就不知道是哪一个蓝牙设备了，iOS能否提供获取当前设备identifier的接口？

**Comment by dzonel** [comment]
Device.getBluetoothLE().connect()，无论peripheralID怎么填，都是返回连接的当前添加的设备，而不是指定peripheralID的设备。
<img width="394" alt="image" src="https://user-images.githubusercontent.com/12531667/50393430-33aae180-0791-11e9-8a28-0f615c3ba5ce.png">

![image](https://user-images.githubusercontent.com/12531667/50393444-402f3a00-0791-11e9-8302-998714733ae9.png)

**Comment by Handby** [comment]
那如何连接指定peripheralID的设备？

**Comment by Handby** [comment]
我测试是可以连接上指定peripheralID的设备（可以看系统蓝牙设置里，显示已连接），但是后续没有service和charater无法读写

**Comment by dzonel** [comment]
@Handby 你的有没有打印.then中的bluetooth？我这边是连接后返回连接成功，但是.then中打印的却是当前添加的设备，不是想要连接的指定的设备的信息。

**Comment by Copypeng** [comment]
connect 接口已确定支持连接普通BLE设备。我会在 https://github.com/MiEcosystem/miot-plugin-sdk/issues/140 中跟进连接后的 services 发现问题。

**Comment by kasparovfeng** [comment]
![image](https://user-images.githubusercontent.com/13309478/50756503-6c6daf00-1297-11e9-901c-b5aada6b32d6.png)

**Comment by kasparovfeng** [comment]
这个uuid能不能返回，不好匹配多个同一类型的蓝牙设备啊

**Comment by kasparovfeng** [comment]
哎

**Comment by kasparovfeng** [comment]
@Copypeng
