### ISSUE TITLE
蓝牙Mesh网页使用指南页面上 title重复

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#850]
环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10011/]
相关模块:[Host.ui.openBtGatewayPage

android米家app版本： 5.5.21.2测试版
ios米家app版本： buildid 为221
![mesh标题重复](https://user-images.githubusercontent.com/44045029/58454884-65661100-8152-11e9-8dca-461ffdd32093.png)

**Comment by blockdate** [comment]
并未能复现该问题，是否是在iOS和Android下都存在这个现象？

是否尝试过在线上app上测试，能否复现

**Comment by Banjiemin** [comment]
IOS线上版本OK，

Android上米家app（5.5.21）还有此问题 。

**Comment by lvjie0519** [comment]
经分析属于APP的问题，已反馈，修复这边会及时反馈。

**Comment by Banjiemin** [comment]
> 经分析属于APP的问题，已反馈，修复这边会及时反馈。

我刚才用最新版本测试了，android 上修改了，但IOS上却不正常了，都没有返回键了，怎么退出呢？

**Comment by lvjie0519** [comment]
@blockdate   看下ios问题是否存在？

**Comment by Banjiemin** [comment]
ios上米家app 版本号：4.19.2，问题还没好 ！

刚才不能退出，我只好kill掉app了，再进app，想截图给你们看看的，蓝牙网关进不去了 。

**Comment by santcool** [comment]
我这边看到已解决了，你可以在github下载最新的测试包试试看
![image](https://user-images.githubusercontent.com/8580061/61593353-003e1180-ac11-11e9-8716-43b90de51a43.png)
