### ISSUE TITLE
Android上commonSetting里的法律信息页面没有title(IOS有)

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#851]
环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10011/]
相关模块:[Host.ui.openXiaoAiLearnPage]

android米家app版本： 5.5.21.2测试版
ios米家app版本： buildid 为221

现象（必填）
Android上commonSetting里的法律信息页面没有title(IOS有)

希望能加上 。

![法律信息没有标题](https://user-images.githubusercontent.com/44045029/58454999-bf66d680-8152-11e9-80b5-46be41fdcd03.png)

**Comment by blockdate** [comment]
这个已经在改版中，下一版会进行统一，不需要插件设置了。

**Comment by mirse** [comment]
安卓，设备时区、法律信息没有标题栏     iOS智能场景、安全设置的设置密码页没标题

**Comment by santcool** [comment]
iOS智能场景已增加标题，安全设置页勿需标题。用户协议和隐私政策已统一

**Comment by zanetti4** [comment]
#1014

**Comment by lvjie0519** [comment]
已修复，相同问题， 请使用最新apk进行测试，谢谢，有问题再1014进行跟踪。
https://github.com/MiEcosystem/miot-plugin-sdk/issues/1014
