### ISSUE TITLE
原来插件中的APNS事件监听没有了,新插件中有没有替代的方案?

### ISSUE THREAD

**Issue by georgeChina** [MiEcosystem/miot-plugin-sdk#852]
---
**公司名称（必填）**
卡麦

**是否为新产品（必填）**
"否"

**产品名称/Model（必填）**
lcrmcr.safe.an35sidz,
lcrmcr.safe.an35sizw

**环境（必填）**
- 电脑操作系统:[eg.Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master]
- 相关模块:[eg.*]

**现象（必填）**
原来的插件中有一个APNS事件监听:
    //监听ＡＰＮＳ推送
    this.APNSsubscription = DeviceEventEmitter.addListener(MHPluginSDK.onReceivingForegroundPushEventName, (notification) => {
      // 插件在前台收到push的通知回调
      console.log("APNS:", notification);
   //todo...
    });
新的插件中没有了这个监听事件了.

**期望（必填）**
产品是个蓝牙保险箱,需要一个异常报警的功能.保险箱哪里有个异常报警通过网关上送米家,米家要推送给手机,并且插件中需要有个事件来监听,从而来拉取最新的异常上报事件,显示出来.

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
在Android旧的原生插件下面是通过何种方式实现的。

**Comment by georgeChina** [comment]
旧插件,就是在主页面中监听
this.APNSsubscription = DeviceEventEmitter.addListener(MHPluginSDK.onReceivingForegroundPushEventName, (notification) => {
// 插件在前台收到push的通知回调
console.log("APNS:", notification);
//todo...在这里获取设备的上报事件的最新值,并去刷新页面
    MHPluginSDK.callSmartHomeAPI('/user/get_user_device_data', params, (response) => {
      console.log("user_device_data get warning:", response);
      if (response.message === "ok") {
       刷新页面
      }
    });
});

**Comment by blockdate** [comment]
我问的是Android的插件

**Comment by georgeChina** [comment]
原来安卓是原生写的,安卓同事给的大概流程:
1.订阅时间:// 订阅事件信息，每次只维持3分钟订阅事件
    public void subscribeEvent(String[] events, Callback<Void> callback) {
        ArrayList<String> eventList = new ArrayList<String>();
        for (String event : events) {
            if (event.startsWith("event.")) {
                eventList.add(event);
            } else {
                eventList.add("event." + event);
            }
        }
        XmPluginHostApi.instance().subscribeDevice(getDid(), mDeviceStat.pid, eventList, 3,
                callback);
    }
2.在MessageReceiver.java中 handleMessage()会收到回调:
       if ("DevicePush".equals(msgType)) {// 订阅的消息
                    String data = intent.getStringExtra("data");
                    Device device = Device.getDevice(deviceStat);
                    device.onSubscribeData(data);
                }
3.Device.java :
// 收到订阅的信息
    public void onSubscribeData(String data) {
             }

**Comment by blockdate** [comment]
这个需要新增AP以及Native功能更新支持，我们这边讨论看如何支持下。

**Comment by blockdate** [comment]
@georgeChina  我这边看了下，你这边的需求是要监听设备的 event 事件推送么。参考下[设备事件属性订阅](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/05-%E6%8F%92%E4%BB%B6%E8%AE%BE%E5%A4%87%E6%A8%A1%E5%9D%97#module_miot/Device--module.exports.IDeviceWifi+subscribeMessages),看是否满足需求

**Comment by santcool** [comment]
长时间未响应，暂时关闭。
