### ISSUE TITLE
RkSwitchoff时显示不正确。

### ISSUE THREAD

**Issue by brockliu1010** [MiEcosystem/miot-plugin-sdk#853]
**公司名称（必填）**
飞利浦

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
philips.light.sread1

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1/
- SDK分支: master/10002/
- 相关模块:react-native-ui-kitten

**现象（必填）**
RkSwitch 在进入页面component时，为off，背景为白色。
RkSwitch 在进入页面component时，设置为on时，一段时间后更新状态为off，背景为灰色。

**期望（必填）**
off时背景一直为白色。

**其他的上下文/日志/截图**
                            <RkSwitch
                                thumbTintColor='#eee'
                                tintColor='#eee'
                                rkType='success'
                                style={styles.switch}
                                value={this.state.night}
通过修改this.state.night，改变switch状态。

**尝试过的解决办法**
尝试更改tintColor颜色，没有解决。

**Comment by LiuMengzhou** [comment]
@brockliu1010 
 可以用SDK提供的Switch组件
SDK_10020, `miot/ui/Switch`

**Comment by lvjie0519** [comment]
请使用  SDK_10020, miot/ui/Switch， 如有问题再reopen，谢谢。
