### ISSUE TITLE
connect（）timeout最短时间是多少

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#854]
设备dfu之后使用
1、retrievePeripheralsWithServicesForIOS查找设备；
2、Bluetooth.createBluetoothLE(key)创建蓝牙实例；
3、调用connect(type,{forceReconnect:true}) 等待几秒之后返回code = -7；
4、执行bt.disconnect(0)；

---
**公司名称（必填）**
Philips

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
米家飞利浦夜灯

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
设备dfu之后，进行disconnect，需要先connec（），而该过程需要时间，该时间段内用户操作无效(该时段内用户可能按夜灯按钮重连)
**期望（必填）**
缩短connect()时间或者能否提供最快  断连  重连  流程。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by 123start** [comment]
使用 react-native-nordic-dfu 进行的dfu

**Comment by blockdate** [comment]
-7 表示你传入的type不为3，建议使用 connect(3,{forceReconnect:true}) 再试试

或者直接 connect(type,{forceReconnect:true， timeout:1000}) 指定超时时长
