### ISSUE TITLE
iOS切换国家后连接已绑定设备时，提示“Failed to initialize device (3)”

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#856]
1、切换国家之后，直接点击该账号下原有的车辆进行连接，就会出现该弹窗。

![Pasted Graphic 2](https://user-images.githubusercontent.com/1590420/58464515-64d87500-8168-11e9-8704-8e97c6bba9e5.png)

2、切换国家之后，如果把原有的车辆删除，重新添加车辆就可以添加并且连接成功

model: ninebot.scooter.v2

注：从中国切换到英国、意大利，等。都有此问题

**Comment by blockdate** [comment]
切换国家之后，设备列表并不共享，应该会被初始化。

这个问题是稳定复现的么，提供下app的版本，如果是测试版，提供下首页icon的编号

**Comment by Woody2016** [comment]
请注明下是从“哪个国家”切换到“哪个国家” 时才会出现此问题

**Comment by dan-huang** [comment]
主题中已添加具体国家。 @Woody2016

**Comment by blockdate** [comment]
确认下问题
1. 从中国切换到英国，设备列表没有变化么
2. 提供下公司名称，设备名称等，我们这边看下有没有可以测试的设备，尝试重现下

**Comment by dan-huang** [comment]
1. 没有变化，中国连接过的设备仍然显示；
2. 设备名称是米家电动滑板车，公司名称应该是纳恩博。

@blockdate

**Comment by dan-huang** [comment]
@blockdate 请问下这个问题有进展吗- -

**Comment by zanetti4** [comment]
@santcool 请协助查看此问题

**Comment by dan-huang** [comment]
@zanetti4 @santcool 请问下这个问题有进展吗～

**Comment by dan-huang** [comment]
@zanetti4 @santcool 请问下这个问题有进展吗- -

**Comment by santcool** [comment]
问题已解决，请使用最新SDK_10024验证。
