### ISSUE TITLE
调用三方接口

### ISSUE THREAD

**Issue by JiuanZbf** [MiEcosystem/miot-plugin-sdk#857]
**公司名称（必填）**
iHealth

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
"model": "ihealth.bpm.kd5907“

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: [master]
- 相关模块:[miot/service/smarthome]

**现象（必填）**
调用这个方法时miot/service/smarthome.callThirdPartyAPI(params)
报{
  "code": -8,
  "msg": "invalid retry_time",
}
上述反馈

**期望（必填）**
因为我们之前有一款产品后台已对接过产品model:ihealth.bp.bpm1
想访问上述那个model已对接过的接口

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
使用已对接model访问同一接口可以访问到，但是用新model的插件使用同样参数就是不行

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
提供下param参数，如果参数中含有隐私信息，请发送邮件至wulei7@xiaomi.com

**Comment by JiuanZbf** [comment]
邮件已发送，请查收，谢谢。

**Comment by JiuanZbf** [comment]
您好，有答复吗。

**Comment by JiuanZbf** [comment]
您好，我这边

**Comment by JiuanZbf** [comment]
您好，我这边 现在可以看到输出出我们后台的会调了 但是sdk内部没有给我返回结果 提示的是
Possible Unhandled Promise Rejection (id: 2):
Object {
  "message": "callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-8 \"(null)\" UserInfo={message=invalid retry_time, result=false, code=-8}",
}
但是我这边将sdk版本切换到10000就可以 当前是10011

**Comment by blockdate** [comment]
这边检查了一下，10010与10011下的实现并无区别。

1. -8表示你的参数传递有问题
2. invalid retry_time 是接收服务端第一次返回时，根据返回的retry_time 进行第二次请求，这边需要分享下设备到 894158105，同时提供详细的参数请求，之前发送的参数中有自定义的字段，我这边无法复现。

**Comment by blockdate** [comment]
该情况已处理，修复SDK为 10011 及以上

**Comment by JiuanZbf** [comment]
好的，多谢，更新sdk后验证成功 可以用
