### ISSUE TITLE
getDevicesConfig与getRangeOpenConfig等接口适配问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#858]
公司名称
青岛亿联客信息技术有限公司

是否为新产品
否

产品名称/Model
yeelink.light.ceiling12(不限于该model)

环境
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 6.0/iOS 12.2]
- SDK分支: [master]
- 相关模块:[Service]

现象
1、文档中有提到getDevicesConfig已经废弃，推荐使用batchGetDeviceDatas。在调试batchGetDeviceDatas时提示”no valid did“。
![image](https://user-images.githubusercontent.com/9053681/58468313-e7b0fe00-816f-11e9-9aa4-45c340fd82cc.png)
入参为param为{did: "91294457",limit: 20,offset: 0,prefix: "user_scene_"}。

2、getRangeOpenConfig(包括)该接口返回数据格式与旧接口不一样，旧接口返回数据格式为
![image](https://user-images.githubusercontent.com/9053681/58467207-cb13c680-816d-11e9-9213-233352ffd3a5.png)

而现在则是
![image](https://user-images.githubusercontent.com/9053681/58467210-cea74d80-816d-11e9-8a34-f4c0c5dc7417.png)

期望
1、期望能返回正确数据；
2、期望返回数据格式与旧接口保持一致。

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法
尝试过哪些操作？

不要贴大段代码❗️

**Comment by santcool** [comment]
新旧接口是不兼容的，这个得你们自己适配下。

**Comment by TheWalkingDead1024** [comment]
> 新旧接口是不兼容的，这个得你们自己适配下。

请问getRangeOpenConfig这个接口数据结构有发生过变化么？因为米家新框架上一两天前还是好用的，不知道是后台返回数据格式发生了变化还是有什么其他原因？

**Comment by blockdate** [comment]
@TheWalkingDead1024 你是指以前的返回格式带有code 和 message， 现在的直接就是result中的返回数据么

**Comment by TheWalkingDead1024** [comment]
> @TheWalkingDead1024 你是指以前的返回格式带有code 和 message， 现在的直接就是result中的返回数据么

嗯嗯，是的。不管是生产环境米家还是beta米家（版本号也没变过）都有这个问题，怀疑是后台数据格式发生了变化，但是我们用米家旧SDK返回数据是正常的。

**Comment by blockdate** [comment]
我这边排查下接口返回，发布一个修复版本，将数据格式配置成你需要的样式

**Comment by TheWalkingDead1024** [comment]
> 我这边排查下接口返回，发布一个修复版本，将数据格式配置成你需要的样式，稍后在线上或者测试app中打开一两次插件之后，问题应该就可以修复了。

好的，非常感谢您啦。

**Comment by TheWalkingDead1024** [comment]
> 我这边排查下接口返回，发布一个修复版本，将数据格式配置成你需要的样式，稍后在线上或者测试app中打开一两次插件之后，问题应该就可以修复了。

还有第一个问题麻烦您帮忙看一下。我传的参数都是按照文档来的，为什么还会提示我no valid did呢？

**Comment by blockdate** [comment]
batchGetDeviceDatas 是一个新的接口了，param需要更换

`let params = {'did':Device.deviceID, 'props': [   
      "prop.s_push_switch"
      ]}   
  Service.smarthome.batchGetDeviceDatas([params]).then(...)`

**Comment by TheWalkingDead1024** [comment]
> batchGetDeviceDatas 是一个新的接口了，param需要更换
> 
> `let params = {'did':Device.deviceID, 'props': [ "prop.s_push_switch" ]} Service.smarthome.batchGetDeviceDatas([params]).then(...)`

嗯嗯，我看到过这个要求。但是我那里是这样的{did: "91294457",limit: 20,offset: 0,prefix: "user_scene_"}几个键值对，怎么采用新的格式呢？新的格式是prop的一个数组，和我这个字典类型没办法转换呀？

**Comment by blockdate** [comment]
你可能理解误差了
1. batchGetDeviceDatas 也是用来存储kv数据的接口，与旧接口并没有数据上的兼容，只是性能方面更优，建议切换使用。
2. 这边batchGetDeviceDatas 并不能获取到 getDevicesConfig 的已有数据，建议自行获取之后转移一下。

**Comment by TheWalkingDead1024** [comment]
> 你可能理解误差了
> 
> 1. batchGetDeviceDatas 也是用来存储kv数据的接口，与旧接口并没有数据上的兼容，只是性能方面更优，建议切换使用。
> 2. 这边batchGetDeviceDatas 并不能获取到 getDevicesConfig 的已有数据，建议自行获取之后转移一下。

嗯嗯，谢谢您的解释。
1、之前已经我们提过issue，你们也和我们确认过数据确实是不兼容的。这个我们目前是没有异议的；
2、目前问题是，我现在用新接口去获取数据，我们写的参数您也看到了，应该是符合要求的，但是提示的是”no valid did“，这个设备did是正确的，不知道为什么提示这个错误。拉取数据之前我也调用了batchSetDeviceDatas去存储数据，入参是下图，
![image](https://user-images.githubusercontent.com/9053681/58536255-88f88c80-8222-11e9-8374-473addbf0f60.png)

callback返回了一个true，应该是成功了，说明写数据是成功的。现在是读数据接口提示感觉有问题，再麻烦您帮忙看一下。

**Comment by blockdate** [comment]
没看错参数不符合要求把。

你传入的是 `{did: "91294457",limit: 20,offset: 0,prefix: "user_scene_"}` 

要求的是 ` { 'did':Device.deviceID, 'props': [ "prop.s_push_switch" ] } ` ,props的命名需要以 ‘prop.s_’开头

**Comment by TheWalkingDead1024** [comment]
> 没看错参数不符合要求把。
> 
> 你传入的是 `{did: "91294457",limit: 20,offset: 0,prefix: "user_scene_"}`
> 
> 要求的是 `{ 'did':Device.deviceID, 'props': [ "prop.s_push_switch" ] }` ,props的命名需要以 ‘prop.s_’开头

嗯嗯，谢谢您的回复。
1、我是需要{did: "91294457", prop.s_limit: 20, prop.s_offset: 0, prop.s_prefix: "user_scene_"}
这样来传，还是
{did: "91294457", 'props':{prop.s_limit: 20, prop.s_offset: 0, prop.s_prefix: "user_scene_"}}。这样来传入呢？因为感觉文档确实写的不是太清晰。
2、还有个问题就是为什么错误提示是写的”no valid did"呢？
麻烦您再帮忙看看啦，谢谢。

**Comment by blockdate** [comment]
props 的数组表示要获取的键值对的key的数组，不知道这样表述是否清晰，你可以参考一下Demo->教程->与服务器交互 中查看这两个函数的使用

**Comment by TheWalkingDead1024** [comment]
> props 的数组表示要获取的键值对的key的数组，不知道这样表述是否清晰，你可以参考一下Demo->教程->与服务器交互 中查看这两个函数的使用

嗯嗯，非常感谢您的回复。我能理解您说的props数组是要获取的键值对，但是之前已经和您说过了，我这里是要传参数的，您已经也看到了，limit表示一次拉取最大20条，offset表示偏移量等等，能麻烦您再看一下吗，谢谢啦。

**Comment by TheWalkingDead1024** [comment]
> props 的数组表示要获取的键值对的key的数组，不知道这样表述是否清晰，你可以参考一下Demo->教程->与服务器交互 中查看这两个函数的使用

你好，这个旧接口之前是有大小分页限制的，所以才有分页这些参数。新接口没有大小限制了么？可以一次性拉取所有数据么？

**Comment by TheWalkingDead1024** [comment]
> props 的数组表示要获取的键值对的key的数组，不知道这样表述是否清晰，你可以参考一下Demo->教程->与服务器交互 中查看这两个函数的使用

你好，我现在理解就是新接口没有去兼容旧接口参数了，是我之前理解有误，sorry。现在有个疑问是，如果某个属性的value是一个很大的数据，会有分页操作么？

**Comment by blockdate** [comment]
没有，新的 接口是属于纯 kv存储，不涉及分页。

**Comment by TheWalkingDead1024** [comment]
> 没有，新的 接口是属于纯 kv存储，不涉及分页。

好的，谢谢。

**Comment by TheWalkingDead1024** [comment]
> 没有，新的 接口是属于纯 kv存储，不涉及分页。

大佬，你好。冒昧的问一下，getRangeOpenConfig返回数据格式与旧接口不一样这个问题，大概多久可以解决呢，😋

**Comment by blockdate** [comment]
这个已经处理了

**Comment by DennisJu007** [comment]
@blockdate 大佬你好，目前使用YLSmartHome.rangeGetOpenConfig请求收藏数据，当前返回数据格式还是：
![1560925308011](https://user-images.githubusercontent.com/42829167/59744243-b6c27580-92a4-11e9-8646-c432a6b03ad9.jpg)
实际上旧框架用的是这种数据格式：
![2](https://user-images.githubusercontent.com/42829167/59744398-0e60e100-92a5-11e9-9ca1-004ad213dd30.jpg)
嗯咱这边说修复了是指修复了这个数据格式吗，是新框架通用都要使用第一张图片这种格式么
