### ISSUE TITLE
react-native-nordic-dfu 进行的dfu android需要20s以上才开始升级，iOS三五秒就开始，能否进行优化

### ISSUE THREAD

**Issue by 123start** [MiEcosystem/miot-plugin-sdk#859]
react-native-nordic-dfu 进行的dfu android需要20s以上才开始升级，iOS三五秒就开始，能否进行优化

**公司名称（必填）**
Philips

**是否为新产品（必填）**
否
**产品名称/Model（必填）**
米家飞利浦蓝牙夜灯

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
Android使用react-native-nordic-dfu 进行的dfu，启动后需要20秒以上才开始

**期望（必填）**
针对Android优化，缩短升级时间

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@123start   我们这边只是简单的集成了该库， 请你那边单独用一个RN工程，使用react-native-nordic-dfu升级是否存在相同现象？

**Comment by fishle** [comment]
麻烦用rn-nodrc-dfu这个tag过滤一下log，我们看下哪里比较慢

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，  如有需要配合排查在reopen。
