### ISSUE TITLE
TitleBarBlack中onPressRight2的图标怎么修改？

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#86]
您好，这个图标是不能自定义吗？

![1543576871187](https://user-images.githubusercontent.com/12531667/49286454-2d4c8100-f4d5-11e8-9905-ecd08c76e57d.jpg)

**Comment by LiuMengzhou** [comment]
@dzonel 
源码都在这里啦，你可以自己替换图片文件的

**Comment by dzonel** [comment]
@LiuMengzhou 在这里改动源码的话，之后打包的话会带上这里的改动吗？

**Comment by dzonel** [comment]
好的，谢谢。
