### ISSUE TITLE
无网络时，使用撤销授权功能后，没有提示信息

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#860]
**公司名称（必填）**
舒可士（深圳）科技有限公司

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
米家声波电动牙刷M1S          soocare.toothbrush.m1s

**环境（必填）**
- 手机系统:[iOS]

**现象（必填）**
无网络时，使用撤销授权功能，没有提示信息

**期望（必填）**
无网络时，使用撤销授权功能，可以弹出有效提示信息

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/48087638/58471750-2a2a0900-8177-11e9-9a52-06aafec066b9.png)

**Comment by blockdate** [comment]
这是米家app的问题，已提交内部issue处理，与插件开发者关系不大，问题关闭。
