### ISSUE TITLE
（紧急）点击“撤销使用条款和隐私政策授权”后，返回页面有误  P18-0138 

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#861]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S
soocare.toothbrush.m1s

环境（必填）
手机系统:【Android】

现象（必填）
点击“撤销使用条款和隐私政策授权”后，返回至插件页面，且仍然可以使用插件功能。

期望（必填）
点击“撤销使用条款和隐私政策授权”后，返回至米家首页

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/48087638/58485310-5c972e80-8196-11e9-846f-95a938a2e07c.png)

**Comment by blockdate** [comment]
你这是Android的吧，app版本是多少

**Comment by huangjr126** [comment]
@blockdate 是安卓，5.5.21

**Comment by lvjie0519** [comment]
线下沟通，已解决，建议监听 PackageEvent.packageAuthorizationCancel 该事件。
