### ISSUE TITLE
蓝牙连接失败后，会自动连接牙刷蓝牙并且不断开

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#862]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S
soocare.toothbrush.m1s

环境（必填）
手机系统:【IOS】

现象（必填）
1、启动牙刷，使其无法被蓝牙连接
2、进入插件，进行下拉同步数据
3、显示蓝牙连接超时后，将牙刷停止或暂停
4、查看牙刷蓝牙状态，会自动连接并不断开

期望（必填）
牙刷不会自动进行蓝牙连接

**Comment by santcool** [comment]
有几点我们不太懂，你看看能不能给解答下：
1.启动牙刷，怎么使其无法被蓝牙连接，此牙刷，是否已经被添加到设备列表？
2.进入插件，既然还未连接，怎么下拉同步数据？进入插件，不是先连接蓝牙吗？
3.你的期望是不会自动进行蓝牙连接，是指哪一步操作的时候，不会自动连接？

**Comment by huangjr126** [comment]
@santcool

**Comment by huangjr126** [comment]
@santcool 
1、首先在米家首页中添加绑定“米家声波电动牙刷”，然后成功进入插件后，启动牙刷（模拟一个插件无法连接牙刷的环境）。
2、在牙刷震动当中，在插件首页执行下来同步操作，20秒后会出现“蓝牙连接超时”的提示信息。
3、出现“蓝牙连接超时”后，将牙刷关闭震动。这时正常情况是插件不会再次尝试蓝牙连接，而实际情况则是插件会再次进行蓝牙连接且连接成功后不会断开。

**Comment by santcool** [comment]
连接蓝牙，你们执行的哪个方法，还有执行同步操作，你们调用的是哪个方法？我根据这两个方法去查一下

**Comment by huangjr126** [comment]
@santcool
 Device.getBluetoothLE().connect(0，{timeout: 15000})

**Comment by santcool** [comment]
我们找了下代码，并没有自动重连。怀疑是“模拟插件无法连接牙刷的情况”这一步出了问题，或者说系统已经记住需要连接这个蓝牙了，我们的代码无法控制。

**Comment by Woody2016** [comment]
@huangjr126 

这个问题只在iOS平台下出现，android呢？

插件框架这块，不会做蓝牙连接失败重连，所以你们反馈的这个重连问题，大概率是插件里自己做了什么逻辑导致，请仔细检查插件代码先

**Comment by JxXiaoXie** [comment]
@Woody2016 

ios，android都会出现。

插件逻辑没有问题，我们这边执行connect操作后，你们回调超时后，我们就在界面显示连接设备超时，并没有再做重连操作。

**Comment by santcool** [comment]
问题是否依旧存在？你们之前是否曾给武汉小米邮寄过此种设备？如果没有，请邮寄一个设备到武汉小米，我们需要用真实设备调试此问题，谢谢！
