### ISSUE TITLE
使用红米3的手机测试sdk的更多设置，里面的选项文字看不见

### ISSUE THREAD

**Issue by heping99** [MiEcosystem/miot-plugin-sdk#863]
**公司名称（必填）**
上海小寻科技有限公司

**是否为新产品（必填）**
是

**产品名称/Model（必填）**
xiaoxun.watch.sw760

**现象（必填）**
使用红米3的手机测试sdk的更多设置，里面的选项文字看不见，功能可以使用

**期望（必填）**
使用红米3的手机测试sdk的更多设置，可以看见每个选项的文字

**Comment by blockdate** [comment]
这边是否使用了某些字体？

**Comment by lvjie0519** [comment]
1、麻烦截个图，看下具体是哪个页面？
2、检查下是否对字体设置了颜色值？

**Comment by lvjie0519** [comment]
暂时关闭，有问题再reopen。

**Comment by lvjie0519** [comment]
暂时关闭，有问题再reopen。
