### ISSUE TITLE
shareSecureKey 返回 key already shared to target user 改进建议

### ISSUE THREAD

**Issue by mny459** [MiEcosystem/miot-plugin-sdk#864]
**公司名称（必填）**
陨石科技

**是否为新产品（必填）**
否

**产品名称/Model（必填）**
M1智能锁/yunshi.lock.s2

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:  与手机系统无关
- SDK分支: 10011
- 相关模块: [API 地址](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/17-%E7%B3%BB%E7%BB%9F%E6%9C%8D%E5%8A%A1_%E5%AE%89%E5%85%A8%E6%A8%A1%E5%9D%97#module_miot/service/security--module.exports.shareSecureKey)

**现象（必填）**
调用 `shareSecureKey` 重复分发权限给一个用户会返回 `key already shared to target user` 的错误，但实际对用户的权限做了修改

**期望（必填）**
对用户对权限做修改并返回成功；或者返回error 可以有错误表作为参照，包含 code 和 message 以防止 message 以后出现变化

**其他的上下文/日志/截图**
e

**尝试过的解决办法**
目前仅能根据 `key already shared to target user` 这个字符串强行判断这个情况并作出相关提示

**不要贴大段代码❗️**

**Comment by santcool** [comment]
现在我们这边有这个判断，正常情况下服务端会给一个keyid，然后我们就能够返回一个ISecureKey对象。此种情况服务端只给了一个ok，无法生成ISecureKey对象
if (ok && res == 'ok') {
       //如果res为ok，则表示该用户已经被分享过
      return reject('key already shared to target user')
}

**Comment by mny459** [comment]
> 现在我们这边有这个判断，正常情况下服务端会给一个keyid，然后我们就能够返回一个ISecureKey对象。此种情况服务端只给了一个ok，无法生成ISecureKey对象
> if (ok && res == 'ok') {
> //如果res为ok，则表示该用户已经被分享过
> return reject('key already shared to target user')
> }

这个情况目前为是知道的，只是担心后面你们开发有没有可能修改 `key already shared to target user`  这个字符串导致客户端这边的判断会失效，所以我提了个建议就是以 code 和 message 的形式返回，这样后期你们如果可能添加其他的错误的话客户端这边也方便修改，但是如果你能保证这个字符串不会变的话那这个也就不是问题了。

**Comment by santcool** [comment]
懂了。这个确实不合理，我们给一个code吧，message依旧用这个

**Comment by santcool** [comment]
此处改为：return reject({ code: -1, message: 'key already shared to target user' })
放在SDK_10020版本
看看有没有问题，如果有，尽快回复，如果没有，请关闭issue
