### ISSUE TITLE
智能触发结果异常

### ISSUE THREAD

**Issue by mny459** [MiEcosystem/miot-plugin-sdk#866]
**公司名称（必填）**
陨石科技

**是否为新产品（必填）**
若是旧框架插件迁移相关，请填"否"

**产品名称/Model（必填）**
M1智能锁/

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统: Android 9 iOS12.3.1
- SDK分支: 10011
- 相关模块: 

**现象（必填）**
创建一个智能场景 关锁(M1智能锁)-打开摄像头(米家智能摄像机1080P)，实际操作结果是关锁成功，摄像头打开，但是2s左右以后，摄像头又关闭了。

**期望（必填）**
关锁-打开摄像头，不会自动关闭。在这里同时想确认一下现在智能场景的实现逻辑，因为之前我们的M1锁在智能场景中的使用逻辑是操作锁之后，由蓝牙网关来分发事件，也就是说必须要有蓝牙网关在附近。现在测试发现脱离蓝牙网关M1锁也可以实现智能场景，是不是可以理解为M1的开关锁会被上报到后台，由后台来分发智能场景的事件呢？如果是后者，我怀疑是不是后台多下发了一次事件呢，麻烦解答一下，谢谢

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by mny459** [comment]
根据 #647 的描述，似乎是要为智能场景配置如下属性, trigger_ids 里的值是自动化设置里的id。这边实际测试发现，配置与不配置对于我来说似乎没有什么特殊区别，所以想要请教一下，这个配置项所起到的作用是什么呢，是否是必须的呢？麻烦解答一下，谢谢
```
  "entrance_scene": {
    "action_ids": [],
    "trigger_ids": [
      573,
      554,
      567,
      568
    ]
  }
```

**Comment by santcool** [comment]
1.一般智能场景都是有后台分发智能事件。你的意思是蓝牙网关会下发一次智能事件，同时后台也会下发一次，导致摄像头打开又关闭？
2.此配置为必须的。为了解决RN插件版本兼容的问题，防止使用老的app里面的旧的RN插件，无法打开对应action/trigger页面的情况。

**Comment by mny459** [comment]
> 1.一般智能场景都是有后台分发智能事件。你的意思是蓝牙网关会下发一次智能事件，同时后台也会下发一次，导致摄像头打开又关闭？
> 2.此配置为必须的。为了解决RN插件版本兼容的问题，防止使用老的app里面的旧的RN插件，无法打开对应action/trigger页面的情况。

1.  所以是不是可以理解客户端都操作被自动上传了。
2. 存在蓝牙网关和不存在蓝牙网关都会出现摄像头开启，2s左右又关闭。因为我是接手这个项目，所以我获取到的内容是，我们的M1必须在有网关存在的情况下才能使用智能，而现在测试发现没有也可以，所以确认一下逻辑。
3. 请教一下action对应的id是在哪里配置的呢？担心自己有所遗漏

**Comment by santcool** [comment]
1.那看来我的第一条理解是错误的。打开2s后又关闭，看样子得找一下你们嵌入式的同学，看看是不是因为服务端下发两次指令导致的。你也可以换个android手机试试，看看是不是移动端这边的问题。
2.在这个页面

**Comment by mny459** [comment]
> 1.那看来我的第一条理解是错误的。打开2s后又关闭，看样子得找一下你们嵌入式的同学，看看是不是因为服务端下发两次指令导致的。你也可以换个android手机试试，看看是不是移动端这边的问题。
> 2.在这个页面：并且在里面有个扩展程序参数需要配置，可以用方法名啥的。
> ![image](https://user-images.githubusercontent.com/8580061/58632051-1ddcb200-8317-11e9-996e-449a55f70b89.png)

1. 应该是我的描述不完整导致您的理解还是有偏差。
    - 首先，手机换过，小米8、小米note3、苹果7，苹果7p，系统都是最新版本
    - 第二，我们的 M1锁 只能蓝牙操作，不能联网的，所以我的理解是，M1锁执行成功，返回给手机端，手机端将事件上报给了米家后台，米家后台下发智能事件。按照您的意思的话，是手机端上报了两次事件？可是事件上报不是SDK内部控制的吗？而且，上面说的事件问题不是必现的，偶尔表现正常，但却是高频的

2. 截图那个不是 triggerid 吗？是我理解错了吗？

**Comment by santcool** [comment]
图中的类型if对应着triggerid, then对应着actionid。还有两点需要你确认下：1.你如果选择手动执行，也会执行打开2s后又关闭吗？2.是否能不使用蓝牙网关触发智能锁的自动化操作？

**Comment by mny459** [comment]
1. 手动执行，不会触发任何智能
2. 隔了周末两天来试发现：一开始在没有蓝牙网关的情况下无法触发智能；在加入蓝牙网关后触发了蓝牙智能，但是发生了2s左右后关闭的情况(偶现)；之后在去掉蓝牙网关，也可以触发智能

**Comment by santcool** [comment]
去掉蓝牙网关还会触发智能，你们的锁是双模的吗？要不然，肯定是蓝牙锁的硬件自动执行智能。建议先从这一点查一下

**Comment by mny459** [comment]
对于您双模的具体概念不是很清楚。我介绍一下吧，M1锁是只能通过蓝牙和自身触摸控制的，自身不能连接网络，所以我的测试情况都是如您锁描述的 通过手机通过蓝牙直接连上智能锁并且能下发事件

**Comment by santcool** [comment]
相关同事在看这个问题了，有结果我会及时通知你哈

**Comment by mny459** [comment]
目前因为这个问题RN重构版本还没有上线，但是用户反馈旧版本有诸如收不到通知，无法触发智能的问题，想问这个问题预期什么时候会解决呢？

**Comment by santcool** [comment]
@mny459 你们能否先看看otlog，有没有多发一条休眠命令，如果有找出来谁发的就可以了，如果没有，那就比较麻烦了，需要看摄像头的log，看看为什么休眠了。另外，用户UID多少，只有这一个摄像头是这样的吗？我们也去后台查查看

**Comment by mny459** [comment]
能微信具体聊吗？我的就是mny459

**Comment by mny459** [comment]
这个问题无疾而终了？怎么就关了呢？
