### ISSUE TITLE
react-native-image-picker 在Android中不能正常工作

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#867]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家电子体温计

**项目ID（必填）**
913

**企业名称（必填）**
秒秒测
**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[eg.Android 9]
- SDK分支: [eg.master/10011/]
- 相关模块:[eg.react-native-image-picker]

**现象（必填）**
react-native-image-picker 在Android上拍照，选择图片成功后没有调用回调，xiaomi.demo上也是一样的现象，取消拍照有回调，iOS上正常

**期望（必填）**
能够正常使用拍照，图库等功能。

**Comment by Android-yzhang** [comment]
没有权限也没有提示

**Comment by zanetti4** [comment]
@lvjie0519 [#939](https://github.com/MiEcosystem/miot-plugin-sdk/issues/939) 也是这个问题，请你协助查看。

**Comment by lvjie0519** [comment]
@Android-yzhang   @zanetti4   问题已修复，  请使用最新apk进行测试。

**Comment by zanetti4** [comment]
@Android-yzhang 使用最新的 apk 测试，已经能够成功执行回调函数了。你测试一下，如没有问题请关闭此 issue

**Comment by Android-yzhang** [comment]
OK啦，谢谢
