### ISSUE TITLE
能否提供设置MTU的接口？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#868]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
AirDots蓝牙耳机

**企业名称（必填）**
猎声电子

**现象（必填）**
使用BLE进行OTA的时候，需要设置MTU值，以缩短OTA时间，阅读文档没有发现可以设置MTU值的接口。

**期望（必填）**
能够设置BLE的MTU值。例如在Android原生代码：

    private boolean requestMTU(int mtu) {
        if (mBluetoothAdapter == null) {
            Log.w(TAG, "Request MTU cannot be processed: BluetoothAdapter is null.");
            return false;
        }
        if (mBluetoothGatt == null) {
            Log.w(TAG, "Request MTU cannot be processed: BluetoothGatt is null.");
            return false;
        }

        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            boolean done = mBluetoothGatt.requestMtu(mtu);
            Log.d(TAG, "Request read remote RSSI dispatched to system: " + done);
            return done;
        }
        else {
            Log.w(TAG, "Request MTU cannot be processed: requires at least Android Lollipop API 21.");
            return false;
        }
    }

**Comment by blockdate** [comment]
我们这边评估下

**Comment by blockdate** [comment]
这边 因为iOS是不支持修改的，同时由于Android的机型等问题过于繁杂，不建议开放此功能，建议适配系统默认的。
