### ISSUE TITLE
米家牙刷插件，“位置管理”页面，所显示语种有误

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#869]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S
soocare.toothbrush.m1s

环境（必填）
手机系统:【Android & IOS】

现象（必填）
米家语言设置为英语，绑定米家声波电动牙刷并进入插件，进入设置页面点击“位置管理”，所显示内容为中文。

期望（必填）
米家设置为英语时，“位置管理”内容显示也应该为英语。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/48087638/58550727-00d5af80-8241-11e9-8d04-353b2f22c052.png)
![image](https://user-images.githubusercontent.com/48087638/58550734-0632fa00-8241-11e9-8bc1-ac6bfdba2bbb.png)

**Comment by santcool** [comment]
这些名字都是用户自己输入的，或者是在绑定插件是自己选的。你可以试试，在英文环境下，绑定设备成功后，绑定到一个中文房间。之前也有人质疑，但是忽略了设备是在中文环境下绑定的，此处逻辑没有问题
