### ISSUE TITLE
米家牙刷插件，设备无法共享给微信好友

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#870]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S
soocare.toothbrush.m1s

环境（必填）
手机系统:【Android & IOS】

现象（必填）
绑定米家声波电动牙刷并进入插件，进入设置页面点击“设备共享”，共享给微信好友，提示分享失败。

期望（必填）
绑定米家声波电动牙刷并进入插件，进入设置页面点击“设备共享”，可以成功共享给微信好友。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/48087638/58552555-45fbe080-8245-11e9-8626-3c8674e591c4.png)

**Comment by santcool** [comment]
你们设备的后台配置不支持微信分享。我刚给你们修改了下，你们过5-10分钟，清除缓存，再试下。

**Comment by huangjr126** [comment]
@santcool 您好，我这会清缓存试了下，还是能看到微信共享，且点完后仍然提醒共享失败。安卓和IOS情况一样。

**Comment by santcool** [comment]
重启app了没？再多试两次？和微信共享相关的，就这么一个逻辑

**Comment by huangjr126** [comment]
@santcool 现在Android和IOS都可以进行微信分享了，这是您修改后的结果吗？

**Comment by santcool** [comment]
对的，这个在后台配置的，有缓存，时长我也不太了解，所以需要等一段时间才能生效
