### ISSUE TITLE
米家牙刷插件，撤销授权后，数据删除不及时

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#871]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S
soocare.toothbrush.m1s

环境（必填）
手机系统:【Android & IOS】

现象（必填）
绑定米家声波电动牙刷并进入插件，进入设置页面点击“法律信息”，点击“撤销授权”后，短时间内立刻重新绑定该牙刷，数据仍然存在，未被清空。

期望（必填）
点击“撤销授权”后，插件所有数据需即时清空。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/48087638/58554058-dab40d80-8248-11e9-98ec-c48286991f2e.png)

**Comment by santcool** [comment]
什么数据没清空？短时间重新绑定，进入插件后，是否依旧弹出使用条款和隐私政策弹框？

**Comment by huangjr126** [comment]
@santcool 数据清空的意思包括个性定制、刷牙数据、刷头天数全部清空或者恢复出厂默认状态。短时间重新绑定，进入插件后，依旧弹出使用条款和隐私政策弹框

**Comment by santcool** [comment]
撤销使用条款和隐私政策，只会处理隐私政策相关，并且只是临时让用户无法使用。如果想清除数据，请直接删除插件。此处逻辑不存在问题

**Comment by huangjr126** [comment]
@santcool 好的。现在还有一个问题是关于（安卓端）撤销授权后，页面仍然停留在插件里。期望结果是：撤销授权后，返回米家设备列表。
