### ISSUE TITLE
点击push消息无法跳转到插件页（Android）

### ISSUE THREAD

**Issue by betterFuture** [MiEcosystem/miot-plugin-sdk#872]
安卓端 
异常提醒功能
可以正常收到push消息 但是点击push消息无法跳转到插件页，iOS端正常

**Comment by blockdate** [comment]
提供下 推送消息的设置格式，这边确认下 消息推送的逻辑

**Comment by lvjie0519** [comment]
问题已知，我这边排期修复，需要原生APP做一定支持，修复完毕我这边及时通知，谢谢。

**Comment by lvjie0519** [comment]
@betterFuture  已修复，  请使用最新apk进行测试，谢谢。

**Comment by lvjie0519** [comment]
暂时关闭，如有问题，再reopen。

**Comment by WWJ1993** [comment]
@betterFuture 你的iOS点击push消息可以正常跳转到插件首页还是米家首页？你的SDK分支是哪个？我的iOS只能跳到米家首页，安卓可以跳到插件首页，你怎么做的处理，分享一下呀
