### ISSUE TITLE
扩展程序内页面转跳不成功

### ISSUE THREAD

**Issue by icedu8910** [MiEcosystem/miot-plugin-sdk#873]
**是否为新品（必填）**
填 新品

**关联的产品名称（必填）**
星辰灯具

**项目ID（必填）**
无ID

**企业名称（必填）**
海南众明科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [10002]
- 相关模块:[Package]

**现象（必填）**
扩展程序APP内，点击右上角的三个点，可以转跳至更多菜单moreMenu，我们在菜单中添加了一个页面，并使用Package.entry(About, _ => {
        });
进行转跳。但转跳不成功，也没有任何报错信息。

**期望（必填）**
希望能提供简单的转跳例子。

**其他的上下文/日志/截图**

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
Package.entry 仅在开启插件时有效，使用 `this.props.navigation.navigate()`, 建议参考下 project/com.xiaomi.deo的实现
