### ISSUE TITLE
扩展程序打包上传，IOT平台提示打包失败。

### ISSUE THREAD

**Issue by icedu8910** [MiEcosystem/miot-plugin-sdk#874]
**是否为新品（必填）**
填 新品

**关联的产品名称（必填）**
星辰灯具

**项目ID（必填）**
无ID

**企业名称（必填）**
海南众明科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [10002]
- 相关模块:[Package]

**现象（必填）**
按照教程，我们已经使用npm install --save 将第三方JS保存到了本地。
然后使用npm run XXX对项目进行打包。提示打包成功并在项目目录下生成了build文件夹和mpkg文件。将mpkg文件上传MI IOT平台，提示正在打包，几分钟后提示打包失败。

**期望（必填）**
扩展程序打包需要注意什么？流程步奏怎么操作？如何排除失败原因？

**其他的上下文/日志/截图**

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by santcool** [comment]
按照教程，我们已经使用npm install --save 将第三方JS保存到了本地。
---注意npm install --save执行的文件夹，不是miot-workspace文件夹
鼠标放到插件包上传页面的打包失败那几个字上面，停留几秒钟，会有详细错误提示。

**Comment by icedu8910** [comment]
{"Cmd":"/usr/local/node-v8.12.0-linux-x64/bin/node","PID":22510,"Complete":true,"Exit":1,"Error":null,"StartTs":1559148472610592676,"StopTs":1559148503834291912,"Runtime":31.22369929,"Stdout":["/home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile/projects/temp_b2e5d52f_d404_4aaa_b441_7d1fa60c4a15","================================","/home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile/bin/buildBundle.js --android --target /tmp/1559148472610558852/release/android 397.light.hallight","/home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile","","[MIOT]start to build android bundle for 397.light.hallight","compile /home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile/projects/397.light.hallight","output /tmp/1559148472610558852/release/android","","Loading dependency graph, done.","","","transform[stdout]: FIXBUG node_modules/react-navigation-stack/dist/views/Header/HeaderBackButton.js","","","transform[stdout]: FIXBUG node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-prod.js","","","error：","","error：SyntaxError in /home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile/projects/397.light.hallight/node_modules/react-native-ui-kitten/src/components/calendar/strategy/index.js: /home/ocean/mesos/sandbox/data/MIOT_SDK_10012_1559148464031886029/compile/projects/397.light.hallight/node_modules/react-native-ui-kitten/src/components/calendar/strategy/index.js: Unexpected token (1:9)","","error：",""],"Stderr":[]}




你好，能帮我看看错误的原因吗？

**Comment by santcool** [comment]
这还不明显：/src/components/calendar/strategy/index.js: Unexpected token (1:9)"
