### ISSUE TITLE
点击异常通知跳转到原生页面

### ISSUE THREAD

**Issue by asdfeng** [MiEcosystem/miot-plugin-sdk#875]
**是否为新品（必填）**
 在售

**关联的产品名称（必填）**
米家电暖器

**项目ID（必填）**
P18-0080

**企业名称（必填）**
智米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [10005]

**现象（必填）**
在消息中心点击电暖器异常通知，跳转到电暖器原生页面而不是RN页面。

**期望（必填）**
跳转到RN页面

**Comment by santcool** [comment]
请问这个问题解决了没有？

**Comment by santcool** [comment]
没人回复，此问题暂且关闭，有问题请新开issue
