### ISSUE TITLE
Host.ui跳转的页面导航栏和状态栏问题

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#876]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
米家智能插座/lumi.plug.v1

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3]
- SDK分支: [10020]
- 相关模块:[Host]

**现象（必填）**
1. Host.ui跳转的页面的状态栏会受上一个页面的影响
例如：在插座首页做了插座开关的监听，根据开关状态在状态栏显示不同的颜色，在跳转到定时页面或者倒计时页面时，更改插座开关仍然会修改状态栏的颜色

2. Host.ui跳转的页面在iOS上右滑返回的过程中，导航栏内容会消失

**期望（必填）**
1. Host.ui跳转的页面的状态栏不会受上一个页面的影响
2. Host.ui跳转的页面在iOS上右滑返回的过程中，导航栏内容正常显示

**其他的上下文/日志/截图**
1. Host.ui跳转的页面的状态栏会受上一个页面的影响
例如：在插座首页做了插座开关的监听，根据开关状态在状态栏显示不同的颜色，在跳转到定时页面或者倒计时页面时，更改插座开关仍然会修改状态栏的颜色
![gifhome_448x960_20s](https://user-images.githubusercontent.com/20435121/58605673-2ad3b400-82cb-11e9-8b4b-769943e11d8f.gif)

2. Host.ui跳转的页面在iOS上右滑返回的过程中，导航栏内容会消失
![gifhome_448x960_24s](https://user-images.githubusercontent.com/20435121/58605786-a0d81b00-82cb-11e9-8fb9-f4bcfb322067.gif)

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
1. 你通过订阅监听灯的开关状态，然后改变状态栏的type。
我觉得，你只要在跳转原生页面的时候，取消监听即可，然后在返回到主页的时候重新监听。

2. 这个可能和APP有关。

**Comment by blockdate** [comment]
这个导航栏隐藏可能是因为屏蔽了默认的导航nav，如果是这种情况，建议采用将默认的nav设置成透明，再来自行实现导航样式

**Comment by xyliusun** [comment]
这个导航栏隐藏的是Host.ui里面原生页面的导航nav，请问“建议采用将默认的nav设置成透明”这里是将RN上面的导航栏设置为透明？
