### ISSUE TITLE
新Dialog需求

### ISSUE THREAD

**Issue by xuanxuandaoren** [MiEcosystem/miot-plugin-sdk#877]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家飞利浦读写台灯

**项目ID（必填）**

philips.light.rwread

**企业名称（必填）**
飞慧智能照明

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [master/10010]
- 相关模块:[Host/Ui]

**现象（必填）**
新需求

**期望（必填）**

提供带有radio button 的messagedialog 

**其他的上下文/日志/截图**
![12511559185373_ pic](https://user-images.githubusercontent.com/18681867/58605747-771ef400-82cb-11e9-8de1-93d84037e28a.jpg)

**Comment by LiuMengzhou** [comment]
正在开发中。敬请期待
（大约本月输出）
