### ISSUE TITLE
订阅属性消息有时候会收不到消息

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#878]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.2
- SDK分支: master
- 相关模块: Device

**现象（必填）**
订阅设备属性，在云平台上可以看到有上行数据，app端有时会收不到订阅的属性消息，但是这个时候发送的callMethod却可以收到返回的'OK'。

**期望（必填）**
每次设备有上行的props数据时，app端订阅的属性都可以准确的收到消息

**其他的上下文/日志/截图**
<img width="1116" alt="屏幕快照 2019-05-29 下午2 43 54" src="https://user-images.githubusercontent.com/8509320/58606685-20b3b480-82cf-11e9-89c3-47b048d6f950.png">
<img width="984" alt="屏幕快照 2019-05-29 下午2 46 30" src="https://user-images.githubusercontent.com/8509320/58606692-2b6e4980-82cf-11e9-9d74-f1ebcaa4db52.png">
这里是我发送了get_prop，如果2秒后没有收到订阅消息就会再次发送callMethod,请求get_prop，所以出现了上面的日志

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by icedu8910** [comment]
我也发现订阅信息接收并不稳定。尤其是网络状态不佳，订阅数量较多的时候。丢包概率很高。

**Comment by killua4github** [comment]
> 我也发现订阅信息接收并不稳定。尤其是网络状态不佳，订阅数量较多的时候。丢包概率很高。

订阅数量指的是我这边订阅的属性和事件数量还是平台所有的订阅量？我这边一共订阅了10个属性/事件
这个有优化方案吗?

**Comment by icedu8910** [comment]
我们试了三种方案，都没有很好的解决这个问题。

**Comment by killua4github** [comment]
> 我们试了三种方案，都没有很好的解决这个问题。

等你们好消息了

**Comment by blockdate** [comment]
这个暂时是属于推送服务的问题了，现在的送达率还没有达到100%。

目前建议可以自行实现采用长时间没有收到推送，自行开启轮询查询，收到推送后关闭轮询操作的方法。
