### ISSUE TITLE
自动化返回参数问题

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/miot-plugin-sdk#879]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
米家台灯

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.2]
- SDK分支: [master]
- 相关模块:[Package]

**现象（必填）**
![image](https://user-images.githubusercontent.com/6743367/58611332-4fd32180-82e1-11e9-91c4-6e9c4ab44eb7.png)
未找到plug_id字段,目前打印只有以下字段
![image](https://user-images.githubusercontent.com/6743367/58611370-6bd6c300-82e1-11e9-989f-259f145c25ea.png)

**期望（必填）**
1.正确显示"扩展程序参数"(plug_id)等字段

**其他的上下文/日志/截图**

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by santcool** [comment]
确认了下，这个参数是漏了，我在SDK_10020这个版本加一下，不过这个参数对于你们用处不大，它不可编辑和处理。

**Comment by BaroneX** [comment]
![image](https://user-images.githubusercontent.com/6743367/58631463-4368bc00-8315-11e9-845d-60d33bd98837.png)
额 大佬 我们这边是根据这个参数来判断打开哪个页面的,因为涉及页面比较多,所以这个参数还是很紧急的,麻烦尽快吧

**Comment by santcool** [comment]
你们为什么不用id呢？这个我已经改了，明天早上一来你就可以直接更新ipa了

**Comment by BaroneX** [comment]
谢谢大佬,是这样的我们智能场景这部分代码是公共的,所有灯类设备,自定义的场景判断都走的是'扩展程序参数',走iD判断的话也可行,但是对我们现在的架构来说,改动较多,比较麻烦
