### ISSUE TITLE
Service.smarthome.getWeatherInfo

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#88]
**平台：iOS**

> Service
        .smarthome
        .getWeatherInfo(Device.deviceID)
        .then((result)=>{
            MYLOG(("-------------"))
            MYLOG(("get weather:"+JSON.stringify(result)));
        })
        .catch((error)=>{
            MYLOG(("-------------"))
            MYLOG(("get weather error:"+JSON.stringify(error)));
        });

获得的数据只有：

> {"city_id":"101190000","city":"江苏"}

1. 请问  `WeatherInfo` 其他的属性开放了么？

1. 打印 Device.latitude 及  Device.longitude都是0，iOS平台，米家定位权限是打开的

**Comment by edwardair** [comment]
android返回的数据是一样的，所以这个不光是iOS的问题 @laohuang88

**Comment by edwardair** [comment]
最新测试返回错误：

> {"code":-6,"msg":"aqi is null"}

要不要更新 ipa/apk 的？

**Comment by dingshaoran** [comment]
Service.smarthome.getWeatherInfo(Device.deviceID).then(res=>console.log(res)); 

{ city: '顺义',
      city_id: '101010400',
      pub_time: '2018-12-07 19:00',
      aqi: '67',
      pm25: '13',
      pm10: '83',
      so2: '4',
      no2: '39',
      src: '中国环境监测总站',
      spot: '' }

天气的问题您换个 did 试试，接口是没有问题的

**Comment by dingshaoran** [comment]
Device. latitude 是设备的经纬度，如果要获取手机的请使用Host.locale.getGPS()

**Comment by edwardair** [comment]
错误信息：

> {"message":"callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-6 \"(null)\" UserInfo={message=aqi is null, result={\n    aqi =     {\n        city = \"\";\n    };\n}, code=-6}"}

**Comment by edwardair** [comment]
@dingshaoran did应该怎么去改？我们设备是纯蓝牙设备，没有任何网络环境，天气这个数据理论上应该也不跟设备ID相关联，不清楚API为什么还要传did

**Comment by dingshaoran** [comment]
获取设备所在地的天气，不是手机的。蓝牙设备可能不支持这个 api，换个did就是换个其他设备试试，我用 wifi 设备试的可以。

**Comment by edwardair** [comment]
我们没有wifi设备，有没有其他同类的API提供？需要pm2.5、温湿度这些数据

**Comment by dingshaoran** [comment]
就这一个 api 可以获取

**Comment by edwardair** [comment]
那请问我们这个天气数据该如何获取，不可能去找个别人的did内置到我们插件里面吧

**Comment by LiuMengzhou** [comment]
@edwardair  绍然说的接口应该只适用于Wif设备，传入did，获取设备所在地址的天气状况。对于蓝牙设备，目前暂时没有。你们之前在老框架上是如何获取的呢？

**Comment by dingshaoran** [comment]
后端的同事说蓝牙设备框架里没有 city_id，你们固件的同事能提供city_id 给你也行，这个接口的参数有 did 和 city_id，如果传了 did 则找这个 did 的对应城市，蓝牙设备没有对应的城市 可以传city_id

**Comment by edwardair** [comment]
我们只是纯蓝牙设备，硬件不可能有cityid这种数据的

**Comment by edwardair** [comment]
旧框架是通过  `MHPluginSDK.callSmartHomeAPI` ` '/location/area_prop_info'` 获取的天气数据 @LiuMengzhou

**Comment by edwardair** [comment]
@LiuMengzhou @dingshaoran @kyou 请问目前问题解决进度怎样？

**Comment by LiuMengzhou** [comment]
> 旧框架是通过 `MHPluginSDK.callSmartHomeAPI` ` '/location/area_prop_info'` 获取的天气数据 @LiuMengzhou

给出传参和回调的示例。我们加一下

**Comment by blockdate** [comment]
更新SDK，已处理
smarthome.getAreaPropInfo(params)
