### ISSUE TITLE
获取定时器信息

### ISSUE THREAD

**Issue by sikaiven** [MiEcosystem/miot-plugin-sdk#880]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
乐秀电暖气

**项目ID（必填）**
无项目ID

**企业名称（必填）**
乐秀

**环境（必填）**
mac os
ios 11.0
10005
ui

**现象（必填）**
能否告知下，获取定时数组的接口的详细用法？
Device.loadTimerScenes().then((sceneArr) => {
Alert.alert(JSON.stringify(sceneArr));
})
我通过以上的接口获取，返回的是'{[]}'空json。

**Comment by blockdate** [comment]
确认下时是否设置了相关的定时。

![image](https://user-images.githubusercontent.com/4339364/58614465-ff60c180-82ea-11e9-9233-7d8ce283a50a.png)

**Comment by sikaiven** [comment]
设置了的，是通过SDK中封装好的定时页面设置的定时
