### ISSUE TITLE
华为HONOR v20没法收到订阅的属性消息

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#881]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统: 华为HONOR V20 Android 9.0
- SDK分支: master
- 相关模块:Device

**现象（必填）**
 可以下发指令成功，但是完全收不到订阅的属性消息（其他手机可以收到）

**期望（必填）**
可以正常收到订阅消息

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@killua4github   请提供下您的关键代码，我这边方便排查，谢谢。

**Comment by killua4github** [comment]
> @killua4github 请提供下您的关键代码，我这边方便排查，谢谢。

是消息堵塞的问题，后来又可以收到了的，再另外一个issue里有提到

**Comment by lvjie0519** [comment]
@killua4github   请问还有问题吗？ 如果没有请关闭issue，谢谢。
