### ISSUE TITLE
请问为什么我一使用组件 webview，在开发者模式下就会报错，而打包上传以后，这个就是正常的呢？

### ISSUE THREAD

**Issue by hc520messi** [MiEcosystem/miot-plugin-sdk#882]
![IMG_1027](https://user-images.githubusercontent.com/47098962/58615353-6ed7b080-82ed-11e9-8ab0-1a29ed915a43.PNG)
![IMG_1028](https://user-images.githubusercontent.com/47098962/58615359-7303ce00-82ed-11e9-9518-212bf74a4d27.PNG)

**Comment by LiuMengzhou** [comment]
#50

**Comment by hc520messi** [comment]
那个fixed是404啊，被删除了？

**Comment by hc520messi** [comment]
不解决就给我colsed了？？？？

**Comment by hc520messi** [comment]
> 
> 
> #50

这个问题能不能解决一下？难道是系统的问题，我一模一样的代码，在mac的电脑上就可以运行，晕死了
