### ISSUE TITLE
需要一个可接受单击事件的Slider

### ISSUE THREAD

**Issue by asdfeng** [MiEcosystem/miot-plugin-sdk#883]
是否为新品（必填）
在售

关联的产品名称（必填）
米家电暖器

项目ID（必填）
P18-0080

企业名称（必填）
智米

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.0]
SDK分支: [10005]

**现象（必填）**
目前提供的Slider组件只有滑动事件，希望可以提供一个既接受滑动事件也接受点击事件的Slider。我尝试实现了一个，但是只在iOS上起作用，在android上不起作用。

**期望（必填）**
期望Slider组件可以接受点击事件

**Comment by LiuMengzhou** [comment]
@asdfeng 请按照issue模板填写完整。
