### ISSUE TITLE
现在IOS版本的米家Beta   V4.17.1 ，只要选择了开发者设置中的直接调试就闪退出APP了

### ISSUE THREAD

**Issue by hc520messi** [MiEcosystem/miot-plugin-sdk#884]
![55UH%Z4B2IX6JF1~@D`RRII](https://user-images.githubusercontent.com/47098962/58616265-d5f66480-82ef-11e9-8ac4-a982e26bbc51.png)
只要点击立即调试就卡顿了，然后闪退出APP，也不弹出窗口

**Comment by santcool** [comment]
处理中，今天稍微晚点你就可以下载新包了

**Comment by santcool** [comment]
新包已经可以下载了。
