### ISSUE TITLE
自定义自动化无法跳转

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#885]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
咱家智能窗帘电机（Wi-Fi版）

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.2]
- SDK分支: [10010]
- 相关模块:[Host]

**现象（必填）**

线上版本（4.17.2）和 DB229  正式环境下 无法打开自定义的自动化配置页面。
插件的Apilevel为 10010

在debug调试环境可以正常打开自定义的配置页面，
![image](https://user-images.githubusercontent.com/15864191/58617140-f6272300-82f1-11e9-8b3f-6328e997e646.png)

此问题block新品上市，还请尽快排查解决

**期望（必填）**
正常打开自定义的自动化配置页面。

**其他的上下文/日志/截图**
project.json内容如下

![image](https://user-images.githubusercontent.com/15864191/58617347-73eb2e80-82f2-11e9-9866-e0ca0b204052.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
你们未配置扩展程序参数，有扩展程序参数的自动化才能跳转到扩展程序页面。参数可以等同于iot后台配置自动化时的方法

**Comment by wanggoingdown** [comment]
> 你们未配置扩展程序参数，有扩展程序参数的自动化才能跳转到扩展程序页面。参数可以等同于iot后台配置自动化时的方法

我们已经按照格式配置了一遍发现以下情况：
1.android与ios米家版本安装为github提供的最新版本（android：5.5.23.1 ，ios：4.17.1）
最终发现ios能跳转，android并不能跳转

**Comment by santcool** [comment]
android还有些问题，同事正在调。因为是一个技术问题，所以暂时无法给你估计一个工期，但调好了后，我会通知你们

**Comment by damiknows** [comment]
@santcool 文峰哥，针对安卓的问题提交了新的issue：https://github.com/MiEcosystem/miot-plugin-sdk/issues/895，后续有更新麻烦在新issue下回复，感谢
