### ISSUE TITLE
Android 设置页使用帮助 进入问题详情后返回问题列表会回到顶部

### ISSUE THREAD

**Issue by joyami** [MiEcosystem/miot-plugin-sdk#886]
普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
“米家微波炉”

**项目ID（必填）**
项目ID

**企业名称（必填）**
上海纯米电子科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.00]
- SDK分支: [10010]
- 相关模块:[UI]

**现象（必填）**
Android 设置页使用帮助  滚动几屏 进入问题详情页后返回 问题列表会回到顶部

**期望（必填）**
问题列表滚动到哪里  详情页返回 不自动回到顶部

**Comment by lvjie0519** [comment]
@joyami  麻烦提供几个截图，方便排查，谢谢。

**Comment by joyami** [comment]
这个问题截图不好说明呢   就是到使用帮助页面  滚动看目录   滚动几屏后  随便点击一个目录进入看问题详情  然后点击返回   使用帮助页面没有停在刚才点目录进去时的那一页  而是自己滚动到了最上面   又需要往下翻页才能找到刚才点击的目录
![1DF49C0D7DC9E80631456A44B8DEB04D](https://user-images.githubusercontent.com/34296463/58863918-58af6300-86e6-11e9-893b-475bdf0746fa.jpg)

**Comment by lvjie0519** [comment]
@joyami 问题已知，属于APP问题，正在排查，有反馈及时回复。

**Comment by lvjie0519** [comment]
@joyami   经APP组反馈，这个模块实现如此，如果你那边有提bug，可以指到米家这边。

**Comment by joyami** [comment]
好的 谢谢！
