### ISSUE TITLE
米家牙刷插件，切换语言后，设备名称没有变更语种

### ISSUE THREAD

**Issue by huangjr126** [MiEcosystem/miot-plugin-sdk#887]
公司名称（必填）
舒可士（深圳）科技有限公司

是否为新产品（必填）
是

产品名称/Model（必填）
米家声波电动牙刷M1S、M1
soocare.toothbrush.m1s
soocare.toothbrush.m1

环境（必填）
手机系统:【 IOS】

现象（必填）
米家初始语言设置为中文后绑定米家牙刷，绑定成功后语言设置为英语，查看设备列表中以及插件中的设备名称，语种有误。（Android显示正确，IOS显示有误）

期望（必填）
切换语言后，设备名称会自动翻译成对应语种。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/48087638/58620672-40ac9d80-82fa-11e9-9b86-9281d4407ceb.png)
![image](https://user-images.githubusercontent.com/48087638/58620694-50c47d00-82fa-11e9-9637-221fab3879ec.png)

**Comment by huangjr126** [comment]
@blockdate 您好，帮忙看下是什么原因呢

**Comment by santcool** [comment]
稍等，我来看这个问题

**Comment by santcool** [comment]
用android手机测试了下，并没有此问题，视频如下，
[android_name.mov.zip](https://github.com/MiEcosystem/miot-plugin-sdk/files/3255212/android_name.mov.zip)
逻辑和iOS是一致的。另外，添加设备后，有改名这一步，如图
<img width="394" alt="屏幕快照 2019-06-05 上午10 08 34" src="https://user-images.githubusercontent.com/8580061/58925396-facc5b00-8779-11e9-96ef-7e5ef3cbf8cc.png">
，你写的是中文就是中文，写的是英文就是英文，就算你切换app语音或者系统语言，这个名字也是不会改变的。

**Comment by huangjr126** [comment]
@santcool 在默认未修改设备名称的情况下，修改米家语言后，设备名称会随着所修改的语言显示不同语种。（Android一直可以实现，IOS之前不行，昨天可以，现在又实现不了）
