### ISSUE TITLE
倒计时页面安卓上显示报错

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#888]
是否为新品（必填）
在售

关联的产品名称（必填）
米家智能插座/lumi.plug.v1

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 6]
SDK分支: [10020]
相关模块:[Host.ui.openCountDownPage]

现象（必填）
在安卓上跳转倒计时页面显示报错，在iOS上能正常显示

期望（必填）
倒计时页面安卓上跳转显示正常

其他的上下文/日志/截图
![Screenshot_2019-05-30-16-58-08-004_com xiaomi smarthome](https://user-images.githubusercontent.com/20435121/58629781-fe8e5680-830f-11e9-9be5-311942a05f1a.png)

**Comment by lvjie0519** [comment]
参数转换错误，麻烦提供下你传入的参数，谢谢。

**Comment by xyliusun** [comment]
Host.ui.openCountDownPage(isOn1, {
                  onMethod: 'toggle_plug',
                  offMethod: 'toggle_plug',
                  onParam: [onoff, 'on'],
                  offParam: [onoff, 'off']
                });
你好，参数如上

**Comment by lvjie0519** [comment]
onParam: [onoff, 'on'],offParam: [onoff, 'off']，   这两个都是字符串格式， 需要将数组转换为字符串。

**Comment by xyliusun** [comment]
改成字符串的形式去传参数后，安卓可以正常使用倒计时，iOS可以进入倒计时页面，但是创建的倒计时无法执行
参数数据格式：
offMethod:"toggle_plug"
offParam:"["channel_0","off"]"
onMethod:"toggle_plug"
onParam:"["channel_0","on"]"
