### ISSUE TITLE
在插件内想用mobx管理状态，配置不成功

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#889]
**是否为新品（必填）*
新品

**关联的产品名称（必填）**
正准备开发

**现象（必填）**
据悉米家客户端中内置的 RN 引擎版本为 0.54.4,我新建了一个RN版本为0.54.4的Demo,通过`npm install mobx@3.4.1 --save ` 和`npm install mobx-react@4.3.5 --save` 安装mobx，又通过`npm i --save-dev babel-plugin-transform-decorators-legacy` 手动安装装饰器语法，又修改.babelrc。通过这一系列配置可以在demo中使用mobx对状态进行管理，但是通过相同的操作想再miot-sdk的扩展插件里使用mobx管理状态，却不可以。我这里也不知道怎么解决。希望你们那边能给予解决
，
**期望（必填）**
能够在miot-sdk插件内使用mobx管理状态

**Comment by devYoungyang** [comment]
不安排一个人解决一下这个问题吗？

**Comment by blockdate** [comment]
经测试，非注解写法的mobx可以正常使用。
  
支持注解的需要升级babel，在不升级RN的前提下，这块是不会单独升级的，见谅。

**Comment by devYoungyang** [comment]
> 经测试，非注解写法的mobx可以正常使用。
> 
> 支持注解的需要升级巴贝尔，在不升级RN的前提下，这块是不会单独升级的，见谅。

我想使用装饰器语法，需要怎么升级巴贝尔？
