### ISSUE TITLE
iOS进入插件时显示： Requiring unknown module "10001".

### ISSUE THREAD

**Issue by dan-huang** [MiEcosystem/miot-plugin-sdk#890]
debug没问题，发到lot平台测试出现的该问题。

API Level: 10011
model: ninebot.scooter.v1

miot-plugin-sdk已经更新到master分支的最新代码。

**Comment by santcool** [comment]
问题已解决，在这儿更新下SDK，并使用github新包调试。

**Comment by blockdate** [comment]
需要重新提交平台打包

今天因为打包脚本出了点问题，在今天 2019-05-31 09:00 至 2019-05-31 17:30 之间提交插件打包的同学，这期间出的包在高本版apk(当前测试版)下会有异常，线上APP正常，请注意该期间的插件包不建议提交审核，如果需要提交审核，请重新上传打包一次。
