### ISSUE TITLE
Host.ui.openPrivacyLicense展示不完整，`使用条款`没有显示

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#891]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
米家智能门锁

**项目ID（必填）**
ECO-绿米LVMI

**企业名称（必填）**
绿米联创

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0
- SDK分支: 10011
- 相关模块: Host.ui.openPrivacyLicense

**现象（必填）**
使用新的米家主App（5.5.23.1测试版）调用Host.ui.openPrivacyLicense展示不完整，`使用条款`没有展示；
使用旧的米家主App（5.5.15测试版）调用Host.ui.openPrivacyLicense可以正常展示；
如下图所示：

![1132](https://user-images.githubusercontent.com/2813239/58679914-0f82aa80-8398-11e9-8efc-cb9022dd08e9.png)

![1131](https://user-images.githubusercontent.com/2813239/58679927-18737c00-8398-11e9-8dfe-863d0cb21943.png)

**期望（必填）**
调用Host.ui.openPrivacyLicense展示完整

**Comment by lvjie0519** [comment]
@fengdexunmi  
1、看一下您的传参？
2、有传递对应的参数吗？  这个模块有修改，使用条款是可选项，未传递数据则不显示。

**Comment by fengdexunmi** [comment]
@lvjie0519 谢谢回复，是我们这边`使用条款`的名称部分更改了导致的问题，可以关闭这个issue了
