### ISSUE TITLE
五月三十一日下午六点前打包的插件，不能提交审核，请重新打包

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#893]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:/Mac OS
- 手机系统:Android/iOS
- SDK分支: master
- 相关模块:无法进入插件

**现象（必填）**
之前有上传过测试包到平台，并且一切都是正常的，今天更新了一个包上去，把之前平台上的测试版本删掉了。然后就不能再进入插件了。还有一部分手机可以进入插件，但是里面的功能是之前的包的

**期望（必填）**
希望可以正常进入新的软件进行测试。

**其他的上下文/日志/截图**
<img width="1032" alt="屏幕快照 2019-05-31 上午11 37 18" src="https://user-images.githubusercontent.com/8509320/58683180-0d274d00-83a6-11e9-9b0c-999742f4c392.png">
![10501559273871_ pic](https://user-images.githubusercontent.com/8509320/58683188-144e5b00-83a6-11e9-94cd-2b60f8d337f7.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zhuxinleibandou** [comment]
同样也是，跪求解决～

**Comment by zhuxinleibandou** [comment]
![47213F62-80A2-461C-ABFF-AFEED0F1087D](https://user-images.githubusercontent.com/18374383/58688592-7bc0d680-83b7-11e9-9de8-da381fb9cf65.png)

我是10004版本，平台上也是10004，可是在debug app上显示 unkonwn....10001,无法进入插件。 

debug app是最新的，iOS是30号晚上发布的，Android是29号发布的。

**Comment by blockdate** [comment]
将设备分享到 894158105， 同时最好可以提供打包的mpkg文件到 邮箱 wulei7@xiaomi.com

**Comment by killua4github** [comment]
> 将设备分享到 894158105， 同时最好可以提供打包的mpkg文件到 邮箱 [wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)

你好，设备已分享，包也已经发邮箱了，注意查收下

**Comment by blockdate** [comment]
已处理，重新打包上传一下，应该可以了

**Comment by killua4github** [comment]
> 已处理，重新打包上传一下，应该可以了
是什么原因呢？

**Comment by zhuxinleibandou** [comment]
> 将设备分享到 894158105， 同时最好可以提供打包的mpkg文件到 邮箱 [wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)

已经分享，mpkg文件已发发送到邮箱，谢谢

**Comment by zhuxinleibandou** [comment]
> > 将设备分享到 894158105， 同时最好可以提供打包的mpkg文件到 邮箱 [wulei7@xiaomi.com](mailto:wulei7@xiaomi.com)
> 
> 已经分享，mpkg文件已发发送到邮箱，谢谢

我已经把这个mpkg提审了 - - 不会被拒绝吧  好像撤销不掉了。但是我在米家的正式版本是可以进入的，在beta版本就会提示

**Comment by killua4github** [comment]
> 已处理，重新打包上传一下，应该可以了

重新上传了，但是还是进不去，麻烦再看下，谢谢

**Comment by blockdate** [comment]
重新打包之后需要过一段时间才可以正式生效

**Comment by killua4github** [comment]
> 重新打包之后需要过一段时间才可以正式生效
那我等会儿再看看

**Comment by Android-yzhang** [comment]
刚才我上传了一个版本也是这样，5点20分的时候又上传了一次，提示打包失败cmd timeout 15min

**Comment by blockdate** [comment]
@zhuxinleibandou 建议沟通一下让产品方拒绝之后重新打包提审一个，不然会有隐患。

**Comment by killua4github** [comment]
> 重新打包之后需要过一段时间才可以正式生效

好了，谢谢

**Comment by blockdate** [comment]
这个问题是打包脚本在打包插件时，误删除删除了一些模块依赖，导致插件包会引用到一个undefine 的 module。

这个有问题的插件包目前只能被高版本的app获取到(测试版)，所以建议有提测的，重新打包提测一下。

**Comment by blockdate** [comment]
今天因为打包脚本出了点问题，在今天 2019-05-31 09:00 至 2019-05-31 17:30 之间提交插件打包的同学，这期间出的包在高本版apk(当前测试版)下会有异常，线上APP正常，请注意该期间的插件包不建议提交审核，如果需要提交审核，请重新上传打包一次。
