### ISSUE TITLE
自定义自动化android无法跳转

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#895]
是否为新品（必填）
新品

关联的产品名称（必填）
咱家智能窗帘电机（Wi-Fi版）

项目ID（必填）
【无项目ID】

企业名称（必填）
绿米

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[android 8.1]
SDK分支: [10010]
相关模块:[Host]
现象（必填）

线上版本（5.5.25）和 5.5.23.1 正式环境下 无法打开自定义的自动化配置页面。
插件的Apilevel为 10010

此问题block新品上市，还请尽快排查解决

期望（必填）
正常打开自定义的自动化配置页面。

其他的上下文/日志/截图
自动化配置
<img width="875" alt="WeChat7db46451dd00325c2bb6aba898f5cda0" src="https://user-images.githubusercontent.com/10232787/58685228-86766e00-83ad-11e9-987b-2a2f28debe5d.png">

project.json内容如下
<img width="360" alt="WeChat1c8d77274e8857c9265f0d0312f4bff7" src="https://user-images.githubusercontent.com/10232787/58685280-c50c2880-83ad-11e9-9727-58038df3c3b5.png">

是否尝试其他测试方式：
在ios端能正常跳转

**Comment by zanetti4** [comment]
请问打开自定义的自动化配置页面调用了哪个接口？我进行测试

**Comment by lvjie0519** [comment]
@wanggoingdown 
1、目前线上版本  5.5.25 和 fir上的 5.5.23.3 之前版本， project.json中数组要配置成字符串格式，
2、 fir上的 5.5.23.3及之后版本已经修复了该问题，支持整数和字符串，请使用fir上最新apk测试试试。

**Comment by wanggoingdown** [comment]
@lvjie0519 
目前我已经把entrance_scene更换为字符串格式，但是还是发现以下问题
1.fir上的5.5.23.5能够实现跳转
2.米家应用商城的5.5.25不能实现跳转

**Comment by lvjie0519** [comment]
@wanggoingdown  
后面的版本apk有做过一次优化，优先跳转到插件页面，应该是你配置自动化的时候指定进入的是原生开发的界面， 你可以将设备分享给894158105，我这边排查下。

**Comment by wanggoingdown** [comment]
@lvjie0519 已经把设备分享过去了，请帮我排查一下，设备名字是咱家智能窗帘电机（Wifi）

**Comment by wanggoingdown** [comment]
@lvjie0519 已经解决了

**Comment by lvjie0519** [comment]
@wanggoingdown    解决了，麻烦把解决方案也共享下吧，方便其他开发人员参考，谢谢。

**Comment by fergus825** [comment]
@wanggoingdown 我们也遇到了和你一样的问题，请问你是怎么解决的？谢谢！
