### ISSUE TITLE
添加了匹配蓝牙的图片后，安卓版本无法连接设备

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#896]
您好，
      我在小米IoT平台添加了匹配蓝牙图片后，安卓版本无法添加设备，可以搜索到设备，但是就会停在这里，没有下一步反应了。

![image](https://user-images.githubusercontent.com/18459414/58686933-cab83d00-83b2-11e9-8cc0-4d84a4e63035.png)
![Snip20190531_4](https://user-images.githubusercontent.com/18459414/58686961-db68b300-83b2-11e9-8ea1-13bc8d73e31b.png)

之前没有添加匹配蓝牙图片的时候，是可以正常连接设备的。
![WechatIMG927](https://user-images.githubusercontent.com/18459414/58687007-f6d3be00-83b2-11e9-8ebe-9bc9fe6069b4.jpeg)

请问这个应该怎么解决？谢谢！

**Comment by caojunhua** [comment]
@blockdate 很急很关键，无法绑定连接，影响到其他测试，盼回复，谢谢！

**Comment by caojunhua** [comment]
补充：在搜索的是，附近的设备是能搜索多个的，但是我点击的时候，不会弹出设备列表，我点击不会有列表选择设备，但是ios会有列表可以选择。如下图：
![3921559286730_ pic](https://user-images.githubusercontent.com/18459414/58688274-9b0b3400-83b6-11e9-9e1d-f5fb3f3760f9.jpg)
![3931559286731_ pic](https://user-images.githubusercontent.com/18459414/58688281-9e062480-83b6-11e9-9e71-72399038211f.jpg)
![3941559286738_ pic_hd](https://user-images.githubusercontent.com/18459414/58688291-a3636f00-83b6-11e9-9729-c398e01541a2.jpg)
![3951559286750_ pic_hd](https://user-images.githubusercontent.com/18459414/58688297-a5c5c900-83b6-11e9-9c36-c7723361e18a.jpg)

**Comment by caojunhua** [comment]
@Copypeng @blockdate @zanetti4 @kyou 拜托各位小伙伴们，百忙之中看看这个问题可以吗，感激不尽！

**Comment by dessmann** [comment]
我们碰到过这种情况，是因为设备没有清空，不知道你们是不是这个原因！

**Comment by cfJand** [comment]
请按照issue模板提交issue，此issue由于未按照要求发issue，暂时关闭。
