### ISSUE TITLE
新固件上传后，固件不显示更新

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#897]
---
**是否为新品（必填）*
新品
**关联的产品名称（必填）**
新品

**项目ID（必填）**
minij.washer.v11

**企业名称（必填）**
小吉科技
**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 8.1/ios]
- SDK分支: 老SDK
- 相关模块:[minij.washer.jumpv11]

**现象（必填）**
AI版的固件已上传，但是app端不显示当前固件版本号，pro版可以显示出来，如图是AI版和pro版，帮忙协助看下AI版为什么不显示当前固件也不显示更新

**期望（必填）**
显示当前固件版本号,显示有更新。

**其他的上下文/日志/截图**
![微信图片_20190531174129](https://user-images.githubusercontent.com/28422366/58697078-7e2d2b80-83cb-11e9-80a9-68cecfbde4a8.jpg)
其他机型正常的显示

**尝试过的解决办法**
过几小时正常。当时的异常时什么情况
![微信图片_20190531174303](https://user-images.githubusercontent.com/28422366/58697162-a4eb6200-83cb-11e9-956c-7226982c3389.jpg)

**Comment by hao0000** [comment]
部分手机仍然不能更新。
手机机型：Redmi note7 pro
![微信图片_20190531180109](https://user-images.githubusercontent.com/28422366/58698627-2c39d500-83ce-11e9-8e14-26c4e54555de.png)

**Comment by aiquestion** [comment]
不好意思，没有理解，这个固件版本不是线上是2.0.3吧。其他还在灰度，请检查用户是否在灰度范围

**Comment by hao0000** [comment]
正常应该显示当前版本是2.0.4.0003，显示最新版本是2.0.4.0009，但是这个只显示了2.0.4.
用户在灰度范围。
![微信图片_20190531214404](https://user-images.githubusercontent.com/28422366/58709785-7b433280-83ed-11e9-9f0c-611c7711b600.jpg)
同样型号的洗衣机，正常应该显示如上图
现在不正常的显示如下图
![微信图片_20190531214420](https://user-images.githubusercontent.com/28422366/58709822-91e98980-83ed-11e9-861f-7481f674dd23.png)
uid：1410780757
时间一整天

**Comment by hao0000** [comment]
用户在灰度范围 UID:1410780757 时间：今天一整天都不行------------------ 原始邮件 ------------------
发件人: "Shawn"<notifications@github.com>
发送时间: 2019年5月31日(星期五) 晚上9:13
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "hao0000"<987158014@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] 新固件上传后，固件不显示更新 (#897)



不好意思，没有理解，这个固&#x4EF6;版本不是线上是2.0.3吧。其他还在灰度，请检查用户是否在灰度范围
 
&mdash;

**Comment by larstos** [comment]
> 用户在灰度范围 UID:1410780757 时间：今天一整天都不行------------------ 原始邮件 ------------------ 发件人: "Shawn"<notifications@github.com> 发送时间: 2019年5月31日(星期五) 晚上9:13 收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>; 抄送: "hao0000"<987158014@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [MiEcosystem/miot-plugin-sdk] 新固件上传后，固件不显示更新 (#897) 不好意思，没有理解，这个固&#x4EF6;版本不是线上是2.0.3吧。其他还在灰度，请检查用户是否在灰度范围 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

1、设备当前版本是根据设备上报提示的，没有后面的mcu版本号辛苦确认一下对应版本固件在上报设备信息时是否能正确上报Mcu版本。
2、由于设备固件信息读多写少，故服务器有缓存策略，新上传固件在30-40分钟左右全面刷新，不会立即对app生效的。
3、固件版本判断优先级是：上传序号>版本编号。若出现低版本号的固件上传编号较大，则会影响正常版本判断

**Comment by zanetti4** [comment]
@hao0000 这个问题是否已经解决？

**Comment by hao0000** [comment]
不确定，最近没出------------------ 原始邮件 ------------------
发件人: "zanetti4"<notifications@github.com>
发送时间: 2019年6月21日(星期五) 晚上9:02
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "hao0000"<987158014@qq.com>;"Assign"<assign@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] 新固件上传后，固件不显示更新 (#897)



Assigned #897 to @hao0000.
 
&mdash;

**Comment by zanetti4** [comment]
那我先把这个问题关闭了，如果再发现，你可以 reopen 并留言。
