### ISSUE TITLE
米家app扫描二维码快速添加二维码失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#898]
您好，
      使用米家app扫描二维码快速添加蓝牙设备的时候，会有扫描二维码一直没有反应的情况，过一段时间，再扫描又有可能可以扫描出来我们对应的蓝牙设备。
      出现的概率大概50%吧。不知道是什么情况，盼回复，谢谢！

**Comment by zanetti4** [comment]
请问涉及到的系统是安卓，还是 ios?

**Comment by pencilCool** [comment]
请给出设备的model ，如果问题还复现了，请上传一下本地日志。本地日志的上传方法是：
米家app 的 “我的” -> “帮助与反馈” -> 选中出问题的设备 -》反馈问题 （勾选  同时候发送问题日志）
