### ISSUE TITLE
IOS发现蓝牙服务少于Android

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#899]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米兔儿童牙刷

**项目ID（必填）**
PRJ18-SOOCA-X-003

**企业名称（必填）**
舒可士（深圳）科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.2]
- SDK分支: [master]
- 相关模块:[BluetoothEvent.bluetoothDeviceDiscovered]

**现象（必填）**
ios下发现蓝牙服务比android少，而且没有发现到自定义的服务。
android下没有问题。

**期望（必填）**
可以正常发现到自定义的服务

**其他的上下文/日志/截图**
ios:
![image](https://user-images.githubusercontent.com/14890491/58705827-e3d8e200-83e2-11e9-8997-38ac028b1bb4.png)
android:
![image](https://user-images.githubusercontent.com/14890491/58705834-f0f5d100-83e2-11e9-8a88-24f7a071c011.png)

**尝试过的解决办法**
扫描也没有用

**Comment by lijian9088** [comment]
需要发现到42ed0001-539a-f397-4c45-ddf7c0ccf671这个服务，项目比较紧急，盼回复。

**Comment by blockdate** [comment]
1. 提供下JS端的代码使用
2. 使用lightblue app 查看下改蓝牙设备的所有service，并截图发上来看一下问题在哪

**Comment by lijian9088** [comment]
![image](https://user-images.githubusercontent.com/14890491/58796125-00695a00-862f-11e9-9286-e9b7563475fb.png)
![image](https://user-images.githubusercontent.com/14890491/58796132-05c6a480-862f-11e9-9953-3256327c90fb.png)

**Comment by blockdate** [comment]
提供下你定义的`ServiceUUID` 的值

**Comment by lijian9088** [comment]
42ed0001-539a-f397-4c45-ddf7c0ccf671，就是上图里面的第二个service

**Comment by blockdate** [comment]
iOS端扫描的结果会根据传入的service做限制，建议将你所知的service全部传入，这样扫描出来就会是完整的。

**Comment by lijian9088** [comment]
好的，已经解决了谢谢。
