### ISSUE TITLE
新插件打包上传后，打开插件报错

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#900]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
米家智能门锁

**项目ID（必填）**
ECO-绿米LVMI  lumi.lock.mcn01

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9.0/iOS 11.0
- SDK分支: 10011
- 相关模块: 打包

**现象（必填）**
本地运行正常，打包后打开插件运行打包后的插件报错，错误如下：

![IMG_0007](https://user-images.githubusercontent.com/2813239/58708417-526d6e00-83ea-11e9-91fe-473e4ea85c9d.PNG)

![IMG_0B441BB34675-1](https://user-images.githubusercontent.com/2813239/58708424-57322200-83ea-11e9-91dc-889cdb01b9a3.jpeg)

**期望（必填）**
打包插件可以正常运行

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
Google了报错内容，好像是第三方库`react-native-screens`被重复引用了，我projects下面的项目没有引入过这个库

https://github.com/kmagiera/react-native-screens/issues/15

**Comment by zanetti4** [comment]
请检查是否在多个 package.json 中安装过此依赖 react-native-screens

**Comment by fengdexunmi** [comment]
@zanetti4 你好，麻烦关闭下这个issue，是projects下的package.json引入了一个和主工程重复的包
