### ISSUE TITLE
白名单测试，Android系统无法进去插件

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#901]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: master
- 相关模块:整个插件进不去

**现象（必填）**
发布包到平台进行白名单测试，iOS系统可以正常了，但是Android系统一直处于加载中。5月31号之前都是可以正常的。

**期望（必填）**
iOS、Android都可以正常进入插件

**其他的上下文/日志/截图**
<img width="1032" alt="屏幕快照 2019-06-01 下午12 23 46" src="https://user-images.githubusercontent.com/8509320/58743668-93a46300-8468-11e9-848c-304a6464382d.png">
![10721559353278_ pic_hd](https://user-images.githubusercontent.com/8509320/58743671-9a32da80-8468-11e9-800f-63e97bb4e2e2.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@killua4github   请问使用的是哪个apk？  版本5.5.23.1 和 之前的5.5.23.2 ， apk存在部分问题， 请使用最新apk测试试试。

**Comment by killua4github** [comment]
> @killua4github 请问使用的是哪个apk？ 版本5.5.23.1 和 之前的5.5.23.2 ， apk存在部分问题， 请使用最新apk测试试试。

刚刚下载了最新的apk试过了，还是一直处于加载中

**Comment by lvjie0519** [comment]
请把设备分享给 894158105账号，同时告知下设备名称及设备model，我这边排查下看看

**Comment by killua4github** [comment]
> 请把设备分享给 894158105账号，同时告知下设备名称及设备model，我这边排查下看看
设备已经分享了
设备名称：solista 智能炒菜机
设备model：jyaiot.cm.ccj01

**Comment by lvjie0519** [comment]
请检查下你们的代码，onPressLeft定义了多次。
![image](https://user-images.githubusercontent.com/22487747/58793878-9c906280-8629-11e9-8816-52af83a61e7e.png)

![image](https://user-images.githubusercontent.com/22487747/58793863-95695480-8629-11e9-926a-aa3e226b7eef.png)
