### ISSUE TITLE
SingleChooseDialog iOS回调数据异常

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#902]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
小米米家智能门锁

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
SingleChoseDialog点击确定后onConfirm的ios回调异常
Android回调是带有position的对象,正常，
iOS回调的是带有target的对象，且target的值都是70。

**期望（必填）**
SingleChooseDialog能正常使用，且在两个平台上表现一致。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/46777658/58746457-f9a4e080-8490-11e9-905f-bb9bc877d356.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
处理中，明早提供包

**Comment by santcool** [comment]
已经解决，请在github下载安装最新ipa尝试。若已经解决，请在此回复

**Comment by WeizhiKong** [comment]
已经验证OK了

**Comment by santcool** [comment]
代码已合入master，6月11号的发版将会带上。
