### ISSUE TITLE
connect()一直报错code=-13.而且重新进插件,也一直报code=-13.

### ISSUE THREAD

**Issue by georgeChina** [MiEcosystem/miot-plugin-sdk#906]
---
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
卡麦保险箱

**项目ID（必填）**
1120

**企业名称（必填）**
卡麦

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1]
- SDK分支: [eg.master]
- 相关模块:[eg.Bluetooth]

**现象（必填）**
bt.connect(-1):报错code=-13,一直重连,一直报-13.不能复位.重新退出再进入插件,还是一直报code=-13.不能操作任何操作.

**期望（必填）**
能重连成功

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/36940614/58770446-8c549500-85e1-11e9-9452-4c32559b25a0.png)

**尝试过的解决办法**
退出插件,杀掉app,再次进入还是code=-13

**不要贴大段代码❗️**

**Comment by cfJand** [comment]
“bt.connect(-1)”，建议检查-1参数是否正确。

**Comment by cfJand** [comment]
从日志截图来看，当前有正在处理的Request，建议连接之前先尝试断开连接。
此issue长时间未回复，先关闭。
