### ISSUE TITLE
andriod,蓝牙链接状态监听,没有收到信息

### ISSUE THREAD

**Issue by georgeChina** [MiEcosystem/miot-plugin-sdk#907]
---
**是否为新品（必填）**
 在售

**关联的产品名称（必填）**
卡麦保险箱

**项目ID（必填）**
1120

**企业名称（必填）**
卡麦

**环境（必填）**
- 电脑操作系统:[eg./Linux]
- 手机系统:[eg.Android 8.1]
- SDK分支: [eg.master/]
- 相关模块:[eg.Bluetooth]

**现象（必填）**
蓝牙链接状态改变,BluetoothEvent.bluetoothConnectionStatusChanged这个事件没有收到推送.以致于,蓝牙链接状态的错误判断,操作交互错落.

**期望（必填）**
BluetoothEvent.bluetoothConnectionStatusChanged这个事件能及时收到推送.

**其他的上下文/日志/截图**
代码:
    this._s6 = BluetoothEvent.bluetoothConnectionStatusChanged.addListener((blut, isConnect) => {
      console.log("蓝牙链接状态改变事件:", blut, isConnect);
      console.log("bt:,platform.os",bt,Platform.OS,blut.isConnected);});
日志:
![image](https://user-images.githubusercontent.com/36940614/58771079-ec990600-85e4-11e9-9c9d-33ca4bfc1dcc.png)
在Bluetooth.js中已经收到2次这个事件了,但是我在代码中设置的BluetoothEvent.bluetoothConnectionStatusChanged事件监听没有收到.

**尝试过的解决办法**
多次尝试,重进插件,还是出现这种情况.
**不要贴大段代码❗️**

**Comment by cfJand** [comment]
@georgeChina 已经处理了会触发2次事件的问题。
关于“BluetoothEvent.bluetoothConnectionStatusChanged事件监听没有收到”的问题，建议 @georgeChina 看下代码，是否注册监听有问题。
也麻烦 @lvjie0519  跟进下，监听收不到的问题。

**Comment by lvjie0519** [comment]
@georgeChina   
1、BluetoothEvent.bluetoothConnectionStatusChanged.addListener  这段代码写在什么位置的？
2、看你log日志，  不是已经收到监听事件了吗。

**Comment by lvjie0519** [comment]
@georgeChina  关于触发两次事件，请使用最新apk进行测试，如果问题仍然存在，请使用 “miot-rn-plugin” 过滤下原生层打印出的log日志，谢谢。

**Comment by georgeChina** [comment]
这是好久前的了，现在能收到了，但是偶尔会收到2次，已经是断开状态的，连上了，会先来一次蓝牙断开的消息，再来一次连上的消息。和那个蓝牙开关状态监听也是一样的，蓝牙开关开启的时候，会来2次。 先来一个关闭，再来一个开启。------------------ 原始邮件 ------------------
发件人: "小米-吕杰"<notifications@github.com>
发送时间: 2019年8月13日(星期二) 上午10:17
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "georgeChina"<3143037924@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] andriod,蓝牙链接状态监听,没有收到信息 (#907)



@georgeChina
 1、BluetoothEvent.bluetoothConnectionStatusChanged.addListener  这段代码写在什么位置的？
 2、看你log日志，  不是已经收到监听事&#x4EF6;了吗。
 
&mdash;

**Comment by lvjie0519** [comment]
但是偶尔会收到2次，已经是断开状态的，连上了，会先来一次蓝牙断开的消息，再来一次连上的消息
@cfJand   看一下这个问题，如果确实如此，就关闭issue吧。

**Comment by cfJand** [comment]
重复2次的问题，已经在最新代码修改过，此issue关闭。
