### ISSUE TITLE
InputDialog 控件在 iOS 端调用不起来，在 android 可以。

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#908]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家智能多模网关

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
InputDialog 控件在 iOS 端调用不起来，在 android 可以。

**期望（必填）**
InputDialog 控件在 iOS 端正常使用。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by WeizhiKong** [comment]
+1

**Comment by blockdate** [comment]
这边提供下dialog的 js端使用代码，在demo中验证可以正常使用

**Comment by zanetti4** [comment]
我测试时在 IOS, android 也都能使用，请提供具体的使用代码。

**Comment by Pandalzm** [comment]
刚刚测试，应该是调用问题，message没有填的情况下，iOS不能使用，android能用。我这边修改一下。
