### ISSUE TITLE
解决了 iconURL 问题的 app，不支持 Host.ui.openZigbeeConnectDeviceList(did) 

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#909]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家智能多模网关

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:Host

**现象（必填）**
解决了 iconURL 问题的 app，不支持 Host.ui.openZigbeeConnectDeviceList(did) 

**期望（必填）**
解决了 iconURL 问题的 app，同时支持 Host.ui.openZigbeeConnectDeviceList(did) 

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
Host.ui.openZigbeeConnectDeviceList 这个接口的功能还在内部测试中，而且不确定该功能是否能顺利跟这一次的版本，因此代码并未同步，所以是两个测试版本app。

有消息及时通知你们。

**Comment by Pandalzm** [comment]
请问这个问题有进度了吗？是否能跟进这次的版本？

**Comment by Pandalzm** [comment]
已修复，close
