### ISSUE TITLE
Device.getSubDevices() 不退出插件的前提下重新获取数据，数据不更新。

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#910]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家智能多模网关

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:Device

**现象（必填）**
进入插件后通过 Device.getSubDevices() 获取子设备列表，成功获取，此时子设备的数量发生变化，不退出插件的情况下重新进行获取，子设备列表不更新，需要退出插件然后重新进入，子设备列表才会更新。
另外，通过抓包发现，不退出插件进行重新获取并没有发送获取命令，读取的应该是 app 的缓存。

**期望（必填）**
不退出插件的前提下，访问子设备获取接口，可以获得真实数据。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
收到反馈，我们这边会处理

**Comment by zanetti4** [comment]
请把米家智能多模网关分享给我，我进行调试，我的米家 id: 894158105

**Comment by Pandalzm** [comment]
@zanetti4 已经分享了，“Aqara网关 M2” 在设置页中的 “子设备列表”

**Comment by damiknows** [comment]
@zanetti4 昨天分享的设备不小心删除了，重新共享了设备 - 小米米家智能多模网关

**Comment by blockdate** [comment]
已调整，在10020分支默认不会使用缓存数据。请验证

**Comment by damiknows** [comment]
验证OK，数据可以刷新了，感谢 @blockdate

**Comment by Pandalzm** [comment]
android 端也存在这个问题，删除设备后，需要回到米家首页，下拉刷新后再次进入插件，设备列表才会刷新。

**Comment by Pandalzm** [comment]
重新打开

**Comment by lvjie0519** [comment]
@Pandalzm  已修复， 请使用fir上最新apk， sdk 选择10024分支进行验证，谢谢。

**Comment by Pandalzm** [comment]
这个问题修复了，但是没有 iconurl。希望帮忙处理一下。

**Comment by lvjie0519** [comment]
@Pandalzm   确认apk是从 fir上下载的。
