### ISSUE TITLE
小米iot平台，不支持个人开发测试么

### ISSUE THREAD

**Issue by buzai** [MiEcosystem/miot-plugin-sdk#911]

**Comment by buzai** [comment]
这难道想学学还得注册个公司。。。

**Comment by santcool** [comment]
我们这个插件框架，主要是针对于想接入小米iot平台的硬件生产厂商，如果想学习。可以先去学习React Native，学好了之后，再接触此框架，开发起来将会非常简单。May you have a nice day！
