### ISSUE TITLE
第一次添加新设备后无法正常连接设备

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#912]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
米家电子体温计

**项目ID（必填）**
913

**企业名称（必填）**
秒秒测北京

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.4.1]
- SDK分支: [10020]
- 相关模块:[Bluetooth]

**现象（必填）**
第一次添加新设备后，进入插件bluetooth.isConnected返回false，之后调用bluetooth.connect提示无法找到设备，退出后进入插件bluetooth.isConnected返回undefined，之后调用bluetooth.connect可以找到设备，一切正常

**期望（必填）**
第一次进入插件也可以正常连接，记得旧版插件第一次进入插件直接是连接状态

代码：
if (bluetooth.isConnected) {
      console.log("connected");
      bluetooth.startDiscoverServices(BluetoothUUID.SERVICE_MMC, "180A", "1809");
      self.setState({deviceConnected:true});
    } else {
      bluetooth.connect(-1, { timeout: 10000 }).then((data) => {
        self.setState({deviceConnected:true});
        console.log('connected', data);
        bluetooth.startDiscoverServices(BluetoothUUID.SERVICE_MMC, "180A", "1809");
      }).catch((data) => {
        console.log('err', data);
        // this.connect();
      });
    }

**Comment by Android-yzhang** [comment]
没看明白 #855 是怎么处理的

**Comment by blockdate** [comment]
本质上就是蓝牙处于连接状态进入了插件，导致connect 返回 device not found。

解决方法参考如下：

#738 

断开蓝牙后重连即可
