### ISSUE TITLE
消息提示时间有误

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#913]
---
**是否为新品（必填）**新品

**关联的产品名称（必填）**
新品

**项目ID（必填）**
minij.washer.v5

**企业名称（必填）**
小吉科技

**环境（必填）**
- 电脑操作系统:[Windows
- 手机系统:[
- SDK分支: 
- 相关模块:

**现象（必填）**
内测用户米家APP消息中心显示“昨天洗衣完成”，其实是今天刚洗完。

**期望（必填）**
显示今天洗完

**其他的上下文/日志/截图**
小米账号1213667301
**尝试过的解决办法**
重进

**Comment by hao0000** [comment]
mix3手机，高优先级，miui10.3，

**Comment by zanetti4** [comment]
请提供涉及的 SDK分支、相关模块和具体代码，我进行调试。

**Comment by hao0000** [comment]
老sdk的。模块：minij.washer.jumpv5 消息中心界面应该是你们的代码。------------------ 原始邮件 ------------------
发件人: "zanetti4"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 晚上9:15
收件人: "MiEcosystem/miot-plugin-sdk"<miot-plugin-sdk@noreply.github.com>;
抄送: "hao0000"<987158014@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MiEcosystem/miot-plugin-sdk] 消息提示时间有误 (#913)



请提供涉及的 SDK分支、相关模块和具体代码，我进行调试。
 
&mdash;

**Comment by blockdate** [comment]
消息中心的消息数据是根据你们配置的消息推送格式，以及触发消息的上报信息来合成的，这边建议检查下你们上报的数据以及消息推送的配置。
