### ISSUE TITLE
固件更新完成后不退出还提示有新版，实际已经是最新了

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#914]
**是否为新品（必填）**
新品 

**关联的产品名称（必填）**
新品

**项目ID（必填）**
minij.washer.v5

**企业名称（必填）**
小吉科技

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:Android 8.1
- SDK分支: 
- 相关模块:

**现象（必填）**
Android 】固件升级完成后，在此页面不退出 然后还是显示有新版固件-----退出到插件主页在此进入显示正常

**期望（必填）**
更新完成后不显示有新版

**其他的上下文/日志/截图**
暂无

**尝试过的解决办法**
尝试过哪些操作？
此前其他型号也出现过

**Comment by lvjie0519** [comment]
@hao0000 
1、麻烦添加上截图；
2、麻烦提供具体使用的是哪个api，我这边方便排查，谢谢。

**Comment by hao0000** [comment]
老的sdk，使用的api是
/**
 * Apilevel:51
 * 显示下拉菜单, 但是新增了支持对通用设置二级菜单的功能配置
 *
 * @param menus 同上
 * @param useDefault 同上
 * @param requestCode 同上
 * @param params 同上
 * @param commonSettingParams
input_intent
 *        name: "firmware_enable", value: true/false, default: true, 显示/隐藏"检查固件升级"item（分享的设备/子设备/虚拟设备不显示本item）

**Comment by hao0000** [comment]
老的sdk，使用的api是
/**
 * Apilevel:51
 * 显示下拉菜单, 但是新增了支持对通用设置二级菜单的功能配置
 *
 * @param menus 同上
 * @param useDefault 同上
 * @param requestCode 同上
 * @param params 同上
 * @param commonSettingParams
input_intent
 *        name: "firmware_enable", value: true/false, default: true, 显示/隐藏"检查固件升级"item（分享的设备/子设备/虚拟设备不显示本item）

**Comment by hao0000** [comment]
您好，我这里有视频，怎么发给您方便？github上没有找到上传视频的地方

**Comment by lvjie0519** [comment]
@hao0000   你这是使用的旧框架开发的插件？
视频可以压缩成zip文件，直接拖到输入框就可以；

**Comment by hao0000** [comment]
嗯嗯，使用的是旧框架开发的

**Comment by hao0000** [comment]
我这边还是无法上传截图，点编辑是无效的，我智能添加评论，zip文件拖到评论内容里也不生效，我尝试发了邮件给您

**Comment by lvjie0519** [comment]
@hao0000  我的邮箱： lvjie1@xiaomi.com

**Comment by hao0000** [comment]
已与小米开发同学取得联系，目前无法复现，后续如果复现会第一时间与小米同学沟通排查

**Comment by lvjie0519** [comment]
先暂时关闭，如还存在问题，reopen issue。
