### ISSUE TITLE
readFile读取文件失败。

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#915]
**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: 10011
- 相关模块:miot/host/file

**现象（必填）**
今天更新了Android米家客户端测试版本，结果在读取文件的时候失败。
米家客户端版本号：5.5.23.3 测试版 
https://fir.im/MiHomeForAndroid

**其他的上下文/日志/截图**
API接口调用：

    static getByteFromFile(filePath, callback){
        console.log("MYTESTLOG", "filePath = " + filePath);
        Host.file.readFileToHexString(filePath).then(content =>{
            console.log("MYTESTLOG", "content = " + content);
            callback(content);
           }).catch((error, msg) =>{
            console.log("MYTESTLOG", "error = ", error, msg);
           })
    }

调用之后的打印信息为：
<img width="1115" alt="屏幕快照 2019-06-03 17 47 16" src="https://user-images.githubusercontent.com/12670497/58792925-afa23300-8627-11e9-80d0-9b9a2aa01cf3.png">

**Comment by lvjie0519** [comment]
@dgutkai  你的filePath  具体值从哪里来的？  应该传递文件的相对路径，不是绝对路径。

**Comment by dgutkai** [comment]
文件是内存卡目录下的绝对路径，我使用老版本的米家是可以的。

**Comment by dgutkai** [comment]
filePath是SD卡上的绝对路径，在老版本的米家中可以正常读取文件内容。 @lvjie0519

**Comment by lvjie0519** [comment]
@dgutkai   我知道，  最近路径验证有调整，建议你们不要使用绝对路径， 请问是哪个接口会返回文件的绝对路径？

**Comment by dgutkai** [comment]
现在我是测试OTA，所以我把OTA文件放在内存卡上的，后面正式上线会从服务器下载OTA文件。

**Comment by lvjie0519** [comment]
@dgutkai   我们对每个插件都有对应的特有文件目录，需要放到对应的插件目录，建议走下载、解压、读文件这样怎个流程，你可以将文件上传到某个服务平台都可以。
