### ISSUE TITLE
downloadFile下载大资源文件

### ISSUE THREAD

**Issue by lijian9088** [MiEcosystem/miot-plugin-sdk#916]
是否为新品（必填）
新品

关联的产品名称（必填）
米兔儿童牙刷

项目ID（必填）
PRJ18-SOOCA-X-003

企业名称（必填）
舒可士（深圳）科技有限公司

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.2]
SDK分支: [master]
相关模块:[Host.file.downloadFile]
现象（必填）
1.下载资源文件没有进度回调。
2.android下下载资源文件，界面会阻塞，iphone下没有问题。
（progressBar卡住）

期望（必填）
下载有进度回调，下载资源界面不会阻塞。

其他的上下文/日志/截图
![image](https://user-images.githubusercontent.com/14890491/58799514-129bc600-8638-11e9-9056-9d15d9197717.png)

尝试过的解决办法
无

**Comment by lvjie0519** [comment]
@lijian9088   已排查出问题，请耐心等待，完成修复会再此同步。

**Comment by lvjie0519** [comment]
@lijian9088   问题已修复，请使用最新apk 进行测试，谢谢。

**Comment by lijian9088** [comment]
好的，下载资源界面阻塞已解决。谢谢
问一下下载进度回调是否有计划添加接口？

**Comment by lvjie0519** [comment]
@lijian9088  已经支持，参考xiaomi.demo，apk今晚会发一个包，明天可以验证。

**Comment by lvjie0519** [comment]
@lijian9088  请使用最新apk进行验证，sdk选择10021分支，可参考xiaomi.demo实现。

**Comment by lijian9088** [comment]
好的，问题已解决。谢谢。
