### ISSUE TITLE
关于智能配置的问题

### ISSUE THREAD

**Issue by dessmann** [MiEcosystem/miot-plugin-sdk#917]
**公司名称**
德施曼

**是否为新产品**
否

**产品名称/Model**
德施曼Q3智能锁/dsm.lock.q3

**环境**
- 电脑操作系统:  MAC
- 手机系统:  ios 12.2
- SDK分支:   10010
- 相关模块:  智能

**现象**
智能里面，要区分手机蓝牙开锁、密码开锁、指纹开锁，我们现在只定义了密码开锁，但是测试发现这三种方式都能触发智能.

**期望**
智能相互独立，互不影响，定义了蓝牙开锁，则只有蓝牙开锁才触发智能，密码和指纹也一样

**其他的上下文/日志/截图**
在智能的自定义页面已按不同的智能ID回传不同的value
参考一：
       let entryInfo = Package.entryInfo;
        if (entryInfo.payload.id === '1856') {//蓝牙开锁
            entryInfo.payload.value = '0000';
        } else if (entryInfo.payload.id === '1924') {//普通密码开锁
            entryInfo.payload.value = '0001';
        } else if (entryInfo.payload.id === '1888') {//指纹开锁
            entryInfo.payload.value = '0002';
        } else if (entryInfo.payload.id === '1925') {
            entryInfo.payload.value = '0006';
        }
        console.log(entryInfo);
        Package.exit(entryInfo)

参考二：
        let entryInfo = Package.entryInfo;
        if (entryInfo.payload.id === '1856') {//蓝牙开锁
            entryInfo.payload.value = 0;
        } else if (entryInfo.payload.id === '1924') {//普通密码开锁
            entryInfo.payload.value = 1;
        } else if (entryInfo.payload.id === '1888') {//指纹开锁
            entryInfo.payload.value = 2;
        } else if (entryInfo.payload.id === '1925') {
            entryInfo.payload.value = 6;
        }
        console.log(entryInfo);
        Package.exit(entryInfo)

在之定义页面接收到的数据:
{
    "payload":{
        "name":"任意普通密码开锁",
        "default_value":0,
        "value":"0001",
        "src":"device",
        "device_name":"Q32",
        "tr_id":104,
        "scene_type":1,
        "id":"1924",
        "did":"1010851293",
        "device_abbr":"门锁",
        "command":"event.dsm.lock.q3.unlock"
    }
}
在自定义尝试回传的数据：
{
    "payload":{
        "name":"任意普通密码开锁",
        "default_value":0,
        "value":1,
        "src":"device",
        "device_name":"Q32",
        "tr_id":104,
        "scene_type":1,
        "id":"1924",
        "did":"1010851293",
        "device_abbr":"门锁",
        "command":"event.dsm.lock.q3.unlock"
    }
}
或者
{
    "payload":{
        "name":"任意普通密码开锁",
        "default_value":0,
        "value":"0001",
        "src":"device",
        "device_name":"Q32",
        "tr_id":104,
        "scene_type":1,
        "id":"1924",
        "did":"1010851293",
        "device_abbr":"门锁",
        "command":"event.dsm.lock.q3.unlock"
    }
}

**Comment by santcool** [comment]
没太明白你们的意思，能拍个小视频说明下吗？

**Comment by dessmann** [comment]
就是我们只配置了一个智能：
密码开锁的时候米家床头灯打开
但是发现密码开锁、指纹开锁、手机开锁之后，米家床头灯都打开了，需求是：
指纹开锁、手机开锁之后，不打开米家床头灯

**Comment by santcool** [comment]
我懂了，这样实现是不行的，更改value对智能的执行不会有任何影响。正确的做法是，将密码开锁，指纹开锁和手机开锁事件分为2个方法，修改下图中的触发属性，这个需要你们的嵌入式工程师的配合。
<img width="915" alt="屏幕快照 2019-06-03 21 42 18" src="https://user-images.githubusercontent.com/8580061/58806452-c9a03d80-8648-11e9-87e8-7ef3bc6818fe.png">

**Comment by santcool** [comment]
请问现在这个位子还有问题吗？

**Comment by dessmann** [comment]
问题还存在，请问具体需要嵌入式工程师怎么配合，能让双方的嵌入式工程师对接一下吗？
