### ISSUE TITLE
Android偶现 点击桌面快捷方式崩溃

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/miot-plugin-sdk#918]
**企业名称（必填）**
云丁鹿客

**现象（必填）**
门锁产品 ，生成一个桌面快捷方式后。通过快捷方式进入插件，偶现崩溃

![image](https://user-images.githubusercontent.com/13412744/58801924-7b863c80-863e-11e9-8ec5-bde6cecdfce4.png)

**期望（必填）**
不崩溃，如果是已经修复过的问题，就关掉吧，因为当时我们也不清楚app版本多少

**Comment by lvjie0519** [comment]
@zhaolios   用最新apk， 我这边暂时未能复现，该数据是从APP层传递过来，APP层有修复过一版，暂时关闭，如果还出现再reopen。
