### ISSUE TITLE
断网情况下[撤销隐私协议授权]后弹窗错误

### ISSUE THREAD

**Issue by WangWeiYi185** [MiEcosystem/miot-plugin-sdk#919]
**是否为新品（必填）**
 新品

**关联的产品名称（必填）**
70迈智能行车助手

**项目ID（必填）**
产品Model  midr.rv_mirror.m5
pid 66361

**企业名称（必填）**
新案数字科技

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [eg.master/9832]
- 相关模块:[MHMediator/MHStandardMoreSettingsViewController_initWithDevice]

**现象（必填）**
1.进入米家APP设备页-->断开手机网络
2.进入插件->更多>用户协议和隐私政策>撤销授权->左上角返回键

点击撤销授权时没有提示信息，点击返回键时，界面提示“该账号下无法查询到该设备”，点击删除设备时提示“操作失败”

**期望（必填）**
点击撤销授权时有相应的提示信息，不会出现异常的弹窗提示 (安卓正常)

**其他的上下文/日志/截图**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/17384529/58804967-aaec7780-8645-11e9-86de-9d68bb235e22.png">

**不要贴大段代码❗️**

**Comment by santcool** [comment]
点击撤销授权时没有提示信息，点击返回键时，界面提示“该账号下无法查询到该设备”，点击删除设备时提示“操作失败”
---------------------------------------
这个是怎么操作的？我们现有逻辑是，如果撤销隐私授权成功了，就会直接退出插件，如果没有撤销成功，不做任何操作（此处缺少文本提示），不会存在点击返回界面提示“该账号下无法查询到该设备”的情况。

**Comment by Woody2016** [comment]
@WangWeiYi185 请问这个问题出现的几率如何，是必现还是偶现？

**Comment by WangWeiYi185** [comment]
提示 "账号下无法查询到该设备" 不是毕现 , 原因未知

**Comment by santcool** [comment]
我加上了撤销授权失败时的错误提示。明天早上即可在首页下载新包
