### ISSUE TITLE
Service.security.shareSecureKey接口异常

### ISSUE THREAD

**Issue by dzonel** [MiEcosystem/miot-plugin-sdk#92]
sdk和米家都是最新的
手机：iPhone 6
用法：
![1543822659764](https://user-images.githubusercontent.com/12531667/49359996-d3d19580-f712-11e8-8100-9904a778aeab.jpg)
结果：
![1543822460769](https://user-images.githubusercontent.com/12531667/49360002-daf8a380-f712-11e8-84b9-5ee55b74ddca.jpg)

**Comment by Copypeng** [comment]
已确定问题，请等待我们更新iPA文件。

**Comment by dingshaoran** [comment]
android 有没有问题

**Comment by halloaw** [comment]
Android 也是一样的问题 @dingshaoran

**Comment by blockdate** [comment]
问题已解决，请更新SDK。

**Comment by dzonel** [comment]
@blockdate 您好，实测发现，只能通过小米账号分享，无法通过绑定的手机号和绑定邮箱分享。另外，返回的数据中keyID、shareUserID、isOutOfDate三个都是undefined，如图：
<img width="401" alt="wechatimg89" src="https://user-images.githubusercontent.com/12531667/50128037-862a6080-02ae-11e9-932e-54b153836f3e.png">

**Comment by blockdate** [comment]
关于这三个参数为空，可以查看下日志 过滤 ‘shareSecureKey with response:’ 查看实际接口返回的结果，希望您这边能提供一下

**Comment by dzonel** [comment]
@blockdate 您好，返回结果如下图：
<img width="816" alt="image" src="https://user-images.githubusercontent.com/12531667/50276900-0f43c200-047e-11e9-9b52-abd3aa6f7783.png">

**Comment by dzonel** [comment]
会不会是大小写的原因呢？
<img width="454" alt="image" src="https://user-images.githubusercontent.com/12531667/50277332-0f908d00-047f-11e9-949a-6473d0100f20.png">

**Comment by blockdate** [comment]
SDK已更新，请确认问题是否解决

**Comment by dzonel** [comment]
@blockdate 您好，测试发现，没解决，还引入了新的问题
<img width="602" alt="image" src="https://user-images.githubusercontent.com/12531667/50279108-cd1d7f00-0483-11e9-8623-9db8fa2e6c1b.png">


Service.security.loadSecureKeys的结果出现在了.catch中。且数据结构与之前相比，好像发生了变化

**Comment by blockdate** [comment]
不好意思，这个结构变动没注意到，这边再次更新SDK尝试问题是否解决

**Comment by dzonel** [comment]
@blockdate 您好，Service.security.shareSecureKey后crash了：
<img width="791" alt="image" src="https://user-images.githubusercontent.com/12531667/50280531-bbd67180-0487-11e9-87de-99459f0a211c.png">

另外，在刚进入插件页时Service.security.loadSecureKeys
![image](https://user-images.githubusercontent.com/12531667/50280598-e45e6b80-0487-11e9-9962-d142eb311b24.png)
之后进入分享页面，再次Service.security.loadSecureKeys时
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12531667/50280635-ff30e000-0487-11e9-9351-1dd259a81702.png">

**Comment by blockdate** [comment]
crash 问题已修补，数据异常问题暂时无法复现

**Comment by dzonel** [comment]
@blockdate 您好，异常数据是在进入插件页的第一个页面的componentDidMount中调用Service.security.loadSecureKeys出现的。之后在进入其他页面，执行Service.security.loadSecureKeys时，异常数据就没了。

**Comment by dzonel** [comment]
@blockdate 您好，分享结果，数据异常。如图示：
<img width="796" alt="image" src="https://user-images.githubusercontent.com/12531667/50320824-1532b500-0509-11e9-988a-a3fb9e798d72.png">

**Comment by blockdate** [comment]
分享数据异常问题已经fix。
ps。loadSecureKeys数据并不会异常，我正常使用没有问题。在我排查了你提交的代码 #160  之后才复现问题，你再load之后直接使用了remove，这样才导致的SecureKey数据异常。望知晓。

**Comment by blockdate** [comment]
这是由console.log的机制决定的，您有兴趣可自行查阅，不影响使用

**Comment by dzonel** [comment]
@blockdate 好的，多谢。
