### ISSUE TITLE
同环境同接口，苹果返回的数据和安卓不一致，苹果正确，安卓不对

### ISSUE THREAD

**Issue by WWJ1993** [MiEcosystem/miot-plugin-sdk#920]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
“米家iHealth血压计”

**项目ID（必填）**
"model": "ihealth.bp.bpm1“

**企业名称（必填）**
iHealth

**环境（必填）**
电脑操作系统:[Mac OS]
手机系统:[手机型号MI NOTE LTE  安卓版本： Android 6.0.1   MIUI版本： MIUI 9.2]
SDK分支: [master_10000]
相关模块:[miot/service/smarthome.callThirdPartyAPI]

**现象（必填）**
调用这个方法时miot/service/smarthome.callThirdPartyAPI(params)
ios 返回{"code":0,result:{ReturnValue:{"Data:[]",Ts :"1559617511}}}类似的结构；
Android 返回{"code":0,result:{"sid":1983397369,"interver":"1"}},
ios 和Android完全不一致，安卓返回一堆无关紧要的，没有我们想要的数据

**期望（必填）**
因为我们的一款产品已对接过米家老版插件，现在紧急更新新版插件，iOS可调通，但是安卓不可以，影响我们新版插件更新，希望能您能配合着尽快处理

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/19355283/58849599-7c11e800-86bd-11e9-82c7-5bab41379077.png)
<img width="608" alt="屏幕快照 2019-06-04 上午11 40 43" src="https://user-images.githubusercontent.com/19355283/58849663-c85d2800-86bd-11e9-9c74-74558cb76feb.png">

**尝试过的
<img width="608" alt="屏幕快照 2019-06-04 上午11 40 43" src="https://user-images.githubusercontent.com/19355283/58849623-9946b680-86bd-11e9-8dc2-2010fe5932ef.png">
解决办法*
保证在安卓和苹果同一个环境下，同一个接口，同时调试，打印返回结果；
更换不同机型的安卓手机，返回的都一样；
尝试测试其他的接口，安卓和苹果同一个环境下，苹果和安卓返回的数据结构都是如上描述的结构一样，iOS是OK的，安卓返回的没有我们所需要的信息

**Comment by lvjie0519** [comment]
@WWJ1993   sdk master分支代码，或使用目前最新10020分支进行测试

**Comment by lvjie0519** [comment]
暂时关闭，如有问题再reopen。
