### ISSUE TITLE
米家Dialog类组件文字颜色是否可以提供自定义

### ISSUE THREAD

**Issue by fengdexunmi** [MiEcosystem/miot-plugin-sdk#921]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
小米米家智能门锁

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android 9/iOS 11.0
- SDK分支: 10011
- 相关模块: miot/ui

**现象（必填）**
你好，目前我们线上插件（非RN）都是按照miui 10蓝色规范设计的，但是miot/ui提供的dialog类组件文字颜色都是米家绿，是否可以提供自定义颜色或者miui 10蓝色风格

**期望（必填）**
期望InputDialog/MessageDialog/SingleChooseDialog/NumberSpinner等ui组件可以提供文字颜色自定义或者miui 10蓝色风格

**截图**
![image](https://user-images.githubusercontent.com/2813239/58850024-3eae5a00-86bf-11e9-84e8-d6808e9f3bed.png)

**Comment by santcool** [comment]
NumberSpinner即将可以。其他的待和产品过需求，numberSpinner将会发布于SDK_10021版本

**Comment by LiuMengzhou** [comment]
可以使用[时间选择器(MHDatePicker)](https://github.com/MiEcosystem/miot-plugin-sdk/blob/ui_doc/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E6%97%B6%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8mhdatepicker)

**Comment by LiuMengzhou** [comment]
> 可以使用[时间选择器(MHDatePicker)](https://github.com/MiEcosystem/miot-plugin-sdk/blob/ui_doc/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E6%97%B6%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8mhdatepicker)

SDK_10021

**Comment by fengdexunmi** [comment]
@LiuMengzhou  SDK_10021下，时间选择器(MHDatePicker)会闪退，用工程com.xiaomi.demo测试也是一样。

我把时间调到2月28日，然后月份调到3月份，首先会报错，dismiss掉错误页面，然后再滑动day那一列的时候就闪退。

![ezgif-5-49e632cfb43f](https://user-images.githubusercontent.com/2813239/59344105-fab2f900-8d3f-11e9-8637-9720733c2160.gif)

**Comment by LiuMengzhou** [comment]
@lvjie0519 
感谢发现这个问题，可以复现，正在定位解决中。。。

**Comment by lvjie0519** [comment]
@fengdexunmi   @LiuMengzhou    已修复，请使用最新apk进行测试
