### ISSUE TITLE
Host.ui.openCountDownPage倒计时页面一些使用问题

### ISSUE THREAD

**Issue by xyliusun** [MiEcosystem/miot-plugin-sdk#922]
是否为新品（必填）
新品

关联的产品名称（必填）
米家智能插座/lumi.plug.mmeu01

企业名称（必填）
绿米

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[Android 6/iOS 11.4.1]
SDK分支: [10020]
相关模块:[Host.ui.openCountDownPage]

项目ID（必填）
米家欧标插座
model:lumi.plug.mmeu01
项目ID: 21100

现象（必填）
1. 安卓倒计时页面动画为每分钟改变页面，iOS倒计时页面动画为每秒改变页面
2. 安卓倒计时页面转盘动画改变方向为逆时针，iOS为顺时针
3. 安卓与iOS倒计时的圈内文案不统一，安卓为：1分钟后开，iOS为：00:01:00后开启
4. 安卓和iOS开启5分钟的倒计时，一分钟后退出界面再重新进入页面，倒计时转盘从100%重新算起
5. 安卓开启5分钟倒计时，iOS偶现进入倒计时页面显示倒计时从24:00:00开始倒计
6. iOS开启1分钟倒计时并按停止键，倒计时正常执行
7.  安卓开启5分钟倒计时，iOS进入倒计时偶现时间在减少但是转盘动画一直为100%
8. 安卓iOS添加的自定义时间无法删除
9. 安卓开启5分钟倒计时并按停止键，iOS进入倒计时，显示设置倒计时页面，此时在安卓上点击启动会提示设置失败

期望（必填）
1. 两端统一
2. 两端统一
3. 两端统一
4. 安卓和iOS开启5分钟的倒计时，一分钟后退出界面再重新进入页面，倒计时转盘从75%算起
5. 安卓开启5分钟倒计时，显示正确的倒计时
6. iOS开启1分钟倒计时并按停止键，倒计时停止，不会执行
7. 安卓开启5分钟倒计时，iOS进入倒计时时间和动画在同步减少
8. 安卓iOS添加的自定义时间可以删除
9. 安卓开启5分钟倒计时并按停止键，iOS进入倒计时显示倒计时停止的倒计时页面，在安卓上点击启动会继续启动倒计时

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
倒计时这一块我们已经安排人员在进行Android和iOS的功能统一开发了

**Comment by damiknows** [comment]
@blockdate 请问能给一下预期的解决时间吗？6/14号绿米这边计划提测一版新的RN插件

**Comment by zanetti4** [comment]
Duplicate of #734

**Comment by santcool** [comment]
倒计时问题很多，已排期，确定8月份解决倒计时的所有问题。issue暂且关闭，到时出包会知会大家。
