### ISSUE TITLE
缺少homekit绑定API

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#923]
**是否为新品（必填）**
新品 

**关联的产品名称（必填）**
“米家智能多模网关”

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [10020]
- 相关模块:[Host]

**现象（必填）**
缺少绑定设备到HomeKit的接口，以及查询绑定状态

**期望（必填）**
提供绑定设备到HomeKit 和查询绑定状态 的api

**其他的上下文/日志/截图**
iOS原生功能如下图：
![image](https://user-images.githubusercontent.com/15864191/58858861-20eeee00-86db-11e9-9dbe-0f373fb61510.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by damiknows** [comment]
@blockdate 请问有具体排期支持的时间吗？

**Comment by blockdate** [comment]
在处理中

**Comment by blockdate** [comment]
SDK 10021中已添加，请更新app至最新版本(>=250)。
参考com.xiaomi.demo中的DeviceControl
![image](https://user-images.githubusercontent.com/4339364/59399029-0bf21900-8dc5-11e9-808d-1f57e9b16651.png)

**Comment by blockdate** [comment]
如使用有问题，及时反馈

**Comment by damiknows** [comment]
@blockdate 检查绑定状态的接口，获取的状态不对，一直是已经绑定，未绑定到HomeKit的设备获取到的状态也是 已经绑定的
```
Device.checkHomeKitConnected().then(res => {
                        alert((res ? "已经" : "没有") + ' 连入HomeKit')
                    })
```
米家APP线上版本获取到的状态：
![image](https://user-images.githubusercontent.com/15864191/59415445-1973c700-8df6-11e9-95d1-52dbcce8312d.png)

调试时返回的绑定状态：
![image](https://user-images.githubusercontent.com/15864191/59415480-2a243d00-8df6-11e9-9c06-d1622541f235.png)

**Comment by blockdate** [comment]
更新下最新的测试app，验证问题是否处理

**Comment by damiknows** [comment]
绑定状态已验证可以正确获取，谢谢支持
