### ISSUE TITLE
用户体验计划API

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#924]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
“米家智能多模网关”

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.0]
- SDK分支: [10020]
- 相关模块:[Host]

**现象（必填）**
缺少用户体验计划的api

**期望（必填）**
提供用户体验计划的api

**其他的上下文/日志/截图**
页面如下图
![image](https://user-images.githubusercontent.com/15864191/58859616-bc349300-86dc-11e9-89e1-4089a7082310.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
已完成
