### ISSUE TITLE
华为Honor10手机点击插件，米家会闪退

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#925]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统: 华为Honor10 Android 8.1.0
- SDK分支: master
- 相关模块:插件

**现象（必填）**
1、第一次启动米家，点击进入设备插件(正常)
2、退出插件回到米家设备列表主页
3、回到手机主页面使米家回到后台
4、点击米家app进入前台
5、点击插件，米家闪退

**期望（必填）**
点击插件，米家不闪退

**其他的上下文/日志/截图**
![11331559636144_ pic](https://user-images.githubusercontent.com/8509320/58863106-b773dd00-86e4-11e9-9c8f-b6c3d59d9edb.jpg)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@killua4github 
1、使用的是最新apk吗？
2、闪退请提供下log日志，谢谢。

**Comment by killua4github** [comment]
> @killua4github
> 1、使用的是最新apk吗？
> 2、闪退请提供下log日志，谢谢。

是最新的，米家的日志怎么提供给你

**Comment by lvjie0519** [comment]
@killua4github   放到txt文件里面，上传到这里，或者截图关键的错误日志也行。

**Comment by killua4github** [comment]
> @killua4github 放到txt文件里面，上传到这里，或者截图关键的错误日志也行。

我的问题是在哪里可以看到米家的错误日志？

**Comment by lvjie0519** [comment]
Android 用logcat进行查看，如果未安装此工具，先进行安装。

**Comment by lvjie0519** [comment]
@killua4github  如果问题未解决，麻烦提供下log日志，我这边方便排查，谢谢。

**Comment by lvjie0519** [comment]
issue不活跃，暂时关闭，如有问题再reopen。
