### ISSUE TITLE
通用设置固件升级小红点

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#926]
**是否为新品（必填）**
新品

**关联的产品名称（必填）**

**项目ID（必填）**

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android 9]
- SDK分支: [10020]
- 相关模块:[UI]

**现象（必填）**
通用设置里的固件升级能增加小红点吗？

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by LiuMengzhou** [comment]
#775
