### ISSUE TITLE
安卓手机连接蓝牙失败

### ISSUE THREAD

**Issue by caojunhua** [MiEcosystem/miot-plugin-sdk#927]
您好，
       安卓连接蓝牙失败，报错信息如下：'连接失败的error:', { msg: 'CONNECTION_NOT_READY', code: -6 }
       请问这个是什么原因呢?谢谢！

**Comment by zanetti4** [comment]
请按照模版填写具体的信息，谢谢

**Comment by zanetti4** [comment]
code: -6 代表连接不可用，请给出调用 connect 方法的具体代码。

**Comment by cfJand** [comment]
上述问题，可能原因有：1.发现服务超时；2.连接服务超时；3重新连接服务失败。
鉴于这些问题，多存在于连接蓝牙超时，建议提示用户 重试连接。

**Comment by cfJand** [comment]
此issue长时间未回复，关闭。
