### ISSUE TITLE
IOS  TitleBar返回按钮调用Package.exit()函数退出插件没有响应。

### ISSUE THREAD

**Issue by lq790312** [MiEcosystem/miot-plugin-sdk#928]
IOS TitleBar返回按钮调用Package.exit()函数退出插件没有响应。

**Comment by santcool** [comment]
现在好了没有？请参考demo中的使用方式。

**Comment by lq790312** [comment]
没有好 用测试时出现过2次点击， TitleBar返回按钮调用Package.exit()函数退出插件没有响应。

**Comment by zanetti4** [comment]
这是在哪个分支？请按照模版提供详细信息，谢谢

**Comment by zanetti4** [comment]
我在 SDK_10020 上测试，能退出插件。
