### ISSUE TITLE
项目里怎么集成mobx?

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#929]
**是否为新品（必填）**
否

**关联的产品名称（必填）**
即将研发的产品

**项目ID（必填）**
暂无

**企业名称（必填）**
飞利浦照明

**环境（必填）**
- 电脑操作系统:macOS 10.14.3
- SDK分支: [eg.master/10003]

**现象（必填）**
集成mobx管理状态出现各种errors

**期望（必填）**
能够使用mobx

**其他的上下文/日志/截图**
`Requires Babel "^7.0.0", but wa loaded with "6.2.3". if you are sure you have a compatible version of @babel/core,it is likely that somethings in your build process is loading the loading the wrong version,`

**尝试过的解决办法**
尝试不用装饰器
尝试新建一个版本为0.54.4的rn项目集成mobx，成功，在miot-sdk项目里失败

请把在miot-sdk集成mobx并可以使用装饰器 的步骤告知一下，谢谢！
紧急求助
紧急求助
紧急求助
重要的事情说三遍！

**Comment by devYoungyang** [comment]
我使用的mobx版本3.4.1  mobx-react版本4.3.5

**Comment by devYoungyang** [comment]
不使用注解我也尝试过，我是使用最新的mobx版本5.9.4，node服务启动成功，真机报`mobx-react-lite requires React with Hooks support`
Store.js代码块如下：
`
import { observable, computed, action, decorate } from "mobx";
class AppStore {
    clickedCounts = 0;
    addCounts() {
        this.start += 1;
    }
}
decorate(AppStore, {
    clickedCounts: observable,
    addCounts: action
})
export default new AppStore();
`
使用Store的代码块如下：
`
const Home = observer(class HomePage extends Component {
    render() {
        return (
            <View style={{ flex: 1, backgroundColor: '#fff', alignItems: 'center', flexDirection: 'row', justifyContent: 'space-around', padding: 20 }} >
                <Text>{AppStore.start}</Text>
                <Button title='增加' onPress={() => {
                    AppStore.addCounts();
                }
                } />
            </View>
        )
    }
})
export default Home;
`
不实用装饰器这样写有什么问题吗？

**Comment by blockdate** [comment]
参考 
```javascript
'use strict';
import { observable } from 'mobx';
import { observer } from 'mobx-react/native';
import React, { Component } from 'react';
import { StyleSheet, Text, TouchableHighlight, View } from 'react-native';
// 被观察者, 观察 counter 变量  
const storer = observable({
  counter: 0
});
storer.plus = () => {
  storer.counter++;
};
storer.minus = () => {
  storer.counter--;
};
class Counter extends Component {
  render() {
    return (
      <View style={styles.container}>
        {/*加一*/}
        <TouchableHighlight
          onPress={() => { this.props.store.plus() }}>
          <Text>Add</Text>
        </TouchableHighlight>
        {/* 显示处理结果 */}
        <Text style={styles.resultTxtStyle}>
          {this.props.store.counter}
        </Text>
        {/*减一*/}
        <TouchableHighlight
          onPress={() => { storer.minus() }}>
          <Text>Minus</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
// 使用 observer 创建
const CounterComponent = observer(Counter);
export default class MOBXNormal extends Component {
  render() {
    return (
      <View style={{ flex: 1, marginTop: 64 }}>

        <CounterComponent store={storer} />
      </View>
    );
  }
}
/* 样式定义 */
const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-around'
  },
  resultTxtStyle: {
    fontSize: 22,
    color: 'red'
  }
});
```

·

**Comment by devYoungyang** [comment]
@blockdate [logr日志](http://pslz8up93.bkt.clouddn.com/1111.jpeg)
使用mobx版本3.4.1。 error如上图

**Comment by devYoungyang** [comment]
> 参考 ,可以直接在demo中运行使用
> 
> ```js
> 'use strict';
> import { observable } from 'mobx';
> import { observer } from 'mobx-react/native';
> import React, { Component } from 'react';
> import { StyleSheet, Text, TouchableHighlight, View } from 'react-native';
> // 被观察者, 观察 counter 变量  
> const storer = observable({
>   counter: 0
> });
> storer.plus = () => {
>   storer.counter++;
> };
> storer.minus = () => {
>   storer.counter--;
> };
> class Counter extends Component {
>   render() {
>     return (
>       <View style={styles.container}>
>         {/*加一*/}
>         <TouchableHighlight
>           onPress={() => { this.props.store.plus() }}>
>           <Text>Add</Text>
>         </TouchableHighlight>
>         {/* 显示处理结果 */}
>         <Text style={styles.resultTxtStyle}>
>           {this.props.store.counter}
>         </Text>
>         {/*减一*/}
>         <TouchableHighlight
>           onPress={() => { storer.minus() }}>
>           <Text>Minus</Text>
>         </TouchableHighlight>
>       </View>
>     );
>   }
> }
> // 使用 observer 创建
> const CounterComponent = observer(Counter);
> export default class MOBXNormal extends Component {
>   render() {
>     return (
>       <View style={{ flex: 1, marginTop: 64 }}>
> 
>         <CounterComponent store={storer} />
>       </View>
>     );
>   }
> }
> /* 样式定义 */
> const styles = StyleSheet.create({
>   container: {
>     flexDirection: 'row',
>     justifyContent: 'space-around'
>   },
>   resultTxtStyle: {
>     fontSize: 22,
>     color: 'red'
>   }
> });
> ```
> 
> ·

你这个使用mobx版本是多少？不需要安装其他插件吗？  .babelrc也不需要配置？

**Comment by devYoungyang** [comment]
你那个不启用装饰器语法的代码我运行成功了。
