### ISSUE TITLE
缺少 安卓平台 bindDevice 和 setAlertConfigs 对应接口。

### ISSUE THREAD

**Issue by ftc300** [MiEcosystem/miot-plugin-sdk#93]
安卓原生插件使用
```
XmBluetoothManager.getInstance().bindDevice(MAC);
XmBluetoothManager.getInstance().setAlertConfigs(MAC, ALERT_INCALL_IN_CONTACTS_ENABLED, true);
```

来打开来电提醒功能，在新sdk中未找到相应接口

**Comment by dingshaoran** [comment]
bluetooth下添加了bindDeviceforMIUI unBindDeviceforMIUI setAlertConfigsMIUI 三个方法

**Comment by ftc300** [comment]
感谢支持。调用 Bluetooth.bindDeviceforMIUI() 和 Bluetooth.setAlertConfigsOnMIUI(1,true)  使用正常。
但是调用 Bluetooth.unBindDeviceforMIUI() 时报错如下：
![_20181211184101](https://user-images.githubusercontent.com/12816061/49795201-593cf180-fd74-11e8-9c37-d971358c30b4.jpg)
@dingshaoran
