### ISSUE TITLE
旧框架MHPluginSDK.callSmartHomeAPI set_extra_data&get_extra_data接口替换问题

### ISSUE THREAD

**Issue by CJackKao** [MiEcosystem/miot-plugin-sdk#930]
**是否为新品（必填）**
在售

**关联的产品名称（必填）**
米家电磁炉

**企业名称（必填）**
纯米

**环境（必填）**
- 电脑操作系统:[Windows]
- 手机系统:[Android / iOS]
- SDK分支: [10010]

**现象（必填）**
麻烦问下, 有关旧框架MHPluginSDK.callSmartHomeAPI的/v2/device/set_extra_data以及 /v2/device/get_extra_data在新框架中是替换成哪個接口了?

**尝试过的解决办法**
1. 有关set_extra_data的部份, 原本有在新框架中找到smarthome.deviceSetExtraData这个接口做替换, 但这接口后来版本似乎被废弃了, 也找不到其它可替换的接口了

**Comment by blockdate** [comment]
建议使用 batchGet/SetDeviceDatas,作为新的数据存储方案。
deviceGet/SetExtraData 暂时任然可以使用，建议在使用过程中，将deviceGet/SetExtraData 中的数据转移到 batchGet/SetDeviceDatas 接口中

**Comment by CJackKao** [comment]
感谢~
问题已解
