### ISSUE TITLE
平台发布测试不成功

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#931]
---
**是否为新品（必填）**
新品

**关联的产品名称（必填）**
solista 智能炒菜机

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:/Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: master
- 相关模块:插件

**现象（必填）**
在平台上传了测试包，点击开启测试后，再次刷新页面有需要点击开启测试

**期望（必填）**
正常开启测试

**其他的上下文/日志/截图**
之前开启测试之后是这样的：
![10491559273860_ pic_hd](https://user-images.githubusercontent.com/8509320/58927646-fdcb4980-8781-11e9-9ac0-618ae14d5bad.jpg)
现在开启测试之后是这样的：
<img width="1030" alt="屏幕快照 2019-06-05 上午11 00 35" src="https://user-images.githubusercontent.com/8509320/58927661-0f145600-8782-11e9-9041-31100dd88f99.png">
刷新之后又变成这样了：
<img width="1033" alt="屏幕快照 2019-06-05 上午11 00 22" src="https://user-images.githubusercontent.com/8509320/58927670-19365480-8782-11e9-957c-595a1e107244.png">

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by JxXiaoXie** [comment]
同样问题 插件Id 1161

**Comment by zanetti4** [comment]
请 @blockdate 看下次问题先

**Comment by blockdate** [comment]
这个已经处理了，后台FDS限额问题。
