### ISSUE TITLE
分屏模式下无法调整程序顺序并保存

### ISSUE THREAD

**Issue by hao0000** [MiEcosystem/miot-plugin-sdk#932]
**是否为新品（必填）**
 新品 

**关联的产品名称（必填）**
新品

**项目ID（必填）**
minij.washer.v5

**企业名称（必填）**
小吉科技

**环境（必填）**
- 电脑操作系统：Windows
- 手机系统：Android 8.1
- SDK分支: 
- 相关模块:

**现象（必填）**
分屏模式下不能对程序进行排序保存

**期望（必填）**
分配模式可以对程序排序保存

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by hao0000** [comment]
手机型号redmi K20

**Comment by hao0000** [comment]
手机型号redmi K20

**Comment by hao0000** [comment]
手机型号redmi K20

**Comment by zanetti4** [comment]
不清楚您在问什么，请提供更多详细信息，如截图，视频等
