### ISSUE TITLE
Android手机本地调试问题

### ISSUE THREAD

**Issue by killua4github** [MiEcosystem/miot-plugin-sdk#933]
---
**是否为新品（必填）**
新品

**关联的产品model**
jyaiot.cm.ccj01

**项目ID（必填）**
1251

**企业名称（必填）**
九阳

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android
- SDK分支: master
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
1、android系统的手机完成相关设置，
2、开启本地服务（手机和电脑处于同一wifi环境下）
3、点击绑定的设备（chrome浏览器弹出React Native Debugger页，按住command + shift + i 进入调试页）
4、Console里出现报错
5、然后摇晃手机点击Stop Remote JS Debugging
6、点击刷新，成功进入插件

**期望（必填）**
不需要第5步的关闭远程调试就可以进入插件

**其他的上下文/日志/截图**
1、按照文档进行相关设置
![2711559719423_ pic](https://user-images.githubusercontent.com/8509320/58937766-f322ab80-87a5-11e9-8a17-e9d4e423b0d7.jpg)
2、点击插件后浏览器出现如下报错
<img width="1129" alt="屏幕快照 2019-06-05 下午3 13 26" src="https://user-images.githubusercontent.com/8509320/58938118-c28f4180-87a6-11e9-885a-29a5aef88a42.png">
3、点击关闭远程调试
![2731559719768_ pic](https://user-images.githubusercontent.com/8509320/58938152-ccb14000-87a6-11e9-8dca-0210a579fa53.jpg)
4、成功进入插件
![2701559719422_ pic](https://user-images.githubusercontent.com/8509320/58938183-daff5c00-87a6-11e9-9e12-bcc38c053193.jpg)

**尝试过的解决办法**
之前有说在哪里设置localhost,有尝试在ip设置那里设置过，但是不行

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
1、遇到问题，建议先通过关键字搜索下issue，看是否有相同问题；
2、Android开启浏览器调试，需要将ip地址修改为localhost；
https://github.com/MiEcosystem/miot-plugin-sdk/issues/832

**Comment by killua4github** [comment]
> 1、遇到问题，建议先通过关键字搜索下issue，看是否有相同问题；
> 2、Android开启浏览器调试，需要将浏览器的ip地址修改为localhost；
> #832

知道了
