### ISSUE TITLE
不连接网关，蓝牙开门也能收到推送问题

### ISSUE THREAD

**Issue by changgongxinshi** [MiEcosystem/miot-plugin-sdk#935]
**是否为新品（必填）**
 新品 

**关联的产品model**
dsm.lock.q3

**企业名称（必填）**
德施曼

**现象（必填）**
用蓝牙开门不连接网关的时候，也能收到推送和开门记录。如果连接网关，一次蓝牙开门，会收到两条开门推送，两条开门记录。
android和ios都有这个问题
用指纹和密码开门没有这个问题，
用测试版本的米家APP也没有这个问题。

**期望（必填）**
能像之前一样，不连接网关，不收到推送消息

**其他的上下文/日志/截图**

![image](https://user-images.githubusercontent.com/16306138/58944939-667fe980-87b5-11e9-9c28-3f2ce4ec029c.png)

**Comment by zanetti4** [comment]
请提供 uid 或者设备 id，我们这边进行排查。

**Comment by changgongxinshi** [comment]
did:1010851293 
uid:1404769031
麻烦帮忙排查一下

**Comment by changgongxinshi** [comment]
您好，问题有结果了吗？请帮忙处理下！

**Comment by zanetti4** [comment]
@Copypeng @dingshaoran 请你们协助查看此问题

**Comment by changgongxinshi** [comment]
现在用蓝牙开门，连接网关的情况下，只会收到一条推送了，但是获取的开门记录还是一次开门能获取到两条
