### ISSUE TITLE
iOS蓝牙设备第一次添加后，插件无法检测蓝牙连接状态，导致插件显示未连接

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#937]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA App Store V4.17.2
- SDK master最新

---
**是否为新品（必填）**
在售

**关联的产品model**
roidmi.vacuum.v1

**项目ID（必填）**
无项目ID

**企业名称（必填）**
睿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:[eg.iOS9-12
- SDK分支:  master
- 相关模块:[eg.BluetoothLE]

**现象（必填）**
1、第一次添加设备，进入插件
2、由于未调用 ble.connect()前，获取 Device.getBluetoothLE().isConnect始终为undefined，故
插件会先调用 ble.connect()
3、通常调用connect()后，会回调连接成功
4、最新版本测试，会回调错误结果：{"message":"device not found","code":-7}
5、android上无问题，正常connect

**期望（必填）**
iOS在设备第一次添加环境（即进入插件时，蓝牙已经连接），调用ble.connect()能够返回连接成功回调

**尝试过的解决办法**
1、尝试过开发版ipa、线上版ipa、debug环境、白名单环境，问题都一样

**Comment by blockdate** [comment]
本质上就是蓝牙处于连接状态进入了插件，导致connect 返回 device not found。

解决方法参考如下：

#738 

断开蓝牙后重连即可

**Comment by edwardair** [comment]
意思就是插件每次进入，都要先 disconect一次嘛。。。。

**Comment by blockdate** [comment]
可以不重连，retrieve之后connect -3 作为普通蓝牙处理即可。

根据这一块收到的反馈，我们会对这一情形进行优化处理。

**Comment by 123start** [comment]
@blockdate 我们的小夜灯产品也遇到同样问题，首次绑定进入插件报code = -7，需要再按一下蓝牙广播按钮才能连上，按照你们提供的方法，重连也是要设备重新发送蓝牙广播，请给一个解决方案

**Comment by 123start** [comment]
> 意思就是插件每次进入，都要先 disconect一次嘛。。。。

请问下解决了吗，怎么解决的
