### ISSUE TITLE
Loading Dialog样式Android和iOS的不一致

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#938]
**是否为新品（必填）**
在售

**关联的产品model**
小米米家智能门锁 lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
之前写原生插件时，Android是根据MIUI 10的风格样式做的，现在RN提供的样式是比较老的样式，希望Android的样式和iOS统一。

**期望（必填）**
希望Android的样式和iOS一样，

**其他的上下文/日志/截图**

目前Android的：
![image](https://user-images.githubusercontent.com/46777658/59006678-d180fd00-8855-11e9-86fa-fc5c089bd13f.png)

iOS的：
![image](https://user-images.githubusercontent.com/46777658/59006704-ef4e6200-8855-11e9-8b3d-f5facc915ba3.png)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@LiuMengzhou 请你看一下这个问题

**Comment by LiuMengzhou** [comment]
#877

**Comment by LiuMengzhou** [comment]
#719

**Comment by LiuMengzhou** [comment]
原生组件改动较麻烦，纯JS版正在开发中。推荐：

等不及，自己实现
等（大约本月输出）
