### ISSUE TITLE
ImagePicker选择图片回调未执行

### ISSUE THREAD

**Issue by BaroneX** [MiEcosystem/miot-plugin-sdk#939]
**是否为新品（必填）**
在售

**关联的产品model**
yeelink.light.bslamp1
yeelink.light.bslamp2
yeelink.light.bslamp3
yeelink.light.strip1
yeelink.light.strip2
yeelink.light.color1
yeelink.light.color2
yeelink.light.color4

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 4.4-9.0]
- SDK分支: [10020]
- 相关模块:[ImagePicker]

**现象（必填）**
小米提供的Demo->ImagePickerDemo,
ImagePicker在安卓上选择图片,回调未执行,
iOS上能够成功回调

**期望（必填）**
成功进入回调逻辑

**其他的上下文/日志/截图**
米家版本
![image](https://user-images.githubusercontent.com/6743367/59010478-009e6b00-8864-11e9-8b33-90a33b1ecb89.png)

![image](https://user-images.githubusercontent.com/6743367/59010457-ebc1d780-8863-11e9-8cd3-60020afe6b87.png)

**尝试过的解决办法**

**不要贴大段代码❗️**

**Comment by Android-yzhang** [comment]
我也是 #867

**Comment by zanetti4** [comment]
@lvjie0519 我在安卓上测试，点击 Select a Photo 按钮后，立即点击手机的后退按钮，能触发回调函数。但是从相册或者拍照选择照片后，不会触发。
我看了一下 npm 的 [react-native-image-picker](https://www.npmjs.com/package/react-native-image-picker) 模块，如果传入该网站提供的 options，选择 Choose Photo from Facebook 可以触发回调函数。请你查看

**Comment by lvjie0519** [comment]
@zanetti4 @BaroneX   ok， 问题已知，我这边排查修复，修复完成及时在这里反馈。

**Comment by BaroneX** [comment]
大佬 这个问题修改了没,麻烦抽空给解决一下

**Comment by lvjie0519** [comment]
@BaroneX   明天排查，有结论及时反馈。

**Comment by lvjie0519** [comment]
@BaroneX   问题已修复，  请使用最新apk 进行测试。

**Comment by zanetti4** [comment]
@BaroneX 测试后如没有问题，请关闭此 issue，谢谢
