### ISSUE TITLE
react-native-camera API中不支持Camera.PreviewCallback的回调

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/miot-plugin-sdk#940]
**是否为新品（必填）**
 在售

**关联的产品model**
yeelink.light.bslamp1
yeelink.light.bslamp2
yellink.light.bslamp3
...

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
Yeelight

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 4.4及以上]
- SDK分支: [master/10020]
- 相关模块:[react-native-camera]

**现象（必填）**
查看react-native-camera库，Camera.PreviewCallback被设置成了null，没有回调功能

**期望（必填）**
  1、希望在RN层开放Camera.PreviewCallback回调，我们需要在摄像头拍照前preview的是有捕捉镜头上的图像，并进行YUV转RGB操作，具体实现功能类似：https://blog.csdn.net/iblade/article/details/66968626
  2、能同步支持Android和IOS最好
**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
   查看源码
   在小米demo中测试摄像头相关的功能

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@blockdate 请你在 RN 层开放此回调

**Comment by blockdate** [comment]
详细描述下这个功能的用途吧，直接扩展三方库的行为，一般是不建议的。

**Comment by DennisJu007** [comment]
嗯针对对这个callback回调的需求，具体功能就是开启摄像头的时候，获取摄像头预览界面的YUV的data数据，我们拿到data数据将其转换成RGB的形式并设置到灯上
![1201560135401_ pic_hd](https://user-images.githubusercontent.com/42829167/59169833-7c532d00-8b6e-11e9-8deb-f574fe42f893.jpg)

**Comment by Woody2016** [comment]
@DennisJu007 

这个库是第三方的，我们不好直接去改代码
关于这个需求，请考虑下有没有别的解决方案

**Comment by TheWalkingDead1024** [comment]
> @DennisJu007
> 
> 这个库是第三方的，我们不好直接去改代码
> 关于这个需求，请考虑下有没有别的解决方案

嗯嗯，非常感谢。请问能否在SDK中给支持这样一个接口呢？调用原生摄像头，像素点位置为输入参数，接口输出是该像素点的RGB值。或者还有什么其他实现方式呢？之前旧框架我们是要打一个静态库在米家App里面，只是这样实现对于米家App也不是一个好的实现方式，米家App可能也会越来越冗余，希望有更好的解决方案。

**Comment by DennisJu007** [comment]
这个优先级还是很高的，牵扯到在售的产品 @Woody2016

**Comment by Woody2016** [comment]
插件里可不可以尝试截图，然后获取某个像素点的rgb值？

**Comment by TheWalkingDead1024** [comment]
> 插件里可不可以尝试截图，然后获取某个像素点的rgb值？

谢谢武哥的方案。我们想了一下，如果频繁截图，耗费资源肯定是比较大的，体验也不好，用户看到的像素点RGB值会不是很实时，使用起来会比较卡顿。毕竟这是在视频流数据中获取某一帧图片某个像素点的数据，如果获取像素点rgb值实时性不高的话，都会影响用户使用体验。

**Comment by zanetti4** [comment]
@DennisJu007 @TheWalkingDead1024 请问这个问题还要提供支持吗？

**Comment by santcool** [comment]
没人回复，问题关闭。要是还有需求，请重开issue
