### ISSUE TITLE
android上CommonSetting每一行都没有右箭头

### ISSUE THREAD

**Issue by Banjiemin** [MiEcosystem/miot-plugin-sdk#941]
公司名称（必填）
江苏紫米电子技术有限公司

是否为新产品（必填）
新

产品名称/Model（必填）
米家智能驱蚊器/zimi.mosq.v1

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[Android 7/iOS 10.3.3]
SDK分支: [master/10011/]
相关模块:[miot/ui/CommonSetting]
现象（必填）
android apk正式版上，每一条都没有右箭头，
android apk测试版正常，ios都正常 。
![20190606_1538](https://user-images.githubusercontent.com/44045029/59015374-6a714180-8871-11e9-94db-8f6000a95c39.png)

**Comment by zanetti4** [comment]
@LiuMengzhou 我在10011进行测试，安卓米家正式版能显示右侧箭头。请你查看

**Comment by zanetti4** [comment]
你的米家 app 是什么版本？

**Comment by Banjiemin** [comment]
奇怪了，今天在5.5.25版本上测试，右箭头又出现了？

之前我们两个项目，QA都发现这个问题的 。

解决就好，先关闭 。

**Comment by edwardair** [comment]
Android 正式版 5.5.25 刚刚测试，没有右箭头+1啊，SDK分支是10012（master最新）
@zanetti4
