### ISSUE TITLE
Android 报了一堆SDK的错误，插件界面不能正常显示。

### ISSUE THREAD

**Issue by balddonkey** [MiEcosystem/miot-plugin-sdk#942]
是否新品：新品

model: opple.light.cablelamp

无项目ID

欧普

macOS Mojave 10.14.3
Android6.1
SDK: master 10005
整体现象

现象：
在iOS12.1上面跑起来完全正常的插件，在Android上面完全没办法工作，控制台也没有报错，不知道怎么解决了，以下是截图：
![753C2D4CDE2D196F99A7A752CC47E60B](https://user-images.githubusercontent.com/7577854/59018567-be335900-8878-11e9-8ba8-45a6ede805c1.jpg)

期望：
插件可以正常工作。

请问我该如何排查这个问题，ReactNative debug工具也完全没有报错，该有的log都有，一切正常就是界面显示不出来。

**Comment by balddonkey** [comment]
附加:
![image](https://user-images.githubusercontent.com/7577854/59019736-2aaf5780-887b-11e9-8af9-5a50b3675959.png)

**Comment by balddonkey** [comment]
附加：
![第三方库](https://user-images.githubusercontent.com/7577854/59019898-7104b680-887b-11e9-9163-c07cdb72bab2.png)
使用了这两个第三方库

**Comment by blockdate** [comment]
建议检查下是否使用了  bool && <View/> 这种语法的使用，如果有，建议改成 bool ? <View> : null 这种格式

**Comment by balddonkey** [comment]
> 建议检查下是否使用了 bool && View 这种语法的使用，如果有，建议改成 bool ? View : null 这种格式

![1A5D01B6D1CD52783AAD3639E73FBE86](https://user-images.githubusercontent.com/7577854/59020487-b1186900-887c-11e9-8aa9-2b0f66ddec36.jpg)
你好，多谢回复，现在报的这些错误，请问这些是什么原因～

**Comment by balddonkey** [comment]
> 建议检查下是否使用了 bool && View 这种语法的使用，如果有，建议改成 bool ? View : null 这种格式

附加：
未使用 bool && View 这种写法，代码里面有些 onCancel && onCancel(); 这种类似写法，已经全部替换成了常规的写法。

**Comment by zanetti4** [comment]
你可以看一下这篇[帖子](https://blog.csdn.net/wapchief/article/details/79917190)，该帖子和你说的有点儿像，是否能解决问题？

**Comment by balddonkey** [comment]
> 你可以看一下这篇[帖子](https://blog.csdn.net/wapchief/article/details/79917190)，该帖子和你说的有点儿像，是否能解决问题？

真的很头疼，你们的Android调试app也太难用了，切换过缓存没办法清，我切换过model以后，打开的还是小米测试程序，我选的是自己的model，应该进入自己的程序界面啊，用iOS是没问题的，我甚至把npm关掉，Android仍然能进入小米测试程序，太难受了。

**Comment by lvjie0519** [comment]
1、请说明下你具体使用的Android  apk是哪个版本？
2、你们的Android调试app也太难用了，切换过缓存没办法清， 请问这句话具体什么意思，没看明白；
3、我切换过model以后，打开的还是小米测试程序，我选的是自己的model；
这里是指开发者设置的过程吗？ 切换过model，添加model和packageName请确认添加成功了吗？设置完成后，回到米家首页设备列表页面进入插件，第一次确实可能存在进入的是之前设置的packageName对应的插件页面，退出插件之后再进入插件肯定是不会的；

**Comment by balddonkey** [comment]
1、版本是今天刚刚从fir下载的。
2、缓存现在我是用设置中的应用程序管理来清理，可以清除了。
3、model没有填错，因为一开始我用的是我们自己的model，后来切换到小米测试demo，然后查看过我需要看的东西以后，我切换回来我们自己的model，然后无论我关闭npm在开启，app重启，开发模式开关无数遍都没用，我甚至关掉npm，依然进入小米的测试app，最后我卸载掉重装了（注：这个时候我还没有想起使用设置中应用程序管理来清理数据这个方法）。

**Comment by lvjie0519** [comment]
请截图看下你的开发者设置页面（ 我的-->开发者设置 ）， 相同的model如果绑定了两个package，请删除掉其中一个，左滑item，即可删除对应的item， 无需清楚缓存或卸载重装apk等操作。

**Comment by balddonkey** [comment]
> 请截图看下你的开发者设置页面（ 我的-->开发者设置 ）， 相同的model如果绑定了两个package，请删除掉其中一个，左滑item，即可删除对应的item， 无需清楚缓存或卸载重装apk等操作。

已经卸载重装了，之前尝试过删除，删掉以后进入的仍然是小米测试demo，删掉小米的model以后，重启app，进入开发者设置界面（即model列表界面），小米测试model仍然存在，多次尝试都是如此，没有办法我就重装了，现在只添加了我们自己的model。

**Comment by lvjie0519** [comment]
@balddonkey    进入到插件页面时，如果显示的任然是之前的缓存界面内容，也可以点击 "debug 调试",  可以重新加载js  bundle 文件，有尝试过吗？ 请问如上issue问题是否可以复现？

**Comment by balddonkey** [comment]
> @balddonkey 进入到插件页面时，如果显示的任然是之前的缓存界面内容，也可以点击 "debug 调试", 可以重新加载js bundle 文件，有尝试过吗？ 请问如上issue问题是否可以复现？

可以重现，以下是步骤
安装fir app，登录开启开发者模式，填写我们公司的model，回到到米家首页设备列表，选择我们的设备，进入我们的插件界面，然后回到开发者们模式设置界面，添加米家测试model（com.xiaomi.demo，zimi.clock.myk01），反勾选掉我们的model只留下米家测试demo的model，然后点击下面的直接调试，进入的插件页是我们产品的插件页，非米家demo的插件页，关掉npm后点击直接调试还可以进入插件页（依然是我们的插件页），然后重启app，重启npm，点击开发者模式设置界面的直接调试依然会进入我们产品的插件页（注：一直保持的米家demo的model选中状态，我们自己产品的model未选中状态）。

尝试了一下点击 "debug 调试"，可以正常加载米家demo的插件了。

**Comment by balddonkey** [comment]
> @balddonkey 进入到插件页面时，如果显示的任然是之前的缓存界面内容，也可以点击 "debug 调试", 可以重新加载js bundle 文件，有尝试过吗？ 请问如上issue问题是否可以复现？

可以重现，以下是步骤
测试设备：乐视2 Android6.1
安装fir app，登录开启开发者模式，填写我们公司的model，回到到米家首页设备列表，选择我们的设备，进入我们的插件界面，然后回到开发者们模式设置界面，添加米家测试model（com.xiaomi.demo，zimi.clock.myk01），反勾选掉我们的model只留下米家测试demo的model，然后点击下面的直接调试，进入的插件页是我们产品的插件页，非米家demo的插件页，关掉npm后点击直接调试还可以进入插件页（依然是我们的插件页），然后重启app，重启npm，点击开发者模式设置界面的直接调试依然会进入我们产品的插件页（注：一直保持的米家demo的model选中状态，我们自己产品的model未选中状态）。

尝试了一下点击 "debug 调试"，可以正常加载米家demo的插件了。

**Comment by balddonkey** [comment]
> @balddonkey 进入到插件页面时，如果显示的任然是之前的缓存界面内容，也可以点击 "debug 调试", 可以重新加载js bundle 文件，有尝试过吗？ 请问如上issue问题是否可以复现？

还有，调试是通过同局域网设置ip端口，然后调试的。

**Comment by lvjie0519** [comment]
> @balddonkey 进入到插件页面时，如果显示的任然是之前的缓存界面内容，也可以点击 "debug 调试", 可以重新加载js bundle 文件，有尝试过吗？ 请问如上issue问题是否可以复现？
> 
> 可以重现，以下是步骤
> 测试设备：乐视2 Android6.1
> 安装fir app，登录开启开发者模式，填写我们公司的model，回到到米家首页设备列表，选择我们的设备，进入我们的插件界面，然后回到开发者们模式设置界面，添加米家测试model（com.xiaomi.demo，zimi.clock.myk01），反勾选掉我们的model只留下米家测试demo的model，然后点击下面的直接调试，进入的插件页是我们产品的插件页，非米家demo的插件页，关掉npm后点击直接调试还可以进入插件页（依然是我们的插件页），然后重启app，重启npm，点击开发者模式设置界面的直接调试依然会进入我们产品的插件页（注：一直保持的米家demo的model选中状态，我们自己产品的model未选中状态）。
> 尝试了一下点击 "debug 调试"，可以正常加载米家demo的插件了。

以上是正常情况，调试状态下默认是加载手机本地缓存，进入插件后点击 “debug 调试”, 就会再次加载最新的bundle文件。

**Comment by zanetti4** [comment]
@balddonkey 如果此问题已得到解决，请您关闭，谢谢
