### ISSUE TITLE
CommonSetting在小米手机中title默认是白色

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#943]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）新品
填 新品 or 在售

**关联的产品model**   msj.f_washer.m1
此issue关联的产品model，如“xiaomi.demo.v1”

**项目ID（必填）**  pid：1364
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**  美高厨具
贵司的名称

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]  Mac OS/
- 手机系统:[eg.Android 8.1/iOS 11.0]  Android 9
- SDK分支: [eg.master/10000/...]   10004
- 相关模块:[eg.Host/Service/Account] HOST

**现象（必填）**
CommonSetting 在小米手机上title显示白色，手机型号是 Redmi 4A,在iOS上是title是黑色的。

**期望（必填）**
简单明了地描述一下期望的表现。
希望在小米手机上是白色的。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![IMG_6055](https://user-images.githubusercontent.com/18374383/59026798-dc558500-8889-11e9-9d02-609c7b3d99f9.JPG)

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@LiuMengzhou 我在我的安卓手机上测试，能显示 title，请你查看。

**Comment by Aub1nLin** [comment]
这个手机很坑爹，你还是手动设置一下字体的颜色

**Comment by zhuxinleibandou** [comment]
> 这个手机很坑爹，你还是手动设置一下字体的颜色

请问是在哪个文件里设置字体的颜色？ 我们设置了很久，发现没有用，不知道是不是没有设置对地方 -  尴尬，谢谢！

**Comment by LiuMengzhou** [comment]
@Aub1nLin @zhuxinleibandou 
已知问题，已修复 #771
请升级SDK
