### ISSUE TITLE
新手关于几个设备控制api的问题

### ISSUE THREAD

**Issue by zouzhe1** [MiEcosystem/miot-plugin-sdk#944]
我发现设备控制页面的api，好像就这3个是最主要的。
但是api里面对这几个函数的介绍也太简陋了。
1，iDeviceWifi.callMethod(method, args, extraPayload),
2，deviceReceivedMessages (device, messages, originData)
3，iDeviceWifi.subscribeMessages(...propertyOrEventNames)

我想说说，我对这3个函数的理解，请你们帮看一下，对不对。
1，这个呼叫方法，是不是就是把我们在web页设置的method的名字和参数，以json方式发给设备的串口？我只在开发板的自带usb看到了信息，却没有在io16 io17看到信息(esp32)。那么问题来了，这个io16 io17才是连接mcu的串口，这里没有信息，我该怎么办？

3，api页面就说了一句，订阅设备消息。我也不知道啥意思。请问第二个不就是从设备取得信息用的吗？这个第三个什么意思呢？

最终，我就是想实现一个按钮控制设备开关的功能。
是不是只用1,2就可以实现？哪里有更详细的说明吗？
你们有官方技术支持qq群吗？
给你们发邮件简直费劲，这都2019年了，沟通竟然还这么困难吗？

**Comment by blockdate** [comment]
1. 用于通过OT服务端向设备发送RPC指令，进行直接控制设备行为的操作。

2. 3. 这两个方式是组合使用的，通过subscribeMessages 声明订阅那些prop、event的变化，然后通过deviceReceivedMessages监听prop、event的变更通知。其中第二个是通过消息订阅实现的，是被动的接收设备推送的数据，并且需要提前订阅声明。

至于官方沟通群，这边使用微信群沟通，这个每个公司都可以有一到两个入群，建议找对接的产品来拉入群。
