### ISSUE TITLE
从通用设置返回主界面，状态栏问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#946]
**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1]
- SDK分支: [10020]
- 相关模块:[UI]

**现象（必填）**
安卓5.5.23.5测试版，将插件上传到小米云再载入到手机出现如下问题：

1.使用TitleBar这个控件

2.安卓主界面-->进通用设置界面-->再进主界面，顶部标题栏字体变黑

3.进入插件后，点击…，进入到通用设置页面，在修改名称后顶部时间栏会显示空白

![image](https://user-images.githubusercontent.com/5188922/59170699-6f383d00-8b72-11e9-8e7a-974e0b0eaade.png)

![image](https://user-images.githubusercontent.com/5188922/59170768-b3c3d880-8b72-11e9-8c8a-5b595d7fad03.png)

![image](https://user-images.githubusercontent.com/5188922/59170708-765f4b00-8b72-11e9-92ca-05cec3207bcb.png)

![image](https://user-images.githubusercontent.com/5188922/59170813-de159600-8b72-11e9-86ad-126a41fee9b2.png)

![image](https://user-images.githubusercontent.com/5188922/59170703-72cbc400-8b72-11e9-98a0-4ba7d0b7028f.png)

安卓5.5.23.5测试版，将插件从电脑编译到手机不出现如上问题。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@lvjie0519 我在安卓系统用米家 APP 测试，没有顶部状态栏文字颜色变黑的问题。第二个问题，我修改设备名称失败，但是顶部状态栏不会消失，修改设备名称时点击取消，状态栏也不会消失。个人感觉这与 TitleBar 无关，请你查看。

**Comment by mirse** [comment]
用线上版测试才会出现这个问题！！本地调试没有问题。

**Comment by lvjie0519** [comment]
@mirse  请加微信，微信号：18750118631， 详聊下吧。
