### ISSUE TITLE
Android解析问题

### ISSUE THREAD

**Issue by balddonkey** [MiEcosystem/miot-plugin-sdk#947]
是否新品：新品

model: opple.light.cablelamp

无项目ID

欧普

macOS Mojave 10.14.3
Android6.1
SDK: master 10005
整体现象

现象：
使用Device.getDeviceWifi().callMethod(...) 会返回以下错误，是callMethod的promise直接进入的catch里面，自己未做处理，仅在Android出现。
![image](https://user-images.githubusercontent.com/7577854/59175098-d364fc00-8b86-11e9-8766-0f76d0d03302.png)

期望：
可以正常解析返回数据

**Comment by balddonkey** [comment]
附加：

**Comment by balddonkey** [comment]
附加：
此种返回值会失败
![image](https://user-images.githubusercontent.com/7577854/59175452-31461380-8b88-11e9-8adc-c5587d2bfea2.png)
此种返回值会成功
![image](https://user-images.githubusercontent.com/7577854/59175477-458a1080-8b88-11e9-9b85-9fe19b090167.png)

**Comment by zanetti4** [comment]
你可以把设备分享给我，并写出 callMethod 方法的具体使用代码，我进行测试。

**Comment by zanetti4** [comment]
我的米家 id: 894158105

**Comment by balddonkey** [comment]
> 我的米家 id: 894158105

已共享，调用方法 Device.getDeviceWifi().callMethod('SyncBaseInfo').then...
即可

**Comment by lvjie0519** [comment]
callMethod至少需要两个参数，如果没有第二个参数，尝试如下：
Device.getDeviceWifi().callMethod("SyncBaseInfo",{}).then

**Comment by balddonkey** [comment]
> callMethod至少需要两个参数，如果没有第二个参数，尝试如下：
> Device.getDeviceWifi().callMethod("SyncBaseInfo",{}).then

多谢，确实是Android不传第二个参数就会报错～
