### ISSUE TITLE
灯组管理显示异常

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#948]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**

灯组管理    
 iOS：列表显示为空     
Android：灯组管理成功后，直接创建了一个新的灯组，当前灯组的设备还是原来创建时的设备

![image](https://user-images.githubusercontent.com/5188922/59180911-ac172a80-8b98-11e9-90fb-806e6ec0756e.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
请提供相关模块的使用代码，如有必要请把设备分享给我，进行测试。我的米家 id: 894158105

**Comment by Aub1nLin** [comment]
> 请提供相关模块的使用代码，如有必要请把设备分享给我，进行测试。我的米家 id: 894158105

halo，设备组不支持共享吧？

**Comment by santcool** [comment]
那麻烦给一个包含灯组的测试账号给我们使用下，不然问题不太好定位哈。邮箱：zhangwenfeng@xiaomi.com

**Comment by mirse** [comment]
> 那麻烦给一个包含灯组的测试账号给我们使用下，不然问题不太好定位哈。邮箱：[zhangwenfeng@xiaomi.com](mailto:zhangwenfeng@xiaomi.com)

已发送

**Comment by Aub1nLin** [comment]
> 那麻烦给一个包含灯组的测试账号给我们使用下，不然问题不太好定位哈。邮箱：[zhangwenfeng@xiaomi.com](mailto:zhangwenfeng@xiaomi.com)

还有一个就，在调用 Host.ui.openAddDeviceGroupPage(); 这个方法的时候，Android会弹出Toast【米家：无可编辑分组设备】，而iOS是没问题的。

**Comment by lvjie0519** [comment]
@mirse   @Aub1nLin   Android问题，请更新 sdk到10020分支或使用master分支，openAddDeviceGroupPage()需要你们传递groupModel，具体groupModel为何值，请参考你们之前的原生插件的实现。

**Comment by santcool** [comment]
@mirse  灯组管理提供了两个方法：打开创建设备组页（openAddDeviceGroupPage） 和 打开编辑设备组页面（openEditDeviceGroupPage），在灯组插件里面，应该使用后面这个方法

**Comment by mirse** [comment]
@lvjie0519  @santcool  
使用Host.ui.openAddDeviceGroupPage('philips.light.virtual')方法，还是不行

**Comment by zanetti4** [comment]
不是需要使用后面那个方法吗？打开编辑设备组页面（openEditDeviceGroupPage）

**Comment by santcool** [comment]
在某个设备页创建灯组使用openAddDeviceGroupPage这个方法，而在灯组页编辑灯组，应该使用openEditDeviceGroupPage方法

**Comment by Aub1nLin** [comment]
> 在某个设备页创建灯组使用openAddDeviceGroupPage这个方法，而在灯组页编辑灯组，应该使用openEditDeviceGroupPage方法

我重新描述一下：
1、我的设备插件有一个需求是创建灯组，然后我调用Host.ui.openAddDeviceGroupPage('philips.light.virtual')方法，Android显示【米家无可编辑的分组】，iOS是可以的！

2、我的灯组插件有一个需求是灯组管理，然后我调用 Host.ui.openEditDeviceGroupPage(dids) 这个接口，我将dids（当前灯组中，灯ID的数组）传入，但是在进入页面编辑灯组这个页面的时候，Android不会选中我传入数组中的设备，而且标题显示为【创建设备分组】，iOS标题为添加（null）。

另外，这个问题我已经提过了，你们把它关闭了。
https://github.com/MiEcosystem/miot-plugin-sdk/issues/378

**Comment by santcool** [comment]
灯组这一块问题很多，我们正在努力修复中，估计最少得到下周才能给出修复之后的包，各位耐心等待

**Comment by santcool** [comment]
修复此处的代码已更新到SDK_10020，同时增加了Demo。各位下午4点左右可以去尝试（注意看Demo及其文档）。

**Comment by Aub1nLin** [comment]
> 修复此处的代码已更新到SDK_10020，同时增加了Demo。各位下午4点左右可以去尝试（注意看Demo及其文档）。

hi，
我们试了最新的DEMO，并更新到10021，调用创建灯组接口（如下图1）
iOS的创建灯组，进去页面后为空（如下图2）
Android的创建灯组弹出toast显示不可用（如下图3）
![image](https://user-images.githubusercontent.com/45021910/59573135-01e15a80-90e4-11e9-9cb5-d8c5a5faddd8.png)
![image](https://user-images.githubusercontent.com/45021910/59573434-82548b00-90e5-11e9-925a-26061fd23b8c.png)

![image](https://user-images.githubusercontent.com/45021910/59573440-8b455c80-90e5-11e9-8492-0124c7e47d5f.png)

**Comment by Aub1nLin** [comment]
> 修复此处的代码已更新到SDK_10020，同时增加了Demo。各位下午4点左右可以去尝试（注意看Demo及其文档）。

另外，编辑灯组，我调用了 Host.ui.openDeviceGroupPageForEdit(Device.deviceID)（下图1），在Android上可用，没问题了，但是在iOS下仍然不可用会显示网络错误，并且下方的按钮是检查固件更新？？？（下图2）
![image](https://user-images.githubusercontent.com/45021910/59573459-aa43ee80-90e5-11e9-9211-9e41074cbe53.png)
![image](https://user-images.githubusercontent.com/45021910/59573502-d8293300-90e5-11e9-8860-ad304f73f39b.png)

**Comment by lvjie0519** [comment]
@mirse   Android请使用最新apk进行测试。
