### ISSUE TITLE
位置管理显示异常

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#949]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**

位置管理     
iOS：房间显示（null）\|（null）    （如图）
Android：修改灯组所在房间显示成功，返回米家主界面再进灯组插件，实际移动房间失败

![image](https://user-images.githubusercontent.com/5188922/59181192-5a22d480-8b99-11e9-9322-3c9a537dd7fe.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
创建灯组的时候，不让选地址，因为灯组不应该属于哪一个房间，此菜单项应该隐藏掉。

**Comment by Aub1nLin** [comment]
> 创建灯组的时候，不让选地址，因为灯组不应该属于哪一个房间，此菜单项应该隐藏掉。

创建灯组的时候就没有选择房间一项，另外，该菜单项在通用设置说明文档里面是必选项。

**Comment by Aub1nLin** [comment]
@santcool   创建灯组的时候就没有选择房间一项，另外，该菜单项在通用设置说明文档里面是必选项。
