### ISSUE TITLE
灯组法律信息

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#950]
**是否为新品（必填）**
 在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**

Android，法律信息里的用户协议和隐私政策点击没有反应

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by lvjie0519** [comment]
@mirse 
请给出截图并同时给出对应的关键代码，方便我这边排查，谢谢。

**Comment by mirse** [comment]
由于CommonSetting里的法律信息是默认存在的，但是灯组是不存在用户协议和隐私政策的，所以没放对应的html文件，导致点击没反应，法律信息有办法隐藏吗？ @lvjie0519

**Comment by santcool** [comment]
这个问题，我们产品在介入中，下周内应该会给出一个方案，请稍等。

**Comment by LiuMengzhou** [comment]
该问题`SDK_10021`上已经修复。
1. 灯组不再显示法律信息。
2. 安全设置，也可以通过传参数屏蔽掉。参考[demo Setting](https://github.com/MiEcosystem/miot-plugin-sdk/blob/SDK_10021/projects/com.xiaomi.demo/Main/tutorial/Setting.js#L57)
```js
const extraOptions = {
      showUpgrade: true,
      // upgradePageKey: 'FirmwareUpgrade',
      // licenseUrl: require('../resources/html/license_zh.html'),
      // policyUrl: require('../resources/html/privacy_zh.html'),
      deleteDeviceMessage: '真的要删除？你不再考虑考虑？',
      excludeRequiredOptions: [secondAllOptions.SECURITY]
    }
```
