### ISSUE TITLE
灯组更多设置点击无反应

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#951]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**
更多设置点击无响应。

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
请查看CommonSetting的文档：
 * **注意：**
 **  如果需要显示「更多设置」「固件升级」的二级菜单页面，需要从 miot/ui/CommonSetting 中导出 MoreSetting 和 FirmwareUpgrade 页面，并放在项目入口文件index.js的RootStack中。**
