### ISSUE TITLE
创建灯组成功/失败 现象

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#952]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulbs

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**
iOS，单灯插件里创建灯组成功后，直接跳转到米家APP首页。
Android，单灯插件里创建灯组失败，提示无可编辑分组设备

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
我看iOS的逻辑是，创建成功后，先返回APP首页，再进入插件页面，看样子是没问题的。如果想直接打开插件，可以参照Demo，如下图：
![7781560325747_ pic_hd](https://user-images.githubusercontent.com/8580061/59332824-b583cc80-8d29-11e9-8de0-376846279a50.jpg)
Android需要等Android那边的同事查看。

**Comment by lvjie0519** [comment]
@mirse  
1、Android，单灯插件里创建灯组失败，提示无可编辑分组设备
 请提供一下使用的是哪个api及对应的参数，谢谢

**Comment by Aub1nLin** [comment]
> @mirse
> 1、Android，单灯插件里创建灯组失败，提示无可编辑分组设备
> 请提供一下使用的是哪个api及对应的参数，谢谢
使用这个Api：      Host.ui.openDeviceGroupPageForCreate(Device.deviceID);

**Comment by lvjie0519** [comment]
@mirse   sdk请更新到10021分支，同时请使用最新apk，openDeviceGroupPageForCreate这个api废弃了， 请使用openAddDeviceGroupPage或openMeshDeviceGroupPage，Android和ios使用相同的api即可。

**Comment by Aub1nLin** [comment]
> @mirse sdk请更新到10021分支，同时请使用最新apk，openDeviceGroupPageForCreate这个api废弃了， 请使用openAddDeviceGroupPage或openMeshDeviceGroupPage，Android和ios使用相同的api即可。

用这个API可以了，感谢。
但是现在暴露一个新的问题，在iOS下，点击调用的时候，创建灯组这一页是从下往上的，这个时候，我的导航栏会显示设备页的导航栏，如下图。
在Android下是没问题的，因为是左右导航，且两个平台的样式也不同，建议改成Android的？

![image](https://user-images.githubusercontent.com/45021910/59740043-7c9fa680-9299-11e9-8572-980f89be624f.png)

**Comment by lvjie0519** [comment]
@santcool  看看这个问题？

**Comment by santcool** [comment]
从下往上是没问题的。这是正常的iOS系统自带的转场动画

**Comment by Aub1nLin** [comment]
> 从下往上是没问题的。这是正常的iOS系统自带的转场动画

转场动画是没问题，问题出现在为啥转场的时候，会出现设备控制页的导航栏标题？不应该只有设置页的导航栏标题嘛？这样会有重叠的阴影效果。你看一下上面的图，有两个返回按钮图标。
