### ISSUE TITLE
设备时区显示问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#953]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulb

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**
在通用设置-->更多设置中，任意选择设备时区，退出插件后再次进入插件，点击通用设置查看设备时区信息不显示了

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
@mirse 
手机系统:[Android 8.1/iOS 11.0] --- 你的意思是这个问题在android和ios上同时存在？

**Comment by Woody2016** [comment]
请问你用的是CommonSetting组件吗？

**Comment by mirse** [comment]
> 请问你用的是CommonSetting组件吗？

是用的CommonSetting，ios上没问题，只有android有问题。

**Comment by lvjie0519** [comment]
@mirse   发现问题了，正在修复，修复及时更新消息，谢谢。

**Comment by lvjie0519** [comment]
@mirse  已修复，请使用最新apk， sdk选择10021分支，谢谢。
