### ISSUE TITLE
进入插件首页界面下移

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#954]
**是否为新品（必填）**
 在售

**关联的产品model**
philips.light.bulb

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
手机一进入插件主界面会下移，进入通用设置再返回就会显示正常（不是100%复现，第一次进入出现的概率较高）
![image](https://user-images.githubusercontent.com/5188922/59182235-c999c380-8b9b-11e9-9b58-b00e22fab98d.png)
![image](https://user-images.githubusercontent.com/5188922/59182245-cdc5e100-8b9b-11e9-8eed-244b5480b6bc.png)

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@santcool @lvjie0519 这看起来是顶部的状态栏没有显示，并不是整个页面下移了，请进行查看。

**Comment by santcool** [comment]
我这边使用iPhone 8/iOS11.0.1来测试，并没有复现。请尝试换个手机，或者发一个小视频来看看

**Comment by santcool** [comment]
这个问题梦舟看一下吧。

**Comment by mirse** [comment]
同样是刚进入界面时的显示，状态栏还是米家首页的状态栏
![image](https://user-images.githubusercontent.com/5188922/59246367-b7c52880-8c4e-11e9-81c2-4567e8bda811.png)

**Comment by LiuMengzhou** [comment]
应该就是状态栏没有正常设置。
可以参考这两个开发者的解决办法。
https://github.com/MiEcosystem/miot-plugin-sdk/issues/976#issuecomment-501983504
https://github.com/MiEcosystem/miot-plugin-sdk/issues/739#issuecomment-502642544

**Comment by LiuMengzhou** [comment]
#976 
#739

**Comment by mirse** [comment]
> #976
> #739

问题不一致，现在会出现再三星S7和Mix2两台手机中。
你看一下如下图片，整个状态栏的颜色变白，且我的导航栏（是用demo中的TitleBar）是被往下挤压得，挤压高度就是StatusBar的高度。

![image](https://user-images.githubusercontent.com/5188922/59668471-25db9380-91eb-11e9-90c8-5b1ca34acbd4.png)

**Comment by mirse** [comment]
> #976
> #739

但是，当我点击右边的更多按钮，进入到设置页后，再回到这一页，他就恢复了。
对了，这种情况的出现几率比较大，但不是百分百复现，只有将插件放到小米云再load到手机中才会出现，直接从电脑debug进手机不会出现。

**Comment by LiuMengzhou** [comment]
你分享设备给 `894158105`，我们这边复现看看。
@lvjie0519 帮忙看看吧。我觉得有可能是Native端的问题：在进入插件页面的时候，原生的导航栏没有正确隐藏？个人猜测。

**Comment by lvjie0519** [comment]
@mirse  
1、只有三星S7和Mix2两台手机会出现问题吗？
2、设备分享给894158105，说下设备名称；

**Comment by lvjie0519** [comment]
总结： 状态栏下移，是因为StatusBar.setTranslucent(true); 在render函数中执行，同时APP端也进行了修复，验证问题已解决。
