### ISSUE TITLE
IOS右滑返回问题

### ISSUE THREAD

**Issue by mirse** [MiEcosystem/miot-plugin-sdk#955]
**是否为新品（必填）**
在售

**关联的产品model**
philips.light.bulb

**企业名称（必填）**
Philips

**环境（必填）**
- 电脑操作系统:[Windows/Mac OS]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**

iOS右滑     
1.创建灯组不能右滑返回     
2.设备共享的共享管理，只要有右滑的动作，立马返回到上一层     
3.使用帮助内容页右滑返回的是设置页而不是使用帮助页

**期望（必填）**
简单明了地描述一下期望的表现。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
1.这个页面本来就不允许优化返回，就如同你微信打开相册一样
2.一个遗留的bug，问题不大，我们需要考虑，是否需要修改。
3.已修改，SDK10021上
