### ISSUE TITLE
Android上CommonSetting和iOS上显示的设置项不太一致

### ISSUE THREAD

**Issue by zhuxinleibandou** [MiEcosystem/miot-plugin-sdk#956]
**注意事项：（阅读后，创建issue时此段可删除）**

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**  新品 
填 新品 or 在售

**关联的产品model**  msj.f_washer.m1
此issue关联的产品model，如“xiaomi.demo.v1”

**项目ID（必填）** pid: 1364
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
美高厨具

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]  Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]  Android 8.1
- SDK分支: [eg.master/10000/...]  10004
- 相关模块:[eg.Host/Service/Account]  miot/ui/CommonSetting

**现象（必填）**
android和iOS 在通用设置上显示不一致，截图运行的是小米demo，使用的是虚拟设备。

**期望（必填）**
希望Android和iOS显示上表现一致

**其他的上下文/日志/截图**
![201906161181845](https://user-images.githubusercontent.com/18374383/59189269-3d43cc80-8bac-11e9-858d-3d5802c53668.jpg)

**尝试过的解决办法**
尝试过哪些操作？copy代码到自己项目，也是显示这样。6.5号节前，Android还是可以和iOS显示一样多的设置。

**不要贴大段代码❗️**

**Comment by zhuxinleibandou** [comment]
麻烦看一下，谢谢！

**Comment by zanetti4** [comment]
经过我的测试，安卓和苹果手机都能显示9项。请把使用 CommonSetting 组件的具体代码贴上来，我再看看。

**Comment by zhuxinleibandou** [comment]
> 经过我的测试，安卓和苹果手机都能显示9项。请把使用 CommonSetting 组件的具体代码贴上来，我再看看。

好的，我就是从git上拉下来的代码 未改动，10005.我将代码提出来，请稍等

**Comment by zhuxinleibandou** [comment]
#

**Comment by zhuxinleibandou** [comment]
好的

> 经过我的测试，安卓和苹果手机都能显示9项。请把使用 CommonSetting 组件的具体代码贴上来，我再看看。

好的，我就是从git上拉下来的代码，10005，运行的xiaomi.demo.v1，虚拟设备运行的，请稍等，我将代码贴出来

**Comment by zhuxinleibandou** [comment]
const firstOptions = {
  /**
   * 按键设置，多键开关`必选`，其余设备`必不选`
   */
  MEMBER_SET: 'memberSet',
  /**
   * 设备共享, `可选`
   */
  SHARE: 'share',
  /**
   * 蓝牙网关, `可选`
   */
  BTGATEWAY: 'btGateway',
  /**
   * 语音授权, `可选`
   */
  VOICE_AUTH: 'voiceAuth',
  /**
   * 智能场景, `可选`
   */
  IFTTT: 'ifttt',
  /**
   * 固件升级，`可选`
   */
  FIRMWARE_UPGRADE: 'firmwareUpgrade',
};
const firstAllOptions = {
  ...firstOptions,
  /**
   * 设备名称，`必选`
   */
  NAME: 'name',
  /**
   * 位置管理，`必选`
   */
  LOCATION: 'location',
  /**
   * 使用帮助，`必选`
   */
  HELP: 'help',
  /**
   * 更多设置，`必选`
   */
  MORE: 'more',
  /**
   * 法律信息，`必选`
   */
  LEGAL_INFO: 'legalInfo'
};
/**
 * 分享设备的设置项
 * 0: 不显示
 * 1: 显示
 */
const firstSharedOptions = {
  [firstAllOptions.NAME]: 0,
  [firstAllOptions.MEMBER_SET]: 0,
  [firstAllOptions.LOCATION]: 0,
  [firstAllOptions.SHARE]: 0,
  [firstAllOptions.BTGATEWAY]: 0,
  [firstAllOptions.VOICE_AUTH]: 0,
  [firstAllOptions.IFTTT]: 0,
  [firstAllOptions.FIRMWARE_UPGRADE]: 0,
  [firstAllOptions.MORE]: 1,
  [firstAllOptions.HELP]: 1,
  [firstAllOptions.LEGAL_INFO]: 1,
};
const secondOptions = {
  /**
   * 固件升级——固件自动升级, `可选`
   */
  AUTO_UPGRADE: 'autoUpgrade',
  /**
   * 更多设置——设备时区, `可选`
   */
  TIMEZONE: 'timezone',
  /**
   * 法律信息——加入用户体验计划, `可选`
   */
  USER_EXPERIENCE_PROGRAM: 'userExperienceProgram'
};
const secondAllOptions = {
  ...secondOptions,
  /**
   * 固件升级——检查固件更新，`必选`
   */
  CHECK_UPGRADE: 'checkUpgrade',
  /**
   * 更多设置——安全设置，`必选`
   */
  SECURITY: 'security',
  /**
   * 更多设置——反馈问题，`必选`
   */
  FEEDBACK: 'feedback',
  /**
   * 更多设置——添加桌面快捷方式，`必选`
   */
  ADD_TO_DESKTOP: 'addToDesktop',
  /**
   * 法律信息——用户协议，`必选`
   */
  USER_AGREEMENT: 'userAgreement',
  /**
   * 法律信息——隐私政策，`必选`
   */
  PRIVACY_POLICY: 'privacyPolicy'
};
export const SETTING_KEYS = {
  // 一级菜单
  first_options: firstOptions,
  // 二级菜单
  second_options: secondOptions
};
export { firstAllOptions, secondAllOptions };
/**
 * @export public
 * @doc_name CommonSetting
 * @doc_index 23
 * @author Geeook
 * @since 10004
 * @module CommonSetting
 * @description 米家通用设置项
 * @property {array} firstOptions - 一级菜单列表项的keys，keys的顺序代表显示的顺序，不传将显示全部，传空数组将显示必选项
 * @property {array} secondOptions - 二级菜单列表项的keys，keys的顺序代表显示的顺序，不传将显示全部，传空数组将显示必选项
 * @property {object} extraOptions - 其他特殊配置项
 * ```js
 * // extraOptions
 * extraOptions: {
 *   showUpgrade: bool // 「固件升级」是否显示二级菜单。默认值true。一般来说，wifi设备显示二级菜单，蓝牙设备不显示二级菜单
 *   upgradePageKey: string // 「固件升级」如果不显示二级菜单，请传入想跳转页面的key(定义在 index.js 的 RootStack 中)
 *   licenseUrl: 资源id, // 见 miot/Host.ui.privacyAndProtocolReview 的传参说明
 *   policyUrl: 资源id, // 见 miot/Host.ui.privacyAndProtocolReview 的传参说明
 *   deleteDeviceMessage: string // 删除设备的弹窗中自定义提示文案，见 miot/Host.ui.openDeleteDevice 的传参说明
 * }
 * ```
 * @property {object} navigation - 必须传入当前插件的路由，即 `this.props.navigation`，否则无法跳转二级页面
 * **注意：**
 * **1. 如果需要显示「更多设置」「固件升级」的二级菜单页面，需要从 miot/ui/CommonSetting 中导出 MoreSetting 和 FirmwareUpgrade 页面，**
 *    **并放在项目入口文件index.js的RootStack中。**
 * ```js
 * // index.js snippet
 * import { FirmwareUpgrade, MoreSetting } from "miot/ui/CommonSetting";
 * ...
 * const RootStack = createStackNavigator(
 * {
 *     Setting, // 设置页
 *     MoreSetting, // 二级菜单——更多设置
 *     FirmwareUpgrade, // 二级菜单——固件升级
 * }
 * ...
 * )
 * ```
 * **2. 必须传入当前插件的路由，即 `this.props.navigation`，否则无法跳转二级页面**
 * ```js
 * <CommonSetting
 *   navigation={this.props.navigation}
 * />
 * ```
 * @see com.xiaomi.demo->教程->插件通用设置项
 */
export default class CommonSetting extends React.Component {
  static propTypes = {
    firstOptions: PropTypes.array,
    secondOptions: PropTypes.array,
    extraOptions: PropTypes.object,
    navigation: PropTypes.object.isRequired
  }
  static defaultProps = {
    firstOptions: [
      firstAllOptions.MEMBER_SET,
      firstAllOptions.SHARE,
      firstAllOptions.BTGATEWAY,
      firstAllOptions.VOICE_AUTH,
      firstAllOptions.IFTTT,
      firstAllOptions.FIRMWARE_UPGRADE
    ],
    secondOptions: [
      secondAllOptions.AUTO_UPGRADE,
      secondAllOptions.TIMEZONE,
      secondAllOptions.USER_EXPERIENCE_PROGRAM
    ]
  }
  getCommonSetting(state) {
    return {
      [firstAllOptions.NAME]: {
        title: strings.name,
        value: state.name,
        onPress: _ => Host.ui.openChangeDeviceName()
      },
      [firstAllOptions.LOCATION]: {
        title: strings.location,
        onPress: _ => Host.ui.openRoomManagementPage()
      },
      [firstAllOptions.MEMBER_SET]: {
        title: strings.memberSet,
        onPress: _ => console.warn('unavailable temporarily')
      },
      [firstAllOptions.SHARE]: {
        title: strings.share,
        onPress: _ => Host.ui.openShareDevicePage()
      },
      [firstAllOptions.BTGATEWAY]: {
        title: strings.btGateway,
        onPress: _ => Host.ui.openBtGatewayPage()
      },
      [firstAllOptions.VOICE_AUTH]: {
        title: strings.voiceAuth,
        onPress: _ => Host.ui.openVoiceCtrlDeviceAuthPage()
      },
      [firstAllOptions.IFTTT]: {
        title: strings.ifttt,
        onPress: _ => Host.ui.openIftttAutoPage()
      },
      [firstAllOptions.HELP]: {
        title: strings.help,
        onPress: _ => Host.ui.openHelpPage()
      },
      [firstAllOptions.FIRMWARE_UPGRADE]: {
        title: strings.firmwareUpgrade,
        onPress: _ => this.chooseFirmwareUpgrade()
      },
      [firstAllOptions.MORE]: {
        title: strings.more,
        onPress: _ => this.openSubPage('MoreSetting')
      },
      [firstAllOptions.LEGAL_INFO]: {
        title: strings.legalInfo,
        onPress: _ => this.privacyAndProtocolReview()
      }
    };
  }
  constructor(props, context) {
    super(props, context);
    this.state = { name: Device.name };
    this.commonSetting = this.getCommonSetting(this.state);
  }
  /**
   * @description 点击「法律信息」，传入用户协议和隐私政策的文件地址
   */
  privacyAndProtocolReview() {
    const { licenseUrl, policyUrl } = this.props.extraOptions || {};
    Host.ui.privacyAndProtocolReview('', licenseUrl, '', policyUrl);
  }
  /**
   * @description 点击「固件升级」，选择性跳转
   */
  chooseFirmwareUpgrade() {
    // 默认是wifi设备固件升级的二级页面
    const { showUpgrade, upgradePageKey } = this.props.extraOptions || {};
    if (showUpgrade === false) {
      // 蓝牙统一OTA界面
      if (upgradePageKey === undefined) {
        console.warn('请在 extraOptions.upgradePageKey 中填写你想跳转的固件升级页面, 传给 CommonSetting 组件');
        return;
      }
      if (typeof upgradePageKey !== 'string') {
        console.warn('upgradePageKey 必须是字符串, 是你在 index.js 的 RootStack 中定义的页面 key');
        return;
      }
      this.openSubPage(upgradePageKey, {}); // 跳转到开发者指定页面
      console.warn('蓝牙统一OTA界面正在火热开发中');
    }
    else {
      // wifi设备固件升级
      this.openSubPage('FirmwareUpgrade');
    }
  }
  /**
   * @description 打开二级菜单
   * @param {string} page index.js的RootStack中页面定义的key
   */
  openSubPage(page, params = { secondOptions: this.props.secondOptions }) {
    if (this.props.navigation) {
      this.props.navigation.navigate(page, params);
    }
    else {
      console.warn("props 'navigation' is required for CommonSetting");
    }
  }
  /**
   * @description 弹出「删除设备」弹窗
   */
  openDeleteDevice() {
    const { deleteDeviceMessage } = this.props.extraOptions || {};
    Host.ui.openDeleteDevice(deleteDeviceMessage);
  }
  render() {
    const requireKeys1 = [firstAllOptions.NAME, firstAllOptions.LOCATION];
    const requireKeys2 = [
      firstAllOptions.MORE,
      firstAllOptions.HELP,
      firstAllOptions.LEGAL_INFO
    ];
    let options = this.props.firstOptions.filter(key => key && Object.values(firstOptions).includes(key)); // 去掉杂质
    options = [...new Set(options)]; // 去除重复
    let keys = [...requireKeys1, ...options, ...requireKeys2]; // 拼接必选项和可选项
    if (Device.isOwner === false) {
      keys = keys.filter(key => firstSharedOptions[key]); // 如果是共享设备或者家庭设备，需要过滤一下
    }
    const items = keys.map(key => this.commonSetting[key]).filter(item => item); // 防空
    return (
      <View style={styles.container}>
        <View style={styles.titleContainer}>
          <Text style={styles.title}>{strings.commonSetting}</Text>
        </View>
        <Separator style={{ marginLeft: Styles.common.padding }} />
        {
          items.map((item, index) => {
            const showSeparator = index !== items.length - 1;
            return (
              <ListItem
                key={item.title}
                title={item.title || ''}
                value={item.value}
                onPress={item.onPress}
                showSeparator={showSeparator}
              />
            );
          })
        }
        <Separator />
        <View style={styles.bottomContainer}>
          <RkButton
            style={styles.buttonContainer}
            contentStyle={styles.buttonText}
            onPress={_ => this.openDeleteDevice()}
            activeOpacity={0.8}
          >
            {strings.deleteDevice}
          </RkButton>
        </View>
      </View>
    );
  }
  componentWillMount() {
    this._deviceNameChangedListener = DeviceEvent.deviceNameChanged.addListener(device => {
      this.state.name = device.name;
      this.commonSetting = this.getCommonSetting(this.state);
      this.forceUpdate();
    });
  }
  componentWillUnmount() {
    this._deviceNameChangedListener.remove();
  }
}

**Comment by zhuxinleibandou** [comment]
> 经过我的测试，安卓和苹果手机都能显示9项。请把使用 CommonSetting 组件的具体代码贴上来，我再看看。

不好意思，贴了大段代码，我从10010、10011、10012版本都运行了一下，android手机上还是只有两三个，都是运行的demo，是不是哪里运行错了呢   百思不得骑姐

**Comment by zhuxinleibandou** [comment]
10004版本通用设置，Android和iOS是8个，从10005开始，10010、10011、10012Android就不是八个了，就显示上图的三个，iOS还是8个 - - 好奇怪 我也不知道哪里的问题，崩溃中老哥～

**Comment by zhuxinleibandou** [comment]
我拿文件对比工具进行对比，10004版本的和10005版本的CommonSetting组件，代码都是一摸一样的

**Comment by zhuxinleibandou** [comment]
代码贴错了，贴一下com.xiaomi.demo的使用


'use strict';

import { strings, Styles } from 'miot/resources';
import { CommonSetting, SETTING_KEYS } from "miot/ui/CommonSetting";
import { ListItem, ListItemWithSlider, ListItemWithSwitch } from 'miot/ui/ListItem';
import Separator from 'miot/ui/Separator';
import TitleBar from 'miot/ui/TitleBar';
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

export default class Setting extends React.Component {

  static navigationOptions = ({ navigation }) => {
    return {
      header:
        <TitleBar
          type='dark'
          title={strings.setting}
          style={{ backgroundColor: '#fff' }}
          onPressLeft={_ => navigation.goBack()}
        />
    };
  };

  constructor(props, context) {
    super(props, context);
  }

  render() {
    const { first_options, second_options } = SETTING_KEYS;
    // 显示部分一级菜单项
    const firstOptions = [
      first_options.SHARE,
      first_options.IFTTT,
      first_options.VOICE_AUTH,
    ]
    // 显示部分二级菜单项
    const secondOptions = [
      second_options.AUTO_UPGRADE,
      second_options.TIMEZONE,
    ]
    // 显示固件升级二级菜单
    const extraOptions = {
      showUpgrade: true,
      // licenseUrl: require('../resources/html/license_zh.html'),
      // policyUrl: require('../resources/html/privacy_zh.html'),
      deleteDeviceMessage: '真的要删除？你不再考虑考虑？'
    }
    return (
      <View style={styles.container}>
        <Separator />
        <ScrollView
          showsVerticalScrollIndicator={false}>
          <View style={[styles.blank, { borderTopWidth: 0 }]} />
          <View style={styles.featureSetting}>
            <View style={styles.titleContainer}>
              <Text style={styles.title}>{strings.featureSetting}</Text>
            </View>
            <Separator style={{ marginLeft: Styles.common.padding }} />
            <ListItem
              title='这是'
              onPress={_ => console.log(0)}
            />
            <ListItemWithSwitch
              title='三个'
              onValueChange={value => console.log(value)}
            />
            <ListItemWithSlider
              title='测试'
              onSlidingComplete={value => console.log(value)}
              showSeparator={false}
            />
          </View>
          <View style={styles.blank} />
          <CommonSetting
            navigation={this.props.navigation}
            firstOptions={firstOptions}
            secondOptions={secondOptions}
            extraOptions={extraOptions}
          />
          <View style={{ height: 20 }} />
        </ScrollView>
      </View>
    );
  }

  componentDidMount() {
    // TODO: 拉取功能设置项里面的初始值，比如开关状态，slider的value
  }
}

var styles = StyleSheet.create({
  container: {
    backgroundColor: Styles.common.backgroundColor,
    flex: 1,
  },
  featureSetting: {
    backgroundColor: '#fff',
  },
  blank: {
    height: 8,
    backgroundColor: Styles.common.backgroundColor,
    borderTopColor: Styles.common.hairlineColor,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Styles.common.hairlineColor,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  titleContainer: {
    height: 32,
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingLeft: Styles.common.padding,
  },
  title: {
    fontSize: 11,
    color: 'rgba(0,0,0,0.5)',
    lineHeight: 14,
  }
});

**Comment by LiuMengzhou** [comment]
@zhuxinleibandou 
应该是分享设备的原因。
1. `SDK_10004`版本没有做分享权限控制，`>=10005` 之后的版本在分享设备上只显示那三项。
2. 虚拟设备在安卓上应该被当成了共享设备

所以你用真实的设备再试试吧

**Comment by LiuMengzhou** [comment]
> @zhuxinleibandou
> 应该是分享设备的原因。
> 
> 1. `SDK_10004`版本没有做分享权限控制，`>=10005` 之后的版本在分享设备上只显示那三项。
> 2. 虚拟设备在安卓上应该被当成了共享设备
> 
> 所以你用真实的设备再试试吧

和平台没关系。
附上[文档链接](https://github.com/MiEcosystem/miot-plugin-sdk/blob/ui_doc/%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8UI%E7%BB%84%E4%BB%B6%E6%89%8B%E5%86%8C.md#%E7%B1%B3%E5%AE%B6%E6%8F%92%E4%BB%B6%E9%80%9A%E7%94%A8%E8%AE%BE%E7%BD%AEcommonsetting)

**Comment by zhuxinleibandou** [comment]
> @zhuxinleibandou
> 应该是分享设备的原因。
> 
> 1. `SDK_10004`版本没有做分享权限控制，`>=10005` 之后的版本在分享设备上只显示那三项。
> 2. 虚拟设备在安卓上应该被当成了共享设备
> 
> 所以你用真实的设备再试试吧

哦 明白了 那我没问题了，我以为是我这里使用不当才显示成这样的呢，谢谢了！
