### ISSUE TITLE
callMethod返回-7未知id错误原因有哪些

### ISSUE THREAD

**Issue by hj0407** [MiEcosystem/miot-plugin-sdk#957]
Device.getDeviceWifi().callMethod('get_props', ['status','wash','subwash','grade','level','lefttime','runstop'MHLocalizableString.js])
  .then(res => {console.log('success:', res),alert(res)}
   
  )
  .catch(err => {console.error('failed:', err),alert(res)})
}

**Comment by zanetti4** [comment]
请按照模版填写相应信息，谢谢

**Comment by zanetti4** [comment]
['status','wash','subwash','grade','level','lefttime','runstop'MHLocalizableString.js]
数组最后一项是不是写错了？
