### ISSUE TITLE
batchSetDeviceDatas(params)和batchGetDeviceDatas(params)无法使用

### ISSUE THREAD

**Issue by chenhaoge** [MiEcosystem/miot-plugin-sdk#958]
---
**是否为新品（必填）**
否

**关联的产品model**
此issue关联的产品model，“xiaomi.demo.v1”

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
贵司的名称

**环境（必填）**
- 电脑操作系统:[eg.Windows]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10012/...]
- 相关模块:[eg.Service/smarthome/batchSetDeviceDatas]
- 相关模块:[eg.Service/smarthome/batchGetDeviceDatas]

**现象（必填）**
使用batchSetDeviceDatas(params)和batchGetDeviceDatas(params)都显示TypeError:undefined is not a function。

**期望（必填）**
可以正常使用这两个方法。

**其他的上下文/日志/截图**
Service.smarthome.batchSetDeviceDatas([{
            'did': Device.deviceID, 'props': {
                "prop.s_license_privacy": "0"
            }
        }]).then((value => {
            
        }))

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
1. 请按模板要求补充好issue内容

2. prop.s_license_privacy ---- 这是什么属性？

**Comment by chenhaoge** [comment]
> 1. 请按模板要求补充好issue内容
> 2. prop.s_license_privacy ---- 这是什么属性？

prop.s_license_privacy这个属性是需要在后台配置的吗，还是可以在插件里自定义

**Comment by chenhaoge** [comment]
> 1. 请按模板要求补充好issue内容
> 2. prop.s_license_privacy ---- 这是什么属性？

**Comment by blockdate** [comment]
prop是自定义的，建议检查下SDK版本以及是否正确的更新下来了。

**Comment by chenhaoge** [comment]
> prop是自定义的，建议检查下SDK版本以及是否正确的更新下来了。

![image](https://user-images.githubusercontent.com/37482096/59237915-8ccadc80-8c2e-11e9-8028-8d3da286509a.png)
![image](https://user-images.githubusercontent.com/37482096/59237939-a835e780-8c2e-11e9-90aa-a5113471b09f.png)
现在我调用的这个方法，我点进去就跳到sdk里面了

**Comment by chenhaoge** [comment]
![image](https://user-images.githubusercontent.com/37482096/59237993-d6b3c280-8c2e-11e9-84ea-07a2878ee3a2.png)

**Comment by chenhaoge** [comment]
![image](https://user-images.githubusercontent.com/37482096/59238012-e8956580-8c2e-11e9-9186-4e328f873cfb.png)

**Comment by blockdate** [comment]
这个一般是你的SDK没有完整的从github上拉取下来，建议检查下。

**Comment by chenhaoge** [comment]
> 这个一般是你的SDK没有完整的从github上拉取下来，建议检查下。

好的，谢谢
