### ISSUE TITLE
 PackageEvent.packageAuthorizationCancel.addListener问题（紧急！！！）

### ISSUE THREAD

**Issue by WWJ1993** [MiEcosystem/miot-plugin-sdk#959]
**是否为新品（必填）**
在售

**关联的产品model**
"model": "ihealth.bp.bpm1“

**项目ID（必填）**
"model": "ihealth.bp.bpm1“
**企业名称（必填）**
iHealth
**环境（必填）**
电脑操作系统:[Mac OS]
手机系统:[手机型号MI NOTE LTE 安卓版本： Android 6.0.1 MIUI版本： MIUI 9.2]
SDK分支: [master_10011]
相关模块:  PackageEvent.packageAuthorizationCancel.addListener

**现象（必填）**
1、openPrivacyLicense进行软件政策和隐私协议授权；
2、privacyAndProtocolReview打开软件政策和隐私协议页面，取消授权；
3、在MainPage.js里的componentDidMount监听packageAuthorizationCancel消息，收到了这个消息，断点调试，此方法走了，但是还没来得及执行 Host.storage.set(licenseKey, false);这行代码，程序就退出了，导致状态没有改变，再次绑定还是授权状态。
代码如下：
 PackageEvent.packageAuthorizationCancel.addListener(()=>{
         // 用户撤销授权,需要清除缓存
   
    let licenseKey = "license-" + Device.deviceID;
    console.log("licenseKey"+licenseKey);
    Host.storage.set(licenseKey, false);
    Package.exit();

    })
**期望（必填）**
希望能尽快给解决一下，已经影响了使用
**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
也参考过其他人提出的相关问题，但是我遇到这个现象没有人遇到过
**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
@lvjie0519 我用安卓手机进行测试，授权成功后再执行 Host.ui.privacyAndProtocolReview，打印出：
解析后的URL {__packager_asset: true, width: undefined, height: undefined, uri: "http://10.231.94.239:8081/assets/projects/com.xiao…orm=android&hash=69bec23738a458acc38da0a13213450b", scale: 1}
没有执行 packageAuthorizationCancel 的监听代码，也没有退出插件。请你测试一下

**Comment by lvjie0519** [comment]
@WWJ1993  有没有尝试类似xiaomi.demo那样？  将监听实现为全局的方式，是否能够写入成功？

**Comment by lvjie0519** [comment]
@zanetti4    Host.ui.privacyAndProtocolReview 是打开具体的用户协议和隐私政策页面，需要点击下方的  “撤销……”   按钮，才会发送具体的撤销事件。

**Comment by blockdate** [comment]
隐私协议授权可以参考如下

```
//batchGetDeviceDatas 设置的属性在设备删除以及设备取消授权之后会自动清空，因此只需要在请求授权检测时，检查下flag即可。撤销授权时可以不用手动清理flag
Service.smarthome.batchGetDeviceDatas([{ did: Device.deviceID, props: ["prop.s_auth_config"] }]).then(res => {
            console.log('batchGetDeviceDatas ', res);
            let alreadyAuthed = false;
            let result = res[Device.deviceID];
            let config;
            if (result && result['prop.s_auth_config']) {
              config = result['prop.s_auth_config']
            }
            if (config) {
              try {
                let authJson = JSON.parse(config);
                console.log('auth config ', authJson)
                alreadyAuthed = authJson.privacyAuthed && true;
              } catch (err) {
                //json解析失败，不处理
              }
            }

            if (alreadyAuthed) {
              //已授权，不再弹窗显示
              alert("已经授权")
              return new Promise.resolve("已经授权")
            } else {
              return Host.ui.openPrivacyLicense(xxxxxx).then(res => {
                console.log('授权结果', res)
                if (res) {
                  return Service.smarthome.batchSetDeviceDatas([{ did: Device.deviceID, props: { "prop.s_auth_config": JSON.stringify({ 'privacyAuthed': 'true' }) } }])
                } else {
                  return new Promise.reject("取消授权")
                }
              })
            }
          }).catch(err => {
            //没能授权成功
            console.log('授权错误', err)
            Package.exit()
          });

```

**Comment by edwardair** [comment]
看了上面的代码，发现现在隐私授权的flag需要依赖服务器存储了？以前集成时，依赖的是本地存储，导致会在不同手机上同一个设备多次授权，以及米家APP首页删除设备的话，授权不会再次显示问题
@blockdate

**Comment by blockdate** [comment]
现在建议使用服务器，参考这一句：

//batchGetDeviceDatas 设置的属性在设备删除以及设备取消授权之后会自动清空，因此只需要在请求授权检测时，检查下flag即可。撤销授权时可以不用手动清理flag
