### ISSUE TITLE
android使用Svg闪退（iOS无问题）

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#96]
**（iOS无问题）**

android上，代码如图：
![default](https://user-images.githubusercontent.com/2043635/49423879-d34d0380-f7d3-11e8-83c4-ed77bda17e7e.png)
测试，单独放一个空的Svg不会闪退，但是只要用到其他子类，如：Text，插件会直接闪退：
![screenshot_2018-12-04-14-50-55-119_com xiaomi sma](https://user-images.githubusercontent.com/2043635/49423951-0b544680-f7d4-11e8-8d3a-64fe512274ca.png)

**Comment by dingshaoran** [comment]
参考 com.xiaomi.demo->第三方库能力->SVG:shape  对应js文件为 SVGDemo.js  这里包含了 svg 的大多数用法，修改这个文件484行render 方法里的 this.test20 为 this.test10 是 text 的示例，
svg 完全是第三方库，可能实现上由于系统差异有一些不兼容，需要您适配一下。
![image](https://user-images.githubusercontent.com/8750415/49638866-7015d800-fa44-11e8-988c-a69b8553e4d2.png)

**Comment by dingshaoran** [comment]
混淆的问题，已经修改，请下载最新 apk

**Comment by edwardair** [comment]
现在测试正常了，可能开发过程中某个版本问题
