### ISSUE TITLE
安卓米家APP测试版和正式版只能装一个

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#960]
**是否为新品（必填）**
新品

**关联的产品model**
无
**环境（必填）**
安卓手机

**现象（必填）**
安卓手机无法同时安装米家app测试版和正式版

**期望（必填）**
安卓手机能同时安装米家app测试版和正式版，像iOS一样，不用频繁卸载切换版本

**Comment by zanetti4** [comment]
目前安卓手机无法像 ios 那样，安装两个版本。
