### ISSUE TITLE
未调用startDiscoverServices,但是可以监听到发现服务的回调,并且返回的services数组是空的

### ISSUE THREAD

**Issue by xiaofulon** [MiEcosystem/miot-plugin-sdk#961]
**是否为新品（必填）**
新品

**关联的产品model**
lanzu.watch.lanzoom

**项目ID（必填）**
无项目ID

**企业名称（必填）**
厦门蓝族创意科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3.1]
- SDK分支: [10005]
- 相关模块:[Bluetooth]

**现象（必填）**
在ios设备上,蓝牙连接成功后,未调用startDiscoverServices,但是可以监听到发现服务的回调,并且返回的services数组是空的;
主动去调用startDiscoverServices,现象和未调用startDiscoverServices的现象是一样的,只会监听到一次发现服务的回调,并且services数组还是空的;

**期望（必填）**
未调用startDiscoverServices,监听不需要回调,调用startDiscoverServices,监听需要回调并且服务能正常发现,不为空的

**其他的上下文/日志/截图**
1.连接并发现服务
<img width="578" alt="image" src="https://user-images.githubusercontent.com/17547876/59243018-90fff580-8c40-11e9-9c63-3d8b9e8e7c95.png">

2.监听发现服务
<img width="767" alt="image" src="https://user-images.githubusercontent.com/17547876/59242960-4da58700-8c40-11e9-9712-b82d708162ef.png">

**尝试过的解决办法**
1.在原生app中,测试可以正常的发现服务
2.浏览了相关issue,其中关于服务的方法都有进行尝试,包括不同的方法创建BluetoothLE
ble = Bluetooth.createBluetoothLE(uuid)//ble = Device.getBluetoothLE()
安卓上可以正常使用

**Comment by xiaofulon** [comment]
有人出现过这样的情况吗?等的好焦急!

**Comment by zanetti4** [comment]
@blockdate 请下周有时间进行查看

**Comment by blockdate** [comment]
建议提供下你scan的连个service的uuid，并且提供下通过lightblue扫描到的设备的所有service的uuid列表
