### ISSUE TITLE
app不在前台的时候，蓝牙连接断开后，插件能否接收到事件通知

### ISSUE THREAD

**Issue by Iceux** [MiEcosystem/miot-plugin-sdk#963]
**是否为新品（必填）**
新品

**关联的产品model**
minuo.tracker.lm001

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
陕西米诺电子信息技术有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3.1]
- SDK分支: [master]
- 相关模块:[miot/Bluetooth]

**现象（必填）**
当app不在前台的时候，目前无法实现防丢器蓝牙连接断开后，将这个消息通知到插件
**期望（必填）**
当app不在前台的时候，防丢器需要实现手机与防丢器保持长连接，当连接断开后，希望能有消息通知到插件，实现位置记录和本地app推送提醒

**Comment by Iceux** [comment]
补充一点，希望在插件退出后米家app能在后台维持蓝牙连接，收到设备发送的消息后能有机制唤醒插件进行处理（比如发送本地推送提醒，或播放提示音）。

**Comment by Woody2016** [comment]
1. 退出插件，保持蓝牙的连接，这个是可以做的，插件在退出时不要断开蓝牙连接即可
2. app切后台，手机系统会根据不同的情况kill掉app，用户也可能主动kill app，这时即使蓝牙连接不断开，也干不了啥了

**Comment by Woody2016** [comment]
所以贵司是不是应该再考虑下此需求的必要性

**Comment by Iceux** [comment]
@Woody2016  由于产品功能的特点，我们期望能实现当app切后台（非用户手动kill app情况下）仍然能处理蓝牙通信的消息。
目前在iOS上可以使用蓝牙的 central Background Execution Mode实现（需要在原生应用的info.plist中配置启用）
Android上可能需要允许app后台运行，处理蓝牙长连接消息。
您说的用户手动kill app情况，我们考虑可以通过产品使用说明书和应用内提示，引导用户不要手动kill app，从而实现现当app切后台情况下根据蓝牙通信数据和连接状态实现app本地推送提醒。

**Comment by Iceux** [comment]
由于用户使用防丢器过程中，不太可能一直保持app在前台运行，所以实现app切后台（当用户不手动kill app情况下）仍然能保持处理蓝牙通信数据，并根据设备发送的指令或蓝牙连接状态，在app上实现相应的提醒很有必要。

**Comment by Iceux** [comment]
我们考虑到当用户在户外或室内没有蓝牙网关的情况下实现app本地推送提醒（不通过网络推送）：
1、实现用户通过防丢器查找手机(双击防丢器上的按键，通过蓝牙发送特点指令数据到手机，手机本地推送提醒)。
2、防丢器和手机蓝牙断开连接后，手机本地推送提醒，并最好能在断开的时候通过手机获取当前定位，并通知到我们的插件程序内。
以上两点，也需要当app切后台（用户不手动kill app情况下）实现，这样真个产品的体验才算比较完整。

**Comment by Woody2016** [comment]
1.
目前在iOS上可以使用蓝牙的 central Background Execution Mode实现（需要在原生应用的info.plist中配置启用）
Android上可能需要允许app后台运行，处理蓝牙长连接消息。
---- 这个修改需要米家技术组评估

2. 
实现app切后台（当用户不手动kill app情况下）仍然能保持处理蓝牙通信数据，并根据设备发送的指令或蓝牙连接状态，在app上实现相应的提醒很有必要。
--- 这就相当于在米家app端（不是在插件内），为了这一个设备而添加一些特殊的蓝牙逻辑处理，和我们的app设计理念不符。一般来说，设备相关的业务处理都要放在插件里做。

基于这个产品情况特殊，建议采用独立sdk开发独立app来做，自由度大
