### ISSUE TITLE
隐私声明策略咨询

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#964]
目前在集成 CommonSetting组件，发现如果设备是分享的设备，那么在设置里面是无法查看“法律信息”这一栏的，也就代表此用户是无法取消授权，但是插件在第一次打开时，会弹窗显示“隐私声明”确认弹窗，只有用户确认后才能进入此插件，导致用户能授权，但不能取消授权，造成不统一问题

**咨询下，分享的设备，插件在第一次进入时，仍旧显示隐私弹窗，还是判断此设备为分享的设备，从而不会显示隐私弹窗？**

**Comment by blockdate** [comment]
分享设备是不需要隐私授权的，这个我们在后续SDK会默认带上这个判断。

但是在10020以及之前版本的SDK上，这一块的逻辑需要自己判断。

**Comment by edwardair** [comment]
10021多久会合并？（双平台），在等10021固件升级的小红点
