### ISSUE TITLE
iOS无法调试旧版插件

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#965]
**现象（必填）**
昨天刚下载的测试版米家iOS，可以进入开发者模式，可以连接本地开发环境，但是不能调试，错误同https://www.jianshu.com/p/2c5e738cecca，解决办法也在网页里，需要你们来查一下

**期望（必填）**
能够调试，看到log

**Comment by santcool** [comment]
老的调试需要打开 开发者设置 - 其他设置 - 插件调试已关闭。注意调试完毕后需要关闭此选项，否则会影响新插件的调试

**Comment by Android-yzhang** [comment]
我开发了很长时间了，一直没啥问题，昨天下了个新版的，突然不好使了。而且刚才发现，调试新版插件，原先打开插件调试就可以了，刚才也不行，需要像直接开发rn那样，摇出菜单，这都是之前没有的 @santcool

**Comment by zanetti4** [comment]
@Android-yzhang 如果此问题已解决，请您关闭
