### ISSUE TITLE
MHLog在新框架上不支持

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#966]
**是否为新品（必填）**
在售

**关联的产品model**
lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [10021]
- 相关模块:[Host]

**现象（必填）**
MHLog在新框架上没有对应的接口

**期望（必填）**
在新框架上提供MHLog对应的接口

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
现在最新的正式分支是10012，先用这个吧。10021还在开发中

**Comment by zanetti4** [comment]
Service.smarthome.reportLog，可以使用这个模块，[参考文档](https://github.com/MiEcosystem/miot-plugin-sdk/wiki/08-%E6%97%A5%E5%BF%97%E7%BB%9F%E8%AE%A1%E6%A8%A1%E5%9D%97)

**Comment by ts87** [comment]
thanks
