### ISSUE TITLE
Host.ui.openDevice接口无法在当前插件页面跳转

### ISSUE THREAD

**Issue by damiknows** [MiEcosystem/miot-plugin-sdk#967]
**是否为新品（必填）**
新品 

**关联的产品model**
“lumi.gateway.mgl03”

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 11.0]
- SDK分支: [10020]
- 相关模块:[Host/UI]

**现象（必填）**
Host.ui.openDevice接口无法在当前插件页面跳转，会先退出插件，返回米家首页再跳转页面

**期望（必填）**
Host.ui.openDevice接口能在当前插件页面跳转，并能返回当前插件页面。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
使用 `Host.ui.openDevice(did, model, { dismiss_current_plug: false })`

**Comment by Pandalzm** [comment]
@blockdate 你好，我这边使用 Host.ui.openDevice(did, model, { dismiss_current_plug: false })，测试过之后，发现，iOS 没问题，安卓的还是会先退出当前插件，再跳转到对应的插件。

**Comment by Pandalzm** [comment]
安卓端使用的版本：5.5.23.5

**Comment by blockdate** [comment]
Android这边插件打开逻辑如下：
1. 打开RN插件，会直接返回上一个原生页面(首页，或者退出当前插件)
2. 打开JavaNative插件，如果是关联设备(服务端配置)，可以直接打开，如果是非关联设备，会返回上一个原生页面。
