### ISSUE TITLE
安卓端房间命名相关API没有实现

### ISSUE THREAD

**Issue by HunterHeRock** [MiEcosystem/miot-plugin-sdk#968]
**是否为新品（必填）**
在售

**关联的产品model**
roborock.vacuum.tanos

**企业名称（必填）**
石头科技

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/]
- 手机系统:[Android 8.1/iOS 11.0]
- SDK分支: [10012]
- 相关模块:[]

**现象（必填）**
简单明了地描述一下实际的现象。

**期望（必填）**
扫地机地图房间名称编辑和显示功能，需要以下3个MHRoom中与房间命名（获取房间名称）相关的接口，
1.  getRoomList
2.  addNewRoomWithName
3.  editRoom

此3个API在IOS端已能正常使用，安卓端没有实现，需要补齐。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
两端已统一提供。更新SDK至 10021， 参考Service.room的方法以及 com.xiaomi.demo/Main/Service/room.js的demo实现。

![image](https://user-images.githubusercontent.com/4339364/59731312-2706d200-9278-11e9-8a62-c24dde30cfb8.png)

**Comment by lvjie0519** [comment]
@HunterHeRock   用最新apk及sdk 使用10021分支进行验证，谢谢。

**Comment by zanetti4** [comment]
@HunterHeRock 如果问题得到解决，请关闭此 issue
