### ISSUE TITLE
蓝牙返回error code

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/miot-plugin-sdk#969]
**是否为新品（必填）**
在售

**关联的产品model**
“yuemee.airmonitor.mhfd1”

**项目ID（必填）**
无项目ID

**企业名称（必填）**
Honeywell

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android /iOS ]
- SDK分支: [10011]
- 相关模块:[BLE]

**现象（必填）**
1、蓝牙连接接口connect，超时时间具体为多少？
2、蓝牙连接接口connect，什么情况下会返回-1（device not exist）、-7（timeout）

**期望（必填）**
插件需要做重连处理，故需要miot提供哪些error code需要做重连。

**Comment by zanetti4** [comment]
1.超时时间可以在参数中设置
connect(3, {peripheralID:"1-a-b-3-c", timeout:12000})
2.请求失败时返回-1，请求超时返回-7.请检查传入的参数是否正确。

**Comment by EllisonYe** [comment]
插件需要做重连处理，故需要miot提供哪些error code需要做重连?

**Comment by zanetti4** [comment]
@pencilCool @dingshaoran 请你们协助查看此问题

**Comment by pencilCool** [comment]
超时错误码- 7 可以做重试处理。其他错误码可以提示用户手动重试

**Comment by EllisonYe** [comment]
好的

发自我的 iPhone

在 2019年7月31日，下午5:41，小米-pencilCool <notifications@github.com<mailto:notifications@github.com>> 写道：


超时错误码- 7 可以做重试处理。其他错误码可以提示用户手动重试

**Comment by zanetti4** [comment]
如果问题已解决，请关闭

**Comment by EllisonYe** [comment]
close
