### ISSUE TITLE
三方接口调用 code=-17

### ISSUE THREAD

**Issue by JiuanZbf** [MiEcosystem/miot-plugin-sdk#970]
**是否为新品（必填）**
新品

**关联的产品model**
ihealth.bpm.kd5907

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
iHealth

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3.1]
- SDK分支: [10012]
- 相关模块:[Service]

**现象（必填）**
调用这个方法时miot/service/smarthome.callThirdPartyAPI(params)
报
callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-17 "(null)" UserInfo={message=result not received yet, result=callback_time not exists, code=-17}
这个为偶发，有的时候重新调用就会正常返回

**期望（必填）**
正常返回

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
在carch到这个错误的时候我会去重新调用一遍这个方法，大概7 8 遍的时候会成功返回

**不要贴大段代码❗️**

**Comment by santcool** [comment]
Duplicate of #971

**Comment by JiuanZbf** [comment]
额？这个问题怎么关了？

**Comment by zanetti4** [comment]
这个问题和 #971 是一个问题
