### ISSUE TITLE
接口code=-17，iOS频发，非常影响使用，紧急优先级

### ISSUE THREAD

**Issue by WWJ1993** [MiEcosystem/miot-plugin-sdk#971]
是否为新品（必填）
新品

关联的产品model
ihealth.bp.bpm1

项目ID（必填）
【无项目ID】

企业名称（必填）
iHealth

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 11.2.2]
SDK分支: [10011]
相关模块:[Service]
现象（必填）
调用这个方法时miot/service/smarthome.callThirdPartyAPI(params)
报
callSmartHomeAPI failedError Domain=MiHomeNetworkErrorRemote Code=-17 "(null)" UserInfo={message=result not received yet, result=callback_time not exists, code=-17}
iOS频发，有时候10次，9次不行，太难用
期望（必填）
正常返回

其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法
各个接口都有出现这种情况的概率
不要贴大段代码❗️

**Comment by blockdate** [comment]
提供下具体的使用代码，并分享使用设备到894158105

**Comment by WWJ1993** [comment]
如下是封装的接口方法
function historyApi(bodyDic, callBack)
{
    var timer;
    var timeoutFlag = false;

    //启动定时器,登录接口设置60s超时
    timer = setTimeout(()=>{
       timeoutFlag = true;
    //    iHealth.log("historyApi", '数据下载-----网络访问超时！！！');
       callBack(false, '超时错误', '102');
     }, 15000);

     let configureInfo={
       'ApiType':'bpm1datadownload',
       'sc':'7c789858c0ec4ebf8189ebb14b6730a5',
       'sv':'39907b2543041d9h93b6075576381a0e',
       'AppVersion':'MiHome_i_1.0.1',
       'AppGuid':bodyDic.AppGuid,
       'PhoneID':bodyDic.PhoneID,
       'PhoneName':Host.systemInfo.mobileModel,
       'PhoneOS':Host.systemInfo.sysName + Host.systemInfo.sysVersion,
       'PhoneLanguage':'zh',
       'PhoneRegion':'CN',
       'Token':Service.account.ID+'@mi',
       'Un':Service.account.ID+'@mi',

       'VerifyToken' : bodyDic.verifyToken,
       'QueueNum' : bodyDic.queueNum,
       'PageSize' : bodyDic.pageSize,
       'Position' : bodyDic.position,
       'TS' : bodyDic.ts,
       'DidList' : bodyDic.didList
     };
    // iHealth.log("historyApi configureInfo:", JSON.stringify(configureInfo));

    Service.smarthome.callThirdPartyAPI({"app_id":"10021","dids":[Device.deviceID],"params":configureInfo}).then(res => {
            iHealth.log("historyApi result",JSON.parse(res).result);

            let code = JSON.parse(res).code;
            let responseResultString = JSON.parse(res).result;
            let responseResult = JSON.parse(responseResultString);
            if (!timeoutFlag){
                iHealth.log('historyApi', '无超时');
                clearTimeout(timer);
                //code==0,请求成功
                if((code === 0) && responseResult){
                    if (responseResult.ResultMessage === '100') {
                        callBack(true, responseResult, '100');
                    }
                    else if (responseResult.ResultMessage === '200') {
                        //接收服务器返回的正确地址
                        callBack(false, '服务器地址错误', '200');
                    }
                    else if (responseResult.ResultMessage === '208') {
                        //接收服务器返回的正确地址
                        callBack(false, '服务器地址错误', '208');
                    }
                    else if (responseResult.ResultMessage === '212') {
                        //刷新token
                        callBack(false, 'token失效', '212');
                    }
                    else if ((responseResult.ResultMessage === '221') || (responseResult.ResultMessage === '218')) {
                        //令牌错误或刷新令牌错误，需要重新登录获取令牌和刷新令牌
                        callBack(false, '令牌错误', '221');
                    }
                    else {
                        //其他错误
                        callBack(false, '其他错误', '500');
                    }
                }
                else {
                    //其他错误
                    callBack(false, '其他错误', '500');
                }
            }

        }
    );

}
设备已经分享

**Comment by WWJ1993** [comment]
而且，点击插件，进入设备首页时候特别慢，

**Comment by santcool** [comment]
Error Domain=MiHomeNetworkErrorRemote Code=-17 "(null)" UserInfo={message=result not received yet, result=callback_time not exists, code=-17} 应该是你们传的参数有问题，这个问题是我们服务端去请求你们服务端数据时，出现错误，导致数据没取回来。请你们服务端的同学打一下log，看看问题在哪儿

**Comment by santcool** [comment]
另外，进入首页特别慢的问题，我抓包发现，你们进入页面，执行了多次callThirdPartyAPI。另外这个接口涉及到移动端到iot平台，再到你们自己的服务器，接口时间无法保证，故需要你们做一些优化：尽量少发这种跨服务器的请求（比如，减少请求书，或者直接从iot平台获取数据），尽量展示一个友好的加载页面。

**Comment by WWJ1993** [comment]
@santcool ，好的，谢谢，我先查一下

**Comment by WWJ1993** [comment]
老版本的米SDK是没有这个问题的

**Comment by santcool** [comment]
调试的时候慢是正常的，因为要从node服务器上获取资源。如果是打包上传之后，首次加载慢，首次因为我们需要加载js SDK，也会慢一点。如果都不是，建议你先注销部分功能，上传一个阉割的包试试看，分析出来是哪一步慢。

**Comment by WWJ1993** [comment]
ok

**Comment by DanielYinhd** [comment]
Error Code=-17时，是请求我们的服务器端，服务器端未响应，还是服务器端有响应但返回参数有错误

**Comment by JiuanZbf** [comment]
@santcool 这边catch 到-17报错的时候在后台输出中是可以看到你们有收到我们正确的请求的输出如下，
receive mi push: {
	result = {
	message = ,
	result = {正确的返回},
	sid = 2062606128,
	model = *****,
	msgid = *****
}

**Comment by santcool** [comment]
@JiuanZbf  能提供一个抓包的完整接口吗？包括请求参数和返回值（-17）,我这边需要提供给服务端的查一下

**Comment by JiuanZbf** [comment]
@santcool 我这边不是抓包获取的，是用rn在debug模式 控制台输出出来的 上面我发的应该是你们内部输出的结果

**Comment by santcool** [comment]
不是，这个是接口返回的，然后被我们log出来。之前有使用过charles进行抓包吗？https://michaelyb.top/2018/08/Use-Charles/这儿有个简单的charles教程可以看看

**Comment by JiuanZbf** [comment]
@santcool 好 麻烦提供一个邮箱 我把抓包数据发给你

**Comment by santcool** [comment]
@JiuanZbf  zhangwenfeng@xiaomi.com

**Comment by JiuanZbf** [comment]
@santcool 邮件昨天已发送，麻烦查收下

**Comment by santcool** [comment]
现在这个问题还在吗啊？当时那个邮件我好像没收到……能重新发一份吗？

**Comment by JiuanZbf** [comment]
@santcool 问题还在，邮件已发送。

**Comment by JiuanZbf** [comment]
@santcool 额 解决分支是在最新master上还是新版测试app？
