### ISSUE TITLE
android webview内嵌视频，如何将全屏播放的按钮移除或生效

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#972]
- IPA/APK 最新
- SDK master 10012最新

---
**是否为新品（必填）**
在售

**关联的产品model**
roidmi.carairpuri.v1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
睿米

**环境（必填）**
- 电脑操作系统: Mac OS
- 手机系统: Android
- SDK分支: master
- 相关模块: WebView

**现象（必填）**
我们有个网页内嵌了一个视频，HTML代码：
```
<video width="100%" id="veido" controls="true" controlsList="nodownload nofullscreen" autoplay="autoplay" playsinline="true" webkit-playsinline="true" loop="true">
<source src="*.mp4" type="video/mp4">
</video> 
```
在安卓上，视频的播放组件上会有一个灰色的全屏按钮，无法点击，查了资料说是RN Android webivew不支持全屏的缘故

**期望（必填）**
视频的播放组件上，灰色全屏按钮移除 / 或者如何让它有效

**其他的上下文/日志/截图**
![1](https://user-images.githubusercontent.com/2043635/59256810-447be080-8c67-11e9-900b-0cdb3d799946.png)

**Comment by zanetti4** [comment]
react native 官网建议用 [react-native-community/react-native-webview](https://github.com/react-native-community/react-native-webview) 替代 WebView 组件。你用的是这个新模块吗？

**Comment by edwardair** [comment]
不是，用的RN自带的webview，像这种库，是带有平台原生代码的，米家插件不允许导入原生代码的库，所以没法使用
@zanetti4

**Comment by zanetti4** [comment]
@lvjie0519 如果不取消 controls 属性，还有什么解决办法吗？

**Comment by lvjie0519** [comment]
@edwardair @zanetti4   我这边排期排查下，预计下周，谢谢。

**Comment by zanetti4** [comment]
@edwardair 我用安卓手机测试，发现视频的全屏图标已经移除了。

**Comment by fishle** [comment]
@zanetti4 估计有些rom在底层修复这个问题, @edwardair 如果还不行的话，试试在css里面加上
video::-webkit-media-controls-fullscreen-button {
          display: none;
        }
这边测试可以隐藏掉全屏按钮
