### ISSUE TITLE
接收到推送，如何实现点击推送可自动启动米家app

### ISSUE THREAD

**Issue by WWJ1993** [MiEcosystem/miot-plugin-sdk#973]
是否为新品（必填）
在售

关联的产品名称（必填）
“米家iHealth血压计”

项目ID（必填）
"model": "ihealth.bp.bpm1“

企业名称（必填）
iHealth

环境（必填）
电脑操作系统:[Mac OS]
手机系统:[手机型号MI NOTE LTE 安卓版本： Android 6.0.1 MIUI版本： MIUI 9.2]
SDK分支: [master_10011]
相关模块:推送

现象（必填）
iOS接收到推送，点击推送消息可自动启动米家app，但是
安卓接收到推送，点击推送消息没有反应，安卓该如何做处理
期望（必填）
安卓可以和iOS一样，点击推送消息可自动启动米家app

**Comment by zanetti4** [comment]
#872

**Comment by lvjie0519** [comment]
@WWJ1993   
1、ios自动启动米家app，仅仅只是进入米家首页还是进入到插件页面？
2、检查下Android apk 是否为fir上最新版本？

**Comment by WWJ1993** [comment]
iOS只是进入了米家首页

**Comment by WWJ1993** [comment]
安卓和iOS都是最新版本的安装包，iOS还是只是进入了米家首页，安卓进入了我们接入设备的首页（插件首页），他们俩不能同步吗？

**Comment by lvjie0519** [comment]
@WWJ1993   你们推送的具体是什么消息？ 是什么类型消息？

**Comment by WWJ1993** [comment]
这个我和后台确认一下，明天给你答复

**Comment by WWJ1993** [comment]
pushToMiHome.pushNewResultToMiHome = async (did,title,desc,data) => {
    //推送Android
    let ts = moment().format('X');
    let msgid = md5(did+'device'+ts);
    let payloadAndroid = {
        "msgid": msgid,
        "type": "scene",
        "body": {
            "model": "ihealth.bp.bpm1",
            "did": did,
            "event": "result",
            "time": ts,
            "extra": data
        }
    }
    pushToMiHome.push(did,title,desc,payloadAndroid,2,1);
    //推送iOS
    let dataStr = data.DataID+','+data.Did+','+data.HeartRate+','+data.HighP+','+data.LowP+','+data.Position+','+data.UserID+','+data.Mood+','+data.TakePill+','+data.MeasureTime;
    let resultStr = encodeBASE64.encode64(dataStr);
    let payloadiOS = 'scene,ihealth.bp.bpm1,result,'+did+','+ts+','+resultStr;
    pushToMiHome.push(did,title,desc,payloadiOS,2,2);
};

**Comment by WWJ1993** [comment]
http://open.io.mi.com/open/mipush/notify

**Comment by WWJ1993** [comment]
@lvjie0519 我们提供的信息可以吗？给答复一下呗

**Comment by lvjie0519** [comment]
@WWJ1993    我这边正在两端沟通，请稍等，有消息及时回复。

**Comment by blockdate** [comment]
@WWJ1993 这个消息在消息中心点击可以正常打开设备么。

**Comment by WWJ1993** [comment]
iOS可以正常启动app，只是进入米家首页，进不了插件首页，安卓在消息中心点击可直接进插件首页（也就是点击点击我们设备，进入的第一个页面）

**Comment by WWJ1993** [comment]
发现 iOS app 在 Chrome 的 remote debug 情况下，会在js中输出了推送信息，
receive mi push: {
	result = {
	message = ,
	result = {......
},
	sid = *******,
	model = *****,
	msgid = *****
}
然后我们插件如何做处理呢？

**Comment by WWJ1993** [comment]
我看到文档中这样写的，但是有些参数不知道传什么
 let  msgSubscription = null;
      Device.getDeviceWifi().subscribeMessages(？？？？这咋写).then((subcription)=>{
        msgSubscription = subcription;
        console.log('magSubscription'+ JSON.stringify(subcription) );
      }).catch((error)=>{
          console.log('subcription error'+error);
      });

      

      const subscription = DeviceEvent.deviceReceivedMessages.addListener(
        (device, res) => {
          console.log('deviceReceivedMessages', device,JSON.stringify(res));
        }
  )

**Comment by WWJ1993** [comment]
@blockdate @lvjie0519 有进展吗？

**Comment by lvjie0519** [comment]
@WWJ1993  从消息中心点击详细，不是相当于已经打开米家APP了吗， Android从消息中心点击消息可以进入插件， ios仍然是跳转到米家首页（设备列表页面）？

**Comment by WWJ1993** [comment]
![image](https://user-images.githubusercontent.com/19355283/59581605-028be800-9108-11e9-91cd-68ec708562f2.png)
我指的是从这里点进去，ios仍然是跳转到米家首页， Android可以进入我们链接的插件首页。咱俩说的是一个意思吗？

**Comment by WWJ1993** [comment]
能加一下微信吗？

**Comment by lvjie0519** [comment]
@WWJ1993   微信号： 18750118631

**Comment by santcool** [comment]
我这边试了下，是可以进入设备页面的。请使用最新的测试包，SDK_10025再做尝试。
