### ISSUE TITLE
非小米机型状态栏背景为黑色

### ISSUE THREAD

**Issue by fergus825** [MiEcosystem/miot-plugin-sdk#976]
**是否为新品（必填）**
新品(在售)
**关联的产品model**
chuangmi.lock.hmi501

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
创米科技

**环境（必填）**
- 电脑操作系统:Mac OS 10.14.5
- 手机系统:android 9.0
- SDK分支: 10011，10020
- 相关模块:[UI]

**现象（必填）**
华为荣耀V9和华为Mate 20 插件状态栏区域全黑，此外其他适配了新RN框架的产品的插件也是相同效果。

**期望（必填）**
呈现沉浸式状态栏效果。

**其他的上下文/日志/截图**
![image](https://user-images.githubusercontent.com/25863361/59274793-a5b6aa80-8c8d-11e9-9918-ceb22b653781.png)
![image](https://user-images.githubusercontent.com/25863361/59274864-c7b02d00-8c8d-11e9-9ee9-7289cde2d612.png)

**尝试过的解决办法**
小米手机测试正常，sdk升级由10011升级到10020问题依然存在。

**Comment by LiuMengzhou** [comment]
本地调试还是线上？
安卓米家APP版本

**Comment by fergus825** [comment]
本地调试和线上都是一样。米家调试版本5.5.25。

**Comment by LiuMengzhou** [comment]
那你有没有试过我们的 com.xiaomi.demo

在首页->教程->Titlebar Demo 和NavigationBar Demo

**Comment by fergus825** [comment]
好的，我先试一下。

**Comment by fergus825** [comment]
demo 上显示正常。我把主页的TitleBarWhite 换成了TitleBar，状态栏上的文字变成白色的了，但是背景还是黑色，没有和状态栏融为一体形成沉浸效果。把设置页面的TitleBarBlack改成TitleBar，添加type={'dark'}后，刚进入该页面状态栏文字白色，背景还是黑色，然后文字全部变成黑色。之后返回主页面，主页面状态栏页面也变成了全黑。然后按照demo上的写法重写插件里的标题栏布局，状态栏还是黑色的。然后换了OPPO R11 运行demo，状态栏都是黑色的，运行新框架的智能设备的插件，状态栏也是黑色。因此是小米手机: demo、插件 均正常； 华为:demo正常，插件异常， OPPO: demo 插件均异常。

**Comment by fergus825** [comment]
升级到最新的10021，换用NavigationBar，荣耀V9，锤子ML，OPPO R11 状态栏还是没有沉浸效果。

**Comment by fergus825** [comment]
尝试了一种方法可以解决非小米机型状态栏显示为黑色的问题：在TitleBar或NavigationBar上方添加一个StatusBar，并设置其backgroundColor为'transparent'。如大家也遇到相同问题且有更优雅的解决方式，烦请不吝赐教。

**Comment by Banjiemin** [comment]
> 尝试了一种方法可以解决非小米机型状态栏显示为黑色的问题：在TitleBar或NavigationBar上方添加一个StatusBar，并设置其backgroundColor为'transparent'。如大家也遇到相同问题且有更优雅的解决方式，烦请不吝赐教。

兄弟，具体是怎么做的呢？请把完整的代码（mainpage.js中涉及到titleBar的地方）发出来看看哦，谢谢 ！

**Comment by fergus825** [comment]
> > 尝试了一种方法可以解决非小米机型状态栏显示为黑色的问题：在TitleBar或NavigationBar上方添加一个StatusBar，并设置其backgroundColor为'transparent'。如大家也遇到相同问题且有更优雅的解决方式，烦请不吝赐教。
> 
> 兄弟，具体是怎么做的呢？请把完整的代码（mainpage.js中涉及到titleBar的地方）发出来看看哦，谢谢 ！

我上次试了下TitleBar上加透明状态栏没有达到沉浸式的效果。建议使用10021起支持的NavigationBar。
![image](https://user-images.githubusercontent.com/25863361/60065569-e3f4a500-9736-11e9-8c63-41c70f285a37.png)

**Comment by Banjiemin** [comment]
> > > 尝试了一种方法可以解决非小米机型状态栏显示为黑色的问题：在TitleBar或NavigationBar上方添加一个StatusBar，并设置其backgroundColor为'transparent'。如大家也遇到相同问题且有更优雅的解决方式，烦请不吝赐教。
> > 
> > 
> > 兄弟，具体是怎么做的呢？请把完整的代码（mainpage.js中涉及到titleBar的地方）发出来看看哦，谢谢 ！
> 
> 我上次试了下TitleBar上加透明状态栏没有达到沉浸式的效果。建议使用10021起支持的NavigationBar。
> ![image](https://user-images.githubusercontent.com/25863361/60065569-e3f4a500-9736-11e9-8c63-41c70f285a37.png)

Ok，谢谢，我来试试
