### ISSUE TITLE
Service.smarthome.getDeviceSettingV2获取数据会变化

### ISSUE THREAD

**Issue by wanggoingdown** [MiEcosystem/miot-plugin-sdk#977]
**注意事项：（阅读后，创建issue时此段可删除）**
- Issue提交及后续处理流程中，均需指定assignee，自己处理完毕后需要其他人继续跟进的，请及时更改assignee（创建issue时assignee默认是米家这边）
- 每个issue需要指定待修复的SDK版本，通过milestone指定（米家指定）
- 请issue处理人指定issue的优先级（米家+开发者协商）
    紧急优先级：线上插件的严重bug 或 block验收的新产品接入问题。12小时内响应，48小时内解决
    高优先级：排期紧张(<1月)的新产品接入相关问题。24小时内响应，1周内解决
    普通优先级：已有老框架插件功能补齐及迁移；排期较宽松(>1月)的新产品接入；已有模块的性能优化等。24小时内响应，3周内解决

**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
- SDK 是否更新到最新？
- Check 文档了吗？
- 是否尝试搜索issue？

---
**是否为新品（必填）**
填 新品 or 在售
新品

**关联的产品model**
此issue关联的产品model，如“lumi.curtain.hagl05”

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】
无项目ID

**企业名称（必填）**
贵司的名称
绿米联创

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
Mac OS
- 手机系统:[eg.Android 8.1/iOS 11.0]
Android8.1 Ios 11。0
- SDK分支: [eg.master/10000/...]
10010
- 相关模块:[eg.Host/Service/Account]
Service
**现象（必填）**
简单明了地描述一下实际的现象。
我多台调用Service.smarthome.getDeviceSettingV2接口获取同一个数据，
一开始是正常的，但是过了一段时间，其中一台手机获取到一个错误的值，
而其余手机是正常的。而任意一手机调用Service.smarthome.setDeviceSetting去设置一个值，
全部手机再调用Service.smarthome.getDeviceSettingV2获取数据，数据再次恢复正常。
该现象为偶现现象，希望能帮助排查问题。

**期望（必填）**
简单明了地描述一下期望的表现。
希望在Service.smarthome.getDeviceSettingV2能稳定获取数值

**其他的上下文/日志/截图**
[提供更多的上下文，有日志或者截图更好。]

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
希望能贴上正确和错误的对比，以及出错的手机型号，是否总是那一台手机出现错误？

**Comment by wanggoingdown** [comment]
@zanetti4 没有固定出现的手机，但是一旦出现请求数据，那么每一次都是错误的，我先贴个图给你看
![366c8cf83758348c0dec09a148882df0](https://user-images.githubusercontent.com/10232787/59415201-99e5f800-8df5-11e9-81fe-2d64ba1c4659.jpg)

**Comment by wanggoingdown** [comment]
@zanetti4 左边正确，右边错误，右边每次请求都是错误的数据，而左边进行数据的更新后，再刷新右边，右边也会跟着改变

**Comment by zanetti4** [comment]
@blockdate 请你帮忙看一下这是什么问题

**Comment by santcool** [comment]
给出抓包信息，不然我们这边没法判断。
