### ISSUE TITLE
如何获取固件版本号和下载固件文件？

### ISSUE THREAD

**Issue by dgutkai** [MiEcosystem/miot-plugin-sdk#978]
**是否为新品（必填）**
新品

**关联的产品model**
ls123.headphone.t10

**企业名称（必填）**
猎声电子

**环境（必填）**
- SDK分支: 10011

**现象（必填）**
项目需要实现设备的OTA功能，请问固件的版本号以及固件文件的下载地址是通过米家接口获得吗？还是需要我们自己搭建服务器？
使用Device.extra返回空的数据。截图是Device的值。
<img width="991" alt="屏幕快照 2019-06-12 10 47 58" src="https://user-images.githubusercontent.com/12670497/59320265-58275580-8d00-11e9-85e5-b25320c65727.png">

**期望（必填）**
能够像旧版Android那样提供固件版本号的查询和下载功能。
<img width="912" alt="屏幕快照 2019-06-12 10 52 26" src="https://user-images.githubusercontent.com/12670497/59320252-447bef00-8d00-11e9-8afa-5bf9cf8f3aa1.png">

**Comment by santcool** [comment]
请查看工程中的 蓝牙OTA步骤.md 和 iot平台的[蓝牙开发指南]（https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E6%96%B0%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/03-%E8%93%9D%E7%89%99%E8%AE%BE%E5%A4%87%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97）中的固件升级部分

**Comment by dgutkai** [comment]
看到了，谢谢解答！
