### ISSUE TITLE
希望提供一个可以指定设备（通过did）的重命名方法

### ISSUE THREAD

**Issue by Pandalzm** [MiEcosystem/miot-plugin-sdk#979]
**是否为新品（必填）**
新品

**关联的产品model**
lumi.gateway.iragl01

**项目ID（必填）**
22538

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:iOS 12.3
- SDK分支: SDK_10020
- 相关模块:Host

**现象（必填）**

**期望（必填）**
现在 Host.ui.openChangeDeviceName() 只能对当前设备进行重命名，
网关有子设备这个概念，需要对某个子设备进行重命名。
希望提供一个可以指定设备（通过did）的重命名方法，

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by Woody2016** [comment]
本周提供sdk接口及db包供试用

@blockdate @lvjie0519 @Pandalzm

**Comment by santcool** [comment]
已完成，在SDK_10022

**Comment by Pandalzm** [comment]
@santcool 首页的包会报如下错误
![ad52ec452b6c77cf67ac16bf2dae2fc8](https://user-images.githubusercontent.com/8938524/60335194-d9087180-99cf-11e9-9439-3e4154a31684.jpg)

**Comment by lvjie0519** [comment]
@Pandalzm   
1、如上错误是Android还是ios？
2、检查下是否最新apk或ipa？

**Comment by Pandalzm** [comment]
@lvjie0519 
1.如上错误是 iOS 的
2. 已经更新到 10022 最新代码，并且更新首页最新的 ipa

**Comment by santcool** [comment]
https://fir.im/tes5?release_id=5d1b4d01f94548536658d98d
试试这个包？

**Comment by Pandalzm** [comment]
@santcool 这个包不报错了，但是无论你传入的 did 是什么，都是修改的是网关的名字。需求是通过 did 修改对应的”子设备“的名字。
