### ISSUE TITLE
iOS 蓝牙问题：read()、setNotify(true)等报错：characteristic or service not found

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#98]
import { Device,BluetoothEvent,Bluetooth} from 'miot'
const bt = Device.bluetooth;

1、bt.connect()之前调用bt.isConnected，100%报undefined;连接成功后，在监听的BluetoothEvent里，有几率报undefined。
2、在BluetoothEvent.bluetoothCharacteristicDiscovered的方法里，执行下面代码，报characteristic or service not found：
bluetooh.getService('180A').getCharacteristic('2a28')
     .read().then(value=>{}).catch(err=>{...})等方法报： error:{"message":"characteristic or service not found"}    

旧版本的方式：
if(notification.service=='180A') {
	//固件版本回调
	MHBluetooth.readBase64DataWithCallback('2a28',notification.service, (isSuccess,            loopbackParams) => {
	});
}

service 和Characteristic分别写为：0000180a-0000-1000-8000-00805f9b34fb和00002a28-0000-1000-8000-00805f9b34fb也还是报：characteristic or service not found

setNotify(true)的方法也是一样。

不知道哪里写的不对。

**Comment by flingInTheSky** [comment]
第二点问题，知道哪里出错了。第一点的问题还是存在

**Comment by dzonel** [comment]
@flingInTheSky  您好，我遇到了和您第二点相同的问题(characteristic or service not found)，请问您是怎么解决的？

**Comment by flingInTheSky** [comment]
在bluetoothSeviceDiscovered的监听里，s.startDiscoverCharacteristics("aa01",'aa02'...);
aa01、aa02是characteristics，而不是services。与旧版本是有区别的。

**Comment by flingInTheSky** [comment]
具体可以看蓝牙的startDiscoverCharacteristics接口说明

**Comment by flingInTheSky** [comment]
第一点这个问题，你们没有遇到吗？

**Comment by edwardair** [comment]
> 第一点这个问题，你们没有遇到吗？

遇到的，只是忽略它，继续走connect也可以

**Comment by flingInTheSky** [comment]
那你们怎么处理蓝牙断开再重莲的问题？这时候得要判断isConnected的吧。

**Comment by LiuMengzhou** [comment]
Duplicate of #134
