### ISSUE TITLE
webview html中引用外部的资源

### ISSUE THREAD

**Issue by wxy693172809** [MiEcosystem/miot-plugin-sdk#980]
**是否为新品（必填）**
新品

**关联的产品model**
“aiqi.remote.xiaomimaze”

**项目ID（必填）**
无项目ID

**企业名称（必填）**
北京爱其科技有限公司

**环境（必填）**
- 电脑操作系统:Mac OS
- 手机系统:Android 7.0，Android 7.12， iOS 11.0
![IMG_20190612_110449](https://user-images.githubusercontent.com/11309056/59321017-151ab180-8d03-11e9-9506-c9d824d73904.jpg)

- SDK分支: 10010
- 相关模块:WebView

**现象（必填）**
米家中使用webview引用本地html，html中引用外部的js和图片地址不生效，扩展程序在开发环境下运行正常

**期望（必填）**
webview中能正常引用外部文件

**其他的上下文/日志/截图**
![IMG_20190612_110449](https://user-images.githubusercontent.com/11309056/59320904-b9e8bf00-8d02-11e9-80da-c9f4623faeeb.jpg)

**尝试过的解决办法**
将js直接放入html中生效

**不要贴大段代码❗️**
<View style={styles.container}>
                <Text>显示webview</Text>
                <WebView
                  originWhitelist={['*']}
                  javaScriptEnabled={true}
                  style={styles.webview}
                  source={uri}
                  ref={webview => this.webview = webview}
                  onMessage={this.handleMessage}
                />
 </View>

  html：       
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
<body bgcolor="#ABCDEF">
	<p>webview 显示</p>
    <p id = "jstest">js 未生效</p>
    <script src="jstest.js" charset="utf-8"></script>
	<image src = "splash.png">
	</image>
</body>
</html>

js:
(function function_name(argument) {
    let p = document.getElementById("jstest");
    p.innerText = "js 生效";
}());

**Comment by zanetti4** [comment]
html 中引入的图片是本地的吗？

**Comment by blockdate** [comment]
未被require的js文件是不会被bundle打包包含的。

**Comment by wxy693172809** [comment]
> html 中引入的图片是本地的吗？
是本地图片，Resources里面的图片

**Comment by wxy693172809** [comment]
> 未被require的js文件是不会被bundle打包包含的。

那HTML里面引用的js怎样才能打包包含进去

**Comment by blockdate** [comment]
js文件被require之后，会被统一到一个jsbundle中，建议直接内置在html中。

这边是逻辑特别复杂，需要大规模复用js么。

**Comment by zanetti4** [comment]
或者把 html 引入的外部文件放到线上

**Comment by wxy693172809** [comment]
> 或者把 html 引入的外部文件放到线上

是把html引用的文件放到外部链接上吗？米家中能否把这个html链接放到外部链接上？

**Comment by zanetti4** [comment]
是这个意思，可以试试把 html 里引用的 js、图片放到外部链接。

**Comment by zanetti4** [comment]
你的 html 文件中有什么内容？

**Comment by santcool** [comment]
https://liruwei.github.io/2017/08/02/ReactNative-%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6/

1.你们为什么不能使用远程图片呢？2.你们为什么不直接RN来实现页面吗？
 RN加载本地js和图片资源坑都比较多，暂时不计划解决此类问题，建议采用上面两种方式。

**Comment by wxy693172809** [comment]
谢谢，现在是将js逻辑和图片资源直接放到html实现想要的效果。
