### ISSUE TITLE
白名单测试时，从米家首页进入插件有时是旧的原生插件，有时是白名单RN插件

### ISSUE THREAD

**Issue by WeizhiKong** [MiEcosystem/miot-plugin-sdk#981]
**是否为新品（必填）**
在售

**关联的产品model**
小米米家智能门锁 lumi.lock.mcn01

**项目ID（必填）**
21379

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
RN插件提交白名单测试，在米家APP上登录企业账号，进入插件，有时候进去是旧的原生插件，有时候进去是白名单的RN插件。

**期望（必填）**
进入插件是白名单的RN插件

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by blockdate** [comment]
插件上传时间需要超过半小时之后才会稳定，现在还有问题吗。

**Comment by WeizhiKong** [comment]
@blockdate 嗯，现在不会了
