### ISSUE TITLE
固件升级在升级完后提示升级失败，但断电重启设备之后就显示已经成功更新到最新版本

### ISSUE THREAD

**Issue by flingInTheSky** [MiEcosystem/miot-plugin-sdk#984]
---
**是否为新品（必填）**
在售

**关联的产品model**
viomi.hood.c1

**项目ID（必填）**
【无项目ID】

**企业名称（必填）**
云米

**环境（必填）**
- 手机系统:[eg.Android/iOS]
- SDK分支: [eg.master/10010]
- 相关模块:[固件升级]

**现象（必填）**
升级完后提示升级失败但断电重启设备之后就显示已经成功更新到最新版本（wifi模组1.2.8）

**期望（必填）**
正常升级固件

**Comment by Woody2016** [comment]
@flingInTheSky 请问这个问题是出现的那个平台下，android还是iOS？

**Comment by flingInTheSky** [comment]
iOS和Android都一样

**Comment by flingInTheSky** [comment]
@Woody2016

**Comment by pencilCool** [comment]
问题是否还存在？

**Comment by pencilCool** [comment]
据你们的固件说是模组的问题。
请问如果是固件模组的问题，之前有没有和米家的模组开发者确认过。

如果没有和米家的模组开发者确认过，请提供以下信息：
1模组的芯片型号
2测试次数，复现概率
3模组的log

**Comment by flingInTheSky** [comment]
确认过
