### ISSUE TITLE
ScrollView在Android和iOS中API和回调表现不一致，如何处理

### ISSUE THREAD

**Issue by Android-yzhang** [MiEcosystem/miot-plugin-sdk#985]
**是否为新品（必填）**
新品

**关联的产品model**
miaomiaoce.thermo.t10

**项目ID（必填）**
913

**企业名称（必填）**
秒秒测

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 9/iOS 12]
- SDK分支: [eg.master/10020/...]

**现象（必填）**
1.ScrollView中contentOffset是iOS专有API，Android没有这个方法，无法在一开始滑动到末尾；
2.在Android中，在滑动ScrollView中，先停止滑动，在抬起手指，不会调用onScrollEndDrag这个回调函数，导致Android上有些功能异常

**期望（必填）**
能够提供替代的办法

**Comment by zanetti4** [comment]
1.scrollToEnd({animated: false})
这个方法可以试一下

**Comment by zanetti4** [comment]
2.我的手机安卓7.0可以触发 onScrollEndDrag 这个回调函数。你检查一下是否哪里写错了

**Comment by zanetti4** [comment]
2. Android 9也能触发 onScrollEndDrag 这个回调函数

**Comment by Android-yzhang** [comment]
手指直接滑动是可以的，先滑动，然后静止一小会在抬起手指，就不执行onScrollEndDrag

**Comment by lvjie0519** [comment]
@Android-yzhang    把您对ScrollView的需求 ， 目前无法满足的请详细说明一下，谢谢。

**Comment by Android-yzhang** [comment]
2个功能点需要满足，第一个是在绘制完成后，需要ScrollView滑动到末尾，这点现在iOS可以，但是Android无法满足。第二个，举例说，手指滑动到了x=40这个位置，在手指抬起后，要自动的滑动到x=0的位置上，手指滑动到了x=1700这个位置，在手指抬起后，要自动的滑动到x=200的位置上

**Comment by zanetti4** [comment]
scrollToEnd 这个方法你有试过吗？能解决第一个问题吗？

**Comment by lvjie0519** [comment]
1、问题一， 可以如下方式解决
onContentSizeChange={(e)=>{
                        console.log("onContentSizeChange()...")
                        this.refs.myScrollView.scrollToEnd({animated: true, duration: 500});
                    }}
2、问题二， 我这边手机尝试 onScrollEndDrag  是可以执行的，麻烦你那边再确认下。

**Comment by Android-yzhang** [comment]
问题1 ：我是在componentDidUpdate()做的处理，
问题2：我是在onTouchEnd中处理的，我这边Android在手指完全静止之后再抬起，一直不执行onScrollEndDrag回调
