### ISSUE TITLE
IOS录音设置audioFormatMPEG4AAC报错

### ISSUE THREAD

**Issue by zhaowei1357** [MiEcosystem/miot-plugin-sdk#987]
- IPA/APK 是否更新到最新？V4.17.1
- SDK 是否更新到最新？10010
- Check 文档了吗？已检查
- 是否尝试搜索issue？是

是否为新品（必填）
新品 

此issue关联的产品model，如“ydhome.lock.m2silver”

**项目ID（必填）**
955

**企业名称（必填）**
深圳优点科技有限公司

**环境（必填）**
- 电脑操作系统:Windows
- 手机系统:iOS 12.0
- SDK分支: 10010
- 相关模块:Host.audio

**现象（必填）**
ios平台设置AVFormatIDKey: 'audioFormatMPEG4AAC ',直接报错

**期望（必填）**
希望支持audioFormatMPEG4AAC 格式。

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。
![image](https://user-images.githubusercontent.com/29081956/59337894-fb459280-8d33-11e9-9943-22cae48172d6.png)
const AudioSettings = {
  AVFormatIDKey: 'audioFormatMPEG4AAC ',
  // AVFormatIDKey: 'audioFormatLinearPCM',
  AVSampleRateKey: 44100,
  AVNumberOfChannelsKey: 1,
  AVEncoderAudioQualityKey: 'audioQualityMin',
  AVLinearPCMBitDepthKey: 16,
  AVLinearPCMIsBigEndianKey: false,
  AVLinearPCMIsFloatKey: false,
};

**尝试过的解决办法**
android未报错，正常

**不要贴大段代码❗️**
const AudioSettings = {
  AVFormatIDKey: 'audioFormatMPEG4AAC ',
  // AVFormatIDKey: 'audioFormatLinearPCM',
  AVSampleRateKey: 44100,
  AVNumberOfChannelsKey: 1,
  AVEncoderAudioQualityKey: 'audioQualityMin',
  AVLinearPCMBitDepthKey: 16,
  AVLinearPCMIsBigEndianKey: false,
  AVLinearPCMIsFloatKey: false,
};

**Comment by santcool** [comment]
后面明显多加了空格

**Comment by zhaowei1357** [comment]
ok，检查了以下，确实多了个空格，去掉空格后android也可以录音了，三克油

**Comment by zhaowei1357** [comment]
ok，已解决，三克油
