### ISSUE TITLE
android米家版本疑问

### ISSUE THREAD

**Issue by ldezho** [MiEcosystem/miot-plugin-sdk#988]
**是否为新品（必填）**
在售

**关联的产品model**
shjszn.lock.c1

**项目ID（必填）**
项目ID是指小米生态链部立项的项目ID，未在生态链部立项的项目填【无项目ID】

**企业名称（必填）**
上海榉树智能科技有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
- 手机系统:[eg.Android 8.1/iOS 11.0]
- SDK分支: [eg.master/10000/...]
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
米家版本均为正式版本，用户为白名单用户！

安卓手机相同米家版本，插件页表现不一样。。。
首先米家版本相同都是，v5.5.25，但UI表现不一样
其次在插件页内，智能设置锤子手机不能进入下一层，One Plus 6T则可以，

锤子手机：
![WechatIMG669](https://user-images.githubusercontent.com/12531667/59344457-b5db9200-8d40-11e9-8876-200a26fa04f4.jpeg)
![WechatIMG668](https://user-images.githubusercontent.com/12531667/59344468-b8d68280-8d40-11e9-996b-7275c06a2ae4.jpeg)

One Plus 6T:
![WechatIMG671](https://user-images.githubusercontent.com/12531667/59344477-bffd9080-8d40-11e9-96ab-81f3adf3a8df.jpeg)
![WechatIMG670](https://user-images.githubusercontent.com/12531667/59344494-c855cb80-8d40-11e9-93b5-ca80f3ab1477.jpeg)

可以进入下一页的情况（点击任意开锁，可以进入第二张图片）：
不可以进入的手机，则点击后直接返回（如锤子手机不能进入下一层，点击任意开锁后就直接返回了）
![WechatIMG674](https://user-images.githubusercontent.com/12531667/59399074-380d9a00-8dc5-11e9-91b2-415e19ed6215.png)
![WechatIMG675](https://user-images.githubusercontent.com/12531667/59399080-3cd24e00-8dc5-11e9-96fa-7f00780b94b4.png)

**期望（必填）**
相同米家版本，表现一样，且正常

**其他的上下文/日志/截图**
提供更多的上下文，有日志或者截图更好。

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by zanetti4** [comment]
这两款手机的安卓版本各是什么？

**Comment by ldezho** [comment]
One Plus 6T：Android 9
锤子：android 7.1.2

**Comment by lvjie0519** [comment]
@ldezho    线上v5.5.25存在此问题，  fir上下载最新apk  是否存在此问题？

**Comment by ldezho** [comment]
fir上的5.5.25.1和5.5.25.3均不存在这个问题

**Comment by lvjie0519** [comment]
@ldezho  
1、线上版本不太方便排查，请使用fir上  5.5.21.1 (Build 62874) 版本测试下试试？这个和线上版本是相同的；
2、清空缓存还是会出现相同情况吗？

**Comment by ldezho** [comment]
@lvjie0519  5.5.21.1 (Build 62874)这个版本存在这个问题

**Comment by lvjie0519** [comment]
@ldezho   提供下  有问题的手机对应的log日志，或加微信：18750118631，详聊下。

**Comment by ldezho** [comment]
@lvjie0519 log发您微信了

**Comment by lvjie0519** [comment]
Android， 在sdk  为10012之前，project.json文件中配置的id必须是字符串类型，10012之后，做了兼容，整形和字符串都支持。
