### ISSUE TITLE
iOS BluetoothEvent.bluetoothSeviceDiscovered回调优化建议

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#989]
由于iOS端，插件进入时，采用了 `Bluetooth.retrievePeripheralsForIOS` 及 `Bluetooth.retrievePeripheralsWithServicesForIOS` 来恢复已处于连接中的BLE（主要是解决产品第一次添加进入插件时的连接问题），此时插件内会手动创建新的

- BluetoothLE（**B**）= `Bluetooth.createBluetoothLE(deviceID)`

- 插件本身的BluetoothLE（**A**）= `Device.getBluetoothLE()`

发现在  `BluetoothEvent.bluetoothSeviceDiscovered.addListener((blut, services) => {}`回调中，居然是

- **B** != blut

- **A** == blut

---
导致的问题：获取blut.isConnected == undefined，只能另外使用B.isConnected来判断连接情况；
调用主体是 `B.startDiscoverServices`，但回调中返回的却是A，造成bluetooth混乱问题

**Comment by pencilCool** [comment]
之前遇到类似的问题是，别人用service uuid 当成了 device uuid 在使用，请确认是不是这种情况。

**Comment by edwardair** [comment]
不管混不混用，问题点是，B调用的startDiscoverServices，相应的，DiscoverServices回调中，不应该是回调B么，为什么回调的是A？谁调用，返回谁，这个应该是基本逻辑吧？

**Comment by pencilCool** [comment]
你们是哪款什么遇到了这个问题

**Comment by pencilCool** [comment]
你们是哪款设备遇到了这个问题，model 是多少

**Comment by edwardair** [comment]
我们所有设备都是采用这种方案在做，都有问题，这个我们自己通过代码可以解决问题，只是SDK这么设计有点反人道，建议修改
