### ISSUE TITLE
使用Svg自定组件实现问题

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/miot-plugin-sdk#990]
**请自查：（不用回答，创建issue时此段可删除）**
- IPA/APK 是否更新到最新？
是
- SDK 是否更新到最新？
是
- Check 文档了吗？
是
- 是否尝试搜索issue？
是

---
**是否为新品（必填）**
在售

**关联的产品model**
dmaker.fan.p5

**企业名称（必填）**
浙江星月电器有限公司

**环境（必填）**
- 电脑操作系统:[eg.Windows/Mac OS/Linux]
mac
- 手机系统:[eg.Android 8.1/iOS 11.0]
android 9.0
- SDK分支: [eg.master/10000/...]
10012
- 相关模块:[eg.Host/Service/Account]

**现象（必填）**
使用了Svg自定义控件后，进行rotateZ动画，目前发现redmi7 和 荣耀10 显示的控件边缘有很多锯齿。

**期望（必填）**
正常显示，没有锯齿

**其他的上下文/日志/截图**
**注意圆的边角部分**
<img width="146" alt="circleTest" src="https://user-images.githubusercontent.com/11881751/59402940-28954d80-8dd3-11e9-83a3-fda8f3184145.png">

**尝试过的解决办法**

**不要贴大段代码❗️**
``````
<View style={{
                flex: 1,
                backgroundColor: 'red',
            }}>
                <Animated.View style={{
                    width: circleRadius * 2,
                    height: circleRadius * 2,
                    alignItems: "center",
                    justifyContent: 'center',
                    marginLeft: 30,
                    marginTop: 30,
                    transform: [
                        {rotateZ: this.rotateCircleZ},
                        ]
                }}>
                    <SvgCircle
                        svgStyle={{
                            width: circleRadius * 2,
                            height: circleRadius * 2,
                        }}
                        size={circleRadius * 2}
                        strokeWidth={1}
                        stroke='yellow'
                    />
                </Animated.View>
            </View>
``````

**Comment by zanetti4** [comment]
我使用 react-native-svg 提供的组件在安卓手机测试了一下，边缘没有锯齿。所以能否不用自定组件？

**Comment by zanetti4** [comment]
在10021分支上我增加了一个演示文件，你可以看一下。
miot-workspace/projects/com.xiaomi.demo/Main/ThirdPartDemo/AnimatedSVGDemo.js

**Comment by evansherry** [comment]
@zanetti4 请问使用的redmi7、honor10吗？我这边测试了一下demo ,还是有锯齿
![SvgDemo](https://user-images.githubusercontent.com/11881751/59477277-1379f680-8e87-11e9-8560-7218ca2e954d.jpg)

**Comment by zanetti4** [comment]
我是用荣耀9安卓7.0测试的，手机上截图放大也没有锯齿。其他同事下班了，下周一我借个你的机型测一下。

**Comment by evansherry** [comment]
@zanetti4 能否留个微信，这样沟通起来比较方便

**Comment by zanetti4** [comment]
Recife-2014，这是我的微信号，昵称：悦仔。能搜到吗？

**Comment by zanetti4** [comment]
我们测试这边没有你的那两款手机，暂无法测试。

**Comment by evansherry** [comment]
@zanetti4 可以尝试其它全面屏手机，三星S9也出现了周边很多锯齿

**Comment by evansherry** [comment]
@zanetti4 我尝试去掉svg，给View设置一个背景旋转，也会出现这样的问题。代码如下
``````
  <View style={{
                flex: 1,
                backgroundColor: 'red',
            }}>
                <Animated.View
                    style={{
                        width: circleRadius * 2,
                        height: circleRadius * 2,
                        alignItems: "center",
                        justifyContent: 'center',
                        backgroundColor: 'blue',
                        marginLeft: 30,
                        marginTop: 30,
                        transform: [
                            {rotateZ: this.rotateCircleZ},
                        ]
                    }}>
                </Animated.View>
            </View>
``````

**Comment by zanetti4** [comment]
@lvjie0519 安卓边缘出现锯齿的问题，请你协助查看一下

**Comment by zanetti4** [comment]
@evansherry 这边没有三星S9手机

**Comment by evansherry** [comment]
我用Android原生测试了一下锯齿问题，给FramLayout设置一个背景，然后start Rotate动画，发现旋转的时候有锯齿现象。综上出现问题的手机都是全面屏，可否试一下全面屏手机？

**Comment by zanetti4** [comment]
搜到这篇[帖子](https://blog.csdn.net/panda_8/article/details/89839742)，你如果使用图片是否可以？

**Comment by fishle** [comment]
试试这个包，看看没有好一点：
https://pan.mioffice.cn:443/#/link/235346B5E14A4F41577F29FFB08AC348
