### ISSUE TITLE
Android CommonSetting无右箭头

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#991]
master最新SDK（10012）
APK：线上5.5.25

---
**是否为新品（必填）**
在售

**企业名称（必填）**
睿米

**现象（必填）**
CommonSetting缺少右箭头显示（iOS有，并且Android测试环境也有，白名单测试无右箭头）

**期望（必填）**
CommonSetting 右箭头能够显示

**Comment by edwardair** [comment]
#941

**Comment by edwardair** [comment]
最新测试：
A/B两个插件同时对比测试：（两个插件基本同一时间段打包上传，开启白名单测试）
1. 当米家APP清理全部数据后，进入插件A，有箭头
2. 退出，进入B插件，无箭头
3. 退出，再次进入A插件，无箭头
4. 退出，再次进入B插件，无箭头
5. 米家APP清理全部数据，循环步骤2

另外：A/B对调顺序的话，两个插件永远无箭头，那么问题出在B插件，同时B插件会影响A插件的显示

**Comment by edwardair** [comment]
![Android上右箭头不显示](https://user-images.githubusercontent.com/2043635/59419127-d49f5e80-8dfc-11e9-9c09-aaf5771f2537.png)

**Comment by DennisJu007** [comment]
有类似的需求就直接在这里盖楼了方便统一管理，看了demo里面没有下面图片中的这种样式，能不能在原基础上支持一下加个带右边箭头的，然后用一个状态来控制右边箭头显示隐藏，具体需求如下：
![image](https://user-images.githubusercontent.com/42829167/59671330-0d21ac80-91f0-11e9-92b6-5a7154104215.png)

**Comment by LiuMengzhou** [comment]
> 有类似的需求就直接在这里盖楼了方便统一管理，看了demo里面没有下面图片中的这种样式，能不能在原基础上支持一下加个带右边箭头的，然后用一个状态来控制右边箭头显示隐藏，具体需求如下：
> ![image](https://user-images.githubusercontent.com/42829167/59671330-0d21ac80-91f0-11e9-92b6-5a7154104215.png)

你详细描述一下使用场景，目前设计师并没有输出这种组件的设计稿，也没与其他开发者有此诉求。
如果使用场景很通用的话，我们可以考虑排期开发。

**Comment by lvjie0519** [comment]
@edwardair   问题已修复， 用最新apk进行测试。

**Comment by zanetti4** [comment]
@edwardair 如果测试后问题已修复，请关闭此问题。

**Comment by edwardair** [comment]
请问用什么apk测试？
- 线上版：5.5.30，测试问题仍存在
- 开发版：5.5.30.1测试版，没问题了
@lvjie0519 @zanetti4

**Comment by lvjie0519** [comment]
@edwardair   是的， 线上版5.5.30确实存在问题，修复版本已经集测了；5.5.30.1测试版没问题就可以。

**Comment by edwardair** [comment]
好的，等待新版apk上架
