### ISSUE TITLE
新创建的项目打包失败问题

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#993]
master最新 10012
新创建项目，在 `npm run publish  com.xxx.xxx`时会因为JSON解析问题导致打包失败，原因是：

```
{ 
    "package_path": "com.xxx.xxx",
    "min_sdk_api_level":10012,
    "developer_id": "",
    "version_code":1,
    "entrance_scene":{
        "action_ids":[],
        "trigger_ids":[],  <<<<<<<<<<<<<<<<<这里最后一位多了一个逗号，导致打包失败，移除后，打包正常
    }
}
```

**Comment by santcool** [comment]
问题不大，我们有时间改一下

**Comment by zxd620** [comment]
也许这个问题看起来不大，但是我们浪费了一天的时间来排查，基于我们信任你们的框架是严肃认真做出来的，是对开发者负责任的，所以我们从来都是从自己身上找原因，然而，从你的回复中我并没有看出来你的专业性和责任心。
我相信，不止我和楼主两个人遇到这个问题，希望你们即刻修复这个bug。

**Comment by zxd620** [comment]
> 问题不大，我们有时间改一下
也许这个问题看起来不大，但是我们浪费了一天的时间来排查，基于我们信任你们的框架是严肃认真做出来的，是对开发者负责任的，所以我们从来都是从自己身上找原因，然而，从你的回复中我并没有看出来你的专业性和责任心。
我相信，不止我和楼主两个人遇到这个问题，希望你们即刻修复这个bug。
