### ISSUE TITLE
react-navigation版本问题

### ISSUE THREAD

**Issue by TheWalkingDead1024** [MiEcosystem/miot-plugin-sdk#994]
是否为新品（必填）
在售

关联的产品model
yeelink.light.bslamp1
yeelink.light.bslamp2
yellink.light.bslamp3
...

项目ID（必填）
【无项目ID】

企业名称（必填）
Yeelight

环境（必填）

电脑操作系统:[Mac OS]
手机系统:[iOS 12.3及以上]
SDK分支: [master/10012]
相关模块:[react-navigation]
现象（必填）
当前react-navigation版本有点低，能否考虑升级到3.x.x，性能更好，以及对redux支持度等其他方面更好一些

期望（必填）
能升级react-navigation 到3.x.x

2、能同步支持Android和IOS最好
其他的上下文/日志/截图
提供更多的上下文，有日志或者截图更好。

尝试过的解决办法
查看源码

**Comment by zanetti4** [comment]
经过测试，将 react-navigation 升级到3.0.7无法与现有的 react-native 版本兼容……

**Comment by TheWalkingDead1024** [comment]
> 经过测试，将 react-navigation 升级到3.0.7无法与现有的 react-native 版本兼容……

请问未来可有升级react-native和react-navigation的计划呢？
