### ISSUE TITLE
ios设备上发现的服务为空数组,安卓设备中不存在这个问题

### ISSUE THREAD

**Issue by xiaofulon** [MiEcosystem/miot-plugin-sdk#995]
**是否为新品（必填）**
新品

**关联的产品model**
lanzu.watch.lanzoom

**项目ID（必填）**
无项目ID

**企业名称（必填）**
厦门蓝族创意科技有限公司

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[iOS 12.3.1]
- SDK分支: [master/10005]
- 相关模块:[Bluetooth]

**现象（必填）**
蓝牙连接上后,自动回调发现服务的监听,且service为空数组

**期望（必填）**
服务不为空

**其他的上下文/日志/截图**
1.外部调用注册监听
<img width="759" alt="image" src="https://user-images.githubusercontent.com/17547876/59479803-d450a300-8e90-11e9-83e6-9edfe3aad0c8.png">

2.外部调用开始连接
<img width="510" alt="image" src="https://user-images.githubusercontent.com/17547876/59479302-1aa50280-8e8f-11e9-9a44-e02263736a27.png">

3.retrieve手机底层连接的设备
<img width="589" alt="image" src="https://user-images.githubusercontent.com/17547876/59479342-41fbcf80-8e8f-11e9-853f-80dc8ee07bd6.png">

4.retrieve失败,调用连接
<img width="507" alt="image" src="https://user-images.githubusercontent.com/17547876/59479648-5d1b0f00-8e90-11e9-8b46-66107f926904.png">

5.调用发现服务
<img width="440" alt="image" src="https://user-images.githubusercontent.com/17547876/59479661-64dab380-8e90-11e9-8c39-513ca225886e.png">

**尝试过的解决办法**
1.用原生的app测试发现服务正常可以发现'FFF0'和'180A',
2.用lightBluetooth测试,也可以发现服务
3.查找所有的关于发现蓝牙服务的issue,并按其中的去尝试,并没有用;
4.同样的代码,在安卓手机上能正常的发现服务
5.因为这个问题,项目进度已经延迟了2周,希望能够得到大家的帮助,谢谢大家!

**Comment by blockdate** [comment]
提供下lightblue的连接截图。

同时提供下调试过程中的js端日志log
