### ISSUE TITLE
自定义自动化页面，native传过来的参数在 iOS 和 Android 上数据格式不一致。

### ISSUE THREAD

**Issue by MisterrWu** [MiEcosystem/miot-plugin-sdk#996]
**是否为新品（必填）**
  在售

**关联的产品model**
lumi.sensor_ht.v1

**项目ID（必填）**
无项目ID

**企业名称（必填）**
绿米

**环境（必填）**
- 电脑操作系统:[Mac OS]
- 手机系统:[Android 8.1，iOS 12.1.4]
- SDK分支: [10020]
- 相关模块:[Package]

**现象（必填）**
自定义自动化页面，native传过来的参数在 iOS 和 Android 上数据格式不一致,例如value 在iOS上是object 在Android上是string, id 在iOS上是string 在Android上是number。

**期望（必填）**
自定义自动化页面，native传过来的参数在 iOS 和 Android 上数据格式一致。

**其他的上下文/日志/截图**
Android：
接受  {"payload":{"package_msgType":3,"extra":null,"model":"lumi.sensor_ht.v1","value":"{\"min\":-20}","did":"lumi.158d0001dcbbef","id":62,"scene_type":1,"command":"prop.lumi.sensor_ht.v1.temperature","plug_id":"get_condition_value","name":"高于指定温度","tr_id":"110"}}

iOS：
接受  {"payload":{"name":"高于指定温度","device_name":"米家温湿度传感器","default_value":0,"value":{"min":-20},"plug_id":"get_condition_value","src":"device","tr_id":110,"command":"prop.lumi.sensor_ht.v1.temperature","device_abbr":"温湿度传感器","did":"lumi.158d0001dcbbef","scene_type":1,"id":"62"}}

**尝试过的解决办法**
尝试过哪些操作？

**不要贴大段代码❗️**

**Comment by santcool** [comment]
android和ios均已修改，将发布于版本SDK_10021。value根据服务端的返回值了来，若给的String，两边就都为String；若给的是object，两边都为object。 id统一为number。

**Comment by santcool** [comment]
请使用此包验证。https://fir.im/tes5?release_id=5d076579ca87a84d76cc527e

**Comment by lvjie0519** [comment]
@MisterrWu  Android无需修改，只需验证ios是否与Android一致即可。

**Comment by MisterrWu** [comment]
使用上面的包以及分支10021最新代码，iOS上面value 还是object，id 还是string，如下：
接受  {"payload":{"name":"高于指定温度","device_name":"米家温湿度传感器","default_value":0,"value":{"min":-20},"plug_id":"get_condition_value","src":"device","tr_id":110,"command":"prop.lumi.sensor_ht.v1.temperature","device_abbr":"温湿度传感器","did":"lumi.158d0001dcbbef","scene_type":1,"id":"62"}}

**Comment by santcool** [comment]
你怎么log的，我试了下，master上的id都是number？

**Comment by MisterrWu** [comment]
米家beta 2034 以及sdk 10020上，value 和 id 在iOS和Android上面格式一致。
iOS：
{"payload":{"package_msgType":3,"extra":null,"model":"lumi.sensor_ht.v1","value":"{\"min\":-20}","did":"lumi.158d0001dcbbef","id":62,"scene_type":1,"command":"prop.lumi.sensor_ht.v1.temperature","plug_id":"get_condition_value","name":"高于指定温度","tr_id":"110"}}
