### ISSUE TITLE
米家app登录我的小米账号在安卓手机测试版没有开发者模式

### ISSUE THREAD

**Issue by devYoungyang** [MiEcosystem/miot-plugin-sdk#997]
**是否为新品（必填）**
填 新品
**环境（必填）**

- 手机系统:安卓

**现象（必填）**
米家app登录我的小米账号在安卓手机测试版没有开发者模式，在iOS测试版就有开发者模式

**期望（必填）**
米家app安卓测试版有开发者模式

**Comment by devYoungyang** [comment]
是不是我没有加入企业开发组米家app测试版才没有开发者模式

**Comment by zanetti4** [comment]
我的安卓手机用的米家 app 测试版5.5.25.3，开发者设置里有开发模式。你用的什么版本？升级一下试试呢？

**Comment by blockdate** [comment]
加入企业开发组就会有。

建议多重启或者重新登陆几次试试。
