### ISSUE TITLE
购买小爱、电视的有品链接在iOS系统10上无法显示

### ISSUE THREAD

**Issue by madv-rd** [MiEcosystem/miot-plugin-sdk#998]
小爱购买链接  https://app.xiaomiyoupin.com/detail?gid=105569
电视购买链接  https://app.xiaomiyoupin.com/detail?gid=106640
这两个链接不适配iOS系统10，请麻烦适配一下，多谢

是否为新品（必填）
在售

关联的产品model
madv.cateye.dlowl

项目ID（必填）
65594

企业名称（必填）
疯景

环境（必填）

电脑操作系统: Mac OS
手机系统: iOS 10.3.1、10.1.1

现象（必填）
上面两个链接在iOS系统10上用uiwebview加载不出来，这边试了一下在iOS系统10上的safari也加载不出来

期望（必填）
在iOS系统10可以正常加载出来

其他的上下文/日志/截图
![log_1](https://user-images.githubusercontent.com/47879744/59505913-62507c00-8ed9-11e9-9ba5-3a11be219a0b.gif)

**Comment by zanetti4** [comment]
不适配 win10系统？请按照 issue 模版进行提问，谢谢

**Comment by blockdate** [comment]
对于商城部分，建议使用 `Host.ui.canOpenStorePage()` 判断能否使用商城，随后使用`Host.ui.openShopPage(gid)` 打开商品页面

**Comment by santcool** [comment]
已告知有品的同事，这个需要他们的前端的同学去处理下

**Comment by madv-rd** [comment]
这个问题大概什么时候可以解决
