### ISSUE TITLE
应测试要求，咨询Android上如何测试CPU消耗

### ISSUE THREAD

**Issue by edwardair** [MiEcosystem/miot-plugin-sdk#999]
RT：
![需求参数表](https://user-images.githubusercontent.com/2043635/59495030-0da10700-8ec1-11e9-935b-9f930aa8a7a8.png)

按照上述表格，请问如何检测插件部分的CPU/内存消耗

尝试使用android stdio attach app，但是不清楚具体attach哪个进程：
![AS process](https://user-images.githubusercontent.com/2043635/59494907-c61a7b00-8ec0-11e9-93b4-10b5b2b289a0.png)

**Comment by lvjie0519** [comment]
@edwardair   关闭，麻烦说一下解决方案， 谢谢，可以方便其他开发人员参考。

**Comment by edwardair** [comment]
`attach com.xiaomihome:plugin*` (* 以最新产生的数字为准)
但其实检测的消耗率并不清楚是否准确，比如插件刚进入时，内存消耗会瞬时间很大（我们一个插件是260MB，因为RN框架的插件页面大多数都是在index.js中一次性加载导致的），而260MB的最大值，肯定100%超出了米家规范中标明的：`内存最高消耗应小于100MB`

- 新问题：米家的规范，按照新RN框架来说，是否应该更新下了？
